### ISSUE TITLE
bootstrap: "all: merge dev.cc (a91c2e0) into master" breaks the build on openbsd 5.5

### ISSUE THREAD

**Issue by mikioh** [golang/go#10008]
For bootstrapping, changing go1.4.2 to go1.4.1 doesn't affect the result. Not sure the reason why openbsd 5.6 builders work well.
```
cmd/internal/gc
# cmd/internal/gc
fatal error: runtime: out of memory

runtime stack:
runtime.SysMap(0xc225900000, 0x100000, 0x6e100, 0x80c838)
        /home/mikioh/go/src/runtime/mem_openbsd.c:87 +0x98
runtime.MHeap_SysAlloc(0x811f20, 0x100000, 0x443052)
        /home/mikioh/go/src/runtime/malloc.c:284 +0x124
runtime.MHeap_Alloc(0x811f20, 0x1, 0x10000000019, 0x426149)
        /home/mikioh/go/src/runtime/mheap.c:240 +0x66
runtime.MCentral_CacheSpan(0x81a478, 0x200b6cca8)
        /home/mikioh/go/src/runtime/mcentral.c:85 +0x167
runtime.MCache_Refill(0x20b90c000, 0x200000019, 0x200b6cca8)
        /home/mikioh/go/src/runtime/mcache.c:90 +0xa0

goroutine 1 [running]:
runtime.switchtoM()
        /home/mikioh/go/src/runtime/asm_amd64.s:198 fp=0xc215f37550 sp=0xc215f37548
runtime.mallocgc(0x200, 0x6a8fa0, 0x3b000000000, 0x77)
        /home/mikioh/go/src/runtime/malloc.go:178 +0x849 fp=0xc215f37600 sp=0xc215f37550
runtime.newobject(0x6a8fa0, 0xc210b38560)
        /home/mikioh/go/src/runtime/malloc.go:353 +0x49 fp=0xc215f37628 sp=0xc215f37600
bootstrap/internal/gc.gen_as_init(0xc2258b2a00, 0xc2000087ca)
        /home/mikioh/go/pkg/bootstrap/src/bootstrap/internal/gc/sinit.go:1424 +0x41 fp=0xc215f37868 sp=0xc215f37628
bootstrap/internal/gc.gen(0xc2258b2a00)
        /home/mikioh/go/pkg/bootstrap/src/bootstrap/internal/gc/gen.go:833 +0x152 fp=0xc215f37980 sp=0xc215f37868
bootstrap/internal/gc.Genlist(0xc2258a49c0)
        /home/mikioh/go/pkg/bootstrap/src/bootstrap/internal/gc/gen.go:227 +0x37 fp=0xc215f37990 sp=0xc215f37980
main.cgen_ret(0xc20c5a8800)
        /home/mikioh/go/pkg/bootstrap/src/bootstrap/6g/ggen.go:427 +0x33 fp=0xc215f379c0 sp=0xc215f37990
bootstrap/internal/gc.gen(0xc20c5a8800)
        /home/mikioh/go/pkg/bootstrap/src/bootstrap/internal/gc/gen.go:855 +0xfe7 fp=0xc215f37ad8 sp=0xc215f379c0
bootstrap/internal/gc.Genlist(0xc2258a43c0)
        /home/mikioh/go/pkg/bootstrap/src/bootstrap/internal/gc/gen.go:227 +0x37 fp=0xc215f37ae8 sp=0xc215f37ad8
bootstrap/internal/gc.compile(0xc20c5a4400)
        /home/mikioh/go/pkg/bootstrap/src/bootstrap/internal/gc/pgen.go:500 +0x986 fp=0xc215f37c08 sp=0xc215f37ae8
bootstrap/internal/gc.funccompile(0xc20c5a4400)
        /home/mikioh/go/pkg/bootstrap/src/bootstrap/internal/gc/dcl.go:1470 +0x267 fp=0xc215f37ca0 sp=0xc215f37c08
bootstrap/internal/gc.Main()
        /home/mikioh/go/pkg/bootstrap/src/bootstrap/internal/gc/lex.go:459 +0x24df fp=0xc215f37f70 sp=0xc215f37ca0
main.main()
        /home/mikioh/go/pkg/bootstrap/src/bootstrap/6g/galign.go:110 +0x56a fp=0xc215f37f98 sp=0xc215f37f70
runtime.main()
        /home/mikioh/go/src/runtime/proc.go:63 +0xf3 fp=0xc215f37fe0 sp=0xc215f37f98
runtime.goexit()
        /home/mikioh/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc215f37fe8 sp=0xc215f37fe0
```

**Comment by minux** [comment]
how much memory do you have? The pure Go compilers might be using
significantly more memory than the C version.

**Comment by mikioh** [comment]
Good catch. Looks like 6g on tip uses around 800Meg. I adjusted /etc/login.conf (:datasize-max=infinity, previous value=512M) and got succeeded.
