### ISSUE TITLE
build: too many open files in buildlet

### ISSUE THREAD

**Issue by bradfitz** [golang/go#10062]
Just observed this new failure when starting a Windows buildlet:

```
  builder: windows-amd64-gce
      rev: 0cdf1d2bc265b6ed8e1b9834ec9f6c59dcecdcfd
  vm name: buildlet-windows-amd64-gce-0cdf1d2b-rnbb9a0b
  started: 2015-03-03 00:49:42.356721167 +0000 UTC
  started: 2015-03-03 00:50:52.996985212 +0000 UTC
  success: false

Events:
         2015-03-03T00:49:43Z instance_create_requested
  +23.2s 2015-03-03T00:50:06Z instance_created
   +0.1s 2015-03-03T00:50:06Z waiting_for_buildlet
  +39.0s 2015-03-03T00:50:45Z buildlet_up
   +0.0s 2015-03-03T00:50:45Z start_write_version_tar
   +0.0s 2015-03-03T00:50:45Z start_fetch_gerrit_tgz
   +0.1s 2015-03-03T00:50:45Z start_write_go_tar
   +0.0s 2015-03-03T00:50:45Z start_write_go14_tar
   +7.2s 2015-03-03T00:50:52Z end_write_go_tar

Build log:


Error: Post http://10.240.20.29/writetgz?dir=go1.4: dial tcp 10.240.20.29:80: too many open files
```

Does the buildlet have an fd leak?

/cc @adg

**Comment by bradfitz** [comment]
Related?

Lots of old goroutines:

```
goroutine 11564 [select, 4076 minutes]:
net/http.(*persistConn).writeLoop(0xc20892c370)
	/home/bradfitz/go/src/net/http/transport.go:945 +0x419
created by net/http.(*Transport).dialConn
	/home/bradfitz/go/src/net/http/transport.go:661 +0xbc7

goroutine 312279 [select, 2900 minutes]:
net/http.(*persistConn).writeLoop(0xc209188e70)
	/home/bradfitz/go/src/net/http/transport.go:945 +0x419
created by net/http.(*Transport).dialConn
	/home/bradfitz/go/src/net/http/transport.go:661 +0xbc7

goroutine 9444 [select, 4093 minutes]:
net/http.(*persistConn).writeLoop(0xc2080f8b00)
	/home/bradfitz/go/src/net/http/transport.go:945 +0x419
created by net/http.(*Transport).dialConn
	/home/bradfitz/go/src/net/http/transport.go:661 +0xbc7

goroutine 5692 [select, 4243 minutes]:
net/http.(*persistConn).writeLoop(0xc2082e9c30)
	/home/bradfitz/go/src/net/http/transport.go:945 +0x419
created by net/http.(*Transport).dialConn
	/home/bradfitz/go/src/net/http/transport.go:661 +0xbc7

goroutine 5893 [select, 4243 minutes]:
net/http.(*persistConn).writeLoop(0xc208638370)
	/home/bradfitz/go/src/net/http/transport.go:945 +0x419
created by net/http.(*Transport).dialConn
	/home/bradfitz/go/src/net/http/transport.go:661 +0xbc7

goroutine 27925 [select, 3191 minutes]:
net/http.(*persistConn).writeLoop(0xc2080f8dc0)
	/home/bradfitz/go/src/net/http/transport.go:945 +0x419
created by net/http.(*Transport).dialConn
	/home/bradfitz/go/src/net/http/transport.go:661 +0xbc7

goroutine 8844 [select, 4101 minutes]:
net/http.(*persistConn).writeLoop(0xc208639c30)
	/home/bradfitz/go/src/net/http/transport.go:945 +0x419
created by net/http.(*Transport).dialConn
	/home/bradfitz/go/src/net/http/transport.go:661 +0xbc7
```

Those shouldn't be idle that long.

**Comment by bradfitz** [comment]
Seems like we're not hanging up on buildlets, despite our attempts to do so:

```
bradfitz@farmer ~ $ sudo lsof -p 21941 | wc -l
1036
bradfitz@farmer ~ $ sudo lsof -p 21941 | grep :http | wc -l
1020
bradfitz@farmer ~ $ sudo lsof -p 21941 | grep :http | head -20
coordinat 21941 root    0u  IPv4           14190756      0t0      TCP farmer.c.symbolic-datum-552.internal:39594->buildlet-linux-amd64-noopt-f46e51a2-rn1481b9.c.symbolic-datum-552.internal:http (ESTABLISHED)
coordinat 21941 root    3u  IPv4           12478678      0t0      TCP farmer.c.symbolic-datum-552.internal:47781->metadata:http (CLOSE_WAIT)
coordinat 21941 root    5u  IPv4           13191064      0t0      TCP farmer.c.symbolic-datum-552.internal:57465->10.240.171.124:http (ESTABLISHED)
coordinat 21941 root    7u  IPv4           12512332      0t0      TCP farmer.c.symbolic-datum-552.internal:40707->10.240.12.235:http (ESTABLISHED)
coordinat 21941 root    8u  IPv4           12512361      0t0      TCP farmer.c.symbolic-datum-552.internal:60858->10.240.151.187:http (ESTABLISHED)
coordinat 21941 root    9u  IPv4           12528746      0t0      TCP farmer.c.symbolic-datum-552.internal:46661->10.240.13.250:http (ESTABLISHED)
coordinat 21941 root   10u  IPv4           12511336      0t0      TCP farmer.c.symbolic-datum-552.internal:40626->10.240.13.29:http (ESTABLISHED)
coordinat 21941 root   11u  IPv4           12490768      0t0      TCP farmer.c.symbolic-datum-552.internal:36800->10.240.50.144:http (ESTABLISHED)
coordinat 21941 root   12u  IPv4           12511339      0t0      TCP farmer.c.symbolic-datum-552.internal:43263->10.240.157.244:http (ESTABLISHED)
coordinat 21941 root   13u  IPv6           12478684      0t0      TCP *:http (LISTEN)
coordinat 21941 root   14u  IPv4           13239897      0t0      TCP farmer.c.symbolic-datum-552.internal:39391->10.240.248.154:http (ESTABLISHED)
coordinat 21941 root   15u  IPv4           12514508      0t0      TCP farmer.c.symbolic-datum-552.internal:33668->10.240.131.223:http (ESTABLISHED)
coordinat 21941 root   16u  IPv4           12480260      0t0      TCP farmer.c.symbolic-datum-552.internal:46574->10.240.90.39:http (ESTABLISHED)
coordinat 21941 root   17u  IPv4           13191258      0t0      TCP farmer.c.symbolic-datum-552.internal:50680->10.240.78.214:http (ESTABLISHED)
coordinat 21941 root   18u  IPv4           12491823      0t0      TCP farmer.c.symbolic-datum-552.internal:44942->10.240.123.20:http (ESTABLISHED)
coordinat 21941 root   19u  IPv4           12513926      0t0      TCP farmer.c.symbolic-datum-552.internal:39284->10.240.105.160:http (ESTABLISHED)
coordinat 21941 root   20u  IPv4           12480353      0t0      TCP farmer.c.symbolic-datum-552.internal:57665->10.240.53.176:http (ESTABLISHED)
coordinat 21941 root   21u  IPv4           13212578      0t0      TCP farmer.c.symbolic-datum-552.internal:53618->10.240.167.53:http (ESTABLISHED)
coordinat 21941 root   22u  IPv4           12510734      0t0      TCP farmer.c.symbolic-datum-552.internal:43997->10.240.4.153:http (ESTABLISHED)
coordinat 21941 root   23u  IPv4           12491886      0t0      TCP farmer.c.symbolic-datum-552.internal:42433->10.240.24.59:http (ESTABLISHED)
```

**Comment by adg** [comment]
Do we hang up? In the coordinators `buildInVM` function we create a `buildlet.Client` with `buildlet.StartNewVM` but then we never tear it down. Won't the `buildlet.Client`'s internal `*http.Client` maintain a connection pool?
