### ISSUE TITLE
runtime: SIGBUS during gcmarkwb_m on freebsd/386 during runtime/pprof test

### ISSUE THREAD

**Issue by minux** [golang/go#10161]
Encountered this failure during trybot run of CL 7284 (unrelated to freebsd or runtime).
Note: it's SIGBUS, not SIGSEGV.

https://storage.googleapis.com/go-build-log/4f5ec22b/freebsd-386-gce101_74e4c6fd.log

```
fatal error: unexpected signal during runtime execution
[signal 0xa code=0xc addr=0x28318000 pc=0x805493e]

runtime stack:
runtime.throw(0x82317e8, 0x2a)
	/tmp/buildlet-scatch297012884/go/src/runtime/panic.go:543 +0x81
runtime.sigpanic()
	/tmp/buildlet-scatch297012884/go/src/runtime/sigpanic_unix.go:12 +0x55
runtime.gcmarkwb_m(0x383f6320, 0x583d94b0)
	/tmp/buildlet-scatch297012884/go/src/runtime/mbarrier.go:71 +0xae
runtime.writebarrierptr_nostore1.func1()
	/tmp/buildlet-scatch297012884/go/src/runtime/mbarrier.go:93 +0x2e
runtime.systemstack(0x38401f50)
	/tmp/buildlet-scatch297012884/go/src/runtime/asm_386.s:283 +0x77
runtime.writebarrierptr_nostore1(0x383f6320, 0x583d94b0)
	/tmp/buildlet-scatch297012884/go/src/runtime/mbarrier.go:94 +0x44
runtime.writebarrierptr(0x383f6320, 0x583d94b0)
	/tmp/buildlet-scatch297012884/go/src/runtime/mbarrier.go:117 +0x77
runtime.acquirep(0x3844e000)
	/tmp/buildlet-scatch297012884/go/src/runtime/proc1.go:2582 +0x85
runtime.stoplockedm()
	/tmp/buildlet-scatch297012884/go/src/runtime/proc1.go:1137 +0x129
runtime.schedule()
	/tmp/buildlet-scatch297012884/go/src/runtime/proc1.go:1406 +0x62
runtime.goschedImpl(0x383d90e0)
	/tmp/buildlet-scatch297012884/go/src/runtime/proc1.go:1519 +0xf6
runtime.gosched_m(0x383d90e0)
	/tmp/buildlet-scatch297012884/go/src/runtime/proc1.go:1527 +0x33
runtime.mcall(0x383f62ac)
	/tmp/buildlet-scatch297012884/go/src/runtime/asm_386.s:210 +0x43

goroutine 61 [runnable, locked to thread]:
runtime.Gosched()
	/tmp/buildlet-scatch297012884/go/src/runtime/proc.go:135 +0x10 fp=0x3e9e17d4 sp=0x3e9e17cc
runtime/pprof_test.TestTraceStress.func4(0x3e9d2740)
	/tmp/buildlet-scatch297012884/go/src/runtime/pprof/trace_test.go:136 +0x4a fp=0x3e9e17e8 sp=0x3e9e17d4
runtime.goexit()
	/tmp/buildlet-scatch297012884/go/src/runtime/asm_386.s:2423 +0x1 fp=0x3e9e17ec sp=0x3e9e17e8
created by runtime/pprof_test.TestTraceStress
	/tmp/buildlet-scatch297012884/go/src/runtime/pprof/trace_test.go:139 +0x376

goroutine 1 [chan receive]:
testing.RunTests(0x8252d68, 0x82e8140, 0xd, 0xd, 0x1)
	/tmp/buildlet-scatch297012884/go/src/testing/testing.go:557 +0x874
testing.(*M).Run(0x384140c0, 0x82fea60)
	/tmp/buildlet-scatch297012884/go/src/testing/testing.go:486 +0x65
main.main()
	runtime/pprof/_test/_testmain.go:80 +0x171

goroutine 57 [runnable]:
runtime/pprof_test.TestTraceStress(0x3843bbc0)
	/tmp/buildlet-scatch297012884/go/src/runtime/pprof/trace_test.go:144 +0x3b4
testing.tRunner(0x3843bbc0, 0x82e81c4)
	/tmp/buildlet-scatch297012884/go/src/testing/testing.go:448 +0x9a
created by testing.RunTests
	/tmp/buildlet-scatch297012884/go/src/testing/testing.go:556 +0x842

goroutine 58 [chan receive]:
runtime/pprof_test.TestTraceStress.func1(0x3e9d2740, 0x3e8d5860)
	/tmp/buildlet-scatch297012884/go/src/runtime/pprof/trace_test.go:99 +0x32
created by runtime/pprof_test.TestTraceStress
	/tmp/buildlet-scatch297012884/go/src/runtime/pprof/trace_test.go:101 +0x9c

goroutine 40 [select (no cases)]:
runtime/pprof_test.TestTraceSymbolize.func1()
	/tmp/buildlet-scatch297012884/go/src/runtime/pprof/trace_stack_test.go:38 +0x18
created by runtime/pprof_test.TestTraceSymbolize
	/tmp/buildlet-scatch297012884/go/src/runtime/pprof/trace_stack_test.go:39 +0x17c

goroutine 41 [chan send (nil chan)]:
runtime/pprof_test.TestTraceSymbolize.func2()
	/tmp/buildlet-scatch297012884/go/src/runtime/pprof/trace_stack_test.go:42 +0x38
created by runtime/pprof_test.TestTraceSymbolize
	/tmp/buildlet-scatch297012884/go/src/runtime/pprof/trace_stack_test.go:43 +0x190

goroutine 42 [chan receive (nil chan)]:
runtime/pprof_test.TestTraceSymbolize.func3()
	/tmp/buildlet-scatch297012884/go/src/runtime/pprof/trace_stack_test.go:46 +0x30
created by runtime/pprof_test.TestTraceSymbolize
	/tmp/buildlet-scatch297012884/go/src/runtime/pprof/trace_stack_test.go:47 +0x1a4

goroutine 60 [trace reader (blocked)]:
runtime.ReadTrace(0x0, 0x0, 0x0)
	/tmp/buildlet-scatch297012884/go/src/runtime/trace.go:305 +0x1de
runtime/pprof.StartTrace.func1(0x583f7298, 0x3843bc20)
	/tmp/buildlet-scatch297012884/go/src/runtime/pprof/pprof.go:629 +0x1b
created by runtime/pprof.StartTrace
	/tmp/buildlet-scatch297012884/go/src/runtime/pprof/pprof.go:635 +0x69

goroutine 59 [syscall]:
syscall.Syscall(0x5, 0x3e9e27cf, 0x1, 0x1, 0x0, 0x586e2218, 0x5a1)
	/tmp/buildlet-scatch297012884/go/src/syscall/asm_freebsd_386.s:20 +0x5
syscall.read(0x5, 0x3e9e27cf, 0x1, 0x1, 0xbb47b44b, 0x0, 0x0)
	/tmp/buildlet-scatch297012884/go/src/syscall/zsyscall_freebsd_386.go:890 +0x50
syscall.Read(0x5, 0x3e9e27cf, 0x1, 0x1, 0x586e2000, 0x0, 0x0)
	/tmp/buildlet-scatch297012884/go/src/syscall/syscall_unix.go:136 +0x46
os.(*File).read(0x383f44e8, 0x3e9e27cf, 0x1, 0x1, 0x1, 0x0, 0x0)
	/tmp/buildlet-scatch297012884/go/src/os/file_unix.go:203 +0x6c
os.(*File).Read(0x383f44e8, 0x3e9e27cf, 0x1, 0x1, 0xfde8, 0x0, 0x0)
	/tmp/buildlet-scatch297012884/go/src/os/file.go:95 +0x6c
runtime/pprof_test.TestTraceStress.func3(0x383f44e8, 0x3e9d2740, 0x3e8d5860)
	/tmp/buildlet-scatch297012884/go/src/runtime/pprof/trace_test.go:115 +0x54
created by runtime/pprof_test.TestTraceStress
	/tmp/buildlet-scatch297012884/go/src/runtime/pprof/trace_test.go:118 +0x1fd
FAIL	runtime/pprof	6.714s
```

/cc @RLH

**Comment by mikioh** [comment]
Merged into #9953.
