### ISSUE TITLE
build: update linux-x86-nacl builder to at least pepper-39

### ISSUE THREAD

**Issue by minux** [golang/go#10225]
CL 1755 needs at least pepper-39 to build.

**Comment by bradfitz** [comment]
I made a test VM image from rev 4 of https://go-review.googlesource.com/#/c/7970/4 and a locally-modified gomote (well, locally modified dashboard/builders.go using my temporary testing VM image name) but it fails when running go/src/nacltest.bash with:

```
##### Testing packages. 
ok      archive/tar     0.928s
ok      archive/zip     1.725s
ok      bufio   0.175s
ok      bytes   0.181s
ok      compress/bzip2  0.130s
ok      compress/flate  1.657s
ok      compress/gzip   0.834s
ok      compress/lzw    0.929s
ok      compress/zlib   2.367s
ok      container/heap  0.055s
ok      container/list  0.055s
ok      container/ring  0.062s
?       crypto  [no test files]
ok      crypto/aes      0.090s
--- FAIL: ExampleNewCTR (0.00s)
panic: open /dev/urandom: No such file or directory [recovered]
        panic: open /dev/urandom: No such file or directory

goroutine 1 [running]:
testing.runExample.func2(0xcca3f8f9, 0xe, 0xa49ff20, 0x778c00, 0x1091c260, 0x1091c0f0, 0x1185b300, 0x222df8, 0xd, 0x264dcc, ...)
        /tmp/buildlet-scatch379298522/go/src/testing/example.go:93 +0x420
crypto/cipher_test.ExampleNewCTR()
        /tmp/buildlet-scatch379298522/go/src/crypto/cipher/example_test.go:155 +0x2a0
testing.runExample(0x222df8, 0xd, 0x264dcc, 0x226598, 0xf, 0x0, 0x0, 0x1)
        /tmp/buildlet-scatch379298522/go/src/testing/example.go:98 +0x420
testing.RunExamples(0x264e20, 0x7738c0, 0x4, 0x4, 0x1f0401, 0x1)
        /tmp/buildlet-scatch379298522/go/src/testing/example.go:36 +0x360
testing.(*M).Run(0x1093a120, 0x7738c0, 0x4, 0x4)
        /tmp/buildlet-scatch379298522/go/src/testing/testing.go:491 +0x140
main.main()
        /tmp/go-build394476987/crypto/cipher/_test/_testmain.go:96 +0x200
FAIL    crypto/cipher   0.851s
ok      crypto/des      0.066s
--- FAIL: TestSignAndVerify (0.88s)
        dsa_test.go:17: 0: error signing: open /dev/urandom: No such file or directory
FAIL    
FAIL    crypto/dsa      0.983s
--- FAIL: TestKeyGeneration (0.76s)
        ecdsa_test.go:27: p224: error: open /dev/urandom: No such file or directory
--- FAIL: TestSignAndVerify (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0xffffffff addr=0x0 pc=0xb79c4]
        
goroutine 8 [running]:
testing.tRunner.func1(0x1147a000, 0x10a1bd7c)
        /tmp/buildlet-scatch379298522/go/src/testing/testing.go:446 +0x1e0
crypto/ecdsa.Sign(0xfeec42f0, 0x10a0a700, 0x0, 0x114bc130, 0x7, 0x8, 0x0, 0x0, 0x0, 0x0)
        /tmp/buildlet-scatch379298522/go/src/crypto/ecdsa/ecdsa.go:138 +0x944
crypto/ecdsa.testSignAndVerify(0x1147a000, 0xfeec4390, 0x10a5e070, 0x24e488, 0x4, 0x5a5c)
        /tmp/buildlet-scatch379298522/go/src/crypto/ecdsa/ecdsa_test.go:49 +0x100
crypto/ecdsa.TestSignAndVerify(0x1147a000, 0x0)
        /tmp/buildlet-scatch379298522/go/src/crypto/ecdsa/ecdsa_test.go:66 +0x80
testing.tRunner(0x1147a000, 0x7b424c)
        /tmp/buildlet-scatch379298522/go/src/testing/testing.go:452 +0x120
created by testing.RunTests
        /tmp/buildlet-scatch379298522/go/src/testing/testing.go:560 +0xb20
…
goroutine 1 [chan receive]:
testing.RunTests(0x28c7e0, 0x7a1f80, 0x16, 0x16, 0xfeec0000, 0x10a1c048)
        /tmp/buildlet-scatch379298522/go/src/testing/testing.go:561 +0xb60
testing.(*M).Run(0x10a3a1e0, 0x7bbf60, 0x0, 0x0)
        /tmp/buildlet-scatch379298522/go/src/testing/testing.go:490 +0x100
main.main()
        /tmp/go-build394476987/crypto/rsa/_test/_testmain.go:100 +0x200
FAIL    crypto/rsa      1.119s
ok      crypto/sha1     0.855s
ok      crypto/sha256   0.056s
ok      crypto/sha512   0.069s
ok      crypto/subtle   0.060s
--- FAIL: TestClientResumption (0.00s)
        handshake_client_test.go:399: Handshake: handshake failed: remote error: internal error
--- FAIL: TestVersion (0.00s)
        handshake_server_test.go:278: handshake failed: remote error: internal error
--- FAIL: TestCipherSuitePreference (0.00s)
        handshake_server_test.go:297: handshake failed: remote error: internal error
--- FAIL: TestFallbackSCSV (0.00s)
        handshake_server_test.go:478: TLSv11-FallbackSCSV #2: mismatch on read: got:15030200020250 want:15030200020256
        handshake_server_test.go:441: Error from Server.Write: open /dev/urandom: No such file or directory
        handshake_server_test.go:447: Error expected containing 'inappropriate protocol fallback' but got 'open /dev/urandom: No such file or directory'
FAIL
FAIL    crypto/tls      9.590s
--- FAIL: TestEncrypt (0.77s)
        pem_decrypt_test.go:42: test 0. 1
        pem_decrypt_test.go:50: encrypt:  x509: cannot generate IV: open /dev/urandom: No such file or directory
        pem_decrypt_test.go:42: test 1. 2
        pem_decrypt_test.go:50: encrypt:  x509: cannot generate IV: open /dev/urandom: No such file or directory
        pem_decrypt_test.go:42: test 2. 3
        pem_decrypt_test.go:50: encrypt:  x509: cannot generate IV: open /dev/urandom: No such file or directory
        pem_decrypt_test.go:42: test 3. 4
        pem_decrypt_test.go:50: encrypt:  x509: cannot generate IV: open /dev/urandom: No such file or directory
        pem_decrypt_test.go:42: test 4. 5
        pem_decrypt_test.go:50: encrypt:  x509: cannot generate IV: open /dev/urandom: No such file or directory
        pem_decrypt_test.go:42: test 5. 3
        pem_decrypt_test.go:50: encrypt:  x509: cannot generate IV: open /dev/urandom: No such file or directory
--- FAIL: TestCreateSelfSignedCertificate (0.00s)
        x509_test.go:317: Failed to generate ECDSA key: open /dev/urandom: No such file or directory
--- FAIL: TestUnknownCriticalExtension (0.00s)
        x509_test.go:495: Failed to generate ECDSA key: open /dev/urandom: No such file or directory
--- FAIL: TestCRLCreation (0.00s)
        x509_test.go:759: error creating CRL: open /dev/urandom: No such file or directory
        x509_test.go:764: error reparsing CRL: asn1: syntax error: sequence truncated
--- FAIL: TestCreateCertificateRequest (0.00s)
        x509_test.go:858: Failed to generate ECDSA key: open /dev/urandom: No such file or directory
--- FAIL: TestCertificateRequestOverrides (0.00s)
        x509_test.go:929: open /dev/urandom: No such file or directory
--- FAIL: TestMaxPathLen (0.00s)
        x509_test.go:1069: failed to create certificate: open /dev/urandom: No such file or directory
FAIL
FAIL    crypto/x509     1.981s
?       crypto/x509/pkix        [no test files]
ok      database/sql    0.112s
ok      database/sql/driver     0.052s
ok      debug/dwarf     0.862s
ok      debug/elf       0.863s
…
ok      net/mail        0.842s
ok      net/rpc 0.893s  
ok      net/rpc/jsonrpc 0.098s
--- FAIL: TestTLSClient (0.77s)
        smtp_test.go:567: failed to handle connection: remote error: internal error
--- FAIL: TestTLSConnState (0.00s)
        smtp_test.go:602: StartTLS: tls: short read from Rand: open /dev/urandom: No such file or directory
        smtp_test.go:588: server error: remote error: internal error
FAIL    
FAIL    net/smtp        0.844s
ok      net/textproto   0.053s
ok      net/url 0.080s
ok      os      0.826s
ok      os/exec 0.875s
ok      os/signal       0.048s
ok      os/user 0.050s
ok      path    0.058s
ok      path/filepath   0.858s
ok      reflect 0.203s
ok      regexp  1.054s
…
```

**Comment by minux** [comment]
Sorry, I wasn't clear about the background information in this issue.

The upstream NaCl had a breaking change and removed the support
for SecureRandom SRPC service that our binaries rely on, and instead
introduced a new getrandom syscall.

Even though the syscall is introduced first and the SRPC interface
removed after than, I couldn't find a released version of the NaCl SDK
that contains both interfaces. Thus this update to pepper-39 will break
the build, and CL 1755 is supposed to fix that. (This is the reason I
can't submit that CL without updating the builder, the build will also
break.)

I can build a sel_ldr that supports both interfaces though. If you prefer
not to break builds.

**Comment by bradfitz** [comment]
Oh, then let me test it with gomote and your CL patched in.

**Comment by bradfitz** [comment]
Done.
