### ISSUE TITLE
cmd/link: external linking fails with -s on darwin

### ISSUE THREAD

**Issue by chai2010** [golang/go#10254]
```
go version
go version devel +2420926 Wed Mar 25 02:55:56 2015 +0000 windows/amd64

go get -ldflags "-s" github.com/chai2010/protoc
# github.com/chai2010/protoc
panic: runtime error: index out of range

goroutine 1 [running]:
cmd/internal/ld.addpesymtable()
        C:/go/gotip/src/cmd/internal/ld/pe.go:1024 +0x46c
cmd/internal/ld.Asmbpe()
        C:/go/gotip/src/cmd/internal/ld/pe.go:1145 +0x167
main.asmb()
        C:/go/gotip/src/cmd/6l/asm.go:840 +0xde2
cmd/internal/ld.Ldmain()
        C:/go/gotip/src/cmd/internal/ld/pobj.go:207 +0x19a9
main.main()
        C:/go/gotip/src/cmd/6l/obj.go:44 +0x27
```

**Comment by chai2010** [comment]
```
go version
go version go1.4.2 darwin/amd64

go build -ldflags "-s"
# github.com/chai2010/protoc
ld: warning: option -s is obsolete and being ignored
ld: internal error: atom not found in symbolIndex(__ZN6google8protobuf10TextFormat6Parser10ParserImpl11ReportErrorEiiRKNSt3__112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEE) for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
/usr/local/go/pkg/tool/darwin_amd64/6l: running clang++ failed: unsuccessful exit status 0x100
```

**Comment by alexbrainman** [comment]
Even our misc/ccgo/test fails:

```
C:\>cd %GOROOT%\misc\cgo\test

C:\go\root\misc\cgo\test>go test -ldflags "-s"
# testmain
panic: runtime error: index out of range

goroutine 1 [running]:
cmd/internal/ld.addpesymtable()
        C:/go/root/src/cmd/internal/ld/pe.go:1024 +0x38a
cmd/internal/ld.Asmbpe()
        C:/go/root/src/cmd/internal/ld/pe.go:1145 +0x154
main.asmb()
        C:/go/root/src/cmd/8l/asm.go:728 +0xbec
cmd/internal/ld.Ldmain()
        C:/go/root/src/cmd/internal/ld/pobj.go:207 +0x14e0
main.main()
        C:/go/root/src/cmd/8l/obj.go:44 +0x23
FAIL    _/C_/go/root/misc/cgo/test [build failed]
```

Alex

**Comment by minux** [comment]
The problem is that when -s is set, cmd/internal/ld will not generate the
COFF
symbol table, however, the symbol table is essential for external linking.

For now, please don't pass -ldflags -s if you're external linking, instead,
use
-ldflags "-extldflags -s".

**Comment by alexbrainman** [comment]
It is Go linker crashing. It is bug that needs to be fixed.

I don't have computer to confirm, but I suspect it is crashing because we ncoffsym++ in initdynimport. Why do we ncoffsym++ if we don't store symbols into coffsym. ncoffsym will get reset to 0 later on anyway in addpesymtable. I think our logic is flawed.

Alex

**Comment by rsc** [comment]
It sounds like if -s is given but we find ourselves in external linking mode, then we need to remember the -s for invoking the external linker and not treat cmd/link as having the -s anymore.
