### ISSUE TITLE
runtime: ppc64 schedule holding locks

### ISSUE THREAD

**Issue by bradfitz** [golang/go#10298]
ppc64 (but not ppc64le) is currently failing with:

rev f8fd5502ecdb (and earlier):
http://build.golang.org/log/42997938d48662f9bc36c3affd57290aee5056d6
```
##### Building compilers and go_bootstrap for host, linux/ppc64.
runtime
errors
sync/atomic
sync
io
unicode
unicode/utf8
unicode/utf16
bytes
math
strings
strconv
bufio
sort
container/heap
encoding/base64
syscall
time
internal/syscall/windows
os
reflect
fmt
encoding
encoding/binary
encoding/json
flag
path/filepath
path
io/ioutil
log
regexp/syntax
regexp
go/token
go/scanner
go/ast
go/parser
os/exec
os/signal
net/url
text/template/parse
text/template
go/doc
go/build
cmd/go

##### Building packages and commands for linux/ppc64.
fatal error: schedule: holding locks

runtime stack:
runtime.throw(0x352710, 0x17)
	/tmp/gobuilder/linux-ppc64-f8fd5502ecdb/go/src/runtime/panic.go:543 +0xb0
runtime.schedule()
	/tmp/gobuilder/linux-ppc64-f8fd5502ecdb/go/src/runtime/proc1.go:1416 +0x6c
runtime.park_m(0xc2080005a0)
	/tmp/gobuilder/linux-ppc64-f8fd5502ecdb/go/src/runtime/proc1.go:1518 +0x170
runtime.mcall(0xc2080005a0)
	/tmp/gobuilder/linux-ppc64-f8fd5502ecdb/go/src/runtime/asm_ppc64x.s:176 +0x4c

goroutine 1 [chan receive, locked to thread]:
runtime.gopark(0x3b21f8, 0xc208044058, 0x3316f0, 0xc, 0x1700000000000001, 0x3)
	/tmp/gobuilder/linux-ppc64-f8fd5502ecdb/go/src/runtime/proc.go:162 +0x17c
runtime.goparkunlock(0xc208044058, 0x3316f0, 0xc, 0x1700000000000068, 0x3)
	/tmp/gobuilder/linux-ppc64-f8fd5502ecdb/go/src/runtime/proc.go:168 +0x58
runtime.chanrecv(0x254200, 0xc208044000, 0x0, 0x10000c208039f70, 0x8cd1c)
	/tmp/gobuilder/linux-ppc64-f8fd5502ecdb/go/src/runtime/chan.go:491 +0x988
runtime.chanrecv1(0x254200, 0xc208044000, 0x0)
	/tmp/gobuilder/linux-ppc64-f8fd5502ecdb/go/src/runtime/chan.go:335 +0x30
runtime.gcenable()
	/tmp/gobuilder/linux-ppc64-f8fd5502ecdb/go/src/runtime/mgc.go:174 +0x7c
runtime.main()
	/tmp/gobuilder/linux-ppc64-f8fd5502ecdb/go/src/runtime/proc.go:61 +0xf4
runtime.goexit()
	/tmp/gobuilder/linux-ppc64-f8fd5502ecdb/go/src/runtime/asm_ppc64x.s:1272 +0x4
Build complete, duration 4m18.789382s. Result: error: exit status 2
```

/cc @rsc @dvyukov @davecheney @aclements (I forget who's been working on ppc64)

**Comment by minux** [comment]
This issue has been fixed by https://golang.org/cl/9647
(commit 931328b8b837d0a827d05989f79f28725a704b71)

It seems nobody is working on ppc64 (not ppc64le) these days....
