### ISSUE TITLE
runtime: signal arrived during cgo execution in syscall.AcceptEx

### ISSUE THREAD

**Issue by AudriusButkevicius** [golang/go#10300]
Reporting on behalf of our user.

Running on go1.4.2 windows-386 but cross-compiled on Linux.
I believe no CGO is involved (otherwise we wouldn't be able to cross-compile that easily?)

```
Exception 0xc0000005 0x0 0x0 0x0
PC=0x0
signal arrived during cgo execution

syscall.AcceptEx(0x6b8, 0x680, 0x113b27e0, 0x0, 0x70, 0x70, 0x1153a058, 0x1153a038, 0x0, 0x0)
    /usr/local/go/src/syscall/zsyscall_windows.go:1499 +0x96
net.funcВ·028(0x1153a038, 0x0, 0x0)
    /usr/local/go/src/net/fd_windows.go:557 +0x85
net.(*ioSrv).ProcessRemoteIO(0x113ac758)
    /usr/local/go/src/net/fd_windows.go:146 +0x9d
created by net.startServer
    /usr/local/go/src/net/fd_windows.go:244 +0xba

goroutine 1 [running, locked to thread]:
    goroutine running on other thread; stack unavailable

goroutine 5 [syscall]:
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:21 +0x21
created by os/signal.initВ·1
    /usr/local/go/src/os/signal/signal_unix.go:27 +0x34

goroutine 7 [select]:
github.com/syncthing/syncthing/internal/events.(*Subscription).Poll(0x113e6a60, 0xf8475800, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /go/src/github.com/syncthing/syncthing/internal/events/events.go:173 +0x33f
github.com/syncthing/syncthing/internal/events.(*BufferedSubscription).pollingLoop(0x11394750)
    /go/src/github.com/syncthing/syncthing/internal/events/events.go:209 +0x44
created by github.com/syncthing/syncthing/internal/events.NewBufferedSubscription
    /go/src/github.com/syncthing/syncthing/internal/events/events.go:203 +0x175

goroutine 8 [chan receive]:
main.trackCPUUsage()
    /go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_windows.go:37 +0x460
created by main.initВ·3
    /go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_windows.go:17 +0x25

goroutine 10 [chan receive]:
github.com/syncthing/syncthing/internal/config.(*Wrapper).Serve(0x113caea0)
    /go/src/github.com/syncthing/syncthing/internal/config/wrapper.go:79 +0x6a
created by github.com/syncthing/syncthing/internal/config.Wrap
    /go/src/github.com/syncthing/syncthing/internal/config/wrapper.go:54 +0x10b

goroutine 11 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0x113d24d0)
    /go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:205 +0x1c5
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
    /go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:236 +0x1bb

goroutine 12 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0x113b2540)
    /go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:120 +0x414
created by github.com/syndtr/goleveldb/leveldb.openDB
    /go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:126 +0x731

goroutine 13 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0x113b2540)
    /go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_state.go:73 +0x11d
created by github.com/syndtr/goleveldb/leveldb.openDB
    /go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:127 +0x746

goroutine 14 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0x113b2540)
    /go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:812 +0x68a
created by github.com/syndtr/goleveldb/leveldb.openDB
    /go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:130 +0x780

goroutine 15 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0x113b2540)
    /go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:759 +0x221
created by github.com/syndtr/goleveldb/leveldb.openDB
    /go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:131 +0x795

goroutine 16 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0x113b2540)
    /go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x153
created by github.com/syndtr/goleveldb/leveldb.openDB
    /go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:132 +0x7aa

goroutine 17 [select]:
github.com/syncthing/syncthing/internal/model.(*ProgressEmitter).Serve(0x114342a0)
    /go/src/github.com/syncthing/syncthing/internal/model/progressemitter.go:48 +0x6d8
created by github.com/syncthing/syncthing/internal/model.NewModel
    /go/src/github.com/syncthing/syncthing/internal/model/model.go:117 +0x570

goroutine 18 [sleep]:
github.com/syncthing/syncthing/internal/model.funcВ·029()
    /go/src/github.com/syncthing/syncthing/internal/model/util.go:17 +0x57
created by github.com/syncthing/syncthing/internal/model.deadlockDetect
    /go/src/github.com/syncthing/syncthing/internal/model/util.go:35 +0xb8

goroutine 19 [sleep]:
github.com/syncthing/syncthing/internal/model.funcВ·029()
    /go/src/github.com/syncthing/syncthing/internal/model/util.go:17 +0x57
created by github.com/syncthing/syncthing/internal/model.deadlockDetect
    /go/src/github.com/syncthing/syncthing/internal/model/util.go:35 +0xb8

goroutine 20 [select]:
github.com/syncthing/syncthing/internal/ignore.(*Matcher).clean(0x1142e180, 0x61714000, 0x68c)
    /go/src/github.com/syncthing/syncthing/internal/ignore/ignore.go:153 +0x192
created by github.com/syncthing/syncthing/internal/ignore.New
    /go/src/github.com/syncthing/syncthing/internal/ignore/ignore.go:53 +0xb4

goroutine 22 [chan receive, locked to thread]:
net.(*ioSrv).ProcessRemoteIO(0x113ac760)
    /usr/local/go/src/net/fd_windows.go:144 +0x6d
created by net.startServer
    /usr/local/go/src/net/fd_windows.go:246 +0x109

goroutine 23 [chan receive]:
net.(*ioSrv).ExecIO(0x113ac758, 0x1153a038, 0x8aa078, 0x8, 0x11604000, 0x113b28c0, 0x0, 0x0)
    /usr/local/go/src/net/fd_windows.go:171 +0xb2b
net.(*netFD).acceptOne(0x1153a000, 0x113b27e0, 0x2, 0x2, 0x1153a038, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/fd_windows.go:558 +0x3ee
net.(*netFD).accept(0x1153a000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/fd_windows.go:585 +0x119
net.(*TCPListener).AcceptTCP(0x113ac768, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:234 +0x48
net.(*TCPListener).Accept(0x113ac768, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:244 +0x48
main.(*DowngradingListener).Accept(0x11399330, 0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/syncthing/syncthing/cmd/syncthing/tls.go:104 +0x61
net/http.(*Server).Serve(0x11452580, 0x313bde50, 0x11399330, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:1728 +0x7b
main.funcВ·001()
    /go/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:183 +0x58
created by main.startGUI
    /go/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:187 +0x10a8
eax     0x6b8
ebx     0x11c7cf28
ecx     0x0
edx     0x11c7cefc
edi     0x3152ff6c
esi     0x11c7cf74
ebp     0x3152ff44
esp     0x3152ff1c
eip     0x0
eflags  0x10246
cs      0x1b
fs      0x3b
gs      0x0
```

Another crash, but slightly different stacktrace:
```
Exception 0xc0000005 0x0 0x0 0x0
PC=0x0
signal arrived during cgo execution

syscall.AcceptEx(0x6a0, 0x680, 0x113b27e0, 0x0, 0x70, 0x70, 0x11510058, 0x11510038, 0x0, 0x0)
    /usr/local/go/src/syscall/zsyscall_windows.go:1499 +0x96
net.funcВ·028(0x11510038, 0x0, 0x0)
    /usr/local/go/src/net/fd_windows.go:557 +0x85
net.(*ioSrv).ProcessRemoteIO(0x114341d8)
    /usr/local/go/src/net/fd_windows.go:146 +0x9d
created by net.startServer
    /usr/local/go/src/net/fd_windows.go:244 +0xba

goroutine 1 [syscall, locked to thread]:
syscall.Setsockopt(0x678, 0x0, 0x11450ae4, 0x11438000, 0x113a2000, 0x115100e0, 0x0)
    /usr/local/go/src/syscall/zsyscall_windows.go:1391 +0x7e
syscall.SetsockoptIPMreq(0x7a4820, 0x11432840, 0x11450b3c, 0x0, 0x10, 0x11436d20)
    /usr/local/go/src/syscall/syscall_windows.go:891 +0x58
net.(*ioSrv).ExecIO(0x114341e0, 0x11510164, 0x8b0a58, 0x9, 0x9ae21c, 0x2, 0x4ee013, 0x115100e0)
    /usr/local/go/src/net/fd_windows.go:171 +0xb2b
net.(*netFD).writeTo(0x313a6b98, 0x113b46c0, 0x89, 0x90, 0x11438000, 0x11436d20, 0x89, 0x0, 0x313a0000)
    /usr/local/go/src/net/fd_windows.go:532 +0x172
...
[snip]
...
eax     0x6a0
ebx     0x11c7cf28
ecx     0x0
edx     0x11c7cefc
edi     0x314eff6c
esi     0x11c7cf74
ebp     0x314eff44
esp     0x314eff1c
eip     0x0
eflags  0x10246
cs      0x1b
fs      0x3b
gs      0x0
```
You can find more stacktraces at: https://github.com/syncthing/syncthing/issues/1519

**Comment by ianlancetaylor** [comment]
Windows system calls use the cgo mechanism even if your program doesn't use cgo.  In this case that message just means that the exception occurred while executing a system call.

I don't know what the actual problem is, but the message about cgo is a distraction.

**Comment by minux** [comment]
interesting note: pc == 0.

we need gdb backtrace for those runs, because the argument to AcceptEx
is not obviously wrong.

A standalone reproducer would be even better.

**Comment by rsc** [comment]
Without instructions to reproduce, I don't think we can fix this.
