### ISSUE TITLE
misc/cgo/testso: broken by https://go-review.googlesource.com/8523 on darwin, netbsd

### ISSUE THREAD

**Issue by mikioh** [golang/go#10360]
It fails with the following dying message:
```
# _/go/misc/cgo/testso
duplicate symbol _exported_var in:
    $WORK/_/go/misc/cgo/testso/_obj/_cgo_export.o
    $WORK/_/go/misc/cgo/testso/_obj/cgoso.cgo2.o
duplicate symbol _exported_var in:
    $WORK/_/go/misc/cgo/testso/_obj/_cgo_export.o
    $WORK/_/go/misc/cgo/testso/_obj/cgoso.o
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by mikioh** [comment]
cd $GOROOT/misc/cgo/testso && go build -x -v -work main.go 
```
WORK=/var/folders/vf/54l674h969s3l44yrks6f50r0000gn/T/go-build797442963
_/go/misc/cgo/testso
mkdir -p $WORK/_/go/misc/cgo/testso/_obj/
mkdir -p $WORK/_/go/misc/cgo/
cd /go/misc/cgo/testso
CGO_LDFLAGS="-g" "-O2" "-L." "libcgosotest.dylib" /go/pkg/tool/darwin_amd64/cgo -objdir $WORK/_/go/misc/cgo/testso/_obj/ -- -I $WORK/_/go/misc/cgo/testso/_obj/ cgoso.go
clang -I . -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common -print-libgcc-file-name
clang -I . -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common -I $WORK/_/go/misc/cgo/testso/_obj/ -g -O2 -o $WORK/_/go/misc/cgo/testso/_obj/_cgo_main.o -c $WORK/_/go/misc/cgo/testso/_obj/_cgo_main.c
clang -I . -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common -I $WORK/_/go/misc/cgo/testso/_obj/ -g -O2 -o $WORK/_/go/misc/cgo/testso/_obj/_cgo_export.o -c $WORK/_/go/misc/cgo/testso/_obj/_cgo_export.c
clang -I . -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common -I $WORK/_/go/misc/cgo/testso/_obj/ -g -O2 -o $WORK/_/go/misc/cgo/testso/_obj/cgoso.cgo2.o -c $WORK/_/go/misc/cgo/testso/_obj/cgoso.cgo2.c
clang -I . -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common -I $WORK/_/go/misc/cgo/testso/_obj/ -g -O2 -o $WORK/_/go/misc/cgo/testso/_obj/cgoso.o -c ./cgoso.c
clang -I . -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common -o $WORK/_/go/misc/cgo/testso/_obj/_cgo_.o $WORK/_/go/misc/cgo/testso/_obj/_cgo_main.o $WORK/_/go/misc/cgo/testso/_obj/_cgo_export.o $WORK/_/go/misc/cgo/testso/_obj/cgoso.cgo2.o $WORK/_/go/misc/cgo/testso/_obj/cgoso.o -g -O2 -L. libcgosotest.dylib
# _/go/misc/cgo/testso
duplicate symbol _exported_var in:
    $WORK/_/go/misc/cgo/testso/_obj/_cgo_export.o
    $WORK/_/go/misc/cgo/testso/_obj/cgoso.cgo2.o
duplicate symbol _exported_var in:
    $WORK/_/go/misc/cgo/testso/_obj/_cgo_export.o
    $WORK/_/go/misc/cgo/testso/_obj/cgoso.o
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by mikioh** [comment]
Also NetBSD: http://build.golang.org/log/d6bf46b1935d9684bf8c87864ad30aa482db9a0c
```
##### ../misc/cgo/testso
panic: testExportedVar: got "", but want "Hello world"

goroutine 1 [running]:
_/tmp/gobuilder/netbsd-386-minux-9fa9f966e99e/go/misc/cgo/testso.testExportedVar()
	/tmp/gobuilder/netbsd-386-minux-9fa9f966e99e/go/misc/cgo/testso/cgoso.go:39 +0x35b
_/tmp/gobuilder/netbsd-386-minux-9fa9f966e99e/go/misc/cgo/testso.Test()
	/tmp/gobuilder/netbsd-386-minux-9fa9f966e99e/go/misc/cgo/testso/cgoso.go:32 +0x22
main.main()
	/tmp/gobuilder/netbsd-386-minux-9fa9f966e99e/go/misc/cgo/testso/main.go:12 +0x18

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/tmp/gobuilder/netbsd-386-minux-9fa9f966e99e/go/src/runtime/asm_386.s:1637 +0x1
2015/04/07 03:14:01 Failed: exit status 2
```

**Comment by bradfitz** [comment]
@alexbrainman, please revert your change or fix quickly.

**Comment by alexbrainman** [comment]
@bradfitz I don't know how to fix this I will leave it for @minux. I am happy to revert. Do I just press "revert" button in "Gerrit"?

Alex

**Comment by alexbrainman** [comment]
https://go-review.googlesource.com/#/c/8527/ to revert. I wonder why trybots didn't complain before we have submitted original change

Alex

**Comment by alexbrainman** [comment]
I guess trybots didn't complain, because we don't have any darwin or netbsd trybots running at this moment. I will just revert.

Alex.

**Comment by ianlancetaylor** [comment]
Should be fixed by https://golang.org/cl/12470.
