### ISSUE TITLE
cmd/go: go build crashes with "index out of range"

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#10391]
Running

```
GOOS=windows go build -gcflags -m syscall
```

against 414444d41622a9bfd8010786d5c3b8a28e10e2a5

on linux-386 outputs

```
# runtime
../runtime/alg.go:50: can inline memhash0
../runtime/stubs.go:17: can inline add
...
...
...
../sync/atomic/value.go:44: leaking param: x
../sync/atomic/value.go:49: (*Value).Store &x does not escape
panic: runtime error: index out of range

goroutine 7 [running]:
regexp.(*machine).backtrack(0x18aab290, 0xb6c3cbb8, 0x18aab2fc, 0x0, 0x32c7, 0x0, 0x1886d760)
	/root/go/root/src/regexp/backtrack.go:343 +0x26e
regexp.(*Regexp).doExecute(0x1887c840, 0x0, 0x0, 0x0, 0x0, 0x0, 0x18ad6000, 0x32c7, 0x0, 0x0, ...)
	/root/go/root/src/regexp/exec.go:449 +0x34c
regexp.(*Regexp).MatchString(0x1887c840, 0x18ad6000, 0x32c7, 0x3e00)
	/root/go/root/src/regexp/regexp.go:400 +0x60
main.(*builder).processOutput(0x188c2880, 0x188f8000, 0x32c7, 0x3e00, 0x0, 0x0)
	/root/go/root/src/cmd/go/build.go:1426 +0x109
main.(*builder).build(0x188c2880, 0x18ae2310, 0x0, 0x0)
	/root/go/root/src/cmd/go/build.go:972 +0x204a
main.(*builder).do.func1(0x18ae2310)
	/root/go/root/src/cmd/go/build.go:737 +0x2d6
main.(*builder).do.func2(0x18af62e0, 0x188c2880, 0x18aec480)
	/root/go/root/src/cmd/go/build.go:794 +0x11b
created by main.(*builder).do
	/root/go/root/src/cmd/go/build.go:800 +0x388

goroutine 1 [runnable]:
sync.runtime_Semacquire(0x18aec490)
	/root/go/root/src/runtime/sema.go:43 +0x2d
sync.(*WaitGroup).Wait(0x18af62e0)
	/root/go/root/src/sync/waitgroup.go:132 +0x13e
main.(*builder).do(0x188c2880, 0x18ae2070)
	/root/go/root/src/cmd/go/build.go:803 +0x3a5
main.runBuild(0x85c55e0, 0x1880a378, 0x0, 0x0)
	/root/go/root/src/cmd/go/build.go:326 +0x5c6
main.main()
	/root/go/root/src/cmd/go/main.go:175 +0x632

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/root/go/root/src/runtime/asm_386.s:1637 +0x1

goroutine 5 [syscall]:
os/signal.loop()
	/root/go/root/src/os/signal/signal_unix.go:22 +0x21
created by os/signal.init.1
	/root/go/root/src/os/signal/signal_unix.go:28 +0x3d
```

Alex

**Comment by minux** [comment]
Merge into #10319.
