### ISSUE TITLE
cmd/gc: compiler crash

### ISSUE THREAD

**Issue by bradfitz** [golang/go#10441]
This commit causes compiling Camlistore to crash in the compiler:

@dvyukov: cmd/gc: fix escape analysis of closures
https://go-review.googlesource.com/#/c/8408/

It seems that the new Node lacks a Type perhaps.

Repro:

```
$ go get -d camlistore.org/pkg/server
$ go install camlistore.org/pkg/server
$ go install -v camlistore.org/pkg/server
camlistore.org/pkg/search
camlistore.org/pkg/server
# camlistore.org/pkg/server
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xf pc=0x10fdcf]

goroutine 1 [running]:
cmd/internal/gc.haspointers(0x0, 0xffffffffffffffff)
	/Users/bradfitz/go/src/cmd/internal/gc/reflect.go:623 +0x1f
cmd/internal/gc.escwalk(0x20c82dc00, 0xffffffffffffffff, 0x20c82dda0, 0x20c835520)
	/Users/bradfitz/go/src/cmd/internal/gc/esc.go:1291 +0x14aa
cmd/internal/gc.escwalk(0x20c82dc00, 0xffffffffffffffff, 0x20c82dda0, 0x20beac340)
	/Users/bradfitz/go/src/cmd/internal/gc/esc.go:1386 +0x836
cmd/internal/gc.escwalk(0x20c82dc00, 0x0, 0x20c82dda0, 0x20c5f4000)
	/Users/bradfitz/go/src/cmd/internal/gc/esc.go:1328 +0x11b2
cmd/internal/gc.escwalk(0x20c82dc00, 0x0, 0x20c82dda0, 0x20beaf1e0)
	/Users/bradfitz/go/src/cmd/internal/gc/esc.go:1386 +0x836
cmd/internal/gc.escflood(0x20c82dc00, 0x20c82dda0)
	/Users/bradfitz/go/src/cmd/internal/gc/esc.go:1224 +0x324
cmd/internal/gc.escAnalyze(0x20c830b20, 0x20c829c00)
	/Users/bradfitz/go/src/cmd/internal/gc/esc.go:302 +0x312
cmd/internal/gc.(*bottomUpVisitor).visit(0x20c7b54a0, 0x20bea2000, 0xb2)
	/Users/bradfitz/go/src/cmd/internal/gc/esc.go:115 +0x1e6
cmd/internal/gc.(*bottomUpVisitor).visitcode(0x20c7b54a0, 0x20be9f380, 0xb2, 0x2000000b2)
	/Users/bradfitz/go/src/cmd/internal/gc/esc.go:149 +0x245
cmd/internal/gc.(*bottomUpVisitor).visitcodelist(0x20c7b54a0, 0x20be797e0, 0x2000000b2, 0x90c4d)
	/Users/bradfitz/go/src/cmd/internal/gc/esc.go:123 +0x4d
cmd/internal/gc.(*bottomUpVisitor).visit(0x20c7b54a0, 0x20c5eb520, 0xb0)
	/Users/bradfitz/go/src/cmd/internal/gc/esc.go:91 +0x10e
cmd/internal/gc.(*bottomUpVisitor).visitcode(0x20c7b54a0, 0x20be9dba0, 0x2000000b0, 0xb0)
	/Users/bradfitz/go/src/cmd/internal/gc/esc.go:157 +0x1cf
cmd/internal/gc.(*bottomUpVisitor).visitcode(0x20c7b54a0, 0x20be9f520, 0xb0, 0xb0)
	/Users/bradfitz/go/src/cmd/internal/gc/esc.go:134 +0x75
cmd/internal/gc.(*bottomUpVisitor).visitcode(0x20c7b54a0, 0x20be9f6c0, 0xb0, 0xb0)
	/Users/bradfitz/go/src/cmd/internal/gc/esc.go:134 +0x75
cmd/internal/gc.(*bottomUpVisitor).visitcodelist(0x20c7b54a0, 0x20be79800, 0xb0, 0xb0)
	/Users/bradfitz/go/src/cmd/internal/gc/esc.go:123 +0x4d
cmd/internal/gc.(*bottomUpVisitor).visitcode(0x20c7b54a0, 0x20be9cb60, 0xb0, 0x2000000b0)
	/Users/bradfitz/go/src/cmd/internal/gc/esc.go:139 +0x13d
cmd/internal/gc.(*bottomUpVisitor).visitcodelist(0x20c7b54a0, 0x20be79820, 0xb0, 0x90c4d)
	/Users/bradfitz/go/src/cmd/internal/gc/esc.go:123 +0x4d
cmd/internal/gc.(*bottomUpVisitor).visit(0x20c7b54a0, 0x20be961a0, 0xac)
	/Users/bradfitz/go/src/cmd/internal/gc/esc.go:91 +0x10e
cmd/internal/gc.(*bottomUpVisitor).visitcode(0x20c7b54a0, 0x20be95380, 0xac, 0xac)
	/Users/bradfitz/go/src/cmd/internal/gc/esc.go:149 +0x245
cmd/internal/gc.(*bottomUpVisitor).visitcode(0x20c7b54a0, 0x20be95520, 0x2000000ac, 0x2000000ac)
	/Users/bradfitz/go/src/cmd/internal/gc/esc.go:134 +0x75
cmd/internal/gc.(*bottomUpVisitor).visitcodelist(0x20c7b54a0, 0x20be79140, 0xac, 0x90c4d)
	/Users/bradfitz/go/src/cmd/internal/gc/esc.go:123 +0x4d
cmd/internal/gc.(*bottomUpVisitor).visit(0x20c7b54a0, 0x20be8e680, 0x200000086)
	/Users/bradfitz/go/src/cmd/internal/gc/esc.go:91 +0x10e
cmd/internal/gc.(*bottomUpVisitor).visitcode(0x20c7b54a0, 0x20bdce4e0, 0x200000086, 0x200000086)
	/Users/bradfitz/go/src/cmd/internal/gc/esc.go:149 +0x245
cmd/internal/gc.(*bottomUpVisitor).visitcode(0x20c7b54a0, 0x20bdce680, 0x200000086, 0x200000086)
	/Users/bradfitz/go/src/cmd/internal/gc/esc.go:134 +0x75
cmd/internal/gc.(*bottomUpVisitor).visitcodelist(0x20c7b54a0, 0x20bdc2a20, 0x86, 0x86)
	/Users/bradfitz/go/src/cmd/internal/gc/esc.go:123 +0x4d
cmd/internal/gc.(*bottomUpVisitor).visitcode(0x20c7b54a0, 0x20bdce000, 0x86, 0x200000086)
	/Users/bradfitz/go/src/cmd/internal/gc/esc.go:139 +0x13d
cmd/internal/gc.(*bottomUpVisitor).visitcodelist(0x20c7b54a0, 0x20bdc2a40, 0x86, 0x84)
	/Users/bradfitz/go/src/cmd/internal/gc/esc.go:123 +0x4d
cmd/internal/gc.(*bottomUpVisitor).visit(0x20c7b54a0, 0x20bdaf1e0, 0x84)
	/Users/bradfitz/go/src/cmd/internal/gc/esc.go:91 +0x10e
cmd/internal/gc.visitBottomUp(0x208713320, 0x3c7058)
	/Users/bradfitz/go/src/cmd/internal/gc/esc.go:67 +0xaf
cmd/internal/gc.escapes(0x208713320)
	/Users/bradfitz/go/src/cmd/internal/gc/esc.go:198 +0x34
cmd/internal/gc.Main()
	/Users/bradfitz/go/src/cmd/internal/gc/lex.go:427 +0x1cc2
main.main()
	/Users/bradfitz/go/src/cmd/6g/galign.go:123 +0x71f
```

In case Camlistore accidentally changes and ends up avoiding this crash, I verify it's still crashing at camlistore/camlistore@f88da2ae70d9

**Comment by bradfitz** [comment]
I whittled it down to this:

```
package main

func main() {
        dst := &T{
                fn: func(error) error { return nil },
        }
        dst.Get()
}

type T struct {
        c   <-chan error
        fn  func(error) error
        err error
}

func (t *T) Set(err error) {
        if t.fn != nil && err != nil {
                err = t.fn(err)
        }
}

func (t *T) Get() error {
        t.Set(<-t.c)
        return t.err
}
```

If you `go run` that, it'll crash the same way.

**Comment by dr2chase** [comment]
I'm testing a patch of mine, if it deadlocks, that means the bug is
fixed/better-hidden?
(Sorry if the deadlock is obviously intended, I'm learning my Go on a
street corner.)


On Mon, Apr 13, 2015 at 11:09 PM, Brad Fitzpatrick <notifications@github.com

**Comment by bradfitz** [comment]
Yes, this program in its minimal form simply deadlocks when ran.

**Comment by dvyukov** [comment]
@dr2chase I've already mailed https://go-review.googlesource.com/#/c/8932/ with a fix

**Comment by dr2chase** [comment]
So, in theory my patch fixes it, but I don't believe it because the -m
chit-chat looks to be the same, modulo cosmetic changes.  Oh, this is the
bug that Dmitry is fixing (or so it looks to me).  Never mind.


On Tue, Apr 14, 2015 at 11:00 AM, Brad Fitzpatrick <notifications@github.com
