### ISSUE TITLE
net: possible nil pointer deref. on ReadFrom for windows

### ISSUE THREAD

**Issue by mikioh** [golang/go#10516]
See http://build.golang.org/log/3a328d1f4e0b6874c9092dc862efe00f93322ad6
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x5d12d4]

goroutine 276 [running]:
syscall.(*RawSockaddrAny).Sockaddr(0x0, 0x0, 0x0, 0x0, 0x0)
	C:/workdir/go/src/syscall/syscall_windows.go:657 +0x44
net.(*netFD).readFrom(0xc082246900, 0xc082237000, 0x400, 0x400, 0x0, 0x0, 0x0, 0x0, 0x0)
	C:/workdir/go/src/net/fd_windows.go:484 +0x239
net.(*UDPConn).ReadFromUDP(0xc082020380, 0xc082237000, 0x400, 0x400, 0x23bef0a0, 0x864be0, 0x0, 0x0)
	C:/workdir/go/src/net/udpsock_posix.go:61 +0x121
net.(*UDPConn).ReadFrom(0xc082020380, 0xc082237000, 0x400, 0x400, 0x0, 0x0, 0x0, 0x0, 0x0)
	C:/workdir/go/src/net/udpsock_posix.go:79 +0x120
net.runDatagramPacketConnServer(0xc082230870, 0x6f63b0, 0x3, 0x6faa10, 0xb, 0xc082282180, 0xc0822821e0)
	C:/workdir/go/src/net/server_test.go:324 +0x582
created by net.TestTimeoutUDP
	C:/workdir/go/src/net/timeout_test.go:313 +0xc6
```

**Comment by alexbrainman** [comment]
How can I reproduce this?

Alex

**Comment by mikioh** [comment]
Not sure, perhaps, 1) zero-byte read/write ops, 2) timeout ops, 3) combo of (1)+(2). I'm working on polishing (4-yrs old) test cases and will add above cases.
