### ISSUE TITLE
runtime: fatal error: acquireSudog: found s.elem != nil in cache

### ISSUE THREAD

**Issue by dvyukov** [golang/go#10541]
Just observed the following crash:
```
fatal error: acquireSudog: found s.elem != nil in cache

goroutine 54 [running]:
runtime.throw(0x8a6bd0, 0x2a)
	src/runtime/panic.go:543 +0x96 fp=0xc209b939a8 sp=0xc209b93990
runtime.acquireSudog(0xc20801edc8)
	src/runtime/proc.go:232 +0x456 fp=0xc209b93a48 sp=0xc209b939a8
runtime.chanrecv(0x6ecee0, 0xc20801ed80, 0xc209b93b78, 0x1, 0x0)
	src/runtime/chan.go:422 +0x306 fp=0xc209b93b08 sp=0xc209b93a48
runtime.chanrecv1(0x6ecee0, 0xc20801ed80, 0xc209b93b78)
	src/runtime/chan.go:335 +0x2b fp=0xc209b93b38 sp=0xc209b93b08
main.(*Testee).shutdown(0xc2081c2380, 0x0, 0x0, 0x0)
	src/github.com/dvyukov/go-fuzz/go-fuzz/testee.go:200 +0xd4 fp=0xc209b93b98 sp=0xc209b93b38
main.(*Slave).exec(0xc208188210, 0xc208010380, 0x7, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	src/github.com/dvyukov/go-fuzz/go-fuzz/slave.go:344 +0x20a fp=0xc209b93bf8 sp=0xc209b93b98
main.(*Slave).minimizeInput(0xc208188210, 0xc208011c20, 0xb, 0xb, 0x6dc301, 0xc209b93de8, 0x0, 0x0, 0x0)
	src/github.com/dvyukov/go-fuzz/go-fuzz/slave.go:179 +0x171 fp=0xc209b93da0 sp=0xc209b93bf8
main.(*Slave).processCrasher(0xc208188210, 0xc208011c20, 0xb, 0xb, 0xc20a505000, 0xbbb, 0xbbb, 0xc208110e40, 0xb4, 0xc0, ...)
	src/github.com/dvyukov/go-fuzz/go-fuzz/slave.go:166 +0x93 fp=0xc209b93e58 sp=0xc209b93da0
main.(*Slave).loop(0xc208188210)
	src/github.com/dvyukov/go-fuzz/go-fuzz/slave.go:67 +0x124 fp=0xc209b93fd8 sp=0xc209b93e58
runtime.goexit()
	src/runtime/asm_amd64.s:1671 +0x1 fp=0xc209b93fe0 sp=0xc209b93fd8
created by main.slaveMain
	src/github.com/dvyukov/go-fuzz/go-fuzz/slave.go:56 +0xf6
```

I see it for the first time.

go version devel +87054c4 Wed Apr 22 02:50:48 2015 +0000 linux/amd64

**Comment by aclements** [comment]
Hi Dmitry. I think we've fixed this issue in the course of fixing various memory corruption and lost write barrier problems over the past few weeks. Please reopen if you're still seeing this or come across it again.
