### ISSUE TITLE
cmd/cgo: TestCgoExternalThreadPanic fails by "invalid relocation and dwarf: definition of unknown kind 0" on openbsd/386

### ISSUE THREAD

**Issue by mikioh** [golang/go#10567]
See https://storage.googleapis.com/go-build-log/9460f554/openbsd-386-gce56_6fb4d378.log
```
##### GOMAXPROCS=2 runtime -cpu=1,2,4
--- FAIL: TestCgoExternalThreadPanic (1.53s)
	crash_test.go:92: building source: exit status 2
		# _/tmp/go-build410912323
		type.*struct { F uintptr; s **runtime.mspan; h *runtime.mheap; npage uintptr; sizeclass int32; large bool }: type.*struct { F uintptr; s **runtime.mspan; h *runtime.mheap; npage uintptr; sizeclass int32; large bool }: invalid relocation 0+173 not in [0,44)
		syscall.errors: dwarf: definition of unknown kind 0: type.*struct { F uintptr; s **runtime.mspan; h *runtime.mheap; npage uintptr; sizeclass int32; large bool }
FAIL
FAIL	runtime	53.702s
```

**Comment by bradfitz** [comment]
Just saw another on openbsd-386 at 4a8dbaa4b1d4 (but passed before & after):

http://build.golang.org/log/087d2ce773bc58aa635485cb32750acd996ecc28
```
##### GOMAXPROCS=2 runtime -cpu=1,2,4
--- FAIL: TestCgoExternalThreadPanic-2 (1.36s)
	crash_test.go:92: building source: exit status 2
		# _/tmp/go-build428181342
		type..alg524288: type..alg524288: invalid relocation 414911616+173 not in [0,8)
		type..alg524288: missing xsym in relocation
		type..alg524288: missing xsym in relocation
		panic: runtime error: invalid memory address or nil pointer dereference
		[signal 0xb code=0x1 addr=0x1eb pc=0x80e41e2]
		
		goroutine 1 [running]:
		cmd/internal/ld.undefsym(0x1877c000)
			/tmp/buildlet-scatch752582679/go/src/cmd/internal/ld/lib.go:1791 +0x92
		cmd/internal/ld.undef()
			/tmp/buildlet-scatch752582679/go/src/cmd/internal/ld/lib.go:1805 +0x56
		cmd/internal/ld.Ldmain()
			/tmp/buildlet-scatch752582679/go/src/cmd/internal/ld/pobj.go:241 +0x1828
		main.main()
			/tmp/buildlet-scatch752582679/go/src/cmd/8l/obj.go:44 +0x1d
FAIL
```

I'm going to tag this Go 1.5 until we at least understand it. If it ends up being an OpenBSD-specific thing, we wouldn't hold up the release for it.

**Comment by rsc** [comment]
Given the lack of activity, I assume this has resolved itself or is openbsd-specific. If the issue should be reopened, please remove the Go1.5 milestone.
