### ISSUE TITLE
cmd/8g: panic()s on invalid GO386

### ISSUE THREAD

**Issue by mwhudson** [golang/go#10592]
Not looked into this at all.

```
mwhudson@glamdring:src$ GO386=xxx go tool 8g
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x683f4c]

goroutine 1 [running]:
bufio.(*Writer).flush(0x0, 0x0, 0x0)
	/opt/opensource/go/src/bufio/bufio.go:557 +0x3c
bufio.(*Writer).Flush(0x0, 0x0, 0x0)
	/opt/opensource/go/src/bufio/bufio.go:552 +0x34
cmd/internal/obj.Bflush(0x952ee0, 0x0, 0x0)
	/opt/opensource/go/src/cmd/internal/obj/util.go:193 +0x38
cmd/internal/gc.Flusherrors()
	/opt/opensource/go/src/cmd/internal/gc/subr.go:85 +0x32
cmd/internal/gc.Fatal(0x7a75d0, 0x1c, 0xc20803ff50, 0x1, 0x1)
	/opt/opensource/go/src/cmd/internal/gc/subr.go:200 +0x27
main.main()
	/opt/opensource/go/src/cmd/8g/galign.go:61 +0xaca
```

**Comment by davecheney** [comment]
Looks like calling `gc.Fatal` so early in the piece is a mistake because `obj.Bflush` isn't set up properly at that point.
