### ISSUE TITLE
runtime: bad pointer in write barrier

### ISSUE THREAD

**Issue by minux** [golang/go#10603]
happened during trybot run of https://golang.org/cl/8383.

https://storage.googleapis.com/go-build-log/dd551202/freebsd-386-gce101_20904c99.log

```
fatal error: bad pointer in write barrier

runtime stack:
runtime.throw(0x8231ee8, 0x1c)
	/tmp/buildlet-scatch663483884/go/src/runtime/panic.go:543 +0x79
runtime.writebarrierptr.func1()
	/tmp/buildlet-scatch663483884/go/src/runtime/mbarrier.go:116 +0x2b
runtime.systemstack(0x8268b08)
	/tmp/buildlet-scatch663483884/go/src/runtime/asm_386.s:283 +0x77
runtime.writebarrierptr(0x3840e500, 0x68686868)
	/tmp/buildlet-scatch663483884/go/src/runtime/mbarrier.go:116 +0x6c
runtime.typedmemmove.func1()
	/tmp/buildlet-scatch663483884/go/src/runtime/mbarrier.go:237 +0x1c6
runtime.systemstack(0x3840c000)
	/tmp/buildlet-scatch663483884/go/src/runtime/asm_386.s:267 +0x52
runtime.mstart()
	/tmp/buildlet-scatch663483884/go/src/runtime/proc1.go:686

goroutine 58 [running]:
runtime.systemstack_switch()
	/tmp/buildlet-scatch663483884/go/src/runtime/asm_386.s:222 fp=0x3840e4d8 sp=0x3840e4d4
runtime.typedmemmove(0x81e5440, 0x80c48868, 0x68686864)
	/tmp/buildlet-scatch663483884/go/src/runtime/mbarrier.go:250 +0x47 fp=0x3840e4f8 sp=0x3840e4d8
runtime.growslice(0x81a9120, 0x60636000, 0x7e5800, 0x7e5800, 0x1, 0x0, 0x0, 0x0)
	/tmp/buildlet-scatch663483884/go/src/runtime/slice.go:90 +0x2b2 fp=0x3840e530 sp=0x3840e4f8
internal/trace.readTrace(0x58716338, 0x38407f80, 0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/buildlet-scatch663483884/go/src/internal/trace/parser.go:145 +0x535 fp=0x3840e660 sp=0x3840e530
internal/trace.Parse(0x58716338, 0x38407f80, 0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/buildlet-scatch663483884/go/src/internal/trace/parser.go:61 +0x42 fp=0x3840e6a4 sp=0x3840e660
runtime/pprof_test.parseTrace(0x58716338, 0x38407f80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/buildlet-scatch663483884/go/src/runtime/pprof/trace_test.go:82 +0x48 fp=0x3840e70c sp=0x3840e6a4
runtime/pprof_test.TestTraceStress(0x38407f20)
	/tmp/buildlet-scatch663483884/go/src/runtime/pprof/trace_test.go:222 +0x91a fp=0x3840e7c4 sp=0x3840e70c
testing.tRunner(0x38407f20, 0x83032c4)
	/tmp/buildlet-scatch663483884/go/src/testing/testing.go:452 +0x8c fp=0x3840e7e8 sp=0x3840e7c4
runtime.goexit()
	/tmp/buildlet-scatch663483884/go/src/runtime/asm_386.s:1637 +0x1 fp=0x3840e7ec sp=0x3840e7e8
```

/cc @RLH @aclements

**Comment by aclements** [comment]
Based on the dashboard, it looks like this stopped happening on May 11th when there were several commits that dramatically changed the way typedmemmove works.
