### ISSUE TITLE
cmd/compile: compiler crash on valid code

### ISSUE THREAD

**Issue by crawshaw** [golang/go#10654]
At rev 5f69e739d3b0 (1 May):

```
package main

var s string

func main() {
	if (s == "all") != (s == "all") {
	}
}
```

Results in:

```
$ go build junk.go 
# command-line-arguments
naddr [0x208773180]
.   ANDAND u(100) l(6) tc(1) bool
.   .   EQ u(2) l(6) tc(1) bool
.   .   .   LEN u(2) a(true) l(6) tc(1) int
.   .   .   .   NAME-main.s u(1) a(true) l(3) x(0+0) class(PEXTERN) tc(1) used(true) string
.   .   .   LITERAL-3 u(1) a(true) x(0+0) tc(1) int
.   .   CALLFUNC u(100) l(6) tc(1) bool
.   .   .   NAME-runtime.eqstring u(1) a(true) l(2) x(0+0) class(PFUNC) tc(1) used(true) FUNC-func(string, string) bool
.   .   CALLFUNC-list
.   .   .   AS u(1) l(6) tc(1)
.   .   .   .   INDREG-SP a(true) l(6) x(0+0) tc(1) string
.   .   .   .   NAME-main.s u(1) a(true) l(3) x(0+0) class(PEXTERN) tc(1) used(true) string

.   .   .   AS u(1) l(6) tc(1)
.   .   .   .   INDREG-SP a(true) l(6) x(16+0) tc(1) string
.   .   .   .   LITERAL-"all" u(1) a(true) l(6) tc(1) string
./junk.go:6: internal compiler error: naddr: bad && 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x14a737]

goroutine 1 [running]:
cmd/internal/gc.hcrash()
	/Users/crawshaw/go/src/cmd/internal/gc/subr.go:105 +0x57
cmd/internal/gc.Fatal(0x38c7b0, 0x10, 0x20877b550, 0x2, 0x2)
	/Users/crawshaw/go/src/cmd/internal/gc/subr.go:213 +0x2c4
cmd/internal/gc.Naddr(0x20878b0f0, 0x208773180)
	/Users/crawshaw/go/src/cmd/internal/gc/gsubr.go:307 +0x15fc
main.gins(0x3036, 0x208773180, 0x20877c380, 0x2085b7369)
	/Users/crawshaw/go/src/cmd/6g/gsubr.go:597 +0x101
cmd/internal/gc.bgenx(0x208771180, 0x0, 0x1, 0x0, 0x20877e780)
	/Users/crawshaw/go/src/cmd/internal/gc/cgen.go:2087 +0x17f7
cmd/internal/gc.Bgen(0x208771180, 0x20877e900, 0x0, 0x20877e780)
	/Users/crawshaw/go/src/cmd/internal/gc/cgen.go:1765 +0x4e
cmd/internal/gc.gen(0x208770fc0)
	/Users/crawshaw/go/src/cmd/internal/gc/gen.go:928 +0xcec
cmd/internal/gc.Genlist(0x20873b620)
	/Users/crawshaw/go/src/cmd/internal/gc/gen.go:220 +0x37
cmd/internal/gc.compile(0x20876ba40)
	/Users/crawshaw/go/src/cmd/internal/gc/pgen.go:482 +0xba0
cmd/internal/gc.funccompile(0x20876ba40)
	/Users/crawshaw/go/src/cmd/internal/gc/dcl.go:1474 +0x1b3
cmd/internal/gc.Main()
	/Users/crawshaw/go/src/cmd/internal/gc/lex.go:464 +0x1ea7
main.main()
	/Users/crawshaw/go/src/cmd/6g/galign.go:126 +0x5f7
```

**Comment by josharian** [comment]
This is probably my fault. @crawshaw is it blocking you? If not, I will look in a week or two.

**Comment by crawshaw** [comment]
It's not blocking me, it just needs to be fixed before the release.

**Comment by minux** [comment]
The first CL that exhibits this problem is
https://golang.org/cl/7853

We probably should invest some energy into (re-)reviewing
that huge CL. It's also the one that breaks linux/ppc64.

**Comment by josharian** [comment]
Started.
