### ISSUE TITLE
cmd/link: panic: runtime error: index out of range

### ISSUE THREAD

**Issue by bradfitz** [golang/go#10718]
Noticed during a trybot run on `openbsd-386` at f09a660e:

https://storage.googleapis.com/go-build-log/98a8c347/openbsd-386-gce56_e093cb69.log

```
...
?   	cmd/pprof/internal/tempfile	[no test files]
?   	cmd/trace	[no test files]
?   	cmd/yacc	[no test files]

##### GOMAXPROCS=2 runtime -cpu=1,2,4
--- FAIL: TestGcSys-4 (0.58s)
	crash_test.go:92: building source: exit status 2
		# _/tmp/go-build672872450
		panic: runtime error: index out of range
		
		goroutine 1 [running]:
		cmd/internal/ld.getvarint(0x192adda8, 0x6f)
			/tmp/buildlet-scatch822141721/go/src/cmd/internal/ld/pcln.go:46 +0x11b
		cmd/internal/ld.pciternext(0x192add9c)
			/tmp/buildlet-scatch822141721/go/src/cmd/internal/ld/pcln.go:81 +0xea
		cmd/internal/ld.stkcheck(0x1866a950, 0x0, 0x0)
			/tmp/buildlet-scatch822141721/go/src/cmd/internal/ld/lib.go:1456 +0x437
		cmd/internal/ld.dostkcheck()
			/tmp/buildlet-scatch822141721/go/src/cmd/internal/ld/lib.go:1400 +0x1b9
		cmd/internal/ld.Ldmain()
			/tmp/buildlet-scatch822141721/go/src/cmd/internal/ld/pobj.go:226 +0x17d2
		main.main()
			/tmp/buildlet-scatch822141721/go/src/cmd/8l/obj.go:44 +0x1d
FAIL
FAIL	runtime	109.404s
2015/05/06 09:50:46 Failed: exit status 1

Error: src/all.bash failed: exit status 1
```

**Comment by rsc** [comment]
Unless this keeps happening, ascribing to fixed memory corruption.
