### ISSUE TITLE
build: plan9 broken by map element zero value change

### ISSUE THREAD

**Issue by bradfitz** [golang/go#10872]
The plan9 build was broken by 7e26a2d9a80b825d019c2cdaf6437d89001506a9 (runtime: allocate map element zero values for reflect-created types on demand)

```
--- FAIL: TestNM (1.41s)
	nm_test.go:102: go tool nm /tmp/go-build326333815/cmd/nm/_test/nm.test: exit status: 'testnm.exe 3841: 2'
		runtime: out of memory: cannot allocate 1820983296-byte block (1048576 in use)
		fatal error: out of memory
		
		runtime stack:
		runtime.throw(0x1b3f98, 0xd)
			/tmp/buildlet-scatch760636585/go/src/runtime/panic.go:527 +0x7e
		runtime.largeAlloc(0x6c89241c, 0x1, 0x2b)
			/tmp/buildlet-scatch760636585/go/src/runtime/malloc.go:718 +0xac
		runtime.mallocgc.func3()
			/tmp/buildlet-scatch760636585/go/src/runtime/malloc.go:631 +0x38
		runtime.systemstack(0x28a1d8)
			/tmp/buildlet-scatch760636585/go/src/runtime/asm_386.s:267 +0x56
		runtime.mstart()
			/tmp/buildlet-scatch760636585/go/src/runtime/proc1.go:682
		
		goroutine 1 [running]:
		runtime.systemstack_switch()
			/tmp/buildlet-scatch760636585/go/src/runtime/asm_386.s:222 fp=0x10457aac sp=0x10457aa8
		runtime.mallocgc(0x6c89241c, 0x12e440, 0x1, 0x304bc358)
			/tmp/buildlet-scatch760636585/go/src/runtime/malloc.go:632 +0x70a fp=0x10457b14 sp=0x10457aac
		runtime.newarray(0x12e440, 0x6c89241c, 0x0)
			/tmp/buildlet-scatch760636585/go/src/runtime/malloc.go:748 +0xae fp=0x10457b34 sp=0x10457b14
		runtime.makeslice(0x129100, 0x6c89241c, 0x0, 0x6c89241c, 0x0, 0x0, 0x0, 0x0)
			/tmp/buildlet-scatch760636585/go/src/runtime/slice.go:32 +0x148 fp=0x10457b60 sp=0x10457b34
		debug/pe.NewFile(0x304bc2c0, 0x103dc2d0, 0x4, 0x0, 0x0)
			/tmp/buildlet-scatch760636585/go/src/debug/pe/file.go:169 +0x69f fp=0x10457d40 sp=0x10457b60
		cmd/internal/objfile.openPE(0x103dc2d0, 0x0, 0x0, 0x0, 0x0)
			/tmp/buildlet-scatch760636585/go/src/cmd/internal/objfile/pe.go:21 +0x5f fp=0x10457d84 sp=0x10457d40
		cmd/internal/objfile.Open(0xdfffef8c, 0x2b, 0x75, 0x0, 0x0)
			/tmp/buildlet-scatch760636585/go/src/cmd/internal/objfile/objfile.go:53 +0xc3 fp=0x10457e00 sp=0x10457d84
		main.nm(0xdfffef8c, 0x2b)
			/tmp/buildlet-scatch760636585/go/src/cmd/nm/nm.go:89 +0x4d fp=0x10457f34 sp=0x10457e00
		main.main()
			/tmp/buildlet-scatch760636585/go/src/cmd/nm/nm.go:75 +0x1a3 fp=0x10457fc8 sp=0x10457f34
		runtime.main()
			/tmp/buildlet-scatch760636585/go/src/runtime/proc.go:111 +0x272 fp=0x10457ff0 sp=0x10457fc8
		runtime.goexit()
			/tmp/buildlet-scatch760636585/go/src/runtime/asm_386.s:1636 +0x1 fp=0x10457ff4 sp=0x10457ff0
FAIL
FAIL	cmd/nm	1.448s
ok  	cmd/objdump	1.910s
```

/cc @0intro

**Comment by bradfitz** [comment]
Dup of #10871 which @0intro filed at the same time as mine.
