### ISSUE TITLE
Is correct uusing select for sending to a closed channel?

### ISSUE THREAD

**Issue by denghongcai** [golang/go#11015]
```
func Publish(text string, pipe chan string) {
    for {
        pipe <- text
    }
}

func main() {
    pipe := make(chan string)
    go Publish("Channels let goroutines communicate.", pipe)
    fmt.Println("Waiting for the news...")
    for i := 0; i < 5; i++ {
        text := <-pipe
        fmt.Println(text)
    }
    close(pipe)
    fmt.Println("The news is out, time to leave.")
    time.Sleep(time.Second)
}
```
The code above will cause panic:
```
panic: send on closed channel

goroutine 5 [running]:
main.Publish(0x1443c8, 0x24, 0x1042e040, 0x0)
    /tmp/sandbox452988919/main.go:10 +0x60
created by main.main
    /tmp/sandbox452988919/main.go:16 +0xa0

goroutine 1 [sleep]:
main.main()
    /tmp/sandbox452988919/main.go:24 +0x3c0

goroutine 6 [runnable]:
runtime.timerproc()
    /usr/src/go/src/runtime/time.go:151
runtime.goexit()
    /usr/src/go/src/runtime/asm_amd64p32.s:1086 +0x1
```
Though this pattern has been discussed long time ago, I can't find a good solution.
To solve this problem but not using mutex, I have following code:
```
type Pipe struct {
    pipe   chan string
    closed chan bool
}

func Publish(text string, pipeStruct *Pipe) {
    for {
        select {
        case <-pipeStruct.closed:
            return
        case pipeStruct.pipe <- text:

        }

    }
}

func main() {
    pipeStruct := &Pipe{
        pipe:   make(chan string),
        closed: make(chan bool),
    }
    go Publish("Channels let goroutines communicate.", pipeStruct)
    fmt.Println("Waiting for the news...")
    for i := 0; i < 5; i++ {
        text := <-pipeStruct.pipe
        fmt.Println(text)
    }
    close(pipeStruct.closed)
    close(pipeStruct.pipe)
    fmt.Println("The news is out, time to leave.")
    time.Sleep(time.Second)
}
```
Seems work properly, but I do not know why. From the spec:
>If one or more of the communications can proceed, a single one that can proceed is chosen via a uniform pseudo-random selection. 

Due to `Random chosen`, I want to know why my solution work properly. Thanks.

**Comment by minux** [comment]
Your program contains a data race. Run it under the race
detector to see.

btw, please ask questions like this on the golang-nuts
mailing list.
