### ISSUE TITLE
runtime: TestStackOverflow panics on linux

### ISSUE THREAD

**Issue by davecheney** [golang/go#11049]
```
##### GOMAXPROCS=2 runtime -cpu=1,2,4
--- FAIL: TestStackOverflow (0.04s)
	crash_test.go:92: building source: exit status 2
		panic: runtime error: slice bounds out of range
		fatal error: panic on system stack
		
		runtime stack:
		runtime.throw(0x985d70, 0x15)
			/tmp/buildlet-scatch465833892/go/src/runtime/panic.go:527 +0x96
		runtime.gopanic(0x891b00, 0xc208010190)
			/tmp/buildlet-scatch465833892/go/src/runtime/panic.go:354 +0xbc
		runtime.panicslice()
			/tmp/buildlet-scatch465833892/go/src/runtime/panic.go:18 +0x50
		runtime.gcInstallStackBarrier(0xc20863c9a0, 0xc208033c78)
			/tmp/buildlet-scatch465833892/go/src/runtime/mgcmark.go:510 +0xb1
		runtime.scanstack.func1(0xc208033c78, 0x0, 0x1)
			/tmp/buildlet-scatch465833892/go/src/runtime/mgcmark.go:365 +0xa2
		runtime.gentraceback(0x6286a5, 0xc2080fca18, 0x0, 0xc20863c9a0, 0x0, 0x0, 0x7fffffff, 0xc208033d90, 0x0, 0x0, ...)
			/tmp/buildlet-scatch465833892/go/src/runtime/traceback.go:336 +0xa81
		runtime.scanstack(0xc20863c9a0)
			/tmp/buildlet-scatch465833892/go/src/runtime/mgcmark.go:380 +0x351
		runtime.gcphasework(0xc20863c9a0)
			/tmp/buildlet-scatch465833892/go/src/runtime/mgcmark.go:273 +0x70
		runtime.stopg(0xc20863c9a0, 0x3)
			/tmp/buildlet-scatch465833892/go/src/runtime/proc1.go:395 +0x91
		runtime.markroot(0xc208018000, 0xd)
			/tmp/buildlet-scatch465833892/go/src/runtime/mgcmark.go:138 +0x1f2
		runtime.parfordo(0xc208018000)
			/tmp/buildlet-scatch465833892/go/src/runtime/parfor.go:95 +0x12d
		runtime.gcscan_m()
			/tmp/buildlet-scatch465833892/go/src/runtime/mgcmark.go:37 +0xe1
		runtime.gc.func1()
			/tmp/buildlet-scatch465833892/go/src/runtime/mgc.go:843 +0x5f
		runtime.systemstack(0xc20801b500)
			/tmp/buildlet-scatch465833892/go/src/runtime/asm_amd64.s:262 +0x7c
		runtime.mstart()
			/tmp/buildlet-scatch465833892/go/src/runtime/proc1.go:656
		
		goroutine 21 [garbage collection scan]:
		runtime.systemstack_switch()
			/tmp/buildlet-scatch465833892/go/src/runtime/asm_amd64.s:216 fp=0xc2080204e8 sp=0xc2080204e0
		runtime.gc(0x0)
			/tmp/buildlet-scatch465833892/go/src/runtime/mgc.go:855 +0x1dc fp=0xc208020790 sp=0xc2080204e8
		runtime.backgroundgc()
			/tmp/buildlet-scatch465833892/go/src/runtime/mgc.go:775 +0x40 fp=0xc2080207c0 sp=0xc208020790
		runtime.goexit()
			/tmp/buildlet-scatch465833892/go/src/runtime/asm_amd64.s:1700 +0x1 fp=0xc2080207c8 sp=0xc2080207c0
		created by runtime.startGC
			/tmp/buildlet-scatch465833892/go/src/runtime/mgc.go:748 +0x14a
		
		goroutine 1 [semacquire]:
		sync.runtime_Semacquire(0xc208617360)
			/tmp/buildlet-scatch465833892/go/src/runtime/sema.go:43 +0x2d
		sync.(*WaitGroup).Wait(0xc2086495a0)
			/tmp/buildlet-scatch465833892/go/src/sync/waitgroup.go:132 +0x15d
		main.(*builder).do(0xc2081399d0, 0xc208112d00)
			/tmp/buildlet-scatch465833892/go/src/cmd/go/build.go:1153 +0x3c9
		main.runBuild(0xb90360, 0xc208056130, 0x0, 0x0)
			/tmp/buildlet-scatch465833892/go/src/cmd/go/build.go:441 +0x51f
		main.main()
			/tmp/buildlet-scatch465833892/go/src/cmd/go/main.go:177 +0x750
		
		goroutine 19 [syscall]:
		os/signal.loop()
			/tmp/buildlet-scatch465833892/go/src/os/signal/signal_unix.go:22 +0x1f
		created by os/signal.init.1
			/tmp/buildlet-scatch465833892/go/src/os/signal/signal_unix.go:28 +0x3e
		
		goroutine 23 [syscall]:
		syscall.Syscall(0x0, 0x6, 0xc2080fcae0, 0x8, 0x0, 0x8, 0x0)
			/tmp/buildlet-scatch465833892/go/src/syscall/asm_linux_amd64.s:18 +0x5
		syscall.readlen(0x6, 0xc2080fcae0, 0x8, 0xf, 0x0, 0x0)
			/tmp/buildlet-scatch465833892/go/src/syscall/zsyscall_linux_amd64.go:1085 +0x53
		syscall.forkExec(0xc20800a880, 0x3d, 0xc20866e0e0, 0xe, 0xe, 0xc2080fccb0, 0x15d4, 0x0, 0x0)
			/tmp/buildlet-scatch465833892/go/src/syscall/exec_unix.go:200 +0x56a
		syscall.StartProcess(0xc20800a880, 0x3d, 0xc20866e0e0, 0xe, 0xe, 0xc2080fccb0, 0x1, 0x4, 0x0, 0x0)
			/tmp/buildlet-scatch465833892/go/src/syscall/exec_unix.go:238 +0x6e
		os.startProcess(0xc20800a880, 0x3d, 0xc20866e0e0, 0xe, 0xe, 0xc2080fcee8, 0x90a160, 0x0, 0x0)
			/tmp/buildlet-scatch465833892/go/src/os/exec_posix.go:45 +0x33f
		os.StartProcess(0xc20800a880, 0x3d, 0xc20866e0e0, 0xe, 0xe, 0xc2080fcee8, 0x0, 0x0, 0x0)
			/tmp/buildlet-scatch465833892/go/src/os/doc.go:24 +0x6c
		os/exec.(*Cmd).Start(0xc208670000, 0x0, 0x0)
			/tmp/buildlet-scatch465833892/go/src/os/exec/exec.go:319 +0x76a
		os/exec.(*Cmd).Run(0xc208670000, 0x0, 0x0)
			/tmp/buildlet-scatch465833892/go/src/os/exec/exec.go:246 +0x34
		main.(*builder).runOut(0xc2081399d0, 0xc208127100, 0x16, 0xc208127080, 0x17, 0x0, 0x0, 0x0, 0xc20866c000, 0xd, ...)
			/tmp/buildlet-scatch465833892/go/src/cmd/go/build.go:1902 +0x334
		main.gcToolchain.gc(0xc2081399d0, 0xc208125400, 0xc208644b40, 0x30, 0xc20865e200, 0x34, 0xc208172600, 0xc20800e540, 0x2, 0x2, ...)
			/tmp/buildlet-scatch465833892/go/src/cmd/go/build.go:2146 +0xf1e
		main.(*gcToolchain).gc(0xbbcf70, 0xc2081399d0, 0xc208125400, 0xc208644b40, 0x30, 0xc20865e200, 0x34, 0x0, 0xc20800e540, 0x2, ...)
			<autogenerated>:3 +0x191
		main.(*builder).build(0xc2081399d0, 0xc208112d00, 0x0, 0x0)
			/tmp/buildlet-scatch465833892/go/src/cmd/go/build.go:1320 +0x2551
		main.(*builder).do.func1(0xc208112d00)
			/tmp/buildlet-scatch465833892/go/src/cmd/go/build.go:1087 +0x3bc
		main.(*builder).do.func2(0xc2086495a0, 0xc2081399d0, 0xc208649580)
			/tmp/buildlet-scatch465833892/go/src/cmd/go/build.go:1144 +0x158
		created by main.(*builder).do
			/tmp/buildlet-scatch465833892/go/src/cmd/go/build.go:1150 +0x3a1
		
		goroutine 24 [select]:
		main.(*builder).do.func2(0xc2086495a0, 0xc2081399d0, 0xc208649580)
			/tmp/buildlet-scatch465833892/go/src/cmd/go/build.go:1134 +0x1d1
		created by main.(*builder).do
			/tmp/buildlet-scatch465833892/go/src/cmd/go/build.go:1150 +0x3a1
FAIL
FAIL	runtime	25.490s
```

http://build.golang.org/log/de2894c6b3b2b342cb66bd859be2c197e8e641ad

/cc @aclements

**Comment by davecheney** [comment]
Several other similar crashes

http://build.golang.org/log/5e30bf30a0356f097ef7205c7c4e6ef0236c36fb
http://build.golang.org/log/9edf288793cf3b49eea17094be833872bc9c3171

**Comment by davecheney** [comment]
Previous failures were on linux/amd64, also spotted on linux/arm

http://build.golang.org/log/1cec4a0f83ab91bd50f5c6250f02a784e8000370
http://build.golang.org/log/9edf288793cf3b49eea17094be833872bc9c3171

**Comment by aclements** [comment]
This also happens on Solaris:
http://build.golang.org/log/bff4ec7a48a45672a4d43a03c416a3fd5fb8d74f

I'm able to reproduce this locally within a few minutes with
    GOMAXPROCS=2 stress ./runtime.test -test.run TestGCFairness -test.cpu 2 -test.v

If I can't track this down soon, I'll check in a work around (it's also fine to *not* install a stack barrier, so it can just return if it runs out of room in the slice), but I want to understand the actual issue here.
