### ISSUE TITLE
runtime: crash with "fatal error: runtime: sudog with non-nil selectdone"

### ISSUE THREAD

**Issue by rhysh** [golang/go#11042]
```
$ go version
go version devel +8cd191b Sat May 30 12:21:56 2015 +0000 linux/amd64
$ uname -a | awk '$2="host"'
Linux host 3.13.0-52-generic #86~precise1-Ubuntu SMP Tue May 5 18:08:21 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

I have a process that receives data over a few hundred concurrent TCP connections and writes them to files. It's been crashing on recent versions of tip (it was stable on 1.4.1).

I'm working on reproducing this (and the other recent crashes I've seen), I don't have a minimal test case or bisect yet. They may all be due to the same memory corruption bug.

```
fatal error: runtime: sudog with non-nil selectdone

goroutine 3476 [running]:
runtime.throw(0x8e1430, 0x26)
	/usr/local/go/src/runtime/panic.go:527 +0x96 fp=0xc208b4a4d8 sp=0xc208b4a4c0
runtime.releaseSudog(0xc20f958cc0)
	/usr/local/go/src/runtime/proc.go:244 +0x5f fp=0xc208b4a570 sp=0xc208b4a4d8
runtime.chansend(0x718740, 0xc2080c4240, 0xc208b4a7a0, 0xc209032001, 0x405abe, 0x1000)
	/usr/local/go/src/runtime/chan.go:243 +0x8e6 fp=0xc208b4a640 sp=0xc208b4a570
runtime.chansend1(0x718740, 0xc2080c4240, 0xc208b4a7a0)
	/usr/local/go/src/runtime/chan.go:92 +0x43 fp=0xc208b4a678 sp=0xc208b4a640
redacted(0xc2081280a0, 0x7ff4aea62a38, 0xc20b336978, 0xc2080c4240)
	/redacted.go:105 +0x25e fp=0xc208b4a7c0 sp=0xc208b4a678
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1670 +0x1 fp=0xc208b4a7c8 sp=0xc208b4a7c0
created by redacted
	/redacted.go:81 +0x21e

goroutine 1 [chan receive, 38 minutes]:
main.main()
	/redacted.go:230 +0xe7b

goroutine 5 [chan send]:
redacted(0xc2080ae000)
	/redacted.go:199 +0x1f0
created by redacted.init.1
	/redacted.go:184 +0x6e

[snip]
```

**Comment by methane** [comment]
This may be same to #10942 and some other runtime failure.

**Comment by rhysh** [comment]
I'm unable to reproduce this on 8fa1a69f0ba3d149f0697a1d3fd815d5f853485b (from 17 June 2015).

It looks like I was hitting the same set of bugs as are documented in #10941 (including most recently the "fatal error: g already has stack barriers" crash), but my app ran for several days on the 17 June version when it used to crash several times an hour.

This looks fixed to me.
