### ISSUE TITLE
x/mobile/example/sprite: crashes on Kubuntu

### ISSUE THREAD

**Issue by ainar-g** [golang/go#11066]
Go version:

    go version devel +2db587c Thu Jun 4 07:16:25 2015 +0000 linux/amd64

uname -a

    Linux in3678 3.13.0-53-generic #89-Ubuntu SMP Wed May 20 10:34:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

`go get -u golang.org/x/mobile/example/sprite` succeeds, sprite binary is put in the `${GOPATH}/bin`, but when I try to run it I get this:

```
libEGL warning: failed to create a pipe screen for i965
panic: runtime error: index out of range

goroutine 1 [running, locked to thread]:
golang.org/x/mobile/gl.TexSubImage2D(0xde1, 0x0, 0x0, 0x0, 0x1, 0x1, 0x140100001908, 0x0, 0x0, 0x0)
        /home/in3678-user/go/src/golang.org/x/mobile/gl/gl.go:1499 +0x125
golang.org/x/mobile/gl/glutil.(*Image).Upload(0xc20800a540)
        /home/in3678-user/go/src/golang.org/x/mobile/gl/glutil/glimage.go:208 +0x148
golang.org/x/mobile/app/debug.DrawFPS()
        /home/in3678-user/go/src/golang.org/x/mobile/app/debug/fps.go:70 +0x40b
main.draw()
        /home/in3678-user/go/src/golang.org/x/mobile/example/sprite/main.go:79 +0x1e9
golang.org/x/mobile/app.onDraw()
        /home/in3678-user/go/src/golang.org/x/mobile/app/x11.go:104 +0x30f
golang.org/x/mobile/app._Cfunc_eventLoop()
        golang.org/x/mobile/app/_obj/_cgo_gotypes.go:45 +0x38
golang.org/x/mobile/app.run(0xc20808a000, 0x2, 0x3)
        /home/in3678-user/go/src/golang.org/x/mobile/app/x11.go:45 +0x11f
golang.org/x/mobile/app.Run(0x0, 0x0, 0x5f2598, 0x5f25a0, 0x0)
        /home/in3678-user/go/src/golang.org/x/mobile/app/app.go:26 +0x95
main.main()
        /home/in3678-user/go/src/golang.org/x/mobile/example/sprite/main.go:59 +0x60

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /home/in3678-user/go/go-tip/src/runtime/asm_amd64.s:1700 +0x1

goroutine 5 [runnable, locked to thread]:
golang.org/x/mobile/gl.Start(0x5f24d8)
        /home/in3678-user/go/src/golang.org/x/mobile/gl/work.go:85 +0x146
created by golang.org/x/mobile/app.run
        /home/in3678-user/go/src/golang.org/x/mobile/app/x11.go:41 +0xe2
```

After some debugging, I've found out that this happens because `geom.PixelsPerPt` doesn't get set. If I add

    geom.PixelsPerPt = 1

in `fpsInit`, it works. I only get this on my Kubuntu 14.04 machine. When I try to reproduce in on Ubuntu 14.04, everything works fine. This might be due to "libEGL warning: failed to create a pipe screen for i965", or the fact that `geom.PixelsPerPt` on linux doesn't get set anywhere except for `onResize`, or both.

**Comment by rakyll** [comment]
cc/ @crawshaw @nigeltao

**Comment by nigeltao** [comment]
When you say that it works fine on Ubuntu, what graphics chip does your Ubuntu machine have? Run "lspci | grep VGA" in a terminal and copy/paste the output here, please.

**Comment by nigeltao** [comment]
It's possibly the racy bug introduced in git commit 019f8eb658 aka https://go-review.googlesource.com/10623 which fixed the linux/X11 breakage in git commit 068a51c195 aka https://go-review.googlesource.com/10452 which changed the app/gl threading model.

If you sync back to git commit 0d468be861, are you still broken on your Kubuntu machine? Does your Ubuntu machine still work?

**Comment by ainar-g** [comment]
On Ubuntu machine:

```
$ lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 09)
```

Also, I get the libEGL warning on Ubuntu as well. On Kubuntu machine:

```
$ lspci | grep VGA
0:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)
```

`git checkout 0d468be861 && go install && sprite` works on Ubuntu machine, but on Kubuntu it still crashes. I've also applied https://golang.org/cl/10744 to master, but that doesn't fix it either. Moving the `geom.PixelsPerPt` check from `onResize` to `onDraw` makes it work on Kubuntu, but I don't know if that's a good solution.

**Comment by ainar-g** [comment]
Another interesting thing. I tried to rebuild it with the race detector enabled. The binary still crashed, but with a different stack trace:

```
$ go install -a -race && sprite 
libEGL warning: failed to create a pipe screen for i965
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x0 pc=0x4158a5]

runtime stack:
runtime.throw(0x67fc90, 0x2a)
        /home/in3678-user/go/go-tip/src/runtime/panic.go:527 +0x96
runtime.sigpanic()
        /home/in3678-user/go/go-tip/src/runtime/sigpanic_unix.go:12 +0x5d

goroutine 1 [syscall, locked to thread]:
runtime.cgocall_errno(0x430400, 0xc208051e78, 0x0)
        /home/in3678-user/go/go-tip/src/runtime/cgocall.go:125 +0xc5 fp=0xc208051e58 sp=0xc208051e30
golang.org/x/mobile/app._Cfunc_eventLoop()
        golang.org/x/mobile/app/_obj/_cgo_gotypes.go:45 +0x56 fp=0xc208051e78 sp=0xc208051e58
golang.org/x/mobile/app.run(0xc20801a230, 0x2, 0x2)
        /home/in3678-user/go/src/golang.org/x/mobile/app/x11.go:45 +0xef fp=0xc208051e98 sp=0xc208051e78
golang.org/x/mobile/app.Run(0x0, 0x0, 0x69ce58, 0x69ce60, 0x0)
        /home/in3678-user/go/src/golang.org/x/mobile/app/app.go:26 +0x186 fp=0xc208051f00 sp=0xc208051e98
main.main()
        /home/in3678-user/go/src/golang.org/x/mobile/example/sprite/main.go:59 +0x6e fp=0xc208051f58 sp=0xc208051f00
runtime.main()
        /home/in3678-user/go/go-tip/src/runtime/proc.go:111 +0x250 fp=0xc208051fa0 sp=0xc208051f58
runtime.goexit()
        /home/in3678-user/go/go-tip/src/runtime/asm_amd64.s:1700 +0x1 fp=0xc208051fa8 sp=0xc208051fa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /home/in3678-user/go/go-tip/src/runtime/asm_amd64.s:1700 +0x1

goroutine 5 [chan receive, locked to thread]:
golang.org/x/mobile/gl.Start(0x69cd98)
        /home/in3678-user/go/src/golang.org/x/mobile/gl/work.go:85 +0x118
created by golang.org/x/mobile/app.run
        /home/in3678-user/go/src/golang.org/x/mobile/app/x11.go:41 +0x92
```

**Comment by ainar-g** [comment]
Patch set 4 of https://golang.org/cl/10744 fixes it on Kubuntu.
