### ISSUE TITLE
runtime: darwin/arm64 panics with slice bounds out of range error

### ISSUE THREAD

**Issue by rakyll** [golang/go#11085]
Not consistently reproducible, but make.bash occasionally panics with slice bounds out of range error.

```
$ CGO_ENABLED=1 GOARCH=arm64 CC_FOR_TARGET=`pwd`/../misc/ios/clangwrap.sh CXX_FOR_TARGET=`pwd`/../misc/ios/clangwrap.sh ./make.bash

##### Building packages and commands for host, darwin/amd64.
runtime
errors
sync/atomic
unicode
unicode/utf8
math
sort
container/list
container/ring
crypto/subtle
encoding
unicode/utf16
sync
image/color
runtime/race
cmd/vet/whitelist
container/heap
image/color/palette
io
syscall
internal/singleflight
hash
crypto/cipher
hash/crc32
hash/adler32
crypto/hmac
hash/crc64
hash/fnv
bytes
strings
bufio
text/tabwriter
panic: runtime error: slice bounds out of range
fatal error: panic on system stack
time

runtime stack:
runtime.throw(0x387e70, 0x15)
  /Users/jbd/go/src/runtime/panic.go:527 +0x96
runtime.gopanic(0x2e6460, 0x20856c100)
  /Users/jbd/go/src/runtime/panic.go:354 +0xb9
runtime.panicslice()
  /Users/jbd/go/src/runtime/panic.go:18 +0x49
runtime.gcInstallStackBarrier(0x208735340, 0x208aa5c78)
  /Users/jbd/go/src/runtime/mgcmark.go:510 +0xae
runtime.scanstack.func1(0x208aa5c78, 0x0, 0x1)
  /Users/jbd/go/src/runtime/mgcmark.go:365 +0x9f
runtime.gentraceback(0x1c3385, 0x208acad48, 0x0, 0x208735340, 0x0, 0x0, 0x7fffffff, 0x208aa5d90, 0x0, 0x0, ...)
  /Users/jbd/go/src/runtime/traceback.go:336 +0xa7e
runtime.scanstack(0x208735340)
  /Users/jbd/go/src/runtime/mgcmark.go:380 +0x34e
runtime.gcphasework(0x208735340)
  /Users/jbd/go/src/runtime/mgcmark.go:273 +0x6d
runtime.stopg(0x208735340, 0x3)
  /Users/jbd/go/src/runtime/proc1.go:395 +0x8e
runtime.markroot(0x2085760c0, 0x15)
  /Users/jbd/go/src/runtime/mgcmark.go:138 +0x1ef
runtime.parfordo(0x2085760c0)
  /Users/jbd/go/src/runtime/parfor.go:95 +0x12a
runtime.gcscan_m()
  /Users/jbd/go/src/runtime/mgcmark.go:37 +0xde
runtime.gc.func1()
  /Users/jbd/go/src/runtime/mgc.go:843 +0x5c
runtime.systemstack(0x208585500)
  /Users/jbd/go/src/runtime/asm_amd64.s:262 +0x7c
runtime.mstart()
  /Users/jbd/go/src/runtime/proc1.go:656

goroutine 17 [garbage collection scan]:
runtime.systemstack_switch()
  /Users/jbd/go/src/runtime/asm_amd64.s:216 fp=0x2085884e8 sp=0x2085884e0
runtime.gc(0x0)
  /Users/jbd/go/src/runtime/mgc.go:855 +0x1d9 fp=0x208588790 sp=0x2085884e8
runtime.backgroundgc()
  /Users/jbd/go/src/runtime/mgc.go:775 +0x3d fp=0x2085887c0 sp=0x208588790
runtime.goexit()
  /Users/jbd/go/src/runtime/asm_amd64.s:1700 +0x1 fp=0x2085887c8 sp=0x2085887c0
created by runtime.startGC
  /Users/jbd/go/src/runtime/mgc.go:748 +0x147

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0x20893a430)
  /Users/jbd/go/src/runtime/sema.go:43 +0x26
sync.(*WaitGroup).Wait(0x20890cfa0)
  /Users/jbd/go/src/sync/waitgroup.go:132 +0x15a
main.(*builder).do(0x208640850, 0x20880e750)
  /Users/jbd/go/src/cmd/go/build.go:1177 +0x3c6
main.runInstall(0x4e04a0, 0x208568100, 0x2, 0x2)
  /Users/jbd/go/src/cmd/go/build.go:542 +0x324
main.main()
  /Users/jbd/go/src/cmd/go/main.go:177 +0x74d

goroutine 5 [syscall]:
os/signal.loop()
  /Users/jbd/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
  /Users/jbd/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 7 [select]:
main.(*builder).do.func2(0x20890cfa0, 0x208640850, 0x20890cf80)
  /Users/jbd/go/src/cmd/go/build.go:1158 +0x1ce
created by main.(*builder).do
  /Users/jbd/go/src/cmd/go/build.go:1174 +0x39e

goroutine 8 [syscall]:
syscall.Syscall(0x5, 0x208b8f980, 0x1000000, 0x0, 0x3, 0x0, 0x0)
  /Users/jbd/go/src/syscall/asm_darwin_amd64.s:16 +0x5
syscall.Open(0x208b8f500, 0x59, 0x1000000, 0x200000000, 0x0, 0x0, 0x0)
  /Users/jbd/go/src/syscall/zsyscall_darwin_amd64.go:903 +0xa0
os.OpenFile(0x208b8f500, 0x59, 0x0, 0x0, 0x0, 0x0, 0x0)
  /Users/jbd/go/src/os/file_unix.go:93 +0x122
os.Open(0x208b8f500, 0x59, 0x200, 0x0, 0x0)
  /Users/jbd/go/src/os/file.go:246 +0x4a
io/ioutil.ReadFile(0x208b8f500, 0x59, 0x0, 0x0, 0x0, 0x0, 0x0)
  /Users/jbd/go/src/io/ioutil/ioutil.go:50 +0x69
main.toolVerify(0x208640850, 0x208a72c00, 0x352340, 0x5, 0x208b8f500, 0x59, 0x208acb2b8, 0x10, 0x10, 0x0, ...)
  /Users/jbd/go/src/cmd/go/build.go:2223 +0x30c
main.gcToolchain.asm(0x208640850, 0x208a72c00, 0x2089234a0, 0x50, 0x208b8f500, 0x59, 0x208bb49c0, 0x23, 0x0, 0x0)
  /Users/jbd/go/src/cmd/go/build.go:2205 +0xbdf
main.(*gcToolchain).asm(0x50a178, 0x208640850, 0x208a72c00, 0x2089234a0, 0x50, 0x208b8f500, 0x59, 0x20875ef4a, 0x9, 0x0, ...)
  <autogenerated>:4 +0xfb
main.(*builder).build(0x208640850, 0x20885ef70, 0x0, 0x0)
  /Users/jbd/go/src/cmd/go/build.go:1396 +0x32a1
main.(*builder).do.func1(0x20885ef70)
  /Users/jbd/go/src/cmd/go/build.go:1111 +0x3b9
main.(*builder).do.func2(0x20890cfa0, 0x208640850, 0x20890cf80)
  /Users/jbd/go/src/cmd/go/build.go:1168 +0x155
created by main.(*builder).do
  /Users/jbd/go/src/cmd/go/build.go:1174 +0x39e

goroutine 9 [runnable]:
main.(*builder).do.func2(0x20890cfa0, 0x208640850, 0x20890cf80)
  /Users/jbd/go/src/cmd/go/build.go:1158 +0x1ce
created by main.(*builder).do
  /Users/jbd/go/src/cmd/go/build.go:1174 +0x39e

goroutine 10 [runnable]:
syscall.Syscall6(0x7, 0x16c86, 0x208ac8d84, 0x0, 0x2089a8e10, 0x0, 0x0, 0x16c86, 0x0, 0x0)
  /Users/jbd/go/src/syscall/asm_darwin_amd64.s:41 +0x5
syscall.wait4(0x16c86, 0x208ac8d84, 0x0, 0x2089a8e10, 0x90, 0x0, 0x0)
  /Users/jbd/go/src/syscall/zsyscall_darwin_amd64.go:34 +0x72
syscall.Wait4(0x16c86, 0x208ac8dcc, 0x0, 0x2089a8e10, 0x2087a8080, 0x0, 0x0)
  /Users/jbd/go/src/syscall/syscall_bsd.go:129 +0x55
os.(*Process).wait(0x208a10460, 0x35, 0x0, 0x0)
  /Users/jbd/go/src/os/exec_unix.go:22 +0x105
os.(*Process).Wait(0x208a10460, 0x0, 0x0, 0x0)
  /Users/jbd/go/src/os/doc.go:45 +0x2d
os/exec.(*Cmd).Wait(0x2087e8280, 0x0, 0x0)
  /Users/jbd/go/src/os/exec/exec.go:367 +0x211
os/exec.(*Cmd).Run(0x2087e8280, 0x0, 0x0)
  /Users/jbd/go/src/os/exec/exec.go:249 +0x64
main.(*builder).runOut(0x208640850, 0x2087aa140, 0x20, 0x2086a17d1, 0xe, 0x0, 0x0, 0x0, 0x20882c480, 0xd, ...)
  /Users/jbd/go/src/cmd/go/build.go:1926 +0x331
main.gcToolchain.gc(0x208640850, 0x208816000, 0x20883dc20, 0x53, 0x20883db60, 0x57, 0x208571100, 0x208827fe0, 0x2, 0x2, ...)
  /Users/jbd/go/src/cmd/go/build.go:2173 +0xfdf
main.(*gcToolchain).gc(0x50a178, 0x208640850, 0x208816000, 0x20883dc20, 0x53, 0x20883db60, 0x57, 0x0, 0x208827fe0, 0x2, ...)
  <autogenerated>:3 +0x18e
main.(*builder).build(0x208640850, 0x2085ba8f0, 0x0, 0x0)
  /Users/jbd/go/src/cmd/go/build.go:1344 +0x254e
main.(*builder).do.func1(0x2085ba8f0)
  /Users/jbd/go/src/cmd/go/build.go:1111 +0x3b9
main.(*builder).do.func2(0x20890cfa0, 0x208640850, 0x20890cf80)
  /Users/jbd/go/src/cmd/go/build.go:1168 +0x155
created by main.(*builder).do
  /Users/jbd/go/src/cmd/go/build.go:1174 +0x39e

goroutine 11 [syscall]:
syscall.Syscall6(0x7, 0x16c85, 0x208a8ad84, 0x0, 0x208b8b5f0, 0x0, 0x0, 0x208a8ad58, 0x208a8ad60, 0x208a8ad50)
  /Users/jbd/go/src/syscall/asm_darwin_amd64.s:41 +0x5
syscall.wait4(0x16c85, 0x208a8ad84, 0x0, 0x208b8b5f0, 0x90, 0x0, 0x0)
  /Users/jbd/go/src/syscall/zsyscall_darwin_amd64.go:34 +0x72
syscall.Wait4(0x16c85, 0x208a8adcc, 0x0, 0x208b8b5f0, 0x208af8238, 0x0, 0x0)
  /Users/jbd/go/src/syscall/syscall_bsd.go:129 +0x55
os.(*Process).wait(0x2087abfc0, 0x35, 0x0, 0x0)
  /Users/jbd/go/src/os/exec_unix.go:22 +0x105
os.(*Process).Wait(0x2087abfc0, 0x0, 0x0, 0x0)
  /Users/jbd/go/src/os/doc.go:45 +0x2d
os/exec.(*Cmd).Wait(0x208b04f00, 0x0, 0x0)
  /Users/jbd/go/src/os/exec/exec.go:367 +0x211
os/exec.(*Cmd).Run(0x208b04f00, 0x0, 0x0)
  /Users/jbd/go/src/os/exec/exec.go:249 +0x64
main.(*builder).runOut(0x208640850, 0x20890d720, 0x17, 0x2087646c1, 0x5, 0x0, 0x0, 0x0, 0x208851680, 0xe, ...)
  /Users/jbd/go/src/cmd/go/build.go:1926 +0x331
main.gcToolchain.gc(0x208640850, 0x208a73800, 0x208868140, 0x4a, 0x2088680a0, 0x4e, 0x208571100, 0x2087ab980, 0x2, 0x2, ...)
  /Users/jbd/go/src/cmd/go/build.go:2173 +0xfdf
main.(*gcToolchain).gc(0x50a178, 0x208640850, 0x208a73800, 0x208868140, 0x4a, 0x2088680a0, 0x4e, 0x0, 0x2087ab980, 0x2, ...)
  <autogenerated>:3 +0x18e
main.(*builder).build(0x208640850, 0x20885f5f0, 0x0, 0x0)
  /Users/jbd/go/src/cmd/go/build.go:1344 +0x254e
main.(*builder).do.func1(0x20885f5f0)
  /Users/jbd/go/src/cmd/go/build.go:1111 +0x3b9
main.(*builder).do.func2(0x20890cfa0, 0x208640850, 0x20890cf80)
  /Users/jbd/go/src/cmd/go/build.go:1168 +0x155
created by main.(*builder).do
  /Users/jbd/go/src/cmd/go/build.go:1174 +0x39e

goroutine 12 [runnable]:
main.(*builder).do.func2(0x20890cfa0, 0x208640850, 0x20890cf80)
  /Users/jbd/go/src/cmd/go/build.go:1158 +0x1ce
created by main.(*builder).do
  /Users/jbd/go/src/cmd/go/build.go:1174 +0x39e

goroutine 13 [runnable]:
syscall.Syscall(0x152, 0x2087257c0, 0x208a3af30, 0x0, 0xffffffffffffffff, 0x0, 0x2)
  /Users/jbd/go/src/syscall/asm_darwin_amd64.s:16 +0x5
syscall.Stat(0x2085b9db0, 0x4d, 0x208a3af30, 0x0, 0x0)
  /Users/jbd/go/src/syscall/zsyscall_darwin_amd64.go:1223 +0x8b
os.Stat(0x2085b9db0, 0x4d, 0x0, 0x0, 0x0, 0x0)
  /Users/jbd/go/src/os/file_unix.go:154 +0x6a
os.MkdirAll(0x2085b9db0, 0x4d, 0x2000001ff, 0x0, 0x0)
  /Users/jbd/go/src/os/path.go:21 +0x4f
main.(*builder).mkdir(0x208640850, 0x2085b9db0, 0x4d, 0x0, 0x0)
  /Users/jbd/go/src/cmd/go/build.go:2024 +0x1aa
main.(*builder).build(0x208640850, 0x20885e4e0, 0x0, 0x0)
  /Users/jbd/go/src/cmd/go/build.go:1230 +0xac0
main.(*builder).do.func1(0x20885e4e0)
  /Users/jbd/go/src/cmd/go/build.go:1111 +0x3b9
main.(*builder).do.func2(0x20890cfa0, 0x208640850, 0x20890cf80)
  /Users/jbd/go/src/cmd/go/build.go:1168 +0x155
created by main.(*builder).do
  /Users/jbd/go/src/cmd/go/build.go:1174 +0x39e

goroutine 14 [runnable]:
syscall.Syscall6(0x7, 0x16c91, 0x208acec44, 0x0, 0x208bfe2d0, 0x0, 0x0, 0x16c91, 0x0, 0x0)
  /Users/jbd/go/src/syscall/asm_darwin_amd64.s:41 +0x5
syscall.wait4(0x16c91, 0x208acec44, 0x0, 0x208bfe2d0, 0x90, 0x0, 0x0)
  /Users/jbd/go/src/syscall/zsyscall_darwin_amd64.go:34 +0x72
syscall.Wait4(0x16c91, 0x208acec8c, 0x0, 0x208bfe2d0, 0x2085b64c0, 0x0, 0x0)
  /Users/jbd/go/src/syscall/syscall_bsd.go:129 +0x55
os.(*Process).wait(0x208736300, 0x35, 0x0, 0x0)
  /Users/jbd/go/src/os/exec_unix.go:22 +0x105
os.(*Process).Wait(0x208736300, 0x0, 0x0, 0x0)
  /Users/jbd/go/src/os/doc.go:45 +0x2d
os/exec.(*Cmd).Wait(0x208bf8140, 0x0, 0x0)
  /Users/jbd/go/src/os/exec/exec.go:367 +0x211
os/exec.(*Cmd).Run(0x208bf8140, 0x0, 0x0)
  /Users/jbd/go/src/os/exec/exec.go:249 +0x64
main.(*builder).runOut(0x208640850, 0x208797420, 0x16, 0x20863dec1, 0x4, 0x0, 0x0, 0x0, 0x208acf2b8, 0x10, ...)
  /Users/jbd/go/src/cmd/go/build.go:1926 +0x331
main.(*builder).run(0x208640850, 0x208797420, 0x16, 0x20863dec1, 0x4, 0x0, 0x0, 0x0, 0x208acf2b8, 0x10, ...)
  /Users/jbd/go/src/cmd/go/build.go:1871 +0xd9
main.gcToolchain.asm(0x208640850, 0x208a8c800, 0x2085b9540, 0x4d, 0x208bdca20, 0x5a, 0x208bfc150, 0x24, 0x0, 0x0)
  /Users/jbd/go/src/cmd/go/build.go:2187 +0xa30
main.(*gcToolchain).asm(0x50a178, 0x208640850, 0x208a8c800, 0x2085b9540, 0x4d, 0x208bdca20, 0x5a, 0x208843547, 0xd, 0x0, ...)
  <autogenerated>:4 +0xfb
main.(*builder).build(0x208640850, 0x20885e000, 0x0, 0x0)
  /Users/jbd/go/src/cmd/go/build.go:1396 +0x32a1
main.(*builder).do.func1(0x20885e000)
  /Users/jbd/go/src/cmd/go/build.go:1111 +0x3b9
main.(*builder).do.func2(0x20890cfa0, 0x208640850, 0x20890cf80)
  /Users/jbd/go/src/cmd/go/build.go:1168 +0x155
created by main.(*builder).do
  /Users/jbd/go/src/cmd/go/build.go:1174 +0x39e

goroutine 83 [runnable]:
syscall.Syscall(0x3, 0x6, 0x208762e00, 0x200, 0x0, 0x0, 0x0)
  /Users/jbd/go/src/syscall/asm_darwin_amd64.s:16 +0x5
syscall.read(0x6, 0x208762e00, 0x200, 0x200, 0x0, 0x0, 0x0)
  /Users/jbd/go/src/syscall/zsyscall_darwin_amd64.go:972 +0x5f
syscall.Read(0x6, 0x208762e00, 0x200, 0x200, 0x208589d00, 0x0, 0x0)
  /Users/jbd/go/src/syscall/syscall_unix.go:160 +0x4d
os.(*File).read(0x2087a8078, 0x208762e00, 0x200, 0x200, 0x208762e00, 0x0, 0x0)
  /Users/jbd/go/src/os/file_unix.go:211 +0x75
os.(*File).Read(0x2087a8078, 0x208762e00, 0x200, 0x200, 0x1, 0x0, 0x0)
  /Users/jbd/go/src/os/file.go:95 +0x8a
bytes.(*Buffer).ReadFrom(0x20865c310, 0x2208750530, 0x2087a8078, 0x0, 0x0, 0x0)
  /Users/jbd/go/src/bytes/buffer.go:173 +0x23f
io.copyBuffer(0x2208790900, 0x20865c310, 0x2208750530, 0x2087a8078, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
  /Users/jbd/go/src/io/io.go:375 +0x180
io.Copy(0x2208790900, 0x20865c310, 0x2208750530, 0x2087a8078, 0x0, 0x0, 0x0)
  /Users/jbd/go/src/io/io.go:351 +0x64
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
  /Users/jbd/go/src/os/exec/exec.go:224 +0x80
os/exec.(*Cmd).Start.func1(0x208a10100, 0x2087e8280)
  /Users/jbd/go/src/os/exec/exec.go:331 +0x1d
created by os/exec.(*Cmd).Start
  /Users/jbd/go/src/os/exec/exec.go:332 +0x96d

goroutine 123 [syscall]:
syscall.Syscall(0x3, 0x9, 0x208b94600, 0x200, 0x0, 0x0, 0x8e179)
  /Users/jbd/go/src/syscall/asm_darwin_amd64.s:16 +0x5
syscall.read(0x9, 0x208b94600, 0x200, 0x200, 0x0, 0x0, 0x0)
  /Users/jbd/go/src/syscall/zsyscall_darwin_amd64.go:972 +0x5f
syscall.Read(0x9, 0x208b94600, 0x200, 0x200, 0x208b71500, 0x0, 0x0)
  /Users/jbd/go/src/syscall/syscall_unix.go:160 +0x4d
os.(*File).read(0x208af8230, 0x208b94600, 0x200, 0x200, 0x208b94600, 0x0, 0x0)
  /Users/jbd/go/src/os/file_unix.go:211 +0x75
os.(*File).Read(0x208af8230, 0x208b94600, 0x200, 0x200, 0x1, 0x0, 0x0)
  /Users/jbd/go/src/os/file.go:95 +0x8a
bytes.(*Buffer).ReadFrom(0x208afd2d0, 0x2208750530, 0x208af8230, 0x0, 0x0, 0x0)
  /Users/jbd/go/src/bytes/buffer.go:173 +0x23f
io.copyBuffer(0x2208790900, 0x208afd2d0, 0x2208750530, 0x208af8230, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
  /Users/jbd/go/src/io/io.go:375 +0x180
io.Copy(0x2208790900, 0x208afd2d0, 0x2208750530, 0x208af8230, 0x0, 0x0, 0x0)
  /Users/jbd/go/src/io/io.go:351 +0x64
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
  /Users/jbd/go/src/os/exec/exec.go:224 +0x80
os/exec.(*Cmd).Start.func1(0x2087abba0, 0x208b04f00)
  /Users/jbd/go/src/os/exec/exec.go:331 +0x1d
created by os/exec.(*Cmd).Start
  /Users/jbd/go/src/os/exec/exec.go:332 +0x96d

goroutine 156 [runnable]:
syscall.Syscall(0x3, 0x4, 0x208bcd000, 0x200, 0x0, 0x0, 0x0)
  /Users/jbd/go/src/syscall/asm_darwin_amd64.s:16 +0x5
syscall.read(0x4, 0x208bcd000, 0x200, 0x200, 0x0, 0x0, 0x0)
  /Users/jbd/go/src/syscall/zsyscall_darwin_amd64.go:972 +0x5f
syscall.Read(0x4, 0x208bcd000, 0x200, 0x200, 0x208be5500, 0x0, 0x0)
  /Users/jbd/go/src/syscall/syscall_unix.go:160 +0x4d
os.(*File).read(0x2085b64b8, 0x208bcd000, 0x200, 0x200, 0x208bcd000, 0x0, 0x0)
  /Users/jbd/go/src/os/file_unix.go:211 +0x75
os.(*File).Read(0x2085b64b8, 0x208bcd000, 0x200, 0x200, 0x0, 0x0, 0x0)
  /Users/jbd/go/src/os/file.go:95 +0x8a
bytes.(*Buffer).ReadFrom(0x208bee2a0, 0x2208750530, 0x2085b64b8, 0x0, 0x0, 0x0)
  /Users/jbd/go/src/bytes/buffer.go:173 +0x23f
io.copyBuffer(0x2208790900, 0x208bee2a0, 0x2208750530, 0x2085b64b8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
  /Users/jbd/go/src/io/io.go:375 +0x180
io.Copy(0x2208790900, 0x208bee2a0, 0x2208750530, 0x2085b64b8, 0x0, 0x0, 0x0)
  /Users/jbd/go/src/io/io.go:351 +0x64
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
  /Users/jbd/go/src/os/exec/exec.go:224 +0x80
os/exec.(*Cmd).Start.func1(0x208775e60, 0x208bf8140)
  /Users/jbd/go/src/os/exec/exec.go:331 +0x1d
created by os/exec.(*Cmd).Start
  /Users/jbd/go/src/os/exec/exec.go:332 +0x96d
```

**Comment by bradfitz** [comment]
Dup of #11049
