### ISSUE TITLE
x/mobile: apps crash on darwin/arm64 at draw_arrays(__GLIContextRec*, unsigned int, int, int)

### ISSUE THREAD

**Issue by rakyll** [golang/go#11086]
Apps crash on darwin/arm at draw_arrays(__GLIContextRec*, unsigned int, int, int) slightly after the launch. It usually takes 3-4 seconds for me to see the EXC_BAD_ACCESS.

I am packing the arm64 binary in a lipo file, my build steps are available for inspection at https://github.com/rakyll/go-xcode/blob/master/Makefile.

```
#0  0x00000001829ef064 in ___lldb_unnamed_function235$$AGXGLDriver ()
#1  0x00000001829eecf0 in agxuBeginRenderCommand(AGXContextRec*, unsigned int, bool, bool) ()
#2  0x00000001829e5bbc in glrAGXRenderVertexArray(GLDContextRec*, unsigned int, unsigned int, int, int, unsigned int, void const*, int, void const*) ()
#3  0x0000000187f90e58 in glDrawArrays_ACC_ES2Exec ()
#4  0x0000000004509b64 in draw_arrays(__GLIContextRec*, unsigned int, int, int) ()
#5  0x00000000040dce9c in _cgo_80207b16a855_Cfunc_process ()
#6  0x0000000004138dd0 in asmcgocall ()
#7  0x00000000040de178 in threadentry ()
#8  0x0000000196317dc8 in _pthread_body ()
#9  0x0000000196317d24 in _pthread_start ()
```

/cc @crawshaw @hyangah @nigeltao @minux

**Comment by crawshaw** [comment]
go install -tags lldb runtime/cgo
then go build -tags lldb
that should let you see a panic when running under lldb

**Comment by rakyll** [comment]
Neat!

```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x0 pc=0x182a227a4]

runtime stack:
runtime.throw(0x421a470, 0x2a)
	/Users/jbd/go/src/runtime/panic.go:527 +0x80
runtime.sigpanic()
	/Users/jbd/go/src/runtime/sigpanic_unix.go:12 +0x50

goroutine 5 [syscall, locked to thread]:
runtime.cgocall_errno(0x404487c, 0xe5bbe18, 0x0)
	/Users/jbd/go/src/runtime/cgocall.go:125 +0x150 fp=0xe5bbdf0 sp=0xe5bbdc0
golang.org/x/mobile/gl._Cfunc_process(0x1)
	??:0 +0x30 fp=0xe5bbe10 sp=0xe5bbdf0
golang.org/x/mobile/gl.Start(0xe5a64a0)
	/Users/jbd/src/golang.org/x/mobile/gl/work.go:109 +0x4d4 fp=0xe5bbfb0 sp=0xe5bbe10
runtime.goexit()
	/Users/jbd/go/src/runtime/asm_arm64.s:1021 +0x4 fp=0xe5bbfb0 sp=0xe5bbfb0
created by golang.org/x/mobile/app.drawgl
	/Users/jbd/src/golang.org/x/mobile/app/darwin_armx.go:184 +0x84

goroutine 1 [syscall, locked to thread]:
golang.org/x/mobile/app._Cfunc_runApp()
	??:0 +0x30
golang.org/x/mobile/app.run(0xe62a000, 0x2, 0x3)
	/Users/jbd/src/golang.org/x/mobile/app/darwin_armx.go:55 +0x1b8
golang.org/x/mobile/app.Run(0x422c6b0, 0x422c6b8, 0x422c6a8, 0x422c6c0, 0x0)
	/Users/jbd/src/golang.org/x/mobile/app/app.go:26 +0x114
main.main()
	/Users/jbd/src/golang.org/x/mobile/example/basic/main.go:59 +0x64

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/Users/jbd/go/src/runtime/asm_arm64.s:1021 +0x4
```
