### ISSUE TITLE
cmd/go: panic: runtime error: slice bounds out of range in disallowInternal

### ISSUE THREAD

**Issue by ebfe** [golang/go#11201]
$ go version
    go version devel +a1fe3b5 Sat Jun 13 04:33:26 2015 +0000 linux/amd64

    $ go get github.com/gonum/floats
    panic: runtime error: slice bounds out of range
    
    goroutine 1 [running]:
    main.disallowInternal(0xc20811b3e0, 0x26, 0xc20815ac00, 0xc208135b90, 0x2)
            .../go/src/cmd/go/pkg.go:349 +0x484
    main.loadImport(0xc20813b581, 0x1d, 0xc20811b3e0, 0x26, 0xc208135b90, 0xc20811baa0, 0x1, 0x1, 0x0)
            .../go/src/cmd/go/pkg.go:289 +0x860
    main.(*Package).load(0xc208137c00, 0xc208135b90, 0xc2080f2600, 0x0, 0x0, 0x4)
            .../go/src/cmd/go/pkg.go:624 +0x4eaa
    main.loadImport(0x7ffd26b87b7a, 0x17, 0xc20800e0e4, 0x12, 0xc208135b90, 0x0, 0x0, 0x0, 0x0)
            .../go/src/cmd/go/pkg.go:282 +0x6f8
    main.loadPackage(0x7ffd26b87b7a, 0x17, 0xc208135b90, 0x0)
            .../go/src/cmd/go/pkg.go:975 +0x1395
    main.download(0x7ffd26b87b7a, 0x17, 0xc208135b90, 0xc20814b500)
            .../go/src/cmd/go/get.go:152 +0x7c
    main.runGet(0xba3c20, 0xc20800a410, 0x1, 0x1)
            .../go/src/cmd/go/get.go:79 +0x15e
    main.main()
            .../go/src/cmd/go/main.go:177 +0x74d
    
    goroutine 17 [syscall, locked to thread]:
    runtime.goexit()
            .../go/src/runtime/asm_amd64.s:1700 +0x1
    
    goroutine 5 [syscall]:
    os/signal.loop()
            .../go/src/os/signal/signal_unix.go:22 +0x18
    created by os/signal.init.1
            .../go/src/os/signal/signal_unix.go:28 +0x37

**Comment by ebfe** [comment]
Simpler testcase:

```
$ mkdir -p t/internal/foo
$ cat << EOF > t/t.go
package main
import "internal/foo"
func main() {}
EOF
$ go list ./t
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.disallowInternal(0xc208144f60, 0xa, 0xc208137800, 0xc20812d838, 0x8)
        .../src/go/src/cmd/go/pkg.go:349 +0x484
main.loadImport(0xc2081452f1, 0xc, 0xc208144f60, 0xa, 0xc20812d838, 0xc20810bb00, 0x1, 0x1, 0x0)
        .../src/go/src/cmd/go/pkg.go:289 +0x860
main.(*Package).load(0xc208137400, 0xc20812d838, 0xc208146600, 0x0, 0x0, 0x4)
        .../src/go/src/cmd/go/pkg.go:624 +0x4eaa
main.loadImport(0xc208144a30, 0x3, 0xc208010054, 0x8, 0xc20812d838, 0x0, 0x0, 0x0, 0x0)
        .../src/go/src/cmd/go/pkg.go:282 +0x6f8
main.loadPackage(0xc208144a30, 0x3, 0xc20812d838, 0x0)
        .../src/go/src/cmd/go/pkg.go:975 +0x1395
main.packagesAndErrors(0xc208144a50, 0x1, 0x1, 0x0, 0x0, 0x0)
        .../src/go/src/cmd/go/pkg.go:1014 +0x3b4
main.packages(0xc208066260, 0x1, 0x1, 0x0, 0x0, 0x0)
        .../src/go/src/cmd/go/pkg.go:988 +0x8a
main.runList(0xba5080, 0xc208066260, 0x1, 0x1)
        .../src/go/src/cmd/go/list.go:177 +0x1e7
main.main()
        .../src/go/src/cmd/go/main.go:177 +0x74d

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        .../src/go/src/runtime/asm_amd64.s:1700 +0x1

goroutine 20 [syscall]:
os/signal.loop()
        .../src/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        .../src/go/src/os/signal/signal_unix.go:28 +0x37
```
