### ISSUE TITLE
cmd/got: panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by pebbe** [golang/go#11349]
go version devel +6b24da6 Sun Jun 14 01:52:54 2015 +0000 linux/amd64

```
(peter) ~ go get -u -v -x github.com/gonum/plot
github.com/gonum/plot (download)
cd .
git clone https://github.com/gonum/plot /home/peter/go/src/github.com/gonum/plot
cd /home/peter/go/src/github.com/gonum/plot
git show-ref
cd /home/peter/go/src/github.com/gonum/plot
git checkout 
cd /home/peter/go/src/bitbucket.org/zombiezen/gopdf
hg paths default
bitbucket.org/zombiezen/gopdf (download)
cd /home/peter/go/src/bitbucket.org/zombiezen/gopdf
hg pull
cd /home/peter/go/src/bitbucket.org/zombiezen/gopdf
hg tags
cd /home/peter/go/src/bitbucket.org/zombiezen/gopdf
hg branches
cd /home/peter/go/src/bitbucket.org/zombiezen/gopdf
hg update default
cd /home/peter/go/src/code.google.com/p/freetype-go
hg paths default
code.google.com/p/freetype-go (download)
cd /home/peter/go/src/code.google.com/p/freetype-go
hg pull
cd /home/peter/go/src/code.google.com/p/freetype-go
hg tags
cd /home/peter/go/src/code.google.com/p/freetype-go
hg branches
cd /home/peter/go/src/code.google.com/p/freetype-go
hg update default
cd /home/peter/go/src/code.google.com/p/freetype-go
hg paths default
cd /home/peter/go/src/code.google.com/p/freetype-go
hg paths default
cd /home/peter/go/src/github.com/ajstarks/svgo
git config remote.origin.url
github.com/ajstarks/svgo (download)
cd /home/peter/go/src/github.com/ajstarks/svgo
git symbolic-ref HEAD
# cd /home/peter/go/src/github.com/ajstarks/svgo; git symbolic-ref HEAD
fatal: ref HEAD is not a symbolic ref
/home/peter/go/src/github.com/ajstarks/svgo on detached head; repairing
cd /home/peter/go/src/github.com/ajstarks/svgo
git checkout master
cd /home/peter/go/src/github.com/ajstarks/svgo
git pull --ff-only
cd /home/peter/go/src/github.com/ajstarks/svgo
git show-ref
cd /home/peter/go/src/github.com/ajstarks/svgo
git checkout 
github.com/gonum/floats (download)
cd .
git clone https://github.com/gonum/floats /home/peter/go/src/github.com/gonum/floats
cd /home/peter/go/src/github.com/gonum/floats
git show-ref
cd /home/peter/go/src/github.com/gonum/floats
git checkout 
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.disallowInternal(0xc208482240, 0x2a, 0xc2081e2000, 0xc208579ba0, 0x2)
        /my/opt/go/src/cmd/go/pkg.go:349 +0x484
main.loadImport(0xc2083b29a1, 0x1d, 0xc208482240, 0x2a, 0xc208579ba0, 0xc208482bd0, 0x1, 0x1, 0x0)
        /my/opt/go/src/cmd/go/pkg.go:289 +0x860
main.(*Package).load(0xc2082e3c00, 0xc208579ba0, 0xc2082b9800, 0x0, 0x0, 0x4)
        /my/opt/go/src/cmd/go/pkg.go:624 +0x4eaa
main.loadImport(0xc208011f61, 0x17, 0xc20800e074, 0xb, 0xc208579ba0, 0x0, 0x0, 0x0, 0x0)
        /my/opt/go/src/cmd/go/pkg.go:282 +0x6f8
main.loadPackage(0xc208011f61, 0x17, 0xc208579ba0, 0x0)
        /my/opt/go/src/cmd/go/pkg.go:975 +0x1395
main.download(0xc208011f61, 0x17, 0xc208579ba0, 0xc2080da800)
        /my/opt/go/src/cmd/go/get.go:222 +0x168a
main.download(0x7fffc7b7a34c, 0x15, 0xc208579ba0, 0xc208160600)
        /my/opt/go/src/cmd/go/get.go:255 +0x90e
main.runGet(0xba4c20, 0xc20800a170, 0x1, 0x1)
        /my/opt/go/src/cmd/go/get.go:79 +0x15e
main.main()
        /my/opt/go/src/cmd/go/main.go:177 +0x74d

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
        /my/opt/go/src/runtime/asm_amd64.s:1700 +0x1

goroutine 5 [syscall, 1 minutes]:
os/signal.loop()
        /my/opt/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /my/opt/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 39 [select]:
net/http.(*persistConn).writeLoop(0xc20812fa20)
        /my/opt/go/src/net/http/transport.go:1011 +0x40c
created by net/http.(*Transport).dialConn
        /my/opt/go/src/net/http/transport.go:685 +0xc80

goroutine 38 [IO wait]:
net.runtime_pollWait(0x7fb39b849ce8, 0x72, 0xc20800e2c0)
        /my/opt/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc208157cd0, 0x72, 0x0, 0x0)
        /my/opt/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc208157cd0, 0x0, 0x0)
        /my/opt/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc208157c70, 0xc208375000, 0x800, 0x800, 0x0, 0x7fb39d88b050, 0xc20800e2c0)
        /my/opt/go/src/net/fd_unix.go:233 +0x23a
net.(*conn).Read(0xc2080f43a8, 0xc208375000, 0x800, 0x800, 0x0, 0x0, 0x0)
        /my/opt/go/src/net/net.go:124 +0xe4
crypto/tls.(*block).readFromUntil(0xc2084cecc0, 0x7fb39b84a218, 0xc2080f43a8, 0x5, 0x0, 0x0)
        /my/opt/go/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc2084c2000, 0xa29617, 0x0, 0x0)
        /my/opt/go/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc2084c2000, 0xc208221000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /my/opt/go/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0x7fb39d89e788, 0xc2084c2000, 0xc20812fa78, 0xc208221000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /my/opt/go/src/net/http/transport.go:1352 +0x67
net/http.(*noteEOFReader).Read(0xc20848ebc0, 0xc208221000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        <autogenerated>:125 +0xd0
bufio.(*Reader).fill(0xc208381f20)
        /my/opt/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc208381f20, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /my/opt/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc20812fa20)
        /my/opt/go/src/net/http/transport.go:887 +0xf7
created by net/http.(*Transport).dialConn
        /my/opt/go/src/net/http/transport.go:684 +0xc5b

```

**Comment by mikioh** [comment]
This is a dup of #11201.
