### ISSUE TITLE
cmd/go: panic: main.vendoredImportPath src/cmd/go/pkg.go:396

### ISSUE THREAD

**Issue by jbuberel** [golang/go#11439]
The sample project tree, from the root of $GOPATH:
```
$ tree       
.
|-- bin
|-- src
|   `-- p
|       `-- cmd.go
`-- vendor
    `-- q
        `-- lib.go
```

Source of `p/cmd.go`:
```go
package main

import (
        "q"
        "fmt"
)

func main() {
        fmt.Println("hello")
        fmt.Printf("Val: %v\n", q.Do())
}
```

source of `vendor/q/lib.go`:
```go
package q

func Do() (string) {
        return "value"
}
```

experimental vendor flag set:
```bash
$ set | grep GO
GO15VENDOREXPERIMENT=1
GOPATH=/home/jbuberel/gosrc
$ go build p
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.vendoredImportPath(0xc820116400, 0xc82010ef21, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/jbuberel/go15/src/cmd/go/pkg.go:396 +0x58d
main.loadImport(0xc82010ef21, 0x1, 0xc820106b20, 0x1a, 0xc820116400, 0xc8200f9860, 0xc8200e5410, 0x1, 0x1, 0x0)
        /home/jbuberel/go15/src/cmd/go/pkg.go:264 +0x1344
main.(*Package).load(0xc820116400, 0xc8200f9860, 0xc8200d2600, 0x0, 0x0, 0x4)
        /home/jbuberel/go15/src/cmd/go/pkg.go:837 +0x4219
main.loadImport(0x7ffcfbdfc7b1, 0x1, 0xc82000e0a4, 0x14, 0x0, 0xc8200f9860, 0x0, 0x0, 0x0, 0x0)
        /home/jbuberel/go15/src/cmd/go/pkg.go:319 +0xd45
main.loadPackage(0x7ffcfbdfc7b1, 0x1, 0xc8200f9860, 0x0)
        /home/jbuberel/go15/src/cmd/go/pkg.go:1504 +0x13a4
main.packagesAndErrors(0xc82010ee00, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/jbuberel/go15/src/cmd/go/pkg.go:1543 +0x3b4
main.packagesForBuild(0xc82000a2f0, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/jbuberel/go15/src/cmd/go/pkg.go:1556 +0x89
main.runBuild(0xbb6040, 0xc82000a2f0, 0x1, 0x1)
        /home/jbuberel/go15/src/cmd/go/build.go:401 +0x8c
main.main()
        /home/jbuberel/go15/src/cmd/go/main.go:177 +0x74d

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /home/jbuberel/go15/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
        /home/jbuberel/go15/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /home/jbuberel/go15/src/os/signal/signal_unix.go:28 +0x37
```

Version info:
```bash
$ go version
go version devel +aea348a Fri Jun 26 23:33:39 2015 +0000 linux/amd64
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/jbuberel/gosrc"
GORACE=""
GOROOT="/home/jbuberel/go15"
GOTOOLDIR="/home/jbuberel/go15/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
jbuberel@ubuntu:~/gosrc$ 
```

**Comment by bradfitz** [comment]
Dup of #11414 I think.

**Comment by jbuberel** [comment]
Very well could be the case. I'll retest when that issue gets resolve. Thanks!

**Comment by jbuberel** [comment]
@bradfitz - just rebuilt and retested with b6ead9f171742cd5b519a22ecc690354b0d1ce27 - would you be willing to re-open?

```
$ go version
go version devel +b6ead9f Tue Jul 7 21:53:11 2015 +0000 linux/amd64
$ set | grep GO
GO15VENDOREXPERIMENT=1
GOPATH=/home/jbuberel/gosrc
```

Same sample code as posted above, results:
```
$ go build -v -x p
WORK=/tmp/go-build027022446
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.vendoredImportPath(0xc820109400, 0xc82011af51, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
 /home/jbuberel/go15/src/cmd/go/pkg.go:396 +0x540
main.loadImport(0xc82011af51, 0x1, 0xc820112b20, 0x1a, 0xc820109400, 0xc820101860, 0xc8200ef440, 0x1, 0x1, 0x0)
 /home/jbuberel/go15/src/cmd/go/pkg.go:264 +0x1344
main.(*Package).load(0xc820109400, 0xc820101860, 0xc8200d2900, 0x0, 0x0, 0x4)
 /home/jbuberel/go15/src/cmd/go/pkg.go:841 +0x4219
main.loadImport(0x7ffc27a4c7a5, 0x1, 0xc82000e084, 0x14, 0x0, 0xc820101860, 0x0, 0x0, 0x0, 0x0)
 /home/jbuberel/go15/src/cmd/go/pkg.go:319 +0xd45
main.loadPackage(0x7ffc27a4c7a5, 0x1, 0xc820101860, 0x0)
 /home/jbuberel/go15/src/cmd/go/pkg.go:1508 +0x13a4
main.packagesAndErrors(0xc82011ae20, 0x1, 0x1, 0x0, 0x0, 0x0)
 /home/jbuberel/go15/src/cmd/go/pkg.go:1547 +0x3b4
main.packagesForBuild(0xc82000a090, 0x1, 0x1, 0x0, 0x0, 0x0)
 /home/jbuberel/go15/src/cmd/go/pkg.go:1560 +0x89
main.runBuild(0xb93180, 0xc82000a090, 0x1, 0x1)
 /home/jbuberel/go15/src/cmd/go/build.go:401 +0x8c
main.main()
 /home/jbuberel/go15/src/cmd/go/main.go:177 +0x74d

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
 /home/jbuberel/go15/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
 /home/jbuberel/go15/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
 /home/jbuberel/go15/src/os/signal/signal_unix.go:28 +0x37
```

**Comment by rsc** [comment]
Dup of #11414.
