### ISSUE TITLE
reflect: test panic at tip

### ISSUE THREAD

**Issue by davecheney** [golang/go#11433]
Building from tip at 77132c810d66971318d898190c3ad02b3eedca40, `reflect` tests panic
```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0xc81ffbffff pc=0x412373]

goroutine 107 [running]:
runtime.throw(0x6aa990, 0x2a)
        /home/dfc/go/src/runtime/panic.go:527 +0x96 fp=0xc8200ee1f8 sp=0xc8200ee1e0
runtime.sigpanic()
        /home/dfc/go/src/runtime/sigpanic_unix.go:12 +0x5a fp=0xc8200ee248 sp=0xc8200ee1f8
runtime.runGCProg(0xc8200aad94, 0xc8200ee288, 0xc81ffc36ff, 0x2, 0x640000000054be95)
        /home/dfc/go/src/runtime/mbitmap.go:1501 +0x633 fp=0xc8200ee250 sp=0xc8200ee248
runtime.heapBitsSetTypeGCProg(0xc81ffc36ff, 0xc800000000, 0x27100, 0x27100, 0x4e200, 0x50000, 0xc8200aad94)
        /home/dfc/go/src/runtime/mbitmap.go:1206 +0x387 fp=0xc8200ee2b8 sp=0xc8200ee250
runtime.heapBitsSetType(0xc820792000, 0x50000, 0x4e200, 0xc820456480)
        /home/dfc/go/src/runtime/mbitmap.go:763 +0x236 fp=0xc8200ee390 sp=0xc8200ee2b8
runtime.mallocgc(0x50000, 0xc820456480, 0x0, 0x20)
        /home/dfc/go/src/runtime/malloc.go:652 +0x64d fp=0xc8200ee460 sp=0xc8200ee390
runtime.newarray(0xc820456480, 0x2, 0xc8204eb480)
        /home/dfc/go/src/runtime/malloc.go:759 +0xc9 fp=0xc8200ee4a0 sp=0xc8200ee460
reflect.unsafe_NewArray(0xc820456480, 0x2, 0xc820456480)
        /home/dfc/go/src/runtime/malloc.go:764 +0x2b fp=0xc8200ee4c0 sp=0xc8200ee4a0
reflect.MakeSlice(0x7fadafa830a8, 0xc820014410, 0x0, 0x2, 0x0, 0x0, 0x0)
        /home/dfc/go/src/reflect/value.go:2037 +0x237 fp=0xc8200ee530 sp=0xc8200ee4c0
reflect_test.verifyGCBitsSlice(0xc820432090, 0x7fadafa830a8, 0xc820014410, 0x2, 0xc820729000, 0x4e20, 0x4e20)
        /home/dfc/go/src/reflect/all_test.go:4544 +0x56 fp=0xc8200ee668 sp=0xc8200ee530
reflect_test.TestGCBits(0xc820432090)
        /home/dfc/go/src/reflect/all_test.go:4670 +0x6ae0 fp=0xc8201dbee8 sp=0xc8200ee668
testing.tRunner(0xc820432090, 0xb07b08)
        /home/dfc/go/src/testing/testing.go:455 +0x98 fp=0xc8201dbf20 sp=0xc8201dbee8
runtime.goexit()
        /home/dfc/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8201dbf28 sp=0xc8201dbf20
created by testing.RunTests
        /home/dfc/go/src/testing/testing.go:560 +0x86d

goroutine 1 [chan receive]:
testing.RunTests(0xa596a8, 0xb071c0, 0x6c, 0x6c, 0xaef101)
        /home/dfc/go/src/testing/testing.go:561 +0x8ad
testing.(*M).Run(0xc8200d5ef8, 0x0)
        /home/dfc/go/src/testing/testing.go:493 +0x70
main.main()
        reflect/_test/_testmain.go:288 +0x116

goroutine 38 [sleep]:
time.Sleep(0x3b9aca00)
        /home/dfc/go/src/runtime/time.go:59 +0xf9
reflect_test.selectWatcher()
        /home/dfc/go/src/reflect/all_test.go:1383 +0x2c
created by reflect_test.TestSelect.func1
        /home/dfc/go/src/reflect/all_test.go:1113 +0x2b
FAIL    reflect 0.102s
```

**Comment by crawshaw** [comment]
I can't replicate this on darwin/amd64 at 4ef836faf6c33dbdb25db12e0ddd903730ccaa0f. Is it still happening? On what GOOS?

**Comment by rsc** [comment]
Dup of #11430, fixed.
