### ISSUE TITLE
runtime: crash with unexpected fault address 0xc82... on go1.5beta1

### ISSUE THREAD

**Issue by rhysh** [golang/go#11644]
With go version go1.5beta1 on linux/amd64, I see the following crash in an http server that serves short-lived requests. The process is stable with go1.4.1. (@rsc)

I'll be able to try running with GODEBUG=gccheckmark=1 early next week, but here's what I have for now:

```
unexpected fault address 0xc821731d40
fatal error: fault
[signal 0xb code=0x2 addr=0xc821731d40 pc=0xc821731d40]

goroutine 326758 [running]:
runtime.throw(0xa45e70, 0x5)
	/usr/local/go/src/runtime/panic.go:527 +0x96 fp=0xc820fc1da8 sp=0xc820fc1d90
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:27 +0x2ab fp=0xc820fc1df8 sp=0xc820fc1da8
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1843 +0x3f6

goroutine 1 [IO wait]:
net.runtime_pollWait(0x7f4d148b0320, 0x72, 0xc820012130)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8201b8df0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201b8df0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8201b8d90, 0x0, 0x7f4d158f1190, 0xc821f80b80)
	/usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820136148, 0xc8216f3230, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:249 +0x4d
net.(*TCPListener).Accept(0xc820136148, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:259 +0x3d
redacted(0x7f4d158f10d8, 0xc820136148, 0x0, 0x0, 0x0, 0x0)
	/redacted.go:26 +0x53
redacted(0xc82025a440, 0x0, 0x0, 0x0, 0x0)
	<autogenerated>:3 +0xb0
net/http.(*Server).Serve(0xc820208ba0, 0x7f4d148b5960, 0xc82025a440, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1820 +0xb3
redacted(0xc820208b40, 0x7f4d148b5960, 0xc82025a440, 0x0, 0x0)
	/redacted.go:32 +0x1a7
redacted(0x7f4d158f10d8, 0xc820136148, 0x7f4d148b5938, 0xc820197380, 0x0, 0x0)
	/redacted.go:99 +0x85
main.main()
	/redacted.go:147 +0x12ea

[snip]
```

**Comment by ianlancetaylor** [comment]
CC @RLH @aclements

**Comment by aclements** [comment]
8c3533c was just committed and should fix the other memory corruption issue you filed with this program. Would you mind updating and testing to see if this issue was also a consequence of that bug?

**Comment by rhysh** [comment]
The server in question has been running for over an hour with go version `devel +0bcdffe Mon Jul 13 19:42:35 2015 +0000` with no crashes. With go1.5beta1, it would crash every few minutes. This could very well have the same root cause as #11643. Thank you.
