### ISSUE TITLE
 cmd/compile: nil pointer dereference (2)

### ISSUE THREAD

**Issue by dvyukov** [golang/go#11666]
on dev.ssa branch
go version devel +9b04852 Sat Jul 11 00:08:50 2015 +0000 linux/amd64

compile crashes on the following program:
```go
package a

func f_ssa() {
	return
	for {
		return
	}
}
```
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0x5d3617]

goroutine 1 [running]:
cmd/compile/internal/gc.buildssa.func1(0xc82011b4b0)
	src/cmd/compile/internal/gc/ssa.go:46 +0x4d
cmd/compile/internal/gc.(*state).stmt(0xc8200ad778, 0xc82018a6c0)
	src/cmd/compile/internal/gc/ssa.go:390 +0x577
cmd/compile/internal/gc.(*state).stmtList(0xc8200ad778, 0xc82015b860)
	src/cmd/compile/internal/gc/ssa.go:281 +0x3a
cmd/compile/internal/gc.buildssa(0xc82018a510, 0x0, 0xc82018b500)
	src/cmd/compile/internal/gc/ssa.go:95 +0x944
cmd/compile/internal/gc.compile(0xc82018a510)
	src/cmd/compile/internal/gc/pgen.go:412 +0x608
cmd/compile/internal/gc.funccompile(0xc82018a510)
	src/cmd/compile/internal/gc/dcl.go:1480 +0x1c9
cmd/compile/internal/gc.Main()
	src/cmd/compile/internal/gc/lex.go:473 +0x1f08
cmd/compile/internal/amd64.Main()
	src/cmd/compile/internal/amd64/galign.go:127 +0x58d
main.main()
	src/cmd/compile/main.go:26 +0x189
```

**Comment by dvyukov** [comment]
@josharian @DanielMorsing

**Comment by josharian** [comment]
Fixed by CL 12445.
