### ISSUE TITLE
cmd/asm: index out of range

### ISSUE THREAD

**Issue by dvyukov** [golang/go#11759]
cmd/asm crashes on the following program:
```
FUNCDATA
```
```
panic: runtime error: index out of range

goroutine 1 [running]:
cmd/asm/internal/asm.(*Parser).asmFuncData(0xc820043e80, 0xc820010720, 0x8, 0xc820043b40, 0x0, 0x3)
	src/cmd/asm/internal/asm/asm.go:289 +0x2cd
cmd/asm/internal/asm.(*Parser).pseudo(0xc820043e80, 0x7, 0xc820010720, 0x8, 0xc820043b40, 0x0, 0x3)
	src/cmd/asm/internal/asm/parse.go:220 +0xae
cmd/asm/internal/asm.(*Parser).line(0xc820043e80, 0xc82000a540)
	src/cmd/asm/internal/asm/parse.go:180 +0x9ac
cmd/asm/internal/asm.(*Parser).Parse(0xc820043e80, 0xc82000a540, 0xc820014750)
	src/cmd/asm/internal/asm/parse.go:81 +0x21
main.main()
	src/cmd/asm/main.go:59 +0xb39
```
go version devel +9b04852 Sat Jul 11 00:08:50 2015 +0000 linux/amd64

**Comment by dvyukov** [comment]
Similar one, but leads to nil deref:
```
FUNCDATA(SB 
```
(there is a space at the end of line)
