### ISSUE TITLE
cmd/asm: slice bounds out of range

### ISSUE THREAD

**Issue by dvyukov** [golang/go#11760]
```
DATA 0
```
```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
cmd/asm/internal/asm.(*Parser).asmData(0xc820043e80, 0xc820010710, 0x4, 0xc820043b40, 0x1, 0x3)
	src/cmd/asm/internal/asm/asm.go:183 +0x71b
cmd/asm/internal/asm.(*Parser).pseudo(0xc820043e80, 0x3, 0xc820010710, 0x4, 0xc820043b40, 0x1, 0x3)
	src/cmd/asm/internal/asm/parse.go:214 +0x81
cmd/asm/internal/asm.(*Parser).line(0xc820043e80, 0xc82000a540)
	src/cmd/asm/internal/asm/parse.go:180 +0x9ac
cmd/asm/internal/asm.(*Parser).Parse(0xc820043e80, 0xc82000a540, 0xc820014750)
	src/cmd/asm/internal/asm/parse.go:81 +0x21
main.main()
	src/cmd/asm/main.go:59 +0xb39
```
go version devel +9b04852 Sat Jul 11 00:08:50 2015 +0000 linux/amd64

**Comment by dvyukov** [comment]
Similar one, but leads to nil deref:
```
DATA(0
```

**Comment by dvyukov** [comment]
Another one:
```
DATA(0)
```
