### ISSUE TITLE
all.bash: go tip failure on Raspberry Pi B+ (armv6l)

### ISSUE THREAD

**Issue by jonathanpittman** [golang/go#11785]
I am using go1.4.2 and trying to build go at tip on a Raspberry Pi B+ with 512MB RAM (16MB allocated to video, the rest to the system).  I am synced to commit "e1ee314 internal/trace: fix fuzzer crashers".

I am getting this when running all.bash at tip.  It was happening before 1.5 beta 1 and is still happening.  I had no problems building 1.4.2 from source (which is what is being used for the bootstrapping).

```Linux raspberrypi 3.18.11+ #781 PREEMPT Tue Apr 21 18:02:18 BST 2015 armv6l GNU/Linux```

```
pi@raspberrypi ~/go/src $ ./all.bash
##### Building Go bootstrap tool.
cmd/dist

##### Building Go toolchain using /home/pi/go1.4.
bootstrap/internal/obj
bootstrap/internal/obj/arm
bootstrap/internal/obj/arm64
bootstrap/internal/obj/ppc64
bootstrap/internal/obj/x86
bootstrap/asm/internal/arch
bootstrap/asm/internal/flags
bootstrap/asm/internal/lex
bootstrap/asm/internal/asm
bootstrap/asm
bootstrap/compile/internal/big
bootstrap/internal/gcprog
bootstrap/compile/internal/gc
bootstrap/compile/internal/amd64
bootstrap/compile/internal/arm
bootstrap/compile/internal/arm64
bootstrap/compile/internal/ppc64
bootstrap/compile/internal/x86
bootstrap/compile
bootstrap/internal/asm
bootstrap/link/internal/ld
bootstrap/link/internal/amd64
bootstrap/link/internal/arm
bootstrap/link/internal/arm64
bootstrap/link/internal/ppc64
bootstrap/link/internal/x86
bootstrap/link
bootstrap/old5a
bootstrap/old6a
bootstrap/old8a
bootstrap/old9a

##### Building compilers and go_bootstrap for host, linux/arm.
runtime
errors
sync/atomic
sync
internal/singleflight
io
unicode
unicode/utf8
unicode/utf16
bytes
math
strings
strconv
bufio
sort
container/heap
encoding/base64
syscall
internal/syscall/windows/registry
time
internal/syscall/windows  
os
reflect
fmt
encoding
encoding/binary
encoding/json
flag
path/filepath
path
io/ioutil
log
regexp/syntax
regexp
go/token
go/scanner
go/ast
go/parser
os/exec
os/signal
net/url
text/template/parse
text/template
go/doc
go/build
hash
crypto
crypto/sha1
debug/dwarf
debug/elf
cmd/go

##### Building packages and commands for linux/arm.
runtime
errors
sync/atomic
sync
io
unicode
unicode/utf8
bytes
bufio
math
strconv
reflect
encoding/binary
syscall
time
os
fmt
sort
flag
log
strings
path/filepath
cmd/internal/obj
cmd/internal/goobj
cmd/internal/rsc.io/arm/armasm
cmd/internal/rsc.io/x86/x86asm
path
debug/dwarf
debug/elf
debug/gosym
debug/macho
debug/pe
debug/plan9obj
regexp/syntax
regexp
text/tabwriter
cmd/internal/objfile
cmd/addr2line
io/ioutil
archive/tar
compress/flate
hash
hash/crc32
archive/zip
compress/bzip2
compress/gzip
compress/lzw
hash/adler32
compress/zlib
container/heap
container/list
container/ring
crypto
crypto/subtle
crypto/cipher
crypto/aes
crypto/des
math/rand
math/big
crypto/dsa
crypto/elliptic
crypto/sha512
encoding/asn1
crypto/ecdsa
crypto/hmac
crypto/md5
internal/syscall/unix
crypto/rand
crypto/rc4
crypto/rsa
crypto/sha1
crypto/sha256
crypto/x509/pkix
encoding/hex
encoding/base64
encoding/pem
internal/singleflight
go/token
go/scanner
go/ast
go/parser
go/printer
os/exec
cmd/cgo
runtime/cgo
net
crypto/x509
crypto/tls
database/sql/driver
database/sql
encoding
encoding/ascii85
encoding/base32
encoding/csv
encoding/gob
unicode/utf16
encoding/json
encoding/xml
mime
mime/quotedprintable
net/textproto
mime/multipart
net/http/internal
net/url
net/http
expvar
text/template/parse
text/template
go/doc
go/build
go/constant
internal/format
go/format
go/types
text/scanner
go/internal/gccgoimporter 
go/internal/gcimporter
go/importer
hash/crc64
hash/fnv
html
html/template
image/color
image
image/color/palette
image/internal/imageutil  
image/draw
image/gif
image/jpeg
image/png
index/suffixarray
runtime/pprof
testing
internal/testenv
internal/trace
log/syslog
math/cmplx
net/http/cgi
net/http/cookiejar
net/http/fcgi
net/http/httptest
net/http/httputil
net/http/pprof
net/internal/socktest
net/mail
net/rpc
net/rpc/jsonrpc
net/smtp
os/signal
os/user
runtime/debug
runtime/race
testing/iotest
testing/quick
cmd/api
cmd/internal/obj/arm
cmd/internal/obj/arm64
cmd/internal/obj/ppc64
cmd/internal/obj/x86
cmd/asm/internal/arch
cmd/asm/internal/flags
cmd/asm/internal/lex
cmd/asm/internal/asm
cmd/asm
cmd/compile/internal/big
cmd/internal/gcprog
cmd/compile/internal/gc
cmd/compile/internal/amd64
cmd/compile/internal/arm
cmd/compile/internal/arm64
cmd/compile/internal/ppc64
cmd/compile/internal/x86
cmd/compile
cmd/cover
cmd/dist
cmd/doc
cmd/fix
cmd/go
cmd/gofmt
cmd/internal/asm
cmd/link/internal/ld
cmd/link/internal/amd64
cmd/link/internal/arm
cmd/link/internal/arm64
cmd/link/internal/ppc64
cmd/link/internal/x86
cmd/link
cmd/newlink
cmd/nm
cmd/objdump
cmd/old5a
cmd/old6a
cmd/old8a
cmd/old9a
cmd/pack
cmd/pprof/internal/profile
cmd/pprof/internal/plugin
cmd/pprof/internal/report
cmd/pprof/internal/svg
cmd/pprof/internal/tempfile
cmd/pprof/internal/commands
cmd/pprof/internal/driver
cmd/pprof/internal/fetch
cmd/pprof/internal/symbolizer
cmd/pprof/internal/symbolz
cmd/pprof
cmd/trace
cmd/vet/whitelist
cmd/vet
cmd/yacc


##### Testing packages.
ok      archive/tar     0.134s
ok      archive/zip     16.000s
ok      bufio   1.217s
ok      bytes   2.220s
ok      compress/bzip2  1.059s
ok      compress/flate  10.946s
ok      compress/gzip   0.074s
ok      compress/lzw    1.274s
ok      compress/zlib   24.612s
ok      container/heap  0.041s
ok      container/list  0.035s
ok      container/ring  0.196s
ok      crypto/aes      0.219s
ok      crypto/cipher   0.081s
ok      crypto/des      0.244s
ok      crypto/dsa      0.092s
ok      crypto/ecdsa    1.005s
ok      crypto/elliptic 1.028s
ok      crypto/hmac     0.093s
ok      crypto/md5      0.064s
ok      crypto/rand     0.244s
ok      crypto/rc4      1.992s
ok      crypto/rsa      2.581s
ok      crypto/sha1     0.050s
ok      crypto/sha256   0.104s
ok      crypto/sha512   0.087s
ok      crypto/subtle   0.124s
ok      crypto/tls      28.467s
ok      crypto/x509     30.289s
ok      database/sql    0.847s
ok      database/sql/driver     0.033s
ok      debug/dwarf     0.129s
ok      debug/elf       0.295s
ok      debug/gosym     0.031s
ok      debug/macho     0.119s
ok      debug/pe        0.289s
ok      debug/plan9obj  0.040s
ok      encoding/ascii85        0.043s
ok      encoding/asn1   0.073s
ok      encoding/base32 0.051s
ok      encoding/base64 0.057s
ok      encoding/binary 0.053s
ok      encoding/csv    0.052s
ok      encoding/gob    1.121s
ok      encoding/hex    0.039s
ok      encoding/json   2.725s
ok      encoding/pem    0.700s
ok      encoding/xml    0.222s
ok      errors  0.040s
ok      expvar  0.089s
ok      flag    0.050s
ok      fmt     5.794s
ok      go/ast  0.158s
ok      go/build        2.428s
ok      go/constant     0.099s
ok      go/doc  0.994s
ok      go/format       0.162s
ok      go/internal/gccgoimporter       0.073s
ok      go/internal/gcimporter  0.487s
ok      go/parser       0.704s
ok      go/printer      7.044s
ok      go/scanner      0.067s
ok      go/token        0.989s
ok      go/types        29.081s
ok      hash/adler32    0.110s
ok      hash/crc32      0.033s
ok      hash/crc64      0.031s
ok      hash/fnv        0.032s
ok      html    0.053s
ok      html/template   0.892s
ok      image   2.926s
ok      image/color     1.807s
ok      image/draw      2.051s
ok      image/gif       1.377s
ok      image/jpeg      2.792s
ok      image/png       0.917s
ok      index/suffixarray       0.147s
ok      internal/singleflight   0.044s
ok      internal/trace  0.087s
ok      io      0.071s
ok      io/ioutil       0.056s
ok      log     0.076s
ok      log/syslog      2.443s
ok      math    0.116s
ok      math/big        21.132s
ok      math/cmplx      0.077s
ok      math/rand       5.710s
ok      mime    0.172s
ok      mime/multipart  1.334s
ok      mime/quotedprintable    3.647s
ok      net     5.174s
ok      net/http        38.926s
ok      net/http/cgi    4.522s
ok      net/http/cookiejar      0.138s
ok      net/http/fcgi   0.096s
ok      net/http/httptest       0.123s
ok      net/http/httputil       0.225s
ok      net/http/internal       0.056s
ok      net/internal/socktest   0.216s
ok      net/mail        0.095s
ok      net/rpc 0.454s
ok      net/rpc/jsonrpc 0.139s
ok      net/smtp        0.643s
ok      net/textproto   0.086s
ok      net/url 0.252s
ok      os      0.631s
ok      os/exec 3.558s
ok      os/signal       3.583s
ok      os/user 0.055s
ok      path    0.045s
ok      path/filepath   0.407s
ok      reflect 1.743s
ok      regexp  2.883s
ok      regexp/syntax   7.061s
panic: test timed out after 4m0s

goroutine 22625 [running]:
testing.startAlarm.func1()
        /home/pi/go/src/testing/testing.go:702 +0x10c
created by time.goFunc
        /home/pi/go/src/time/sleep.go:129 +0x34

goroutine 1 [chan receive, locked to thread]:
testing.RunTests(0x25a7f0, 0x300110, 0x9c, 0x9c, 0x1)
        /home/pi/go/src/testing/testing.go:561 +0x618
testing.(*M).Run(0x10543f7c, 0x121e8)
        /home/pi/go/src/testing/testing.go:493 +0x6c
main.main()
        runtime/_test/_testmain.go:892 +0x118

goroutine 22622 [syscall]:
syscall.Syscall6(0x72, 0x5805, 0x10e6dbc0, 0x0, 0x1051ee10, 0x0, 0x0, 0x154954, 0x1540c4, 0x8)
        /home/pi/go/src/syscall/asm_linux_arm.s:48 +0x8
syscall.wait4(0x5805, 0x10e6dbc0, 0x0, 0x1051ee10, 0x50, 0x0, 0x0)
        /home/pi/go/src/syscall/zsyscall_linux_arm.go:172 +0x64
syscall.Wait4(0x5805, 0x10e6dbe4, 0x0, 0x1051ee10, 0x10e6dc4c, 0x0, 0x0)
        /home/pi/go/src/syscall/syscall_linux.go:256 +0x54
os.(*Process).wait(0x1156b930, 0x3, 0x0, 0x0)
        /home/pi/go/src/os/exec_unix.go:22 +0xcc
os.(*Process).Wait(0x1156b930, 0x1156b790, 0x0, 0x0)
        /home/pi/go/src/os/doc.go:45 +0x2c
os/exec.(*Cmd).Wait(0x113ff0e0, 0x0, 0x0)
        /home/pi/go/src/os/exec/exec.go:379 +0x1b4
os/exec.(*Cmd).Run(0x113ff0e0, 0x0, 0x0)
        /home/pi/go/src/os/exec/exec.go:257 +0x58
os/exec.(*Cmd).CombinedOutput(0x113ff0e0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/os/exec/exec.go:423 +0x2c8
runtime_test.executeTest(0x11057200, 0x260010, 0x2c0, 0x1aefc0, 0x1156b700, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/runtime/crash_test.go:68 +0xc94
runtime_test.TestGcSys(0x11057200)
        /home/pi/go/src/runtime/gc_test.go:22 +0x1a4
testing.tRunner(0x11057200, 0x30032c)
        /home/pi/go/src/testing/testing.go:455 +0xa8
created by testing.RunTests
        /home/pi/go/src/testing/testing.go:560 +0x5ec

goroutine 22624 [syscall]:
syscall.Syscall(0x3, 0x4, 0x1131f600, 0x200, 0x5412c, 0x200, 0x1b79f0)
        /home/pi/go/src/syscall/asm_linux_arm.s:17 +0x8
syscall.read(0x4, 0x1131f600, 0x200, 0x200, 0x115398, 0x0, 0x0)
        /home/pi/go/src/syscall/zsyscall_linux_arm.go:783 +0x78
syscall.Read(0x4, 0x1131f600, 0x200, 0x200, 0x0, 0x0, 0x0)
        /home/pi/go/src/syscall/syscall_unix.go:160 +0x4c
os.(*File).read(0x10528d30, 0x1131f600, 0x200, 0x200, 0x1131f600, 0x0, 0x0)
        /home/pi/go/src/os/file_unix.go:211 +0x54
os.(*File).Read(0x10528d30, 0x1131f600, 0x200, 0x200, 0x4012c, 0x0, 0x0)
        /home/pi/go/src/os/file.go:95 +0x7c
bytes.(*Buffer).ReadFrom(0x11057260, 0xb6e928f8, 0x10528d30, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/bytes/buffer.go:173 +0x22c
io.copyBuffer(0xb6e928c8, 0x11057260, 0xb6e928f8, 0x10528d30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/pi/go/src/io/io.go:375 +0x124
io.Copy(0xb6e928c8, 0x11057260, 0xb6e928f8, 0x10528d30, 0x1947a0, 0x113d26b0, 0x0, 0x0)
        /home/pi/go/src/io/io.go:351 +0x64
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
        /home/pi/go/src/os/exec/exec.go:232 +0x94
os/exec.(*Cmd).Start.func1(0x1156b780, 0x113ff0e0)
        /home/pi/go/src/os/exec/exec.go:339 +0x1c
created by os/exec.(*Cmd).Start
        /home/pi/go/src/os/exec/exec.go:340 +0x840

goroutine 22620 [syscall]:
runtime_test.TestFutexsleep.func1(0x0, 0x914f0000, 0x4e94, 0x226570, 0x14, 0x1051a100)
        /home/pi/go/src/runtime/futex_test.go:47 +0x54
created by runtime_test.TestFutexsleep
        /home/pi/go/src/runtime/futex_test.go:51 +0x20c

goroutine 22621 [syscall]:
runtime_test.TestFutexsleep.func1(0x0, 0x4876e800, 0x1dcd6517, 0x221818, 0x13, 0x1051a140)
        /home/pi/go/src/runtime/futex_test.go:47 +0x54
created by runtime_test.TestFutexsleep
        /home/pi/go/src/runtime/futex_test.go:51 +0x20c
FAIL    runtime 240.264s
ok      runtime/debug   0.148s
ok      runtime/pprof   17.004s
ok      sort    1.151s
ok      strconv 4.936s
ok      strings 2.363s
ok      sync    1.440s
ok      sync/atomic     4.095s
ok      syscall 0.297s
ok      testing 1.511s
ok      testing/quick   0.927s
ok      text/scanner    0.074s
ok      text/tabwriter  0.071s
ok      text/template   0.531s
ok      text/template/parse     0.337s
ok      time    8.724s
ok      unicode 0.048s
ok      unicode/utf16   0.037s
ok      unicode/utf8    0.080s
ok      cmd/addr2line   25.262s
ok      cmd/api 0.125s
ok      cmd/asm/internal/asm    0.332s
ok      cmd/asm/internal/lex    0.042s
ok      cmd/compile/internal/big        89.894s
ok      cmd/cover       52.554s
ok      cmd/doc 0.344s
ok      cmd/fix 0.311s
SIGQUIT: quit
PC=0x2748e4

goroutine 49 [syscall]:
syscall.Syscall6(0x72, 0x5b34, 0x10849cd4, 0x0, 0x1081fa40, 0x0, 0x0, 0x1cee28, 0x1ce598, 0x8)
        /home/pi/go/src/syscall/asm_linux_arm.s:48 +0x8 fp=0x10849c88 sp=0x10849c84
syscall.wait4(0x5b34, 0x10849cd4, 0x0, 0x1081fa40, 0x50, 0x0, 0x0)
        /home/pi/go/src/syscall/zsyscall_linux_arm.go:172 +0x64 fp=0x10849cb4 sp=0x10849c88
syscall.Wait4(0x5b34, 0x10849cf8, 0x0, 0x1081fa40, 0x10849d60, 0x0, 0x0)
        /home/pi/go/src/syscall/syscall_linux.go:256 +0x54 fp=0x10849cd8 sp=0x10849cb4
os.(*Process).wait(0x10a3a760, 0x3, 0x0, 0x0)
        /home/pi/go/src/os/exec_unix.go:22 +0xcc fp=0x10849d30 sp=0x10849cd8
os.(*Process).Wait(0x10a3a760, 0x10a3a5e0, 0x0, 0x0)
        /home/pi/go/src/os/doc.go:45 +0x2c fp=0x10849d44 sp=0x10849d30
os/exec.(*Cmd).Wait(0x10866f00, 0x0, 0x0)
        /home/pi/go/src/os/exec/exec.go:379 +0x1b4 fp=0x10849dac sp=0x10849d44
os/exec.(*Cmd).Run(0x10866f00, 0x0, 0x0)
        /home/pi/go/src/os/exec/exec.go:257 +0x58 fp=0x10849dc4 sp=0x10849dac
cmd/go_test.(*testgoData).doRun(0x10855b20, 0x10a3a560, 0x2, 0x2, 0x0, 0x0)
        /home/pi/go/src/cmd/go/go_test.go:255 +0x654 fp=0x10849f14 sp=0x10849dc4
cmd/go_test.(*testgoData).run(0x10855b20, 0x10a3a560, 0x2, 0x2)
        /home/pi/go/src/cmd/go/go_test.go:270 +0x34 fp=0x10849f68 sp=0x10849f14
cmd/go_test.TestGoInstallErrorOnCrossCompileToBin(0x10a340c0)
        /home/pi/go/src/cmd/go/go_test.go:767 +0x384 fp=0x10849fa0 sp=0x10849f68
testing.tRunner(0x10a340c0, 0x6a2990)
        /home/pi/go/src/testing/testing.go:455 +0xa8 fp=0x10849fc4 sp=0x10849fa0
runtime.goexit()
        /home/pi/go/src/runtime/asm_arm.s:1016 +0x4 fp=0x10849fc4 sp=0x10849fc4
created by testing.RunTests
        /home/pi/go/src/testing/testing.go:560 +0x5ec

goroutine 1 [chan receive]:
testing.RunTests(0x566b0c, 0x6a28b8, 0x7e, 0x7e, 0x4ab601)
        /home/pi/go/src/testing/testing.go:561 +0x618
testing.(*M).Run(0x108b9f6c, 0x6)
        /home/pi/go/src/testing/testing.go:493 +0x6c
cmd/go_test.TestMain(0x108b9f6c)
        /home/pi/go/src/cmd/go/go_test.go:89 +0x534
main.main()
        cmd/go/_test/_testmain.go:304 +0x118

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /home/pi/go/src/runtime/asm_arm.s:1016 +0x4

goroutine 5 [syscall]:
os/signal.loop()
        /home/pi/go/src/os/signal/signal_unix.go:22 +0x14
created by os/signal.init.1
        /home/pi/go/src/os/signal/signal_unix.go:28 +0x30

goroutine 23 [chan receive]:
testing.(*T).Parallel(0x108ef020)
        /home/pi/go/src/testing/testing.go:421 +0x60
cmd/go_test.(*testgoData).parallel(0x108555e0)
        /home/pi/go/src/cmd/go/go_test.go:170 +0x714
cmd/go_test.TestFileLineInErrorMessages(0x108ef020)
        /home/pi/go/src/cmd/go/go_test.go:601 +0x5c
testing.tRunner(0x108ef020, 0x6a2930)
        /home/pi/go/src/testing/testing.go:455 +0xa8
created by testing.RunTests
        /home/pi/go/src/testing/testing.go:560 +0x5ec

goroutine 24 [chan receive]:
testing.RunTests.func1(0x108cd000, 0x108ef020)
        /home/pi/go/src/testing/testing.go:564 +0x3c
created by testing.RunTests
        /home/pi/go/src/testing/testing.go:565 +0x660

goroutine 25 [chan receive]:
testing.(*T).Parallel(0x108ef080)
        /home/pi/go/src/testing/testing.go:421 +0x60
cmd/go_test.(*testgoData).parallel(0x108556c0)
        /home/pi/go/src/cmd/go/go_test.go:170 +0x714
cmd/go_test.TestProgramNameInCrashMessages(0x108ef080)
        /home/pi/go/src/cmd/go/go_test.go:615 +0x5c
testing.tRunner(0x108ef080, 0x6a293c)
        /home/pi/go/src/testing/testing.go:455 +0xa8
created by testing.RunTests
        /home/pi/go/src/testing/testing.go:560 +0x5ec

goroutine 26 [chan receive]:
testing.RunTests.func1(0x108cd000, 0x108ef080)
        /home/pi/go/src/testing/testing.go:564 +0x3c
created by testing.RunTests
        /home/pi/go/src/testing/testing.go:565 +0x660

goroutine 45 [chan receive]:
testing.(*T).Parallel(0x10a34000)
        /home/pi/go/src/testing/testing.go:421 +0x60
cmd/go_test.(*testgoData).parallel(0x10855960)
        /home/pi/go/src/cmd/go/go_test.go:170 +0x714
cmd/go_test.TestGoInstallRebuildsStalePackagesInOtherGOPATH(0x10a34000)
        /home/pi/go/src/cmd/go/go_test.go:701 +0x70
testing.tRunner(0x10a34000, 0x6a2978)
        /home/pi/go/src/testing/testing.go:455 +0xa8
created by testing.RunTests
        /home/pi/go/src/testing/testing.go:560 +0x5ec

goroutine 47 [chan receive]:
testing.(*T).Parallel(0x10a34060)
        /home/pi/go/src/testing/testing.go:421 +0x60
cmd/go_test.(*testgoData).parallel(0x10855a40)
        /home/pi/go/src/cmd/go/go_test.go:170 +0x714
cmd/go_test.TestGoInstallDetectsRemovedFiles(0x10a34060)
        /home/pi/go/src/cmd/go/go_test.go:731 +0x5c
testing.tRunner(0x10a34060, 0x6a2984)
        /home/pi/go/src/testing/testing.go:455 +0xa8
created by testing.RunTests
        /home/pi/go/src/testing/testing.go:560 +0x5ec

goroutine 46 [chan receive]:
testing.RunTests.func1(0x108cd000, 0x10a34000)
        /home/pi/go/src/testing/testing.go:564 +0x3c
created by testing.RunTests
        /home/pi/go/src/testing/testing.go:565 +0x660

goroutine 48 [chan receive]:
testing.RunTests.func1(0x108cd000, 0x10a34060)
        /home/pi/go/src/testing/testing.go:564 +0x3c
created by testing.RunTests
        /home/pi/go/src/testing/testing.go:565 +0x660

goroutine 57 [syscall]:   
syscall.Syscall(0x3, 0x6, 0x10a3c000, 0x600, 0x0, 0x0, 0x0)
        /home/pi/go/src/syscall/asm_linux_arm.s:17 +0x8
syscall.read(0x6, 0x10a3c000, 0x600, 0x600, 0x0, 0x0, 0x0)
        /home/pi/go/src/syscall/zsyscall_linux_arm.go:783 +0x78
syscall.Read(0x6, 0x10a3c000, 0x600, 0x600, 0x1, 0x0, 0x0)
        /home/pi/go/src/syscall/syscall_unix.go:160 +0x4c
os.(*File).read(0x10829cb8, 0x10a3c000, 0x600, 0x600, 0xb6416868, 0x0, 0x0)
        /home/pi/go/src/os/file_unix.go:211 +0x54
os.(*File).Read(0x10829cb8, 0x10a3c000, 0x600, 0x600, 0x1, 0x0, 0x0)
        /home/pi/go/src/os/file.go:95 +0x7c
bytes.(*Buffer).ReadFrom(0x10855ba8, 0xb6416348, 0x10829cb8, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/bytes/buffer.go:173 +0x22c
io.copyBuffer(0xb6416820, 0x10855ba8, 0xb6416348, 0x10829cb8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/pi/go/src/io/io.go:375 +0x124
io.Copy(0xb6416820, 0x10855ba8, 0xb6416348, 0x10829cb8, 0x12df4, 0x0, 0x0, 0x0)
        /home/pi/go/src/io/io.go:351 +0x64
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
        /home/pi/go/src/os/exec/exec.go:232 +0x94
os/exec.(*Cmd).Start.func1(0x10a3a5d0, 0x10866f00)
        /home/pi/go/src/os/exec/exec.go:339 +0x1c
created by os/exec.(*Cmd).Start
        /home/pi/go/src/os/exec/exec.go:340 +0x840

goroutine 56 [syscall]:   
syscall.Syscall(0x3, 0x4, 0x10875a00, 0x200, 0x0, 0x0, 0x0)
        /home/pi/go/src/syscall/asm_linux_arm.s:17 +0x8
syscall.read(0x4, 0x10875a00, 0x200, 0x200, 0x0, 0x0, 0x0)
        /home/pi/go/src/syscall/zsyscall_linux_arm.go:783 +0x78
syscall.Read(0x4, 0x10875a00, 0x200, 0x200, 0x1, 0x0, 0x0)
        /home/pi/go/src/syscall/syscall_unix.go:160 +0x4c
os.(*File).read(0x10829c98, 0x10875a00, 0x200, 0x200, 0xb6416868, 0x0, 0x0)
        /home/pi/go/src/os/file_unix.go:211 +0x54
os.(*File).Read(0x10829c98, 0x10875a00, 0x200, 0x200, 0x1, 0x0, 0x0)
        /home/pi/go/src/os/file.go:95 +0x7c
bytes.(*Buffer).ReadFrom(0x10855b50, 0xb6416348, 0x10829c98, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/src/bytes/buffer.go:173 +0x22c
io.copyBuffer(0xb6416820, 0x10855b50, 0xb6416348, 0x10829c98, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/pi/go/src/io/io.go:375 +0x124
io.Copy(0xb6416820, 0x10855b50, 0xb6416348, 0x10829c98, 0x12df4, 0x0, 0x0, 0x0)
        /home/pi/go/src/io/io.go:351 +0x64
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
        /home/pi/go/src/os/exec/exec.go:232 +0x94
os/exec.(*Cmd).Start.func1(0x10a3a5b0, 0x10866f00)
        /home/pi/go/src/os/exec/exec.go:339 +0x1c
created by os/exec.(*Cmd).Start
        /home/pi/go/src/os/exec/exec.go:340 +0x840

trap    0x6
error   0x0
oldmask 0x0
r0      0x5b34
r1      0x10849cd4
r2      0x0
r3      0x1081fa40
r4      0x0
r5      0x0
r6      0x6
r7      0x72
r8      0x1092e4e0
r9      0x0
r10     0x1092e410
fp      0x6a4694
ip      0x1092e515
sp      0x10849c84
lr      0x7045c
pc      0x2748e4
cpsr    0x60000010
fault   0x0
*** Test killed with quit: ran too long (5m0s).
FAIL    cmd/go  300.082s  
ok      cmd/gofmt       2.030s
ok      cmd/internal/goobj      0.070s
ok      cmd/internal/obj        0.073s
ok      cmd/internal/obj/x86    0.695s
ok      cmd/internal/rsc.io/arm/armasm  0.273s
ok      cmd/internal/rsc.io/x86/x86asm  4.134s
ok      cmd/newlink     0.316s
ok      cmd/nm  26.345s   
ok      cmd/objdump     76.693s
ok      cmd/pack        57.140s
ok      cmd/pprof/internal/profile      0.046s
ok      cmd/vet 134.648s  
2015/07/18 19:11:49 Failed: exit status 1
```

**Comment by bradfitz** [comment]
Looks like a probably dup of #11779 (just too slow).
