### ISSUE TITLE
runtime: frame cmd/compile/internal/gc.(*yyParserImpl).Parse untyped args 859530599120+32

### ISSUE THREAD

**Issue by titanous** [golang/go#11787]
```text
$ go version
go version go1.5beta2 linux/amd64
$ uname -a
Linux flynn 3.19.0-22-generic #22~14.04.1-Ubuntu SMP Wed Jun 17 10:03:13 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

While running `go test`:

```text
WORK=/tmp/go-build778471220
mkdir -p $WORK/github.com/flynn/flynn/router/proxy/_test/github.com/flynn/flynn/router/
mkdir -p $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa/_obj/
mkdir -p $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/
mkdir -p $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/
mkdir -p $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/
cd /home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa
/vagrant/util/_toolchain/go/pkg/tool/linux_amd64/compile -o $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa.a -trimpath $WORK -p github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa -buildid c13f10f0f394750003bd4f6eda2844332ffe73c9 -D _/home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa -I $WORK -pack -asmhdr $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa/_obj/go_asm.h ./hsalsa20.go ./salsa208.go ./salsa20_amd64.go
cd /home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305
/vagrant/util/_toolchain/go/pkg/tool/linux_amd64/compile -o $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305.a -trimpath $WORK -p github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305 -buildid 98ac4b17e9c7615cd4e12c8d41cf91187390c708 -D _/home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305 -I $WORK -pack -asmhdr $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/go_asm.h ./poly1305.go ./sum_amd64.go
cd /home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa
/vagrant/util/_toolchain/go/pkg/tool/linux_amd64/asm -o $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa/_obj/salsa2020_amd64.o -trimpath $WORK -I $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa/_obj/ -I /vagrant/util/_toolchain/go/pkg/include -D GOOS_linux -D GOARCH_amd64 ./salsa2020_amd64.s
/vagrant/util/_toolchain/go/pkg/tool/linux_amd64/old6a -o $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa/_obj/salsa2020_amd64.o.new -trimpath $WORK -I $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa/_obj/ -I /vagrant/util/_toolchain/go/pkg/include -D GOOS_linux -D GOARCH_amd64 ./salsa2020_amd64.s
pack r $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa.a $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa/_obj/salsa2020_amd64.o # internal
# github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305
runtime: frame cmd/compile/internal/gc.(*yyParserImpl).Parse untyped args 859530599120+32
fatal error: missing stackmap

runtime stack:
runtime.throw(0x83f960, 0x10)
	/usr/local/go/src/runtime/panic.go:527 +0x96 fp=0x7fffd5222340 sp=0x7fffd5222328
runtime.adjustframe(0x7fffd52224d0, 0x7fffd52225b0, 0x1)
	/usr/local/go/src/runtime/stack1.go:530 +0x611 fp=0x7fffd52223f8 sp=0x7fffd5222340
runtime.gentraceback(0x635010, 0xc820041ac8, 0x0, 0xc820000180, 0x0, 0x0, 0x7fffffff, 0x896968, 0x7fffd52225b0, 0x0, ...)
	/usr/local/go/src/runtime/traceback.go:336 +0xa7e fp=0x7fffd5222528 sp=0x7fffd52223f8
runtime.copystack(0xc820000180, 0x4000)
	/usr/local/go/src/runtime/stack1.go:616 +0x1a7 fp=0x7fffd5222618 sp=0x7fffd5222528
runtime.newstack()
	/usr/local/go/src/runtime/stack1.go:801 +0xb9b fp=0x7fffd5222790 sp=0x7fffd5222618
runtime.morestack()
	/usr/local/go/src/runtime/asm_amd64.s:330 +0x82 fp=0x7fffd5222798 sp=0x7fffd5222790

goroutine 1 [copystack]:
cmd/compile/internal/gc.(*yyParserImpl).Parse(0xc820082038, 0x7f3206d44700, 0xda37f8, 0xc820041b08)
	yaccpar:157 fp=0xc820041ad0 sp=0xc820041ac8
cmd/compile/internal/gc.yyparse()
	/usr/local/go/src/cmd/compile/internal/gc/lex.go:1849 +0xb4 fp=0xc820041b10 sp=0xc820041ad0
cmd/compile/internal/gc.Main()
	/usr/local/go/src/cmd/compile/internal/gc/lex.go:348 +0x1b6f fp=0xc820041e10 sp=0xc820041b10
cmd/compile/internal/amd64.Main()
	/usr/local/go/src/cmd/compile/internal/amd64/galign.go:127 +0x58d fp=0xc820041e78 sp=0xc820041e10
main.main()
	/usr/local/go/src/cmd/compile/main.go:26 +0x189 fp=0xc820041f50 sp=0xc820041e78
runtime.main()
	/usr/local/go/src/runtime/proc.go:111 +0x2bf fp=0xc820041fa0 sp=0xc820041f50
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820041fa8 sp=0xc820041fa0

goroutine 2 [force gc (idle)]:
runtime.gopark(0x896bb8, 0xc7c6b0, 0x81bc20, 0xf, 0x14, 0x1)
	/usr/local/go/src/runtime/proc.go:185 +0x169 fp=0xc82002e758 sp=0xc82002e730
runtime.goparkunlock(0xc7c6b0, 0x81bc20, 0xf, 0xc820000114, 0x1)
	/usr/local/go/src/runtime/proc.go:191 +0x54 fp=0xc82002e790 sp=0xc82002e758
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:152 +0xb8 fp=0xc82002e7c0 sp=0xc82002e790
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002e7c8 sp=0xc82002e7c0
created by runtime.init.4
	/usr/local/go/src/runtime/proc.go:141 +0x2b

goroutine 3 [GC sweep wait]:
runtime.gopark(0x896bb8, 0xc7c880, 0x817630, 0xd, 0x41c314, 0x1)
	/usr/local/go/src/runtime/proc.go:185 +0x169 fp=0xc82002ef48 sp=0xc82002ef20
runtime.goparkunlock(0xc7c880, 0x817630, 0xd, 0x14, 0x1)
	/usr/local/go/src/runtime/proc.go:191 +0x54 fp=0xc82002ef80 sp=0xc82002ef48
runtime.bgsweep(0xc82001a070)
	/usr/local/go/src/runtime/mgcsweep.go:51 +0xb1 fp=0xc82002efb8 sp=0xc82002ef80
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002efc0 sp=0xc82002efb8
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:200 +0x53

goroutine 17 [finalizer wait]:
runtime.gopark(0x896bb8, 0xda3728, 0x81b840, 0xe, 0x14, 0x1)
	/usr/local/go/src/runtime/proc.go:185 +0x169 fp=0xc82002a718 sp=0xc82002a6f0
runtime.goparkunlock(0xda3728, 0x81b840, 0xe, 0x14, 0x1)
	/usr/local/go/src/runtime/proc.go:191 +0x54 fp=0xc82002a750 sp=0xc82002a718
runtime.runfinq()
	/usr/local/go/src/runtime/mfinal.go:154 +0xaa fp=0xc82002a7c0 sp=0xc82002a750
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002a7c8 sp=0xc82002a7c0
created by runtime.createfing
	/usr/local/go/src/runtime/mfinal.go:135 +0x60
$WORK/github.com/flynn/flynn/router/proxy/_test/proxy.test -test.run=xxxxx
FAIL	github.com/flynn/flynn/router/proxy [build failed]
```

This happens pretty rarely (less than 1 in 800 builds).

Core dump: https://cl.ly/3w3v1J1A0g44

**Comment by titanous** [comment]
I found the core dump from this crash: http://cl.ly/3w3v1J1A0g44

**Comment by ianlancetaylor** [comment]
CC @randall77

**Comment by rsc** [comment]
Dup of #11792.
