### ISSUE TITLE
cmd/compile: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by titanous** [golang/go#11788]
```text
$ go version
go version go1.5beta2 linux/amd64
$ uname -a
Linux flynn 3.19.0-22-generic #22~14.04.1-Ubuntu SMP Wed Jun 17 10:03:13 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

While running `go test`:

```text
WORK=/tmp/go-build719717523
mkdir -p $WORK/github.com/flynn/flynn/router/proxy/_test/github.com/flynn/flynn/router/
mkdir -p $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/
mkdir -p $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/
mkdir -p $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa/_obj/
mkdir -p $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/
cd /home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa
/vagrant/util/_toolchain/go/pkg/tool/linux_amd64/compile -o $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa.a -trimpath $WORK -p github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa -buildid c13f10f0f394750003bd4f6eda2844332ffe73c9 -D _/home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa -I $WORK -pack -asmhdr $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa/_obj/go_asm.h ./hsalsa20.go ./salsa208.go ./salsa20_amd64.go
cd /home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305
/vagrant/util/_toolchain/go/pkg/tool/linux_amd64/compile -o $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305.a -trimpath $WORK -p github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305 -buildid 98ac4b17e9c7615cd4e12c8d41cf91187390c708 -D _/home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305 -I $WORK -pack -asmhdr $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/go_asm.h ./poly1305.go ./sum_amd64.go
/vagrant/util/_toolchain/go/pkg/tool/linux_amd64/asm -o $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/const_amd64.o -trimpath $WORK -I $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/ -I /vagrant/util/_toolchain/go/pkg/include -D GOOS_linux -D GOARCH_amd64 ./const_amd64.s
/vagrant/util/_toolchain/go/pkg/tool/linux_amd64/old6a -o $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/const_amd64.o.new -trimpath $WORK -I $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/ -I /vagrant/util/_toolchain/go/pkg/include -D GOOS_linux -D GOARCH_amd64 ./const_amd64.s
/vagrant/util/_toolchain/go/pkg/tool/linux_amd64/asm -o $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/poly1305_amd64.o -trimpath $WORK -I $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/ -I /vagrant/util/_toolchain/go/pkg/include -D GOOS_linux -D GOARCH_amd64 ./poly1305_amd64.s
# github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xa pc=0x644496]

goroutine 1 [running]:
runtime.gopanic(0x7d1ae0, 0xc820010130)
	/usr/local/go/src/runtime/panic.go:461 +0x3fe fp=0xc8200b17b8 sp=0xc8200b1738
runtime.panicmem()
	/usr/local/go/src/runtime/panic.go:42 +0x49 fp=0xc8200b17e0 sp=0xc8200b17b8
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:24 +0x2ba fp=0xc8200b1830 sp=0xc8200b17e0
cmd/compile/internal/gc.(*yyParserImpl).Parse(0xc820072040, 0x7fd2bd3d1700, 0xda37f8, 0x0)
	go.y:1467 +0xf486 fp=0xc8200b5ab0 sp=0xc8200b1830
cmd/compile/internal/gc.yyparse()
	/usr/local/go/src/cmd/compile/internal/gc/lex.go:1849 +0xb4 fp=0xc8200b5af0 sp=0xc8200b5ab0
cmd/compile/internal/gc.Main()
	/usr/local/go/src/cmd/compile/internal/gc/lex.go:348 +0x1b6f fp=0xc8200b5df0 sp=0xc8200b5af0
cmd/compile/internal/amd64.Main()
	/usr/local/go/src/cmd/compile/internal/amd64/galign.go:127 +0x58d fp=0xc8200b5e58 sp=0xc8200b5df0
main.main()
	/usr/local/go/src/cmd/compile/main.go:26 +0x189 fp=0xc8200b5f30 sp=0xc8200b5e58
runtime.main()
	/usr/local/go/src/runtime/proc.go:111 +0x2bf fp=0xc8200b5f80 sp=0xc8200b5f30
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8200b5f88 sp=0xc8200b5f80

goroutine 2 [force gc (idle)]:
runtime.gopark(0x896bb8, 0xc7c6b0, 0x81bc20, 0xf, 0x14, 0x1)
	/usr/local/go/src/runtime/proc.go:185 +0x169 fp=0xc82002e758 sp=0xc82002e730
runtime.goparkunlock(0xc7c6b0, 0x81bc20, 0xf, 0xc820000114, 0x1)
	/usr/local/go/src/runtime/proc.go:191 +0x54 fp=0xc82002e790 sp=0xc82002e758
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:152 +0xb8 fp=0xc82002e7c0 sp=0xc82002e790
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002e7c8 sp=0xc82002e7c0
created by runtime.init.4
	/usr/local/go/src/runtime/proc.go:141 +0x2b

goroutine 3 [GC sweep wait]:
runtime.gopark(0x896bb8, 0xc7c880, 0x817630, 0xd, 0x41c314, 0x1)
	/usr/local/go/src/runtime/proc.go:185 +0x169 fp=0xc82002ef48 sp=0xc82002ef20
runtime.goparkunlock(0xc7c880, 0x817630, 0xd, 0x14, 0x1)
	/usr/local/go/src/runtime/proc.go:191 +0x54 fp=0xc82002ef80 sp=0xc82002ef48
runtime.bgsweep(0xc82001a070)
	/usr/local/go/src/runtime/mgcsweep.go:51 +0xb1 fp=0xc82002efb8 sp=0xc82002ef80
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002efc0 sp=0xc82002efb8
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:200 +0x53

goroutine 17 [finalizer wait]:
runtime.gopark(0x896bb8, 0xda3728, 0x81b840, 0xe, 0x14, 0x1)
	/usr/local/go/src/runtime/proc.go:185 +0x169 fp=0xc82002a718 sp=0xc82002a6f0
runtime.goparkunlock(0xda3728, 0x81b840, 0xe, 0x14, 0x1)
	/usr/local/go/src/runtime/proc.go:191 +0x54 fp=0xc82002a750 sp=0xc82002a718
runtime.runfinq()
	/usr/local/go/src/runtime/mfinal.go:154 +0xaa fp=0xc82002a7c0 sp=0xc82002a750
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002a7c8 sp=0xc82002a7c0
created by runtime.createfing
	/usr/local/go/src/runtime/mfinal.go:135 +0x60
/vagrant/util/_toolchain/go/pkg/tool/linux_amd64/old6a -o $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/poly1305_amd64.o.new -trimpath $WORK -I $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/ -I /vagrant/util/_toolchain/go/pkg/include -D GOOS_linux -D GOARCH_amd64 ./poly1305_amd64.s
pack r $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305.a $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/const_amd64.o $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/poly1305_amd64.o # internal
$WORK/github.com/flynn/flynn/router/proxy/_test/proxy.test -test.run=xxxxx
FAIL	github.com/flynn/flynn/router/proxy [build failed]
```

Core dump: https://cl.ly/1Q3m2Q0J0J3c

This happens rarely (less than 1 in 800 builds).

**Comment by ianlancetaylor** [comment]
CC @aclements @RLH

**Comment by titanous** [comment]
Not sure if this is the same:

```text
WORK=/tmp/go-build397946551
mkdir -p $WORK/github.com/flynn/flynn/router/proxy/_test/github.com/flynn/flynn/router/
mkdir -p $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/
mkdir -p $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/
mkdir -p $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa/_obj/
mkdir -p $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/
cd /home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa
/vagrant/util/_toolchain/go/pkg/tool/linux_amd64/compile -o $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa.a -trimpath $WORK -p github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa -buildid c13f10f0f394750003bd4f6eda2844332ffe73c9 -D _/home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa -I $WORK -pack -asmhdr $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa/_obj/go_asm.h ./hsalsa20.go ./salsa208.go ./salsa20_amd64.go
cd /home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305
/vagrant/util/_toolchain/go/pkg/tool/linux_amd64/compile -o $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305.a -trimpath $WORK -p github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305 -buildid 98ac4b17e9c7615cd4e12c8d41cf91187390c708 -D _/home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305 -I $WORK -pack -asmhdr $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/go_asm.h ./poly1305.go ./sum_amd64.go
/vagrant/util/_toolchain/go/pkg/tool/linux_amd64/asm -o $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/const_amd64.o -trimpath $WORK -I $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/ -I /vagrant/util/_toolchain/go/pkg/include -D GOOS_linux -D GOARCH_amd64 ./const_amd64.s
/vagrant/util/_toolchain/go/pkg/tool/linux_amd64/old6a -o $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/const_amd64.o.new -trimpath $WORK -I $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/ -I /vagrant/util/_toolchain/go/pkg/include -D GOOS_linux -D GOARCH_amd64 ./const_amd64.s
/vagrant/util/_toolchain/go/pkg/tool/linux_amd64/asm -o $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/poly1305_amd64.o -trimpath $WORK -I $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/ -I /vagrant/util/_toolchain/go/pkg/include -D GOOS_linux -D GOARCH_amd64 ./poly1305_amd64.s
/vagrant/util/_toolchain/go/pkg/tool/linux_amd64/old6a -o $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/poly1305_amd64.o.new -trimpath $WORK -I $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/ -I /vagrant/util/_toolchain/go/pkg/include -D GOOS_linux -D GOARCH_amd64 ./poly1305_amd64.s
# github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0x59b014]

goroutine 1 [running]:
runtime.gopanic(0x7d1ae0, 0xc820010130)
	/usr/local/go/src/runtime/panic.go:461 +0x3fe fp=0xc820319688 sp=0xc820319608
runtime.panicmem()
	/usr/local/go/src/runtime/panic.go:42 +0x49 fp=0xc8203196b0 sp=0xc820319688
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:24 +0x2ba fp=0xc820319700 sp=0xc8203196b0
cmd/compile/internal/gc.fixjmp(0xc8200aefc0)
	/usr/local/go/src/cmd/compile/internal/gc/popt.go:152 +0x364 fp=0xc8203197f8 sp=0xc820319700
cmd/compile/internal/gc.compile(0xc82018ecf0)
	/usr/local/go/src/cmd/compile/internal/gc/pgen.go:506 +0xd13 fp=0xc820319a68 sp=0xc8203197f8
cmd/compile/internal/gc.funccompile(0xc82018ecf0)
	/usr/local/go/src/cmd/compile/internal/gc/dcl.go:1480 +0x1c9 fp=0xc820319ae0 sp=0xc820319a68
cmd/compile/internal/gc.Main()
	/usr/local/go/src/cmd/compile/internal/gc/lex.go:473 +0x1f08 fp=0xc820319de0 sp=0xc820319ae0
cmd/compile/internal/amd64.Main()
	/usr/local/go/src/cmd/compile/internal/amd64/galign.go:127 +0x58d fp=0xc820319e48 sp=0xc820319de0
main.main()
	/usr/local/go/src/cmd/compile/main.go:26 +0x189 fp=0xc820319f20 sp=0xc820319e48
runtime.main()
	/usr/local/go/src/runtime/proc.go:111 +0x2bf fp=0xc820319f70 sp=0xc820319f20
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820319f78 sp=0xc820319f70

goroutine 2 [force gc (idle)]:
runtime.gopark(0x896bb8, 0xc7c6b0, 0x81bc20, 0xf, 0x14, 0x1)
	/usr/local/go/src/runtime/proc.go:185 +0x169 fp=0xc82002e758 sp=0xc82002e730
runtime.goparkunlock(0xc7c6b0, 0x81bc20, 0xf, 0xc820000114, 0x1)
	/usr/local/go/src/runtime/proc.go:191 +0x54 fp=0xc82002e790 sp=0xc82002e758
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:152 +0xb8 fp=0xc82002e7c0 sp=0xc82002e790
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002e7c8 sp=0xc82002e7c0
created by runtime.init.4
	/usr/local/go/src/runtime/proc.go:141 +0x2b

goroutine 3 [GC sweep wait]:
runtime.gopark(0x896bb8, 0xc7c880, 0x817630, 0xd, 0x41c314, 0x1)
	/usr/local/go/src/runtime/proc.go:185 +0x169 fp=0xc82002ef48 sp=0xc82002ef20
runtime.goparkunlock(0xc7c880, 0x817630, 0xd, 0x14, 0x1)
	/usr/local/go/src/runtime/proc.go:191 +0x54 fp=0xc82002ef80 sp=0xc82002ef48
runtime.bgsweep(0xc820018070)
	/usr/local/go/src/runtime/mgcsweep.go:51 +0xb1 fp=0xc82002efb8 sp=0xc82002ef80
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002efc0 sp=0xc82002efb8
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:200 +0x53

goroutine 4 [finalizer wait]:
runtime.gopark(0x896bb8, 0xda3728, 0x81b840, 0xe, 0x14, 0x1)
	/usr/local/go/src/runtime/proc.go:185 +0x169 fp=0xc82002f718 sp=0xc82002f6f0
runtime.goparkunlock(0xda3728, 0x81b840, 0xe, 0x14, 0x1)
	/usr/local/go/src/runtime/proc.go:191 +0x54 fp=0xc82002f750 sp=0xc82002f718
runtime.runfinq()
	/usr/local/go/src/runtime/mfinal.go:154 +0xaa fp=0xc82002f7c0 sp=0xc82002f750
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002f7c8 sp=0xc82002f7c0
created by runtime.createfing
	/usr/local/go/src/runtime/mfinal.go:135 +0x60
pack r $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305.a $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/const_amd64.o $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/poly1305_amd64.o # internal
$WORK/github.com/flynn/flynn/router/proxy/_test/proxy.test -test.run=xxxxx
FAIL	github.com/flynn/flynn/router/proxy [build failed]
```

Core dump: https://cl.ly/160q3n2N2g1b

**Comment by rsc** [comment]
Dup of #11792.
