### ISSUE TITLE
runtime: out of memory: cannot allocate -8410442019078995968-byte block

### ISSUE THREAD

**Issue by titanous** [golang/go#11789]
```text
$ go version
go version go1.5beta2 linux/amd64
$ uname -a
Linux flynn 3.19.0-22-generic #22~14.04.1-Ubuntu SMP Wed Jun 17 10:03:13 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

While running `go test`:

```text
WORK=/tmp/go-build607548415
mkdir -p $WORK/github.com/flynn/flynn/router/proxy/_test/github.com/flynn/flynn/router/
mkdir -p $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/
mkdir -p $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/
mkdir -p $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa/_obj/
mkdir -p $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/
cd /home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa
/vagrant/util/_toolchain/go/pkg/tool/linux_amd64/compile -o $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa.a -trimpath $WORK -p github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa -buildid c13f10f0f394750003bd4f6eda2844332ffe73c9 -D _/home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa -I $WORK -pack -asmhdr $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa/_obj/go_asm.h ./hsalsa20.go ./salsa208.go ./salsa20_amd64.go
cd /home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305
/vagrant/util/_toolchain/go/pkg/tool/linux_amd64/compile -o $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305.a -trimpath $WORK -p github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305 -buildid 98ac4b17e9c7615cd4e12c8d41cf91187390c708 -D _/home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305 -I $WORK -pack -asmhdr $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/go_asm.h ./poly1305.go ./sum_amd64.go
/vagrant/util/_toolchain/go/pkg/tool/linux_amd64/asm -o $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/const_amd64.o -trimpath $WORK -I $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/ -I /vagrant/util/_toolchain/go/pkg/include -D GOOS_linux -D GOARCH_amd64 ./const_amd64.s
cd /home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa
/vagrant/util/_toolchain/go/pkg/tool/linux_amd64/asm -o $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa/_obj/salsa2020_amd64.o -trimpath $WORK -I $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa/_obj/ -I /vagrant/util/_toolchain/go/pkg/include -D GOOS_linux -D GOARCH_amd64 ./salsa2020_amd64.s
cd /home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305
/vagrant/util/_toolchain/go/pkg/tool/linux_amd64/old6a -o $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/const_amd64.o.new -trimpath $WORK -I $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/ -I /vagrant/util/_toolchain/go/pkg/include -D GOOS_linux -D GOARCH_amd64 ./const_amd64.s
/vagrant/util/_toolchain/go/pkg/tool/linux_amd64/asm -o $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/poly1305_amd64.o -trimpath $WORK -I $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/ -I /vagrant/util/_toolchain/go/pkg/include -D GOOS_linux -D GOARCH_amd64 ./poly1305_amd64.s
/vagrant/util/_toolchain/go/pkg/tool/linux_amd64/old6a -o $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/poly1305_amd64.o.new -trimpath $WORK -I $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/ -I /vagrant/util/_toolchain/go/pkg/include -D GOOS_linux -D GOARCH_amd64 ./poly1305_amd64.s
pack r $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305.a $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/const_amd64.o $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/poly1305_amd64.o # internal
# github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa
runtime: out of memory: cannot allocate -8410442019078995968-byte block (1048576 in use)
fatal error: out of memory

runtime stack:
runtime.throw(0x614b00, 0xd)
	/usr/local/go/src/runtime/panic.go:527 +0x96 fp=0x7fff11032078 sp=0x7fff11032060
runtime.largeAlloc(0x8b481b8b48c61c8d, 0x0, 0x7f75bd0b2078)
	/usr/local/go/src/runtime/malloc.go:729 +0xbe fp=0x7fff110320c0 sp=0x7fff11032078
runtime.mallocgc.func3()
	/usr/local/go/src/runtime/malloc.go:634 +0x33 fp=0x7fff110320e8 sp=0x7fff110320c0
runtime.systemstack(0x710e18)
	/usr/local/go/src/runtime/asm_amd64.s:262 +0x7c fp=0x7fff110320f0 sp=0x7fff110320e8
runtime.mstart()
	/usr/local/go/src/runtime/proc1.go:668 fp=0x7fff110320f8 sp=0x7fff110320f0

goroutine 1 [running, locked to thread]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc820041d28 sp=0xc820041d20
runtime.mallocgc(0x8b481b8b48c61c8d, 0x5e5d40, 0x0, 0xc820032008)
	/usr/local/go/src/runtime/malloc.go:635 +0x972 fp=0xc820041df8 sp=0xc820041d28
runtime.newobject(0x5e5d40, 0xc820032008)
	/usr/local/go/src/runtime/malloc.go:742 +0x42 fp=0xc820041e20 sp=0xc820041df8
os.NewFile(0x0, 0x60ff70, 0xa, 0xc8200102c0)
	/usr/local/go/src/os/file_unix.go:54 +0x5f fp=0xc820041e78 sp=0xc820041e20
os.init()
	/usr/local/go/src/os/file.go:50 +0x288 fp=0xc820041ec0 sp=0xc820041e78
fmt.init()
	/usr/local/go/src/fmt/scan.go:1191 +0x56 fp=0xc820041f20 sp=0xc820041ec0
flag.init()
	/usr/local/go/src/flag/flag.go:957 +0x47 fp=0xc820041f48 sp=0xc820041f20
main.init()
	/usr/local/go/src/cmd/asm/main.go:67 +0x3b fp=0xc820041f50 sp=0xc820041f48
runtime.main()
	/usr/local/go/src/runtime/proc.go:100 +0x28e fp=0xc820041fa0 sp=0xc820041f50
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820041fa8 sp=0xc820041fa0

goroutine 2 [force gc (idle)]:
runtime.gopark(0x6586c0, 0x7107a0, 0x6138d0, 0xf, 0x14, 0x1)
	/usr/local/go/src/runtime/proc.go:185 +0x169 fp=0xc82002e758 sp=0xc82002e730
runtime.goparkunlock(0x7107a0, 0x6138d0, 0xf, 0xc820000114, 0x1)
	/usr/local/go/src/runtime/proc.go:191 +0x54 fp=0xc82002e790 sp=0xc82002e758
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:152 +0xb8 fp=0xc82002e7c0 sp=0xc82002e790
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002e7c8 sp=0xc82002e7c0
created by runtime.init.4
	/usr/local/go/src/runtime/proc.go:141 +0x2b

goroutine 3 [GC sweep wait]:
runtime.gopark(0x6586c0, 0x710900, 0x6108d0, 0xd, 0x41cc14, 0x1)
	/usr/local/go/src/runtime/proc.go:185 +0x169 fp=0xc82002ef48 sp=0xc82002ef20
runtime.goparkunlock(0x710900, 0x6108d0, 0xd, 0x14, 0x1)
	/usr/local/go/src/runtime/proc.go:191 +0x54 fp=0xc82002ef80 sp=0xc82002ef48
runtime.bgsweep(0xc82001a070)
	/usr/local/go/src/runtime/mgcsweep.go:51 +0xb1 fp=0xc82002efb8 sp=0xc82002ef80
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002efc0 sp=0xc82002efb8
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:200 +0x53
$WORK/github.com/flynn/flynn/router/proxy/_test/proxy.test -test.run=xxxxx
FAIL	github.com/flynn/flynn/router/proxy [build failed]
```

Core dump: https://cl.ly/0D320B0E1A28

This happens pretty rarely (less than 1 in 1000 builds).

**Comment by ianlancetaylor** [comment]
CC @aclements @RLH

**Comment by rsc** [comment]
Dup of #11792.
