### ISSUE TITLE
runtime: SIGILL during compilation

### ISSUE THREAD

**Issue by titanous** [golang/go#11795]
```text
$ go version
go version go1.5beta2 linux/amd64
$ uname -a
Linux flynn 3.19.0-22-generic #22~14.04.1-Ubuntu SMP Wed Jun 17 10:03:13 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

While running `go test`:

```text
WORK=/tmp/go-build680090135
mkdir -p $WORK/github.com/flynn/flynn/router/proxy/_test/github.com/flynn/flynn/router/
mkdir -p $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/
mkdir -p $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/
mkdir -p $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa/_obj/
mkdir -p $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/
cd /home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa
/vagrant/util/_toolchain/go/pkg/tool/linux_amd64/compile -o $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa.a -trimpath $WORK -p github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa -buildid c13f10f0f394750003bd4f6eda2844332ffe73c9 -D _/home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa -I $WORK -pack -asmhdr $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa/_obj/go_asm.h ./hsalsa20.go ./salsa208.go ./salsa20_amd64.go
cd /home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305
/vagrant/util/_toolchain/go/pkg/tool/linux_amd64/compile -o $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305.a -trimpath $WORK -p github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305 -buildid 98ac4b17e9c7615cd4e12c8d41cf91187390c708 -D _/home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305 -I $WORK -pack -asmhdr $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/go_asm.h ./poly1305.go ./sum_amd64.go
/vagrant/util/_toolchain/go/pkg/tool/linux_amd64/asm -o $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/const_amd64.o -trimpath $WORK -I $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/ -I /vagrant/util/_toolchain/go/pkg/include -D GOOS_linux -D GOARCH_amd64 ./const_amd64.s
cd /home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa
/vagrant/util/_toolchain/go/pkg/tool/linux_amd64/asm -o $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa/_obj/salsa2020_amd64.o -trimpath $WORK -I $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa/_obj/ -I /vagrant/util/_toolchain/go/pkg/include -D GOOS_linux -D GOARCH_amd64 ./salsa2020_amd64.s
cd /home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305
/vagrant/util/_toolchain/go/pkg/tool/linux_amd64/old6a -o $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/const_amd64.o.new -trimpath $WORK -I $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305/_obj/ -I /vagrant/util/_toolchain/go/pkg/include -D GOOS_linux -D GOARCH_amd64 ./const_amd64.s
cd /home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa
/vagrant/util/_toolchain/go/pkg/tool/linux_amd64/old6a -o $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa/_obj/salsa2020_amd64.o.new -trimpath $WORK -I $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa/_obj/ -I /vagrant/util/_toolchain/go/pkg/include -D GOOS_linux -D GOARCH_amd64 ./salsa2020_amd64.s
pack r $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa.a $WORK/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/salsa20/salsa/_obj/salsa2020_amd64.o # internal
# github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/poly1305
SIGILL: illegal instruction
PC=0x5117f0 m=0

goroutine 1 [running, locked to thread]:
syscall.init()
	/usr/local/go/src/syscall/ztypes_linux_amd64.go:712 fp=0xc820045e48 sp=0xc820045e40
os.init()
	/usr/local/go/src/os/types_notwin.go:25 +0x4c fp=0xc820045e90 sp=0xc820045e48
fmt.init()
	/usr/local/go/src/fmt/scan.go:1191 +0x56 fp=0xc820045ef0 sp=0xc820045e90
flag.init()
	/usr/local/go/src/flag/flag.go:957 +0x47 fp=0xc820045f18 sp=0xc820045ef0
cmd/internal/asm.init()
	/usr/local/go/src/cmd/internal/asm/macbody.go:855 +0x47 fp=0xc820045f48 sp=0xc820045f18
main.init()
	a.y:732 +0x3b fp=0xc820045f50 sp=0xc820045f48
runtime.main()
	/usr/local/go/src/runtime/proc.go:100 +0x28e fp=0xc820045fa0 sp=0xc820045f50
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820045fa8 sp=0xc820045fa0

goroutine 2 [force gc (idle)]:
runtime.gopark(0x5c7248, 0x6623d0, 0x58c760, 0xf, 0x14, 0x1)
	/usr/local/go/src/runtime/proc.go:185 +0x169 fp=0xc82002e758 sp=0xc82002e730
runtime.goparkunlock(0x6623d0, 0x58c760, 0xf, 0xc820000114, 0x1)
	/usr/local/go/src/runtime/proc.go:191 +0x54 fp=0xc82002e790 sp=0xc82002e758
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:152 +0xb8 fp=0xc82002e7c0 sp=0xc82002e790
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002e7c8 sp=0xc82002e7c0
created by runtime.init.4
	/usr/local/go/src/runtime/proc.go:141 +0x2b

goroutine 3 [GC sweep wait]:
runtime.gopark(0x5c7248, 0x662580, 0x589e20, 0xd, 0x426014, 0x1)
	/usr/local/go/src/runtime/proc.go:185 +0x169 fp=0xc82002ef48 sp=0xc82002ef20
runtime.goparkunlock(0x662580, 0x589e20, 0xd, 0x14, 0x1)
	/usr/local/go/src/runtime/proc.go:191 +0x54 fp=0xc82002ef80 sp=0xc82002ef48
runtime.bgsweep(0xc820018070)
	/usr/local/go/src/runtime/mgcsweep.go:51 +0xb1 fp=0xc82002efb8 sp=0xc82002ef80
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002efc0 sp=0xc82002efb8
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:200 +0x53

rax    0x7f8a6cfcb028
rbx    0x2
rcx    0xc820000180
rdx    0x17f0
rdi    0x4523f0
rsi    0x10
rbp    0x0
rsp    0xc820045e40
r8     0x46771
r9     0x591530
r10    0x556b20
r11    0x286
r12    0x10
r13    0x5c6c76
r14    0x8
r15    0x0
rip    0x5117f0
rflags 0x10202
cs     0x33
fs     0x0
gs     0x0

-----

SIGQUIT: quit
PC=0x460303 m=1

goroutine 0 [idle]:
runtime.futex(0x6628e0, 0x0, 0xc820043ea0, 0x0, 0x0, 0x46015c, 0x3c, 0x0, 0x417494, 0x6628e0, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:289 +0x23 fp=0xc820043e70 sp=0xc820043e68
runtime.futexsleep(0x6628e0, 0x0, 0xdf8475800)
	/usr/local/go/src/runtime/os1_linux.go:56 +0xf0 fp=0xc820043eb8 sp=0xc820043e70
runtime.notetsleep_internal(0x6628e0, 0xdf8475800, 0xc820000480)
	/usr/local/go/src/runtime/lock_futex.go:167 +0x134 fp=0xc820043ee8 sp=0xc820043eb8
runtime.notetsleep(0x6628e0, 0xdf8475800, 0x0)
	/usr/local/go/src/runtime/lock_futex.go:187 +0x71 fp=0xc820043f08 sp=0xc820043ee8
runtime.sysmon()
	/usr/local/go/src/runtime/proc1.go:2971 +0x4aa fp=0xc820043f90 sp=0xc820043f08
runtime.mstart1()
	/usr/local/go/src/runtime/proc1.go:715 +0xf7 fp=0xc820043fb0 sp=0xc820043f90
runtime.mstart()
	/usr/local/go/src/runtime/proc1.go:685 +0x72 fp=0xc820043fc0 sp=0xc820043fb0
rax    0xfffffffffffffffc
rbx    0xc820043ea0
rcx    0xffffffffffffffff
rdx    0x0
rdi    0x6628e0
rsi    0x0
rbp    0x0
rsp    0xc820043e68
r8     0x0
r9     0x0
r10    0xc820043ea0
r11    0x246
r12    0x4361a0
r13    0x5c6d78
r14    0x8
r15    0x0
rip    0x460303
rflags 0x246
cs     0x33
fs     0x0
gs     0x0

-----

SIGQUIT: quit
PC=0x460301 m=2

goroutine 0 [idle]:
runtime.futex(0xc820034588, 0x0, 0x0, 0x0, 0x0, 0x662820, 0x0, 0x0, 0x41731a, 0xc820034588, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:288 +0x21 fp=0xc82003fe10 sp=0xc82003fe08
runtime.futexsleep(0xc820034588, 0x0, 0xffffffffffffffff)
	/usr/local/go/src/runtime/os1_linux.go:39 +0x53 fp=0xc82003fe58 sp=0xc82003fe10
runtime.notesleep(0xc820034588)
	/usr/local/go/src/runtime/lock_futex.go:142 +0xaa fp=0xc82003fe80 sp=0xc82003fe58
runtime.stopm()
	/usr/local/go/src/runtime/proc1.go:1122 +0x124 fp=0xc82003fea8 sp=0xc82003fe80
runtime.findrunnable(0xc820023500, 0x0)
	/usr/local/go/src/runtime/proc1.go:1508 +0x6bf fp=0xc82003ff28 sp=0xc82003fea8
runtime.schedule()
	/usr/local/go/src/runtime/proc1.go:1617 +0x282 fp=0xc82003ff60 sp=0xc82003ff28
runtime.park_m(0xc820000600)
	/usr/local/go/src/runtime/proc1.go:1676 +0x1ac fp=0xc82003ff88 sp=0xc82003ff60
runtime.mcall(0x0)
	/usr/local/go/src/runtime/asm_amd64.s:204 +0x5e fp=0xc82003ff98 sp=0xc82003ff88
rax    0xca
rbx    0x0
rcx    0xffffffffffffffff
rdx    0x0
rdi    0xc820034588
rsi    0x0
rbp    0x1
rsp    0xc82003fe08
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x4361a0
r13    0x5c6d78
r14    0x8
r15    0x0
rip    0x460301
rflags 0x286
cs     0x33
fs     0x0
gs     0x0

-----

SIGQUIT: quit
PC=0x460301 m=3

goroutine 0 [idle]:
runtime.futex(0xc820034a08, 0x0, 0x0, 0x0, 0x0, 0x662820, 0x0, 0x0, 0x41731a, 0xc820034a08, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:288 +0x21 fp=0xc820041e70 sp=0xc820041e68
runtime.futexsleep(0xc820034a08, 0x0, 0xffffffffffffffff)
	/usr/local/go/src/runtime/os1_linux.go:39 +0x53 fp=0xc820041eb8 sp=0xc820041e70
runtime.notesleep(0xc820034a08)
	/usr/local/go/src/runtime/lock_futex.go:142 +0xaa fp=0xc820041ee0 sp=0xc820041eb8
runtime.stopm()
	/usr/local/go/src/runtime/proc1.go:1122 +0x124 fp=0xc820041f08 sp=0xc820041ee0
runtime.startlockedm(0xc820000180)
	/usr/local/go/src/runtime/proc1.go:1292 +0xca fp=0xc820041f28 sp=0xc820041f08
runtime.schedule()
	/usr/local/go/src/runtime/proc1.go:1624 +0x2b5 fp=0xc820041f60 sp=0xc820041f28
runtime.park_m(0xc820000d80)
	/usr/local/go/src/runtime/proc1.go:1676 +0x1ac fp=0xc820041f88 sp=0xc820041f60
runtime.mcall(0x0)
	/usr/local/go/src/runtime/asm_amd64.s:204 +0x5e fp=0xc820041f98 sp=0xc820041f88
rax    0xca
rbx    0x0
rcx    0xffffffffffffffff
rdx    0x0
rdi    0xc820034a08
rsi    0x0
rbp    0x1
rsp    0xc820041e68
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x4361a0
r13    0x5c6d78
r14    0x8
r15    0x0
rip    0x460301
rflags 0x286
cs     0x33
fs     0x0
gs     0x0

-----

SIGQUIT: quit
PC=0x460301 m=4

goroutine 0 [idle]:
runtime.futex(0xc82005e108, 0x0, 0x0, 0x0, 0x0, 0x662820, 0x0, 0x0, 0x41731a, 0xc82005e108, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:288 +0x21 fp=0xc82006fe40 sp=0xc82006fe38
runtime.futexsleep(0xc82005e108, 0x0, 0xffffffffffffffff)
	/usr/local/go/src/runtime/os1_linux.go:39 +0x53 fp=0xc82006fe88 sp=0xc82006fe40
runtime.notesleep(0xc82005e108)
	/usr/local/go/src/runtime/lock_futex.go:142 +0xaa fp=0xc82006feb0 sp=0xc82006fe88
runtime.stopm()
	/usr/local/go/src/runtime/proc1.go:1122 +0x124 fp=0xc82006fed8 sp=0xc82006feb0
runtime.findrunnable(0xc820024a00, 0x0)
	/usr/local/go/src/runtime/proc1.go:1508 +0x6bf fp=0xc82006ff58 sp=0xc82006fed8
runtime.schedule()
	/usr/local/go/src/runtime/proc1.go:1617 +0x282 fp=0xc82006ff90 sp=0xc82006ff58
runtime.mstart1()
	/usr/local/go/src/runtime/proc1.go:725 +0x129 fp=0xc82006ffb0 sp=0xc82006ff90
runtime.mstart()
	/usr/local/go/src/runtime/proc1.go:685 +0x72 fp=0xc82006ffc0 sp=0xc82006ffb0
rax    0xca
rbx    0x0
rcx    0xffffffffffffffff
rdx    0x0
rdi    0xc82005e108
rsi    0x0
rbp    0x1
rsp    0xc82006fe38
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x4361a0
r13    0x5c6d78
r14    0x8
r15    0x0
rip    0x460301
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
$WORK/github.com/flynn/flynn/router/proxy/_test/proxy.test -test.run=xxxxx
FAIL	github.com/flynn/flynn/router/proxy [build failed]
```

Core dump: https://s3.amazonaws.com/flynn-temp/sigill_core.gz

This happens rarely (less than 1 in 1000 builds).

**Comment by ianlancetaylor** [comment]
CC @aclements @RLH

**Comment by aclements** [comment]
@titanous, can you also post the pkg/tool/linux_amd64/old6a binary that this core goes with? Or did this (and your other bugs) come from the binary distribution of 1.5beta2 from golang.org?

**Comment by titanous** [comment]
@aclements This was using the binary distribution with SHA1 `6fede71082a2f57c13f2521ecd054b86ae77d0e5`.

**Comment by rsc** [comment]
Dup of #11792.
