### ISSUE TITLE
runtime: fatal error: runtime: address space conflict

### ISSUE THREAD

**Issue by mikioh** [golang/go#11993]
See http://build.golang.org/log/ca57dbe5b2989d7196ba34f33ada9112c80c286b.
```
runtime: address space conflict: map(0x0) = 0x40539000
fatal error: runtime: address space conflict

runtime stack:
runtime.throw(0x2092e0, 0x1f)
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/panic.go:527 +0x78
runtime.sysMap(0x0, 0x100000, 0x107ebe00, 0x2d3610)
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/mem_bsd.go:81 +0x108
runtime.mHeap_SysAlloc(0x2c0fe8, 0x100000, 0x2ac0e0)
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/malloc.go:423 +0x160
runtime.mHeap_Grow(0x2c0fe8, 0x80, 0x0)
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/mheap.go:625 +0x68
runtime.mHeap_AllocSpanLocked(0x2c0fe8, 0x80, 0x10552540)
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/mheap.go:529 +0x6b8
runtime.mHeap_Alloc_m(0x2c0fe8, 0x80, 0x0, 0x1, 0x1e210)
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/mheap.go:422 +0x190
runtime.mHeap_Alloc.func1()
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/mheap.go:481 +0x40
runtime.systemstack(0x107ebf74)
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/asm_arm.s:256 +0xa8
runtime.mHeap_Alloc(0x2c0fe8, 0x80, 0x0, 0x404b0101, 0x105b4580)
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/mheap.go:482 +0x58
runtime.largeAlloc(0x100000, 0x1, 0x30400000)
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/malloc.go:727 +0x9c
runtime.mallocgc.func3()
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/malloc.go:634 +0x34
runtime.systemstack(0x105a7400)
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/asm_arm.s:242 +0x80
runtime.mstart()
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/proc1.go:674

goroutine 30 [running]:
runtime.systemstack_switch()
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/asm_arm.s:187 +0x4 fp=0x10576e64 sp=0x10576e60
runtime.mallocgc(0x100000, 0x1992d8, 0x1, 0x1)
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/malloc.go:635 +0x97c fp=0x10576ed0 sp=0x10576e64
runtime.newarray(0x1992d8, 0x100000, 0x30400000)
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/malloc.go:759 +0xe4 fp=0x10576ef0 sp=0x10576ed0
runtime.makeslice(0x194100, 0x100000, 0x0, 0x100000, 0x0, 0x0, 0x0, 0x0)
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/slice.go:32 +0x1d8 fp=0x10576f18 sp=0x10576ef0
runtime/trace_test.TestTraceStressStartStop.func1(0x12356580, 0x1235e1e0)
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/trace/trace_test.go:264 +0x280 fp=0x10576fd4 sp=0x10576f18
runtime.goexit()
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/asm_arm.s:1031 +0x4 fp=0x10576fd4 sp=0x10576fd4
created by runtime/trace_test.TestTraceStressStartStop
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/trace/trace_test.go:335 +0xa4

goroutine 1 [chan receive]:
testing.RunTests(0x22c964, 0x2bab20, 0x7, 0x7, 0x1)
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/testing/testing.go:562 +0x618
testing.(*M).Run(0x1053df7c, 0x12490)
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/testing/testing.go:494 +0x6c
main.main()
	runtime/trace/_test/_testmain.go:68 +0x118

goroutine 29 [runnable]:
time.Sleep(0xf4240, 0x0)
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/time.go:57 +0xcc
runtime/trace_test.TestTraceStressStartStop(0x1235e1e0)
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/trace/trace_test.go:342 +0x1ec
testing.tRunner(0x1235e1e0, 0x2bab5c)
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/testing/testing.go:456 +0xa8
created by testing.RunTests
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/testing/testing.go:561 +0x5ec

goroutine 36 [chan receive]:
runtime/trace_test.TestTraceStressStartStop.func1.2(0x12362000, 0x138d0000)
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/trace/trace_test.go:228 +0x2c
created by runtime/trace_test.TestTraceStressStartStop.func1
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/trace/trace_test.go:230 +0xc4

goroutine 8 [select (no cases)]:
runtime/trace_test.TestTraceSymbolize.func1()
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/trace/trace_stack_test.go:38 +0x14
created by runtime/trace_test.TestTraceSymbolize
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/trace/trace_stack_test.go:39 +0x1a8

goroutine 9 [chan send (nil chan)]:
runtime/trace_test.TestTraceSymbolize.func2()
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/trace/trace_stack_test.go:42 +0x34
created by runtime/trace_test.TestTraceSymbolize
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/trace/trace_stack_test.go:43 +0x1bc

goroutine 10 [chan receive (nil chan)]:
runtime/trace_test.TestTraceSymbolize.func3()
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/trace/trace_stack_test.go:46 +0x2c
created by runtime/trace_test.TestTraceSymbolize
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/trace/trace_stack_test.go:47 +0x1d0

goroutine 32 [runnable, locked to thread]:
runtime.Gosched()
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/proc.go:166 +0x10
runtime/trace_test.TestTraceStressStartStop.func1.5(0x12362000)
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/trace/trace_test.go:256 +0xa0
created by runtime/trace_test.TestTraceStressStartStop.func1
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/trace/trace_test.go:259 +0x240

goroutine 113 [runnable]:
runtime/trace.Start.func1(0x403ad3d0, 0x1235f020)
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/trace/trace.go:26
created by runtime/trace.Start
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/trace/trace.go:34 +0x68

goroutine 37 [syscall]:
syscall.Syscall(0x3, 0x3, 0x10574fbc, 0x1, 0x0, 0x40489220, 0xd253)
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/syscall/asm_openbsd_arm.s:19 +0x8
syscall.read(0x3, 0x10574fbc, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/syscall/zsyscall_openbsd_arm.go:882 +0x78
syscall.Read(0x3, 0x10574fbc, 0x1, 0x1, 0x32592, 0x0, 0x0)
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/syscall/syscall_unix.go:160 +0x4c
os.(*File).read(0x12364000, 0x10574fbc, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/os/file_unix.go:211 +0x54
os.(*File).Read(0x12364000, 0x10574fbc, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/os/file.go:95 +0x7c
runtime/trace_test.TestTraceStressStartStop.func1.4(0x12364000, 0x12362000, 0x138d0000)
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/trace/trace_test.go:243 +0x54
created by runtime/trace_test.TestTraceStressStartStop.func1
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/trace/trace_test.go:246 +0x210

goroutine 97 [select (no cases)]:
runtime/trace_test.TestTraceStress.func9()
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/trace/trace_test.go:194 +0x18
created by runtime/trace_test.TestTraceStress
	/home/gopher/build/openbsd-arm-5e15e28e0ed0/go/src/runtime/trace/trace_test.go:195 +0x7b8
FAIL	runtime/trace	26.637s
```

**Comment by rsc** [comment]
Dup of #11911 - GC not keeping up.

**Comment by aclements** [comment]
If I'm reading the traceback correctly, we asked to map more heap memory at address 0, the OS was kind enough not to oblige, and we panicked. I don't see what this has to do with the GC not keeping up.
