### ISSUE TITLE
cmd/cgo: segfaults when resolving C.enum_* functions

### ISSUE THREAD

**Issue by g2p** [golang/go#12160]
main.go
```
package main
// void enum_things(void) {}
import "C"

func main() {
	C.enum_things()
}
```

go build main.go 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x40f0f6]

goroutine 1 [running]:
main.(*Package).rewriteRef(0xc8200762a0, 0xc82007c080)
	…git/go/src/cmd/cgo/gcc.go:610 +0x1466
main.(*Package).Translate(0xc8200762a0, 0xc82007c080)
	…git/go/src/cmd/cgo/gcc.go:170 +0x197
main.main()
	…git/go/src/cmd/cgo/main.go:269 +0x1059
```

**Comment by ianlancetaylor** [comment]
There are some special prefixes documented at https://golang.org/cmd/cgo , so this isn't going to work as you hope.  But obviously cgo should not crash.

**Comment by rsc** [comment]
Why did CL 15264 only update this issue? It seems fixed. I don't think we should try to distinguish alternate meanings for the special syntaxes like C.enum_x.

**Comment by ianlancetaylor** [comment]
I agree.  This is as fixed as it is going to get.
