### ISSUE TITLE
runtime: test timeout during ./all.bash on BananaPro

### ISSUE THREAD

**Issue by niphor** [golang/go#12404]
```
su
Load: 0.05, 0.10, 0.13 - Board: 50.8°C - Drive: 40°C / 1.5Tb - Memory: 828Mb
uname  -a
Linux bananapi 4.1.2-bananapi #30 SMP Sun Jul 12 07:03:27 CEST 2015 armv7l armv7l armv7l GNU/Linux
```
I downloaded go 1.4.2 from http://dave.cheney.net/unofficial-arm-tarballs
and when I compile 1.5, test timeout.

```
$ export GOOS=linux
$ export GOARCH=arm
$ export GOARM=7
$ env GOROOT_BOOTSTRAP=/home/go1.4 ./all.bash
##### Building Go bootstrap tool.
cmd/dist

##### Building Go toolchain using /home/go1.4.
bootstrap/internal/obj
bootstrap/asm/internal/flags
bootstrap/compile/internal/big
bootstrap/internal/obj/arm
bootstrap/internal/obj/arm64
bootstrap/internal/obj/ppc64
bootstrap/internal/obj/x86
bootstrap/asm/internal/lex
bootstrap/internal/gcprog
bootstrap/compile/internal/gc
bootstrap/asm/internal/arch
bootstrap/asm/internal/asm
bootstrap/asm
bootstrap/link/internal/ld
bootstrap/link/internal/amd64
bootstrap/link/internal/arm
bootstrap/link/internal/arm64
bootstrap/link/internal/ppc64
bootstrap/link/internal/x86
bootstrap/link
bootstrap/compile/internal/amd64
bootstrap/compile/internal/arm
bootstrap/compile/internal/arm64
bootstrap/compile/internal/ppc64
bootstrap/compile/internal/x86
bootstrap/compile

##### Building go_bootstrap for host, linux/arm.
runtime
errors
sync/atomic
sync
internal/singleflight
io
unicode
unicode/utf8
unicode/utf16
bytes
math
strings
strconv
bufio
sort
container/heap
encoding/base64
syscall
internal/syscall/windows/registry
time
internal/syscall/windows
os
reflect
fmt
encoding
encoding/binary
encoding/json
flag
path/filepath
path
io/ioutil
log
regexp/syntax
regexp
go/token
go/scanner
go/ast
go/parser
os/exec
os/signal
net/url
text/template/parse
text/template
go/doc
go/build
hash
crypto
crypto/sha1
debug/dwarf
debug/elf
cmd/go

##### Building packages and commands for linux/arm.
runtime
errors
sync/atomic
unicode
sync
io
unicode/utf8
math
bytes
bufio
syscall
strconv
reflect
time
os
encoding/binary
sort
fmt
strings
path/filepath
path
flag
log
cmd/internal/rsc.io/arm/armasm
cmd/internal/obj
cmd/internal/rsc.io/x86/x86asm
cmd/internal/goobj
debug/dwarf
debug/elf
debug/gosym
debug/macho
debug/pe
debug/plan9obj
regexp/syntax
text/tabwriter
io/ioutil
archive/tar
regexp
compress/flate
cmd/internal/objfile
hash
hash/crc32
archive/zip
cmd/addr2line
compress/bzip2
compress/gzip
compress/lzw
hash/adler32
compress/zlib
container/heap
container/list
container/ring
crypto
crypto/subtle
crypto/cipher
math/rand
math/big
crypto/aes
crypto/des
crypto/sha512
crypto/hmac
crypto/md5
internal/syscall/unix
crypto/rc4
crypto/sha1
crypto/sha256
encoding/hex
encoding/base64
crypto/dsa
crypto/elliptic
encoding/asn1
crypto/rand
crypto/ecdsa
crypto/x509/pkix
crypto/rsa
encoding/pem
internal/singleflight
go/token
os/exec
go/scanner
go/ast
database/sql/driver
database/sql
encoding
encoding/ascii85
encoding/base32
go/parser
go/printer
encoding/csv
encoding/gob
cmd/cgo
unicode/utf16
encoding/json
encoding/xml
mime
mime/quotedprintable
runtime/cgo
net/http/internal
net/url
text/template/parse
net
text/template
go/doc
go/build
go/constant
internal/format
go/format
go/types
crypto/x509
crypto/tls
net/textproto
text/scanner
mime/multipart
go/internal/gccgoimporter
net/http
go/internal/gcimporter
go/importer
hash/crc64
hash/fnv
html
html/template
expvar
image/color
image
image/color/palette
image/internal/imageutil
image/png
image/draw
image/gif
image/jpeg
index/suffixarray
runtime/pprof
runtime/trace
internal/trace
testing
log/syslog
internal/testenv
math/cmplx
net/http/cgi
net/http/cookiejar
net/http/httptest
net/http/fcgi
net/http/httputil
net/http/pprof
net/internal/socktest
net/mail
net/rpc
net/smtp
os/signal
os/user
net/rpc/jsonrpc
runtime/debug
runtime/race
testing/iotest
testing/quick
cmd/api
cmd/internal/obj/arm
cmd/internal/obj/arm64
cmd/internal/obj/ppc64
cmd/internal/obj/x86
cmd/asm/internal/flags
cmd/asm/internal/lex
cmd/asm/internal/arch
cmd/compile/internal/big
cmd/asm/internal/asm
cmd/asm
cmd/internal/gcprog
cmd/compile/internal/gc
cmd/cover
cmd/dist
cmd/doc
cmd/fix
cmd/go
cmd/compile/internal/amd64
cmd/compile/internal/arm
cmd/compile/internal/arm64
cmd/compile/internal/ppc64
cmd/compile/internal/x86
cmd/gofmt
cmd/compile
cmd/link/internal/ld
cmd/nm
cmd/objdump
cmd/pack
cmd/link/internal/amd64
cmd/link/internal/arm
cmd/link/internal/arm64
cmd/link/internal/ppc64
cmd/link/internal/x86
cmd/pprof/internal/profile
cmd/link
cmd/pprof/internal/plugin
cmd/pprof/internal/report
cmd/pprof/internal/svg
cmd/pprof/internal/tempfile
cmd/pprof/internal/fetch
cmd/pprof/internal/symbolizer
cmd/pprof/internal/symbolz
cmd/trace
cmd/pprof/internal/commands
cmd/pprof/internal/driver
cmd/pprof
cmd/vet/whitelist
cmd/vet
cmd/yacc


##### Testing packages.
ok      archive/tar     0.082s
ok      archive/zip     5.680s
ok      bufio   0.677s
ok      bytes   1.164s
ok      compress/bzip2  0.617s
ok      compress/flate  6.047s
ok      compress/gzip   0.085s
ok      compress/lzw    0.594s
ok      compress/zlib   13.709s
ok      container/heap  0.025s
ok      container/list  0.026s
ok      container/ring  0.055s
ok      crypto/aes      0.152s
ok      crypto/cipher   0.043s
ok      crypto/des      0.140s
ok      crypto/dsa      0.057s
ok      crypto/ecdsa    0.680s
ok      crypto/elliptic 0.500s
ok      crypto/hmac     0.030s
ok      crypto/md5      0.041s
ok      crypto/rand     0.148s
ok      crypto/rc4      1.459s
ok      crypto/rsa      1.487s
ok      crypto/sha1     0.034s
ok      crypto/sha256   0.037s
ok      crypto/sha512   0.050s
ok      crypto/subtle   0.056s
ok      crypto/tls      16.474s
ok      crypto/x509     14.221s
ok      database/sql    0.406s
ok      database/sql/driver     0.020s
ok      debug/dwarf     0.087s
ok      debug/elf       0.151s
ok      debug/gosym     0.042s
ok      debug/macho     0.044s
ok      debug/pe        0.213s
ok      debug/plan9obj  0.030s
ok      encoding/ascii85        0.023s
ok      encoding/asn1   0.043s
ok      encoding/base32 0.028s
ok      encoding/base64 0.033s
ok      encoding/binary 0.036s
ok      encoding/csv    0.039s
ok      encoding/gob    0.499s
ok      encoding/hex    0.026s
ok      encoding/json   1.472s
ok      encoding/pem    0.490s
ok      encoding/xml    0.126s
ok      errors  0.024s
ok      expvar  0.036s
ok      flag    0.034s
ok      fmt     1.675s
ok      go/ast  0.050s
ok      go/build        1.159s
ok      go/constant     0.030s
ok      go/doc  0.642s
ok      go/format       0.084s
ok      go/internal/gccgoimporter       0.079s
ok      go/internal/gcimporter  4.774s
ok      go/parser       0.306s
ok      go/printer      3.569s
ok      go/scanner      0.041s
ok      go/token        0.331s
ok      go/types        19.337s
ok      hash/adler32    0.056s
ok      hash/crc32      0.076s
ok      hash/crc64      0.022s
ok      hash/fnv        0.023s
ok      html    0.031s
ok      html/template   0.457s
ok      image   1.721s
ok      image/color     1.125s
ok      image/draw      0.866s
ok      image/gif       0.672s
ok      image/jpeg      1.928s
ok      image/png       0.534s
ok      index/suffixarray       0.094s
ok      internal/singleflight   0.046s
ok      internal/trace  0.020s
ok      io      0.046s
ok      io/ioutil       0.054s
ok      log     0.060s
ok      log/syslog      2.143s
ok      math    0.036s
ok      math/big        11.317s
ok      math/cmplx      0.047s
ok      math/rand       3.220s
ok      mime    0.087s
ok      mime/multipart  0.799s
ok      mime/quotedprintable    2.176s
ok      net     4.616s
ok      net/http        19.186s
ok      net/http/cgi    1.651s
ok      net/http/cookiejar      0.068s
ok      net/http/fcgi   0.040s
ok      net/http/httptest       0.048s
ok      net/http/httputil       0.169s
ok      net/http/internal       0.031s
ok      net/internal/socktest   0.026s
ok      net/mail        0.042s
ok      net/rpc 0.139s
ok      net/rpc/jsonrpc 0.074s
ok      net/smtp        0.534s
ok      net/textproto   0.034s
ok      net/url 0.105s
ok      os      0.471s
ok      os/exec 1.771s
ok      os/signal       3.588s
ok      os/user 0.030s
ok      path    0.051s
ok      path/filepath   0.209s
ok      reflect 0.932s
ok      regexp  1.955s
ok      regexp/syntax   4.467s
ok      runtime 299.016s
ok      runtime/debug   0.088s
ok      runtime/pprof   16.002s
ok      runtime/trace   31.274s
ok      sort    0.649s
ok      strconv 57.199s
ok      strings 1.097s
ok      sync    0.942s
ok      sync/atomic     3.530s
ok      syscall 0.280s
ok      testing 1.851s
ok      testing/quick   0.477s
ok      text/scanner    0.041s
ok      text/tabwriter  0.037s
ok      text/template   0.238s
ok      text/template/parse     0.073s
ok      time    4.917s
ok      unicode 0.028s
ok      unicode/utf16   0.021s
ok      unicode/utf8    0.048s
ok      cmd/addr2line   12.144s
ok      cmd/api 0.074s
ok      cmd/asm/internal/asm    0.255s
ok      cmd/asm/internal/lex    0.022s
ok      cmd/compile/internal/big        50.774s
ok      cmd/cover       26.922s
ok      cmd/doc 0.164s
ok      cmd/fix 0.120s
ok      cmd/go  366.144s
ok      cmd/gofmt       0.470s
ok      cmd/internal/goobj      0.026s
ok      cmd/internal/obj        0.025s
ok      cmd/internal/obj/x86    0.143s
ok      cmd/internal/rsc.io/arm/armasm  0.070s
ok      cmd/internal/rsc.io/x86/x86asm  2.231s
ok      cmd/nm  12.172s
ok      cmd/objdump     34.192s
ok      cmd/pack        25.783s
ok      cmd/pprof/internal/profile      0.028s
ok      cmd/vet 65.636s

##### GOMAXPROCS=2 runtime -cpu=1,2,4
panic: test timed out after 10m0s

goroutine 209742 [running]:
testing.startAlarm.func1()
        /home/go1.5/src/testing/testing.go:703 +0x10c
created by time.goFunc
        /home/go1.5/src/time/sleep.go:129 +0x34

goroutine 1 [chan receive, locked to thread]:
testing.RunTests(0x261054, 0x3080f8, 0xa1, 0xa1, 0x1)
        /home/go1.5/src/testing/testing.go:582 +0x894
testing.(*M).Run(0x10551f7c, 0x125e0)
        /home/go1.5/src/testing/testing.go:494 +0x6c
main.main()
        runtime/_test/_testmain.go:902 +0x118

goroutine 208507 [runnable]:
runtime_test.growStackWithCallback.func1(0x22)
        /home/go1.5/src/runtime/stack_test.go:200
runtime_test.growStackWithCallback.func1(0x23)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x24)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x25)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x26)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x27)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x28)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x29)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x2a)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x2b)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x2c)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x2d)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x2e)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x2f)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x30)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x31)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x32)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x33)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x34)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x35)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x36)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x37)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x38)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x39)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x3a)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x3b)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x3c)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x3d)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x3e)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x3f)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x40)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x41)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x42)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x43)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x44)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x45)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x46)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x47)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x48)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x49)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x4a)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x4b)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x4c)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x4d)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x4e)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x4f)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x50)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x51)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x52)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x53)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x54)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x55)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x56)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x57)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x58)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x59)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x5a)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x5b)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x5c)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x5d)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x5e)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x5f)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x60)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x61)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x62)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x63)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x64)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x65)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x66)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x67)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x68)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x69)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x6a)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x6b)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x6c)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x6d)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x6e)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x6f)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x70)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x71)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x72)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x73)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x74)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x75)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x76)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x77)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x78)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x79)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x7a)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x7b)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x7c)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x7d)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x7e)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x7f)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x80)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x81)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x82)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x83)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x84)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
runtime_test.growStackWithCallback.func1(0x85)
        /home/go1.5/src/runtime/stack_test.go:205 +0x4c
...additional frames elided...
created by runtime_test.TestStackGrowthCallback
        /home/go1.5/src/runtime/stack_test.go:180 +0x8c

goroutine 22630 [syscall, 4 minutes]:
runtime_test.TestFutexsleep.func1(0x0, 0x4876e800, 0x1dcd6517, 0x225d68, 0x13, 0x10562080)
        /home/go1.5/src/runtime/futex_test.go:47 +0x54
created by runtime_test.TestFutexsleep
        /home/go1.5/src/runtime/futex_test.go:51 +0x20c

goroutine 22629 [syscall, 4 minutes]:
runtime_test.TestFutexsleep.func1(0x0, 0x914f0000, 0x4e94, 0x22ab20, 0x14, 0x10562040)
        /home/go1.5/src/runtime/futex_test.go:47 +0x54
created by runtime_test.TestFutexsleep
        /home/go1.5/src/runtime/futex_test.go:51 +0x20c

goroutine 207691 [semacquire]:
sync.runtime_Semacquire(0x1056837c)
        /home/go1.5/src/runtime/sema.go:43 +0x24
sync.(*WaitGroup).Wait(0x10568370)
        /home/go1.5/src/sync/waitgroup.go:126 +0xc0
runtime_test.TestStackGrowthCallback(0x1058c540)
        /home/go1.5/src/runtime/stack_test.go:195 +0xc8
testing.tRunner(0x1058c540, 0x308788)
        /home/go1.5/src/testing/testing.go:456 +0xa8
created by testing.RunTests
        /home/go1.5/src/testing/testing.go:561 +0x5ec

goroutine 207689 [semacquire]:
sync.runtime_Semacquire(0x1050e7dc)
        /home/go1.5/src/runtime/sema.go:43 +0x24
sync.(*WaitGroup).Wait(0x1050e7d0)
        /home/go1.5/src/sync/waitgroup.go:126 +0xc0
runtime_test.TestStackGrowth(0x1058c4e0)
        /home/go1.5/src/runtime/stack_test.go:83 +0x68
testing.tRunner(0x1058c4e0, 0x30877c)
        /home/go1.5/src/testing/testing.go:456 +0xa8
created by testing.RunTests
        /home/go1.5/src/testing/testing.go:561 +0x5ec

goroutine 207692 [chan receive]:
testing.RunTests.func1(0x10562240, 0x1058c540)
        /home/go1.5/src/testing/testing.go:565 +0x3c
created by testing.RunTests
        /home/go1.5/src/testing/testing.go:566 +0x660

goroutine 208716 [runnable]:
runtime_test.growStackIter(0x10dd3fa0, 0xa8)
        /home/go1.5/src/runtime/stack_test.go:142
runtime_test.growStack()
        /home/go1.5/src/runtime/stack_test.go:132 +0x64
runtime_test.TestStackGrowth.func1(0x1050e7d0)
        /home/go1.5/src/runtime/stack_test.go:81 +0x44
created by runtime_test.TestStackGrowth
        /home/go1.5/src/runtime/stack_test.go:82 +0x5c

goroutine 207690 [chan receive]:
testing.RunTests.func1(0x10562240, 0x1058c4e0)
        /home/go1.5/src/testing/testing.go:565 +0x3c
created by testing.RunTests
        /home/go1.5/src/testing/testing.go:566 +0x660
FAIL    runtime 600.208s
2015/08/30 14:11:25 Failed: exit status 1
```

and , it use too much time...
sometime it fails before `GOMAXPROCS=2 runtime -cpu=1,2,4` test
```
ok      runtime 299.016s
```

**Comment by minux** [comment]
Please set $GO_TEST_TIMEOUT_SCALE to a big integer and
try again.

It's probably just because the hardware is slow.
