### ISSUE TITLE
go build crash: "fatal error: missing stackmap"

### ISSUE THREAD

**Issue by rojer** [golang/go#12589]
my code does not compile, but _how_ it fails is interesting - go build crashes.
something about gc, i gather. sample stack traces below.
every now and then it succeeds.
not a virtual machine, Ubuntu 15.04 x86-64

```
$ uname -a
Linux nbt.rojer.me 3.19.0-26-generic #28-Ubuntu SMP Tue Aug 11 14:16:32 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ go version
go version go1.5 linux/amd64
$ go build                                                                                                                                                            
# ...
runtime: frame runtime.runfinq untyped locals 0xc82002b750+0x68
fatal error: missing stackmap

runtime stack:
runtime.throw(0x841f30, 0x10)
        /usr/local/go/src/runtime/panic.go:527 +0x90
runtime.scanframeworker(0x7ffc39ad8260, 0x0, 0xc82001f220)
        /usr/local/go/src/runtime/mgcmark.go:453 +0x694
runtime.scanstack.func1(0x7ffc39ad8260, 0x0, 0x1)
        /usr/local/go/src/runtime/mgcmark.go:384 +0x65
runtime.gentraceback(0x42b033, 0xc82002b6f0, 0x0, 0xc820001080, 0x0, 0x0, 0x7fffffff, 0x7ffc39ad8380, 0x0, 0x0, ...)
        /usr/local/go/src/runtime/traceback.go:336 +0xa69
runtime.scanstack(0xc820001080)
        /usr/local/go/src/runtime/mgcmark.go:406 +0x38b
runtime.scang(0xc820001080)
        /usr/local/go/src/runtime/proc1.go:422 +0xf3
runtime.markroot(0xc82001c000, 0x7ffc00000008)
        /usr/local/go/src/runtime/mgcmark.go:133 +0x1ba
runtime.parfordo(0xc82001c000)
        /usr/local/go/src/runtime/parfor.go:95 +0x12a
runtime.gcscan_m()
        /usr/local/go/src/runtime/mgcmark.go:36 +0xc6
runtime.gc.func1()
        /usr/local/go/src/runtime/mgc.go:996 +0xdd
runtime.systemstack(0xc80c20)
        /usr/local/go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
        /usr/local/go/src/runtime/proc1.go:674

goroutine 5 [garbage collection scan]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc82002bc98 sp=0xc82002bc90
runtime.gc(0x0)
        /usr/local/go/src/runtime/mgc.go:1005 +0x1db fp=0xc82002bf90 sp=0xc82002bc98
runtime.backgroundgc()
        /usr/local/go/src/runtime/mgc.go:896 +0x3d fp=0xc82002bfc0 sp=0xc82002bf90
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002bfc8 sp=0xc82002bfc0
created by runtime.startGC
        /usr/local/go/src/runtime/mgc.go:869 +0x186

goroutine 1 [runnable]:
cmd/compile/internal/gc.(*Pkg).LookupBytes(0xc820014370, 0xc82000b320, 0x8, 0x103, 0x7)
        /usr/local/go/src/cmd/compile/internal/gc/subr.go:302 +0x4bd
cmd/compile/internal/gc.LookupBytes(0xc82000b320, 0x8, 0x103, 0x0)
        /usr/local/go/src/cmd/compile/internal/gc/subr.go:266 +0x41
cmd/compile/internal/gc._yylex(0xc820019080, 0xc80000002e)
        /usr/local/go/src/cmd/compile/internal/gc/lex.go:1411 +0x351
cmd/compile/internal/gc.yylex(0xc820019080, 0x2e)
        /usr/local/go/src/cmd/compile/internal/gc/lex.go:1859 +0x25
cmd/compile/internal/gc.yy.Lex(0xc820019080, 0x2e)
        /usr/local/go/src/cmd/compile/internal/gc/lex.go:1841 +0x21
cmd/compile/internal/gc.(*yy).Lex(0xda67e0, 0xc820019080, 0x2e)
        <autogenerated>:11 +0x97
cmd/compile/internal/gc.yylex1(0x7f0138bc07f8, 0xda67e0, 0xc820019080, 0x2e, 0x0)
        yaccpar:120 +0x52
cmd/compile/internal/gc.(*yyParserImpl).Parse(0xc82002e050, 0x7f0138bc07f8, 0xda67e0, 0x0)
        yaccpar:206 +0x1a9c3
cmd/compile/internal/gc.yyparse()
        /usr/local/go/src/cmd/compile/internal/gc/lex.go:1854 +0xb4
cmd/compile/internal/gc.Main()
        /usr/local/go/src/cmd/compile/internal/gc/lex.go:348 +0x1b6f
cmd/compile/internal/amd64.Main()
        /usr/local/go/src/cmd/compile/internal/amd64/galign.go:127 +0x58d
main.main()
        /usr/local/go/src/cmd/compile/main.go:26 +0x189
rojer@nbt:~/go/src/cesanta.com/projects/quantex/tcpuart/test/data_test q3$ go build 
# ...
runtime: frame runtime.runfinq untyped locals 0xc82002b750+0x68
fatal error: missing stackmap

runtime stack:
runtime.throw(0x841f30, 0x10)
        /usr/local/go/src/runtime/panic.go:527 +0x90
runtime.scanframeworker(0x7fffdf6059f0, 0x0, 0xc820020720)
        /usr/local/go/src/runtime/mgcmark.go:453 +0x694
runtime.scanstack.func1(0x7fffdf6059f0, 0x0, 0x1)
        /usr/local/go/src/runtime/mgcmark.go:384 +0x65
runtime.gentraceback(0x42b033, 0xc82002b6f0, 0x0, 0xc820001080, 0x0, 0x0, 0x7fffffff, 0x7fffdf605b10, 0x0, 0x0, ...)
        /usr/local/go/src/runtime/traceback.go:336 +0xa69
runtime.scanstack(0xc820001080)
        /usr/local/go/src/runtime/mgcmark.go:406 +0x38b
runtime.scang(0xc820001080)
        /usr/local/go/src/runtime/proc1.go:422 +0xf3
runtime.markroot(0xc82001c000, 0x7fff00000008)
        /usr/local/go/src/runtime/mgcmark.go:133 +0x1ba
runtime.parfordo(0xc82001c000)
        /usr/local/go/src/runtime/parfor.go:95 +0x12a
runtime.gcscan_m()
        /usr/local/go/src/runtime/mgcmark.go:36 +0xc6
runtime.gc.func1()
        /usr/local/go/src/runtime/mgc.go:996 +0xdd
runtime.systemstack(0xc80c20)
        /usr/local/go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
        /usr/local/go/src/runtime/proc1.go:674

goroutine 5 [garbage collection scan]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc82002bc98 sp=0xc82002bc90
runtime.gc(0x0)
        /usr/local/go/src/runtime/mgc.go:1005 +0x1db fp=0xc82002bf90 sp=0xc82002bc98
runtime.backgroundgc()
        /usr/local/go/src/runtime/mgc.go:896 +0x3d fp=0xc82002bfc0 sp=0xc82002bf90
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002bfc8 sp=0xc82002bfc0
created by runtime.startGC
        /usr/local/go/src/runtime/mgc.go:869 +0x186

goroutine 1 [runnable]:
cmd/compile/internal/gc.yylex1(0x7ff48afe8728, 0xda67e0, 0xc820019080, 0x28, 0x3c)
        yaccpar:118
cmd/compile/internal/gc.(*yyParserImpl).Parse(0xc82002e040, 0x7ff48afe8728, 0xda67e0, 0x0)
        yaccpar:206 +0x1a9c3
cmd/compile/internal/gc.yyparse()
        /usr/local/go/src/cmd/compile/internal/gc/lex.go:1854 +0xb4
cmd/compile/internal/gc.Main()
        /usr/local/go/src/cmd/compile/internal/gc/lex.go:348 +0x1b6f
cmd/compile/internal/amd64.Main()
        /usr/local/go/src/cmd/compile/internal/amd64/galign.go:127 +0x58d
main.main()
        /usr/local/go/src/cmd/compile/main.go:26 +0x189
```

after a few attempts:

```
$ go build 
# ...
./main.go:33: missing return at end of function
./main.go:37: undefined: rand in rand.Seed
./main.go:37: undefined: time in time.Now
```

**Comment by rojer** [comment]
looks like 1.5.1 fixed this.
