### ISSUE TITLE
x/image/draw: TestTformOver fails on linux/ppc64

### ISSUE THREAD

**Issue by minux** [golang/go#12597]
```
=== RUN   TestTformOver
--- FAIL: TestTformOver (7.61s)
panic: runtime error: index out of range [recovered]
        panic: runtime error: index out of range

goroutine 19 [running]:
testing.tRunner.func1(0xc82009c000)
        /go/src/testing/testing.go:450 +0x170
vendor/golang.org/x/image/draw.ablInterpolator.transform_RGBA_NRGBA_Over(0xc820016e80, 0xf, 0xa, 0x52, 0x4d, 0x0, 0x0, 0x43, 0x43, 0xc8200a77e0, ...)
        /src/golang.org/x/image/draw/impl.go:2998 +0xcf4
```

Probably a codegen bug.

**Comment by minux** [comment]
On linux/ppc64, TestInterpClipCommute and TestRectDstMask also fails.

It's probably due to missing narrowing masks.

**Comment by mwhudson** [comment]
Can this be added to the go 1.5.2 milestone please?

**Comment by ianlancetaylor** [comment]
Done (without actually looking at the issue).

**Comment by minux** [comment]
It's a ppc64 codegen bug (optimizer keeps a live variable in REGTMP).
