### ISSUE TITLE
x/mobile/cmd/gomobile: gomobile install fails when assets dir is symlink

### ISSUE THREAD

**Issue by momchil-atanasov** [golang/go#12713]
It seems that `gomobile` fails when the `assets` directory is a symlink. (In my case equal to `../assets/`).

I am using `go version go1.5.1 darwin/amd64` and `gomobile version +afa8a11 Fri Sep 18 00:19:08 2015 +0000 (android,ios);`.

```bash
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.goAndroidBuild.func4(0xc8201f9140, 0x57, 0xaa4180, 0xc8201f59a0, 0x0, 0x0, 0x0, 0x0)
	/Users/momchil/Workspace/Go/src/golang.org/x/mobile/cmd/gomobile/build_androidapp.go:189 +0x170
path/filepath.walk(0xc8201f9140, 0x57, 0xaa4180, 0xc8201f59a0, 0xc82020bb28, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:349 +0x80
path/filepath.Walk(0xc8201f9140, 0x57, 0xc82020bb28, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:396 +0xe1
main.goAndroidBuild(0xc820156000, 0x0, 0x0, 0x0)
	/Users/momchil/Workspace/Go/src/golang.org/x/mobile/cmd/gomobile/build_androidapp.go:191 +0x1ac0
main.runBuild(0x927140, 0x0, 0x0)
	/Users/momchil/Workspace/Go/src/golang.org/x/mobile/cmd/gomobile/build.go:101 +0x760
main.runInstall(0x927140, 0x0, 0x0)
	/Users/momchil/Workspace/Go/src/golang.org/x/mobile/cmd/gomobile/install.go:36 +0xa7
main.main()
	/Users/momchil/Workspace/Go/src/golang.org/x/mobile/cmd/gomobile/main.go:63 +0x495

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
```

Use case: I want to have something that can be compiled both as an Android library but can also be tested as a standalone application, since the later is much quicker to run (and also since Library GL applications are not yet actually supported #12649). I cannot have a `lib` package and `main` package in the same folder so they have to be separated and share the assets directory somehow.

**Comment by ianlancetaylor** [comment]
CC @crawshaw
