### ISSUE TITLE
x/mobile/exp/app/debug: occatianal "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by rakyll** [golang/go#12922]
I am coming across a panic occasionally by following the steps below:
1. Launch the basic app on Android.
2. Press the back button.
3. App crashes with "panic: runtime error: invalid memory address or nil pointer dereference".

```
/Adreno-ES20( 6535): <core_glUseProgram:1557>: GL_INVALID_VALUE
E/Go      ( 6535): panic: runtime error: invalid memory address or nil pointer dereference
E/Go      ( 6535): [signal 0xb code=0x1 addr=0x0 pc=0xaea9a854]
E/Go      ( 6535): goroutine 12 [running]:
E/Go      ( 6535): golang.org/x/mobile/exp/app/debug.(*FPS).Draw(0x93ad2120, 0x438, 0x6f0, 0x43220000, 0x43853333, 0x40d55555, 0x1)
E/Go      ( 6535):  /Users/jbd/src/golang.org/x/mobile/exp/app/debug/fps.go:66 +0x2d8
E/Go      ( 6535): main.onPaint(0xaf19e170, 0x93a6a120, 0x438, 0x6f0, 0x43220000, 0x43853333, 0x40d55555, 0x1)
E/Go      ( 6535):  /Users/jbd/src/golang.org/x/mobile/example/sensor/main.go:175 +0x2bc
E/Go      ( 6535): main.main.func1(0xaf11a000, 0xaebe79e0)
E/Go      ( 6535):  /Users/jbd/src/golang.org/x/mobile/example/sensor/main.go:107 +0x23c
E/Go      ( 6535): golang.org/x/mobile/app.mainUI.func1(0x93a5e580)
E/Go      ( 6535):  /Users/jbd/src/golang.org/x/mobile/app/android.go:274 +0x84
E/Go      ( 6535): created by golang.org/x/mobile/app.mainUI
E/Go      ( 6535):  /Users/jbd/src/golang.org/x/mobile/app/android.go:276 +0xb0
```

/cc @crawshaw @nigeltao

**Comment by changkun** [comment]
I can't reproduce this crash today. Close as outdated, but also feel free to comment any updates.
