### ISSUE TITLE
net/http/httptest: test Server blocked after 5 seconds with StateNew conns

### ISSUE THREAD

**Issue by bradfitz** [golang/go#13032]
See https://storage.googleapis.com/go-build-log/cd0968ff/linux-amd64_3f5c4149.log

```
2015/10/22 23:01:52 httptest.Server blocked in Close after 5 seconds, waiting for connections:
  *net.TCPConn 0xc820692200 127.0.0.1:35530 in state new
panic: test timed out after 3m0s

goroutine 124 [running]:
testing.startAlarm.func1()
	/tmp/workdir/go/src/testing/testing.go:703 +0x132
created by time.goFunc
	/tmp/workdir/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive, 2 minutes]:
testing.RunTests(0x9f7650, 0xb7ac80, 0xf4, 0xf4, 0x701)
	/tmp/workdir/go/src/testing/testing.go:562 +0x8b9
testing.(*M).Run(0xc820183f08, 0x5bdca7)
	/tmp/workdir/go/src/testing/testing.go:494 +0x70
net/http_test.TestMain(0xc820183f08)
	/tmp/workdir/go/src/net/http/main_test.go:19 +0x21
main.main()
	net/http/_test/_testmain.go:584 +0x114

goroutine 17 [syscall, 2 minutes, locked to thread]:
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:1805 +0x1

goroutine 114 [semacquire, 2 minutes]:
sync.runtime_Semacquire(0xc82018b7dc)
	/tmp/workdir/go/src/runtime/sema.go:43 +0x26
sync.(*WaitGroup).Wait(0xc82018b7d0)
	/tmp/workdir/go/src/sync/waitgroup.go:126 +0xb4
net/http/httptest.(*Server).Close(0xc82018b7a0)
	/tmp/workdir/go/src/net/http/httptest/server.go:170 +0x26a
net/http_test.TestClientWrites(0xc820079950)
	/tmp/workdir/go/src/net/http/client_test.go:572 +0x78a
testing.tRunner(0xc820079950, 0xb7b0e8)
	/tmp/workdir/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:561 +0x879
```

From changes in https://go-review.googlesource.com/#/c/15151/

**Comment by bradfitz** [comment]
And https://storage.googleapis.com/go-build-log/ed6176f8/linux-386_52ca634c.log

**Comment by aclements** [comment]
This has been happening fairly regularly:

[2015-10-20T15:48:49-7d2c6eb/linux-386-387](http://build.golang.org/log/283853431f832d2ef9ae1e7d535e526a059a29a6)
[2015-10-23T16:38:27-e4feb18/linux-386-sid](http://build.golang.org/log/13f54fe632eb1768f8ef0b55ab7bf623f55ba6a0)
[2015-10-26T10:14:38-adf9b30/linux-amd64-clang](http://build.golang.org/log/3261e17fe74677df0bb61ee79a9e757ad3f9e0af)
[2015-10-20T14:10:24-77b1fef/linux-amd64-clang](http://build.golang.org/log/2147a9d843740025f34d8eda830e057abc4b7596)
[2015-10-23T07:54:42-6410e67/solaris-amd64-smartos](http://build.golang.org/log/e294444d0a8e950305d4e6aa83f8d6a536819ae2)
[2015-10-26T13:57:48-afe9837/dragonfly-amd64](http://build.golang.org/log/557955b626f52445987734c128ba828c3fcae11d)
[2015-10-22T14:08:10-c4fa25f/linux-amd64-clang](http://build.golang.org/log/c29f0854fac3c05218e9f5db5b499de47ae32c6b)
[2015-10-23T01:57:15-c7e2eaf/linux-ppc64le-canonical](http://build.golang.org/log/1998c055aa5ce4e2e945f93cd196374c225f05c2)
[2015-10-20T22:11:11-7628521/linux-ppc64-minux](http://build.golang.org/log/d08129def341c324dc33200d72a4e792950313dc)
[2015-10-21T17:50:39-5174df9/linux-386-clang](http://build.golang.org/log/dec1be6644ff135dd72baf46a7aa83fe327c6071)
[2015-10-26T11:23:31-a30dd9c/solaris-amd64-smartos](http://build.golang.org/log/f58cf2b7e05e3a0c6e4a5d18ce493f86e1b89afa)
[2015-10-20T23:21:23-09eb588/linux-amd64](http://build.golang.org/log/6c0204033f976fa774b8a403090b53f204295c35)
[2015-10-22T18:04:20-3319ea9/linux-386-clang](http://build.golang.org/log/84b0074693da1cb61d4e10415187a18f3277339f)
[2015-10-22T21:01:29-ae2f54a/linux-ppc64le-canonical](http://build.golang.org/log/102b780203251bdeca0d738d04314865482a8e2a)

**Comment by bradfitz** [comment]
Yup.  :( I spent a couple days fighting that CL originally (the one now causing the flakes) and then at the last minute we simplified it, cutting it way back and I thought we made it more reliable (by making it more aggressive). I'll investigate and fix with a vengeance. I hate flakes.
