### ISSUE TITLE
cmd/go: go test should be more explicit about test failures

### ISSUE THREAD

**Issue by pmezard** [golang/go#13106]
In the best case, the output of `go test github.com/blevesearch/bleve/...` is 88 lines long. If one of the early test fails, the error message can easily be scrolled out and short of looking at `$?` or scrolling back manually, the user has no way to know the test run failed.

I propose `go test` prints something visible at the end of the run in that case like:

```
TEST RESULT: FAILED
```

Having a prefix like `TEST RESULT:` may make it easier for tools processing test output to ignore this line in the future, should its format change (by adding the number of tests run/successful, or time it took, etc.).
A `TEST RESULT: OK` might be displayed on success to.

Thoughts?

**Comment by meirf** [comment]
To be specific on the scope of this issue:
The case of `go test`ing a single package does not have this problem: When verbose mode is not set, the output will show only failures, including FAIL at the end of the output. When verbose mode is set, even if only the first test fails, the last line of the output will show FAIL.

For `go test`ing multiple packages, some kind of error message at the end of the output seems useful. I understand that most code would detect this by the exit status as pmezard mentions, but for humans that's not adequate.

I think go testing a single package vs multiple packages is semantically the same thing in this context - one failure should cause net failure.

@bcmills

**Comment by agnivade** [comment]
Is the `-json` flag not sufficient for this ? I thought that was meant to be processed by automated tools.

**Comment by bcmills** [comment]
On the one hand, it's true that a long list of tests might scroll a failure off the screen.

On the other hand, it's relatively easy to use a bash `PROMPT_COMMAND` (or equivalent for other shells) to get a visible indicator of exit status regardless.

Perhaps rather than `TEST RESULT: FAILED` we should just recapitulate a list of the failing tests after everything has finished running.

For example, this output today:

<details>

```
$ go test github.com/blevesearch/bleve/...
# github.com/couchbase/moss
_gopath/pkg/mod/github.com/couchbase/moss@v0.0.0-20181127195802-b19695552c83/api.go:176:15: undefined: ghistogram.Histograms
_gopath/pkg/mod/github.com/couchbase/moss@v0.0.0-20181127195802-b19695552c83/collection.go:98:13: undefined: ghistogram.Histograms
--- FAIL: TestIndexMeta (0.00s)
    index_meta_test.go:41: mkdir doesnotexit.bleve: permission denied
    index_meta_test.go:48: cannot open index, path does not exist
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8adcc5]

goroutine 87 [running]:
testing.tRunner.func1(0xc0001c6100)
        /usr/local/google/home/bcmills/go/src/testing/testing.go:830 +0x388
panic(0x94b540, 0xe76620)
        /usr/local/google/home/bcmills/go/src/runtime/panic.go:522 +0x1b5
github.com/blevesearch/bleve.TestIndexMeta(0xc0001c6100)
        /tmp/tmp.DLG9ag97ES/_gopath/pkg/mod/github.com/blevesearch/bleve@v0.7.0/index_meta_test.go:50 +0x1a5
testing.tRunner(0xc0001c6100, 0x9f9da8)
        /usr/local/google/home/bcmills/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
        /usr/local/google/home/bcmills/go/src/testing/testing.go:916 +0x357
FAIL    github.com/blevesearch/bleve    0.181s
ok      github.com/blevesearch/bleve/analysis   (cached)
?       github.com/blevesearch/bleve/analysis/analyzer/custom   [no test files]
?       github.com/blevesearch/bleve/analysis/analyzer/keyword  [no test files]
?       github.com/blevesearch/bleve/analysis/analyzer/simple   [no test files]
?       github.com/blevesearch/bleve/analysis/analyzer/standard [no test files]
?       github.com/blevesearch/bleve/analysis/analyzer/web      [no test files]
?       github.com/blevesearch/bleve/analysis/char/html [no test files]
ok      github.com/blevesearch/bleve/analysis/char/regexp       (cached)
?       github.com/blevesearch/bleve/analysis/char/zerowidthnonjoiner   [no test files]
ok      github.com/blevesearch/bleve/analysis/datetime/flexible (cached)
?       github.com/blevesearch/bleve/analysis/datetime/optional [no test files]
ok      github.com/blevesearch/bleve/analysis/lang/ar   (cached)
?       github.com/blevesearch/bleve/analysis/lang/bg   [no test files]
ok      github.com/blevesearch/bleve/analysis/lang/ca   (cached)
ok      github.com/blevesearch/bleve/analysis/lang/cjk  (cached)
ok      github.com/blevesearch/bleve/analysis/lang/ckb  (cached)
?       github.com/blevesearch/bleve/analysis/lang/cs   [no test files]
ok      github.com/blevesearch/bleve/analysis/lang/da   (cached)
ok      github.com/blevesearch/bleve/analysis/lang/de   (cached)
?       github.com/blevesearch/bleve/analysis/lang/el   [no test files]
ok      github.com/blevesearch/bleve/analysis/lang/en   (cached)
ok      github.com/blevesearch/bleve/analysis/lang/es   (cached)
?       github.com/blevesearch/bleve/analysis/lang/eu   [no test files]
ok      github.com/blevesearch/bleve/analysis/lang/fa   (cached)
ok      github.com/blevesearch/bleve/analysis/lang/fi   (cached)
ok      github.com/blevesearch/bleve/analysis/lang/fr   (cached)
ok      github.com/blevesearch/bleve/analysis/lang/ga   (cached)
?       github.com/blevesearch/bleve/analysis/lang/gl   [no test files]
ok      github.com/blevesearch/bleve/analysis/lang/hi   (cached)
ok      github.com/blevesearch/bleve/analysis/lang/hu   (cached)
?       github.com/blevesearch/bleve/analysis/lang/hy   [no test files]
?       github.com/blevesearch/bleve/analysis/lang/id   [no test files]
ok      github.com/blevesearch/bleve/analysis/lang/in   (cached)
ok      github.com/blevesearch/bleve/analysis/lang/it   (cached)
ok      github.com/blevesearch/bleve/analysis/lang/nl   (cached)
ok      github.com/blevesearch/bleve/analysis/lang/no   (cached)
ok      github.com/blevesearch/bleve/analysis/lang/pt   (cached)
ok      github.com/blevesearch/bleve/analysis/lang/ro   (cached)
ok      github.com/blevesearch/bleve/analysis/lang/ru   (cached)
ok      github.com/blevesearch/bleve/analysis/lang/sv   (cached)
ok      github.com/blevesearch/bleve/analysis/lang/tr   (cached)
ok      github.com/blevesearch/bleve/analysis/token/apostrophe  (cached)
ok      github.com/blevesearch/bleve/analysis/token/camelcase   (cached)
ok      github.com/blevesearch/bleve/analysis/token/compound    (cached)
ok      github.com/blevesearch/bleve/analysis/token/edgengram   (cached)
ok      github.com/blevesearch/bleve/analysis/token/elision     (cached)
ok      github.com/blevesearch/bleve/analysis/token/keyword     (cached)
ok      github.com/blevesearch/bleve/analysis/token/length      (cached)
ok      github.com/blevesearch/bleve/analysis/token/lowercase   (cached)
ok      github.com/blevesearch/bleve/analysis/token/ngram       (cached)
ok      github.com/blevesearch/bleve/analysis/token/porter      (cached)
ok      github.com/blevesearch/bleve/analysis/token/shingle     (cached)
ok      github.com/blevesearch/bleve/analysis/token/snowball    (cached)
ok      github.com/blevesearch/bleve/analysis/token/stop        (cached)
ok      github.com/blevesearch/bleve/analysis/token/truncate    (cached)
ok      github.com/blevesearch/bleve/analysis/token/unicodenorm (cached)
ok      github.com/blevesearch/bleve/analysis/token/unique      (cached)
ok      github.com/blevesearch/bleve/analysis/tokenizer/character       (cached)
ok      github.com/blevesearch/bleve/analysis/tokenizer/exception       (cached)
?       github.com/blevesearch/bleve/analysis/tokenizer/letter  [no test files]
ok      github.com/blevesearch/bleve/analysis/tokenizer/regexp  (cached)
ok      github.com/blevesearch/bleve/analysis/tokenizer/single  (cached)
ok      github.com/blevesearch/bleve/analysis/tokenizer/unicode (cached)
ok      github.com/blevesearch/bleve/analysis/tokenizer/web     (cached)
ok      github.com/blevesearch/bleve/analysis/tokenizer/whitespace      (cached)
?       github.com/blevesearch/bleve/analysis/tokenmap  [no test files]
ok      github.com/blevesearch/bleve/document   (cached)
ok      github.com/blevesearch/bleve/geo        (cached)
--- FAIL: TestHandlers (0.00s)
    handlers_test.go:41: mkdir testbase: permission denied
FAIL
FAIL    github.com/blevesearch/bleve/http       0.075s
ok      github.com/blevesearch/bleve/index/scorch       1.477s
ok      github.com/blevesearch/bleve/index/scorch/mergeplan     (cached)
ok      github.com/blevesearch/bleve/index/scorch/segment       (cached)
ok      github.com/blevesearch/bleve/index/scorch/segment/mem   (cached)
ok      github.com/blevesearch/bleve/index/scorch/segment/zap   1.223s
--- FAIL: TestBoltDBKVCrud (0.00s)
    store_test.go:29: open test: permission denied
--- FAIL: TestBoltDBReaderIsolation (0.00s)
    store_test.go:29: open test: permission denied
--- FAIL: TestBoltDBReaderOwnsGetBytes (0.00s)
    store_test.go:29: open test: permission denied
--- FAIL: TestBoltDBWriterOwnsBytes (0.00s)
    store_test.go:29: open test: permission denied
--- FAIL: TestBoltDBPrefixIterator (0.00s)
    store_test.go:29: open test: permission denied
--- FAIL: TestBoltDBPrefixIteratorSeek (0.00s)
    store_test.go:29: open test: permission denied
--- FAIL: TestBoltDBRangeIterator (0.00s)
    store_test.go:29: open test: permission denied
--- FAIL: TestBoltDBRangeIteratorSeek (0.00s)
    store_test.go:29: open test: permission denied
--- FAIL: TestBoltDBMerge (0.00s)
    store_test.go:29: open test: permission denied
--- FAIL: TestBoltDBConfig (0.00s)
    store_test.go:126: open test: permission denied
FAIL
FAIL    github.com/blevesearch/bleve/index/store/boltdb 0.027s
--- FAIL: TestGoLevelDBKVCrud (0.00s)
    store_test.go:31: mkdir test: permission denied
--- FAIL: TestGoLevelDBReaderIsolation (0.00s)
    store_test.go:31: mkdir test: permission denied
--- FAIL: TestGoLevelDBReaderOwnsGetBytes (0.00s)
    store_test.go:31: mkdir test: permission denied
--- FAIL: TestGoLevelDBWriterOwnsBytes (0.00s)
    store_test.go:31: mkdir test: permission denied
--- FAIL: TestGoLevelDBPrefixIterator (0.00s)
    store_test.go:31: mkdir test: permission denied
--- FAIL: TestGoLevelDBPrefixIteratorSeek (0.00s)
    store_test.go:31: mkdir test: permission denied
--- FAIL: TestGoLevelDBRangeIterator (0.00s)
    store_test.go:31: mkdir test: permission denied
--- FAIL: TestGoLevelDBRangeIteratorSeek (0.00s)
    store_test.go:31: mkdir test: permission denied
--- FAIL: TestGoLevelDBMerge (0.00s)
    store_test.go:31: mkdir test: permission denied
FAIL
FAIL    github.com/blevesearch/bleve/index/store/goleveldb      0.025s
ok      github.com/blevesearch/bleve/index/store/gtreap (cached)
ok      github.com/blevesearch/bleve/index/store/metrics        (cached)
FAIL    github.com/blevesearch/bleve/index/store/moss [build failed]
ok      github.com/blevesearch/bleve/index/store/null   (cached)
--- FAIL: TestDump (0.00s)
    dump_test.go:42: error opening index: open test: permission denied
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x62868a]

goroutine 20 [running]:
testing.tRunner.func1(0xc00014a300)
        /usr/local/google/home/bcmills/go/src/testing/testing.go:830 +0x388
panic(0x6a4860, 0x969d40)
        /usr/local/google/home/bcmills/go/src/runtime/panic.go:522 +0x1b5
github.com/blevesearch/bleve/index/upsidedown.(*UpsideDownCouch).Close(0xc000146100, 0x0, 0x50)
        /tmp/tmp.DLG9ag97ES/_gopath/pkg/mod/github.com/blevesearch/bleve@v0.7.0/index/upsidedown/upsidedown.go:412 +0x2a
github.com/blevesearch/bleve/index/upsidedown.TestDump.func2(0x755ca0, 0xc000146100, 0xc00014a300)
        /tmp/tmp.DLG9ag97ES/_gopath/pkg/mod/github.com/blevesearch/bleve@v0.7.0/index/upsidedown/dump_test.go:45 +0x31
panic(0x6a4860, 0x969d40)
        /usr/local/google/home/bcmills/go/src/runtime/panic.go:522 +0x1b5
github.com/blevesearch/bleve/index/upsidedown.(*UpsideDownCouch).Reader(0xc000146100, 0x0, 0x0, 0x0, 0x0)
        /tmp/tmp.DLG9ag97ES/_gopath/pkg/mod/github.com/blevesearch/bleve@v0.7.0/index/upsidedown/upsidedown.go:1006 +0x41
github.com/blevesearch/bleve/index/upsidedown.TestDump(0xc00014a300)
        /tmp/tmp.DLG9ag97ES/_gopath/pkg/mod/github.com/blevesearch/bleve@v0.7.0/index/upsidedown/dump_test.go:52 +0x25b
testing.tRunner(0xc00014a300, 0x704e88)
        /usr/local/google/home/bcmills/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
        /usr/local/google/home/bcmills/go/src/testing/testing.go:916 +0x357
FAIL    github.com/blevesearch/bleve/index/upsidedown   0.042s
ok      github.com/blevesearch/bleve/mapping    (cached)
ok      github.com/blevesearch/bleve/numeric    (cached)
ok      github.com/blevesearch/bleve/search     (cached)
ok      github.com/blevesearch/bleve/search/collector   (cached)
ok      github.com/blevesearch/bleve/search/facet       (cached) [no tests to run]
ok      github.com/blevesearch/bleve/search/highlight   (cached)
ok      github.com/blevesearch/bleve/search/highlight/format/html       (cached)
ok      github.com/blevesearch/bleve/search/highlight/fragmenter/simple (cached)
ok      github.com/blevesearch/bleve/search/highlight/highlighter/simple        (cached)
ok      github.com/blevesearch/bleve/search/query       (cached)
ok      github.com/blevesearch/bleve/search/scorer      (cached)
ok      github.com/blevesearch/bleve/search/searcher    (cached)
FAIL    github.com/blevesearch/bleve/test [build failed]

$
```

</details><br>

might become:

<details>

```
$ go test github.com/blevesearch/bleve/...
# github.com/couchbase/moss
_gopath/pkg/mod/github.com/couchbase/moss@v0.0.0-20181127195802-b19695552c83/api.go:176:15: undefined: ghistogram.Histograms
_gopath/pkg/mod/github.com/couchbase/moss@v0.0.0-20181127195802-b19695552c83/collection.go:98:13: undefined: ghistogram.Histograms
--- FAIL: TestIndexMeta (0.00s)
    index_meta_test.go:41: mkdir doesnotexit.bleve: permission denied
    index_meta_test.go:48: cannot open index, path does not exist
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8adcc5]

goroutine 87 [running]:
testing.tRunner.func1(0xc0001c6100)
        /usr/local/google/home/bcmills/go/src/testing/testing.go:830 +0x388
panic(0x94b540, 0xe76620)
        /usr/local/google/home/bcmills/go/src/runtime/panic.go:522 +0x1b5
github.com/blevesearch/bleve.TestIndexMeta(0xc0001c6100)
        /tmp/tmp.DLG9ag97ES/_gopath/pkg/mod/github.com/blevesearch/bleve@v0.7.0/index_meta_test.go:50 +0x1a5
testing.tRunner(0xc0001c6100, 0x9f9da8)
        /usr/local/google/home/bcmills/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
        /usr/local/google/home/bcmills/go/src/testing/testing.go:916 +0x357
FAIL    github.com/blevesearch/bleve    0.181s
ok      github.com/blevesearch/bleve/analysis   (cached)
?       github.com/blevesearch/bleve/analysis/analyzer/custom   [no test files]
?       github.com/blevesearch/bleve/analysis/analyzer/keyword  [no test files]
?       github.com/blevesearch/bleve/analysis/analyzer/simple   [no test files]
?       github.com/blevesearch/bleve/analysis/analyzer/standard [no test files]
?       github.com/blevesearch/bleve/analysis/analyzer/web      [no test files]
?       github.com/blevesearch/bleve/analysis/char/html [no test files]
ok      github.com/blevesearch/bleve/analysis/char/regexp       (cached)
?       github.com/blevesearch/bleve/analysis/char/zerowidthnonjoiner   [no test files]
ok      github.com/blevesearch/bleve/analysis/datetime/flexible (cached)
?       github.com/blevesearch/bleve/analysis/datetime/optional [no test files]
ok      github.com/blevesearch/bleve/analysis/lang/ar   (cached)
?       github.com/blevesearch/bleve/analysis/lang/bg   [no test files]
ok      github.com/blevesearch/bleve/analysis/lang/ca   (cached)
ok      github.com/blevesearch/bleve/analysis/lang/cjk  (cached)
ok      github.com/blevesearch/bleve/analysis/lang/ckb  (cached)
?       github.com/blevesearch/bleve/analysis/lang/cs   [no test files]
ok      github.com/blevesearch/bleve/analysis/lang/da   (cached)
ok      github.com/blevesearch/bleve/analysis/lang/de   (cached)
?       github.com/blevesearch/bleve/analysis/lang/el   [no test files]
ok      github.com/blevesearch/bleve/analysis/lang/en   (cached)
ok      github.com/blevesearch/bleve/analysis/lang/es   (cached)
?       github.com/blevesearch/bleve/analysis/lang/eu   [no test files]
ok      github.com/blevesearch/bleve/analysis/lang/fa   (cached)
ok      github.com/blevesearch/bleve/analysis/lang/fi   (cached)
ok      github.com/blevesearch/bleve/analysis/lang/fr   (cached)
ok      github.com/blevesearch/bleve/analysis/lang/ga   (cached)
?       github.com/blevesearch/bleve/analysis/lang/gl   [no test files]
ok      github.com/blevesearch/bleve/analysis/lang/hi   (cached)
ok      github.com/blevesearch/bleve/analysis/lang/hu   (cached)
?       github.com/blevesearch/bleve/analysis/lang/hy   [no test files]
?       github.com/blevesearch/bleve/analysis/lang/id   [no test files]
ok      github.com/blevesearch/bleve/analysis/lang/in   (cached)
ok      github.com/blevesearch/bleve/analysis/lang/it   (cached)
ok      github.com/blevesearch/bleve/analysis/lang/nl   (cached)
ok      github.com/blevesearch/bleve/analysis/lang/no   (cached)
ok      github.com/blevesearch/bleve/analysis/lang/pt   (cached)
ok      github.com/blevesearch/bleve/analysis/lang/ro   (cached)
ok      github.com/blevesearch/bleve/analysis/lang/ru   (cached)
ok      github.com/blevesearch/bleve/analysis/lang/sv   (cached)
ok      github.com/blevesearch/bleve/analysis/lang/tr   (cached)
ok      github.com/blevesearch/bleve/analysis/token/apostrophe  (cached)
ok      github.com/blevesearch/bleve/analysis/token/camelcase   (cached)
ok      github.com/blevesearch/bleve/analysis/token/compound    (cached)
ok      github.com/blevesearch/bleve/analysis/token/edgengram   (cached)
ok      github.com/blevesearch/bleve/analysis/token/elision     (cached)
ok      github.com/blevesearch/bleve/analysis/token/keyword     (cached)
ok      github.com/blevesearch/bleve/analysis/token/length      (cached)
ok      github.com/blevesearch/bleve/analysis/token/lowercase   (cached)
ok      github.com/blevesearch/bleve/analysis/token/ngram       (cached)
ok      github.com/blevesearch/bleve/analysis/token/porter      (cached)
ok      github.com/blevesearch/bleve/analysis/token/shingle     (cached)
ok      github.com/blevesearch/bleve/analysis/token/snowball    (cached)
ok      github.com/blevesearch/bleve/analysis/token/stop        (cached)
ok      github.com/blevesearch/bleve/analysis/token/truncate    (cached)
ok      github.com/blevesearch/bleve/analysis/token/unicodenorm (cached)
ok      github.com/blevesearch/bleve/analysis/token/unique      (cached)
ok      github.com/blevesearch/bleve/analysis/tokenizer/character       (cached)
ok      github.com/blevesearch/bleve/analysis/tokenizer/exception       (cached)
?       github.com/blevesearch/bleve/analysis/tokenizer/letter  [no test files]
ok      github.com/blevesearch/bleve/analysis/tokenizer/regexp  (cached)
ok      github.com/blevesearch/bleve/analysis/tokenizer/single  (cached)
ok      github.com/blevesearch/bleve/analysis/tokenizer/unicode (cached)
ok      github.com/blevesearch/bleve/analysis/tokenizer/web     (cached)
ok      github.com/blevesearch/bleve/analysis/tokenizer/whitespace      (cached)
?       github.com/blevesearch/bleve/analysis/tokenmap  [no test files]
ok      github.com/blevesearch/bleve/document   (cached)
ok      github.com/blevesearch/bleve/geo        (cached)
--- FAIL: TestHandlers (0.00s)
    handlers_test.go:41: mkdir testbase: permission denied
FAIL
FAIL    github.com/blevesearch/bleve/http       0.075s
ok      github.com/blevesearch/bleve/index/scorch       1.477s
ok      github.com/blevesearch/bleve/index/scorch/mergeplan     (cached)
ok      github.com/blevesearch/bleve/index/scorch/segment       (cached)
ok      github.com/blevesearch/bleve/index/scorch/segment/mem   (cached)
ok      github.com/blevesearch/bleve/index/scorch/segment/zap   1.223s
--- FAIL: TestBoltDBKVCrud (0.00s)
    store_test.go:29: open test: permission denied
--- FAIL: TestBoltDBReaderIsolation (0.00s)
    store_test.go:29: open test: permission denied
--- FAIL: TestBoltDBReaderOwnsGetBytes (0.00s)
    store_test.go:29: open test: permission denied
--- FAIL: TestBoltDBWriterOwnsBytes (0.00s)
    store_test.go:29: open test: permission denied
--- FAIL: TestBoltDBPrefixIterator (0.00s)
    store_test.go:29: open test: permission denied
--- FAIL: TestBoltDBPrefixIteratorSeek (0.00s)
    store_test.go:29: open test: permission denied
--- FAIL: TestBoltDBRangeIterator (0.00s)
    store_test.go:29: open test: permission denied
--- FAIL: TestBoltDBRangeIteratorSeek (0.00s)
    store_test.go:29: open test: permission denied
--- FAIL: TestBoltDBMerge (0.00s)
    store_test.go:29: open test: permission denied
--- FAIL: TestBoltDBConfig (0.00s)
    store_test.go:126: open test: permission denied
FAIL
FAIL    github.com/blevesearch/bleve/index/store/boltdb 0.027s
--- FAIL: TestGoLevelDBKVCrud (0.00s)
    store_test.go:31: mkdir test: permission denied
--- FAIL: TestGoLevelDBReaderIsolation (0.00s)
    store_test.go:31: mkdir test: permission denied
--- FAIL: TestGoLevelDBReaderOwnsGetBytes (0.00s)
    store_test.go:31: mkdir test: permission denied
--- FAIL: TestGoLevelDBWriterOwnsBytes (0.00s)
    store_test.go:31: mkdir test: permission denied
--- FAIL: TestGoLevelDBPrefixIterator (0.00s)
    store_test.go:31: mkdir test: permission denied
--- FAIL: TestGoLevelDBPrefixIteratorSeek (0.00s)
    store_test.go:31: mkdir test: permission denied
--- FAIL: TestGoLevelDBRangeIterator (0.00s)
    store_test.go:31: mkdir test: permission denied
--- FAIL: TestGoLevelDBRangeIteratorSeek (0.00s)
    store_test.go:31: mkdir test: permission denied
--- FAIL: TestGoLevelDBMerge (0.00s)
    store_test.go:31: mkdir test: permission denied
FAIL
FAIL    github.com/blevesearch/bleve/index/store/goleveldb      0.025s
ok      github.com/blevesearch/bleve/index/store/gtreap (cached)
ok      github.com/blevesearch/bleve/index/store/metrics        (cached)
FAIL    github.com/blevesearch/bleve/index/store/moss [build failed]
ok      github.com/blevesearch/bleve/index/store/null   (cached)
--- FAIL: TestDump (0.00s)
    dump_test.go:42: error opening index: open test: permission denied
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x62868a]

goroutine 20 [running]:
testing.tRunner.func1(0xc00014a300)
        /usr/local/google/home/bcmills/go/src/testing/testing.go:830 +0x388
panic(0x6a4860, 0x969d40)
        /usr/local/google/home/bcmills/go/src/runtime/panic.go:522 +0x1b5
github.com/blevesearch/bleve/index/upsidedown.(*UpsideDownCouch).Close(0xc000146100, 0x0, 0x50)
        /tmp/tmp.DLG9ag97ES/_gopath/pkg/mod/github.com/blevesearch/bleve@v0.7.0/index/upsidedown/upsidedown.go:412 +0x2a
github.com/blevesearch/bleve/index/upsidedown.TestDump.func2(0x755ca0, 0xc000146100, 0xc00014a300)
        /tmp/tmp.DLG9ag97ES/_gopath/pkg/mod/github.com/blevesearch/bleve@v0.7.0/index/upsidedown/dump_test.go:45 +0x31
panic(0x6a4860, 0x969d40)
        /usr/local/google/home/bcmills/go/src/runtime/panic.go:522 +0x1b5
github.com/blevesearch/bleve/index/upsidedown.(*UpsideDownCouch).Reader(0xc000146100, 0x0, 0x0, 0x0, 0x0)
        /tmp/tmp.DLG9ag97ES/_gopath/pkg/mod/github.com/blevesearch/bleve@v0.7.0/index/upsidedown/upsidedown.go:1006 +0x41
github.com/blevesearch/bleve/index/upsidedown.TestDump(0xc00014a300)
        /tmp/tmp.DLG9ag97ES/_gopath/pkg/mod/github.com/blevesearch/bleve@v0.7.0/index/upsidedown/dump_test.go:52 +0x25b
testing.tRunner(0xc00014a300, 0x704e88)
        /usr/local/google/home/bcmills/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
        /usr/local/google/home/bcmills/go/src/testing/testing.go:916 +0x357
FAIL    github.com/blevesearch/bleve/index/upsidedown   0.042s
ok      github.com/blevesearch/bleve/mapping    (cached)
ok      github.com/blevesearch/bleve/numeric    (cached)
ok      github.com/blevesearch/bleve/search     (cached)
ok      github.com/blevesearch/bleve/search/collector   (cached)
ok      github.com/blevesearch/bleve/search/facet       (cached) [no tests to run]
ok      github.com/blevesearch/bleve/search/highlight   (cached)
ok      github.com/blevesearch/bleve/search/highlight/format/html       (cached)
ok      github.com/blevesearch/bleve/search/highlight/fragmenter/simple (cached)
ok      github.com/blevesearch/bleve/search/highlight/highlighter/simple        (cached)
ok      github.com/blevesearch/bleve/search/query       (cached)
ok      github.com/blevesearch/bleve/search/scorer      (cached)
ok      github.com/blevesearch/bleve/search/searcher    (cached)
FAIL    github.com/blevesearch/bleve/test [build failed]

Failure summary:
FAIL    github.com/blevesearch/bleve    0.160s
FAIL    github.com/blevesearch/bleve/http       0.057s
FAIL    github.com/blevesearch/bleve/index/store/boltdb 0.095s
FAIL    github.com/blevesearch/bleve/index/store/goleveldb      0.033s
FAIL    github.com/blevesearch/bleve/index/store/moss [build failed]
FAIL    github.com/blevesearch/bleve/index/upsidedown   0.035s
FAIL    github.com/blevesearch/bleve/test [build failed]

$
```

</details><br>

**Comment by matloob** [comment]
Is this still an issue? You should be able to run a tool that invokes `go test -json` and produces a useful summary.
