### ISSUE TITLE
runtime error: index out of range

### ISSUE THREAD

**Issue by DieselDraft** [golang/go#13250]
```
func getTasks(name string) []models.TaskQueue {
	limit := 100

13:	indexMutex.Lock()
14:	tasks := models.GetTasks(name, index, limit)
15:	index += tasks[len(tasks)-1].ID
	indexMutex.Unlock()

	return tasks
}
```

```
runtime error: index out of range

goroutine 11 [running]:
taskmanager.getTasks
	/home/oherych/go/src/bitbucket.org/bukorama/app/services/taskmanager/loading.go:15
taskmanager.loading
	/home/oherych/go/src/bitbucket.org/bukorama/app/services/taskmanager/loading.go:24
created by bitbucket.org_bukorama_app_services_taskmanager.Init
	/home/oherych/go/src/bitbucket.org/bukorama/app/services/taskmanager/main.go:19
```

How this possible. I want get last element from slice. I get this error once on 1000 iteration

**Comment by DieselDraft** [comment]
Sorry, this was my mistate. `len(tasks) == 0`  ==> `tasks[-1]`
