### ISSUE TITLE
cmd/godoc: -analytics crashes with too many files open 

### ISSUE THREAD

**Issue by Thomasdezeeuw** [golang/go#13314]
What version of Go are you using (go version)?
`go version devel +f84420c Wed Nov 11 01:04:39 2015 +0000 darwin/amd64`

What operating system and processor architecture are you using?
`OS X 10.10.5`

What did you do?
Ran `godoc -http :23432 -analysis type,pointer`

What did you expect to see?
Godoc running without errors.

What did you see instead?
```
panic: imported["google.golang.org/grpc/benchmark/client"].err = open /Users/thomas/go/src/google.golang.org/grpc/benchmark/client: too many open files

goroutine 1335 [running]:
golang.org/x/tools/go/loader.(*Config).Load(0xc8200b48c0, 0x871f80, 0x0, 0x0)
	/Users/thomas/go/src/golang.org/x/tools/go/loader/loader.go:533 +0x1ea3
golang.org/x/tools/godoc/analysis.Run(0xbd4b01, 0xc82017c170)
	/Users/thomas/go/src/golang.org/x/tools/godoc/analysis/analysis.go:378 +0xc0e
created by main.main
	/Users/thomas/go/src/golang.org/x/tools/cmd/godoc/main.go:310 +0x1afb

goroutine 1 [IO wait]:
net.runtime_pollWait(0x194a010, 0x72, 0xc8200740a0)
	/go/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820546840, 0x72, 0x0, 0x0)
	/go/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820546840, 0x0, 0x0)
	/go/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8205467e0, 0x0, 0x194a108, 0xc820b6bf80)
	/go/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820302430, 0xc8205159e0, 0x0, 0x0)
	/go/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc820302430, 0x0, 0x0, 0x0, 0x0)
	/go/go/src/net/http/server.go:2138 +0x41
net/http.(*Server).Serve(0xc82103a9c0, 0x194a0d0, 0xc820302430, 0x0, 0x0)
	/go/go/src/net/http/server.go:1887 +0xb3
net/http.(*Server).ListenAndServe(0xc82103a9c0, 0x0, 0x0)
	/go/go/src/net/http/server.go:1877 +0x136
net/http.ListenAndServe(0x7fff5fbffcb4, 0x6, 0x1949038, 0xc820076cf0, 0x0, 0x0)
	/go/go/src/net/http/server.go:1967 +0x8f
main.main()
	/Users/thomas/go/src/golang.org/x/tools/cmd/godoc/main.go:314 +0x18fd

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/go/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 1284 [sleep]:
time.Sleep(0x2540be400)
	/go/go/src/runtime/time.go:59 +0xf9
golang.org/x/tools/godoc.(*Corpus).refreshMetadataLoop(0xc82017c000)
	/Users/thomas/go/src/golang.org/x/tools/godoc/meta.go:142 +0x5b
created by golang.org/x/tools/godoc.(*Corpus).Init
	/Users/thomas/go/src/golang.org/x/tools/godoc/corpus.go:145 +0x8a
```

I know this error can be solved by increasing the limit, however maybe there should be a limit on how many files should be opened at the same time for analysing. Especially with a big $GOPATH/src folder it's easy to run into this error.

**Comment by rsc** [comment]
The bug report is using code from Nov 11. It's possible this is fixed.

**Comment by Thomasdezeeuw** [comment]
I just pulled the latest changes (`go version devel +c7c7c70 Mon Dec 28 01:12:24 2015 +0000 darwin/amd64`) recompiled and tried again, but got the same result.

**Comment by alandonovan** [comment]
Hi Thomas, thanks for reporting this crash.

The particular crash you're seeing isn't caused by too many open files (though that has been a problem in the past), but a sanity-check assertion, one that was recently removed due to some internal design changes that made it irrelevant.  Could you sync and build the latest code in `golang.org/x/tools` and try again?

thanks
alan

BTW, the version numbers you reported relate to the main `golang.org` repo which provides the toolchain and the standard library, but not godoc itself.  Use this command instead:

```
  $ cd $HOME/got3/src/golang.org/x/tools && git log | head -n 1
```

**Comment by Thomasdezeeuw** [comment]
Just ran with `golang.org/x/tools` at `a09dffbb6c9a92df8f0380ce64dc56316d3af9a1` and `go` at `8d5ff2e182c52c4fa6af18e536dcef6e12ad8cb2` and got the same error.

```
panic: imported["github.com/golang/tools/godoc/dl"].err = open /Users/thomas/go/src/github.com/golang/tools/godoc/dl: too many open files

goroutine 1416 [running]:
golang.org/x/tools/go/loader.(*Config).Load(0xc820924000, 0x871f80, 0x0, 0x0)
	/Users/thomas/go/src/golang.org/x/tools/go/loader/loader.go:533 +0x1ea3
golang.org/x/tools/godoc/analysis.Run(0xbd4b01, 0xc82014e4b0)
	/Users/thomas/go/src/golang.org/x/tools/godoc/analysis/analysis.go:378 +0xc0e
created by main.main
	/Users/thomas/go/src/golang.org/x/tools/cmd/godoc/main.go:310 +0x1afb

goroutine 1 [IO wait]:
net.runtime_pollWait(0x1e44038, 0x72, 0xc820010190)
	/go/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82112abc0, 0x72, 0x0, 0x0)
	/go/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82112abc0, 0x0, 0x0)
	/go/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc82112ab60, 0x0, 0x1e44130, 0xc820a83840)
	/go/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc8202144e8, 0xc82092d9e0, 0x0, 0x0)
	/go/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc8202144e8, 0x0, 0x0, 0x0, 0x0)
	/go/go/src/net/http/server.go:2138 +0x41
net/http.(*Server).Serve(0xc820e66660, 0x1e440f8, 0xc8202144e8, 0x0, 0x0)
	/go/go/src/net/http/server.go:1887 +0xb3
net/http.(*Server).ListenAndServe(0xc820e66660, 0x0, 0x0)
	/go/go/src/net/http/server.go:1877 +0x136
net/http.ListenAndServe(0x7fff5fbffc8c, 0x6, 0x1e43060, 0xc820014d20, 0x0, 0x0)
	/go/go/src/net/http/server.go:1967 +0x8f
main.main()
	/Users/thomas/go/src/golang.org/x/tools/cmd/godoc/main.go:314 +0x18fd

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/go/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 1297 [sleep]:
time.Sleep(0x2540be400)
	/go/go/src/runtime/time.go:59 +0xf9
golang.org/x/tools/godoc.(*Corpus).refreshMetadataLoop(0xc82014e340)
	/Users/thomas/go/src/golang.org/x/tools/godoc/meta.go:142 +0x5b
created by golang.org/x/tools/godoc.(*Corpus).Init
	/Users/thomas/go/src/golang.org/x/tools/godoc/corpus.go:145 +0x8a
```

**Comment by alandonovan** [comment]
On 29 December 2015 at 20:57, Thomas de Zeeuw <notifications@github.com>
wrote:

> Just ran with golang.org/x/tools at
> a09dffbb6c9a92df8f0380ce64dc56316d3af9a1 and go at
> 8d5ff2e182c52c4fa6af18e536dcef6e12ad8cb2 and got the same error.
>
> panic: imported["github.com/golang/tools/godoc/dl"].err = open /Users/thomas/go/src/github.com/golang/tools/godoc/dl: too many open files
>
>
Are you certain you're using a binary built from the most recent version of
golang.org/x/tools/go/loader/loader.go?  The hash a09dffb looks right, but
the stack trace tells me that the version of this file is 739a26a from back
in August.  The assertion on line 533 moved around on every subsequent
revision, and was deleted entirely last week.

cheers
alan

**Comment by Thomasdezeeuw** [comment]
I just updated again and it's fixed.

**Comment by Thomasdezeeuw** [comment]
Thanks for you patience.
