### ISSUE TITLE
Runtine panic

### ISSUE THREAD

**Issue by Qteam** [golang/go#13353]
I get panic while loading a data from Mysql table, but panic is from runtime:
```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0xf1 pc=0x5333db]

runtime stack:
runtime.throw(0xa5a9e0, 0x2a)
        /usr/local/go/src/runtime/panic.go:527 +0x90
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.munmap(0x7f4dcebfb000, 0x123ede0, 0x4f5d89, 0x7f4dcebfb000, 0x123ede0, 0xe75ce0, 0x36bc9a, 0x7f4dcebfb000, 0x247dbc, 0x247dbc, ...)
        /usr/local/go/src/runtime/sys_linux_amd64.s:266 +0x1b
runtime.sysFree(0x7f4dcebfb000, 0x123ede0, 0xe75ce0)
        /usr/local/go/src/runtime/mem_linux.go:103 +0x34
runtime.recordspan(0xe56b60, 0x7f4dc96a71c0)
        /usr/local/go/src/runtime/mheap.go:174 +0x229
runtime.fixAlloc_Alloc(0xe62e78, 0x4e4544)
        /usr/local/go/src/runtime/mfixalloc.go:74 +0x14f
runtime.mHeap_AllocSpanLocked(0xe56b60, 0x1, 0x7f4dc96a70e0)
        /usr/local/go/src/runtime/mheap.go:561 +0x1a7
runtime.mHeap_Alloc_m(0xe56b60, 0x1, 0x3, 0x7f4dc96a70e0)
        /usr/local/go/src/runtime/mheap.go:425 +0x1ac
runtime.mHeap_Alloc.func1()
        /usr/local/go/src/runtime/mheap.go:484 +0x41
runtime.systemstack(0x7ffff3f16cc0)
        /usr/local/go/src/runtime/asm_amd64.s:278 +0xab
runtime.mHeap_Alloc(0xe56b60, 0x1, 0x10000000003, 0x4e4544)
        /usr/local/go/src/runtime/mheap.go:485 +0x63
runtime.mCentral_Grow(0xe5e278, 0x0)
        /usr/local/go/src/runtime/mcentral.go:190 +0x93
runtime.mCentral_CacheSpan(0xe5e278, 0x7f4dc96a70e0)
        /usr/local/go/src/runtime/mcentral.go:86 +0x4d4
runtime.mCache_Refill(0x7f4e0bc3b2e0, 0x3, 0x7f4dc96a70e0)
        /usr/local/go/src/runtime/mcache.go:118 +0xcf
runtime.mallocgc.func2()
        /usr/local/go/src/runtime/malloc.go:611 +0x2b
runtime.systemstack(0xe4ef20)
        /usr/local/go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
        /usr/local/go/src/runtime/proc1.go:674
```

**Comment by Qteam** [comment]
The server is on CentOS release 6.3

Full stack, if you need it:

```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0xf1 pc=0x5333db]

runtime stack:
runtime.throw(0xa5a9e0, 0x2a)
        /usr/local/go/src/runtime/panic.go:527 +0x90
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.munmap(0x7f4dcebfb000, 0x123ede0, 0x4f5d89, 0x7f4dcebfb000, 0x123ede0, 0xe75ce0, 0x36bc9a, 0x7f4dcebfb000, 0x247dbc, 0x247dbc, ...)
        /usr/local/go/src/runtime/sys_linux_amd64.s:266 +0x1b
runtime.sysFree(0x7f4dcebfb000, 0x123ede0, 0xe75ce0)
        /usr/local/go/src/runtime/mem_linux.go:103 +0x34
runtime.recordspan(0xe56b60, 0x7f4dc96a71c0)
        /usr/local/go/src/runtime/mheap.go:174 +0x229
runtime.fixAlloc_Alloc(0xe62e78, 0x4e4544)
        /usr/local/go/src/runtime/mfixalloc.go:74 +0x14f
runtime.mHeap_AllocSpanLocked(0xe56b60, 0x1, 0x7f4dc96a70e0)
        /usr/local/go/src/runtime/mheap.go:561 +0x1a7
runtime.mHeap_Alloc_m(0xe56b60, 0x1, 0x3, 0x7f4dc96a70e0)
        /usr/local/go/src/runtime/mheap.go:425 +0x1ac
runtime.mHeap_Alloc.func1()
        /usr/local/go/src/runtime/mheap.go:484 +0x41
runtime.systemstack(0x7ffff3f16cc0)
        /usr/local/go/src/runtime/asm_amd64.s:278 +0xab
runtime.mHeap_Alloc(0xe56b60, 0x1, 0x10000000003, 0x4e4544)
        /usr/local/go/src/runtime/mheap.go:485 +0x63
runtime.mCentral_Grow(0xe5e278, 0x0)
        /usr/local/go/src/runtime/mcentral.go:190 +0x93
runtime.mCentral_CacheSpan(0xe5e278, 0x7f4dc96a70e0)
        /usr/local/go/src/runtime/mcentral.go:86 +0x4d4
runtime.mCache_Refill(0x7f4e0bc3b2e0, 0x3, 0x7f4dc96a70e0)
        /usr/local/go/src/runtime/mcache.go:118 +0xcf
runtime.mallocgc.func2()
        /usr/local/go/src/runtime/malloc.go:611 +0x2b
runtime.systemstack(0xe4ef20)
        /usr/local/go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
        /usr/local/go/src/runtime/proc1.go:674

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc9e7356d50 sp=0xc9e7356d48
runtime.mallocgc(0x20, 0x85f900, 0x0, 0xcb30102aa0)
        /usr/local/go/src/runtime/malloc.go:612 +0x842 fp=0xc9e7356e20 sp=0xc9e7356d50
runtime.newobject(0x85f900, 0x1)
        /usr/local/go/src/runtime/malloc.go:760 +0x42 fp=0xc9e7356e48 sp=0xc9e7356e20
runtime.convT2E(0x85f900, 0xc9e7356f48, 0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/iface.go:138 +0xc9 fp=0xc9e7356e70 sp=0xc9e7356e48
github.com/go-sql-driver/mysql.(*mysqlRows).readRow(0xca304d1b90, 0xcae5fcec80, 0x13, 0x13, 0x0, 0x0)
        /home/httpd/mydomain.com/content/go/gocode/src/github.com/go-sql-driver/mysql/packets.go:560 +0x206 fp=0xc9e7356f98 sp=0xc9e7356e70
github.com/go-sql-driver/mysql.(*mysqlRows).Next(0xca304d1b90, 0xcae5fcec80, 0x13, 0x13, 0x0, 0x0)
        /home/httpd/mydomain.com/content/go/gocode/src/github.com/go-sql-driver/mysql/rows.go:70 +0x20b fp=0xc9e7357008 sp=0xc9e7356f98
database/sql.(*Rows).Next(0xca4f61e3c0, 0xc9e73579c0)
        /usr/local/go/src/database/sql/sql.go:1639 +0x12b fp=0xc9e7357090 sp=0xc9e7357008
main.loadTrade(0xc97d33c0a0, 0x1)
        /home/httpd/mydomain.com/content/go/gocode/src/myproj2c/loadData.go:2520 +0x43b9 fp=0xc9e7357af8 sp=0xc9e7357090
main.prepareData()
        /home/httpd/mydomain.com/content/go/gocode/src/myproj2c/myproj2c.go:5655 +0x1f1f fp=0xc9e7357e10 sp=0xc9e7357af8
main.main()
        /home/httpd/mydomain.com/content/go/gocode/src/myproj2c/myproj2c.go:6331 +0x37 fp=0xc9e7357f40 sp=0xc9e7357e10
runtime.main()
        /usr/local/go/src/runtime/proc.go:111 +0x2b0 fp=0xc9e7357f90 sp=0xc9e7357f40
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc9e7357f98 sp=0xc9e7357f90

goroutine 17 [syscall, 31 minutes, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 18 [syscall, 31 minutes]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 20 [sleep]:
time.Sleep(0x12a05f200)
        /usr/local/go/src/runtime/time.go:59 +0xf9
main.cronServerInfo()
        /home/httpd/mydomain.com/content/go/gocode/src/myproj2c/myproj2c.go:6270 +0x11da
created by main.prepareData
        /home/httpd/mydomain.com/content/go/gocode/src/myproj2c/myproj2c.go:5485 +0x1af

goroutine 50 [sleep]:
time.Sleep(0x2540be400)
        /usr/local/go/src/runtime/time.go:59 +0xf9
main.sendServerStatus()
        /home/httpd/mydomain.com/content/go/gocode/src/myproj2c/rpc.go:2721 +0x56
created by main.prepareData
        /home/httpd/mydomain.com/content/go/gocode/src/myproj2c/myproj2c.go:5526 +0x888

goroutine 72 [syscall, 31 minutes]:
syscall.Syscall6(0x3d, 0x79cb, 0xc820052cd4, 0x0, 0xc82111e480, 0x0, 0x0, 0x8e4cc0, 0xc8219825a0, 0x3)
        /usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.wait4(0x79cb, 0xc820052cd4, 0x0, 0xc82111e480, 0x90, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_linux_amd64.go:172 +0x72
syscall.Wait4(0x79cb, 0xc820052d1c, 0x0, 0xc82111e480, 0xc820128050, 0x0, 0x0)
        /usr/local/go/src/syscall/syscall_linux.go:256 +0x55
os.(*Process).wait(0xc82272c160, 0x10, 0x0, 0x0)
        /usr/local/go/src/os/exec_unix.go:22 +0x105
os.(*Process).Wait(0xc82272c160, 0x0, 0x0, 0x0)
        /usr/local/go/src/os/doc.go:45 +0x2d
os/exec.(*Cmd).Wait(0xc8219ad2c0, 0x0, 0x0)
        /usr/local/go/src/os/exec/exec.go:380 +0x211
os/exec.(*Cmd).Run(0xc8219ad2c0, 0x0, 0x0)
        /usr/local/go/src/os/exec/exec.go:258 +0x64
main.sphinxPrepare.func1()
        /home/httpd/mydomain.com/content/go/gocode/src/myproj2c/myproj2c.go:4913 +0xfa
created by main.sphinxPrepare
        /home/httpd/mydomain.com/content/go/gocode/src/myproj2c/myproj2c.go:4915 +0x2bb

goroutine 748 [chan receive, 2 minutes]:
database/sql.(*DB).connectionOpener(0xc97d33c0a0)
        /usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
        /usr/local/go/src/database/sql/sql.go:481 +0x336
```

**Comment by Qteam** [comment]
$ go version
go version go1.5.1 linux/amd64

**Comment by ianlancetaylor** [comment]
Almost certainly #13227 .
