### ISSUE TITLE
x/tools/oracle: describe package panics if the package doesn't exist

### ISSUE THREAD

**Issue by LMMilewski** [golang/go#13380]
Given the code

```
package main

import "doesntexist"

func main() {}
```

The command
```
oracle -pos=oraclepanic.go:#23 describe
```

Panics
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x48 pc=0xe1abf]

goroutine 1 [running]:
golang.org/x/tools/oracle.describePackage(0x82072d340, 0x82072d310, 0x3, 0x3, 0x82072d310, 0x0, 0x0)
	/Users/lukaszmilewski/p/src/golang.org/x/tools/oracle/describe.go:522 +0x16f
golang.org/x/tools/oracle.describe(0x8207dc930, 0x0, 0x0)
	/Users/lukaszmilewski/p/src/golang.org/x/tools/oracle/describe.go:64 +0x724
golang.org/x/tools/oracle.Run(0x8207dc930, 0x0, 0x0)
	/Users/lukaszmilewski/p/src/golang.org/x/tools/oracle/oracle.go:126 +0x416
main.main()
	/Users/lukaszmilewski/p/src/golang.org/x/tools/cmd/oracle/main.go:178 +0x6d8
```

**Comment by alandonovan** [comment]
https://go-review.googlesource.com/#/c/18215/
