### ISSUE TITLE
x/tools/cmd/oracle: panic: runtime error: index out of range

### ISSUE THREAD

**Issue by tamird** [golang/go#13459]
I don't have a reduced case for this, but it is reproducible on https://github.com/cockroachdb/cockroach/commit/02c6eae14bff51cda9a5cc8dea1552b71c1451a8 with the invocation `oracle -pos=sql/parser/type_check.go:#8409 -format=plain referrers`, and produces the following output:
```
/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/expr.go:282:6: 68 references to type QualifiedName struct{Base Name; Indirect Indirection; normalized nameType}
/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/alter_table.go:28.12-28.24: 	Table    *QualifiedName
/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/create.go:50.15-50.27: 	Table       *QualifiedName
/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/create.go:265.15-265.27: 	Table       *QualifiedName
/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/eval.go:1038.10-1038.22: func (t *QualifiedName) Eval(_ EvalContext) (Datum, error) {
/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/expr.go:279.23-279.35: var _ VariableExpr = &QualifiedName{}
/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/expr.go:289.8-289.20: func (*QualifiedName) Variable() {}
/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/expr.go:292.18-292.30: func StarExpr() *QualifiedName {
/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/expr.go:293.10-293.22: 	return &QualifiedName{Indirect: Indirection{unqualifiedStar}}
/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/expr.go:309.10-309.22: func (n *QualifiedName) NormalizeTableName(database string) error {
/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/expr.go:373.10-373.22: func (n *QualifiedName) NormalizeColumnName() error {
/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/expr.go:421.10-421.22: func (n *QualifiedName) Database() string {
/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/expr.go:431.10-431.22: func (n *QualifiedName) Table() string {
/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/expr.go:443.10-443.22: func (n *QualifiedName) Index() string {
/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/expr.go:455.10-455.22: func (n *QualifiedName) Column() string {
/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/expr.go:463.10-463.22: func (n *QualifiedName) IsStar() bool {
/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/expr.go:476.10-476.22: func (n *QualifiedName) String() string {
/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/expr.go:486.24-486.36: type QualifiedNames []*QualifiedName
/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/expr.go:633.12-633.24: 	Name     *QualifiedName
/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/expr_test.go:49.9-49.21: 		q := &QualifiedName{Base: Name(tc.in)}
/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/expr_test.go:81.43-81.55: 		q := stmts[0].(*Select).Exprs[0].Expr.(*QualifiedName)
/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/expr_test.go:124.43-124.55: 		q := stmts[0].(*Select).Exprs[0].Expr.(*QualifiedName)
/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/insert.go:33.11-33.23: 	Table   *QualifiedName
/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/normalize.go:92.38-92.50: 				case *BinaryExpr, VariableExpr, *QualifiedName, ValArg:
/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/rename.go:43.12-43.24: 	Name     *QualifiedName
/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/rename.go:44.12-44.24: 	NewName  *QualifiedName
/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/rename.go:60.12-60.24: 	Name     *QualifiedName
/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/rename.go:77.11-77.23: 	Table   *QualifiedName
/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/select.go:162.7-162.19: func (QualifiedName) simpleTableExpr() {}
/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/set.go:30.10-30.22: 	Name   *QualifiedName
/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/show.go:42.9-42.21: 	Table *QualifiedName
/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/show.go:62.9-62.21: 	Table *QualifiedName
/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/show.go:71.8-71.20: 	Name *QualifiedName
/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/sql.y:39.18-39.30:   qnames         QualifiedNames
panic: runtime error: index out of range

goroutine 1 [running]:
golang.org/x/tools/oracle.(*referrersResult).display(0xc8411f6e80, 0xc8411d3540)
	/Users/tamird/src/go/src/golang.org/x/tools/oracle/referrers.go:206 +0x98f
golang.org/x/tools/oracle.(*Query).WriteTo(0xc8200f08c0, 0x8ce1a0, 0xc820098008)
	/Users/tamird/src/go/src/golang.org/x/tools/oracle/oracle.go:105 +0x9a
main.main()
	/Users/tamird/src/go/src/golang.org/x/tools/cmd/oracle/main.go:202 +0xe34

goroutine 17029 [chan send]:
golang.org/x/tools/oracle.(*referrersResult).display.func1(0xc823f036d0, 0x45, 0x160f, 0xcc, 0x21, 0xc8411f73c0)
	/Users/tamird/src/go/src/golang.org/x/tools/oracle/referrers.go:193 +0x1d8
created by golang.org/x/tools/oracle.(*referrersResult).display
	/Users/tamird/src/go/src/golang.org/x/tools/oracle/referrers.go:194 +0x53f

goroutine 17027 [chan send]:
golang.org/x/tools/oracle.(*referrersResult).display.func1(0xc8215e9aa0, 0x52, 0x20d8, 0x151, 0xd, 0xc8411f7340)
	/Users/tamird/src/go/src/golang.org/x/tools/oracle/referrers.go:193 +0x1d8
created by golang.org/x/tools/oracle.(*referrersResult).display
	/Users/tamird/src/go/src/golang.org/x/tools/oracle/referrers.go:194 +0x53f

goroutine 17026 [runnable]:
golang.org/x/tools/oracle.(*referrersResult).display.func1(0xc826b29cc0, 0x4c, 0x2212e, 0x24d, 0x14, 0xc8411f7280)
	/Users/tamird/src/go/src/golang.org/x/tools/oracle/referrers.go:193 +0x1d8
created by golang.org/x/tools/oracle.(*referrersResult).display
	/Users/tamird/src/go/src/golang.org/x/tools/oracle/referrers.go:194 +0x53f

goroutine 17030 [chan send]:
golang.org/x/tools/oracle.(*referrersResult).display.func1(0xc823edf630, 0x45, 0x1c17, 0x104, 0x3d, 0xc8411f7400)
	/Users/tamird/src/go/src/golang.org/x/tools/oracle/referrers.go:193 +0x1d8
created by golang.org/x/tools/oracle.(*referrersResult).display
	/Users/tamird/src/go/src/golang.org/x/tools/oracle/referrers.go:194 +0x53f

goroutine 17031 [chan send]:
golang.org/x/tools/oracle.(*referrersResult).display.func1(0xc823d9c5a0, 0x45, 0x1a1c, 0xdf, 0x14, 0xc8411f74c0)
	/Users/tamird/src/go/src/golang.org/x/tools/oracle/referrers.go:193 +0x1d8
created by golang.org/x/tools/oracle.(*referrersResult).display
	/Users/tamird/src/go/src/golang.org/x/tools/oracle/referrers.go:194 +0x53f

goroutine 17028 [chan send]:
golang.org/x/tools/oracle.(*referrersResult).display.func1(0xc82437b9a0, 0x4c, 0xd53, 0x79, 0x8, 0xc8411f7380)
	/Users/tamird/src/go/src/golang.org/x/tools/oracle/referrers.go:193 +0x1d8
created by golang.org/x/tools/oracle.(*referrersResult).display
	/Users/tamird/src/go/src/golang.org/x/tools/oracle/referrers.go:194 +0x53f

goroutine 17033 [chan send]:
golang.org/x/tools/oracle.(*referrersResult).display.func1(0xc823d9c9b0, 0x46, 0x1254, 0xae, 0x2e, 0xc8411f7540)
	/Users/tamird/src/go/src/golang.org/x/tools/oracle/referrers.go:193 +0x1d8
created by golang.org/x/tools/oracle.(*referrersResult).display
	/Users/tamird/src/go/src/golang.org/x/tools/oracle/referrers.go:194 +0x53f

goroutine 17032 [chan send]:
golang.org/x/tools/oracle.(*referrersResult).display.func1(0xc823d9c640, 0x45, 0x688, 0x34, 0x21, 0xc8411f7500)
	/Users/tamird/src/go/src/golang.org/x/tools/oracle/referrers.go:193 +0x1d8
created by golang.org/x/tools/oracle.(*referrersResult).display
	/Users/tamird/src/go/src/golang.org/x/tools/oracle/referrers.go:194 +0x53f
```

**Comment by alandonovan** [comment]
Fixed by https://go-review.googlesource.com/18209
