### ISSUE TITLE
cmd/compile: runs out of memory allocating 12k + items in a map at init, works as literal map

### ISSUE THREAD

**Issue by pindamonhangaba** [golang/go#13554]
On Ubuntu 14.04, Go 1.4.1 64 bits code compiles fine, with 1.5.2 64 bits I get the following error:

```
    # command-line-arguments
    fatal error: runtime: out of memory

    runtime stack:
    runtime.throw(0x843f10, 0x16)
            /usr/local/go/src/runtime/panic.go:527 +0x90
    runtime.sysMap(0xc8fc0c0000, 0xf6d0000, 0x44a600, 0xdab818)
            /usr/local/go/src/runtime/mem_linux.go:203 +0x9b
    runtime.mHeap_SysAlloc(0xc95400, 0xf6d0000, 0x0)
            /usr/local/go/src/runtime/malloc.go:426 +0x160
    runtime.mHeap_Grow(0xc95400, 0x7b68, 0x0)
            /usr/local/go/src/runtime/mheap.go:628 +0x63
    runtime.mHeap_AllocSpanLocked(0xc95400, 0x7b63, 0x0)
            /usr/local/go/src/runtime/mheap.go:532 +0x5f1
    runtime.mHeap_Alloc_m(0xc95400, 0x7b63, 0x100000000, 0xc81982ccff)
            /usr/local/go/src/runtime/mheap.go:425 +0x1ac
    runtime.mHeap_Alloc.func1()
            /usr/local/go/src/runtime/mheap.go:484 +0x41
    runtime.systemstack(0xc82003dee0)
            /usr/local/go/src/runtime/asm_amd64.s:278 +0xab
    runtime.mHeap_Alloc(0xc95400, 0x7b63, 0x100000000, 0xc820022720)
            /usr/local/go/src/runtime/mheap.go:485 +0x63
    runtime.largeAlloc(0xf6c6000, 0x3, 0x0)
            /usr/local/go/src/runtime/malloc.go:748 +0xb3
    runtime.mallocgc.func3()
            /usr/local/go/src/runtime/malloc.go:637 +0x33
    runtime.systemstack(0xc820021500)
            /usr/local/go/src/runtime/asm_amd64.s:262 +0x79
    runtime.mstart()
            /usr/local/go/src/runtime/proc1.go:668

    goroutine 1 [running]:
    runtime.systemstack_switch()
            /usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc8b55892c8 sp=0xc8b55892c0
    runtime.mallocgc(0xf6c6000, 0x0, 0x3, 0xc8efa66000)
            /usr/local/go/src/runtime/malloc.go:638 +0x9c4 fp=0xc8b5589398 sp=0xc8b55892c8
    runtime.rawmem(0xf6c6000, 0xc8b55893d8)
            /usr/local/go/src/runtime/malloc.go:791 +0x32 fp=0xc8b55893c0 sp=0xc8b5589398
    runtime.growslice(0x785c20, 0xc8efa66000, 0xc56a000, 0xc56a000, 0xc56a001, 0x0, 0x0, 0x0)
            /usr/local/go/src/runtime/slice.go:92 +0x233 fp=0xc8b5589430 sp=0xc8b55893c0
    cmd/internal/obj.Symgrow(0xc8200aa000, 0xc8309ec1e0, 0xc56a001)
            /usr/local/go/src/cmd/internal/obj/data.go:52 +0x23b fp=0xc8b55894f0 sp=0xc8b5589430
    cmd/internal/obj.Setuintxx(0xc8200aa000, 0xc8309ec1e0, 0xc56a000, 0x0, 0x1, 0xc56a000)
            /usr/local/go/src/cmd/internal/obj/data.go:126 +0x76 fp=0xc8b5589548 sp=0xc8b55894f0
    cmd/compile/internal/gc.duintxx(0xc8309a5100, 0xc56a000, 0x0, 0x1, 0xc56a000)
            /usr/local/go/src/cmd/compile/internal/gc/obj.go:178 +0x97 fp=0xc8b5589630 sp=0xc8b5589548
    cmd/compile/internal/gc.duint8(0xc8309a5100, 0xc56a000, 0x12b00, 0xc56a000)
            /usr/local/go/src/cmd/compile/internal/gc/obj.go:182 +0x3e fp=0xc8b5589660 sp=0xc8b5589630
    cmd/compile/internal/gc.onebitwritesymbol(0xc8bcc82000, 0x63df, 0x7600, 0xc8309a5100)
            /usr/local/go/src/cmd/compile/internal/gc/plive.go:1747 +0x19b fp=0xc8b55896e8 sp=0xc8b5589660
    cmd/compile/internal/gc.liveness(0xc8201fcc60, 0xc8214de000, 0xc8309a5080, 0xc8309a5100)
            /usr/local/go/src/cmd/compile/internal/gc/plive.go:1815 +0x3ba fp=0xc8b55897c8 sp=0xc8b55896e8
    cmd/compile/internal/gc.compile(0xc8201fcc60)
            /usr/local/go/src/cmd/compile/internal/gc/pgen.go:528 +0xe07 fp=0xc8b5589a38 sp=0xc8b55897c8
    cmd/compile/internal/gc.funccompile(0xc8201fcc60)
            /usr/local/go/src/cmd/compile/internal/gc/dcl.go:1484 +0x1c9 fp=0xc8b5589ab0 sp=0xc8b5589a38
    cmd/compile/internal/gc.Main()
            /usr/local/go/src/cmd/compile/internal/gc/lex.go:473 +0x1f08 fp=0xc8b5589db0 sp=0xc8b5589ab0
    cmd/compile/internal/amd64.Main()
            /usr/local/go/src/cmd/compile/internal/amd64/galign.go:127 +0x58d fp=0xc8b5589e18 sp=0xc8b5589db0
    main.main()
            /usr/local/go/src/cmd/compile/main.go:26 +0x189 fp=0xc8b5589ef0 sp=0xc8b5589e18
    runtime.main()
            /usr/local/go/src/runtime/proc.go:111 +0x2b0 fp=0xc8b5589f40 sp=0xc8b5589ef0
    runtime.goexit()
            /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc8b5589f48 sp=0xc8b5589f40
```

As a side note, after compiling this example I saw that the executable had around 500 MB in size! So I realized that I should've just made it a literal map, and that brought it back to 8MB. And it compiled in both 1.4.1 and 1.5.2.

[noram.go](https://github.com/golang/go/files/57320/noram.go.txt)

**Comment by ianlancetaylor** [comment]
This is the compiler running out of memory, not the runtime.

**Comment by aclements** [comment]
I don't think this is new in 1.5.2. Both 1.5.2 and 1.4.1 use ~3.5GB of memory when compiling this.

```
$ /usr/bin/time $(gover run 1.5.2 go tool -n compile noram.go)
28.48user 8.36system 0:31.88elapsed 115%CPU (0avgtext+0avgdata 3512724maxresident)k
25224inputs+506144outputs (108major+800295minor)pagefaults 0swaps
$ du -h noram.o
248M	noram.o

$ /usr/bin/time $(gover run 1.4.1 go tool -n 6g noram.go) 
17.16user 2.46system 0:20.93elapsed 93%CPU (0avgtext+0avgdata 3701620maxresident)k
248inputs+983576outputs (1major+922620minor)pagefaults 0swaps
$ du -h noram.o
248M	noram.o
```

Tip (b8b65c1) is basically the same as 1.5.2. Since the memory use of the C version of the compiler is similar to the Go version of the compiler (a little worse, actually), this is certainly just the compiler using a lot of memory and not a runtime memory management issue.

**Comment by randall77** [comment]
This appears somewhat better now.  It only used ~2GB to compile at tip.
I'm going to punt this to 1.8 for now.  Almost freeze and no pending changes I know of will help this issue.

**Comment by josharian** [comment]
Comparing 1.7.5, 1.8.1, and tip at c20e54533ea49ca68640d9a59c9ed935b27da8e5 shows a mixed bag. Compile time is up, but memory use is down, and object file size is way down.

```
name \ time/op       17           18           tip
Pkg                   18.1s ± 3%   32.3s ± 3%   53.1s ± 2%

name \ user-time/op  17           18           tip
Pkg                   20.9s ± 4%   35.2s ± 3%   55.0s ± 2%

name \ alloc/op      17           18           tip
Pkg                  2.58GB ± 0%  4.14GB ± 0%  2.04GB ± 0%

name \ allocs/op     17           18           tip
Pkg                   6.34M ± 0%   6.99M ± 0%   6.21M ± 0%

name \ object-bytes  17           18           tip
Pkg                    252M ± 0%    193M ± 0%     28M ± 0%

name \ export-bytes  17           18           tip
Pkg                     176 ± 0%     181 ± 0%     208 ± 0%
```

I suspect that the memory usage decrease is due to CL 35114.

Compiling this file now spends a whopping 64% of its CPU time on line fuse.go:123, which is `v.Block = c` from:

```go
	// move all of b's values to c.
	for _, v := range b.Values {
		v.Block = c
	}
```

Looks like fuseBlockPlain is accidentally quadratic. In a long series of plain blocks, every value gets moved along one at a time, block by block. I'll think about whether there's a low risk fix for that.

**Comment by josharian** [comment]
There were actually two quadratic bits. CLs 43570 and 43571 contain fairly minimal fixes for them. Up to @randall77 and @cherrymui whether they want them for 1.9 or 1.10, and whether @cherrymui would like to do 43571 differently.

After those CLs, this code now compiles in a somewhat acceptable 8s, although memory usage is still high at 2gb. I don't see any obvious next fixes for the memory usage. The next likely source of speed-ups would be to fix #20393.

**Comment by odeke-em** [comment]
@aclements, you added "wait-release" to @randall77's CL https://go-review.googlesource.com/c/go/+/151497/ but this issue is still triaged for Go1.12.
Should we perhaps move this to Go1.13? After all this isn't necessarily a new regression as it has existed since Go1.4*

**Comment by randall77** [comment]
Tip uses only about 1.2GB to compile this example now.
I'm going to close as fixed.
(I'm sure there's more we could do, but we can track that work on other issues.)
