### ISSUE TITLE
runtime: deadlock in cmd/dist on darwin-amd64

### ISSUE THREAD

**Issue by broady** [golang/go#13664]
This error occurred while building the go1.6 beta release:
`$ release -user release -version go1.6beta1 -rev d0f472e99ad31ef3aa842800eff9861dab4778de -tools master -skip_tests`

```
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive (nil chan)]:
main.install(0x7fff5fbff5ef, 0x7)
	/usr/local/go/src/cmd/dist/build.go:504 +0x205
main.cmdinstall()
	/usr/local/go/src/cmd/dist/build.go:1144 +0xe5
main.xmain()
	/usr/local/go/src/cmd/dist/main.go:42 +0x1e9
main.main()
	/usr/local/go/src/cmd/dist/util.go:502 +0x58a

goroutine 20 [select]:
main.bghelper()
	/usr/local/go/src/cmd/dist/util.go:152 +0x152
created by main.bginit
	/usr/local/go/src/cmd/dist/util.go:145 +0x5a

goroutine 21 [select]:
main.bghelper()
	/usr/local/go/src/cmd/dist/util.go:152 +0x152
created by main.bginit
	/usr/local/go/src/cmd/dist/util.go:145 +0x5a

goroutine 22 [select]:
main.bghelper()
	/usr/local/go/src/cmd/dist/util.go:152 +0x152
created by main.bginit
	/usr/local/go/src/cmd/dist/util.go:145 +0x5a

goroutine 23 [select]:
main.bghelper()
	/usr/local/go/src/cmd/dist/util.go:152 +0x152
created by main.bginit
	/usr/local/go/src/cmd/dist/util.go:145 +0x5a
```

cc @aclements @bradfitz

**Comment by broady** [comment]
```
windows-amd64: Error: go tool dist install runtime: exit status 1
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive (nil chan)]:
main.install(0xc0820022b0, 0x7)
	c:/go/src/cmd/dist/build.go:504 +0x206
main.cmdinstall()
	c:/go/src/cmd/dist/build.go:1144 +0xec
main.xmain()
	c:/go/src/cmd/dist/main.go:42 +0x1f0
main.main()
	c:/go/src/cmd/dist/util.go:502 +0x596

goroutine 5 [select]:
main.bghelper()
	c:/go/src/cmd/dist/util.go:152 +0x159
created by main.bginit
	c:/go/src/cmd/dist/util.go:145 +0x61

goroutine 6 [select]:
main.bghelper()
	c:/go/src/cmd/dist/util.go:152 +0x159
created by main.bginit
	c:/go/src/cmd/dist/util.go:145 +0x61

goroutine 7 [select]:
main.bghelper()
	c:/go/src/cmd/dist/util.go:152 +0x159
created by main.bginit
	c:/go/src/cmd/dist/util.go:145 +0x61

goroutine 8 [select]:
main.bghelper()
	c:/go/src/cmd/dist/util.go:152 +0x159
created by main.bginit
	c:/go/src/cmd/dist/util.go:145 +0x61
```

```
linux-amd64: Error: go tool dist install runtime: exit status 1
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive (nil chan)]:
main.install(0x7fff663b9d59, 0x7)
	/usr/local/go/src/cmd/dist/build.go:504 +0x205
main.cmdinstall()
	/usr/local/go/src/cmd/dist/build.go:1144 +0xe5
main.xmain()
	/usr/local/go/src/cmd/dist/main.go:42 +0x1e9
main.main()
	/usr/local/go/src/cmd/dist/util.go:502 +0x58a

goroutine 6 [select]:
main.bghelper()
	/usr/local/go/src/cmd/dist/util.go:152 +0x152
created by main.bginit
	/usr/local/go/src/cmd/dist/util.go:145 +0x5a

goroutine 7 [select]:
main.bghelper()
	/usr/local/go/src/cmd/dist/util.go:152 +0x152
created by main.bginit
	/usr/local/go/src/cmd/dist/util.go:145 +0x5a

goroutine 8 [select]:
main.bghelper()
	/usr/local/go/src/cmd/dist/util.go:152 +0x152
created by main.bginit
	/usr/local/go/src/cmd/dist/util.go:145 +0x5a

goroutine 9 [select]:
main.bghelper()
	/usr/local/go/src/cmd/dist/util.go:152 +0x152
created by main.bginit
	/usr/local/go/src/cmd/dist/util.go:145 +0x5a
```

```
reebsd-amd64: Error: go tool dist install runtime: exit status 1
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive (nil chan)]:
main.install(0x7fffffffed44, 0x7)
	/usr/local/go/src/cmd/dist/build.go:504 +0x205
main.cmdinstall()
	/usr/local/go/src/cmd/dist/build.go:1144 +0xe5
main.xmain()
	/usr/local/go/src/cmd/dist/main.go:42 +0x1e9
main.main()
	/usr/local/go/src/cmd/dist/util.go:502 +0x58a

goroutine 6 [select]:
main.bghelper()
	/usr/local/go/src/cmd/dist/util.go:152 +0x152
created by main.bginit
	/usr/local/go/src/cmd/dist/util.go:145 +0x5a

goroutine 7 [select]:
main.bghelper()
	/usr/local/go/src/cmd/dist/util.go:152 +0x152
created by main.bginit
	/usr/local/go/src/cmd/dist/util.go:145 +0x5a

goroutine 8 [select]:
main.bghelper()
	/usr/local/go/src/cmd/dist/util.go:152 +0x152
created by main.bginit
	/usr/local/go/src/cmd/dist/util.go:145 +0x5a

goroutine 9 [select]:
main.bghelper()
	/usr/local/go/src/cmd/dist/util.go:152 +0x152
created by main.bginit
	/usr/local/go/src/cmd/dist/util.go:145 +0x5a
```

**Comment by broady** [comment]
cc @rsc

**Comment by broady** [comment]
@michaelmatloob @ianlancetaylor

**Comment by bradfitz** [comment]
I suspect this is something about an old dist building a new runtime with dependencies (@michaelmatloob's stuff). Oddly some of the release builds succeeded, making me think it's a builder configuration/environment problem. Yet the main builders using the same configs succeed.

**Comment by broady** [comment]
It happens when building the race detector:
`2015/12/17 14:53:20 linux-amd64: Building race detector.`

**Comment by bradfitz** [comment]
Hah, this is due to a old workaround in x/build/cmd/release for old `go install -a` bugs:

```go
                b.logf("Building race detector.")

                // Because on release branches, go install -a std is a NOP,                                                                                                  
                // we have to resort to delete pkg/$GOOS_$GOARCH, install -race,                                                                                             
                // and then reinstall std so that we're not left with a slower,                                                                                              
                // race-enabled cmd/go, etc.                                                                                                                                 
                if err := client.RemoveAll(path.Join(goDir, "pkg", b.OS+"_"+b.Arch)); err != nil {
                        return err
                }
                if err := runGo("tool", "dist", "install", "runtime"); err != nil {
	                return err
                }
                if err := runGo("install", "-race", "std"); err != nil {
                        return err
                }
                if err := runGo("install", "std"); err != nil {
                        return err
                }
```
