### ISSUE TITLE
x/tools/cmd/gorename: using '.' as -from package causes panic

### ISSUE THREAD

**Issue by ericchiang** [golang/go#13866]
Don't know if using a '.' as the -from package is supposed to be legal but I ran into a panic doing so.

```
$ cd $GOPATH/src/foo
$ ls
hello.go
$ cat hello.go
package main

func sayHello() {
}

func main() {
}
$ gorename -from '".".sayHello' -to 'sayGoodbye'
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4a6812]

goroutine 1 [running]:
golang.org/x/tools/refactor/rename.findObjects(0x0, 0xc8200aea10, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/eric/src/golang.org/x/tools/refactor/rename/spec.go:419 +0x352
golang.org/x/tools/refactor/rename.findFromObjects(0xc82001a800, 0xc8200aea10, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/eric/src/golang.org/x/tools/refactor/rename/spec.go:292 +0x1ed
golang.org/x/tools/refactor/rename.Main(0x88bd00, 0x0, 0x0, 0x7ffeacf52f39, 0xc, 0x7ffeacf52f4a, 0xa, 0x0, 0x0)
	/home/eric/src/golang.org/x/tools/refactor/rename/rename.go:253 +0x625
main.main()
	/home/eric/src/golang.org/x/tools/cmd/gorename/main.go:49 +0x337
```

This is using the latest checkout of golang/tools.

**Comment by griesemer** [comment]
I think the command shouldn't crash and I would consider this a bug.

**Comment by ericchiang** [comment]
It looks like the loader is loading the package just fine, but findFromObjects does map lookup using the package name "." [here](https://github.com/golang/tools/blob/dd6e749ee1461e4067ce1fc2e19d99c6c37d6ba4/refactor/rename/spec.go#L290) producing a nil *loader.PackageInfo

**Comment by alandonovan** [comment]
Fixed by https://go-review.googlesource.com/#/c/18453
