### ISSUE TITLE
x/mobile/bind: testJavaRefKeep flaky

### ISSUE THREAD

**Issue by crawshaw** [golang/go#13909]
Nexus 7, Android 5.1.1. TestJavaSeqTest fails 3 out of 20 runs with:

```
I/TestRunner(12611): failed: testJavaRefKeep(go.SeqTest)
I/TestRunner(12611): ----- begin exception -----
I/TestRunner(12611): 
I/TestRunner(12611): junit.framework.AssertionFailedError: want obj not to be kept by Go
I/TestRunner(12611): 	at junit.framework.Assert.fail(Assert.java:50)
I/TestRunner(12611): 	at junit.framework.Assert.assertTrue(Assert.java:20)
I/TestRunner(12611): 	at go.SeqTest.testJavaRefKeep(SeqTest.java:309)
I/TestRunner(12611): 	at java.lang.reflect.Method.invoke(Native Method)
I/TestRunner(12611): 	at java.lang.reflect.Method.invoke(Method.java:372)
I/TestRunner(12611): 	at junit.framework.TestCase.runTest(TestCase.java:168)
I/TestRunner(12611): 	at junit.framework.TestCase.runBare(TestCase.java:134)
I/TestRunner(12611): 	at junit.framework.TestResult$1.protect(TestResult.java:115)
I/TestRunner(12611): 	at junit.framework.TestResult.runProtected(TestResult.java:133)
I/TestRunner(12611): 	at junit.framework.TestResult.run(TestResult.java:118)
I/TestRunner(12611): 	at junit.framework.TestCase.run(TestCase.java:124)
I/TestRunner(12611): 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
I/TestRunner(12611): 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
I/TestRunner(12611): 	at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
I/TestRunner(12611): 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1853)
I/TestRunner(12611): ----- end exception -----
```

**Comment by crawshaw** [comment]
I believe this was fixed by recent changes by Elias.
