### ISSUE TITLE
net/http: send on closed channel

### ISSUE THREAD

**Issue by karmeye** [golang/go#13933]
Using latest code in the master branch (771da53)

Got this when connecting to db (with race detector on)

```go
2016/01/13 09:46:20 http2: panic serving 127.0.0.1:54807: send on closed channel
goroutine 2329 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc825287f4f, 0xc820188280, 0xc8201430d0)
	/usr/local/go/src/net/http/h2_bundle.go:3737 +0xde
database/sql.(*DB).putConnDBLocked(0xc8200ca210, 0xc82005c230, 0x0, 0x0, 0xc8265422a0)
	/usr/local/go/src/database/sql/sql.go:940 +0x30d
database/sql.(*DB).putConn(0xc8200ca210, 0xc82005c230, 0x0, 0x0)
	/usr/local/go/src/database/sql/sql.go:906 +0x2f0
database/sql.(*DB).prepare(0xc8200ca210, 0x658a40, 0x46, 0x1, 0x1c4, 0x0, 0x0)
	/usr/local/go/src/database/sql/sql.go:1000 +0x41b
database/sql.(*DB).Prepare(0xc8200ca210, 0x658a40, 0x46, 0x11400, 0x0, 0x0)
	/usr/local/go/src/database/sql/sql.go:964 +0x87
```

Related to https://github.com/golang/go/issues/13924 ?

**Comment by bradfitz** [comment]
Yes, duplicate.
