### ISSUE TITLE
net/http: TestServerValidatesHostHeader timeout

### ISSUE THREAD

**Issue by aclements** [golang/go#13950]
TestServerValidatesHostHeader is occasionally timing out on the `<-conn.closec`. Here's a recent example from the builders: [2016-01-12T02:00:48-352e287/linux-amd64-race](https://build.golang.org/log/8c382d35fa67de8235ccb31aed0ebe92fbe482ed).

I've been able to reproduce this a few times myself by running `go test -short std` in a loop on the linux-amd64-nocgo builder. In case it's relevant, here's the full GOTRACEBACK=crash trace from a timeout:

```
SIGQUIT: quit
PC=0x45f8f1 m=0

goroutine 0 [idle]:
runtime.futex(0xbe18c8, 0x0, 0x0, 0x0, 0x0, 0xbe0e70, 0x0, 0x0, 0x40e594, 0xbe18c8, ...)
        /tmp/workdir/go/src/runtime/sys_linux_amd64.s:302 +0x21 fp=0x7fffeaaf42d8 sp=0x7fffeaaf42d0
runtime.futexsleep(0xbe18c8, 0x0, 0xffffffffffffffff)
        /tmp/workdir/go/src/runtime/os1_linux.go:40 +0x53 fp=0x7fffeaaf4320 sp=0x7fffeaaf42d8
runtime.notesleep(0xbe18c8)
        /tmp/workdir/go/src/runtime/lock_futex.go:145 +0xa4 fp=0x7fffeaaf4348 sp=0x7fffeaaf4320
runtime.stopm()
        /tmp/workdir/go/src/runtime/proc.go:1531 +0x10b fp=0x7fffeaaf4368 sp=0x7fffeaaf4348
runtime.findrunnable(0xc820015500, 0x0)
        /tmp/workdir/go/src/runtime/proc.go:1957 +0x73a fp=0x7fffeaaf43e8 sp=0x7fffeaaf4368
runtime.schedule()
        /tmp/workdir/go/src/runtime/proc.go:2056 +0x24f fp=0x7fffeaaf4420 sp=0x7fffeaaf43e8
runtime.park_m(0xc820000a80)
        /tmp/workdir/go/src/runtime/proc.go:2121 +0x18b fp=0x7fffeaaf4448 sp=0x7fffeaaf4420
runtime.mcall(0x7fffeaaf4470)
        /tmp/workdir/go/src/runtime/asm_amd64.s:233 +0x5b fp=0x7fffeaaf4458 sp=0x7fffeaaf4448

goroutine 1 [chan receive, 9 minutes]:
runtime.gopark(0xa467e8, 0xc8203c9df8, 0x96be80, 0xc, 0x17, 0x3)
        /tmp/workdir/go/src/runtime/proc.go:262 +0x163 fp=0xc82056cb58 sp=0xc82056cb30  
runtime.goparkunlock(0xc8203c9df8, 0x96be80, 0xc, 0x7ff0638b3017, 0x3)
        /tmp/workdir/go/src/runtime/proc.go:268 +0x54 fp=0xc82056cb90 sp=0xc82056cb58   
runtime.chanrecv(0x816220, 0xc8203c9da0, 0xc82056cd70, 0xc82018dc01, 0x470000) 
        /tmp/workdir/go/src/runtime/chan.go:470 +0x49f fp=0xc82056cc18 sp=0xc82056cb90  
runtime.chanrecv1(0x816220, 0xc8203c9da0, 0xc82056cd70)
        /tmp/workdir/go/src/runtime/chan.go:355 +0x2b fp=0xc82056cc48 sp=0xc82056cc18   
testing.RunTests(0xa44ee8, 0xbdd740, 0x145, 0x145, 0x601)
        /tmp/workdir/go/src/testing/testing.go:583 +0x8d2 fp=0xc82056cdc8 sp=0xc82056cc48
testing.(*M).Run(0xc82056cf08, 0x20)
        /tmp/workdir/go/src/testing/testing.go:515 +0x81 fp=0xc82056ce50 sp=0xc82056cdc8
net/http_test.TestMain(0xc82056cf08)
        /tmp/workdir/go/src/net/http/main_test.go:22 +0x21 fp=0xc82056ce70 sp=0x
c82056ce50
main.main()
        net/http/_test/_testmain.go:746 +0x114 fp=0xc82056cf60 sp=0xc82056ce70
runtime.main()
        /tmp/workdir/go/src/runtime/proc.go:188 +0x2b0 fp=0xc82056cfb0 sp=0xc82056cf60
runtime.goexit()
        /tmp/workdir/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82056cfb8 sp=0xc82056cfb0

goroutine 2 [force gc (idle), 3 minutes]:
runtime.gopark(0xa467e8, 0xbe0750, 0x96db90, 0xf, 0x100000000000014, 0x1)
        /tmp/workdir/go/src/runtime/proc.go:262 +0x163 fp=0xc82001c758 sp=0xc82001c730
runtime.goparkunlock(0xbe0750, 0x96db90, 0xf, 0xc820000114, 0x1)
        /tmp/workdir/go/src/runtime/proc.go:268 +0x54 fp=0xc82001c790 sp=0xc82001c758
runtime.forcegchelper()
        /tmp/workdir/go/src/runtime/proc.go:229 +0xb8 fp=0xc82001c7c0 sp=0xc82001c790
runtime.goexit()
        /tmp/workdir/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82001c7c8 sp=0xc82001c7c0
created by runtime.init.4
        /tmp/workdir/go/src/runtime/proc.go:218 +0x2b

goroutine 3 [GC sweep wait]:
runtime.gopark(0xa467e8, 0xbe0900, 0x966d40, 0xd, 0x452614, 0x1)
        /tmp/workdir/go/src/runtime/proc.go:262 +0x163 fp=0xc82001cf48 sp=0xc82001cf20
runtime.goparkunlock(0xbe0900, 0x966d40, 0xd, 0x14, 0x1)
        /tmp/workdir/go/src/runtime/proc.go:268 +0x54 fp=0xc82001cf80 sp=0xc82001cf48
runtime.bgsweep(0xc820044000)
        /tmp/workdir/go/src/runtime/mgcsweep.go:79 +0x14d fp=0xc82001cfb8 sp=0xc82001cf80
runtime.goexit()
        /tmp/workdir/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82001cfc0 sp=0xc82001cfb8
created by runtime.gcenable
        /tmp/workdir/go/src/runtime/mgc.go:191 +0x53

goroutine 4 [finalizer wait, 9 minutes]:
runtime.gopark(0xa467e8, 0xbfdcd8, 0x96d640, 0xe, 0x100000014, 0x1)
        /tmp/workdir/go/src/runtime/proc.go:262 +0x163 fp=0xc82001d718 sp=0xc82001d6f0
runtime.goparkunlock(0xbfdcd8, 0x96d640, 0xe, 0x2000000014, 0x1)
        /tmp/workdir/go/src/runtime/proc.go:268 +0x54 fp=0xc82001d750 sp=0xc82001d718
runtime.runfinq()
        /tmp/workdir/go/src/runtime/mfinal.go:158 +0xaa fp=0xc82001d7c0 sp=0xc82001d750
runtime.goexit()
        /tmp/workdir/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82001d7c8 sp=0xc82001d7c0
created by runtime.createfing
        /tmp/workdir/go/src/runtime/mfinal.go:139 +0x60

goroutine 1271 [chan receive, 9 minutes]:
runtime.gopark(0xa467e8, 0xc82004e298, 0x96be80, 0xc, 0x17, 0x3)
        /tmp/workdir/go/src/runtime/proc.go:262 +0x163 fp=0xc820038a90 sp=0xc820038a68
runtime.goparkunlock(0xc82004e298, 0x96be80, 0xc, 0xa43417, 0x3)
        /tmp/workdir/go/src/runtime/proc.go:268 +0x54 fp=0xc820038ac8 sp=0xc820038a90
runtime.chanrecv(0x8160a0, 0xc82004e240, 0x0, 0x477001, 0xbe0000)
        /tmp/workdir/go/src/runtime/chan.go:470 +0x49f fp=0xc820038b50 sp=0xc820038ac8
runtime.chanrecv1(0x8160a0, 0xc82004e240, 0x0)
        /tmp/workdir/go/src/runtime/chan.go:355 +0x2b fp=0xc820038b80 sp=0xc820038b50
testing.(*T).Parallel(0xc820463cb0)
        /tmp/workdir/go/src/testing/testing.go:441 +0x12b fp=0xc820038bf0 sp=0xc820038b80
net/http_test.setParallel(0xc820463cb0)
        /tmp/workdir/go/src/net/http/main_test.go:90 +0x31 fp=0xc820038c00 sp=0xc820038bf0
net/http_test.TestServerTimeouts(0xc820463cb0)
        /tmp/workdir/go/src/net/http/serve_test.go:459 +0x83 fp=0xc820038f68 sp=0xc820038c00
testing.tRunner(0xc820463cb0, 0xbde700)
        /tmp/workdir/go/src/testing/testing.go:473 +0x98 fp=0xc820038fa0 sp=0xc820038f68
runtime.goexit()
        /tmp/workdir/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820038fa8 sp=0xc820038fa0
created by testing.RunTests
        /tmp/workdir/go/src/testing/testing.go:582 +0x892

goroutine 36 [GC worker (idle), 1 minutes]:
runtime.gopark(0xa46660, 0xc820022400, 0x9a9bd0, 0x10, 0xc83ab93914, 0x0)
        /tmp/workdir/go/src/runtime/proc.go:262 +0x163 fp=0xc82001df48 sp=0xc82001df20
runtime.gcBgMarkWorker(0xc820014000)
        /tmp/workdir/go/src/runtime/mgc.go:1378 +0x12c fp=0xc82001dfb8 sp=0xc82001df48
runtime.goexit()
        /tmp/workdir/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82001dfc0 sp=0xc82001dfb8
created by runtime.gcBgMarkStartWorkers
        /tmp/workdir/go/src/runtime/mgc.go:1325 +0x93

goroutine 37 [GC worker (idle), 1 minutes]:
runtime.gopark(0xa46660, 0xbe17c0, 0x9a9bd0, 0x10, 0x14, 0x0)
        /tmp/workdir/go/src/runtime/proc.go:262 +0x163 fp=0xc82001e748 sp=0xc82001e720
runtime.gcBgMarkWorker(0xc820015500)
        /tmp/workdir/go/src/runtime/mgc.go:1378 +0x12c fp=0xc82001e7b8 sp=0xc82001e748
runtime.goexit()
        /tmp/workdir/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82001e7c0 sp=0xc82001e7b8
created by runtime.gcBgMarkStartWorkers
        /tmp/workdir/go/src/runtime/mgc.go:1325 +0x93

goroutine 60 [timer goroutine (idle), 9 minutes]:
runtime.gopark(0xa467e8, 0xbe09a0, 0x9bc1d0, 0x16, 0x11d158f14, 0x1)
        /tmp/workdir/go/src/runtime/proc.go:262 +0x163 fp=0xc82001a700 sp=0xc82001a6d8
runtime.goparkunlock(0xbe09a0, 0x9bc1d0, 0x16, 0x14, 0x1)
        /tmp/workdir/go/src/runtime/proc.go:268 +0x54 fp=0xc82001a738 sp=0xc82001a700
runtime.timerproc()
        /tmp/workdir/go/src/runtime/time.go:202 +0x123 fp=0xc82001a7c0 sp=0xc82001a738
runtime.goexit()
        /tmp/workdir/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82001a7c8 sp=0xc82001a7c0
created by runtime.addtimerLocked
        /tmp/workdir/go/src/runtime/time.go:116 +0x11f

goroutine 3796 [chan receive, 9 minutes]:
runtime.gopark(0xa467e8, 0xc820442d78, 0x96be80, 0xc, 0x17, 0x3)
        /tmp/workdir/go/src/runtime/proc.go:262 +0x163 fp=0xc8202a5870 sp=0xc8202a5848
runtime.goparkunlock(0xc820442d78, 0x96be80, 0xc, 0x7ff0638b3017, 0x3)
        /tmp/workdir/go/src/runtime/proc.go:268 +0x54 fp=0xc8202a58a8 sp=0xc8202a5870
runtime.chanrecv(0x8160a0, 0xc820442d20, 0x0, 0xc8202a5901, 0x590000)
        /tmp/workdir/go/src/runtime/chan.go:470 +0x49f fp=0xc8202a5930 sp=0xc8202a58a8
runtime.chanrecv1(0x8160a0, 0xc820442d20, 0x0)
        /tmp/workdir/go/src/runtime/chan.go:355 +0x2b fp=0xc8202a5960 sp=0xc8202a5930
net/http_test.TestServerValidatesHostHeader(0xc8200714d0)
        /tmp/workdir/go/src/net/http/serve_test.go:3835 +0x3fc fp=0xc8202a5f58 sp=0xc8202a5960
testing.tRunner(0xc8200714d0, 0xbdef58)
        /tmp/workdir/go/src/testing/testing.go:473 +0x98 fp=0xc8202a5f90 sp=0xc8202a5f58
runtime.goexit()
        /tmp/workdir/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8202a5f98 sp=0xc8202a5f90
created by testing.RunTests
        /tmp/workdir/go/src/testing/testing.go:582 +0x892

goroutine 1384 [chan receive, 9 minutes]:
runtime.gopark(0xa467e8, 0xc82004e298, 0x96be80, 0xc, 0x17, 0x3)
        /tmp/workdir/go/src/runtime/proc.go:262 +0x163 fp=0xc8203f1bd0 sp=0xc8203f1ba8
runtime.goparkunlock(0xc82004e298, 0x96be80, 0xc, 0xa43417, 0x3)
        /tmp/workdir/go/src/runtime/proc.go:268 +0x54 fp=0xc8203f1c08 sp=0xc8203f1bd0
runtime.chanrecv(0x8160a0, 0xc82004e240, 0x0, 0x477001, 0xbe0000)
        /tmp/workdir/go/src/runtime/chan.go:470 +0x49f fp=0xc8203f1c90 sp=0xc8203f1c08
runtime.chanrecv1(0x8160a0, 0xc82004e240, 0x0)
        /tmp/workdir/go/src/runtime/chan.go:355 +0x2b fp=0xc8203f1cc0 sp=0xc8203f1c90
testing.(*T).Parallel(0xc8201dc900)
        /tmp/workdir/go/src/testing/testing.go:441 +0x12b fp=0xc8203f1d30 sp=0xc8203f1cc0
net/http_test.setParallel(0xc8201dc900)
        /tmp/workdir/go/src/net/http/main_test.go:90 +0x31 fp=0xc8203f1d40 sp=0xc8203f1d30
net/http_test.TestTLSHandshakeTimeout(0xc8201dc900)
        /tmp/workdir/go/src/net/http/serve_test.go:943 +0x46 fp=0xc8203f1f78 sp=0xc8203f1d40
testing.tRunner(0xc8201dc900, 0xbde838)
        /tmp/workdir/go/src/testing/testing.go:473 +0x98 fp=0xc8203f1fb0 sp=0xc8203f1f78
runtime.goexit()
        /tmp/workdir/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8203f1fb8 sp=0xc8203f1fb0
created by testing.RunTests
        /tmp/workdir/go/src/testing/testing.go:582 +0x892

goroutine 1385 [chan receive, 9 minutes]:
runtime.gopark(0xa467e8, 0xc8203c9cd8, 0x96be80, 0xc, 0x17, 0x3)
        /tmp/workdir/go/src/runtime/proc.go:262 +0x163 fp=0xc8203f1690 sp=0xc8203f1668
runtime.goparkunlock(0xc8203c9cd8, 0x96be80, 0xc, 0x17, 0x3)
        /tmp/workdir/go/src/runtime/proc.go:268 +0x54 fp=0xc8203f16c8 sp=0xc8203f1690
runtime.chanrecv(0x816220, 0xc8203c9c80, 0xc8203f1798, 0xbfdd01, 0x0)
        /tmp/workdir/go/src/runtime/chan.go:470 +0x49f fp=0xc8203f1750 sp=0xc8203f16c8
runtime.chanrecv1(0x816220, 0xc8203c9c80, 0xc8203f1798)
        /tmp/workdir/go/src/runtime/chan.go:355 +0x2b fp=0xc8203f1780 sp=0xc8203f1750
testing.RunTests.func1(0xc82004e1e0, 0xc8201dc900)
        /tmp/workdir/go/src/testing/testing.go:586 +0x47 fp=0xc8203f17b0 sp=0xc8203f1780
runtime.goexit()
        /tmp/workdir/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8203f17b8 sp=0xc8203f17b0
created by testing.RunTests
        /tmp/workdir/go/src/testing/testing.go:587 +0x933

goroutine 1272 [chan receive, 9 minutes]:
runtime.gopark(0xa467e8, 0xc8203d5378, 0x96be80, 0xc, 0x17, 0x3)
        /tmp/workdir/go/src/runtime/proc.go:262 +0x163 fp=0xc820018690 sp=0xc820018668
runtime.goparkunlock(0xc8203d5378, 0x96be80, 0xc, 0x17, 0x3)
        /tmp/workdir/go/src/runtime/proc.go:268 +0x54 fp=0xc8200186c8 sp=0xc820018690
runtime.chanrecv(0x816220, 0xc8203d5320, 0xc820018798, 0x1, 0x470000)
        /tmp/workdir/go/src/runtime/chan.go:470 +0x49f fp=0xc820018750 sp=0xc8200186c8
runtime.chanrecv1(0x816220, 0xc8203d5320, 0xc820018798)
        /tmp/workdir/go/src/runtime/chan.go:355 +0x2b fp=0xc820018780 sp=0xc820018750
testing.RunTests.func1(0xc82004e1e0, 0xc820463cb0)
        /tmp/workdir/go/src/testing/testing.go:586 +0x47 fp=0xc8200187b0 sp=0xc820018780
runtime.goexit()
        /tmp/workdir/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200187b8 sp=0xc8200187b0
created by testing.RunTests
        /tmp/workdir/go/src/testing/testing.go:587 +0x933
              
rax    0xca
rbx    0x0
rcx    0xffffffffffffffff
rdx    0x0
rdi    0xbe18c8
rsi    0x0
rbp    0x1
rsp    0x7fffeaaf42d0
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x800
r13    0x180
r14    0x2
r15    0x8
rip    0x45f8f1
rflags 0x286
cs     0x33
fs     0x0
gs     0x0

-----

SIGQUIT: quit
PC=0x45f8f3 m=1

goroutine 0 [idle]:
runtime.futex(0xbe0f30, 0x0, 0xc820031eb0, 0x0, 0x0, 0x45f71c, 0x3c, 0x0, 0x40e6fb, 0xbe0f30, ...)
        /tmp/workdir/go/src/runtime/sys_linux_amd64.s:303 +0x23 fp=0xc820031e80 sp=0xc820031e78
runtime.futexsleep(0xbe0f30, 0x0, 0xdf8475800)
        /tmp/workdir/go/src/runtime/os1_linux.go:57 +0xf0 fp=0xc820031ec8 sp=0xc820031e80
runtime.notetsleep_internal(0xbe0f30, 0xdf8475800, 0xc820000480)
        /tmp/workdir/go/src/runtime/lock_futex.go:174 +0x12b fp=0xc820031ef8 sp=0xc820031ec8
runtime.notetsleep(0xbe0f30, 0xdf8475800, 0x9fe047770f3)
        /tmp/workdir/go/src/runtime/lock_futex.go:194 +0x6b fp=0xc820031f18 sp=0xc820031ef8
runtime.sysmon()
        /tmp/workdir/go/src/runtime/proc.go:3459 +0x487 fp=0xc820031f90 sp=0xc820031f18
runtime.mstart1()
        /tmp/workdir/go/src/runtime/proc.go:1095 +0xec fp=0xc820031fb0 sp=0xc820031f90
runtime.mstart()
        /tmp/workdir/go/src/runtime/proc.go:1065 +0x72 fp=0xc820031fc0 sp=0xc820031fb0
rax    0xfffffffffffffffc
rbx    0xc820031eb0
rcx    0xffffffffffffffff
rdx    0x0
rdi    0xbe0f30
rsi    0x0
rbp    0x0
rsp    0xc820031e78
r8     0x0
r9     0x0
r10    0xc820031eb0
r11    0x246
r12    0x430f90
r13    0xa43624
r14    0x0
r15    0x8
rip    0x45f8f3
rflags 0x246
cs     0x33
fs     0x0
gs     0x0

-----

SIGQUIT: quit
PC=0x45f8f1 m=2
              
goroutine 0 [idle]:
runtime.futex(0xc820022508, 0x0, 0x0, 0x0, 0x0, 0xbe0e70, 0x0, 0x0, 0x40e594, 0xc820022508, ...)
        /tmp/workdir/go/src/runtime/sys_linux_amd64.s:302 +0x21 fp=0xc82002de18 sp=0xc82002de10
runtime.futexsleep(0xc820022508, 0x0, 0xffffffffffffffff)
        /tmp/workdir/go/src/runtime/os1_linux.go:40 +0x53 fp=0xc82002de60 sp=0xc82002de18
runtime.notesleep(0xc820022508)
        /tmp/workdir/go/src/runtime/lock_futex.go:145 +0xa4 fp=0xc82002de88 sp=0xc82002de60
runtime.stopm()
        /tmp/workdir/go/src/runtime/proc.go:1531 +0x10b fp=0xc82002dea8 sp=0xc82002de88
runtime.findrunnable(0xc820014000, 0x0)
        /tmp/workdir/go/src/runtime/proc.go:1957 +0x73a fp=0xc82002df28 sp=0xc82002dea8
runtime.schedule()
        /tmp/workdir/go/src/runtime/proc.go:2056 +0x24f fp=0xc82002df60 sp=0xc82002df28
runtime.park_m(0xc820001b00)
        /tmp/workdir/go/src/runtime/proc.go:2121 +0x18b fp=0xc82002df88 sp=0xc82002df60
runtime.mcall(0x0)
        /tmp/workdir/go/src/runtime/asm_amd64.s:233 +0x5b fp=0xc82002df98 sp=0xc82002df88
rax    0xca
rbx    0x0
rcx    0xffffffffffffffff
rdx    0x0
rdi    0xc820022508
rsi    0x0
rbp    0x1
rsp    0xc82002de10
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x1
r13    0x180
r14    0x3
r15    0x8
rip    0x45f8f1
rflags 0x286
cs     0x33
fs     0x0
gs     0x0

-----

SIGQUIT: quit
PC=0x45f8f1 m=3

goroutine 0 [idle]:
runtime.futex(0xc820022908, 0x0, 0x0, 0x0, 0x0, 0xbe0e70, 0x0, 0x0, 0x40e594, 0xc820022908, ...)
        /tmp/workdir/go/src/runtime/sys_linux_amd64.s:302 +0x21 fp=0xc82002fe10 sp=0xc82002fe08
runtime.futexsleep(0xc820022908, 0x0, 0xffffffffffffffff)
        /tmp/workdir/go/src/runtime/os1_linux.go:40 +0x53 fp=0xc82002fe58 sp=0xc82002fe10
runtime.notesleep(0xc820022908)
        /tmp/workdir/go/src/runtime/lock_futex.go:145 +0xa4 fp=0xc82002fe80 sp=0xc82002fe58
runtime.stopm()
        /tmp/workdir/go/src/runtime/proc.go:1531 +0x10b fp=0xc82002fea0 sp=0xc82002fe80
runtime.findrunnable(0xc820015500, 0x0)
        /tmp/workdir/go/src/runtime/proc.go:1957 +0x73a fp=0xc82002ff20 sp=0xc82002fea0
runtime.schedule()
        /tmp/workdir/go/src/runtime/proc.go:2056 +0x24f fp=0xc82002ff58 sp=0xc82002ff20
runtime.goexit0(0xc8200f7b00)
        /tmp/workdir/go/src/runtime/proc.go:2191 +0x1f9 fp=0xc82002ff88 sp=0xc82002ff58
runtime.mcall(0x0)
        /tmp/workdir/go/src/runtime/asm_amd64.s:233 +0x5b fp=0xc82002ff98 sp=0xc82002ff88
rax    0xca
rbx    0x0
rcx    0xffffffffffffffff
rdx    0x0
rdi    0xc820022908
rsi    0x0
rbp    0x1
rsp    0xc82002fe08
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0xbb7010
r13    0xa4331c
r14    0x1
r15    0x8
rip    0x45f8f1
rflags 0x286
cs     0x33
fs     0x0
gs     0x0

-----

SIGQUIT: quit
PC=0x45fa79 m=4

goroutine 0 [idle]:
runtime.epollwait(0x5, 0xc820189898, 0xffffffff00000080, 0xffffffff00000000, 0xffffffff, 0x1ffffffff, 0x0, 0x0, 0x0, 0x0, ...)
        /tmp/workdir/go/src/runtime/sys_linux_amd64.s:440 +0x19 fp=0xc820189860 sp=0xc820189858
runtime.netpoll(0xbe0e01, 0x0)
        /tmp/workdir/go/src/runtime/netpoll_epoll.go:67 +0x94 fp=0xc820189ea0 sp=0xc820189860
runtime.findrunnable(0xc820015500, 0x0)
        /tmp/workdir/go/src/runtime/proc.go:1939 +0x62d fp=0xc820189f20 sp=0xc820189ea0
runtime.schedule()
        /tmp/workdir/go/src/runtime/proc.go:2056 +0x24f fp=0xc820189f58 sp=0xc820189f20
runtime.goexit0(0xc8200f7b00)
        /tmp/workdir/go/src/runtime/proc.go:2191 +0x1f9 fp=0xc820189f88 sp=0xc820189f58
runtime.mcall(0x0)
        /tmp/workdir/go/src/runtime/asm_amd64.s:233 +0x5b fp=0xc820189f98 sp=0xc820189f88
rax    0xfffffffffffffffc
rbx    0xffffffff
rcx    0xffffffffffffffff
rdx    0x80
rdi    0x5
rsi    0xc820189898
rbp    0xc820023400
rsp    0xc820189858
r8     0xc820023400
r9     0xc820014000
r10    0xffffffff
r11    0x246
r12    0x813cc421
r13    0xa
r14    0x1
r15    0x8
rip    0x45fa79
rflags 0x246
cs     0x33
fs     0x0
gs     0x0

-----

SIGQUIT: quit
PC=0x45f8f1 m=5

goroutine 0 [idle]:
runtime.futex(0xc8204bb908, 0x0, 0x0, 0x0, 0x0, 0xbe0e70, 0x0, 0x0, 0x40e594, 0xc8204bb908, ...)
        /tmp/workdir/go/src/runtime/sys_linux_amd64.s:302 +0x21 fp=0xc820033ed0 sp=0xc820033ec8
runtime.futexsleep(0xc8204bb908, 0x100000000, 0xffffffffffffffff)
        /tmp/workdir/go/src/runtime/os1_linux.go:40 +0x53 fp=0xc820033f18 sp=0xc820033ed0
runtime.notesleep(0xc8204bb908)
        /tmp/workdir/go/src/runtime/lock_futex.go:145 +0xa4 fp=0xc820033f40 sp=0xc820033f18
runtime.stopm()
        /tmp/workdir/go/src/runtime/proc.go:1531 +0x10b fp=0xc820033f60 sp=0xc820033f40
runtime.exitsyscall0(0xc8200f6900)
        /tmp/workdir/go/src/runtime/proc.go:2568 +0x176 fp=0xc820033f88 sp=0xc820033f60
runtime.mcall(0x0)
        /tmp/workdir/go/src/runtime/asm_amd64.s:233 +0x5b fp=0xc820033f98 sp=0xc820033f88
rax    0xca
rbx    0x0
rcx    0xffffffffffffffff
rdx    0x0
rdi    0xc8204bb908
rsi    0x0
rbp    0x1
rsp    0xc820033ec8
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x6
r13    0xa43346
r14    0x3
r15    0x8
rip    0x45f8f1
rflags 0x286
cs     0x33
fs     0x0
gs     0x0

-----

SIGQUIT: quit
PC=0x45f8f1 m=6

goroutine 0 [idle]:
runtime.futex(0xc820023d08, 0x0, 0x0, 0x0, 0x0, 0xbe0e70, 0x0, 0x0, 0x40e594, 0xc820023d08, ...)
        /tmp/workdir/go/src/runtime/sys_linux_amd64.s:302 +0x21 fp=0xc82018fe68 sp=0xc82018fe60
runtime.futexsleep(0xc820023d08, 0xc800000000, 0xffffffffffffffff)
        /tmp/workdir/go/src/runtime/os1_linux.go:40 +0x53 fp=0xc82018feb0 sp=0xc82018fe68
runtime.notesleep(0xc820023d08)
        /tmp/workdir/go/src/runtime/lock_futex.go:145 +0xa4 fp=0xc82018fed8 sp=0xc82018feb0
runtime.stopm()
        /tmp/workdir/go/src/runtime/proc.go:1531 +0x10b fp=0xc82018fef8 sp=0xc82018fed8
runtime.gcstopm()
        /tmp/workdir/go/src/runtime/proc.go:1727 +0x128 fp=0xc82018ff28 sp=0xc82018fef8
runtime.schedule()
        /tmp/workdir/go/src/runtime/proc.go:2020 +0x9c fp=0xc82018ff60 sp=0xc82018ff28
runtime.park_m(0xc820001b00)
        /tmp/workdir/go/src/runtime/proc.go:2121 +0x18b fp=0xc82018ff88 sp=0xc82018ff60
runtime.mcall(0xc8200ee600)
        /tmp/workdir/go/src/runtime/asm_amd64.s:233 +0x5b fp=0xc82018ff98 sp=0xc82018ff88
rax    0xca
rbx    0x0
rcx    0xffffffffffffffff
rdx    0x0
rdi    0xc820023d08
rsi    0x0
rbp    0x1
rsp    0xc82018fe60
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x1e
r13    0xa434e8
r14    0x2
r15    0x8
rip    0x45f8f1
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (10m0s).
FAIL    net/http        600.006s
```

**Comment by aclements** [comment]
```
$ findflakes -grep TestServerValidatesHostHeader
First observed d6a203e 21 Dec 20:21 2015 (184 commits ago)
Last observed  352e287 12 Jan 02:00 2016 (13 commits ago)
28% chance failure is still happening
9.4% failure probability (17 of 172 commits)
Likely culprits:
    9% d6a203e cmd/compile: const name and label name may match
    8% 97f854c net: make use of IPv4 for parsing routing information on windows
    8% 2cf5f04 net: adjust TestInterfaceHardwareAddrWithGetmac
    7% 471b6ec api: fix typo in README
    6% fbdfa99 runtime: for c-archive/c-shared, don't install unnecessary signal handlers
    6% 32cf985 doc: change go1.6 http heading
    5% f40c05e runtime: write sigsetstack for Darwin, fix sigaction arg
    5% e5ef5d4 doc: add mention of debug.SetTraceback
    4% 57337da testing: use debug.SetTraceback("all") to show all goroutines at test timeout
    4% bb0567b runtime/debug: add SetTraceback
No known past failures
```

`$ greplogs -dashboard -md -l -e TestServerValidatesHostHeader`
[2015-12-21T20:21:28-d6a203e/freebsd-386-gce101](https://build.golang.org/log/3640587c572ab0b339a369b4904a57355ecc8db2)
[2015-12-22T03:38:51-f80f6e4/linux-arm64-linaro](https://build.golang.org/log/95c816bbeebae1de216b4ffa69656d1b9d2d4e0a)
[2015-12-28T01:12:24-c7c7c70/linux-arm64-canonical](https://build.golang.org/log/2c0ca5bee265269d650ebd50be3d387932ca0ca5)
[2015-12-28T01:12:24-c7c7c70/linux-mips64-minux](https://build.golang.org/log/58ccdbe826fb72f38a1b107547abedf77fd0e0c0)
[2015-12-29T16:26:50-b6473ff/linux-arm64-linaro](https://build.golang.org/log/a786a2dc0f86e848264617d907c892462a9526bd)
[2016-01-01T05:00:12-ca9876d/linux-arm64-linaro](https://build.golang.org/log/5c751b9d11d03e3477602b5152b04ef2d70628a5)
[2016-01-03T20:52:07-e2093cd/linux-mips64-minux](https://build.golang.org/log/4841bb0ef8239b10bea696353fc31f7e5ddc0413)
[2016-01-04T20:10:17-7f4443d/android-arm-sdk19](https://build.golang.org/log/33ac0d3c1d32b6421a6e564ae27cc50ba6151711)
[2016-01-05T01:21:26-b80ea53/linux-ppc64le-canonical](https://build.golang.org/log/6d52229974c3f8666370af9f4f9cceb6c535e57f)
[2016-01-06T06:08:34-91f997b/windows-amd64-gce](https://build.golang.org/log/7da59c68296882f38b0a6312de07317fa9030cab)
[2016-01-06T14:25:39-e24b244/nacl-arm-cheney](https://build.golang.org/log/3b817d5021c8edbbf1473d15710e628c8f082e7c)
[2016-01-06T17:39:43-91ba9f4/linux-arm64-linaro](https://build.golang.org/log/dfefcea41d1715f50c7293a2037cf2a3020d8f04)
[2016-01-06T23:11:42-a7cad52/linux-arm64-linaro](https://build.golang.org/log/0a196872d888098eee221235f1d5310d384dc312)
[2016-01-07T23:06:17-40a26c9/linux-ppc64le-canonical](https://build.golang.org/log/921c2ba12e30d9fc558351b197c01670f252ec60)
[2016-01-08T15:34:03-81adfa5/linux-ppc64le-canonical](https://build.golang.org/log/d46eb8ca5cde20917ad5cf6b43b07c66a48fffd7)
[2016-01-08T19:40:00-a62a62d/linux-arm64-linaro](https://build.golang.org/log/d468ef13d995afca0cd8fc27fffe117b5d53479e)
[2016-01-10T06:18:22-30919fe/linux-arm64-canonical](https://build.golang.org/log/d020b32478f6e02a737471410e812090e0fd270f)
[2016-01-12T02:00:48-352e287/linux-amd64-race](https://build.golang.org/log/8c382d35fa67de8235ccb31aed0ebe92fbe482ed)
