### ISSUE TITLE
runtime test fails on Linux/arm

### ISSUE THREAD

**Issue by hlapp** [golang/go#13952]
I built Go 1.5.3 from source on Linux/Arm (Raspberry Pi 2, Debian Jessie). All tests pass except one, both when run through `all.bash` and when run standalone after installation. Below is the standalone result.

I thought this might be in the same vein as #11959, which was fixed, but oddly enough I can't find the referenced commit that purportedly fixed it in the commit history of the go1.5.3 tag.

```sh
$ TMPDIR=$HOME/Tmp go test runtime
SIGQUIT: quit
PC=0x744cc m=0

goroutine 0 [idle]:
runtime.futex(0x30c168, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1f1c8, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/runtime/sys_linux_arm.s:246 +0x1c
runtime.futexsleep(0x30c168, 0x0, 0xffffffff, 0xffffffff)
	/usr/local/go/src/runtime/os1_linux.go:39 +0x68
runtime.notesleep(0x30c168)
	/usr/local/go/src/runtime/lock_futex.go:142 +0xa4
runtime.stoplockedm()
	/usr/local/go/src/runtime/proc1.go:1276 +0xa0
runtime.schedule()
	/usr/local/go/src/runtime/proc1.go:1598 +0x58
runtime.park_m(0x105000e0)
	/usr/local/go/src/runtime/proc1.go:1706 +0x16c
runtime.mcall(0x30bf00)
	/usr/local/go/src/runtime/asm_arm.s:178 +0x5c

goroutine 1 [chan receive, 2 minutes, locked to thread]:
runtime.gopark(0x26275c, 0x10512170, 0x221828, 0xc, 0x17, 0x3)
	/usr/local/go/src/runtime/proc.go:185 +0x148 fp=0x10543d70 sp=0x10543d5c
runtime.goparkunlock(0x10512170, 0x221828, 0xc, 0x17, 0x3)
	/usr/local/go/src/runtime/proc.go:191 +0x44 fp=0x10543d8c sp=0x10543d70
runtime.chanrecv(0x1b6c70, 0x10512140, 0x10543eac, 0x10543e01, 0x90000)
	/usr/local/go/src/runtime/chan.go:448 +0x4b8 fp=0x10543df8 sp=0x10543d8c
runtime.chanrecv1(0x1b6c70, 0x10512140, 0x10543eac)
	/usr/local/go/src/runtime/chan.go:349 +0x28 fp=0x10543e10 sp=0x10543df8
testing.RunTests(0x262538, 0x30a110, 0xa2, 0xa2, 0x1)
	/usr/local/go/src/testing/testing.go:562 +0x618 fp=0x10543ee0 sp=0x10543e10
testing.(*M).Run(0x10543f7c, 0x125e0)
	/usr/local/go/src/testing/testing.go:494 +0x6c fp=0x10543f28 sp=0x10543ee0
main.main()
	runtime/_test/_testmain.go:954 +0x118 fp=0x10543fa4 sp=0x10543f28
runtime.main()
	/usr/local/go/src/runtime/proc.go:111 +0x2b4 fp=0x10543fcc sp=0x10543fa4
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm.s:1036 +0x4 fp=0x10543fcc sp=0x10543fcc

goroutine 20213232 [running]:
	goroutine running on other thread; stack unavailable
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:561 +0x5ec

goroutine 20213203 [running]:
	goroutine running on other thread; stack unavailable
created by runtime_test.TestPrintGC
	/usr/local/go/src/runtime/gc_test.go:408 +0x16c

trap    0x6
error   0x0
oldmask 0x0
r0      0x30c168
r1      0x0
r2      0x0
r3      0x0
r4      0x0
r5      0x0
r6      0x10520a00
r7      0xf0
r8      0x30c0c8
r9      0x0
r10     0x30bee0
fp      0x30bdb4
ip      0x10e311b9
sp      0x7e92a5a4
lr      0x3af30
pc      0x744cc
cpsr    0xa0000010
fault   0x0
*** Test killed with quit: ran too long (10m0s).
FAIL	runtime	600.018s
```

**Comment by davecheney** [comment]
`/all.bash` runs `go test runtime -short`, it is likely that the full tests suite will not pass on the rpi in under 10 minutes.

Please consult, http://dave.cheney.net/2015/09/04/building-go-1-5-on-the-raspberry-pi. I'm going to close this now, please reopen it if you have further questions, or feel free to take this to the golang-nuts mailing list.

**Comment by hlapp** [comment]
I had missed that blog post. Indeed with the following the test does succeed:

```sh
$ ulimit -s 1024
$ go test runtime -short
ok  	runtime	158.323s
```
If I leave off the `-short` but set `GO_TEST_TIMEOUT_SCALE=10` as per your post, it still gets killed after 600 seconds.

I added a [tip to the GoArm wiki page](https://github.com/golang/go/wiki/GoArm#test-failures-due-to-resource-starvation), and also added a link to your blog post under the [RPi 2 section](https://github.com/golang/go/wiki/GoArm#raspberry-pi-2) (which is where I scrolled to, going right past the RPi section which does link to your post).
