### ISSUE TITLE
x/tools/cmd/oracle: `panic: builtin unsafe.Alignof` when handling `import "unsafe"`

### ISSUE THREAD

**Issue by drathier** [golang/go#14160]
`go version go1.5.3 windows/amd64`

I'm using git commit `f8ecfdb6b66ec67ca930b39806519a2b72d1eaca` of oracle, fetched using `go get golang.org/x/tools/cmd/oracle`

```
drathier@dratq MINGW64 /
$ oracle -format=json -pos=$GOPATH/src/github.com/couchbase/go-couchbase/platform/sync.go:#184 describe github.com/couchbase/go-couchbase/platform
panic: builtin unsafe.Alignof

goroutine 1 [running]:
golang.org/x/tools/oracle.tokenOf(0xf74748, 0xc082011540, 0x0, 0x0)
        C:/gopath/src/golang.org/x/tools/oracle/describe15.go:684 +0x128
golang.org/x/tools/oracle.(*describePackageResult).toSerial(0xc0826d22d0, 0xc082ce68c0, 0xc0820c5200)
        C:/gopath/src/golang.org/x/tools/oracle/describe15.go:656 +0x328
golang.org/x/tools/oracle.(*Query).Serial(0xc0820a8a10, 0x4)
        C:/gopath/src/golang.org/x/tools/oracle/oracle.go:98 +0xb0
main.main()
        C:/gopath/src/golang.org/x/tools/cmd/oracle/main.go:186 +0xb66
```

Contents of `$GOPATH/src/github.com/couchbase/go-couchbase/platform/sync.go`, truncated:
```
//
// This is a thin wrapper around sync/atomic to help with alignment issues.
// This is for 64-bit OS and hence is a no-op effectively.
//

// +build !386

package platform

import "unsafe"
import orig "sync/atomic"

type AlignedInt64 int64
type AlignedUint64 uint64

func NewAlignedInt64(v int64) AlignedInt64 {
	return AlignedInt64(v)
}
```

The `184`th character is the `u` in `import "unsafe"`

I'm using git commit `3b77a41676c2fbcbd0d1e6c3ed49c533a28ac067` of `github.com/couchbase/go-couchbase`.

**Comment by alandonovan** [comment]
Fixed by https://go-review.googlesource.com/19158
