### ISSUE TITLE
bufio panic: runtime error: slice bounds out of range (b.r/b.w out of sync?)

### ISSUE THREAD

**Issue by tgulacsi** [golang/go#14523]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.6 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/kobe/dev/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

3. What did you do?
(Use play.golang.org to provide a runnable example, if possible.)
Create a padding-fixing base64 decoder with io.Pipe

4. What did you expect to see?
works, no panic

5. What did you see instead?
```
panic: runtime error: slice bounds out of range

goroutine 31 [running]:
panic(0xa2b5e0, 0xc82000e0e0)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
bufio.(*Reader).Read(0xc8200706c0, 0xc82018a0ab, 0xf55, 0xf55, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:214 +0x3c8
io.(*multiReader).Read(0xc8201d7280, 0xc82018a0ab, 0xf55, 0xf55, 0x7fe74ce4c880, 0x0, 0x0)
        /usr/local/go/src/io/multi.go:13 +0xa4
bufio.(*Reader).fill(0xc820070720)
        /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820070720, 0x1000, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xcc
mime/multipart.partReader.Read(0xc820087040, 0xc82018b028, 0xfd8, 0xfd8, 0x0, 0x0, 0x0)
        /usr/local/go/src/mime/multipart/multipart.go:156 +0x146
mime/multipart.(*Part).Read(0xc820087040, 0xc82018b028, 0xfd8, 0xfd8, 0xc8200ee580, 0x0, 0x0)
        /usr/local/go/src/mime/multipart/multipart.go:137 +0x6d
io.(*multiReader).Read(0xc8201d73e0, 0xc82018b028, 0xfd8, 0xfd8, 0xc82000e170, 0x0, 0x0)
        /usr/local/go/src/io/multi.go:13 +0xa4
bufio.(*Reader).fill(0xc8200707e0)
        /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8200707e0, 0x1000, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xcc
mime/multipart.partReader.Read(0xc820087130, 0xc82018df4d, 0xb3, 0xb3, 0x0, 0x0, 0x0)
        /usr/local/go/src/mime/multipart/multipart.go:156 +0x146
mime/multipart.(*Part).Read(0xc820087130, 0xc82018df4d, 0xb3, 0xb3, 0x0, 0x0, 0x0)
        /usr/local/go/src/mime/multipart/multipart.go:137 +0x6d
io.(*multiReader).Read(0xc8201d74a0, 0xc82018df4d, 0xb3, 0xb3, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/multi.go:13 +0xa4
bufio.(*Reader).fill(0xc820070de0)
        /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820070de0, 0x1000, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xcc
mime/multipart.partReader.Read(0xc820087220, 0xc8213bc000, 0x4000, 0x4000, 0x0, 0x0, 0x0)
        /usr/local/go/src/mime/multipart/multipart.go:156 +0x146
mime/multipart.(*Part).Read(0xc820087220, 0xc8213bc000, 0x4000, 0x4000, 0x4000, 0x0, 0x0)
        /usr/local/go/src/mime/multipart/multipart.go:137 +0x6d
github.com/tgulacsi/go/i18nmail.NewFilterReader.func1(0x7fe74ce4ea18, 0xc820087220, 0xc8200de500, 0xc82002c040)
        /home/kobe/dev/go/src/github.com/tgulacsi/go/i18nmail/base64_decode.go:38 +0xed
created by github.com/tgulacsi/go/i18nmail.NewFilterReader
        /home/kobe/dev/go/src/github.com/tgulacsi/go/i18nmail/base64_decode.go:72 +0x1f9
```

**Comment by minux** [comment]
We need a program (preferably small and standalone) to reproduce this.

Have you run you program under race detector?

**Comment by tgulacsi** [comment]
I'm inclined to think that there is a data race.
I cannot reproduce it yet, and of course it happened only in production. Now it runs with race detector enabled, but a different implementation (without io.Pipe).

I see that bufio.Reader is not concurrency-safe; I'll try to find where it is read from multiple goroutines.

**Comment by tgulacsi** [comment]
I could reproduce something alike (only with -race):
[go14523.go.zip](https://github.com/golang/go/files/148624/go14523.go.zip)

So yes, it seems to be a data race - sorry for the noise!
