### ISSUE TITLE
linux/amd64 buildbot failure: need to be zeroed pointer leaked into live program

### ISSUE THREAD

**Issue by davecheney** [golang/go#14666]
```
unexpected fault address 0x0
fatal error: fault
[signal 0x7 code=0x80 addr=0x0 pc=0x55c755]

goroutine 36 [running]:
runtime.throw(0x70f852, 0x5)
	/tmp/workdir/go/src/runtime/panic.go:566 +0x8c fp=0xc8201ed2b0 sp=0xc8201ed298
runtime.sigpanic()
	/tmp/workdir/go/src/runtime/sigpanic_unix.go:21 +0xe8 fp=0xc8201ed300 sp=0xc8201ed2b0
math/big.nat.cmp(0xdeaddeaddeaddead, 0x9, 0x1e, 0xc82007a410, 0x9, 0xa, 0x9)
	/tmp/workdir/go/src/math/big/nat.go:162 +0x45 fp=0xc8201ed308 sp=0xc8201ed300
math/big.nat.div(0x0, 0x0, 0x0, 0xdeaddeaddeaddead, 0x9, 0x1e, 0xdeaddeaddeaddead, 0x9, 0x1e, 0xc82007a410, ...)
	/tmp/workdir/go/src/math/big/nat.go:525 +0x7b fp=0xc8201ed3c8 sp=0xc8201ed308
math/big.(*Int).QuoRem(0xc8201ed4b0, 0xc8203ac200, 0xc82000e920, 0xc8203ac200, 0xc820012840, 0xc82039c920)
	/tmp/workdir/go/src/math/big/int.go:227 +0xaf fp=0xc8201ed478 sp=0xc8201ed3c8
math/big.(*Int).Mod(0xc8203ac200, 0xc8203ac200, 0xc82000e920, 0xc82039c8a0)
	/tmp/workdir/go/src/math/big/int.go:258 +0xcf fp=0xc8201ed4f8 sp=0xc8201ed478
crypto/ecdsa.Verify(0xc8201b1900, 0xc8201b1de0, 0x14, 0x20, 0xc8201b1e00, 0xc8201b1e20, 0x0)
	/tmp/workdir/go/src/crypto/ecdsa/ecdsa.go:259 +0x405 fp=0xc8201ed608 sp=0xc8201ed4f8
crypto/tls.(*ecdheKeyAgreement).processServerKeyExchange(0xc8201aebc0, 0xc820080280, 0xc8201b23c0, 0xc8201de580, 0xc8201f0480, 0xc8201b6c30, 0x0, 0xc8201cec00)
	/tmp/workdir/go/src/crypto/tls/key_agreement.go:366 +0x796 fp=0xc8201ed738 sp=0xc8201ed608
crypto/tls.(*clientHandshakeState).doFullHandshake(0xc8201edc50, 0xc8201cec60, 0x59)
	/tmp/workdir/go/src/crypto/tls/handshake_client.go:318 +0x416 fp=0xc8201edaa0 sp=0xc8201ed738
crypto/tls.(*Conn).clientHandshake(0xc8201cc600, 0x72a778, 0xc8201cc614)
	/tmp/workdir/go/src/crypto/tls/handshake_client.go:209 +0xec9 fp=0xc8201edd00 sp=0xc8201edaa0
crypto/tls.(*Conn).Handshake(0xc8201cc600, 0x0, 0x0)
	/tmp/workdir/go/src/crypto/tls/conn.go:1031 +0x9f fp=0xc8201edd28 sp=0xc8201edd00
crypto/tls.(*Conn).Write(0xc8201cc600, 0xc8201ede70, 0x6, 0x6, 0x0, 0x0, 0x0)
	/tmp/workdir/go/src/crypto/tls/conn.go:878 +0xdd fp=0xc8201eddb0 sp=0xc8201edd28
crypto/tls.(*clientTest).run.func1(0xc8201cc600, 0xc82013ecf0, 0xc8201c6b80, 0x7fc10778e7e0, 0xc8201b49a0, 0xc8201ceae0)
	/tmp/workdir/go/src/crypto/tls/handshake_client_test.go:212 +0x8a fp=0xc8201edf60 sp=0xc8201eddb0
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:2006 +0x1 fp=0xc8201edf68 sp=0xc8201edf60
created by crypto/tls.(*clientTest).run
	/tmp/workdir/go/src/crypto/tls/handshake_client_test.go:223 +0x210
```

https://storage.googleapis.com/go-build-log/ea276538/linux-amd64_e00cadd4.log

**Comment by bradfitz** [comment]
Sorry, I filed a dup at #14667 before seeing this. Mine has a tiny bit more info (and an assignment), so I'll close this one, even though yours came first.

**Comment by davecheney** [comment]
@bradfitz no worries, thanks for logging a version with more information.
