### ISSUE TITLE
x/tools/cmd/guru: running guru on non-Go file panics

### ISSUE THREAD

**Issue by dominikh** [golang/go#14684]
```
$ touch /tmp/foo        
$ guru what /tmp/foo:\#0
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x4274bb]

goroutine 1 [running]:
panic(0x81f800, 0xc820012180)
	/usr/lib/go/src/runtime/panic.go:464 +0x3e6
main.fileOffsetToPos(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/dominikh/prj/go/src/golang.org/x/tools/cmd/guru/pos.go:78 +0x4b
main.fastQueryPos(0xab2be0, 0x7fff0dd27320, 0xb, 0xc81fffc2c0, 0x0, 0x0)
	/home/dominikh/prj/go/src/golang.org/x/tools/cmd/guru/pos.go:128 +0x1fb
main.what(0xc8200ce930, 0x0, 0x0)
	/home/dominikh/prj/go/src/golang.org/x/tools/cmd/guru/what.go:28 +0x60
main.Run(0xc8200ce930, 0x0, 0x0)
	/home/dominikh/prj/go/src/golang.org/x/tools/cmd/guru/guru.go:126 +0x13f
main.main()
	/home/dominikh/prj/go/src/golang.org/x/tools/cmd/guru/main.go:204 +0x8d5
```

/cc @alandonovan

**Comment by dominikh** [comment]
Closing this issue manually because @gopherbot refuses to.
