### ISSUE TITLE
cmd/link: panic during go install -buildmode=shared -linkshared std

### ISSUE THREAD

**Issue by paulzhol** [golang/go#14841]
1. What version of Go are you using (`go version`)?
`go version devel +80a0517 Tue Mar 15 16:25:40 2016 +0000 linux/386`

2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="386"
GOBIN=""
GOEXE=""
GOHOSTARCH="386"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/home/yuval/go.git"
GOTOOLDIR="/home/yuval/go.git/pkg/tool/linux_386"
CC="gcc"
GOGCCFLAGS="-fPIC -m32 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build105912400=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

3. What did you do?
running `GOHOSTARCH=386 GOARCH=386 ../bin/go install -buildmode=shared -linkshared std`
from the src directory.

4. What did you expect to see?
success

5. What did you see instead?
```
# /tmp/go-build111140044/libstd.so
panic: method slice pointer in ".dup" leads to a different symbol

goroutine 1 [running]:
panic(0x81d5080, 0x1e9e2bf0)
        /home/yuval/go.git/src/runtime/panic.go:500 +0x331
cmd/link/internal/ld.decodetype_methods(0x1cdb1b50, 0x0, 0x0, 0x0)
        /home/yuval/go.git/src/cmd/link/internal/ld/decodesym.go:351 +0x31d
cmd/link/internal/ld.(*deadcodepass).flood(0x1853bd94)
        /home/yuval/go.git/src/cmd/link/internal/ld/deadcode.go:306 +0x998
cmd/link/internal/ld.deadcode(0x18796000)
        /home/yuval/go.git/src/cmd/link/internal/ld/deadcode.go:59 +0x1ae
cmd/link/internal/ld.Ldmain()
        /home/yuval/go.git/src/cmd/link/internal/ld/pobj.go:190 +0x1290
cmd/link/internal/x86.Main()
        /home/yuval/go.git/src/cmd/link/internal/x86/obj.go:44 +0x1c
main.main()
        /home/yuval/go.git/src/cmd/link/main.go:25 +0xf6
```

**Comment by ianlancetaylor** [comment]
CC @mwhudson

**Comment by mwhudson** [comment]
Hm happens on linux/amd64 too. Oh good.
