### ISSUE TITLE
runtime: gccgo internal compiler error bootstrapping master

### ISSUE THREAD

**Issue by alberts** [golang/go#14880]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?

gcc-go-5.3.1-2.fc23.x86_64
1. What operating system and processor architecture are you using (`go env`)?

``` GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr"
GOTOOLDIR="/usr/libexec/gcc/x86_64-redhat-linux/5.3.1"
CC="/usr/bin/gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="/usr/bin/g++"
CGO_ENABLED="1"
```
1. What did you do?

/usr/bin/go configured with update-alternatives to be /usr/bin/go.gcc.

did a GOROOT_BOOTSTRAP=/usr ./make.bash of master
1. What did you see instead?

```
##### Building go_bootstrap for host, linux/amd64.
runtime/internal/sys
runtime/internal/atomic
runtime
/home/albert/repos/go/src/runtime/alg.go:132: internal compiler error: panic during generic cse while compiling c64hash:

runtime error: index out of range

goroutine 16 [running]:
ssa.$nested0
    /home/albert/repos/go/src/cmd/compile/internal/ssa/compile.go:31
ssa.cse
    /home/albert/repos/go/src/cmd/compile/internal/ssa/cse.go:155
bootstrap_compile_internal_ssa.Compile
    /home/albert/repos/go/src/cmd/compile/internal/ssa/compile.go:64
gc.buildssa
    /home/albert/repos/go/src/cmd/compile/internal/gc/ssa.go:221
gc.compile
    /home/albert/repos/go/src/cmd/compile/internal/gc/pgen.go:409
gc.funccompile
    /home/albert/repos/go/src/cmd/compile/internal/gc/dcl.go:1305
bootstrap_compile_internal_gc.Main
    /home/albert/repos/go/src/cmd/compile/internal/gc/main.go:475
bootstrap_compile_internal_amd64.Main
    /home/albert/repos/go/src/cmd/compile/internal/amd64/galign.go:104
main.main
    /home/albert/repos/go/src/cmd/compile/main.go:32
```

Works fine with the go1.6 branch, so some of the new ssa code is making gccgo unhappy.

This is probably a rare bootstrap setup, but probably something to be aware of.

**Comment by ianlancetaylor** [comment]
I don't know what went wrong here, but I just tried it with tip and it seemed to work fine.  Closing.
