### ISSUE TITLE
runtime: fatal error: bad pointer in write barrier on linux-s390x-ibm

### ISSUE THREAD

**Issue by mikioh** [golang/go#15270]
See http://build.golang.org/log/0c4bb957f324e4371f4364878cc79d42c57187b5
```
ok  	regexp	0.074s
ok  	regexp/syntax	0.388s
runtime: writebarrierptr *0x3503d0 = 0x400
fatal error: bad pointer in write barrier

runtime stack:
runtime.throw(0x26eb38, 0x1c)
	/data/golang/workdir/go/src/runtime/panic.go:566 +0x96 fp=0x3ff8dc7eee0 sp=0x3ff8dc7eec8
runtime.writebarrierptr.func1()
	/data/golang/workdir/go/src/runtime/mbarrier.go:140 +0xc0 fp=0x3ff8dc7ef08 sp=0x3ff8dc7eee0
runtime.systemstack(0xc82001a000)
	/data/golang/workdir/go/src/runtime/asm_s390x.s:249 +0x9a fp=0x3ff8dc7ef10 sp=0x3ff8dc7ef08
runtime.mstart()
	/data/golang/workdir/go/src/runtime/proc.go:1077 fp=0x3ff8dc7ef10 sp=0x3ff8dc7ef10
(snip)
```
/CC @aclements

**Comment by aclements** [comment]
It looks like atomic.Storep1 on s390 generates a write barrier. On other platforms it does not (that's what `runtime.atomicstorep` is for, though this appears to be completely undocumented).

Going a little further down, here's where the "bad pointer write" actually happened:

```
goroutine 102586 [running]:
runtime.systemstack_switch()
	/data/golang/workdir/go/src/runtime/asm_s390x.s:203 +0x10 fp=0xc820409be8 sp=0xc820409be0
runtime.writebarrierptr(0x3503d0, 0x400)
	/data/golang/workdir/go/src/runtime/mbarrier.go:141 +0xd2 fp=0xc820409c18 sp=0xc820409be8
runtime/internal/atomic.Storep1(0x3503d0, 0x400)
	/data/golang/workdir/go/src/runtime/internal/atomic/atomic_s390x.go:43 +0x56 fp=0xc820409c30 sp=0xc820409c18
runtime.mapzero(0x206f80)
	/data/golang/workdir/go/src/runtime/hashmap.go:1079 +0x13a fp=0xc820409c60 sp=0xc820409c30
...
```

This is actually a scalar write (the zerosize global), but we're doing it using an atomic pointer write (yuck!).

I'll send a CL.
