### ISSUE TITLE
net/http/httptest: panic: net.dialTCP: deadline not implemented on Plan 9

### ISSUE THREAD

**Issue by mikioh** [golang/go#15328]
See http://build.golang.org/log/a8c60a1abdc14d36f097654d58ad072fbfa3a869. The package encoding/json uses net/http/httptest package.
```
ok  	encoding/hex	0.029s
panic: net.dialTCP: deadline not implemented on Plan 9

goroutine 76 [running]:
panic(0x2443c0, 0x10713470)
	/tmp/workdir/go/src/runtime/panic.go:500 +0x32f
net.doDialTCP(0x381480, 0x10681e80, 0x284f28, 0x3, 0x0, 0x107117e0, 0x491b0, 0x0, 0x0)
	/tmp/workdir/go/src/net/tcpsock_plan9.go:26 +0xd0
net.dialTCP(0x381480, 0x10681e80, 0x284f28, 0x3, 0x0, 0x107117e0, 0xfc22d0a7, 0x0, 0x0)
	/tmp/workdir/go/src/net/tcpsock_plan9.go:21 +0xa3
net.dialSingle(0x381480, 0x10681e80, 0x1064a9b0, 0x380410, 0x107117e0, 0x0, 0x0, 0x0, 0x0)
	/tmp/workdir/go/src/net/dial.go:482 +0x4f6
net.dialSerial(0x381480, 0x10681e80, 0x1064a9b0, 0x10713468, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/tmp/workdir/go/src/net/dial.go:459 +0x7b2
net.(*Dialer).DialContext(0x104f2540, 0x381480, 0x10681e80, 0x284f28, 0x3, 0x10711687, 0xf, 0x0, 0x0, 0x0, ...)
	/tmp/workdir/go/src/net/dial.go:341 +0x776
net.(*Dialer).Dial(0x104f2540, 0x284f28, 0x3, 0x10711687, 0xf, 0x0, 0x0, 0x0, 0x0)
	/tmp/workdir/go/src/net/dial.go:282 +0x7d
net.(*Dialer).Dial-fm(0x284f28, 0x3, 0x10711687, 0xf, 0x0, 0x0, 0x0, 0x0)
	/tmp/workdir/go/src/net/http/transport.go:38 +0x57
net/http.(*Transport).dial(0x10510630, 0x284f28, 0x3, 0x10711687, 0xf, 0x0, 0x0, 0x0, 0x0)
	/tmp/workdir/go/src/net/http/transport.go:694 +0x67
net/http.(*Transport).dialConn(0x10510630, 0x0, 0x10711680, 0x4, 0x10711687, 0xf, 0x0, 0x0, 0x0)
	/tmp/workdir/go/src/net/http/transport.go:800 +0x1be9
net/http.(*Transport).getConn.func4(0x10510630, 0x0, 0x10711680, 0x4, 0x10711687, 0xf, 0x10681c80)
	/tmp/workdir/go/src/net/http/transport.go:741 +0x4c
created by net/http.(*Transport).getConn
	/tmp/workdir/go/src/net/http/transport.go:743 +0x206
FAIL	encoding/json	0.217s
ok
```
/CC @bradfitz

**Comment by bradfitz** [comment]
Yay #15251

**Comment by 0intro** [comment]
This is related to issue  #11932.
