### ISSUE TITLE
runtime: SIGILL on s390x

### ISSUE THREAD

**Issue by mundaym** [golang/go#15441]
Seen once on builder: https://build.golang.org/log/98f78c44f220efba6d59ff71e675126b841950a0
```
##### GOMAXPROCS=2 runtime -cpu=1,2,4
SIGILL: illegal instruction
PC=0x82be4 m=2

goroutine 0 [idle]:
runtime.usleep()
	/data/golang/workdir/go/src/runtime/sys_linux_s390x.s:129 +0x54 fp=0x3ff9cffee98 sp=0x3ff9cffee80

goroutine 1 [chan receive, locked to thread]:
runtime.gopark(0x2803d0, 0xc8202add98, 0x25fcfe, 0xc, 0x1700000000000010, 0x3)
	/data/golang/workdir/go/src/runtime/proc.go:264 +0x18a fp=0xc8200479a0 sp=0xc820047978
runtime.goparkunlock(0xc8202add98, 0x25fcfe, 0xc, 0x1700000000000000, 0x3)
	/data/golang/workdir/go/src/runtime/proc.go:270 +0x66 fp=0xc8200479d8 sp=0xc8200479a0
runtime.chanrecv(0x2133a0, 0xc8202add40, 0x0, 0x10000c820047a98, 0x97d46)
	/data/golang/workdir/go/src/runtime/chan.go:496 +0x548 fp=0xc820047a60 sp=0xc8200479d8
runtime.chanrecv1(0x2133a0, 0xc8202add40, 0x0)
	/data/golang/workdir/go/src/runtime/chan.go:378 +0x3a fp=0xc820047a90 sp=0xc820047a60
testing.(*T).Run(0xc82007ac00, 0x261a8a, 0x11, 0x281400, 0x100000000042b62)
	/data/golang/workdir/go/src/testing/testing.go:584 +0x3a0 fp=0xc820047b60 sp=0xc820047a90
testing.RunTests.func1(0xc82007a0c0)
	/data/golang/workdir/go/src/testing/testing.go:730 +0xda fp=0xc820047bf0 sp=0xc820047b60
testing.tRunner(0xc82007a0c0, 0xc820047d30)
	/data/golang/workdir/go/src/testing/testing.go:547 +0xd8 fp=0xc820047c28 sp=0xc820047bf0
testing.RunTests(0x27fd80, 0x369ac0, 0xba, 0xba, 0x1000000000e9ce7)
	/data/golang/workdir/go/src/testing/testing.go:736 +0x3da fp=0xc820047d50 sp=0xc820047c28
testing.(*M).Run(0xc820047ef8, 0x2e9b80)
	/data/golang/workdir/go/src/testing/testing.go:680 +0x88 fp=0xc820047dd8 sp=0xc820047d50
runtime_test.TestMain(0xc820047ef8)
	/data/golang/workdir/go/src/runtime/crash_test.go:24 +0x2a fp=0xc820047e58 sp=0xc820047dd8
main.main()
	runtime/_test/_testmain.go:1040 +0x14c fp=0xc820047f48 sp=0xc820047e58
runtime.main()
	/data/golang/workdir/go/src/runtime/proc.go:188 +0x2de fp=0xc820047f98 sp=0xc820047f48
runtime.goexit()
	/data/golang/workdir/go/src/runtime/asm_s390x.s:1016 +0x2 fp=0xc820047f98 sp=0xc820047f98

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/data/golang/workdir/go/src/runtime/asm_s390x.s:1016 +0x2 fp=0xc820036fb0 sp=0xc820036fb0

goroutine 2 [force gc (idle)]:
runtime.gopark(0x2803d0, 0x36d320, 0x260e24, 0xf, 0x1400000000000000, 0x1)
	/data/golang/workdir/go/src/runtime/proc.go:264 +0x18a fp=0xc820022750 sp=0xc820022728
runtime.goparkunlock(0x36d320, 0x260e24, 0xf, 0x140000c820000180, 0x1)
	/data/golang/workdir/go/src/runtime/proc.go:270 +0x66 fp=0xc820022788 sp=0xc820022750
runtime.forcegchelper()
	/data/golang/workdir/go/src/runtime/proc.go:229 +0xba fp=0xc8200227b8 sp=0xc820022788
runtime.goexit()
	/data/golang/workdir/go/src/runtime/asm_s390x.s:1016 +0x2 fp=0xc8200227b8 sp=0xc8200227b8
created by runtime.init.4
	/data/golang/workdir/go/src/runtime/proc.go:218 +0x30

goroutine 3 [GC sweep wait]:
runtime.gopark(0x2803d0, 0x36d660, 0x2600cc, 0xd, 0x1400000000075b70, 0x1)
	/data/golang/workdir/go/src/runtime/proc.go:264 +0x18a fp=0xc820022f40 sp=0xc820022f18
runtime.goparkunlock(0x36d660, 0x2600cc, 0xd, 0x1400000000000000, 0x1)
	/data/golang/workdir/go/src/runtime/proc.go:270 +0x66 fp=0xc820022f78 sp=0xc820022f40
runtime.bgsweep(0xc820052000)
	/data/golang/workdir/go/src/runtime/mgcsweep.go:79 +0x154 fp=0xc820022fb0 sp=0xc820022f78
runtime.goexit()
	/data/golang/workdir/go/src/runtime/asm_s390x.s:1016 +0x2 fp=0xc820022fb0 sp=0xc820022fb0
created by runtime.gcenable
	/data/golang/workdir/go/src/runtime/mgc.go:195 +0x5a

goroutine 4 [finalizer wait]:
runtime.gopark(0x2803d0, 0x3975c0, 0x260858, 0xe, 0x1400000100000020, 0x1)
	/data/golang/workdir/go/src/runtime/proc.go:264 +0x18a fp=0xc820023710 sp=0xc8200236e8
runtime.goparkunlock(0x3975c0, 0x260858, 0xe, 0x1400002000000020, 0x1)
	/data/golang/workdir/go/src/runtime/proc.go:270 +0x66 fp=0xc820023748 sp=0xc820023710
runtime.runfinq()
	/data/golang/workdir/go/src/runtime/mfinal.go:158 +0xa4 fp=0xc8200237b8 sp=0xc820023748
runtime.goexit()
	/data/golang/workdir/go/src/runtime/asm_s390x.s:1016 +0x2 fp=0xc8200237b8 sp=0xc8200237b8
created by runtime.createfing
	/data/golang/workdir/go/src/runtime/mfinal.go:139 +0x66

goroutine 5 [syscall]:
runtime.notetsleepg(0x36d778, 0x3b90cab0, 0x0)
	/data/golang/workdir/go/src/runtime/lock_futex.go:205 +0x4e fp=0xc820023f30 sp=0xc820023f08
runtime.timerproc()
	/data/golang/workdir/go/src/runtime/time.go:209 +0xec fp=0xc820023fb8 sp=0xc820023f30
runtime.goexit()
	/data/golang/workdir/go/src/runtime/asm_s390x.s:1016 +0x2 fp=0xc820023fb8 sp=0xc820023fb8
created by runtime.addtimerLocked
	/data/golang/workdir/go/src/runtime/time.go:116 +0x1c2

goroutine 102793 [runnable]:
strconv.bigFtoa(0xc82007a068, 0x1, 0x44, 0x2, 0x660003ff9d339000, 0x12dfd694ccab3f, 0xffffffffffffffef, 0x350a10, 0x0, 0x15a804, ...)
	/data/golang/workdir/go/src/strconv/ftoa.go:155 fp=0xc820049528 sp=0xc820049528
strconv.genericFtoa(0xc82007a068, 0x1, 0x44, 0x3ee2dfd694ccab3f, 0x660000000002421a, 0x2, 0x40, 0x0, 0x0, 0x0)
	/data/golang/workdir/go/src/strconv/ftoa.go:149 +0x5de fp=0xc8200496f0 sp=0xc820049528
strconv.AppendFloat(0xc82007a068, 0x1, 0x44, 0x3ee2dfd694ccab3f, 0x6600000000000000, 0x2, 0x40, 0x0, 0x0, 0x0)
	/data/golang/workdir/go/src/strconv/ftoa.go:51 +0x78 fp=0xc820049748 sp=0xc8200496f0
fmt.(*fmt).fmt_float(0xc82007a040, 0x3ee2dfd694ccab3f, 0x40, 0x6620034928, 0x2)
	/data/golang/workdir/go/src/fmt/format.go:459 +0xba fp=0xc820049850 sp=0xc820049748
fmt.(*pp).fmtFloat(0xc82007a000, 0x3ee2dfd694ccab3f, 0x40, 0x6620034928)
	/data/golang/workdir/go/src/fmt/print.go:395 +0x8e fp=0xc820049880 sp=0xc820049850
fmt.(*pp).printArg(0xc82007a000, 0x212040, 0xc820230bf8, 0x6600000001)
	/data/golang/workdir/go/src/fmt/print.go:630 +0x484 fp=0xc820049a28 sp=0xc820049880
fmt.(*pp).doPrintf(0xc82007a000, 0x25d802, 0x5, 0xc820049d48, 0x1, 0x1)
	/data/golang/workdir/go/src/fmt/print.go:1078 +0x163a fp=0xc820049ca8 sp=0xc820049a28
fmt.Sprintf(0x25d802, 0x5, 0xc820049d48, 0x1, 0x1, 0x0, 0x0)
	/data/golang/workdir/go/src/fmt/print.go:196 +0x78 fp=0xc820049cf8 sp=0xc820049ca8
testing.fmtDuration(0x2328, 0x0, 0x0)
	/data/golang/workdir/go/src/testing/testing.go:301 +0x152 fp=0xc820049d70 sp=0xc820049cf8
testing.(*T).report(0xc82007ac00)
	/data/golang/workdir/go/src/testing/testing.go:697 +0x50 fp=0xc820049e98 sp=0xc820049d70
testing.tRunner.func1(0xc82007ac00)
	/data/golang/workdir/go/src/testing/testing.go:541 +0x2b4 fp=0xc820049f50 sp=0xc820049e98
testing.tRunner(0xc82007ac00, 0x281400)
	/data/golang/workdir/go/src/testing/testing.go:549 +0xe6 fp=0xc820049f88 sp=0xc820049f50
runtime.goexit()
	/data/golang/workdir/go/src/runtime/asm_s390x.s:1016 +0x2 fp=0xc820049f88 sp=0xc820049f88
created by testing.(*T).Run
	/data/golang/workdir/go/src/testing/testing.go:583 +0x376

goroutine 144 [GC worker (idle)]:
runtime.gopark(0x2801f8, 0xc820011300, 0x261204, 0x10, 0x140000c8200bffa0, 0x0)
	/data/golang/workdir/go/src/runtime/proc.go:264 +0x18a fp=0xc8200bff40 sp=0xc8200bff18
runtime.gcBgMarkWorker(0xc82001a000)
	/data/golang/workdir/go/src/runtime/mgc.go:1413 +0x104 fp=0xc8200bffb0 sp=0xc8200bff40
runtime.goexit()
	/data/golang/workdir/go/src/runtime/asm_s390x.s:1016 +0x2 fp=0xc8200bffb0 sp=0xc8200bffb0
created by runtime.gcBgMarkStartWorkers
	/data/golang/workdir/go/src/runtime/mgc.go:1334 +0x98

r0   0x0	r1   0x8e
r2   0x0	r3   0x0
r4   0x0	r5   0x0
r6   0x3ff9cffee88	r7   0xafecffaf5336b
r8   0x36dbd0	r9   0x3ff9cfff1f0
r10  0x14	r11  0x0
r12  0x280490	r13  0xc820000900
r14  0x51c98	r15  0x3ff9cffee80
pc   0x82be4	link 0x51c98
FAIL	runtime	14.693s
2016/04/25 15:25:30 Failed: exit status 1
2016/04/25 15:25:30 FAILED
```

**Comment by mundaym** [comment]
Duplicate of #16126, will continue investigation there.
