### ISSUE TITLE
Binary export crashes on "go get -u golang.org/x/tools/godoc/analysis

### ISSUE THREAD

**Issue by dr2chase** [golang/go#15470]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
```
go version devel +74a9bad Wed Apr 27 17:47:49 2016 +0000 darwin/amd64
```

2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/drchase/GoogleDrive/work/gocode"
GORACE=""
GOROOT="/Users/drchase/GoogleDrive/work/go-ssa2"
GOTOOLDIR="/Users/drchase/GoogleDrive/work/go-ssa2/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```
3. What did you do?
Initially `go get -u golang.org/x/tools/cmd/godoc`
Later refined to `go get -u golang.org/x/tools/godoc/analysis`
I'll try to make a smaller test case

4. What did you expect to see?
Success

5. What did you see instead?
```
# golang.org/x/tools/godoc/analysis
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x28 pc=0xef3be]

goroutine 1 [running]:
panic(0x478ec0, 0xc82000e0e0)
	/.../go-ssa2/src/runtime/panic.go:500 +0x18c
cmd/compile/internal/gc.(*exporter).param(0xc8218378b0, 0xc821470800, 0x3, 0x0)
	/.../go-ssa2/src/cmd/compile/internal/gc/bexport.go:834 +0xbe
cmd/compile/internal/gc.(*exporter).paramList(0xc8218378b0, 0xc821498be0, 0xc821470600)
	/.../go-ssa2/src/cmd/compile/internal/gc/bexport.go:810 +0xe2
cmd/compile/internal/gc.(*exporter).method(0xc8218378b0, 0xc821470640)
	/.../go-ssa2/src/cmd/compile/internal/gc/bexport.go:744 +0x87
cmd/compile/internal/gc.(*exporter).methodList(0xc8218378b0, 0xc821498730)
	/.../go-ssa2/src/cmd/compile/internal/gc/bexport.go:737 +0xae
cmd/compile/internal/gc.(*exporter).typ(0xc8218378b0, 0xc821498730)
	/.../go-ssa2/src/cmd/compile/internal/gc/bexport.go:679 +0xf5f
cmd/compile/internal/gc.(*exporter).typ(0xc8218378b0, 0xc8214986e0)
	/.../go-ssa2/src/cmd/compile/internal/gc/bexport.go:586 +0x2eb
cmd/compile/internal/gc.(*exporter).obj(0xc8218378b0, 0xc8208d3b20)
	/.../go-ssa2/src/cmd/compile/internal/gc/bexport.go:459 +0xa3
cmd/compile/internal/gc.export(0xc8221fcd80, 0x0, 0x0)
	/.../go-ssa2/src/cmd/compile/internal/gc/bexport.go:261 +0x47e
cmd/compile/internal/gc.dumpexport()
	/.../go-ssa2/src/cmd/compile/internal/gc/export.go:410 +0x397
cmd/compile/internal/gc.dumpobj()
	/.../go-ssa2/src/cmd/compile/internal/gc/obj.go:44 +0x353
cmd/compile/internal/gc.Main()
	/.../go-ssa2/src/cmd/compile/internal/gc/main.go:487 +0x19fa
cmd/compile/internal/amd64.Main()
	/.../go-ssa2/src/cmd/compile/internal/amd64/galign.go:96 +0x381
main.main()
	/.../go-ssa2/src/cmd/compile/main.go:33 +0x286
```

**Comment by dr2chase** [comment]
A detail that may or may not matter: just before this particular crash, I had tried to update all the tools:
```
for i in benchcmp bundle callgraph cover digraph eg fiximports godex godoc \
goimports gomvpkg gorename gotype guru html2article oracle present ssadump \
stress stringer tip ; do go get -u golang.org/x/tools/cmd/$i; done
```

**Comment by josharian** [comment]
@gri @mdempsky

**Comment by mewmew** [comment]
I also see this with golang/tools@94f857c7cfbc5d8f9a4d0bc33ca16e3d968bb6e2

```
u@x1 ~/D/g/s/g/m/uc> go version
go version devel +2da642a Thu Apr 28 01:38:01 2016 +0000 linux/amd64
```

```
goroutine 1 [running]:
panic(0x877c80, 0xc820010130)
	/home/u/go/src/runtime/panic.go:500 +0x18c
cmd/compile/internal/gc.(*exporter).param(0xc8224f78c0, 0xc8214344c0, 0x3, 0x0)
	/home/u/go/src/cmd/compile/internal/gc/bexport.go:834 +0xbe
cmd/compile/internal/gc.(*exporter).paramList(0xc8224f78c0, 0xc82144bae0, 0xc821434300)
	/home/u/go/src/cmd/compile/internal/gc/bexport.go:810 +0xe2
cmd/compile/internal/gc.(*exporter).method(0xc8224f78c0, 0xc821434300)
	/home/u/go/src/cmd/compile/internal/gc/bexport.go:744 +0x87
cmd/compile/internal/gc.(*exporter).methodList(0xc8224f78c0, 0xc82144b630)
	/home/u/go/src/cmd/compile/internal/gc/bexport.go:737 +0xae
cmd/compile/internal/gc.(*exporter).typ(0xc8224f78c0, 0xc82144b630)
	/home/u/go/src/cmd/compile/internal/gc/bexport.go:679 +0xf5f
cmd/compile/internal/gc.(*exporter).typ(0xc8224f78c0, 0xc82144b5e0)
	/home/u/go/src/cmd/compile/internal/gc/bexport.go:586 +0x2eb
cmd/compile/internal/gc.(*exporter).obj(0xc8224f78c0, 0xc8210dfd50)
	/home/u/go/src/cmd/compile/internal/gc/bexport.go:459 +0xa3
cmd/compile/internal/gc.export(0xc8224ec000, 0x0, 0x0)
	/home/u/go/src/cmd/compile/internal/gc/bexport.go:261 +0x47e
cmd/compile/internal/gc.dumpexport()
	/home/u/go/src/cmd/compile/internal/gc/export.go:410 +0x397
cmd/compile/internal/gc.dumpobj()
	/home/u/go/src/cmd/compile/internal/gc/obj.go:44 +0x353
cmd/compile/internal/gc.Main()
	/home/u/go/src/cmd/compile/internal/gc/main.go:487 +0x19fa
cmd/compile/internal/amd64.Main()
	/home/u/go/src/cmd/compile/internal/amd64/galign.go:96 +0x381
main.main()
	/home/u/go/src/cmd/compile/main.go:33 +0x286
```

**Comment by siebenmann** [comment]
I am seeing this too on current go tip (devel +824e74b) on linux amd64. For me it reproduces if you create a new clean `$GOPATH` to work in:

    export GOPATH=/tmp/gp-temp
    mkdir $GOPATH
    go get golang.org/x/tools/godoc/analysis
    [original reporter's panic happens]

I have not attempted to git bisect to find the git version that introduces this.

**Comment by mewmew** [comment]
> I have not attempted to git bisect to find the git version that introduces this.

Presumably commit 7538b1db8ec0d82a623847fe5987f1988fe16448

**Comment by griesemer** [comment]
Yes, related to the new import format. Please try:

`go get -gcflags="-newexport=0" -u golang.org/x/tools/cmd/godoc`

to see if that helps (it doesn't for me, but I don't know yet if for unrelated reasons or not). Investigating.

**Comment by mewmew** [comment]
> Yes, related to the new import format. Please try:
> `go get -gcflags="-newexport=0" -u golang.org/x/tools/cmd/godoc`

It gave the following (using the same Go version and x/tools revision as reported above):

```
u@x1 ~> go get -gcflags="-newexport=0" -u golang.org/x/tools/cmd/godoc
# golang.org/x/tools/cmd/godoc
goget/src/golang.org/x/tools/cmd/godoc/codewalk.go:32: inconsistent definition for type reflect.rtype during import
	struct { size uintptr; ptrdata uintptr; hash uint32; tflag reflect.tflag; align uint8; fieldAlign uint8; kind uint8; alg *reflect.typeAlg; gcdata *byte; str reflect.nameOff; _ int32 } (in "golang.org/x/tools/blog")
	struct { size uintptr; ptrdata uintptr; hash uint32; tflag reflect.tflag; align uint8; fieldAlign uint8; kind uint8; alg *reflect.typeAlg; gcdata *byte; str reflect.nameOff; _ int32 } (in "golang.org/x/tools/godoc")
```

**Comment by griesemer** [comment]
Temporary work-around: Build our std lib using old export format:

`(export GO_GCFLAGS="-newexport=0"; sh make.bash)`

Then

`go get -gcflags="-newexport=0" -u golang.org/x/tools/cmd/godoc`

seems to work, and possibly also:

`go get -u golang.org/x/tools/cmd/godoc`

**Comment by griesemer** [comment]
@mewmew The std lib also needs to be built with `GO_GCFLAGS="-newexport=0"`, unfortunately.

**Comment by mewmew** [comment]
After recompiling the standard library, using

> `(export GO_GCFLAGS="-newexport=0"; sh make.bash)`

Both

> `go get -gcflags="-newexport=0" -u golang.org/x/tools/cmd/godoc`

and

> `go get -u golang.org/x/tools/cmd/godoc`

work as expected. I'll continue using the new binary format for now, to see if it tickles some other bugs.

**Comment by mewmew** [comment]
@griesemer, thanks for the suggested workaround though! I appreciate having `godoc` installed locally.

**Comment by griesemer** [comment]
Found the issue. Should have a fix as soon as I am confident it's the right one.

**Comment by griesemer** [comment]
@mewmew Please try again (sync and rebuild std lib). You may need to use `go get -a golang.org/x/tools/cmd/godoc` (`-a` option), at least the first time. Thanks.
