### ISSUE TITLE
fatal error: invalid stack pointer

### ISSUE THREAD

**Issue by tokotify** [golang/go#15794]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
```
go version go1.6.2 windows/386
```

2. What operating system and processor architecture are you using (`go env`)?
```
set GOARCH=386
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\user\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_386
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
```
3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

I compiled and ran the following program with proprietarydll.dll. I should provide proprietarydll.dll to reproduce the error, but it is a proprietary library, so I can't. I'm sorry

**crash.go**
```Go
package main

import (
	"fmt"
	"log"
	"runtime"
)

/*
#cgo LDFLAGS: -L. -lproprietarydll
#cgo CFLAGS: -I .
#include "proprietarydll.h"
*/
import "C"

func main() {
	if status, err := C.funcA(); status != C.SUCCESS || err != nil {
		log.Fatal(err)
	}

	handleB, err := C.funcB()
	if handleB == nil || err != nil {
		if err != nil {
			log.Fatal(err)
		}
		log.Fatal("handleB is nil")
	}
	fmt.Println("before:\tGC(funcB)", handleB)
	runtime.GC() // <- cause no error
	fmt.Println("after:\tGC(funcB)", handleB)

	handleC, err := C.funcC(handleB)
	if handleC == nil || err != nil {
		if err != nil {
			log.Fatal("handleC is nil")
		}
		return
	}
	fmt.Println("before:\tGC(funcC)", handleC)
	runtime.GC() // <- cause error
	fmt.Println("after:\tGC(funcC)", handleC)
}
```
**proprietarydll.h** 
(Function names are modified, but types of arguments and return values are same as the original.)
```C
#include <winsock2.h>
#include <windows.h>

// dummy value
#define SUCCESS 12345

// funcA is called to initialize this dll.
DWORD funcA();

// funcB returns a handle for funcC
HANDLE funcB();

// funcC requires a handle returned by funcB
HANDLE funcC(HANDLE);
```

4. What did you expect to see?
I expected that the program is finished without any error.

5. What did you see instead?
I saw the following error
```
before:	GC(funcB) 0xe630020
after:	GC(funcB) 0xe630020
before:	GC(funcC) 0x1a0
runtime: bad pointer in frame main.main at 0x222cdf0c: 0x1a0
fatal error: invalid stack pointer

runtime stack:
runtime.throw(0x4eeb10, 0x15)
	C:/Go/src/runtime/panic.go:547 +0x7f fp=0x2a2fa0c sp=0x2a2fa00
runtime.adjustpointers(0x222cdf0c, 0x2a2facc, 0x2a2fcac, 0x50e784)
	C:/Go/src/runtime/stack.go:579 +0x235 fp=0x2a2fa80 sp=0x2a2fa0c
runtime.adjustframe(0x2a2fc3c, 0x2a2fcac, 0x2a2fb01)
	C:/Go/src/runtime/stack.go:644 +0x163 fp=0x2a2fae8 sp=0x2a2fa80
runtime.gentraceback(0x44aa80, 0x222cdcf8, 0x0, 0x222b8000, 0x0, 0x0, 0x7fffffff, 0x506e60, 0x2a2fcac, 0x0, ...)
	C:/Go/src/runtime/traceback.go:369 +0xbce fp=0x2a2fc68 sp=0x2a2fae8
runtime.copystack(0x222b8000, 0x1000)
	C:/Go/src/runtime/stack.go:759 +0x161 fp=0x2a2fda0 sp=0x2a2fc68
runtime.shrinkstack(0x222b8000)
	C:/Go/src/runtime/stack.go:1026 +0x122 fp=0x2a2fdb8 sp=0x2a2fda0
runtime.markroot(0x5)
	C:/Go/src/runtime/mgcmark.go:155 +0x23e fp=0x2a2fe0c sp=0x2a2fdb8
runtime.gcDrain(0x2a2fe44, 0x0)
	C:/Go/src/runtime/mgcmark.go:812 +0x26a fp=0x2a2fe34 sp=0x2a2fe0c
runtime.gchelper()
	C:/Go/src/runtime/mgc.go:1806 +0x87 fp=0x2a2fe64 sp=0x2a2fe34
runtime.stopm()
	C:/Go/src/runtime/proc.go:1541 +0x10c fp=0x2a2fe74 sp=0x2a2fe64
runtime.findrunnable(0x222b4a00, 0x0)
	C:/Go/src/runtime/proc.go:1976 +0x62a fp=0x2a2febc sp=0x2a2fe74
runtime.schedule()
	C:/Go/src/runtime/proc.go:2075 +0x202 fp=0x2a2fedc sp=0x2a2febc
runtime.park_m(0x222b84e0)
	C:/Go/src/runtime/proc.go:2140 +0x163 fp=0x2a2fef0 sp=0x2a2fedc
runtime.mcall(0x933658)
	C:/Go/src/runtime/asm_386.s:255 +0x47 fp=0x2a2fef8 sp=0x2a2fef0

goroutine 1 [copystack]:
runtime.systemstack_switch()
	C:/Go/src/runtime/asm_386.s:267 fp=0x222cdcfc sp=0x222cdcf8
runtime.gcMarkTermination()
	C:/Go/src/runtime/mgc.go:1182 +0x121 fp=0x222cdec4 sp=0x222cdcfc
runtime.gcStart(0x2, 0x222c2000)
	C:/Go/src/runtime/mgc.go:1018 +0x3f4 fp=0x222cdee4 sp=0x222cdec4
runtime.GC()
	C:/Go/src/runtime/mgc.go:840 +0x26 fp=0x222cdef0 sp=0x222cdee4
main.main()
	C:/dev/crash/crash.go:40 +0x3b4 fp=0x222cdfa8 sp=0x222cdef0
runtime.main()
	C:/Go/src/runtime/proc.go:188 +0x234 fp=0x222cdfd0 sp=0x222cdfa8
runtime.goexit()
	C:/Go/src/runtime/asm_386.s:1585 +0x1 fp=0x222cdfd4 sp=0x222cdfd0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	C:/Go/src/runtime/asm_386.s:1585 +0x1 fp=0x222cbfd4 sp=0x222cbfd0

goroutine 2 [force gc (idle)]:
runtime.gopark(0x506f84, 0x55b488, 0x4e7b40, 0xf, 0x14, 0x1)
	C:/Go/src/runtime/proc.go:262 +0x130 fp=0x222befa4 sp=0x222bef90
runtime.goparkunlock(0x55b488, 0x4e7b40, 0xf, 0x222b8014, 0x1)
	C:/Go/src/runtime/proc.go:268 +0x4b fp=0x222befc0 sp=0x222befa4
runtime.forcegchelper()
	C:/Go/src/runtime/proc.go:229 +0xaa fp=0x222befd8 sp=0x222befc0
runtime.goexit()
	C:/Go/src/runtime/asm_386.s:1585 +0x1 fp=0x222befdc sp=0x222befd8
created by runtime.init.4
	C:/Go/src/runtime/proc.go:218 +0x2a

goroutine 3 [GC sweep wait]:
runtime.gopark(0x506f84, 0x55b500, 0x4e70b0, 0xd, 0x41c914, 0x1)
	C:/Go/src/runtime/proc.go:262 +0x130 fp=0x222bff98 sp=0x222bff84
runtime.goparkunlock(0x55b500, 0x4e70b0, 0xd, 0x14, 0x1)
	C:/Go/src/runtime/proc.go:268 +0x4b fp=0x222bffb4 sp=0x222bff98
runtime.bgsweep(0x222aa0c0)
	C:/Go/src/runtime/mgcsweep.go:63 +0xa0 fp=0x222bffd0 sp=0x222bffb4
runtime.goexit()
	C:/Go/src/runtime/asm_386.s:1585 +0x1 fp=0x222bffd4 sp=0x222bffd0
created by runtime.gcenable
	C:/Go/src/runtime/mgc.go:191 +0x52

goroutine 4 [finalizer wait]:
runtime.gopark(0x506f84, 0x56b1e8, 0x4e7aa0, 0xe, 0x14, 0x1)
	C:/Go/src/runtime/proc.go:262 +0x130 fp=0x222c0f84 sp=0x222c0f70
runtime.goparkunlock(0x56b1e8, 0x4e7aa0, 0xe, 0x14, 0x1)
	C:/Go/src/runtime/proc.go:268 +0x4b fp=0x222c0fa0 sp=0x222c0f84
runtime.runfinq()
	C:/Go/src/runtime/mfinal.go:158 +0x9e fp=0x222c0fd8 sp=0x222c0fa0
runtime.goexit()
	C:/Go/src/runtime/asm_386.s:1585 +0x1 fp=0x222c0fdc sp=0x222c0fd8
created by runtime.createfing
	C:/Go/src/runtime/mfinal.go:139 +0x5c
```

**Comment by minux** [comment]
You need to arrange HANDLE to be translated to a Go uintptr type, rather
than a unsafe.Pointer type.

It's a known problem in Windows API that even though HANDLE is a pointer
type, functions typically return small integers. Go runtime will treat each
declared pointer type as a pointer and crash if it finds an invalid pointer.

**Comment by minux** [comment]
Closing because there is nothing for us to do. Comment if that doesn't fix the problem.

**Comment by tokotify** [comment]
I apologize for my wrong issue report. I wrap functions which return HANDLE to return uintptr_t, then the error no longer occurs.
Thank you.
