### ISSUE TITLE
runtime: defer in shared library on 386 panics

### ISSUE THREAD

**Issue by mwhudson** [golang/go#15916]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

1.6

2. What operating system and processor architecture are you using (`go env`)?

linux/386

3. What did you do?

```
(master)mwhudson@aeglos:/opt/opensource/go/src$ cat $GOPATH/src/t1/t1.go
package t1

func F() {
	defer func() {}()
}
(master)mwhudson@aeglos:/opt/opensource/go/src$ cat /opt/opensource/go-test-cases/triv1.go
package main

import "t1"

func main() {
	t1.F()
}
(master)mwhudson@aeglos:/opt/opensource/go/src$ go install -buildmode=shared std
(master)mwhudson@aeglos:/opt/opensource/go/src$ go install -linkshared -buildmode=shared t1
(master)mwhudson@aeglos:/opt/opensource/go/src$ go run -linkshared /opt/opensource/go-test-cases/triv1.go
```

4. What did you expect to see?

no output

5. What did you see instead?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

goroutine 1 [running]:
panic(0xf74d3c80, 0xd6512018)
	/opt/opensource/go/src/runtime/panic.go:500 +0x59a
t1.F()
	/opt/opensource/gopath/src/t1/t1.go:5 +0x52
main.main()
	/opt/opensource/go-test-cases/triv1.go:6 +0x23
exit status 2
```

I was sure there was a test for this, but there is only one for using defer in a dynamically linked executable, not a shared object. No idea what the issue is yet.

**Comment by mwhudson** [comment]
Ah, think the test case might be a red herring, and it's actually that the inserted call to morestack is not following the ABI rules properly (in which case I'm surprised anything works at all, but...)
