### ISSUE TITLE
go/parser: documentation: fset must be non-nil

### ISSUE THREAD

**Issue by barrucadu** [golang/go#16018]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.6.2 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
~~~
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/michaelwalker/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
~~~

3. What did you do?
~~~go
package main

import (
        "go/parser"
)

func main() {
        // This file must exist, or you get an `open` error before the issue happens.
        _, _ = parser.ParseFile(nil, "foo.go", nil, 0)
        panic("Aha!")
}
~~~

4. What did you expect to see?
A panic

5. What did you see instead?
The program terminates with no output.

---

After putting this through gdb, there's a segfault happening because the first parameter I am passing in to `parser.ParseFile` is `nil`. This surprises me in two ways: firstly, I generally expect to see "Program terminated due to SIGSEGV" or something when there's a segfault, without needing to resort to a debugger; and secondly the documentation doesn't say that this is invalid.

**Comment by LordAro** [comment]
Cannot reproduce, fwiw
```

 > go version
go version go1.6.2 linux/amd64
 > go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
 > cat main.go 
package main

import (
	"go/parser"
	"runtime"
)

func main() {
	_, filename, _, _ := runtime.Caller(0) // Get itself
	_, _ = parser.ParseFile(nil, filename, nil, 0)
	panic("Aha!")
}
 > go run main.go 
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4779a3]

goroutine 1 [running]:
panic(0x51fb20, 0xc82000a110)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
go/parser.ParseFile.func1(0xc82003bf10, 0xc820001080, 0xc82003bf18)
	/usr/lib/go-1.6/src/go/parser/interface.go:96 +0x6a
panic(0x51fb20, 0xc82000a110)
	/usr/lib/go-1.6/src/runtime/panic.go:443 +0x4e9
go/token.(*FileSet).AddFile(0x0, 0x5f4d60, 0x2f, 0xffffffffffffffff, 0xb7, 0x0)
	/usr/lib/go-1.6/src/go/token/position.go:364 +0x433
go/parser.(*parser).init(0xc820001080, 0x0, 0x5f4d60, 0x2f, 0xc820086000, 0xb7, 0x2b7, 0x0)
	/usr/lib/go-1.6/src/go/parser/parser.go:74 +0x4c
go/parser.ParseFile(0x0, 0x5f4d60, 0x2f, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/go/parser/interface.go:116 +0x199
main.main()
	/home/lordaro/dev/go/src/test/parsefile/main.go:10 +0x64
exit status 2
```

**Comment by LordAro** [comment]
Regardless of the possible segfault, surely ParseFile should return an error, rather than a panic/nil pointer deref?
