### ISSUE TITLE
cmd/compile: internal compiler error: methods are too far away

### ISSUE THREAD

**Issue by dsnet** [golang/go#16037]
Using `go1.7beta1`

Consider this generator code:
```go
package main

import (
	"fmt"
	"html/template"
	"os"
)

var tmpl = template.Must(template.New("main").Parse(`
package main

type T struct {
{{range .Names}}
	{{.Name}} *string
{{end}}
}

{{range .Names}}
func (t *T) Get{{.Name}}() string {
	if t.{{.Name}} == nil {
		return ""
	}
	return *t.{{.Name}}
}
{{end}}

func main() {}
`))

func main() {
	const n = 5000

	type Name struct{ Name string }
	var t struct{ Names []Name }
	for i := 0; i < n; i++ {
		t.Names = append(t.Names, Name{Name: fmt.Sprintf("H%06X", i)})
	}
	tmpl.Execute(os.Stdout, t)
}
```

This program produces a giant struct with *n* fields, and *n* accessor methods to get at those fields and is similar to whats generated by large protobuf files.

Compiling the program produced by this generator crashes the compiler:
```
$ go run gen.go > main.go
$ go run main.go
# command-line-arguments
main.go:45011: internal compiler error: methods are too far away on T: 120008

goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/go/src/runtime/debug/stack.go:24 +0x79
cmd/compile/internal/gc.Fatalf(0x4fffff, 0x22, 0xc420c6b340, 0x2, 0x2)
	/go/src/cmd/compile/internal/gc/subr.go:165 +0x248
cmd/compile/internal/gc.dextratype(0xc420e693b0, 0x54, 0xc420c40af0, 0x1d4c8, 0x50)
	/go/src/cmd/compile/internal/gc/reflect.go:613 +0x2db
cmd/compile/internal/gc.dtypesym(0xc420c40af0, 0xc420c40af0)
	/go/src/cmd/compile/internal/gc/reflect.go:1305 +0x103b
cmd/compile/internal/gc.dtypesym(0xc420c40c30, 0xc420c6ba20)
	/go/src/cmd/compile/internal/gc/reflect.go:1278 +0xd37
cmd/compile/internal/gc.dumptypestructs()
	/go/src/cmd/compile/internal/gc/reflect.go:1363 +0xcc
cmd/compile/internal/gc.dumpobj1(0x7fff5fbff451, 0x5b, 0x3)
	/go/src/cmd/compile/internal/gc/obj.go:133 +0x553
cmd/compile/internal/gc.dumpobj()
	/go/src/cmd/compile/internal/gc/obj.go:45 +0x52
cmd/compile/internal/gc.Main()
	/go/src/cmd/compile/internal/gc/main.go:488 +0x1a5d
cmd/compile/internal/amd64.Main()
	/go/src/cmd/compile/internal/amd64/galign.go:93 +0x2fa
main.main()
	/go/src/cmd/compile/main.go:33 +0x2a3
```

This did not fail with the `Go1.6` compiler.

/cc @crawshaw @griesemer @ianlancetaylor @randall77

**Comment by dsnet** [comment]
The error was introduced in 7d469179e6e3dafe16700b7fc1cf8683ad9453fa

**Comment by ianlancetaylor** [comment]
Hmmm, this does seem to be a problem.  The overhaul of the reflection data structures assumed that all types are small.  That appears not to be the case.

**Comment by crawshaw** [comment]
Even when the offset CL series is complete in 1.8 the space needed for each struct field on amd64 will be 16-bytes, so several thousand fields will overflow a uint16. So it looks like the moff field of uncommonType needs to be 4-bytes. For alignment, mcount should probably be pushed up to 4-bytes.

I'll do this tomorrow when I'm back from vacation.
