### ISSUE TITLE
cmd/vet: panic: interface conversion: types.Type is *types.Named, not *types.Signature

### ISSUE THREAD

**Issue by mikioh** [golang/go#16143]
go version devel +1f44643.
```
go tool vet -lostcancel /go/src/net

http/h2_bundle.go:2000: the cancel function is not used on all paths (possible context leak)
http/h2_bundle.go:2005: this return statement may be reached without using the cancel var defined on line 2000
http/server.go:774: the cancelCtx function is not used on all paths (possible context leak)
http/server.go:783: this return statement may be reached without using the cancelCtx var defined on line 774
panic: interface conversion: types.Type is *types.Named, not *types.Signature

goroutine 1 [running]:
panic(0x288d60, 0xc4207d9140)
        /go/src/runtime/panic.go:500 +0x1a1
main.callName(0xc420d0bd10, 0xc420ee8500, 0xc421114120, 0x1e)
        /go/src/cmd/vet/lostcancel.go:283 +0x333
main.checkLostCancel.func2(0xc420ee8500, 0xc422634dd0)
        /go/src/cmd/vet/lostcancel.go:98 +0x34
cmd/vet/internal/cfg.(*builder).stmt(0xc421227258, 0x3efc00, 0xc4224b1110)
        /go/src/cmd/vet/internal/cfg/builder.go:43 +0x1570
cmd/vet/internal/cfg.(*builder).stmtList(0xc421227258, 0xc4214b2f00, 0xb, 0x10)
        /go/src/cmd/vet/internal/cfg/builder.go:158 +0x57
cmd/vet/internal/cfg.(*builder).stmt(0xc421227258, 0x3ef940, 0xc4224af830)
        /go/src/cmd/vet/internal/cfg/builder.go:110 +0x1485
cmd/vet/internal/cfg.(*builder).forStmt(0xc421227258, 0xc420ee8780, 0x0)
        /go/src/cmd/vet/internal/cfg/builder.go:381 +0x603
cmd/vet/internal/cfg.(*builder).stmt(0xc421227258, 0x3efc40, 0xc420ee8780)
        /go/src/cmd/vet/internal/cfg/builder.go:146 +0xd17
cmd/vet/internal/cfg.(*builder).stmtList(0xc421227258, 0xc4214b3000, 0x9, 0x10)
        /go/src/cmd/vet/internal/cfg/builder.go:158 +0x57
cmd/vet/internal/cfg.(*builder).stmt(0xc421227258, 0x3ef940, 0xc4224af860)
        /go/src/cmd/vet/internal/cfg/builder.go:110 +0x1485
cmd/vet/internal/cfg.New(0xc4224af860, 0xc422681b90, 0xc421139ca0)
        /go/src/cmd/vet/internal/cfg/cfg.go:92 +0x19c
main.checkLostCancel(0xc4206d9800, 0x3ee6c0, 0xc4224af890)
        /go/src/cmd/vet/lostcancel.go:106 +0x313
main.(*File).Visit(0xc4206d9800, 0x3ee6c0, 0xc4224af890, 0x3ed6c0, 0xc4206d9800)
        /go/src/cmd/vet/main.go:485 +0x106
go/ast.Walk(0x3ed6c0, 0xc4206d9800, 0x3ee6c0, 0xc4224af890)
        /go/src/go/ast/walk.go:52 +0x63
go/ast.walkDeclList(0x3ed6c0, 0xc4206d9800, 0xc4224ec000, 0xa7, 0x100)
        /go/src/go/ast/walk.go:38 +0x89
go/ast.Walk(0x3ed6c0, 0xc4206d9800, 0x3ee680, 0xc422471300)
        /go/src/go/ast/walk.go:353 +0x29dd
main.(*File).walkFile(0xc4206d9800, 0xc42125b490, 0xe, 0xc422471300)
        /go/src/cmd/vet/main.go:452 +0x135
main.doPackage(0xc4210d5710, 0x4, 0xc420977680, 0x1e, 0x24, 0x0)
        /go/src/cmd/vet/main.go:351 +0xbea
main.doPackageDir(0xc4210d5710, 0x4)
        /go/src/cmd/vet/main.go:281 +0x5fd
main.visit(0xc4210d5710, 0x4, 0x3f1360, 0xc420d6b2b0, 0x0, 0x0, 0x0, 0x0)
        /go/src/cmd/vet/main.go:367 +0xf3
path/filepath.walk(0xc4210d5710, 0x4, 0x3f1360, 0xc420d6b2b0, 0x2f3af0, 0x0, 0x0)
        /go/src/path/filepath/path.go:349 +0x81
path/filepath.walk(0x7fff5fbffaaf, 0x2, 0x3f1360, 0xc4200a1ba0, 0x2f3af0, 0x0, 0xc4200a1ad0)
        /go/src/path/filepath/path.go:374 +0x344
path/filepath.Walk(0x7fff5fbffaaf, 0x2, 0x2f3af0, 0xc, 0xc4200a1ad0)
        /go/src/path/filepath/path.go:396 +0xd5
main.walkDir(0x7fff5fbffaaf, 0x2)
```
/cc @alandonovan

**Comment by mikioh** [comment]
FIxed by https://go-review.googlesource.com//24325/
