### ISSUE TITLE
cmd/go: go get -u: panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by SpComb** [golang/go#16167]
1. What version of Go are you using (`go version`)?

    This also happens with go 1.6: https://github.com/golang/go/issues/14826#issuecomment-228041810

    Verified against git master, but using a custom binary patched to workaround #16165 with go 1.7 beta, which breaks git submodule clones. The issue above contains the complete diff that I used.

        go version devel +aa6345d Thu Jun 23 04:31:19 2016 +0000 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?

    ```
	GOARCH="amd64"
	GOBIN=""
	GOEXE=""
	GOHOSTARCH="amd64"
	GOHOSTOS="linux"
	GOOS="linux"
	GOPATH="/root/go"
	GORACE=""
	GOROOT="/root/src/go"
	GOTOOLDIR="/root/src/go/pkg/tool/linux_amd64"
	CC="gcc"
	GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build329298084=/tmp/go-build -gno-record-gcc-switches"
	CXX="g++"
	CGO_ENABLED="1"
    ```

3. What did you do?

    Run `go get -u` against a repo that is missing some git submodules:

    ```
	$ /root/src/go/bin/go get -v -u github.com/qmsk/e2/cmd/tally
	github.com/qmsk/e2 (download)
	github.com/jessevdk/go-flags (download)
	github.com/golang/glog (download)
	github.com/jessevdk/go-flags
	github.com/qmsk/e2/discovery
	github.com/golang/glog
	github.com/qmsk/e2/client
	github.com/qmsk/e2/vendor/github.com/kidoman/embd
	github.com/qmsk/e2/vendor/github.com/kidoman/embd/host/generic
	github.com/qmsk/e2/vendor/github.com/kidoman/embd/host/rpi
	github.com/qmsk/e2/tally
	github.com/qmsk/e2/cmd/tally
	$ cat src/github.com/qmsk/e2/.gitmodules 
	[submodule "vendor/github.com/kidoman/embd"]
		path = vendor/github.com/kidoman/embd
		url = git@github.com:SpComb/embd.git
		branch = digitalpin-exported
	$ rm -rf src/github.com/qmsk/e2/vendor/github.com/kidoman/embd/
    ```

    The original scenario for this was running the initial `go get` with missing SSH keys, causing the submodule clone to fail, and then re-running `go get -u` to fetch the missing submodules.

4. What did you expect to see?

    I would expect go get to clone the missing submodules.

5. What did you see instead?

    Go get panics, after succesfully cloning the missing vendor submodule:

    ```
	$ /root/src/go/bin/go get -v -u github.com/qmsk/e2/cmd/tally
	github.com/qmsk/e2 (download)
	github.com/jessevdk/go-flags (download)
	github.com/kidoman/embd (download)
	github.com/golang/glog (download)
	panic: runtime error: slice bounds out of range

	goroutine 1 [running]:
	panic(0x7dd7a0, 0xc420010120)
		/root/src/go/src/runtime/panic.go:500 +0x1a1
	main.vendoredImportPath(0xc4200b7680, 0xc420292de1, 0x24, 0x3, 0x0)
		/root/src/go/src/cmd/go/pkg.go:463 +0x668
	main.loadImport(0xc420292de1, 0x24, 0xc420145180, 0x47, 0xc4200b7680, 0xc42044f9f8, 0xc420292ed0, 0x1, 0x1, 0x1, ...)
		/root/src/go/src/cmd/go/pkg.go:333 +0x9ea
	main.(*Package).load(0xc4200b7680, 0xc42044f9f8, 0xc4202b8000, 0x0, 0x0, 0x4)
		/root/src/go/src/cmd/go/pkg.go:940 +0x12a5
	main.loadImport(0xc4203178c1, 0x20, 0xc420316f90, 0x25, 0xc4204f6900, 0xc42044f9f8, 0xc420317a10, 0x1, 0x1, 0x1, ...)
		/root/src/go/src/cmd/go/pkg.go:374 +0x470
	main.(*Package).load(0xc4204f6900, 0xc42044f9f8, 0xc420482380, 0x0, 0x0, 0x4)
		/root/src/go/src/cmd/go/pkg.go:940 +0x12a5
	main.loadImport(0xc42036b3e1, 0x18, 0xc420287a10, 0x29, 0xc42011bb00, 0xc42044f9f8, 0xc42028c1e0, 0x1, 0x1, 0x1, ...)
		/root/src/go/src/cmd/go/pkg.go:374 +0x470
	main.(*Package).load(0xc42011bb00, 0xc42044f9f8, 0xc4201c6a80, 0x0, 0x0, 0xc)
		/root/src/go/src/cmd/go/pkg.go:940 +0x12a5
	main.loadImport(0x7fff6d41d82d, 0x1c, 0xc420010054, 0x8, 0x0, 0xc42044f9f8, 0x0, 0x0, 0x0, 0x0, ...)
		/root/src/go/src/cmd/go/pkg.go:374 +0x470
	main.loadPackage(0x7fff6d41d82d, 0x1c, 0xc42044f9f8, 0x0)
		/root/src/go/src/cmd/go/pkg.go:1658 +0x28f
	main.packagesAndErrors(0xc4203969a0, 0x1, 0x1, 0xc420396980, 0x1c, 0x8444ad)
		/root/src/go/src/cmd/go/pkg.go:1703 +0x329
	main.packagesForBuild(0xc420396980, 0x1, 0x1, 0xc420396980, 0x1, 0x1)
		/root/src/go/src/cmd/go/pkg.go:1719 +0x75
	main.runGet(0xa20d40, 0xc420396980, 0x1, 0x1)
		/root/src/go/src/cmd/go/get.go:131 +0x318
	main.main()
		/root/src/go/src/cmd/go/main.go:181 +0x624

	$ ls -la src/github.com/qmsk/e2/vendor/github.com/kidoman/embd/
	total 120
	drwxr-xr-x 1 root root   650 Jun 23 13:50 .
	drwxr-xr-x 1 root root     8 Jun 23 13:50 ..
	-rw-r--r-- 1 root root   153 Jun 23 13:50 AUTHORS
	-rw-r--r-- 1 root root  1441 Jun 23 13:50 CONTRIBUTING.md
	-rw-r--r-- 1 root root   288 Jun 23 13:50 CONTRIBUTORS
        ....
    ```

**Comment by bradfitz** [comment]
Can you make this crash without changes to cmd/go? Otherwise this bug report can be read as "if I modify the cmd/go binary, I can make it crash", which is less compelling of a bug report than if you can crash it unmodified.

**Comment by SpComb** [comment]
The exact same repro steps work with an unmodified go 1.6.1 binary.

It does not crash with an unmodified go 1.7 beta binary, but it does not clone the vendor submodules either.

**Comment by quentinmit** [comment]
I am able to reproduce the panic with current HEAD.
