### ISSUE TITLE
Atomic operation fails on mapped memory when using -race flag

### ISSUE THREAD

**Issue by deslaughter** [golang/go#16206]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
    go version go1.6.2 windows/amd64

2. What operating system and processor architecture are you using (`go env`)?
    ```
    > go env
    set GOARCH=amd64
    set GOBIN=
    set GOEXE=.exe
    set GOHOSTARCH=amd64
    set GOHOSTOS=windows
    set GOOS=windows
    set GOPATH=C:\work\projects\armada\
    set GORACE=
    set GOROOT=c:\go
    set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
    set GO15VENDOREXPERIMENT=1
    set CC=gcc
    set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
    set CXX=g++
    set CGO_ENABLED=1
    ```

3. What did you do?

    Run the following program on Windows 10 amd64: `go run -race main.go`

   ```
    package main

    import (
        "fmt"
        "os"
        "sync/atomic"
        "syscall"
        "unsafe"
    )

    func main() {

        size := 10

        // Open file
        file, err := os.OpenFile("test.bin", os.O_CREATE|os.O_RDWR, os.ModePerm)
        if err != nil {
            return
        }
        defer file.Close()

        err = file.Truncate(int64(size))
        if err != nil {
            return
        }

        handle, err := syscall.CreateFileMapping(
            syscall.Handle(file.Fd()), nil,
            syscall.PAGE_READWRITE, 0, uint32(size), nil)
        if handle == 0 {
            return
        }
        defer syscall.Close(handle)

        addr, err := syscall.MapViewOfFile(
            handle, syscall.FILE_MAP_WRITE, 0, 0, uintptr(size))
        if addr == 0 {
            return
        }
        defer func() {
            syscall.UnmapViewOfFile(addr)
        }()

        value := (*uintptr)(unsafe.Pointer(addr))

        atomic.StoreUintptr(value, 5)

        fmt.Println("value =", *value)
    }
    ```

    Running with `go run main.go` produces `value = 5`

4. What did you expect to see?
`value = 5`

5. What did you see instead?

    ```
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xc0000005 code=0x0 addr=0x155 pc=0x45a2f2]

    goroutine 1 [running]:
    panic(0x554700, 0xc082002080)
            c:/go/src/runtime/panic.go:481 +0x40d
    sync/atomic.StoreInt64()
            c:/go/src/runtime/race_amd64.s:220 +0xc
    main.main()
            C:/work/projects/armada/src/atommem/main.go:46 +0x25f
    exit status 2
```

**Comment by josharian** [comment]
@dvyukov

**Comment by dvyukov** [comment]
Please provide a full report with `GOTRACEBACK=system` env var.
Does it crash with Go1.7 beta2?
https://golang.org/dl/#go1.7beta2

**Comment by alexbrainman** [comment]
> Please provide a full report with GOTRACEBACK=system env var.
> Does it crash with Go1.7 beta2?

It does crashes at the tip:
```
c:\dev\src\issues\issue16206>go version
go version devel +85a4f44 Tue Jun 28 22:09:00 2016 +0000 windows/amd64

c:\dev\src\issues\issue16206>go run -race main.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x15d pc=0x458ef2]

goroutine 1 [running]:
panic(0x4fa340, 0xc0420040c0)
	C:/dev/go/src/runtime/panic.go:500 +0x1bc fp=0xc042029e20 sp=0xc042029d90
runtime.panicmem()
	C:/dev/go/src/runtime/panic.go:62 +0x74 fp=0xc042029e50 sp=0xc042029e20
runtime.sigpanic()
	C:/dev/go/src/runtime/signal_windows.go:161 +0x97 fp=0xc042029e80 sp=0xc042029e50
racecallatomic()
	C:/dev/go/src/runtime/race_amd64.s:342 +0x62 fp=0xc042029e88 sp=0xc042029e80
sync/atomic.StoreInt64()
	C:/dev/go/src/runtime/race_amd64.s:234 +0xc fp=0xc042029e90 sp=0xc042029e88
main.main()
	c:/dev/src/issues/issue16206/main.go:46 +0x20d fp=0xc042029f40 sp=0xc042029e90
runtime.main()
	C:/dev/go/src/runtime/proc.go:183 +0x17b fp=0xc042029f90 sp=0xc042029f40
runtime.goexit()
	C:/dev/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc042029f98 sp=0xc042029f90

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	C:/dev/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc04201dfa8 sp=0xc04201dfa0

goroutine 2 [runnable]:
runtime.forcegchelper()
	C:/dev/go/src/runtime/proc.go:216 fp=0xc04201bfa0 sp=0xc04201bf98
runtime.goexit()
	C:/dev/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc04201bfa8 sp=0xc04201bfa0
created by runtime.init.4
	C:/dev/go/src/runtime/proc.go:213 +0x3c

goroutine 3 [GC sweep wait]:
runtime.gopark(0x51d3a0, 0xf355a0, 0x510b97, 0xd, 0x41ed14, 0x1)
	C:/dev/go/src/runtime/proc.go:259 +0x104 fp=0xc042017f18 sp=0xc042017ee8
runtime.goparkunlock(0xf355a0, 0x510b97, 0xd, 0x14, 0x1)
	C:/dev/go/src/runtime/proc.go:265 +0x65 fp=0xc042017f58 sp=0xc042017f18
runtime.bgsweep(0xc04202a000)
	C:/dev/go/src/runtime/mgcsweep.go:63 +0xc4 fp=0xc042017f98 sp=0xc042017f58
runtime.goexit()
	C:/dev/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc042017fa0 sp=0xc042017f98
created by runtime.gcenable
	C:/dev/go/src/runtime/mgc.go:195 +0x68

goroutine 4 [runnable]:
runtime.runfinq()
	C:/dev/go/src/runtime/mfinal.go:144 fp=0xc042019fa0 sp=0xc042019f98
runtime.goexit()
	C:/dev/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc042019fa8 sp=0xc042019fa0
created by runtime.createfing
	C:/dev/go/src/runtime/mfinal.go:139 +0x7a
exit status 2

c:\dev\src\issues\issue16206>
```

Alex

**Comment by davecheney** [comment]
Address 0x15d is not aligned.

**Comment by dvyukov** [comment]
Alex, please try the following patch:

```
diff --git a/src/runtime/race_amd64.s b/src/runtime/race_amd64.s
index 94ca76d..cc1d92f 100644
--- a/src/runtime/race_amd64.s
+++ b/src/runtime/race_amd64.s
@@ -338,6 +338,7 @@ racecallatomic_ignore:
        // An attempt to synchronize on the address would cause crash.
        MOVQ    AX, R15 // remember the original function
        MOVQ    $__tsan_go_ignore_sync_begin(SB), AX
+       get_tls(R12)
        MOVQ    g(R12), R14
        MOVQ    g_racectx(R14), RARG0   // goroutine context
        CALL    racecall<>(SB)
```

**Comment by alexbrainman** [comment]
> Alex, please try the following patch:

The patch fixes this problem.

Alex

**Comment by dvyukov** [comment]
Linux magically works, because `MOVQ g(R12), R14` is compiled to TLS access `mov    %fs:0xfffffffffffffff8,%r14` even without preceding `get_tls(R12)`.

**Comment by dvyukov** [comment]
Mailed https://go-review.googlesource.com/#/c/24590

**Comment by dvyukov** [comment]
However, note that even if race detector does not crash, it ignore synchronization on such external memory, so it can lead to false race reports.

**Comment by deslaughter** [comment]
@dvyukov That's an excellent point.

I thank you all for getting this resolved so quickly. Very impressive.
