### ISSUE TITLE
internal compiler error: gen_as_init couldn't make data statement

### ISSUE THREAD

**Issue by kr** [golang/go#16306]
Please answer these questions before submitting your issue. Thanks!

##### What version of Go are you using (`go version`)?

- go version go1.7rc1 darwin/amd64
- (also go version go1.6.2 darwin/amd64)

##### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/kr"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8z/b6ynlpkd5kxfb7f8zb4pxj7w0000gn/T/go-build587944134=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

##### What did you do?

https://play.golang.org/p/jC6aV8VMMm
(reproduced below)

```
go build x.go
```

```
package main

import "unsafe"

func main() {
	_ = map[unsafe.Pointer]int{unsafe.Pointer(uintptr(0)): 0}
}
```

##### What did you expect to see?

No output (successful compile).

##### What did you see instead?

```
; go build x.go 
# command-line-arguments

gen_as_init [0xc4204346c0]
.   AS u(2) l(6) tc(1) dd(2)
.   .   DOT u(2) l(6) x(0+0) tc(1) assigned main.a TUNSAFEPTR-unsafe.Pointer
.   .   .   INDEX u(2) l(6) tc(1) assigned bounded STRUCT-struct { a unsafe.Pointer; b int }
.   .   .   .   NAME-main.statictmp_1 u(1) a(true) l(6) x(0+0) class(PEXTERN) f(1) tc(1) addrtaken assigned used(true) ARRAY-[1]struct { a unsafe.Pointer; b int }
.   .   .   .   LITERAL-0 u(1) a(true) l(6) tc(1) int
.   .   LITERAL-0 l(6) tc(1) TUNSAFEPTR-unsafe.Pointer
.   .   .   LITERAL-0 l(6) tc(1) uintptr
.   .   .   .   LITERAL-0 l(6) tc(1) uintptr
./x.go:6: internal compiler error: gen_as_init couldn't make data statement

goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
cmd/compile/internal/gc.Fatalf(0x5059dd, 0x28, 0x0, 0x0, 0x0)
	/usr/local/go/src/cmd/compile/internal/gc/subr.go:165 +0x248
cmd/compile/internal/gc.gen_as_init(0xc4204346c0, 0x1, 0xc4200e8360)
	/usr/local/go/src/cmd/compile/internal/gc/sinit.go:1356 +0xb8
cmd/compile/internal/gc.(*state).stmt(0xc4200e8360, 0xc4204346c0)
	/usr/local/go/src/cmd/compile/internal/gc/ssa.go:659 +0x10f
cmd/compile/internal/gc.(*state).stmtList(0xc4200e8360, 0xc420430560)
	/usr/local/go/src/cmd/compile/internal/gc/ssa.go:542 +0x5e
cmd/compile/internal/gc.(*state).stmt(0xc4200e8360, 0xc420420d80)
	/usr/local/go/src/cmd/compile/internal/gc/ssa.go:561 +0xd1
cmd/compile/internal/gc.(*state).stmts(0xc4200e8360, 0xc420430020)
	/usr/local/go/src/cmd/compile/internal/gc/ssa.go:535 +0x5e
cmd/compile/internal/gc.buildssa(0xc420420090, 0x0)
	/usr/local/go/src/cmd/compile/internal/gc/ssa.go:182 +0x6b8
cmd/compile/internal/gc.compile(0xc420420090)
	/usr/local/go/src/cmd/compile/internal/gc/pgen.go:405 +0x1363
cmd/compile/internal/gc.funccompile(0xc420420090)
	/usr/local/go/src/cmd/compile/internal/gc/dcl.go:1287 +0x186
cmd/compile/internal/gc.Main()
	/usr/local/go/src/cmd/compile/internal/gc/main.go:467 +0x19f9
cmd/compile/internal/amd64.Main()
	/usr/local/go/src/cmd/compile/internal/amd64/galign.go:93 +0x2fa
main.main()
	/usr/local/go/src/cmd/compile/main.go:33 +0x2a3

```

**Comment by josharian** [comment]
@randall77 I see you self-assigned. Let me know if you'd like me to look, too.

**Comment by mdempsky** [comment]
Since this isn't a regression from Go 1.6, can/should we defer to Go 1.8?

**Comment by josharian** [comment]
I missed that it wasn't a regression. Yes, I think this should wait for 1.8. I'd be happy to take it, since I have lots of other sinit changes queued.

**Comment by mdempsky** [comment]
FYI, @randall77 already prepared https://go-review.googlesource.com/#/c/24836.  Not sure why @gopherbot hasn't linked it yet.
