### ISSUE TITLE
golint crashes with tip

### ISSUE THREAD

**Issue by vadmeste** [golang/go#16310]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version devel +54b499e Fri Jul 8 19:40:59 2016 +0000 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/vadmeste/work/gospace/"
GORACE=""
GOROOT="/home/vadmeste/work/gotip"
GOTOOLDIR="/home/vadmeste/work/gotip/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build556579675=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

3. What did you do?
```
$ go get github.com/golang/lint/golint # (revision c7bacac2b21ca01afa1dee0acf64df3ce047c28f)
$ go get github.com/minio/mc
$ cd $GOPATH/src/github.com/minio/mc
$ git checkout 7a21e4bb0d2c8db9a96065e883ec8336f216a380
$ golint .
```
4. What did you expect to see?
Regular results.

5. What did you see instead?
A panic

```
panic: NoColor already declared [recovered]
	panic: NoColor already declared

goroutine 1 [running]:
panic(0x6029e0, 0xc4200e8760)
	/home/vadmeste/work/gotip/src/runtime/panic.go:500 +0x1a1
go/types.(*Checker).handleBailout(0xc42046c000, 0xc4205f95e0)
	/home/vadmeste/work/gotip/src/go/types/check.go:213 +0xae
panic(0x6029e0, 0xc4200e8760)
	/home/vadmeste/work/gotip/src/runtime/panic.go:458 +0x243
golang.org/x/tools/go/gcimporter15.(*importer).declare(0xc42085c620, 0x740420, 0xc420477950)
	/home/vadmeste/work/gospace/src/golang.org/x/tools/go/gcimporter15/bimport.go:184 +0x16b
golang.org/x/tools/go/gcimporter15.(*importer).obj(0xc42085c620, 0xfffffffffffffffc)
	/home/vadmeste/work/gospace/src/golang.org/x/tools/go/gcimporter15/bimport.go:204 +0x1bd
golang.org/x/tools/go/gcimporter15.BImportData(0xc420169cc0, 0xc420462ab0, 0xc4206be000, 0xa739, 0xfe00, 0xc4200e4021, 0x16, 0x31, 0x40c2b4, 0x62f700, ...)
	/home/vadmeste/work/gospace/src/golang.org/x/tools/go/gcimporter15/bimport.go:97 +0x3e8
golang.org/x/tools/go/gcimporter15.Import(0xc420462ab0, 0xc4200e4021, 0x16, 0x64a264, 0x1, 0xc4208aeeb0, 0x0, 0x0)
	/home/vadmeste/work/gospace/src/golang.org/x/tools/go/gcimporter15/gcimporter.go:178 +0x5da
github.com/golang/lint.importer.ImportFrom(0x66b318, 0xc420462ab0, 0xc4200e4021, 0x16, 0x64a264, 0x1, 0x0, 0x628660, 0x2f88c801, 0x7f6b38893900)
	/home/vadmeste/work/gospace/src/github.com/golang/lint/lint16.go:16 +0x58
github.com/golang/lint.(*importer).ImportFrom(0xc42045f950, 0xc4200e4021, 0x16, 0x64a264, 0x1, 0x0, 0xc4204edea0, 0x0, 0x0)
	<autogenerated>:5 +0x97
go/types.(*Checker).collectObjects(0xc42046c000)
	/home/vadmeste/work/gotip/src/go/types/resolver.go:191 +0x81d
go/types.(*Checker).checkFiles(0xc42046c000, 0xc420058800, 0x48, 0x80, 0x0, 0x0)
	/home/vadmeste/work/gotip/src/go/types/check.go:225 +0xaa
go/types.(*Checker).Files(0xc42046c000, 0xc420058800, 0x48, 0x80, 0xc420462ba0, 0xc420058800)
	/home/vadmeste/work/gotip/src/go/types/check.go:218 +0x49
go/types.(*Config).Check(0xc420466ec0, 0xc420335190, 0x4, 0xc420147840, 0xc420058800, 0x48, 0x80, 0xc420455a40, 0xc420465e40, 0x18, ...)
	/home/vadmeste/work/gotip/src/go/types/api.go:344 +0x19f
github.com/golang/lint.(*pkg).typeCheck(0xc420126550, 0xbf0000000044f3f0, 0x8)
	/home/vadmeste/work/gospace/src/github.com/golang/lint/lint.go:274 +0x403
github.com/golang/lint.(*pkg).lint(0xc420126550, 0xc42014baa0, 0xc42021d918, 0xc42021d910)
	/home/vadmeste/work/gospace/src/github.com/golang/lint/lint.go:130 +0x40
github.com/golang/lint.(*Linter).LintFiles(0xc4205f9a40, 0xc4205f9ae0, 0xc42003fab8, 0xc42003fac8, 0x510, 0x0, 0x0)
	/home/vadmeste/work/gospace/src/github.com/golang/lint/lint.go:110 +0x6e7
main.lintFiles(0xc42009b000, 0x48, 0x80)
	/home/vadmeste/work/gospace/src/github.com/golang/lint/golint/golint.go:92 +0x234
main.lintImportedPackage(0xc420071500, 0x0, 0x0)
	/home/vadmeste/work/gospace/src/github.com/golang/lint/golint/golint.go:136 +0x364
main.lintDir(0x7ffc172560bb, 0x1)
	/home/vadmeste/work/gospace/src/github.com/golang/lint/golint/golint.go:107 +0x60
main.main()
	/home/vadmeste/work/gospace/src/github.com/golang/lint/golint/golint.go:52 +0x333
```

**Comment by griesemer** [comment]
@vadmeste I cannot reproduce this at tip. This is very likely due to a bug that has been fixed quite a while back. You may have installed packages that are not compiled with the latest version of the compiler. Please rebuild all your sources with the compiler at tip and let me know if you can still cause this error. Thanks.

**Comment by ianlancetaylor** [comment]
Timed out.

Please comment if you have an answer to the question above.

**Comment by vadmeste** [comment]
Sorry for the delay, @griesemer it works fine now. Thanks
