### ISSUE TITLE
x/exp/shiny/example/basic: go run main.go hanges on windows

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#16341]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

`go version devel +29f0984 Fri Jul 1 01:12:24 2016 +0000 windows/386`

2. What operating system and processor architecture are you using (`go env`)?

```
set GOARCH=386
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=c:\dev
set GORACE=
set GOROOT=c:\dev\go
set GOTOOLDIR=c:\dev\go\pkg\tool\windows_386
set CC=gcc
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\DOCUME~1\brainman\LOCALS~1\Temp\go-build024791586=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
```

3. What did you do?

```
C:\dev\src\golang.org\x\exp\shiny\example\basic>git rev-parse HEAD
a16ab4a434a95ebed3f8c4b58b88bcc2b1fa64b2

C:\dev\src\golang.org\x\exp\shiny\example\basic>go run main.go
```

4. What did you expect to see?

I expect to see new window open on my screen, and so on.

5. What did you see instead?

Nothing. Program just hangs.

Alex

**Comment by mattn** [comment]
I got different behavior on windows10.

```
c:\dev\go\src\golang.org\x\exp\shiny\example\basic>git rev-parse HEAD
a16ab4a434a95ebed3f8c4b58b88bcc2b1fa64b2

c:\dev\go\src\golang.org\x\exp\shiny\example\basic>go run main.go

got lifecycle.Event{From:StageDead, To:StageVisible, DrawContext:<nil>}
got lifecycle.Event{From:StageVisible, To:StageFocused, DrawContext:<nil>}
got size.Event{WidthPx:944, HeightPx:687, WidthPt:944, HeightPt:687, PixelsPerPt:1, Orientation:0}
got paint.Event{External:false}
panic: TODO: implement

goroutine 18 [running]:
panic(0x4cfac0, 0xc0420041a0)
	C:/go/src/runtime/panic.go:500 +0x1af
golang.org/x/exp/shiny/driver/windriver.(*windowImpl).DrawUniform(0xc042082000, 0x3fdbb67ae8584caa, 0xbfe0000000000000, 0x4059000000000000, 0x3fd0000000000000, 0x3febb67ae8584caa, 0x4069000000000000, 0x565720, 0xc042004198, 0x1e, ...)
	c:/dev/go/src/golang.org/x/exp/shiny/driver/windriver/window.go:81 +0x74
main.main.func1(0x565f60, 0x577120)
	c:/dev/go/src/golang.org/x/exp/shiny/example/basic/main.go:114 +0xcf3
golang.org/x/exp/shiny/driver/windriver.Main.func1()
	c:/dev/go/src/golang.org/x/exp/shiny/driver/windriver/windriver.go:22 +0x44
golang.org/x/exp/shiny/driver/internal/win32.screenWindowWndProc.func1()
	c:/dev/go/src/golang.org/x/exp/shiny/driver/internal/win32/win32.go:279 +0x30
created by golang.org/x/exp/shiny/driver/internal/win32.screenWindowWndProc
	c:/dev/go/src/golang.org/x/exp/shiny/driver/internal/win32/win32.go:281 +0x17e
exit status 2
```

**Comment by alexbrainman** [comment]
> I got different behavior on windows10.

I see what you see on my Windows 7 computer. But on my Windows XP computer it just hangs.

Alex

**Comment by mattn** [comment]
Okay, now I can try this on Windows7. Will update this comment in later.

**Comment by alexbrainman** [comment]
> Seems to be occur on WindowsXP.

I think it is matter of luck when it works and when it does not. But this https://go-review.googlesource.com/#/c/24921/ fixes my problem.

Alex
