### ISSUE TITLE
Unable to build go project on macOS 10.12 beta 4

### ISSUE THREAD

**Issue by DefinitelyCarter** [golang/go#16575]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
```go version go1.6.3 darwin/amd64```

2. What operating system and processor architecture are you using (`go env`)?
```GOARCH="amd64"
GOBIN="/Users/adamcarter/Projects/Go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/adamcarter/Projects/Go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

3. What did you do?
Try to build a go project `go build -o ./api/bin/api ./api/api.go`

4. What did you expect to see?
A successful build

5. What did you see instead?
The following panic
```
fatal error: unexpected signal during runtime execution
[signal 0xa code=0x2 addr=0x12946dfda82 pc=0xf0eb]

runtime stack:
runtime.throw(0x4971c0, 0x2a)
	/usr/local/go/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.unlock(0x982540)
	/usr/local/go/src/runtime/lock_sema.go:107 +0x14b
runtime.(*mheap).alloc_m(0x982540, 0x8, 0x100000000, 0x983f80)
	/usr/local/go/src/runtime/mheap.go:492 +0x314
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0xc820039ee0)
	/usr/local/go/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x982540, 0x8, 0x10100000000, 0x149cc)
	/usr/local/go/src/runtime/mheap.go:503 +0x63
runtime.largeAlloc(0xe968, 0x0, 0x11)
	/usr/local/go/src/runtime/malloc.go:766 +0xb3
runtime.mallocgc.func3()
	/usr/local/go/src/runtime/malloc.go:664 +0x33
runtime.systemstack(0xc820001b40)
	/usr/local/go/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1051

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:245 fp=0xc820cbb0b8 sp=0xc820cbb0b0
runtime.mallocgc(0xe968, 0x428dc0, 0xc800000000, 0x6a774)
	/usr/local/go/src/runtime/malloc.go:665 +0x9eb fp=0xc820cbb190 sp=0xc820cbb0b8
runtime.newarray(0x428dc0, 0x2a7, 0xc820d80540)
	/usr/local/go/src/runtime/malloc.go:798 +0xc9 fp=0xc820cbb1d0 sp=0xc820cbb190
runtime.makeslice(0x3b02a0, 0x2a7, 0x2a7, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/slice.go:32 +0x165 fp=0xc820cbb220 sp=0xc820cbb1d0
cmd/compile/internal/gc.Flowstart(0xc820d5a360, 0x4c4758, 0x20)
	/usr/local/go/src/cmd/compile/internal/gc/popt.go:271 +0x298 fp=0xc820cbb330 sp=0xc820cbb220
cmd/compile/internal/gc.regopt(0xc820d5a360)
	/usr/local/go/src/cmd/compile/internal/gc/reg.go:1064 +0x3d0 fp=0xc820cbb7e8 sp=0xc820cbb330
cmd/compile/internal/gc.compile(0xc820203b90)
	/usr/local/go/src/cmd/compile/internal/gc/pgen.go:521 +0xe6d fp=0xc820cbba58 sp=0xc820cbb7e8
cmd/compile/internal/gc.funccompile(0xc820203b90)
	/usr/local/go/src/cmd/compile/internal/gc/dcl.go:1450 +0x1c0 fp=0xc820cbbad0 sp=0xc820cbba58
cmd/compile/internal/gc.Main()
	/usr/local/go/src/cmd/compile/internal/gc/lex.go:472 +0x2116 fp=0xc820cbbdf0 sp=0xc820cbbad0
cmd/compile/internal/amd64.Main()
	/usr/local/go/src/cmd/compile/internal/amd64/galign.go:127 +0x58d fp=0xc820cbbe58 sp=0xc820cbbdf0
main.main()
	/usr/local/go/src/cmd/compile/main.go:32 +0x395 fp=0xc820cbbf30 sp=0xc820cbbe58
runtime.main()
	/usr/local/go/src/runtime/proc.go:188 +0x2b0 fp=0xc820cbbf80 sp=0xc820cbbf30
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820cbbf88 sp=0xc820cbbf80
```

**Comment by bradfitz** [comment]
Dup of #16570
