### ISSUE TITLE
Can't build go on MacOS 10.12 public beta 3

### ISSUE THREAD

**Issue by dozer47528** [golang/go#16583]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
1.6.3 & 1.7rc5

2. What operating system and processor architecture are you using (`go env`)?
MacOS 10.12 public beta 3

3. What did you do?
`brew install go`
`brew install go --devel`

4. What did you expect to see?
Install successfully.

5. What did you see instead?
````
brew install go --without-race --without-vet --without-godoc --without-cgo --devel
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.


You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
==> Downloading https://storage.googleapis.com/golang/go1.7rc5.src.tar.gz
Already downloaded: /Users/dozer/Library/Caches/Homebrew/go-1.7rc5.tar.gz
==> Downloading https://storage.googleapis.com/golang/go1.4.2.darwin-amd64-osx10.8.tar.gz
Already downloaded: /Users/dozer/Library/Caches/Homebrew/go--gobootstrap-10.8.tar.gz
==> ./make.bash --no-clean
==> ./make.bash --no-clean
Last 15 lines from /Users/dozer/Library/Logs/Homebrew/go/02.make.bash:
	/private/tmp/go-20160803-15120-15sdxep/go/src/cmd/dist/build.go:512 +0x205
created by main.cmdbootstrap
	/private/tmp/go-20160803-15120-15sdxep/go/src/cmd/dist/build.go:1063 +0x7a4

goroutine 68 [chan receive]:
main.install(0x1b6070, 0xd)
	/private/tmp/go-20160803-15120-15sdxep/go/src/cmd/dist/build.go:512 +0x205
created by main.cmdbootstrap
	/private/tmp/go-20160803-15120-15sdxep/go/src/cmd/dist/build.go:1063 +0x7a4

goroutine 69 [chan receive]:
main.install(0x1b6090, 0xc)
	/private/tmp/go-20160803-15120-15sdxep/go/src/cmd/dist/build.go:512 +0x205
created by main.cmdbootstrap
	/private/tmp/go-20160803-15120-15sdxep/go/src/cmd/dist/build.go:1063 +0x7a4
````

**Comment by odeke-em** [comment]
Probably related to https://github.com/golang/go/issues/16570.
@dozer47528 could you try getting beta 5 from  https://golang.org/dl/#go1.7rc5 and testing with that?

**Comment by davecheney** [comment]
The problem is the 1.4.2 image that brew is using as the bootstrap image
does not have the sierra fix.

@dozer, the workaround for you is to install go 1.7rc5 from the website
rather than brew until we can roll a 1.4.x version that has the fix.

**Comment by bradfitz** [comment]
Dup of #16352
