### ISSUE TITLE
Encountering strange build stack trace when running go build

### ISSUE THREAD

**Issue by zg** [golang/go#16627]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
`Go version go1.6.3 darwin/amd64`

2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/zg/work"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.6.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.6.3/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```
3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

I tried to run `go build gitHub.com/sn/service/router` and a huge stack trace spit out. After running the command again, it was successful without any issues.

4. What did you expect to see?
I expected to see the build succeed without any issues on the internals of Go itself.

5. What did you see instead?
I saw a stack trace that was unrecognizable.

Is there some kind of caching mechanism involved that has to be cleared? When I run `go clean` and then try doing `go build` again, things build fine.

Here is the stack trace:
```
$ go clean && go test github.com/sn/service/router | tee out
# testmain
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x14233b9aa4e2 pc=0xf47b]

runtime stack:
runtime.throw(0x2c4920, 0x2a)
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.unlock(0x3a70a0)
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/lock_sema.go:107 +0x14b
runtime.(*mheap).alloc_m(0x3a70a0, 0x1, 0x40000000012, 0x71fff0)
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/mheap.go:492 +0x314
runtime.(*mheap).alloc.func1()
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0xc820039e58)
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x3a70a0, 0x1, 0x10000000012, 0xf11f)
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/mheap.go:503 +0x63
runtime.(*mcentral).grow(0x3a8b50, 0x0)
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/mcentral.go:209 +0x93
runtime.(*mcentral).cacheSpan(0x3a8b50, 0x71fff0)
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/mcentral.go:89 +0x47d
runtime.(*mcache).refill(0x402000, 0xc800000012, 0x71fff0)
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/mcache.go:119 +0xcc
runtime.mallocgc.func2()
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:642 +0x2b
runtime.systemstack(0xc82001d500)
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:1051

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:245 fp=0xc82003e9d0 sp=0xc82003e9c8
runtime.mallocgc(0x120, 0x25c4c0, 0xc800000000, 0xc820072240)
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:643 +0x869 fp=0xc82003eaa8 sp=0xc82003e9d0
runtime.newarray(0x25c4c0, 0x6, 0x152a68)
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:798 +0xc9 fp=0xc82003eae8 sp=0xc82003eaa8
runtime.makeslice(0x1e67a0, 0x6, 0x6, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/slice.go:32 +0x165 fp=0xc82003eb38 sp=0xc82003eae8
cmd/link/internal/ld.readsym(0xc820072240, 0xc82379db00, 0xc821925fe0, 0x7, 0xc8237a4c80, 0x45)
        /usr/local/Cellar/go/1.6.3/libexec/src/cmd/link/internal/ld/objfile.go:239 +0xba6 fp=0xc82003ef80 sp=0xc82003eb38
cmd/link/internal/ld.ldobjfile(0xc820072240, 0xc82379db00, 0xc821925fe0, 0x7, 0x8e007, 0xc8237a4c80, 0x45)
        /usr/local/Cellar/go/1.6.3/libexec/src/cmd/link/internal/ld/objfile.go:147 +0xa62 fp=0xc82003f190 sp=0xc82003ef80
cmd/link/internal/ld.ldobj(0xc82379db00, 0xc821925fe0, 0x7, 0x8e030, 0xc8237a4c80, 0x45, 0xc821919ac0, 0x3d, 0x1, 0x0)
        /usr/local/Cellar/go/1.6.3/libexec/src/cmd/link/internal/ld/lib.go:1351 +0x1569 fp=0xc82003f400 sp=0xc82003f190
cmd/link/internal/ld.objfile(0xc820abca10)
        /usr/local/Cellar/go/1.6.3/libexec/src/cmd/link/internal/ld/lib.go:847 +0x10d9 fp=0xc82003f710 sp=0xc82003f400
cmd/link/internal/ld.loadlib()
        /usr/local/Cellar/go/1.6.3/libexec/src/cmd/link/internal/ld/lib.go:513 +0x5ce fp=0xc82003f9f0 sp=0xc82003f710
cmd/link/internal/ld.Ldmain()
        /usr/local/Cellar/go/1.6.3/libexec/src/cmd/link/internal/ld/pobj.go:214 +0x1cd3 fp=0xc82003fe70 sp=0xc82003f9f0
cmd/link/internal/amd64.Main()
        /usr/local/Cellar/go/1.6.3/libexec/src/cmd/link/internal/amd64/obj.go:44 +0x19 fp=0xc82003fe78 sp=0xc82003fe70
main.main()
        /usr/local/Cellar/go/1.6.3/libexec/src/cmd/link/main.go:27 +0x36f fp=0xc82003ff50 sp=0xc82003fe78
runtime.main()
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:188 +0x2b0 fp=0xc82003ffa0 sp=0xc82003ff50
runtime.goexit()
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82003ffa8 sp=0xc82003ffa0
FAIL    github.com/sn/service/router [build failed]

```

**Comment by davecheney** [comment]
Can you please post the full output from the first failure.

**Comment by zg** [comment]
Yes, I've attached it at the bottom. Not sure what happened to my clipboard, but it's there now.

**Comment by davecheney** [comment]
Looks like your test program is crashing, you can confirm this with
```
% go test -c
% ./router.test
```
This is most likely due to a data race, which can be verified with
```
% go test -race
```
or
```
% go test -c -race
% ./router.test
```

**Comment by zg** [comment]
How does adding the `-race` flag verify that there is a race? I'm just seeing the same error again.

```
$ go test -c -race                                                                                                                                                                                          [3/171]
# testmain
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x15820bc54210 pc=0xf47b]

runtime stack:
runtime.throw(0x2c4920, 0x2a)
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.unlock(0x3a70a0)
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/lock_sema.go:107 +0x14b
runtime.(*mheap).alloc_m(0x3a70a0, 0x1, 0x1a, 0x778798)
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/mheap.go:492 +0x314
runtime.(*mheap).alloc.func1()
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0xc82044de58)
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x3a70a0, 0x1, 0x1000000001a, 0xf11f)
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/mheap.go:503 +0x63
runtime.(*mcentral).grow(0x3a8ed0, 0x0)
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/mcentral.go:209 +0x93
runtime.(*mcentral).cacheSpan(0x3a8ed0, 0x769ee8)
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/mcentral.go:89 +0x47d
runtime.(*mcache).refill(0x402e10, 0x1a, 0x769ee8)
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/mcache.go:119 +0xcc
runtime.mallocgc.func2()
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:642 +0x2b
runtime.systemstack(0xc820020000)
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:1051

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:245 fp=0xc82003e9d0 sp=0xc82003e9c8
runtime.mallocgc(0x240, 0x25c4c0, 0xc800000000, 0xc820086240)
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:643 +0x869 fp=0xc82003eaa8 sp=0xc82003e9d0
runtime.newarray(0x25c4c0, 0xb, 0x152a68)
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:798 +0xc9 fp=0xc82003eae8 sp=0xc82003eaa8
runtime.makeslice(0x1e67a0, 0xb, 0xb, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/slice.go:32 +0x165 fp=0xc82003eb38 sp=0xc82003eae8
cmd/link/internal/ld.readsym(0xc820086240, 0xc8250eb1c0, 0xc821ac9540, 0xd, 0xc8259b5450, 0x50)
        /usr/local/Cellar/go/1.6.3/libexec/src/cmd/link/internal/ld/objfile.go:239 +0xba6 fp=0xc82003ef80 sp=0xc82003eb38
cmd/link/internal/ld.ldobjfile(0xc820086240, 0xc8250eb1c0, 0xc821ac9540, 0xd, 0xab5f, 0xc8259b5450, 0x50)
        /usr/local/Cellar/go/1.6.3/libexec/src/cmd/link/internal/ld/objfile.go:147 +0xa62 fp=0xc82003f190 sp=0xc82003ef80
cmd/link/internal/ld.ldobj(0xc8250eb1c0, 0xc821ac9540, 0xd, 0xab88, 0xc8259b5450, 0x50, 0xc82307ff90, 0x48, 0x1, 0x0)
        /usr/local/Cellar/go/1.6.3/libexec/src/cmd/link/internal/ld/lib.go:1351 +0x1569 fp=0xc82003f400 sp=0xc82003f190
cmd/link/internal/ld.objfile(0xc8230571f0)
        /usr/local/Cellar/go/1.6.3/libexec/src/cmd/link/internal/ld/lib.go:847 +0x10d9 fp=0xc82003f710 sp=0xc82003f400
cmd/link/internal/ld.loadlib()
        /usr/local/Cellar/go/1.6.3/libexec/src/cmd/link/internal/ld/lib.go:513 +0x5ce fp=0xc82003f9f0 sp=0xc82003f710
cmd/link/internal/ld.Ldmain()
        /usr/local/Cellar/go/1.6.3/libexec/src/cmd/link/internal/ld/pobj.go:214 +0x1cd3 fp=0xc82003fe70 sp=0xc82003f9f0
cmd/link/internal/amd64.Main()
        /usr/local/Cellar/go/1.6.3/libexec/src/cmd/link/internal/amd64/obj.go:44 +0x19 fp=0xc82003fe78 sp=0xc82003fe70
main.main()
        /usr/local/Cellar/go/1.6.3/libexec/src/cmd/link/main.go:27 +0x36f fp=0xc82003ff50 sp=0xc82003fe78
runtime.main()
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:188 +0x2b0 fp=0xc82003ffa0 sp=0xc82003ff50
runtime.goexit()
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82003ffa8 sp=0xc82003ffa0
```

**Comment by bradfitz** [comment]
This isn't a failure in go build as the title suggests. I agree with Dave that this is probably a test failure due to a race. Closing until there's something we can do.

**Comment by bradfitz** [comment]
Oh this is in the linker. Just read the stack.

**Comment by bradfitz** [comment]
Can you try Go 1.7?

**Comment by zg** [comment]
@bradfitz: No problem - it is Saturday. 😄 I upgraded to Go 1.7rc5 using `brew upgrade go --devel` and the problem doesn't arise.

@davecheney: Yep, I'm on macOS Sierra (10.12 Beta).

**Comment by davecheney** [comment]
Your Brew instance is 1.6.3, I think that doesn't have the fix.

I recommend switching to the official release from golang.org.

**Comment by zg** [comment]
Which commit on golang/go has the fix?

**Comment by davecheney** [comment]
It's in 1.7rc5, it's not been backported to other branches yet sorry.

**Comment by bradfitz** [comment]
Dup of #16352 / #16570
