### ISSUE TITLE
panic issues with go get

### ISSUE THREAD

**Issue by s7v7nislands** [golang/go#16634]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

> go version go1.6.3 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN="/Users/s7v7nislands/source/gocode/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/s7v7nislands/source/gocode"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.6.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.6.3/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```
3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

> go get github.com/sourcegraph/checkup

4. What did you expect to see?

> install checkup package

5. What did you see instead?
```
# github.com/aws/aws-sdk-go/vendor/github.com/jmespath/go-jmespath
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x4a354f566ae pc=0xf0eb]

runtime stack:
runtime.throw(0x4971e0, 0x2a)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.unlock(0x984540)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/lock_sema.go:107 +0x14b
runtime.(*mheap).alloc_m(0x984540, 0x1, 0x12, 0xb7da58)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/mheap.go:492 +0x314
runtime.(*mheap).alloc.func1()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0xc820039e58)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x984540, 0x1, 0x10000000012, 0xed8f)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/mheap.go:503 +0x63
runtime.(*mcentral).grow(0x985ff0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/mcentral.go:209 +0x93
runtime.(*mcentral).cacheSpan(0x985ff0, 0xc82000c1b0)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/mcentral.go:89 +0x47d
runtime.(*mcache).refill(0xaf6000, 0xc800000012, 0xc8217e4960)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/mcache.go:119 +0xcc
runtime.mallocgc.func2()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:642 +0x2b
runtime.systemstack(0xc820001b40)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:1051

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:245 fp=0xc8217e42e8 sp=0xc8217e42e0
runtime.mallocgc(0x120, 0x42e1a0, 0x0, 0xc821affe60)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:643 +0x869 fp=0xc8217e43c0 sp=0xc8217e42e8
runtime.newobject(0x42e1a0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:781 +0x42 fp=0xc8217e43e8 sp=0xc8217e43c0
cmd/compile/internal/gc.Prog(0x31ba, 0xc821afbb90)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/compile/internal/gc/gsubr.go:117 +0x58 fp=0xc8217e4450 sp=0xc8217e43e8
cmd/compile/internal/amd64.gins(0x31ba, 0xc821afbdd0, 0xc821afbb90, 0xc821affd40)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/compile/internal/amd64/gsubr.go:636 +0xf6 fp=0xc8217e4530 sp=0xc8217e4450
cmd/compile/internal/amd64.gmove(0xc821afbdd0, 0xc821afbb90)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/compile/internal/amd64/gsubr.go:540 +0x501 fp=0xc8217e46b0 sp=0xc8217e4530
cmd/compile/internal/amd64.gmove(0xc821afbc20, 0xc821afbb90)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/compile/internal/amd64/gsubr.go:561 +0x36e fp=0xc8217e4830 sp=0xc8217e46b0
cmd/compile/internal/gc.componentgen_wb.func4(0xc82008c5a0, 0x10, 0x437901)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/compile/internal/gc/gen.go:1147 +0x285 fp=0xc8217e48d8 sp=0xc8217e4830
cmd/compile/internal/gc.visitComponents(0xc8208b3950, 0x8, 0xc8217e4a80, 0xc8217e4901)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/compile/internal/gc/gen.go:1199 +0x5a1 fp=0xc8217e4918 sp=0xc8217e48d8
cmd/compile/internal/gc.visitComponents(0xc8208b34a0, 0x0, 0xc8217e4a80, 0x1)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/compile/internal/gc/gen.go:1240 +0x506 fp=0xc8217e4958 sp=0xc8217e4918
cmd/compile/internal/gc.componentgen_wb(0xc8207614d0, 0xc821a09170, 0x3100, 0xc821afaf00)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/compile/internal/gc/gen.go:1149 +0xa1c fp=0xc8217e4ad0 sp=0xc8217e4958
cmd/compile/internal/gc.sgen_wb(0xc8207614d0, 0xc821a09170, 0x30, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/compile/internal/gc/cgen.go:2274 +0x459 fp=0xc8217e4bc8 sp=0xc8217e4ad0
cmd/compile/internal/gc.cgen_wb(0xc8207614d0, 0xc821a09170, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/compile/internal/gc/cgen.go:85 +0x427 fp=0xc8217e4f98 sp=0xc8217e4bc8
cmd/compile/internal/gc.Cgen_as_wb(0xc821a09170, 0xc8207614d0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/compile/internal/gc/gen.go:935 +0x166 fp=0xc8217e4ff8 sp=0xc8217e4f98
cmd/compile/internal/gc.Cgen_as(0xc821a09170, 0xc8207614d0)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/compile/internal/gc/gen.go:886 +0x30 fp=0xc8217e5018 sp=0xc8217e4ff8
cmd/compile/internal/gc.gen(0xc821a09200)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/compile/internal/gc/gen.go:833 +0x191 fp=0xc8217e5170 sp=0xc8217e5018
cmd/compile/internal/gc.Genlist(0xc821a046a0)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/compile/internal/gc/gen.go:215 +0x30 fp=0xc8217e5180 sp=0xc8217e5170
cmd/compile/internal/gc.cgen_call(0xc821afb8c0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/compile/internal/gc/cgen.go:2526 +0xae fp=0xc8217e51c0 sp=0xc8217e5180
cmd/compile/internal/gc.cgen_callmeth(0xc820772870, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/compile/internal/gc/gen.go:956 +0x16b fp=0xc8217e5238 sp=0xc8217e51c0
cmd/compile/internal/gc.gen(0xc820772870)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/compile/internal/gc/gen.go:842 +0x389 fp=0xc8217e5390 sp=0xc8217e5238
cmd/compile/internal/gc.Genlist(0xc821a04720)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/compile/internal/gc/gen.go:215 +0x30 fp=0xc8217e53a0 sp=0xc8217e5390
cmd/compile/internal/gc.gen(0xc821a09710)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/compile/internal/gc/gen.go:655 +0x41a fp=0xc8217e54f8 sp=0xc8217e53a0
cmd/compile/internal/gc.Genlist(0xc821842b40)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/compile/internal/gc/gen.go:215 +0x30 fp=0xc8217e5508 sp=0xc8217e54f8
cmd/compile/internal/gc.gen(0xc8207721b0)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/compile/internal/gc/gen.go:782 +0xd30 fp=0xc8217e5660 sp=0xc8217e5508
cmd/compile/internal/gc.Genlist(0xc821842b80)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/compile/internal/gc/gen.go:215 +0x30 fp=0xc8217e5670 sp=0xc8217e5660
cmd/compile/internal/gc.gen(0xc820761b00)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/compile/internal/gc/gen.go:800 +0x1290 fp=0xc8217e57c8 sp=0xc8217e5670
cmd/compile/internal/gc.Genlist(0xc821842e60)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/compile/internal/gc/gen.go:215 +0x30 fp=0xc8217e57d8 sp=0xc8217e57c8
cmd/compile/internal/gc.compile(0xc820761680)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/compile/internal/gc/pgen.go:484 +0xc02 fp=0xc8217e5a48 sp=0xc8217e57d8
cmd/compile/internal/gc.funccompile(0xc820761680)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/compile/internal/gc/dcl.go:1450 +0x1c0 fp=0xc8217e5ac0 sp=0xc8217e5a48
cmd/compile/internal/gc.Main()
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/compile/internal/gc/lex.go:472 +0x2116 fp=0xc8217e5de0 sp=0xc8217e5ac0
cmd/compile/internal/amd64.Main()
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/compile/internal/amd64/galign.go:127 +0x58d fp=0xc8217e5e48 sp=0xc8217e5de0
main.main()
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/compile/main.go:32 +0x395 fp=0xc8217e5f20 sp=0xc8217e5e48
runtime.main()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:188 +0x2b0 fp=0xc8217e5f70 sp=0xc8217e5f20
runtime.goexit()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8217e5f78 sp=0xc8217e5f70
```

**Comment by davecheney** [comment]
Have you recently upgraded your system to the macOS Sierra beta ?

**Comment by s7v7nislands** [comment]
yes.

```
$ uname -a
Darwin s7v7nislandss-MacBook.local 16.0.0 Darwin Kernel Version 16.0.0: Tue Jul 26 18:32:56 PDT 2016; root:xnu-3789.1.4.1.1~1/RELEASE_X86_64 x86_64
```

**Comment by davecheney** [comment]
You need to use go1.7rc5 or later. I recommend using the version from the
golang.org website.

**Comment by bradfitz** [comment]
Dup of #16352 and #16570
