### ISSUE TITLE
Build interrupted with panic and segmentation fault on OS X Sierra 

### ISSUE THREAD

**Issue by Gufran** [golang/go#16669]
1. What version of Go are you using (`go version`)?
go1.6.2 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
```
→ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/Gufran/Workspace/Go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.6.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.6.2/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

3. What did you do?
Run `go build` on any valid go program.

4. What did you expect to see?
Build finished successfully and an executable binary produced.

5. What did you see instead?

Sometimes

```
→ go build main.go
# command-line-arguments
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0xdcbaa08fdee pc=0xf47b]

runtime stack:
runtime.throw(0x2c4920, 0x2a)
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.unlock(0x3a70a0)
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/lock_sema.go:107 +0x14b
runtime.(*mheap).alloc_m(0x3a70a0, 0x1, 0x15, 0x5b7968)
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/mheap.go:492 +0x314
runtime.(*mheap).alloc.func1()
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0x7fff5fbfea38)
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x3a70a0, 0x1, 0x10000000015, 0xf11f)
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/mheap.go:503 +0x63
runtime.(*mcentral).grow(0x3a8ca0, 0x0)
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/mcentral.go:209 +0x93
runtime.(*mcentral).cacheSpan(0x3a8ca0, 0x5b7968)
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/mcentral.go:89 +0x47d
runtime.(*mcache).refill(0x4032c0, 0xc800000015, 0x5b7968)
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/mcache.go:119 +0xcc
runtime.mallocgc.func2()
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/malloc.go:642 +0x2b
runtime.systemstack(0x3a0700)
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/proc.go:1051

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:245 fp=0xc8200429d0 sp=0xc8200429c8
runtime.mallocgc(0x180, 0x25c4c0, 0xc800000000, 0xc820084240)
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/malloc.go:643 +0x869 fp=0xc820042aa8 sp=0xc8200429d0
runtime.newarray(0x25c4c0, 0x8, 0x152a58)
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/malloc.go:798 +0xc9 fp=0xc820042ae8 sp=0xc820042aa8
runtime.makeslice(0x1e67a0, 0x8, 0x8, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/slice.go:32 +0x165 fp=0xc820042b38 sp=0xc820042ae8
cmd/link/internal/ld.readsym(0xc820084240, 0xc8220dc0e0, 0xc820949756, 0x4, 0xc8220153b0, 0x42)
        /usr/local/Cellar/go/1.6.2/libexec/src/cmd/link/internal/ld/objfile.go:239 +0xba6 fp=0xc820042f80 sp=0xc820042b38
cmd/link/internal/ld.ldobjfile(0xc820084240, 0xc8220dc0e0, 0xc820949756, 0x4, 0x1b364, 0xc8220153b0, 0x42)
        /usr/local/Cellar/go/1.6.2/libexec/src/cmd/link/internal/ld/objfile.go:147 +0xa62 fp=0xc820043190 sp=0xc820042f80
cmd/link/internal/ld.ldobj(0xc8220dc0e0, 0xc820949756, 0x4, 0x1b38d, 0xc8220153b0, 0x42, 0xc820df4ac0, 0x3a, 0x1, 0x0)
        /usr/local/Cellar/go/1.6.2/libexec/src/cmd/link/internal/ld/lib.go:1351 +0x1569 fp=0xc820043400 sp=0xc820043190
cmd/link/internal/ld.objfile(0xc820d8b650)
        /usr/local/Cellar/go/1.6.2/libexec/src/cmd/link/internal/ld/lib.go:847 +0x10d9 fp=0xc820043710 sp=0xc820043400
cmd/link/internal/ld.loadlib()
        /usr/local/Cellar/go/1.6.2/libexec/src/cmd/link/internal/ld/lib.go:513 +0x5ce fp=0xc8200439f0 sp=0xc820043710
cmd/link/internal/ld.Ldmain()
        /usr/local/Cellar/go/1.6.2/libexec/src/cmd/link/internal/ld/pobj.go:214 +0x1cd3 fp=0xc820043e70 sp=0xc8200439f0
cmd/link/internal/amd64.Main()
        /usr/local/Cellar/go/1.6.2/libexec/src/cmd/link/internal/amd64/obj.go:44 +0x19 fp=0xc820043e78 sp=0xc820043e70
main.main()
        /usr/local/Cellar/go/1.6.2/libexec/src/cmd/link/main.go:27 +0x36f fp=0xc820043f50 sp=0xc820043e78
runtime.main()
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/proc.go:188 +0x2b0 fp=0xc820043fa0 sp=0xc820043f50
runtime.goexit()
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820043fa8 sp=0xc820043fa0

```

and sometimes

```
→ go build main.go
go build command-line-arguments: /usr/local/Cellar/go/1.6.2/libexec/pkg/tool/darwin_amd64/link: signal: segmentation fault
```

Both of these errors appear at random, I wasn't able to replicate them reliably. As far as I know, repeatedly running `go build` will crash a few times.

I updated to OS X Sierra about 12 hours ago and this issue started after than, before the upgrade everything was working perfectly fine.
I am going to purge my current Go installation and reinstall again, if the issue persist I'll update the thread.

**Comment by davecheney** [comment]
You must upgrade to go1.7rc6 or later.

**Comment by bradfitz** [comment]
Dup of #16352, #16272, etc.
