### ISSUE TITLE
cmd/compile: GOARCH=386 SSA not lowered: v2146, Cvt64Fto32U UINT FLOAT64

### ISSUE THREAD

**Issue by bradfitz** [golang/go#16738]
The x/tools repo is currently broken at tip for GOARCH=386 with:

https://build.golang.org/log/a53f0025ba878ebacd0dc523e01691474e7dc184
```
# golang.org/x/tools/go/ssa/interp
../../gopath/src/golang.org/x/tools/go/ssa/interp/ops.go:1157: internal compiler error: not lowered: v2146, Cvt64Fto32U UINT FLOAT64

goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/tmp/workdir/go/src/runtime/debug/stack.go:24 +0x74
cmd/compile/internal/gc.Fatalf(0x854870f, 0x2, 0x190b22c0, 0x1, 0x1)
	/tmp/workdir/go/src/cmd/compile/internal/gc/subr.go:165 +0x1f0
cmd/compile/internal/gc.(*ssaExport).Unimplementedf(0x87cc864, 0xaa0, 0x854870f, 0x2, 0x190b22c0, 0x1, 0x1)
	/tmp/workdir/go/src/cmd/compile/internal/gc/ssa.go:4578 +0xed
cmd/compile/internal/ssa.(*Config).Unimplementedf(0x198e4000, 0xaa0, 0x854870f, 0x2, 0x190b22c0, 0x1, 0x1)
	/tmp/workdir/go/src/cmd/compile/internal/ssa/config.go:274 +0x5a
cmd/compile/internal/ssa.(*Func).Unimplementedf(0x19f53680, 0x854870f, 0x2, 0x190b22c0, 0x1, 0x1)
	/tmp/workdir/go/src/cmd/compile/internal/ssa/func.go:399 +0x55
cmd/compile/internal/ssa.checkLower(0x19f53680)
	/tmp/workdir/go/src/cmd/compile/internal/ssa/lower.go:36 +0x2e0
cmd/compile/internal/ssa.Compile(0x19f53680)
	/tmp/workdir/go/src/cmd/compile/internal/ssa/compile.go:64 +0x296
cmd/compile/internal/gc.buildssa(0x19308660, 0x0)
	/tmp/workdir/go/src/cmd/compile/internal/gc/ssa.go:235 +0xa50
cmd/compile/internal/gc.compile(0x19308660)
	/tmp/workdir/go/src/cmd/compile/internal/gc/pgen.go:405 +0x1006
cmd/compile/internal/gc.funccompile(0x19308660)
	/tmp/workdir/go/src/cmd/compile/internal/gc/dcl.go:1287 +0x16a
cmd/compile/internal/gc.Main()
	/tmp/workdir/go/src/cmd/compile/internal/gc/main.go:465 +0x1671
cmd/compile/internal/x86.Main()
	/tmp/workdir/go/src/cmd/compile/internal/x86/galign.go:85 +0x388
main.main()
	/tmp/workdir/go/src/cmd/compile/main.go:31 +0x180

```

Repro:

```
$ GOARCH=386 go test -c -i golang.org/x/tools/go/ssa/interp
```

**Comment by quentinmit** [comment]
@cherrymui has a fix for this
