### ISSUE TITLE
go vet is crash

### ISSUE THREAD

**Issue by runner-mei** [golang/go#16826]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
   go version go1.7 windows/amd64

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=d:\developing\go\xxx\..\3td;d:\developing\go\xxx\
set GORACE=
set GOROOT=d:\tools\go_amd64
set GOTOOLDIR=d:\tools\go_amd64\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\xxx\AppData\Local\Temp\go-build765068130=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1

3. What did you do?
I run "go vet"

4. What did you expect to see?
````
panic: inconsistent import:
	var bufio.ErrInvalidUnreadByte error
previously imported as:
	var ErrInvalidUnreadByte error
 [recovered]
	panic: inconsistent import:
	var bufio.ErrInvalidUnreadByte error
previously imported as:
	var ErrInvalidUnreadByte error


goroutine 1 [running]:
panic(0x68c640, 0xc042d04060)
	c:/go/src/runtime/panic.go:500 +0x1af
go/types.(*Checker).handleBailout(0xc0420942a0, 0xc04285f8d8)
	c:/go/src/go/types/check.go:213 +0xb5
panic(0x68c640, 0xc042d04060)
	c:/go/src/runtime/panic.go:458 +0x251
go/internal/gcimporter.(*importer).declare(0xc042389d40, 0x814620, 0xc04271a460)
	c:/go/src/go/internal/gcimporter/bimport.go:175 +0x183
go/internal/gcimporter.(*importer).obj(0xc042389d40, 0xfffffffffffffffc)
	c:/go/src/go/internal/gcimporter/bimport.go:195 +0x1bb
go/internal/gcimporter.BImportData(0xc0420571d0, 0xc042a78000, 0x1802a, 0x1fe00, 0xc0423db1f1, 0x5, 0x0, 0x5, 0x10, 0x10)
	c:/go/src/go/internal/gcimporter/bimport.go:88 +0x397
go/internal/gcimporter.Import(0xc0420571d0, 0xc0423db1f1, 0x5, 0x6e7604, 0x1, 0xc04211ab40, 0x0, 0x0)
	c:/go/src/go/internal/gcimporter/gcimporter.go:166 +0x558
go/importer.gcimports.ImportFrom(0xc0420571d0, 0xc0423db1f1, 0x5, 0x6e7604, 0x1, 0x0, 0x4, 0x8, 0x0)
	c:/go/src/go/importer/importer.go:70 +0x6e
go/types.(*Checker).collectObjects(0xc0420942a0)
	c:/go/src/go/types/resolver.go:191 +0x82d
go/types.(*Checker).checkFiles(0xc0420942a0, 0xc042085200, 0x29, 0x40, 0x0, 0x0)
	c:/go/src/go/types/check.go:225 +0xb1
go/types.(*Checker).Files(0xc0420942a0, 0xc042085200, 0x29, 0x40, 0xc0424dec90, 0xc04202f960)
	c:/go/src/go/types/check.go:218 +0x50
go/types.(*Config).Check(0xc042117c80, 0xc042005828, 0x8, 0xc0420099c0, 0xc042085200, 0x29, 0x40, 0xc042474870, 0x200, 0xc04201e000, ...)
	c:/go/src/go/types/api.go:344 +0x1aa
main.(*Package).check(0xc042015a40, 0xc0420099c0, 0xc042085200, 0x29, 0x40, 0x0, 0xc04252e500)
	c:/go/src/cmd/vet/types.go:76 +0x377
main.doPackage(0x6e7604, 0x1, 0xc04206a010, 0x29, 0x29, 0x0, 0x1)
	c:/go/src/cmd/vet/main.go:336 +0x9a0
main.main()
	c:/go/src/cmd/vet/main.go:244 +0x34c
exit status 2

````

**Comment by QuentinPerez** [comment]
Same issue with `go tool vet --all=true ./pkg` on the github.com/scaleway/scaleway repository

```bash
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/quentinperez/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/5r/_xh_6_fs0h16qgqvrdygnd540000gn/T/go-build825551204=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

**Comment by minux** [comment]
Dup of #15728.
