### ISSUE TITLE
cmd/compile: TestFP fail on linux/mips64

### ISSUE THREAD

**Issue by minux** [golang/go#16903]
See https://build.golang.org/log/c6251926ba6ec8827b6b486ba21a4e32ab932f2d

```
--- FAIL: TestFP (16.39s)
	ssa_test.go:32: Failed: exit status 1:
		Out: Saw 4 failures
		
		Stderr: F64 Expected +2.147484e+009 for e , got -1.000000e+000
		F64 Expected -2.147484e+009 for e , got -2.000000e+000
		F32 Expected +2.147484e+009 for e , got -1.000000e+000
		F32 Expected -2.147484e+009 for e , got -2.000000e+000
		panic: Failed.
		
		goroutine 1 [running]:
		panic(0xbcd60, 0xc42000a440)
			/gobuild/gobuilder/linux-mips64-minux-3427f16642a1/go/src/runtime/panic.go:500 +0x194
		main.main()
			/gobuild/gobuilder/linux-mips64-minux-3427f16642a1/go/src/cmd/compile/internal/gc/testdata/fp_ssa.go:1700 +0x1324
		exit status 2
		
FAIL
FAIL	cmd/compile/internal/gc	832.801s
```

/cc @cherrymui

**Comment by cherrymui** [comment]
Coudl you try if this patch fix the problem? I am having problem to push to gerrit now.
```
diff --git a/src/cmd/compile/internal/mips64/ssa.go b/src/cmd/compile/internal/mips64/ssa.go
index da30ddc..fdeb43f 100644
--- a/src/cmd/compile/internal/mips64/ssa.go
+++ b/src/cmd/compile/internal/mips64/ssa.go
@@ -103,9 +103,9 @@ func isHILO(r int16) bool {
 // loadByType returns the load instruction of the given type.
 func loadByType(t ssa.Type, r int16) obj.As {
        if isFPreg(r) {
-               if t.IsFloat() && t.Size() == 4 { // float32
+               if t.Size() == 4 { // float32 or int32
                        return mips.AMOVF
-               } else { // float64 or integer in FP register
+               } else { // float64 or int64
                        return mips.AMOVD
                }
        } else {
@@ -138,9 +138,9 @@ func loadByType(t ssa.Type, r int16) obj.As {
 // storeByType returns the store instruction of the given type.
 func storeByType(t ssa.Type, r int16) obj.As {
        if isFPreg(r) {
-               if t.IsFloat() && t.Size() == 4 { // float32
+               if t.Size() == 4 { // float32 or int32
                        return mips.AMOVF
-               } else { // float64 or integer in FP register
+               } else { // float64 or int64
                        return mips.AMOVD
                }
        } else {
```

**Comment by minux** [comment]
After applying the patch to rev 54d7de7dd62b, at least
TestFP has passed. I will update when the test finishes.

The mips64 builder is really slow (compiling the test
alone requires 20 minutes).... we really need to add
software FP support to linux/mips64{,le}.

**Comment by minux** [comment]
all tests in cmd/compile/internal/gc passed with the patch applied.

**Comment by cherrymui** [comment]
Thank you. CL https://go-review.googlesource.com/c/27933/ sent.
