### ISSUE TITLE
segmentation violation

### ISSUE THREAD

**Issue by bronze1man** [golang/go#16987]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
```
go version go1.7 linux/amd64
```

### What operating system and processor architecture are you using (`go env`)?
```
# go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build548111168=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6515ef]

goroutine 27407223 [running]:
panic(0xa3ff60, 0xc420010060)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
net/http.(*persistConn).closeConnIfStillIdle(0xc420272400)
	/usr/local/go/src/net/http/transport.go:1311 +0x2f
net/http.(*persistConn).(net/http.closeConnIfStillIdle)-fm()
	/usr/local/go/src/net/http/transport.go:683 +0x2a
created by time.goFunc
	/usr/local/go/src/time/sleep.go:154 +0x44
```

**Comment by bronze1man** [comment]
This stuff happened randomly.
It looks like https://github.com/golang/go/issues/16208

**Comment by bradfitz** [comment]
This is a dup of #16208. Go 1.7.1 will come soon. It was supposed to be last week.

**Comment by quentinmit** [comment]
Closing as dupe. Please watch for Go 1.7.1.
