### ISSUE TITLE
After update to Mac OSX, GO BUILD ending up in fatal error: unexpected signal during runtime execution [signal 0xb code=0x1 addr=0x1e069c6ce02 pc=0xf47b]

### ISSUE THREAD

**Issue by ishananand** [golang/go#17367]
### What version of Go are you using (`go version`)?
```
go version go1.6.3 darwin/amd64
```

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/me/work/src/myproject/vendors:/Users/me/work:/Users/me/.gvm/pkgsets/go1.6.3/global"
GORACE=""
GOROOT="/Users/me/.gvm/gos/go1.6.3"
GOTOOLDIR="/Users/me/.gvm/gos/go1.6.3/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

### What did you do?
I ran various versions of go build(go build, go build -tags dev, go build -o myproject).

### What did you expect to see?
Successful build or a compile time error

### What did you see instead?
```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x1e069c6ce02 pc=0xf47b]

runtime stack:
runtime.throw(0x2c4900, 0x2a)
	/usr/local/go/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.unlock(0x3a60a0)
	/usr/local/go/src/runtime/lock_sema.go:107 +0x14b
runtime.(*mheap).alloc_m(0x3a60a0, 0x1, 0x40000000012, 0x717728)
	/usr/local/go/src/runtime/mheap.go:492 +0x314
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0xc820041e58)
	/usr/local/go/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x3a60a0, 0x1, 0x10000000012, 0xf11f)
	/usr/local/go/src/runtime/mheap.go:503 +0x63
runtime.(*mcentral).grow(0x3a7b50, 0x0)
	/usr/local/go/src/runtime/mcentral.go:209 +0x93
runtime.(*mcentral).cacheSpan(0x3a7b50, 0x6be430)
	/usr/local/go/src/runtime/mcentral.go:89 +0x47d
runtime.(*mcache).refill(0x401000, 0xc800000012, 0x6be430)
	/usr/local/go/src/runtime/mcache.go:119 +0xcc
runtime.mallocgc.func2()
	/usr/local/go/src/runtime/malloc.go:642 +0x2b
runtime.systemstack(0xc82001e000)
	/usr/local/go/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1051

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:245 fp=0xc82003aa38 sp=0xc82003aa30
runtime.mallocgc(0x120, 0x276fa0, 0x0, 0xc82302fc20)
	/usr/local/go/src/runtime/malloc.go:643 +0x869 fp=0xc82003ab10 sp=0xc82003aa38
runtime.newobject(0x276fa0, 0xc82142d400)
	/usr/local/go/src/runtime/malloc.go:781 +0x42 fp=0xc82003ab38 sp=0xc82003ab10
cmd/link/internal/ld.readsym(0xc82007e240, 0xc821ddd280, 0xc82023fd10, 0x7, 0xc823821800, 0x40)
	/usr/local/go/src/cmd/link/internal/ld/objfile.go:208 +0x75c fp=0xc82003af80 sp=0xc82003ab38
cmd/link/internal/ld.ldobjfile(0xc82007e240, 0xc821ddd280, 0xc82023fd10, 0x7, 0x8e007, 0xc823821800, 0x40)
	/usr/local/go/src/cmd/link/internal/ld/objfile.go:147 +0xa62 fp=0xc82003b190 sp=0xc82003af80
cmd/link/internal/ld.ldobj(0xc821ddd280, 0xc82023fd10, 0x7, 0x8e030, 0xc823821800, 0x40, 0xc820ceea40, 0x38, 0x1, 0x0)
	/usr/local/go/src/cmd/link/internal/ld/lib.go:1351 +0x1569 fp=0xc82003b400 sp=0xc82003b190
cmd/link/internal/ld.objfile(0xc820c71810)
	/usr/local/go/src/cmd/link/internal/ld/lib.go:847 +0x10d9 fp=0xc82003b710 sp=0xc82003b400
cmd/link/internal/ld.loadlib()
	/usr/local/go/src/cmd/link/internal/ld/lib.go:513 +0x5ce fp=0xc82003b9f0 sp=0xc82003b710
cmd/link/internal/ld.Ldmain()
	/usr/local/go/src/cmd/link/internal/ld/pobj.go:214 +0x1cd3 fp=0xc82003be70 sp=0xc82003b9f0
cmd/link/internal/amd64.Main()
	/usr/local/go/src/cmd/link/internal/amd64/obj.go:44 +0x19 fp=0xc82003be78 sp=0xc82003be70
main.main()
	/usr/local/go/src/cmd/link/main.go:27 +0x36f fp=0xc82003bf50 sp=0xc82003be78
runtime.main()
	/usr/local/go/src/runtime/proc.go:188 +0x2b0 fp=0xc82003bfa0 sp=0xc82003bf50
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82003bfa8 sp=0xc82003bfa0
make: *** [build] Error 2
```

**Comment by quentinmit** [comment]
Go 1.6.3 does not support macOS Sierra. You need to upgrade to Go 1.7 or later.
