### ISSUE TITLE
crypto/tls: TestConnCloseWrite flake

### ISSUE THREAD

**Issue by bradfitz** [golang/go#17486]
Trybot failure flake:

https://storage.googleapis.com/go-build-log/ae11a8d3/nacl-386_4211e444.log

```
panic: Fail in goroutine after  has completed

goroutine 318 [running]:
panic(0x274c00, 0x1223bcc0)
    /tmp/workdir/go/src/runtime/panic.go:527 +0x1a0
testing.(*common).Fail(0x10b40580)
    /tmp/workdir/go/src/testing/testing.go:422 +0x160
testing.(*common).Fail(0x1254cf80)
    /tmp/workdir/go/src/testing/testing.go:416 +0x1c0
testing.(*common).FailNow(0x1254cf80)
    /tmp/workdir/go/src/testing/testing.go:441 +0x40
testing.(*common).Fatal(0x1254cf80, 0x12a37fc4, 0x1, 0x1)
    /tmp/workdir/go/src/testing/testing.go:501 +0x80
crypto/tls.TestConnCloseWrite.func2(0x7c2040, 0x1223bbd0, 0x1254cf80)
    /tmp/workdir/go/src/crypto/tls/tls_test.go:526 +0xc0
created by crypto/tls.TestConnCloseWrite
    /tmp/workdir/go/src/crypto/tls/tls_test.go:534 +0x780
FAIL    crypto/tls  2.810s
```

/cc @benburkert 
/cc @randall77 from https://go-review.googlesource.com/c/31260

**Comment by aclements** [comment]
Been happening a lot:

`$ greplogs -dashboard -E "TestConnCloseWrite has completed" -l -md`
[2016-10-17T14:26:55-c6185aa/solaris-amd64-smartosbuildlet](https://build.golang.org/log/3f7808c069eb698ff0af5c27e5d0e11498fd88a1)
[2016-10-17T15:21:33-f444b48/solaris-amd64-smartosbuildlet](https://build.golang.org/log/7d693686011901f57f33717f901984aedb911945)
[2016-10-17T15:22:11-15040c1/linux-ppc64-buildlet](https://build.golang.org/log/a8cdfcb55ca25a984c6b96399bccbbaa0fb9649b)
[2016-10-17T15:22:17-237d7e3/solaris-amd64-smartosbuildlet](https://build.golang.org/log/e4ef14f08fa72d95f6c647176c66303163792bfa)
[2016-10-17T15:26:25-0ce1d79/linux-amd64-noopt](https://build.golang.org/log/c10c7c4ee03c7a3f5601aaad12377193df7b6961)
[2016-10-17T15:26:25-0ce1d79/solaris-amd64-smartosbuildlet](https://build.golang.org/log/d8fc78183050373054ed9c9e288cecafc32eb77d)
[2016-10-17T16:06:04-d26b066/solaris-amd64-smartosbuildlet](https://build.golang.org/log/4594ba983ffa7bc033115ef6bf28fcf1e42346e3)
[2016-10-17T17:05:39-9a97c3b/linux-amd64-noopt](https://build.golang.org/log/0c506ca773e2810423f9120b4378316065427bc7)
[2016-10-17T18:11:24-77b6a08/solaris-amd64-smartosbuildlet](https://build.golang.org/log/69efe9b373b17f5755ae2dda5c1a980adeed0d6d)
[2016-10-17T18:23:32-cbf28ff/solaris-amd64-smartos](https://build.golang.org/log/ddfe8ca22fb77b8dd54560702fd1c79516769b16)
[2016-10-17T18:26:20-6f4a6fa/solaris-amd64-smartosbuildlet](https://build.golang.org/log/b1477cd067723c5cf40bd43d0dda232781e2fcd4)
[2016-10-17T18:34:02-7c46f03/solaris-amd64-smartos](https://build.golang.org/log/c4f1b16e9d14297b07c85a8e0f3c1e70840df08c)
[2016-10-17T18:34:02-7c46f03/solaris-amd64-smartosbuildlet](https://build.golang.org/log/af3b742972b9f5d5539bd6aa1e6194bfc492cb57)
[2016-10-17T18:46:20-1e28dce/solaris-amd64-smartosbuildlet](https://build.golang.org/log/05942d475b8f52a74898bcd3cd7ac08a2ad4602c)
[2016-10-17T18:53:22-0ba3c60/solaris-amd64-smartosbuildlet](https://build.golang.org/log/f91ccb80c16ebd7bd5863575987ec109d3b4d433)
[2016-10-17T18:56:09-687d9d5/solaris-amd64-smartosbuildlet](https://build.golang.org/log/5a27bff4750516790750d1256716f67c3ec682ef)
[2016-10-17T18:57:01-d5bd797/solaris-amd64-smartos](https://build.golang.org/log/4c615b8305a98e281943de90c229794fdd4b0e2f)
[2016-10-17T18:57:01-d5bd797/solaris-amd64-smartosbuildlet](https://build.golang.org/log/eec4e87b01a3b1231e399de36f45094522378b4d)
[2016-10-17T19:09:07-395d36a/solaris-amd64-smartos](https://build.golang.org/log/5263d956905177ff391be7acdf63c5fd1a864927)
[2016-10-17T19:09:07-395d36a/solaris-amd64-smartosbuildlet](https://build.golang.org/log/37197a7bebdd60b84d6ad788e4ebb6da4c322116)
[2016-10-17T19:09:30-81c431a/solaris-amd64-smartos](https://build.golang.org/log/fdb4500ee5ebd2dd00f2c569bba7d423d978de97)
[2016-10-17T19:09:30-81c431a/solaris-amd64-smartosbuildlet](https://build.golang.org/log/85fb06cc93f6230e1f00e11b31c061e0d72e3b67)
[2016-10-17T19:09:30-81c431a/windows-amd64-race](https://build.golang.org/log/6653c99e3e1a3b674321847732a3ecafda558087)
[2016-10-17T19:09:37-984753b/solaris-amd64-smartosbuildlet](https://build.golang.org/log/9375a48670e8cd5a905ede1fcbd5f692a3fb802d)
[2016-10-17T19:09:37-984753b/windows-amd64-race](https://build.golang.org/log/0ddbffda26bb94dc9b64cc07ccf5bfdeda761ea6)

```
$ greplogs -dashboard -E "TestConnCloseWrite has completed" -l | findflakes -dir ~/.cache/fetchlogs/rev -paths
First observed c6185aa 17 Oct 14:26 2016 (18 commits ago)
Last observed  984753b 17 Oct 19:09 2016 (1 commits ago)
0.00% chance failure is still happening
100% failure probability (18 of 18 commits)
Likely culprits:
  100% c6185aa crypto/tls: add CloseWrite method to Conn
No known past failures
```

Commit c6185aa was by @benburkert.

**Comment by bradfitz** [comment]
@benburkert, can you look into making that test non-flaky?

**Comment by mdempsky** [comment]
FYI, https://go-review.googlesource.com/#/c/31310/ is up to revert CL 31260 since it seems to be causing other failures too.  The TestConnCloseWrite flakes predate it, but somehow CL 31260 seems to make them more frequent.

**Comment by rsc** [comment]
Fixed by CL 31318.
