### ISSUE TITLE
runtime: Go 1.6.3 panics on macOS sierra

### ISSUE THREAD

**Issue by magiconair** [golang/go#17550]
### What version of Go are you using (`go version`)?
go1.6.3

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/frschroeder/gopath"
GORACE=""
GOROOT="/Users/frschroeder/Downloads/go1.6.3"
GOTOOLDIR="/Users/frschroeder/Downloads/go1.6.3/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```
### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

Run this code with go1.6.3 from https://storage.googleapis.com/golang/go1.6.3.darwin-amd64.tar.gz

```
package main

import "log"

func main() {
	for {
		log.Print("foo")
	}
}
```

### What did you expect to see?

Endless stream of log output

### What did you see instead?

```
$ ~/Downloads/go1.6.3/bin/go run repro.go
2016/10/22 10:43:03 foo
...
2016/10/22 10:37:04 foo
2016/10/22 10:37:04 foo
2016/10/22 10:37:04 foo
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x4943cfdb1ec7 pc=0x6f460]

goroutine 1 [running]:
runtime.throw(0x122de0, 0x2a)
	/Users/frschroeder/Downloads/go1.6.3/src/runtime/panic.go:547 +0x90 fp=0xc82003bd60 sp=0xc82003bd48
runtime.sigpanic()
	/Users/frschroeder/Downloads/go1.6.3/src/runtime/sigpanic_unix.go:12 +0x5a fp=0xc82003bdb0 sp=0xc82003bd60
sync.(*Pool).Get(0x184f40, 0x0, 0x0)
	/Users/frschroeder/Downloads/go1.6.3/src/sync/pool.go:102 +0x40 fp=0xc82003be00 sp=0xc82003bdb0
fmt.newPrinter(0xecf9d1c30)
	/Users/frschroeder/Downloads/go1.6.3/src/fmt/print.go:133 +0x27 fp=0xc82003be40 sp=0xc82003be00
fmt.Sprint(0xc82003bf10, 0x1, 0x1, 0x0, 0x0)
	/Users/frschroeder/Downloads/go1.6.3/src/fmt/print.go:238 +0x28 fp=0xc82003be90 sp=0xc82003be40
log.Print(0xc82003bf10, 0x1, 0x1)
	/Users/frschroeder/Downloads/go1.6.3/src/log/log.go:283 +0x35 fp=0xc82003bed8 sp=0xc82003be90
main.main()
	/Users/frschroeder/gopath/src/frank/repro.go:7 +0xcc fp=0xc82003bf50 sp=0xc82003bed8
runtime.main()
	/Users/frschroeder/Downloads/go1.6.3/src/runtime/proc.go:188 +0x2b0 fp=0xc82003bfa0 sp=0xc82003bf50
runtime.goexit()
	/Users/frschroeder/Downloads/go1.6.3/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82003bfa8 sp=0xc82003bfa0
exit status 2
```

This seems to crash consul 0.7.0 on sierra as well. It was built with go1.6.3. See https://github.com/hashicorp/consul/issues/2407

Confirmed the crash on a second machine.

This works with go1.7.1

**Comment by mikioh** [comment]
See https://github.com/golang/go/wiki/Darwin. This is a duplicate issue of #16570.

**Comment by magiconair** [comment]
Log writes the time ... Thx.
