### ISSUE TITLE
cmd/go: -buildmode=plugin crashes if package imports "plugin" package

### ISSUE THREAD

**Issue by rakyll** [golang/go#17624]
```
$ cat main.go

package main

import (
    "log"
    "plugin"
)

func main() {
    p, err := plugin.Open("main.so")
    if err != nil {
        log.Fatal(err)
    }
    s, err := p.Lookup("main.main")
    if err != nil {
        log.Fatal(err)
    }
    log.Println(s)
}

$ go build -buildmode=plugin
# hello/plugin
panic: found import cycle while visiting plugin

goroutine 1 [running]:
panic(0x19c4a0, 0xc4214f8950)
    /Users/jbd/go/src/runtime/panic.go:531 +0x1a0
cmd/link/internal/ld.dfs(0xc4204d6000, 0xc42003da78, 0xc42003da60)
    /Users/jbd/go/src/cmd/link/internal/ld/lib.go:2124 +0x2ef
cmd/link/internal/ld.dfs(0xc4204d6000, 0xc42003da78, 0xc42003da60)
    /Users/jbd/go/src/cmd/link/internal/ld/lib.go:2128 +0x129
cmd/link/internal/ld.postorder(0xc420075b00, 0x13, 0x20, 0x0, 0xc421435c30, 0xc4204c8038)
    /Users/jbd/go/src/cmd/link/internal/ld/lib.go:2114 +0x137
cmd/link/internal/ld.(*Link).loadlib(0xc4204be000)
    /Users/jbd/go/src/cmd/link/internal/ld/lib.go:619 +0xc01
cmd/link/internal/ld.Main()
    /Users/jbd/go/src/cmd/link/internal/ld/main.go:183 +0x7f0
main.main()
    /Users/jbd/go/src/cmd/link/main.go:55 +0x139
```

**Comment by crawshaw** [comment]
Fixed by 9da7058466c.
