### ISSUE TITLE
plugin: doc example doesn't work

### ISSUE THREAD

**Issue by aclements** [golang/go#17693]
#### What did you do?
Attempted to use the example from the plugin package documentation to try it out:

```sh
cat >x.go <<EOF
package main

// // No C code needed.
import "C"

import "fmt"

var V int

func F() { fmt.Println("Hello, number %d", V) }
EOF
cat >y.go <<EOF
package main

import "plugin"

func main() {
	_, err := plugin.Open("x.so")
	if err != nil {
		panic(err)
	}
}
EOF
go build -buildmode=plugin x.go
go run y.go
```

#### What did you expect to see?
Nothing.

#### What did you see instead?
```
panic: plugin.Open: could not find symbol V: /home/austin/tmp/x.so: undefined symbol: x.V

goroutine 1 [running]:
panic(0x49ce40, 0xc42000c1a0)
	/home/austin/go.dev/src/runtime/panic.go:531 +0x1cf
main.main()
	/home/austin/tmp/y.go:8 +0x63
exit status 2
```

#### System details

```
go version devel +f135106 Sun Oct 30 19:14:08 2016 +0000 linux/amd64
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/austin/r/go"
GORACE=""
GOROOT="/home/austin/go.dev"
GOTOOLDIR="/home/austin/go.dev/pkg/tool/linux_amd64"
TERM="dumb"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build979699063=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
uname -sr: Linux 4.2.0-42-generic
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
/lib/x86_64-linux-gnu/libc.so.6: GNU C Library (Ubuntu EGLIBC 2.19-0ubuntu6.9) stable release version 2.19, by Roland McGrath et al.
gdb --version: GNU gdb (GDB) 7.9-gg19
```

**Comment by crawshaw** [comment]
This was fixed in 9da7058466c8c9f32e1481f28d57732832ee3b30, which your toolchain is two commits behind.
