### ISSUE TITLE
cmd/vendor/golang.org/x/arch/ppc64/ppc64asm: test deadlock without -short

### ISSUE THREAD

**Issue by josharian** [golang/go#17698]
Broken out from #17472.

```bash
$ go test -v cmd/vendor/golang.org/x/arch/ppc64/ppc64asm
=== RUN   TestDecode
--- PASS: TestDecode (0.00s)
=== RUN   TestBitField
--- PASS: TestBitField (0.00s)
=== RUN   TestObjdumpPowerTestdata
starting objdump
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
testing.(*T).Run(0xc4200ae0c0, 0x113e97e, 0x18, 0x1143750, 0x1055301)
	/Users/josh/go/tip/src/testing/testing.go:677 +0x2ee
testing.runTests.func1(0xc4200ae0c0)
	/Users/josh/go/tip/src/testing/testing.go:832 +0x67
testing.tRunner(0xc4200ae0c0, 0xc420041e30)
	/Users/josh/go/tip/src/testing/testing.go:639 +0x85
testing.runTests(0x1143800, 0x11e9980, 0x4, 0x4, 0x24)
	/Users/josh/go/tip/src/testing/testing.go:838 +0x29d
testing.(*M).Run(0xc420041f28, 0x0)
	/Users/josh/go/tip/src/testing/testing.go:773 +0x90
main.main()
	cmd/vendor/golang.org/x/arch/ppc64/ppc64asm/_test/_testmain.go:60 +0xc6

goroutine 21 [chan receive]:
cmd/vendor/golang.org/x/arch/ppc64/ppc64asm.testExtDis.func3(0xc420076ce0, 0x4, 0x4)
	/Users/josh/go/tip/src/cmd/vendor/golang.org/x/arch/ppc64/ppc64asm/ext_test.go:134 +0xf7
cmd/vendor/golang.org/x/arch/ppc64/ppc64asm.testdataCases.func1(0xc4200745a0)
	/Users/josh/go/tip/src/cmd/vendor/golang.org/x/arch/ppc64/ppc64asm/ext_test.go:519 +0x65
cmd/vendor/golang.org/x/arch/ppc64/ppc64asm.testExtDis(0xc4200ae3c0, 0x1138546, 0x3, 0x1143760, 0xc420070500, 0x1143758)
	/Users/josh/go/tip/src/cmd/vendor/golang.org/x/arch/ppc64/ppc64asm/ext_test.go:163 +0x44b
cmd/vendor/golang.org/x/arch/ppc64/ppc64asm.testObjdump(0xc4200ae3c0, 0xc420070500)
	/Users/josh/go/tip/src/cmd/vendor/golang.org/x/arch/ppc64/ppc64asm/objdumpext_test.go:32 +0xee
cmd/vendor/golang.org/x/arch/ppc64/ppc64asm.TestObjdumpPowerTestdata(0xc4200ae3c0)
	/Users/josh/go/tip/src/cmd/vendor/golang.org/x/arch/ppc64/ppc64asm/objdump_test.go:13 +0x43
testing.tRunner(0xc4200ae3c0, 0x1143750)
	/Users/josh/go/tip/src/testing/testing.go:639 +0x85
created by testing.(*T).Run
	/Users/josh/go/tip/src/testing/testing.go:676 +0x2c4

goroutine 22 [chan send]:
cmd/vendor/golang.org/x/arch/ppc64/ppc64asm.testExtDis.func2(0xc420074540, 0x1143760, 0xc42007aa80)
	/Users/josh/go/tip/src/cmd/vendor/golang.org/x/arch/ppc64/ppc64asm/ext_test.go:131 +0x68
created by cmd/vendor/golang.org/x/arch/ppc64/ppc64asm.testExtDis
	/Users/josh/go/tip/src/cmd/vendor/golang.org/x/arch/ppc64/ppc64asm/ext_test.go:132 +0x30a
FAIL	cmd/vendor/golang.org/x/arch/ppc64/ppc64asm	0.024s
```

Adding `	defer close(ext.Dec)` to the beginning of `func objdump` in `cmd/vendor/golang.org/x/arch/ppc64/ppc64asm/objdumpext_test.go` changes this to regular test failures:

```bash
$ go test -v cmd/vendor/golang.org/x/arch/ppc64/ppc64asm
=== RUN   TestDecode
--- PASS: TestDecode (0.00s)
=== RUN   TestBitField
--- PASS: TestBitField (0.00s)
=== RUN   TestObjdumpPowerTestdata
--- FAIL: TestObjdumpPowerTestdata (0.01s)
	ext_test.go:136: decoding stream ended early
	ext_test.go:136: decoding stream ended early
	ext_test.go:136: decoding stream ended early
	ext_test.go:136: decoding stream ended early
	ext_test.go:136: decoding stream ended early
	ext_test.go:136: decoding stream ended early
	ext_test.go:136: decoding stream ended early
	ext_test.go:136: decoding stream ended early
	ext_test.go:136: decoding stream ended early
	ext_test.go:136: decoding stream ended early
	ext_test.go:136: decoding stream ended early
	ext_test.go:136: decoding stream ended early
	ext_test.go:136: decoding stream ended early
	ext_test.go:136: decoding stream ended early
	ext_test.go:136: decoding stream ended early
	ext_test.go:136: decoding stream ended early
	ext_test.go:136: decoding stream ended early
	ext_test.go:136: decoding stream ended early
	ext_test.go:136: decoding stream ended early
	ext_test.go:136: decoding stream ended early
	ext_test.go:136: decoding stream ended early
	ext_test.go:136: decoding stream ended early
	ext_test.go:136: decoding stream ended early
	ext_test.go:136: decoding stream ended early
	ext_test.go:136: decoding stream ended early
	ext_test.go:176: 0 test cases, 0 expected mismatches, 0 failures; 0 cases/second
	ext_test.go:179: external disassembler: not enough results found [32768 32868]
=== RUN   TestObjdumpPowerManual
--- FAIL: TestObjdumpPowerManual (0.01s)
	ext_test.go:136: decoding stream ended early
	ext_test.go:136: decoding stream ended early
	ext_test.go:136: decoding stream ended early
	ext_test.go:176: 0 test cases, 0 expected mismatches, 0 failures; 0 cases/second
	ext_test.go:179: external disassembler: not enough results found [32768 32780]
FAIL
FAIL	cmd/vendor/golang.org/x/arch/ppc64/ppc64asm	0.030s
```

This is an improvement over a deadlock, but still not great. Presumably the problem is that I don't have the right cross-disassembler installed on my system, but the test should detect that and t.Skip instead.

cc @minux

**Comment by dr2chase** [comment]
@laboger not sure if this concerns you guys or not

**Comment by laboger** [comment]
This failure only happens when built and run on cross? It doesn't fail natively.
I can add detection of the system disassembler and skip the test if it isn't available.

**Comment by laboger** [comment]
I created https://go-review.googlesource.com/32510 for the fix in golang.org/x/arch/ppc64/ppc64asm, and once this is in I will create the CL for the golang cmd/vendor directory and mark that one as fixing this issue.
