### ISSUE TITLE
cmd/doc: Panic when showing unexported symbols on pkg with invalid go file

### ISSUE THREAD

**Issue by keegancsmith** [golang/go#17788]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.3 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

### What did you do?
```
$ go get -d github.com/ardanlabs/gotraining/topics/language/embedding/exercises/template1
$ go doc -u github.com/ardanlabs/gotraining/topics/language/embedding/exercises/template1
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x177620, 0xc4200101a0)
        /usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1
go/doc.(*reader).readFunc(0xc420041c60, 0xc420078e70)
        /usr/local/Cellar/go/1.7.3/libexec/src/go/doc/reader.go:365 +0x3af
go/doc.(*reader).readFile(0xc420041c60, 0xc4200a4a00)
        /usr/local/Cellar/go/1.7.3/libexec/src/go/doc/reader.go:519 +0x5fb
go/doc.(*reader).readPackage(0xc420041c60, 0xc420078ff0, 0x1)
        /usr/local/Cellar/go/1.7.3/libexec/src/go/doc/reader.go:552 +0x35a
go/doc.New(0xc420078ff0, 0x7fff5fbff320, 0x4d, 0x1, 0xc42007b8e8)
        /usr/local/Cellar/go/1.7.3/libexec/src/go/doc/doc.go:96 +0x7f
main.parsePackage(0x2504a0, 0xc420094008, 0xc42007d880, 0x7fff5fbff320, 0x4d, 0x0)
        /usr/local/Cellar/go/1.7.3/libexec/src/cmd/doc/pkg.go:140 +0x183
main.do(0x2504a0, 0xc420094008, 0xc4200742a0, 0xc420078190, 0x2, 0x2, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.3/libexec/src/cmd/doc/main.go:97 +0x2e9
main.main()
        /usr/local/Cellar/go/1.7.3/libexec/src/cmd/doc/main.go:72 +0xbc
exit status 2
```

### What did you expect to see?
No panic

### What did you see instead?
A panic! The go file it is parsing is not valid go, but I don't expect to see a panic.

### More context:

This only happens if you pass in `-u`. We noticed this error in production at Sourcegraph due to using `doc.New` with the `Mode` set to `doc.AllDecls` (see https://github.com/sourcegraph/go-langserver/blob/c9034820629b806e84f19677e0d2e71fd4ba8b56/langserver/symbol.go#L335 ). Production is a linux environment. I could reproduce it with the `go doc` command, so reported it as such.

**Comment by keegancsmith** [comment]
Here is a minimal example to reproduce:

```
package issue17788

func ( /* receiver type */ ) f0() {
}
```

placing this at `src/go/doc/testdata/issue17788.go` will get go test to fail.

**Comment by keegancsmith** [comment]
@quentinmit FYI I added https://go-review.googlesource.com/#/c/32790/ which fixes the panic
