### ISSUE TITLE
cmd/link: regression in big text fix for external linking on ppc64le

### ISSUE THREAD

**Issue by laboger** [golang/go#17795]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version devel +04d7135 Fri Nov 4 14:09:52 2016 +0000 linux/ppc64le

### What operating system and processor architecture are you using (`go env`)?
Ubuntu 16.04 ppc64le

### What did you do?
Testing with Go 1.8, attempted to build and test hyperkube from Kubernetes on ppc64le with golang master.

### What did you expect to see?
Successful build and run.

### What did you see instead?
Successful build but execution failure:
unexpected fault address 0xed840
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xed840 pc=0xed840]

goroutine 1 [running, locked to thread]:
runtime.throw(0x12d81cdf, 0x5)
    /usr/local/go/src/runtime/panic.go:596 +0x7c fp=0xc420703eb8 sp=0xc420703e88
runtime.sigpanic()
    /usr/local/go/src/runtime/signal_unix.go:276 +0x24c fp=0xc420703f18 sp=0xc420703eb8
main.init()
    /root/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/hyperkube/server.go:76 +0x70 fp=0xc420703f58 sp=0xc420703f38
runtime.main()
    /usr/local/go/src/runtime/proc.go:173 +0x1b0 fp=0xc420703fc0 sp=0xc420703f58
runtime.goexit()
    /usr/local/go/src/runtime/asm_ppc64x.s:1271 +0x4 fp=0xc420703fc0 sp=0xc420703fc0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_ppc64x.s:1271 +0x4

goroutine 5 [chan receive]:
k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x1601d740)
    /root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:879 +0x64
created by k8s.io/kubernetes/vendor/github.com/golang/glog.init.1
    /root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:410 +0x1fc
[root@localhost kubernetes]#

I found this error was introduced in commit c7e8556.  I have a simple fix for it.

**Comment by laboger** [comment]
This is related to #15823 and #16665.  For ppc64 & ppc64le, trampolines are used to solve the too-far branch problem only for internal linking.  For external linking, the solution for ppc64le is to split the text sections and allow the external linker to handle the long calls.  External linking doesn't work for ppc64.
