### ISSUE TITLE
plugin: doc example segfaults on OS X

### ISSUE THREAD

**Issue by leonklingele** [golang/go#17804]
### What version of Go are you using (`go version`)?
Latest master, `go version devel +dd1e7b3 Fri Nov 4 23:02:39 2016 +0000 darwin/amd64`

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/path/to/go"
GORACE=""
GOROOT="/path/to/go"
GOTOOLDIR="/path/to/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/jv/n5rf3drx1td1ljkt6xk2_60w0000gn/T/go-build981233985=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?
- Try to use the example plugin provided at https://tip.golang.org/pkg/plugin/
- It works fine on linux/amd64

### What did you expect to see?
- Should work on OS X, too

### What did you see instead?
```
unexpected fault address 0xb01dfacedebac1e
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x5054c1c]

goroutine 1 [running]:
runtime.throw(0x406e2de, 0x5)
	/path/to/go/src/runtime/panic.go:596 +0x95 fp=0xc420051b00 sp=0xc420051ae0
runtime.sigpanic()
	/path/to/go/src/runtime/signal_unix.go:276 +0x28c fp=0xc420051b50 sp=0xc420051b00
panic: runtime error: slice bounds out of range
fatal error: panic on system stack
panic during panic

runtime stack:
panic(0x4061a20, 0x40a3de0)
	/path/to/go/src/runtime/panic.go:420 +0x7d6

goroutine 1 [running]:
runtime.systemstack_switch()
	/path/to/go/src/runtime/asm_amd64.s:268 fp=0xc420051aa0 sp=0xc420051a98
runtime.dopanic(0x0)
	/path/to/go/src/runtime/panic.go:579 +0x58 fp=0xc420051ae0 sp=0xc420051aa0
runtime.throw(0x406e2de, 0x5)
	/path/to/go/src/runtime/panic.go:596 +0x95 fp=0xc420051b00 sp=0xc420051ae0
runtime.sigpanic()
	/path/to/go/src/runtime/signal_unix.go:276 +0x28c fp=0xc420051b50 sp=0xc420051b00
panic: runtime error: slice bounds out of range
fatal error: panic on system stack
stack trace unavailable
exit status 4
```

If `import "C"` is not used:
```
unexpected fault address 0xb01dfacedebac1e
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x584c61c]

goroutine 1 [running]:
runtime.throw(0x406e2de, 0x5)
	/path/to/go/src/runtime/panic.go:596 +0x95 fp=0xc420051b00 sp=0xc420051ae0
runtime.sigpanic()
	/path/to/go/src/runtime/signal_unix.go:276 +0x28c fp=0xc420051b50 sp=0xc420051b00
invalid spdelta ty/go/src/runtime/slice.go 0x4051420 0x584c61c 0x2b335 -1
ty/go/src/runtime/slice.go()
	?:0 +0x17fb1fc fp=0xc420051b57 sp=0xc420051b50

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/path/to/go/src/runtime/asm_amd64.s:2184 +0x1
exit status 2
```

**Comment by crawshaw** [comment]
What version of macOS are you using? Does all.bash pass?

**Comment by dAdAbird** [comment]
I tried on my mac and got the same:
```
unexpected fault address 0xb01dfacedebac1e
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x454c61c]

goroutine 1 [running]:
runtime.throw(0x406e11e, 0x5)
	/Users/andrew/projects/go/src/github.com/golang/go/src/runtime/panic.go:596 +0x95 fp=0xc420051b00 sp=0xc420051ae0
runtime.sigpanic()
	/Users/andrew/projects/go/src/github.com/golang/go/src/runtime/signal_unix.go:276 +0x28c fp=0xc420051b50 sp=0xc420051b00
invalid spdelta s/andrew/projects/go/src/github.com/golang/go/src/runtime/string.go 0x4051260 0x454c61c 0x2b335 -1
s/andrew/projects/go/src/github.com/golang/go/src/runtime/string.go()
	?:0 +0x4fb3bc fp=0xc420051b57 sp=0xc420051b50

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/Users/andrew/projects/go/src/github.com/golang/go/src/runtime/asm_amd64.s:2184 +0x1
```

`all.bash` pass.

`go version devel +3df059e Mon Nov 7 06:46:01 2016 +0000 darwin/amd64`
`macOS Sierra (ver. 10.12 (16A323))`

Just in case:
```go
package main

// // No C code needed.
import "C"

import "fmt"

var V int

func F() { fmt.Println("Hello, number %d", V) }
```

```go
package main

import "plugin"

func main() {
	p, err := plugin.Open("main.so")
	if err != nil {
		panic(err)
	}

	v, err := p.Lookup("V")
	if err != nil {
		panic(err)
	}

	f, err := p.Lookup("F")
	if err != nil {
		panic(err)
	}

	*v.(*int) = 7
	f.(func())()
}

```

**Comment by leonklingele** [comment]
@crawshaw I'm on 10.11.6, `all.bash` did pass: `ALL TESTS PASSED`

**Comment by AlekSi** [comment]
Probably related to #18190.

**Comment by bradfitz** [comment]
Plugin support was removed from Darwin in c1ada22. Pushing to 1.9.

**Comment by dragonfax** [comment]
Any word on plugin support for macos? When it first game out, I used it successfully in an app, and was surprised to find it disabled in the release.

**Comment by bradfitz** [comment]
@dragonfax, nobody is working on it. There is no update.

**Comment by crawshaw** [comment]
This case is fixed. Plugins are enabled (with tests in all.bash) at tip on macOS. If they make it into the 1.10 release, they will be experimental on macOS.
