### ISSUE TITLE
gcimporter: go archive is missing __.PKGDEF

### ISSUE THREAD

**Issue by cyphar** [golang/go#17890]
This only happens on openSUSE packages, because I believe that OBS (the Open Build Service) is modifying the entries in `fmt.a` and similar archives.

```
% go version
go version go1.7 linux/amd64
% go env
GOARCH="amd64"
GOBIN="/home/cyphar/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/cyphar/.local"
GORACE=""
GOROOT="/usr/lib64/go"
GOTOOLDIR="/usr/lib64/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build022377736=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
% rpm -qi go
Name        : go
Version     : 1.7.0
Release     : 1.1
Architecture: x86_64
Install Date: Sun 06 Nov 2016 11:22:21 PM AEDT
Group       : Development/Languages/Other
Size        : 199522326
License     : BSD-3-Clause
Signature   : RSA/SHA256, Sat 05 Nov 2016 08:00:32 AM AEDT, Key ID b88b2fd43dbdc284
Source RPM  : go-1.7.0-1.1.src.rpm
Build Date  : Sat 05 Nov 2016 07:57:13 AM AEDT
Build Host  : cloud127
Relocations : (not relocatable)
Packager    : http://bugs.opensuse.org
Vendor      : openSUSE
URL         : http://golang.org
Summary     : A compiled, garbage-collected, concurrent programming language
Description :
Go is an expressive, concurrent, garbage collected systems programming language
that is type safe and memory safe. It has pointers but no pointer arithmetic.
Go has fast builds, clean syntax, garbage collection, methods for any type, and
run-time reflection. It feels like a dynamic language but has the speed and
safety of a static language.
Distribution: openSUSE Tumbleweed
```

If you run a tool like `go vet` on any project you'll get errors:

### What did you expect to see?
No errors.

### What did you see instead?
```
% go vet github.com/cyphar/umoci/image/cas
vet: import failed: reading export data: /usr/lib64/go/pkg/linux_amd64/fmt.a: go archive is missing __.PKGDEF
vet: import failed: reading export data: /usr/lib64/go/pkg/linux_amd64/fmt.a: go archive is missing __.PKGDEF
exit status 1
```

**Comment by cyphar** [comment]
I've figured out why this is happening by the way:

It's because (for some reason), the packaged version of the `fmt.a` and similar static archives have been "cleaned" in a way. You can see it if you modify the source of `go/internal/gcimporter/exportdata.go`:

```go
// Copyright 2011 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// This file implements FindExportData.

package main

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

func readGopackHeader(r *bufio.Reader) (name string, size int, err error) {
	// See $GOROOT/include/ar.h.
	hdr := make([]byte, 16+12+6+6+8+10+2)
	_, err = io.ReadFull(r, hdr)
	if err != nil {
		return
	}
	// leave for debugging
	if false {
		fmt.Printf("header: %s", hdr)
	}
	s := strings.TrimSpace(string(hdr[16+12+6+6+8:][:10]))
	size, err = strconv.Atoi(s)
	if err != nil || hdr[len(hdr)-2] != '`' || hdr[len(hdr)-1] != '\n' {
		err = fmt.Errorf("invalid archive header")
		return
	}
	name = strings.TrimSpace(string(hdr[:16]))
	return
}

// FindExportData positions the reader r at the beginning of the
// export data section of an underlying GC-created object/archive
// file by reading from it. The reader must be positioned at the
// start of the file before calling this function. The hdr result
// is the string before the export data, either "$$" or "$$B".
//
func FindExportData(r *bufio.Reader) (hdr string, err error) {
	// Read first line to make sure this is an object file.
	line, err := r.ReadSlice('\n')
	if err != nil {
		err = fmt.Errorf("can't find export data (%v)", err)
		return
	}

	if string(line) == "!<arch>\n" {
		// Archive file. Scan to __.PKGDEF.
		var name string
		if name, _, err = readGopackHeader(r); err != nil {
			return
		}

		// First entry should be __.PKGDEF.
		if name != "__.PKGDEF" {
			fmt.Printf("name=%s\n", name)
			err = fmt.Errorf("go archive is missing __.PKGDEF")
			return
		}

		// Read first line of __.PKGDEF data, so that line
		// is once again the first line of the input.
		if line, err = r.ReadSlice('\n'); err != nil {
			err = fmt.Errorf("can't find export data (%v)", err)
			return
		}
	}

	// Now at __.PKGDEF in archive or still at beginning of file.
	// Either way, line should begin with "go object ".
	if !strings.HasPrefix(string(line), "go object ") {
		err = fmt.Errorf("not a Go object file")
		return
	}

	// Skip over object header to export data.
	// Begins after first line starting with $$.
	for line[0] != '$' {
		if line, err = r.ReadSlice('\n'); err != nil {
			err = fmt.Errorf("can't find export data (%v)", err)
			return
		}
	}
	hdr = string(line)

	return
}

func main() {
	fh, err := os.Open("/usr/lib64/go/pkg/linux_amd64/fmt.a")
	if err != nil {
		panic(err)
	}
	defer fh.Close()

	bio := bufio.NewReader(fh)
	hdr, err := FindExportData(bio)
	if err != nil {
		panic(err)
	}

	fmt.Printf("hdr: %s\n", hdr)
}
```

On openSUSE you get the error:

```
% go run exportdata.go
name=__.PKGDEF/
panic: go archive is missing __.PKGDEF

goroutine 1 [running]:
panic(0x49c240, 0xc42000a540)
        /usr/lib64/go/src/runtime/panic.go:500 +0x1a1
main.main()
        /home/cyphar/tmp/archive/exportdata.go:105 +0x1b7
exit status 2
```

So I do have a fix, which is this patch:

```diff
From f254166f521a3dfa172eed0bb8c63b058462a86e Mon Sep 17 00:00:00 2001
From: Aleksa Sarai <asarai@suse.com>
Date: Fri, 11 Nov 2016 15:00:35 +1100
Subject: [PATCH] gcimporter: clean header name when checking for __.PKGDEF

In some distributions, the build system will "sanitise" archives and do
silly things like append '/' to all directory entries. This caused all
tools that used "go/internal/gcimporter" to not work on such
distributions, even though the actual compiler was fully operational.

Fix this by cleaning the path before checking if it is equal to
"__.PKGDEF", which ensures that we are doing a proper lexical
comparison of paths.

Fixes: #17890
Signed-off-by: Aleksa Sarai <asarai@suse.com>
---
 src/go/internal/gcimporter/exportdata.go | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/src/go/internal/gcimporter/exportdata.go b/src/go/internal/gcimporter/exportdata.go
index c12e459c3db1..0cd31fde9f23 100644
--- a/src/go/internal/gcimporter/exportdata.go
+++ b/src/go/internal/gcimporter/exportdata.go
@@ -10,6 +10,7 @@ import (
 	"bufio"
 	"fmt"
 	"io"
+	"path/filepath"
 	"strconv"
 	"strings"
 )
@@ -57,7 +58,7 @@ func FindExportData(r *bufio.Reader) (hdr string, err error) {
 		}
 
 		// First entry should be __.PKGDEF.
-		if name != "__.PKGDEF" {
+		if filepath.Clean(name) != "__.PKGDEF" {
 			err = fmt.Errorf("go archive is missing __.PKGDEF")
 			return
 		}
-- 
2.10.1
```

**Comment by cyphar** [comment]
Can you comment if that patch is valid? Would you be interested in me making an actual merge request? Or should we just carry that patch inside openSUSE?

**Comment by minux** [comment]
Perhaps we should figure out why the build tool is treating the entry as a
directory instead.

**Comment by cyphar** [comment]
@minux I figured it out. It's not because of OBS, it's actually because if you run `strip` on a Go archive it will convert it to become invalid (and OBS automatically strips binaries in packages). We can fix this on the openSUSE side, but IMO a language's runtime breaking if you run `strip` on it is not the best thing in the world.

**Comment by cyphar** [comment]
Note that dropping `strip` has increased our package sizes by 4x. :cry:

**Comment by ianlancetaylor** [comment]
It does not make sense to run strip on an archive, whether the archive is Go or C.  Can you explain precisely what you are doing?

**Comment by cyphar** [comment]
@ianlancetaylor I'm trying to fix the Go installation in openSUSE. By default, the Open Build Service (openSUSE's build system) will run strip on every file which looks like a binary file. This is probably not the best idea in the world, and can be disabled. However, the reason for this is quite simple -- `strip` should not remove headers it doesn't know are safe to remove. It turns out however that `strip` changes the entries in a `.a` archive even after stating that it doesn't understand the entries. While this is a `strip` bug, it's also probably not a general bug (I find it hard to believe that this causes serious issues with C archives).

Since opening this issue I have fixed the core issue (stripping anything in the Go package). Now our Go package works perfectly fine. However, our Go package now is 45MB as opposed to the old size of 12MB. Which is a huge price to pay.

So, this issue needs to be fixed somewhere so that we can go back to stripping the binaries in our Go packages that are safe to strip.

**Comment by ianlancetaylor** [comment]
When I run `strip runtime.a` I see

    strip:runtime.a(__.PKGDEF): Unable to recognise the format of file: File format not recognized
    strip:runtime.a(_go_.o): Unable to recognise the format of file: File format not recognized
    strip:runtime.a(asm.o): Unable to recognise the format of file: File format not recognized

and the file size is unchanged.

Can you tell us precisely what you are doing to the archive to make it so much smaller?  I don't see how that is possible without breaking it.  Or, do you mean that the package gets smaller because you run strip on the executables?  In that case, keep running strip, just skip the .a files.  As the error messages show, strip doesn't understand Go .a files anyhow.

**Comment by cyphar** [comment]
@iangudger Check the `sha256sum` and you'll see it's different. I know that it produces an error message, but `strip` still modifies the archive:

```
% cp pkg/linux_amd64/runtime.a .
% strip ./runtime.a
strip:runtime.a(__.PKGDEF): Unable to recognise the format of file: File format not recognized
strip:runtime.a(_go_.o): Unable to recognise the format of file: File format not recognized
strip:runtime.a(asm.o): Unable to recognise the format of file: File format not recognized
% ls -la pkg/linux_amd64/runtime.a runtime.a
-rw-r--r-- 1 cyphar users 1490238 Nov 11 15:19 pkg/linux_amd64/runtime.a
-rw-r--r-- 1 cyphar users 1490238 Nov 12 15:11 runtime.a
% sha256sum pkg/linux_amd64/runtime.a runtime.a
4379f032997a03a8f443abfd26bd52c9d43c247c55acfd1a08388e34e6ae6add  pkg/linux_amd64/runtime.a
ec91aa9008898e9cf4a5b50f50d1f3f4980e184eba746f54b426b7ebc9e776e4  runtime.a
```

Namely what's happening is that `strip` is appending `/` to `__.PKGDEF`. I'm not sure what else is happening in the file to make the filesize not change, but I'm sure that this is what's changing. Just look:

```
% cat -v runtime.a | head -n2
!<arch>
__.PKGDEF/      1478923862  1000  100   100644  12766     `
% cat -v pkg/linux_amd64/runtime.a | head -n2
!<arch>
__.PKGDEF       0           0     0     644     12766     `
```

**Comment by cyphar** [comment]
@iangudger The problem is that the build system doesn't really give you a choice of what files to strip (I'm investigating that though). At the very least, I thought you might want to know what `strip` does to your archives...

**Comment by cyphar** [comment]
Actually, that script has several bugs in it. I will fix those, so this issue is not really applicable anymore.
