### ISSUE TITLE
net: TestAcceptTimeout flake

### ISSUE THREAD

**Issue by bradfitz** [golang/go#17927]
On Darwin: https://build.golang.org/log/27aab1b9073306540c0f424a645f3b2bd326a639
```
panic: Fail in goroutine after TestAcceptTimeout has completed

goroutine 918 [running]:
panic(0x1236860, 0xc42019a120)
	/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/runtime/panic.go:531 +0x1cf
testing.(*common).Fail(0xc4205e02a0)
	/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/testing/testing.go:464 +0x119
testing.(*common).Error(0xc4205e02a0, 0xc42020df40, 0x1, 0x1)
	/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/testing/testing.go:531 +0x6f
net.TestAcceptTimeout.func1(0x1399d80, 0xc4201c8080, 0x1399740, 0xc4200b6010, 0xc4205e02a0)
	/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/net/timeout_test.go:176 +0x19a
created by net.TestAcceptTimeout
	/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/net/timeout_test.go:182 +0x88f
FAIL	net	2.547s
```

/cc @mikioh

**Comment by bradfitz** [comment]
Still flaky. I opened #17948 with the new failures.
