### ISSUE TITLE
net: TestAcceptTimeout still flaky

### ISSUE THREAD

**Issue by bradfitz** [golang/go#17948]
`TestAcceptTimeout` is still flaky:

https://build.golang.org/log/74ef15095b884eff2e47c1d1ed91a7643c2424cb
```
panic: test timed out after 3m0s

goroutine 984 [running]:
panic(0x12368c0, 0xc420078150)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/runtime/panic.go:531 +0x1cf
testing.startAlarm.func1()
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:1041 +0xf9
created by time.goFunc
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/time/sleep.go:170 +0x44

goroutine 1 [chan receive, 2 minutes]:
testing.tRunner.func1(0xc4200c40e0)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:655 +0x17e
testing.tRunner(0xc4200c40e0, 0xc420051db8)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:681 +0x149
testing.runTests(0xc42008eee0, 0x13bb980, 0xd2, 0xd2, 0x0)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:906 +0x29d
testing.(*M).Run(0xc420193f20, 0x13d9200)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:841 +0xfc
net.TestMain(0xc420051f20)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/net/main_test.go:50 +0x39
main.main()
	net/_test/_testmain.go:506 +0xf7

goroutine 17 [syscall, 2 minutes, locked to thread]:
runtime.goexit()
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/runtime/asm_amd64.s:2184 +0x1

goroutine 848 [chan send, 2 minutes]:
testing.tRunner.func1(0xc42047a9a0)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:674 +0x208
testing.tRunner(0xc42047a9a0, 0x128ef18)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:681 +0x149
created by testing.(*T).Run
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:716 +0x2c7

goroutine 874 [chan send, 2 minutes]:
testing.tRunner.func1(0xc4200c4ee0)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:674 +0x208
testing.tRunner(0xc4200c4ee0, 0x128ef90)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:681 +0x149
created by testing.(*T).Run
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:716 +0x2c7

goroutine 859 [chan send, 2 minutes]:
testing.tRunner.func1(0xc4202a4460)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:674 +0x208
testing.tRunner(0xc4202a4460, 0x128f218)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:681 +0x149
created by testing.(*T).Run
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:716 +0x2c7

goroutine 858 [chan send, 2 minutes]:
testing.tRunner.func1(0xc4202a4380)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:674 +0x208
testing.tRunner(0xc4202a4380, 0x128eef0)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:681 +0x149
created by testing.(*T).Run
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:716 +0x2c7

goroutine 857 [chan send, 2 minutes]:
testing.tRunner.func1(0xc4202a42a0)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:674 +0x208
testing.tRunner(0xc4202a42a0, 0x128ef08)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:681 +0x149
created by testing.(*T).Run
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:716 +0x2c7

goroutine 854 [chan send, 2 minutes]:
testing.tRunner.func1(0xc4202a4000)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:674 +0x208
testing.tRunner(0xc4202a4000, 0x128f230)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:681 +0x149
created by testing.(*T).Run
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:716 +0x2c7

goroutine 856 [chan send, 2 minutes]:
testing.tRunner.func1(0xc4202a41c0)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:674 +0x208
testing.tRunner(0xc4202a41c0, 0x128f238)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:681 +0x149
created by testing.(*T).Run
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:716 +0x2c7

goroutine 868 [chan send, 2 minutes]:
testing.tRunner.func1(0xc4200c4a80)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:674 +0x208
testing.tRunner(0xc4200c4a80, 0x128e860)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:681 +0x149
created by testing.(*T).Run
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:716 +0x2c7

goroutine 866 [semacquire, 2 minutes]:
sync.runtime_Semacquire(0xc4200e678c)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/runtime/sema.go:47 +0x34
sync.(*WaitGroup).Wait(0xc4200e6780)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/sync/waitgroup.go:131 +0x73
net.TestAcceptTimeout(0xc4200c48c0)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/net/timeout_test.go:208 +0x3d6
testing.tRunner(0xc4200c48c0, 0x128e878)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:679 +0x13f
created by testing.(*T).Run
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:716 +0x2c7

goroutine 871 [chan send, 2 minutes]:
testing.tRunner.func1(0xc4200c4c40)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:674 +0x208
testing.tRunner(0xc4200c4c40, 0x128f1f8)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:681 +0x149
created by testing.(*T).Run
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:716 +0x2c7

goroutine 855 [chan send, 2 minutes]:
testing.tRunner.func1(0xc4202a40e0)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:674 +0x208
testing.tRunner(0xc4202a40e0, 0x128f228)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:681 +0x149
created by testing.(*T).Run
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:716 +0x2c7

goroutine 875 [chan send, 2 minutes]:
testing.tRunner.func1(0xc4200c4fc0)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:674 +0x208
testing.tRunner(0xc4200c4fc0, 0x128ef78)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:681 +0x149
created by testing.(*T).Run
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:716 +0x2c7

goroutine 867 [chan send, 2 minutes]:
testing.tRunner.func1(0xc4200c49a0)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:674 +0x208
testing.tRunner(0xc4200c49a0, 0x128e870)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:681 +0x149
created by testing.(*T).Run
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:716 +0x2c7

goroutine 978 [IO wait, 2 minutes]:
net.runtime_pollWait(0x1700900, 0x72, 0xb)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc4200d0538, 0x72, 0x1398580, 0x1396380)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc4200d0538, 0xc420078550, 0x1)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc4200d04d0, 0xc420078550, 0x1, 0x1, 0x0, 0x1398580, 0x1396380)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc4200f0038, 0xc420078550, 0x1, 0x1, 0x0, 0x0, 0x0)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/net/net.go:180 +0x70
net.TestAcceptTimeout.func1(0xc4200e6780, 0x1399740, 0xc4200ee040, 0xc4200c48c0)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/net/timeout_test.go:180 +0x205
created by net.TestAcceptTimeout
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/net/timeout_test.go:182 +0x84d

goroutine 941 [chan receive, 2 minutes]:
testing.runTests.func1.1(0xc4200c40e0)
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:905 +0x47
created by testing.runTests.func1
	/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/testing/testing.go:905 +0xaf
FAIL	net	180.040s
```

I'm just going to disable it for now. It's doing more harm than good.

**Comment by bradfitz** [comment]
Nope. Still flaky: freebsd-amd64-gce101 at 81627f0e47f91a6e6e7bfd7c59b4e3ac596668ca

**Comment by mikioh** [comment]
That's  a different issue. We fixed two issues: a) context-based canceling based on defer function execution behaves differently than previous versions on Darwin and FreeBSD, b) TCP control segments for active close operation at passive open side don't deliver immediately on Darwin, and now have c) "dial tcp 127.0.0.1:42120: i/o timeout" at active open side.

It's fine to move forward step by step, I'm not sure why the test starts behaving unbridledly during Go 1.8 development cycle, though. Does Go 1.8 contain massive changes to runtime, net or testing packages?

**Comment by bradfitz** [comment]
> That's a different issue.

In any case, it's still flaky.

> Does Go 1.8 contain massive changes to runtime, net or testing packages?

There have certainly been runtime changes. You would know whether there have been net changes. I don't think there have been notable testing changes.

**Comment by bcmills** [comment]
This test has been sitting in the tree with an unconditional skip for a long time. If it is actually useful we should fix it properly; otherwise we should get rid of it.
