### ISSUE TITLE
GOARCH=mips doesn't run on mips32r2

### ISSUE THREAD

**Issue by jech** [golang/go#17984]
Using go version devel +f39050c Fri Nov 18 20:44:52 2016 +0000 linux/amd64.

I've compiled everyone's favourite helloworld binary using

    GOARCH=mips go build

and attempted to run it on a router with a mips32r2 CPU (24Kc v7.4).  The binary immediately segfaults with SIGILL.

Gdb backtrace:

    #0  runtime.check () at /usr/local/src/go/src/runtime/runtime1.go:151
    #1  0x00063cb4 in runtime.rt0_go ()
        at /usr/local/src/go/src/runtime/asm_mipsx.s:48
    #2  0x00000000 in ?? ()

Disassembly of offending function:

    Dump of assembler code for function runtime.check:
       0x0004a724 <+0>:     8f c1 00 08     lw      at,8(s8)
       0x0004a728 <+4>:     00 3d 08 2b     sltu    at,at,sp
       0x0004a72c <+8>:     14 20 00 06     bnez    at,0x4a748 <runtime.check+36>
       0x0004a730 <+12>:    00 00 00 00     nop
       0x0004a734 <+16>:    03 e0 18 25     move    v1,ra
       0x0004a738 <+20>:    0c 01 8f e4     jal     0x63f90 <runtime.morestack_noctxt>
       0x0004a73c <+24>:    00 00 00 00     nop
       0x0004a740 <+28>:    10 00 ff f8     b       0x4a724 <runtime.check>
       0x0004a744 <+32>:    00 00 00 00     nop
       0x0004a748 <+36>:    af bf ff bc     sw      ra,-68(sp)
       0x0004a74c <+40>:    27 bd ff bc     addiu   sp,sp,-68
       0x0004a750 <+44>:    af a0 00 28     sw      zero,40(sp)
    => 0x0004a754 <+48>:    44 80 00 00     mtc1    zero,$f0
       0x0004a758 <+52>:    e7 a0 00 24     swc1    $f0,36(sp)
       0x0004a75c <+56>:    e7 a0 00 20     swc1    $f0,32(sp)
       0x0004a760 <+60>:    3c 17 00 0d     lui     s7,0xd
       0x0004a764 <+64>:    d6 e0 8a 98     ldc1    $f0,-30056(s7)
       0x0004a768 <+68>:    f7 a0 00 34     sdc1    $f0,52(sp)
       0x0004a76c <+72>:    f7 a0 00 2c     sdc1    $f0,44(sp)
       0x0004a770 <+76>:    af a0 00 40     sw      zero,64(sp)
       0x0004a774 <+80>:    a3 a0 00 1c     sb      zero,28(sp)

**Comment by jech** [comment]
Silly me, the target machine doesn't have an FPU.  I guess it's working as designed.
