### ISSUE TITLE
cmd/compile: internal compiler error: gen_as_init couldn't make data statement

### ISSUE THREAD

**Issue by cznic** [golang/go#17990]
### What version of Go are you using (`go version`)?

`go version go1.7.3 linux/amd64`

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/jnml"
GORACE=""
GOROOT="/home/jnml/go"
GOTOOLDIR="/home/jnml/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build788289581=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1
```

### What did you do?

```bash
jnml@4670:~$ go get github.com/cznic/c/internal/sqlite
```

### What did you expect to see?

Nothing, meaning `go get` succeeded or any non-internal compiler error.

### What did you see instead?

```
jnml@4670:~$ go get github.com/cznic/c/internal/sqlite
# github.com/cznic/c/internal/sqlite

gen_as_init [0xc420af2000]
.   AS u(2) l(12091) tc(1) dd(2)
.   .   DOT u(2) l(12091) x(8+0) tc(1) assigned sqlite.XpUserData TUNSAFEPTR-unsafe.Pointer
.   .   .   INDEX u(2) l(12216) tc(1) assigned bounded sqlite.TFuncDef
.   .   .   .   NAME-sqlite.statictmp_34 u(1) a(true) l(12216) x(0+0) class(PEXTERN) f(1) tc(1) assigned used(true) ARRAY-[8]TFuncDef
.   .   .   .   LITERAL-0 u(1) a(true) l(12088) tc(1) int
.   .   LITERAL-0 l(12091) tc(1) TUNSAFEPTR-unsafe.Pointer
.   .   .   LITERAL-0 l(12091) tc(1) uintptr
.   .   .   .   LITERAL-0 l(12091) tc(1) uintptr
src/github.com/cznic/c/internal/sqlite/sqlite64.go:12213: internal compiler error: gen_as_init couldn't make data statement

goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/home/jnml/go/src/runtime/debug/stack.go:24 +0x79
cmd/compile/internal/gc.Fatalf(0x90a6f4, 0x28, 0x0, 0x0, 0x0)
	/home/jnml/go/src/cmd/compile/internal/gc/subr.go:165 +0x248
cmd/compile/internal/gc.gen_as_init(0xc420af2000, 0x1, 0xc422afd9e0)
	/home/jnml/go/src/cmd/compile/internal/gc/sinit.go:1356 +0xb8
cmd/compile/internal/gc.(*state).stmt(0xc422afd9e0, 0xc420af2000)
	/home/jnml/go/src/cmd/compile/internal/gc/ssa.go:659 +0x10f
cmd/compile/internal/gc.(*state).stmtList(0xc422afd9e0, 0xc420c097a0)
	/home/jnml/go/src/cmd/compile/internal/gc/ssa.go:542 +0x5e
cmd/compile/internal/gc.(*state).stmt(0xc422afd9e0, 0xc4203b15f0)
	/home/jnml/go/src/cmd/compile/internal/gc/ssa.go:561 +0xd1
cmd/compile/internal/gc.(*state).stmts(0xc422afd9e0, 0xc420c08720)
	/home/jnml/go/src/cmd/compile/internal/gc/ssa.go:535 +0x5e
cmd/compile/internal/gc.buildssa(0xc420cdc000, 0x0)
	/home/jnml/go/src/cmd/compile/internal/gc/ssa.go:182 +0x6c0
cmd/compile/internal/gc.compile(0xc420cdc000)
	/home/jnml/go/src/cmd/compile/internal/gc/pgen.go:405 +0x1377
cmd/compile/internal/gc.funccompile(0xc420cdc000)
	/home/jnml/go/src/cmd/compile/internal/gc/dcl.go:1287 +0x186
cmd/compile/internal/gc.Main()
	/home/jnml/go/src/cmd/compile/internal/gc/main.go:467 +0x19f8
cmd/compile/internal/amd64.Main()
	/home/jnml/go/src/cmd/compile/internal/amd64/galign.go:93 +0x2fa
main.main()
	/home/jnml/go/src/cmd/compile/main.go:33 +0x2a3

jnml@4670:~$ 
```
### Additional info

Applies to https://github.com/cznic/c/commit/78de003e7103331de74cee3396b906708c460d3d

**Comment by dhananjay92** [comment]
Looks like a duplicate of #16306 which has been fixed. Could not reproduce the error at https://github.com/golang/go/commit/7dc97d9e328edc800e2ce41d5b211ef4e0ef41d0

**Comment by cznic** [comment]
Thank you. How could I forgot to check with tip? Closing.
