### ISSUE TITLE
html/template Execute not working concurrently. text/template works as expected.

### ISSUE THREAD

**Issue by curtiscovington** [golang/go#18065]
### What version of Go are you using (`go version`)?
go version go1.7.3 darwin/amd64

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

This problem occurs when hitting an endpoint concurrently
https://play.golang.org/p/A2ctbqJa1Z

Line 80 is the endpoint that is executing. But the problem happens on all endpoints except "/" where I specifically clone the template on every request. 

Switching to text/template eliminates the problem.

### What did you expect to see?
I expect template.Execute to be executed safely concurrently as the documentation describes.

### What did you see instead?
```
fatal error: concurrent map read and map write

goroutine 45 [running]:
runtime.throw(0x391f1c, 0x21)
	/usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc420051738 sp=0xc420051718
runtime.mapaccess1_faststr(0x327d80, 0xc420011e00, 0xc42012be76, 0x7, 0xd58c0)
	/usr/local/go/src/runtime/hashmap_fast.go:201 +0x4f3 fp=0xc420051798 sp=0xc420051738
text/template.(*state).walkTemplate(0xc420051a08, 0x34a0e0, 0xc4213b9e90, 0x99, 0xc420015640)
	/usr/local/go/src/text/template/exec.go:369 +0x9a fp=0xc420051868 sp=0xc420051798
text/template.(*state).walk(0xc420051a08, 0x34a0e0, 0xc4213b9e90, 0x99, 0x5075e0, 0xc420015640)
	/usr/local/go/src/text/template/exec.go:239 +0x24c fp=0xc4200518f0 sp=0xc420051868
text/template.(*state).walk(0xc420051a08, 0x34a0e0, 0xc4213b9e90, 0x99, 0x5073a0, 0xc420154030)
	/usr/local/go/src/text/template/exec.go:234 +0x13d fp=0xc420051978 sp=0xc4200518f0
text/template.(*Template).execute(0xc420015180, 0x5018a0, 0xc420a496c0, 0x34a0e0, 0xc4213b9e90, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:189 +0x204 fp=0xc420051a60 sp=0xc420051978
text/template.(*Template).Execute(0xc420015180, 0x5018a0, 0xc420a496c0, 0x34a0e0, 0xc4213b9e90, 0xc4213b9e90, 0xc420051b80)
	/usr/local/go/src/text/template/exec.go:175 +0x53 fp=0xc420051aa8 sp=0xc420051a60
html/template.(*Template).Execute(0xc420011f50, 0x5018a0, 0xc420a496c0, 0x34a0e0, 0xc4213b9e90, 0x1, 0xc420a465a0)
	/usr/local/go/src/html/template/template.go:104 +0x78 fp=0xc420051af0 sp=0xc420051aa8
main.main.func1(0x5059e0, 0xc420a496c0, 0xc420a465a0)
	/Users/curtiscovington/Documents/go/src/github.com/curtiscovington/curtiscovington.com/main.go:65 +0x1a9 fp=0xc420051bb8 sp=0xc420051af0
net/http.HandlerFunc.ServeHTTP(0x3b4230, 0x5059e0, 0xc420a496c0, 0xc420a465a0)
	/usr/local/go/src/net/http/server.go:1726 +0x44 fp=0xc420051be0 sp=0xc420051bb8
github.com/gorilla/mux.(*Router).ServeHTTP(0xc420016f50, 0x5059e0, 0xc420a496c0, 0xc420a465a0)
	/Users/curtiscovington/Documents/go/src/github.com/gorilla/mux/mux.go:114 +0x10d fp=0xc420051ce0 sp=0xc420051be0
net/http.serverHandler.ServeHTTP(0xc42016e000, 0x5059e0, 0xc420a496c0, 0xc420a463c0)
	/usr/local/go/src/net/http/server.go:2202 +0x7d fp=0xc420051d28 sp=0xc420051ce0
net/http.(*conn).serve(0xc42007ea80, 0x5061e0, 0xc42007b0c0)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7 fp=0xc420051f88 sp=0xc420051d28
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420051f90 sp=0xc420051f88
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d
```

**Comment by kardianos** [comment]
It looks like you have a map that is written to in a racy way. Please test with the race detector on.

**Comment by curtiscovington** [comment]
I tested that and noticed it pointing me to the html/template escape methods. Nothing is being written to the map by my code, it is all internal to the html/template as far as I can see.

**Comment by curtiscovington** [comment]
@kardianos 
```WARNING: DATA RACE
Write at 0x00c42014c330 by goroutine 17:
  runtime.mapassign1()
      /usr/local/go/src/runtime/hashmap.go:442 +0x0
  text/template.(*Template).associate()
      /usr/local/go/src/text/template/template.go:216 +0x166
  text/template.(*Template).AddParseTree()
      /usr/local/go/src/text/template/template.go:128 +0x26c
  html/template.(*escaper).commit()
      /usr/local/go/src/html/template/escape.go:746 +0x30c
  html/template.escapeTemplate()
      /usr/local/go/src/html/template/escape.go:39 +0x4fd
  html/template.(*Template).escape()
      /usr/local/go/src/html/template/template.go:85 +0x2fb
  html/template.(*Template).Execute()
      /usr/local/go/src/html/template/template.go:101 +0x3c
  main.handleBlogIndex()
      /Users/curtiscovington/Documents/go/src/github.com/curtiscovington/curtiscovington.com/main.go:186 +0x1e2
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:1726 +0x51
  github.com/gorilla/mux.(*Router).ServeHTTP()
      /Users/curtiscovington/Documents/go/src/github.com/gorilla/mux/mux.go:114 +0x18d
  net/http.serverHandler.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2202 +0xbb
  net/http.(*conn).serve()
      /usr/local/go/src/net/http/server.go:1579 +0x5f6

Previous read at 0x00c42014c330 by goroutine 16:
  runtime.mapaccess1_faststr()
      /usr/local/go/src/runtime/hashmap_fast.go:192 +0x0
  text/template.(*state).walkTemplate()
      /usr/local/go/src/text/template/exec.go:369 +0x12b
  text/template.(*state).walk()
      /usr/local/go/src/text/template/exec.go:239 +0x3a4
  text/template.(*state).walk()
      /usr/local/go/src/text/template/exec.go:234 +0x1f7
  text/template.(*Template).execute()
      /usr/local/go/src/text/template/exec.go:189 +0x4a2
  text/template.(*Template).Execute()
      /usr/local/go/src/text/template/exec.go:175 +0x64
  html/template.(*Template).Execute()
      /usr/local/go/src/html/template/template.go:104 +0xd0
  main.handleBlogIndex()
      /Users/curtiscovington/Documents/go/src/github.com/curtiscovington/curtiscovington.com/main.go:186 +0x1e2
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:1726 +0x51
  github.com/gorilla/mux.(*Router).ServeHTTP()
      /Users/curtiscovington/Documents/go/src/github.com/gorilla/mux/mux.go:114 +0x18d
  net/http.serverHandler.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2202 +0xbb
  net/http.(*conn).serve()
      /usr/local/go/src/net/http/server.go:1579 +0x5f6```

**Comment by kardianos** [comment]
`text/template` is safe for concurrent *execution*. It is *not* safe for concurrent parse and execution. I looked at what you posed, however I suspect the issue is that in `github.com/curtiscovington/curtiscovington.com` you are doing a re-parse before execution. So when you have two concurrent requests, one ends up in the parse, the other is executing. Throw a mutex around each step if you want to do that.

**Comment by curtiscovington** [comment]
I can't tell where I would be reparsing it. I parse all my files once in main, and then store them in a map. And then in my handler I call the execute method on the stored template. 

```go
get.HandleFunc("/contact", func(w http.ResponseWriter, r *http.Request) {
		templates["contact.html"].Execute(w, Page{r, "contact", nil})
	})

```
Something like this. No where else is it parsing, to the best of my knowledge. Unless I am missing something behind the scenes.

**Comment by cespare** [comment]
This sounds like #16101.

@curtiscovington can you try Go tip and confirm that the problem is fixed there?
