### ISSUE TITLE
panic: encoding unexpected fault

### ISSUE THREAD

**Issue by oiooj** [golang/go#18062]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version 1.7.3

### What operating system and processor architecture are you using (`go env`)?
ubuntu 14.04 on circleCI

### What did you do?

panic when I encode my data.(and I rebuild , didn't reproduc)

```
unexpected fault address 0x7fb900e32170
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7fb900e32170 pc=0x5b08a8]

goroutine 28 [running]:
runtime.throw(0x83b1e7, 0x5)
	/usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc420048c40 sp=0xc420048c20
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:27 +0x288 fp=0xc420048c98 sp=0xc420048c40
encoding/base64.(*Encoding).Encode(0xc42007a160, 0xc42012def0, 0x44, 0x44, 0x7fb900e32170, 0x33, 0x33)
	/usr/local/go/src/encoding/base64/base64.go:102 +0x68 fp=0xc420048ca0 sp=0xc420048c98
encoding/json.encodeByteSlice(0xc4200e68f0, 0x7a57a0, 0xc42012deb8, 0x197, 0x100)
	/usr/local/go/src/encoding/json/encode.go:675 +0x1aa fp=0xc420048d28 sp=0xc420048ca0
encoding/json.(*structEncoder).encode(0xc4202ba090, 0xc4200e68f0, 0x7f26c0, 0xc42012dea0, 0x199, 0x100)
	/usr/local/go/src/encoding/json/encode.go:601 +0x253 fp=0xc420048e88 sp=0xc420048d28
encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc4200e68f0, 0x7f26c0, 0xc42012dea0, 0x199, 0x7f0100)
	/usr/local/go/src/encoding/json/encode.go:615 +0x64 fp=0xc420048ec8 sp=0xc420048e88
encoding/json.(*arrayEncoder).encode(0xc4200282f8, 0xc4200e68f0, 0x7a34a0, 0xc42035d908, 0x197, 0x100)
	/usr/local/go/src/encoding/json/encode.go:723 +0xee fp=0xc420048f20 sp=0xc420048ec8
encoding/json.(*arrayEncoder).(encoding/json.encode)-fm(0xc4200e68f0, 0x7a34a0, 0xc42035d908, 0x197, 0x780100)
	/usr/local/go/src/encoding/json/encode.go:730 +0x64 fp=0xc420048f60 sp=0xc420048f20
encoding/json.(*sliceEncoder).encode(0xc420028300, 0xc4200e68f0, 0x7a34a0, 0xc42035d908, 0x197, 0x100)
	/usr/local/go/src/encoding/json/encode.go:697 +0xc1 fp=0xc420048fa0 sp=0xc420048f60
encoding/json.(*sliceEncoder).(encoding/json.encode)-fm(0xc4200e68f0, 0x7a34a0, 0xc42035d908, 0x197, 0x100)
	/usr/local/go/src/encoding/json/encode.go:709 +0x64 fp=0xc420048fe0 sp=0xc420048fa0
encoding/json.(*structEncoder).encode(0xc420111f50, 0xc4200e68f0, 0x7e50e0, 0xc42035d8f0, 0x199, 0x100)
	/usr/local/go/src/encoding/json/encode.go:601 +0x253 fp=0xc420049140 sp=0xc420048fe0
encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc4200e68f0, 0x7e50e0, 0xc42035d8f0, 0x199, 0xc420350100)
	/usr/local/go/src/encoding/json/encode.go:615 +0x64 fp=0xc420049180 sp=0xc420049140
encoding/json.(*ptrEncoder).encode(0xc420028308, 0xc4200e68f0, 0x797320, 0xc42035d8f0, 0x16, 0x790100)
	/usr/local/go/src/encoding/json/encode.go:742 +0xe3 fp=0xc4200491c0 sp=0xc420049180
encoding/json.(*ptrEncoder).(encoding/json.encode)-fm(0xc4200e68f0, 0x797320, 0xc42035d8f0, 0x16, 0xc420350100)
	/usr/local/go/src/encoding/json/encode.go:747 +0x64 fp=0xc420049200 sp=0xc4200491c0
encoding/json.(*encodeState).reflectValue(0xc4200e68f0, 0x797320, 0xc42035d8f0, 0x16, 0x100)
	/usr/local/go/src/encoding/json/encode.go:307 +0x82 fp=0xc420049238 sp=0xc420049200
encoding/json.(*encodeState).marshal(0xc4200e68f0, 0x797320, 0xc42035d8f0, 0x100, 0x0, 0x0)
	/usr/local/go/src/encoding/json/encode.go:280 +0xb8 fp=0xc420049270 sp=0xc420049238
encoding/json.Marshal(0x797320, 0xc42035d8f0, 0x0, 0xc42001af00, 0x5f3bb1, 0xc420049310, 0x410a78)
	/usr/local/go/src/encoding/json/encode.go:145 +0x8f fp=0xc4200492b8 sp=0xc420049270

```

**Comment by bradfitz** [comment]
There isn't really enough information to help you here.

Either include a reproduction case, or see https://golang.org/wiki/Questions for general help about Go. Confirm you also don't have data races. (Use the race detector... any reported problems?)

Feel free to reopen this once there's something actionable for us.
