### ISSUE TITLE
Slice bounds out of range during CGO callback in go 1.7.1

### ISSUE THREAD

**Issue by adamfaulkner** [golang/go#18206]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go 1.7.1

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
TERM="dumb"
CC="gcc"
GOGCCFLAGS="-g -O2 -fPIC -m64 -pthread"
CXX="g++"
CGO_ENABLED="1"

### What did you do?

I have a program that spends a lot of time doing CGO callbacks. Roughly 3% of the time, it will crash with slice bounds out of range. This code does not crash when using go 1.6.

I've set GOTRACEBACK=crash, and uncovered that this slice bounds out of range is occurring here: 
https://golang.org/src/runtime/mstkbar.go#L227

Using gdb, I've found that stkbar has a len of 0 in all cases, and stkbarPos is greater than 0. (Interestingly, in all cases that I've inspected, stkbarPos is less than cap(stkbar)). It doesn't seem likely that my c function is corrupting this data.

Is it possible that there's a race happening between these cgo callbacks and some other thread that modifies these?

Here is how my cgo callbacks are declared:

in one file:
```
/*
extern char* fullMerge(void* s, const char* key, size_t key_length,
                        const char* existing_value,
                        size_t existing_value_length,
                        const char* const* operands_list,
                        const size_t* operands_list_length, int num_operands,
                        unsigned char* success, size_t* new_value_length);
*/
import "C"
```

in another file:
```
//export fullMerge
func fullMerge(
	state unsafe.Pointer,
	key *C.char,
	key_length C.size_t,
	existing_value *C.char,
	existing_value_length C.size_t,
	operands_list **C.char,
	operands_list_length *C.size_t,
	num_operands C.int,
	success *C.char,
	new_value_length *C.size_t) *C.char {
```

I'm going to try updating to go 1.7.4 and seeing if that fixes the issue since that's a possibility. 

I'm also trying to find a more minimal example to share, since this one is very intertwined with a lot of my company's code and takes 5 hours to run, and only crashes 3% of the time. I'll update this if I get such an example.

### What did you expect to see?
I expected the program to not crash inside the runtime.

### What did you see instead?
The program crashed with this stack trace.

```
goroutine 6729 [runnable (scan), locked to thread]:
panic: runtime error: slice bounds out of range
fatal error: panic on system stack
panic during panic

runtime stack:
runtime.startpanic_m()
        /home/pusher/.cache/bazel/_bazel_pusher/d26e8814cab9e74e386bf0f4b1add632/execroot/server/external/go1_7_1_linux_amd64_tar_gz/go/src/runtime/panic.go:623 +0xfc fp=0x7fd7e1ffd230 sp=0x7fd7e1ffd200
runtime.systemstack(0x14151b8)
        /home/pusher/.cache/bazel/_bazel_pusher/d26e8814cab9e74e386bf0f4b1add632/execroot/server/external/go1_7_1_linux_amd64_tar_gz/go/src/runtime/asm_amd64.s:314 +0xab fp=0x7fd7e1ffd238 sp=0x7fd7e1ffd230
runtime.startpanic()
        /home/pusher/.cache/bazel/_bazel_pusher/d26e8814cab9e74e386bf0f4b1add632/execroot/server/external/go1_7_1_linux_amd64_tar_gz/go/src/runtime/panic.go:544 +0x1e fp=0x7fd7e1ffd250 sp=0x7fd7e1ffd238
runtime.throw(0x138ef85, 0x15)
        /home/pusher/.cache/bazel/_bazel_pusher/d26e8814cab9e74e386bf0f4b1add632/execroot/server/external/go1_7_1_linux_amd64_tar_gz/go/src/runtime/panic.go:565 +0x88 fp=0x7fd7e1ffd270 sp=0x7fd7e1ffd250
panic(0x1248100, 0xc4200120b0)
        /home/pusher/.cache/bazel/_bazel_pusher/d26e8814cab9e74e386bf0f4b1add632/execroot/server/external/go1_7_1_linux_amd64_tar_gz/go/src/runtime/panic.go:389 +0x6d2 fp=0x7fd7e1ffd300 sp=0x7fd7e1ffd270
runtime.panicslice()
        /home/pusher/.cache/bazel/_bazel_pusher/d26e8814cab9e74e386bf0f4b1add632/execroot/server/external/go1_7_1_linux_amd64_tar_gz/go/src/runtime/panic.go:34 +0x6d fp=0x7fd7e1ffd330 sp=0x7fd7e1ffd300
runtime.gentraceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc4249124e0, 0x0, 0x0, 0x64, 0x0, 0x0, 0x0, ...)
        /home/pusher/.cache/bazel/_bazel_pusher/d26e8814cab9e74e386bf0f4b1add632/execroot/server/external/go1_7_1_linux_amd64_tar_gz/go/src/runtime/traceback.go:149 +0x1aa1 fp=0x7fd7e1ffd5b8 sp=0x7fd7e1ffd330
runtime.traceback1(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc4249124e0, 0x0)
        /home/pusher/.cache/bazel/_bazel_pusher/d26e8814cab9e74e386bf0f4b1add632/execroot/server/external/go1_7_1_linux_amd64_tar_gz/go/src/runtime/traceback.go:661 +0x121 fp=0x7fd7e1ffd720 sp=0x7fd7e1ffd5b8
runtime.traceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc4249124e0)
        /home/pusher/.cache/bazel/_bazel_pusher/d26e8814cab9e74e386bf0f4b1add632/execroot/server/external/go1_7_1_linux_amd64_tar_gz/go/src/runtime/traceback.go:622 +0x52 fp=0x7fd7e1ffd758 sp=0x7fd7e1ffd720
runtime.tracebackothers(0xc42044eb60)
        /home/pusher/.cache/bazel/_bazel_pusher/d26e8814cab9e74e386bf0f4b1add632/execroot/server/external/go1_7_1_linux_amd64_tar_gz/go/src/runtime/traceback.go:785 +0x1d2 fp=0x7fd7e1ffd7c0 sp=0x7fd7e1ffd758
runtime.dopanic_m(0xc42044eb60, 0x54d435, 0x7fd7e1ffd898)
        /home/pusher/.cache/bazel/_bazel_pusher/d26e8814cab9e74e386bf0f4b1add632/execroot/server/external/go1_7_1_linux_amd64_tar_gz/go/src/runtime/panic.go:669 +0x2a2 fp=0x7fd7e1ffd820 sp=0x7fd7e1ffd7c0
runtime.dopanic.func1()
        /home/pusher/.cache/bazel/_bazel_pusher/d26e8814cab9e74e386bf0f4b1add632/execroot/server/external/go1_7_1_linux_amd64_tar_gz/go/src/runtime/panic.go:553 +0x3c fp=0x7fd7e1ffd848 sp=0x7fd7e1ffd820
runtime.systemstack(0x7fd7e1ffd868)
        /home/pusher/.cache/bazel/_bazel_pusher/d26e8814cab9e74e386bf0f4b1add632/execroot/server/external/go1_7_1_linux_amd64_tar_gz/go/src/runtime/asm_amd64.s:314 +0xab fp=0x7fd7e1ffd850 sp=0x7fd7e1ffd848
runtime.dopanic(0x0)
        /home/pusher/.cache/bazel/_bazel_pusher/d26e8814cab9e74e386bf0f4b1add632/execroot/server/external/go1_7_1_linux_amd64_tar_gz/go/src/runtime/panic.go:554 +0x70 fp=0x7fd7e1ffd898 sp=0x7fd7e1ffd850
runtime.throw(0x138ef85, 0x15)
        /home/pusher/.cache/bazel/_bazel_pusher/d26e8814cab9e74e386bf0f4b1add632/execroot/server/external/go1_7_1_linux_amd64_tar_gz/go/src/runtime/panic.go:566 +0x95 fp=0x7fd7e1ffd8b8 sp=0x7fd7e1ffd898
panic(0x1248100, 0xc4200120b0)
        /home/pusher/.cache/bazel/_bazel_pusher/d26e8814cab9e74e386bf0f4b1add632/execroot/server/external/go1_7_1_linux_amd64_tar_gz/go/src/runtime/panic.go:389 +0x6d2 fp=0x7fd7e1ffd948 sp=0x7fd7e1ffd8b8
runtime.panicslice()
        /home/pusher/.cache/bazel/_bazel_pusher/d26e8814cab9e74e386bf0f4b1add632/execroot/server/external/go1_7_1_linux_amd64_tar_gz/go/src/runtime/panic.go:34 +0x6d fp=0x7fd7e1ffd978 sp=0x7fd7e1ffd948
runtime.gcRemoveStackBarriers(0xc4249124e0)
        /home/pusher/.cache/bazel/_bazel_pusher/d26e8814cab9e74e386bf0f4b1add632/execroot/server/external/go1_7_1_linux_amd64_tar_gz/go/src/runtime/mstkbar.go:227 +0xe4 fp=0x7fd7e1ffd9b8 sp=0x7fd7e1ffd978
runtime.scanstack(0xc4249124e0, 0xc42001b228)
        /home/pusher/.cache/bazel/_bazel_pusher/d26e8814cab9e74e386bf0f4b1add632/execroot/server/external/go1_7_1_linux_amd64_tar_gz/go/src/runtime/mgcmark.go:720 +0x146 fp=0x7fd7e1ffdb98 sp=0x7fd7e1ffd9b8
runtime.scang(0xc4249124e0, 0xc42001b228)
        /home/pusher/.cache/bazel/_bazel_pusher/d26e8814cab9e74e386bf0f4b1add632/execroot/server/external/go1_7_1_linux_amd64_tar_gz/go/src/runtime/proc.go:828 +0x14b fp=0x7fd7e1ffdbd0 sp=0x7fd7e1ffdb98
runtime.markroot.func1()
        /home/pusher/.cache/bazel/_bazel_pusher/d26e8814cab9e74e386bf0f4b1add632/execroot/server/external/go1_7_1_linux_amd64_tar_gz/go/src/runtime/mgcmark.go:236 +0x6d fp=0x7fd7e1ffdc10 sp=0x7fd7e1ffdbd0
runtime.systemstack(0xc42044eba0)
        /home/pusher/.cache/bazel/_bazel_pusher/d26e8814cab9e74e386bf0f4b1add632/execroot/server/external/go1_7_1_linux_amd64_tar_gz/go/src/runtime/asm_amd64.s:298 +0x79 fp=0x7fd7e1ffdc18 sp=0x7fd7e1ffdc10
runtime.mstart()
        /home/pusher/.cache/bazel/_bazel_pusher/d26e8814cab9e74e386bf0f4b1add632/execroot/server/external/go1_7_1_linux_amd64_tar_gz/go/src/runtime/proc.go:1079 fp=0x7fd7e1ffdc20 sp=0x7fd7e1ffdc18
```

Please let me know what else you'd like to see.

**Comment by bradfitz** [comment]
Please try Go 1.8beta1. We're not making any changes to Go 1.7 in any case.

**Comment by adamfaulkner** [comment]
Go 1.8 beta 1 fixed the issue, it seems. Since the panic was related to stack barriers, and it looks like a lot of related things changed substantially, it's unclear exactly what the cause and fix for my issue was.

Anyway, thanks for the suggestion, I've spent entirely too much time tracking this down.
