### ISSUE TITLE
net/http: test panic on linux-386

### ISSUE THREAD

**Issue by broady** [golang/go#18801]
While cutting 1.7.5:

```
panic: Fail in goroutine after TestIdleConnH2Crash has completed

goroutine 6665 [running]:
panic(0x83f0620, 0x18ae4330)
        /tmp/workdir/go/src/runtime/panic.go:500 +0x331
testing.(*common).Fail(0x18e30300)
        /tmp/workdir/go/src/testing/testing.go:412 +0x10d
testing.(*common).Error(0x18e30300, 0x1894ac14, 0x1, 0x1)
        /tmp/workdir/go/src/testing/testing.go:478 +0x61
net/http_test.TestIdleConnH2Crash.func2(0x84460d3, 0x3, 0x18c513c8, 0xf, 0x0, 0x0, 0x0, 0x0)
        /tmp/workdir/go/src/net/http/transport_test.go:3545 +0x1d9
net/http.(*Transport).dialConn(0x18b140a0, 0x85d8680, 0x18c51460, 0x0, 0x18c513c0, 0x5, 0x18c513c8, 0xf, 0x0, 0x0, ...)
        /tmp/workdir/go/src/net/http/transport.go:949 +0x3c5
net/http.(*Transport).getConn.func4(0x18b140a0, 0x85d8680, 0x18c51460, 0x18c514a0, 0x18b4a500)
        /tmp/workdir/go/src/net/http/transport.go:885 +0x48
created by net/http.(*Transport).getConn
        /tmp/workdir/go/src/net/http/transport.go:887 +0x3a0
FAIL    net/http        16.102s
```

**Comment by bradfitz** [comment]
Yeah, test looks like it could use work. It's also full of typos. Will fix, thanks.

**Comment by ianlancetaylor** [comment]
Just saw this failure on OpenBSD:

    --- FAIL: TestIdleConnH2Crash (0.06s)
    	transport_test.go:3742: write tcp 127.0.0.1:42762->127.0.0.1:4536: write: socket is not connected
    FAIL
    FAIL	net/http	5.203s

https://storage.googleapis.com/go-build-log/b809bbbc/openbsd-amd64-60_156a748f.log

**Comment by rsc** [comment]
Timed out.
