### ISSUE TITLE
runtime: timeout in runtime/pprof on linux-amd64-race

### ISSUE THREAD

**Issue by dsnet** [golang/go#18884]
Seen on http://golang.org/cl/35556

Relevant builder log: https://storage.googleapis.com/go-build-log/6c32b15d/linux-amd64-race_9d799fd7.log

```
panic: test timed out after 3m0s

goroutine 98 [running]:
testing.startAlarm.func1()
	/tmp/workdir/go/src/testing/testing.go:1024 +0x139
created by time.goFunc
	/tmp/workdir/go/src/time/sleep.go:170 +0x52

goroutine 1 [chan receive, 3 minutes]:
testing.(*T).Run(0xc42009c680, 0x67a2e9, 0x16, 0x6826f0, 0xc42006dc01)
	/tmp/workdir/go/src/testing/testing.go:700 +0x599
testing.runTests.func1(0xc42009c680)
	/tmp/workdir/go/src/testing/testing.go:883 +0xab
testing.tRunner(0xc42009c680, 0xc42006dd78)
	/tmp/workdir/go/src/testing/testing.go:657 +0x108
testing.runTests(0xc4200a89c0, 0x7916a0, 0xa, 0xa, 0x98)
	/tmp/workdir/go/src/testing/testing.go:889 +0x4e1
testing.(*M).Run(0xc42006df28, 0xc42006ded0)
	/tmp/workdir/go/src/testing/testing.go:824 +0x1c4
main.main()
	runtime/pprof/_test/_testmain.go:62 +0x210

goroutine 17 [syscall, 3 minutes, locked to thread]:
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 50 [syscall]:
syscall.Syscall6(0xf7, 0x1, 0x2ad6, 0xc42005fbc8, 0x1000004, 0x0, 0x0, 0x0, 0x0, 0xc42005fbf8)
	/tmp/workdir/go/src/syscall/asm_linux_amd64.s:44 +0x5
os.(*Process).blockUntilWaitable(0xc420010300, 0xc420010300, 0x0, 0x0)
	/tmp/workdir/go/src/os/wait_waitid.go:28 +0xcd
os.(*Process).wait(0xc420010300, 0xc4200e4120, 0xc420010300, 0xc420096240)
	/tmp/workdir/go/src/os/exec_unix.go:22 +0x72
os.(*Process).Wait(0xc420010300, 0xc4200e40b0, 0x43529a, 0xc4200e40a0)
	/tmp/workdir/go/src/os/exec.go:115 +0x39
os/exec.(*Cmd).Wait(0xc4200e4000, 0x0, 0x0)
	/tmp/workdir/go/src/os/exec/exec.go:435 +0xf0
os/exec.(*Cmd).Run(0xc4200e4000, 0x68, 0x1)
	/tmp/workdir/go/src/os/exec/exec.go:280 +0x87
os/exec.(*Cmd).CombinedOutput(0xc4200e4000, 0x35, 0xc420516758, 0x1, 0x1, 0xc4200e4000)
	/tmp/workdir/go/src/os/exec/exec.go:495 +0x2ba
runtime/pprof_test.TestCPUProfileWithFork(0xc4203b80d0)
	/tmp/workdir/go/src/runtime/pprof/pprof_test.go:275 +0x339
testing.tRunner(0xc4203b80d0, 0x6826f0)
	/tmp/workdir/go/src/testing/testing.go:657 +0x108
created by testing.(*T).Run
	/tmp/workdir/go/src/testing/testing.go:699 +0x55b

goroutine 89 [syscall, 3 minutes]:
runtime.CPUProfile(0xc4200d6070, 0x68, 0x793b80)
	/tmp/workdir/go/src/runtime/cpuprof.go:448 +0x2d
runtime/pprof.profileWriter(0x778760, 0xc42008e000)
	/tmp/workdir/go/src/runtime/pprof/pprof.go:701 +0xbe
created by runtime/pprof.StartCPUProfile
	/tmp/workdir/go/src/runtime/pprof/pprof.go:688 +0x16b

goroutine 114 [syscall]:
syscall.Syscall(0x0, 0x4, 0xc42051c400, 0x200, 0x7f4d7acb6d98, 0xc42051c000, 0x301000061c8d2)
	/tmp/workdir/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x4, 0xc42051c400, 0x200, 0x200, 0x200, 0xc42051c400, 0x7f4d7acb6d98)
	/tmp/workdir/go/src/syscall/zsyscall_linux_amd64.go:783 +0x63
syscall.Read(0x4, 0xc42051c400, 0x200, 0x200, 0x7f4d7adaa4b0, 0x0, 0x0)
	/tmp/workdir/go/src/syscall/syscall_unix.go:162 +0x5b
os.(*File).read(0xc42000e018, 0xc42051c400, 0x200, 0x200, 0xc420528820, 0x0, 0x0)
	/tmp/workdir/go/src/os/file_unix.go:165 +0x83
os.(*File).Read(0xc42000e018, 0xc42051c400, 0x200, 0x200, 0x0, 0x0, 0x1)
	/tmp/workdir/go/src/os/file.go:101 +0xd0
bytes.(*Buffer).ReadFrom(0xc42008e070, 0x7788e0, 0xc42000e018, 0x7f4d7acbc3b0, 0xc42008e070, 0x1)
	/tmp/workdir/go/src/bytes/buffer.go:179 +0x1bd
io.copyBuffer(0x778760, 0xc42008e070, 0x7788e0, 0xc42000e018, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/workdir/go/src/io/io.go:384 +0x35b
io.Copy(0x778760, 0xc42008e070, 0x7788e0, 0xc42000e018, 0x0, 0x0, 0x0)
	/tmp/workdir/go/src/io/io.go:360 +0x7f
os/exec.(*Cmd).writerDescriptor.func1(0x482681, 0x0)
	/tmp/workdir/go/src/os/exec/exec.go:254 +0x69
os/exec.(*Cmd).Start.func1(0xc4200e4000, 0xc42000c620)
	/tmp/workdir/go/src/os/exec/exec.go:371 +0x39
created by os/exec.(*Cmd).Start
	/tmp/workdir/go/src/os/exec/exec.go:372 +0x925
FAIL	runtime/pprof	236.885s
2017/02/01 19:21:33 Failed: exit status 1
```

**Comment by dsnet** [comment]
\cc @ianlancetaylor @matloob

**Comment by bcmills** [comment]
This report is quite old, and `watchflakes` will file a new issue for this failure mode if it recurs. Closing as obsolete.
