### ISSUE TITLE
cmd/compile: SIGSEGV on bytes.Join([][]byte{....})

### ISSUE THREAD

**Issue by navytux** [golang/go#19056]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?

Hello up there. For the following test program today's compiler crashes with SIGSEGV:

```go
package main

import (
        "bytes"
)

func main() {
        bytes.Join([][]byte{....})       // TODO
}
```

(https://play.golang.org/p/4IchXL12Df)

#### What did you expect to see?

Just error message, like e.g.:

```
kirr@deco:~/tmp/trashme/t$ go18 build x.go 
# command-line-arguments
./x.go:8: syntax error: unexpected ..., expecting expression
```

#### What did you see instead?

```
kirr@deco:~/tmp/trashme/t$ go build x.go 
# command-line-arguments
./x.go:8: syntax error: unexpected ..., expecting expression
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x823744]

goroutine 5 [running]:
cmd/compile/internal/syntax.Parse.func1(0xc420041f30)
        /home/kirr/src/tools/go/go/src/cmd/compile/internal/syntax/syntax.go:60 +0xdb
panic(0xa5f2e0, 0xd47a90)
        /home/kirr/src/tools/go/go/src/runtime/panic.go:489 +0x26e
cmd/compile/internal/syntax.(*parser).pexpr(0xc420026c00, 0xc420018201, 0x0, 0x0)
        /home/kirr/src/tools/go/go/src/cmd/compile/internal/syntax/parser.go:803 +0x714
cmd/compile/internal/syntax.(*parser).unaryExpr(0xc420026c00, 0x0, 0x0)
        /home/kirr/src/tools/go/go/src/cmd/compile/internal/syntax/parser.go:629 +0x51e
cmd/compile/internal/syntax.(*parser).binaryExpr(0xc420026c00, 0x0, 0x0, 0xc4200466a0)
        /home/kirr/src/tools/go/go/src/cmd/compile/internal/syntax/parser.go:525 +0x2f
cmd/compile/internal/syntax.(*parser).expr(0xc420026c00, 0x0, 0x0)
        /home/kirr/src/tools/go/go/src/cmd/compile/internal/syntax/parser.go:518 +0x46
cmd/compile/internal/syntax.(*parser).bare_complitexpr(0xc420026c00, 0x0, 0x0)
        /home/kirr/src/tools/go/go/src/cmd/compile/internal/syntax/parser.go:902 +0x7f
cmd/compile/internal/syntax.(*parser).complitexpr(0xc420026c00, 0x0)
        /home/kirr/src/tools/go/go/src/cmd/compile/internal/syntax/parser.go:919 +0xf2
cmd/compile/internal/syntax.(*parser).pexpr(0xc420026c00, 0xc420046801, 0x0, 0x0)
        /home/kirr/src/tools/go/go/src/cmd/compile/internal/syntax/parser.go:879 +0xae8
cmd/compile/internal/syntax.(*parser).unaryExpr(0xc420026c00, 0x0, 0x0)
        /home/kirr/src/tools/go/go/src/cmd/compile/internal/syntax/parser.go:629 +0x51e
cmd/compile/internal/syntax.(*parser).binaryExpr(0xc420026c00, 0x0, 0xc420026c01, 0xc4203239c0)
        /home/kirr/src/tools/go/go/src/cmd/compile/internal/syntax/parser.go:525 +0x2f
cmd/compile/internal/syntax.(*parser).expr(0xc420026c00, 0x0, 0x0)
        /home/kirr/src/tools/go/go/src/cmd/compile/internal/syntax/parser.go:518 +0x46
cmd/compile/internal/syntax.(*parser).call(0xc420026c00, 0xd2b960, 0xc420316b40, 0x0)
        /home/kirr/src/tools/go/go/src/cmd/compile/internal/syntax/parser.go:2054 +0x11d
cmd/compile/internal/syntax.(*parser).pexpr(0xc420026c00, 0x1, 0x0, 0x0)
        /home/kirr/src/tools/go/go/src/cmd/compile/internal/syntax/parser.go:854 +0x5b1
cmd/compile/internal/syntax.(*parser).unaryExpr(0xc420026c00, 0x0, 0x0)
        /home/kirr/src/tools/go/go/src/cmd/compile/internal/syntax/parser.go:629 +0x51e
cmd/compile/internal/syntax.(*parser).binaryExpr(0xc420026c00, 0x0, 0x0, 0x0)
        /home/kirr/src/tools/go/go/src/cmd/compile/internal/syntax/parser.go:525 +0x2f
cmd/compile/internal/syntax.(*parser).expr(0xc420026c00, 0x0, 0x0)
        /home/kirr/src/tools/go/go/src/cmd/compile/internal/syntax/parser.go:518 +0x46
cmd/compile/internal/syntax.(*parser).exprList(0xc420026c00, 0x0, 0x0)
        /home/kirr/src/tools/go/go/src/cmd/compile/internal/syntax/parser.go:2137 +0x58
cmd/compile/internal/syntax.(*parser).stmt(0xc420026c00, 0x0, 0x0)
        /home/kirr/src/tools/go/go/src/cmd/compile/internal/syntax/parser.go:1913 +0xac6
cmd/compile/internal/syntax.(*parser).stmtList(0xc420026c00, 0x0, 0x0, 0x0)
        /home/kirr/src/tools/go/go/src/cmd/compile/internal/syntax/parser.go:2020 +0x99
cmd/compile/internal/syntax.(*parser).funcBody(0xc420026c00, 0x0, 0x0, 0x0)
        /home/kirr/src/tools/go/go/src/cmd/compile/internal/syntax/parser.go:1164 +0x81
cmd/compile/internal/syntax.(*parser).funcDecl(0xc420026c00, 0x0)
        /home/kirr/src/tools/go/go/src/cmd/compile/internal/syntax/parser.go:494 +0x14e
cmd/compile/internal/syntax.(*parser).file(0xc420026c00, 0x0)
        /home/kirr/src/tools/go/go/src/cmd/compile/internal/syntax/parser.go:289 +0x3b1
cmd/compile/internal/syntax.Parse(0xc420323900, 0xd271a0, 0xc42000c540, 0xc420015460, 0xc420015470, 0x0, 0x0, 0x0, 0x0)
        /home/kirr/src/tools/go/go/src/cmd/compile/internal/syntax/syntax.go:67 +0xf0
cmd/compile/internal/gc.parseFiles.func1(0xc420323840, 0x7ffdfd42b0cc, 0x1d)
        /home/kirr/src/tools/go/go/src/cmd/compile/internal/gc/noder.go:38 +0x312
created by cmd/compile/internal/gc.parseFiles
        /home/kirr/src/tools/go/go/src/cmd/compile/internal/gc/noder.go:27 +0x16f
```

#### Does this issue reproduce with the latest release (go1.7.5)?

No:

```
kirr@deco:~/tmp/trashme/t$ go17 build x.go 
# command-line-arguments
./x.go:8: syntax error: unexpected ..., expecting expression
```

#### System details

```
go version devel +8da91a6297 Mon Feb 13 06:10:35 2017 +0000 linux/amd64
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/kirr/go"
GORACE=""
GOROOT="/home/kirr/src/tools/go/go"
GOTOOLDIR="/home/kirr/src/tools/go/go/pkg/tool/linux_amd64"
GCCGO="/usr/bin/gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build411645692=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
GOROOT/bin/go version: go version devel +8da91a6297 Mon Feb 13 06:10:35 2017 +0000 linux/amd64
GOROOT/bin/go tool compile -V: compile version devel +8da91a6297 Mon Feb 13 06:10:35 2017 +0000 X:framepointer
uname -sr: Linux 4.9.0-1-amd64
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.0 (stretch)
Release:	9.0
Codename:	stretch
/lib/x86_64-linux-gnu/libc.so.6: GNU C Library (Debian GLIBC 2.24-9) stable release version 2.24, by Roland McGrath et al.
gdb --version: GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
```

**Comment by bradfitz** [comment]
Looks like it works in Go 1.8rc3. Regression at tip?

**Comment by griesemer** [comment]
@bradfitz Probably. On it.

**Comment by navytux** [comment]
@bradfitz, @griesemer thanks for the fix.
