### ISSUE TITLE
cmd/compile: test/ken/divconst.go failed on MIPS64

### ISSUE THREAD

**Issue by cherrymui** [golang/go#19153]
`test/ken/divconst.go` failed after CL https://go-review.googlesource.com/c/37015/. Could be this CL, or the SSA rules I wrote originally. I'll take a look.

https://build.golang.org/log/a9f125ee433f583e7a7887b31b5f0920bd200c3b
```
# go run run.go -- ken/divconst.go
exit status 1
u32 28 3 7 4
panic: fail

goroutine 1 [running]:
main.u32test(0x30000001c, 0x7)
	/tmp/gobuilder/linux-mips64le-cherry-79f6a5c7bd68/go/test/ken/divconst.go:276 +0x140
main.u32run()
	/tmp/gobuilder/linux-mips64le-cherry-79f6a5c7bd68/go/test/ken/divconst.go:299 +0x1c0
main.main()
	/tmp/gobuilder/linux-mips64le-cherry-79f6a5c7bd68/go/test/ken/divconst.go:626 +0x4c
exit status 2

FAIL	ken/divconst.go	2.930s
```

**Comment by randall77** [comment]
I found the problem.  Fix coming.
