### ISSUE TITLE
os/exec: flaky TestStdinCloseRace

### ISSUE THREAD

**Issue by bradfitz** [golang/go#19211]
https://build.golang.org/log/638ade578f749a07444424d53c92a64681559411
```
PASS
panic: Fail in goroutine after  has completed

goroutine 21 [running]:
testing.(*common).Fail(0xc420074f70)
	/tmp/workdir/go/src/testing/testing.go:445 +0x179
testing.(*common).Fail(0xc4201220d0)
	/tmp/workdir/go/src/testing/testing.go:439 +0x1b0
testing.(*common).Errorf(0xc4201220d0, 0x8927f0, 0x8, 0xc42001e7b0, 0x1, 0x1)
	/tmp/workdir/go/src/testing/testing.go:518 +0x95
os/exec_test.TestStdinCloseRace.func1(0xc420124160, 0xc4201220d0)
	/tmp/workdir/go/src/os/exec/exec_test.go:267 +0xf6
created by os/exec_test.TestStdinCloseRace
	/tmp/workdir/go/src/os/exec/exec_test.go:265 +0x261
FAIL	os/exec	2.210s
```

**Comment by alexbrainman** [comment]
Probably unrelated, but if I run this test 100 times, like
```
go test -v -c -o a.exe os/exec && for /l %x in (1, 1, 100) do a.exe -test.run=TestStdinCloseRace
```
it usually fails couple of times with:
```
--- FAIL: TestStdinCloseRace (0.01s)
        exec_test.go:282: Wait: succeeded unexpectedly
FAIL
```
only on my Windows XP 32-bit, never on Windows 7 64-bit.

My failure is, probably, related to #17245.

Alex

**Comment by ianlancetaylor** [comment]
Setting milestone to 1.8.1 since the fix is trivial and the problem has been reported by people trying to build 1.8 (in #19213).

**Comment by ianlancetaylor** [comment]
Reopening to consider merging the CL to 1.8.1.

**Comment by rsc** [comment]
Cherry-picked to release branch. Closing.
