### ISSUE TITLE
build: linux/mipsle failure -- memory corruption?

### ISSUE THREAD

**Issue by josharian** [golang/go#19396]
https://build.golang.org/log/0bde41bbabb1d05b0a3892c9b053b64106052a59

The failure is:

```
ok  	cmd/compile	20.018s
# cmd/compile/internal/gc
go/src/cmd/compile/internal/gc/constFold_test.go:11834: internal compiler error: zero alignment with nonzero size %!v(PANIC=runtime error: invalid memory address or nil pointer dereference)

goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/data/mipsle/go/src/runtime/debug/stack.go:24 +0x7c
cmd/compile/internal/gc.Fatalf(0x713079, 0x23, 0xd5c5170, 0x1, 0x1)
	/data/mipsle/go/src/cmd/compile/internal/gc/subr.go:175 +0x1fc
cmd/compile/internal/gc.dowidth(0xab1f080)
	/data/mipsle/go/src/cmd/compile/internal/gc/align.go:121 +0xd4
cmd/compile/internal/gc.(*state).assign(0xd414900, 0x12235b00, 0xc863c78, 0x12000000)
	/data/mipsle/go/src/cmd/compile/internal/gc/ssa.go:2341 +0x88
cmd/compile/internal/gc.(*state).stmt(0xd414900, 0x12235b60)
	/data/mipsle/go/src/cmd/compile/internal/gc/ssa.go:743 +0x2a8
cmd/compile/internal/gc.(*state).stmtList(0xd414900, 0x12226e30)
	/data/mipsle/go/src/cmd/compile/internal/gc/ssa.go:484 +0x74
cmd/compile/internal/gc.(*state).stmt(0xd414900, 0x12235c80)
	/data/mipsle/go/src/cmd/compile/internal/gc/ssa.go:507 +0x120c
cmd/compile/internal/gc.(*state).stmtList(0xd414900, 0x12226ea0)
	/data/mipsle/go/src/cmd/compile/internal/gc/ssa.go:484 +0x74
cmd/compile/internal/gc.(*state).stmt(0xd414900, 0xaea4fc0)
	/data/mipsle/go/src/cmd/compile/internal/gc/ssa.go:503 +0xa8
cmd/compile/internal/gc.(*state).stmtList(0xd414900, 0x121f3840)
	/data/mipsle/go/src/cmd/compile/internal/gc/ssa.go:484 +0x74
cmd/compile/internal/gc.(*state).stmt(0xd414900, 0xaea4e40)
	/data/mipsle/go/src/cmd/compile/internal/gc/ssa.go:757 +0x37cc
cmd/compile/internal/gc.(*state).stmtList(0xd414900, 0x121f3850)
	/data/mipsle/go/src/cmd/compile/internal/gc/ssa.go:484 +0x74
cmd/compile/internal/gc.buildssa(0xae76780, 0x0)
	/data/mipsle/go/src/cmd/compile/internal/gc/ssa.go:132 +0xc1c
cmd/compile/internal/gc.compile(0xae76780)
	/data/mipsle/go/src/cmd/compile/internal/gc/pgen.go:366 +0x2f0
cmd/compile/internal/gc.funccompile(0xae76780)
	/data/mipsle/go/src/cmd/compile/internal/gc/dcl.go:1222 +0x114
cmd/compile/internal/gc.Main()
	/data/mipsle/go/src/cmd/compile/internal/gc/main.go:493 +0x2638
main.main()
	/data/mipsle/go/src/cmd/compile/main.go:50 +0x154

FAIL	cmd/compile/internal/gc [build failed]
2017/03/03 18:21:06 Failed: exit status 2
```

All the other builds in that column are green, and this should be 100% repeatable. Smells like memory corruption. Filing this issue in case someone with mipsle hardware wants to try running that test in a loop for a while.

**Comment by josharian** [comment]
The mipsle builder definitely seems sick. Recent failures:

```
# bootstrap/cmd/link/internal/ld
/data/mipsle/go/src/cmd/link/internal/ld/macho_combine_dwarf.go:117[/data/mipsle/go/pkg/bootstrap/src/bootstrap/cmd/link/internal/ld/macho_combine_dwarf.go:120]: internal compiler error: two final stores - simultaneous live stores v631 v1485

goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/net/mipssw051/export/tmp/bkirby/go-initial-test-build/bootstrap/go-linux-mipsle-bootstrap/src/runtime/debug/stack.go:24 +0x80
cmd/compile/internal/gc.Fatalf(0x6e8ee6, 0x31, 0x116ef990, 0x2, 0x2)
	/net/mipssw051/export/tmp/bkirby/go-initial-test-build/bootstrap/go-linux-mipsle-bootstrap/src/cmd/compile/internal/gc/subr.go:165 +0x1f4
cmd/compile/internal/gc.(*ssaExport).Fatalf(0x98ee75, 0x3930, 0x6e8ee6, 0x31, 0x116ef990, 0x2, 0x2)
	/net/mipssw051/export/tmp/bkirby/go-initial-test-build/bootstrap/go-linux-mipsle-bootstrap/src/cmd/compile/internal/gc/ssa.go:4785 +0x6c
cmd/compile/internal/ssa.(*Config).Fatalf(0x11e40000, 0x3930, 0x6e8ee6, 0x31, 0x116ef990, 0x2, 0x2)
	/net/mipssw051/export/tmp/bkirby/go-initial-test-build/bootstrap/go-linux-mipsle-bootstrap/src/cmd/compile/internal/ssa/config.go:343 +0x7c
cmd/compile/internal/ssa.(*Func).Fatalf(0x12a4c480, 0x6e8ee6, 0x31, 0x116ef990, 0x2, 0x2)
	/net/mipssw051/export/tmp/bkirby/go-initial-test-build/bootstrap/go-linux-mipsle-bootstrap/src/cmd/compile/internal/ssa/func.go:413 +0x78
cmd/compile/internal/ssa.(*Block).Fatalf(0x11e63384, 0x6e8ee6, 0x31, 0x116ef990, 0x2, 0x2)
	/net/mipssw051/export/tmp/bkirby/go-initial-test-build/bootstrap/go-linux-mipsle-bootstrap/src/cmd/compile/internal/ssa/block.go:200 +0x6c
cmd/compile/internal/ssa.dse(0x12a4c480)
	/net/mipssw051/export/tmp/bkirby/go-initial-test-build/bootstrap/go-linux-mipsle-bootstrap/src/cmd/compile/internal/ssa/deadstore.go:65 +0xac4
cmd/compile/internal/ssa.Compile(0x12a4c480)
	/net/mipssw051/export/tmp/bkirby/go-initial-test-build/bootstrap/go-linux-mipsle-bootstrap/src/cmd/compile/internal/ssa/compile.go:68 +0x310
cmd/compile/internal/gc.buildssa(0x119756e0, 0x0)
	/net/mipssw051/export/tmp/bkirby/go-initial-test-build/bootstrap/go-linux-mipsle-bootstrap/src/cmd/compile/internal/gc/ssa.go:176 +0x868
cmd/compile/internal/gc.compile(0x119756e0)
	/net/mipssw051/export/tmp/bkirby/go-initial-test-build/bootstrap/go-linux-mipsle-bootstrap/src/cmd/compile/internal/gc/pgen.go:357 +0x228
cmd/compile/internal/gc.funccompile(0x119756e0)
	/net/mipssw051/export/tmp/bkirby/go-initial-test-build/bootstrap/go-linux-mipsle-bootstrap/src/cmd/compile/internal/gc/dcl.go:1292 +0x120
cmd/compile/internal/gc.Main()
	/net/mipssw051/export/tmp/bkirby/go-initial-test-build/bootstrap/go-linux-mipsle-bootstrap/src/cmd/compile/internal/gc/main.go:460 +0x2160
main.main()
	/net/mipssw051/export/tmp/bkirby/go-initial-test-build/bootstrap/go-linux-mipsle-bootstrap/src/cmd/compile/main.go:50 +0x158
```

```
--- FAIL: TestBestSpeed (6.46s)
	deflate_test.go:634: i=1, firstN=131072, flush=true: corruption during deflate-then-inflate
FAIL
FAIL	compress/flate	7.987s
```

```
# cmd/internal/obj/mips
cmd/internal/obj/mips/obj0.go:759:7: cannot use ABNE (type obj.As) as type %!v(PANIC=runtime error: invalid memory address or nil pointer dereference) in assignment
cmd/internal/obj/mips/obj0.go:759:7: internal compiler error: zero alignment with nonzero size %!v(PANIC=runtime error: invalid memory address or nil pointer dereference)

goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/data/mipsle/go/src/runtime/debug/stack.go:24 +0x80
bootstrap/cmd/compile/internal/gc.Fatalf(0x6985ad, 0x23, 0x1122586c, 0x1, 0x1)
	/data/mipsle/go/src/cmd/compile/internal/gc/subr.go:175 +0x218
bootstrap/cmd/compile/internal/gc.dowidth(0x10e9c280)
	/data/mipsle/go/src/cmd/compile/internal/gc/align.go:121 +0xd8
bootstrap/cmd/compile/internal/gc.needwritebarrier(0x11149b00, 0x0)
	/data/mipsle/go/src/cmd/compile/internal/gc/walk.go:2054 +0xc4
bootstrap/cmd/compile/internal/gc.updateHasCall(0x11149b60)
	/data/mipsle/go/src/cmd/compile/internal/gc/subr.go:1162 +0x1cc
bootstrap/cmd/compile/internal/gc.convas(0x11149b60, 0x11225c64, 0x10fd5900)
	/data/mipsle/go/src/cmd/compile/internal/gc/walk.go:2107 +0x90
bootstrap/cmd/compile/internal/gc.walkexpr(0x11149b60, 0x11225c64, 0x0)
	/data/mipsle/go/src/cmd/compile/internal/gc/walk.go:747 +0x5e8c
bootstrap/cmd/compile/internal/gc.walkstmt(0x11149b60, 0x11149a40)
	/data/mipsle/go/src/cmd/compile/internal/gc/walk.go:189 +0x130
bootstrap/cmd/compile/internal/gc.walkstmtlist(0x1140e000, 0xe4, 0x100)
	/data/mipsle/go/src/cmd/compile/internal/gc/walk.go:80 +0x74
bootstrap/cmd/compile/internal/gc.walk(0x10e9dbc0)
	/data/mipsle/go/src/cmd/compile/internal/gc/walk.go:65 +0x228
bootstrap/cmd/compile/internal/gc.compile(0x10e9dbc0)
	/data/mipsle/go/src/cmd/compile/internal/gc/pgen.go:344 +0x230
bootstrap/cmd/compile/internal/gc.funccompile(0x10e9dbc0)
	/data/mipsle/go/src/cmd/compile/internal/gc/dcl.go:1222 +0x120
bootstrap/cmd/compile/internal/gc.Main()
	/data/mipsle/go/src/cmd/compile/internal/gc/main.go:495 +0x2250
main.main()
	/data/mipsle/go/src/cmd/compile/main.go:50 +0x158
```

**Comment by josharian** [comment]
https://github.com/golang/go/wiki/DashboardBuilders doesn't list the owner of this builder. Anyone know who it is?

**Comment by bradfitz** [comment]
Backport this one to Go 1.8.x? @ianlancetaylor? @cherrymui?

**Comment by cherrymui** [comment]
SGTM

**Comment by cherrymui** [comment]
reopen for patching Go 1.8.

**Comment by aclements** [comment]
Cherry-picked to release.
