### ISSUE TITLE
cmd/compile: "go build -gcflags=-S runtime/internal/sys" panics

### ISSUE THREAD

**Issue by mdempsky** [golang/go#19427]
At HEAD (0332b6cf589a51f421a88176f756f0315c9f1491), `go build -gcflags=-S runtime/internal/sys` is panicking while printing out Bswap64:

    	0x003a 00058 (/usr/local/google/home/mdempsky/wd/go/src/runtime/internal/sys/intrinsics.go:62)	SHLQ	$16, CX
    	0x003e 0panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4d5ef6]

    goroutine 1 [running]:
    cmd/internal/obj.(*objWriter).writeSymDebug(0xc420074770, 0xc42044ca10)
    	/usr/local/google/home/mdempsky/wd/go/src/cmd/internal/obj/objfile.go:339 +0x256
    cmd/internal/obj.(*objWriter).writeSym(0xc420074770, 0xc42044ca10)
    	/usr/local/google/home/mdempsky/wd/go/src/cmd/internal/obj/objfile.go:385 +0x8df
    cmd/internal/obj.WriteObjFile(0xc4200e6000, 0xc420394f40)
    	/usr/local/google/home/mdempsky/wd/go/src/cmd/internal/obj/objfile.go:244 +0x5c9
    cmd/compile/internal/gc.dumpobj1(0x7fff3c75effc, 0x2d, 0x3)
    	/usr/local/google/home/mdempsky/wd/go/src/cmd/compile/internal/gc/obj.go:154 +0x3e0
    cmd/compile/internal/gc.dumpobj()
    	/usr/local/google/home/mdempsky/wd/go/src/cmd/compile/internal/gc/obj.go:49 +0x61
    cmd/compile/internal/gc.Main()
    	/usr/local/google/home/mdempsky/wd/go/src/cmd/compile/internal/gc/main.go:522 +0x20b4
    main.main()
    	/usr/local/google/home/mdempsky/wd/go/src/cmd/compile/main.go:50 +0x101
    toolstash: exit status 2

**Comment by mdempsky** [comment]
Doh, this is from a CL in my patch series actually.
