### ISSUE TITLE
cmd/compile: index of out of range compiling internal/obj/arm64 on linux-mipsle

### ISSUE THREAD

**Issue by bradfitz** [golang/go#19641]
Is this flaky hardware again?

https://build.golang.org/log/b48f08a61d4681905022d8d75068df7dfc745af6

```
cmd/internal/obj/arm64
cmd/internal/obj/mips
cmd/internal/obj/ppc64
# cmd/internal/obj/arm64
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x634340, 0x8e5cc0)
	/data/mipsle/go/src/runtime/panic.go:531 +0x1a8
bootstrap/cmd/internal/src.(*PosTable).Pos(0x10ccc028, 0x1160c450, 0x1160c748, 0x1181d040, 0x0)
	/data/mipsle/go/src/cmd/internal/src/xpos.go:72 +0x84
bootstrap/cmd/internal/obj.(*Link).OutermostPos(0x10ccc000, 0x1160c450, 0x1160c748, 0x4947e8, 0x1181d073)
	/data/mipsle/go/src/cmd/internal/obj/inl.go:69 +0x5c
bootstrap/cmd/compile/internal/gc.linestr(0x1160c450, 0x1160c748, 0x651b01, 0x494aec)
	/data/mipsle/go/src/cmd/compile/internal/gc/subr.go:90 +0x54
bootstrap/cmd/compile/internal/gc.Fatalf(0x674a54, 0x19, 0x11636d4c, 0x1, 0x1)
	/data/mipsle/go/src/cmd/compile/internal/gc/subr.go:163 +0x58
bootstrap/cmd/compile/internal/gc.dowidth(0x1160bb68)
	/data/mipsle/go/src/cmd/compile/internal/gc/align.go:213 +0x568
bootstrap/cmd/compile/internal/gc.checkwidth(0x1160bb68)
	/data/mipsle/go/src/cmd/compile/internal/gc/align.go:410 +0x1d0
bootstrap/cmd/compile/internal/gc.typecheck1(0x11836000, 0x22, 0x1160c748)
	/data/mipsle/go/src/cmd/compile/internal/gc/typecheck.go:2142 +0x7cc
bootstrap/cmd/compile/internal/gc.typecheck(0x11836000, 0x22, 0x1128b540)
	/data/mipsle/go/src/cmd/compile/internal/gc/typecheck.go:199 +0x648
bootstrap/cmd/compile/internal/gc.typecheckas(0x11836060)
	/data/mipsle/go/src/cmd/compile/internal/gc/typecheck.go:3293 +0x94
bootstrap/cmd/compile/internal/gc.typecheck1(0x11836060, 0x1, 0x100)
	/data/mipsle/go/src/cmd/compile/internal/gc/typecheck.go:1982 +0x3520
bootstrap/cmd/compile/internal/gc.typecheck(0x11836060, 0x1, 0x11836d20)
	/data/mipsle/go/src/cmd/compile/internal/gc/typecheck.go:199 +0x648
bootstrap/cmd/compile/internal/gc.typecheckslice(0x1181cec0, 0xf, 0x10, 0x1)
	/data/mipsle/go/src/cmd/compile/internal/gc/typecheck.go:53 +0x7c
bootstrap/cmd/compile/internal/gc.fninit(0x11282000, 0x2b9, 0x540)
	/data/mipsle/go/src/cmd/compile/internal/gc/init.go:163 +0x9c4
bootstrap/cmd/compile/internal/gc.Main(0x683f30)
	/data/mipsle/go/src/cmd/compile/internal/gc/main.go:518 +0x236c
main.main()
	/data/mipsle/go/src/cmd/compile/main.go:49 +0xb4
cmd/internal/obj/s390x
crypto/x509
vendor/golang_org/x/net/lex/httplex
vendor/golang_org/x/net/proxy
net/textproto
```

/cc @cherrymui @mdempsky

**Comment by vstefanovic** [comment]
I wonder if rebuilding the bootstrap with https://golang.org/cl/38257 would help.

**Comment by cherrymui** [comment]
Sounds a good thing to try.

**Comment by bradfitz** [comment]
Who owns this builder? It's not listed in https://github.com/golang/go/wiki/DashboardBuilders

Please document it.

**Comment by cherrymui** [comment]
> Who owns this builder? 

Probably @vstefanovic ?

**Comment by vstefanovic** [comment]
I suppose it's Brendan Kirby, he maintains that machine.

**Comment by MIPSbkirby** [comment]
I rebuilt the bootstrap environment.  It is now at commit 01cd22c:
```
$ /usr/local/go-bootstrap-mipsle/bin/go version 
go version devel +01cd22c Tue Mar 21 13:25:17 2017 linux/mipsle
```

which includes commit 24dc8c6c.

**Comment by bradfitz** [comment]
Thanks, @MIPSbkirby! You want me to clear some builds with golang.org/x/build/cmd/retrybuilds? Or you're welcome to too.

**Comment by bradfitz** [comment]
I cleared the obvious weirdo candidates. We'll watch it going forward.

**Comment by cherrymui** [comment]
Still see occasional failures in bootstrapping, for example
https://build.golang.org/log/0c39fed4846b95602caf257672caa02f939b0d74

**Comment by cherrymui** [comment]
Seems this has not happened for quite a long time. I'm going to close it. We can reopen if we see it again.
