### ISSUE TITLE
golang/dep: RSA key fingerprint 

### ISSUE THREAD

**Issue by themihai** [golang/go#19657]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/themihai/go"
GORACE=""
GOROOT="/Users/themihai/gosrc"
GOTOOLDIR="/Users/themihai/gosrc/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/96/xn9qmts104s1mcdqg31s66lh0000gn/T/go-build120918767=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?
dep init

### What did you expect to see?

No error. 

### What did you see instead?
 It started to get some auth errors and then got stuck.
 I  killed it with CTRL+C. Then I tried again dep init (after clearing the cached fingerprints).  Then I tried ` dep init` again but it errors out a different message(`getSourceManager: cache lock file /Users/themihai/go/pkg/dep/sm.lock exists - another process crashed or is still running?`). I removed `sm.lock` but now whenever I execute dep init I get the fingerprint errors and then it gets stuck. go get-ing the bitbucket packages works without any issue so I can only assume there is a bug 'dep' bug. Perhaps `dep` is trying to use SSH instead of https?

Initial error[0]
```

The authenticity of host 'bitbucket.org (104.192.143.3)' can't be established.
RSA key fingerprint is SHA256:zzXQOXSRBEiUtuE8AikJYKwbHaxvSc0ojez9YXaGp1A.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'bitbucket.org (104.192.143.3)' can't be established.
RSA key fingerprint is SHA256:zzXQOXSRBEiUtuE8AikJYKwbHaxvSc0ojez9YXaGp1A.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'bitbucket.org (104.192.143.3)' can't be established.
RSA key fingerprint is SHA256:zzXQOXSRBEiUtuE8AikJYKwbHaxvSc0ojez9YXaGp1A.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'bitbucket.org (104.192.143.3)' can't be established.
RSA key fingerprint is SHA256:zzXQOXSRBEiUtuE8AikJYKwbHaxvSc0ojez9YXaGp1A.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'bitbucket.org (104.192.143.3)' can't be established.
RSA key fingerprint is SHA256:zzXQOXSRBEiUtuE8AikJYKwbHaxvSc0ojez9YXaGp1A.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'bitbucket.org (104.192.143.3)' can't be established.
RSA key fingerprint is SHA256:zzXQOXSRBEiUtuE8AikJYKwbHaxvSc0ojez9YXaGp1A.
Are you sure you want to continue connecting (yes/no)? Cached github.com/themihai/keybd_event
The authenticity of host 'bitbucket.org (104.192.143.3)' can't be established.
RSA key fingerprint is SHA256:zzXQOXSRBEiUtuE8AikJYKwbHaxvSc0ojez9YXaGp1A.
Are you sure you want to continue connecting (yes/no)? Cached github.com/golang/glog
Cached github.com/grandcat/zeroconf
Cached github.com/cenkalti/backoff
Cached golang.org/x/net
Cached github.com/miekg/dns




^CUnable to cache bitbucket.org/brev/context
Unable to cache bitbucket.org/brev/tvs
^[[AThe authenticity of host 'bitbucket.org (104.192.143.3)' can't be established.
RSA key fingerprint is SHA256:zzXQOXSRBEiUtuE8AikJYKwbHaxvSc0ojez9YXaGp1A.
Are you sure you want to continue connecting (yes/no)? panic: runtime error: slice bounds out of range

goroutine 74 [running]:
github.com/golang/dep/vendor/github.com/sdboyer/gps.(*gitSource).doListVersions(0xc4201e6420, 0x1465988, 0xc4201e6450, 0x0, 0xc420474640, 0xc42002dc00)
	/Users/themihai/go/src/github.com/golang/dep/vendor/github.com/sdboyer/gps/vcs_source.go:216 +0xfca
github.com/golang/dep/vendor/github.com/sdboyer/gps.(*gitSource).listVersions(0xc4201e6420, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/themihai/go/src/github.com/golang/dep/vendor/github.com/sdboyer/gps/vcs_source.go:119 +0x2bf
github.com/golang/dep/vendor/github.com/sdboyer/gps.maybeGitSource.try(0xc4201e5800, 0xc42019cb80, 0x1a, 0x160f060, 0x165bfe0, 0xc4201e4480, 0x2, 0x4, 0x0, 0x160aea0, ...)
	/Users/themihai/go/src/github.com/golang/dep/vendor/github.com/sdboyer/gps/maybe_source.go:86 +0x45f
github.com/golang/dep/vendor/github.com/sdboyer/gps.maybeSources.try(0xc4201e5900, 0x7, 0x8, 0xc42019cb80, 0x1a, 0x160f060, 0x165bfe0, 0xc4202526c0, 0x0, 0x1354599, ...)
	/Users/themihai/go/src/github.com/golang/dep/vendor/github.com/sdboyer/gps/maybe_source.go:28 +0xb7
github.com/golang/dep/vendor/github.com/sdboyer/gps.(*maybeSources).try(0xc4202e01c0, 0xc42019cb80, 0x1a, 0x160f060, 0x165bfe0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	<autogenerated>:170 +0x97
github.com/golang/dep/vendor/github.com/sdboyer/gps.(*SourceMgr).deduceFromPath.func2.1.1(0xc4201e6e40, 0xc4201d12c0, 0xc4201d12d0, 0xc4201d12e0, 0x160cb20, 0xc4202e01c0, 0xc42019cb80, 0x1a, 0x160f060, 0x165bfe0)
	/Users/themihai/go/src/github.com/golang/dep/vendor/github.com/sdboyer/gps/deduce.go:567 +0x9f
created by github.com/golang/dep/vendor/github.com/sdboyer/gps.(*SourceMgr).deduceFromPath.func2.1
	/Users/themihai/go/src/github.com/golang/dep/vendor/github.com/sdboyer/gps/deduce.go:568 +0x174

```

**Comment by themihai** [comment]
The error is fixed once I add confirm the SSH fingerprint manually ( git clone ssh://bitbucket.org/xyz/z)  but I've got a different crash 

```
 dep init
Cached github.com/grandcat/zeroconf
Cached github.com/themihai/keybd_event
Cached github.com/golang/glog
Cached golang.org/x/net
panic: runtime error: slice bounds out of range

goroutine 59 [running]:
github.com/golang/dep/vendor/github.com/sdboyer/gps.(*gitSource).doListVersions(0xc420071080, 0x1465988, 0xc4200710b0, 0x0, 0xc4204a5590, 0xc42002d800)
	/Users/themihai/go/src/github.com/golang/dep/vendor/github.com/sdboyer/gps/vcs_source.go:216 +0xfca
github.com/golang/dep/vendor/github.com/sdboyer/gps.(*gitSource).listVersions(0xc420071080, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/themihai/go/src/github.com/golang/dep/vendor/github.com/sdboyer/gps/vcs_source.go:119 +0x2bf
github.com/golang/dep/vendor/github.com/sdboyer/gps.maybeGitSource.try(0xc4202a6980, 0xc42019cb60, 0x1a, 0x160f060, 0x165bfe0, 0xc4202a7b00, 0x2, 0x4, 0x0, 0x160aea0, ...)
	/Users/themihai/go/src/github.com/golang/dep/vendor/github.com/sdboyer/gps/maybe_source.go:86 +0x45f
github.com/golang/dep/vendor/github.com/sdboyer/gps.maybeSources.try(0xc4202a6a80, 0x7, 0x8, 0xc42019cb60, 0x1a, 0x160f060, 0x165bfe0, 0xc420014440, 0x105d068, 0x1354599, ...)
	/Users/themihai/go/src/github.com/golang/dep/vendor/github.com/sdboyer/gps/maybe_source.go:28 +0xb7
github.com/golang/dep/vendor/github.com/sdboyer/gps.(*maybeSources).try(0xc4202e0920, 0xc42019cb60, 0x1a, 0x160f060, 0x165bfe0, 0x115cebf, 0xc420250010, 0x0, 0xc420029f88, 0x100563d, ...)
	<autogenerated>:170 +0x97
github.com/golang/dep/vendor/github.com/sdboyer/gps.(*SourceMgr).deduceFromPath.func2.1.1(0xc420222660, 0xc420214760, 0xc420214770, 0xc420214780, 0x160cb20, 0xc4202e0920, 0xc42019cb60, 0x1a, 0x160f060, 0x165bfe0)
	/Users/themihai/go/src/github.com/golang/dep/vendor/github.com/sdboyer/gps/deduce.go:567 +0x9f
created by github.com/golang/dep/vendor/github.com/sdboyer/gps.(*SourceMgr).deduceFromPath.func2.1
	/Users/themihai/go/src/github.com/golang/dep/vendor/github.com/sdboyer/gps/deduce.go:568 +0x174
```

**Comment by ALTree** [comment]
Hi,

the dep issue tracker is here: https://github.com/golang/dep/issues. This is the tracker of the go project, and we don't track dep issues here. Please submit your issue on the dep tracker. Thanks!
