### ISSUE TITLE
cmd/vet: SIGSEGV in the presence of duplicate function definitions

### ISSUE THREAD

**Issue by jgrahn** [golang/go#19656]
Running `go vet` (version `go1.8 darwin/amd64`) on a package as defined below results in a SIGSEGV panic.

### What version of Go are you using (`go version`)?
`go1.8 darwin/amd64`

### What operating system and processor architecture are you using (`go env`)?
`GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"`

### What did you do?

Created a package directory containing two identical files, named `1.go` and `2.go`, having the following content:

```
package main

import "context"

func f() {
	var ctx, cancel = context.WithCancel(context.Background())
}
```

Then ran `go vet {package}` on that package.

### What did you expect to see?

Ideally a vet error notifying about the duplicate function definition. Alternatively two vet errors warning about the lost context cancel, once for each file. Not a crash.

### What did you see instead?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x12321b7]

goroutine 1 [running]:
main.checkLostCancel(0xc420080600, 0x13f16a0, 0xc4201f0e10)
	/usr/local/Cellar/go/1.8/libexec/src/cmd/vet/lostcancel.go:107 +0x767
main.(*File).Visit(0xc420080600, 0x13f16a0, 0xc4201f0e10, 0x13f0760, 0xc420080600)
	/usr/local/Cellar/go/1.8/libexec/src/cmd/vet/main.go:500 +0x104
go/ast.Walk(0x13f0760, 0xc420080600, 0x13f16a0, 0xc4201f0e10)
	/usr/local/Cellar/go/1.8/libexec/src/go/ast/walk.go:52 +0x66
go/ast.walkDeclList(0x13f0760, 0xc420080600, 0xc4201f3280, 0x2, 0x2)
	/usr/local/Cellar/go/1.8/libexec/src/go/ast/walk.go:38 +0x89
go/ast.Walk(0x13f0760, 0xc420080600, 0x13f1660, 0xc4200a5500)
	/usr/local/Cellar/go/1.8/libexec/src/go/ast/walk.go:353 +0x2bb4
main.(*File).walkFile(0xc420080600, 0x7fff5fbffa41, 0xd, 0xc4200a5500)
	/usr/local/Cellar/go/1.8/libexec/src/cmd/vet/main.go:467 +0x120
main.doPackage(0x12d07b4, 0x1, 0xc42008c010, 0x2, 0x2, 0x0, 0xffffffffffffffff)
	/usr/local/Cellar/go/1.8/libexec/src/cmd/vet/main.go:358 +0xbd1
main.main()
	/usr/local/Cellar/go/1.8/libexec/src/cmd/vet/main.go:247 +0x382
exit status 2
```

**Comment by josharian** [comment]
@alandonovan
