### ISSUE TITLE
cmd/compile: internal compiler error: assigning to non-1-length array

### ISSUE THREAD

**Issue by ALTree** [golang/go#19671]
The following program:

```
package a

func Crash() {
	var i int
	arr := [0][2]int{}
	arr[i][0] = 0
}
```

crashes the 1.7.5, 1.8, and tip compilers.

```
./2.go:6:12: internal compiler error: assigning to non-1-length array

goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/home/adonizetti/go/src/runtime/debug/stack.go:24 +0x79
cmd/compile/internal/gc.Fatalf(0xaccca1, 0x1f, 0x0, 0x0, 0x0)
	/home/adonizetti/go/src/cmd/compile/internal/gc/subr.go:175 +0x230
cmd/compile/internal/gc.(*ssafn).Fatalf(0xc4202d8930, 0x60c00000001, 0xaccca1, 0x1f, 0x0, 0x0, 0x0)
	/home/adonizetti/go/src/cmd/compile/internal/gc/ssa.go:4890 +0x67
cmd/compile/internal/gc.(*state).Fatalf(0xc4200f60e0, 0xaccca1, 0x1f, 0x0, 0x0, 0x0)
	/home/adonizetti/go/src/cmd/compile/internal/gc/ssa.go:286 +0x98
cmd/compile/internal/gc.(*state).assign(0xc4200f60e0, 0xc4202f8b40, 0xc42030e1e0, 0x0)
	/home/adonizetti/go/src/cmd/compile/internal/gc/ssa.go:2352 +0x4e6
cmd/compile/internal/gc.(*state).stmt(0xc4200f60e0, 0xc4202f8ab0)
	/home/adonizetti/go/src/cmd/compile/internal/gc/ssa.go:718 +0x246
cmd/compile/internal/gc.(*state).stmtList(0xc4200f60e0, 0xc42030a220)
	/home/adonizetti/go/src/cmd/compile/internal/gc/ssa.go:498 +0x5e
cmd/compile/internal/gc.buildssa(0xc4200b2140, 0x0)
	/home/adonizetti/go/src/cmd/compile/internal/gc/ssa.go:172 +0x873
cmd/compile/internal/gc.compile(0xc4200b2140)
	/home/adonizetti/go/src/cmd/compile/internal/gc/pgen.go:307 +0x177
cmd/compile/internal/gc.funccompile(0xc4200b2140)
	/home/adonizetti/go/src/cmd/compile/internal/gc/dcl.go:1172 +0xbb
cmd/compile/internal/gc.Main(0xad9020)
	/home/adonizetti/go/src/cmd/compile/internal/gc/main.go:511 +0x22f4
main.main()
	/home/adonizetti/go/src/cmd/compile/main.go:49 +0x95
```

**Comment by ianlancetaylor** [comment]
CC @randall77 @josharian @mdempsky

**Comment by josharian** [comment]
Bisection wanted. :)

**Comment by ALTree** [comment]
I was wrong, go1.7.5 is not affected (1.8 and tip are).

This was introduced in 741445068f7f582824f1c5625159e0b728090265 (cmd/compile: make [0]T and [1]T SSAable types) 

cc @randall77
