### ISSUE TITLE
encoding/binary: handle unexported fields more gracefully

### ISSUE THREAD

**Issue by dominikh** [golang/go#19794]
### What version of Go are you using (`go version`)?
go version go1.8 linux/amd64

### What did you do?
https://play.golang.org/p/gcvrJJD1uS

### What did you expect to see?
Either an error to be returned, or the unexported fields to be skipped.

### What did you see instead?
```
panic: reflect: reflect.Value.SetUint using value obtained using unexported field

goroutine 1 [running]:
reflect.flag.mustBeAssignable(0x1a8, 0x0)
	/usr/local/go/src/reflect/value.go:225 +0x1c0
reflect.Value.SetUint(0xf1e00, 0x1040a0d9, 0x1a8, 0x1ce2, 0x78, 0x0)
	/usr/local/go/src/reflect/value.go:1493 +0x40
encoding/binary.(*decoder).value(0x10429f5c, 0xf1e00, 0x1040a0d9, 0x1a8)
	/usr/local/go/src/encoding/binary/binary.go:546 +0xac0
encoding/binary.(*decoder).value(0x10429f5c, 0xf4760, 0x1040a0d9, 0x199)
	/usr/local/go/src/encoding/binary/binary.go:521 +0x320
encoding/binary.Read(0x170630, 0x10440240, 0x1714c0, 0x1931c8, 0xe89a0, 0x1040a0d9, 0x0, 0x2)
	/usr/local/go/src/encoding/binary/binary.go:247 +0x1360
main.main()
	/tmp/sandbox482800808/main.go:16 +0x120
```

**Comment by SamWhited** [comment]
The documentation for `Read` says:

> When reading into a struct, all non-blank fields must be exported.

That seems to me to indicate that the panic is expected (although that could be made more clear: "~ or Read may panic").
