### ISSUE TITLE
runtime: TestCgoPprofPIE fails on Alpine

### ISSUE THREAD

**Issue by bradfitz** [golang/go#19938]
Thanks to @jessfraz's setting up an Alpine Linux builder (#17891), we now get to deal with more bugs, like this one:

```
--- FAIL: TestCgoPprofPIE (8.39s)
	crash_cgo_test.go:285: signal: segmentation fault (core dumped)
FAIL
FAIL	runtime	16.270s
```

@ianlancetaylor?

**Comment by jessfraz** [comment]
I feel like I know why this is happening... I can debug

**Comment by jessfraz** [comment]
https://github.com/golang/go/issues/18243

**Comment by jessfraz** [comment]
So it's because https://github.com/golang/go/blob/master/src/cmd/link/internal/amd64/obj.go#L70
```
ld.Thearch.Linuxdynld = "/lib64/ld-linux-x86-64.so.2"
```
on alpine this is:
```
ld.Thearch.Linuxdynld = "/lib/ld-musl-x86_64.so.1"
```

we should maybe have a way of using a different one? but alpine is not a GOOS so unsure what you all would want here

**Comment by jessfraz** [comment]
There are other failures following that failure as well. Details below.

I have a hunch this is because an `#include <sys/types.h>` is missing somewhere in `runtime`.

<details>
<summary>TestTestEmpty</summary>

```
--- FAIL: TestTestEmpty (1.82s)
    --- FAIL: TestTestEmpty/pkg (1.82s)
        go_test.go:260: running testgo [test -cover -coverpkg=. -race]
        go_test.go:279: standard error:
        go_test.go:280: # runtime/race
                race_linux_amd64.syso: In function `__sanitizer::InternalAlloc(unsigned long, __sanitizer::SizeClassAllocatorLocalCache<__sanitizer::SizeClassAllocator32<0ul, 140737488355328ull, 0ul, __sanitizer::SizeClassMap<3ul, 4ul, 8ul, 17ul, 64ul, 14ul>, 20ul, __sanitizer::TwoLevelByteMap<32768ull, 4096ull, __sanitizer::NoOpMapUnmapCallback>, __sanitizer::NoOpMapUnmapCallback> >*, unsigned long)':
                gotsan.cc:(.text+0x16e1): undefined reference to `__libc_malloc'
                race_linux_amd64.syso: In function `__sanitizer::GetArgv()':
                gotsan.cc:(.text+0x4543): undefined reference to `__libc_stack_end'
                race_linux_amd64.syso: In function `__sanitizer::InternalRealloc(void*, unsigned long, __sanitizer::SizeClassAllocatorLocalCache<__sanitizer::SizeClassAllocator32<0ul, 140737488355328ull, 0ul, __sanitizer::SizeClassMap<3ul, 4ul, 8ul, 17ul, 64ul, 14ul>, 20ul, __sanitizer::TwoLevelByteMap<32768ull, 4096ull, __sanitizer::NoOpMapUnmapCallback>, __sanitizer::NoOpMapUnmapCallback> >*)':
                gotsan.cc:(.text+0x7dd0): undefined reference to `__libc_realloc'
                race_linux_amd64.syso: In function `__sanitizer::ReExec()':
                gotsan.cc:(.text+0xed47): undefined reference to `__libc_stack_end'
                race_linux_amd64.syso: In function `__sanitizer::InternalFree(void*, __sanitizer::SizeClassAllocatorLocalCache<__sanitizer::SizeClassAllocator32<0ul, 140737488355328ull, 0ul, __sanitizer::SizeClassMap<3ul, 4ul, 8ul, 17ul, 64ul, 14ul>, 20ul, __sanitizer::TwoLevelByteMap<32768ull, 4096ull, __sanitizer::NoOpMapUnmapCallback>, __sanitizer::NoOpMapUnmapCallback> >*)':
                gotsan.cc:(.text+0x7438): undefined reference to `__libc_free'
                collect2: error: ld returned 1 exit status
    
        go_test.go:289: go [test -cover -coverpkg=. -race] failed unexpectedly: exit status 2
```

</details>

<details>
<summary>TestTestRaceInstall</summary>

```
--- FAIL: TestTestRaceInstall (1.99s)
        go_test.go:260: running testgo [install -race -pkgdir=/tmp/gotest207241282/pkg std]
        go_test.go:279: standard error:
        go_test.go:280: # runtime/race
                race_linux_amd64.syso: In function `__sanitizer::InternalAlloc(unsigned long, __sanitizer::SizeClassAllocatorLocalCache<__sanitizer::SizeClassAllocator32<0ul, 140737488355328ull, 0ul, __sanitizer::SizeClassMap<3ul, 4ul, 8ul, 17ul, 64ul, 14ul>, 20ul, __sanitizer::TwoLevelByteMap<32768ull, 4096ull, __sanitizer::NoOpMapUnmapCallback>, __sanitizer::NoOpMapUnmapCallback> >*, unsigned long)':
                gotsan.cc:(.text+0x16e1): undefined reference to `__libc_malloc'
                race_linux_amd64.syso: In function `__sanitizer::GetArgv()':
                gotsan.cc:(.text+0x4543): undefined reference to `__libc_stack_end'
                race_linux_amd64.syso: In function `__sanitizer::InternalRealloc(void*, unsigned long, __sanitizer::SizeClassAllocatorLocalCache<__sanitizer::SizeClassAllocator32<0ul, 140737488355328ull, 0ul, __sanitizer::SizeClassMap<3ul, 4ul, 8ul, 17ul, 64ul, 14ul>, 20ul, __sanitizer::TwoLevelByteMap<32768ull, 4096ull, __sanitizer::NoOpMapUnmapCallback>, __sanitizer::NoOpMapUnmapCallback> >*)':
                gotsan.cc:(.text+0x7dd0): undefined reference to `__libc_realloc'
                race_linux_amd64.syso: In function `__sanitizer::ReExec()':
                gotsan.cc:(.text+0xed47): undefined reference to `__libc_stack_end'
                race_linux_amd64.syso: In function `__sanitizer::InternalFree(void*, __sanitizer::SizeClassAllocatorLocalCache<__sanitizer::SizeClassAllocator32<0ul, 140737488355328ull, 0ul, __sanitizer::SizeClassMap<3ul, 4ul, 8ul, 17ul, 64ul, 14ul>, 20ul, __sanitizer::TwoLevelByteMap<32768ull, 4096ull, __sanitizer::NoOpMapUnmapCallback>, __sanitizer::NoOpMapUnmapCallback> >*)':
                gotsan.cc:(.text+0x7438): undefined reference to `__libc_free'
                collect2: error: ld returned 1 exit status

        go_test.go:289: go [install -race -pkgdir=/tmp/gotest207241282/pkg std] failed unexpectedly: exit status 2
```

</details>

<details>
<summary>TestGoTestRaceInstallCgo</summary>

```
--- FAIL: TestGoTestRaceInstallCgo (1.90s)
        go_test.go:260: running testgo [tool -n cgo]
        go_test.go:275: standard output:
        go_test.go:276: /usr/src/go/pkg/tool/linux_amd64/cgo

        go_test.go:260: running testgo [test -race -i runtime/race]
        go_test.go:279: standard error:
        go_test.go:280: # runtime/race
                race_linux_amd64.syso: In function `__sanitizer::InternalAlloc(unsigned long, __sanitizer::SizeClassAllocatorLocalCache<__sanitizer::SizeClassAllocator32<0ul, 140737488355328ull, 0ul, __sanitizer::SizeClassMap<3ul, 4ul, 8ul, 17ul, 64ul, 14ul>, 20ul, __sanitizer::TwoLevelByteMap<32768ull, 4096ull, __sanitizer::NoOpMapUnmapCallback>, __sanitizer::NoOpMapUnmapCallback> >*, unsigned long)':
                gotsan.cc:(.text+0x16e1): undefined reference to `__libc_malloc'
                race_linux_amd64.syso: In function `__sanitizer::GetArgv()':
                gotsan.cc:(.text+0x4543): undefined reference to `__libc_stack_end'
                race_linux_amd64.syso: In function `__sanitizer::InternalRealloc(void*, unsigned long, __sanitizer::SizeClassAllocatorLocalCache<__sanitizer::SizeClassAllocator32<0ul, 140737488355328ull, 0ul, __sanitizer::SizeClassMap<3ul, 4ul, 8ul, 17ul, 64ul, 14ul>, 20ul, __sanitizer::TwoLevelByteMap<32768ull, 4096ull, __sanitizer::NoOpMapUnmapCallback>, __sanitizer::NoOpMapUnmapCallback> >*)':
                gotsan.cc:(.text+0x7dd0): undefined reference to `__libc_realloc'
                race_linux_amd64.syso: In function `__sanitizer::ReExec()':
                gotsan.cc:(.text+0xed47): undefined reference to `__libc_stack_end'
                race_linux_amd64.syso: In function `__sanitizer::InternalFree(void*, __sanitizer::SizeClassAllocatorLocalCache<__sanitizer::SizeClassAllocator32<0ul, 140737488355328ull, 0ul, __sanitizer::SizeClassMap<3ul, 4ul, 8ul, 17ul, 64ul, 14ul>, 20ul, __sanitizer::TwoLevelByteMap<32768ull, 4096ull, __sanitizer::NoOpMapUnmapCallback>, __sanitizer::NoOpMapUnmapCallback> >*)':
                gotsan.cc:(.text+0x7438): undefined reference to `__libc_free'
                collect2: error: ld returned 1 exit status

        go_test.go:289: go [test -race -i runtime/race] failed unexpectedly: exit status 2
```

</details>

<details>
<summary>TestGoTestRaceFailures</summary>

```
--- FAIL: TestGoTestRaceFailures (0.69s)
        go_test.go:260: running testgo [test testrace]
        go_test.go:275: standard output:
        go_test.go:276: ok      testrace        0.002s

        go_test.go:260: running testgo [test -race testrace]
        go_test.go:275: standard output:
        go_test.go:276: FAIL    testrace [build failed]

        go_test.go:279: standard error:
        go_test.go:280: # runtime/race
                race_linux_amd64.syso: In function `__sanitizer::InternalAlloc(unsigned long, __sanitizer::SizeClassAllocatorLocalCache<__sanitizer::SizeClassAllocator32<0ul, 140737488355328ull, 0ul, __sanitizer::SizeClassMap<3ul, 4ul, 8ul, 17ul, 64ul, 14ul>, 20ul, __sanitizer::TwoLevelByteMap<32768ull, 4096ull, __sanitizer::NoOpMapUnmapCallback>, __sanitizer::NoOpMapUnmapCallback> >*, unsigned long)':
                gotsan.cc:(.text+0x16e1): undefined reference to `__libc_malloc'
                race_linux_amd64.syso: In function `__sanitizer::GetArgv()':
                gotsan.cc:(.text+0x4543): undefined reference to `__libc_stack_end'
                race_linux_amd64.syso: In function `__sanitizer::InternalRealloc(void*, unsigned long, __sanitizer::SizeClassAllocatorLocalCache<__sanitizer::SizeClassAllocator32<0ul, 140737488355328ull, 0ul, __sanitizer::SizeClassMap<3ul, 4ul, 8ul, 17ul, 64ul, 14ul>, 20ul, __sanitizer::TwoLevelByteMap<32768ull, 4096ull, __sanitizer::NoOpMapUnmapCallback>, __sanitizer::NoOpMapUnmapCallback> >*)':
                gotsan.cc:(.text+0x7dd0): undefined reference to `__libc_realloc'
                race_linux_amd64.syso: In function `__sanitizer::ReExec()':
                gotsan.cc:(.text+0xed47): undefined reference to `__libc_stack_end'
                race_linux_amd64.syso: In function `__sanitizer::InternalFree(void*, __sanitizer::SizeClassAllocatorLocalCache<__sanitizer::SizeClassAllocator32<0ul, 140737488355328ull, 0ul, __sanitizer::SizeClassMap<3ul, 4ul, 8ul, 17ul, 64ul, 14ul>, 20ul, __sanitizer::TwoLevelByteMap<32768ull, 4096ull, __sanitizer::NoOpMapUnmapCallback>, __sanitizer::NoOpMapUnmapCallback> >*)':
                gotsan.cc:(.text+0x7438): undefined reference to `__libc_free'
                collect2: error: ld returned 1 exit status

        go_test.go:299: testgo failed as expected: exit status 2
        go_test.go:365: TestRace did not fail
        go_test.go:366: pattern FAIL: TestRace not found in standard output
FAIL
```

</details>

**Comment by jessfraz** [comment]
Lastly there is:

```
--- FAIL: TestGroupCleanup (0.00s)
        exec_linux_test.go:214: id command output: "uid=0(root) gid=0(root)", expected prefix: "uid=0(root) gid=0(root) groups=0(root)"
--- FAIL: TestGroupCleanupUserNamespace (0.00s)
        exec_linux_test.go:256: id command output: "uid=0(root) gid=0(root) groups=0(root),65534(nobody),65534(nobody),65534(nobody),65534(nobody),65534(nobody),65534(nobody),65534(nobody),65534(nobody),65534(nobody),65534(nobody)", expected one of ["uid=0(root) gid=0(root) groups=0(root)" "uid=0(root) gid=0(root) groups=0(root),65534(nobody)" "uid=0(root) gid=0(root) groups=0(root),65534(nogroup)" "uid=0(root) gid=0(root) groups=0(root),65534"]
FAIL
```

which I can open a CL to fix

**Comment by bradfitz** [comment]
Should we run the Alpine builder with CGO_ENABLED=0 perhaps?

**Comment by ianlancetaylor** [comment]
@bradfitz That seems reasonable until we have a fix for #18243.

**Comment by bradfitz** [comment]
I'm slightly repurposing this bug.

There are existing bugs tracking fixing actual Alpine problems, such as:

#18243 -- internal linking broken
#14481 -- race doesn't work

This bug is only about getting the builders in "ok" state, even if that means temporarily disabling some tests.

To that end, I just tried setting GO_EXTLINK_ENABLED=1 on the Alpine builder in https://go-review.googlesource.com/c/41798/ but that seems to have caused a new error:

https://build.golang.org/log/a3288076e1057e053548837886fb064f2cf5d921
```
--- FAIL: TestSimpleDeadlock (60.10s)
	crash_test.go:106: testprog SimpleDeadlock exit status: exit status 2
	crash_test.go:205: output does not start with "fatal error: all goroutines are asleep - deadlock!\n":
		SIGQUIT: quit
		PC=0x454a31 m=0 sigcode=0
		
		goroutine 0 [idle]:
		runtime.futex(0x787990, 0x0, 0x0, 0x0, 0x0, 0x7fb672d977c0, 0x0, 0x0, 0x7ffeae1c2008, 0x40e211, ...)
			/tmp/workdir/go/src/runtime/sys_linux_amd64.s:422 +0x21
		runtime.futexsleep(0x787990, 0x0, 0xffffffffffffffff)
			/tmp/workdir/go/src/runtime/os_linux.go:45 +0x62
		runtime.notesleep(0x787990)
			/tmp/workdir/go/src/runtime/lock_futex.go:150 +0x81
		runtime.stopm()
			/tmp/workdir/go/src/runtime/proc.go:1637 +0xe5
		runtime.findrunnable(0xc42001c000, 0x0)
			/tmp/workdir/go/src/runtime/proc.go:2092 +0x5c7
		runtime.schedule()
			/tmp/workdir/go/src/runtime/proc.go:2212 +0x134
		runtime.park_m(0xc420000180)
			/tmp/workdir/go/src/runtime/proc.go:2275 +0xb6
		runtime.mcall(0x7ffeae1c21a0)
			/tmp/workdir/go/src/runtime/asm_amd64.s:276 +0x5b
		
		goroutine 1 [select (no cases)]:
		main.SimpleDeadlock()
			/tmp/workdir/go/src/runtime/testdata/testprog/deadlock.go:39 +0x20
		main.main()
			/tmp/workdir/go/src/runtime/testdata/testprog/main.go:34 +0x1da
		
		goroutine 17 [syscall, locked to thread]:
		runtime.goexit()
			/tmp/workdir/go/src/runtime/asm_amd64.s:2349 +0x1
		
		rax    0xca
		rbx    0x787880
		rcx    0x454a33
		rdx    0x0
		rdi    0x787990
		rsi    0x0
		rbp    0x7ffeae1c1fd0
		rsp    0x7ffeae1c1f88
		r8     0x0
		r9     0x0
		r10    0x0
		r11    0x286
		r12    0xc420096fa3
		r13    0x8
		r14    0xffffffffffffffff
		r15    0x8
		rip    0x454a31
		rflags 0x286
		cs     0x33
		fs     0x0
		gs     0x0
--- FAIL: TestInitDeadlock (60.00s)
...
(same)
...
panic: test timed out after 3m0s
```

I guess the external linker disables deadlock detection?

**Comment by bradfitz** [comment]
I cleared the four builds from the dashboard built with GO_EXTLINK_ENABLED=1.

They're now all back to failing with:

https://build.golang.org/log/4d41ef62d744100b3271757b084f95166abddbb5
```
##### ../misc/cgo/test
unexpected fault address 0x7fb6ae1a9b90
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7fb6ae1a9b90 pc=0x7fb6ae1a9b90]

goroutine 19 [running]:
runtime.throw(0x5dc6d5, 0x5)
        /tmp/workdir/go/src/runtime/panic.go:596 +0x95 fp=0xc420046768 sp=0xc420046748
runtime.sigpanic()
        /tmp/workdir/go/src/runtime/signal_unix.go:355 +0x282 fp=0xc4200467b8 sp=0xc420046768
created by _/tmp/workdir/go/misc/cgo/test.runTestSetgid
        /tmp/workdir/go/misc/cgo/test/setgid_linux.go:26 +0x6f
```

From local changes with `go test -v`, I see that crash is from `=== RUN   TestSetgid`

**Comment by bradfitz** [comment]
And if I skip TestSetgid, it just moves to a few tests later:

```
##### ../misc/cgo/test
=== RUN   TestSetgid
--- SKIP: TestSetgid (0.00s)
        setgid_linux.go:40: temp skip
=== RUN   Test6997
--- PASS: Test6997 (0.50s)
=== RUN   TestBuildID
--- PASS: TestBuildID (0.00s)
=== RUN   Test9400
unexpected fault address 0x7f38ab094af8
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7f38ab094af8 pc=0x7f38ab094af8]
 
goroutine 9 [running, locked to thread]:
runtime.throw(0x5dc739, 0x5)
        /tmp/workdir/go/src/runtime/panic.go:596 +0x95 fp=0xc420046768 sp=0xc420046748
runtime.sigpanic()
        /tmp/workdir/go/src/runtime/signal_unix.go:355 +0x282 fp=0xc4200467b8 sp=0xc420046768
created by _/tmp/workdir/go/misc/cgo/test.test9400
        /tmp/workdir/go/misc/cgo/test/issue9400_linux.go:30 +0xa2
```

**Comment by mwhudson** [comment]
How can I reproduce this? (no promises, but I might be able to have a quick poke at it)

**Comment by bradfitz** [comment]
gomote if you have access (email me if not) or run all.bash in an Alpine Docker container: https://github.com/golang/build/blob/master/env/linux-x86-alpine/Dockerfile

**Comment by chlunde** [comment]
Regarding the TestSetgid and Test9400 crashes, here's my understanding of the issue:
* Go requires all signal handlers to use `SA_ONSTACK` to execute on an alternate stack. See #9400, https://golang.org/pkg/os/signal/ and http://man7.org/linux/man-pages/man2/sigaltstack.2.html for more information.
* setxid requires a lot of special care for multithreaded programs on Linux.  musl uses `SIGRT_2` (34) as `SIGSYNCCALL` to perform `setxid` across multiple threads. See https://ewontfix.com/17/ and http://git.musl-libc.org/cgit/musl/tree/src/thread/synccall.c
* musl does not set `SA_ONSTACK` (and `SA_RESTART`), which means the signal will be executed on a very small go stack, which will likely overflow, and then cause a `SIGSEGV`
* unlike glibc, the handler is installed only when required, which means the go runtime will not be able to patch the handler flags, so a code change in musl is required.  I have not found any trivial workaround.

### Alt. A: Increasing stack guard area
As a temporary workaround, it is possible to set/increase the guard area by setting `_StackSystem = 2048` in `src/runtime/stack.go`, or maybe even higher.  
```diff
--- a/src/runtime/sigtab_linux_generic.go
+++ b/src/runtime/sigtab_linux_generic.go
@@ -50,7 +50,7 @@ var sigtable = [...]sigTabT{
        /* 31 */ {_SigThrow, "SIGSYS: bad system call"},
        /* 32 */ {_SigSetStack + _SigUnblock, "signal 32"}, /* SIGCANCEL; see issue 6997 */
        /* 33 */ {_SigSetStack + _SigUnblock, "signal 33"}, /* SIGSETXID; see issues 3871, 9400, 12498 */
-       /* 34 */ {_SigNotify, "signal 34"},
+       /* 34 */ {_SigSetStack + _SigUnblock, "signal 34"}, /* SIGSYNCCALL; see issue 19938 */
diff --git a/src/runtime/stack.go b/src/runtime/stack.go
index 562427a..4eb3368 100644
--- a/src/runtime/stack.go
+++ b/src/runtime/stack.go
@@ -65,7 +65,8 @@ const (
        // to each stack below the usual guard area for OS-specific
        // purposes like signal handling. Used on Windows, Plan 9,
        // and Darwin/ARM because they do not use a separate stack.
-       _StackSystem = sys.GoosWindows*512*sys.PtrSize + sys.GoosPlan9*512 + sys.GoosDarwin*sys.GoarchArm*1024
+       _StackSystem = sys.GoosWindows*512*sys.PtrSize + sys.GoosPlan9*512 + sys.GoosDarwin*sys.GoarchArm*1024 + 2048 // TODO: conditional on cgo + musl?
```

I assume this is not something we want, even if it could be made conditional on cgo+musl.  It does seem to work, but test9400 would also need an update:
```
	issue9400_linux.go:55: entry 756 of test pattern is wrong; 0x7ff92884d045 != 0x123456789abcdef
```

### Alt. B: Modifying musl
If I modify musl to

    ./src/thread/synccall.c:	struct sigaction sa = { .sa_flags = SA_ONSTACK|SA_RESTART, .sa_handler = handler };

this test case does not crash.

There are probably more handlers in musl which needs a look, for example:
* src/time/timer_create.c
* src/thread/pthread_cancel.c
and perhaps
* src/process/posix_spawn.c

Do we think it would be reasonable for musl to use `SA_ONSTACK|SA_RESTART` by default, or might that break other programs?  Are there any other alternatives that will not break other programs?  One idea I have is that we might be able to set `SA_ONSTACK|SA_RESTART` on the relevant handlers with `SIG_DFL`, and then request that musl changes behaviour and check for that property on these signals, and reuse the same flags on its own handler.  I believe musl clobbers the handler anyway, so it should not break any existing behaviour.

PS!  To get this error message to print: `fatal error: unexpected signal during runtime execution`, I had to make some changes, but I do not know if they are safe.
```diff
diff --git a/src/runtime/signal_unix.go b/src/runtime/signal_unix.go
index e0ea724..c20528e 100644
--- a/src/runtime/signal_unix.go
+++ b/src/runtime/signal_unix.go
@@ -326,10 +326,13 @@ func sigtrampgo(sig uint32, info *siginfo, ctx unsafe.Pointer) {
 // the signal handler. The effect is that the program will act as
 // though the function that got the signal simply called sigpanic
 // instead.
+//go:nosplit
 func sigpanic() {
        g := getg()
        if !canpanic(g) {
-               throw("unexpected signal during runtime execution")
+               systemstack(func() {
+                       throw("unexpected signal during runtime execution")
+               })
        }
 
        switch g.sig {
```

**Comment by ianlancetaylor** [comment]
The use of `SA_RESTART` is not too important (but see #20400) but every signal handler in a Go program must use `SA_ONSTACK`.  Since `SA_ONSTACK` does nothing if the thread does not call `sigaltstack`, and since a thread that calls `sigaltstack` presumably wants to actually use it, I think it would be reasonable for musl to use `SA_ONSTACK` when it temporarily installs a signal handler.  Of course, I am not a musl maintainer.

**Comment by richfelker** [comment]
I'm not entirely opposed to using SA_ONSTACK for the implementation-internal signals, but also cautious, as it means the signal handlers may end up running on an application-provided stack rather than the main one. The signal handlers in musl themselves use very little stack space, so the culprit causing the crash is almost certainly the kernel saving sigcontext, which can be very large on some archs. Could you post to the musl mailing list explaining the issue so we can discuss it somewhere the musl community sees and has an opportunity to give feedback if there are concerns about SA_ONSTACK?

**Comment by nmeum** [comment]
What is the current status on this? The cgo issues discussed above are also (partially?) discussed in #39857. *I think* the related discussion on the musl ML is https://www.openwall.com/lists/musl/2020/08/09/1 (@richfelker has there been any update on this?).

I am a contributor to Alpine Linux. At Alpine we simply run the Go testsuite as `./run.bash -run='!(^cgo_test$)'`, i.e. we disable the cgo tests (due to #39857). Maybe it would be possible to do that on on official Go Alpine runner as well in the meantime (i.e. until this aforementioned issue is addressed in musl) to catch stuff like #51787 earlier in the future? (:

**Comment by ALTree** [comment]
The current status is that the Alpine builder is still disabled and no one is working on that, I think.

The original Alpine builder config is here: https://github.com/golang/build/tree/cb8d385252287910555c8d2d9a058ea17e0e921a/env/linux-x86-alpine

The code that keeps it disabled is here: https://github.com/golang/build/blob/3ce827870238fe4179c5505312493a9e99f7704e/dashboard/builders.go#L1601

If there's some interesting in reviving in, the first steps would be (if the team in charge of the build infrastructure agree) to see if it works and send patched re-enabling it. This is the easy part. Then keep it green and passing. This is the hard part.

**Comment by nocive** [comment]
:arrow_up:
