### ISSUE TITLE
testing (gccgo): panic in subtest does not include test or subtest name in output

### ISSUE THREAD

**Issue by bcmills** [golang/go#19951]
```
$ gccgo --version
gccgo (google-gccgo-245786) 7.0.1 20170228 (experimental)
$ go version
go version go1.8.1 linux/amd64
```

gccgosubtest/gccgosubtest_test.go:
```go
package gccgosubtest

import (
	"fmt"
	"testing"
)

func TestPanicInTest(t *testing.T) {
	panic("oh 💩!")
}

func TestPanicInSubtest(t *testing.T) {
	for i := 0; i < 3; i++ {
		t.Run(fmt.Sprint(i), func(t *testing.T) {
			if i == 2 {
				panic("oh 💩!")
			}
		})
	}
}
```

If a regular test panics, I get both a `FAIL` message with the test name and a stack trace that includes the test function.

```
$ go test -run=TestPanicInTest -gccgoflags=-static -compiler gccgo gccgosubtest
--- FAIL: TestPanicInTest (0.00s)
panic: oh 💩! [recovered]
        panic: oh 💩!

goroutine 19 [running]:
runtime.gopanic
        […]/libgo/go/runtime/panic.go:493
testing.$nested8
        […]/libgo/go/testing/testing.go:607
runtime.gopanic
        […]/libgo/go/runtime/panic.go:450
gccgosubtest.TestPanicInTest
        […]/gccgosubtest/gccgosubtest_test.go:9
testing.tRunner
        […]/libgo/go/testing/testing.go:657
kickoff
        […]/libgo/runtime/proc.c:273
FAIL    gccgosubtest    0.258s
```

However, if the panic occurs in a subtest, the test header is missing _and_ the stack trace for the panic doesn't include the name of the test function.  (The only function on the stack at that point is the closure passed to `t.Run`, which `gccgo` unhelpfully names `$nested0`.)  In that case, all I have to go by is the file and line number:

```
$ go test -run=TestPanicInSubtest -gccgoflags=-static -compiler gccgo gccgosubtest
panic: oh 💩! [recovered]
        panic: oh 💩!

goroutine 22 [running]:
runtime.gopanic
        […]/libgo/go/runtime/panic.go:493
testing.$nested8
        […]/libgo/go/testing/testing.go:607
runtime.gopanic
        […]/libgo/go/runtime/panic.go:450
gccgosubtest.$nested0
        […]/gccgosubtest/gccgosubtest_test.go:16
testing.tRunner
        […]/libgo/go/testing/testing.go:657
kickoff
        […]/libgo/runtime/proc.c:273
FAIL    gccgosubtest    0.300s
```

**Comment by bcmills** [comment]
(@ianlancetaylor)

**Comment by ianlancetaylor** [comment]
This is now fixed on tip.

```
panic: oh 💩! [recovered]
	panic: oh 💩!

goroutine 8 [running]:
panic
	../../../gccgo3/libgo/go/runtime/panic.go:557
testing.tRunner..func1
	../../../gccgo3/libgo/go/testing/testing.go:728
panic
	../../../gccgo3/libgo/go/runtime/panic.go:498
gccgosubtest.TestPanicInSubtest..func1
	/home/iant/foo_test.go:16
testing.tRunner
	../../../gccgo3/libgo/go/testing/testing.go:777
created by testing.T.Run
	../../../gccgo3/libgo/go/testing/testing.go:824 +989
FAIL	command-line-arguments	0.060s
```
