### ISSUE TITLE
reflect Convert can't work

### ISSUE THREAD

**Issue by qianlnk** [golang/go#20006]
## go version

go 1.7

## code

[https://play.golang.org/p/Ka9aEOlTvU](https://play.golang.org/p/Ka9aEOlTvU)

## Error message 

```shell
panic: reflect.Value.Convert: value of type main.S cannot be converted to type struct { Name string "json:\"-\""; F string "species:\"gopher\" colo
r:\"blue\"" }

goroutine 1 [running]:
panic(0xd3040, 0xc42000a3f0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
reflect.Value.Convert(0xe2240, 0xc42000e2c0, 0x99, 0x174720, 0xc420018120, 0xc420070f70, 0x1, 0x2)
        /usr/local/go/src/reflect/value.go:2175 +0x20b
main.main()
        /Users/qianlnk/go/src/github.com/qianlnk/koala/05/test.go:27 +0x3b4
exit status 2
```

**Comment by bradfitz** [comment]
The was a language change in Go 1.8, not Go 1.7. See:

https://golang.org/doc/go1.8#language
