### ISSUE TITLE
misc/cgo/test: test failures on Alpine (musl libc)

### ISSUE THREAD

**Issue by bradfitz** [golang/go#20120]
I'm not sure what's failing here. @ianlancetaylor?

https://build.golang.org/log/b9c96d2af39554722bc44ba53c5f4c50a7817e14
```
##### ../misc/cgo/test
unexpected fault address 0x7f29641b6b90
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7f29641b6b90 pc=0x7f29641b6b90]

goroutine 19 [running]:
runtime.throw(0x5dc4d1, 0x5)
	/tmp/workdir/go/src/runtime/panic.go:596 +0x95 fp=0xc420048768 sp=0xc420048748
runtime.sigpanic()
	/tmp/workdir/go/src/runtime/signal_unix.go:355 +0x282 fp=0xc4200487b8 sp=0xc420048768
created by _/tmp/workdir/go/misc/cgo/test.runTestSetgid
	/tmp/workdir/go/misc/cgo/test/setgid_linux.go:26 +0x6f

goroutine 1 [chan receive]:
runtime.gopark(0x5e9cb0, 0xc4200bc1d8, 0x5ddfee, 0xc, 0xc42001f317, 0x3)
	/tmp/workdir/go/src/runtime/proc.go:268 +0x12c fp=0xc42006fb40 sp=0xc42006fb10
runtime.goparkunlock(0xc4200bc1d8, 0x5ddfee, 0xc, 0x17, 0x3)
	/tmp/workdir/go/src/runtime/proc.go:274 +0x5e fp=0xc42006fb80 sp=0xc42006fb40
runtime.chanrecv(0xc4200bc180, 0x0, 0xc42006fc01, 0x4c421e)
	/tmp/workdir/go/src/runtime/chan.go:506 +0x304 fp=0xc42006fc30 sp=0xc42006fb80
runtime.chanrecv1(0xc4200bc180, 0x0)
	/tmp/workdir/go/src/runtime/chan.go:388 +0x2b fp=0xc42006fc60 sp=0xc42006fc30
testing.(*T).Run(0xc4200be000, 0x5dd7b7, 0xa, 0x5e6e48, 0x474b76)
	/tmp/workdir/go/src/testing/testing.go:789 +0x2fc fp=0xc42006fd10 sp=0xc42006fc60
testing.runTests.func1(0xc4200be000)
	/tmp/workdir/go/src/testing/testing.go:975 +0x6c fp=0xc42006fd60 sp=0xc42006fd10
testing.tRunner(0xc4200be000, 0xc42006fe10)
	/tmp/workdir/go/src/testing/testing.go:746 +0xd0 fp=0xc42006fd88 sp=0xc42006fd60
testing.runTests(0xc4200ba000, 0x8e1740, 0x4a, 0x4a, 0x0)
	/tmp/workdir/go/src/testing/testing.go:973 +0x1f6 fp=0xc42006fe40 sp=0xc42006fd88
testing.(*M).Run(0xc42006ff20, 0xc42006ff78)
	/tmp/workdir/go/src/testing/testing.go:915 +0xf7 fp=0xc42006ff10 sp=0xc42006fe40
main.main()
	_/tmp/workdir/go/misc/cgo/test/_test/_testmain.go:192 +0xdb fp=0xc42006ff88 sp=0xc42006ff10
runtime.main()
	/tmp/workdir/go/src/runtime/proc.go:185 +0x205 fp=0xc42006ffe0 sp=0xc42006ff88
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:2349 +0x1 fp=0xc42006ffe8 sp=0xc42006ffe0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:2349 +0x1 fp=0xc42005efe8 sp=0xc42005efe0

goroutine 2 [force gc (idle)]:
runtime.gopark(0x5e9cb0, 0x8f5af0, 0x5deb0e, 0xf, 0x5e9b14, 0x1)
	/tmp/workdir/go/src/runtime/proc.go:268 +0x12c fp=0xc42004c768 sp=0xc42004c738
runtime.goparkunlock(0x8f5af0, 0x5deb0e, 0xf, 0xc420000114, 0x1)
	/tmp/workdir/go/src/runtime/proc.go:274 +0x5e fp=0xc42004c7a8 sp=0xc42004c768
runtime.forcegchelper()
	/tmp/workdir/go/src/runtime/proc.go:226 +0x82 fp=0xc42004c7e0 sp=0xc42004c7a8
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:2349 +0x1 fp=0xc42004c7e8 sp=0xc42004c7e0
created by runtime.init.4
	/tmp/workdir/go/src/runtime/proc.go:215 +0x35

goroutine 3 [GC sweep wait]:
runtime.gopark(0x5e9cb0, 0x8f5cc0, 0x5de2c7, 0xd, 0x423914, 0x1)
	/tmp/workdir/go/src/runtime/proc.go:268 +0x12c fp=0xc42004cf60 sp=0xc42004cf30
runtime.goparkunlock(0x8f5cc0, 0x5de2c7, 0xd, 0x14, 0x1)
	/tmp/workdir/go/src/runtime/proc.go:274 +0x5e fp=0xc42004cfa0 sp=0xc42004cf60
runtime.bgsweep(0xc420018070)
	/tmp/workdir/go/src/runtime/mgcsweep.go:52 +0xa3 fp=0xc42004cfd8 sp=0xc42004cfa0
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:2349 +0x1 fp=0xc42004cfe0 sp=0xc42004cfd8
created by runtime.gcenable
	/tmp/workdir/go/src/runtime/mgc.go:216 +0x5d

goroutine 4 [finalizer wait]:
runtime.gopark(0x5e9cb0, 0x955168, 0x5de761, 0xe, 0x14, 0x1)
	/tmp/workdir/go/src/runtime/proc.go:268 +0x12c fp=0xc42004d700 sp=0xc42004d6d0
runtime.goparkunlock(0x955168, 0x5de761, 0xe, 0x14, 0x1)
	/tmp/workdir/go/src/runtime/proc.go:274 +0x5e fp=0xc42004d740 sp=0xc42004d700
runtime.runfinq()
	/tmp/workdir/go/src/runtime/mfinal.go:175 +0x8d fp=0xc42004d7e0 sp=0xc42004d740
created by runtime.createfing
	/tmp/workdir/go/src/runtime/mfinal.go:156 +0x62

goroutine 5 [syscall]:
runtime.notetsleepg(0x955440, 0xffffffffffffffff, 0x0)
	/tmp/workdir/go/src/runtime/lock_futex.go:226 +0x42 fp=0xc42004df80 sp=0xc42004df50
os/signal.signal_recv(0x0)
	/tmp/workdir/go/src/runtime/sigqueue.go:116 +0xad fp=0xc42004dfa8 sp=0xc42004df80
os/signal.loop()
	/tmp/workdir/go/src/os/signal/signal_unix.go:22 +0x22 fp=0xc42004dfe0 sp=0xc42004dfa8
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:2349 +0x1 fp=0xc42004dfe8 sp=0xc42004dfe0
created by os/signal.init.0
	/tmp/workdir/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 18 [select]:
runtime.gopark(0x5e9ce8, 0x0, 0x5dc76d, 0x6, 0x18, 0x1)
	/tmp/workdir/go/src/runtime/proc.go:268 +0x12c fp=0xc42005abf0 sp=0xc42005abc0
runtime.selectgo(0xc42005aea0, 0xc4200bc2a0)
	/tmp/workdir/go/src/runtime/select.go:395 +0xc76 fp=0xc42005ae70 sp=0xc42005abf0
_/tmp/workdir/go/misc/cgo/test.runTestSetgid(0xf5bab)
	/tmp/workdir/go/misc/cgo/test/setgid_linux.go:30 +0x128 fp=0xc42005af30 sp=0xc42005ae70
_/tmp/workdir/go/misc/cgo/test.testSetgid(0xc4200be0f0)
	/tmp/workdir/go/misc/cgo/test/setgid_linux.go:40 +0x26 fp=0xc42005af90 sp=0xc42005af30
_/tmp/workdir/go/misc/cgo/test.TestSetgid(0xc4200be0f0)
	/tmp/workdir/go/misc/cgo/test/cgo_linux_test.go:9 +0x2b fp=0xc42005afa8 sp=0xc42005af90
testing.tRunner(0xc4200be0f0, 0x5e6e48)
	/tmp/workdir/go/src/testing/testing.go:746 +0xd0 fp=0xc42005afd0 sp=0xc42005afa8
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:2349 +0x1 fp=0xc42005afd8 sp=0xc42005afd0
created by testing.(*T).Run
	/tmp/workdir/go/src/testing/testing.go:788 +0x2de

goroutine 20 [syscall]:
runtime.notetsleepg(0x8f5d78, 0x12a05d9d9, 0x0)
	/tmp/workdir/go/src/runtime/lock_futex.go:226 +0x42 fp=0xc420048f60 sp=0xc420048f30
runtime.timerproc()
	/tmp/workdir/go/src/runtime/time.go:214 +0x325 fp=0xc420048fe0 sp=0xc420048f60
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:2349 +0x1 fp=0xc420048fe8 sp=0xc420048fe0
created by runtime.addtimerLocked
	/tmp/workdir/go/src/runtime/time.go:121 +0xed
exit status 2
FAIL	_/tmp/workdir/go/misc/cgo/test	0.023s
2017/04/25 20:17:22 Failed: exit status 1
unexpected fault address 0x7fd72848cb90
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7fd72848cb90 pc=0x7fd72848cb90]

goroutine 19 [running]:
runtime.throw(0x5d8d51, 0x5)
	/tmp/workdir/go/src/runtime/panic.go:596 +0x95 fp=0xc420048768 sp=0xc420048748
runtime.sigpanic()
	/tmp/workdir/go/src/runtime/signal_unix.go:355 +0x282 fp=0xc4200487b8 sp=0xc420048768
created by _/tmp/workdir/go/misc/cgo/test.runTestSetgid
	/tmp/workdir/go/misc/cgo/test/setgid_linux.go:26 +0x6f

goroutine 1 [chan receive]:
runtime.gopark(0x5e6530, 0xc4200ca1d8, 0x5da86e, 0xc, 0xc42001e017, 0x3)
	/tmp/workdir/go/src/runtime/proc.go:268 +0x12c fp=0xc42006fb40 sp=0xc42006fb10
runtime.goparkunlock(0xc4200ca1d8, 0x5da86e, 0xc, 0x17, 0x3)
	/tmp/workdir/go/src/runtime/proc.go:274 +0x5e fp=0xc42006fb80 sp=0xc42006fb40
runtime.chanrecv(0xc4200ca180, 0x0, 0xc42006fc01, 0x4c381e)
	/tmp/workdir/go/src/runtime/chan.go:506 +0x304 fp=0xc42006fc30 sp=0xc42006fb80
runtime.chanrecv1(0xc4200ca180, 0x0)
	/tmp/workdir/go/src/runtime/chan.go:388 +0x2b fp=0xc42006fc60 sp=0xc42006fc30
testing.(*T).Run(0xc4200cc000, 0x5da037, 0xa, 0x5e36c8, 0x474176)
	/tmp/workdir/go/src/testing/testing.go:789 +0x2fc fp=0xc42006fd10 sp=0xc42006fc60
testing.runTests.func1(0xc4200cc000)
	/tmp/workdir/go/src/testing/testing.go:975 +0x6c fp=0xc42006fd60 sp=0xc42006fd10
testing.tRunner(0xc4200cc000, 0xc42006fe10)
	/tmp/workdir/go/src/testing/testing.go:746 +0xd0 fp=0xc42006fd88 sp=0xc42006fd60
testing.runTests(0xc4200c8000, 0x6f1fe0, 0x4a, 0x4a, 0x0)
	/tmp/workdir/go/src/testing/testing.go:973 +0x1f6 fp=0xc42006fe40 sp=0xc42006fd88
testing.(*M).Run(0xc42006ff20, 0xc42006ff78)
	/tmp/workdir/go/src/testing/testing.go:915 +0xf7 fp=0xc42006ff10 sp=0xc42006fe40
main.main()
	_/tmp/workdir/go/misc/cgo/test/_test/_testmain.go:192 +0xdb fp=0xc42006ff88 sp=0xc42006ff10
runtime.main()
	/tmp/workdir/go/src/runtime/proc.go:185 +0x205 fp=0xc42006ffe0 sp=0xc42006ff88
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:2349 +0x1 fp=0xc42006ffe8 sp=0xc42006ffe0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:2349 +0x1 fp=0xc42005efe8 sp=0xc42005efe0

goroutine 2 [force gc (idle)]:
runtime.gopark(0x5e6530, 0x6f5db0, 0x5db38e, 0xf, 0x5e6414, 0x1)
	/tmp/workdir/go/src/runtime/proc.go:268 +0x12c fp=0xc42004c768 sp=0xc42004c738
runtime.goparkunlock(0x6f5db0, 0x5db38e, 0xf, 0xc420000114, 0x1)
	/tmp/workdir/go/src/runtime/proc.go:274 +0x5e fp=0xc42004c7a8 sp=0xc42004c768
runtime.forcegchelper()
	/tmp/workdir/go/src/runtime/proc.go:226 +0x82 fp=0xc42004c7e0 sp=0xc42004c7a8
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:2349 +0x1 fp=0xc42004c7e8 sp=0xc42004c7e0
created by runtime.init.4
	/tmp/workdir/go/src/runtime/proc.go:215 +0x35

goroutine 3 [GC sweep wait]:
runtime.gopark(0x5e6530, 0x6f5f80, 0x5dab47, 0xd, 0x422f14, 0x1)
	/tmp/workdir/go/src/runtime/proc.go:268 +0x12c fp=0xc42004cf60 sp=0xc42004cf30
runtime.goparkunlock(0x6f5f80, 0x5dab47, 0xd, 0x14, 0x1)
	/tmp/workdir/go/src/runtime/proc.go:274 +0x5e fp=0xc42004cfa0 sp=0xc42004cf60
runtime.bgsweep(0xc420018070)
	/tmp/workdir/go/src/runtime/mgcsweep.go:52 +0xa3 fp=0xc42004cfd8 sp=0xc42004cfa0
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:2349 +0x1 fp=0xc42004cfe0 sp=0xc42004cfd8
created by runtime.gcenable
	/tmp/workdir/go/src/runtime/mgc.go:216 +0x5d

goroutine 4 [finalizer wait]:
runtime.gopark(0x5e6530, 0x7132f0, 0x5dafe1, 0xe, 0x14, 0x1)
	/tmp/workdir/go/src/runtime/proc.go:268 +0x12c fp=0xc42004d700 sp=0xc42004d6d0
runtime.goparkunlock(0x7132f0, 0x5dafe1, 0xe, 0x14, 0x1)
	/tmp/workdir/go/src/runtime/proc.go:274 +0x5e fp=0xc42004d740 sp=0xc42004d700
runtime.runfinq()
	/tmp/workdir/go/src/runtime/mfinal.go:175 +0x8d fp=0xc42004d7e0 sp=0xc42004d740
created by runtime.createfing
	/tmp/workdir/go/src/runtime/mfinal.go:156 +0x62

goroutine 5 [syscall]:
runtime.notetsleepg(0x7135c0, 0xffffffffffffffff, 0x0)
	/tmp/workdir/go/src/runtime/lock_futex.go:226 +0x42 fp=0xc42004df80 sp=0xc42004df50
os/signal.signal_recv(0x0)
	/tmp/workdir/go/src/runtime/sigqueue.go:116 +0xad fp=0xc42004dfa8 sp=0xc42004df80
os/signal.loop()
	/tmp/workdir/go/src/os/signal/signal_unix.go:22 +0x22 fp=0xc42004dfe0 sp=0xc42004dfa8
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:2349 +0x1 fp=0xc42004dfe8 sp=0xc42004dfe0
created by os/signal.init.0
	/tmp/workdir/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 18 [select]:
runtime.gopark(0x5e6568, 0x0, 0x5d8fed, 0x6, 0x18, 0x1)
	/tmp/workdir/go/src/runtime/proc.go:268 +0x12c fp=0xc42005abf0 sp=0xc42005abc0
runtime.selectgo(0xc42005aea0, 0xc4200ca2a0)
	/tmp/workdir/go/src/runtime/select.go:395 +0xc76 fp=0xc42005ae70 sp=0xc42005abf0
_/tmp/workdir/go/misc/cgo/test.runTestSetgid(0xf5bab)
	/tmp/workdir/go/misc/cgo/test/setgid_linux.go:30 +0x128 fp=0xc42005af30 sp=0xc42005ae70
_/tmp/workdir/go/misc/cgo/test.testSetgid(0xc4200cc0f0)
	/tmp/workdir/go/misc/cgo/test/setgid_linux.go:40 +0x26 fp=0xc42005af90 sp=0xc42005af30
_/tmp/workdir/go/misc/cgo/test.TestSetgid(0xc4200cc0f0)
	/tmp/workdir/go/misc/cgo/test/cgo_linux_test.go:9 +0x2b fp=0xc42005afa8 sp=0xc42005af90
testing.tRunner(0xc4200cc0f0, 0x5e36c8)
	/tmp/workdir/go/src/testing/testing.go:746 +0xd0 fp=0xc42005afd0 sp=0xc42005afa8
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:2349 +0x1 fp=0xc42005afd8 sp=0xc42005afd0
created by testing.(*T).Run
	/tmp/workdir/go/src/testing/testing.go:788 +0x2de

goroutine 20 [syscall]:
runtime.notetsleepg(0x6f6038, 0x12a05ce8a, 0x0)
	/tmp/workdir/go/src/runtime/lock_futex.go:226 +0x42 fp=0xc420048f60 sp=0xc420048f30
runtime.timerproc()
	/tmp/workdir/go/src/runtime/time.go:214 +0x325 fp=0xc420048fe0 sp=0xc420048f60
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:2349 +0x1 fp=0xc420048fe8 sp=0xc420048fe0
created by runtime.addtimerLocked
	/tmp/workdir/go/src/runtime/time.go:121 +0xed
exit status 2
FAIL	_/tmp/workdir/go/misc/cgo/test	0.025s
2017/04/25 20:17:22 Failed: exit status 1
unexpected fault address 0x7f1c7c17ab90
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7f1c7c17ab90 pc=0x7f1c7c17ab90]

goroutine 19 [running]:
runtime.throw(0x5dc4d1, 0x5)
	/tmp/workdir/go/src/runtime/panic.go:596 +0x95 fp=0xc420048768 sp=0xc420048748
runtime.sigpanic()
	/tmp/workdir/go/src/runtime/signal_unix.go:355 +0x282 fp=0xc4200487b8 sp=0xc420048768
created by _/tmp/workdir/go/misc/cgo/test.runTestSetgid
	/tmp/workdir/go/misc/cgo/test/setgid_linux.go:26 +0x6f

goroutine 1 [chan receive]:
runtime.gopark(0x5e9cb0, 0xc4200ba1d8, 0x5ddfee, 0xc, 0xc42001f317, 0x3)
	/tmp/workdir/go/src/runtime/proc.go:268 +0x12c fp=0xc42006fb40 sp=0xc42006fb10
runtime.goparkunlock(0xc4200ba1d8, 0x5ddfee, 0xc, 0x17, 0x3)
	/tmp/workdir/go/src/runtime/proc.go:274 +0x5e fp=0xc42006fb80 sp=0xc42006fb40
runtime.chanrecv(0xc4200ba180, 0x0, 0xc42006fc01, 0x4c421e)
	/tmp/workdir/go/src/runtime/chan.go:506 +0x304 fp=0xc42006fc30 sp=0xc42006fb80
runtime.chanrecv1(0xc4200ba180, 0x0)
	/tmp/workdir/go/src/runtime/chan.go:388 +0x2b fp=0xc42006fc60 sp=0xc42006fc30
testing.(*T).Run(0xc4200bc000, 0x5dd7b7, 0xa, 0x5e6e48, 0x474b76)
	/tmp/workdir/go/src/testing/testing.go:789 +0x2fc fp=0xc42006fd10 sp=0xc42006fc60
testing.runTests.func1(0xc4200bc000)
	/tmp/workdir/go/src/testing/testing.go:975 +0x6c fp=0xc42006fd60 sp=0xc42006fd10
testing.tRunner(0xc4200bc000, 0xc42006fe10)
	/tmp/workdir/go/src/testing/testing.go:746 +0xd0 fp=0xc42006fd88 sp=0xc42006fd60
testing.runTests(0xc4200b6000, 0x8e1740, 0x4a, 0x4a, 0x0)
	/tmp/workdir/go/src/testing/testing.go:973 +0x1f6 fp=0xc42006fe40 sp=0xc42006fd88
testing.(*M).Run(0xc42006ff20, 0xc42006ff78)
	/tmp/workdir/go/src/testing/testing.go:915 +0xf7 fp=0xc42006ff10 sp=0xc42006fe40
main.main()
	_/tmp/workdir/go/misc/cgo/test/_test/_testmain.go:192 +0xdb fp=0xc42006ff88 sp=0xc42006ff10
runtime.main()
	/tmp/workdir/go/src/runtime/proc.go:185 +0x205 fp=0xc42006ffe0 sp=0xc42006ff88
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:2349 +0x1 fp=0xc42006ffe8 sp=0xc42006ffe0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:2349 +0x1 fp=0xc42005efe8 sp=0xc42005efe0

goroutine 2 [force gc (idle)]:
runtime.gopark(0x5e9cb0, 0x8f5af0, 0x5deb0e, 0xf, 0x5e9b14, 0x1)
	/tmp/workdir/go/src/runtime/proc.go:268 +0x12c fp=0xc42004c768 sp=0xc42004c738
runtime.goparkunlock(0x8f5af0, 0x5deb0e, 0xf, 0xc420000114, 0x1)
	/tmp/workdir/go/src/runtime/proc.go:274 +0x5e fp=0xc42004c7a8 sp=0xc42004c768
runtime.forcegchelper()
	/tmp/workdir/go/src/runtime/proc.go:226 +0x82 fp=0xc42004c7e0 sp=0xc42004c7a8
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:2349 +0x1 fp=0xc42004c7e8 sp=0xc42004c7e0
created by runtime.init.4
	/tmp/workdir/go/src/runtime/proc.go:215 +0x35

goroutine 3 [GC sweep wait]:
runtime.gopark(0x5e9cb0, 0x8f5cc0, 0x5de2c7, 0xd, 0x423914, 0x1)
	/tmp/workdir/go/src/runtime/proc.go:268 +0x12c fp=0xc42004cf60 sp=0xc42004cf30
runtime.goparkunlock(0x8f5cc0, 0x5de2c7, 0xd, 0x14, 0x1)
	/tmp/workdir/go/src/runtime/proc.go:274 +0x5e fp=0xc42004cfa0 sp=0xc42004cf60
runtime.bgsweep(0xc420018070)
	/tmp/workdir/go/src/runtime/mgcsweep.go:52 +0xa3 fp=0xc42004cfd8 sp=0xc42004cfa0
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:2349 +0x1 fp=0xc42004cfe0 sp=0xc42004cfd8
created by runtime.gcenable
	/tmp/workdir/go/src/runtime/mgc.go:216 +0x5d

goroutine 4 [finalizer wait]:
runtime.gopark(0x5e9cb0, 0x955168, 0x5de761, 0xe, 0x14, 0x1)
	/tmp/workdir/go/src/runtime/proc.go:268 +0x12c fp=0xc42004d700 sp=0xc42004d6d0
runtime.goparkunlock(0x955168, 0x5de761, 0xe, 0x14, 0x1)
	/tmp/workdir/go/src/runtime/proc.go:274 +0x5e fp=0xc42004d740 sp=0xc42004d700
runtime.runfinq()
	/tmp/workdir/go/src/runtime/mfinal.go:175 +0x8d fp=0xc42004d7e0 sp=0xc42004d740
created by runtime.createfing
	/tmp/workdir/go/src/runtime/mfinal.go:156 +0x62

goroutine 5 [syscall]:
runtime.notetsleepg(0x955440, 0xffffffffffffffff, 0x0)
	/tmp/workdir/go/src/runtime/lock_futex.go:226 +0x42 fp=0xc42004df80 sp=0xc42004df50
os/signal.signal_recv(0x0)
	/tmp/workdir/go/src/runtime/sigqueue.go:116 +0xad fp=0xc42004dfa8 sp=0xc42004df80
os/signal.loop()
	/tmp/workdir/go/src/os/signal/signal_unix.go:22 +0x22 fp=0xc42004dfe0 sp=0xc42004dfa8
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:2349 +0x1 fp=0xc42004dfe8 sp=0xc42004dfe0
created by os/signal.init.0
	/tmp/workdir/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 18 [select]:
runtime.gopark(0x5e9ce8, 0x0, 0x5dc76d, 0x6, 0x18, 0x1)
	/tmp/workdir/go/src/runtime/proc.go:268 +0x12c fp=0xc42005abf0 sp=0xc42005abc0
runtime.selectgo(0xc42005aea0, 0xc4200ba2a0)
	/tmp/workdir/go/src/runtime/select.go:395 +0xc76 fp=0xc42005ae70 sp=0xc42005abf0
_/tmp/workdir/go/misc/cgo/test.runTestSetgid(0xf5bab)
	/tmp/workdir/go/misc/cgo/test/setgid_linux.go:30 +0x128 fp=0xc42005af30 sp=0xc42005ae70
_/tmp/workdir/go/misc/cgo/test.testSetgid(0xc4200bc0f0)
	/tmp/workdir/go/misc/cgo/test/setgid_linux.go:40 +0x26 fp=0xc42005af90 sp=0xc42005af30
_/tmp/workdir/go/misc/cgo/test.TestSetgid(0xc4200bc0f0)
	/tmp/workdir/go/misc/cgo/test/cgo_linux_test.go:9 +0x2b fp=0xc42005afa8 sp=0xc42005af90
testing.tRunner(0xc4200bc0f0, 0x5e6e48)
	/tmp/workdir/go/src/testing/testing.go:746 +0xd0 fp=0xc42005afd0 sp=0xc42005afa8
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:2349 +0x1 fp=0xc42005afd8 sp=0xc42005afd0
created by testing.(*T).Run
	/tmp/workdir/go/src/testing/testing.go:788 +0x2de

goroutine 20 [syscall]:
runtime.notetsleepg(0x8f5d78, 0x12a05da40, 0x0)
	/tmp/workdir/go/src/runtime/lock_futex.go:226 +0x42 fp=0xc420048f60 sp=0xc420048f30
runtime.timerproc()
	/tmp/workdir/go/src/runtime/time.go:214 +0x325 fp=0xc420048fe0 sp=0xc420048f60
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:2349 +0x1 fp=0xc420048fe8 sp=0xc420048fe0
created by runtime.addtimerLocked
	/tmp/workdir/go/src/runtime/time.go:121 +0xed
exit status 2
FAIL	_/tmp/workdir/go/misc/cgo/test	0.023s
2017/04/25 20:17:22 Failed: exit status 1
PASS
ok  	_/tmp/workdir/go/misc/cgo/testtls	0.013s
skipped due to earlier error
skipped due to earlier error
skipped due to earlier error
skipped due to earlier error
skipped due to earlier error
skipped due to earlier error
skipped due to earlier error
skipped due to earlier error
2017/04/25 20:17:22 FAILED
```

**Comment by ianlancetaylor** [comment]
I think that anything that uses cgo with -linkmode=internal will currently fail on Alpine.  It's a little hard to tell whether that is what is happening here, but I don't see anything that prevents the `-linkmode=internal` case in `tester.cgoTest` in cmd/dist/test.go on Alpine.

**Comment by bradfitz** [comment]
Ah, I see. Dup of #18243 then. Sent https://golang.org/cl/41759
