### ISSUE TITLE
cmd/compile: internal compiler error: width not calculated: func(interface {}) ([]byte, error)

### ISSUE THREAD

**Issue by dcheney-atlassian** [golang/go#20152]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version devel +fc08a19 Thu Apr 27 22:58:13 2017 +0000 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

linux/amd64

### What did you do?

building https://github.com/davecheney/benchjuju
```
for i in $(seq 1 10); do
        /usr/bin/time -f '%e' ${GO} build -gcflags=-c=${i} -o /tmp/jujud github.com/juju/juju/cmd/jujud \
                && ls -al /tmp/jujud \
                && rm /tmp/jujud
done
```
### What did you expect to see?

successful compilation

### What did you see instead?
```
# github.com/juju/juju/resource/cmd
src/github.com/juju/juju/resource/cmd/list_charm_resources.go:80:16: internal compiler error: width not calculated: func(interface {}) ([]byte, error)

goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        /home/dfc/go/src/runtime/debug/stack.go:24 +0xa7
cmd/compile/internal/gc.Fatalf(0xba0aa5, 0x18, 0xc4211ce5f0, 0x1, 0x1)
        /home/dfc/go/src/cmd/compile/internal/gc/subr.go:181 +0x230
cmd/compile/internal/types.(*Type).AssertWidthCalculated(0xc4206a7da0)
        /home/dfc/go/src/cmd/compile/internal/types/type.go:855 +0xa7
cmd/compile/internal/types.(*Type).MustAlignment(0xc4206a7da0, 0x8)
        /home/dfc/go/src/cmd/compile/internal/types/type.go:888 +0x2b
cmd/compile/internal/ssa.round(...)
        /home/dfc/go/src/cmd/compile/internal/ssa/writebarrier.go:294
cmd/compile/internal/ssa.wbcall(0x530300000204, 0xc420eaabc0, 0xc420e47ab0, 0x0, 0x0, 0xc420e71b30, 0xc420e717e8, 0xc420e71338, 0xc420e700f0, 0xc420e70168, ...)
        /home/dfc/go/src/cmd/compile/internal/ssa/writebarrier.go:294 +0x40c
cmd/compile/internal/ssa.writebarrier(0xc421165540)
        /home/dfc/go/src/cmd/compile/internal/ssa/writebarrier.go:197 +0x118a
cmd/compile/internal/ssa.Compile(0xc421165540)
        /home/dfc/go/src/cmd/compile/internal/ssa/compile.go:70 +0x2ea
cmd/compile/internal/gc.buildssa(0xc420d02280, 0x0, 0x0)
        /home/dfc/go/src/cmd/compile/internal/gc/ssa.go:212 +0x8ac
cmd/compile/internal/gc.compileSSA(0xc420d02280, 0x0)
        /home/dfc/go/src/cmd/compile/internal/gc/pgen.go:237 +0x3c
cmd/compile/internal/gc.compile(0xc420d02280)
        /home/dfc/go/src/cmd/compile/internal/gc/pgen.go:218 +0x203
cmd/compile/internal/gc.funccompile(0xc420d02280)
        /home/dfc/go/src/cmd/compile/internal/gc/dcl.go:1049 +0xb7
cmd/compile/internal/gc.Main(0xbb0cc0)
        /home/dfc/go/src/cmd/compile/internal/gc/main.go:570 +0x26cf
main.main()
        /home/dfc/go/src/cmd/compile/main.go:49 +0x95
```

**Comment by josharian** [comment]
Thanks! On it.
