### ISSUE TITLE
build: plan9-386 flake during init (memory corruption?)

### ISSUE THREAD

**Issue by josharian** [golang/go#20300]
Single flake, at CL 42953 (probably unrelated): https://build.golang.org/log/59df2c18e77de00732b9d1790bf9e86d2e7b310f.

```
# vendor/golang_org/x/net/idna
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0x3 code=0x0 addr=0x0 pc=0x79fd]

goroutine 1 [running]:
panic(0x459440, 0x107ce030)
	/tmp/workdir/go/src/runtime/panic.go:500 +0x32f
bootstrap/cmd/compile/internal/gc.init.2.func3(0x496ea1, 0xb, 0x4957ba, 0xb, 0x4a6aca, 0x17, 0x48968a, 0x5, 0x107ec480, 0xc, ...)
	/tmp/workdir/go/src/cmd/compile/internal/gc/ssa.go:2548 +0x122
bootstrap/cmd/compile/internal/gc.init.2()
	/tmp/workdir/go/src/cmd/compile/internal/gc/ssa.go:2896 +0x2223
bootstrap/cmd/compile/internal/gc.init()
	/tmp/workdir/go/src/cmd/compile/internal/gc/walk.go:3830 +0x63a5
bootstrap/cmd/compile/internal/amd64.init()
	/tmp/workdir/go/src/cmd/compile/internal/amd64/ssa.go:1020 +0x4c
main.init()
	/tmp/workdir/go/src/cmd/compile/main.go:52 +0x47
```

This panic really shouldn't be possible.

This is before concurrent compilation was turned on.

**Comment by bcmills** [comment]
This issue is very old; any current failures will be reported by `watchflakes` as new issues.
