### ISSUE TITLE
cmd/cgo: TestCgoFlagContainsSpace test failures

### ISSUE THREAD

**Issue by ALTree** [golang/go#20324]
Commit 1df777f6a425d9e61f8094cfb1d96fd90bb0bdf1 broke `all.bash` on my debian system (and on the `linux-386-sid` and `linux-amd64-sid` [builders](https://build.golang.org/#)).

`TestCgoFlagContainsSpace` fails with:

```
--- FAIL: TestCgoFlagContainsSpace (0.41s)
	go_test.go:310: running testgo [build]
	go_test.go:310: running testgo [run /tmp/gotest310476999/src/cgo/cgo.go]
	go_test.go:323: standard error:
	go_test.go:324: # command-line-arguments
		panic: exit status 1
		
		goroutine 1 [running]:
		main.main()
			/tmp/gotest310476999/src/cc/main.go:32 +0x181
		
	go_test.go:333: go [run /tmp/gotest310476999/src/cgo/cgo.go] failed unexpectedly: exit status 2
```

[CL 43155](https://go-review.googlesource.com/c/43155/) does not help, it still fails with this:

```
--- FAIL: TestCgoFlagContainsSpace (0.46s)
	go_test.go:301: running testgo [env CC]
	go_test.go:310: standard output:
	go_test.go:311: gcc
		
	go_test.go:301: running testgo [env GOGCCFLAGS]
	go_test.go:310: standard output:
	go_test.go:311: -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build221354564=/tmp/go-build -gno-record-gcc-switches
		
	go_test.go:4103: package main
				import (
					"os"
					"os/exec"
				)
		
				func main() {
					var success bool
					for _, arg := range os.Args {
						switch arg {
						case "-Ic flags":
							if success {
								panic("duplicate CFLAGS")
							}
							success = true
						case "-Lld flags":
							if success {
								panic("duplicate LDFLAGS")
							}
							success = true
						}
					}
					if !success {
						panic("args should contains '-Ic flags' or '-Lld flags'")
					}
					cc := []string{"gcc"}
					cc = append(cc, []string{"-fPIC", "-m64", "-pthread", "-fmessage-length=0", "-fdebug-prefix-map=/tmp/go-build221354564=/tmp/go-build", "-gno-record-gcc-switches"}...)
					cc = append(cc, os.Args[1:]...)
					cmd := exec.Command(cc[0], cc[1:]...)
					cmd.Stdin = os.Stdin
					cmd.Stdout = os.Stdout
					err := cmd.Run()
					if err != nil {
						panic(err)
					}
				}
			
	go_test.go:301: running testgo [build]
	go_test.go:301: running testgo [run /tmp/gotest620440761/src/cgo/cgo.go]
	go_test.go:314: standard error:
	go_test.go:315: # command-line-arguments
		panic: exit status 1
		
		goroutine 1 [running]:
		main.main()
			/tmp/gotest620440761/src/cc/main.go:35 +0x326
		
	go_test.go:324: go [run /tmp/gotest620440761/src/cgo/cgo.go] failed unexpectedly: exit status 2
```

```
$ uname -srvm
Linux 4.9.0-2-amd64 #1 SMP Debian 4.9.18-1 (2017-03-30) x86_64
```

```
$ gotip env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/adonizetti/gocode"
GORACE=""
GOROOT="/home/adonizetti/go"
GOTOOLDIR="/home/adonizetti/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build126439993=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

**Comment by hirochachacha** [comment]
Unfortunately, I could not reproduce it on my env. (I don't know the meaning of 'sid')
Could you try a following patch?
```
diff --git a/src/cmd/go/go_test.go b/src/cmd/go/go_test.go
index 131a0985ae..f5cf62a770 100644
--- a/src/cmd/go/go_test.go
+++ b/src/cmd/go/go_test.go
@@ -4055,7 +4055,7 @@ func TestCgoFlagContainsSpace(t *testing.T) {
 	tg := testgo(t)
 	defer tg.cleanup()
 
-	tg.tempFile("src/cc/main.go", fmt.Sprintf(`package main
+	tg.tempFile("src/gcc/main.go", fmt.Sprintf(`package main
 		import (
 			"os"
 			"os/exec"
@@ -4083,15 +4083,16 @@ func TestCgoFlagContainsSpace(t *testing.T) {
 			cmd := exec.Command(%q, os.Args[1:]...)
 			cmd.Stdin = os.Stdin
 			cmd.Stdout = os.Stdout
+			cmd.Stderr = os.Stderr
 			err := cmd.Run()
 			if err != nil {
 				panic(err)
 			}
 		}
 	`, testCC))
-	tg.cd(tg.path("src/cc"))
+	tg.cd(tg.path("src/gcc"))
 	tg.run("build")
-	tg.setenv("CC", tg.path("src/cc/cc"))
+	tg.setenv("CC", tg.path("src/gcc/gcc"))
 	tg.tempFile("src/cgo/cgo.go", `package main
 		// #cgo CFLAGS: -I"c flags"
 		// #cgo LDFLAGS: -L"ld flags"

```

Thanks.

**Comment by ALTree** [comment]
`sid` is Debian Unstable: https://www.debian.org/releases/sid/

After your patch the test prints

```
--- FAIL: TestCgoFlagContainsSpace (0.38s)
	go_test.go:310: running testgo [build]
	go_test.go:310: running testgo [run /tmp/gotest074733030/src/cgo/cgo.go]
	go_test.go:323: standard error:
	go_test.go:324: # command-line-arguments
		/usr/bin/ld: -r and -pie may not be used together
		collect2: error: ld returned 1 exit status
		panic: exit status 1
		
		goroutine 1 [running]:
		main.main()
			/tmp/gotest074733030/src/gcc/main.go:33 +0x1a2
		
	go_test.go:333: go [run /tmp/gotest074733030/src/cgo/cgo.go] failed unexpectedly: exit status 2
```

This may be related to the debian transition to `pie-by-default`, see https://wiki.debian.org/Hardening/PIEByDefaultTransition

**Comment by ALTree** [comment]
Did you edit your message? The patch I applied looks different from the one there's now in the message.

**Comment by hirochachacha** [comment]
Oh, yes. I've edited it one hours ago.

**Comment by ALTree** [comment]
The new version of the test in the patch above fixes the issue (at least on my machine).

**Comment by hirochachacha** [comment]
Thanks! I sent the CL. https://go-review.googlesource.com/c/43330/
