### ISSUE TITLE
cmd/asm: NOP function crashes asm when building for arm64

### ISSUE THREAD

**Issue by stapelberg** [golang/go#20348]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version devel +380aa884b8 Fri May 12 18:08:12 2017 +0000 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="arm64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/michael/go"
GORACE=""
GOROOT="/tmp/upstream-go"
GOTOOLDIR="/tmp/upstream-go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build622527587=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="0"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?

```
$ head -50 repro.go repro_arm64.s 
==> repro.go <==
package main

func stub()

func main() {
        stub()
}

==> repro_arm64.s <==
TEXT ·stub(SB),$0-0
        NOP
```

I ran `GOARCH=arm64 go build` on an `amd64` host machine.

### What did you expect to see?

I *think* the definition of ·stub is invalid, as it’s missing a `RET` instruction. Still, the assembler shouldn’t crash, should it?

### What did you see instead?

```
$ GOARCH=arm64 /tmp/upstream-go/bin/go build         
# asm-crash-repro
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xaa pc=0x4f7760]

goroutine 1 [running]:
cmd/internal/obj/arm64.preprocess(0xc42007a100, 0xc4200a6000, 0xc42004e380)
        /tmp/upstream-go/src/cmd/internal/obj/arm64/obj7.go:469 +0x210
cmd/internal/obj.Flushplist(0xc42007a100, 0xc420045e50, 0xc42004e380)
        /tmp/upstream-go/src/cmd/internal/obj/plist.go:106 +0x692
main.main()
        /tmp/upstream-go/src/cmd/asm/main.go:75 +0x5d1
```

This issue is reproducible with go1.8.1.

**Comment by andybons** [comment]
@ianlancetaylor @josharian
