### ISSUE TITLE
plugin: Getting panic when opening plugins that imports "gopacket" and "net"

### ISSUE THREAD

**Issue by Bigomby** [golang/go#20451]
## Details

**go version**

```
go version go1.8.1 linux/amd64
```

**go env**

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/diego/Documentos"
GORACE=""
GOROOT="/home/diego/.gvm/gos/go1.8.1"
GOTOOLDIR="/home/diego/.gvm/gos/go1.8.1/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build314688111=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

## Description

If a plugin imports the "gopacket" package and another plugin imports the "net" package, the app will panic when opening both plugins.

The panic seems to occur only with these packages and only if opened in that specific order ("gopacket", then "net").

The panic occurs at the second `plugin.Open()` :

```
panic: interface conversion: *net.IPAddr is not net.sockaddr: missing method sockaddr

goroutine 1 [running]:
plugin.lastmoduleinit(0x7f6f70000a90, 0xc42000e030, 0x7f6f70001af0, 0x45, 0x7b5f40)
	/home/diego/.gvm/gos/go1.8.1/src/runtime/plugin.go:60 +0x5e6
plugin.open(0x53154f, 0xa, 0x0, 0x0, 0x0)
	/home/diego/.gvm/gos/go1.8.1/src/plugin/plugin_dlopen.go:72 +0x25d
plugin.Open(0x53154f, 0xa, 0xc42000c460, 0x0, 0x0)
	/home/diego/.gvm/gos/go1.8.1/src/plugin/plugin.go:30 +0x35
main.main()
	/home/diego/Documentos/src/github.com/Bigomby/testsock/cmd/main.go:14 +0xa4
```

### Plugin 1

```go
package main

import (
	"time"

	"github.com/google/gopacket/pcap"
)

func main() {}

func Plugin1() {
	pcap.OpenLive("lo", 1024, false, 1*time.Second)
}
```

### Plugin 2

```go
package main

import "net"

func main() {}

func Plugin2() {
	net.Dial("ip:udp", "0.0.0.0")
}

```

### Main

```go
package main

import "plugin"

func main() {
	plugin.Open("plugin1.so")
	plugin.Open("plugin2.so")
}
```

**Comment by Bigomby** [comment]
The problem seems to happend with the "net" plugin, not the "gopacket" plugin. The following code also make the app crash:

```go
package main

import (
  "plugin"
  "github.com/rcrowley/go-metrics"
)

func main() {
  metrics.NewCounter()
  plugin.Open("plugin2.so") // The "net" plugin
}
```

**Comment by jszroberto** [comment]
seeing this issue too

**Comment by crawshaw** [comment]
I believe this is fixed at HEAD. Tested here on darwin/amd64.

Please let me know if you still see it at HEAD.
