### ISSUE TITLE
cmd/compile: binary exporter debug flag is broken

### ISSUE THREAD

**Issue by ALTree** [golang/go#20684]
```
$ gotip version
go version devel +e7c650bca5 Thu Jun 15 05:57:29 2017 +0000 linux/amd64
```

There's a debug flag in `bexport.go`

```
// NOTE: This flag is the first flag to enable if importing dies because of
// (suspected) format errors, and whenever a change is made to the format.
const debugFormat = false // default: false
```

but it seems to be broken. Setting it to `true` and then running `make.bash` gives:

```
[...]

##### Building go_bootstrap for host, linux/amd64.
runtime/internal/sys
<autogenerated>:1:0: internal compiler error: incorrect marker: got t; want p (pos = 32)

goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/home/adonizetti/go/src/runtime/debug/stack.go:24 +0x79
bootstrap/cmd/compile/internal/gc.Fatalf(0x9625be, 0x2c, 0xc4203890c8, 0x3, 0x3)
	/home/adonizetti/go/src/cmd/compile/internal/gc/subr.go:181 +0x24c
bootstrap/cmd/compile/internal/gc.(*importer).formatErrorf(0xc42032fa00, 0x9625be, 0x2c, 0xc4203890c8, 0x3, 0x3)
	/home/adonizetti/go/src/cmd/compile/internal/gc/bimport.go:237 +0x66
bootstrap/cmd/compile/internal/gc.(*importer).marker(0xc42032fa00, 0xc420389170)
	/home/adonizetti/go/src/cmd/compile/internal/gc/bimport.go:1313 +0x26d
bootstrap/cmd/compile/internal/gc.(*importer).path(0xc42032fa00, 0xc42040e760, 0x3)
	/home/adonizetti/go/src/cmd/compile/internal/gc/bimport.go:424 +0x2ca
bootstrap/cmd/compile/internal/gc.(*importer).pkg(0xc42032fa00, 0xc420364f00)
	/home/adonizetti/go/src/cmd/compile/internal/gc/bimport.go:277 +0xd3
bootstrap/cmd/compile/internal/gc.Import(0xc420316aa0, 0xc42038d860)
	/home/adonizetti/go/src/cmd/compile/internal/gc/bimport.go:118 +0x396
bootstrap/cmd/compile/internal/gc.dumpexport.func1()
	/home/adonizetti/go/src/cmd/compile/internal/gc/export.go:177 +0x8e
bootstrap/cmd/compile/internal/types.CleanroomDo(0xc420389788)
	/home/adonizetti/go/src/cmd/compile/internal/types/pkg.go:133 +0x78
bootstrap/cmd/compile/internal/gc.dumpexport()
	/home/adonizetti/go/src/cmd/compile/internal/gc/export.go:178 +0x2b4
bootstrap/cmd/compile/internal/gc.dumpobj1(0x7ffca663a1f5, 0x37, 0x3)
	/home/adonizetti/go/src/cmd/compile/internal/gc/obj.go:95 +0x81b
bootstrap/cmd/compile/internal/gc.dumpobj()
	/home/adonizetti/go/src/cmd/compile/internal/gc/obj.go:51 +0x61
bootstrap/cmd/compile/internal/gc.Main(0x968fc0)
	/home/adonizetti/go/src/cmd/compile/internal/gc/main.go:631 +0x2003
main.main()
	/home/adonizetti/go/src/cmd/compile/main.go:49 +0x9a
```

**Comment by ALTree** [comment]
cc @griesemer

**Comment by bradfitz** [comment]
I'll conservative flag this Go 1.9 in case it implies a larger problem.

**Comment by griesemer** [comment]
Minor discrepancy in redundant code used for debugging. Does not affect anything else but will fix.
