### ISSUE TITLE
x/tools/cmd/bundle: panic while bundling package math

### ISSUE THREAD

**Issue by josharian** [golang/go#20751]
```
$ cd $GOROOT/src/math
$ bundle -o out.go .
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x11e15f8]

goroutine 1 [running]:
main.bundle(0x7fff5fbff9bc, 0x1, 0xc420012357, 0x4, 0xc420014ca8, 0x4, 0x0, 0x0, 0x126355f, 0x3d, ...)
	/Users/josh/src/golang.org/x/tools/cmd/bundle/main.go:205 +0x1a8
main.main()
	/Users/josh/src/golang.org/x/tools/cmd/bundle/main.go:163 +0x12d
```

Instrumentation says that `info` is nil.

Probably an easy fix, but I'm distracted elsewhere.

golang.org/s/owners doesn't list anyone for this package, so... cc @bradfitz @kevinburke @alandonovan @shurcooL

**Comment by bradfitz** [comment]
bundle is @alandonovan

**Comment by josharian** [comment]
Thanks, Brad. Added to /s/owners.
