### ISSUE TITLE
cmd/compile: internal compiler error: dowidth: unknown type: untyped number

### ISSUE THREAD

**Issue by ALTree** [golang/go#20813]
```
$ gotip version
go version devel +b4dd1d965d Sun Jun 25 15:57:18 2017 +0000 linux/amd64
```

The following program:
```
package p

func f() {
	1 = 2
}
```

crashes the go1.9 compiler on dowidth

```
./test.go:4:4: internal compiler error: dowidth: unknown type: untyped number

goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/home/adonizetti/go/src/runtime/debug/stack.go:24 +0xa7
cmd/compile/internal/gc.Fatalf(0xb616c4, 0x19, 0xc420302760, 0x1, 0x1)
	/home/adonizetti/go/src/cmd/compile/internal/gc/subr.go:181 +0x230
cmd/compile/internal/gc.dowidth(0xc420095da0)
	/home/adonizetti/go/src/cmd/compile/internal/gc/align.go:227 +0x4e6
cmd/compile/internal/gc.checkwidth(0xc420095da0)
	/home/adonizetti/go/src/cmd/compile/internal/gc/align.go:424 +0x17c
cmd/compile/internal/gc.typecheckas(0xc420316a00)
	/home/adonizetti/go/src/cmd/compile/internal/gc/typecheck.go:3374 +0x18b
cmd/compile/internal/gc.typecheck1(0xc420316a00, 0x1, 0x4b3731)
	/home/adonizetti/go/src/cmd/compile/internal/gc/typecheck.go:2047 +0x3b04
cmd/compile/internal/gc.typecheck(0xc420316a00, 0x1, 0x3)
	/home/adonizetti/go/src/cmd/compile/internal/gc/typecheck.go:201 +0x764
cmd/compile/internal/gc.typecheckslice(0xc42007e508, 0x1, 0x1, 0x1)
	/home/adonizetti/go/src/cmd/compile/internal/gc/typecheck.go:55 +0x54
cmd/compile/internal/gc.Main(0xb717b0)
	/home/adonizetti/go/src/cmd/compile/internal/gc/main.go:480 +0x1fd0
main.main()
	/home/adonizetti/go/src/cmd/compile/main.go:49 +0x95
```

This is new: the go1.8 compiler does not crash on this program.

**Comment by ALTree** [comment]
Bisected to 0b6a10ef246ff55085d6ec88f68f5fd96677b141.

**Comment by mvdan** [comment]
cc @josharian
