### ISSUE TITLE
:= assignment in for loop statement throws internal compiler error

### ISSUE THREAD

**Issue by iamsamwood** [golang/go#20840]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

```
package main

import "fmt"

func main() {
	j := 0
	for ; false; j := j + 1 {
		fmt.Printf("%d", j)
	}
}
```

https://play.golang.org/p/IYyO02KX8Y

#### What did you expect to see?

A more descriptive compiler error.

#### What did you see instead?
```
tmp/sandbox205983736/main.go:5: internal compiler error: Value live at entry. It shouldn't be. func main, node j, value v52

goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
cmd/compile/internal/gc.Fatalf(0xacd433, 0x40, 0xc420333200, 0x3, 0x3)
	/usr/local/go/src/cmd/compile/internal/gc/subr.go:167 +0x226
cmd/compile/internal/gc.(*ssaExport).Fatalf(0xdcb195, 0x5, 0xacd433, 0x40, 0xc420333200, 0x3, 0x3)
	/usr/local/go/src/cmd/compile/internal/gc/ssa.go:4979 +0x5d
cmd/compile/internal/ssa.(*Config).Fatalf(0xc42034a000, 0xc400000005, 0xacd433, 0x40, 0xc420333200, 0x3, 0x3)
	/usr/local/go/src/cmd/compile/internal/ssa/config.go:343 +0x6e
cmd/compile/internal/gc.(*state).Fatalf(0xc42031c1e0, 0xacd433, 0x40, 0xc420333200, 0x3, 0x3)
	/usr/local/go/src/cmd/compile/internal/gc/ssa.go:286 +0x83
cmd/compile/internal/gc.(*simplePhiState).insertPhis(0xc4203454b0)
	/usr/local/go/src/cmd/compile/internal/gc/phi.go:458 +0x2c5
cmd/compile/internal/gc.(*state).insertPhis(0xc42031c1e0)
	/usr/local/go/src/cmd/compile/internal/gc/phi.go:33 +0x172
cmd/compile/internal/gc.buildssa(0xc42032fa70, 0x0)
	/usr/local/go/src/cmd/compile/internal/gc/ssa.go:174 +0x8ee
cmd/compile/internal/gc.compile(0xc42032fa70)
	/usr/local/go/src/cmd/compile/internal/gc/pgen.go:362 +0x204
cmd/compile/internal/gc.funccompile(0xc42032fa70)
	/usr/local/go/src/cmd/compile/internal/gc/dcl.go:1292 +0xdc
cmd/compile/internal/gc.Main()
	/usr/local/go/src/cmd/compile/internal/gc/main.go:464 +0x1f08
main.main()
	/usr/local/go/src/cmd/compile/main.go:50 +0xfe
```

#### System details

```
go version go1.8.3 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/swood/work"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.8.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.8.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/50/cx00dntd6t7b6l2n8482fyc40000gn/T/go-build619286091=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
GOROOT/bin/go version: go version go1.8.3 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.8.3 X:framepointer
uname -v: Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.12.5
BuildVersion:	16F73
lldb --version: lldb-360.1.70
```

**Comment by bradfitz** [comment]
This is fixed in Go 1.9. (tested with Go tip, a bit after Go 1.9beta2).
