### ISSUE TITLE
tools/cmd/go-contrib-init: panic if not in directory

### ISSUE THREAD

**Issue by smcquay** [golang/go#21021]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version                                                                                       
go version devel +eab99a8d54 Mon Jun 26 21:12:22 2017 +0000 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/sm/go"
GORACE=""
GOROOT="/Users/sm/src/go"
GOTOOLDIR="/Users/sm/src/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/l6/16ml7k9d3j728cv1qnrwsp280000gn/T/go-build974224850=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?

Following along with the [gophercon workshop](https://golang.org/s/gophercon2017) I ran `go-contrib-init -repo scratch` outside the `scratch` directory and the command panicked. The command worked if I cd'd into the `scratch` directory.

### What did you expect to see?

```bash
go-contrib-init -repo scratch                                                                    
All good. Happy hacking!
Remember to squash your revised commits and preserve the magic Change-Id lines.
Next steps: https://golang.org/doc/contribute.html#commit_changes

```

### What did you see instead?

```bash
go-contrib-init -repo scratch                                                             rc: 2  
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.detectrepo(0x60, 0x0)
        /Users/sm/src/golang.org/x/tools/cmd/go-contrib-init/contrib.go:54 +0x253
main.init()
        /Users/sm/src/golang.org/x/tools/cmd/go-contrib-init/contrib.go:27 +0x87

```

**Comment by smcquay** [comment]
I seem to have had an older version of this tool.
