### ISSUE TITLE
x/mobile:  gobind.exe finished with non-zero exit value 1

### ISSUE THREAD

**Issue by FengMingJian** [golang/go#21319]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

C:\Users\fengm>go version
go version go1.8.3 windows/amd64

C:\Users\fengm>java -version
java version "1.8.0_141"
Java(TM) SE Runtime Environment (build 1.8.0_141-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.141-b15, mixed mode)

### What operating system and processor architecture are you using (`go env`)?

C:\Users\fengm>go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\fengm\go\bin
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2

### What did you do?
This is my steps：
1.Install Go,Git,Java,Android Studio(With SDK),Android NDK

2.System environment
   (1)ANDROID_NDK_HOME : D:\Windows10\android-ndk-r14b
   (2)GOROOT                       : C:\Go\
   (3)GOPATH                        : C:\Users\fengm\go\bin

3.Exec Command “go get golang.org/x/mobile/cmd/gomobile” [Success]

4.Exec Command "go get golang.org/x/mobile/cmd/..." [Success]

5.Exec Command "gomobile init -v -ndk D:\Windows10\android-ndk-r14b" [Success]

6.Open Android Studio And Create New APP(Add No Activity), Then, Import Module , The Path Is "$GOPATH\src\golang.org\x\mobile\example\reverse\android"

7.Rebuild Project

8.Build Failed

### What did you expect to see?
Build Successfully And The APP Can Run In My Phone

### What did you see instead?

`Executing tasks: [clean, :android:generateDebugSources, :android:mockableAndroidJar, :android:prepareDebugUnitTestDependencies, :android:generateDebugAndroidTestSources, :android:compileDebugSources, :android:compileDebugUnitTestSources, :android:compileDebugAndroidTestSources, :app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies, :app:compileDebugSources, :app:compileDebugAndroidTestSources, :app:compileDebugUnitTestSources]

Configuration on demand is an incubating feature.
Incremental java compilation is an incubating feature.
:clean
:android:clean
:app:clean
:android:preBuild UP-TO-DATE
:android:preDebugBuild UP-TO-DATE
:android:checkDebugManifest
:android:preReleaseBuild UP-TO-DATE
:android:prepareComAndroidDatabindingAdapters131Library
:android:prepareComAndroidDatabindingLibrary131Library
:android:prepareComAndroidSupportAnimatedVectorDrawable2421Library
:android:prepareComAndroidSupportAppcompatV72421Library
:android:prepareComAndroidSupportSupportCompat2421Library
:android:prepareComAndroidSupportSupportCoreUi2421Library
:android:prepareComAndroidSupportSupportCoreUtils2421Library
:android:prepareComAndroidSupportSupportFragment2421Library
:android:prepareComAndroidSupportSupportMediaCompat2421Library
:android:prepareComAndroidSupportSupportV42421Library
:android:prepareComAndroidSupportSupportVectorDrawable2421Library
:android:prepareDebugDependencies
:android:compileDebugAidl
:android:compileDebugRenderscript
:android:generateDebugBuildConfig
:android:gobindDebug
unsupported basic type: invalid type
unsupported basic type: invalid type
unsupported basic type: invalid type
unsupported basic type: invalid type
unsupported basic type: invalid type
unsupported basic type: invalid type
unsupported basic type: invalid type
unsupported basic type: invalid type
unsupported basic type: invalid type
unsupported basic type: invalid type
unsupported basic type: invalid type
unsupported basic type: invalid type
unsupported basic type: invalid type
unsupported basic type: invalid type
unsupported basic type: invalid type
unsupported basic type: invalid type
unsupported basic type: invalid type
unsupported basic type: invalid type
unsupported basic type: invalid type
unsupported basic type: invalid type
unsupported basic type: invalid type
unsupported basic type: invalid type
unsupported basic type: invalid type
unsupported basic type: invalid type
unsupported basic type: invalid type
unsupported basic type: invalid type
unsupported basic type: invalid type

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':android:gobindDebug'.
> Process 'command 'C:/Users/fengm/go/bin\gobind.exe'' finished with non-zero exit value 1

* Try:
Run with --info or --debug option to get more log output.

Caused by: org.gradle.process.internal.ExecException: Process 'command 'C:/Users/fengm/go/bin\gobind.exe'' finished with non-zero exit value 1
	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:369)
	at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:31)
	at org.gradle.api.internal.file.DefaultFileOperations.exec(DefaultFileOperations.java:176)
	at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:951)
	at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:947)
	at org.gradle.api.Project$exec$0.call(Unknown Source)
	at org.golang.mobile.BindTask.run(GobindPlugin.groovy:141)
	at org.golang.mobile.BindTask$run.callCurrent(Unknown Source)
	at org.golang.mobile.GobindTask.gobind(GobindPlugin.groovy:197)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:632)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:615)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
	... 78 more

BUILD FAILED

Total time: 6.94 secs
`

Can tell me which step is wrong, or what step is missing ， thank you very much

**Comment by xiaox0321** [comment]
I have the same problem

**Comment by xiaox0321** [comment]
hi, When I use the go1.9 version, I compiled successfully, I hope you will help

> C:\Users\xiao>go version
> go version go1.9rc2 windows/amd64
> 
> C:\Users\xiao>java -version
> java version "1.8.0_20"
> Java(TM) SE Runtime Environment (build 1.8.0_20-b26)
> Java HotSpot(TM) 64-Bit Server VM (build 25.20-b23, mixed mode)
> 



> <======-------> 51% EXECUTING
> > :gobindDebug
> :gobindDebug
> :processDebugManifest
> :processDebugResources
> :generateDebugSources
> :dataBindingExportBuildInfoDebug
> :incrementalDebugJavaCompilationSafeguard
> :compileDebugJavaWithJavac
> :gomobileDebug
> :compileDebugNdk NO-SOURCE
> :compileDebugSources
> :mergeDebugShaders
> :compileDebugShaders
> :generateDebugAssets
> :mergeDebugAssets
> :transformClassesWithDexForDebug
> 
> Running dex as a separate process.
> 
> To run dex in process, the Gradle daemon needs a larger heap.
> It currently has 1024 MB.
> For faster builds, increase the maximum heap size for the Gradle daemon to at least 1536 MB.
> To do this set org.gradle.jvmargs=-Xmx1536M in the project gradle.properties.
> For more information see https://docs.gradle.org/current/userguide/build_environment.html
> 
> :mergeDebugJniLibFolders
> :transformNative_libsWithMergeJniLibsForDebug
> :processDebugJavaRes NO-SOURCE
> :transformResourcesWithMergeJavaResForDebug
> :validateSigningDebug
> :packageDebug
> :assembleDebug
> 
> BUILD SUCCESSFUL
> 
> Total time: 3 mins 15.797 secs
