### ISSUE TITLE
SIGSERV in go vet, same as #19656

### ISSUE THREAD

**Issue by pavel-si** [golang/go#21446]
Same as #19656, still there. 

### What version of Go are you using (`go version`)?
`go version go1.8.3 darwin/amd64`

### What operating system and processor architecture are you using (`go env`)?
```GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.8.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.8.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/n_/jzd9gw9s3w174wjzxgwcklph0000gn/T/go-build833604199=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?
`go vet` on my entire repo.

### What did you expect to see?
List of lint errors.
As in the original issue, there are multiple main files in one folder. 

### What did you see instead?
```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x1232377]

goroutine 1 [running]:
main.checkLostCancel(0xc4200aa480, 0x13f26a0, 0xc4201eb620)
	/usr/local/Cellar/go/1.8.3/libexec/src/cmd/vet/lostcancel.go:107 +0x767
main.(*File).Visit(0xc4200aa480, 0x13f26a0, 0xc4201eb620, 0x13f1760, 0xc4200aa480)
	/usr/local/Cellar/go/1.8.3/libexec/src/cmd/vet/main.go:500 +0x104
go/ast.Walk(0x13f1760, 0xc4200aa480, 0x13f26a0, 0xc4201eb620)
	/usr/local/Cellar/go/1.8.3/libexec/src/go/ast/walk.go:52 +0x66
go/ast.walkDeclList(0x13f1760, 0xc4200aa480, 0xc4200b5b00, 0xe, 0x10)
	/usr/local/Cellar/go/1.8.3/libexec/src/go/ast/walk.go:38 +0x89
go/ast.Walk(0x13f1760, 0xc4200aa480, 0x13f2660, 0xc4204d8100)
	/usr/local/Cellar/go/1.8.3/libexec/src/go/ast/walk.go:353 +0x2bb4
main.(*File).walkFile(0xc4200aa480, 0x7fff5fbff755, 0x1d, 0xc4204d8100)
	/usr/local/Cellar/go/1.8.3/libexec/src/cmd/vet/main.go:467 +0x120
main.doPackage(0x12d0974, 0x1, 0xc42000e2e0, 0x2, 0x2, 0x0, 0xffffffffffffffff)
	/usr/local/Cellar/go/1.8.3/libexec/src/cmd/vet/main.go:358 +0xbd1
main.main()
	/usr/local/Cellar/go/1.8.3/libexec/src/cmd/vet/main.go:247 +0x382
exit status 2```

**Comment by ianlancetaylor** [comment]
If this is the same as #19656, then it is fixed in the 1.9 release.  You can try 1.9rc2 now, and the final release will be out very soon.
