### ISSUE TITLE
runtime: crash on Plan 9 since CL 46033

### ISSUE THREAD

**Issue by 0intro** [golang/go#22227]
Since the runtime.LockOSThread change in CL [46033](https://golang.org/cl/46033), Go programs are crashing on Plan 9 when running commands with os/exec.

```
fatal error: unexpected signal during runtime execution
[signal sys: trap: fault read code=0x0 addr=0x0 pc=0x5ef]

runtime stack:
runtime.throw(0x36dca9, 0x2a)
	/tmp/workdir/go/src/runtime/panic.go:616 +0x6a
runtime.sigpanic()
	/tmp/workdir/go/src/runtime/os_plan9.go:79 +0x240

goroutine 1 [chan receive]:
syscall.startProcess(0x1087b310, 0x7, 0x1085db60, 0x4, 0x4, 0x107b7290, 0x10, 0x1087bc80, 0x107b7290)
	/tmp/workdir/go/src/syscall/exec_plan9.go:514 +0xac
syscall.StartProcess(0x1087b310, 0x7, 0x1085db60, 0x4, 0x4, 0x107b7290, 0x2, 0x4, 0x0, 0x0)
	/tmp/workdir/go/src/syscall/exec_plan9.go:525 +0x48
os.startProcess(0x1087b310, 0x7, 0x1085db60, 0x4, 0x4, 0x108a1c3c, 0x1084ca00, 0x3d, 0x3d)
	/tmp/workdir/go/src/os/exec_plan9.go:33 +0x191
os.StartProcess(0x1087b310, 0x7, 0x1085db60, 0x4, 0x4, 0x108a1c3c, 0x0, 0x0, 0x41dbde8)
	/tmp/workdir/go/src/os/exec.go:94 +0x48
os/exec.(*Cmd).Start(0x107c0580, 0x1086b201, 0x1076f7a0)
	/tmp/workdir/go/src/os/exec/exec.go:363 +0x3c1
os/exec.(*Cmd).Run(0x107c0580, 0x1076f7a0, 0x1086b858)
	/tmp/workdir/go/src/os/exec/exec.go:286 +0x20
os/exec.(*Cmd).CombinedOutput(0x107c0580, 0x1, 0x1, 0x1086b4a0, 0x3c, 0x3c)
	/tmp/workdir/go/src/os/exec/exec.go:506 +0xed
cmd/go/internal/work.(*Builder).gccSupportsFlag(0x107e2230, 0x10766ea8, 0x1, 0x1, 0x3661a1, 0x18, 0x0)
	/tmp/workdir/go/src/cmd/go/internal/work/build.go:3514 +0x437
cmd/go/internal/work.(*Builder).compilerCmd(0x107e2230, 0x35d3b1, 0x2, 0x35d387, 0x2, 0x35d2b1, 0x1, 0x0, 0x0, 0x302ce0, ...)
	/tmp/workdir/go/src/cmd/go/internal/work/build.go:3454 +0x61b
cmd/go/internal/work.(*Builder).GccCmd(0x107e2230, 0x35d2b1, 0x1, 0x0, 0x0, 0x107c29a0, 0xb, 0x16)
	/tmp/workdir/go/src/cmd/go/internal/work/build.go:3390 +0x64
cmd/go/internal/envcmd.MkEnv(0x1086a000, 0x3b, 0x3b)
	/tmp/workdir/go/src/cmd/go/internal/envcmd/env.go:76 +0x31a
main.main()
	/tmp/workdir/go/src/cmd/go/main.go:122 +0x479

goroutine 5 [syscall]:
os/signal.signal_recv(0x0, 0x0)
	/tmp/workdir/go/src/runtime/sigqueue_plan9.go:109 +0x69
os/signal.loop()
	/tmp/workdir/go/src/os/signal/signal_plan9.go:27 +0x19
created by os/signal.init.0
	/tmp/workdir/go/src/os/signal/signal_plan9.go:22 +0x36

goroutine 13 [runnable, locked to thread]:
syscall.Close(0x7, 0x1085dbe0, 0x5)
	/tmp/workdir/go/src/syscall/zsyscall_plan9_386.go:245 +0x86
syscall.forkExec(0x1087b310, 0x7, 0x1085db60, 0x4, 0x4, 0x107b7290, 0x108159d0, 0x0, 0x0)
	/tmp/workdir/go/src/syscall/exec_plan9.go:434 +0x4c0
syscall.startProcess.func1(0x1087b310, 0x7, 0x1085db60, 0x4, 0x4, 0x107b7290, 0x1084f600)
	/tmp/workdir/go/src/syscall/exec_plan9.go:488 +0x51
created by syscall.startProcess
	/tmp/workdir/go/src/syscall/exec_plan9.go:484 +0x80
2017/10/11 15:05:51 Failed: exit status: 'go 2462: 2'
```

See https://build.golang.org/log/c14eefc1c70d14ad2d0f768ff9f13222fa8d435c

**Comment by 0intro** [comment]
After disabling the use of template thread in [newm](https://github.com/golang/go/blob/926373e/src/runtime/proc.go#L1812), the build passes. However, I get another issue when running the net tests:

```
fatal error: runtime·lock: lock count
fatal error: runtime·unlock: lock count
fatal error: fatal error: systemstack called from unexpected goroutineruntime·lock: lock count
```

This issue seems to disappear once I add a call to runtime.UnlockOSThread in [newAsyncIO](https://github.com/golang/go/blob/3792db5/src/internal/poll/fd_io_plan9.go#L49). Why is it necessary?

Also, why the template thread doesn't work on Plan 9?

@aclements

**Comment by 0intro** [comment]
I propose CL [70231](https://golang.org/cl/70231) and CL [70450](https://golang.org/cl/70450) which should get the Plan 9 builders back to "ok".

**Comment by 0intro** [comment]
The "lock count" panics are related to the change to terminate locked OS threads in CL [46038](https://golang.org/cl/46038) (see [goexit0](https://github.com/golang/go/blob/926373e/src/runtime/proc.go#L2672)).

As I said earlier, this issue can be worked around by calling runtime.UnlockOSThread in [newAsyncIO](https://github.com/golang/go/blob/3792db5/src/internal/poll/fd_io_plan9.go#L49) (see CL [70450](https://golang.org/cl/70450)), so the OS threads are reused instead of being terminated.

I'm not sure why I get "lock count" panics when locked OS threads are terminated.

**Comment by 0intro** [comment]
Any help would be kindly appreciated.

**Comment by ianlancetaylor** [comment]
CC @aclements

**Comment by ianlancetaylor** [comment]
The "lock count" panic means that the lock count of the m is negative.  That clearly shouldn't happen, so the question is why it does happen.  Can you get a stack trace of where it happens?

**Comment by 0intro** [comment]
I couldn't manage to get a proper stack trace. It looks like the stacks are corrupted and it usually ends in a recursive panic.

The output usually looks like:

```
fatal error: runtime·lock: lock count
panic during panic
fatal error: systemstack called from unexpected goroutine

runtime stack:

stack trace unavailable
fatal error: systemstack called from unexpected goroutine
fatal error: runtime·lock: lock count
fatal error: systemstack called from unexpected goroutine
fatal error: systemstack called from unexpected goroutine
[...]
fatal error: systemstack called from unexpected goroutine
fatal error: systemstack called from unexpected goroutine
runtime: newstack called from g=0x1061ee00
	m=0x10620000 m->curg=0x10746fc0 m->g0=0x1061e0e0 m->gsignal=0x1061e000
runtime.recordForPanic(0x1ae92f, 0xd, 0xd)
	/usr/go/src/runtime/print.go:40 +0x1d
runtime.gwrite(0x1ae92f, 0xd, 0xd)
	/usr/go/src/runtime/print.go:89 +0x3c
runtime.printstring(0x1ae92f, 0xd)
	/usr/go/src/runtime/print.go:236 +0x6c
runtime.throw(0x1b7412, 0x2c)
	/usr/go/src/runtime/panic.go:610 +0x1e
runtime.badsystemstack()
	/usr/go/src/runtime/stubs.go:57 +0x2a
runtime.systemstack(0x1bb398)
	/usr/go/src/runtime/asm_386.s:371 +0x2e
runtime.startpanic()
	/usr/go/src/runtime/panic.go:589 +0x11
runtime.throw(0x1b7412, 0x2c)
	/usr/go/src/runtime/panic.go:615 +0x5e
[...]
fatal error: runtime: wrong goroutine in newstack
```

**Comment by 92161898515** [comment]
👍

**Comment by 0intro** [comment]
I've replaced CL [70450](https://golang.org/cl/70450) by CL [71230](https://golang.org/cl/71230) so it makes more clear what is the problem worked around in this change.

I still don't know why termination of OS threads isn't working properly on Plan9. I'm investigating.

**Comment by 0intro** [comment]
To sum it up, there are two issues on Plan 9 caused by the recent runtime changes.

- CL [46033](https://golang.org/cl/46033), which implements "termplate threads", lead to fault read/write panic when running os.StartProcess (worked around in CL [70231](https://golang.org/cl/70231)).
- CL [46037](https://golang.org/cl/46037) and CL [46038](https://golang.org/cl/46038), which implement termination of locked OS thread, lead to `lock count` panic when using runtime.LockOSThread without calling runtime.UnlockOSThread (notably in the net tests) (worked around in CL [71230](https://golang.org/cl/71230)).

**Comment by ianlancetaylor** [comment]
@0intro Do you know what the status of this issue is?  Thanks.

**Comment by 0intro** [comment]
The issue has been worked around with CL [70231](https://golang.org/cl/70231) and CL [71230](https://golang.org/cl/71230). Unfortunately, I've been able to find a better solution yet.

Maybe we can postpone this issue to Go 1.12.

**Comment by bcmills** [comment]
`greplogs --dashboard -md -l -e '(?ms)plan9-.*^fatal error: unexpected signal.*^os\.StartProcess' --since=2021-01-01`

[2021-11-06T19:41:15-61d789d/plan9-386-0intro](https://build.golang.org/log/2d38a4485fd12cb53120a8c73c80d0701beea8de)
[2021-11-05T22:30:17-b07c41d/plan9-386-0intro](https://build.golang.org/log/52246232bddd321227036c4cd057e5867d51ff30)
[2021-11-05T21:28:50-fb8b176/plan9-386-0intro](https://build.golang.org/log/608bdb55ff25feba8d4d2da755c155bce204f12c)
[2021-11-03T21:45:33-2c98350-d3f5dd5/plan9-arm](https://build.golang.org/log/6a135ae85859a490993c52e0c25c65bd6a6d734e)
[2021-10-15T21:46:06-ed1c8db/plan9-386-0intro](https://build.golang.org/log/b6d58c6835c9dae0d8e787a1b0faac9375d52823)
[2021-10-11T17:02:03-089bfa5-577bb7d/plan9-arm](https://build.golang.org/log/21d6682c002a5428df09854d5b42a5ba51938487)
[2021-10-08T19:19:09-b9e1e1b/plan9-386-0intro](https://build.golang.org/log/5adb190fcfc394ef3d59f5c4d8d7e9d031e1c6be)
[2021-08-21T08:58:07-dcee007/plan9-arm](https://build.golang.org/log/587793f5c447ebbc0c69e704a4e0bbd547252930)
[2021-07-18T21:03:43-a66190e/plan9-arm](https://build.golang.org/log/34b11964928c64228e0447e7876054b896809187)
[2021-05-08T05:15:48-9d0819b/plan9-386-0intro](https://build.golang.org/log/c9e567c5b91fb3edf252f2977c5fba5f310ac97e)
[2021-04-26T18:54:39-0d1280c/plan9-arm](https://build.golang.org/log/36eeecb2a80704114f97a6221c0643e3c4a754ab)
[2021-04-02T01:13:58-41e8a9f/plan9-arm](https://build.golang.org/log/4e4da93799c03d0366052786f848513d6ccf0956)
[2021-02-24T20:23:56-6c3f8a2/plan9-arm](https://build.golang.org/log/153ab42c61d1f7e6cf5e50242e4abec766e53729)

**Comment by bcmills** [comment]
https://github.com/golang/go/issues/22227#issuecomment-336138495 mentions `runtime.newm`, which is also implicated in frequent crashes on `plan9-386` in particular:

`greplogs --dashboard -md -l -e '(?ms)plan9-.*^fatal error: unexpected signal.*^runtime\.newm1' --since=2021-01-01`

[2021-11-18T22:40:42-2375b6e/plan9-386-0intro](https://build.golang.org/log/abadaffc37f40e01fc77cf4c18d7a8cbe7598053)
[2021-06-01T13:23:26-2e59cc5/plan9-386-0intro](https://build.golang.org/log/cc5c889d4bcef2a5779e1444ad7ed7eb616b7772)
[2021-05-30T17:47:50-3b770f2/plan9-386-0intro](https://build.golang.org/log/cdb7ff7a7554deb25458be9c2eb77bf334adbf13)
[2021-05-28T18:41:07-1419ca7/plan9-386-0intro](https://build.golang.org/log/e7a8365cce8fa1f9b2425391713180e92f8bfda9)
[2021-05-26T22:43:54-1d5298d/plan9-386-0intro](https://build.golang.org/log/814ebf42420deeb54018b12a0c42ebc29a9d9b4c)
[2021-05-26T22:41:55-0fbecec/plan9-386-0intro](https://build.golang.org/log/ae7a9ca97fdeb96f677b4477d4359b0df5330876)
[2021-04-09T18:19:42-952187a/plan9-386-0intro](https://build.golang.org/log/b3b64c73e32e6c5ae9c4a4bc4bbcb393754fa0b9)
[2021-02-11T17:55:50-26ceae8/plan9-386-0intro](https://build.golang.org/log/e8ce9db086c27a25f4d7f4b8c6a47fbf6518d868)
[2021-01-29T19:48:48-4436114/plan9-386-0intro](https://build.golang.org/log/5ef923fb43abb1b89828bc60e9268397002f0831)
[2021-01-25T22:54:28-e6b6d10/plan9-386-0intro](https://build.golang.org/log/8f6a570acad3d0eb3799e16b16d57308e5197a10)
