### ISSUE TITLE
all: Go 1.8.5 release status

### ISSUE THREAD

**Issue by rsc** [golang/go#22264]
# Go 1.8.5 release status

## PROBLEMS WITH RELEASE

  - go1.8.5 tag already exists in Go repository!

## Issues with fixes

  - #20226 cmd/internal/obj/x86: backport "cmd/internal/obj/x86: use LEAx rather than ADDx" to 1\.8 branch
    - [CL 70871](https://golang.org/cl/70871) per rsc; 
  - #20530 cmd/compile: corrupted value
    - [CL 37154](https://golang.org/cl/37154) per rsc; 
    - [CL 44430](https://golang.org/cl/44430) per rsc; 
    - [CL 70841](https://golang.org/cl/70841) per rsc; 
  - #20591 doc: go1\.8\.txt
    - [CL 45015](https://golang.org/cl/45015) per rsc; 
  - #20670 cmd/link: request backport for ppc64le linker fix to go 1\.8
    - [CL 70837](https://golang.org/cl/70837) per rsc; 
  - #21520 runtime: usleep\(\) does not work on Linux 386 \[Go 1\.8\]
    - [CL 56850](https://golang.org/cl/56850) per rsc; 
  - #22261 crypto/x509: intermediates with unknown critical extensions not rejected \[Go1\.8\]
    - [CL 70842](https://golang.org/cl/70842) per rsc; 
  - #22271 net/smtp: let NewClient detect TLS connections \[Go1\.8\]
    - [CL 68470](https://golang.org/cl/68470) per rsc; 
  - #22272 cmd/go: non\-Git repository failures \[Go1\.8\]
    - [CL 69670](https://golang.org/cl/69670) per rsc; 
  - #22273 cmd/go: fix TestImportMain not to write to current directory \[Go 1\.8\]
    - [CL 71410](https://golang.org/cl/71410) per rsc; 
  - #22276 net: windows tests fail due to changes to getmac \[Go 1\.8\]
    - [CL 41395](https://golang.org/cl/41395) per rsc; 
  - #22279 net: tests using timer fail on macOS High Sierra 10\.13 / iOS 11 \[Go 1\.8\]
    - [CL 66491](https://golang.org/cl/66491) per rsc; 
    - [CL 67350](https://golang.org/cl/67350) per rsc; 
  - #22364 net/http: TestLinuxSendfile hanging on linux\-arm64 releaselet
    - [CL 38633](https://golang.org/cl/38633) per rsc; 
  - #22433 doc: document Go 1\.8\.5
    - [CL 73392](https://golang.org/cl/73392) per rsc; 

## Changes on release branch

  - **CL missing** for cherry-pick of [CL 37154](https://golang.org/cl/37154) (for #20530)
  - **CL missing** for cherry-pick of [CL 38633](https://golang.org/cl/38633) (for #22364)
  - **CL missing** for cherry-pick of [CL 41395](https://golang.org/cl/41395) (for #22276)
  - **CL missing** for cherry-pick of [CL 44430](https://golang.org/cl/44430) (for #20530)
  - **CL missing** for cherry-pick of [CL 45015](https://golang.org/cl/45015) (for #20591)
  - **CL missing** for cherry-pick of [CL 56850](https://golang.org/cl/56850) (for #21520)
  - **CL missing** for cherry-pick of [CL 66491](https://golang.org/cl/66491) (for #22279)
  - **CL missing** for cherry-pick of [CL 67350](https://golang.org/cl/67350) (for #22279)
  - **CL missing** for cherry-pick of [CL 68470](https://golang.org/cl/68470) (for #22271)
  - **CL missing** for cherry-pick of [CL 69670](https://golang.org/cl/69670) (for #22272)
  - **CL missing** for cherry-pick of [CL 70837](https://golang.org/cl/70837) (for #20670)
  - **CL missing** for cherry-pick of [CL 70841](https://golang.org/cl/70841) (for #20530)
  - **CL missing** for cherry-pick of [CL 70842](https://golang.org/cl/70842) (for #22261)
  - **CL missing** for cherry-pick of [CL 70871](https://golang.org/cl/70871) (for #20226)
  - **CL missing** for cherry-pick of [CL 71410](https://golang.org/cl/71410) (for #22273)
  - **CL missing** for cherry-pick of [CL 73392](https://golang.org/cl/73392) (for #22433)

## Log

    2017/10/26 17:06:10 starting
    2017/10/26 17:06:11 working in /Users/rsc/go-releasebot-work/go1.8.5
    2017/10/26 17:06:11 $ git fetch origin master
    2017/10/26 17:06:14 $ git fetch origin release-branch.go1.8
    2017/10/26 17:06:18 $ git clone --reference /Users/rsc/go-releasebot-work/go1.8.5/gitmirror -b release-branch.go1.8 https://go.googlesource.com/go /Users/rsc/go-releasebot-work/go1.8.5/gitwork
    2017/10/26 17:06:27 $ git change relwork
    2017/10/26 17:06:27 $ git config gc.auto 0
    2017/10/26 17:06:27 $ git rev-parse go1.8.5
    2017/10/26 17:06:27 already released
    2017/10/26 17:06:27 
    
    PANIC: already released
    
    goroutine 71 [running]:
    runtime/debug.Stack(0xc420ca9908, 0x151eaa0, 0xc420ba61e0)
    	/Users/rsc/go1.9/src/runtime/debug/stack.go:24 +0xa7
    main.(*Work).recover(0xc420b92240)
    	/Users/rsc/src/golang.org/x/build/cmd/releasebot/main.go:194 +0x71
    panic(0x151eaa0, 0xc420ba61e0)
    	/Users/rsc/go1.9/src/runtime/panic.go:491 +0x283
    log.(*Logger).Panic(0xc4209e6410, 0xc420ca9b10, 0x1, 0x1)
    	/Users/rsc/go1.9/src/log/log.go:216 +0xbe
    main.(*Work).gitCheckout(0xc420b92240)
    	/Users/rsc/src/golang.org/x/build/cmd/releasebot/git.go:67 +0xa93
    main.(*Work).doRelease(0xc420b92240)
    	/Users/rsc/src/golang.org/x/build/cmd/releasebot/main.go:265 +0x3ab
    main.main.func1(0xc420a67810, 0xc420b92240)
    	/Users/rsc/src/golang.org/x/build/cmd/releasebot/main.go:99 +0x51
    created by main.main
    	/Users/rsc/src/golang.org/x/build/cmd/releasebot/main.go:97 +0x4c4

— golang.org/x/build/cmd/releasebot, Oct 26 21:06:27 UTC

**Comment by rsc** [comment]
## go1.8.5rc3 pre-release distributions

go1.8.5rc3 distributions are now available for testing:

src ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.8.5rc3/go1.8.5rc3.src.tar.gz))
linux\-386 ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.8.5rc3/go1.8.5rc3.linux-386.tar.gz))
linux\-armv6l ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.8.5rc3/go1.8.5rc3.linux-armv6l.tar.gz))
linux\-amd64 ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.8.5rc3/go1.8.5rc3.linux-amd64.tar.gz))
linux\-arm64 (~~tar\.gz~~)
freebsd\-386 ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.8.5rc3/go1.8.5rc3.freebsd-386.tar.gz))
freebsd\-amd64 ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.8.5rc3/go1.8.5rc3.freebsd-amd64.tar.gz))
windows\-386 ([zip](https://golang-release-staging.storage.googleapis.com/go1.8.5rc3/go1.8.5rc3.windows-386.zip)) ([msi](https://golang-release-staging.storage.googleapis.com/go1.8.5rc3/go1.8.5rc3.windows-386.msi))
windows\-amd64 ([zip](https://golang-release-staging.storage.googleapis.com/go1.8.5rc3/go1.8.5rc3.windows-amd64.zip)) ([msi](https://golang-release-staging.storage.googleapis.com/go1.8.5rc3/go1.8.5rc3.windows-amd64.msi))
darwin\-amd64 ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.8.5rc3/go1.8.5rc3.darwin-amd64.tar.gz)) ([pkg](https://golang-release-staging.storage.googleapis.com/go1.8.5rc3/go1.8.5rc3.darwin-amd64.pkg))
linux\-s390x ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.8.5rc3/go1.8.5rc3.linux-s390x.tar.gz))
linux\-ppc64le ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.8.5rc3/go1.8.5rc3.linux-ppc64le.tar.gz))

— golang.org/x/build/cmd/releasebot, Oct 19 23:25:49 UTC

**Comment by rsc** [comment]
## go1.8.5rc4 pre-release distributions

go1.8.5rc4 distributions are now available for testing:

src ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.8.5rc4/go1.8.5rc4.src.tar.gz))
linux\-386 ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.8.5rc4/go1.8.5rc4.linux-386.tar.gz))
linux\-armv6l ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.8.5rc4/go1.8.5rc4.linux-armv6l.tar.gz))
linux\-amd64 ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.8.5rc4/go1.8.5rc4.linux-amd64.tar.gz))
linux\-arm64 ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.8.5rc4/go1.8.5rc4.linux-arm64.tar.gz))
freebsd\-386 ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.8.5rc4/go1.8.5rc4.freebsd-386.tar.gz))
freebsd\-amd64 ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.8.5rc4/go1.8.5rc4.freebsd-amd64.tar.gz))
windows\-386 ([zip](https://golang-release-staging.storage.googleapis.com/go1.8.5rc4/go1.8.5rc4.windows-386.zip)) ([msi](https://golang-release-staging.storage.googleapis.com/go1.8.5rc4/go1.8.5rc4.windows-386.msi))
windows\-amd64 ([zip](https://golang-release-staging.storage.googleapis.com/go1.8.5rc4/go1.8.5rc4.windows-amd64.zip)) ([msi](https://golang-release-staging.storage.googleapis.com/go1.8.5rc4/go1.8.5rc4.windows-amd64.msi))
darwin\-amd64 ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.8.5rc4/go1.8.5rc4.darwin-amd64.tar.gz)) ([pkg](https://golang-release-staging.storage.googleapis.com/go1.8.5rc4/go1.8.5rc4.darwin-amd64.pkg))
linux\-s390x ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.8.5rc4/go1.8.5rc4.linux-s390x.tar.gz))
linux\-ppc64le ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.8.5rc4/go1.8.5rc4.linux-ppc64le.tar.gz))

— golang.org/x/build/cmd/releasebot, Oct 20 17:54:25 UTC

**Comment by rsc** [comment]
## go1.8.5rc5 pre-release distributions

go1.8.5rc5 distributions are now available for testing:

src ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.8.5rc5/go1.8.5rc5.src.tar.gz))
linux\-386 ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.8.5rc5/go1.8.5rc5.linux-386.tar.gz))
linux\-armv6l (~~tar\.gz~~)
linux\-amd64 ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.8.5rc5/go1.8.5rc5.linux-amd64.tar.gz))
linux\-arm64 ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.8.5rc5/go1.8.5rc5.linux-arm64.tar.gz))
freebsd\-386 (~~tar\.gz~~)
freebsd\-amd64 (~~tar\.gz~~)
windows\-386 ([zip](https://golang-release-staging.storage.googleapis.com/go1.8.5rc5/go1.8.5rc5.windows-386.zip)) ([msi](https://golang-release-staging.storage.googleapis.com/go1.8.5rc5/go1.8.5rc5.windows-386.msi))
windows\-amd64 (~~zip~~) (~~msi~~)
darwin\-amd64 ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.8.5rc5/go1.8.5rc5.darwin-amd64.tar.gz)) ([pkg](https://golang-release-staging.storage.googleapis.com/go1.8.5rc5/go1.8.5rc5.darwin-amd64.pkg))
linux\-s390x ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.8.5rc5/go1.8.5rc5.linux-s390x.tar.gz))
linux\-ppc64le ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.8.5rc5/go1.8.5rc5.linux-ppc64le.tar.gz))

— golang.org/x/build/cmd/releasebot, Oct 25 16:46:37 UTC

**Comment by rsc** [comment]
go1.8.5 has been packaged and includes:

  - [CL 37154](https://golang.org/cl/37154) 
  - [CL 38633](https://golang.org/cl/38633) 
  - [CL 41395](https://golang.org/cl/41395) 
  - [CL 44430](https://golang.org/cl/44430) 
  - [CL 45015](https://golang.org/cl/45015) 
  - [CL 56850](https://golang.org/cl/56850) 
  - [CL 66491](https://golang.org/cl/66491) 
  - [CL 67350](https://golang.org/cl/67350) 
  - [CL 68470](https://golang.org/cl/68470) 
  - [CL 69670](https://golang.org/cl/69670) 
  - [CL 70837](https://golang.org/cl/70837) 
  - [CL 70841](https://golang.org/cl/70841) 
  - [CL 70842](https://golang.org/cl/70842) 
  - [CL 70871](https://golang.org/cl/70871) 
  - [CL 71410](https://golang.org/cl/71410) 
  - [CL 73392](https://golang.org/cl/73392) 

The release is posted at [golang.org/dl](https://golang.org/dl).

— golang.org/x/build/cmd/releasebot, Oct 26 21:07:55 UTC
