### ISSUE TITLE
runtime: TestNetpollDeadlock fails on Linux in go1.9.1

### ISSUE THREAD

**Issue by bsed** [golang/go#22280]
--- FAIL: TestNetpollDeadlock (60.03s)
	crash_test.go:106: testprognet NetpollDeadlock exit status: exit status 2
	crash_test.go:416: output does not start with "done\n":
		dialing
		SIGQUIT: quit
		PC=0x459d31 m=0 sigcode=0
		
		goroutine 0 [idle]:
		runtime.futex(0x5dfdd0, 0x0, 0x0, 0x0, 0x7ffd00000000, 0x0, 0x0, 0x0, 0x7ffd190373a8, 0x41034b, ...)
			/home/kelvin/go/src/runtime/sys_linux_amd64.s:438 +0x21
		runtime.futexsleep(0x5dfdd0, 0x7ffd00000000, 0xffffffffffffffff)
			/home/kelvin/go/src/runtime/os_linux.go:45 +0x62
		runtime.notesleep(0x5dfdd0)
			/home/kelvin/go/src/runtime/lock_futex.go:151 +0x9b
		runtime.stoplockedm()
			/home/kelvin/go/src/runtime/proc.go:1819 +0x8c
		runtime.schedule()
			/home/kelvin/go/src/runtime/proc.go:2205 +0x2cf
		runtime.park_m(0xc420000180)
			/home/kelvin/go/src/runtime/proc.go:2310 +0xb6
		runtime.mcall(0x7ffd190374c0)
			/home/kelvin/go/src/runtime/asm_amd64.s:286 +0x5b
		
		goroutine 1 [IO wait, locked to thread]:
		internal/poll.runtime_pollWait(0x7f651d1c8f70, 0x77, 0x7f651d1c8f78)
			/home/kelvin/go/src/runtime/netpoll.go:173 +0x57
		internal/poll.(*pollDesc).wait(0xc4200c4118, 0x77, 0xc420059600, 0xc420059678, 0xc420059601)
			/home/kelvin/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
		internal/poll.(*pollDesc).waitWrite(0xc4200c4118, 0xc4200c4100, 0x0, 0x0)
			/home/kelvin/go/src/internal/poll/fd_poll_runtime.go:94 +0x3d
		internal/poll.(*FD).WaitWrite(0xc4200c4100, 0xc42008e010, 0xc42008e010)
			/home/kelvin/go/src/internal/poll/fd_unix.go:400 +0x37
		net.(*netFD).connect(0xc4200c4100, 0x5caac0, 0xc42008e010, 0x0, 0x0, 0x5c9940, 0xc420016100, 0x0, 0x0, 0x0, ...)
			/home/kelvin/go/src/net/fd_unix.go:152 +0x2b6
		net.(*netFD).dial(0xc4200c4100, 0x5caac0, 0xc42008e010, 0x5cafe0, 0x0, 0x5cafe0, 0xc4200869c0, 0xc420059888, 0x4d010e)
			/home/kelvin/go/src/net/sock_posix.go:142 +0xe9
		net.socket(0x5caac0, 0xc42008e010, 0x53195d, 0x3, 0xa, 0x1, 0x0, 0x0, 0x5cafe0, 0x0, ...)
			/home/kelvin/go/src/net/sock_posix.go:93 +0x1a5
		net.internetSocket(0x5caac0, 0xc42008e010, 0x53195d, 0x3, 0x5cafe0, 0x0, 0x5cafe0, 0xc4200869c0, 0x1, 0x0, ...)
			/home/kelvin/go/src/net/ipsock_posix.go:141 +0x129
		net.doDialTCP(0x5caac0, 0xc42008e010, 0x53195d, 0x3, 0x0, 0xc4200869c0, 0x5caac0, 0xc420059a58, 0x0)
			/home/kelvin/go/src/net/tcpsock_posix.go:62 +0xb9
		net.dialTCP(0x5caac0, 0xc42008e010, 0x53195d, 0x3, 0x0, 0xc4200869c0, 0x449fc8, 0x5cd7406ff4b, 0xc437243d3a)
			/home/kelvin/go/src/net/tcpsock_posix.go:58 +0xe4
		net.dialSingle(0x5caac0, 0xc42008e010, 0xc4200c0000, 0x5c9f80, 0xc4200869c0, 0x0, 0x0, 0x0, 0x0)
			/home/kelvin/go/src/net/dial.go:547 +0x3e2
		net.dialSerial(0x5caac0, 0xc42008e010, 0xc4200c0000, 0xc420094140, 0x4, 0x4, 0x0, 0x0, 0x0, 0x0)
			/home/kelvin/go/src/net/dial.go:515 +0x247
		net.(*Dialer).DialContext(0xc420059e00, 0x5caac0, 0xc42008e010, 0x53195d, 0x3, 0x5334da, 0xf, 0x0, 0x0, 0x0, ...)
			/home/kelvin/go/src/net/dial.go:397 +0x6ee
		net.(*Dialer).Dial(0xc420059e00, 0x53195d, 0x3, 0x5334da, 0xf, 0x0, 0x8, 0xc4200a8000, 0x0)
			/home/kelvin/go/src/net/dial.go:320 +0x75
		net.Dial(0x53195d, 0x3, 0x5334da, 0xf, 0x0, 0x0, 0x50fcc0, 0xc420096001)
			/home/kelvin/go/src/net/dial.go:291 +0x99
		main.NetpollDeadlockInit()
			/home/kelvin/go/src/runtime/testdata/testprognet/net.go:19 +0x99
		main.registerInit(0x533444, 0xf, 0x539988)
			/home/kelvin/go/src/runtime/testdata/testprognet/main.go:20 +0x7d
		main.init.0()
			/home/kelvin/go/src/runtime/testdata/testprognet/net.go:13 +0x42
		main.init()
			<autogenerated>:1 +0xb4
		
		goroutine 19 [syscall]:
		os/signal.signal_recv(0x0)
			/home/kelvin/go/src/runtime/sigqueue.go:131 +0xa6
		os/signal.loop()
			/home/kelvin/go/src/os/signal/signal_unix.go:22 +0x22
		created by os/signal.init.0
			/home/kelvin/go/src/os/signal/signal_unix.go:28 +0x41
		
		rax    0xca
		rbx    0x5dfcc0
		rcx    0x459d33
		rdx    0x0
		rdi    0x5dfdd0
		rsi    0x0
		rbp    0x7ffd19037370
		rsp    0x7ffd19037328
		r8     0x0
		r9     0x0
		r10    0x0
		r11    0x286
		r12    0x0
		r13    0xf7
		r14    0x77
		r15    0x0
		rip    0x459d31
		rflags 0x286
		cs     0x33
		fs     0x0
		gs     0x0
FAIL
FAIL	runtime	96.784s
ok  	runtime/debug	0.015s

**Comment by odeke-em** [comment]
@bsed thank you for the report. How often is this happening? Is this a flake or can you continuously reproduce it?

/cc @aclements

**Comment by bsed** [comment]
```
kelvin@gnux:~/go> git checkout go1.9.1
Note: checking out 'go1.9.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 7f40c1214d... [release-branch.go1.9] go1.9.1
kelvin@gnux:~/go> cd src/                                                                                                                                          ((go1.9.1)) (10/18 21:21:55)
kelvin@gnux:~/go/src> ./all                                                                                                                                        ((go1.9.1)) (10/18 21:22:03)
all.bash  all.rc    
kelvin@gnux:~/go/src> ./all.bash 
##### Building Go bootstrap tool.
cmd/dist

##### Building Go toolchain using /home/kelvin/go1.4.
bootstrap/cmd/internal/dwarf
bootstrap/cmd/internal/objabi
bootstrap/cmd/internal/src
bootstrap/cmd/internal/sys
bootstrap/cmd/asm/internal/flags
bootstrap/cmd/internal/bio
bootstrap/math/bits
bootstrap/cmd/compile/internal/syntax
bootstrap/cmd/internal/obj
bootstrap/cmd/asm/internal/lex
bootstrap/math/big
bootstrap/cmd/internal/gcprog
bootstrap/debug/pe
bootstrap/cmd/internal/obj/arm
bootstrap/cmd/internal/obj/arm64
bootstrap/cmd/internal/obj/mips
bootstrap/cmd/internal/obj/ppc64
bootstrap/cmd/internal/obj/s390x
bootstrap/cmd/internal/obj/x86
bootstrap/cmd/compile/internal/types
bootstrap/cmd/link/internal/ld
bootstrap/cmd/asm/internal/arch
bootstrap/cmd/compile/internal/ssa
bootstrap/cmd/asm/internal/asm
bootstrap/cmd/asm
bootstrap/cmd/link/internal/amd64
bootstrap/cmd/link/internal/arm
bootstrap/cmd/link/internal/arm64
bootstrap/cmd/link/internal/mips
bootstrap/cmd/link/internal/mips64
bootstrap/cmd/link/internal/ppc64
bootstrap/cmd/link/internal/s390x
bootstrap/cmd/link/internal/x86
bootstrap/cmd/link
bootstrap/cmd/compile/internal/gc
bootstrap/cmd/compile/internal/amd64
bootstrap/cmd/compile/internal/arm
bootstrap/cmd/compile/internal/arm64
bootstrap/cmd/compile/internal/mips
bootstrap/cmd/compile/internal/mips64
bootstrap/cmd/compile/internal/ppc64
bootstrap/cmd/compile/internal/s390x
bootstrap/cmd/compile/internal/x86
bootstrap/cmd/compile

##### Building go_bootstrap for host, linux/amd64.
runtime/internal/sys
runtime/internal/atomic
runtime
encoding
errors
internal/cpu
internal/race
internal/syscall/windows/sysdll
math/bits
sync/atomic
unicode
unicode/utf16
unicode/utf8
math
sync
io
syscall
internal/singleflight
cmd/go/internal/web
hash
bytes
strings
hash/adler32
bufio
strconv
path
internal/syscall/windows
internal/syscall/windows/registry
time
reflect
encoding/base64
crypto
crypto/sha1
internal/poll
os
sort
encoding/binary
container/heap
regexp/syntax
os/signal
fmt
path/filepath
io/ioutil
context
flag
go/token
log
cmd/go/internal/str
net/url
text/template/parse
compress/flate
encoding/xml
encoding/json
debug/dwarf
regexp
os/exec
go/scanner
cmd/internal/objabi
go/ast
compress/zlib
debug/macho
debug/elf
text/template
go/parser
go/doc
go/build
cmd/go/internal/cfg
cmd/go/internal/base
cmd/go/internal/buildid
cmd/go/internal/cmdflag
cmd/go/internal/doc
cmd/go/internal/help
cmd/go/internal/load
cmd/go/internal/tool
cmd/go/internal/version
cmd/go/internal/fix
cmd/go/internal/fmtcmd
cmd/go/internal/work
cmd/go/internal/clean
cmd/go/internal/envcmd
cmd/go/internal/generate
cmd/go/internal/get
cmd/go/internal/list
cmd/go/internal/run
cmd/go/internal/test
cmd/go/internal/vet
cmd/go/internal/bug
cmd/go

##### Building packages and commands for linux/amd64.
runtime/internal/sys
runtime/internal/atomic
runtime
internal/cpu
internal/race
errors
sync/atomic
unicode
unicode/utf8
math
sync
container/list
math/bits
io
syscall
hash
hash/adler32
hash/crc32
bytes
strings
strconv
bufio
path
text/tabwriter
reflect
cmd/internal/src
container/ring
crypto
crypto/subtle
time
crypto/internal/cipherhw
crypto/cipher
math/rand
crypto/sha512
crypto/aes
crypto/hmac
crypto/md5
internal/syscall/unix
crypto/rc4
crypto/sha1
crypto/sha256
encoding/base64
internal/nettrace
internal/singleflight
vendor/golang_org/x/crypto/poly1305
internal/poll
vendor/golang_org/x/crypto/curve25519
encoding
encoding/ascii85
encoding/base32
unicode/utf16
vendor/golang_org/x/text/transform
os
hash/crc64
hash/fnv
html
image/color
image
image/color/palette
internal/syscall/windows
internal/syscall/windows/registry
internal/syscall/windows/sysdll
runtime/trace
math/cmplx
os/signal
fmt
sort
encoding/binary
image/internal/imageutil
path/filepath
regexp/syntax
cmd/internal/sys
compress/bzip2
io/ioutil
container/heap
crypto/des
encoding/pem
flag
log
debug/dwarf
compress/flate
cmd/internal/objabi
debug/gosym
cmd/internal/goobj
debug/plan9obj
cmd/vendor/golang.org/x/arch/arm/armasm
cmd/vendor/golang.org/x/arch/ppc64/ppc64asm
compress/zlib
debug/macho
debug/elf
debug/pe
cmd/vendor/golang.org/x/arch/x86/x86asm
regexp
archive/tar
archive/zip
compress/gzip
compress/lzw
context
math/big
encoding/hex
go/token
os/exec
go/scanner
cmd/internal/objfile
go/ast
vendor/golang_org/x/crypto/chacha20poly1305/internal/chacha20
vendor/golang_org/x/crypto/chacha20poly1305
database/sql/driver
cmd/addr2line
database/sql
go/parser
crypto/dsa
crypto/elliptic
encoding/asn1
crypto/rand
go/printer
encoding/csv
crypto/rsa
encoding/gob
crypto/ecdsa
crypto/x509/pkix
encoding/json
encoding/xml
cmd/cgo
vendor/golang_org/x/net/http2/hpack
vendor/golang_org/x/text/unicode/bidi
vendor/golang_org/x/text/unicode/norm
net/url
mime
vendor/golang_org/x/text/secure/bidirule
mime/quotedprintable
net/http/internal
text/template/parse
go/constant
vendor/golang_org/x/net/idna
go/format
go/types
text/template
text/scanner
image/draw
image/gif
runtime/cgo
go/doc
html/template
go/build
image/jpeg
net
image/png
index/suffixarray
runtime/debug
testing
internal/trace
go/internal/gccgoimporter
go/internal/gcimporter
go/internal/srcimporter
internal/testenv
runtime/pprof
net/internal/socktest
go/importer
os/user
plugin
runtime/pprof/internal/profile
runtime/race
testing/internal/testdeps
testing/iotest
testing/quick
vendor/golang_org/x/text/secure
vendor/golang_org/x/text/unicode
cmd/api
cmd/internal/dwarf
cmd/asm/internal/flags
cmd/asm/internal/lex
cmd/internal/obj
cmd/internal/bio
cmd/compile/internal/syntax
cmd/internal/obj/arm
crypto/x509
vendor/golang_org/x/net/lex/httplex
vendor/golang_org/x/net/proxy
net/textproto
log/syslog
crypto/tls
vendor/golang_org/x/net/nettest
mime/multipart
net/mail
cmd/internal/obj/arm64
cmd/internal/obj/mips
cmd/internal/obj/ppc64
cmd/internal/obj/s390x
cmd/internal/obj/x86
net/http/httptrace
net/http
net/smtp
cmd/compile/internal/types
cmd/internal/gcprog
cmd/compile/internal/test
cmd/internal/browser
cmd/cover
cmd/dist
cmd/asm/internal/arch
cmd/asm/internal/asm
cmd/asm
cmd/compile/internal/ssa
cmd/doc
cmd/fix
cmd/go/internal/cfg
cmd/go/internal/str
expvar
net/http/cgi
net/http/cookiejar
net/http/httptest
net/http/httputil
net/http/fcgi
net/http/pprof
net/rpc
cmd/go/internal/base
cmd/go/internal/buildid
cmd/go/internal/web
cmd/go/internal/load
cmd/go/internal/doc
cmd/go/internal/help
net/rpc/jsonrpc
cmd/go/internal/cmdflag
cmd/go/internal/tool
cmd/go/internal/version
cmd/gofmt
cmd/link/internal/ld
cmd/go/internal/work
cmd/go/internal/fix
cmd/go/internal/fmtcmd
cmd/nm
cmd/objdump
cmd/go/internal/envcmd
cmd/go/internal/bug
cmd/go/internal/clean
cmd/go/internal/generate
cmd/go/internal/get
cmd/go/internal/list
cmd/go/internal/run
cmd/go/internal/test
cmd/go/internal/vet
cmd/pack
cmd/go
cmd/vendor/github.com/google/pprof/internal/elfexec
cmd/vendor/github.com/google/pprof/profile
cmd/link/internal/amd64
cmd/link/internal/arm
cmd/link/internal/arm64
cmd/link/internal/mips
cmd/link/internal/mips64
cmd/link/internal/ppc64
cmd/link/internal/s390x
cmd/link/internal/x86
cmd/vendor/github.com/google/pprof/internal/plugin
cmd/link
cmd/vendor/github.com/ianlancetaylor/demangle
cmd/vendor/github.com/google/pprof/internal/measurement
cmd/vendor/github.com/google/pprof/internal/graph
cmd/vendor/github.com/google/pprof/internal/report
cmd/vendor/github.com/google/pprof/internal/symbolz
cmd/vendor/github.com/google/pprof/third_party/svg
cmd/trace
cmd/vendor/github.com/google/pprof/internal/proftest
cmd/vet/internal/cfg
cmd/vendor/github.com/google/pprof/internal/binutils
cmd/vet/internal/whitelist
cmd/vet
cmd/vendor/github.com/google/pprof/internal/symbolizer
cmd/vendor/github.com/google/pprof/internal/driver
cmd/vendor/github.com/google/pprof/driver
cmd/pprof
cmd/compile/internal/gc
cmd/compile/internal/amd64
cmd/compile/internal/mips
cmd/compile/internal/arm
cmd/compile/internal/arm64
cmd/compile/internal/mips64
cmd/compile/internal/ppc64
cmd/compile/internal/s390x
cmd/compile/internal/x86
cmd/compile


##### cmd/go terminal test
PASS
ok  	_/home/kelvin/go/src/cmd/go/testdata/testterminal18153	0.001s

##### Testing packages.
ok  	archive/tar	0.017s
ok  	archive/zip	1.586s
ok  	bufio	0.059s
ok  	bytes	0.546s
ok  	compress/bzip2	0.060s
ok  	compress/flate	1.007s
ok  	compress/gzip	0.012s
ok  	compress/lzw	0.034s
ok  	compress/zlib	0.048s
ok  	container/heap	0.001s
ok  	container/list	0.011s
ok  	container/ring	0.010s
ok  	context	0.980s
ok  	crypto/aes	0.033s
ok  	crypto/cipher	0.008s
ok  	crypto/des	0.007s
ok  	crypto/dsa	0.008s
ok  	crypto/ecdsa	0.061s
ok  	crypto/elliptic	0.036s
ok  	crypto/hmac	0.001s
ok  	crypto/md5	0.002s
ok  	crypto/rand	0.045s
ok  	crypto/rc4	0.085s
ok  	crypto/rsa	0.099s
ok  	crypto/sha1	0.031s
ok  	crypto/sha256	0.003s
ok  	crypto/sha512	0.002s
ok  	crypto/subtle	0.009s
ok  	crypto/tls	0.793s
ok  	crypto/x509	0.872s
ok  	database/sql	0.543s
ok  	database/sql/driver	0.008s
ok  	debug/dwarf	0.009s
ok  	debug/elf	0.028s
ok  	debug/gosym	0.374s
ok  	debug/macho	0.015s
ok  	debug/pe	0.025s
ok  	debug/plan9obj	0.003s
ok  	encoding/ascii85	0.019s
ok  	encoding/asn1	0.003s
ok  	encoding/base32	0.015s
ok  	encoding/base64	0.005s
ok  	encoding/binary	0.008s
ok  	encoding/csv	0.004s
ok  	encoding/gob	0.043s
ok  	encoding/hex	0.011s
ok  	encoding/json	0.603s
ok  	encoding/pem	0.015s
ok  	encoding/xml	0.030s
ok  	errors	0.027s
ok  	expvar	0.004s
ok  	flag	0.005s
ok  	fmt	0.082s
ok  	go/ast	0.013s
ok  	go/build	0.077s
ok  	go/constant	0.005s
ok  	go/doc	0.039s
ok  	go/format	0.008s
ok  	go/internal/gccgoimporter	0.006s
ok  	go/internal/gcimporter	0.583s
ok  	go/internal/srcimporter	0.701s
ok  	go/parser	0.024s
ok  	go/printer	0.428s
ok  	go/scanner	0.016s
ok  	go/token	0.021s
ok  	go/types	0.798s
ok  	hash/adler32	0.007s
ok  	hash/crc32	0.004s
ok  	hash/crc64	0.002s
ok  	hash/fnv	0.003s
ok  	html	0.006s
ok  	html/template	0.067s
ok  	image	0.092s
ok  	image/color	0.021s
ok  	image/draw	0.051s
ok  	image/gif	0.067s
ok  	image/jpeg	0.230s
ok  	image/png	0.045s
ok  	index/suffixarray	0.006s
ok  	internal/cpu	0.001s
ok  	internal/poll	0.015s
ok  	internal/singleflight	0.012s
ok  	internal/trace	0.772s
ok  	io	0.056s
ok  	io/ioutil	0.009s
ok  	log	0.004s
ok  	log/syslog	1.216s
ok  	math	0.004s
ok  	math/big	1.941s
ok  	math/bits	0.027s
ok  	math/cmplx	0.002s
ok  	math/rand	0.070s
ok  	mime	0.027s
ok  	mime/multipart	0.569s
ok  	mime/quotedprintable	0.126s
ok  	net	1.773s
ok  	net/http	3.343s
ok  	net/http/cgi	0.397s
ok  	net/http/cookiejar	0.006s
ok  	net/http/fcgi	0.009s
ok  	net/http/httptest	0.022s
ok  	net/http/httptrace	0.008s
ok  	net/http/httputil	0.036s
ok  	net/http/internal	0.002s
ok  	net/internal/socktest	0.010s
ok  	net/mail	0.005s
ok  	net/rpc	0.011s
ok  	net/rpc/jsonrpc	0.005s
ok  	net/smtp	0.007s
ok  	net/textproto	0.007s
ok  	net/url	0.003s
ok  	os	0.389s
ok  	os/exec	0.538s
ok  	os/signal	4.384s
ok  	os/user	0.006s
ok  	path	0.002s
ok  	path/filepath	0.005s
ok  	reflect	0.172s
ok  	regexp	0.114s
ok  	regexp/syntax	0.390s
--- FAIL: TestNetpollDeadlock (60.03s)
	crash_test.go:106: testprognet NetpollDeadlock exit status: exit status 2
	crash_test.go:416: output does not start with "done\n":
		dialing
		SIGQUIT: quit
		PC=0x45a001 m=0 sigcode=0
		
		goroutine 0 [idle]:
		runtime.futex(0x5dfdd0, 0x0, 0x0, 0x0, 0x7fff00000000, 0x413cc8, 0x0, 0x0, 0x7fffb3014758, 0x4103ab, ...)
			/home/kelvin/go/src/runtime/sys_linux_amd64.s:438 +0x21
		runtime.futexsleep(0x5dfdd0, 0x7fff00000000, 0xffffffffffffffff)
			/home/kelvin/go/src/runtime/os_linux.go:45 +0x62
		runtime.notesleep(0x5dfdd0)
			/home/kelvin/go/src/runtime/lock_futex.go:151 +0x9b
		runtime.stoplockedm()
			/home/kelvin/go/src/runtime/proc.go:1817 +0x8c
		runtime.schedule()
			/home/kelvin/go/src/runtime/proc.go:2203 +0x2cf
		runtime.park_m(0xc420000180)
			/home/kelvin/go/src/runtime/proc.go:2308 +0xb6
		runtime.mcall(0x7fffb3014870)
			/home/kelvin/go/src/runtime/asm_amd64.s:286 +0x5b
		
		goroutine 1 [IO wait, locked to thread]:
		internal/poll.runtime_pollWait(0x7f25f8950f70, 0x77, 0x7f25f8950f78)
			/home/kelvin/go/src/runtime/netpoll.go:173 +0x57
		internal/poll.(*pollDesc).wait(0xc4200d4018, 0x77, 0xc420059600, 0xc420059678, 0xc420059601)
			/home/kelvin/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
		internal/poll.(*pollDesc).waitWrite(0xc4200d4018, 0xc4200d4000, 0x0, 0x0)
			/home/kelvin/go/src/internal/poll/fd_poll_runtime.go:94 +0x3d
		internal/poll.(*FD).WaitWrite(0xc4200d4000, 0xc42001e180, 0xc42001e180)
			/home/kelvin/go/src/internal/poll/fd_unix.go:402 +0x37
		net.(*netFD).connect(0xc4200d4000, 0x5caac0, 0xc42001e180, 0x0, 0x0, 0x5c9940, 0xc4200d6000, 0x0, 0x0, 0x0, ...)
			/home/kelvin/go/src/net/fd_unix.go:152 +0x2b6
		net.(*netFD).dial(0xc4200d4000, 0x5caac0, 0xc42001e180, 0x5cafe0, 0x0, 0x5cafe0, 0xc42009e420, 0xc420059888, 0x4d06ce)
			/home/kelvin/go/src/net/sock_posix.go:142 +0xe9
		net.socket(0x5caac0, 0xc42001e180, 0x531d3d, 0x3, 0xa, 0x1, 0x0, 0x0, 0x5cafe0, 0x0, ...)
			/home/kelvin/go/src/net/sock_posix.go:93 +0x1a5
		net.internetSocket(0x5caac0, 0xc42001e180, 0x531d3d, 0x3, 0x5cafe0, 0x0, 0x5cafe0, 0xc42009e420, 0x1, 0x0, ...)
			/home/kelvin/go/src/net/ipsock_posix.go:141 +0x129
		net.doDialTCP(0x5caac0, 0xc42001e180, 0x531d3d, 0x3, 0x0, 0xc42009e420, 0x5caac0, 0xc420059a58, 0x0)
			/home/kelvin/go/src/net/tcpsock_posix.go:62 +0xb9
		net.dialTCP(0x5caac0, 0xc42001e180, 0x531d3d, 0x3, 0x0, 0xc42009e420, 0x44a1c8, 0x5b7b1fc222d, 0xc4376ad023)
			/home/kelvin/go/src/net/tcpsock_posix.go:58 +0xe4
		net.dialSingle(0x5caac0, 0xc42001e180, 0xc4200ca000, 0x5c9f80, 0xc42009e420, 0x0, 0x0, 0x0, 0x0)
			/home/kelvin/go/src/net/dial.go:547 +0x3e2
		net.dialSerial(0x5caac0, 0xc42001e180, 0xc4200ca000, 0xc42009c100, 0x4, 0x4, 0x0, 0x0, 0x0, 0x0)
			/home/kelvin/go/src/net/dial.go:515 +0x247
		net.(*Dialer).DialContext(0xc420059e00, 0x5caac0, 0xc42001e180, 0x531d3d, 0x3, 0x5338c1, 0xf, 0x0, 0x0, 0x0, ...)
			/home/kelvin/go/src/net/dial.go:397 +0x6ee
		net.(*Dialer).Dial(0xc420059e00, 0x531d3d, 0x3, 0x5338c1, 0xf, 0x0, 0x8, 0xc420084000, 0x0)
			/home/kelvin/go/src/net/dial.go:320 +0x75
		net.Dial(0x531d3d, 0x3, 0x5338c1, 0xf, 0x0, 0x0, 0x50fcc0, 0xc42000c001)
			/home/kelvin/go/src/net/dial.go:291 +0x99
		main.NetpollDeadlockInit()
			/home/kelvin/go/src/runtime/testdata/testprognet/net.go:19 +0x99
		main.registerInit(0x53382b, 0xf, 0x539d58)
			/home/kelvin/go/src/runtime/testdata/testprognet/main.go:20 +0x7d
		main.init.0()
			/home/kelvin/go/src/runtime/testdata/testprognet/net.go:13 +0x42
		main.init()
			<autogenerated>:1 +0xb4
		
		goroutine 5 [syscall]:
		os/signal.signal_recv(0x0)
			/home/kelvin/go/src/runtime/sigqueue.go:131 +0xa6
		os/signal.loop()
			/home/kelvin/go/src/os/signal/signal_unix.go:22 +0x22
		created by os/signal.init.0
			/home/kelvin/go/src/os/signal/signal_unix.go:28 +0x41
		
		rax    0xca
		rbx    0x5dfcc0
		rcx    0x45a003
		rdx    0x0
		rdi    0x5dfdd0
		rsi    0x0
		rbp    0x7fffb3014720
		rsp    0x7fffb30146d8
		r8     0x0
		r9     0x0
		r10    0x0
		r11    0x286
		r12    0x0
		r13    0xf7
		r14    0x77
		r15    0x0
		rip    0x45a001
		rflags 0x286
		cs     0x33
		fs     0x0
		gs     0x0
FAIL
FAIL	runtime	83.292s
ok  	runtime/debug	0.003s
ok  	runtime/internal/atomic	0.111s
ok  	runtime/internal/sys	0.005s
ok  	runtime/pprof	3.188s
ok  	runtime/pprof/internal/profile	0.001s
ok  	runtime/trace	1.670s
ok  	sort	0.066s
ok  	strconv	0.423s
ok  	strings	0.122s
ok  	sync	0.161s
ok  	sync/atomic	0.023s
ok  	syscall	0.064s
ok  	testing	0.889s
ok  	testing/quick	0.122s
ok  	text/scanner	0.005s
ok  	text/tabwriter	0.002s
ok  	text/template	0.294s
ok  	text/template/parse	0.006s
ok  	time	2.653s
ok  	unicode	0.003s
ok  	unicode/utf16	0.001s
ok  	unicode/utf8	0.004s
ok  	vendor/golang_org/x/crypto/chacha20poly1305	0.047s
ok  	vendor/golang_org/x/crypto/chacha20poly1305/internal/chacha20	0.001s
ok  	vendor/golang_org/x/crypto/curve25519	0.015s
ok  	vendor/golang_org/x/crypto/poly1305	0.001s
ok  	vendor/golang_org/x/net/http2/hpack	0.025s
ok  	vendor/golang_org/x/net/idna	0.002s
ok  	vendor/golang_org/x/net/lex/httplex	0.005s
ok  	vendor/golang_org/x/net/nettest	1.007s
ok  	vendor/golang_org/x/net/proxy	0.002s
ok  	vendor/golang_org/x/text/transform	0.004s
ok  	vendor/golang_org/x/text/unicode/norm	0.001s
ok  	cmd/addr2line	1.231s
ok  	cmd/api	0.004s
ok  	cmd/asm/internal/asm	0.216s
ok  	cmd/asm/internal/lex	0.003s
ok  	cmd/compile	6.538s
ok  	cmd/compile/internal/gc	12.466s
ok  	cmd/compile/internal/ssa	0.151s
ok  	cmd/compile/internal/syntax	0.020s
ok  	cmd/compile/internal/test	0.018s [no tests to run]
ok  	cmd/compile/internal/types	0.023s
ok  	cmd/cover	1.995s
ok  	cmd/doc	0.054s
ok  	cmd/fix	0.023s
ok  	cmd/go	43.193s
ok  	cmd/go/internal/generate	0.012s
ok  	cmd/go/internal/get	0.025s
ok  	cmd/go/internal/load	0.003s
ok  	cmd/go/internal/work	0.004s
ok  	cmd/gofmt	0.031s
ok  	cmd/internal/dwarf	0.007s
ok  	cmd/internal/obj	0.001s
ok  	cmd/internal/obj/arm64	0.001s
ok  	cmd/internal/obj/x86	0.191s
ok  	cmd/internal/objabi	0.003s
ok  	cmd/internal/src	0.003s
ok  	cmd/link	2.533s
ok  	cmd/link/internal/ld	2.397s
ok  	cmd/nm	1.647s
ok  	cmd/objdump	1.273s
ok  	cmd/pack	0.925s
ok  	cmd/trace	0.005s
ok  	cmd/vendor/github.com/google/pprof/internal/binutils	0.001s
ok  	cmd/vendor/github.com/google/pprof/internal/driver	0.121s
ok  	cmd/vendor/github.com/google/pprof/internal/elfexec	0.001s
ok  	cmd/vendor/github.com/google/pprof/internal/graph	0.009s
ok  	cmd/vendor/github.com/google/pprof/internal/report	0.003s
ok  	cmd/vendor/github.com/google/pprof/internal/symbolizer	0.004s
ok  	cmd/vendor/github.com/google/pprof/internal/symbolz	0.005s
ok  	cmd/vendor/github.com/google/pprof/profile	0.061s
ok  	cmd/vendor/github.com/ianlancetaylor/demangle	0.014s
ok  	cmd/vendor/golang.org/x/arch/arm/armasm	0.003s
ok  	cmd/vendor/golang.org/x/arch/ppc64/ppc64asm	0.013s
ok  	cmd/vendor/golang.org/x/arch/x86/x86asm	0.078s
ok  	cmd/vet	2.140s
ok  	cmd/vet/internal/cfg	0.001s
2017/10/18 21:24:54 Failed: exit status 1

kelvin@gnux:~/go/src> uname -ar                                                                                                                                    ((go1.9.1)) (10/18 21:24:54)
Linux gnux 4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by bsed** [comment]
https://build.golang.org/log/42df64c7f96c7dad71289193236d36cb7153bb36

**Comment by ianlancetaylor** [comment]
@bsed It would be great if you could answer @odeke-em 's questions: How often is this happening? Is this a flake or can you continuously reproduce it?  Thanks.

**Comment by bsed** [comment]
@odeke-em I under ubuntu17.04, upgrade the system kernel , and then compile go1.9.1 source code, each compile this error.

**Comment by aclements** [comment]
@bsed, just a hunch, but are you running a firewall or anything that might interfere with IP routing?

**Comment by bsed** [comment]
@aclements I've shut down the firewall. This can be ruled out.

**Comment by bsed** [comment]
The problem has not been resolved
