### ISSUE TITLE
x/build/cmd/coordinator: staging environment doesn’t run current version

### ISSUE THREAD

**Issue by andybons** [golang/go#22437]
When running coordinator on the `go-dashboard-dev` project (our staging environment), it panics:
```
2017/10/25 17:24:24 Running in prod mode
panic: unknown builder "windows-386-gce"

goroutine 1 [running]:
main.stagingClusterBuilders(0x8)
	/go/src/golang.org/x/build/cmd/coordinator/coordinator.go:396 +0x527
main.main()
	/go/src/golang.org/x/build/cmd/coordinator/coordinator.go:318 +0xc50
```

This appears to be an issue with the environment and not the binary logic.

/cc @adams-sarah

**Comment by adams-sarah** [comment]
Oh it is in the binary.

See
https://github.com/golang/build/blob/master/cmd/coordinator/coordinator.go#L391

The set of (hard-coded) staging builders is out of date. There is no longer any builder called "windows-386-gce".
The string should just be update to "windows-386-2008" or something.
