### ISSUE TITLE
cmd/compile: internal compiler error: block b10 not in loop branches to non-header block b8 in loop

### ISSUE THREAD

**Issue by ALTree** [golang/go#22560]
```
$ gotip version
go version devel +eaf603601b Fri Nov 3 01:55:16 2017 +0000 linux/amd64
```

```
$ cd src/cmd/compile/internal/gc

$ gotip test -run=TestGenFlowGrap
--- FAIL: TestGenFlowGraph (0.85s)
	ssa_test.go:97: Failed: exit status 1:
		Out: /tmp/ssa_fg_tmp1642404268/run.go:28287:2: internal compiler error: block b10 not in loop branches to non-header block b8 in loop
		
		goroutine 1 [running]:
		runtime/debug.Stack(0x0, 0x0, 0x0)
			/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
		cmd/compile/internal/gc.Fatalf(0xb70d75, 0x3c, 0xc420cb1ce0, 0x2, 0x2)
			/usr/local/go/src/cmd/compile/internal/gc/subr.go:181 +0x230
		cmd/compile/internal/gc.(*ssafn).Fatalf(0xc423fd6cc0, 0x6e7f0200000002, 0xb70d75, 0x3c, 0xc420cb1ce0, 0x2, 0x2)
			/usr/local/go/src/cmd/compile/internal/gc/ssa.go:5044 +0x67
		cmd/compile/internal/ssa.(*Func).Fatalf(0xc423d043c0, 0xb70d75, 0x3c, 0xc420cb1ce0, 0x2, 0x2)
			/usr/local/go/src/cmd/compile/internal/ssa/func.go:496 +0x78
		cmd/compile/internal/ssa.checkFunc(0xc423d043c0)
			/usr/local/go/src/cmd/compile/internal/ssa/check.go:284 +0x52c3
		cmd/compile/internal/ssa.Compile(0xc423d043c0)
			/usr/local/go/src/cmd/compile/internal/ssa/compile.go:110 +0x36d
		cmd/compile/internal/gc.buildssa(0xc4219de420, 0x0, 0x0)
			/usr/local/go/src/cmd/compile/internal/gc/ssa.go:216 +0xd89
		cmd/compile/internal/gc.compileSSA(0xc4219de420, 0x0)
			/usr/local/go/src/cmd/compile/internal/gc/pgen.go:240 +0x3c
		cmd/compile/internal/gc.compile(0xc4219de420)
			/usr/local/go/src/cmd/compile/internal/gc/pgen.go:219 +0x218
		cmd/compile/internal/gc.funccompile(0xc4219de420)
			/usr/local/go/src/cmd/compile/internal/gc/dcl.go:1049 +0xb7
		cmd/compile/internal/gc.Main(0xb73f98)
			/usr/local/go/src/cmd/compile/internal/gc/main.go:585 +0x29d2
		main.main()
			/usr/local/go/src/cmd/compile/main.go:49 +0x95
		
		
		Stderr: 
FAIL
exit status 1
FAIL	cmd/compile/internal/gc	0.857s
```

**Comment by ALTree** [comment]
cc @randall77
