### ISSUE TITLE
proposal: cmd/compile: better format for multiple runtime panics

### ISSUE THREAD

**Issue by dotaheor** [golang/go#23097]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.9.2 linux/amd64

### What did you do?

```
// a.go
package main

func main() {
	var s []int
	var is interface{} = s
	go func() {
		_ = s == nil
	}()
	go func() {
		_ = is == is
	}()
	
	var m map[string]bool = nil
	_ = m["Go"]
	_, _ = m["Go"]
	m, _ = is.(map[string]bool)
	m = is.(map[string]bool)
}
```

### What did you expect to see?

```
$ go run a.go

panic: interface conversion: interface {} is []int, not map[string]bool
goroutine 1 [running]:
main.main()
	/tmp/a.go:17 +0x15a

panic: runtime error: comparing uncomparable type []int
goroutine 19 [running]:
main.main.func2(0x45b480, 0x4cc2c0)
	/tmp/a.go:10 +0x3a
created by main.main
	/tmp/a.go:9 +0xc9
exit status 2
```

### What did you see instead?

```
$ go run a.go
panic: interface conversion: interface {} is []int, not map[string]bool

goroutine 1 [running]:
main.main()
	/tmp/a.go:17 +0x15a
panic: runtime error: comparing uncomparable type []int

goroutine 19 [running]:
main.main.func2(0x45b480, 0x4cc2c0)
	/tmp/a.go:10 +0x3a
created by main.main
	/tmp/a.go:9 +0xc9
exit status 2
```

**Comment by titanous** [comment]
Can you describe in more detail what the differences are? Without running `diff`, it just looks like there's a newline in a different place.

**Comment by dotaheor** [comment]
@titanous yes, the newline makes the messages get a better readability.

**Comment by odeke-em** [comment]
Gotcha @dotaheor. So this looks to me like an improvement that can be implemented without having to be a proposal and I can work on this. @randall77 am I right to say that we can JustDoIt (randall ™)?

**Comment by dotaheor** [comment]
It looks this is caused by two panics are printed at the same time. Sometimes, their messages may intertwine.

**Comment by dotaheor** [comment]
Maybe add a `print("\n")` line before https://github.com/golang/go/blob/master/src/runtime/panic.go#L819 is acceptable.
