### ISSUE TITLE
Latest tip version of all.bash fails on macOS

### ISSUE THREAD

**Issue by YoshikiShibata** [golang/go#24165]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

I tried to rebuild the latest tip version, using all.bash

#### What did you expect to see?

Rebuild everything and pass tests.

#### What did you see instead?

```go
ok  	cmd/internal/goobj	0.890s
ok  	cmd/internal/obj	0.006s
ok  	cmd/internal/obj/arm64	0.007s
ok  	cmd/internal/obj/x86	0.308s
ok  	cmd/internal/objabi	0.007s
ok  	cmd/internal/src	0.011s
ok  	cmd/internal/test2json	0.108s
ok  	cmd/link	2.034s
--- FAIL: TestAbstractOriginSanityWithLocationLists (14.24s)
	dwarf_test.go:97: build: # command-line-arguments
		panic: runtime error: index out of range
		
		goroutine 1 [running]:
		encoding/binary.littleEndian.Uint64(...)
			/Users/yoshiki/tools/go/src/encoding/binary/binary.go:76
		encoding/binary.(*littleEndian).Uint64(0x1313a00, 0xc000abd562, 0x1, 0x1, 0x0)
			<autogenerated>:1 +0x4c
		cmd/link/internal/ld.readPtr(0xc0004f4000, 0xc000abd562, 0x1, 0x1, 0x0)
			/Users/yoshiki/tools/go/src/cmd/link/internal/ld/dwarf.go:1843 +0x6e
		cmd/link/internal/ld.removeLocationListBaseAddress(0xc0004f4000, 0xc0006eecc8, 0xc0006eebd0)
			/Users/yoshiki/tools/go/src/cmd/link/internal/ld/dwarf.go:1807 +0xe5
		cmd/link/internal/ld.collectlocs(0xc0004f4000, 0xc00577a000, 0x3588, 0x3800, 0xc003536400, 0x58, 0x80, 0x3582, 0x5, 0x8)
			/Users/yoshiki/tools/go/src/cmd/link/internal/ld/dwarf.go:1764 +0x1fe
		cmd/link/internal/ld.dwarfgeneratedebugsyms(0xc0004f4000)
			/Users/yoshiki/tools/go/src/cmd/link/internal/ld/dwarf.go:1747 +0xcc3
		cmd/link/internal/ld.(*Link).dodata(0xc0004f4000)
			/Users/yoshiki/tools/go/src/cmd/link/internal/ld/data.go:1569 +0x3314
		cmd/link/internal/ld.Main(0x12eb320, 0x10, 0x20, 0x1, 0x7, 0x10, 0x11fc096, 0x1b, 0x11f9535, 0x14, ...)
			/Users/yoshiki/tools/go/src/cmd/link/internal/ld/main.go:224 +0xb5d
		main.main()
			/Users/yoshiki/tools/go/src/cmd/link/main.go:62 +0x271
		
	dwarf_test.go:98: build error: exit status 2
FAIL
FAIL	cmd/link/internal/ld	35.099s
```

#### System details

```
go version devel +a375a6b363 Tue Feb 27 23:26:36 2018 +0000 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/yoshiki/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/yoshiki/gocode"
GORACE=""
GOROOT="/Users/yoshiki/tools/go"
GOTMPDIR=""
GOTOOLDIR="/Users/yoshiki/tools/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/rk/f21ym6ks1ydfj0rf1kqt1ctc0000gn/T/go-build425577796=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version devel +a375a6b363 Tue Feb 27 23:26:36 2018 +0000 darwin/amd64
GOROOT/bin/go tool compile -V: compile version devel +a375a6b363 Tue Feb 27 23:26:36 2018 +0000
uname -v: Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.13.3
BuildVersion:	17D102
lldb --version: lldb-900.0.64
  Swift-4.0
```

**Comment by heschik** [comment]
Thanks for letting me know, and sorry for the trouble.
