### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by protheusfr** [golang/go#24218]
### What version of Go are you using (`go version`)?
`go version go1.10 linux/amd64`

### Does this issue reproduce with the latest release?
Yes, and it appear only on latest release, not present on version 1.9.4

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/lib/go.1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go.1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build313800813=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

The issue appear through the usage of Minio GoLang SDK (https://github.com/minio/minio) to upload encrypted file.
This appear almost randomly (not each time on the same file upload) and appear only when compiled with Go 1.10 (no issue with Go 1.9.4).

### What did you expect to see?
Nothing more than a confirmation of files uploading.

### What did you see instead?

```
panic: runtime error: slice bounds out of range

goroutine 933 [running]:
bytes.(*Buffer).grow(0xc420170bd0, 0x200, 0xc4200aa050)
	/usr/lib/go/src/bytes/buffer.go:139 +0x297
bytes.(*Buffer).ReadFrom(0xc420170bd0, 0xda10c0, 0xc420663460, 0x7f8b73181120, 0xc420170bd0, 0x1)
	/usr/lib/go/src/bytes/buffer.go:204 +0x48
io.copyBuffer(0xda0020, 0xc420170bd0, 0xda10c0, 0xc420663460, 0x0, 0x0, 0x0, 0xbe0aa0, 0x13, 0x18)
	/usr/lib/go/src/io/io.go:386 +0x31a
io.Copy(0xda0020, 0xc420170bd0, 0xda10c0, 0xc420663460, 0x10, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:362 +0x5a
io.CopyN(0xda0020, 0xc420170bd0, 0xda1720, 0xc4202e6000, 0x10, 0x10, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:338 +0x8b
xxx/xxx/vendor/github.com/minio/minio-go/pkg/encrypt.(*CBCSecureMaterials).Read(0xc420376480, 0xc445120000, 0x24000000, 0x24000000, 0xca40, 0x0, 0x0)
```

**Comment by ALTree** [comment]
If you run the thing to upload a file with the race detector enabled, does it print warnings?

**Comment by protheusfr** [comment]
Hello @ALTree ,

Not easy to enable race detector for me for two reasons : 
1/ the binary is packed in a Docker container without anything else (From Scratch), then CGO is not easy
2/ when I try to cross compile with `-race` I obtain the following error : 

```
env CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -race .
```

```
ld: warning: ignoring file race_linux_amd64.syso, file was built for unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): race_linux_amd64.syso
```

**Comment by bradfitz** [comment]
We'll probably need to close this bug as not reproducible and likely a data race, then.

**Comment by protheusfr** [comment]
@bradfitz I will you know if I found a way to provide a simple code to reproduce.
In the meantime we had revert to Go 1.9.4 (where the issue isn't present).

**Comment by bradfitz** [comment]
@protheusfr, if this is a race (which I suspect it is), then you're probably just getting lucky in Go 1.9 and it's not getting reported, but the race is still there.

See https://github.com/golang/go/issues/24091#issuecomment-368209375 for another user finding that the Go 1.10 bytes.Buffer code exposes a race in Go 1.0 that was invisible in Go 1.9.

I'm going to close this until there's evidence of a problem. Or feel free to file a new bug if you have a repro that passes with the race detector on.

**Comment by elvizlai** [comment]
maybe the same issue?
```
runtime error: slice bounds out of range
runtime.panicslice
	/usr/local/Cellar/go/1.10/libexec/src/runtime/panic.go:35
bufio.(*Reader).Read
	/usr/local/Cellar/go/1.10/libexec/src/bufio/bufio.go:227
project_path/vendor/git.apache.org/thrift.git/lib/go/thrift.(*TFramedTransport).Read
	/Users/elvizlai/GoLand/kg_rec/src/project_path/vendor/git.apache.org/thrift.git/lib/go/thrift/framed_transport.go:99
io.ReadAtLeast
	/usr/local/Cellar/go/1.10/libexec/src/io/io.go:309
io.ReadFull
	/usr/local/Cellar/go/1.10/libexec/src/io/io.go:327
project_path/vendor/git.apache.org/thrift.git/lib/go/thrift.(*TBinaryProtocol).readAll
	/Users/elvizlai/GoLand/kg_rec/src/project_path/vendor/git.apache.org/thrift.git/lib/go/thrift/binary_protocol.go:473
project_path/vendor/git.apache.org/thrift.git/lib/go/thrift.(*TBinaryProtocol).ReadI32
	/Users/elvizlai/GoLand/kg_rec/src/project_path/vendor/git.apache.org/thrift.git/lib/go/thrift/binary_protocol.go:410
project_path/vendor/git.apache.org/thrift.git/lib/go/thrift.(*TBinaryProtocol).ReadMessageBegin
	/Users/elvizlai/GoLand/kg_rec/src/project_path/vendor/git.apache.org/thrift.git/lib/go/thrift/binary_protocol.go:239
project_path/vendor/git.apache.org/thrift.git/lib/go/thrift.(*TStandardClient).Recv
	/Users/elvizlai/GoLand/kg_rec/src/project_path/vendor/git.apache.org/thrift.git/lib/go/thrift/client.go:33
project_path/vendor/git.apache.org/thrift.git/lib/go/thrift.(*TStandardClient).call
	/Users/elvizlai/GoLand/kg_rec/src/project_path/vendor/git.apache.org/thrift.git/lib/go/thrift/client.go:77
project_path/vendor/git.apache.org/thrift.git/lib/go/thrift.(*TStandardClient).Call
	/Users/elvizlai/GoLand/kg_rec/src/project_path/vendor/git.apache.org/thrift.git/lib/go/thrift/client_go17.go:12
```

**Comment by davecheney** [comment]
@elvizlai please raise a new issue. If you are able to provide a reproduction it would be extremely valuable.
