### ISSUE TITLE
cgo: getting `fatal: morestack on g0 SIGTRAP: trace trap` on darwin

### ISSUE THREAD

**Issue by jkuri** [golang/go#24603]
### What version of Go are you using (`go version`)?

```
go version go1.10 darwin/amd64
```

### Does this issue reproduce with the latest release?

`Yes`

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jan/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jan/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/jj/0sf645y54t18tltng8nknyt80000gn/T/go-build481622353=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?

I am trying to list video capture devices using C code and AVFoundation (Objective-C) via HTTP on Darwin. Similar code works very well on Linux.

I prepared repro repository [here](https://github.com/jkuri/golang-cam-repro).
Reproduction steps (Darwin):

```
go get -u -v github.com/jkuri/golang-cam-repro
go install golang-cam-repro
golang-cam-repro
```
Then open browser on `http://localhost:7350` to init the device list request.

Thing is if I don't trigger that via HTTP request I can `fmt.Println("%v", devices)` with no issues. 

### What did you expect to see?

I am expecting to see JSON output in the browser. 

### What did you see instead?

```
fatal: morestack on g0
SIGTRAP: trace trap
PC=0x40542a2 m=5 sigcode=1

goroutine 0 [idle]:
runtime.morestack()
        /usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:451 +0x22

goroutine 20 [syscall]:
runtime.cgocall(0x4220280, 0xc4205ae420, 0x0)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/cgocall.go:128 +0x64 fp=0xc4205ae3f0 sp=0xc4205ae3b8 pc=0x40040c4
github.com/jkuri/golang-cam-repro/device._Cfunc_get_video_devices(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        _cgo_gotypes.go:89 +0x59 fp=0xc4205ae420 sp=0xc4205ae3f0 pc=0x421f1c9
github.com/jkuri/golang-cam-repro/device.GetVideoDevices(0xc420128100, 0x1, 0x9)
        /Users/jan/go/src/github.com/jkuri/golang-cam-repro/device/device_darwin.go:12 +0x4d fp=0xc42076fc28 sp=0xc4205ae420 pc=0x421f22d
main.deviceListHandler(0x4312720, 0xc42015c0e0, 0xc420146000)
        /Users/jan/go/src/github.com/jkuri/golang-cam-repro/main.go:17 +0x34 fp=0xc42076fcf0 sp=0xc42076fc28 pc=0x421fed4
net/http.HandlerFunc.ServeHTTP(0x42ca610, 0x4312720, 0xc42015c0e0, 0xc420146000)
        /usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:1947 +0x44 fp=0xc42076fd18 sp=0xc42076fcf0 pc=0x41fa1c4
net/http.(*ServeMux).ServeHTTP(0x4455880, 0x4312720, 0xc42015c0e0, 0xc420146000)
        /usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:2337 +0x130 fp=0xc42076fd58 sp=0xc42076fd18 pc=0x41fbe30
net/http.serverHandler.ServeHTTP(0xc4200a0dd0, 0x4312720, 0xc42015c0e0, 0xc420146000)
        /usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:2694 +0xbc fp=0xc42076fd88 sp=0xc42076fd58 pc=0x41fc93c
net/http.(*conn).serve(0xc4200b48c0, 0x4312920, 0xc4200aa200)
        /usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:1830 +0x651 fp=0xc42076ffc8 sp=0xc42076fd88 pc=0x41f93d1
runtime.goexit()
        /usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc42076ffd0 sp=0xc42076ffc8 pc=0x4056d11
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:2795 +0x27b

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x45befe8, 0x72, 0x0)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420128018, 0x72, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.10/libexec/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc420128018, 0xffffffffffffff00, 0x0, 0x0)
        /usr/local/Cellar/go/1.10/libexec/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc420128000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.10/libexec/src/internal/poll/fd_unix.go:372 +0x1a8
net.(*netFD).accept(0xc420128000, 0xc42014a120, 0xc420065da8, 0x4003f98)
        /usr/local/Cellar/go/1.10/libexec/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc4200b0020, 0xc420065dd8, 0x4002ef7, 0xc42014a120)
        /usr/local/Cellar/go/1.10/libexec/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).AcceptTCP(0xc4200b0020, 0xc420065e20, 0xc420065e28, 0x18)
        /usr/local/Cellar/go/1.10/libexec/src/net/tcpsock.go:246 +0x49
net/http.tcpKeepAliveListener.Accept(0xc4200b0020, 0x42ca7a8, 0xc42014a0a0, 0x43129e0, 0xc420096db0)
        /usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:3216 +0x2f
net/http.(*Server).Serve(0xc4200a0dd0, 0x4312860, 0xc4200b0020, 0x0, 0x0)
        /usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:2770 +0x1a5
net/http.(*Server).ListenAndServe(0xc4200a0dd0, 0xc4200a0dd0, 0x42ca610)
        /usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:2711 +0xa9
net/http.ListenAndServe(0x42b74f4, 0x5, 0x0, 0x0, 0xc420065f78, 0xc42008a058)
        /usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:2969 +0x7a
main.main()
        /Users/jan/go/src/github.com/jkuri/golang-cam-repro/main.go:27 +0x67

goroutine 19 [syscall]:
github.com/jkuri/golang-cam-repro/device._Cfunc_get_video_devices(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        _cgo_gotypes.go:89 +0x59
github.com/jkuri/golang-cam-repro/device.GetVideoDevices(0xc420128080, 0x1, 0x9)
        /Users/jan/go/src/github.com/jkuri/golang-cam-repro/device/device_darwin.go:12 +0x4d
main.deviceListHandler(0x4312720, 0xc42015c000, 0xc420144000)
        /Users/jan/go/src/github.com/jkuri/golang-cam-repro/main.go:17 +0x34
net/http.HandlerFunc.ServeHTTP(0x42ca610, 0x4312720, 0xc42015c000, 0xc420144000)
        /usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:1947 +0x44
net/http.(*ServeMux).ServeHTTP(0x4455880, 0x4312720, 0xc42015c000, 0xc420144000)
        /usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:2337 +0x130
net/http.serverHandler.ServeHTTP(0xc4200a0dd0, 0x4312720, 0xc42015c000, 0xc420144000)
        /usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc4200b4820, 0x4312920, 0xc420138040)
        /usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:2795 +0x27b

goroutine 35 [IO wait]:
internal/poll.runtime_pollWait(0x45bed78, 0x72, 0xc420050868)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420148098, 0x72, 0xffffffffffffff00, 0x4310860, 0x441f528)
        /usr/local/Cellar/go/1.10/libexec/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc420148098, 0xc420566000, 0x1000, 0x1000)
        /usr/local/Cellar/go/1.10/libexec/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420148080, 0xc420566000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.10/libexec/src/internal/poll/fd_unix.go:157 +0x1dc
net.(*netFD).Read(0xc420148080, 0xc420566000, 0x1000, 0x1000, 0xc420050978, 0x41f3c5b, 0x428e3e0)
        /usr/local/Cellar/go/1.10/libexec/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc420564000, 0xc420566000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.10/libexec/src/net/net.go:176 +0x6a
net/http.(*connReader).Read(0xc420136210, 0xc420566000, 0x1000, 0x1000, 0xa, 0x0, 0xa)
        /usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:764 +0xf8
bufio.(*Reader).fill(0xc42013e060)
        /usr/local/Cellar/go/1.10/libexec/src/bufio/bufio.go:100 +0x11e
bufio.(*Reader).ReadSlice(0xc42013e060, 0xc420050a0a, 0x4044847, 0x0, 0xc420050ad0, 0x409a6dd, 0xc420050ac0)
        /usr/local/Cellar/go/1.10/libexec/src/bufio/bufio.go:341 +0x2c
bufio.(*Reader).ReadLine(0xc42013e060, 0xc420144100, 0x100, 0xf8, 0x42ad160, 0x42ca5d8, 0xc420050b58)
        /usr/local/Cellar/go/1.10/libexec/src/bufio/bufio.go:370 +0x34
net/textproto.(*Reader).readLineSlice(0xc420136090, 0xc420073100, 0xc420050ba8, 0x4012ef8, 0x100, 0x42ad160)
        /usr/local/Cellar/go/1.10/libexec/src/net/textproto/reader.go:55 +0x70
net/textproto.(*Reader).ReadLine(0xc420136090, 0xc420144100, 0x0, 0x0, 0x72)
        /usr/local/Cellar/go/1.10/libexec/src/net/textproto/reader.go:36 +0x2b
net/http.readRequest(0xc42013e060, 0x0, 0xc420144100, 0x0, 0x0)
        /usr/local/Cellar/go/1.10/libexec/src/net/http/request.go:929 +0x8c
net/http.(*conn).readRequest(0xc42014a0a0, 0x4312920, 0xc4201381c0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:944 +0x16f
net/http.(*conn).serve(0xc42014a0a0, 0x4312920, 0xc4201381c0)
        /usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:1768 +0x4dc
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:2795 +0x27b

goroutine 36 [IO wait]:
internal/poll.runtime_pollWait(0x45bee48, 0x72, 0xc42003ee58)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420128118, 0x72, 0xffffffffffffff00, 0x4310860, 0x441f528)
        /usr/local/Cellar/go/1.10/libexec/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc420128118, 0xc420096f00, 0x1, 0x1)
        /usr/local/Cellar/go/1.10/libexec/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420128100, 0xc420096f41, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.10/libexec/src/internal/poll/fd_unix.go:157 +0x1dc
net.(*netFD).Read(0xc420128100, 0xc420096f41, 0x1, 0x1, 0x430d9f8, 0x42a4580, 0xc42015c000)
        /usr/local/Cellar/go/1.10/libexec/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc4200b0038, 0xc420096f41, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.10/libexec/src/net/net.go:176 +0x6a
net/http.(*connReader).backgroundRead(0xc420096f30)
        /usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:668 +0x5a
created by net/http.(*connReader).startBackgroundRead
        /usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:664 +0xce

rax    0x17
rbx    0xc420046c00
rcx    0x4057d15
rdx    0x0
rdi    0x2
rsi    0x42bbf02
rbp    0x70000e402080
rsp    0x70000e402070
r8     0x10
r9     0x0
r10    0x7ffeefbffa40
r11    0x202
r12    0xc3
r13    0x2
r14    0x70000e495031
r15    0x11e8
rip    0x40542a2
rflags 0x202
cs     0x2b
fs     0x0
gs     0x0
```

**Comment by jkuri** [comment]
I was able to solve the issue with https://github.com/faiface/mainthread. Thanks anyway,
