### ISSUE TITLE
x/crypto/ssh: TestMuxReadWrite flake

### ISSUE THREAD

**Issue by bradfitz** [golang/go#24612]
Flake on trybot run at https://storage.googleapis.com/go-build-log/4468b0ba/windows-386-2008_b5f0b931.log ...

```
panic: Fail in goroutine after TestMuxReadWrite has completed

goroutine 1387 [running]:
testing.(*common).Fail(0x12841200)
	C:/workdir/go/src/testing/testing.go:512 +0xf8
testing.(*common).FailNow(0x12841200)
	C:/workdir/go/src/testing/testing.go:534 +0x21
testing.(*common).Fatalf(0x12841200, 0x6ce724, 0x9, 0x12cf5fbc, 0x1, 0x1)
	C:/workdir/go/src/testing/testing.go:600 +0x69
golang.org/x/crypto/ssh.TestMuxReadWrite.func1(0x12a7a400, 0x6cf433, 0xb, 0x12841200, 0x6cfa12, 0xc)
	C:/workdir/gopath/src/golang.org/x/crypto/ssh/mux_test.go:113 +0x1e8
created by golang.org/x/crypto/ssh.TestMuxReadWrite
	C:/workdir/gopath/src/golang.org/x/crypto/ssh/mux_test.go:102 +0x102
FAIL	golang.org/x/crypto/ssh	3.991s
```

/cc @hanwen

**Comment by hanwen** [comment]
fixed by https://github.com/golang/crypto/commit/b2aa35443fbc700ab74c586ae79b81c171851023
