### ISSUE TITLE
Is there anyway to get go code in core file?

### ISSUE THREAD

**Issue by YuleiXiao** [golang/go#24681]
The code encapsulates the etcd client, providing an interface to mysql. But sometime it panic. I can not get useful information from stack in core file. Is there anyway to know where it panic or variable in go code?

### What version of Go are you using (`go version`)?
go version go1.10 linux/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/xiaoyulei/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/mnt/hdd1/work/Rainbow"
GORACE=""
GOROOT="/mnt/hdd1/tools/go"
GOTMPDIR=""
GOTOOLDIR="/mnt/hdd1/tools/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build279231519=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?
The code encapsulates the etcdv3 client, providing an interface to mysql. But sometime it panic.

### What did you expect to see?
no panic

### What did you see instead?
```
gdb) where
#0 0x00007fd0ec57e741 in __pthread_kill (threadid=<optimized out>, signo=6) at ../nptl/sysdeps/unix/sysv/linux/pthread_kill.c:61
#1 0x00000000007c9d35 in handle_fatal_signal (sig=6) at /home/ci/jenkins/workspace/c/r/src/github.com/s/p/database/sql/signal_handler.cc:220
#2 <signal handler called>
#3 runtime.raise () at /home/ci/jenkins/go/src/runtime/sys_linux_amd64.s:155
#4 0x00007fd0ed9e9b4b in runtime.dieFromSignal (sig=6) at /home/ci/jenkins/go/src/runtime/signal_unix.go:422
#5 0x00007fd0ed9e9d1b in runtime.crash () at /home/ci/jenkins/go/src/runtime/signal_unix.go:520
#6 0x00007fd0ed9d54d8 in runtime.dopanic_m (gp=0xc42052a600, pc=140535316434723, sp=140509332706336) at /home/ci/jenkins/go/src/runtime/panic.go:754
#7 0x00007fd0ed9fd43e in runtime.dopanic.func1 () at /home/ci/jenkins/go/src/runtime/panic.go:601
#8 0x00007fd0ed9d4e4c in runtime.dopanic (unused=0) at /home/ci/jenkins/go/src/runtime/panic.go:600
#9 0x00007fd0ed9d4f23 in runtime.throw (s=...) at /home/ci/jenkins/go/src/runtime/panic.go:619
#10 0x00007fd0ed9f6af7 in runtime.gentraceback (callback={void (struct runtime.stkframe *, void *, bool *)} 0x7fcae0dd1790, flags=0, gp=0xc420000f00, lr0=0, max=2147483647, pc0=18446744073709551615, pcbuf=0x0, skip=0, sp0=18446744073709551615, v=0x0, ~r10=0)
at /home/ci/jenkins/go/src/runtime/traceback.go:302
#11 0x00007fd0ed9c747f in runtime.scanstack (gcw=0xc420038170, gp=0xc420000f00) at /home/ci/jenkins/go/src/runtime/mgcmark.go:786
#12 0x00007fd0ed9d8ba8 in runtime.scang (gcw=0xc420038170, gp=0xc420000f00) at /home/ci/jenkins/go/src/runtime/proc.go:888
#13 0x00007fd0ed9fc681 in runtime.markroot.func1 () at /home/ci/jenkins/go/src/runtime/mgcmark.go:264
#14 0x00007fd0ed9c6488 in runtime.markroot (gcw=0xc420038170, i=8) at /home/ci/jenkins/go/src/runtime/mgcmark.go:245
#15 0x00007fd0ed9c7f75 in runtime.gcDrain (flags=13, gcw=0xc420038170) at /home/ci/jenkins/go/src/runtime/mgcmark.go:934
#16 0x00007fd0ed9fc5c9 in runtime.gcBgMarkWorker.func2 () at /home/ci/jenkins/go/src/runtime/mgc.go:1865
#17 0x00007fd0ed9fe972 in runtime.systemstack () at /home/ci/jenkins/go/src/runtime/asm_amd64.s:409
#18 0x00007fd0ed9d95d0 in ?? () at /home/ci/jenkins/go/src/runtime/proc.go:1087 from /home/zqt/install/dep/cetcdv3/lib/libwrapper.so
#19 0x0000000000000000 in ?? ()
```

**Comment by mvdan** [comment]
I don't understand this issue. What do you mean by "core file"? Do you mean a core dump file?

Have you looked at the panic that the Go runtime gives you? It should contain a stack trace to help you debug the issue.

**Comment by bcmills** [comment]
We don't use the Go issue tracker for general questions.

Please start a thread on [golang-nuts](https://groups.google.com/forum/#!forum/golang-nuts), or see https://golang.org/wiki/Questions for other venues.
