### ISSUE TITLE
cmd/go: test timeout on netbsd/arm

### ISSUE THREAD

**Issue by bsiegert** [golang/go#24774]
The tests for cmd/go keep timing out (after 6 minutes) on the netbsd-arm builder. Not sure if they are just slow, or indicating a synchronization problem of some sort.

Here is a typical log from a recent build:

```
panic: test timed out after 6m0s

goroutine 396 [running]:
testing.(*M).startAlarm.func1()
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:1258 +0xcc
created by time.goFunc
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/time/sleep.go:172 +0x34

goroutine 1 [runnable]:
testing.(*T).Run(0x87ccf0, 0x478b6f, 0xe, 0x4aeeb4, 0x9b0001)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:839 +0x260
testing.runTests.func1(0x9c4000)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:1081 +0x50
testing.tRunner(0x9c4000, 0x851da4)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:791 +0xac
testing.runTests(0x9c0000, 0x6c3d88, 0x110, 0x110, 0x7)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:1079 +0x21c
testing.(*M).Run(0x96a300, 0x0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:996 +0x134
cmd/go_test.TestMain(0x96a300)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:204 +0x148
main.main()
	_testmain.go:584 +0x12c

goroutine 5 [syscall, 3 minutes]:
os/signal.signal_recv(0x0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/runtime/sigqueue.go:139 +0x130
os/signal.loop()
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/os/signal/signal_unix.go:22 +0x14
created by os/signal.init.0
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/os/signal/signal_unix.go:28 +0x30

goroutine 35 [chan receive, 3 minutes]:
testing.(*T).Parallel(0x9c4090)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:700 +0x180
cmd/go_test.(*testgoData).parallel(0x9c8000)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:285 +0x2cc
cmd/go_test.TestBuildComplex(0x9c4090)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:782 +0x50
testing.tRunner(0x9c4090, 0x4aec50)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:791 +0xac
created by testing.(*T).Run
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:838 +0x240

goroutine 157 [chan receive, 3 minutes]:
testing.(*T).Parallel(0xa5a750)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:700 +0x180
cmd/go_test.(*testgoData).parallel(0xc602a0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:285 +0x2cc
cmd/go_test.TestNonCanonicalImportPaths(0xa5a750)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:1533 +0x50
testing.tRunner(0xa5a750, 0x4aef60)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:791 +0xac
created by testing.(*T).Run
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:838 +0x240

goroutine 36 [chan receive, 3 minutes]:
testing.(*T).Parallel(0x9c4120)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:700 +0x180
cmd/go_test.(*testgoData).parallel(0x9c81c0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:285 +0x2cc
cmd/go_test.TestFileLineInErrorMessages(0x9c4120)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:795 +0x50
testing.tRunner(0x9c4120, 0x4aed00)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:791 +0xac
created by testing.(*T).Run
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:838 +0x240

goroutine 37 [chan receive, 3 minutes]:
testing.(*T).Parallel(0x9c41b0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:700 +0x180
cmd/go_test.(*testgoData).parallel(0x9c8380)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:285 +0x2cc
cmd/go_test.TestProgramNameInCrashMessages(0x9c41b0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:809 +0x50
testing.tRunner(0x9c41b0, 0x4aef80)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:791 +0xac
created by testing.(*T).Run
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:838 +0x240

goroutine 47 [chan receive, 3 minutes]:
testing.(*T).Parallel(0x9c4990)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:700 +0x180
cmd/go_test.(*testgoData).parallel(0x9c88c0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:285 +0x2cc
cmd/go_test.TestGoInstallDetectsRemovedFiles(0x9c4990)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:1030 +0x50
testing.tRunner(0x9c4990, 0x4aedb0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:791 +0xac
created by testing.(*T).Run
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:838 +0x240

goroutine 118 [chan receive, 3 minutes]:
testing.(*T).Parallel(0x87cc60)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:700 +0x180
cmd/go_test.(*testgoData).parallel(0xbd87e0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:285 +0x2cc
cmd/go_test.TestImportCycle(0x87cc60)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:1365 +0x50
testing.tRunner(0x87cc60, 0x4aee64)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:791 +0xac
created by testing.(*T).Run
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:838 +0x240

goroutine 189 [chan receive, 3 minutes]:
testing.(*T).Parallel(0x87c7e0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:700 +0x180
cmd/go_test.(*testgoData).parallel(0x9c9420)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:285 +0x2cc
cmd/go_test.TestDefaultGOPATH(0x87c7e0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:1977 +0x50
testing.tRunner(0x87c7e0, 0x4aecd8)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:791 +0xac
created by testing.(*T).Run
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:838 +0x240

goroutine 387 [chan receive]:
testing.(*T).Parallel(0x9c43f0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:700 +0x180
cmd/go_test.(*testgoData).parallel(0xbd80e0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:285 +0x2cc
cmd/go_test.TestGoGenerateXTestPkgName(0x9c43f0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:3189 +0x50
testing.tRunner(0x9c43f0, 0x4aed64)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:791 +0xac
created by testing.(*T).Run
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:838 +0x240

goroutine 271 [chan receive, 3 minutes]:
testing.(*T).Parallel(0x87cb40)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:700 +0x180
cmd/go_test.(*testgoData).parallel(0xc60380)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:285 +0x2cc
cmd/go_test.TestCaseCollisions(0x87cb40)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:2298 +0x50
testing.tRunner(0x87cb40, 0x4aec74)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:791 +0xac
created by testing.(*T).Run
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:838 +0x240

goroutine 179 [chan receive, 3 minutes]:
testing.(*T).Parallel(0x87c1b0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:700 +0x180
cmd/go_test.(*testgoData).parallel(0x9c8540)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:285 +0x2cc
cmd/go_test.TestPackageMainTestCompilerFlags(0x87c1b0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:1634 +0x50
testing.tRunner(0x87c1b0, 0x4aef68)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:791 +0xac
created by testing.(*T).Run
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:838 +0x240

goroutine 185 [chan receive, 3 minutes]:
testing.(*T).Parallel(0x87c510)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:700 +0x180
cmd/go_test.(*testgoData).parallel(0x9c8ee0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:285 +0x2cc
cmd/go_test.TestGOROOTSearchFailureReporting(0x87c510)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:1918 +0x50
testing.tRunner(0x87c510, 0x4aed0c)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:791 +0xac
created by testing.(*T).Run
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:838 +0x240

goroutine 407 [chan receive]:
testing.(*T).Parallel(0xa5ac60)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:700 +0x180
cmd/go_test.(*testgoData).parallel(0x8609a0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:285 +0x2cc
cmd/go_test.TestVetWithOnlyCgoFiles(0xa5ac60)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:3287 +0x60
testing.tRunner(0xa5ac60, 0x4af044)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:791 +0xac
created by testing.(*T).Run
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:838 +0x240

goroutine 187 [chan receive, 3 minutes]:
testing.(*T).Parallel(0x87c630)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:700 +0x180
cmd/go_test.(*testgoData).parallel(0x9c9180)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:285 +0x2cc
cmd/go_test.TestMentionGOPATHInFirstGOPATHEntry(0x87c630)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:1941 +0x54
testing.tRunner(0x87c630, 0x4aef38)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:791 +0xac
created by testing.(*T).Run
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:838 +0x240

goroutine 406 [chan receive]:
testing.(*T).Parallel(0xa5abd0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:700 +0x180
cmd/go_test.(*testgoData).parallel(0x8608c0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:285 +0x2cc
cmd/go_test.TestGoVetWithOnlyTestFiles(0xa5abd0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:3273 +0x50
testing.tRunner(0xa5abd0, 0x4aee48)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:791 +0xac
created by testing.(*T).Run
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:838 +0x240

goroutine 186 [chan receive, 3 minutes]:
testing.(*T).Parallel(0x87c5a0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:700 +0x180
cmd/go_test.(*testgoData).parallel(0x9c90a0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:285 +0x2cc
cmd/go_test.TestMultipleGOPATHEntriesReportedSeparately(0x87c5a0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:1928 +0x50
testing.tRunner(0x87c5a0, 0x4aef48)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:791 +0xac
created by testing.(*T).Run
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:838 +0x240

goroutine 188 [chan receive, 3 minutes]:
testing.(*T).Parallel(0x87c750)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:700 +0x180
cmd/go_test.(*testgoData).parallel(0x9c9340)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:285 +0x2cc
cmd/go_test.TestMentionGOPATHNotOnSecondEntry(0x87c750)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:1954 +0x54
testing.tRunner(0x87c750, 0x4aef3c)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:791 +0xac
created by testing.(*T).Run
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:838 +0x240

goroutine 183 [chan receive, 3 minutes]:
testing.(*T).Parallel(0x87c2d0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:700 +0x180
cmd/go_test.(*testgoData).parallel(0x9c8a80)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:285 +0x2cc
cmd/go_test.TestGoListDeps(0x87c2d0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:1893 +0x50
testing.tRunner(0x87c2d0, 0x4aedcc)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:791 +0xac
created by testing.(*T).Run
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:838 +0x240

goroutine 184 [chan receive, 3 minutes]:
testing.(*T).Parallel(0x87c480)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:700 +0x180
cmd/go_test.(*testgoData).parallel(0x9c8d20)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:285 +0x2cc
cmd/go_test.TestUnsuccessfulGoInstallShouldMentionMissingPackage(0x87c480)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:1908 +0x50
testing.tRunner(0x87c480, 0x4aefec)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:791 +0xac
created by testing.(*T).Run
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:838 +0x240

goroutine 307 [chan receive, 3 minutes]:
testing.(*T).Parallel(0xc5ccf0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:700 +0x180
cmd/go_test.(*testgoData).parallel(0x9e5b20)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:285 +0x2cc
cmd/go_test.TestCoverageDashC(0xc5ccf0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:2629 +0x50
testing.tRunner(0xc5ccf0, 0x4aec98)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:791 +0xac
created by testing.(*T).Run
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:838 +0x240

goroutine 272 [chan receive, 3 minutes]:
testing.(*T).Parallel(0x87cbd0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:700 +0x180
cmd/go_test.(*testgoData).parallel(0xc60460)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:285 +0x2cc
cmd/go_test.TestSymlinkWarning(0x87cbd0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:2344 +0x50
testing.tRunner(0x87cbd0, 0x4aefb4)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:791 +0xac
created by testing.(*T).Run
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:838 +0x240

goroutine 295 [chan receive, 3 minutes]:
testing.(*T).Parallel(0xc5c6c0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:700 +0x180
cmd/go_test.(*testgoData).parallel(0x9e5500)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:285 +0x2cc
cmd/go_test.TestCoverageDotImport(0xc5c6c0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:2466 +0x50
testing.tRunner(0xc5c6c0, 0x4aeca0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:791 +0xac
created by testing.(*T).Run
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:838 +0x240

goroutine 256 [chan receive, 3 minutes]:
testing.(*T).Parallel(0xa5a7e0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:700 +0x180
cmd/go_test.(*testgoData).parallel(0x860fc0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:285 +0x2cc
cmd/go_test.TestCgoAsmError(0xa5a7e0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:2759 +0x3c
testing.tRunner(0xa5a7e0, 0x4aec78)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:791 +0xac
created by testing.(*T).Run
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:838 +0x240

goroutine 386 [chan receive]:
testing.(*T).Parallel(0x9c4360)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:700 +0x180
cmd/go_test.(*testgoData).parallel(0xbd8000)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:285 +0x2cc
cmd/go_test.TestGoGenerateEnv(0x9c4360)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:3174 +0x50
testing.tRunner(0x9c4360, 0x4aed50)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:791 +0xac
created by testing.(*T).Run
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:838 +0x240

goroutine 343 [chan receive, 3 minutes]:
testing.(*T).Parallel(0xa5acf0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:700 +0x180
cmd/go_test.TestListTemplateContextFunction(0xa5acf0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:2960 +0x20
testing.tRunner(0xa5acf0, 0x4aeeec)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:791 +0xac
created by testing.(*T).Run
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:838 +0x240

goroutine 338 [chan receive, 3 minutes]:
testing.(*T).Parallel(0xa5aa20)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:700 +0x180
cmd/go_test.(*testgoData).parallel(0x8610a0)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:285 +0x2cc
cmd/go_test.TestCgoShowsFullPathNames(0xa5aa20)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/cmd/go/go_test.go:2799 +0x60
testing.tRunner(0xa5aa20, 0x4aec90)
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:791 +0xac
created by testing.(*T).Run
	/tmp/gobuilder/netbsd-arm-bsiegert-8818b4d27e3a/go/src/testing/testing.go:838 +0x240
FAIL	cmd/go	402.915s
```

/cc @tklauser @bradfitz

**Comment by mvdan** [comment]
There's also #24591 for the recent spike of timeout issues on multiple builders and test. I imagine that the issues are different, since that involves `os/exec` and running child programs. However, the two might still be connected somehow.

**Comment by bcmills** [comment]
The `cmd/go` tests are slow in general; see #26472. I'm surprised they're that slow, though.

They do still seem to time out: https://build.golang.org/log/f397d8329c98f733558168f03017f9e0589f927a is a recent example.

**Comment by bcmills** [comment]
Wait, that's amd64, not arm!

**Comment by bcmills** [comment]
The `netbsd/arm` builder does not seem to be running at all these days.
(https://build.golang.org/log/87db19de070f7114fd0290bced5fea769e0a7989)

CC @bsiegert

**Comment by bcmills** [comment]
@bsiegert, are these tests still timing out? Is there some way for us to reproduce these failures?

**Comment by bsiegert** [comment]
The builder is on my desk at work, I'll reboot it on Monday.

I assume NetBSD/arm runs in qemu, though I haven't tested. Unfortunately, Scaleway VMs do not run 32-bit code so they cannot be used to test this.

**Comment by bsiegert** [comment]
Rebooted and cleaned up the state of its git repo, which is what had been causing these `exit status 128` errors.

I'll need to take the machine offline for a bit later today but I'll let it run some builds in the meantime. I also remounted its filesystem with `-o async`  to help with performance.

**Comment by bsiegert** [comment]
And it looks like it's just slowness: 

```
ok  	cmd/go	814.936s
```

https://build.golang.org/log/2f7edd8edfffbb73680af3f141ac3497c9cc1181
