### ISSUE TITLE
runtime: SIGSEGV from runtime.(*timersBucket).addtimerLocked on darwin/arm64

### ISSUE THREAD

**Issue by eliasnaur** [golang/go#24790]
````
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x100a649bc]



goroutine 7 [running]:

runtime.throw(0x100b7e2be, 0x2a)

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/runtime/panic.go:598 +0x4c fp=0x1300346d0 sp=0x1300346a0 pc=0x100a49a0c

runtime.sigpanic()

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/runtime/signal_unix.go:372 +0x23c fp=0x130034720 sp=0x1300346d0 pc=0x100a5d33c

runtime.lock(0x0)

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/runtime/lock_sema.go:43 +0x34 fp=0x130034760 sp=0x130034730 pc=0x100a2a514

runtime.timerproc(0x0)

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/runtime/time.go:208 +0x22c fp=0x1300347d0 sp=0x130034760 pc=0x100a649bc

runtime.goexit()

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/runtime/asm_arm64.s:1089 +0x4 fp=0x1300347d0 sp=0x1300347d0 pc=0x100a72374

created by runtime.(*timersBucket).addtimerLocked

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/runtime/time.go:160 +0xe4



goroutine 1 [chan receive]:

testing.(*T).Run(0x1300bc0f0, 0x100b77966, 0xc, 0x100b80458, 0x5acc65d5)

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/testing/testing.go:839 +0x248

testing.runTests.func1(0x1300bc000)

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/testing/testing.go:1081 +0x54

testing.tRunner(0x1300bc000, 0x130055df0)

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/testing/testing.go:791 +0xa8

testing.runTests(0x1300881c0, 0x100c47ed0, 0x1, 0x1, 0x1300ba0a8)

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/testing/testing.go:1079 +0x248

testing.(*M).Run(0x1300ba100, 0x0)

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/testing/testing.go:996 +0x148

main.main()

	_testmain.go:42 +0x148



goroutine 20 [chan receive]:

testing.(*T).Run(0x1300bc1e0, 0x100b7628e, 0x3, 0x13007c6f0, 0x5acc65d5)

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/testing/testing.go:839 +0x248

vendor/golang_org/x/net/nettest.TestTestConn(0x1300bc0f0)

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/vendor/golang_org/x/net/nettest/conntest_test.go:26 +0xa0

testing.tRunner(0x1300bc0f0, 0x100b80458)

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/testing/testing.go:791 +0xa8

created by testing.(*T).Run

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/testing/testing.go:838 +0x22c



goroutine 21 [chan receive]:

testing.(*T).Run(0x1300bc870, 0x100b77f3f, 0xe, 0x13007c9a0, 0x1)

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/testing/testing.go:839 +0x248

vendor/golang_org/x/net/nettest.testConn(0x1300bc1e0, 0x13007c720)

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/vendor/golang_org/x/net/nettest/conntest_go17.go:20 +0x2f4

vendor/golang_org/x/net/nettest.TestConn(0x1300bc1e0, 0x13007c720)

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/vendor/golang_org/x/net/nettest/conntest.go:38 +0x28

vendor/golang_org/x/net/nettest.TestTestConn.func1(0x1300bc1e0)

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/vendor/golang_org/x/net/nettest/conntest_test.go:73 +0xac

testing.tRunner(0x1300bc1e0, 0x13007c6f0)

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/testing/testing.go:791 +0xa8

created by testing.(*T).Run

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/testing/testing.go:838 +0x22c



goroutine 69 [semacquire]:

sync.runtime_Semacquire(0x130086628)

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/runtime/sema.go:56 +0x2c

sync.(*WaitGroup).Wait(0x130086620)

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/sync/waitgroup.go:130 +0x64

vendor/golang_org/x/net/nettest.testPresentTimeout(0x1300bc870, 0x100b94d40, 0x13000e040, 0x100b94d40, 0x1300920a0)

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/vendor/golang_org/x/net/nettest/conntest.go:279 +0x13c

vendor/golang_org/x/net/nettest.timeoutWrapper(0x1300bc870, 0x13007c720, 0x100b80528)

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/vendor/golang_org/x/net/nettest/conntest.go:57 +0x1a4

vendor/golang_org/x/net/nettest.testConn.func8(0x1300bc870)

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/vendor/golang_org/x/net/nettest/conntest_go17.go:20 +0x34

testing.tRunner(0x1300bc870, 0x13007c9a0)

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/testing/testing.go:791 +0xa8

created by testing.(*T).Run

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/testing/testing.go:838 +0x22c



goroutine 71 [sleep]:

time.Sleep(0x5f5e100)

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/runtime/time.go:102 +0x118

vendor/golang_org/x/net/nettest.testPresentTimeout.func1(0x130086620, 0x13001a070, 0x100b94d40, 0x13000e040)

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/vendor/golang_org/x/net/nettest/conntest.go:252 +0x48

created by vendor/golang_org/x/net/nettest.testPresentTimeout

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/vendor/golang_org/x/net/nettest/conntest.go:250 +0xb8



goroutine 72 [runnable]:

vendor/golang_org/x/net/nettest.testPresentTimeout.func2(0x130086620, 0x100b94d40, 0x13000e040, 0x1300bc870, 0x13001a070)

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/vendor/golang_org/x/net/nettest/conntest.go:257

created by vendor/golang_org/x/net/nettest.testPresentTimeout

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/vendor/golang_org/x/net/nettest/conntest.go:257 +0xf8



goroutine 73 [runnable]:

syscall.Syscall(0x4, 0x5, 0x1301e8800, 0x400, 0x400, 0x0, 0x0)

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/syscall/asm_darwin_arm64.s:13 +0x8

syscall.write(0x5, 0x1301e8800, 0x400, 0x400, 0x1300bad00, 0x0, 0x0)

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/syscall/zsyscall_darwin_arm64.go:1321 +0x48

syscall.Write(0x5, 0x1301e8800, 0x400, 0x400, 0x400, 0x0, 0x0)

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/syscall/syscall_unix.go:191 +0x38

internal/poll.(*FD).Write(0x1300bad80, 0x1301e8800, 0x400, 0x400, 0x0, 0x0, 0x0)

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/internal/poll/fd_unix.go:262 +0x118

net.(*netFD).Write(0x1300bad80, 0x1301e8800, 0x400, 0x400, 0x400, 0x100b28fd4, 0x400)

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/net/fd_unix.go:220 +0x3c

net.(*conn).Write(0x13000e040, 0x1301e8800, 0x400, 0x400, 0x0, 0x0, 0x0)

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/net/net.go:188 +0x50

vendor/golang_org/x/net/nettest.testPresentTimeout.func3(0x130086620, 0x100b94d40, 0x13000e040, 0x1300bc870, 0x13001a070)

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/vendor/golang_org/x/net/nettest/conntest.go:272 +0x90

created by vendor/golang_org/x/net/nettest.testPresentTimeout

	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-ios/go/src/vendor/golang_org/x/net/nettest/conntest.go:268 +0x138

Process 690 exited with status = 2 (0x00000002) 
go_darwin_arm_exec: test timeout (test completion)
FAIL	vendor/golang_org/x/net/nettest	385.939s
````

From the builder https://build.golang.org/log/2447525d04850cf62fc23eae4c5f7d2e003a2cfc.

**Comment by eliasnaur** [comment]
Another: https://build.golang.org/log/6fba185086de5d7f290fbe607d78cb2427c3d930

Also darwin/arm64.

**Comment by ianlancetaylor** [comment]
There are many examples of this.  It seems to consistently happen when testing the vendored nettest package.  CC @mikioh .  On the other hand, it hasn't happened since April.

[2018-04-04T22:11:34-619679a/darwin-arm64-a1549ios](https://build.golang.org/log/c31a9d3cbba255c74c3a2cf00fb7e499c7bc6b33)
[2018-04-05T07:41:56-9357bb9/darwin-arm64-a1549ios](https://build.golang.org/log/fc07404091474e60fc59b0247f700358c85b09a3)
[2018-04-05T22:01:17-638f112/darwin-arm64-a1549ios](https://build.golang.org/log/5532edfb12052db5fe38600e03b2dab85ffb568d)
[2018-04-09T18:40:55-17df5ed/darwin-arm64-a1549ios](https://build.golang.org/log/fa75fe6b53ff8aa668fbf95e58fca7d311c4716a)
[2018-04-09T19:28:23-568d484/darwin-arm64-a1549ios](https://build.golang.org/log/2447525d04850cf62fc23eae4c5f7d2e003a2cfc)
[2018-04-10T15:25:31-60fee01/darwin-arm64-a1549ios](https://build.golang.org/log/1aad69db41072dc71bb0ac1f44bf8f87f497ed91)
[2018-04-10T18:27:10-c4a3a9c/darwin-arm64-a1549ios](https://build.golang.org/log/9f8e2489bc6650f86aa81143ef91ad835be002b3)
[2018-04-12T19:30:54-299b40b/darwin-arm64-a1549ios](https://build.golang.org/log/9a9b622af7fe8c48db05daf3e8ac88b80858dd73)
[2018-04-12T20:00:25-191efbc/darwin-arm64-a1549ios](https://build.golang.org/log/6fba185086de5d7f290fbe607d78cb2427c3d930)
[2018-04-13T16:18:30-1d8fc21/darwin-arm64-a1549ios](https://build.golang.org/log/00d2a3e8118528c5aade6d95418b415d9c1c273c)
[2018-04-17T23:04:19-fc21598/darwin-arm64-a1549ios](https://build.golang.org/log/b9f8377ebcf316dd50baeff1adc1b3107ea8126a)
[2018-04-17T23:47:18-aefd99d/darwin-arm64-a1549ios](https://build.golang.org/log/ad6acb39c196b133315d7d150782fcad08939200)
[2018-04-20T20:17:00-21fa148/darwin-arm64-a1549ios](https://build.golang.org/log/220f817a838969c468019996100459546dd58abb)
[2018-04-21T00:50:50-566e3e0/darwin-arm64-a1549ios](https://build.golang.org/log/a1d4bc03972b9a1cb8d492d7610dd4e7846340c4)
[2018-04-25T20:19:19-9e0e698/darwin-arm64-a1549ios](https://build.golang.org/log/cd51f27163d125e2a92154852ab78cc6b1731add)
[2018-04-26T14:14:13-b4ac029/darwin-arm64-a1549ios](https://build.golang.org/log/2fdc0c5e1ebc99f71e9eecd297bd4e9922e6e99e)
[2018-04-27T14:36:31-62adf6f/darwin-arm64-a1549ios](https://build.golang.org/log/0d97a8bfc612101d98749056a56b7af6da068aa9)

**Comment by nvanbenschoten** [comment]
@ianlancetaylor you rewrote the `runtime/time.go` implementation in Go1.14 to address https://github.com/golang/go/issues/6239. `(*timersBucket).addtimerLocker` was [removed](https://github.com/golang/go/commit/580337e268a0581bc537e67ca4005b7682be5d66) during this rewrite. While performing the rewrite, did you get a better sense of how this SIGSEGV was possible? Is it safe to assume that this issue is now fixed in Go1.14?

**Comment by ianlancetaylor** [comment]
@nvanbenschoten Thanks for asking.  I don't know what caused this.  But the code is completely different, so I feel confident that this is fixed.

As far as I can tell it hasn't happened since April, 2018, so it may have been fixed (somehow) before the rewrite.

I'm going to close this issue.
