### ISSUE TITLE
go plugin doesn't work on  linux/arm64

### ISSUE THREAD

**Issue by hufengwei** [golang/go#24940]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
**go version go1.8.3 linux/arm64**

### Does this issue reproduce with the latest release?
**Yes**

### What operating system and processor architecture are you using (`go env`)?
**GOARCH="arm64"
GOBIN=""
GOEXE=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_arm64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build100800721=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"**

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

I use "go build -v -o demo.so -buildmode=plugin demo.go" to build go plugin demo.so.
Then I use "plugin.Open(/path/to/demo.so)" to open the plugin in the run-time.

### What did you expect to see?
The plugin demo.so could successfully be loaded into process and run.

### What did you see instead?
My process got panic. Please see the call stack as below: 

==========================================================
fatal error: runtime: no plugin module data

goroutine 1 [running]:
runtime.throw(0xaac21a, 0x1e)
    /usr/lib/golang/src/runtime/panic.go:596 +0x70 fp=0x4420181650 sp=0x4420181630
plugin.lastmoduleinit(0x23b17720, 0x442000e0c8, 0x23b18800, 0x45, 0xd41260)
    /usr/lib/golang/src/runtime/plugin.go:13 +0x9bc fp=0x4420181780 sp=0x4420181650
plugin.open(0x4420078d70, 0x46, 0x0, 0x0, 0x0)
    /usr/lib/golang/src/plugin/plugin_dlopen.go:72 +0x1d0 fp=0x44201819c0 sp=0x4420181780
plugin.Open(0x4420078d70, 0x46, 0x4420012e80, 0x3, 0x4)
    /usr/lib/golang/src/plugin/plugin.go:30 +0x28 fp=0x44201819f0 sp=0x44201819c0
==========================================================

**Comment by ianlancetaylor** [comment]
There have been a number of plugin fixes in more recent releases.  Can you let us know whether this still fails with the 1.10.1 release?

**Comment by WK-LLP** [comment]
I did a test in "go version go1.10.1 linux/arm64", this still fails...

**Comment by Mrbuffoon** [comment]
> Change https://golang.org/cl/109917 mentions this issue: `cmd/link: fix plugin on linux/arm64`

Since it has been fixed，which version I can use

**Comment by cherrymui** [comment]
It should work with Go 1.11 and newer.
