### ISSUE TITLE
net: TestSplice freezes on linux/mips

### ISSUE THREAD

**Issue by cherrymui** [golang/go#25106]
Since CL https://go-review.googlesource.com/c/go/+/107715 (f2316c2), the linux-mips builder (big endian) is failing with net package test timeout.

Seems this is related to TestSplice. All goroutines appeared in the back trace have been waiting for 11 minutes, so I guess this is a real freeze, instead of a timeout due to slow machine.

https://build.golang.org/log/eef005ed74d7a9129f47201612d738a901b2c156

```
panic: test timed out after 12m0s

goroutine 555 [running]:
testing.(*M).startAlarm.func1()
	/data/mips/go/src/testing/testing.go:1260 +0x108
created by time.goFunc
	/data/mips/go/src/time/sleep.go:172 +0x58

goroutine 1 [chan receive, 11 minutes]:
testing.(*T).Run(0xdc5170, 0x6932e7, 0xa, 0x6a34e8, 0x1c10740)
	/data/mips/go/src/testing/testing.go:841 +0x2c4
testing.runTests.func1(0xc68090)
	/data/mips/go/src/testing/testing.go:1083 +0x74
testing.tRunner(0xc68090, 0xc4bef0)
	/data/mips/go/src/testing/testing.go:795 +0x10c
testing.runTests(0xc0c120, 0x799ea0, 0xd4, 0xd4, 0x8)
	/data/mips/go/src/testing/testing.go:1081 +0x288
testing.(*M).Run(0xc56380, 0x0)
	/data/mips/go/src/testing/testing.go:998 +0x16c
net.TestMain(0xc56380)
	/data/mips/go/src/net/main_test.go:50 +0x4c
main.main()
	_testmain.go:530 +0x15c

goroutine 357 [chan receive, 11 minutes]:
testing.(*T).Parallel(0xc69560)
	/data/mips/go/src/testing/testing.go:700 +0x1e8
net.TestLookupGoogleSRV(0xc69560)
	/data/mips/go/src/net/lookup_test.go:66 +0x58
testing.tRunner(0xc69560, 0x6a33b8)
	/data/mips/go/src/testing/testing.go:795 +0x10c
created by testing.(*T).Run
	/data/mips/go/src/testing/testing.go:840 +0x2a4

goroutine 360 [chan receive, 11 minutes]:
testing.(*T).Parallel(0xc69710)
	/data/mips/go/src/testing/testing.go:700 +0x1e8
net.TestLookupGmailTXT(0xc69710)
	/data/mips/go/src/net/lookup_test.go:201 +0x58
testing.tRunner(0xc69710, 0x6a33a8)
	/data/mips/go/src/testing/testing.go:795 +0x10c
created by testing.(*T).Run
	/data/mips/go/src/testing/testing.go:840 +0x2a4

goroutine 554 [IO wait, 11 minutes]:
internal/poll.runtime_pollWait(0x6d0ccec0, 0x72, 0xa)
	/data/mips/go/src/runtime/netpoll.go:173 +0x60
internal/poll.(*pollDesc).wait(0xee2794, 0x72, 0x0, 0x6c7420, 0x79cccc)
	/data/mips/go/src/internal/poll/fd_poll_runtime.go:85 +0xc4
internal/poll.(*pollDesc).waitRead(0xee2794, 0x7, 0x400000, 0x2)
	/data/mips/go/src/internal/poll/fd_poll_runtime.go:90 +0x4c
internal/poll.spliceDrain(0xa, 0xee2780, 0x400000, 0x2, 0x0, 0x0)
	/data/mips/go/src/internal/poll/splice_linux.go:88 +0xb4
internal/poll.Splice(0xee28c0, 0xee2780, 0x3fffffff, 0xfffffffe, 0x0, 0x2, 0xc01ea0, 0x0, 0x0, 0x0, ...)
	/data/mips/go/src/internal/poll/splice_linux.go:53 +0x234
net.splice(0xee28c0, 0x6c6fc0, 0xee0730, 0x665d40, 0x68a660, 0x6d0d1210, 0x0, 0x8)
	/data/mips/go/src/net/splice_linux.go:30 +0xcc
net.(*TCPConn).readFrom(0xee0768, 0x6c6fc0, 0xee0730, 0x49c7f0, 0x40520c, 0xce8030, 0x47fc20)
	/data/mips/go/src/net/tcpsock_posix.go:48 +0x50
net.(*TCPConn).ReadFrom(0xee0768, 0x6c6fc0, 0xee0730, 0x6d0d1210, 0xee0768, 0x1c1e000, 0x404ef4)
	/data/mips/go/src/net/tcpsock.go:103 +0x68
io.copyBuffer(0x6c6fe0, 0xee0768, 0x6c6fc0, 0xee0730, 0x0, 0x0, 0x0, 0x665ce0, 0x68a660, 0xed7840, ...)
	/data/mips/go/src/io/io.go:388 +0x378
io.Copy(0x6c6fe0, 0xee0768, 0x6c6fc0, 0xee0730, 0xee0730, 0xee0730, 0x469ee4, 0x6a38d0)
	/data/mips/go/src/io/io.go:364 +0x60
net.(*spliceTestServer).Copy.func1(0xedda20, 0xed78c0)
	/data/mips/go/src/net/splice_test.go:349 +0xb4
created by net.(*spliceTestServer).Copy
	/data/mips/go/src/net/splice_test.go:348 +0x74

goroutine 359 [chan receive, 11 minutes]:
testing.(*T).Parallel(0xc69680)
	/data/mips/go/src/testing/testing.go:700 +0x1e8
net.TestLookupGmailNS(0xc69680)
	/data/mips/go/src/net/lookup_test.go:157 +0x58
testing.tRunner(0xc69680, 0x6a33a4)
	/data/mips/go/src/testing/testing.go:795 +0x10c
created by testing.(*T).Run
	/data/mips/go/src/testing/testing.go:840 +0x2a4

goroutine 358 [chan receive, 11 minutes]:
testing.(*T).Parallel(0xc695f0)
	/data/mips/go/src/testing/testing.go:700 +0x1e8
net.TestLookupGmailMX(0xc695f0)
	/data/mips/go/src/net/lookup_test.go:113 +0x58
testing.tRunner(0xc695f0, 0x6a33a0)
	/data/mips/go/src/testing/testing.go:795 +0x10c
created by testing.(*T).Run
	/data/mips/go/src/testing/testing.go:840 +0x2a4

goroutine 417 [chan receive, 11 minutes]:
testing.(*T).Parallel(0xdc4360)
	/data/mips/go/src/testing/testing.go:700 +0x1e8
net.TestCloseUnblocksRead(0xdc4360)
	/data/mips/go/src/net/net_test.go:503 +0x3c
testing.tRunner(0xdc4360, 0x6a3164)
	/data/mips/go/src/testing/testing.go:795 +0x10c
created by testing.(*T).Run
	/data/mips/go/src/testing/testing.go:840 +0x2a4

goroutine 551 [IO wait, 11 minutes]:
internal/poll.runtime_pollWait(0x6d0ccdc0, 0x72, 0x49a27c)
	/data/mips/go/src/runtime/netpoll.go:173 +0x60
internal/poll.(*pollDesc).wait(0xee2884, 0x72, 0xffffff, 0x6c7420, 0x79cccc)
	/data/mips/go/src/internal/poll/fd_poll_runtime.go:85 +0xc4
internal/poll.(*pollDesc).waitRead(0xee2884, 0xed4d62, 0x9, 0x9)
	/data/mips/go/src/internal/poll/fd_poll_runtime.go:90 +0x4c
internal/poll.(*FD).Read(0xee2870, 0xed4d62, 0x9, 0x9, 0x0, 0x0, 0x0)
	/data/mips/go/src/internal/poll/fd_unix.go:163 +0x190
net.(*netFD).Read(0xee2870, 0xed4d62, 0x9, 0x9, 0x2, 0x0, 0x0)
	/data/mips/go/src/net/fd_unix.go:202 +0x58
net.(*conn).Read(0xee0770, 0xed4d62, 0x9, 0x9, 0x0, 0x0, 0x0)
	/data/mips/go/src/net/net.go:176 +0x70
net.(*spliceTestServer).Read(0xedda20, 0xed4d62, 0x9, 0x9, 0x2, 0x0, 0x0)
	/data/mips/go/src/net/splice_test.go:314 +0x60
io.ReadAtLeast(0x6c7000, 0xedda20, 0xed4d60, 0xb, 0xb, 0xb, 0x65fa80, 0x1000000, 0xed4d60)
	/data/mips/go/src/io/io.go:310 +0x98
io.ReadFull(0x6c7000, 0xedda20, 0xed4d60, 0xb, 0xb, 0xb, 0x0, 0x4e3438)
	/data/mips/go/src/io/io.go:329 +0x60
net.testSpliceSimple(0xdc5200)
	/data/mips/go/src/net/splice_test.go:36 +0x1e0
testing.tRunner(0xdc5200, 0x6a3728)
	/data/mips/go/src/testing/testing.go:795 +0x10c
created by testing.(*T).Run
	/data/mips/go/src/testing/testing.go:840 +0x2a4

goroutine 550 [chan receive, 11 minutes]:
testing.(*T).Run(0xdc5200, 0x6920bc, 0x6, 0x6a3728, 0xd017c0)
	/data/mips/go/src/testing/testing.go:841 +0x2c4
net.TestSplice(0xdc5170)
	/data/mips/go/src/net/splice_test.go:17 +0x5c
testing.tRunner(0xdc5170, 0x6a34e8)
	/data/mips/go/src/testing/testing.go:795 +0x10c
created by testing.(*T).Run
	/data/mips/go/src/testing/testing.go:840 +0x2a4
FAIL	net	720.048s
```

Note that the problem only appears on the big endian mips builder. It seems fine on the little endian linux-mipsle builder.

**Comment by bcmills** [comment]
(CC: @acln0, @ianlancetaylor, @bradfitz, @ALTree )

I believe https://golang.org/cl/109316 has the fix.
