### ISSUE TITLE
runtime, cmd/link: darwin/amd64 occasionally hangs

### ISSUE THREAD

**Issue by josharian** [golang/go#25181]
https://golang.org/cl/108679 seems to have broken the darwin/arm and darwin/arm64 builds.

Also, I am now experiencing occasional hangs during make.bash. Sample SIGQUIT output:

```
$ ./make.bash
Building Go cmd/dist using /Users/josh/go/1.4.
Building Go toolchain1 using /Users/josh/go/1.4.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for darwin/amd64.
# testing/iotest
SIGQUIT: quit
PC=0x1057115 m=1 sigcode=0

goroutine 0 [idle]:
runtime.usleep(0x5700002710, 0x0, 0x45d9ff8c62, 0x45d964b800, 0x271000000000, 0x576c68ca9e, 0x45d964b800, 0x2, 0x0, 0x45d9ff8c62, ...)
	/Users/josh/go/tip/src/runtime/sys_darwin_amd64.s:418 +0x45
runtime.sysmon()
	/Users/josh/go/tip/src/runtime/proc.go:4256 +0xd0
runtime.mstart1()
	/Users/josh/go/tip/src/runtime/proc.go:1229 +0xe6
runtime.mstart()
	/Users/josh/go/tip/src/runtime/proc.go:1195 +0x6e

goroutine 1 [runnable, locked to thread]:
runtime.gopark(0x183bec0, 0xc000066058, 0x1820255, 0xc, 0xc000020e17, 0x3)
	/Users/josh/go/tip/src/runtime/proc.go:291 +0x105
runtime.goparkunlock(0xc000066058, 0x1820255, 0xc, 0x17, 0x3)
	/Users/josh/go/tip/src/runtime/proc.go:297 +0x5e
runtime.chanrecv(0xc000066000, 0x0, 0xc000000101, 0x10167c8)
	/Users/josh/go/tip/src/runtime/chan.go:520 +0x2d1
runtime.chanrecv1(0xc000066000, 0x0)
	/Users/josh/go/tip/src/runtime/chan.go:402 +0x2b
runtime.gcenable()
	/Users/josh/go/tip/src/runtime/mgc.go:217 +0x6f
runtime.main()
	/Users/josh/go/tip/src/runtime/proc.go:161 +0x119
runtime.goexit()
	/Users/josh/go/tip/src/runtime/asm_amd64.s:1356 +0x1

rax    0x4
rbx    0x2
rcx    0xc000051e00
rdx    0x0
rdi    0x0
rsi    0x0
rbp    0xc000051e10
rsp    0xc000051e00
r8     0xc000051e00
r9     0x0
r10    0x0
r11    0x206
r12    0x85f8e928f07
r13    0x0
r14    0xb0000000
r15    0x0
rip    0x1057115
rflags 0x207
cs     0x7
fs     0x0
gs     0x0
go tool dist: FAILED: /Users/josh/go/tip/pkg/tool/darwin_amd64/go_bootstrap install -gcflags=all= -ldflags=all= std cmd: exit status 2
```

cc @randall77

**Comment by josharian** [comment]
I suspect this darwin/amd64 failure from the dashboard is the same thing: https://build.golang.org/log/16b7534fc8d85a751999df12ffb24f7eb825e79a

**Comment by randall77** [comment]
CL 110123 already out for the arm64 fix.

**Comment by josharian** [comment]
I haven’t experienced it in a while. Closing until proven otherwise.
