### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by azilber** [golang/go#25180]
### What version of Go are you using (`go version`)?
go version go1.10.1 darwin/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/azilber/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/azilber/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vg/ds0mtz4933sdqmng71x23f0m0000gn/T/go-build180512687=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?
Ran this example:  https://github.com/howtographql/graphql-go

### What did you expect to see?
A running app.

### What did you see instead?
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x12d905a]

goroutine 7 [running]:
github.com/howtographql/graphql-go/vendor/github.com/mattes/migrate.(*Migrate).lock.func3(0xc420158200, 0xc4200822a0)
	/Users/azilber/go/src/github.com/howtographql/graphql-go/vendor/github.com/mattes/migrate/migrate.go:867 +0x2a
created by github.com/howtographql/graphql-go/vendor/github.com/mattes/migrate.(*Migrate).lock
	/Users/azilber/go/src/github.com/howtographql/graphql-go/vendor/github.com/mattes/migrate/migrate.go:866 +0x154
```

**Comment by ALTree** [comment]
Thanks for the report.

Can you explain why are you assuming that this is caused by a bug in the Go runtime and not by an error in the application you linked?

**Comment by azilber** [comment]
Hmm, it looks like that app has no error handling.   The error goes away when there's a connection to Postges available.  When there's not, there's the error.  Not a clear error, but does look like it's not an issue with the go runtime.
