### ISSUE TITLE
x/vgo: Crashes running in golang:1.10 docker image

### ISSUE THREAD

**Issue by paulbdavis** [golang/go#25410]
Please answer these questions before submitting your issue. Thanks!

### What did you do?

run `go get -u golang.org/x/vgo` and then try to build with vgo inside the contianer

```
goroutine 1 [running]:
golang.org/x/vgo/vendor/cmd/go/internal/mvs.buildList(0xc4201aa620, 0x17, 0x0, 0x0, 0x981ac0, 0xc420129fc0, 0x0, 0xc4201bd220, 0xc420129fc0, 0xc4201bd660, ...)
	/go/src/golang.org/x/vgo/vendor/cmd/go/internal/mvs/mvs.go:80 +0x101c
golang.org/x/vgo/vendor/cmd/go/internal/mvs.BuildList(0xc4201aa620, 0x17, 0x0, 0x0, 0x981ac0, 0xc420129fc0, 0x86d100, 0xc4201fe290, 0x7f3a2cb70000, 0x1, ...)
	/go/src/golang.org/x/vgo/vendor/cmd/go/internal/mvs/mvs.go:33 +0x78
golang.org/x/vgo/vendor/cmd/go/internal/vgo.iterate(0xc4201bd770)
	/go/src/golang.org/x/vgo/vendor/cmd/go/internal/vgo/load.go:124 +0xae
golang.org/x/vgo/vendor/cmd/go/internal/vgo.importPaths(0xc42001e0f0, 0x0, 0x0, 0x76f5f7, 0xc4201fe080, 0x1)
	/go/src/golang.org/x/vgo/vendor/cmd/go/internal/vgo/load.go:83 +0xe4
golang.org/x/vgo/vendor/cmd/go/internal/vgo.ImportPaths(0xc42001e0f0, 0x0, 0x0, 0xc4201fe080, 0x1, 0x1)
	/go/src/golang.org/x/vgo/vendor/cmd/go/internal/vgo/load.go:71 +0x5a
golang.org/x/vgo/vendor/cmd/go/internal/load.ImportPaths(0xc42001e0f0, 0x0, 0x0, 0x4118e9, 0xc4201aa460, 0x16)
	/go/src/golang.org/x/vgo/vendor/cmd/go/internal/load/pkg.go:1485 +0x4f
golang.org/x/vgo/vendor/cmd/go/internal/load.PackagesAndErrors(0xc42001e0f0, 0x0, 0x0, 0xc4201bda90, 0x433db9, 0xc420000180)
	/go/src/golang.org/x/vgo/vendor/cmd/go/internal/load/pkg.go:1457 +0xac
golang.org/x/vgo/vendor/cmd/go/internal/load.PackagesForBuild(0xc42001e0f0, 0x0, 0x0, 0x10, 0x10, 0x8a2f80)
	/go/src/golang.org/x/vgo/vendor/cmd/go/internal/load/pkg.go:1499 +0x5d
golang.org/x/vgo/vendor/cmd/go/internal/work.runBuild(0xb8f920, 0xc42001e0f0, 0x0, 0x0)
	/go/src/golang.org/x/vgo/vendor/cmd/go/internal/work/build.go:301 +0x85
golang.org/x/vgo/vendor/cmd/go.Main()
	/go/src/golang.org/x/vgo/vendor/cmd/go/main.go:155 +0x82e
main.main()
	/go/src/golang.org/x/vgo/main.go:31 +0x20
```

**Comment by davecheney** [comment]
You cut off the crucial first line. Can you please paste the entire panic message. Thank you.

**Comment by fraenkel** [comment]
@davecheney Doesn't really matter since its https://github.com/golang/vgo/blob/master/vendor/cmd/go/internal/mvs/mvs.go#L80

**Comment by davecheney** [comment]
Right, and if the OP had included the full output, then _both_ of us would not have had to read the source.

**Comment by utrack** [comment]
Same here - `panic: mistake`, latest master seems to be broken (?). Anything I can help with?

**Comment by paulbdavis** [comment]
Sorry about that. The first line was just `panic: mistake` as @utrack mentioned

**Comment by paulbdavis** [comment]
Did some more testing, and found that the cause of the issue is when the module's name in the `go.mod` file does not match the import path.

This was my fault (it was my module that was inproperly named), but I think that error could be more explicit.
