### ISSUE TITLE
cmd/internal/obj/arm64: when the immediate is MOVCON type, assembler handles  cmp/cmn (immediate) instruction incorrectly.

### ISSUE THREAD

**Issue by zhangfannie** [golang/go#25557]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version devel +87a18c6 Tue May 22 02:58:04 2018 +0000 linux/arm64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="arm64"
GOBIN=""
GOCACHE="/home/fanzha02/.cache/go-build"
GOEXE=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/fanzha02/go"
GORACE=""
GOROOT="/mnt/share/homes/fanzha02/RefineAsm/golang"
GOTMPDIR=""
GOTOOLDIR="/mnt/share/homes/fanzha02/RefineAsm/golang/pkg/tool/linux_arm64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build672309942=/tmp/go-build -gno-record-gcc-switches"

### What did you do?
check assembler assembly instruction "CMPW $0x22220000, RSP", the instruction is encoded as two binary 5b44a4d2 ff031b6b.  binary 5b44a4d2 is decoded as MOVD $0x2222000, R27, binary ff031b6b is decoded as CMPW R27, ZR. 

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
 CMPW $0x2222000, RSP is assembled as MOVD $0x22220000, R27, CMPW R27, RSP(CMP (extended register))

### What did you see instead?
 CMPW $0x2222000, RSP is assembled as MOVD $0x22220000, R27, CMPW R27, ZR(CMP (shifted register))

**Comment by andybons** [comment]
@randall77

**Comment by benshi001** [comment]
2. " ADD      $572653568, RSP" causes the assembler crash.

--- FAIL: TestARM64EndToEnd (0.01s)
        endtoend_test.go:186: overflow in spadj: 0 + -572653568 = -572653568
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x501c37]

goroutine 5 [running]:
testing.tRunner.func1(0xc0000dc700)
        /home/local/SPREADTRUM/ben.shi/Desktop/go/src/testing/testing.go:792 +0x387
panic(0x5f8a40, 0x7ac3c0)
        /home/local/SPREADTRUM/ben.shi/Desktop/go/src/runtime/panic.go:494 +0x1b9
cmd/internal/obj.pctospadj(0xc0002ceb40, 0xc00032e310, 0x0, 0xc0003d8ea0, 0x1, 0x0, 0x0, 0xc000000000)
        /home/local/SPREADTRUM/ben.shi/Desktop/go/src/cmd/internal/obj/pcln.go:234 +0x177
cmd/internal/obj.funcpctab(0xc0002ceb40, 0xc0000e96a8, 0xc00032e310, 0x62d397, 0x9, 0x63c2f8, 0x0, 0x0)
        /home/local/SPREADTRUM/ben.shi/Desktop/go/src/cmd/internal/obj/pcln.go:62 +0x577
cmd/internal/obj.linkpcln(0xc0002ceb40, 0xc00032e310)
        /home/local/SPREADTRUM/ben.shi/Desktop/go/src/cmd/internal/obj/pcln.go:320 +0x220
cmd/internal/obj.Flushplist(0xc0002ceb40, 0xc00014bb80, 0xc00031f290, 0x0, 0x0)
        /home/local/SPREADTRUM/ben.shi/Desktop/go/src/cmd/internal/obj/plist.go:108 +0x6c6
cmd/asm/internal/asm.testEndToEnd(0xc0000dc700, 0x62957d, 0x5, 0x62957d, 0x5)
        /home/local/SPREADTRUM/ben.shi/Desktop/go/src/cmd/asm/internal/asm/endtoend_test.go:189 +0x8ed
cmd/asm/internal/asm.TestARM64EndToEnd(0xc0000dc700)
        /home/local/SPREADTRUM/ben.shi/Desktop/go/src/cmd/asm/internal/asm/endtoend_test.go:381 +0x4e
testing.tRunner(0xc0000dc700, 0x63c228)
        /home/local/SPREADTRUM/ben.shi/Desktop/go/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
        /home/local/SPREADTRUM/ben.shi/Desktop/go/src/testing/testing.go:878 +0x353
FAIL    cmd/asm/internal/asm    0.073s
