### ISSUE TITLE
Not able to install revel on raspberry pi

### ISSUE THREAD

**Issue by sujeet03** [golang/go#25566]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9 linux/arm  

### What operating system and processor architecture are you using (`go env`)?
GOARCH="arm"
GOBIN=""
GOEXE=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/pi/gocode"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm"
GCCGO="gccgo"
GOARM="6"
CC="gcc"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build101436108=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?
I tried installing revel by go get -u github.com/revel/cmd/revel. 

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
revel installed

### What did you see instead?
  panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5190b8]
goroutine 1 [running]:
cmd/compile/internal/gc.dumpasmhdr()
       /usr/local/go/src/cmd/compile/internal/gc/export.go:389 +0x20c
cmd/compile/internal/gc.Main(0x6c5f88)
        /usr/local/go/src/cmd/compile/internal/gc/main.go:633 +0x2660
main.main()
        /usr/local/go/src/cmd/compile/main.go:49 +0x7c

**Comment by kardianos** [comment]
If this is a first gen rpi, set GOARM=5.

**Comment by sujeet03** [comment]
No its not first gen rpi

**Comment by mvdan** [comment]
I can't reproduce any crash on linux/amd64 on neither tip nor 1.10.2. Not even after setting `GOARCH=arm`.

@sujeet03 have you tried Go 1.10?
