### ISSUE TITLE
net: TestLookupHostCancel and TestCloseRead flaky on Yosemite

### ISSUE THREAD

**Issue by bcmills** [golang/go#25694]
Examples:
https://build.golang.org/log/63ea433daf839bebe655c49e196c359e83586e88
https://build.golang.org/log/460d2123fc01822ebd2bb6a224e2dedaaaebbaa7
https://build.golang.org/log/49bc59d02f5575c538997f59602d727617c3723e

All with this failure mode:
```
--- FAIL: TestLookupHostCancel (0.80s)
    lookup_test.go:923: lookup www.google.com: no such host
--- FAIL: TestCloseRead (0.00s)
panic: open /var/folders/6g/8k13h11n2zb8hxx99wk6f6y40000gn/T/go-nettest731919775: too many open files [recovered]
	panic: open /var/folders/6g/8k13h11n2zb8hxx99wk6f6y40000gn/T/go-nettest731919775: too many open files

goroutine 2188 [running]:
testing.tRunner.func1(0xc0000b6200)
	/var/folders/6g/8k13h11n2zb8hxx99wk6f6y40000gn/T/workdir/go/src/testing/testing.go:792 +0x387
panic(0x124af40, 0xc00066b2c0)
	/var/folders/6g/8k13h11n2zb8hxx99wk6f6y40000gn/T/workdir/go/src/runtime/panic.go:494 +0x1b9
net.testUnixAddr(0x1285969, 0x4)
	/var/folders/6g/8k13h11n2zb8hxx99wk6f6y40000gn/T/workdir/go/src/net/mockserver_test.go:23 +0xc3
net.newLocalListener(0x1285969, 0x4, 0x1, 0x1, 0x0, 0x12ca1e0)
	/var/folders/6g/8k13h11n2zb8hxx99wk6f6y40000gn/T/workdir/go/src/net/mockserver_test.go:51 +0x2d5
net.TestCloseRead(0xc0000b6200)
	/var/folders/6g/8k13h11n2zb8hxx99wk6f6y40000gn/T/workdir/go/src/net/net_test.go:30 +0xcf
testing.tRunner(0xc0000b6200, 0x1296b78)
	/var/folders/6g/8k13h11n2zb8hxx99wk6f6y40000gn/T/workdir/go/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/var/folders/6g/8k13h11n2zb8hxx99wk6f6y40000gn/T/workdir/go/src/testing/testing.go:878 +0x353
FAIL	net	2.369s
```

**Comment by bcmills** [comment]
CC: @mikioh @bradfitz @ianlancetaylor
