### ISSUE TITLE
runtime: TestGdbPython flaky on linux-mipsle builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#25697]
Examples:
https://build.golang.org/log/e59511fa905a9939c7b85a9f6cefb99140c8915f
https://build.golang.org/log/dc9b43b3eb5e0029089cf9ac53b37f6b8b0e7847

Detail:
```
##### GOMAXPROCS=2 runtime -cpu=1,2,4 -quick
--- FAIL: TestGdbPython (3.10s)
    runtime-gdb_test.go:61: gdb version 7.7
    runtime-gdb_test.go:195: gdb output: Loading Go Runtime support.
        Loaded  Script                                                                 
        Yes     /data/mipsle/go/src/runtime/runtime-gdb.py                             
        Breakpoint 1 at 0x9b508: file /data/mipsle/go/src/fmt/print.go, line 264.
        Failed to read a valid object file image from memory.
        
        Breakpoint 1, fmt.Println (a=..., err=..., n=<optimized out>) at /data/mipsle/go/src/fmt/print.go:264
        264		return Fprintln(os.Stdout, a...)
        BEGIN info goroutines
        * 1 running  runtime.systemstack_switch
          2 runnable runtime.forcegchelper
          3 waiting  runtime.gopark
          4 runnable runtime.runfinq
        END
        #1  0x000a24e0 in main.main () at /tmp/go-build482556707/main.go:13
        13		slicevar = append(slicevar, mapvar["abc"])
        BEGIN print mapvar
        $1 = map[string]string = {["abc"] = "def", ["ghi"] = "jkl"}
        END
        BEGIN print strvar
        $2 = "abc"
        END
        BEGIN info locals
        mapvar = map[string]string = {["abc"] = "def", ["ghi"] = "jkl"}
        slicevar =  []string = {"def"}
        strvar = "abc"
        END
        #0  fmt.Println (a=..., err=..., n=<optimized out>) at /data/mipsle/go/src/fmt/print.go:264
        264		return Fprintln(os.Stdout, a...)
        BEGIN goroutine 1 bt
        #0  fmt.Println (a=..., err=..., n=<optimized out>) at /data/mipsle/go/src/fmt/print.go:264
        #1  0x000a24e0 in main.main () at /tmp/go-build482556707/main.go:13
        END
        BEGIN goroutine 2 bt
        #0  runtime.forcegchelper () at /data/mipsle/go/src/runtime/proc.go:243
        #1  0x000a24e0 in main.main () at /tmp/go-build482556707/main.go:13
        END
        Breakpoint 2 at 0xa2514: file /tmp/go-build482556707/main.go, line 18.
        
        Program received signal SIGTRAP, Trace/breakpoint trap.
        fmt.Println (a=..., err=..., n=<optimized out>) at /data/mipsle/go/src/fmt/print.go:264
        264		return Fprintln(os.Stdout, a...)
        BEGIN goroutine 1 bt at the end
        #0  fmt.Println (a=..., err=..., n=<optimized out>) at /data/mipsle/go/src/fmt/print.go:264
        #1  0x000a24e0 in main.main () at /tmp/go-build482556707/main.go:13
        END
        
    runtime-gdb_test.go:264: goroutine 1 bt at the end failed: #0  fmt.Println (a=..., err=..., n=<optimized out>) at /data/mipsle/go/src/fmt/print.go:264
        #1  0x000a24e0 in main.main () at /tmp/go-build482556707/main.go:13
FAIL
FAIL	runtime	208.804s
```

```

```

**Comment by ianlancetaylor** [comment]
[2018-05-02T04:20:25-500d79c/linux-mipsle](https://build.golang.org/log/6945e3014d3bd631c3c2d0f398a8ed754b451fec)
[2018-05-02T14:41:32-7e960d0/linux-mipsle](https://build.golang.org/log/af4516ec7c80d3491f1e7a20d6ce32419a967f84)
[2018-05-02T16:59:27-2010259/linux-mipsle](https://build.golang.org/log/0a32d842d80f9343ecb87d8c2aaa037e55bb981c)
[2018-05-08T13:15:39-28edaf4/linux-mipsle](https://build.golang.org/log/b9c32ecdc7d2479d2521b64e518aee1c3fb2a6d5)
[2018-05-08T15:00:57-704893b/linux-mipsle](https://build.golang.org/log/08e8df949ff2cf403ebf13099f91c3d3ccb73496)
[2018-05-08T17:32:18-cf4e559/linux-mipsle](https://build.golang.org/log/82dbfa2538924731e2b6a6dc44d29d3dd27934e0)
[2018-05-30T09:10:04-7d704a9/linux-mipsle](https://build.golang.org/log/c0a6e03293f2dc3fdbbdc3285340780df192c91e)
[2018-05-30T13:40:36-e023d5b/linux-mipsle](https://build.golang.org/log/a67b55ecbee7b785ce02e3f3a9a3586625f7a35b)
[2018-05-30T15:25:21-fd4392b/linux-mipsle](https://build.golang.org/log/f13c17ed5ab61e8fe97f7d97a3c7fcbc7549efca)
[2018-05-30T16:28:46-85f4051/linux-mipsle](https://build.golang.org/log/d333c290d0f3a175ce91d3fd878f077c3362857a)
[2018-05-30T18:03:08-d4e2128/linux-mipsle](https://build.golang.org/log/1404a4bff131d76faa22c7be77a28d9ec3fb92ef)
[2018-05-31T14:22:44-bfdf74b/linux-mipsle](https://build.golang.org/log/bbdb5327aa5af7a25941973aa1d955fd69063c0e)
[2018-05-31T15:13:02-08e2e88/linux-mipsle](https://build.golang.org/log/3201790702b1f5faf263afad7f84a1620c59b7dd)
[2018-06-01T05:18:38-063f97a/linux-mipsle](https://build.golang.org/log/dc9b43b3eb5e0029089cf9ac53b37f6b8b0e7847)
[2018-06-01T19:18:43-b280edb/linux-mipsle](https://build.golang.org/log/e59511fa905a9939c7b85a9f6cefb99140c8915f)
[2018-06-04T22:06:42-b219a68/linux-mipsle](https://build.golang.org/log/dcc7770447141ab2241362fc2687ecbf7026c630)
[2018-06-06T01:47:31-2ce295e/linux-mipsle](https://build.golang.org/log/d5d5c7c5f6724bd98d115649e3d0a38242ff9715)
[2018-06-06T14:08:42-6decd3d/linux-mipsle](https://build.golang.org/log/34edb836c32c28bad8423cdcdcec61df1b8a05a2)
[2018-06-06T14:40:25-88dc4ae/linux-mipsle](https://build.golang.org/log/9d8802f27dcc2314b792947d7de82905aff42c67)
[2018-06-06T15:12:32-7c1f361/linux-mipsle](https://build.golang.org/log/edef53e2b1cae81b60cfdf49b661f3cffe420134)
[2018-06-07T01:19:13-33f1768/linux-mipsle](https://build.golang.org/log/49ed51e57f2061986986742d5faf3c02a0232484)
[2018-06-07T14:58:07-cf901a7/linux-mipsle](https://build.golang.org/log/d81e63f1c062f790c230f0e28788c5fc00d8bd8c)
[2018-06-07T15:47:29-0e1517c/linux-mipsle](https://build.golang.org/log/0cadd4238e23c7603854fa1775851b85d1084dd5)
[2018-06-07T21:52:22-19f3794/linux-mipsle](https://build.golang.org/log/bcf031322713517d1ede41f8f8461d594a87fe4d)
[2018-06-08T02:11:51-1425412/linux-mipsle](https://build.golang.org/log/77a76dd72a5cf1ef52ef4e6e46d7d12b0a8b454f)
[2018-06-08T17:07:53-afae876/linux-mipsle](https://build.golang.org/log/451b17cc329043ed2d735265b6800fc82191d887)
[2018-06-08T21:07:22-96faeb0/linux-mipsle](https://build.golang.org/log/a4ec11e80e8a37cb3a48cba49af58292d7b9c873)
[2018-06-11T11:41:31-7ba0c62/linux-mipsle](https://build.golang.org/log/40464a997a602dbc46607665ab8e326d887281d7)
[2018-06-11T18:23:40-b111f3c/linux-mipsle](https://build.golang.org/log/5e533dcda5430dc202784ee19370af75887bbb40)
[2018-06-12T13:41:58-29b631e/linux-mipsle](https://build.golang.org/log/dc7174f50b1ab32288b9b55a712f25d557d4f3ff)
[2018-06-12T17:05:46-021c39d/linux-mipsle](https://build.golang.org/log/2a6401a4e39d6f38a475cf1685e5effc3b04f3fb)
[2018-06-12T20:31:40-f714220/linux-mipsle](https://build.golang.org/log/4ee3f0edba6ed0ab239ccb003029f019ddf230a2)
[2018-06-13T18:27:15-72c29fc/linux-mipsle](https://build.golang.org/log/419bafb6b506db74ba112d5bf929bdf6bc9ccbde)
[2018-06-13T21:57:41-fc0e1d2/linux-mipsle](https://build.golang.org/log/dbf6eb96493868d955d1e9ad6fe75c76333dd458)
[2018-06-13T23:08:56-b8dc931/linux-mipsle](https://build.golang.org/log/3ed40232145da34df157086ed765fc78a11164b7)
[2018-06-14T15:12:11-90559ab/linux-mipsle](https://build.golang.org/log/ab8cf3b9e7b999392da7173ce989432c727dc468)
[2018-06-14T22:26:30-30b045d/linux-mipsle](https://build.golang.org/log/8c43d067976c6d164a4fd1abddd56a6f281c3787)
[2018-06-15T00:04:15-adf72bb/linux-mipsle](https://build.golang.org/log/d19c4456fc295334211d947d4410ca83dafa20af)
[2018-06-15T14:04:32-ed99fcf/linux-mipsle](https://build.golang.org/log/64e3b6dc5aa4bc389fe1eec679f890f2171498ae)
[2018-06-16T00:58:45-cdffe9b/linux-mipsle](https://build.golang.org/log/92f867fa0471e787ba48d177e0e1fc9468dffcb1)
[2018-06-20T17:17:37-dd0e7a9/linux-mipsle](https://build.golang.org/log/687287f22d154bff1dde53ee381ea8b62c5f85a2)
[2018-06-22T16:16:26-82d1c2a/linux-mipsle](https://build.golang.org/log/2e80f743cd50ceb6c4dc4869de2d353d9f9609fa)
[2018-06-26T16:40:09-8997ec1/linux-mipsle](https://build.golang.org/log/7726024a3323d10dd8fc4580167fc9d4ae254f63)
[2018-06-27T20:29:21-bafe466/linux-mipsle](https://build.golang.org/log/5adf7f93883a6d7b6ed96cab7208d883e08a8777)
[2018-06-29T20:48:07-a5f8128/linux-mipsle](https://build.golang.org/log/f9e7c92718319f3372e4ccfbf2b53b8d90ccf965)
[2018-07-02T19:43:07-adfa8b8/linux-mipsle](https://build.golang.org/log/231ec25e25fb8b1395696839a9038b7353222f33)
[2018-07-04T00:15:55-ad4e637/linux-mipsle](https://build.golang.org/log/c68daa934d9e1f631e234982bf6ab9d1d5f54253)
[2018-07-04T10:47:06-7145f1c/linux-mipsle](https://build.golang.org/log/2beb2c25b0658436716d652757db2338321c3b0b)
[2018-07-06T14:45:29-b0155e3/linux-mipsle](https://build.golang.org/log/75d1424eb525e9e8a0eec0ae027408d1a0ddddcf)

**Comment by ianlancetaylor** [comment]
See also #18784.
