### ISSUE TITLE
x/build/cmd/gitmirror: unexpected signal

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#25766]
From the logs, not full trace because there's just no button to see logs as text.

```
E  2018/06/06 22:49:03 Downloading 43 bytes of https://maintner.golang.org/logs/36 ...
E  2018/06/06 22:49:03 wrote /cache/golang-maintner/0036.growing.mutlog
E  2018/06/06 22:49:03 Reloaded data from log *maintner.netMutSource.
E  2018/06/06 22:49:03 Updating data from log *maintner.netMutSource ...
E  2018/06/06 22:49:07 go: git fetch: signal: killed
E  
E  2018/06/06 22:49:21 go: git fetch: signal: killed
E  
E  2018/06/06 22:49:32 go: git fetch: signal: killed
E  
E  2018/06/06 22:49:41 go: git fetch: signal: killed
E  
E  2018/06/06 22:49:51 go: git fetch: signal: killed
E  
E  2018/06/06 22:49:53 http2: server: error reading preface from client 10.240.0.15:60344: read tcp 10.200.3.3:443->10.240.0.15:60344: read: connection reset by peer
E  2018/06/06 22:50:05 go: git fetch: signal: killed
E  
E  2018/06/06 22:50:12 go: git fetch: signal: killed
E  
E  2018/06/06 22:50:26 go: git fetch: signal: killed
E  
E  2018/06/06 22:50:37 go: git fetch: signal: killed
E  
E  2018/06/06 22:50:46 go: git fetch: signal: killed
E  
E  2018/06/06 22:50:57 go: git fetch: signal: killed
E  
E  2018/06/06 22:51:11 go: git fetch: signal: killed
E  
E  2018/06/06 22:51:17 go: git fetch: signal: killed
E  
E  2018/06/06 22:51:31 go: git fetch: signal: killed
E  
E  2018/06/06 22:51:42 go: git fetch: signal: killed
E  
E  2018/06/06 22:51:51 go: git fetch: signal: killed
E  
E  2018/06/06 22:52:02 go: git fetch: signal: killed
E  
E  2018/06/06 22:52:16 go: git fetch: signal: killed
E  
E  2018/06/06 22:52:22 go: git fetch: signal: killed
E  
E  fatal error: unexpected signal during runtime execution
E  [signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x4564b3]
E  
E  goroutine 134 [running]:
E  runtime.throw(0x778cf9, 0x2a)
E  	/usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc45e4eb748 sp=0xc45e4eb728
E  runtime.sigpanic()
E  	/usr/local/go/src/runtime/signal_unix.go:274 +0x2db fp=0xc45e4eb798 sp=0xc45e4eb748
E  runtime.memclrNoHeapPointers(0xc427939680, 0x120)
E  	/usr/local/go/src/runtime/memclr_amd64.s:45 +0x83 fp=0xc45e4eb7a0 sp=0xc45e4eb798
E  runtime.mallocgc(0x120, 0x732e40, 0x4ce701, 0x44)
E  	/usr/local/go/src/runtime/malloc.go:695 +0x7ea fp=0xc45e4eb840 sp=0xc45e4eb7a0
E  runtime.newarray(0x732e40, 0x1, 0xb5c67f00726116f2)
E  	/usr/local/go/src/runtime/malloc.go:833 +0x64 fp=0xc45e4eb880 sp=0xc45e4eb840
E  runtime.mapassign(0x706180, 0xc4639a2120, 0xc4614edc50, 0x2)
E  	/usr/local/go/src/runtime/hashmap.go:507 +0x60a fp=0xc45e4eb920 sp=0xc45e4eb880
E  main.parseRefs(0xc463bce160, 0xc445711800, 0x76a6b0, 0x3)
E  	/go/src/golang.org/x/build/cmd/gitmirror/gitmirror.go:1520 +0x1ef fp=0xc45e4eba48 sp=0xc45e4eb920
E  main.(*Repo).getRemoteRefs(0xc420170000, 0x76a8f6, 0x4, 0x0, 0x0, 0x0)
E  	/go/src/golang.org/x/build/cmd/gitmirror/gitmirror.go:1501 +0x15f fp=0xc45e4ebad0 sp=0xc45e4eba48
E  main.(*Repo).push.func2(0x0, 0xc42021dda8)
E  	/go/src/golang.org/x/build/cmd/gitmirror/gitmirror.go:1105 +0x26f fp=0xc45e4ebd80 sp=0xc45e4ebad0
E  main.try(0x3, 0xc45e4ebdd0, 0xc42021de00, 0xc420170000)
E  	/go/src/golang.org/x/build/cmd/gitmirror/gitmirror.go:1260 +0x55 fp=0xc45e4ebda8 sp=0xc45e4ebd80
E  main.(*Repo).push(0xc420170000, 0x0, 0x0)
E  	/go/src/golang.org/x/build/cmd/gitmirror/gitmirror.go:1160 +0xd8 fp=0xc45e4ebdf8 sp=0xc45e4ebda8
E  main.(*Repo).Loop(0xc420170000)
E  	/go/src/golang.org/x/build/cmd/gitmirror/gitmirror.go:568 +0x271 fp=0xc45e4ebec0 sp=0xc45e4ebdf8
E  main.runGitMirror.func1(0xc4200fc84d, 0x6, 0xc4200fc840, 0x13, 0x1)
E  	/go/src/golang.org/x/build/cmd/gitmirror/gitmirror.go:216 +0x2d1 fp=0xc45e4ebfb8 sp=0xc45e4ebec0
E  runtime.goexit()
E  	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc45e4ebfc0 sp=0xc45e4ebfb8
E  created by main.runGitMirror
E  	/go/src/golang.org/x/build/cmd/gitmirror/gitmirror.go:225 +0x467
E  
E  goroutine 1 [chan receive, 5 minutes]:
E  main.runGitMirror(0x0, 0x0)
E  	/go/src/golang.org/x/build/cmd/gitmirror/gitmirror.go:240 +0x636
E  main.main()
E  	/go/src/golang.org/x/build/cmd/gitmirror/gitmirror.go:115 +0x132
E  
E  goroutine 17 [syscall, 5 minutes, locked to thread]:
E  runtime.goexit()
E  	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1
E  
E  goroutine 2150 [select]:
E  net/http.(*http2ClientConn).RoundTrip(0xc4204381a0, 0xc46738e300, 0x0, 0x0, 0x0)
E  	/usr/local/go/src/net/http/h2_bundle.go:6166 +0xb84
E  net/http.(*http2Transport).RoundTripOpt(0xc4201401e0, 0xc46738e300, 0xc4636d9500, 0x40e1ff, 0x707be0, 0x40c9c2)
E  	/usr/local/go/src/net/http/h2_bundle.go:5703 +0x173
E  net/http.(*http2Transport).RoundTrip(0xc4201401e0, 0xc46738e300, 0xc42001a280, 0xc4636d9740, 0x0)
E  	/usr/local/go/src/net/http/h2_bundle.go:5665 +0x40
E  net/http.http2noDialH2RoundTripper.RoundTrip(0xc4201401e0, 0xc46738e300, 0xc442e8f800, 0x5, 0xc42018a088)
E  	/usr/local/go/src/net/http/h2_bundle.go:345 +0x39
E  net/http.(*Transport).RoundTrip(0x8edfe0, 0xc46738e300, 0x8edfe0, 0x0, 0x0)
E  	/usr/local/go/src/net/http/transport.go:349 +0xaf9
E  net/http.send(0xc46738e300, 0x8c04a0, 0x8edfe0, 0x0, 0x0, 0x0, 0x0, 0x8, 0xc464097518, 0x410ae8)
E  	/usr/local/go/src/net/http/client.go:249 +0x162
E  net/http.(*Client).send(0x8f1ec0, 0xc46738e300, 0x0, 0x0, 0x0, 0xc464097518, 0x0, 0x1, 0xc445cb4510)
E  	/usr/local/go/src/net/http/client.go:173 +0x108
E  net/http.(*Client).Do(0x8f1ec0, 0xc46738e300, 0xc42001a280, 0xc46738e300, 0x0)
E  	/usr/local/go/src/net/http/client.go:595 +0x254
E  golang.org/x/build/maintner.(*netMutSource).getServerSegments(0xc420011260, 0x8c5320, 0xc42001a280, 0x24c33de7, 0x0, 0x0, 0x0, 0x0, 0x0)
E  	/go/src/golang.org/x/build/maintner/netsource.go:175 +0x136
E  golang.org/x/build/maintner.(*netMutSource).getNewSegments(0xc420011260, 0x8c5320, 0xc42001a280, 0xc46437f3b0, 0x7f7f2a02c188, 0xc45cbc2d90, 0xc42015be01, 0x5fa87c)
E  	/go/src/golang.org/x/build/maintner/netsource.go:205 +0xbe
E  golang.org/x/build/maintner.(*netMutSource).sendMutations(0xc420011260, 0x8c5320, 0xc42001a280, 0xc4611b6660, 0x0, 0x0)
E  	/go/src/golang.org/x/build/maintner/netsource.go:335 +0x46
E  golang.org/x/build/maintner.(*netMutSource).GetMutations.func1(0xc420011260, 0x8c5320, 0xc42001a280, 0xc4611b6660)
E  	/go/src/golang.org/x/build/maintner/netsource.go:61 +0x67
E  created by golang.org/x/build/maintner.(*netMutSource).GetMutations
E  	/go/src/golang.org/x/build/maintner/netsource.go:70 +0x7f
E  
E  goroutine 14 [sleep]:
E  time.Sleep(0xdf8475800)
E  	/usr/local/go/src/runtime/time.go:59 +0xf9
E  main.pollGerritAndTickle()
E  	/go/src/golang.org/x/build/cmd/gitmirror/gitmirror.go:1413 +0x1f3
E  created by main.main
E  	/go/src/golang.org/x/build/cmd/gitmirror/gitmirror.go:113 +0x115
E  
E  goroutine 15 [select, 3 minutes]:
E  golang.org/x/build/maintner.(*Corpus).update(0xc42000ae00, 0x8c5320, 0xc42001a280, 0x8c3820, 0x90e810, 0x0, 0x0)
E  	/go/src/golang.org/x/build/maintner/maintner.go:299 +0x43d
E  golang.org/x/build/maintner.(*Corpus).Update(0xc42000ae00, 0x8c5320, 0xc42001a280, 0x0, 0x0)
E  	/go/src/golang.org/x/build/maintner/maintner.go:259 +0xe0
E  main.subscribeToMaintnerAndTickle(0x431b68, 0x77f0d0)
E  	/go/src/golang.org/x/build/cmd/gitmirror/gitmirror.go:1462 +0x207
E  main.subscribeToMaintnerAndTickleLoop()
E  	/go/src/golang.org/x/build/cmd/gitmirror/gitmirror.go:1421 +0x26
E  created by main.main
E  	/go/src/golang.org/x/build/cmd/gitmirror/gitmirror.go:114 +0x12d
E  
E  goroutine 56 [IO wait, 5 minutes]:
E  net.runtime_pollWait(0x7f7f2a0aebe0, 0x72, 0x8c1ee0)
E  	/usr/local/go/src/runtime/netpoll.go:164 +0x59
E  net.(*pollDesc).wait(0xc42013c378, 0x72, 0x8be5d8, 0xc420116560)
E  	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
E  net.(*pollDesc).waitRead(0xc42013c378, 0xffffffffffffffff, 0x0)
E  	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
E  net.(*netFD).accept(0xc42013c310, 0x0, 0x8c0aa0, 0xc420116560)
E  	/usr/local/go/src/net/fd_unix.go:430 +0x1e5
E  net.(*TCPListener).accept(0xc42013e088, 0xc420112720, 0x701220, 0x8e72d0)
E  	/usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
E  net.(*TCPListener).Accept(0xc42013e088, 0xc4201126f0, 0x701220, 0x8e72d0, 0x734ce0)
E  	/usr/local/go/src/net/tcpsock.go:228 +0x49
E  net/http.(*Server).Serve(0xc4201ac000, 0x8c4b20, 0xc42013e088, 0x0, 0x0)
E  	/usr/local/go/src/net/http/server.go:2643 +0x228
E  net/http.Serve(0x8c4b20, 0xc42013e088, 0x0, 0x0, 0x0, 0x0)
E  	/usr/local/go/src/net/http/server.go:2307 +0x78
E  created by main.runGitMirror
E  	/go/src/golang.org/x/build/cmd/gitmirror/gitmirror.go:184 +0x80c
E  
E  goroutine 93 [select]:
E  main.(*Repo).Loop(0xc4206ea900)
E  	/go/src/golang.org/x/build/cmd/gitmirror/gitmirror.go:588 +0x20e
E  main.runGitMirror.func1(0xc42028c800, 0x8, 0xc4202f9660, 0x15, 0x0)
E  	/go/src/golang.org/x/build/cmd/gitmirror/gitmirror.go:216 +0x2d1
E  created by main.runGitMirror
E  	/go/src/golang.org/x/build/cmd/gitmirror/gitmirror.go:233 +0x6ee
E  
E  goroutine 97 [semacquire]:
E  sync.runtime_SemacquireMutex(0x90e9f4)
E  	/usr/local/go/src/runtime/sema.go:62 +0x34
E  sync.(*Mutex).Lock(0x90e9f0)
E  	/usr/local/go/src/sync/mutex.go:87 +0x9d
E  sync.(*RWMutex).Lock(0x90e9f0)
E  	/usr/local/go/src/sync/rwmutex.go:86 +0x2d
E  syscall.forkExec(0xc460827430, 0xc, 0xc4610e1720, 0x2, 0x2, 0xc451471750, 0x0, 0x0, 0xc464082410)
E  	/usr/local/go/src/syscall/exec_unix.go:185 +0x1fd
E  syscall.StartProcess(0xc460827430, 0xc, 0xc4610e1720, 0x2, 0x2, 0xc420808750, 0x2, 0x4, 0xc420018140, 0xc420808720)
E  	/usr/local/go/src/syscall/exec_unix.go:240 +0x64
E  os.startProcess(0xc460827430, 0xc, 0xc4610e1720, 0x2, 0x2, 0xc4208088f8, 0xc45ca39800, 0x79, 0x79)
E  	/usr/local/go/src/os/exec_posix.go:45 +0x1a3
E  os.StartProcess(0xc460827430, 0xc, 0xc4610e1720, 0x2, 0x2, 0xc4208088f8, 0x0, 0x0, 0xc4208088c8)
E  	/usr/local/go/src/os/exec.go:94 +0x64
E  os/exec.(*Cmd).Start(0xc463ba0580, 0x8c35a0, 0xc464097f58)
E  	/usr/local/go/src/os/exec/exec.go:359 +0x3d2
E  main.parseRefs(0xc463ba0580, 0x3, 0xc420808ab0, 0x1)
E  	/go/src/golang.org/x/build/cmd/gitmirror/gitmirror.go:1515 +0x13a
E  main.(*Repo).getLocalRefs(0xc42054d200, 0x7724cb, 0x19, 0x497ce7)
E  	/go/src/golang.org/x/build/cmd/gitmirror/gitmirror.go:1490 +0xa3
E  main.(*Repo).push.func2(0x0, 0xc420808da8)
E  	/go/src/golang.org/x/build/cmd/gitmirror/gitmirror.go:1097 +0x84
E  main.try(0x3, 0xc451471dd0, 0xc420808e00, 0xc42054d200)
E  	/go/src/golang.org/x/build/cmd/gitmirror/gitmirror.go:1260 +0x55
E  main.(*Repo).push(0xc42054d200, 0x0, 0x0)
E  	/go/src/golang.org/x/build/cmd/gitmirror/gitmirror.go:1160 +0xd8
E  main.(*Repo).Loop(0xc42054d200)
E  	/go/src/golang.org/x/build/cmd/gitmirror/gitmirror.go:568 +0x271
E  main.runGitMirror.func1(0xc42028c396, 0xa, 0xc4202f9860, 0x17, 0x0)
E  	/go/src/golang.org/x/build/cmd/gitmirror/gitmirror.go:216 +0x2d1
E  created by main.runGitMirror
E  	/go/src/golang.org/x/build/cmd/gitmirror/gitmirror.go:233 +0x6ee
```

/cc @bradfitz

**Comment by bradfitz** [comment]
We just discovered it was OOM'ing the other day and increased it. I suspect that's what this was?

Closing for now.
