### ISSUE TITLE
cmd/go: crash in go list -e -test

### ISSUE THREAD

**Issue by alandonovan** [golang/go#25980]
```
$ cat src/p/d.go
package d
$ cat src/p/x_test.go
package d_test; import _ "d"
$ go version
go version devel +b7d9e6e149 Mon Jun 18 11:53:40 2018 +0000 linux/amd64
$ GOPATH=$(pwd) go list -e -test p
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x82b5fd]

goroutine 1 [running]:
cmd/go/internal/list.runList(0xcd30c0, 0xc00001e0d0, 0x1, 0x1)
        /usr/local/google/home/adonovan/go/src/cmd/go/internal/list/list.go:287 +0x10ed
main.main()
        /usr/local/google/home/adonovan/go/src/cmd/go/main.go:140 +0x51d
```

**Comment by andybons** [comment]
@gopherbot add label NeedsFix

**Comment by ianlancetaylor** [comment]
CC @bcmills
