### ISSUE TITLE
cmd/compile: internal compiler error: autotmp_17 recorded as live on entry

### ISSUE THREAD

**Issue by ALTree** [golang/go#26105]
```
$ gotip version
go version devel +257d6c48e0 Thu Jun 28 03:12:01 2018 +0000 linux/amd64
```

The following program (reduced from a gosmith-generated one):

```
package p

var S interface{}

func F(n int) {
	f := 1
	fun := func(chan int) int {
		S = f
		return n
	}
	i := fun(([]chan int{})[n])

	var fc [2]chan int
	_ = <-(([...][2]chan int{fc})[i][i])
}
```

crashes the tip compiler with the following error:

```
$ gotip build crash.go 
# command-line-arguments
<autogenerated>:1: internal compiler error: internal error: F .autotmp_17 (type [1][2]chan int) recorded as live on entry

goroutine 8 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/home/alberto/go/src/runtime/debug/stack.go:24 +0xa7
cmd/compile/internal/gc.Fatalf(0xcc628d, 0x2f, 0xc00053b968, 0x2, 0x2)
	/home/alberto/go/src/cmd/compile/internal/gc/subr.go:182 +0x1f7
cmd/compile/internal/gc.(*Liveness).epilogue(0xc0004e4160)
	/home/alberto/go/src/cmd/compile/internal/gc/plive.go:1159 +0x1642
cmd/compile/internal/gc.liveness(0xc0004dc000, 0xc0004e0000, 0x0, 0x0, 0x0)
	/home/alberto/go/src/cmd/compile/internal/gc/plive.go:1690 +0xc4
cmd/compile/internal/gc.genssa(0xc0004e0000, 0xc00050e150)
	/home/alberto/go/src/cmd/compile/internal/gc/ssa.go:4820 +0xbe
cmd/compile/internal/gc.compileSSA(0xc00035c000, 0x1)
	/home/alberto/go/src/cmd/compile/internal/gc/pgen.go:269 +0x1bc
cmd/compile/internal/gc.compileFunctions.func2(0xc00036b740, 0xc000016730, 0x1)
	/home/alberto/go/src/cmd/compile/internal/gc/pgen.go:323 +0x49
created by cmd/compile/internal/gc.compileFunctions
	/home/alberto/go/src/cmd/compile/internal/gc/pgen.go:321 +0x11a
```

It compiles fine on go1.10.

**Comment by ALTree** [comment]
git bisect points to 5c40210987844c7a64eb0bfcb781ed865d9c4b7f (cmd/compile: in prove, add transitive closure of relations) as the first bad commit.

cc @rasky @dr2chase @aclements

**Comment by dr2chase** [comment]
Glorious 🙄. Thanks, will look.

**Comment by josharian** [comment]
Fix was reverted.
