### ISSUE TITLE
cmd/compile: noopt and ssacheck builders broken since CL 121436

### ISSUE THREAD

**Issue by mvdan** [golang/go#26140]
They both went from all green to all red, so the CL seems like a clear candidate: https://go-review.googlesource.com/c/go/+/121436

Two samples:

https://build.golang.org/log/e889d63b84cbfa1cc0fcab45a759747e0055afed
https://build.golang.org/log/9026910896d6f346ec431de4e6a16683d2d496ea

/cc @dr2chase

**Comment by dr2chase** [comment]
It is being glared at, even now.

**Comment by siebenmann** [comment]
I get a consistent failure during tests after this CL (determined from `git bisect`) on Fedora 27 amd64:

````
--- FAIL: TestLldbPython (2.18s)
    runtime-lldb_test.go:166: building source exit status 2
        # unicode
        <autogenerated>:1: internal compiler error: panic during regalloc while compiling init:
        
        runtime error: invalid memory address or nil pointer dereference
        
        goroutine 16 [running]:
        cmd/compile/internal/ssa.Compile.func1(0xc001a97218, 0xc0003b4160)
                /data/code/go-lang/go/src/cmd/compile/internal/ssa/compile.go:38 +0xc6
        panic(0xc4bc20, 0x12fe7a0)
                /data/code/go-lang/go/src/runtime/panic.go:494 +0x1b9
        cmd/compile/internal/ssa.(*regAllocState).allocReg(0xc000371500, 0xffcf, 0xc001724e70, 0x600000001)
                /data/code/go-lang/go/src/cmd/compile/internal/ssa/regalloc.go:408 +0x105
        cmd/compile/internal/ssa.(*regAllocState).regalloc(0xc000371500, 0xc0003b4160)
                /data/code/go-lang/go/src/cmd/compile/internal/ssa/regalloc.go:1455 +0x1e23
        cmd/compile/internal/ssa.regalloc(0xc0003b4160)
                /data/code/go-lang/go/src/cmd/compile/internal/ssa/regalloc.go:145 +0x62
        cmd/compile/internal/ssa.Compile(0xc0003b4160)
                /data/code/go-lang/go/src/cmd/compile/internal/ssa/compile.go:70 +0x30e
        cmd/compile/internal/gc.buildssa(0xc00041fa20, 0x1, 0x0)
                /data/code/go-lang/go/src/cmd/compile/internal/gc/ssa.go:211 +0xaa7
        cmd/compile/internal/gc.compileSSA(0xc00041fa20, 0x1)
                /data/code/go-lang/go/src/cmd/compile/internal/gc/pgen.go:259 +0x39
        cmd/compile/internal/gc.compileFunctions.func2(0xc001434ba0, 0xc0013d3b20, 0x1)
                /data/code/go-lang/go/src/cmd/compile/internal/gc/pgen.go:323 +0x49
        created by cmd/compile/internal/gc.compileFunctions
                /data/code/go-lang/go/src/cmd/compile/internal/gc/pgen.go:321 +0x11a
        
        
        
        goroutine 16 [running]:
        runtime/debug.Stack(0x0, 0x0, 0x0)
                /data/code/go-lang/go/src/runtime/debug/stack.go:24 +0xa7
        cmd/compile/internal/gc.Fatalf(0xcc5088, 0x2c, 0xc0006508c0, 0x4, 0x4)
                /data/code/go-lang/go/src/cmd/compile/internal/gc/subr.go:182 +0x1f7
        cmd/compile/internal/gc.(*ssafn).Fatalf(0xc00148a000, 0x100000000001, 0xcc5088, 0x2c, 0xc0006508c0, 0x4, 0x4)
                /data/code/go-lang/go/src/cmd/compile/internal/gc/ssa.go:5584 +0x67
        cmd/compile/internal/ssa.(*Func).Fatalf(0xc0003b4160, 0xcc5088, 0x2c, 0xc0006508c0, 0x4, 0x4)
                /data/code/go-lang/go/src/cmd/compile/internal/ssa/func.go:562 +0x73
        cmd/compile/internal/ssa.Compile.func1(0xc001a97218, 0xc0003b4160)
                /data/code/go-lang/go/src/cmd/compile/internal/ssa/compile.go:40 +0x23a
        panic(0xc4bc20, 0x12fe7a0)
                /data/code/go-lang/go/src/runtime/panic.go:494 +0x1b9
        cmd/compile/internal/ssa.(*regAllocState).allocReg(0xc000371500, 0xffcf, 0xc001724e70, 0x600000001)
                /data/code/go-lang/go/src/cmd/compile/internal/ssa/regalloc.go:408 +0x105
        cmd/compile/internal/ssa.(*regAllocState).regalloc(0xc000371500, 0xc0003b4160)
                /data/code/go-lang/go/src/cmd/compile/internal/ssa/regalloc.go:1455 +0x1e23
        cmd/compile/internal/ssa.regalloc(0xc0003b4160)
                /data/code/go-lang/go/src/cmd/compile/internal/ssa/regalloc.go:145 +0x62
        cmd/compile/internal/ssa.Compile(0xc0003b4160)
                /data/code/go-lang/go/src/cmd/compile/internal/ssa/compile.go:70 +0x30e
        cmd/compile/internal/gc.buildssa(0xc00041fa20, 0x1, 0x0)
                /data/code/go-lang/go/src/cmd/compile/internal/gc/ssa.go:211 +0xaa7
        cmd/compile/internal/gc.compileSSA(0xc00041fa20, 0x1)
                /data/code/go-lang/go/src/cmd/compile/internal/gc/pgen.go:259 +0x39
        cmd/compile/internal/gc.compileFunctions.func2(0xc001434ba0, 0xc0013d3b20, 0x1)
                /data/code/go-lang/go/src/cmd/compile/internal/gc/pgen.go:323 +0x49
        created by cmd/compile/internal/gc.compileFunctions
                /data/code/go-lang/go/src/cmd/compile/internal/gc/pgen.go:321 +0x11a
        
FAIL
FAIL    runtime 23.687s
````

**Comment by josharian** [comment]
The CL was reverted.
