### ISSUE TITLE
os: Remove/RemoveAll should remove read-only folders on Windows

### ISSUE THREAD

**Issue by Nnnes** [golang/go#26295]
### What version of Go are you using (`go version`)?
`go version go1.10.2 windows/amd64`
### Does this issue reproduce with the latest release?
Untested, but I don't see any changes that would have fixed it
### What operating system and processor architecture are you using (`go env`)?
`windows/amd64`
### What did you do?
```go
package main

import (
	"os"
)

func main() {
	err := os.RemoveAll("./folder_with_icon")
	if err != nil {
		panic(err)
	}
}
```
`folder_with_icon` is an empty folder that has had a custom icon added via Windows Explorer's interface (`Properties` => `Customize` => `Change Icon...`).
### What did you expect to see?
`folder_with_icon` should be deleted.
### What did you see instead?
```
panic: remove ./folder_with_icon: Access is denied.

goroutine 1 [running]:
main.main()
        C:/[path]/test.go:10 +0x6a
```
### Notes
This is similar to #9606.

Setting a custom folder icon on Windows sets the `read-only` attribute on the folder and creates a `desktop.ini` file with the `system` attribute inside the folder. Despite being read-only, the folder can be deleted both through File Explorer and by `rd /s folder_with_icon` by its owner, even if the owner is not an administrator account. The above Go program will not delete the folder, even if it is run with administrator privileges.

`os.RemoveAll()` removes the `desktop.ini` but does not delete the folder.

**Comment by ianlancetaylor** [comment]
By analogy with #9606 it seems that we should do this.

**Comment by oryanmoshe** [comment]
I'm working on it

**Comment by Nnnes** [comment]
This issue is only half fixed. As stated in the title, `os.Remove()` had the same problem as `os.RemoveAll()` for read-only directories. Using Go 1.14:
```go
package main

import (
	"fmt"
	"io/ioutil"
	"os"
)

func main() {
	path := "./folder_with_icon"
	fmt.Println(count_files(path))
	err := os.Remove(path + "/desktop.ini")
	if err != nil {
		panic(err)
	}
	fmt.Println(count_files(path)) // works fine up to here
	err = os.Remove(path)
	if err != nil {
		panic(err)
	}
}

func count_files(path string) int {
	files, _ := ioutil.ReadDir(path)
	return len(files)
}
```
As before, `folder_with_icon` is a folder with a custom icon.
```
C:\[path]>26295.exe
1
0
panic: remove ./folder_with_icon: Access is denied.

goroutine 1 [running]:
main.main()
        C:/[path]/26295.go:19 +0x1d5
```

**Comment by bcmills** [comment]
The analogy to #9606 does not seem to hold: while Unix systems do allow read-only files to be removed from read-write directories, they do not generally allow files to be removed _from within_ a read-only directory without first making the directory writable.

That subtlety is what led us to add the `-modcacherw` flag to `cmd/go` in 1.14 (see #31481).

**Comment by iWdGo** [comment]
The difference of behavior between Remove and RemoveAll is stated in the [documentation](https://golang.org/pkg/os/#RemoveAll)

> RemoveAll removes path and any children it contains. It removes everything it can

os.Remove will only attempt removal and return the error.
This behavior seems desirable even if support to read-only is discussed #35042

**Comment by bcmills** [comment]
@iWdGo, my point is that the proposed change here makes `RemoveAll` on Windows remove _more_ than it does on Unix, but the justification given is consistency with Unix. That doesn't seem right.

If folks want to argue that the behavior on Unix should be expanded to be consistent with the documentation, that's fine by me, but then this issue would not be Windows-specific.

**Comment by iWdGo** [comment]
@bcmills The original issue was on Windows and the difference with Unix seems to start in Go1.12 as #29983 details.

The [comment](https://github.com/golang/go/blob/14d20dc4f38dda548f6991cc687bc71b250b1603/src/os/removeall_at.go#L67) in _at code and what follows does not seem to consider an update of permissions in RemoveAll.

This [test](https://github.com/golang/go/blob/14d20dc4f38dda548f6991cc687bc71b250b1603/src/os/removeall_test.go#L288) expects read-only directories to remain. It is skipped on Windows for the same reason. If this would change, an error would be returned when permission is insufficient although `nil` seems currently returned. I agree that RemoveAll on Unix could be doing more.

**Comment by bcmills** [comment]
@iWdGo, #29983 describes a situation in which _files within_ a writable directory were not remove when that directory was itself within a read-only directory. That situation does not seem very closely related to the one described here.

**Comment by iWdGo** [comment]
@bcmills IMHO, RemoveAll on Unix should attempt a permission update but it was not in the scope of the issue as originally filed. Such a change for Unix would seem along the line of past comments.

**Comment by bcmills** [comment]
> RemoveAll on Unix should attempt a permission update but it was not in the scope of the issue as originally filed. Such a change for Unix would seem along the line of past comments.

That seems fine to me, but that should be a separate issue — and implementing the behavior described in _this_ issue should probably wait for a decision on the broader (cross-platform) `RemoveAll` behavior.

**Comment by odeke-em** [comment]
Moving to Go1.17.

**Comment by Nnnes** [comment]
For the sake of completeness, here's the official Microsoft documentation on read-only attributes on Windows folders: 

> FILE_ATTRIBUTE_READONLY 1 (0x00000001)
> A file that is read-only. Applications can read the file, but cannot write to it or delete it. This attribute is not honored on directories. For more information, see [You cannot view or change the Read-only or the System attributes of folders in Windows Server 2003, in Windows XP, in Windows Vista or in Windows 7](https://support.microsoft.com/kb/326549).

(source: https://learn.microsoft.com/en-us/windows/win32/fileio/file-attribute-constants#file_attribute_readonly)

Excerpt from the linked article:

> Note Unlike the Read-only attribute for a file, the Read-only attribute for a folder is typically ignored by Windows, Windows components and accessories, and other programs. For example, you can delete, rename, and change a folder with the Read-only attribute by using Windows Explorer.
> The Read-only and System attributes is only used by Windows Explorer to determine whether the folder is a special folder...

**Comment by bcmills** [comment]
(CC @golang/windows)

**Comment by qmuntal** [comment]
Looking at what other frameworks do, and there are a few that discard the readonly attribute for either files and folders:

- microsoft/stl: https://github.com/microsoft/STL/blob/c53ac59abae552e50654943f7f80f23376a8039a/stl/src/filesystem.cpp#L578
- boostorg/filesystem: https://github.com/boostorg/filesystem/blob/6f174ba14369143d28ae72f4c697660c65cecae6/src/operations.cpp#L1895C13-L1895C145
- node/libuv: https://github.com/libuv/libuv/pull/4318
- zig: https://github.com/ziglang/zig/blob/dd1fc1cb8c2258256566fd0035deb6fbf700fc69/lib/std/os/windows.zig#L916
