### ISSUE TITLE
x/text: "gotext extract" command crash if no messages

### ISSUE THREAD

**Issue by Chocanto** [golang/go#26312]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.9.2

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
windows/amd64

### What did you do?

Run `gotext extract` command on a project directory without any messages to extract and no `golang.org/x/text/message` import.

### What did you expect to see?

A blank or error response.

### What did you see instead?

A runtime error :

```
>gotext extract
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x866423]

goroutine 1 [running]:
golang.org/x/text/message/pipeline.(*extracter).seedEndpoints(0xc0421c6000)
        C:/GO-projects/src/golang.org/x/text/message/pipeline/extract.go:100 +0x63
golang.org/x/text/message/pipeline.Extract(0xc0420dc750, 0x1, 0x1, 0x0)
        C:/GO-projects/src/golang.org/x/text/message/pipeline/extract.go:45 +0x5c
main.runExtract(0xd6c4c0, 0xc0420dc750, 0xc042046390, 0x0, 0x0, 0x0, 0x0)
        C:/GO-projects/src/golang.org/x/text/cmd/gotext/extract.go:29 +0x63
main.main()
        C:/GO-projects/src/golang.org/x/text/cmd/gotext/main.go:150 +0x34e
```

**Comment by meirf** [comment]
Looks like this started with https://github.com/golang/text/commit/2cb43934f0eece38629746959acc633cba083fe4 "message/pipeline: use ssa and callgraph":

Specifically on [this line](https://github.com/golang/text/commit/2cb43934f0eece38629746959acc633cba083fe4#diff-39c67767612dd716a72eefd00340e739R93) where there is no check whether `Program.Package`'s returned `PackageInfo` is nil.

**Comment by mvrhov** [comment]
I've also hit this as I'm testing the library. IMO the executable should say that there is no translation strings to extract.
However I'd say that the extract command doesn't work per se.

```go
func (me *LoginFormData) Validate(r *http.Request) error {
	T := context.GetDataFromContext(r.Context()).Trans

	 _= T.Sprint("The email address you entered is not valid")) //TRANS:

	return nil
}
```

Will also fail with above error.. And I think this will be a common usecase

**Comment by olivere** [comment]
FWIW I've started to dig deeper into this issue and this is what I found.

I get this error when using vendored dependencies with e.g. `dep`. The reasons seems to be that the `x.iprog.Package("golang.org/x/text/message")` in ...

```
pkg := x.prog.Package(x.iprog.Package("golang.org/x/text/message").Pkg)
```

... is `nil` because the `x.iprog *ssa.Program` will only find the vendored dependency (e.g. `github.com/myorg/myproject/vendor/golang.org/x/text/message`) but not `golang.org/x/text/message`.

**Comment by msama** [comment]
We are having the same issue with vendored dependencies:
```
gotext: extract failed: pipeline: golang.org/x/text/message is not imported
```

Is it there a workaround?

**Comment by koalado** [comment]
Having the same issue when using a vendor folder. When the vendor folder is removed, it works. I just revendor afterwards for the moment.

**Comment by dragon9783** [comment]
@fgm Hello, how to add `import _ "golang.org/x/text/message` at the top-level import? Can you share some code snippet?

**Comment by fgm** [comment]
@dragon9783 this little line _is_ the code snippet: just add it at the top-level package of your library/command (the main package if it's a command)/

**Comment by roman-popenov** [comment]
I still have the same issue, and `import _ "golang.org/x/text/message` at the top-level import doesn't seem to solve it.

**Comment by roman-popenov** [comment]
I have solved the issue by running rm -rf vendor/golang.org/x/text command from the root of the project. Of course for things to work, I also needed to have gotext installed. This can be done by running go get golang.org/x/text/cmd/gotext.

**Comment by roman-popenov** [comment]
I believe the issue could be solved if binaries of `text/message` are installed in the `GOPATH/bin` as well
