### ISSUE TITLE
math/big: TestProbablyPrime crash

### ISSUE THREAD

**Issue by bradfitz** [golang/go#27112]
https://storage.googleapis.com/go-build-log/aaf58d79/windows-amd64-2016_06d45596.log

```
--- FAIL: TestProbablyPrime (0.10s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x5a6cfb]

goroutine 155 [running]:
testing.tRunner.func1(0xc000204600)
	C:/workdir/go/src/testing/testing.go:799 +0x38e
panic(0x643fc0, 0x84d000)
	C:/workdir/go/src/runtime/panic.go:513 +0x1c7
math/big.(*Int).ProbablyPrime(0x0, 0x3, 0x178)
	C:/workdir/go/src/math/big/prime.go:39 +0x3b
math/big.TestProbablyPrime(0xc000204600)
	C:/workdir/go/src/math/big/prime_test.go:140 +0x311
testing.tRunner(0xc000204600, 0x696b88)
	C:/workdir/go/src/testing/testing.go:834 +0xc6
created by testing.(*T).Run
	C:/workdir/go/src/testing/testing.go:885 +0x35a
FAIL	math/big	0.608s
```

/cc @griesemer

**Comment by bradfitz** [comment]
Actually, this might just be @fraenkel's change causing this:
https://go-review.googlesource.com/c/go/+/122875

@fraenkel could you check?

**Comment by bradfitz** [comment]
Yeah, TestProbablyPrime uses strings.Map. False alarm. CL needs work.
