### ISSUE TITLE
x/build/maintner: panic nil Timestamp for issue creation

### ISSUE THREAD

**Issue by broady** [golang/go#27493]
Running a copy of maintnerd, this happens on the client:

```
panic: timestamp: nil Timestamp

goroutine 25 [running]:
golang.org/x/build/maintner.(*Corpus).processGithubIssueMutation(0xb7a6e0, 0xc42476e160)
        /usr/local/google/home/cbro/src/golang.org/x/build/maintner/github.go:1186 +0x1b19
golang.org/x/build/maintner.(*Corpus).processMutationLocked(0xb7a6e0, 0xc42b9c8c00)
        /usr/local/google/home/cbro/src/golang.org/x/build/maintner/maintner.go:351 +0xaf
golang.org/x/build/maintner.(*Corpus).update(0xb7a6e0, 0x9383c0, 0xc4200be010, 0x936960, 0xb97fd0, 0x0, 0x0)
        /usr/local/google/home/cbro/src/golang.org/x/build/maintner/maintner.go:322 +0x152
golang.org/x/build/maintner.(*Corpus).UpdateWithLocker(0xb7a6e0, 0x9383c0, 0xc4200be010, 0x936960, 0xb97fd0, 0x0, 0x0)
        /usr/local/google/home/cbro/src/golang.org/x/build/maintner/maintner.go:280 +0xcf
main.main.func1(0x9383c0, 0xc4200be010)
```

It looks like restarting the process (ie, re-processing the mutations) works around this.

It looks like it's the timestamp for issue creation:
https://github.com/golang/build/blob/e7a2a012f38a99c659a95fa79309f521fe769cee/maintner/github.go#L1183-L1187

I'll look into this more.

**Comment by broady** [comment]
Well, deleting the disk log and re-running didn't do anything.
