### ISSUE TITLE
cmd/compile: 'panic during opt while compiling testfloat' on mipsle

### ISSUE THREAD

**Issue by bcmills** [golang/go#27685]
From https://build.golang.org/log/cd8d650b595dbcdd0a0df672b432c6b29837c490:

```
##### ../test
# go run run.go -- map.go
exit status 2
# command-line-arguments
./map.go:515:31: internal compiler error: 'testfloat': panic during opt while compiling testfloat:

truncate64Fto32F: truncation is not exact

goroutine 7 [running]:
cmd/compile/internal/ssa.Compile.func1(0x191f8c0, 0x182e0b0)
	/data/mipsle/go/src/cmd/compile/internal/ssa/compile.go:38 +0xb8
panic(0x929d60, 0xafc018)
	/data/mipsle/go/src/runtime/panic.go:513 +0x1f4
cmd/compile/internal/ssa.truncate64Fto32F(0xffffffff, 0x7ff7ffff, 0x4)
	/data/mipsle/go/src/cmd/compile/internal/ssa/rewrite.go:425 +0x158
cmd/compile/internal/ssa.rewriteValuegeneric_OpLoad_0(0x179e604, 0x280900)
	/data/mipsle/go/src/cmd/compile/internal/ssa/rewritegeneric.go:13559 +0xabc
cmd/compile/internal/ssa.rewriteValuegeneric(0x179e604, 0x0)
	/data/mipsle/go/src/cmd/compile/internal/ssa/rewritegeneric.go:211 +0x2a48
cmd/compile/internal/ssa.applyRewrite(0x182e0b0, 0x997a30, 0x997a60)
	/data/mipsle/go/src/cmd/compile/internal/ssa/rewrite.go:78 +0x5ac
cmd/compile/internal/ssa.opt(0x182e0b0)
	/data/mipsle/go/src/cmd/compile/internal/ssa/opt.go:9 +0x54
cmd/compile/internal/ssa.Compile(0x182e0b0)
	/data/mipsle/go/src/cmd/compile/internal/ssa/compile.go:72 +0x314
cmd/compile/internal/gc.buildssa(0x168a240, 0x3, 0x0)
	/data/mipsle/go/src/cmd/compile/internal/gc/ssa.go:227 +0x734
cmd/compile/internal/gc.compileSSA(0x168a240, 0x3)
	/data/mipsle/go/src/cmd/compile/internal/gc/pgen.go:258 +0x44
cmd/compile/internal/gc.compileFunctions.func2(0x18aabc0, 0x1412a30, 0x3)
	/data/mipsle/go/src/cmd/compile/internal/gc/pgen.go:322 +0x54
created by cmd/compile/internal/gc.compileFunctions
	/data/mipsle/go/src/cmd/compile/internal/gc/pgen.go:320 +0x13c



goroutine 7 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/data/mipsle/go/src/runtime/debug/stack.go:24 +0xb0
cmd/compile/internal/gc.Fatalf(0x1465840, 0x32, 0x18a4d50, 0x5, 0x6)
	/data/mipsle/go/src/cmd/compile/internal/gc/subr.go:182 +0x20c
cmd/compile/internal/gc.(*ssafn).Fatalf(0x16700e0, 0x2, 0x2031f1, 0x98ea1a, 0x2c, 0x1a5e160, 0x4, 0x4)
	/data/mipsle/go/src/cmd/compile/internal/gc/ssa.go:5695 +0x19c
cmd/compile/internal/ssa.(*Func).Fatalf(0x182e0b0, 0x98ea1a, 0x2c, 0x1a5e160, 0x4, 0x4)
	/data/mipsle/go/src/cmd/compile/internal/ssa/func.go:575 +0x84
cmd/compile/internal/ssa.Compile.func1(0x191f8c0, 0x182e0b0)
	/data/mipsle/go/src/cmd/compile/internal/ssa/compile.go:40 +0x228
panic(0x929d60, 0xafc018)
	/data/mipsle/go/src/runtime/panic.go:513 +0x1f4
cmd/compile/internal/ssa.truncate64Fto32F(0xffffffff, 0x7ff7ffff, 0x4)
	/data/mipsle/go/src/cmd/compile/internal/ssa/rewrite.go:425 +0x158
cmd/compile/internal/ssa.rewriteValuegeneric_OpLoad_0(0x179e604, 0x280900)
	/data/mipsle/go/src/cmd/compile/internal/ssa/rewritegeneric.go:13559 +0xabc
cmd/compile/internal/ssa.rewriteValuegeneric(0x179e604, 0x0)
	/data/mipsle/go/src/cmd/compile/internal/ssa/rewritegeneric.go:211 +0x2a48
cmd/compile/internal/ssa.applyRewrite(0x182e0b0, 0x997a30, 0x997a60)
	/data/mipsle/go/src/cmd/compile/internal/ssa/rewrite.go:78 +0x5ac
cmd/compile/internal/ssa.opt(0x182e0b0)
	/data/mipsle/go/src/cmd/compile/internal/ssa/opt.go:9 +0x54
cmd/compile/internal/ssa.Compile(0x182e0b0)
	/data/mipsle/go/src/cmd/compile/internal/ssa/compile.go:72 +0x314
cmd/compile/internal/gc.buildssa(0x168a240, 0x3, 0x0)
	/data/mipsle/go/src/cmd/compile/internal/gc/ssa.go:227 +0x734
cmd/compile/internal/gc.compileSSA(0x168a240, 0x3)
	/data/mipsle/go/src/cmd/compile/internal/gc/pgen.go:258 +0x44
cmd/compile/internal/gc.compileFunctions.func2(0x18aabc0, 0x1412a30, 0x3)
	/data/mipsle/go/src/cmd/compile/internal/gc/pgen.go:322 +0x54
created by cmd/compile/internal/gc.compileFunctions
	/data/mipsle/go/src/cmd/compile/internal/gc/pgen.go:320 +0x13c


FAIL	map.go	1.008s
```

(CC: @randall77 @josharian @martisch)

**Comment by mvdan** [comment]
Dup of https://github.com/golang/go/issues/27142?

**Comment by bcmills** [comment]
Similar symptom, but different enough that it's not obvious to me whether the cause is the same.

**Comment by randall77** [comment]
Yes, definitely related to #27516 . Unlikely to have anything to do with #27142.
@mundaym

**Comment by ianlancetaylor** [comment]
This error happened regularly on the builders between 2018-09-05 and 2018-09-17, and never since then.  Closing as fixed.
