### ISSUE TITLE
Empty action in template creates panic

### ISSUE THREAD

**Issue by johandalabacka** [golang/go#27798]
### What version of Go are you using (`go version`)?

go version go1.11 darwin/amd64

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

go playground

and

```
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/xxxx/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/xxxx/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/pq/mxp7g_fd5wj6n3fzd8nm9bf8tylprx/T/go-build736706411=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
### What did you do?

```go
package main

import (
	"os"
	"text/template"
)

func main() {
	tmpl, _ := template.New("").Parse("Hello {{  }}!\n")
	tmpl.Execute(os.Stdout, "World")
}
```

### What did you expect to see?
Either a warning about an empty action or just the text "Hello !" 

### What did you see instead?

A panic
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0xffffffff addr=0x0 pc=0x132a0f]

goroutine 1 [running]:
text/template.errRecover(0x1052ff68, 0xe)
	/usr/local/go/src/text/template/exec.go:137 +0x240
panic(0x167e80, 0x22d418)
	/usr/local/go/src/runtime/panic.go:502 +0x2c0
text/template.(*Template).execute(0x0, 0x1ab790, 0x1050c0f8, 0x164300, 0x1aafb8, 0x328b, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:191 +0x18f
text/template.(*Template).Execute(0x0, 0x1ab790, 0x1050c0f8, 0x164300, 0x1aafb8, 0x1ab710, 0x1050c190, 0x0)
	/usr/local/go/src/text/template/exec.go:177 +0x60
main.main()
	/tmp/sandbox337928814/main.go:10 +0xc0
```

**Comment by johandalabacka** [comment]
I'm an idiot. I forgot to put template.Must around the parse function

```go
package main

import (
	"os"
	"text/template"
)

func main() {
	tmpl := template.Must(template.New("").Parse("Hello {{  }}!\n"))
	tmpl.Execute(os.Stdout, "World")
}
```

works much better

```
panic: template: :1: missing value for command

goroutine 1 [running]:
text/template.Must(...)
        /usr/local/Cellar/go/1.11/libexec/src/text/template/helper.go:23
main.main()
        /Users/xxxx/projects/go/test1/test11/main.go:9 +0x19d
exit status 2
```
