### ISSUE TITLE
x/net/html: panic: runtime error: index out of range

### ISSUE THREAD

**Issue by tr3ee** [golang/go#27846]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

`go version go1.10.3 windows/amd64`

### Does this issue reproduce with the latest release?

`yes`

### What operating system and processor architecture are you using (`go env`)?

```
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GORACE=
set GOTMPDIR=
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
```

### What did you do?

```Go
package main

import (
	"strings"

	"golang.org/x/net/html"
)

func main() {
	r := strings.NewReader("<math><template><mn><b></template>")
	html.Parse(r)
}
```

### What did you expect to see?

`No panic exit`

### What did you see instead?

```
panic: runtime error: index out of range

goroutine 1 [running]:
golang.org/x/net/html.(*insertionModeStack).pop(...)
        /path/to/gopath/src/golang.org/x/net/html/node.go:210
golang.org/x/net/html.inHeadIM(0xc042056340, 0x40)
        /path/to/gopath/src/golang.org/x/net/html/parse.go:676 +0x74f
golang.org/x/net/html.inBodyIM(0xc042056340, 0x0)
        /path/to/gopath/src/golang.org/x/net/html/parse.go:1138 +0x3425
golang.org/x/net/html.(*parser).parseCurrentToken(0xc042056340)
        /path/to/gopath/src/golang.org/x/net/html/parse.go:2192 +0x8b
golang.org/x/net/html.(*parser).parse(0xc042056340, 0xc0420b6000, 0xc042056270)
        /path/to/gopath/src/golang.org/x/net/html/parse.go:2218 +0x62
golang.org/x/net/html.Parse(0x4e14c0, 0xc042054460, 0xc0420701e0, 0xc042079f78, 0xc042048058)
        /path/to/gopath/src/golang.org/x/net/html/parse.go:2244 +0xe2
main.main()
        /path/to/gopath/src/main.go:11 +0x7a
exit status 2
```

**Comment by odeke-em** [comment]
Thank you for reporting these bugs @tr3ee! You are on a roll, nice.
/cc @nigeltao @namusyaka @bradfitz

Perhaps this calls for us to fuzz the x/net/html package /cc @dgryski @dvyukov

**Comment by tr3ee** [comment]
> > is it OK to use go-fuzz inside x/net/html?
> 
> What exactly do you mean?

I just learned about [go-fuzz](https://github.com/dvyukov/go-fuzz) project and wrote some ugly code https://github.com/tr3ee/net/commit/a59147add47860171d2eadfdd5ebfaf044b714e8

but it works fine for me and already found a crasher.

```
	"[template]<table></>" +
	"<table><table><_333J" +
	"__Nl1nimuwV_0_t80x_T" +
	"ACB_bic_><table>1_mq" +
	"kW3Y1uzD<table><tabl" +
	"e><__N2_bv__wq_Jqb_4" +
	"x_2i3_pP71A3F_AxqBdv" +
	"L_46_LD_f0_iH_4Jrs_y" +
	"z4L28Kq36Z_E6____ra3" +
	"Tv_><table><table><t" +
	"able><EW><table><tab" +
	"le><table><table>{ta" +
	"ble}<><table><_>{tab" +
	"letableE}<><table><t" +
	"able>[table]<table><" +
	"><><table><table><ta" +
	"ble><table><><tablel" +
	"4cg1_na_5b70h2Qu8Dv_" +
	"Y__T__RY_G>(table)<t" +
	"able><table><table><" +
	"table><table><table>" +
	"<table><<svg><3_><de" +
	"sc><><select>\x00<><><d" +
	"esc><select>\"select\"" +
	"\x00<svg><html><desc><>" +
	"`u3_>\x00<svg><html><D9" +
	"9><select><select>}<" +
	"><html><&><select><>" +
	")<svg>/table<desc><s" +
	"elect><select>\x0f<><1_" +
	"IV_byyC><Kn_DL6Hq0CR" +
	"YBJyOflyuWTozjf__PDU" +
	"H3evJ_n_6tL____kUs9O" +
	"_d2><select><87b_sel" +
	"ect>}<html><CY><sele" +
	"ct><select>)<table><" +
	"table><oOe>\"'<><tabl" +
	"e><table><table>`tab" +
	"le><table><table><><" +
	"table><><table><3q>#" +
	"<table><table>\"table" +
	"\"<><table><table>"
```

**Comment by dvyukov** [comment]
Working as expected :)
