### ISSUE TITLE
os: TestClosedPipeRaceWrite broken on solaris / SmartOS

### ISSUE THREAD

**Issue by bradfitz** [golang/go#27861]
Just noticed that the solaris-amd64-smartosbuildlet builder is all red. It's probably been red for a long time.

https://build.golang.org/log/6a1342d069021b0cc0a00344eb1373b13d2a760f
```
--- FAIL: TestClosedPipeRaceWrite (0.00s)
    pipe_test.go:140: using pipe write limit of 65537
    pipe_test.go:176: I/O on closed pipe unexpectedly succeeded
panic: Fail in goroutine after TestClosedPipeRaceWrite has completed

goroutine 220 [running]:
testing.(*common).Fail(0xc0002b0a00)
	/tmp/workdir/go/src/testing/testing.go:553 +0x132
testing.(*common).Error(0xc0002b0a00, 0xc0005d27a0, 0x1, 0x1)
	/tmp/workdir/go/src/testing/testing.go:623 +0x6f
os_test.testClosedPipeRace.func1(0xc0005c0100, 0xc0005c0140, 0xc0005c0148, 0xc0002b0a00)
	/tmp/workdir/go/src/os/pipe_test.go:165 +0x98
created by os_test.testClosedPipeRace
	/tmp/workdir/go/src/os/pipe_test.go:152 +0x15c
FAIL	os	0.545s
```

**Comment by bradfitz** [comment]
I suspect there are just spinning processes in the background.

That builder isn't created & destroyed per build (in either a container or VM). It's just a process running in a loop.

/cc @dmitshur

**Comment by tklauser** [comment]
Also see #27566

**Comment by bradfitz** [comment]
Ah, thanks. Closing this as duplicate of #27566.
