### ISSUE TITLE
runtime: "non in-use span in unswept list" flake on linux/amd64 

### ISSUE THREAD

**Issue by siebenmann** [golang/go#28003]
### What version of Go are you using (`go version`)?

`go version devel +2f1ef6be00 Thu Oct 4 02:31:59 2018 +0000 linux/amd64`, the latest git tip.

### What operating system and processor architecture are you using (`go env`)?

linux/amd64, specifically Fedora 28

### What did you do?

During `./all.bash` I got the following failure on one run; repeated re-runs didn't produce another instance. In light of the recently landed changes to GC and related things, I thought I should report it in case it is a sign of something other than, eg, the kind of weirdness in #22987.

````
[...]
##### ../test
# go run run.go -- fixedbugs/bug311.go
exit status 2
# command-line-arguments
runtime: bad span s.state=3 s.sweepgen=7 sweepgen=4
fatal error: non in-use span in unswept list

runtime stack:
runtime.throw(0x65dcac, 0x1f)
        /data/code/go-lang/go/src/runtime/panic.go:608 +0x72
runtime.sweepone(0x431e34)
        /data/code/go-lang/go/src/runtime/mgcsweep.go:106 +0x39f
runtime.gosweepone.func1()
        /data/code/go-lang/go/src/runtime/mgcsweep.go:142 +0x2b
runtime.systemstack(0x0)
        /data/code/go-lang/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
        /data/code/go-lang/go/src/runtime/proc.go:1153

goroutine 3 [running]:
runtime.systemstack_switch()
        /data/code/go-lang/go/src/runtime/asm_amd64.s:311 fp=0xc000057780 sp=0xc000057778 pc=0x454220
runtime.gosweepone(0x0)
        /data/code/go-lang/go/src/runtime/mgcsweep.go:141 +0x52 fp=0xc0000577b0 sp=0xc000057780 pc=0x41fb32
runtime.bgsweep(0xc00002e070)
        /data/code/go-lang/go/src/runtime/mgcsweep.go:55 +0xa1 fp=0xc0000577d8 sp=0xc0000577b0 pc=0x41f691
runtime.goexit()
        /data/code/go-lang/go/src/runtime/asm_amd64.s:1340 +0x1 fp=0xc0000577e0 sp=0xc0000577d8 pc=0x456181
created by runtime.gcenable
        /data/code/go-lang/go/src/runtime/mgc.go:208 +0x58

goroutine 1 [runnable]:
bufio.(*Reader).ReadByte(0xc000034480, 0xe4, 0x0, 0x0)
        /data/code/go-lang/go/src/bufio/bufio.go:236 +0xd7
cmd/link/internal/objfile.(*objReader).readInt64(0xc000546598, 0x124)
        /data/code/go-lang/go/src/cmd/link/internal/objfile/objfile.go:429 +0x53
cmd/link/internal/objfile.(*objReader).readInt(0xc000546598, 0x124)
        /data/code/go-lang/go/src/cmd/link/internal/objfile/objfile.go:443 +0x2b
cmd/link/internal/objfile.(*objReader).readSymIndex(0xc000546598, 0xc0ffffffff)
        /data/code/go-lang/go/src/cmd/link/internal/objfile/objfile.go:533 +0x2b
cmd/link/internal/objfile.(*objReader).readSym(0xc000546598)
        /data/code/go-lang/go/src/cmd/link/internal/objfile/objfile.go:317 +0xdd2
cmd/link/internal/objfile.(*objReader).loadObjFile(0xc000546598)
        /data/code/go-lang/go/src/cmd/link/internal/objfile/objfile.go:127 +0x45d
cmd/link/internal/objfile.Load(0x7f3da0, 0xc000530000, 0xc00006c600, 0xc000096a90, 0x2d4914, 0xc00001a3c0, 0x37)
        /data/code/go-lang/go/src/cmd/link/internal/objfile/objfile.go:69 +0x1c4
cmd/link/internal/ld.ldobj(0xc000534000, 0xc00006c600, 0xc000096a90, 0x2d49e0, 0xc00001a3c0, 0x37, 0xc00053c05d, 0x2f, 0x0)
        /data/code/go-lang/go/src/cmd/link/internal/ld/lib.go:1602 +0xc89
cmd/link/internal/ld.loadobjfile(0xc000534000, 0xc000096a90)
        /data/code/go-lang/go/src/cmd/link/internal/ld/lib.go:860 +0x4d9
cmd/link/internal/ld.(*Link).loadlib(0xc000534000)
        /data/code/go-lang/go/src/cmd/link/internal/ld/lib.go:380 +0x160
cmd/link/internal/ld.Main(0x7f3da0, 0x10, 0x20, 0x1, 0x7, 0x10, 0x65be52, 0x1b, 0x658b43, 0x14, ...)
        /data/code/go-lang/go/src/cmd/link/internal/ld/main.go:207 +0xa1a
main.main()
        /data/code/go-lang/go/src/cmd/link/main.go:65 +0x227

FAIL    fixedbugs/bug311.go     0.085s
2018/10/03 22:57:42 Failed: exit status 1

##### API check
[...]
````

**Comment by ianlancetaylor** [comment]
Merging with #27997 .
