### ISSUE TITLE
FAIL: TestLldbPython

### ISSUE THREAD

**Issue by YoshikiShibata** [golang/go#28028]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

Rebuilding the latest tip version with `all.bash`

#### What did you expect to see?

No failure.

#### What did you see instead?

```
ok  	regexp/syntax	0.798s
--- FAIL: TestLldbPython (1.14s)
    runtime-lldb_test.go:39: bad lldb --version output: lldb-1000.11.37.1
          Swift-4.2
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range


goroutine 23021 [running]:
panic(0x129c5c0, 0x1519160)
	/Users/yoshiki/tools/go/src/runtime/panic.go:556 +0x2be fp=0xc0000919c0 sp=0xc000091930 pc=0x102df0e
testing.tRunner.func1(0xc0000c6600)
	/Users/yoshiki/tools/go/src/testing/testing.go:799 +0x378 fp=0xc000091a40 sp=0xc0000919c0 pc=0x10ee618
runtime.call32(0x0, 0x12fda48, 0xc00013e470, 0x800000008)
	/Users/yoshiki/tools/go/src/runtime/asm_amd64.s:522 +0x3b fp=0xc000091a70 sp=0xc000091a40 pc=0x105e50b
panic(0x129c5c0, 0x1519160)
	/Users/yoshiki/tools/go/src/runtime/panic.go:513 +0x1b5 fp=0xc000091b00 sp=0xc000091a70 pc=0x102de05
runtime.panicindex()
	/Users/yoshiki/tools/go/src/runtime/panic.go:44 +0xfa fp=0xc000091b30 sp=0xc000091b00 pc=0x102caaa
runtime_test.checkLldbPython(0xc0000c6600)
	/Users/yoshiki/tools/go/src/runtime/runtime-lldb_test.go:41 +0xbd8 fp=0xc000091d70 sp=0xc000091b30 pc=0x122b328
runtime_test.TestLldbPython(0xc0000c6600)
	/Users/yoshiki/tools/go/src/runtime/runtime-lldb_test.go:166 +0x8c fp=0xc000091fa8 sp=0xc000091d70 pc=0x122b3cc
testing.tRunner(0xc0000c6600, 0x12fd070)
	/Users/yoshiki/tools/go/src/testing/testing.go:834 +0xbf fp=0xc000091fd0 sp=0xc000091fa8 pc=0x10ea61f
runtime.goexit()
	/Users/yoshiki/tools/go/src/runtime/asm_amd64.s:1340 +0x1 fp=0xc000091fd8 sp=0xc000091fd0 pc=0x1060201
created by testing.(*T).Run
	/Users/yoshiki/tools/go/src/testing/testing.go:885 +0x34d
```

#### Does this issue reproduce with the latest release (go1.11.1)?
N/A
#### System details

```
go version devel +808186203b Thu Oct 4 20:26:13 2018 +0000 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/yoshiki/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/yoshiki/gocode:/Users/yoshiki/exercises/gpl:/Users/yoshiki/oak"
GOPROXY=""
GORACE=""
GOROOT="/Users/yoshiki/tools/go"
GOTMPDIR=""
GOTOOLDIR="/Users/yoshiki/tools/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
GOROOT/bin/go version: go version devel +808186203b Thu Oct 4 20:26:13 2018 +0000 darwin/amd64
GOROOT/bin/go tool compile -V: compile version devel +808186203b Thu Oct 4 20:26:13 2018 +0000
uname -v: Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.14
BuildVersion:	18A391
lldb --version: lldb-1000.11.37.1
  Swift-4.2
```

**Comment by agnivade** [comment]
Ah, we are parsing the version string by hand. And it doesn't like ` lldb-1000.11.37.1`. We should probably call `Fatalf` or `Skipf` instead of `Errorf`. Because `Errorf` continues execution which is causing the panic.
