### ISSUE TITLE
x/tools/go/packages: failing on Go 1.10

### ISSUE THREAD

**Issue by bradfitz** [golang/go#28040]
x/tools is broken on Go 1.10 
https://build.golang.org/log/3b7dfcf2bc34eab6b8d3f552f77bb57f9b5b18cf

```
--- FAIL: TestLoadAbsolutePath (0.37s)
	packages_test.go:354: initial packages loaded: got [[b a]], want [a b]
FAIL
FAIL	golang.org/x/tools/go/packages	25.074s
```

and on another builder:

https://build.golang.org/log/d99665968216655f6a954e41f1c8a05e6672a57d
```
--- FAIL: TestLoadImportsC (0.99s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x63c04a]

goroutine 71 [running]:
testing.tRunner.func1(0xc4203c4000)
	/workdir/go/src/testing/testing.go:742 +0x29d
panic(0x69a140, 0x854950)
	/workdir/go/src/runtime/panic.go:502 +0x229
golang.org/x/tools/go/packages.createTestVariants.func1(0x0, 0xc42011f490)
	/workdir/gopath/src/golang.org/x/tools/go/packages/golist_fallback.go:266 +0x6a
golang.org/x/tools/go/packages.createTestVariants.func1(0xc420392000, 0xc42011f490)
	/workdir/gopath/src/golang.org/x/tools/go/packages/golist_fallback.go:270 +0x179
golang.org/x/tools/go/packages.createTestVariants(0xc4203ba1e0, 0xc4203aac40, 0xc42041a380)
	/workdir/gopath/src/golang.org/x/tools/go/packages/golist_fallback.go:299 +0x389
golang.org/x/tools/go/packages.golistDriverFallback(0xc42025f788, 0xc4202f6c20, 0x2, 0x2, 0x0, 0x721360, 0xc42004d030)
	/workdir/gopath/src/golang.org/x/tools/go/packages/golist_fallback.go:246 +0x765
golang.org/x/tools/go/packages.goListDriver.func1(0xc42025f788, 0xc4203b0420, 0x2, 0x2, 0x1, 0x0, 0x0)
	/workdir/gopath/src/golang.org/x/tools/go/packages/golist.go:48 +0xc1
golang.org/x/tools/go/packages.goListDriver(0xc42025f788, 0xc4203b0400, 0x2, 0x2, 0xc42025f780, 0xc42025f7b0, 0xc4203b0400)
	/workdir/gopath/src/golang.org/x/tools/go/packages/golist.go:59 +0xd4e
golang.org/x/tools/go/packages.defaultDriver(0xc42025f788, 0xc4203b0400, 0x2, 0x2, 0xf, 0x83fea6, 0x22)
	/workdir/gopath/src/golang.org/x/tools/go/packages/packages.go:171 +0x68
golang.org/x/tools/go/packages.Load(0xc42002b728, 0xc4203b0400, 0x2, 0x2, 0x445387, 0xc42038f4e8, 0xc420395da0, 0x2, 0x2)
	/workdir/gopath/src/golang.org/x/tools/go/packages/packages.go:157 +0x6f
golang.org/x/tools/go/packages_test.TestLoadImportsC(0xc4203c4000)
	/workdir/gopath/src/golang.org/x/tools/go/packages/packages_test.go:304 +0xdd
testing.tRunner(0xc4203c4000, 0x6fa7b8)
	/workdir/go/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
	/workdir/go/src/testing/testing.go:824 +0x2e0
FAIL	golang.org/x/tools/go/packages	3.222s
```

**Comment by bradfitz** [comment]
Ping somebody. Please fix or skip these tests.

Red on the dashboard is distracting.
