### ISSUE TITLE
Segfault during test using -coverpkg and -race.

### ISSUE THREAD

**Issue by gaillard** [golang/go#28109]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.11.1

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Linux amd64

### What did you do?
`go test -c -o aTestBinary -coverpkg package1,package2,package3 -covermode atomic -race -ldflags '-w -s -extldflags "-static -Wl,--no-export-dynamic"'`
`./aTestBinary -test.v -test.run . -test.coverprofile coverout`

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.
Wish I could at the moment :/

### What did you expect to see?
Success

### What did you see instead?
```
unexpected fault address 0x19600
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x19600 pc=0x12a0389]

goroutine 63887 [running]:
runtime: unexpected return pc for runtime.throw called from 0x5
stack: frame={sp:0x7f0386ffca70, fp:0x7f0386ffcaa0} stack=[0xc0021f4000,0xc0021f6000)

runtime.throw(0x5, 0x7f0386ffcae0)
	/usr/local/go/src/runtime/panic.go:608 +0x72 fp=0x7f0386ffcaa0 sp=0x7f0386ffca70 pc=0x497d42
created by ...

goroutine 1 [chan receive]:
testing.tRunner.func1(0xc000112100)
	/usr/local/go/src/testing/testing.go:803 +0x2e4
testing.tRunner(0xc000112100, 0xc00011bc98)
	/usr/local/go/src/testing/testing.go:831 +0x17f
testing.runTests(0xc0000c4060, 0x410d5c0, 0xa5, 0xa5, 0xc0000bc000)
	/usr/local/go/src/testing/testing.go:1117 +0x4ef
testing.(*M).Run(0xc000232200, 0x0)
	/usr/local/go/src/testing/testing.go:1034 +0x2ef
.../....TestMain(0xc000232200)
	/go/src/....go:36 +0x123
main.main()
	_testmain.go:962 +0x33f

goroutine 50 [chan receive]:
testing.(*testContext).waitParallel(0xc0000ad1d0)
	/usr/local/go/src/testing/testing.go:926 +0x15c
testing.(*T).Parallel(0xc000112200)
	/usr/local/go/src/testing/testing.go:733 +0x3e5
...
```

Probably related #23882?

**Comment by agnivade** [comment]
Do you have a shortened reproducer or perhaps a sample repo for us to test this out and reproduce it ourselves ?

**Comment by gaillard** [comment]
I don't have a repro as it happens in the middle of a larger suite with a number of parallel tests running. However it appears to be related only to having the race detector on. I have not seen the faults without the race detector, even when keeping code coverage, including with -coverpkg. For example here is another one, with race detector but without any coverage:
```
unexpected fault address 0x2600
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2600 pc=0x12629d9]

goroutine 424974 [running]:
runtime: unexpected return pc for runtime.throw called from 0x6
stack: frame={sp:0x7f0bf7ffea70, fp:0x7f0bf7ffeaa0} stack=[0xc002452000,0xc00245a000)

runtime.throw(0x6, 0x7f0bf7ffeae0)
	/usr/local/go/src/runtime/panic.go:608 +0x72 fp=0x7f0bf7ffeaa0 sp=0x7f0bf7ffea70 pc=0x497d42
created by testing.(*B).RunParallel
	/usr/local/go/src/testing/benchmark.go:619 +0x256
```

**Comment by ianlancetaylor** [comment]
CC @aclements @dvyukov

**Comment by ianlancetaylor** [comment]
The signal report is giving you a PC address.  Can you tell us what is at that address?
