### ISSUE TITLE
testing framework panics `encoding alphabet is not 32-bytes long` after 1.11.1 upgrade

### ISSUE THREAD

**Issue by davisford** [golang/go#28443]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

`go version go1.11.1 darwin/amd64`

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/davisford/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/davisford/gocode"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/davisford/git/nupos/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vp/jb9jxbyn6qjbkqclvfcfktrr0000gn/T/go-build298570352=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?

Trying to run test suite of one of our repos now fails with this:

```
panic: encoding alphabet is not 32-bytes long

goroutine 1 [running]:
encoding/base32.NewEncoding(0x1bc6b3c, 0x22, 0x0)
	/usr/local/Cellar/go/1.11.1/libexec/src/encoding/base32/base32.go:41 +0x234
```

I'm trying to get more of a stacktrace or an indication of what happened, b/c that's not much to go on above -- no idea where it is when it hits that panic.

Tried this to get a more complete picture:

`go test -gcflags="all=-N -l -m"`

Here's the end of that output:

```
$GOROOT/src/testing/testing.go:638: testing.(*T).Skip testing.args does not escape
<autogenerated>:1: testing.(*T).Skip &.this.common does not escape
<autogenerated>:1: testing.(*T).SkipNow .this does not escape
<autogenerated>:1: testing.(*T).SkipNow &.this.common does not escape
<autogenerated>:1: testing.(*T).Skipf .this does not escape
$GOROOT/src/testing/testing.go:644: testing.(*T).Skipf testing.format does not escape
$GOROOT/src/testing/testing.go:644: testing.(*T).Skipf testing.args does not escape
<autogenerated>:1: testing.(*T).Skipf &.this.common does not escape
<autogenerated>:1: testing.(*T).Skipped .this does not escape
<autogenerated>:1: testing.(*T).Skipped &.this.common does not escape
<autogenerated>:1: testing.(*T).decorate .this does not escape
$GOROOT/src/testing/testing.go:399: testing.(*T).decorate testing.s does not escape
<autogenerated>:1: testing.(*T).decorate &.this.common does not escape
<autogenerated>:1: testing.(*T).flushToParent .this does not escape
$GOROOT/src/testing/testing.go:437: testing.(*T).flushToParent testing.format does not escape
$GOROOT/src/testing/testing.go:437: testing.(*T).flushToParent testing.args does not escape
<autogenerated>:1: testing.(*T).flushToParent &.this.common does not escape
<autogenerated>:1: testing.(*T).frameSkip .this does not escape
<autogenerated>:1: testing.(*T).frameSkip &.this.common does not escape
<autogenerated>:1: testing.(*T).log .this does not escape
$GOROOT/src/testing/testing.go:594: testing.(*T).log testing.s does not escape
<autogenerated>:1: testing.(*T).log &.this.common does not escape
<autogenerated>:1: testing.(*T).private .this does not escape
<autogenerated>:1: testing.(*T).private &.this.common does not escape
<autogenerated>:1: testing.(*T).setRan .this does not escape
<autogenerated>:1: testing.(*T).setRan &.this.common does not escape
<autogenerated>:1: testing.(*T).skip .this does not escape
<autogenerated>:1: testing.(*T).skip &.this.common does not escape
# ccard.test
/var/folders/vp/jb9jxbyn6qjbkqclvfcfktrr0000gn/T/go-build488050875/b001/_testmain.go:42:42: testdeps.TestDeps literal escapes to heap
panic: encoding alphabet is not 32-bytes long

goroutine 1 [running]:
encoding/base32.NewEncoding(0x1b97bbc, 0x22, 0x0)
	/usr/local/Cellar/go/1.11.1/libexec/src/encoding/base32/base32.go:41 +0x234
exit status 2
FAIL	ccard	0.023s
```

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?

Expected to be able to run our test suite as usual.  Running on go 1.10 did not have this issue.

### What did you see instead?

Now, cannot run our test suite b/c of panic

**Comment by davisford** [comment]
Verified that 1.10.4 does not have issue, but 1.11.1 does:

```
davisford@zeno:~$go version
go version go1.10.4 darwin/amd64
davisford@zeno:~/git/pos/server/src/utilities$go test -v
=== RUN   TestSwapMem
--- PASS: TestSwapMem (0.00s)
=== RUN   TestSort3
--- PASS: TestSort3 (0.00s)
=== RUN   TestSort
--- PASS: TestSort (0.02s)
=== RUN   TestSortStruct
--- PASS: TestSortStruct (0.06s)
=== RUN   TestUtilities
Running Suite: Utilities Suite
==============================
Random Seed: 1540697509
Will run 67 of 67 specs

•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
Ran 67 of 67 Specs in 2.038 seconds
SUCCESS! -- 67 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestUtilities (2.04s)
PASS
ok  	utilities	2.155s
```

```
davisford@zeno:~$go version
go version go1.11.1 darwin/amd64
davisford@zeno:~/git/pos/server/src/utilities$go test -v
panic: encoding alphabet is not 32-bytes long

goroutine 1 [running]:
encoding/base32.NewEncoding(0x196301c, 0x22, 0x1a37bc0)
	/usr/local/Cellar/go/1.11.1/libexec/src/encoding/base32/base32.go:41 +0xd8
exit status 2
FAIL	utilities	0.019s
```

**Comment by agnivade** [comment]
Hi @davisford - Could you provide us with a sample code that causes the above failure ? Without that it is difficult for us to reproduce the issue.

**Comment by mvdan** [comment]
@AlexRouSg is right - this has been documented for a while:

> NewEncoding returns a new Encoding defined by the given alphabet, which must be a 32-byte string.

Closing, as there's nothing to fix here. The panic seems obvious enough to me.
