### ISSUE TITLE
cmd/cgo: panics when building crypto/x509 on darwin and android

### ISSUE THREAD

**Issue by YoshikiShibata** [golang/go#28540]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?

Tried to rebuild the latest tip version on my Mac.

#### What did you expect to see?

The rebuilding is done successfully.

#### What did you see instead?

```
$ git rev-parse HEAD
90df37769d6441ce550443fa7e0c008d38e53455
```

```
$ ./all.bash
Building Go cmd/dist using /usr/local/go.
Building Go toolchain1 using /usr/local/go.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for darwin/amd64.
# crypto/x509
panic: overlapping edits: [5892,5966)->"(_cgo0, _cgo1); }()", [5908,5908)->"func() *_Ctype_UInt8{ _cgo0 := data; _cgoCheckPointer(_cgo0); return "

goroutine 1 [running]:
cmd/internal/edit.(*Buffer).Bytes(0xc000066990, 0xc00033c200, 0x11e4e48, 0xe)
	/Users/yoshiki/tools/go/src/cmd/internal/edit/edit.go:79 +0x5b1
main.(*Package).writeOutput(0xc0000a8000, 0xc00009c140, 0x7ffeefbff414, 0x3a)
	/Users/yoshiki/tools/go/src/cmd/cgo/out.go:547 +0x397
main.main()
	/Users/yoshiki/tools/go/src/cmd/cgo/main.go:345 +0xaee
go tool dist: FAILED: /Users/yoshiki/tools/go/pkg/tool/darwin_amd64/go_bootstrap install -gcflags=all= -ldflags=all= std cmd: exit status 2
```

#### Does this issue reproduce with the latest release (go1.11.1)?

N/A

#### System details

```
go version devel +3553eca27c Wed Oct 31 20:08:50 2018 +0000 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/yoshiki/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/yoshiki/gocode:/Users/yoshiki/exercises/gpl:/Users/yoshiki/oak"
GOPROXY=""
GORACE=""
GOROOT="/Users/yoshiki/tools/go"
GOTMPDIR=""
GOTOOLDIR="/Users/yoshiki/tools/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
GOROOT/bin/go version: go version devel +3553eca27c Wed Oct 31 20:08:50 2018 +0000 darwin/amd64
GOROOT/bin/go tool compile -V: compile version devel +90df37769d Thu Nov 1 21:54:54 2018 +0000
uname -v: Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.14.1
BuildVersion:	18B75
lldb --version: lldb-1000.0.38.2
  Swift-4.2
```

**Comment by dmitshur** [comment]
This is caused by [CL 142884](https://golang.org/cl/142884) (which is commit that the original issue mentions). I can reproduce locally on my Mac. /cc @ianlancetaylor @bradfitz

Strange that trybots didn't catch it.

**Comment by bradfitz** [comment]
We don't have Mac trybots at the moment.

**Comment by ianlancetaylor** [comment]
I have a patch.  Will send shortly.
