### ISSUE TITLE
time: panic in initLocal on js/wasm

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#28649]
This very simple program panics when executed with `misc/wasm/go_js_wasm_exec`.

```
package main

import (
	"log"
)

func main() {
	log.Print("Test.")
}
```

```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
time.itoa(...)
	/Users/valsorda/go/src/time/zoneinfo_js.go:51
time.initLocal()
	/Users/valsorda/go/src/time/zoneinfo_js.go:39 +0x3b
sync.(*Once).Do(0x15a3c0, 0x39a18)
	/Users/valsorda/go/src/sync/once.go:44 +0xf
time.(*Location).get(0x141120, 0x8)
	/Users/valsorda/go/src/time/zoneinfo.go:79 +0x5
time.Time.abs(0xbef100f060a9d100, 0x112701, 0x141120, 0x5)
	/Users/valsorda/go/src/time/time.go:455 +0x4
time.Time.date(0xbef100f060a9d100, 0x112701, 0x141120, 0x16a50001, 0xc056000, 0x32e59, 0x5, 0x100000076)
	/Users/valsorda/go/src/time/time.go:964 +0x2
time.Time.Date(0xbef100f060a9d100, 0x112701, 0x141120, 0x0, 0xc04c000, 0xc000180)
	/Users/valsorda/go/src/time/time.go:495 +0x2
log.(*Logger).formatHeader(0xc04a000, 0xc04a030, 0xbef100f060a9d100, 0x112701, 0x141120, 0x0, 0x0, 0x0)
	/Users/valsorda/go/src/log/log.go:103 +0x5b
log.(*Logger).Output(0xc04a000, 0x2, 0xc0140c8, 0x5, 0x0, 0x0)
	/Users/valsorda/go/src/log/log.go:167 +0x9
log.Print(0xc030788, 0x1, 0x1)
	/Users/valsorda/go/src/log/log.go:296 +0x3
main.main()
	/Users/valsorda/go/src/jspanic.go:8 +0x2
exit status 2
```

**Comment by agnivade** [comment]
My bad, I did not think of negative offsets. Sigh .. Sending a fix.
