### ISSUE TITLE
cmd/compile: method expressions of implicitly defined methods fail

### ISSUE THREAD

**Issue by randall77** [golang/go#29389]
```
package main

import "io"

func main() {
	err := io.EOF
	_ = err.Error
}
```

This fails on tip with
```
# command-line-arguments
panic: runtime error: index out of range

goroutine 52 [running]:
cmd/compile/internal/gc.(*state).peekPos(...)
	/usr/local/google/home/khr/sandbox/issue29007/src/cmd/compile/internal/gc/ssa.go:484
cmd/compile/internal/gc.(*state).pushLine(0xc00054c4e0, 0x0)
	/usr/local/google/home/khr/sandbox/issue29007/src/cmd/compile/internal/gc/ssa.go:466 +0x19c
cmd/compile/internal/gc.buildssa(0xc0000cc420, 0x3, 0x0)
	/usr/local/google/home/khr/sandbox/issue29007/src/cmd/compile/internal/gc/ssa.go:130 +0xe7
cmd/compile/internal/gc.compileSSA(0xc0000cc420, 0x3)
	/usr/local/google/home/khr/sandbox/issue29007/src/cmd/compile/internal/gc/pgen.go:280 +0x4d
cmd/compile/internal/gc.compileFunctions.func2(0xc000538c00, 0xc00053a230, 0x3)
	/usr/local/google/home/khr/sandbox/issue29007/src/cmd/compile/internal/gc/pgen.go:345 +0x49
created by cmd/compile/internal/gc.compileFunctions
	/usr/local/google/home/khr/sandbox/issue29007/src/cmd/compile/internal/gc/pgen.go:343 +0x129
```

The problem is that it's making a function from a method (the `err.Error` part), but it can't find the original line number of the method declaration.  It is the implicit declaration of `Error` for the built-in `error` type, which doesn't have a line number.
We need a backstop line number for cases where the method declaration is implicit.

**Comment by mark-rushakoff** [comment]
Related to https://github.com/golang/go/issues/29304?

**Comment by randall77** [comment]
@mark-rushakoff I don't think they are directly related. Both have to do with `error.Error`, but as far as I can tell in unrelated ways.
