### ISSUE TITLE
runtime: netpoll failed on android/386

### ISSUE THREAD

**Issue by eliasnaur** [golang/go#29423]
From the android/386 builder:

https://build.golang.org/log/e11446723639eb0b41a7268c1f19c0de5f8da7cc

```
runtime: epollwait on fd 6 failed with 22
fatal error: runtime: netpoll failed

runtime stack:
runtime.throw(0xea8e5d96, 0x17)
	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-android/go/src/runtime/panic.go:617 +0x69
runtime.netpoll(0xeab24a00, 0x1a5c7cf0)
	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-android/go/src/runtime/netpoll_epoll.go:75 +0x1f9
runtime.findrunnable(0xb9c23300, 0x0)
	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-android/go/src/runtime/proc.go:2226 +0x8bb
runtime.schedule()
	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-android/go/src/runtime/proc.go:2525 +0x207
runtime.park_m(0xb9cc0000)
	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-android/go/src/runtime/proc.go:2605 +0x84
runtime.mcall(0xea78ab32)
	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-android/go/src/runtime/asm_386.s:345 +0x49

goroutine 1 [chan receive]:
testing.tRunner.func1(0xb9c98000)
	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-android/go/src/testing/testing.go:838 +0x1a2
testing.tRunner(0xb9c98000, 0xb9c3ff1c)
	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-android/go/src/testing/testing.go:866 +0xac
testing.runTests(0xb9c0e0a0, 0xeab10180, 0x23, 0x23, 0x0)
	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-android/go/src/testing/testing.go:1152 +0x286
testing.(*M).Run(0xb9c52380, 0x0)
	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-android/go/src/testing/testing.go:1069 +0x141
main.main()
	_testmain.go:112 +0x14d

goroutine 41 [runnable]:
testing.tRunner.func1(0xb9cd2dc0)
	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-android/go/src/testing/testing.go:857 +0x1fa
testing.tRunner(0xb9cd2dc0, 0xea9c93d8)
	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-android/go/src/testing/testing.go:866 +0xac
created by testing.(*T).Run
	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-android/go/src/testing/testing.go:913 +0x2d1

goroutine 58 [runnable]:
testing.runTests.func1.1(0xb9c98000)
	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-android/go/src/testing/testing.go:1159
created by testing.runTests.func1
	/private/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/workdir-host-darwin-amd64-eliasnaur-android/go/src/testing/testing.go:1159 +0x84
exitcode=2go_android_exec: adb -e shell rm -rf /data/local/tmp/unix.test-17686
FAIL	cmd/vendor/golang.org/x/sys/unix	0.532s
```

**Comment by odeke-em** [comment]
Thank you for this report @eliasnaur!

Kindly paging @ianlancetaylor.

**Comment by ianlancetaylor** [comment]
That is the only instance I can find in the builder logs.  It should be impossible.

**Comment by eliasnaur** [comment]
Abother, this time on android/arm64:

https://build.golang.org/log/ec6550708e7d674f80b19c3a987d0be24eb7dbe4

**Comment by eliasnaur** [comment]
FWIW, I can reproduce this crash locally by running the cmd/vendor/golang.org/x/sys/unix tests in a loop. I don't know how to debug it though.

**Comment by eliasnaur** [comment]
It could be a coincidence, but I once got the crash just as I was ctrl-C'ing the test loop that had run for minutes. If so, there might be a racy interaction between epoll_pwait and signals or during process exit.

**Comment by eliasnaur** [comment]
After modifying the runtime to report whether runtime.netpollclose had been called in runtime.netpoll:

```
diff --git a/src/runtime/netpoll_epoll.go b/src/runtime/netpoll_epoll.go
index f764d6ff7c..c9a63efdeb 100644
--- a/src/runtime/netpoll_epoll.go
+++ b/src/runtime/netpoll_epoll.go
@@ -6,7 +6,10 @@
 
 package runtime
 
-import "unsafe"
+import (
+       "runtime/internal/atomic"
+       "unsafe"
+)
 
 func epollcreate(size int32) int32
 func epollcreate1(flags int32) int32
@@ -20,6 +23,8 @@ func closeonexec(fd int32)
 
 var (
        epfd int32 = -1 // epoll descriptor
+
+       closing uint32
 )
 
 func netpollinit() {
@@ -48,8 +53,11 @@ func netpollopen(fd uintptr, pd *pollDesc) int32 {
 }
 
 func netpollclose(fd uintptr) int32 {
+       atomic.Store(&closing, 1)
        var ev epollevent
-       return -epollctl(epfd, _EPOLL_CTL_DEL, int32(fd), &ev)
+       r := -epollctl(epfd, _EPOLL_CTL_DEL, int32(fd), &ev)
+       atomic.Store(&closing, 2)
+       return r
 }
 
 func netpollarm(pd *pollDesc, mode int) {
@@ -71,7 +79,8 @@ retry:
        n := epollwait(epfd, &events[0], int32(len(events)), waitms)
        if n < 0 {
                if n != -_EINTR {
-                       println("runtime: epollwait on fd", epfd, "failed with", -n)
+                       cl := atomic.Load(&closing)
+                       println("runtime: epollwait on fd", epfd, "failed with", -n, "closing", cl)
                        throw("runtime: netpoll failed")
                }
                goto retry
```

I got this crash

```
--- FAIL: TestTime (0.00s)
    syscall_linux_test.go:93: Time: return value 1550938951 should be nearly equal to time.Now().Unix() 1550938952
FAIL
runtime: epollwait on fd 6 failed with 22 closing 2
fatal error: runtime: netpoll failed

runtime stack:
runtime.throw(0xa7d42a1d, 0x17)
	/home/elias/dev/go-tip/src/runtime/panic.go:617 +0x69
runtime.netpoll(0xa7f8ba00, 0x49c7dbdf)
	/home/elias/dev/go-tip/src/runtime/netpoll_epoll.go:84 +0x244
runtime.findrunnable(0x77022000, 0x0)
	/home/elias/dev/go-tip/src/runtime/proc.go:2226 +0x8cc
runtime.schedule()
	/home/elias/dev/go-tip/src/runtime/proc.go:2525 +0x20d
runtime.park_m(0x77001340)
	/home/elias/dev/go-tip/src/runtime/proc.go:2605 +0x89
runtime.mcall(0xa7be38c2)
	/home/elias/dev/go-tip/src/runtime/asm_386.s:345 +0x49

goroutine 1 [runnable]:
syscall.Syscall(0x4, 0x1, 0x770d0000, 0x5, 0x5, 0x5, 0x0)
	/home/elias/dev/go-tip/src/syscall/asm_linux_386.s:19 +0x5
syscall.write(0x1, 0x770d0000, 0x5, 0x100, 0x0, 0xa7c65d62, 0x7709a000)
	/home/elias/dev/go-tip/src/syscall/zsyscall_linux_386.go:1005 +0x43
syscall.Write(...)
	/home/elias/dev/go-tip/src/syscall/syscall_unix.go:191
internal/poll.(*FD).Write(0x77054080, 0x770d0000, 0x5, 0x100, 0x0, 0x0, 0x0)
	/home/elias/dev/go-tip/src/internal/poll/fd_unix.go:268 +0x146
os.(*File).write(...)
	/home/elias/dev/go-tip/src/os/file_unix.go:280
os.(*File).Write(0x770100d8, 0x770d0000, 0x5, 0x100, 0x0, 0x770141c0, 0x77018300)
	/home/elias/dev/go-tip/src/os/file.go:145 +0x51
fmt.Fprintln(0xa7e34a10, 0x770100d8, 0x7703ff80, 0x1, 0x1, 0x0, 0x3, 0xa9c)
	/home/elias/dev/go-tip/src/fmt/print.go:266 +0x64
fmt.Println(...)
	/home/elias/dev/go-tip/src/fmt/print.go:275
testing.(*M).Run(0x77054380, 0x0)
	/home/elias/dev/go-tip/src/testing/testing.go:1079 +0x258
main.main()
	_testmain.go:112 +0x14e
exitcode=2go_android_exec: adb shell rm -rf /data/local/tmp/unix.test-30792
FAIL	cmd/vendor/golang.org/x/sys/unix	0.262s
```

The crash indicates that the epoll_pwait error happened after runtime.netpollclose.

@ianlancetaylor or someone else with better knowledge about the runtime poller: what is the correct fix? Ignoring EINVAL from epoll_pwait if runtime.netpollclose has been called or should the poller never end up in this situation?
