### ISSUE TITLE
cmd/compile,runtime: s390x build broken "fatal error: inserting span already in treap"

### ISSUE THREAD

**Issue by billotosyr** [golang/go#29506]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.12 master tip

</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="s390x"
GOBIN=""
GOEXE=""
GOHOSTARCH="s390x"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/data/golang/go"
GOTOOLDIR="/data/golang/go/pkg/tool/linux_s390x"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -march=z196 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build646158134=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

</pre></details>

### What did you do?

ran build in build bot

### What did you expect to see?

successful build

### What did you see instead?

fatal error: inserting span already in treap

may have been caused by  69c2c56

**Comment by katiehockman** [comment]
Example: https://build.golang.org/log/72eb3fb60ae17057c83026973333b7f7c26b899d

/cc @randall77 

<details>

```
fatal error: inserting span already in treap

runtime stack:
runtime.throw(0x416f16, 0x1f)
	/data/golang/workdir/go/src/runtime/panic.go:617 +0x72
runtime.(*mTreap).insert(0x6fb208, 0x3ffbb94ab90)
	/data/golang/workdir/go/src/runtime/mgclarge.go:237 +0x374
runtime.(*mheap).freeSpanLocked(0x6fb200, 0x3ffbb94ab90, 0x101000000000400, 0x0)
	/data/golang/workdir/go/src/runtime/mheap.go:1279 +0x5d8
runtime.(*mheap).freeSpan.func1()
	/data/golang/workdir/go/src/runtime/mheap.go:1157 +0x110
runtime.(*mheap).freeSpan(0x6fb200, 0x3ffbb94ab90, 0x3ffbb94d000)
	/data/golang/workdir/go/src/runtime/mheap.go:1136 +0x62
runtime.(*mcentral).freeSpan(0x6fd580, 0x3ffbb94ab90, 0x3ffbb94d000, 0x3b0c0)
	/data/golang/workdir/go/src/runtime/mcentral.go:246 +0x148
runtime.(*mspan).sweep(0x3ffbb94ab90, 0x3ffbb94ab90, 0x0)
	/data/golang/workdir/go/src/runtime/mgcsweep.go:364 +0x6ea
runtime.(*mcentral).uncacheSpan(0x6fd580, 0x3ffbb94ab90)
	/data/golang/workdir/go/src/runtime/mcentral.go:197 +0x8e
runtime.(*mcache).releaseAll(0x3ffbb940000)
	/data/golang/workdir/go/src/runtime/mcache.go:155 +0x82
runtime.(*mcache).prepareForSweep(0x3ffbb940000)
	/data/golang/workdir/go/src/runtime/mcache.go:182 +0x48
runtime.acquirep(0xc00001e000)
	/data/golang/workdir/go/src/runtime/proc.go:4090 +0x42
runtime.stopm()
	/data/golang/workdir/go/src/runtime/proc.go:1938 +0x11a
runtime.findrunnable(0xc000022a00, 0x0)
	/data/golang/workdir/go/src/runtime/proc.go:2399 +0x628
runtime.schedule()
	/data/golang/workdir/go/src/runtime/proc.go:2525 +0x28a
runtime.park_m(0xc000060300)
	/data/golang/workdir/go/src/runtime/proc.go:2605 +0xc0
runtime.mcall(0x48b90)
	/data/golang/workdir/go/src/runtime/asm_s390x.s:237 +0x60

goroutine 1 [semacquire]:
bufio.NewReaderSize(...)
	/data/golang/workdir/go/src/bufio/bufio.go:56
bufio.NewReader(...)
	/data/golang/workdir/go/src/bufio/bufio.go:62
go/build.readImports(0x4ad140, 0xc0000beaa8, 0xc0000beaa8, 0x0, 0xc0000beaa8, 0x0, 0x0, 0x0, 0x0)
	/data/golang/workdir/go/src/go/build/read.go:214 +0x2fc
go/build.(*Context).matchFile(0x6f3740, 0xc0002b0690, 0x23, 0xc0002b10d4, 0x7, 0xc0002cd020, 0xc0002c2460, 0x0, 0x0, 0x0, ...)
	/data/golang/workdir/go/src/go/build/build.go:1242 +0x2d0
go/build.(*Context).Import(0x6f3740, 0xc000219fe1, 0x7, 0xc000247160, 0x20, 0x4, 0xd, 0xc0002c0000, 0xc0002cfa30)
	/data/golang/workdir/go/src/go/build/build.go:770 +0xd0a
cmd/go/internal/load.LoadImport(0xc000219fe1, 0x7, 0xc000247160, 0x20, 0xc00025f680, 0xc0002cfa30, 0xc000296b40, 0x1, 0x1, 0x1, ...)
	/data/golang/workdir/go/src/cmd/go/internal/load/pkg.go:548 +0x18b2
cmd/go/internal/load.(*Package).load(0xc00025f680, 0xc0002cfa30, 0xc0001e7c00, 0x0, 0x0)
	/data/golang/workdir/go/src/cmd/go/internal/load/pkg.go:1403 +0x219c
cmd/go/internal/load.LoadImport(0xc000219741, 0x4, 0xc000246c40, 0x1e, 0xc00025f200, 0xc0002cfa30, 0xc0002536b0, 0x1, 0x1, 0x1, ...)
	/data/golang/workdir/go/src/cmd/go/internal/load/pkg.go:560 +0x1172
cmd/go/internal/load.(*Package).load(0xc00025f200, 0xc0002cfa30, 0xc0001e7880, 0x0, 0x0)
	/data/golang/workdir/go/src/cmd/go/internal/load/pkg.go:1403 +0x219c
cmd/go/internal/load.LoadImport(0xc000191ef9, 0x2, 0xc00001d4d0, 0x21, 0xc00008b200, 0xc0002cfa30, 0xc00015f9f0, 0x2, 0x2, 0x1, ...)
	/data/golang/workdir/go/src/cmd/go/internal/load/pkg.go:560 +0x1172
cmd/go/internal/load.(*Package).load(0xc00008b200, 0xc0002cfa30, 0xc0001e6700, 0x0, 0x0)
	/data/golang/workdir/go/src/cmd/go/internal/load/pkg.go:1403 +0x219c
cmd/go/internal/load.LoadImport(0xc000191997, 0x5, 0xc00001ce10, 0x21, 0xc00008ad80, 0xc0002cfa30, 0xc00015f400, 0x2, 0x2, 0x1, ...)
	/data/golang/workdir/go/src/cmd/go/internal/load/pkg.go:560 +0x1172
cmd/go/internal/load.(*Package).load(0xc00008ad80, 0xc0002cfa30, 0xc0001e6380, 0x0, 0x0)
	/data/golang/workdir/go/src/cmd/go/internal/load/pkg.go:1403 +0x219c
cmd/go/internal/load.LoadImport(0xc000191811, 0x5, 0xc00001c780, 0x23, 0xc00008a900, 0xc0002cfa30, 0xc0001ad470, 0x1, 0x1, 0x1, ...)
	/data/golang/workdir/go/src/cmd/go/internal/load/pkg.go:560 +0x1172
cmd/go/internal/load.(*Package).load(0xc00008a900, 0xc0002cfa30, 0xc0001e6000, 0x0, 0x0)
	/data/golang/workdir/go/src/cmd/go/internal/load/pkg.go:1403 +0x219c
cmd/go/internal/load.loadPackage(0x3ffce1ffcac, 0x7, 0xc0002cfa30, 0x0)
	/data/golang/workdir/go/src/cmd/go/internal/load/pkg.go:1780 +0x6ae
cmd/go/internal/load.PackagesAndErrors(0xc0000100e0, 0x4, 0x4, 0x0, 0x3ffbb940000, 0x0)
	/data/golang/workdir/go/src/cmd/go/internal/load/pkg.go:1851 +0x238
cmd/go/internal/load.PackagesForBuild(0xc0000100e0, 0x4, 0x4, 0x3bebe0, 0x0, 0x0)
	/data/golang/workdir/go/src/cmd/go/internal/load/pkg.go:1897 +0x42
cmd/go/internal/work.runInstall(0x6ebd00, 0xc0000100e0, 0x4, 0x4)
	/data/golang/workdir/go/src/cmd/go/internal/work/build.go:417 +0x42
main.main()
	/data/golang/workdir/go/src/cmd/go/main.go:219 +0xa0c

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/data/golang/workdir/go/src/runtime/sigqueue.go:139 +0xe8
os/signal.loop()
	/data/golang/workdir/go/src/os/signal/signal_unix.go:23 +0x1e
created by os/signal.init.0
	/data/golang/workdir/go/src/os/signal/signal_unix.go:29 +0x3c
go tool dist: FAILED: /data/golang/workdir/go/pkg/tool/linux_s390x/go_bootstrap install -gcflags=all= -ldflags=all= -i cmd/asm cmd/cgo cmd/compile cmd/link: exit status 2
```

</details>

**Comment by ALTree** [comment]
Thanks for the report. This is a dup of #29453, so I'm closing here.
