### ISSUE TITLE
x/mobile/bind: panic on alias to builtin type (e.g. string)

### ISSUE THREAD

**Issue by mijola** [golang/go#29559]
### What version of Go are you using (`go version`)?
go version go1.11.4 darwin/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOOS="darwin"

### What did you do?

// hello.go 
```
package hello
type DeviceType = string
```
Run: gomobile bind -target=ios .

### What did you expect to see?
Succeeded to generate objc framework

### What did you see instead?
```
panic: interface conversion: types.Type is *types.Basic, not *types.Named

goroutine 1 [running]:
golang.org/x/mobile/bind.(*Generator).Init(0xc0000b6dc0)
        /Users/gopher/go/src/golang.org/x/mobile/bind/gen.go:149 +0x1313
golang.org/x/mobile/bind.GenGo(0xc000022a00, 0x1b, 0x137cdc0)
        /Users/gopher/go/src/golang.org/x/mobile/bind/bind.go:45 +0x1a4
main.genPkg(0x7ffeefbff74d, 0x2, 0xc00000f810, 0xc00000c190, 0x1, 0x1, 0xc00000c118, 0x1, 0x1, 0x0, ...)
        /Users/gopher/go/src/golang.org/x/mobile/cmd/gobind/gen.go:116 +0x1dce
main.run()
        /Users/gopher/go/src/golang.org/x/mobile/cmd/gobind/main.go:158 +0xa27
main.main()
        /Users/gopher/go/src/golang.org/x/mobile/cmd/gobind/main.go:45 +0x27
```

**Comment by mijola** [comment]
It's OK for alias to named type, doesn't work for alias to builtin type. Thanks:)
