### ISSUE TITLE
cmd/api: "go tool api" panics on certain package names

### ISSUE THREAD

**Issue by ALTree** [golang/go#29837]
```
$ gotip version
go version devel +5538a9a34f Fri Jan 18 22:41:47 2019 +0000 linux/amd64
```

The `go tool api` tool is supposed to be called with package names, like this:

```
$ gotip tool api fmt
```

And it correctly prints an error on not-existing package names:

```
$ gotip tool api badbadbad
2019/01/19 18:59:26 no source in tree for import "badbadbad": stat /home/alberto/go/src/badbadbad: no such file or directory
```

I noticed it crashes with an `invalid memory address or nil pointer dereference` on certain words. For example, `go`:

```
$ gotip tool api go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5c0468]

goroutine 1 [running]:
go/types.(*Package).Path(...)
	/home/alberto/go/src/go/types/package.go:30
main.(*Walker).export(0xc000099360, 0x0)
	/home/alberto/go/src/cmd/api/goapi.go:232 +0x48
main.main()
	/home/alberto/go/src/cmd/api/goapi.go:173 +0x6df
```

and `cmd`:

```
$ gotip tool api cmd
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5c0468]

goroutine 1 [running]:
go/types.(*Package).Path(...)
	/home/alberto/go/src/go/types/package.go:30
main.(*Walker).export(0xc000099360, 0x0)
	/home/alberto/go/src/cmd/api/goapi.go:232 +0x48
main.main()
	/home/alberto/go/src/cmd/api/goapi.go:173 +0x6df
```

**Comment by ALTree** [comment]
Tentatively milestoning as `1.12` since the new `api` tool was introduced during the `1.12` release cycle.
