### ISSUE TITLE
runtime: SIGILL: illegal instruction from runtime.deductSweepCredit

### ISSUE THREAD

**Issue by vishwaspai** [golang/go#29862]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, go 1.11.4.  But happened only once. 

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

/usr/local/go1.11.4/go/bin# ./go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/var/jenkins_home/workspace"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go1.11.4/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go1.11.4/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build108139547=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

Nothing specific was being done. This code has been running unmodified for few days without any issue.

### What did you expect to see?

No panic

### What did you see instead?

SIGILL: illegal instruction
PC=0x420c60 m=8 sigcode=2

goroutine 0 [idle]:
runtime.deductSweepCredit(0x2000, 0x0)
        /usr/local/go1.11.4/go/src/runtime/mgcsweep.go:390
runtime.(*mcentral).cacheSpan(0x1385618, 0xc0005cfca8)
        /usr/local/go1.11.4/go/src/runtime/mcentral.go:43 +0x60
runtime.(*mcache).refill(0x7f95da4e3000, 0xc0005cfc11)
        /usr/local/go1.11.4/go/src/runtime/mcache.go:122 +0x95
runtime.(*mcache).nextFree.func1()
        /usr/local/go1.11.4/go/src/runtime/malloc.go:749 +0x32
runtime.systemstack(0x0)
        /usr/local/go1.11.4/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
        /usr/local/go1.11.4/go/src/runtime/proc.go:1229

goroutine 444 [running]:
runtime.systemstack_switch()
        /usr/local/go1.11.4/go/src/runtime/asm_amd64.s:311
fp=0xc0005cf9a0 sp=0xc0005cf998 pc=0x4581d0
runtime.(*mcache).nextFree(0x7f95da4e3000, 0x11, 0x1000100,
0xc0005cfa40, 0x40a03d)
        /usr/local/go1.11.4/go/src/runtime/malloc.go:748 +0xb6
fp=0xc0005cf9f8 sp=0xc0005cf9a0 pc=0x40b756
runtime.mallocgc(0x70, 0xb96800, 0x1, 0x0)
        /usr/local/go1.11.4/go/src/runtime/malloc.go:903 +0x793
fp=0xc0005cfa98 sp=0xc0005cf9f8 pc=0x40c0a3
runtime.makeslice(0xb96800, 0x65, 0x65, 0x0, 0x0, 0xa891ff)

...
rax    0x2000
rbx    0x7f95d827c350
rcx    0x8
rdx    0x440
rdi    0x4553c0
rsi    0x137ddc0
rbp    0xc000399f70
rsp    0xc000399f30
r8     0x1
r9     0x11
r10    0x7f95d827c350
r11    0x7fffffffffffff
r12    0x0
r13    0x49
r14    0x49
r15    0x49
rip    0x420c60
rflags 0x10206
cs     0x33
fs     0x0
gs     0x0

*Processor*

processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 79
model name      : Intel(R) Xeon(R) CPU @ 2.20GHz
stepping        : 0
microcode       : 0x1
cpu MHz         : 2200.000
cache size      : 56320 KB
physical id     : 0
siblings        : 2
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge
mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb
rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid pni
pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes
xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch
invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle
avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat
arch_capabilities
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips        : 4400.00
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

*Runtime*

Kubernetes 1.11.6  with Google COS os.

docker version
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.10.3
 Git commit:   f5ec1e2
 Built:        Thu Oct 25 10:42:32 2018
 OS/Arch:      linux/amd64
Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.10.3
 Git commit:   f5ec1e2
 Built:        Thu Oct 25 10:42:32 2018
 OS/Arch:      linux/amd64
 Experimental: false

*Assembly a the PC*

(gdb) disassemble 0x420c60
Dump of assembler code for function runtime.deductSweepCredit:
   **0x0000000000420c60 <+0>: mov    %fs:0xfffffffffffffff8,%rcx**
   0x0000000000420c69 <+9>: cmp    0x10(%rcx),%rsp
   0x0000000000420c6d <+13>: jbe    0x420dc8 <runtime.deductSweepCredit+360>
   0x0000000000420c73 <+19>: sub    $0x20,%rsp
   0x0000000000420c77 <+23>: mov    %rbp,0x18(%rsp)
   0x0000000000420c7c <+28>: lea    0x18(%rsp),%rbp
   0x0000000000420c81 <+33>: movsd  0xf642cf(%rip),%xmm0        #
0x1384f58 <runtime.mheap_+4280>
   0x0000000000420c89 <+41>: xorps  %xmm1,%xmm1
   0x0000000000420c8c <+44>: ucomisd %xmm1,%xmm0
   0x0000000000420c90 <+48>: jne    0x420c98 <runtime.deductSweepCredit+56>
   0x0000000000420c92 <+50>: jnp    0x420dbe <runtime.deductSweepCredit+350>
   0x0000000000420c98 <+56>: lea    0xf6a751(%rip),%rax        #
0x138b3f0 <runtime.trace+16>
   0x0000000000420c9f <+63>: cmpb   $0x0,(%rax)
   0x0000000000420ca2 <+66>: jne    0x420daa <runtime.deductSweepCredit+330>
   0x0000000000420ca8 <+72>: mov    0x28(%rsp),%rcx
   0x0000000000420cad <+77>: mov    0x30(%rsp),%rdx
   0x0000000000420cb2 <+82>: jmp    0x420d1c <runtime.deductSweepCredit+188>
   0x0000000000420cb4 <+84>: lea    0xf6a735(%rip),%rax        #
0x138b3f0 <runtime.trace+16>
   0x0000000000420cbb <+91>: mov    0x28(%rsp),%rcx
   0x0000000000420cc0 <+96>: mov    0x30(%rsp),%rdx
   0x0000000000420cc5 <+101>: mov    0x8(%rsp),%rbx
   0x0000000000420cca <+106>: mov    0x10(%rsp),%rsi
   0x0000000000420ccf <+111>: xorps  %xmm1,%xmm1
   0x0000000000420cd2 <+114>: mov    0xf64267(%rip),%rdi        #
0x1384f40 <runtime.mheap_+4256>
   0x0000000000420cd9 <+121>: sub    %rbx,%rdi
   0x0000000000420cdc <+124>: cmp    %rdi,%rsi
   0x0000000000420cdf <+127>: jle    0x420d72 <runtime.deductSweepCredit+274>
   0x0000000000420ce5 <+133>: callq  0x4201c0 <runtime.gosweepone>
   0x0000000000420cea <+138>: cmpq   $0xffffffffffffffff,(%rsp)
   0x0000000000420cef <+143>: je     0x420d67 <runtime.deductSweepCredit+263>
   0x0000000000420cf1 <+145>: mov    0xf64250(%rip),%rax        #
0x1384f48 <runtime.mheap_+4264>
   0x0000000000420cf8 <+152>: mov    0x8(%rsp),%rcx
   0x0000000000420cfd <+157>: cmp    %rcx,%rax
   0x0000000000420d00 <+160>: je     0x420cb4 <runtime.deductSweepCredit+84>

**Comment by agnivade** [comment]
> This code has been running unmodified for few days without any issue.

Which code ? How do we run it ? Could you show us a small self-contained code which shows the issue ? That will help us debug the issue further.

Have you tried with 1.12beta2 to see if the problem exists there too ?

Thanks.

**Comment by vishwaspai** [comment]
> > This code has been running unmodified for few days without any issue.
> 
> Which code ? How do we run it ? Could you show us a small self-contained code which shows the issue ? That will help us debug the issue further.
> 
> Have you tried with 1.12beta2 to see if the problem exists there too ?
> 
> Thanks.

Right now there nothing in this crash stack trace that gives me hints on creating a self contained snippet that makes this reproducible. Project is compiled as a static go binary running inside a pod in Kubernetes (environment details specified). 

Problem happened once and if it starts repeating multiple times, we will experiment with 1.12 and see if this is specific to 1.11.4.

I would like to understand why the following go runtime is an illegal instruction (full disassembly provided).
   runtime.deductSweepCredit:
   0x0000000000420c60 <+0>: mov %fs:0xfffffffffffffff8,%rcx

**Comment by agnivade** [comment]
It maybe possible that there is a memory corruption somewhere. Please also try to run a race enabled binary to ensure there is no race anywhere.

Also, is that the entire stack trace ? There should also be some user-level code in it.

I will page some folks who can shed some light @ianlancetaylor @randall77 @aclements.

**Comment by vishwaspai** [comment]
Attached full stack trace.
[sigill.log](https://github.com/golang/go/files/2782346/sigill.log)

**Comment by ianlancetaylor** [comment]
I have to agree that a `SIGILL` that has occurred once is most likely memory corruption.  `SIGILL` does not indicate a transient condition.

**Comment by vishwaspai** [comment]
Text/code section can not be corrupted by user code, right? Are you suggesting that there must be hardware bit flip type corruption which caused SIGILL ?

**Comment by ianlancetaylor** [comment]
Yes, I am suggesting a hardware problem.

Of course if it happens on a different machine then my suggestion is almost certainly wrong.  But a single occurrence of `SIGILL` on a single machine is likely a hardware problem.  They do happen.

**Comment by vishwaspai** [comment]
Thanks. I've asked the hosting provider if they provide any guarantees on hardware corruption (using ECC or other mechanisms).

**Comment by vishwaspai** [comment]
Hosting provider is yet to get back to us on the memory corruption. 

But this time a different program running in the same environment (different H/W node and VM) has crashed with SIGSEGV around the same location. If this is same as the previous problem, then it is not pointing towards hardware corruption.

Stack trace:

2019-01-23T09:04:07.309761319Z fatal error: unexpected signal during runtime execution
2019-01-23T09:04:07.3173336Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x2000 pc=0x420c60]
2019-01-23T09:04:07.317392724Z
2019-01-23T09:04:07.317424651Z runtime stack:
2019-01-23T09:04:07.317428766Z runtime.throw(0xcb85af, 0x2a)
2019-01-23T09:04:07.317432608Z  /usr/local/go1.11.4/go/src/runtime/panic.go:608 +0x72
2019-01-23T09:04:07.317437176Z runtime.sigpanic()
2019-01-23T09:04:07.317456298Z  /usr/local/go1.11.4/go/src/runtime/signal_unix.go:374 +0x2f2
2019-01-23T09:04:07.317503889Z runtime.deductSweepCredit(0x2000, 0x0)
2019-01-23T09:04:07.317508757Z  /usr/local/go1.11.4/go/src/runtime/mgcsweep.go:390
2019-01-23T09:04:07.317512666Z runtime.(*mcentral).cacheSpan(0x13107f8, 0xc000686c10)
2019-01-23T09:04:07.317542341Z  /usr/local/go1.11.4/go/src/runtime/mcentral.go:43 +0x60
2019-01-23T09:04:07.317556883Z runtime.(*mcache).refill(0x7fc90a4956c0, 0xc000686b38)
2019-01-23T09:04:07.317565158Z  /usr/local/go1.11.4/go/src/runtime/mcache.go:122 +0x95
2019-01-23T09:04:07.317576046Z runtime.(*mcache).nextFree.func1()
2019-01-23T09:04:07.317580455Z  /usr/local/go1.11.4/go/src/runtime/malloc.go:749 +0x32
2019-01-23T09:04:07.317584669Z runtime.systemstack(0x0)
2019-01-23T09:04:07.317588461Z  /usr/local/go1.11.4/go/src/runtime/asm_amd64.s:351 +0x66
2019-01-23T09:04:07.317592646Z runtime.mstart()
2019-01-23T09:04:07.317600498Z  /usr/local/go1.11.4/go/src/runtime/proc.go:1229

Assembly at PC:

(gdb) disassemble 0x420c60
Dump of assembler code for function runtime.deductSweepCredit:
   0x0000000000420c60 <+0>:     mov    %fs:0xfffffffffffffff8,%rcx
   0x0000000000420c69 <+9>:     cmp    0x10(%rcx),%rsp
   0x0000000000420c6d <+13>:    jbe    0x420dc8 <runtime.deductSweepCredit+360>
   0x0000000000420c73 <+19>:    sub    $0x20,%rsp
   0x0000000000420c77 <+23>:    mov    %rbp,0x18(%rsp)
   0x0000000000420c7c <+28>:    lea    0x18(%rsp),%rbp
   0x0000000000420c81 <+33>:    movsd  0xeeeaef(%rip),%xmm0        # 0x130f778 <runtime.mheap_+4280>
   0x0000000000420c89 <+41>:    xorps  %xmm1,%xmm1
   0x0000000000420c8c <+44>:    ucomisd %xmm1,%xmm0
   0x0000000000420c90 <+48>:    jne    0x420c98 <runtime.deductSweepCredit+56>
   0x0000000000420c92 <+50>:    jnp    0x420dbe <runtime.deductSweepCredit+350>
   0x0000000000420c98 <+56>:    lea    0xef4f71(%rip),%rax        # 0x1315c10 <runtime.trace+16>
   0x0000000000420c9f <+63>:    cmpb   $0x0,(%rax)
   0x0000000000420ca2 <+66>:    jne    0x420daa <runtime.deductSweepCredit+330>
   0x0000000000420ca8 <+72>:    mov    0x28(%rsp),%rcx
   0x0000000000420cad <+77>:    mov    0x30(%rsp),%rdx
   0x0000000000420cb2 <+82>:    jmp    0x420d1c <runtime.deductSweepCredit+188>
   0x0000000000420cb4 <+84>:    lea    0xef4f55(%rip),%rax        # 0x1315c10 <runtime.trace+16>
   0x0000000000420cbb <+91>:    mov    0x28(%rsp),%rcx
   0x0000000000420cc0 <+96>:    mov    0x30(%rsp),%rdx
   0x0000000000420cc5 <+101>:   mov    0x8(%rsp),%rbx
   0x0000000000420cca <+106>:   mov    0x10(%rsp),%rsi
   0x0000000000420ccf <+111>:   xorps  %xmm1,%xmm1

Full stack trace attached below.
[sigsegv.log](https://github.com/golang/go/files/2786553/sigsegv.log)

**Comment by vishwaspai** [comment]
SIGILL at the same location on a different Node+VM happened again.

2019-01-23T12:16:06.202968107Z SIGILL: illegal instruction
2019-01-23T12:16:06.203027783Z PC=0x420c60 m=7 sigcode=2
2019-01-23T12:16:06.203034227Z
2019-01-23T12:16:06.203038628Z goroutine 0 [idle]:
2019-01-23T12:16:06.203155238Z runtime.deductSweepCredit(0x2000, 0x0)
2019-01-23T12:16:06.203162347Z  /usr/local/go1.11.4/go/src/runtime/mgcsweep.go:390
2019-01-23T12:16:06.203167258Z runtime.(*mcentral).cacheSpan(0x1386598, 0xc000684b68)
2019-01-23T12:16:06.20317127Z   /usr/local/go1.11.4/go/src/runtime/mcentral.go:43 +0x60
2019-01-23T12:16:06.203175828Z runtime.(*mcache).refill(0x7f73c182e6c0, 0x45bb0e)
2019-01-23T12:16:06.203180122Z  /usr/local/go1.11.4/go/src/runtime/mcache.go:122 +0x95
2019-01-23T12:16:06.203184492Z runtime.(*mcache).nextFree.func1()
2019-01-23T12:16:06.203220704Z  /usr/local/go1.11.4/go/src/runtime/malloc.go:749 +0x32
2019-01-23T12:16:06.203226099Z runtime.systemstack(0x0)
2019-01-23T12:16:06.203230572Z  /usr/local/go1.11.4/go/src/runtime/asm_amd64.s:351 +0x66
2019-01-23T12:16:06.203235035Z runtime.mstart()
2019-01-23T12:16:06.203239356Z  /usr/local/go1.11.4/go/src/runtime/proc.go:1229
..
..
2019-01-23T12:16:06.311989625Z
2019-01-23T12:16:06.311991885Z rax    0x2000
2019-01-23T12:16:06.311994209Z rbx    0x7f73bf5ca898
2019-01-23T12:16:06.311996577Z rcx    0x7
2019-01-23T12:16:06.311998853Z rdx    0x380
2019-01-23T12:16:06.31202658Z rdi    0x4553c0
2019-01-23T12:16:06.312029347Z rsi    0x137ee00
2019-01-23T12:16:06.312031667Z rbp    0xc0000c1f70
2019-01-23T12:16:06.312033982Z rsp    0xc0000c1f30
2019-01-23T12:16:06.312036301Z r8     0x0
2019-01-23T12:16:06.312038613Z r9     0xe
2019-01-23T12:16:06.312040859Z r10    0x7f73bf5ca898
2019-01-23T12:16:06.312043194Z r11    0x0
2019-01-23T12:16:06.312045797Z r12    0x40
2019-01-23T12:16:06.312048176Z r13    0x40
2019-01-23T12:16:06.312050418Z r14    0xc000684fc8
2019-01-23T12:16:06.312052699Z r15    0x0
2019-01-23T12:16:06.31205496Z rip    0x420c60
2019-01-23T12:16:06.312057312Z rflags 0x10206
2019-01-23T12:16:06.312059595Z cs     0x33
2019-01-23T12:16:06.312061877Z fs     0x0
2019-01-23T12:16:06.312064173Z gs     0x0

**Comment by ianlancetaylor** [comment]
Thanks, that's interesting.  I have no idea what could cause this.  The instruction looks fine, and presumably the same instruction is executed many times in different functions, so why a `SIGILL`?

Is there anything in the kernel logs?

The sigcode  value of `2` is `ILL_ILLOPN` which means "illegal operand."  But looking at the kernel code it seems that is always the sigcode value for `SIGILL` so maybe that doesn't mean anything.

In the stack trace `deductSweepCredit` is called from `cacheSpan`, which starts with the exact same instruction.  It seems implausible that `%fs` would have changed or that the memory mappings would have changed.  The stack pointer is not at a page boundary.  The `SIGSEGV` refers to address `0x2000`, which doesn't make much sense.

You said it was a static Go binary.  Is there any C code in the program, or is it pure Go?

Approximately how often does this happen?  That is, you've seen it twice or maybe three times; how many times is your program running in that time period?

I gather your program is running inside a VM?  Do you have any information about that?

**Comment by vishwaspai** [comment]
Thanks for looking into this.

- Can not find anything interesting in kernel log.

- Seen this problem 3 times in 2 days. 2 of those with the same program running in different dockers (pods on VM in kubernetes). Once (sigsegv) in a different program.

- All binaries are 64bit X86 Linux Pure Go. (no C/Cgo involved)

**Comment by ianlancetaylor** [comment]
3 times in 2 days, but approximately how many instances of the program were run during those 2 days?

**Comment by ianlancetaylor** [comment]
CC @aclements

**Comment by vishwaspai** [comment]
> 3 times in 2 days, but approximately how many instances of the program were run during those 2 days?

- 2 SIGILL from 4 instances and 1 SIGSEGV from 2 instances.

- I just had another SIGSEGV but stack trace is different (but around runtime). I'm not adding this here as that might not be relevant for this issue.

- I've now started suspecting hardware again. Last 2 instances have happened on the same hardware node. I'm asking hosting provider to check that specific hardware.

**Comment by vishwaspai** [comment]
- Hosting provider is still investigating the issue. We are still using the VM so that they can debug the issue.

- We had another instance of this issue (SIGSEGV). What I'm unable to comprehend is the fact that even if this is hardware issue , why does this happen exactly at this point in this specific routine.

- This time it was completely different program that crashed (on the same VM). This is just filebeat go client with very little code change from us.

2019-01-25T09:20:06.904573082Z fatal error: unexpected signal during runtime execution
2019-01-25T09:20:06.906516185Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x2000 pc=0x420c14]
2019-01-25T09:20:06.906580802Z
2019-01-25T09:20:06.906585345Z runtime stack:
2019-01-25T09:20:06.9068671Z runtime.throw(0xf52299, 0x2a)
2019-01-25T09:20:07.004213396Z  /usr/local/go1.11.4/go/src/runtime/panic.go:608 +0x72
2019-01-25T09:20:07.004427053Z runtime.sigpanic()
2019-01-25T09:20:07.004431906Z  /usr/local/go1.11.4/go/src/runtime/signal_unix.go:374 +0x2f2
2019-01-25T09:20:07.004434998Z runtime.deductSweepCredit(0x2000, 0x0)
2019-01-25T09:20:07.004437681Z  /usr/local/go1.11.4/go/src/runtime/mgcsweep.go:390 +0x4
2019-01-25T09:20:07.00444066Z runtime.(*mcentral).cacheSpan(0x18e1018, 0xc00058e900)
2019-01-25T09:20:07.004443314Z  /usr/local/go1.11.4/go/src/runtime/mcentral.go:43 +0x60
2019-01-25T09:20:07.004445959Z runtime.(*mcache).refill(0x7f225e8ae6c0, 0xc000001608)
2019-01-25T09:20:07.004448507Z  /usr/local/go1.11.4/go/src/runtime/mcache.go:122 +0x95
2019-01-25T09:20:07.004451169Z runtime.(*mcache).nextFree.func1()
2019-01-25T09:20:07.004454107Z  /usr/local/go1.11.4/go/src/runtime/malloc.go:749 +0x32
2019-01-25T09:20:07.004456776Z runtime.systemstack(0x0)
2019-01-25T09:20:07.004459596Z  /usr/local/go1.11.4/go/src/runtime/asm_amd64.s:351 +0x66
2019-01-25T09:20:07.004462483Z runtime.mstart()
2019-01-25T09:20:07.004500865Z  /usr/local/go1.11.4/go/src/runtime/proc.go:1229

**Comment by vishwaspai** [comment]
No significant update from hosting provider yet. Several crashes have happened in the past few days. One being "kubectl" command (which is not built or modified by us).

Latest instance is failure of "kubectl" command (trace below).

2019-01-28T02:48:05.901242067Z SIGILL: illegal instruction
2019-01-28T02:48:05.901333098Z PC=0x420d36 m=6 sigcode=2
2019-01-28T02:48:05.90133851Z
2019-01-28T02:48:05.901342404Z goroutine 0 [idle]:
2019-01-28T02:48:05.901346133Z runtime.(*mheap).alloc_m(0x25676e0, 0x1, 0x1c, 0x7fb8afe69000)
2019-01-28T02:48:05.901350095Z  /usr/local/go/src/runtime/mheap.go:536 +0x6
2019-01-28T02:48:05.901354404Z runtime.(*mheap).alloc.func1()
2019-01-28T02:48:05.901360696Z  /usr/local/go/src/runtime/mheap.go:627 +0x4b
2019-01-28T02:48:05.901364515Z runtime.systemstack(0xc42005be90)
2019-01-28T02:48:05.901368395Z  /usr/local/go/src/runtime/asm_amd64.s:343 +0xab
2019-01-28T02:48:05.901769977Z runtime.(*mheap).alloc(0x25676e0, 0x1, 0x1000000001c, 0x7fb8aff29718)
2019-01-28T02:48:05.901790953Z  /usr/local/go/src/runtime/mheap.go:628 +0xa0
2019-01-28T02:48:05.901795287Z runtime.(*mcentral).grow(0x2569650, 0x0)
2019-01-28T02:48:05.901799256Z  /usr/local/go/src/runtime/mcentral.go:212 +0x8e
2019-01-28T02:48:05.901803089Z runtime.(*mcentral).cacheSpan(0x2569650, 0x7fb8aff29bd8)
2019-01-28T02:48:05.901806835Z  /usr/local/go/src/runtime/mcentral.go:93 +0x12a
2019-01-28T02:48:05.90181091Z runtime.(*mcache).refill(0x7fb8b01694b0, 0x7fb80000001c, 0x7fb8aff29bd8)
2019-01-28T02:48:05.901814819Z  /usr/local/go/src/runtime/mcache.go:122 +0xa0
2019-01-28T02:48:05.901836021Z runtime.(*mcache).nextFree.func1()
2019-01-28T02:48:05.901839737Z  /usr/local/go/src/runtime/malloc.go:538 +0x32
2019-01-28T02:48:05.901843404Z runtime.systemstack(0xc420018000)
2019-01-28T02:48:05.901846845Z  /usr/local/go/src/runtime/asm_amd64.s:327 +0x79
2019-01-28T02:48:05.901850514Z runtime.mstart()
2019-01-28T02:48:05.901853923Z  /usr/local/go/src/runtime/proc.go:1132

**Comment by vishwaspai** [comment]
Occurrence of these issues stopped after change of hardware node on which these crashes were happening. Hosting provider has not given any technical details around what might have caused the issue (tick still pending with them). 

This golang git issue can be closed.

/close

**Comment by ianlancetaylor** [comment]
Thanks for following up.

Sorry about your hardware.
