### ISSUE TITLE
cmd/compile: crash when compiling function named "_"

### ISSUE THREAD

**Issue by alandonovan** [golang/go#29870]
```
$ go version
go version devel +cad6d1fef5 Mon Jan 21 23:31:09 2019 +0000 linux/amd64
$ cat test/test.go 
package test

import "log"

func a() {
        log.Println("%2F")
}
$ go build test
$ sed -i -e 's/func a/func _/' test/test.go
$ go build test
# test
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0xc4e259]

goroutine 50 [running]:
cmd/compile/internal/gc.emitStackObjects(0xc000538000, 0xc0005ea0e0)
        ~/goroot/src/cmd/compile/internal/gc/ssa.go:5057 +0x1c9
cmd/compile/internal/gc.genssa(0xc00053c000, 0xc0005ea0e0)
        ~/goroot/src/cmd/compile/internal/gc/ssa.go:5092 +0xe1
cmd/compile/internal/gc.compileSSA(0xc0000cc420, 0x1)
        ~/goroot/src/cmd/compile/internal/gc/pgen.go:301 +0x378
cmd/compile/internal/gc.compileFunctions.func2(0xc0004fcf60, 0xc0004fe1d0, 0x1)
        ~/goroot/src/cmd/compile/internal/gc/pgen.go:356 +0x49
created by cmd/compile/internal/gc.compileFunctions
        ~/goroot/src/cmd/compile/internal/gc/pgen.go:354 +0x129
```

**Comment by bcmills** [comment]
CC @randall77 @josharian @martisch

**Comment by randall77** [comment]
This was introduced as part of adding stack objects.  Fix out for review.

Do we care about functions named "_"?  Is there any legitimate use for them?  If so, we should fix this in 1.12.  If not, we can leave for 1.13.

**Comment by bcmills** [comment]
I could imagine someone using them to contain static assertions: that is, a function named `_` that fails to compile if certain conditions (such as equality of sizes) are not met.

I don't know whether anyone does that in practice.

**Comment by randall77** [comment]
The latter CL is for 1.12. The former CL has more clean up in it and will go in for 1.13.
