### ISSUE TITLE
cmd/compile: compiler crash compiling call to runtime.memmove

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#30061]
The compiler seems to recognize calls to `runtime.memmove` specially, and crashes when compiling code that calls it.

```Go
package p

import "unsafe"

//go:linkname memmove runtime.memmove
func memmove(to, from unsafe.Pointer, n uintptr)

var V1, V2 int

func F() {
	memmove(unsafe.Pointer(&V1), unsafe.Pointer(&V2), unsafe.Sizeof(int(0)))
}
```

```
> go build ~/foo.go
# command-line-arguments
<autogenerated>:1: internal compiler error: Type.Elem UNSAFEPTR

goroutine 34 [running]:
runtime/debug.Stack(0xf81b00, 0xc00000e018, 0x0)
	/home/iant/go/src/runtime/debug/stack.go:24 +0x9d
cmd/compile/internal/gc.Fatalf(0xdd3a25, 0xc, 0xc0004fe030, 0x1, 0x1)
	/home/iant/go/src/cmd/compile/internal/gc/subr.go:190 +0x293
cmd/compile/internal/types.(*Type).Elem(0xc000065e60, 0xc000000815)
	/home/iant/go/src/cmd/compile/internal/types/type.go:796 +0xff
cmd/compile/internal/ssa.rewriteValuegeneric_OpStaticCall_0(0xc0003ad1b8, 0x0)
	/home/iant/go/src/cmd/compile/internal/ssa/rewritegeneric.go:27433 +0x634
cmd/compile/internal/ssa.rewriteValuegeneric(0xc0003ad1b8, 0x0)
	/home/iant/go/src/cmd/compile/internal/ssa/rewritegeneric.go:415 +0x20a5
cmd/compile/internal/ssa.applyRewrite(0xc0004f0000, 0xdf3d08, 0xdf3d70)
	/home/iant/go/src/cmd/compile/internal/ssa/rewrite.go:80 +0x35f
cmd/compile/internal/ssa.opt(0xc0004f0000)
	/home/iant/go/src/cmd/compile/internal/ssa/opt.go:9 +0x43
cmd/compile/internal/ssa.Compile(0xc0004f0000)
	/home/iant/go/src/cmd/compile/internal/ssa/compile.go:90 +0x46f
cmd/compile/internal/gc.buildssa(0xc0000ca420, 0x1, 0x0)
	/home/iant/go/src/cmd/compile/internal/gc/ssa.go:233 +0xbe9
cmd/compile/internal/gc.compileSSA(0xc0000ca420, 0x1)
	/home/iant/go/src/cmd/compile/internal/gc/pgen.go:299 +0x4d
cmd/compile/internal/gc.compileFunctions.func2(0xc0004aa6c0, 0xc0004b6120, 0x1)
	/home/iant/go/src/cmd/compile/internal/gc/pgen.go:364 +0x49
created by cmd/compile/internal/gc.compileFunctions
	/home/iant/go/src/cmd/compile/internal/gc/pgen.go:362 +0x129
```

**Comment by randall77** [comment]
The compiler is trying to find the element type of an unsafe pointer.
We're not expecting someone to linkname memmove like this...
Should be easy to fix, just disable the rule in this case (the rule converts memmove calls to direct load/store instructions).
