### ISSUE TITLE
x/sys/cpu: cpu_linux.go:31 /proc/self/auxv: permission denied on android/arm

### ISSUE THREAD

**Issue by rayvbr** [golang/go#30413]
### What version of Go are you using (`go version`)?
Go 1.12

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Using 'gomobile bind' to compile to android/arm

### What did you do?
Compile arbitrary library (hello world) to android/arm using 'gomobile bind' (Android NDK 19b). Include in Android Java app. 

Note: used git head of golang.org/x/sys (golang/sys@cc5685c)

### What did you expect to see?
Running application

### What did you see instead?
```
2019-02-26 19:12:32.502 8053-0/? E/Go: panic: read proc auxv failed: open /proc/self/auxv: permission denied
2019-02-26 19:12:32.502 8053-8094/? E/GoLog: panic: read proc auxv failed: open /proc/self/auxv: permission denied
2019-02-26 19:12:32.502 8053-0/? E/Go: goroutine 1 [running]:
2019-02-26 19:12:32.502 8053-0/? E/Go: <redacted>vendor/golang.org/x/sys/cpu.init.0()
2019-02-26 19:12:32.502 8053-0/? E/Go: 	<redacted>/vendor/golang.org/x/sys/cpu/cpu_linux.go:31 +0x1ac
2019-02-26 19:12:32.503 8053-8090/? E/CRASH: signal 6 (SIGABRT), code -6 (?), fault addr --------
2019-02-26 19:12:32.503 8053-8090/? E/CRASH: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
```

**Comment by rayvbr** [comment]
Note 1: The problem seems limited to android/arm. android/arm64 seems to work.
Note 2: using git head (cc5685c2db1239775905f3911f0067c0fa74762f) of golang.org/sys/cpu

**Comment by rayvbr** [comment]
Possibly related to https://github.com/golang/go/issues/9229

**Comment by rayvbr** [comment]
Note that not all chipsets seem affected. Crash above was on Snapdragon 821. Exynos 8895 seems unaffected

**Comment by rayvbr** [comment]
Problem resolved! Thanks guys!
