### ISSUE TITLE
all: failed to buld from source with commit fe954ea1e28f8ece95ce00d51312ac095071b2d8

### ISSUE THREAD

**Issue by Gnouc** [golang/go#30650]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/cuonglm/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/cuonglm/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/stow/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/stow/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build024027124=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

From root of git clone repo:

```
$ cd src
$ GOROOT_BOOTSTRAP=/usr/local/stow/go ./make.bash -v
```

### What did you expect to see?

Build success

### What did you see instead?

```
Building Go toolchain3 using go_bootstrap and Go toolchain2.
internal/race
math/bits
unicode/utf8
runtime/internal/sys
runtime/internal/atomic
unicode
internal/cpu
sync/atomic
# unicode/utf8
src/unicode/utf8/utf8.go:64:23: syntax error: unexpected { after top level declaration
src/unicode/utf8/utf8.go:92:36: syntax error: unexpected { after top level declaration
encoding
# math/bits
src/math/bits/bits.go:40:29: syntax error: unexpected { after top level declaration
src/math/bits/bits.go:47:29: syntax error: unexpected { after top level declaration
# runtime/internal/sys
src/runtime/internal/sys/intrinsics.go:13:29: syntax error: unexpected { after top level declaration
src/runtime/internal/sys/intrinsics.go:26:29: syntax error: unexpected { after top level declaration
src/runtime/internal/sys/intrinsics.go:58:25: syntax error: unexpected { after top level declaration
unicode/utf16
# unicode
src/unicode/casetables.go:13:31: syntax error: unexpected { after top level declaration
# internal/cpu
src/internal/cpu/cpu_x86.go:42:20: syntax error: unexpected { at end of statement
src/internal/cpu/cpu_x86.go:43:38: syntax error: unexpected comma after top level declaration
# sync/atomic
<autogenerated>:1: internal compiler error: weird aux: v4 = LEAQ <*string> {""..stmp_0} v3 : AX

goroutine 35 [running]:
runtime/debug.Stack(0x100be80, 0xc00000e018, 0x0)
	/home/cuonglm/sources/go/src/runtime/debug/stack.go:24 +0x9d
cmd/compile/internal/gc.Fatalf(0xe5f76d, 0xd, 0xc0005cb930, 0x1, 0x1)
	/home/cuonglm/sources/go/src/cmd/compile/internal/gc/subr.go:190 +0x293
cmd/compile/internal/gc.affectedNode(0xc00045b810, 0x2, 0x3)
	/home/cuonglm/sources/go/src/cmd/compile/internal/gc/plive.go:360 +0x17b
cmd/compile/internal/gc.(*Liveness).valueEffects(0xc000622000, 0xc00045b810, 0x1, 0x0)
	/home/cuonglm/sources/go/src/cmd/compile/internal/gc/plive.go:288 +0x2f
cmd/compile/internal/gc.(*Liveness).prologue(0xc000622000)
	/home/cuonglm/sources/go/src/cmd/compile/internal/gc/plive.go:819 +0xd5
cmd/compile/internal/gc.liveness(0xc00059c000, 0xc0005a0000, 0xc0005f60e0, 0x0, 0x0, 0x0)
	/home/cuonglm/sources/go/src/cmd/compile/internal/gc/plive.go:1397 +0xa8
cmd/compile/internal/gc.genssa(0xc0005a0000, 0xc0005f60e0)
	/home/cuonglm/sources/go/src/cmd/compile/internal/gc/ssa.go:5104 +0x93
cmd/compile/internal/gc.compileSSA(0xc00038a840, 0x2)
	/home/cuonglm/sources/go/src/cmd/compile/internal/gc/pgen.go:307 +0x36d
cmd/compile/internal/gc.compileFunctions.func2(0xc00052b680, 0xc000528530, 0x2)
	/home/cuonglm/sources/go/src/cmd/compile/internal/gc/pgen.go:362 +0x49
created by cmd/compile/internal/gc.compileFunctions
	/home/cuonglm/sources/go/src/cmd/compile/internal/gc/pgen.go:360 +0x129

# unicode/utf16
<autogenerated>:1: internal compiler error: weird aux: v84 = LEAQ <*uint8> {type.uint16} v3 : AX

<autogenerated>:1: internal compiler error: weird aux: v130 = LEAQ <*uint8> {type.int32} v3 : AX

goroutine 24 [running]:
runtime/debug.Stack(0x100be80, 0xc00000e018, 0x0)
	/home/cuonglm/sources/go/src/runtime/debug/stack.go:24 +0x9d
cmd/compile/internal/gc.Fatalf(0xe5f76d, 0xd, 0xc00057f930, 0x1, 0x1)
	/home/cuonglm/sources/go/src/cmd/compile/internal/gc/subr.go:190 +0x293
cmd/compile/internal/gc.affectedNode(0xc0003838e0, 0x2, 0x3)
	/home/cuonglm/sources/go/src/cmd/compile/internal/gc/plive.go:360 +0x17b
cmd/compile/internal/gc.(*Liveness).valueEffects(0xc000674140, 0xc0003838e0, 0x1, 0x0)
	/home/cuonglm/sources/go/src/cmd/compile/internal/gc/plive.go:288 +0x2f
cmd/compile/internal/gc.(*Liveness).prologue(0xc000674140)
	/home/cuonglm/sources/go/src/cmd/compile/internal/gc/plive.go:819 +0xd5
cmd/compile/internal/gc.liveness(0xc00031b860, 0xc0000d09a0, 0xc0002cc620, 0x0, 0x0, 0x0)
	/home/cuonglm/sources/go/src/cmd/compile/internal/gc/plive.go:1397 +0xa8
cmd/compile/internal/gc.genssa(0xc0000d09a0, 0xc0002cc620)
	/home/cuonglm/sources/go/src/cmd/compile/internal/gc/ssa.go:5104 +0x93
cmd/compile/internal/gc.compileSSA(0xc0000d06e0, 0x0)
	/home/cuonglm/sources/go/src/cmd/compile/internal/gc/pgen.go:307 +0x36d
cmd/compile/internal/gc.compileFunctions.func2(0xc0004cd7a0, 0xc0004bc350, 0x0)
	/home/cuonglm/sources/go/src/cmd/compile/internal/gc/pgen.go:362 +0x49
created by cmd/compile/internal/gc.compileFunctions
	/home/cuonglm/sources/go/src/cmd/compile/internal/gc/pgen.go:360 +0x129

go tool dist: FAILED: /home/cuonglm/sources/go/pkg/tool/linux_amd64/go_bootstrap install -gcflags=all= -ldflags=all= -v -a -i cmd/asm cmd/cgo cmd/compile cmd/link: exit status 2
```

**Comment by Gnouc** [comment]
Sorry, it's my fault when testing https://go-review.googlesource.com/c/go/+/165859
