### ISSUE TITLE
runtime: TestGdbPythonCgo flaky on linux-386 and linux-amd64-race

### ISSUE THREAD

**Issue by bcmills** [golang/go#31569]
https://build.golang.org/log/885863bc2258399f10791b6508f8eef0dbdbd840:

```
--- FAIL: TestGdbPythonCgo (1.26s)
    runtime-gdb_test.go:66: gdb version 7.7
    runtime-gdb_test.go:229: gdb output: Loading Go Runtime support.
        Loading Go Runtime support.
        Breakpoint 1 at 0x80c7ac8: file /workdir/tmp/go-build679205063/main.go, line 15.
        [Thread debugging using libthread_db enabled]
        Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
        [New Thread 0xe7b83b40 (LWP 18609)]
        [New Thread 0xe7382b40 (LWP 18610)]
        [New Thread 0xe6b81b40 (LWP 18611)]
        [New Thread 0xe6180b40 (LWP 18612)]
        
        Breakpoint 1, main.main () at /workdir/tmp/go-build679205063/main.go:15
        15		fmt.Println("hi")
        BEGIN info goroutines
        * 1 running  runtime.systemstack_switch
          2 runnable runtime.forcegchelper
          3 waiting  runtime.gopark
          4 runnable runtime.runfinq
        END
        BEGIN print mapvar
        $1 = map[string]string = {["abc"] = "def", ["ghi"] = "jkl"}
        END
        BEGIN print strvar
        $2 = "abc"
        END
        BEGIN info locals
        mapvar = map[string]string = {["abc"] = "def", ["ghi"] = "jkl"}
        strvar = "abc"
        slicevar =  []string
        END
        BEGIN goroutine 1 bt
        [New Thread 0xe597fb40 (LWP 18613)]
        #0  main.main () at /workdir/tmp/go-build679205063/main.go:15
        END
        BEGIN goroutine 2 bt
        #0  runtime.forcegchelper () at /workdir/go/src/runtime/proc.go:242
        #1  0x08092b01 in runtime.goexit () at /workdir/go/src/runtime/asm_386.s:1324
        #2  0x00000000 in ?? ()
        END
        Breakpoint 2 at 0x80c7b45: file /workdir/tmp/go-build679205063/main.go, line 19.
        hi
        
        Breakpoint 2, main.main () at /workdir/tmp/go-build679205063/main.go:20
        20	}  // END_OF_PROGRAM
        BEGIN goroutine 1 bt at the end
        #0  main.main () at /workdir/tmp/go-build679205063/main.go:20
        END
        
    runtime-gdb_test.go:95: malformed backtrace at line 0: [New Thread 0xe597fb40 (LWP 18613)]
FAIL
FAIL	runtime	20.821s
```

Other examples:
https://build.golang.org/log/ed9084a3e43222de6c5bba9a79936fd3801aa9b4
https://storage.googleapis.com/go-build-log/e5feffcb/linux-386_8f68fa68.log
https://storage.googleapis.com/go-build-log/b5410280/linux-amd64-race_dcb972b2.log

See also #25697.

**Comment by bcmills** [comment]
CC @ianlancetaylor 

Possibly related to https://golang.org/cl/169726? (CC @mundaym @cherrymui)

**Comment by cherrymui** [comment]
Yeah, I think it is due to that CL. It seems that the `[New Thread 0xe597fb40 (LWP 25848)]` output confuses checkCleanBacktrace.
