### ISSUE TITLE
x/tools/cmd/gopls: "slice bounds out of range" when listening on a port

### ISSUE THREAD

**Issue by ainar-g** [golang/go#31570]
Version `4796d4bd`.

```
$ gopls serve --listen :6061
panic: runtime error: slice bounds out of range

goroutine 20 [running]:
bufio.(*Reader).ReadSlice(0xc000098b40, 0xc00009280a, 0xc00006d2b8, 0xc000134ce8, 0xc000134cf8, 0x0, 0x0)
	/home/ainar/go/go1.11/src/bufio/bufio.go:319 +0x20b
bufio.(*Reader).ReadBytes(0xc000098b40, 0xa, 0xc0000ede38, 0xc0000edd80, 0x407b4a, 0x0, 0x0)
	/home/ainar/go/go1.11/src/bufio/bufio.go:419 +0x70
bufio.(*Reader).ReadString(0xc000098b40, 0xa, 0xc00009ed00, 0x450d0987c250b85b, 0x8, 0xc0000eddf0)
	/home/ainar/go/go1.11/src/bufio/bufio.go:459 +0x38
golang.org/x/tools/internal/jsonrpc2.(*headerStream).Read(0xc00009eca0, 0x8a9580, 0xc000092010, 0xc000098ba0, 0xc00009ed80, 0xc00009ed01, 0x0, 0x0)
	/home/ainar/go/src/golang.org/x/tools/internal/jsonrpc2/stream.go:97 +0x84
golang.org/x/tools/internal/jsonrpc2.(*Conn).Run(0xc00016c230, 0x8a9580, 0xc000092010, 0x0, 0x0)
	/home/ainar/go/src/golang.org/x/tools/internal/jsonrpc2/jsonrpc2.go:281 +0xee
golang.org/x/tools/internal/lsp.(*Server).Run(0xc0000bc090, 0x8a9580, 0xc000092010, 0x1000, 0x0)
	/home/ainar/go/src/golang.org/x/tools/internal/lsp/server.go:63 +0x42
created by golang.org/x/tools/internal/lsp.RunServerOnAddress
	/home/ainar/go/src/golang.org/x/tools/internal/lsp/server.go:58 +0xfa
```

If I can provide any additional info, I am ready to help.

**Comment by ianthehat** [comment]
The only time I have seen a crash like this in bufio was because it was being used concurrently.
Not sure how that could be happening in this case, but on the other hand serve --listen mode is only intended for debugging at this point, I would not be surprised if it has problems, especially if more than one client connects to it.

**Comment by stamblerre** [comment]
Closing this issue as obsolete, as @ianthehat has since added the `--debug` flag that should be used instead.
