### ISSUE TITLE
runtime: schedule: holding locks (js/wasm)

### ISSUE THREAD

**Issue by bradfitz** [golang/go#31939]
js/wasm flake: 

https://build.golang.org/log/b658c5bb1f30be3368ddd4b4a6a218b582769d2c
```
##### ../test
# go run run.go -- heapsampling.go
exit status 1
fatal error: schedule: holding locks

runtime stack:
runtime.throw(0x394a5, 0x17)
	/workdir/go/src/runtime/panic.go:714 +0x7
runtime.schedule()
	/workdir/go/src/runtime/proc.go:2465 +0x90
runtime.goschedImpl(0x400780)
	/workdir/go/src/runtime/proc.go:2626 +0x30
runtime.gosched_m(0x400780)
	/workdir/go/src/runtime/proc.go:2634 +0x3
runtime.mcall(0x169cb0)
	/workdir/go/src/runtime/asm_wasm.s:104 +0x1

goroutine 1 [wait for GC cycle]:
runtime.GC()
	/workdir/go/src/runtime/mgc.go:1067 +0x5
main.getMemProfileRecords(0x186a0, 0x1, 0x1)
	/workdir/go/test/heapsampling.go:222 +0x2
main.testInterleavedAllocations(0x1, 0x152a0)
	/workdir/go/test/heapsampling.go:55 +0x6
main.main()
	/workdir/go/test/heapsampling.go:33 +0x2
exit status 2

FAIL	heapsampling.go	10.247s
```

/cc @aclements @neelance

**Comment by bradfitz** [comment]
Presumably fixed by cd03664f82a53dbe20d0b828189158ba3863039c, @mknyszek?

**Comment by mknyszek** [comment]
Yes, but we should still probably wait to see what the bot says before we close it.

**Comment by mknyszek** [comment]
OK bot looks good.
