### ISSUE TITLE
runtime/pprof: "malformed profBuf buffer" on freebsd-arm-paulzhol builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#32025]
https://build.golang.org/log/9fd93dbe71296c536e2c02726f62187c56fae67c

```
fatal error: runtime: malformed profBuf buffer - invalid size

goroutine 34 [running]:
runtime.throw(0x1f52f4, 0x30)
	/tmp/workdir-host-freebsd-arm-paulzhol/go/src/runtime/panic.go:714 +0x5c fp=0x30ae7724 sp=0x30ae7710 pc=0x3ef10
runtime.(*profBuf).read(0x308cc000, 0x0, 0x2, 0x1, 0x5c770, 0x1f9758, 0x2, 0x30abc000, 0x30abe460)
	/tmp/workdir-host-freebsd-arm-paulzhol/go/src/runtime/profbuf.go:538 +0x624 fp=0x30ae7764 sp=0x30ae7724 pc=0x4e23c
runtime/pprof.readProfile(0x5f5e100, 0x0, 0x0, 0x1ffdf, 0x308ce010, 0x0, 0x3ff8)
	/tmp/workdir-host-freebsd-arm-paulzhol/go/src/runtime/cpuprof.go:205 +0x48 fp=0x30ae77ac sp=0x30ae7764 pc=0x16104
runtime/pprof.profileWriter(0x22b4e0, 0x3080b460)
	/tmp/workdir-host-freebsd-arm-paulzhol/go/src/runtime/pprof/pprof.go:780 +0x5c fp=0x30ae77e4 sp=0x30ae77ac pc=0x180198
runtime.goexit()
	/tmp/workdir-host-freebsd-arm-paulzhol/go/src/runtime/asm_arm.s:868 +0x4 fp=0x30ae77e4 sp=0x30ae77e4 pc=0x6cf24
created by runtime/pprof.StartCPUProfile
	/tmp/workdir-host-freebsd-arm-paulzhol/go/src/runtime/pprof/pprof.go:764 +0xf0

goroutine 1 [chan receive]:
testing.(*T).Run(0x30a180a0, 0x1ee9b5, 0x16, 0x1f97f8, 0x1)
	/tmp/workdir-host-freebsd-arm-paulzhol/go/src/testing/testing.go:964 +0x2cc
testing.runTests.func1(0x308ac000)
	/tmp/workdir-host-freebsd-arm-paulzhol/go/src/testing/testing.go:1210 +0x68
testing.tRunner(0x308ac000, 0x30872f10)
	/tmp/workdir-host-freebsd-arm-paulzhol/go/src/testing/testing.go:912 +0xa0
testing.runTests(0x3080c200, 0x344858, 0x19, 0x19, 0x0)
	/tmp/workdir-host-freebsd-arm-paulzhol/go/src/testing/testing.go:1208 +0x238
testing.(*M).Run(0x308a2b00, 0x0)
	/tmp/workdir-host-freebsd-arm-paulzhol/go/src/testing/testing.go:1125 +0x130
main.main()
	_testmain.go:92 +0x120

goroutine 15 [chan receive]:
os/exec.(*Cmd).Wait(0x308860b0, 0x0, 0x0)
	/tmp/workdir-host-freebsd-arm-paulzhol/go/src/os/exec/exec.go:509 +0x108
os/exec.(*Cmd).Run(0x308860b0, 0x30a1c0c0, 0x1)
	/tmp/workdir-host-freebsd-arm-paulzhol/go/src/os/exec/exec.go:341 +0x44
os/exec.(*Cmd).CombinedOutput(0x308860b0, 0x4c, 0x308277a4, 0x1, 0x1, 0x308860b0)
	/tmp/workdir-host-freebsd-arm-paulzhol/go/src/os/exec/exec.go:561 +0x14c
runtime/pprof.TestCPUProfileWithFork(0x30a180a0)
	/tmp/workdir-host-freebsd-arm-paulzhol/go/src/runtime/pprof/pprof_test.go:354 +0x17c
testing.tRunner(0x30a180a0, 0x1f97f8)
	/tmp/workdir-host-freebsd-arm-paulzhol/go/src/testing/testing.go:912 +0xa0
created by testing.(*T).Run
	/tmp/workdir-host-freebsd-arm-paulzhol/go/src/testing/testing.go:963 +0x2ac

goroutine 36 [runnable]:
syscall.Syscall(0x3, 0x6, 0x308b8800, 0x400, 0x400, 0x0, 0x0)
	/tmp/workdir-host-freebsd-arm-paulzhol/go/src/syscall/asm_freebsd_arm.s:17 +0x8
syscall.read(0x6, 0x308b8800, 0x400, 0x400, 0x0, 0x30ae1ee4, 0x0)
	/tmp/workdir-host-freebsd-arm-paulzhol/go/src/syscall/zsyscall_freebsd_arm.go:949 +0x40
syscall.Read(...)
	/tmp/workdir-host-freebsd-arm-paulzhol/go/src/syscall/syscall_unix.go:187
internal/poll.(*FD).Read(0x308a00c0, 0x308b8800, 0x400, 0x400, 0x0, 0x0, 0x0)
	/tmp/workdir-host-freebsd-arm-paulzhol/go/src/internal/poll/fd_unix.go:165 +0x110
os.(*File).read(...)
	/tmp/workdir-host-freebsd-arm-paulzhol/go/src/os/file_unix.go:258
os.(*File).Read(0x3085e050, 0x308b8800, 0x400, 0x400, 0x200, 0x0, 0x0)
	/tmp/workdir-host-freebsd-arm-paulzhol/go/src/os/file.go:112 +0x5c
bytes.(*Buffer).ReadFrom(0x30a1c0c0, 0x22b648, 0x3085e050, 0x305cb888, 0x30a1c0c0, 0x1, 0x1)
	/tmp/workdir-host-freebsd-arm-paulzhol/go/src/bytes/buffer.go:207 +0xa4
io.copyBuffer(0x22b4e0, 0x30a1c0c0, 0x22b648, 0x3085e050, 0x0, 0x0, 0x0, 0x715, 0x13065c, 0x308a0040, ...)
	/tmp/workdir-host-freebsd-arm-paulzhol/go/src/io/io.go:388 +0x2fc
io.Copy(...)
	/tmp/workdir-host-freebsd-arm-paulzhol/go/src/io/io.go:364
os/exec.(*Cmd).writerDescriptor.func1(0x308a0040, 0x30ae1fdc)
	/tmp/workdir-host-freebsd-arm-paulzhol/go/src/os/exec/exec.go:311 +0x50
os/exec.(*Cmd).Start.func1(0x308860b0, 0x308be050)
	/tmp/workdir-host-freebsd-arm-paulzhol/go/src/os/exec/exec.go:435 +0x1c
created by os/exec.(*Cmd).Start
	/tmp/workdir-host-freebsd-arm-paulzhol/go/src/os/exec/exec.go:434 +0x46c
FAIL	runtime/pprof	5.931s
```

CC @hyangah

**Comment by hyangah** [comment]
is it reproducible?

**Comment by hyangah** [comment]
This panic is from the runtime's profile event buffer. @rsc @aclements

**Comment by bcmills** [comment]
> is it reproducible?

It appears to reproduce sporadically on that particular builder:
https://build.golang.org/log/9fd93dbe71296c536e2c02726f62187c56fae67c
https://build.golang.org/log/1620c84d30dd03a844f642ee76d1070de3af0997
https://build.golang.org/log/ff63d5d2654c2db2bbf5cf7f438bf86fdde9db57
https://build.golang.org/log/4c4336f9bef245f871e548a3e3caf8e914fc0c13
https://build.golang.org/log/1becfc3c17b24ba74992bc40a0cbb844cc975b66

**Comment by rsc** [comment]
Dupliate of #24991.
