### ISSUE TITLE
encoding/gob: TestFuzz can use a lot of memory

### ISSUE THREAD

**Issue by mikioh** [golang/go#3225]
<pre>What steps will reproduce the problem?
1. run go test -v std
2.
3.

What is the expected output? What do you see instead?
all tests pass

Please use labels and text to provide additional information.
--- PASS: TestDebugStruct (0.00 seconds)
=== RUN TestFuzz
runtime: out of memory: cannot allocate 268500992-byte block (269549568 in use)
throw: out of memory

goroutine 23 [running]:
encoding/gob.(*Decoder).readMessage(0x98298140, 0x10000766, 0x98262200)
    /home/mikioh/go/src/pkg/encoding/gob/decoder.go:92 +0x5a
encoding/gob.(*Decoder).recvMessage(0x98298140, 0x0, 0x1)
    /home/mikioh/go/src/pkg/encoding/gob/decoder.go:84 +0xaa
encoding/gob.(*Decoder).decodeTypeSequence(0x98298140, 0x98267d00, 0x160, 0x0)
    /home/mikioh/go/src/pkg/encoding/gob/decoder.go:142 +0x57
encoding/gob.(*Decoder).DecodeValue(0x98298140, 0x80f98f0, 0x98267dc0, 0x160, 0x0, ...)
    /home/mikioh/go/src/pkg/encoding/gob/decoder.go:206 +0xe4
encoding/gob.(*Decoder).Decode(0x98298140, 0x80f98e8, 0x98267dc0, 0x98267dc0,
0x98296de0, ...)
    /home/mikioh/go/src/pkg/encoding/gob/decoder.go:185 +0x168
encoding/gob.encFuzzDec(0x98261cc8, 0x80f9640, 0x98278bf8, 0x982373e0, 0x982021a0, ...)
    /home/mikioh/go/src/pkg/encoding/gob/codec_test.go:1429 +0x287
encoding/gob.testFuzz(0x98263440, 0x383acc68, 0x1278f820, 0x64, 0xb8244f68, ...)
    /home/mikioh/go/src/pkg/encoding/gob/codec_test.go:1468 +0x1a4
encoding/gob.TestFuzz(0x98263440, 0xe)
    /home/mikioh/go/src/pkg/encoding/gob/codec_test.go:1452 +0x2fa
testing.tRunner(0x98263440, 0x82113d0, 0x0)
    /tmp/bindist445861990/go/src/pkg/testing/testing.go:271 +0x6e
created by testing.RunTests
    /tmp/bindist445861990/go/src/pkg/testing/testing.go:346 +0x687

goroutine 1 [chan receive]:
testing.RunTests(0x8048c00, 0x82112e0, 0x49, 0x49, 0x8202101, ...)
    /tmp/bindist445861990/go/src/pkg/testing/testing.go:347 +0x6a7
testing.Main(0x8048c00, 0x82112e0, 0x49, 0x49, 0x820dd58, ...)
    /tmp/bindist445861990/go/src/pkg/testing/testing.go:282 +0x46
main.main()
    /tmp/go-build055329031/encoding/gob/_test/_testmain.go:191 +0x4e

goroutine 2 [syscall]:
created by runtime.main
    /tmp/bindist445861990/go/src/pkg/runtime/proc.c:219
FAIL    encoding/gob    0.012s</pre>

**Comment by agnivade** [comment]
Just tested this on tip.

It takes around 400MB now.

```
root@agniva-ubuntu:/home/agniva/play/gosource/go/src# ulimit -v 400000
root@agniva-ubuntu:/home/agniva/play/gosource/go/src# ../bin/go test -v encoding/gob -run=Fuzz -gob.fuzz
=== RUN   TestFuzz
--- PASS: TestFuzz (0.01s)
	codec_test.go:1457: seed=1512208589752279997 n=100 e=*int
	codec_test.go:1457: seed=1512208589752279997 n=100 e=*float32
	codec_test.go:1457: seed=1512208589752279997 n=100 e=*float64
	codec_test.go:1457: seed=1512208589752279997 n=100 e=*complex128
	codec_test.go:1457: seed=1512208589752279997 n=100 e=*gob.ByteStruct
	codec_test.go:1457: seed=1512208589752279997 n=100 e=*gob.ArrayStruct
	codec_test.go:1457: seed=1512208589752279997 n=100 e=*gob.StringStruct
	codec_test.go:1457: seed=1512208589752279997 n=100 e=*gob.GobTest1
=== RUN   TestFuzzRegressions
--- PASS: TestFuzzRegressions (0.11s)
	codec_test.go:1457: seed=1328492090837718000 n=100 e=*float32
	codec_test.go:1457: seed=1330522872628565000 n=100 e=*int
=== RUN   TestFuzzOneByte
--- PASS: TestFuzzOneByte (0.87s)
PASS
ok  	encoding/gob	0.996s
```

When I try 300MB, it always fails.

```
root@agniva-ubuntu:/home/agniva/play/gosource/go/src# ulimit -v 300000
root@agniva-ubuntu:/home/agniva/play/gosource/go/src# ../bin/go test -v encoding/gob -run=Fuzz -gob.fuzz
=== RUN   TestFuzz
--- PASS: TestFuzz (0.00s)
	codec_test.go:1457: seed=1512208580484615295 n=100 e=*int
	codec_test.go:1457: seed=1512208580484615295 n=100 e=*float32
	codec_test.go:1457: seed=1512208580484615295 n=100 e=*float64
	codec_test.go:1457: seed=1512208580484615295 n=100 e=*complex128
	codec_test.go:1457: seed=1512208580484615295 n=100 e=*gob.ByteStruct
	codec_test.go:1457: seed=1512208580484615295 n=100 e=*gob.ArrayStruct
	codec_test.go:1457: seed=1512208580484615295 n=100 e=*gob.StringStruct
	codec_test.go:1457: seed=1512208580484615295 n=100 e=*gob.GobTest1
=== RUN   TestFuzzRegressions
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x5b121c, 0x16)
	/home/agniva/play/gosource/go/src/runtime/panic.go:616 +0x81
runtime.sysMap(0xc420300000, 0x10010000, 0x50ac00, 0x6b36f8)
	/home/agniva/play/gosource/go/src/runtime/mem_linux.go:216 +0x20a
runtime.(*mheap).sysAlloc(0x699800, 0x10010000, 0x7f22c1bcb738)
	/home/agniva/play/gosource/go/src/runtime/malloc.go:470 +0xd4
runtime.(*mheap).grow(0x699800, 0x8007, 0x0)
	/home/agniva/play/gosource/go/src/runtime/mheap.go:907 +0x60
runtime.(*mheap).allocSpanLocked(0x699800, 0x8007, 0x6b3708, 0x7fffcc1bd870)
	/home/agniva/play/gosource/go/src/runtime/mheap.go:820 +0x301
runtime.(*mheap).alloc_m(0x699800, 0x8007, 0x410101, 0xc41ffee9ff)
	/home/agniva/play/gosource/go/src/runtime/mheap.go:686 +0x118
runtime.(*mheap).alloc.func1()
	/home/agniva/play/gosource/go/src/runtime/mheap.go:753 +0x43
runtime.(*mheap).alloc(0x699800, 0x8007, 0x7fffcc010101, 0x41412c)
	/home/agniva/play/gosource/go/src/runtime/mheap.go:752 +0x8a
runtime.largeAlloc(0x1000cf66, 0xc420050101, 0x7f22c1c12000)
	/home/agniva/play/gosource/go/src/runtime/malloc.go:826 +0x94
runtime.mallocgc.func1()
	/home/agniva/play/gosource/go/src/runtime/malloc.go:721 +0x46
runtime.systemstack(0x0)
	/home/agniva/play/gosource/go/src/runtime/asm_amd64.s:409 +0x79
runtime.mstart()
	/home/agniva/play/gosource/go/src/runtime/proc.go:1170

goroutine 6 [running]:
runtime.systemstack_switch()
	/home/agniva/play/gosource/go/src/runtime/asm_amd64.s:363 fp=0xc420057bb8 sp=0xc420057bb0 pc=0x4538c0
runtime.mallocgc(0x1000cf66, 0x56a9c0, 0x1, 0xc420057cd8)
	/home/agniva/play/gosource/go/src/runtime/malloc.go:720 +0x8a2 fp=0xc420057c58 sp=0xc420057bb8 pc=0x410812
runtime.makeslice(0x56a9c0, 0x1000cf66, 0x1000cf66, 0x9, 0x4, 0x0)
	/home/agniva/play/gosource/go/src/runtime/slice.go:61 +0x77 fp=0xc420057c88 sp=0xc420057c58 pc=0x43e237
encoding/gob.(*decBuffer).Size(...)
	/home/agniva/play/gosource/go/src/encoding/gob/decode.go:65
encoding/gob.(*Decoder).readMessage(0xc42022a480, 0x1000cf66)
	/home/agniva/play/gosource/go/src/encoding/gob/decoder.go:100 +0x17e fp=0xc420057ce8 sp=0xc420057c88 pc=0x50c00e
encoding/gob.(*Decoder).recvMessage(0xc42022a480, 0xc420057d68)
	/home/agniva/play/gosource/go/src/encoding/gob/decoder.go:89 +0xf0 fp=0xc420057d40 sp=0xc420057ce8 pc=0x50be60
encoding/gob.(*Decoder).decodeTypeSequence(0xc42022a480, 0x5ba600, 0xc42022a480)
	/home/agniva/play/gosource/go/src/encoding/gob/decoder.go:142 +0x136 fp=0xc420057d60 sp=0xc420057d40 pc=0x50c326
encoding/gob.(*Decoder).DecodeValue(0xc42022a480, 0x5619c0, 0xc420218ed0, 0x16, 0x0, 0x0)
	/home/agniva/play/gosource/go/src/encoding/gob/decoder.go:210 +0xdc fp=0xc420057d98 sp=0xc420057d60 pc=0x50c5ec
encoding/gob.(*Decoder).Decode(0xc42022a480, 0x5619c0, 0xc420218ed0, 0x0, 0x0)
	/home/agniva/play/gosource/go/src/encoding/gob/decoder.go:187 +0x14f fp=0xc420057df0 sp=0xc420057d98 pc=0x50c49f
encoding/gob.encFuzzDec(0xc420057ed8, 0x561480, 0xc420202378, 0x5d13c0, 0xc4200464c0)
	/home/agniva/play/gosource/go/src/encoding/gob/codec_test.go:1415 +0x1d1 fp=0xc420057e60 sp=0xc420057df0 pc=0x528f81
encoding/gob.testFuzz(0xc4200c61e0, 0x126fc084994c53f0, 0x64, 0xc420057f88, 0x1, 0x1)
	/home/agniva/play/gosource/go/src/encoding/gob/codec_test.go:1460 +0x7a fp=0xc420057f48 sp=0xc420057e60 pc=0x5295ba
encoding/gob.TestFuzzRegressions(0xc4200c61e0)
	/home/agniva/play/gosource/go/src/encoding/gob/codec_test.go:1449 +0xa3 fp=0xc420057fa8 sp=0xc420057f48 pc=0x529473
testing.tRunner(0xc4200c61e0, 0x5b9ad8)
	/home/agniva/play/gosource/go/src/testing/testing.go:774 +0xc4 fp=0xc420057fd0 sp=0xc420057fa8 pc=0x4bf314
runtime.goexit()
	/home/agniva/play/gosource/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420057fd8 sp=0xc420057fd0 pc=0x456411
created by testing.(*T).Run
	/home/agniva/play/gosource/go/src/testing/testing.go:821 +0x2ca

goroutine 1 [chan receive]:
testing.(*T).Run(0xc4200c61e0, 0x5aff6e, 0x13, 0x5b9ad8, 0x46c001)
	/home/agniva/play/gosource/go/src/testing/testing.go:822 +0x2eb
testing.runTests.func1(0xc4200c6000)
	/home/agniva/play/gosource/go/src/testing/testing.go:1048 +0x64
testing.tRunner(0xc4200c6000, 0xc420055df8)
	/home/agniva/play/gosource/go/src/testing/testing.go:774 +0xc4
testing.runTests(0xc42000c780, 0x6926c0, 0x5b, 0x5b, 0x410269)
	/home/agniva/play/gosource/go/src/testing/testing.go:1046 +0x2bb
testing.(*M).Run(0xc4200ae150, 0x0)
	/home/agniva/play/gosource/go/src/testing/testing.go:963 +0x15c
main.main()
	_testmain.go:258 +0x151
FAIL	encoding/gob	0.022s
```

If there's nothing else to be done here, perhaps this can be closed.
