### ISSUE TITLE
x/tools/cmd/gopls: panic in (*goFile).GetAST

### ISSUE THREAD

**Issue by muirrn** [golang/go#32478]
Just saw this on master (5aed7825b13ee2b55737e99244fd658841b12a99) as I was debugging a different gopls issue. I think my packages/files were in an unexpected state due to the "parse: no package found for ..." issue I was experiencing.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x150c7c9]

goroutine 7 [running]:
golang.org/x/tools/internal/lsp/cache.(*goFile).GetAST(0xc01eaaff00, 0x1757be0, 0xc03bcde7e0, 0x0)
	/Users/muir/projects/tools/internal/lsp/cache/gofile.go:64 +0x119
golang.org/x/tools/internal/lsp/source.DocumentSymbols(0x1757be0, 0xc03bcde7e0, 0x175eee0, 0xc01eaaff00, 0xc0389685f0, 0x4e, 0x175eee0)
	/Users/muir/projects/tools/internal/lsp/source/symbols.go:45 +0x8d
golang.org/x/tools/internal/lsp.(*Server).documentSymbol(0xc0001723f0, 0x1757be0, 0xc03bcde7e0, 0xc03c43d4a0, 0xc03c43d4a0, 0x0, 0x0, 0x0, 0xc03af48460)
	/Users/muir/projects/tools/internal/lsp/symbols.go:22 +0x138
golang.org/x/tools/internal/lsp.(*Server).DocumentSymbol(0xc0001723f0, 0x1757be0, 0xc03bcde7e0, 0xc03c43d4a0, 0xc03c43d4a0, 0x0, 0x0, 0x0, 0x0)
	/Users/muir/projects/tools/internal/lsp/server.go:198 +0x4d
golang.org/x/tools/internal/lsp/protocol.serverHandler.func1(0x1757be0, 0xc03bcde7e0, 0xc000172460, 0xc03a230860)
	/Users/muir/projects/tools/internal/lsp/protocol/tsserver.go:335 +0x53bc
golang.org/x/tools/internal/jsonrpc2.(*Conn).Run.func1(0xc000093860, 0xc000172460)
	/Users/muir/projects/tools/internal/jsonrpc2/jsonrpc2.go:288 +0x189
created by golang.org/x/tools/internal/jsonrpc2.(*Conn).Run
	/Users/muir/projects/tools/internal/jsonrpc2/jsonrpc2.go:278 +0xba
```

**Comment by stamblerre** [comment]
I think https://golang.org/cl/180857 should fix this.

**Comment by muirrn** [comment]
Closing. Will reopen if I see it again.
