### ISSUE TITLE
x/tools/cmd/gopls: panic after deleting file

### ISSUE THREAD

**Issue by muirrn** [golang/go#32791]
I see the below panic consistently after deleting a file from Emacs (gopls 252024b8295926254bbc18903b9b7d4f0389df2f):

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1524040]

goroutine 53 [running]:
golang.org/x/tools/internal/lsp/cache.(*nativeFileSystem).GetFile(0x1bc53c0, 0xc000b5fec0, 0x26, 0xc00022d270, 0xc00022d2a8)
	/Users/muir/projects/tools/internal/lsp/cache/external.go:27 +0x70
golang.org/x/tools/internal/lsp/cache.(*cache).GetFile(0xc0001f13c0, 0xc000b5fec0, 0x26, 0x0, 0xc00022d2f8)
	/Users/muir/projects/tools/internal/lsp/cache/cache.go:59 +0x51
golang.org/x/tools/internal/lsp/cache.(*session).GetFile(0xc00023c000, 0xc000b5fec0, 0x26, 0xc00022d3e8, 0x11139c7)
	/Users/muir/projects/tools/internal/lsp/cache/session.go:230 +0x97
golang.org/x/tools/internal/lsp/cache.(*fileBase).Handle(0xc0020d0dc0, 0x17823e0, 0xc0024b8210, 0x0, 0x0)
	/Users/muir/projects/tools/internal/lsp/cache/file.go:63 +0xd0
golang.org/x/tools/internal/lsp/cache.(*view).parseImports(0xc0000a7a00, 0x17823e0, 0xc0024b8210, 0xc0020d0dc0, 0xc000b5fec7)
	/Users/muir/projects/tools/internal/lsp/cache/load.go:151 +0x75
golang.org/x/tools/internal/lsp/cache.(*view).checkMetadata(0xc0000a7a00, 0x17823e0, 0xc0024b8210, 0xc0020d0dc0, 0x3, 0xc000038f70, 0xc000038f00, 0x0, 0x0)
	/Users/muir/projects/tools/internal/lsp/cache/load.go:94 +0x6a
golang.org/x/tools/internal/lsp/cache.(*view).loadParseTypecheck(0xc0000a7a00, 0x17823e0, 0xc0024b8210, 0xc0020d0dc0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/muir/projects/tools/internal/lsp/cache/load.go:29 +0xff
golang.org/x/tools/internal/lsp/cache.(*goFile).GetPackages(0xc0020d0dc0, 0x17823e0, 0xc0024b8210, 0x0, 0x0, 0x0)
	/Users/muir/projects/tools/internal/lsp/cache/gofile.go:97 +0x100
golang.org/x/tools/internal/lsp/cache.(*goFile).GetPackage(0xc0020d0dc0, 0x17823e0, 0xc0024b8210, 0x178a420, 0xc0020d0dc0)
	/Users/muir/projects/tools/internal/lsp/cache/gofile.go:118 +0x4c
golang.org/x/tools/internal/lsp.(*Server).didClose(0xc0001f6780, 0x17823e0, 0xc0024b8210, 0xc000d52cb0, 0x0, 0xc0021d2640)
	/Users/muir/projects/tools/internal/lsp/text_synchronization.go:123 +0x1f9
golang.org/x/tools/internal/lsp.(*Server).DidClose(0xc0001f6780, 0x17823e0, 0xc0024b8210, 0xc000d52cb0, 0xc000d52cb0, 0x0)
	/Users/muir/projects/tools/internal/lsp/server.go:155 +0x49
golang.org/x/tools/internal/lsp/protocol.serverHandler.func1(0x17823e0, 0xc0024b8210, 0xc00023a000, 0xc001961020)
	/Users/muir/projects/tools/internal/lsp/protocol/tsserver.go:122 +0x1c2f
golang.org/x/tools/internal/jsonrpc2.(*Conn).Run.func1(0xc0001ff1a0, 0xc00023a000)
	/Users/muir/projects/tools/internal/jsonrpc2/jsonrpc2.go:288 +0x189
created by golang.org/x/tools/internal/jsonrpc2.(*Conn).Run
	/Users/muir/projects/tools/internal/jsonrpc2/jsonrpc2.go:278 +0xba
```

/cc @stamblerre

**Comment by muirrn** [comment]
Still seeing this on master (cf32dd832e4b9969e3e4a278334af8b89de6ac29) after deleting a file:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1522ed0]

goroutine 53 [running]:
golang.org/x/tools/internal/lsp/cache.(*nativeFileSystem).GetFile(0x1bc33c0, 0xc00043e030, 0x26, 0xc000263270, 0xc0002632a8)
	/Users/muir/projects/tools/internal/lsp/cache/external.go:31 +0x70
golang.org/x/tools/internal/lsp/cache.(*cache).GetFile(0xc0002123c0, 0xc00043e030, 0x26, 0x0, 0xc0002632f8)
	/Users/muir/projects/tools/internal/lsp/cache/cache.go:59 +0x51
golang.org/x/tools/internal/lsp/cache.(*session).GetFile(0xc000234000, 0xc00043e030, 0x26, 0xc0002633e8, 0x11139c7)
	/Users/muir/projects/tools/internal/lsp/cache/session.go:234 +0x97
golang.org/x/tools/internal/lsp/cache.(*fileBase).Handle(0xc000416140, 0x1780ac0, 0xc000406ff0, 0x0, 0x0)
	/Users/muir/projects/tools/internal/lsp/cache/file.go:63 +0xd0
golang.org/x/tools/internal/lsp/cache.(*view).parseImports(0xc0002704e0, 0x1780ac0, 0xc000406ff0, 0xc000416140, 0xc00043e037)
	/Users/muir/projects/tools/internal/lsp/cache/load.go:151 +0x75
golang.org/x/tools/internal/lsp/cache.(*view).checkMetadata(0xc0002704e0, 0x1780ac0, 0xc000406ff0, 0xc000416140, 0x3, 0xc000040070, 0xc000040000, 0x0, 0x0)
	/Users/muir/projects/tools/internal/lsp/cache/load.go:94 +0x6a
golang.org/x/tools/internal/lsp/cache.(*view).loadParseTypecheck(0xc0002704e0, 0x1780ac0, 0xc000406ff0, 0xc000416140, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/muir/projects/tools/internal/lsp/cache/load.go:29 +0xff
golang.org/x/tools/internal/lsp/cache.(*goFile).GetPackages(0xc000416140, 0x1780ac0, 0xc000406ff0, 0x0, 0x0, 0x0)
	/Users/muir/projects/tools/internal/lsp/cache/gofile.go:97 +0x100
golang.org/x/tools/internal/lsp/cache.(*goFile).GetPackage(0xc000416140, 0x1780ac0, 0xc000406ff0, 0x1788b40, 0xc000416140)
	/Users/muir/projects/tools/internal/lsp/cache/gofile.go:118 +0x4c
golang.org/x/tools/internal/lsp.(*Server).didClose(0xc0001d6600, 0x1780ac0, 0xc000406ff0, 0xc0003fa550, 0x0, 0xc000416640)
	/Users/muir/projects/tools/internal/lsp/text_synchronization.go:123 +0x1f9
golang.org/x/tools/internal/lsp.(*Server).DidClose(0xc0001d6600, 0x1780ac0, 0xc000406ff0, 0xc0003fa550, 0xc0003fa550, 0x0)
	/Users/muir/projects/tools/internal/lsp/server.go:154 +0x49
golang.org/x/tools/internal/lsp/protocol.serverHandler.func1(0x1780ac0, 0xc000406ff0, 0xc000232000, 0xc000310420)
	/Users/muir/projects/tools/internal/lsp/protocol/tsserver.go:122 +0x1c2f
golang.org/x/tools/internal/jsonrpc2.(*Conn).Run.func1(0xc0001c2de0, 0xc000232000)
	/Users/muir/projects/tools/internal/jsonrpc2/jsonrpc2.go:288 +0x189
created by golang.org/x/tools/internal/jsonrpc2.(*Conn).Run
	/Users/muir/projects/tools/internal/jsonrpc2/jsonrpc2.go:278 +0xba
```
