### ISSUE TITLE
x/image/vector: consistent SIGILL on solaris-amd64-oraclerel builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#32835]
The test for `golang.org/x/image/vector` seems to always fail on the `solaris-amd64-oraclerel` builder ([example](https://build.golang.org/log/2ccfa3746a4209a7e49c251b481784b2bf553dea)).

It looks like something about the assembly code is invalid on that builder — perhaps we're missing an instruction support check somewhere?

```
SIGILL: illegal instruction (not reset when caught)
PC=0x518308 m=0 sigcode=1

goroutine 20 [running]:
golang.org/x/image/vector.floatingAccumulateOpSrcSIMD(0xc000040e20, 0x20, 0x40, 0xc000040e60, 0x20, 0x40)
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/gopath/src/golang.org/x/image/vector/acc_amd64.s:827 +0xa8 fp=0xc000040de0 sp=0xc000040dc8 pc=0x518308
golang.org/x/image/vector.TestFloatingAccumulateSIMDUnaligned(0xc0000ca300)
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/gopath/src/golang.org/x/image/vector/acc_test.go:65 +0xbd fp=0xc000040f70 sp=0xc000040de0 pc=0x50e7cd
testing.tRunner(0xc0000ca300, 0x577b78)
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/testing/testing.go:909 +0xc9 fp=0xc000040fd0 sp=0xc000040f70 pc=0x4bee39
runtime.goexit()
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000040fd8 sp=0xc000040fd0 pc=0x4592f1
created by testing.(*T).Run
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/testing/testing.go:960 +0x350

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0000ca300, 0x5741eb, 0x23, 0x577b78, 0x46ff01)
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/testing/testing.go:961 +0x377
testing.runTests.func1(0xc0000ca000)
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/testing/testing.go:1207 +0x78
testing.tRunner(0xc0000ca000, 0xc000076dc0)
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/testing/testing.go:909 +0xc9
testing.runTests(0xc0000c4000, 0x682bc0, 0x1d, 0x1d, 0x0)
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/testing/testing.go:1205 +0x2a7
testing.(*M).Run(0xc0000b4000, 0x0)
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/testing/testing.go:1122 +0x176
main.main()
	_testmain.go:244 +0x135

rax    0x7fa0
rbx    0x20
rcx    0xc000040e60
rdx    0xffffffffffffffff
rdi    0xc000040e20
rsi    0xc000040e60
rbp    0xc000040dd0
rsp    0xc000040dc8
r8     0x8244403483b9aca
r9     0x0
r10    0x20
r11    0x20
r12    0xfc
r13    0x0
r14    0x594cb0
r15    0x0
rip    0x518308
rflags 0x10283
cs     0x53
fs     0x0
gs     0x0
FAIL	golang.org/x/image/vector	0.045s
```

CC @nigeltao

**Comment by bcmills** [comment]
Looks like the instruction in question is PSHUFB, which requires SSE3.

**Comment by bcmills** [comment]
Confirmed that the `solaris-amd64-oraclerel` builder is now passing tests. Thanks for the fix!
