### ISSUE TITLE
x/build: openbsd-arm misconfigured to run x/mobile tests

### ISSUE THREAD

**Issue by bcmills** [golang/go#32838]
The `openbsd-arm` builder (#25498) is consistently failing the `x/mobile` repo:

```
--- FAIL: TestAndroidBuild (0.00s)
panic: unsupported GOARCH: arm [recovered]
	panic: unsupported GOARCH: arm

goroutine 23 [running]:
testing.tRunner.func1(0x8c0500)
	/home/gopher/build/openbsd-arm-67f181bfd84d/go/src/testing/testing.go:874 +0x360
panic(0x2c1318, 0x375178)
	/home/gopher/build/openbsd-arm-67f181bfd84d/go/src/runtime/panic.go:663 +0x194
golang.org/x/mobile/cmd/gomobile.archNDK(...)
	/home/gopher/build/openbsd-arm-67f181bfd84d/src/golang.org/x/mobile/cmd/gomobile/env.go:280
golang.org/x/mobile/cmd/gomobile.(*ndkToolchain).Path(0x83dc48, 0x308129, 0x9, 0x304e56, 0x5, 0x44, 0xd7518)
	/home/gopher/build/openbsd-arm-67f181bfd84d/src/golang.org/x/mobile/cmd/gomobile/env.go:309 +0xc4
golang.org/x/mobile/cmd/gomobile.envInit(0x378e78, 0x8e48a0)
	/home/gopher/build/openbsd-arm-67f181bfd84d/src/golang.org/x/mobile/cmd/gomobile/env.go:90 +0x144
golang.org/x/mobile/cmd/gomobile.buildEnvInit(0x864240, 0x520470, 0x3f49db00)
	/home/gopher/build/openbsd-arm-67f181bfd84d/src/golang.org/x/mobile/cmd/gomobile/env.go:69 +0x180
golang.org/x/mobile/cmd/gomobile.runBuild(0x549518, 0x0, 0x0)
	/home/gopher/build/openbsd-arm-67f181bfd84d/src/golang.org/x/mobile/cmd/gomobile/build.go:70 +0x28
golang.org/x/mobile/cmd/gomobile.TestAndroidBuild(0x8c0500)
	/home/gopher/build/openbsd-arm-67f181bfd84d/src/golang.org/x/mobile/cmd/gomobile/build_test.go:94 +0x280
testing.tRunner(0x8c0500, 0x3236cc)
	/home/gopher/build/openbsd-arm-67f181bfd84d/go/src/testing/testing.go:909 +0xa8
created by testing.(*T).Run
	/home/gopher/build/openbsd-arm-67f181bfd84d/go/src/testing/testing.go:960 +0x2ac
FAIL	golang.org/x/mobile/cmd/gomobile	0.132s
```

I seriously doubt that `openbsd` is a supported mobile platform, so probably the builder needs to be configured to skip this repo.

CC @dmitshur @FiloSottile @4a6f656c

**Comment by dmitshur** [comment]
I don't see any openbsd-arm builder at https://farmer.golang.org/builders nor in the `x/build/dashboard` source. Based on https://github.com/golang/go/issues/25498#issuecomment-446241343, it sounds like it's a reverse builder, but shouldn't it still show up in x/build source? Am I just not seeing it?

**Comment by bcmills** [comment]
@dmitshur, I thought that comment sounded familiar! See https://github.com/golang/go/issues/21191#issuecomment-497344063.

**Comment by dmitshur** [comment]
Good find. In that case, as I understand, @4a6f656c will need to make this fix on their side, or to convert the builder to use `cmd/buildlet` and then we can do it on our side.

**Comment by 4a6f656c** [comment]
@dmitshur @bcmills - I presume this can now be closed?

**Comment by dmitshur** [comment]
Yep, this issue is resolved. Thanks!
