### ISSUE TITLE
swagger generate spec panic: runtime error: index out of range

### ISSUE THREAD

**Issue by Tazer** [golang/go#33056]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.12.6 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?

Latest Master ( cause trying to generate spec with go modules )

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/patrikpotocki/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/patrikpotocki/.go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/patrikpotocki/dev/fasttrack/crm-integration-api/api-producer/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/6x/028t0fxx6rs7cwrwrmq0pcn80000gn/T/go-build440124602=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
I ran `swagger generate spec`                                                                            

### What did you expect to see?
Either output of the swagger.json OR a friendly error that can tell me what's wrong.

### What did you see instead?
```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/go-swagger/go-swagger/codescan.schemaValidations.SetEnum(0xc019592b40, 0xc0072dfcb6, 0x22)
        /Users/patrikpotocki/.go/src/github.com/go-swagger/go-swagger/codescan/schema.go:95 +0x12d
github.com/go-swagger/go-swagger/codescan.(*setEnum).Parse(0xc0195ad580, 0xc019569120, 0x1, 0x1, 0x0, 0xc019569120)
        /Users/patrikpotocki/.go/src/github.com/go-swagger/go-swagger/codescan/parser.go:938 +0xc7
github.com/go-swagger/go-swagger/codescan.(*tagParser).Parse(...)
        /Users/patrikpotocki/.go/src/github.com/go-swagger/go-swagger/codescan/parser.go:268
github.com/go-swagger/go-swagger/codescan.(*sectionedParser).Parse(0xc0195aab40, 0xc00a3d73a0, 0xb, 0xc019445440)
        /Users/patrikpotocki/.go/src/github.com/go-swagger/go-swagger/codescan/parser.go:656 +0x968
github.com/go-swagger/go-swagger/codescan.(*schemaBuilder).buildFromStruct(0xc0008a1be8, 0xc019496740, 0xc00b61b6b0, 0xc019445440, 0xc0008a1370, 0xc019496740, 0x1)
        /Users/patrikpotocki/.go/src/github.com/go-swagger/go-swagger/codescan/schema.go:727 +0x1248
github.com/go-swagger/go-swagger/codescan.(*schemaBuilder).buildEmbedded(0xc0008a1be8, 0x1a859e0, 0xc00b61b680, 0xc019445440, 0xc0008a1370, 0x0, 0x1)
        /Users/patrikpotocki/.go/src/github.com/go-swagger/go-swagger/codescan/schema.go:821 +0x41a
github.com/go-swagger/go-swagger/codescan.(*schemaBuilder).buildFromStruct(0xc0008a1be8, 0xc00c0fd000, 0xc012a6ac30, 0xc019445440, 0xc0008a1370, 0x0, 0x0)
        /Users/patrikpotocki/.go/src/github.com/go-swagger/go-swagger/codescan/schema.go:621 +0x7c3
github.com/go-swagger/go-swagger/codescan.(*schemaBuilder).buildFromType(0xc0008a1be8, 0x1a85ae0, 0xc012a6ac30, 0x1a96fa0, 0xc0193d7e60, 0x0, 0x0)
        /Users/patrikpotocki/.go/src/github.com/go-swagger/go-swagger/codescan/schema.go:227 +0x929
github.com/go-swagger/go-swagger/codescan.(*schemaBuilder).buildFromDecl(0xc0008a1be8, 0xc00c0fd000, 0xc019445440, 0x206a6c0, 0xd)
        /Users/patrikpotocki/.go/src/github.com/go-swagger/go-swagger/codescan/schema.go:199 +0xd4c
github.com/go-swagger/go-swagger/codescan.(*schemaBuilder).Build(0xc0008a1be8, 0xc0107ba060, 0x0, 0x0)
        /Users/patrikpotocki/.go/src/github.com/go-swagger/go-swagger/codescan/schema.go:144 +0xcc
github.com/go-swagger/go-swagger/codescan.(*specBuilder).buildDiscoveredSchema(0xc0112c0280, 0xc00c0fd000, 0x0, 0x0)
        /Users/patrikpotocki/.go/src/github.com/go-swagger/go-swagger/codescan/spec.go:110 +0xd5
github.com/go-swagger/go-swagger/codescan.(*specBuilder).buildDiscovered(0xc0112c0280, 0x0, 0x0)
        /Users/patrikpotocki/.go/src/github.com/go-swagger/go-swagger/codescan/spec.go:94 +0x212
github.com/go-swagger/go-swagger/codescan.(*specBuilder).Build(0xc0112c0280, 0xc0112ca080, 0x1, 0xc0112c0280)
        /Users/patrikpotocki/.go/src/github.com/go-swagger/go-swagger/codescan/spec.go:58 +0x92
github.com/go-swagger/go-swagger/codescan.Run(0xc0000d2000, 0xc0000d2000, 0x0, 0x0)
        /Users/patrikpotocki/.go/src/github.com/go-swagger/go-swagger/codescan/application.go:75 +0x83
github.com/go-swagger/go-swagger/cmd/swagger/commands/generate.(*SpecFile).Execute(0xc0002b4160, 0xc000426770, 0x1, 0x1, 0xc0002b4160, 0x1)
        /Users/patrikpotocki/.go/src/github.com/go-swagger/go-swagger/cmd/swagger/commands/generate/spec_go111.go:55 +0x1c5
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc000359dc0, 0xc000032090, 0x7, 0x7, 0x0, 0x1943ea9, 0x2a, 0x17cf520, 0xc0002b3410)
        /Users/patrikpotocki/.go/src/github.com/jessevdk/go-flags/parser.go:333 +0x8c7
github.com/jessevdk/go-flags.(*Parser).Parse(...)
        /Users/patrikpotocki/.go/src/github.com/jessevdk/go-flags/parser.go:190
main.main()
        /Users/patrikpotocki/.go/src/github.com/go-swagger/go-swagger/cmd/swagger/swagger.go:145 +0xc2c
```

**Comment by nightlyone** [comment]
@Tazer could you please link the relevant github issue in the go-swagger project here, since it might well be a bug in go-swagger itself. 

Bugs in go-swagger are tracked at https://github.com/go-swagger/go-swagger/issues  and have nothing to do with the Go team.

**Comment by Tazer** [comment]
Wrong repo 🤦‍♀️
