### ISSUE TITLE
os/signal: TestNohup flaky

### ISSUE THREAD

**Issue by bcmills** [golang/go#33174]
Seen on the `solaris-amd64-oraclerel` builder in https://build.golang.org/log/d5185d101eddc0f5a05103f11b74caf24421bf46:
```
--- FAIL: TestNohup (1.25s)
    signal_test.go:329: ran test with -send_uncaught_sighup=1 and it succeeded: expected failure.
        Output:
        PASS
FAIL
FAIL	os/signal	3.575s
```

See previously #8682, #5526.

CC @ianlancetaylor

**Comment by bcmills** [comment]
Same symptom on `linux-ppc64le-power9osu`: https://build.golang.org/log/ae981484d0f765e824066be33e4fb24537b07db5

**Comment by ianlancetaylor** [comment]
Note that the case in https://github.com/golang/go/issues/33174#issuecomment-530411987 is not the same symptom, but rather the reverse:

```
--- FAIL: TestNohup (1.62s)
    signal_test.go:354: ran test with -send_uncaught_sighup=1 under nohup and it failed: expected success.
        Error: signal: user defined signal 1
        Output:
```

**Comment by ianlancetaylor** [comment]
[2017-11-29T16:27:42-be67e26/linux-ppc64le-buildlet](https://build.golang.org/log/80dc5cc2d36c6d1ba858c361a965dec1259413b0)
[2018-11-16T21:11:27-6f5be37/dragonfly-amd64](https://build.golang.org/log/2f29e807764ae19147b6afcbd50773661765bdb8)
[2019-07-17T22:57:03-4814e7d/solaris-amd64-oraclerel](https://build.golang.org/log/d5185d101eddc0f5a05103f11b74caf24421bf46)
[2019-08-29T09:26:02-cb325fe/solaris-amd64-oraclerel](https://build.golang.org/log/ea2096e0c6289c9acebd9db69c1f90432877209d)
[2019-09-06T21:22:26-8a8cf5b/solaris-amd64-oraclerel](https://build.golang.org/log/2b544364fb54cbe3d22e622de556f4c598720dc5)
[2019-09-09T23:04:30-a3a1bdf/solaris-amd64-oraclerel](https://build.golang.org/log/d9cd5b91f930bb54af296ccdfca7ea1f7f655570)
[2019-09-11T03:32:35-904f046/linux-ppc64le-power9osu](https://build.golang.org/log/ae981484d0f765e824066be33e4fb24537b07db5)
[2019-09-11T23:01:45-e7e2b1c/linux-arm64-packet](https://build.golang.org/log/ef0b3a61e6167ad258de43ac07988e12b35ac817)

**Comment by ianlancetaylor** [comment]
I think all these cases could be explained if there is an unusually long time, more than 100 milliseconds, between calling `syscall.Kill` and the time the program actually receives the signal.

**Comment by bcmills** [comment]
Still flaky, unfortunately:
[2020-02-20T19:12:11-75ea964/solaris-amd64-oraclerel](https://build.golang.org/log/2c62e39599b1888fad97a1baf3a6a4b68077dda7)

**Comment by bcmills** [comment]
[2020-03-25T01:11:15-f4fe891/solaris-amd64-oraclerel](https://build.golang.org/log/cb39b90cf9e85bb9734ba6a2dbcd2ed88160defb)

**Comment by bcmills** [comment]
Both of those failures are with `-send_uncaught_sighup=2`:
```
--- FAIL: TestNohup (1.77s)
    signal_test.go:377: ran test with -send_uncaught_sighup=2 and it succeeded: expected failure.
        Output:
        PASS
FAIL
```

**Comment by bcmills** [comment]
Rats, still flaky even with a longer settle time:
https://build.golang.org/log/26c6caee034a65385ec308193deb6166172d9cfc

I'm tempted to dramatically overinflate the settle time on this builder just to see if it's actually dropping the signal.

**Comment by ianlancetaylor** [comment]
That link doesn't show a problem with `TestNohup`.  Wrong link?  Or wrong issue?

**Comment by bcmills** [comment]
Wrong link, edited to fix.

**Comment by bcmills** [comment]
@rorth, are there any known signal-dropping bugs on Oracle solaris that may account for this flakiness?

**Comment by rorth** [comment]
"Bryan C. Mills" <notifications@github.com> writes:

> @rorth, are there any known signal-dropping bugs on Oracle Solaris that may
> account for this flakiness?

None that I'm aware of.

When this first came up, I tried to do some debugging, but the
experience was horrible.  With golang, I couldn't get any code with
sufficient debug info to learn anything.  Still, the stacktrace below is
obviously from golang.

Then I went go gccgo, rebuilt all of libgo with -g3 -O0, and could
reproduce the problem every one in a while.  However, I didn't manage to
make much of the stacktrace I saw (ISTR that I only got the panic when
running with coredumps enabled, not while running under gdb
interactively) and so ultimately gave up.

I'd been running like this:

$ or x in `seq 1 1000`; do ~/net.test -test.timeout=10m0s -test.count=1 -test.run TestUnixAndUnixpacketServer; done

--- FAIL: TestUnixAndUnixpacketServer (10.00s)
    server_test.go:152: skipping unix @nettest/go/unix test
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x5c3c60]

goroutine 19 [running]:
panic(0x64d5a0, 0x858fa0)
	/var/gcc/go/goroot/src/runtime/panic.go:1054 +0x420 fp=0xc0000c9a50 sp=0xc0000c99a8 pc=0x434af0
testing.tRunner.func1(0xc0001d6120)
	/var/gcc/go/goroot/src/testing/testing.go:916 +0x604 fp=0xc0000c9b40 sp=0xc0000c9a50 pc=0x4d9b34
runtime.call32(0x0, 0x69da70, 0xc000132048, 0x800000008)
	/var/gcc/go/goroot/src/runtime/asm_amd64.s:539 +0x3b fp=0xc0000c9b70 sp=0xc0000c9b40 pc=0x4632cb
runtime.reflectcallSave(0xc0000c9c90, 0x69da70, 0xc000132048, 0x8)
	/var/gcc/go/goroot/src/runtime/panic.go:873 +0x58 fp=0xc0000c9ba0 sp=0xc0000c9b70 pc=0x434628
runtime.runOpenDeferFrame(0xc000184180, 0xc000132000, 0xc000198138)
	/var/gcc/go/goroot/src/runtime/panic.go:847 +0x2b9 fp=0xc0000c9c30 sp=0xc0000c9ba0 pc=0x4344e9
panic(0x64d5a0, 0x858fa0)
	/var/gcc/go/goroot/src/runtime/panic.go:961 +0x15d fp=0xc0000c9cd8 sp=0xc0000c9c30 pc=0x43482d
runtime.panicmem(...)
	/var/gcc/go/goroot/src/runtime/panic.go:212
runtime.sigpanic()
	/var/gcc/go/goroot/src/runtime/signal_unix.go:667 +0x3da fp=0xc0000c9d08 sp=0xc0000c9cd8 pc=0x44ac7a
net.TestUnixAndUnixpacketServer(0xc0001d6120)
	/var/gcc/go/goroot/src/net/server_test.go:197 +0x670 fp=0xc0000c9f80 sp=0xc0000c9d08 pc=0x5c3c60
testing.tRunner(0xc0001d6120, 0x69d188)
	/var/gcc/go/goroot/src/testing/testing.go:954 +0xdc fp=0xc0000c9fd0 sp=0xc0000c9f80 pc=0x4d5adc
runtime.goexit()
	/var/gcc/go/goroot/src/runtime/asm_amd64.s:1375 +0x1 fp=0xc0000c9fd8 sp=0xc0000c9fd0 pc=0x465081
created by testing.(*T).Run
	/var/gcc/go/goroot/src/testing/testing.go:1005 +0x357

goroutine 1 [chan receive]:
runtime.gopark(0x69d638, 0xc00019a238, 0x170e, 0x2)
	/var/gcc/go/goroot/src/runtime/proc.go:304 +0xe0 fp=0xc00007bb48 sp=0xc00007bb28 pc=0x437790
runtime.chanrecv(0xc00019a1e0, 0xc00007bc5f, 0xc000000101, 0x4d5ea7)
	/var/gcc/go/goroot/src/runtime/chan.go:563 +0x338 fp=0xc00007bbd8 sp=0xc00007bb48 pc=0x407078
runtime.chanrecv1(0xc00019a1e0, 0xc00007bc5f)
	/var/gcc/go/goroot/src/runtime/chan.go:433 +0x2b fp=0xc00007bc08 sp=0xc00007bbd8 pc=0x406ceb
testing.(*T).Run(0xc0001d6120, 0x692710, 0x1b, 0x69d188, 0x4a5401)
	/var/gcc/go/goroot/src/testing/testing.go:1006 +0x37e fp=0xc00007bcb8 sp=0xc00007bc08 pc=0x4d5ece
testing.runTests.func1(0xc0001d6000)
	/var/gcc/go/goroot/src/testing/testing.go:1247 +0x78 fp=0xc00007bd08 sp=0xc00007bcb8 pc=0x4d9c08
testing.tRunner(0xc0001d6000, 0xc00007bde8)
	/var/gcc/go/goroot/src/testing/testing.go:954 +0xdc fp=0xc00007bd58 sp=0xc00007bd08 pc=0x4d5adc
testing.runTests(0xc0001ce040, 0x86be40, 0xe4, 0xe4, 0x0)
	/var/gcc/go/goroot/src/testing/testing.go:1245 +0x2a7 fp=0xc00007be18 sp=0xc00007bd58 pc=0x4d73d7
testing.(*M).Run(0xc0000b6000, 0x0)
	/var/gcc/go/goroot/src/testing/testing.go:1162 +0x15f fp=0xc00007bef8 sp=0xc00007be18 pc=0x4d632f
net.TestMain(0xc0000b6000)
	/var/gcc/go/goroot/src/net/main_test.go:52 +0x39 fp=0xc00007bf20 sp=0xc00007bef8 pc=0x5ad739
main.main()
	_testmain.go:564 +0x135 fp=0xc00007bf88 sp=0xc00007bf20 pc=0x61aaa5
runtime.main()
	/var/gcc/go/goroot/src/runtime/proc.go:203 +0x212 fp=0xc00007bfe0 sp=0xc00007bf88 pc=0x4373a2
runtime.goexit()
	/var/gcc/go/goroot/src/runtime/asm_amd64.s:1375 +0x1 fp=0xc00007bfe8 sp=0xc00007bfe0 pc=0x465081

goroutine 2 [force gc (idle)]:
runtime.gopark(0x69d828, 0x86e0d0, 0x1411, 0x1)
	/var/gcc/go/goroot/src/runtime/proc.go:304 +0xe0 fp=0xc000068fb0 sp=0xc000068f90 pc=0x437790
runtime.goparkunlock(...)
	/var/gcc/go/goroot/src/runtime/proc.go:310
runtime.forcegchelper()
	/var/gcc/go/goroot/src/runtime/proc.go:253 +0xb7 fp=0xc000068fe0 sp=0xc000068fb0 pc=0x437647
runtime.goexit()
	/var/gcc/go/goroot/src/runtime/asm_amd64.s:1375 +0x1 fp=0xc000068fe8 sp=0xc000068fe0 pc=0x465081
created by runtime.init.6
	/var/gcc/go/goroot/src/runtime/proc.go:242 +0x35

goroutine 3 [GC sweep wait]:
runtime.gopark(0x69d828, 0x86e2c0, 0x140c, 0x1)
	/var/gcc/go/goroot/src/runtime/proc.go:304 +0xe0 fp=0xc0000697a8 sp=0xc000069788 pc=0x437790
runtime.goparkunlock(...)
	/var/gcc/go/goroot/src/runtime/proc.go:310
runtime.bgsweep(0xc000090000)
	/var/gcc/go/goroot/src/runtime/mgcsweep.go:70 +0x9c fp=0xc0000697d8 sp=0xc0000697a8 pc=0x42316c
runtime.goexit()
	/var/gcc/go/goroot/src/runtime/asm_amd64.s:1375 +0x1 fp=0xc0000697e0 sp=0xc0000697d8 pc=0x465081
created by runtime.gcenable
	/var/gcc/go/goroot/src/runtime/mgc.go:214 +0x5c

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x69d828, 0x86e280, 0x140d, 0x1)
	/var/gcc/go/goroot/src/runtime/proc.go:304 +0xe0 fp=0xc000069f50 sp=0xc000069f30 pc=0x437790
runtime.goparkunlock(...)
	/var/gcc/go/goroot/src/runtime/proc.go:310
runtime.bgscavenge(0xc000090000)
	/var/gcc/go/goroot/src/runtime/mgcscavenge.go:220 +0xd3 fp=0xc000069fd8 sp=0xc000069f50 pc=0x421953
runtime.goexit()
	/var/gcc/go/goroot/src/runtime/asm_amd64.s:1375 +0x1 fp=0xc000069fe0 sp=0xc000069fd8 pc=0x465081
created by runtime.gcenable
	/var/gcc/go/goroot/src/runtime/mgc.go:215 +0x7e

goroutine 18 [finalizer wait]:
runtime.gopark(0x69d828, 0x88aa70, 0x1410, 0x1)
	/var/gcc/go/goroot/src/runtime/proc.go:304 +0xe0 fp=0xc000064758 sp=0xc000064738 pc=0x437790
runtime.goparkunlock(...)
	/var/gcc/go/goroot/src/runtime/proc.go:310
runtime.runfinq()
	/var/gcc/go/goroot/src/runtime/mfinal.go:175 +0xa3 fp=0xc0000647e0 sp=0xc000064758 pc=0x418f63
runtime.goexit()
	/var/gcc/go/goroot/src/runtime/asm_amd64.s:1375 +0x1 fp=0xc0000647e8 sp=0xc0000647e0 pc=0x465081
created by runtime.createfing
	/var/gcc/go/goroot/src/runtime/mfinal.go:156 +0x61
Abort (core dumped)

**Comment by bcmills** [comment]
No timeouts on `solaris-amd64-oraclerel` since [CL 228266](https://golang.org/cl/228266), so I think that one may just be a slow builder:
[2020-04-13T20:22:26-6f3a951/solaris-amd64-oraclerel](https://build.golang.org/log/dd62939f6d3b512fe3e6147074a9c6db1144113f)
[2020-04-08T18:04:59-94d22d1/solaris-amd64-oraclerel](https://build.golang.org/log/52d83a72f3a5ea9a16eb5d670c729694144f9624)
[2019-09-09T23:04:30-a3a1bdf/solaris-amd64-oraclerel](https://build.golang.org/log/d9cd5b91f930bb54af296ccdfca7ea1f7f655570)

Unfortunately, it seems that 100ms may be too short on the other builders:
[2020-05-04T22:52:07-b5f7ff4/linux-ppc64-buildlet](https://build.golang.org/log/a1c6056571711f6e01f2de97bab21998f1c36a3c)
[2020-04-22T21:08:58-0ee4b13/darwin-amd64-10_14](https://build.golang.org/log/462b15b5cb9caf4d48edfe9f2b86e3cc7defd5d1)

**Comment by ianlancetaylor** [comment]
Changing milestone to 1.16.

**Comment by odeke-em** [comment]
Moving the milestone to Go1.17, but good to note that we haven't seen this flake in a long time.

**Comment by ianlancetaylor** [comment]
The errors seem to consistently be of the form

    signal_test.go:357: timeout after 100ms waiting for hangup

(for differing signals).

This is where the process sends itself the signal, and then waits for it to arrive.

**Comment by ianlancetaylor** [comment]
Every failure is with `-send_uncaught_sighup` set, either to `1` or `2`.  Every failure is `TestNohup/nohup-N` where `N` is `1` or `2`.  That means the test is running

    nohup signal.test -test.v -test.run=TestStop -send_uncaught_sighup=N

That run is failing waiting for a signal, although the signal that it is waiting for varies.

**Comment by ianlancetaylor** [comment]
The failure always occurs on a separate run of `signal.test`.  Since we are running under nohup, `SIGHUP` is blocked, so the `SIGHUP` subtest always starts by calling `Notify` and then immediately calling `syscall.Kill`.  The signal can of course be delivered to a different thread.  We are assuming that the signal handler will successfully call `sigsend` to send the signal back to the channel.

This is a real stretch, but as far as I can tell there are no atomic operations between setting `sig.inuse` the first time that `signal_enable` is called and testing `sig.inuse` in `sigsend`.  It's at least theoretically possible that the thread receives the signal will think that signals have been enabled, and not queue the signal for delivery.

So while I doubt this is the problem, I'll try removing the test of `sig.inuse` in `sigsend`.
