### ISSUE TITLE
x/tools/gopls: no import for [...]

### ISSUE THREAD

**Issue by mattouille** [golang/go#33395]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mouille/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mouille/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sh/xm6_z_dj1675zkr10j78cpvs63phsb/T/go-build271849061=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

This occurs during normal operation of gopls

### What did you expect to see?

It locates the package on my system

### What did you see instead?

It said the package was missing

@stamblerre requested the following output:

<pre>
2019/07/31 14:09:01 Info:Build info
----------
golang.org/x/tools/gopls v0.1.2
    golang.org/x/tools/gopls@v0.1.3 h1:CB5ECiPysqZrwxcyRjN+exyZpY0gODTZvNiqQi3lpeo=
    golang.org/x/sync@v0.0.0-20190423024810-112230192c58 h1:8gQV6CLnAEikrhgkHFbMAEhagSSnXWGV915qUMm9mrU=
    golang.org/x/tools@v0.0.0-20190710153321-831012c29e42 h1:4IOeC7p+OItq3+O5BWkcmVu2uBe3jekXau5S4QZX9DU=

Go info
-------
go version go1.12.1 darwin/amd64

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mouille/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mouille/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/mouille/Projects/srebot/srebot/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sh/xm6_z_dj1675zkr10j78cpvs63phsb/T/go-build542264115=/tmp/go-build -gno-record-gcc-switches -fno-common"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1543b6f]

goroutine 1 [running]:
golang.org/x/tools/internal/lsp/cmd.(*connection).AddFile(0xc0000baa60, 0x1791b40, 0xc0000281d0, 0xc00029a020, 0x17, 0x0)
    /Users/mouille/go/pkg/mod/golang.org/x/tools@v0.0.0-20190710153321-831012c29e42/internal/lsp/cmd/cmd.go:342 +0x14f
golang.org/x/tools/internal/lsp/cmd.(*check).Run(0xc0001c81e8, 0x1791b40, 0xc0000281d0, 0xc000020090, 0x1, 0x1, 0x0, 0x0)
    /Users/mouille/go/pkg/mod/golang.org/x/tools@v0.0.0-20190710153321-831012c29e42/internal/lsp/cmd/check.go:51 +0x1c3
golang.org/x/tools/internal/tool.Main.func2(0x0, 0x1794680, 0xc0001c81e8, 0x1791b40, 0xc0000281d0, 0xc0000a5b00, 0x0, 0x0)
    /Users/mouille/go/pkg/mod/golang.org/x/tools@v0.0.0-20190710153321-831012c29e42/internal/tool/tool.go:130 +0xb7
golang.org/x/tools/internal/tool.Main(0x1791b40, 0xc0000281d0, 0x1794680, 0xc0001c81e8, 0xc000020090, 0x1, 0x1)
    /Users/mouille/go/pkg/mod/golang.org/x/tools@v0.0.0-20190710153321-831012c29e42/internal/tool/tool.go:131 +0x243
golang.org/x/tools/internal/lsp/cmd.(*Application).Run(0xc000204000, 0x1791b40, 0xc0000281d0, 0xc000020090, 0x2, 0x1, 0x0, 0x0)
    /Users/mouille/go/pkg/mod/golang.org/x/tools@v0.0.0-20190710153321-831012c29e42/internal/lsp/cmd/cmd.go:112 +0x3ef
golang.org/x/tools/internal/tool.Main.func2(0xc000204000, 0x17945c0, 0xc000204000, 0x1791b40, 0xc0000281d0, 0xc0000a5aa0, 0x0, 0x0)
    /Users/mouille/go/pkg/mod/golang.org/x/tools@v0.0.0-20190710153321-831012c29e42/internal/tool/tool.go:130 +0xb7
golang.org/x/tools/internal/tool.Main(0x1791b40, 0xc0000281d0, 0x17945c0, 0xc000204000, 0xc000020060, 0x4, 0x4)
    /Users/mouille/go/pkg/mod/golang.org/x/tools@v0.0.0-20190710153321-831012c29e42/internal/tool/tool.go:131 +0x243
main.main()
    /Users/mouille/go/pkg/mod/golang.org/x/tools/gopls@v0.1.3/main.go:20 +0xbb
</pre>

**Comment by stamblerre** [comment]
Can you try upgrading to master (`go get -u golang.org/x/tools/gopls@master`) and share the output of `gopls -rpc.trace -v check /path/to/file.go`?

If it still crashes, can you try rebuilding `gopls` with this [patch](https://go-review.googlesource.com/c/tools/+/188597) and share the output of the same command? To apply the patch, click the "..." in the top right corner, and select "Download Patch".

**Comment by mattouille** [comment]
@stamblerre 

```
2019/08/02 14:39:30 Info:26.20241ms for GOROOT= GOPATH= GO111MODULE= PWD=/Users/mouille/Projects/oip_selinux go "list" "-e" "-json" "-compiled=true" "-test=true" "-export=false" "-deps=true" "-find=false" "--" "builtin", stderr: <<>>
2019/08/02 14:39:30 Info:Build info
----------
golang.org/x/tools/gopls v0.1.3
    golang.org/x/tools/gopls@v0.1.4-0.20190802200813-43c5e4ca5b10 h1:Jm3dlWFzupg1mS5KRfxFO6niEP3xjGifI7UECZG1nAo=
    golang.org/x/sync@v0.0.0-20190423024810-112230192c58 h1:8gQV6CLnAEikrhgkHFbMAEhagSSnXWGV915qUMm9mrU=
    golang.org/x/tools@v0.0.0-20190802200813-43c5e4ca5b10 h1:W7Spd8fgBu8CaVsJOJymvgBvgq3AWJazbptDuYzmhwk=

Go info
-------
go version go1.12.1 darwin/amd64

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mouille/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mouille/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sh/xm6_z_dj1675zkr10j78cpvs63phsb/T/go-build263808024=/tmp/go-build -gno-record-gcc-switches -fno-common"
2019/08/02 14:39:30 Info:22.740365ms for GOROOT= GOPATH= GO111MODULE= PWD=/Users/mouille/Projects/oip_selinux go "list" "-e" "-json" "-compiled=true" "-test=true" "-export=false" "-deps=true" "-find=false" "--" "/Users/mouille/Projects/srebot/srebot", stderr: <<>>
2019/08/02 14:39:31 Info:552.518953ms for GOROOT= GOPATH= GO111MODULE= PWD=/Users/mouille/Projects/oip_selinux go "list" "-e" "-json" "-compiled=true" "-test=true" "-export=false" "-deps=true" "-find=false" "--" "/Users/mouille/Projects/srebot/srebot/main.go", stderr: <<>>
2019/08/02 14:39:31 Info:go/packages.Load
	packages = 1
2019/08/02 14:39:31 Info:go/packages.Load
	package = command-line-arguments
	files = [/Users/mouille/Projects/srebot/srebot/main.go]
/Users/mouille/Projects/srebot/srebot/main.go:13:4-59: could not import xxxxx/xxxxx/srebot/healthcheck (no parsed files for package xxxxx/xxxxx/srebot/healthcheck)
```

If I do this on one of the packages in my repo it passes that same message (no parsed files for package) for gorilla/mux.

**Comment by mattouille** [comment]
I didn't end up trying the patch. As you noted switching to master fixed the crashing. I'm not sure if you wanted the other errors split off into a separate issue. If you do just let me know.

Thanks for the help! This has already moved miles.

**Comment by stamblerre** [comment]
Glad to hear that master is working better! What is the output of `go list -e -json -compiled -test /path/to/dir/`? I'm noticing in these logs that `gopls` can't find a `go.mod` file, but you are outside of your `$GOPATH`.

**Comment by mattouille** [comment]
Yeah, I've seen those kind of messages before.

```
go list -e -json -compiled -test ~/Projects/srebot/srebot
go: parsing ../go.mod: open /Users/mouille/go/pkg/mod/golang.org/x/tools/go.mod: no such file or directory
go: error loading module requirements
```

It seems to be talking less about my project and seems to be talking about the gopls installation itself? Which it is certainly right, there is no go.mod in that tools directory.

**Comment by stamblerre** [comment]
What does your `go.mod` file look like? It's possible that an indirect dependency was added when you installed `gopls`. Can you try running `go mod tidy` in your directory and then run the command again?

**Comment by mattouille** [comment]
go.mod:

```
require (
	github.com/aws/aws-sdk-go v1.21.4 // indirect
	github.com/boltdb/bolt v1.3.1
	github.com/cskr/pubsub v1.0.2 // indirect
	github.com/gopherworks/bawt v0.0.6
	github.com/gorilla/mux v1.7.3
	github.com/intuit/funnel v0.0.0-20190627033138-d466d4cf6fd2 // indirect
	github.com/jasonlvhit/gocron v0.0.0-20190723234014-d8bcea5b25ad // indirect
	github.com/konsorten/go-windows-terminal-sequences v1.0.2 // indirect
	github.com/lusis/slack-test v0.0.0-20190426140909-c40012f20018 // indirect
	github.com/magiconair/properties v1.8.1 // indirect
	github.com/pelletier/go-toml v1.4.0 // indirect
	github.com/sirupsen/logrus v1.4.2
	github.com/spf13/afero v1.2.2 // indirect
	github.com/spf13/jwalterweatherman v1.1.0 // indirect
	github.com/spf13/viper v1.4.0 // indirect
	github.com/ugorji/go v1.1.7 // indirect
	golang.org/x/crypto v0.0.0-20190701094942-4def268fd1a4 // indirect
	golang.org/x/net v0.0.0-20190724013045-ca1201d0de80 // indirect
	golang.org/x/sys v0.0.0-20190712062909-fae7ac547cb7 // indirect
	golang.org/x/text v0.3.2 // indirect
)
```

I do run `go mod tidy` as part of my Makefile workflow pretty regularly. Generally when I install gopls I use this command:

`cd /tmp;env GO111MODULE=on go get golang.org/x/tools/gopls@master;`

One thing I did notice is that my modules directory (~/go/pkg/mod`) for gopls shows a latest of v0.1.4 where when I type `gopls version` I get v0.1.3:

```
$ cd /tmp;env GO111MODULE=on go get golang.org/x/tools/gopls@master;
go: finding golang.org/x/tools/gopls master
go: downloading golang.org/x/tools v0.0.0-20190723021737-8bb11ff117ca
go: extracting golang.org/x/tools v0.0.0-20190723021737-8bb11ff117ca
go: downloading golang.org/x/tools/gopls v0.1.4-0.20190805165405-2756c524cc1c
go: extracting golang.org/x/tools/gopls v0.1.4-0.20190805165405-2756c524cc1c
$ gopls version
golang.org/x/tools/gopls v0.1.3
    golang.org/x/tools/gopls@v0.1.4-0.20190805165405-2756c524cc1c h1:Io5nWJhiaOwiNVPkWnE4pLdbU1r9WLSRZ0MeeoBOKUU=
```

**Comment by stamblerre** [comment]
After cleaning my module cache and running that command, I consistently get

```
$ gopls version
golang.org/x/tools/gopls v0.1.3
    golang.org/x/tools/gopls@v0.0.0-20190805165405-2756c524cc1c h1:KXHbq+8864MEn46OViKtxKeZnH0OnLU0GMpO661H6vA=
```

I'm not sure how v0.1.4 is even possible, since we've never tagged it.

But that shouldn't be related to the behavior of the `go list` command. Can you try `cd`ing into your `~/Projects/srebot/srebot` directory and running `go list -e -json -compiled -test`? To confirm, the `go.mod` file is inside of `~/Projects/srebot/srebot`, right?

**Comment by mattouille** [comment]
```
{
	"Dir": "/Users/mouille/Projects/srebot/srebot",
	"ImportPath": "xxxxxx/xxxxxx/srebot",
	"Name": "main",
	"Target": "/Users/mouille/go/bin/srebot",
	"Module": {
		"Path": "xxxxxx/xxxxxx/srebot",
		"Main": true,
		"Dir": "/Users/mouille/Projects/srebot/srebot",
		"GoMod": "/Users/mouille/Projects/srebot/srebot/go.mod",
		"GoVersion": "1.12"
	},
	"Match": [
		"."
	],
	"Stale": true,
	"StaleReason": "stale dependency: github.com/codegangsta/negroni",
	"GoFiles": [
		"main.go"
	],
	"CompiledGoFiles": [
		"main.go"
	],
	"Imports": [
		"flag",
		"github.com/gopherworks/bawt",
		"github.com/gopherworks/bawt/web",
		"log",
		"os"
	],
	"Deps": [
		"bufio",
		"bytes",
		"compress/bzip2",
		"compress/flate",
		"compress/gzip",
		"compress/zlib",
		"container/list",
		"context",
		"crypto",
		"crypto/aes",
		"crypto/cipher",
		"crypto/des",
		"crypto/dsa",
		"crypto/ecdsa",
		"crypto/elliptic",
		"crypto/hmac",
		"crypto/internal/randutil",
		"crypto/internal/subtle",
		"crypto/md5",
		"crypto/rand",
		"crypto/rc4",
		"crypto/rsa",
		"crypto/sha1",
		"crypto/sha256",
		"crypto/sha512",
		"crypto/subtle",
		"crypto/tls",
		"crypto/x509",
		"crypto/x509/pkix",
		"database/sql/driver",
		"encoding",
		"encoding/asn1",
		"encoding/base32",
		"encoding/base64",
		"encoding/binary",
		"encoding/csv",
		"encoding/gob",
		"encoding/hex",
		"encoding/json",
		"encoding/pem",
		"encoding/xml",
		"errors",
		"flag",
		"fmt",
		"github.com/aws/aws-sdk-go/aws",
		"github.com/aws/aws-sdk-go/aws/awserr",
		"github.com/aws/aws-sdk-go/aws/awsutil",
		"github.com/aws/aws-sdk-go/aws/client",
		"github.com/aws/aws-sdk-go/aws/client/metadata",
		"github.com/aws/aws-sdk-go/aws/corehandlers",
		"github.com/aws/aws-sdk-go/aws/credentials",
		"github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds",
		"github.com/aws/aws-sdk-go/aws/credentials/endpointcreds",
		"github.com/aws/aws-sdk-go/aws/credentials/processcreds",
		"github.com/aws/aws-sdk-go/aws/credentials/stscreds",
		"github.com/aws/aws-sdk-go/aws/csm",
		"github.com/aws/aws-sdk-go/aws/defaults",
		"github.com/aws/aws-sdk-go/aws/ec2metadata",
		"github.com/aws/aws-sdk-go/aws/endpoints",
		"github.com/aws/aws-sdk-go/aws/request",
		"github.com/aws/aws-sdk-go/aws/session",
		"github.com/aws/aws-sdk-go/aws/signer/v4",
		"github.com/aws/aws-sdk-go/internal/ini",
		"github.com/aws/aws-sdk-go/internal/sdkio",
		"github.com/aws/aws-sdk-go/internal/sdkrand",
		"github.com/aws/aws-sdk-go/internal/sdkuri",
		"github.com/aws/aws-sdk-go/internal/shareddefaults",
		"github.com/aws/aws-sdk-go/private/protocol",
		"github.com/aws/aws-sdk-go/private/protocol/json/jsonutil",
		"github.com/aws/aws-sdk-go/private/protocol/query",
		"github.com/aws/aws-sdk-go/private/protocol/query/queryutil",
		"github.com/aws/aws-sdk-go/private/protocol/rest",
		"github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil",
		"github.com/aws/aws-sdk-go/service/sts",
		"github.com/aws/aws-sdk-go/service/sts/stsiface",
		"github.com/boltdb/bolt",
		"github.com/codegangsta/negroni",
		"github.com/cskr/pubsub",
		"github.com/fsnotify/fsnotify",
		"github.com/google/uuid",
		"github.com/gopherworks/bawt",
		"github.com/gopherworks/bawt/web",
		"github.com/gorilla/context",
		"github.com/gorilla/mux",
		"github.com/gorilla/securecookie",
		"github.com/gorilla/sessions",
		"github.com/gorilla/websocket",
		"github.com/hashicorp/hcl",
		"github.com/hashicorp/hcl/hcl/ast",
		"github.com/hashicorp/hcl/hcl/parser",
		"github.com/hashicorp/hcl/hcl/printer",
		"github.com/hashicorp/hcl/hcl/scanner",
		"github.com/hashicorp/hcl/hcl/strconv",
		"github.com/hashicorp/hcl/hcl/token",
		"github.com/hashicorp/hcl/json/parser",
		"github.com/hashicorp/hcl/json/scanner",
		"github.com/hashicorp/hcl/json/token",
		"github.com/intuit/funnel",
		"github.com/jacobsa/crypto/cmac",
		"github.com/jacobsa/crypto/common",
		"github.com/jacobsa/crypto/siv",
		"github.com/jasonlvhit/gocron",
		"github.com/jmespath/go-jmespath",
		"github.com/magiconair/properties",
		"github.com/mitchellh/mapstructure",
		"github.com/mohae/deepcopy",
		"github.com/nlopes/slack",
		"github.com/nlopes/slack/slackutilsx",
		"github.com/pelletier/go-toml",
		"github.com/pkg/errors",
		"github.com/sirupsen/logrus",
		"github.com/sirupsen/logrus/hooks/syslog",
		"github.com/spf13/afero",
		"github.com/spf13/afero/mem",
		"github.com/spf13/cast",
		"github.com/spf13/jwalterweatherman",
		"github.com/spf13/pflag",
		"github.com/spf13/viper",
		"github.com/ugorji/go/codec",
		"golang.org/x/crypto/cast5",
		"golang.org/x/crypto/hkdf",
		"golang.org/x/crypto/openpgp/elgamal",
		"golang.org/x/crypto/openpgp/errors",
		"golang.org/x/crypto/openpgp/packet",
		"golang.org/x/crypto/openpgp/s2k",
		"golang.org/x/net/context",
		"golang.org/x/sys/unix",
		"golang.org/x/text/transform",
		"golang.org/x/text/unicode/norm",
		"gopkg.in/yaml.v2",
		"hash",
		"hash/adler32",
		"hash/crc32",
		"hash/fnv",
		"html",
		"html/template",
		"image",
		"image/color",
		"image/internal/imageutil",
		"image/jpeg",
		"internal/bytealg",
		"internal/cpu",
		"internal/fmtsort",
		"internal/nettrace",
		"internal/poll",
		"internal/race",
		"internal/singleflight",
		"internal/syscall/unix",
		"internal/testlog",
		"internal/x/crypto/chacha20poly1305",
		"internal/x/crypto/cryptobyte",
		"internal/x/crypto/cryptobyte/asn1",
		"internal/x/crypto/curve25519",
		"internal/x/crypto/hkdf",
		"internal/x/crypto/internal/chacha20",
		"internal/x/crypto/poly1305",
		"internal/x/net/dns/dnsmessage",
		"internal/x/net/http/httpguts",
		"internal/x/net/http/httpproxy",
		"internal/x/net/http2/hpack",
		"internal/x/net/idna",
		"internal/x/net/route",
		"internal/x/text/secure/bidirule",
		"internal/x/text/transform",
		"internal/x/text/unicode/bidi",
		"internal/x/text/unicode/norm",
		"io",
		"io/ioutil",
		"log",
		"log/syslog",
		"math",
		"math/big",
		"math/bits",
		"math/rand",
		"mime",
		"mime/multipart",
		"mime/quotedprintable",
		"net",
		"net/http",
		"net/http/httptrace",
		"net/http/httputil",
		"net/http/internal",
		"net/rpc",
		"net/textproto",
		"net/url",
		"os",
		"os/exec",
		"path",
		"path/filepath",
		"reflect",
		"regexp",
		"regexp/syntax",
		"runtime",
		"runtime/cgo",
		"runtime/debug",
		"runtime/internal/atomic",
		"runtime/internal/math",
		"runtime/internal/sys",
		"sort",
		"strconv",
		"strings",
		"sync",
		"sync/atomic",
		"syscall",
		"text/tabwriter",
		"text/template",
		"text/template/parse",
		"time",
		"unicode",
		"unicode/utf16",
		"unicode/utf8",
		"unsafe"
	]
}
```

I removed some potentially sensitive imports but otherwise this is intact.

**Comment by stamblerre** [comment]
Can you try `cd`ing into the `/Users/mouille/Projects/srebot/srebot` directory and then running `gopls -rpc.trace -v check main.go` from there?

**Comment by mattouille** [comment]
```
2019/08/14 16:32:18 Info:75.831238ms for GOROOT= GOPATH= GO111MODULE= PWD=/Users/mouille/Projects/srebot/srebot go "list" "-e" "-json" "-compiled=true" "-test=true" "-export=false" "-deps=true" "-find=false" "--" "builtin", stderr: <<>>
2019/08/14 16:32:18 Info:Build info
----------
golang.org/x/tools/gopls v0.1.3
    golang.org/x/tools/gopls@v0.1.4-0.20190805165405-2756c524cc1c h1:Io5nWJhiaOwiNVPkWnE4pLdbU1r9WLSRZ0MeeoBOKUU=
    golang.org/x/sync@v0.0.0-20190423024810-112230192c58 h1:8gQV6CLnAEikrhgkHFbMAEhagSSnXWGV915qUMm9mrU=
    golang.org/x/tools@v0.0.0-20190723021737-8bb11ff117ca h1:SqwJrz6xPBlCUltcEHz2/p01HRPR+VGD+aYLikk8uas=

Go info
-------
go version go1.12.1 darwin/amd64

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mouille/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mouille/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/mouille/Projects/srebot/srebot/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sh/xm6_z_dj1675zkr10j78cpvs63phsb/T/go-build709228932=/tmp/go-build -gno-record-gcc-switches -fno-common"
2019/08/14 16:32:19 Info:923.629086ms for GOROOT= GOPATH= GO111MODULE= PWD=/Users/mouille/Projects/srebot/srebot go "list" "-e" "-json" "-compiled=true" "-test=true" "-export=false" "-deps=true" "-find=false" "--" "/Users/mouille/Projects/srebot/srebot", stderr: <<>>
2019/08/14 16:32:19 Info:go/packages.Load
	packages = 1
2019/08/14 16:32:19 Info:go/packages.Load
	package = xxxxx/xxxxx/srebot
	files = [/Users/mouille/Projects/srebot/srebot/main.go]
```

**Comment by stamblerre** [comment]
Based on the output of this command, it looks like `gopls` didn't find any errors with your package. Are you still seeing errors in your editor?

**Comment by stamblerre** [comment]
@mattouille: Is this still an issue for you?

**Comment by stamblerre** [comment]
Closing as obsolete.
