### ISSUE TITLE
go/format: crashes with "illegal line number"

### ISSUE THREAD

**Issue by dsnet** [golang/go#33538]
Using e37a1b1ca6afcbe3b02d2dfd599ad1d3d926ec34

Here's a succinct reproduction:
```go
func main() {
	format.Source([]byte(`package main
import ("foo"
"bar")`))
}
```

This crashes with:
```
panic: illegal line number

goroutine 1 [running]:
go/token.(*File).LineStart(0xc0000a2120, 0x4, 0x0)
	/usr/local/go.tip/src/go/token/position.go:222 +0xf6
go/ast.sortSpecs(0xc0000a4040, 0xc0000aa000, 0xc0000920a0, 0x2, 0x2, 0x1a, 0x2, 0xe)
	/usr/local/go.tip/src/go/ast/import.go:119 +0x269
go/ast.SortImports(0xc0000a4040, 0xc0000aa000)
	/usr/local/go.tip/src/go/ast/import.go:39 +0x117
go/format.Source(0xc000098030, 0x21, 0x21, 0x0, 0x0, 0x0, 0x4f16a0, 0xc00007a058)
	/usr/local/go.tip/src/go/format/format.go:101 +0x1a3
main.main()
	/tmp/sandbox340049386/main.go:11 +0x70
```

Git bisect reports that this is broken by: [CL/162337](https://go-review.googlesource.com/c/go/+/162337)

\cc @agnivade @griesemer

**Comment by dsnet** [comment]
Given that it's late in the cycle and that this seems like an isolated change, should we revert the CL and address it in Go1.14?
