### ISSUE TITLE
cmd/link: panic in (*ld.Link).loadlib on darwin-amd64-10_11 builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#33599]
```
#!watchflakes
post <- goos == "darwin" && log ~ `panic: runtime error: invalid memory address or nil pointer dereference` && log ~ `cmd/link/internal/ld\.\(\*Link\)\.loadlib`
```

Seen on the `darwin-amd64-10_11` builder while running the `cmd/go` tests (https://build.golang.org/log/799476a348dc482b77ae2cdfb6ea6c39645716a0):

```
go test proxy running at GOPROXY=http://127.0.0.1:60472/mod
go proxy: no archive rsc.io v1.5.2: file does not exist
go proxy: no archive rsc.io v1.5.1: file does not exist
go proxy: no archive rsc.io v1.0.0: file does not exist
go proxy: no archive rsc.io v1.0.0: file does not exist
go proxy: no archive rsc.io v1.0.0: file does not exist
go proxy: no archive rsc.io v1.0.0: file does not exist
go proxy: no archive rsc.io v1.1.0: file does not exist
go proxy: no archive example.com/newcycle v1.0.0: file does not exist
--- FAIL: TestScript (0.00s)
    --- FAIL: TestScript/mod_modinfo (0.80s)
        script_test.go:191: 
            # Test to ensure runtime/debug.ReadBuildInfo parses
            # the modinfo embedded in a binary by the go tool
            # when module is enabled. (0.107s)
            # Build a binary and ensure that it can output its own debug info.
            # The debug info should be accessible before main starts (golang.org/issue/29628). (0.652s)
            > go build
            [stderr]
            go: downloading rsc.io/quote v1.0.0
            go: extracting rsc.io/quote v1.0.0
            go: finding rsc.io/quote v1.0.0
            # x
            panic: runtime error: invalid memory address or nil pointer dereference
            [signal SIGSEGV: segmentation violation code=0x1 addr=0x11 pc=0x118dea9]
            
            goroutine 1 [running]:
            cmd/link/internal/ld.(*Link).loadlib(0xc0006da000)
            	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/cmd/link/internal/ld/lib.go:555 +0x849
            cmd/link/internal/ld.Main(0x1450fa0, 0x10, 0x20, 0x1, 0x7, 0x10, 0x1297f7b, 0x1b, 0x1294bad, 0x14, ...)
            	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/cmd/link/internal/ld/main.go:208 +0xb5f
            main.main()
            	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/cmd/link/main.go:65 +0x1d6
            [exit status 2]
            FAIL: testdata/script/mod_modinfo.txt:12: unexpected command failure
            
FAIL
FAIL	cmd/go	137.320s
```

I'm not sure whether this is another manifestation of the same signal-handling bug, or something else entirely.

I've only seen it once so far.

CC @ianlancetaylor @cherrymui @mdempsky @jeremyfaller

**Comment by jeremyfaller** [comment]
Signal handler bug @bcmills is referencing: (https://golang.org/issue/31264)
