### ISSUE TITLE
cmd/compile: 'IterateBits16': not lowered on 386 linux builders

### ISSUE THREAD

**Issue by ALTree** [golang/go#33902]
All 386 linux builders [are currently failing](https://build.golang.org/#) the codegen test suite with this error:

```
codegen/mathbits.go:354:2: internal compiler error: 'IterateBits16': not lowered: v12, Ctz16NonZero INT UINT16

goroutine 1 [running]:
runtime/debug.Stack(0x8b3bea0, 0xb0680d8, 0x0)
	/workdir/go/src/runtime/debug/stack.go:24 +0x83
cmd/compile/internal/gc.Fatalf(0xb3705c8, 0x8, 0xb00d970, 0x2, 0x2)
	/workdir/go/src/cmd/compile/internal/gc/subr.go:188 +0x26a
cmd/compile/internal/gc.(*ssafn).Fatalf(0xb06a320, 0x2, 0x162021, 0x89928aa, 0x2, 0xb00e900, 0x1, 0x1)
	/workdir/go/src/cmd/compile/internal/gc/ssa.go:6159 +0x14a
cmd/compile/internal/ssa.(*Func).Fatalf(...)
	/workdir/go/src/cmd/compile/internal/ssa/func.go:617
cmd/compile/internal/ssa.checkLower(0xb4671e0)
	/workdir/go/src/cmd/compile/internal/ssa/lower.go:36 +0x301
cmd/compile/internal/ssa.Compile(0xb4671e0)
	/workdir/go/src/cmd/compile/internal/ssa/compile.go:92 +0x865
cmd/compile/internal/gc.buildssa(0xb209b00, 0x0, 0x0)
	/workdir/go/src/cmd/compile/internal/gc/ssa.go:289 +0x9eb
cmd/compile/internal/gc.compileSSA(0xb209b00, 0x0)
	/workdir/go/src/cmd/compile/internal/gc/pgen.go:298 +0x3a
cmd/compile/internal/gc.compile(0xb209b00)
	/workdir/go/src/cmd/compile/internal/gc/pgen.go:277 +0x2c1
cmd/compile/internal/gc.funccompile(0xb209b00)
	/workdir/go/src/cmd/compile/internal/gc/pgen.go:222 +0xad
cmd/compile/internal/gc.Main(0x89bd3b0)
	/workdir/go/src/cmd/compile/internal/gc/main.go:685 +0x2cef
main.main()
	/workdir/go/src/cmd/compile/main.go:51 +0x93


# go run run.go -- codegen/mathbits.go
exit status 2
```

This appears to be triggered by the optimization merged at [CL 189277](https://go-review.googlesource.com/c/go/+/189277) (optimize 386's math.bits.TrailingZeros16).

cc @benshi001

**Comment by ALTree** [comment]
Possibly? : ) The trybots were not run before submitting CL 189277, maybe they would have prevented this.

**Comment by beenshi** [comment]
Sorry for the trouble, I am working on it.
