### ISSUE TITLE
cmd/compile: all linux-386 builders are broken

### ISSUE THREAD

**Issue by mvdan** [golang/go#33906]
```
##### ../test
linux/386/387 
 # command-line-arguments
codegen/mathbits.go:354:2: internal compiler error: 'IterateBits16': not lowered: v12, Ctz16NonZero INT UINT16

goroutine 1 [running]:
runtime/debug.Stack(0x8b3bea0, 0x9c0e0e8, 0x0)
	/workdir/go/src/runtime/debug/stack.go:24 +0x83
cmd/compile/internal/gc.Fatalf(0x9f565c8, 0x8, 0x9c0c070, 0x2, 0x2)
	/workdir/go/src/cmd/compile/internal/gc/subr.go:188 +0x26a
cmd/compile/internal/gc.(*ssafn).Fatalf(0x9e29b60, 0x2, 0x162021, 0x89928aa, 0x2, 0x9f9eef8, 0x1, 0x1)
	/workdir/go/src/cmd/compile/internal/gc/ssa.go:6159 +0x14a
cmd/compile/internal/ssa.(*Func).Fatalf(...)
	/workdir/go/src/cmd/compile/internal/ssa/func.go:617
cmd/compile/internal/ssa.checkLower(0x9fc2840)
	/workdir/go/src/cmd/compile/internal/ssa/lower.go:36 +0x301
cmd/compile/internal/ssa.Compile(0x9fc2840)
	/workdir/go/src/cmd/compile/internal/ssa/compile.go:92 +0x865
cmd/compile/internal/gc.buildssa(0x9df3b00, 0x0, 0x0)
	/workdir/go/src/cmd/compile/internal/gc/ssa.go:289 +0x9eb
cmd/compile/internal/gc.compileSSA(0x9df3b00, 0x0)
	/workdir/go/src/cmd/compile/internal/gc/pgen.go:298 +0x3a
cmd/compile/internal/gc.compile(0x9df3b00)
	/workdir/go/src/cmd/compile/internal/gc/pgen.go:277 +0x2c1
cmd/compile/internal/gc.funccompile(0x9df3b00)
	/workdir/go/src/cmd/compile/internal/gc/pgen.go:222 +0xad
cmd/compile/internal/gc.Main(0x89bd3b0)
	/workdir/go/src/cmd/compile/internal/gc/main.go:685 +0x2cef
main.main()
	/workdir/go/src/cmd/compile/main.go:51 +0x93

# go run run.go -- codegen/mathbits.go
exit status 2
FAIL	codegen/mathbits.go	0.123s
```

The culprit looks to be https://go-review.googlesource.com/c/go/+/189277. CC @benshi001 @martisch @randall77 

Can you fix it today? If not, I'll send a revert this evening UTC.

When re-submiting or fixing, please make sure to test it on a 32-bit linux machine or VM.

**Comment by ALTree** [comment]
#33902

**Comment by mvdan** [comment]
Oh, my bad! I did search quickly, but clearly not well enough. In the future, please leave a comment on the CL as well, as I would have definitely seen it there :)
