### ISSUE TITLE
runtime: testtls ran too long on the android-amd64-emu trybot

### ISSUE THREAD

**Issue by mvdan** [golang/go#33944]
https://storage.googleapis.com/go-build-log/030b0bc2/android-amd64-emu_f1b3bca4.log

```

##### ../misc/cgo/test
SIGQUIT: quit
PC=0x4a2ab8 m=0 sigcode=0

goroutine 1 [syscall]:
syscall.Syscall6(0xf7, 0x1, 0x857, 0xc000072860, 0x1000004, 0x0, 0x0, 0x4c0501, 0xc00008c300, 0xc0000728a0)
	/workdir/go/src/syscall/asm_linux_amd64.s:44 +0x5 fp=0xc000072810 sp=0xc000072808 pc=0x4a2a95
os.(*Process).blockUntilWaitable(0xc000084120, 0x203000, 0x8, 0x1)
	/workdir/go/src/os/wait_waitid.go:31 +0x98 fp=0xc000072900 sp=0xc000072810 pc=0x4c2fa8
os.(*Process).wait(0xc000084120, 0x5aed38, 0x5aed40, 0x5aed30)
	/workdir/go/src/os/exec_unix.go:22 +0x39 fp=0xc000072978 sp=0xc000072900 pc=0x4bd729
os.(*Process).Wait(...)
	/workdir/go/src/os/exec.go:125
os/exec.(*Cmd).Wait(0xc00009c160, 0x0, 0x0)
	/workdir/go/src/os/exec/exec.go:501 +0x60 fp=0xc0000729f0 sp=0xc000072978 pc=0x529430
os/exec.(*Cmd).Run(0xc00009c160, 0xc0000686c0, 0xc000088078)
	/workdir/go/src/os/exec/exec.go:341 +0x5c fp=0xc000072a18 sp=0xc0000729f0 pc=0x5288cc
os/exec.(*Cmd).CombinedOutput(0xc00009c160, 0x3, 0x3, 0xc00009c160, 0xc000072a98, 0x434c78)
	/workdir/go/src/os/exec/exec.go:561 +0x91 fp=0xc000072a48 sp=0xc000072a18 pc=0x529a01
main.adb(0xc000072d90, 0x3, 0x3, 0x0, 0xc00008a018)
	/workdir/go/misc/android/go_android_exec.go:51 +0x68 fp=0xc000072af8 sp=0xc000072a48 pc=0x544198
main.runMain(0x0, 0x0, 0x0)
	/workdir/go/misc/android/go_android_exec.go:97 +0x202 fp=0xc000072f20 sp=0xc000072af8 pc=0x544802
main.main()
	/workdir/go/misc/android/go_android_exec.go:73 +0x65 fp=0xc000072f60 sp=0xc000072f20 pc=0x544585
runtime.main()
	/workdir/go/src/runtime/proc.go:203 +0x21e fp=0xc000072fe0 sp=0xc000072f60 pc=0x42da5e
runtime.goexit()
	/workdir/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000072fe8 sp=0xc000072fe0 pc=0x4582b1

goroutine 18 [syscall]:
os/signal.signal_recv(0x0)
	/workdir/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/workdir/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/workdir/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 19 [IO wait]:
internal/poll.runtime_pollWait(0x7f4c5687cea8, 0x72, 0xffffffffffffffff)
	/workdir/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc00008c258, 0x72, 0x201, 0x200, 0xffffffffffffffff)
	/workdir/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/workdir/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00008c240, 0xc0000ce000, 0x200, 0x200, 0x0, 0x0, 0x0)
	/workdir/go/src/internal/poll/fd_unix.go:169 +0x1cf
os.(*File).read(...)
	/workdir/go/src/os/file_unix.go:259
os.(*File).Read(0xc00008a028, 0xc0000ce000, 0x200, 0x200, 0x7f4c56838028, 0x0, 0xc00002eea0)
	/workdir/go/src/os/file.go:116 +0x71
bytes.(*Buffer).ReadFrom(0xc0000686c0, 0x5d6ca0, 0xc00008a028, 0x7f4c56838028, 0xc0000686c0, 0x1)
	/workdir/go/src/bytes/buffer.go:204 +0xb4
io.copyBuffer(0x5d6b80, 0xc0000686c0, 0x5d6ca0, 0xc00008a028, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/workdir/go/src/io/io.go:388 +0x2ed
io.Copy(...)
	/workdir/go/src/io/io.go:364
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
	/workdir/go/src/os/exec/exec.go:311 +0x63
os/exec.(*Cmd).Start.func1(0xc00009c160, 0xc00007e0a0)
	/workdir/go/src/os/exec/exec.go:435 +0x27
created by os/exec.(*Cmd).Start
	/workdir/go/src/os/exec/exec.go:434 +0x608

rax    0xf7
rbx    0xc000022500
rcx    0x4a2aba
rdx    0xc000072860
rdi    0x1
rsi    0x857
rbp    0xc0000728f0
rsp    0xc000072808
r8     0x0
r9     0x0
r10    0x1000004
r11    0x216
r12    0xf1
r13    0x0
r14    0x5d1eb8
r15    0x0
rip    0x4a2ab8
rflags 0x216
cs     0x33
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (11m0s).
exit status 2
FAIL	misc/cgo/test	660.004s
2019/08/29 15:36:19 Failed: exit status 1
SIGQUIT: quit
PC=0x4a2ab8 m=0 sigcode=0

goroutine 1 [syscall]:
syscall.Syscall6(0xf7, 0x1, 0x859, 0xc00007c860, 0x1000004, 0x0, 0x0, 0x4c0501, 0xc0000103c0, 0xc00007c8a0)
	/workdir/go/src/syscall/asm_linux_amd64.s:44 +0x5 fp=0xc00007c810 sp=0xc00007c808 pc=0x4a2a95
os.(*Process).blockUntilWaitable(0xc000016210, 0x203000, 0x8, 0x1)
	/workdir/go/src/os/wait_waitid.go:31 +0x98 fp=0xc00007c900 sp=0xc00007c810 pc=0x4c2fa8
os.(*Process).wait(0xc000016210, 0x5aed38, 0x5aed40, 0x5aed30)
	/workdir/go/src/os/exec_unix.go:22 +0x39 fp=0xc00007c978 sp=0xc00007c900 pc=0x4bd729
os.(*Process).Wait(...)
	/workdir/go/src/os/exec.go:125
os/exec.(*Cmd).Wait(0xc0000922c0, 0x0, 0x0)
	/workdir/go/src/os/exec/exec.go:501 +0x60 fp=0xc00007c9f0 sp=0xc00007c978 pc=0x529430
os/exec.(*Cmd).Run(0xc0000922c0, 0xc0000726c0, 0xc00001a180)
	/workdir/go/src/os/exec/exec.go:341 +0x5c fp=0xc00007ca18 sp=0xc00007c9f0 pc=0x5288cc
os/exec.(*Cmd).CombinedOutput(0xc0000922c0, 0x3, 0x3, 0xc0000922c0, 0xc00007ca98, 0x434c78)
	/workdir/go/src/os/exec/exec.go:561 +0x91 fp=0xc00007ca48 sp=0xc00007ca18 pc=0x529a01
main.adb(0xc00007cd90, 0x3, 0x3, 0x0, 0xc00000e028)
	/workdir/go/misc/android/go_android_exec.go:51 +0x68 fp=0xc00007caf8 sp=0xc00007ca48 pc=0x544198
main.runMain(0x0, 0x0, 0x0)
	/workdir/go/misc/android/go_android_exec.go:97 +0x202 fp=0xc00007cf20 sp=0xc00007caf8 pc=0x544802
main.main()
	/workdir/go/misc/android/go_android_exec.go:73 +0x65 fp=0xc00007cf60 sp=0xc00007cf20 pc=0x544585
runtime.main()
	/workdir/go/src/runtime/proc.go:203 +0x21e fp=0xc00007cfe0 sp=0xc00007cf60 pc=0x42da5e
runtime.goexit()
	/workdir/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00007cfe8 sp=0xc00007cfe0 pc=0x4582b1

goroutine 6 [syscall]:
os/signal.signal_recv(0x0)
	/workdir/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/workdir/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/workdir/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 7 [IO wait]:
internal/poll.runtime_pollWait(0x7ff884d5aea8, 0x72, 0xffffffffffffffff)
	/workdir/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc000010318, 0x72, 0x201, 0x200, 0xffffffffffffffff)
	/workdir/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/workdir/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000010300, 0xc0000ae000, 0x200, 0x200, 0x0, 0x0, 0x0)
	/workdir/go/src/internal/poll/fd_unix.go:169 +0x1cf
os.(*File).read(...)
	/workdir/go/src/os/file_unix.go:259
os.(*File).Read(0xc00000e038, 0xc0000ae000, 0x200, 0x200, 0x7ff884d16028, 0x0, 0xc000034ea0)
	/workdir/go/src/os/file.go:116 +0x71
bytes.(*Buffer).ReadFrom(0xc0000726c0, 0x5d6ca0, 0xc00000e038, 0x7ff884d16028, 0xc0000726c0, 0x1)
	/workdir/go/src/bytes/buffer.go:204 +0xb4
io.copyBuffer(0x5d6b80, 0xc0000726c0, 0x5d6ca0, 0xc00000e038, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/workdir/go/src/io/io.go:388 +0x2ed
io.Copy(...)
	/workdir/go/src/io/io.go:364
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
	/workdir/go/src/os/exec/exec.go:311 +0x63
os/exec.(*Cmd).Start.func1(0xc0000922c0, 0xc00000c100)
	/workdir/go/src/os/exec/exec.go:435 +0x27
created by os/exec.(*Cmd).Start
	/workdir/go/src/os/exec/exec.go:434 +0x608

rax    0xf7
rbx    0xc000020000
rcx    0x4a2aba
rdx    0xc00007c860
rdi    0x1
rsi    0x859
rbp    0xc00007c8f0
rsp    0xc00007c808
r8     0x0
r9     0x0
r10    0x1000004
r11    0x216
r12    0xf1
r13    0x0
r14    0x5d1eb8
r15    0x0
rip    0x4a2ab8
rflags 0x216
cs     0x33
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (11m0s).
exit status 2
FAIL	misc/cgo/test	660.004s
2019/08/29 15:36:19 Failed: exit status 1
SIGQUIT: quit
PC=0x4a2a3e m=0 sigcode=0

goroutine 1 [syscall]:
syscall.Syscall(0x49, 0x3, 0x2, 0x0, 0x42b0da, 0x0, 0x0)
	/workdir/go/src/syscall/asm_linux_amd64.s:18 +0x5 fp=0xc000068ab0 sp=0xc000068aa8 pc=0x4a2a15
syscall.Flock(0x3, 0x2, 0x42, 0xc0000001b6)
	/workdir/go/src/syscall/zsyscall_linux_amd64.go:439 +0x4b fp=0xc000068af8 sp=0xc000068ab0 pc=0x4a0ddb
main.runMain(0x0, 0x0, 0x0)
	/workdir/go/misc/android/go_android_exec.go:90 +0x19f fp=0xc000068f20 sp=0xc000068af8 pc=0x54479f
main.main()
	/workdir/go/misc/android/go_android_exec.go:73 +0x65 fp=0xc000068f60 sp=0xc000068f20 pc=0x544585
runtime.main()
	/workdir/go/src/runtime/proc.go:203 +0x21e fp=0xc000068fe0 sp=0xc000068f60 pc=0x42da5e
runtime.goexit()
	/workdir/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000068fe8 sp=0xc000068fe0 pc=0x4582b1

goroutine 6 [syscall]:
os/signal.signal_recv(0x0)
	/workdir/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/workdir/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/workdir/go/src/os/signal/signal_unix.go:29 +0x41

rax    0x49
rbx    0xc000020000
rcx    0x4a2a40
rdx    0x0
rdi    0x3
rsi    0x2
rbp    0xc000068ae8
rsp    0xc000068aa8
r8     0x0
r9     0x0
r10    0x0
r11    0x216
r12    0x18
r13    0x17
r14    0x200
r15    0x0
rip    0x4a2a3e
rflags 0x216
cs     0x33
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (11m0s).
exit status 2
FAIL	misc/cgo/testtls	660.023s
2019/08/29 15:36:19 Failed: exit status 1
SIGQUIT: quit
PC=0x4a2ab8 m=0 sigcode=0

goroutine 1 [syscall]:
syscall.Syscall6(0xf7, 0x1, 0x651, 0xc000068860, 0x1000004, 0x0, 0x0, 0x4c0501, 0xc0000103c0, 0xc0000688a0)
	/workdir/go/src/syscall/asm_linux_amd64.s:44 +0x5 fp=0xc000068810 sp=0xc000068808 pc=0x4a2a95
os.(*Process).blockUntilWaitable(0xc000016210, 0x203000, 0x8, 0x1)
	/workdir/go/src/os/wait_waitid.go:31 +0x98 fp=0xc000068900 sp=0xc000068810 pc=0x4c2fa8
os.(*Process).wait(0xc000016210, 0x5aed38, 0x5aed40, 0x5aed30)
	/workdir/go/src/os/exec_unix.go:22 +0x39 fp=0xc000068978 sp=0xc000068900 pc=0x4bd729
os.(*Process).Wait(...)
	/workdir/go/src/os/exec.go:125
os/exec.(*Cmd).Wait(0xc00007e160, 0x0, 0x0)
	/workdir/go/src/os/exec/exec.go:501 +0x60 fp=0xc0000689f0 sp=0xc000068978 pc=0x529430
os/exec.(*Cmd).Run(0xc00007e160, 0xc00005e6c0, 0xc000068a68)
	/workdir/go/src/os/exec/exec.go:341 +0x5c fp=0xc000068a18 sp=0xc0000689f0 pc=0x5288cc
os/exec.(*Cmd).CombinedOutput(0xc00007e160, 0x3, 0x3, 0xc00007e160, 0xc000068a98, 0x434c78)
	/workdir/go/src/os/exec/exec.go:561 +0x91 fp=0xc000068a48 sp=0xc000068a18 pc=0x529a01
main.adb(0xc000068d90, 0x3, 0x3, 0x0, 0xc00000e028)
	/workdir/go/misc/android/go_android_exec.go:51 +0x68 fp=0xc000068af8 sp=0xc000068a48 pc=0x544198
main.runMain(0x0, 0x0, 0x0)
	/workdir/go/misc/android/go_android_exec.go:97 +0x202 fp=0xc000068f20 sp=0xc000068af8 pc=0x544802
main.main()
	/workdir/go/misc/android/go_android_exec.go:73 +0x65 fp=0xc000068f60 sp=0xc000068f20 pc=0x544585
runtime.main()
	/workdir/go/src/runtime/proc.go:203 +0x21e fp=0xc000068fe0 sp=0xc000068f60 pc=0x42da5e
runtime.goexit()
	/workdir/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000068fe8 sp=0xc000068fe0 pc=0x4582b1

goroutine 6 [syscall]:
os/signal.signal_recv(0x0)
	/workdir/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/workdir/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/workdir/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 7 [IO wait]:
internal/poll.runtime_pollWait(0x7f8d6d7a2ea8, 0x72, 0xffffffffffffffff)
	/workdir/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc000010318, 0x72, 0x501, 0x5b3, 0xffffffffffffffff)
	/workdir/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/workdir/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000010300, 0xc0000b004d, 0x5b3, 0x5b3, 0x0, 0x0, 0x0)
	/workdir/go/src/internal/poll/fd_unix.go:169 +0x1cf
os.(*File).read(...)
	/workdir/go/src/os/file_unix.go:259
os.(*File).Read(0xc00000e038, 0xc0000b004d, 0x5b3, 0x5b3, 0x1e, 0x0, 0x0)
	/workdir/go/src/os/file.go:116 +0x71
bytes.(*Buffer).ReadFrom(0xc00005e6c0, 0x5d6ca0, 0xc00000e038, 0x7f8d6d75e028, 0xc00005e6c0, 0x1)
	/workdir/go/src/bytes/buffer.go:204 +0xb4
io.copyBuffer(0x5d6b80, 0xc00005e6c0, 0x5d6ca0, 0xc00000e038, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/workdir/go/src/io/io.go:388 +0x2ed
io.Copy(...)
	/workdir/go/src/io/io.go:364
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
	/workdir/go/src/os/exec/exec.go:311 +0x63
os/exec.(*Cmd).Start.func1(0xc00007e160, 0xc00000c100)
	/workdir/go/src/os/exec/exec.go:435 +0x27
created by os/exec.(*Cmd).Start
	/workdir/go/src/os/exec/exec.go:434 +0x608

rax    0xf7
rbx    0xc000020000
rcx    0x4a2aba
rdx    0xc000068860
rdi    0x1
rsi    0x651
rbp    0xc0000688f0
rsp    0xc000068808
r8     0x0
r9     0x0
r10    0x1000004
r11    0x216
r12    0xf1
r13    0x0
r14    0x5d1eb8
r15    0x0
rip    0x4a2ab8
rflags 0x216
cs     0x33
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (11m0s).
exit status 2
FAIL	misc/cgo/testtls	660.025s
2019/08/29 15:36:20 Failed: exit status 1
skipped due to earlier error
skipped due to earlier error
skipped due to earlier error
skipped due to earlier error
skipped due to earlier error
2019/08/29 15:36:21 FAILED

Error: tests failed: dist test failed: cgo_test: exit status 1
```

**Comment by bcmills** [comment]
https://storage.googleapis.com/go-build-log/e97bc956/android-amd64-emu_63ce800e.log

**Comment by bcmills** [comment]
[2020-03-25T14:19:25-91b8b13/windows-386-2008](https://build.golang.org/log/f0c49ada781d2c66141f864d5dd1b81989e581cc)
[2019-11-12T17:55:14-8c5dbba/netbsd-amd64-8_0](https://build.golang.org/log/210e3fec1ca0de952be593f1f3dc4dcd40e1ce58)
[2019-11-12T01:08:57-eb93c68/netbsd-amd64-8_0](https://build.golang.org/log/978bdfdc9d8e3bc39ebd1d9a4c49b8a15a866fcc)

**Comment by bcmills** [comment]
https://storage.googleapis.com/go-build-log/f0e433ef/android-amd64-emu_a0a69f0a.log

**Comment by eliben** [comment]
I see the same thing for a [CL that changes a comment](https://go-review.googlesource.com/c/go/+/396881), net/httputil test:

https://storage.googleapis.com/go-build-log/ddefde89/android-amd64-emu_777d1ef0.log

**Comment by bcmills** [comment]
`greplogs -l -e '\*\*\* Test killed with quit: ran too long.*\n(?:exit status 2\n)FAIL\s+misc/cgo/testtls'`

(0 matching logs)

Looks like `misc/cgo/testtls` in particular is probably fixed..?

**Comment by bcmills** [comment]
@eliben, the more general timeout problem on the Android builders is tracked as #42212.
