### ISSUE TITLE
runtime: "unexpected return pc for runtime.sigpanic" on darwin-amd64-10_11 builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#34039]
Observed on the `darwin-amd64-10_11` builder in https://build.golang.org/log/fb9c62ad898a0ed87137a2fdfa18a001e886c33f:

```
##### Testing race detector
ok  	runtime/race	15.684s
ok  	flag	1.064s
ok  	net	1.089s
ok  	os	1.108s
unexpected fault address 0xffffffffff04a4e3
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xffffffffff04a4e3 pc=0xffffffffff04a4e3]

goroutine 1 [running, locked to thread]:
runtime.throw(0x1553efd, 0x5)
	/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/runtime/panic.go:774 +0x72 fp=0xc0000c7b88 sp=0xc0000c7b58 pc=0x1067082
runtime: unexpected return pc for runtime.sigpanic called from 0xffffffffff04a4e3
stack: frame={sp:0xc0000c7b88, fp:0xc0000c7bb8} stack=[0xc0000c6000,0xc0000c8000)
000000c0000c7a88:  000000c0000c7ad8  000000c000000001 
000000c0000c7a98:  0000000001882900  000000c0000c7ac8 
000000c0000c7aa8:  00000000010866e9 <runtime.write+57>  0000000001099740 <runtime.write_trampoline+0> 
000000c0000c7ab8:  000000c0000c7ad8  0000000000000001 
000000c0000c7ac8:  000000c0000c7b08  0000000001067bc3 <runtime.gwrite+163> 
000000c0000c7ad8:  0000000000000002  00000000015537e4 
000000c0000c7ae8:  0000000000000001  0000000000000001 
000000c0000c7af8:  000000c0000c7b66  0000000000000012 
000000c0000c7b08:  000000c0000c7b58  00000000010683e8 <runtime.printstring+120> 
000000c0000c7b18:  0000000001067247 <runtime.fatalthrow+87>  000000c0000c7b28 
000000c0000c7b28:  0000000001094680 <runtime.fatalthrow.func1+0>  000000c000000180 
000000c0000c7b38:  0000000001067082 <runtime.throw+114>  000000c0000c7b58 
000000c0000c7b48:  000000c0000c7b78  0000000001067082 <runtime.throw+114> 
000000c0000c7b58:  000000c0000c7b60  0000000001094600 <runtime.throw.func1+0> 
000000c0000c7b68:  0000000001553efd  0000000000000005 
000000c0000c7b78:  000000c0000c7ba8  000000000107d6ac <runtime.sigpanic+972> 
000000c0000c7b88: <0000000001553efd  0000000000000005 
000000c0000c7b98:  000000c0000f6000  ffffffffff04a4e3 
000000c0000c7ba8:  000000c0000c7c50 !ffffffffff04a4e3 
000000c0000c7bb8: >000000c0000c7c68  000000c0000c7bf0 
000000c0000c7bc8:  0000000001044df3 <runtime.newarray+99>  0000000000000120 
000000c0000c7bd8:  0000000001515f80  0000000000000001 
000000c0000c7be8:  000000c0000f6000  0000000000000001 
000000c0000c7bf8:  0000000001045ce3 <runtime.makeBucketArray+387>  0000000001515f80 
000000c0000c7c08:  000000c0000f4000  000000c0000f6000 
000000c0000c7c18:  0000000000000000  000000c0000f6008 
000000c0000c7c28:  000000c0000f6048  000000c0000f6090 
000000c0000c7c38:  0000000000000000  000000c0000f6098 
000000c0000c7c48:  000000c0000f60d8  000000c0000c7c78 
000000c0000c7c58:  000000000104a3a2 <runtime.growWork_fast64+98>  00000000014e0c20 
000000c0000c7c68:  000000c0000be270  0000000000000000 
000000c0000c7c78:  000000c0000c7cb8  0000000001049b8a <runtime.mapassign_fast64+698> 
000000c0000c7c88:  00000000014e0c20  000000c0000be270 
000000c0000c7c98:  0000000000000001  000000c0000f4000 
000000c0000c7ca8:  c01e53d651912d35  0000000000000001 
runtime.sigpanic()
	/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/runtime/signal_unix.go:401 +0x3cc fp=0xc0000c7bb8 sp=0xc0000c7b88 pc=0x107d6ac
FAIL	os/exec	0.063s
```

CC @aclements @mknyszek

**Comment by bcmills** [comment]
The `darwin-amd64-10_11` builder is no longer in use, so it seems this may be obsolete.
