### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference OR  fatal error: unexpected signal during runtime execution OR fatal error: bad sweepgen in refill

### ISSUE THREAD

**Issue by whtiehack** [golang/go#34168]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 windows/amd64

go version go1.12.1 windows/amd6

go version go1.10.7 windows/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

windows 10 and windows 7
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\white\AppData\Local\go-build
set GOENV=C:\Users\white\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=E:\GoPath
set GOPRIVATE=
set GOPROXY=https://goproxy.cn
set GOROOT=E:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=E:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=F:\goproj\checkdll_log\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\white\AppData\Local\Temp\go-build140361630=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

[This repo](https://github.com/whtiehack/checkdll_log) can reproduce.

dll.go

```
package main

import "C"
import "log"

func init() {
	//	log.Println("dll init")
}

func main() {
	// Need a main function to make CGO compile package as C shared library

}

//export Showui
func Showui() int {
	// use print will fine.
	print("show uid called\n")
	// use log will panic .  If comment this line, there is a probability of multiple runs.
	log.Println("show ui called")
	return 1
}
```

main.go
```
package main

import (
	"log"
	"syscall"
)

func main() {
	log.Print("main start")
	h, err := syscall.LoadLibrary("test.dll")
	if err != nil {
		log.Panic("load test.dll error")
	}
	proc, err := syscall.GetProcAddress(h, "Showui")
	if err != nil {
		log.Panic("GetProcAddress Showui error")
	}
	_, _, err = syscall.Syscall(proc, 0, 0, 0, 0)
	if err != nil {
		log.Panic("Syscall Showui error")
	}
	log.Print("main end")
	//	print("main end")
	//	fmt.Printf("main end")
}

```
### What did you expect to see?
Can print the log normally

### What did you see instead?

```

F:\goproj\checkdll_log>go build -o main.exe  main.go

F:\goproj\checkdll_log>main.exe
2019/09/07 22:30:58 main start
show uid called
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x0 pc=0x6bf612c5]

goroutine 1 [running]:
sync.(*Mutex).Lock(...)
        E:/Go/src/sync/mutex.go:74
log.(*Logger).Output(0x0, 0x2, 0x1c00006e010, 0xf, 0x0, 0x0)
        E:/Go/src/log/log.go:153 +0x75
log.Println(0xc000087c90, 0x1, 0x1)
        E:/Go/src/log/log.go:313 +0x73
main.Showui(...)
        F:/goproj/checkdll_log/dll.go:20
main._cgoexpwrap_2058aed3dd45_Showui(0x70006)
        _cgo_gotypes.go:45 +0x8b
runtime: unexpected return pc for runtime.cgocallback_gofunc called from 0x453a97
stack: frame={sp:0xc000087e38, fp:0xc000087e58} stack=[0xc000080000,0xc000088000)
000000c000087d38:  000000c000087d78  0000000100000008
000000c000087d48:  000000c000087ce0  000000006bec40a3 <runtime.cgocallbackg1+371>
000000c000087d58:  0000000000000000  0000000000000000
000000c000087d68:  000000c000087eb0  000000c000087d27
000000c000087d78:  000000c00001a000  000000c000036000
000000c000087d88:  000000c000087db8  000000006bef6253 <runtime.exitsyscall+435>
000000c000087d98:  000000c000036000  0000000200000003
000000c000087da8:  000000c000036000  000000c000036000
000000c000087db8:  000000c000087e28  000000006bec3e75 <runtime.cgocallbackg+213>
000000c000087dc8:  0000000000000000  0000000000000008
000000c000087dd8:  000000c000087df0  00000000004036f5
000000c000087de8:  000000006bf618e0  0000000000000000
000000c000087df8:  000000c000087f10  000000006bf618e0
000000c000087e08:  0000000000000000  0000000000000000
000000c000087e18:  000000c000087e60  000000c000036000
000000c000087e28:  000000000083fc40  000000006bf14a82 <runtime.cgocallback_gofunc+178>
000000c000087e38: <0000000000000000  0000000000582300
000000c000087e48:  000000c000087e60 !0000000000453a97
000000c000087e58: >0000000000403719  0000000000455a80
000000c000087e68:  00000000005825d0  000000000042b831
000000c000087e78:  0000000000000000  0000000000582300
000000c000087e88:  000000c000087ef0  000000000044530a
000000c000087e98:  0000000000455a80  00000000005825d0
000000c000087ea8:  000000c000087ef0  0000000100000000
000000c000087eb8:  000000c000087e98  00000000004452a9
000000c000087ec8:  0000000000000000  0000000000000000
000000c000087ed8:  000000c000087f90  0000000000000000
000000c000087ee8:  0000000000582300  000000c000087f50
000000c000087ef8:  00000000004a0b3f  000000006bf618e0
000000c000087f08:  0000000000000000  0000000000000000
000000c000087f18:  0000000000000000  0000000000000000
000000c000087f28:  0000000000000000  0000000000000000
000000c000087f38:  0000000000000000  00000000004b3580
000000c000087f48:  00000000004f3520  000000c000087fd0

F:\goproj\checkdll_log>main.exe
2019/09/07 22:31:02 main start
show uid called
fatal error: unexpected signal during runtime execution
[signal 0xc0000005 code=0x1 addr=0x0 pc=0x6bf164e8]

goroutine 1 [running, locked to thread]:
runtime.throw(0x6bfb76e9, 0x2a)
        E:/Go/src/runtime/panic.go:774 +0x79 fp=0xc000087898 sp=0xc000087868 pc=0x6beed4e9
runtime.sigpanic()
        E:/Go/src/runtime/signal_windows.go:227 +0x25a fp=0xc0000878c8 sp=0xc000087898 pc=0x6befdeea
runtime.memmove(0x0, 0xc00008c800, 0x1)
        E:/Go/src/runtime/memmove_amd64.s:146 +0x108 fp=0xc0000878d0 sp=0xc0000878c8 pc=0x6bf164e8
runtime.heapBitsSetType(0xc00008c800, 0x400, 0x400, 0x6bf99ca0)
        E:/Go/src/runtime/mbitmap.go:1400 +0x4bb fp=0xc0000879d8 sp=0xc0000878d0 pc=0x6bed42fb
runtime.mallocgc(0x400, 0x6bf99ca0, 0xc000006001, 0x8)
        E:/Go/src/runtime/malloc.go:1052 +0x57d fp=0xc000087a78 sp=0xc0000879d8 pc=0x6becbfcd
runtime.makeslice(0x6bf99ca0, 0x8, 0x8, 0x0)
        E:/Go/src/runtime/slice.go:49 +0x73 fp=0xc000087aa8 sp=0xc000087a78 pc=0x6befe1d3
sync.(*Pool).pinSlow(0x6bf71d60, 0x0, 0x0)
        E:/Go/src/sync/pool.go:227 +0x101 fp=0xc000087b48 sp=0xc000087aa8 pc=0x6bf1e151
sync.(*Pool).pin(0x6bf71d60, 0x6bfb1e05, 0x10)
        E:/Go/src/sync/pool.go:206 +0x65 fp=0xc000087b70 sp=0xc000087b48 pc=0x6bf1e025
sync.(*Pool).Get(0x6bf71d60, 0x2, 0x6bfb1e05)
        E:/Go/src/sync/pool.go:128 +0x36 fp=0xc000087bb8 sp=0xc000087b70 pc=0x6bf1dcd6
fmt.newPrinter(0xc000087c18)
        E:/Go/src/fmt/print.go:137 +0x38 fp=0xc000087be0 sp=0xc000087bb8 pc=0x6bf599d8
fmt.Sprintln(0xc000087c90, 0x1, 0x1, 0xc000087c68, 0x6beedf77)
        E:/Go/src/fmt/print.go:280 +0x2d fp=0xc000087c38 sp=0xc000087be0 pc=0x6bf59d8d
log.Println(0xc000087c90, 0x1, 0x1)
        E:/Go/src/log/log.go:313 +0x46 fp=0xc000087c78 sp=0xc000087c38 pc=0x6bf616d6
main.Showui(...)
        F:/goproj/checkdll_log/dll.go:20
main._cgoexpwrap_2058aed3dd45_Showui(0x70006)
        _cgo_gotypes.go:45 +0x8b fp=0xc000087cb0 sp=0xc000087c78 pc=0x6bf6189b
runtime.call32(0x0, 0x83fc80, 0x83fdf0, 0x8)
        E:/Go/src/runtime/asm_amd64.s:539 +0x42 fp=0xc000087ce0 sp=0xc000087cb0 pc=0x6bf13422
runtime.cgocallbackg1(0x0)
        E:/Go/src/runtime/cgocall.go:314 +0x1c5 fp=0xc000087dc8 sp=0xc000087ce0 pc=0x6bec40f5
runtime.cgocallbackg(0x0)
        E:/Go/src/runtime/cgocall.go:191 +0xd5 fp=0xc000087e38 sp=0xc000087dc8 pc=0x6bec3e75
runtime: unexpected return pc for runtime.cgocallback_gofunc called from 0x453a97
stack: frame={sp:0xc000087e38, fp:0xc000087e58} stack=[0xc000080000,0xc000088000)
000000c000087d38:  000000c000087d78  0000000000000008
000000c000087d48:  000000c000087ce0  000000006bec40a3 <runtime.cgocallbackg1+371>
000000c000087d58:  000000006bfb90f8  0000000000000000
000000c000087d68:  000000c000087eb0  000000c000087d27
000000c000087d78:  000000c000087da8  00000000004353f3
000000c000087d88:  000000c000087db8  000000006bef6253 <runtime.exitsyscall+435>
000000c000087d98:  000000c000036000  0000000200000003
000000c000087da8:  000000c000036000  000000c000036000
000000c000087db8:  000000c000087e28  000000006bec3e75 <runtime.cgocallbackg+213>
000000c000087dc8:  0000000000000000  0000000000000008
000000c000087dd8:  000000c000087df0  00000000004036f5
000000c000087de8:  000000006bf618e0  0000000000000000
000000c000087df8:  000000c000087f10  000000006bf618e0
000000c000087e08:  0000000000000000  0000000000000000
000000c000087e18:  000000c000087e60  000000c000036000
000000c000087e28:  000000000083fc40  000000006bf14a82 <runtime.cgocallback_gofunc+178>
000000c000087e38: <0000000000000000  0000000000582300
000000c000087e48:  000000c000087e60 !0000000000453a97
000000c000087e58: >0000000000403719  0000000000455a80
000000c000087e68:  00000000005825d0  000000000042b831
000000c000087e78:  0000000000000000  0000000000582300
000000c000087e88:  000000c000087ef0  000000000044530a
000000c000087e98:  0000000000455a80  00000000005825d0
000000c000087ea8:  000000c000087ef0  0000000000000000
000000c000087eb8:  000000c000087e98  00000000004452a9
000000c000087ec8:  00000000004e2078  0000000000000000
000000c000087ed8:  000000c000087f90  0000000000000000
000000c000087ee8:  0000000000582300  000000c000087f50
000000c000087ef8:  00000000004a0b3f  000000006bf618e0
000000c000087f08:  0000000000000000  0000000000000000
000000c000087f18:  0000000000000000  0000000000000000
000000c000087f28:  0000000000000000  0000000000000000
000000c000087f38:  0000000000000000  00000000004b3580
000000c000087f48:  00000000004f3520  000000c000087fd0
runtime.cgocallback_gofunc(0x403719, 0x455a80, 0x5825d0, 0x42b831)
        E:/Go/src/runtime/asm_amd64.s:793 +0xb2 fp=0xc000087e58 sp=0xc000087e38 pc=0x6bf14a82
```

#### webstorm direct Run output:
```
GOROOT=E:\Go #gosetup
GOPATH=E:\GoPath #gosetup
E:\Go\bin\go.exe build -o C:\Users\white\AppData\Local\Temp\___go_build_main_go.exe F:/goproj/checkdll_log/main.go #gosetup
C:\Users\white\AppData\Local\Temp\___go_build_main_go.exe #gosetup
2019/09/07 22:30:41 main start
show uid called
fatal error: unexpected signal during runtime execution
[signal 0xc0000005 code=0x1 addr=0x0 pc=0x6bf164e8]

goroutine 1 [running, locked to thread]:
runtime.throw(0x6bfb76e9, 0x2a)
	E:/Go/src/runtime/panic.go:774 +0x79 fp=0xc000089898 sp=0xc000089868 pc=0x6beed4e9
runtime.sigpanic()
	E:/Go/src/runtime/signal_windows.go:227 +0x25a fp=0xc0000898c8 sp=0xc000089898 pc=0x6befdeea
runtime.memmove(0x0, 0xc000090800, 0x1)
	E:/Go/src/runtime/memmove_amd64.s:146 +0x108 fp=0xc0000898d0 sp=0xc0000898c8 pc=0x6bf164e8
runtime.heapBitsSetType(0xc000090800, 0x400, 0x400, 0x6bf99ca0)
	E:/Go/src/runtime/mbitmap.go:1400 +0x4bb fp=0xc0000899d8 sp=0xc0000898d0 pc=0x6bed42fb
runtime.mallocgc(0x400, 0x6bf99ca0, 0xc000006001, 0x8)
	E:/Go/src/runtime/malloc.go:1052 +0x57d fp=0xc000089a78 sp=0xc0000899d8 pc=0x6becbfcd
runtime.makeslice(0x6bf99ca0, 0x8, 0x8, 0x0)
	E:/Go/src/runtime/slice.go:49 +0x73 fp=0xc000089aa8 sp=0xc000089a78 pc=0x6befe1d3
sync.(*Pool).pinSlow(0x6bf71d60, 0x0, 0x0)
	E:/Go/src/sync/pool.go:227 +0x101 fp=0xc000089b48 sp=0xc000089aa8 pc=0x6bf1e151
sync.(*Pool).pin(0x6bf71d60, 0x6bfb1e05, 0x10)
	E:/Go/src/sync/pool.go:206 +0x65 fp=0xc000089b70 sp=0xc000089b48 pc=0x6bf1e025
sync.(*Pool).Get(0x6bf71d60, 0x2, 0x6bfb1e05)
	E:/Go/src/sync/pool.go:128 +0x36 fp=0xc000089bb8 sp=0xc000089b70 pc=0x6bf1dcd6
fmt.newPrinter(0xc000089c18)
	E:/Go/src/fmt/print.go:137 +0x38 fp=0xc000089be0 sp=0xc000089bb8 pc=0x6bf599d8
fmt.Sprintln(0xc000089c90, 0x1, 0x1, 0xc000089c68, 0x6beedf77)
	E:/Go/src/fmt/print.go:280 +0x2d fp=0xc000089c38 sp=0xc000089be0 pc=0x6bf59d8d
log.Println(0xc000089c90, 0x1, 0x1)
	E:/Go/src/log/log.go:313 +0x46 fp=0xc000089c78 sp=0xc000089c38 pc=0x6bf616d6
main.Showui(...)
	F:/goproj/checkdll_log/dll.go:20
main._cgoexpwrap_2058aed3dd45_Showui(0x70006)
	_cgo_gotypes.go:45 +0x8b fp=0xc000089cb0 sp=0xc000089c78 pc=0x6bf6189b
runtime.call32(0x0, 0x83fc80, 0x83fdf0, 0x8)
	E:/Go/src/runtime/asm_amd64.s:539 +0x42 fp=0xc000089ce0 sp=0xc000089cb0 pc=0x6bf13422
runtime.cgocallbackg1(0x0)
	E:/Go/src/runtime/cgocall.go:314 +0x1c5 fp=0xc000089dc8 sp=0xc000089ce0 pc=0x6bec40f5
runtime.cgocallbackg(0x0)
	E:/Go/src/runtime/cgocall.go:191 +0xd5 fp=0xc000089e38 sp=0xc000089dc8 pc=0x6bec3e75
runtime: unexpected return pc for runtime.cgocallback_gofunc called from 0x453a97
stack: frame={sp:0xc000089e38, fp:0xc000089e58} stack=[0xc000082000,0xc00008a000)
000000c000089d38:  000000c000089d78  0000000000000008 
000000c000089d48:  000000c000089ce0  000000006bec40a3 <runtime.cgocallbackg1+371> 
000000c000089d58:  000000006bfb90f8  0000000000000000 
000000c000089d68:  000000c000089eb0  000000c000089d27 
000000c000089d78:  000000c000089da8  00000000004353f3 
000000c000089d88:  000000c000089db8  000000006bef6253 <runtime.exitsyscall+435> 
000000c000089d98:  000000c000036000  0000000200000003 
000000c000089da8:  000000c000036000  000000c000036000 
000000c000089db8:  000000c000089e28  000000006bec3e75 <runtime.cgocallbackg+213> 
000000c000089dc8:  0000000000000000  0000000000000008 
000000c000089dd8:  000000c000089df0  00000000004036f5 
000000c000089de8:  000000006bf618e0  0000000000000000 
000000c000089df8:  000000c000089f10  000000006bf618e0 
000000c000089e08:  0000000000000000  0000000000000000 
000000c000089e18:  000000c000089e60  000000c000036000 
000000c000089e28:  000000000083fc40  000000006bf14a82 <runtime.cgocallback_gofunc+178> 
000000c000089e38: <0000000000000000  0000000000582300 
000000c000089e48:  000000c000089e60 !0000000000453a97 
000000c000089e58: >0000000000403719  0000000000455a80 
000000c000089e68:  00000000005825d0  000000000042b831 
000000c000089e78:  0000000000000000  0000000000582300 
000000c000089e88:  000000c000089ef0  000000000044530a 
000000c000089e98:  0000000000455a80  00000000005825d0 
000000c000089ea8:  000000c000089ef0  0000000000000000 
000000c000089eb8:  000000c000089e98  00000000004452a9 
000000c000089ec8:  00000000004e2078  0000000000000000 
000000c000089ed8:  000000c000089f90  0000000000000000 
000000c000089ee8:  0000000000582300  000000c000089f50 
000000c000089ef8:  00000000004a0b3f  000000006bf618e0 
000000c000089f08:  0000000000000000  0000000000000000 
000000c000089f18:  0000000000000000  0000000000000000 
000000c000089f28:  0000000000000000  0000000000000000 
000000c000089f38:  0000000000000000  00000000004b3580 
000000c000089f48:  00000000004f3520  000000c000089fd0 
runtime.cgocallback_gofunc(0x403719, 0x455a80, 0x5825d0, 0x42b831)
	E:/Go/src/runtime/asm_amd64.s:793 +0xb2 fp=0xc000089e58 sp=0xc000089e38 pc=0x6bf14a82

goroutine 1 [runnable, locked to thread]:
syscall.(*LazyDLL).Load(0x1c000004040, 0x6becb8bb, 0xdd9dd8)
	E:/Go/src/syscall/dll_windows.go:229 +0x12d
syscall.(*LazyProc).Find(0x1c000051b30, 0x0, 0x0)
	E:/Go/src/syscall/dll_windows.go:291 +0xbc
syscall.(*LazyProc).mustFind(0x1c000051b30)
	E:/Go/src/syscall/dll_windows.go:309 +0x32
syscall.(*LazyProc).Addr(0x1c000051b30, 0x3)
	E:/Go/src/syscall/dll_windows.go:318 +0x32
syscall.getSystemDirectory(0x1c000056000, 0x104, 0x104, 0x1c000056000, 0x6bf270eb)
	E:/Go/src/syscall/zsyscall_windows.go:1922 +0x38
syscall.init.0()
	E:/Go/src/syscall/dll_windows.go:48 +0x73

Process finished with exit code 2

```

#### If remove the Log package of  `dll.go` .

```
F:\goproj\checkdll_log>go build -o main.exe  main.go

F:\goproj\checkdll_log>main.exe
2019/09/07 22:42:24 main start
show uid called
2019/09/07 22:42:24 main end

F:\goproj\checkdll_log>main.exe
2019/09/07 22:42:28 main start
show uid called
2019/09/07 22:42:28 main end

F:\goproj\checkdll_log>main.exe
2019/09/07 22:42:28 main start
show uid called
2019/09/07 22:42:28 main end

F:\goproj\checkdll_log>main.exe
2019/09/07 22:42:29 main start
show uid called
2019/09/07 22:42:29 main end

F:\goproj\checkdll_log>main.exe
2019/09/07 22:42:29 main start
show uid called
2019/09/07 22:42:29 main end

F:\goproj\checkdll_log>main.exe
2019/09/07 22:42:30 main start
show uid called
2019/09/07 22:42:30 main end

F:\goproj\checkdll_log>main.exe
2019/09/07 22:42:30 main start
show uid called
2019/09/07 22:42:30 main end

F:\goproj\checkdll_log>main.exe
2019/09/07 22:42:30 main start
show uid called
2019/09/07 22:42:30 main end

F:\goproj\checkdll_log>main.exe
2019/09/07 22:42:30 main start
show uid called
2019/09/07 22:42:30 main end

F:\goproj\checkdll_log>main.exe
2019/09/07 22:42:31 main start
show uid called
2019/09/07 22:42:31 main end

F:\goproj\checkdll_log>main.exe
2019/09/07 22:42:31 main start
show uid called
2019/09/07 22:42:31 main end

F:\goproj\checkdll_log>main.exe
2019/09/07 22:42:31 main start
show uid called
2019/09/07 22:42:31 main end

F:\goproj\checkdll_log>main.exe
2019/09/07 22:42:32 main start
show uid called
2019/09/07 22:42:32 main end

F:\goproj\checkdll_log>main.exe
2019/09/07 22:42:32 main start
show uid called
2019/09/07 22:42:32 main end

F:\goproj\checkdll_log>main.exe
2019/09/07 22:42:32 main start
show uid called
2019/09/07 22:42:32 main end

F:\goproj\checkdll_log>main.exe
2019/09/07 22:42:33 main start
show uid called
2019/09/07 22:42:33 main end

F:\goproj\checkdll_log>main.exe
2019/09/07 22:42:33 main start
show uid called
2019/09/07 22:42:33 main end

F:\goproj\checkdll_log>main.exe
2019/09/07 22:42:33 main start
show uid called
2019/09/07 22:42:33 main end

F:\goproj\checkdll_log>main.exe
2019/09/07 22:42:33 main start
show uid called
2019/09/07 22:42:33 main end

F:\goproj\checkdll_log>main.exe
2019/09/07 22:42:34 main start
show uid called
fatal error: bad sweepgen in refill

goroutine 1 [running]:
runtime.throw(0x4dc566, 0x16)
        E:/Go/src/runtime/panic.go:774 +0x79 fp=0xc000093d40 sp=0xc000093d10 pc=0x42c8e9
runtime.(*mcache).refill(0x21f06b0, 0x5)
        E:/Go/src/runtime/mcache.go:132 +0x110 fp=0xc000093d60 sp=0xc000093d40 pc=0x414b40
runtime.(*mcache).nextFree(0x21f06b0, 0xc000036005, 0xc000036000, 0xc000036000, 0xc000093e28)
        E:/Go/src/runtime/malloc.go:854 +0x8e fp=0xc000093d98 sp=0xc000093d60 pc=0x40ac9e
runtime.mallocgc(0x8, 0x0, 0x4b3500, 0x4f3530)
        E:/Go/src/runtime/malloc.go:998 +0x5ed fp=0xc000093e38 sp=0xc000093d98 pc=0x40b43d
runtime.slicebytetostring(0x0, 0xc00006c080, 0x8, 0x10, 0x0, 0x0)
        E:/Go/src/runtime/string.go:102 +0xa6 fp=0xc000093e68 sp=0xc000093e38 pc=0x441436
fmt.Sprint(0xc000093f40, 0x1, 0x1, 0xc000093f90, 0x0)
        E:/Go/src/fmt/print.go:250 +0x85 fp=0xc000093ec0 sp=0xc000093e68 pc=0x4990c5
log.Print(0xc000093f40, 0x1, 0x1)
        E:/Go/src/log/log.go:301 +0x46 fp=0xc000093f00 sp=0xc000093ec0 pc=0x4a09a6
main.main()
        F:/goproj/checkdll_log/main.go:14 +0xff fp=0xc000093f60 sp=0xc000093f00 pc=0x4a0b7f
runtime.main()
        E:/Go/src/runtime/proc.go:203 +0x21e fp=0xc000093fe0 sp=0xc000093f60 pc=0x42e2ce
runtime.goexit()
        E:/Go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000093fe8 sp=0xc000093fe0 pc=0x4541e1

F:\goproj\checkdll_log>main.exe
2019/09/07 22:42:34 main start
show uid called
2019/09/07 22:42:34 main end

F:\goproj\checkdll_log>


```

Every run error is different.  :(

**Comment by antong** [comment]
I guess this is a dup of #22192 ?

**Comment by whtiehack** [comment]
God, it has been two years, has not been dealt with?
