### ISSUE TITLE
While trying to test any package with "mongodb" imports go causes "anonymous field expected" panics.

### ISSUE THREAD

**Issue by matszpk** [golang/go#34182]
I am using go 1.12.2 on Arch Linux (gcc 9.1.0) updated from 2019.09.08.
I am using AMD Ryzen (first generation processor).
Any trial of testing any package with import "go.mongodb.org/mongo-driver" causes enough strange error:

`#go.mongodb.org/mongo-driver/bson
panic: import error <input>:1:31 (byte offset = 30): anonymous field expected [recovered]
	panic: import error <input>:1:31 (byte offset = 30): anonymous field expected

goroutine 1 [running]:
types.r
	/build/gcc/src/gcc/libgo/go/go/types/check.go:240
go..z2ftypes.Checker.handleBailout
	/build/gcc/src/gcc/libgo/go/go/types/check.go:233
panic
	/build/gcc/src/gcc/libgo/go/runtime/panic.go:555
go..z2finternal..z2fgccgoimporter.parser.error
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:86
go..z2finternal..z2fgccgoimporter.parser.parseField
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:251
go..z2finternal..z2fgccgoimporter.parser.parseStructType
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:662
go..z2finternal..z2fgccgoimporter.parser.parseTypeSpec
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:802
go..z2finternal..z2fgccgoimporter.parser.parseSavedType
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:1022
go..z2finternal..z2fgccgoimporter.parser.parseTypeAfterAngle
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:891
go..z2finternal..z2fgccgoimporter.parser.parseType
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:879
go..z2finternal..z2fgccgoimporter.parser.parseNamedType
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:526
go..z2finternal..z2fgccgoimporter.parser.parseTypeSpec
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:791
go..z2finternal..z2fgccgoimporter.parser.parseSavedType
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:1022
go..z2finternal..z2fgccgoimporter.parser.parseTypeAfterAngle
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:891
go..z2finternal..z2fgccgoimporter.parser.parseType
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:879
go..z2finternal..z2fgccgoimporter.parser.parseParam
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:278
go..z2finternal..z2fgccgoimporter.parser.parseParamList
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:683
go..z2finternal..z2fgccgoimporter.parser.parseFunctionType
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:721
go..z2finternal..z2fgccgoimporter.parser.parseFunc
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:737
go..z2finternal..z2fgccgoimporter.parser.parseInterfaceType
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:758
go..z2finternal..z2fgccgoimporter.parser.parseTypeSpec
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:805
go..z2finternal..z2fgccgoimporter.parser.parseSavedType
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:1022
go..z2finternal..z2fgccgoimporter.parser.parseTypeAfterAngle
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:891
go..z2finternal..z2fgccgoimporter.parser.parseType
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:879
go..z2finternal..z2fgccgoimporter.parser.parseNamedType
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:526
go..z2finternal..z2fgccgoimporter.parser.parseTypeSpec
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:791
go..z2finternal..z2fgccgoimporter.parser.parseSavedType
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:1022
go..z2finternal..z2fgccgoimporter.parser.parseTypeAfterAngle
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:891
go..z2finternal..z2fgccgoimporter.parser.parseType
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:879
go..z2finternal..z2fgccgoimporter.parser.parseMapType
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:617
go..z2finternal..z2fgccgoimporter.parser.parseTypeSpec
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:796
go..z2finternal..z2fgccgoimporter.parser.parseSavedType
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:1022
go..z2finternal..z2fgccgoimporter.parser.parseTypeAfterAngle
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:891
go..z2finternal..z2fgccgoimporter.parser.parseType
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:879
go..z2finternal..z2fgccgoimporter.parser.parseField
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:241
go..z2finternal..z2fgccgoimporter.parser.parseStructType
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:662
go..z2finternal..z2fgccgoimporter.parser.parseTypeSpec
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:802
go..z2finternal..z2fgccgoimporter.parser.parseSavedType
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:1022
go..z2finternal..z2fgccgoimporter.parser.parseTypeAfterAngle
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:891
go..z2finternal..z2fgccgoimporter.parser.parseType
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:879
go..z2finternal..z2fgccgoimporter.parser.parseNamedType
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:526
go..z2finternal..z2fgccgoimporter.parser.parseTypeSpec
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:791
go..z2finternal..z2fgccgoimporter.parser.parseSavedType
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:1022
go..z2finternal..z2fgccgoimporter.parser.parseTypeAfterAngle
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:891
go..z2finternal..z2fgccgoimporter.parser.parseType
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:879
go..z2finternal..z2fgccgoimporter.parser.parsePointerType
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:782
go..z2finternal..z2fgccgoimporter.parser.parseTypeSpec
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:809
go..z2finternal..z2fgccgoimporter.parser.parseSavedType
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:1022
go..z2finternal..z2fgccgoimporter.parser.parseTypeAfterAngle
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:891
go..z2finternal..z2fgccgoimporter.parser.parseType
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:879
go..z2finternal..z2fgccgoimporter.parser.parseField
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:241
go..z2finternal..z2fgccgoimporter.parser.parseStructType
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:662
go..z2finternal..z2fgccgoimporter.parser.parseTypeSpec
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:802
go..z2finternal..z2fgccgoimporter.parser.parseSavedType
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:1022
go..z2finternal..z2fgccgoimporter.parser.parseTypeAfterAngle
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:891
go..z2finternal..z2fgccgoimporter.parser.parseType
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:879
go..z2finternal..z2fgccgoimporter.parser.parseNamedType
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:526
go..z2finternal..z2fgccgoimporter.parser.parseTypeSpec
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:791
go..z2finternal..z2fgccgoimporter.parser.parseSavedType
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:1022
go..z2finternal..z2fgccgoimporter.parser.parseTypes
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:998
go..z2finternal..z2fgccgoimporter.parser.parseDirective
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:1175
go..z2finternal..z2fgccgoimporter.parser.parsePackage
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/parser.go:1211
gccgoimporter.GetImporter..func1
	/build/gcc/src/gcc/libgo/go/go/internal/gccgoimporter/importer.go:216
go..z2fimporter.gccgoimports.ImportFrom
	/build/gcc/src/gcc/libgo/go/go/importer/importer.go:128
go..z2fimporter.gccgoimports.Import
	/build/gcc/src/gcc/libgo/go/go/importer/importer.go:121
go..z2ftypes.Checker.importPackage
	/build/gcc/src/gcc/libgo/go/go/types/resolver.go:161
go..z2ftypes.Checker.collectObjects
	/build/gcc/src/gcc/libgo/go/go/types/resolver.go:256
go..z2ftypes.Checker.checkFiles
	/build/gcc/src/gcc/libgo/go/go/types/check.go:252
go..z2ftypes.Checker.Files
	/build/gcc/src/gcc/libgo/go/go/types/check.go:245
go..z2ftypes.Config.Check
	/build/gcc/src/gcc/libgo/go/go/types/api.go:351
main.main
	:0`

go env output:
`GOARCH="amd64"
GOBIN=""
GOCACHE="/mnt/oldsys/home/mat/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/mat/go"
GOPROXY=""
GORACE=""
GOROOT="/usr"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0"
GCCGO="/usr/bin/gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build001405097=/tmp/go-build -gno-record-gcc-switches -funwind-tables"`

Maybe this is bug in gcimporter or other internals? I don't know.

**Comment by agnivade** [comment]
This sounds like an issue with the code itself. Have you tried raising an issue with mongodb ?

Also, this sounds like easily reproducible. Can you provide us with a small self-contained reproducer which demonstrates the issue ? Thanks.

**Comment by matszpk** [comment]
Yes. I did. In package is workspace with trivial example.
[mongodb-tests-ws.zip](https://github.com/golang/go/files/3588947/mongodb-tests-ws.zip)

**Comment by matszpk** [comment]
I am using gccgo compiler, because only that compiler is available in standard installation from Arch Linux (I am using go from Arch standard package).

**Comment by matszpk** [comment]
I was trying run test on my old 32-bit system (Athlon XP with gentoo) with using builtin gccgo (9.1.0) and I got this same error.

**Comment by agnivade** [comment]
Oh I see you are using gccgo, sorry I missed that. Is it a requirement that you use gccgo ? Because you can easily install the standard Go distribution in your machine.

**Comment by OneOfOne** [comment]
Off topic, but standard go is available in the community repo.

```
┏━ oneofone@voyager ❰~❱
┗━❰1❱━● sudo pacman -S go
warning: go-2:1.13-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...
Package (1)   Old Version  New Version  Net Change
community/go  2:1.13-1     2:1.13-1       0.00 MiB
```

**Comment by ianlancetaylor** [comment]
This is a bug in go/internal/gccgoimporter.  A simple test case is

```Go
package issue34182

type T1 struct {
	f *T2
}

type T2 struct {
	f map[int] T3
}

type T3 interface {
	M(T4)
}

type T4 struct {
	*T2
}
```

**Comment by ianlancetaylor** [comment]
Slightly simpler still:

```Go
package issue34182

type T1 struct {
	f *T2
}

type T2 struct {
	f T3
}

type T3 struct {
	*T2
}
```

**Comment by ianlancetaylor** [comment]
Thanks for the report.  This has been fixed on GCC trunk and GCC 9 branch.

It is likely that you can work around the problem by running `go test -vet=off`.
