### ISSUE TITLE
x/tools/gopls: panic in ParseGoHandle

### ISSUE THREAD

**Issue by muirrn** [golang/go#34359]
Starting getting this panic as I was trying to reproduce an unsaved overlay file issue (on master d997db1b286aff6496d2e5a6801d5e40dc2c2575):

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x156ee89]

goroutine 6863 [running]:
go/ast.(*File).Pos(...)
	/usr/local/go/src/go/ast/ast.go:997
golang.org/x/tools/internal/lsp/cache.(*cache).ParseGoHandle.func1(0x17e4380, 0xc001a6a6c0, 0x1723f80, 0xc00ec53500)
	/Users/muir/projects/tools/internal/lsp/cache/parse.go:57 +0x119
golang.org/x/tools/internal/memoize.(*Handle).run.func1(0xc0044d27d0, 0x17e4380, 0xc001a6a6c0)
	/Users/muir/projects/tools/internal/memoize/memoize.go:181 +0x3e
created by golang.org/x/tools/internal/memoize.(*Handle).run
	/Users/muir/projects/tools/internal/memoize/memoize.go:178 +0xfe
```

**Comment by stamblerre** [comment]
I think this will be fixed with https://go-review.googlesource.com/c/tools/+/195997.

**Comment by muirrn** [comment]
Thanks - seems to not happen anymore. Will reopen if I see it again.
