### ISSUE TITLE
cmd/compile: internal compiler error - 'can't find empty register' on ppc64le builders

### ISSUE THREAD

**Issue by ALTree** [golang/go#34468]
The linux-ppc64le builders are currently broken with a `internal compiler error: 'checkIfRange'` crash:

```
##### Testing race detector
# net/http
m:0 unique:58 final:0 rematerializable:0
v2: v2 SP
v414: v414 R3
v205: v205 R4
v459: v348 R5
v458: v458 modtime+8[int64]
v457: v457 modtime+16[*time.Location]
net/http/fs.go:448:14: internal compiler error: 'checkIfRange': can't find empty register on edge b61->b65

goroutine 1 [running]:
runtime/debug.Stack(0xadf820, 0xc000086008, 0x0)
	/tmp/workdir-host-linux-ppc64le-osu/go/src/runtime/debug/stack.go:24 +0x8c
cmd/compile/internal/gc.Fatalf(0xc002c89170, 0x2e, 0xc002d93b00, 0x3, 0x3)
	/tmp/workdir-host-linux-ppc64le-osu/go/src/cmd/compile/internal/gc/subr.go:188 +0x294
cmd/compile/internal/gc.(*ssafn).Fatalf(0xc002f254d0, 0x1c00e000000007, 0x93d17d, 0x28, 0xc002d8d9e0, 0x2, 0x2)
	/tmp/workdir-host-linux-ppc64le-osu/go/src/cmd/compile/internal/gc/ssa.go:6177 +0x160
cmd/compile/internal/ssa.(*Func).Fatalf(...)
	/tmp/workdir-host-linux-ppc64le-osu/go/src/cmd/compile/internal/ssa/func.go:617
cmd/compile/internal/ssa.(*edgeState).findRegFor(0xc002da4a90, 0xc0000883c0, 0xc002da4908, 0xc002ebdca8)
	/tmp/workdir-host-linux-ppc64le-osu/go/src/cmd/compile/internal/ssa/regalloc.go:2287 +0x3dc
cmd/compile/internal/ssa.(*edgeState).process(0xc002da4a90)
	/tmp/workdir-host-linux-ppc64le-osu/go/src/cmd/compile/internal/ssa/regalloc.go:2010 +0x308
cmd/compile/internal/ssa.(*regAllocState).shuffle(0xc002f2b200, 0xc002f03800, 0x49, 0x49)
	/tmp/workdir-host-linux-ppc64le-osu/go/src/cmd/compile/internal/ssa/regalloc.go:1848 +0x204
cmd/compile/internal/ssa.(*regAllocState).regalloc(0xc002f2b200, 0xc002eaac60)
	/tmp/workdir-host-linux-ppc64le-osu/go/src/cmd/compile/internal/ssa/regalloc.go:1659 +0x18d0
cmd/compile/internal/ssa.regalloc(0xc002eaac60)
	/tmp/workdir-host-linux-ppc64le-osu/go/src/cmd/compile/internal/ssa/regalloc.go:146 +0x5c
cmd/compile/internal/ssa.Compile(0xc002eaac60)
	/tmp/workdir-host-linux-ppc64le-osu/go/src/cmd/compile/internal/ssa/compile.go:92 +0x8a4
cmd/compile/internal/gc.buildssa(0xc0008dc160, 0x0, 0x0)
	/tmp/workdir-host-linux-ppc64le-osu/go/src/cmd/compile/internal/gc/ssa.go:289 +0x778
cmd/compile/internal/gc.compileSSA(0xc0008dc160, 0x0)
	/tmp/workdir-host-linux-ppc64le-osu/go/src/cmd/compile/internal/gc/pgen.go:298 +0x38
cmd/compile/internal/gc.compile(0xc0008dc160)
	/tmp/workdir-host-linux-ppc64le-osu/go/src/cmd/compile/internal/gc/pgen.go:277 +0x26c
cmd/compile/internal/gc.funccompile(0xc0008dc160)
	/tmp/workdir-host-linux-ppc64le-osu/go/src/cmd/compile/internal/gc/pgen.go:222 +0xe8
cmd/compile/internal/gc.Main(0x949c48)
	/tmp/workdir-host-linux-ppc64le-osu/go/src/cmd/compile/internal/gc/main.go:682 +0x3184
main.main()
	/tmp/workdir-host-linux-ppc64le-osu/go/src/cmd/compile/main.go:51 +0xb8

2019/09/23 06:03:30 Failed: exit status 2
2019/09/23 06:03:50 FAILED
```

Full log: https://build.golang.org/log/b288cd59a7c053c8cf0136972f9c37c42bc678c6

The breakage started after [CL 194297](https://go-review.googlesource.com/c/go/+/194297) (compile: prefer an AND instead of SHR+SHL instructions).

cc @martisch

**Comment by martisch** [comment]
@laboger. I do not currently have a ppc64le machine setup to test or debug this. Could you please have a look if there is an easy fix forward?

As this only happens in race and on ppc64le (not ppc64) it seems a special/local problem. Maybe since cl/194297 can use introduce the use of an extra register to load a large constant where it previously did not this increased the register pressure above a threshold when compiling the `checkIfRange` in race mode. If that is the case could registers be spilled to resolve the problem?
Seems other changes could run into this problem too if not resolved generally.

https://github.com/golang/go/blob/7ed973b4d9dab38347f34e87febf3c8659160ce6/src/net/http/fs.go#L447

**Comment by randall77** [comment]
This is strange. The register allocator is reporting `m==0` in `(*edgeState).findRegFor`.
That's shouldn't happen. `m` is initialized (and then never modified) to
```
	var m regMask
	if typ.IsFloat() {
		m = e.s.compatRegs(types.Float64)
	} else {
		m = e.s.compatRegs(types.Int64)
	}
```
Both those calls should return nonzero.

**Comment by cherrymui** [comment]
CL 195117 changes it to call `compatRegs` with `typ`, and let `compatRegs` to find the one for the given type. If is float or int, it should be fine. But if `typ` is flags, the behavior changes: it used to return integer register's mask, now it returns 0. In this particular case, `typ` is in fact flags. I thought we shouldn't have flags type here?

The interesting value here is v205, which is of type flags but got register R4. This seems bad.

```
  b61: <- b59
    v352 = MOVDaddr <*int64> {time.t} [8] v2 : R3
    v412 = MOVDstore <mem> [32] v2 v352 v387
    v413 = CALLstatic <mem> {runtime.raceread} [40] v412
    v414 = MOVDload <int64> {time.t} [8] v2 v413 : R3 (~R0[int64])
    v348 = LoadReg <uint64> v459 : R5
    v62 = MOVDconst <uint64> [-9223372036854775808] : R4
    v205 = ANDCC <flags> v348 v62 : R4
    Plain -> b65
```

**Comment by cherrymui** [comment]
PPC64Ops.go has:

```
		{name: "ANDCC", argLength: 2, reg: gp21, asm: "ANDCC", commutative: true, typ: "Flags"}, // arg0&arg1 sets CC
```

I think this is not right. It should have a tuple type like (Int64, Flags) instead of flags type.

**Comment by randall77** [comment]
I think ANDCC doesn't generate the result of the AND, just the flags. So the fix might be as simple as replacing gp21 with gp2flags.
