### ISSUE TITLE
net: TestDialParallelSpuriousConnection occasionally times out

### ISSUE THREAD

**Issue by bcmills** [golang/go#34495]
From the `darwin-amd64-race` builder (https://build.golang.org/log/96aa6d382799b872cbedeb56e3b9d2076acc6546):

<details>

```
panic: test timed out after 3m0s

goroutine 15 [running]:
testing.(*M).startAlarm.func1()
	/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/testing/testing.go:1377 +0x11c
created by time.goFunc
	/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/time/sleep.go:168 +0x52

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000102000, 0x13ceb09, 0x22, 0x13d56f0, 0x1)
	/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/testing/testing.go:961 +0x68a
testing.runTests.func1(0xc000102000)
	/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/testing/testing.go:1202 +0xa7
testing.tRunner(0xc000102000, 0xc000095d08)
	/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/testing/testing.go:909 +0x19a
testing.runTests(0xc0000d6120, 0x1609be0, 0xe4, 0xe4, 0x0)
	/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/testing/testing.go:1200 +0x522
testing.(*M).Run(0xc0000e6000, 0x0)
	/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/testing/testing.go:1117 +0x300
net.TestMain(0xc0000e6000)
	/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/net/main_test.go:52 +0x47
main.main()
	_testmain.go:564 +0x224

goroutine 29 [semacquire]:
sync.runtime_Semacquire(0xc0000b1908)
	/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc0000b1900)
	/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/sync/waitgroup.go:130 +0xb1
net.TestDialParallelSpuriousConnection(0xc000102400)
	/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/net/dial_test.go:502 +0x605
testing.tRunner(0xc000102400, 0x13d56f0)
	/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/testing/testing.go:909 +0x19a
created by testing.(*T).Run
	/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/testing/testing.go:960 +0x652

goroutine 31 [IO wait]:
internal/poll.runtime_pollWait(0x2495f08, 0x72, 0x0)
	/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0000e6598, 0x72, 0x0, 0x0, 0x13c32f2)
	/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/internal/poll/fd_poll_runtime.go:87 +0xe4
internal/poll.(*pollDesc).waitRead(...)
	/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0000e6580, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/internal/poll/fd_unix.go:384 +0x2cc
net.(*netFD).accept(0xc0000e6580, 0xc0000b1830, 0xf, 0xf)
	/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/net/fd_unix.go:238 +0x56
net.(*TCPListener).accept(0xc0000d65e0, 0x5, 0xf, 0x5)
	/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/net/tcpsock_posix.go:139 +0x50
net.(*TCPListener).Accept(0xc0000d65e0, 0xbf5a84fb15435818, 0x12b4d9c54, 0x160d240, 0xc0001e37b0)
	/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/net/tcpsock.go:261 +0x50
net.TestDialParallelSpuriousConnection.func1(0xc000256000, 0x1432d80, 0xc0000d65e0)
	/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/net/dial_test.go:439 +0x7c
net.(*dualStackServer).buildup.func1(0xc0000d65a0, 0xc000256000, 0x1)
	/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/net/mockserver_test.go:148 +0xb3
created by net.(*dualStackServer).buildup
	/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/net/mockserver_test.go:147 +0x86
FAIL	net	180.026s
```

</details>

It's not obvious to me whether the test was deadlocked or just ran out of time.

If the latter, perhaps some of its tests should be skipped in short mode (and/or when the race detector is enabled)?

CC @mikioh @bradfitz @ianlancetaylor

**Comment by bcmills** [comment]
Compare #32534, #32919.

**Comment by bcmills** [comment]
Same failure mode on `solaris-amd64-oraclerel`: https://build.golang.org/log/05176237c5a06f48100a31a8b05997879c9f8ea1

**Comment by bcmills** [comment]
`darwin-amd64-10_12`: https://build.golang.org/log/5a6b1d2da89c39f0aa344ce5d9996aa44b8133a8

**Comment by bcmills** [comment]
`darwin-amd64-10_12`: https://build.golang.org/log/22a57819568de78654e834c54ee909a50826230b

**Comment by bcmills** [comment]
[2020-02-29T17:02:40-74f8983/darwin-arm64-corellium](https://build.golang.org/log/4549765c163a91a0e7e32962889d48bfe7e95bdd)
[2020-02-24T16:39:52-3093959/darwin-arm64-corellium](https://build.golang.org/log/869118b952e5b3701928ec5b1b031ee71d8b35c2)
[2020-01-31T20:18:54-1b7fefc/darwin-arm64-corellium](https://build.golang.org/log/67ea852f406557047ee3cab3ea1f38b8272c3c3b)
[2020-01-23T21:01:12-ace25f8/darwin-arm-mg912baios](https://build.golang.org/log/63b640eba3f3da929bf1fe32d598d055726596a7)
[2020-01-19T14:04:09-8e0be05/darwin-arm-mg912baios](https://build.golang.org/log/dfd177534563923a6d47bc98978e76335a8dfe8f)

**Comment by bcmills** [comment]
More of the new failure mode:
[2020-03-10T00:24:30-08dee51/darwin-arm64-corellium](https://build.golang.org/log/7c802e93b4c866a8b92572dd0a715bbbe596cefa)
[2020-03-02T15:39:23-12d02e7/darwin-arm64-corellium](https://build.golang.org/log/088968d50b6452a8b743f1f22954df5b8d7d921b)

**Comment by bcmills** [comment]
Looks like the old failure mode really did stop in October.

[2019-10-31T23:37:57-ce49f95/aix-ppc64](https://build.golang.org/log/1f6c7a5a5db0d9c4cfa256d5c21f4f097f4b901f)
[2019-10-30T14:06:04-17190de/darwin-amd64-10_12](https://build.golang.org/log/22a57819568de78654e834c54ee909a50826230b)
[2019-10-23T07:43:18-ab3f1a2/darwin-amd64-10_12](https://build.golang.org/log/90c78aa01c32c69a7e995230626aed52e6c74ba0)
[2019-10-11T16:34:01-ba108c9/darwin-amd64-race](https://build.golang.org/log/160cb757981d5c1e4df1d94ff36b54eccd9922f7)
[2019-10-08T17:30:14-868de9a/darwin-amd64-10_12](https://build.golang.org/log/5a6b1d2da89c39f0aa344ce5d9996aa44b8133a8)
[2019-10-02T17:24:11-0000f0b/solaris-amd64-oraclerel](https://build.golang.org/log/05176237c5a06f48100a31a8b05997879c9f8ea1)
[2019-09-24T04:19:31-e29d276/darwin-amd64-race](https://build.golang.org/log/96aa6d382799b872cbedeb56e3b9d2076acc6546)
[2019-09-18T20:32:43-bcf6f9f/darwin-amd64-10_12](https://build.golang.org/log/ded90eca43db4ae11b74f27beeabc3ae3829bc93)
[2019-09-16T22:14:49-115e4c9/darwin-amd64-race](https://build.golang.org/log/55dbba50af52c16a8c77fe9287b1567604ad7eaa)
[2019-09-06T21:22:26-8a8cf5b/darwin-amd64-race](https://build.golang.org/log/06e7ec855e55f254cddb9881def65b248227bf1e)
[2019-06-25T17:51:25-a6ad626/darwin-amd64-race](https://build.golang.org/log/aa6fac9a159eff5da5013b8bf117adb25130e307)
[2019-05-13T17:01:25-db2bf15/darwin-amd64-race](https://build.golang.org/log/52c34c976f66ee4d74a78ef0b8105b58c9e8764b)
[2019-04-30T18:29:07-888bac1/darwin-amd64-race](https://build.golang.org/log/def1e7e61a239530b088fbce3cc5ca961aa27c55)

**Comment by bcmills** [comment]
Actually, those new failures seem Corellium-specific. Opening a new issue.

**Comment by bcmills** [comment]
Looks like the hiatus from October 2019 to March 2020 was only temporary.

`greplogs --dashboard -md -l -e '^panic: test timed out.*\n(?:.*\n)*net\..*\.Accept.*\n\t.*\nnet\.TestDialParallelSpuriousConnection' --since=2020-01-01`

[2021-12-21T22:26:48-60f2c12/freebsd-arm64-dmgk](https://build.golang.org/log/396ec6331b1dbc49944c3a48595647984fb3062a)
[2021-12-02T20:21:16-469f030/netbsd-amd64-9_0-n2d](https://build.golang.org/log/cb6e3c6056642d1f541ac2fa5833f42e3a2fc111)
[2021-10-27T08:50:27-bdefb77/openbsd-arm64-jsing](https://build.golang.org/log/51f2269f911e78cb40bd1f9c8f91d573b2874df2)
[2021-08-26T02:06:43-a6ff433/netbsd-arm-bsiegert](https://build.golang.org/log/097ddeeca30d7d878f51d3d0b1fd47883cd13dc6)
[2021-08-20T18:45:25-0f25251/openbsd-arm64-jsing](https://build.golang.org/log/b95ef1e51285292a40fce5614010d6b5ca4ccb89)
[2021-08-13T20:45:17-98f3d7f/solaris-amd64-oraclerel](https://build.golang.org/log/5879c477d781161ae2f8f7874c2dc6cd4fa265af)
[2021-06-24T18:58:27-cce6214/openbsd-arm64-jsing](https://build.golang.org/log/1b255f104456bf0ede532997c5c764b368df48ad)
[2021-06-18T16:56:48-57aaa19/openbsd-arm64-jsing](https://build.golang.org/log/987d8b82bdebb9581ca4e94359993e01e74b8dc8)
[2021-05-21T18:55:18-e4d7525/illumos-amd64](https://build.golang.org/log/011bb49e821f15b1dee10012804cbe8ba25a100c)
[2021-05-13T14:30:42-fd4631e/openbsd-arm64-jsing](https://build.golang.org/log/816dcaa7ac083d1bb052db9c6f5a913bc988ab30)
[2021-05-11T02:46:21-326a792/illumos-amd64](https://build.golang.org/log/3c81cdfba1ec905bbe5876303da8fc9ba9987525)
[2021-05-01T11:42:49-a9db5a7/openbsd-arm64-jsing](https://build.golang.org/log/7a0acf11a6bbf142141b04e8855420184f673915)
[2021-04-19T23:02:15-7252e1e/darwin-amd64-10_12](https://build.golang.org/log/541acbcdba49174da870ee5622494e00b9524d50)
[2021-04-14T00:25:33-8dcc071/freebsd-arm64-dmgk](https://build.golang.org/log/bb4b53f8347910cf0978c2c2bc09cd1f2a26984e)
[2021-04-09T13:10:36-c432917/netbsd-386-9_0](https://build.golang.org/log/bc24832f366e77f3efe760ca9a46bbbfb754d55a)
[2021-03-29T08:11:13-565e70f/openbsd-arm64-jsing](https://build.golang.org/log/c23a60786b51b37b2418610c7e5fc069ece0c95e)
[2021-01-15T20:37:59-ec94701/darwin-amd64-10_12](https://build.golang.org/log/650751f23f94ae6d509d5564ba761cf117f01f2c)
[2020-12-07T21:01:46-7ad6596/openbsd-arm64-jsing](https://build.golang.org/log/9dae7045f1f9f7d66edf536ed28b26fc60ef81a9)
[2020-11-10T09:01:41-1c7650a/darwin-amd64-10_12](https://build.golang.org/log/fb0a342680c4f62a0c287689fd2c691e1c93e124)
[2020-06-26T17:07:58-d1015f3/solaris-amd64-oraclerel](https://build.golang.org/log/4e3f1d63c03126e03db71b7a4835883db82f12d7)
[2020-04-30T14:41:10-ecdbffd/solaris-amd64-oraclerel](https://build.golang.org/log/f1b2e50f96db03b4d0a228f13e13b6b6248c78b8)
