### ISSUE TITLE
cmd/compile: panic: First time we've seen filename

### ISSUE THREAD

**Issue by ALTree** [golang/go#34520]
```
$ gotip version
go version devel +8f5755e76e Wed Sep 25 07:05:18 2019 +0000 windows/amd64
```

The following program:
```
package p

func f() {
        for true {
        }
}
```

Crashes the tip compiler with this error:

```
 $ gotip tool compile crash.go

panic: First time we've seen filename: "gofile..??"

goroutine 1 [running]:
cmd/internal/obj.(*Link).generateDebugLinesSymbol(0xc0002c2160, 0xc0003a22a0, 0xc0003a24d0)
        D:/users/ZZZZZ/alberto/other/temp/go/src/cmd/internal/obj/dwarf.go:42 +0xb4f
cmd/internal/obj.(*Link).populateDWARF(0xc0002c2160, 0xe36460, 0xc0002c22c0, 0xc0003a22a0, 0x0, 0x0)
        D:/users/ZZZZZ/alberto/other/temp/go/src/cmd/internal/obj/objfile.go:628 +0x323
cmd/internal/obj.Flushplist(0xc0002c2160, 0xc00008f638, 0xc00004e9e0, 0x0, 0x0)
        D:/users/ZZZZZ/alberto/other/temp/go/src/cmd/internal/obj/plist.go:112 +0x7df
cmd/compile/internal/gc.(*Progs).Flush(0xc0003a2620)
        D:/users/ZZZZZ/alberto/other/temp/go/src/cmd/compile/internal/gc/gsubr.go:93 +0xc3
cmd/compile/internal/gc.compileSSA(0xc0002c22c0, 0x0)
        D:/users/ZZZZZ/alberto/other/temp/go/src/cmd/compile/internal/gc/pgen.go:323 +0x6a4
cmd/compile/internal/gc.compile(0xc0002c22c0)
        D:/users/ZZZZZ/alberto/other/temp/go/src/cmd/compile/internal/gc/pgen.go:277 +0x33b
cmd/compile/internal/gc.funccompile(0xc0002c22c0)
        D:/users/ZZZZZ/alberto/other/temp/go/src/cmd/compile/internal/gc/pgen.go:222 +0xc8
cmd/compile/internal/gc.Main(0xe62cb0)
        D:/users/ZZZZZ/alberto/other/temp/go/src/cmd/compile/internal/gc/main.go:682 +0x3133
main.main()
        D:/users/ZZZZZ/alberto/other/temp/go/src/cmd/compile/main.go:51 +0xb3
```

It compiles fine in go1.13.

**Comment by ALTree** [comment]
It appears that this started at ee3dded36d69264998c39af0ec851371850d842b (cmd/compile: generate debug_lines in compiler). 

cc @jeremyfaller
