### ISSUE TITLE
x/tools/internal/imports: data-race causes panic due to concurrent map read and write

### ISSUE THREAD

**Issue by a8m** [golang/go#34895]
When running `imports.Process` concurrently, the program panics with a fatal error due to concurrent map iterations and map writes.

I've created a CL that fixes this - https://go-review.googlesource.com/c/tools/+/200865 (so, I'm not sure this Github issue is really needed?)

This can be reproduced as follows:

```console
$ tree
.
├── main.go
└── testdata
    ├── first.go
    └── second.go
```

<details><summary>main.go</summary>
<p>

```go
package main

import (
	"log"
	"sync"

	"golang.org/x/tools/imports"
)

func main() {
	var (
		n  = 10
		wg sync.WaitGroup
	)
	wg.Add(n)
	for i := 0; i < n; i++ {
		go func() {
			defer wg.Done()
			_, err := imports.Process("testdata/first.go", nil, nil)
			if err != nil {
				log.Fatal(err)
			}
		}()
	}
	wg.Wait()
}
```
</p>
</details>

<details><summary>testdata/first.go</summary>
<p>

```go
package testdata

func _() {
	fmt.Println()
}
```
</p>
</details>

<details><summary>testdata/second.go</summary>
<p>

```go
package testdata

import "fmt"

func _() {
	fmt.Println()
	imports.Bar() // not imported.
}
```
</p>
</details>

----
**Output:**

```output
fatal error: concurrent map writes
fatal error: concurrent map writes
fatal error: concurrent map iteration and map write
fatal error: concurrent map writes

goroutine 14 [running]:
runtime.throw(0x1312874, 0x15)
	/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc0000dda48 sp=0xc0000dda18 pc=0x102c7f2
runtime.mapassign_faststr(0x12a4840, 0xc000073380, 0x12fafa3, 0x9, 0xc0000e2a8c)
	/usr/local/go/src/runtime/map_faststr.go:211 +0x417 fp=0xc0000ddab0 sp=0xc0000dda48 pc=0x10126c7
....
```

**Comment by a8m** [comment]
Closed with golang/tools@1f7a813c0df1b2a1c1526e54c5ee4aa940c58d14
