### ISSUE TITLE
tools/internal/lsp: panic in go/packages during package rename

### ISSUE THREAD

**Issue by leitzler** [golang/go#35035]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.13
</pre>

### Does this issue reproduce with the latest release?
N/A.
I'm running the tools `master`-branch, i.e. [ed542cd](https://github.com/golang/tools/tree/ed542cd5b28ad1b474f8ff7ca112cad2c3ac2dc8)

### What did you do?
In a medium sized project I moved a file from one package to another before `gopls` was running, so that I had a package that contained several go files where one of them had an incorrect `package ...`-declaration at the top.

Then I opened the file in vim (`govim`) and renamed the package, effectively to another non-existing package name (since the change triggeded a `didChange` before I had completed my typing).

That resulted in a panic in gopls:
<pre>
panic: assignment to entry in nil map

goroutine 7172 [running]:
golang.org/x/tools/go/packages.processGolistOverlay(0xc00630f088, 0xc00b78d5b0, 0xc00b78d5c8, 0xc01e0fb810, 0x1, 0x1, 0xc0006b75c8, 0x0, 0x0, 0xbb1e80, ...)
	/home/leitzler/go/pkg/mod/golang.org/x/tools@v0.0.0-20191018212557-ed542cd5b28a/go/packages/golist_overlay.go:142 +0xb0d
golang.org/x/tools/go/packages.goListDriver(0xc00630f088, 0xc01e0fb7c0, 0x1, 0x1, 0x8, 0x10, 0xc00630f080)
	/home/leitzler/go/pkg/mod/golang.org/x/tools@v0.0.0-20191018212557-ed542cd5b28a/go/packages/golist.go:208 +0x57a
golang.org/x/tools/go/packages.defaultDriver(0xc00630f088, 0xc01e0fb7c0, 0x1, 0x1, 0xc01ddd88f0, 0xc0001c4d80, 0x4b)
	/home/leitzler/go/pkg/mod/golang.org/x/tools@v0.0.0-20191018212557-ed542cd5b28a/go/packages/packages.go:225 +0x68
golang.org/x/tools/go/packages.Load(0xc01e25e080, 0xc01e0fb7c0, 0x1, 0x1, 0x1, 0xc01dd85720, 0x4b, 0xda0020, 0xc01e21a270)
	/home/leitzler/go/pkg/mod/golang.org/x/tools@v0.0.0-20191018212557-ed542cd5b28a/go/packages/packages.go:210 +0x6f
golang.org/x/tools/internal/lsp/cache.(*snapshot).load(0xc01d4eb810, 0xda0020, 0xc01e21a270, 0xc000176230, 0x4d, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/leitzler/go/pkg/mod/golang.org/x/tools@v0.0.0-20191018212557-ed542cd5b28a/internal/lsp/cache/load.go:41 +0x2f3
golang.org/x/tools/internal/lsp/cache.(*snapshot).checkPackageHandles(0xc01d4eb810, 0xda0020, 0xc01e21a1b0, 0x7f0d87bec278, 0xc00027d2c0, 0x1152f9e4b, 0x127a620, 0xc01e21a1b0, 0xc01e21a180, 0xbf638ad35e2a00bf)
	/home/leitzler/go/pkg/mod/golang.org/x/tools@v0.0.0-20191018212557-ed542cd5b28a/internal/lsp/cache/gofile.go:42 +0x4b8
golang.org/x/tools/internal/lsp/cache.(*view).CheckPackageHandles(0xc00008ed80, 0xda0020, 0xc01e21a1b0, 0x7f0d87bec278, 0xc00027d2c0, 0x1, 0x1, 0xda0020, 0xc01e21a1b0, 0xc01e153a00, ...)
	/home/leitzler/go/pkg/mod/golang.org/x/tools@v0.0.0-20191018212557-ed542cd5b28a/internal/lsp/cache/gofile.go:20 +0x76
golang.org/x/tools/internal/lsp/source.Diagnostics(0xda0020, 0xc01e21a1b0, 0xdb0640, 0xc00008ed80, 0x7f0d87bec278, 0xc00027d2c0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/leitzler/go/pkg/mod/golang.org/x/tools@v0.0.0-20191018212557-ed542cd5b28a/internal/lsp/source/diagnostics.go:44 +0x1e8
golang.org/x/tools/internal/lsp.(*Server).diagnostics(0xc00027ea20, 0xdb0640, 0xc00008ed80, 0xc01dd85540, 0x4d, 0x0, 0x0)
	/home/leitzler/go/pkg/mod/golang.org/x/tools@v0.0.0-20191018212557-ed542cd5b28a/internal/lsp/diagnostics.go:30 +0x2e0
created by golang.org/x/tools/internal/lsp.(*Server).didChange
	/home/leitzler/go/pkg/mod/golang.org/x/tools@v0.0.0-20191018212557-ed542cd5b28a/internal/lsp/text_synchronization.go:82 +0x373
</pre>

**Comment by leitzler** [comment]
@gopherbot please add label Tools
