### ISSUE TITLE
runtime: parallel test failing on Plan 9

### ISSUE THREAD

**Issue by 0intro** [golang/go#35059]
Since CL [171824](https://golang.org/cl/171824), the parallel runtime test is failing on Plan 9.

```
##### GOMAXPROCS=2 runtime -cpu=1,2,4 -quick
fatal error: notetsleep not on g0

goroutine 63718 [running]:
runtime.throw(0x1bff5c, 0x14)
	/tmp/workdir-gnot/go/src/runtime/panic.go:774 +0x63 fp=0x108cdfa4 sp=0x108cdf90 pc=0x2c393
runtime.notetsleep(0x32cb9c, 0x540be400, 0x2, 0x1cbc01)
	/tmp/workdir-gnot/go/src/runtime/lock_sema.go:272 +0x7e fp=0x108cdfc4 sp=0x108cdfa4 pc=0x9c4e
runtime.netpoll(0x540be400, 0x2, 0x1fdd6c)
	/tmp/workdir-gnot/go/src/runtime/netpoll_stub.go:31 +0x77 fp=0x108cdfd8 sp=0x108cdfc4 pc=0x28697
runtime_test.TestNetpollBreak.func1(0x10903900)
	/tmp/workdir-gnot/go/src/runtime/proc_test.go:1001 +0x43 fp=0x108cdfe8 sp=0x108cdfd8 pc=0x159fe3
runtime.goexit()
	/tmp/workdir-gnot/go/src/runtime/asm_386.s:1337 +0x1 fp=0x108cdfec sp=0x108cdfe8 pc=0x566e1
created by runtime_test.TestNetpollBreak
	/tmp/workdir-gnot/go/src/runtime/proc_test.go:999 +0x87

goroutine 1 [chan receive]:
runtime.gopark(0x1cbcbc, 0x109038f0, 0x170e, 0x3)
	/tmp/workdir-gnot/go/src/runtime/proc.go:304 +0xd8 fp=0x10828d44 sp=0x10828d30 pc=0x2e2e8
runtime.goparkunlock(...)
	/tmp/workdir-gnot/go/src/runtime/proc.go:310
runtime.chanrecv(0x109038c0, 0x10828dcb, 0x10800001, 0xb53bc)
	/tmp/workdir-gnot/go/src/runtime/chan.go:562 +0x276 fp=0x10828d8c sp=0x10828d44 pc=0x4e66
runtime.chanrecv1(0x109038c0, 0x10828dcb)
	/tmp/workdir-gnot/go/src/runtime/chan.go:432 +0x1c fp=0x10828da0 sp=0x10828d8c pc=0x4bbc
testing.(*T).Run(0x10894be0, 0x1bdf14, 0x10, 0x1cc59c, 0x301)
	/tmp/workdir-gnot/go/src/testing/testing.go:961 +0x2cb fp=0x10828df4 sp=0x10828da0 pc=0xb53db
testing.runTests.func1(0x10895cc0)
	/tmp/workdir-gnot/go/src/testing/testing.go:1202 +0x59 fp=0x10828e18 sp=0x10828df4 pc=0xb8279
testing.tRunner(0x10895cc0, 0x10828eac)
	/tmp/workdir-gnot/go/src/testing/testing.go:909 +0x99 fp=0x10828e64 sp=0x10828e18 pc=0xb50a9
testing.runTests(0x10816050, 0x31a1e0, 0xff, 0xff, 0x0)
	/tmp/workdir-gnot/go/src/testing/testing.go:1200 +0x22c fp=0x10828ec0 sp=0x10828e64 pc=0xb646c
testing.(*M).Run(0x1081a0c0, 0x0)
	/tmp/workdir-gnot/go/src/testing/testing.go:1117 +0x13a fp=0x10828f4c sp=0x10828ec0 pc=0xb571a
runtime_test.TestMain(0x1081a0c0)
	/tmp/workdir-gnot/go/src/runtime/crash_test.go:28 +0x20 fp=0x10828f70 sp=0x10828f4c pc=0x112380
main.main()
	_testmain.go:1024 +0xff fp=0x10828fa0 sp=0x10828f70 pc=0x16745f
runtime.main()
	/tmp/workdir-gnot/go/src/runtime/proc.go:203 +0x266 fp=0x10828ff0 sp=0x10828fa0 pc=0x2dee6
runtime.goexit()
	/tmp/workdir-gnot/go/src/runtime/asm_386.s:1337 +0x1 fp=0x10828ff4 sp=0x10828ff0 pc=0x566e1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x1cbcbc, 0x31b500, 0x15cf1411, 0x1)
	/tmp/workdir-gnot/go/src/runtime/proc.go:304 +0xd8 fp=0x10829fd4 sp=0x10829fc0 pc=0x2e2e8
runtime.goparkunlock(...)
	/tmp/workdir-gnot/go/src/runtime/proc.go:310
runtime.forcegchelper()
	/tmp/workdir-gnot/go/src/runtime/proc.go:253 +0xb0 fp=0x10829ff0 sp=0x10829fd4 pc=0x2e160
runtime.goexit()
	/tmp/workdir-gnot/go/src/runtime/asm_386.s:1337 +0x1 fp=0x10829ff4 sp=0x10829ff0 pc=0x566e1
created by runtime.init.4
	/tmp/workdir-gnot/go/src/runtime/proc.go:242 +0x2a

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1cbcbc, 0x31b7b0, 0x140c, 0x1)
	/tmp/workdir-gnot/go/src/runtime/proc.go:304 +0xd8 fp=0x1082afd4 sp=0x1082afc0 pc=0x2e2e8
runtime.goparkunlock(...)
	/tmp/workdir-gnot/go/src/runtime/proc.go:310
runtime.bgsweep(0x1084e000)
	/tmp/workdir-gnot/go/src/runtime/mgcsweep.go:89 +0x117 fp=0x1082afe8 sp=0x1082afd4 pc=0x207b7
runtime.goexit()
	/tmp/workdir-gnot/go/src/runtime/asm_386.s:1337 +0x1 fp=0x1082afec sp=0x1082afe8 pc=0x566e1
created by runtime.gcenable
	/tmp/workdir-gnot/go/src/runtime/mgc.go:210 +0x4c

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x1cbcbc, 0x31b830, 0x140d, 0x1)
	/tmp/workdir-gnot/go/src/runtime/proc.go:304 +0xd8 fp=0x1082bf84 sp=0x1082bf70 pc=0x2e2e8
runtime.goparkunlock(...)
	/tmp/workdir-gnot/go/src/runtime/proc.go:310
runtime.bgscavenge(0x1084e000)
	/tmp/workdir-gnot/go/src/runtime/mgcscavenge.go:374 +0x43d fp=0x1082bfe8 sp=0x1082bf84 pc=0x2019d
runtime.goexit()
	/tmp/workdir-gnot/go/src/runtime/asm_386.s:1337 +0x1 fp=0x1082bfec sp=0x1082bfe8 pc=0x566e1
created by runtime.gcenable
	/tmp/workdir-gnot/go/src/runtime/mgc.go:211 +0x6a

goroutine 5 [finalizer wait]:
runtime.gopark(0x1cbcbc, 0x32cb6c, 0x10a91410, 0x1)
	/tmp/workdir-gnot/go/src/runtime/proc.go:304 +0xd8 fp=0x10824fa8 sp=0x10824f94 pc=0x2e2e8
runtime.goparkunlock(...)
	/tmp/workdir-gnot/go/src/runtime/proc.go:310
runtime.runfinq()
	/tmp/workdir-gnot/go/src/runtime/mfinal.go:175 +0x91 fp=0x10824ff0 sp=0x10824fa8 pc=0x15831
runtime.goexit()
	/tmp/workdir-gnot/go/src/runtime/asm_386.s:1337 +0x1 fp=0x10824ff4 sp=0x10824ff0 pc=0x566e1
created by runtime.createfing
	/tmp/workdir-gnot/go/src/runtime/mfinal.go:156 +0x3e

goroutine 6 [syscall]:
runtime.notetsleepg(0x31d5f4, 0x196fc132, 0x7f, 0x0)
	/tmp/workdir-gnot/go/src/runtime/lock_sema.go:286 +0x30 fp=0x10825f8c sp=0x10825f68 pc=0x9c90
runtime.timerproc(0x31d5e0)
	/tmp/workdir-gnot/go/src/runtime/time.go:306 +0x3f5 fp=0x10825fe8 sp=0x10825f8c pc=0x45cc5
runtime.goexit()
	/tmp/workdir-gnot/go/src/runtime/asm_386.s:1337 +0x1 fp=0x10825fec sp=0x10825fe8 pc=0x566e1
created by runtime.(*timersBucket).addtimerLocked
	/tmp/workdir-gnot/go/src/runtime/time.go:164 +0x117

goroutine 18 [timer goroutine (idle)]:
runtime.gopark(0x1cbcbc, 0x31d620, 0x1415, 0x1)
	/tmp/workdir-gnot/go/src/runtime/proc.go:304 +0xd8 fp=0x108a5f8c sp=0x108a5f78 pc=0x2e2e8
runtime.goparkunlock(...)
	/tmp/workdir-gnot/go/src/runtime/proc.go:310
runtime.timerproc(0x31d620)
	/tmp/workdir-gnot/go/src/runtime/time.go:298 +0x315 fp=0x108a5fe8 sp=0x108a5f8c pc=0x45be5
runtime.goexit()
	/tmp/workdir-gnot/go/src/runtime/asm_386.s:1337 +0x1 fp=0x108a5fec sp=0x108a5fe8 pc=0x566e1
created by runtime.(*timersBucket).addtimerLocked
	/tmp/workdir-gnot/go/src/runtime/time.go:164 +0x117

goroutine 219 [GC worker (idle)]:
runtime.gopark(0x1cbc00, 0x10a96020, 0xffff1418, 0x0)
	/tmp/workdir-gnot/go/src/runtime/proc.go:304 +0xd8 fp=0x108c8f8c sp=0x108c8f78 pc=0x2e2e8
runtime.gcBgMarkWorker(0x1081e000)
	/tmp/workdir-gnot/go/src/runtime/mgc.go:1855 +0xd6 fp=0x108c8fe8 sp=0x108c8f8c pc=0x19a06
runtime.goexit()
	/tmp/workdir-gnot/go/src/runtime/asm_386.s:1337 +0x1 fp=0x108c8fec sp=0x108c8fe8 pc=0x566e1
created by runtime.gcBgMarkStartWorkers
	/tmp/workdir-gnot/go/src/runtime/mgc.go:1803 +0x60

goroutine 63654 [chan receive]:
runtime.gopark(0x1cbcbc, 0x109640b0, 0x1081170e, 0x3)
	/tmp/workdir-gnot/go/src/runtime/proc.go:304 +0xd8 fp=0x10a0eeb8 sp=0x10a0eea4 pc=0x2e2e8
runtime.goparkunlock(...)
	/tmp/workdir-gnot/go/src/runtime/proc.go:310
runtime.chanrecv(0x10964080, 0x0, 0xb4e01, 0x1)
	/tmp/workdir-gnot/go/src/runtime/chan.go:562 +0x276 fp=0x10a0ef00 sp=0x10a0eeb8 pc=0x4e66
runtime.chanrecv1(0x10964080, 0x0)
	/tmp/workdir-gnot/go/src/runtime/chan.go:432 +0x1c fp=0x10a0ef14 sp=0x10a0ef00 pc=0x4bbc
testing.(*T).Parallel(0x10894dc0)
	/tmp/workdir-gnot/go/src/testing/testing.go:814 +0x192 fp=0x10a0ef80 sp=0x10a0ef14 pc=0xb4e72
runtime_test.TestMemmoveLarge0x180000(0x10894dc0)
	/tmp/workdir-gnot/go/src/runtime/memmove_test.go:102 +0x51 fp=0x10a0ef9c sp=0x10a0ef80 pc=0x133d01
testing.tRunner(0x10894dc0, 0x1cc57c)
	/tmp/workdir-gnot/go/src/testing/testing.go:909 +0x99 fp=0x10a0efe8 sp=0x10a0ef9c pc=0xb50a9
runtime.goexit()
	/tmp/workdir-gnot/go/src/runtime/asm_386.s:1337 +0x1 fp=0x10a0efec sp=0x10a0efe8 pc=0x566e1
created by testing.(*T).Run
	/tmp/workdir-gnot/go/src/testing/testing.go:960 +0x2ac

goroutine 114 [timer goroutine (idle)]:
runtime.gopark(0x1cbcbc, 0x31d660, 0x1415, 0x1)
	/tmp/workdir-gnot/go/src/runtime/proc.go:304 +0xd8 fp=0x10917f8c sp=0x10917f78 pc=0x2e2e8
runtime.goparkunlock(...)
	/tmp/workdir-gnot/go/src/runtime/proc.go:310
runtime.timerproc(0x31d660)
	/tmp/workdir-gnot/go/src/runtime/time.go:298 +0x315 fp=0x10917fe8 sp=0x10917f8c pc=0x45be5
runtime.goexit()
	/tmp/workdir-gnot/go/src/runtime/asm_386.s:1337 +0x1 fp=0x10917fec sp=0x10917fe8 pc=0x566e1
created by runtime.(*timersBucket).addtimerLocked
	/tmp/workdir-gnot/go/src/runtime/time.go:164 +0x117

goroutine 63661 [GC worker (idle)]:
runtime.gopark(0x1cbc00, 0x1081d428, 0xffff1418, 0x0)
	/tmp/workdir-gnot/go/src/runtime/proc.go:304 +0xd8 fp=0x10b60f8c sp=0x10b60f78 pc=0x2e2e8
runtime.gcBgMarkWorker(0x1081f300)
	/tmp/workdir-gnot/go/src/runtime/mgc.go:1855 +0xd6 fp=0x10b60fe8 sp=0x10b60f8c pc=0x19a06
runtime.goexit()
	/tmp/workdir-gnot/go/src/runtime/asm_386.s:1337 +0x1 fp=0x10b60fec sp=0x10b60fe8 pc=0x566e1
created by runtime.gcBgMarkStartWorkers
	/tmp/workdir-gnot/go/src/runtime/mgc.go:1803 +0x60

goroutine 63480 [chan receive]:
runtime.gopark(0x1cbcbc, 0x109640b0, 0x1081170e, 0x3)
	/tmp/workdir-gnot/go/src/runtime/proc.go:304 +0xd8 fp=0x10afbe8c sp=0x10afbe78 pc=0x2e2e8
runtime.goparkunlock(...)
	/tmp/workdir-gnot/go/src/runtime/proc.go:310
runtime.chanrecv(0x10964080, 0x0, 0xb4e01, 0x1)
	/tmp/workdir-gnot/go/src/runtime/chan.go:562 +0x276 fp=0x10afbed4 sp=0x10afbe8c pc=0x4e66
runtime.chanrecv1(0x10964080, 0x0)
	/tmp/workdir-gnot/go/src/runtime/chan.go:432 +0x1c fp=0x10afbee8 sp=0x10afbed4 pc=0x4bbc
testing.(*T).Parallel(0x10894000)
	/tmp/workdir-gnot/go/src/testing/testing.go:814 +0x192 fp=0x10afbf54 sp=0x10afbee8 pc=0xb4e72
runtime_test.TestVDSO(0x10894000)
	/tmp/workdir-gnot/go/src/runtime/crash_test.go:147 +0x24 fp=0x10afbf9c sp=0x10afbf54 pc=0x1134a4
testing.tRunner(0x10894000, 0x1cc848)
	/tmp/workdir-gnot/go/src/testing/testing.go:909 +0x99 fp=0x10afbfe8 sp=0x10afbf9c pc=0xb50a9
runtime.goexit()
	/tmp/workdir-gnot/go/src/runtime/asm_386.s:1337 +0x1 fp=0x10afbfec sp=0x10afbfe8 pc=0x566e1
created by testing.(*T).Run
	/tmp/workdir-gnot/go/src/testing/testing.go:960 +0x2ac

goroutine 63504 [chan receive]:
runtime.gopark(0x1cbcbc, 0x109640b0, 0x1081170e, 0x3)
	/tmp/workdir-gnot/go/src/runtime/proc.go:304 +0xd8 fp=0x1091ce8c sp=0x1091ce78 pc=0x2e2e8
runtime.goparkunlock(...)
	/tmp/workdir-gnot/go/src/runtime/proc.go:310
runtime.chanrecv(0x10964080, 0x0, 0xb4e01, 0x1)
	/tmp/workdir-gnot/go/src/runtime/chan.go:562 +0x276 fp=0x1091ced4 sp=0x1091ce8c pc=0x4e66
runtime.chanrecv1(0x10964080, 0x0)
	/tmp/workdir-gnot/go/src/runtime/chan.go:432 +0x1c fp=0x1091cee8 sp=0x1091ced4 pc=0x4bbc
testing.(*T).Parallel(0x10894f00)
	/tmp/workdir-gnot/go/src/testing/testing.go:814 +0x192 fp=0x1091cf54 sp=0x1091cee8 pc=0xb4e72
runtime_test.TestNetpollDeadlock(0x10894f00)
	/tmp/workdir-gnot/go/src/runtime/crash_test.go:438 +0x24 fp=0x1091cf9c sp=0x1091cf54 pc=0x115214
testing.tRunner(0x10894f00, 0x1cc5a0)
	/tmp/workdir-gnot/go/src/testing/testing.go:909 +0x99 fp=0x1091cfe8 sp=0x1091cf9c pc=0xb50a9
runtime.goexit()
	/tmp/workdir-gnot/go/src/runtime/asm_386.s:1337 +0x1 fp=0x1091cfec sp=0x1091cfe8 pc=0x566e1
created by testing.(*T).Run
	/tmp/workdir-gnot/go/src/testing/testing.go:960 +0x2ac

goroutine 22723 [timer goroutine (idle)]:
runtime.gopark(0x1cbcbc, 0x31d6a0, 0x1415, 0x1)
	/tmp/workdir-gnot/go/src/runtime/proc.go:304 +0xd8 fp=0x10a10f8c sp=0x10a10f78 pc=0x2e2e8
runtime.goparkunlock(...)
	/tmp/workdir-gnot/go/src/runtime/proc.go:310
runtime.timerproc(0x31d6a0)
	/tmp/workdir-gnot/go/src/runtime/time.go:298 +0x315 fp=0x10a10fe8 sp=0x10a10f8c pc=0x45be5
runtime.goexit()
	/tmp/workdir-gnot/go/src/runtime/asm_386.s:1337 +0x1 fp=0x10a10fec sp=0x10a10fe8 pc=0x566e1
created by runtime.(*timersBucket).addtimerLocked
	/tmp/workdir-gnot/go/src/runtime/time.go:164 +0x117

goroutine 63618 [chan receive]:
runtime.gopark(0x1cbcbc, 0x109640b0, 0x1081170e, 0x3)
	/tmp/workdir-gnot/go/src/runtime/proc.go:304 +0xd8 fp=0x1089be70 sp=0x1089be5c pc=0x2e2e8
runtime.goparkunlock(...)
	/tmp/workdir-gnot/go/src/runtime/proc.go:310
runtime.chanrecv(0x10964080, 0x0, 0xb4e01, 0x1)
	/tmp/workdir-gnot/go/src/runtime/chan.go:562 +0x276 fp=0x1089beb8 sp=0x1089be70 pc=0x4e66
runtime.chanrecv1(0x10964080, 0x0)
	/tmp/workdir-gnot/go/src/runtime/chan.go:432 +0x1c fp=0x1089becc sp=0x1089beb8 pc=0x4bbc
testing.(*T).Parallel(0x10894140)
	/tmp/workdir-gnot/go/src/testing/testing.go:814 +0x192 fp=0x1089bf38 sp=0x1089becc pc=0xb4e72
runtime_test.testConcurrentReadsAfterGrowth(0x10894140, 0x306301)
	/tmp/workdir-gnot/go/src/runtime/map_test.go:315 +0x24 fp=0x1089bf90 sp=0x1089bf38 pc=0x12d6f4
runtime_test.TestConcurrentReadsAfterGrowthReflect(0x10894140)
	/tmp/workdir-gnot/go/src/runtime/map_test.go:365 +0x25 fp=0x1089bf9c sp=0x1089bf90 pc=0x12d9a5
testing.tRunner(0x10894140, 0x1cc368)
	/tmp/workdir-gnot/go/src/testing/testing.go:909 +0x99 fp=0x1089bfe8 sp=0x1089bf9c pc=0xb50a9
runtime.goexit()
	/tmp/workdir-gnot/go/src/runtime/asm_386.s:1337 +0x1 fp=0x1089bfec sp=0x1089bfe8 pc=0x566e1
created by testing.(*T).Run
	/tmp/workdir-gnot/go/src/testing/testing.go:960 +0x2ac

goroutine 63655 [chan receive]:
runtime.gopark(0x1cbcbc, 0x109640b0, 0x1081170e, 0x3)
	/tmp/workdir-gnot/go/src/runtime/proc.go:304 +0xd8 fp=0x1091aeb8 sp=0x1091aea4 pc=0x2e2e8
runtime.goparkunlock(...)
	/tmp/workdir-gnot/go/src/runtime/proc.go:310
runtime.chanrecv(0x10964080, 0x0, 0xb4e01, 0x1)
	/tmp/workdir-gnot/go/src/runtime/chan.go:562 +0x276 fp=0x1091af00 sp=0x1091aeb8 pc=0x4e66
runtime.chanrecv1(0x10964080, 0x0)
	/tmp/workdir-gnot/go/src/runtime/chan.go:432 +0x1c fp=0x1091af14 sp=0x1091af00 pc=0x4bbc
testing.(*T).Parallel(0x10894e60)
	/tmp/workdir-gnot/go/src/testing/testing.go:814 +0x192 fp=0x1091af80 sp=0x1091af14 pc=0xb4e72
runtime_test.TestMemmoveOverlapLarge0x120000(0x10894e60)
	/tmp/workdir-gnot/go/src/runtime/memmove_test.go:114 +0x51 fp=0x1091af9c sp=0x1091af80 pc=0x133e21
testing.tRunner(0x10894e60, 0x1cc580)
	/tmp/workdir-gnot/go/src/testing/testing.go:909 +0x99 fp=0x1091afe8 sp=0x1091af9c pc=0xb50a9
runtime.goexit()
	/tmp/workdir-gnot/go/src/runtime/asm_386.s:1337 +0x1 fp=0x1091afec sp=0x1091afe8 pc=0x566e1
created by testing.(*T).Run
	/tmp/workdir-gnot/go/src/testing/testing.go:960 +0x2ac

goroutine 63617 [chan receive]:
runtime.gopark(0x1cbcbc, 0x109640b0, 0x1081170e, 0x3)
	/tmp/workdir-gnot/go/src/runtime/proc.go:304 +0xd8 fp=0x109d3e70 sp=0x109d3e5c pc=0x2e2e8
runtime.goparkunlock(...)
	/tmp/workdir-gnot/go/src/runtime/proc.go:310
runtime.chanrecv(0x10964080, 0x0, 0xb4e01, 0x1)
	/tmp/workdir-gnot/go/src/runtime/chan.go:562 +0x276 fp=0x109d3eb8 sp=0x109d3e70 pc=0x4e66
runtime.chanrecv1(0x10964080, 0x0)
	/tmp/workdir-gnot/go/src/runtime/chan.go:432 +0x1c fp=0x109d3ecc sp=0x109d3eb8 pc=0x4bbc
testing.(*T).Parallel(0x108940a0)
	/tmp/workdir-gnot/go/src/testing/testing.go:814 +0x192 fp=0x109d3f38 sp=0x109d3ecc pc=0xb4e72
runtime_test.testConcurrentReadsAfterGrowth(0x108940a0, 0x306300)
	/tmp/workdir-gnot/go/src/runtime/map_test.go:315 +0x24 fp=0x109d3f90 sp=0x109d3f38 pc=0x12d6f4
runtime_test.TestConcurrentReadsAfterGrowth(0x108940a0)
	/tmp/workdir-gnot/go/src/runtime/map_test.go:361 +0x25 fp=0x109d3f9c sp=0x109d3f90 pc=0x12d975
testing.tRunner(0x108940a0, 0x1cc36c)
	/tmp/workdir-gnot/go/src/testing/testing.go:909 +0x99 fp=0x109d3fe8 sp=0x109d3f9c pc=0xb50a9
runtime.goexit()
	/tmp/workdir-gnot/go/src/runtime/asm_386.s:1337 +0x1 fp=0x109d3fec sp=0x109d3fe8 pc=0x566e1
created by testing.(*T).Run
	/tmp/workdir-gnot/go/src/testing/testing.go:960 +0x2ac

goroutine 63505 [chan receive]:
runtime.gopark(0x1cbcbc, 0x109640b0, 0x1081170e, 0x3)
	/tmp/workdir-gnot/go/src/runtime/proc.go:304 +0xd8 fp=0x10ae2e40 sp=0x10ae2e2c pc=0x2e2e8
runtime.goparkunlock(...)
	/tmp/workdir-gnot/go/src/runtime/proc.go:310
runtime.chanrecv(0x10964080, 0x0, 0xb4e01, 0x1)
	/tmp/workdir-gnot/go/src/runtime/chan.go:562 +0x276 fp=0x10ae2e88 sp=0x10ae2e40 pc=0x4e66
runtime.chanrecv1(0x10964080, 0x0)
	/tmp/workdir-gnot/go/src/runtime/chan.go:432 +0x1c fp=0x10ae2e9c sp=0x10ae2e88 pc=0x4bbc
testing.(*T).Parallel(0x10894fa0)
	/tmp/workdir-gnot/go/src/testing/testing.go:814 +0x192 fp=0x10ae2f08 sp=0x10ae2e9c pc=0xb4e72
runtime_test.TestPanicTraceback(0x10894fa0)
	/tmp/workdir-gnot/go/src/runtime/crash_test.go:447 +0x2e fp=0x10ae2f9c sp=0x10ae2f08 pc=0x1153ce
testing.tRunner(0x10894fa0, 0x1cc624)
	/tmp/workdir-gnot/go/src/testing/testing.go:909 +0x99 fp=0x10ae2fe8 sp=0x10ae2f9c pc=0xb50a9
runtime.goexit()
	/tmp/workdir-gnot/go/src/runtime/asm_386.s:1337 +0x1 fp=0x10ae2fec sp=0x10ae2fe8 pc=0x566e1
created by testing.(*T).Run
	/tmp/workdir-gnot/go/src/testing/testing.go:960 +0x2ac

goroutine 63717 [runnable]:
runtime.netpollBreak()
	/tmp/workdir-gnot/go/src/runtime/netpoll_stub.go:17 +0x54 fp=0x10d94f5c sp=0x10d94f58 pc=0x28614
runtime_test.TestNetpollBreak(0x10894be0)
	/tmp/workdir-gnot/go/src/runtime/proc_test.go:1011 +0xb6 fp=0x10d94f9c sp=0x10d94f5c pc=0x13a5f6
testing.tRunner(0x10894be0, 0x1cc59c)
	/tmp/workdir-gnot/go/src/testing/testing.go:909 +0x99 fp=0x10d94fe8 sp=0x10d94f9c pc=0xb50a9
runtime.goexit()
	/tmp/workdir-gnot/go/src/runtime/asm_386.s:1337 +0x1 fp=0x10d94fec sp=0x10d94fe8 pc=0x566e1
created by testing.(*T).Run
	/tmp/workdir-gnot/go/src/testing/testing.go:960 +0x2ac
FAIL	runtime	54.183s
FAIL
```

See https://build.golang.org/log/b78b7f8c6c0a6c37c7f33e1e8e31a7f89c7fe0ac

@ianlancetaylor

**Comment by 0intro** [comment]
I've just noticed issue #35053.

**Comment by bradfitz** [comment]
Closing as dup.
