### ISSUE TITLE
tools/internal/lsp: panic in staticcheck during package rename

### ISSUE THREAD

**Issue by leitzler** [golang/go#35156]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version 1.13.3 linux/amd

golang.org/x/tools@v0.0.0-20191025023517-2077df36852e
</pre>

### What did you do?
In a medium sized project I moved files from one package to another before `gopls` was running, so that I had a package that contained several go files where some of them had incorrect `package ...`-declaration at the top.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x792b0a]

goroutine 7784 [running]:
honnef.co/go/tools/ssa.memberFromObject(0xc010fa6c60, 0x0, 0x0, 0xd99c60, 0xc00fb98c60)
   /home/leitzler/go/pkg/mod/honnef.co/go/tools@v0.0.1-2019.2.3/ssa/create.go:50 +0x3a
honnef.co/go/tools/ssa.membersFromDecl(0xc010fa6c60, 0xda3bc0, 0xc00fb98c60)
   /home/leitzler/go/pkg/mod/honnef.co/go/tools@v0.0.1-2019.2.3/ssa/create.go:150 +0x4d2
honnef.co/go/tools/ssa.(*Program).CreatePackage(0xc00e172dc0, 0xc004d4b8b0, 0xc0112a08e0, 0x3, 0x4, 0xc004c8b220, 0xb84000, 0xc0002ccc08)
   /home/leitzler/go/pkg/mod/honnef.co/go/tools@v0.0.1-2019.2.3/ssa/create.go:191 +0x257
honnef.co/go/tools/internal/passes/buildssa.run(0xc00e172d20, 0xc01128cae0, 0x3, 0x4, 0x0)
   /home/leitzler/go/pkg/mod/honnef.co/go/tools@v0.0.1-2019.2.3/internal/passes/buildssa/buildssa.go:69 +0x266
golang.org/x/tools/internal/lsp/cache.runAnalysis(0xda5fc0, 0xc011265a00, 0xc00027d100, 0xc0121a3770, 0xc00dd65748, 0x4704d4, 0xc0204694a8, 0xffffffffffffffff, 0xc00dd657c0, 0xa8ea0c, ...)
   /home/leitzler/go/pkg/mod/golang.org/x/tools@v0.0.0-20191025023517-2077df36852e/internal/lsp/cache/analysis.go:246 +0x5e0
golang.org/x/tools/internal/lsp/cache.(*snapshot).actionHandle.func1(0xda5fc0, 0xc011265a00, 0xcb7c28, 0xc0011f81f0)
   /home/leitzler/go/pkg/mod/golang.org/x/tools@v0.0.0-20191025023517-2077df36852e/internal/lsp/cache/analysis.go:126 +0x8d
golang.org/x/tools/internal/memoize.(*Handle).run.func1(0xc0121a37c0, 0xda5fc0, 0xc011265a00)
   /home/leitzler/go/pkg/mod/golang.org/x/tools@v0.0.0-20191025023517-2077df36852e/internal/memoize/memoize.go:183 +0x3e
created by golang.org/x/tools/internal/memoize.(*Handle).run
   /home/leitzler/go/pkg/mod/golang.org/x/tools@v0.0.0-20191025023517-2077df36852e/internal/memoize/memoize.go:180 +0xfd
```

**Comment by leitzler** [comment]
@gopherbot please add label Tools

**Comment by leitzler** [comment]
I think this is obsolete by far now and I haven't seen the issue again, closing.
