### ISSUE TITLE
cmd/compile: 0xb01dfacedebac1e on darwin-amd64-race

### ISSUE THREAD

**Issue by bcmills** [golang/go#35187]
From the `darwin-amd64-race` builder (https://build.golang.org/log/f00cd6a95816b1b61cff0ee829933f491b521707):
```
# cmd/compile/internal/ssa
unexpected fault address 0xb01dfacedebac1e
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x14d95a6]

goroutine 21 [running]:
runtime.throw(0x167fb98, 0x5)
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/runtime/panic.go:617 +0x72 fp=0xc018fb9110 sp=0xc018fb90e0 pc=0x102b972
runtime.sigpanic()
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/runtime/signal_unix.go:397 +0x401 fp=0xc018fb9140 sp=0xc018fb9110 pc=0x10408f1
bootstrap/cmd/compile/internal/gc.(*Mpint).Int64(0x100c0040daea0, 0x1666aa0)
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/internal/gc/mpint.go:269 +0x26 fp=0xc018fb9178 sp=0xc018fb9140 pc=0x14d95a6
bootstrap/cmd/compile/internal/gc.(*state).expr(0xc0320178c0, 0xc001f95100, 0x0)
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/internal/gc/ssa.go:2015 +0xa54 fp=0xc018fb9550 sp=0xc018fb9178 pc=0x1520bc4
bootstrap/cmd/compile/internal/gc.(*state).addr(0xc0320178c0, 0xc00b502200, 0xc032017800, 0x0)
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/internal/gc/ssa.go:4598 +0xaa1 fp=0xc018fb9600 sp=0xc018fb9550 pc=0x1534911
bootstrap/cmd/compile/internal/gc.(*state).expr(0xc0320178c0, 0xc00b502200, 0x0)
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/internal/gc/ssa.go:2588 +0x5505 fp=0xc018fb99d8 sp=0xc018fb9600 pc=0x1525675
bootstrap/cmd/compile/internal/gc.(*state).stmt(0xc0320178c0, 0xc00b502080)
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/internal/gc/ssa.go:1239 +0x194 fp=0xc018fb9b88 sp=0xc018fb99d8 pc=0x151d684
bootstrap/cmd/compile/internal/gc.(*state).stmtList(0xc0320178c0, 0xc004023460)
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/internal/gc/ssa.go:1018 +0x5f fp=0xc018fb9bd0 sp=0xc018fb9b88 pc=0x151d4bf
bootstrap/cmd/compile/internal/gc.(*state).stmt(0xc0320178c0, 0xc00b4fe700)
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/internal/gc/ssa.go:1394 +0x16a2 fp=0xc018fb9d80 sp=0xc018fb9bd0 pc=0x151eb92
bootstrap/cmd/compile/internal/gc.(*state).stmtList(0xc0320178c0, 0xc004023e40)
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/internal/gc/ssa.go:1018 +0x5f fp=0xc018fb9dc8 sp=0xc018fb9d80 pc=0x151d4bf
bootstrap/cmd/compile/internal/gc.buildssa(0xc00b4a8840, 0x2, 0x0)
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/internal/gc/ssa.go:426 +0xb26 fp=0xc018fb9f08 sp=0xc018fb9dc8 pc=0x15197d6
bootstrap/cmd/compile/internal/gc.compileSSA(0xc00b4a8840, 0x2)
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/internal/gc/pgen.go:298 +0x4d fp=0xc018fb9f98 sp=0xc018fb9f08 pc=0x14f0edd
bootstrap/cmd/compile/internal/gc.compileFunctions.func2(0xc0147ee300, 0xc00391ee10, 0x2)
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/internal/gc/pgen.go:363 +0x49 fp=0xc018fb9fc8 sp=0xc018fb9f98 pc=0x158bc39
runtime.goexit()
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc018fb9fd0 sp=0xc018fb9fc8 pc=0x1059891
created by bootstrap/cmd/compile/internal/gc.compileFunctions
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/internal/gc/pgen.go:361 +0x128

goroutine 1 [chan send]:
bootstrap/cmd/compile/internal/gc.compileFunctions()
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/internal/gc/pgen.go:369 +0x17c
bootstrap/cmd/compile/internal/gc.Main(0x16a6c70)
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/internal/gc/main.go:709 +0x214e
main.main()
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/main.go:50 +0x93

goroutine 22 [runnable]:
bootstrap/cmd/compile/internal/ssa.(*biasedSparseMap).cap(0xc010446100, 0x2534)
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/internal/ssa/biasedsparsemap.go:31 +0x6d
bootstrap/cmd/compile/internal/ssa.(*biasedSparseMap).get(0xc010446100, 0xb2, 0xc010446100)
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/internal/ssa/biasedsparsemap.go:69 +0x45
bootstrap/cmd/compile/internal/ssa.(*xposmap).get(0xc000c0d160, 0xb20b100002534, 0xc0ffffffff)
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/internal/ssa/xposmap.go:77 +0x68
bootstrap/cmd/compile/internal/ssa.deadcode(0xc031708c60)
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/internal/ssa/deadcode.go:272 +0x714
bootstrap/cmd/compile/internal/ssa.Compile(0xc031708c60)
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/internal/ssa/compile.go:92 +0x8cd
bootstrap/cmd/compile/internal/gc.buildssa(0xc00b4a8160, 0x3, 0x0)
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/internal/gc/ssa.go:444 +0xbc5
bootstrap/cmd/compile/internal/gc.compileSSA(0xc00b4a8160, 0x3)
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/internal/gc/pgen.go:298 +0x4d
bootstrap/cmd/compile/internal/gc.compileFunctions.func2(0xc0147ee300, 0xc00391ee10, 0x3)
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/internal/gc/pgen.go:363 +0x49
created by bootstrap/cmd/compile/internal/gc.compileFunctions
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/internal/gc/pgen.go:361 +0x128

goroutine 19 [runnable]:
bootstrap/cmd/compile/internal/gc.(*state).startBlock(0xc03308a6c0, 0xc01149ac50)
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/internal/gc/ssa.go:681 +0x15e
bootstrap/cmd/compile/internal/gc.(*state).stmt(0xc03308a6c0, 0xc0074a5500)
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/internal/gc/ssa.go:1296 +0x12c9
bootstrap/cmd/compile/internal/gc.(*state).stmtList(0xc03308a6c0, 0xc003884060)
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/internal/gc/ssa.go:1018 +0x5f
bootstrap/cmd/compile/internal/gc.(*state).stmt(0xc03308a6c0, 0xc0074a5080)
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/internal/gc/ssa.go:1394 +0x16a2
bootstrap/cmd/compile/internal/gc.(*state).stmtList(0xc03308a6c0, 0xc0038840a0)
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/internal/gc/ssa.go:1018 +0x5f
bootstrap/cmd/compile/internal/gc.buildssa(0xc00745ef20, 0x0, 0x0)
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/internal/gc/ssa.go:426 +0xb26
bootstrap/cmd/compile/internal/gc.compileSSA(0xc00745ef20, 0x0)
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/internal/gc/pgen.go:298 +0x4d
bootstrap/cmd/compile/internal/gc.compileFunctions.func2(0xc0147ee300, 0xc00391ee10, 0x0)
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/internal/gc/pgen.go:363 +0x49
created by bootstrap/cmd/compile/internal/gc.compileFunctions
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/internal/gc/pgen.go:361 +0x128

goroutine 20 [runnable]:
bootstrap/cmd/internal/obj/x86.(*AsmBuf).asmins(0xc02892dd48, 0xc0002ca160, 0xc011c1c2a0, 0xc000177838)
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/internal/obj/x86/asm6.go:5131 +0x460
bootstrap/cmd/internal/obj/x86.span6(0xc0002ca160, 0xc011c1c2a0, 0xc01045b860)
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/internal/obj/x86/asm6.go:1942 +0x39c
bootstrap/cmd/internal/obj.Flushplist(0xc0002ca160, 0xc02892dee0, 0xc01045b860, 0x7ffeefbfd2a2, 0x18)
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/internal/obj/plist.go:107 +0x6ad
bootstrap/cmd/compile/internal/gc.(*Progs).Flush(0xc025e9a310)
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/internal/gc/gsubr.go:93 +0xbc
bootstrap/cmd/compile/internal/gc.compileSSA(0xc00b40fb80, 0x1)
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/internal/gc/pgen.go:323 +0x402
bootstrap/cmd/compile/internal/gc.compileFunctions.func2(0xc0147ee300, 0xc00391ee10, 0x1)
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/internal/gc/pgen.go:363 +0x49
created by bootstrap/cmd/compile/internal/gc.compileFunctions
	/private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/cmd/compile/internal/gc/pgen.go:361 +0x128
go tool dist: FAILED: /private/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/pkg/tool/darwin_amd64/go_bootstrap install -gcflags=all= -ldflags=all= -i cmd/asm cmd/cgo cmd/compile cmd/link: exit status 2
```

CC @randall77 @rasky @aclements

**Comment by randall77** [comment]
Strange. There appears to be a high bit set in a pointer that shouldn't be:
```
bootstrap/cmd/compile/internal/gc.(*Mpint).Int64(0x100c0040daea0, 0x1666aa0)
```
That should probably be `0xc0040daea0`, not `0x100c0040daea0`.  Dereferencing that bad pointer is what caused the crash.

There isn't really enough information here to extract a cause. Could be a cosmic ray, could be a GC/liveness map bug.

I'll try some GOGC=1 runs on my mac to see if I can get a reproducer.

**Comment by randall77** [comment]
I can't reproduce even with GOGC=1.

This doesn't have anything to do with the race detector, it's not enabled yet during the build.

In any case, this is the bootstrap compiler failing. The bootstrap compiler is from 1.12 (not sure which patch).

Looks likely it is just a machine failure. I'm going to close unless we see another instance.
