### ISSUE TITLE
runtime: TestCgoLockOSThreadExit failures on solaris-amd64-oraclerel

### ISSUE THREAD

**Issue by bcmills** [golang/go#35288]
Two instances of an apparent regression on `solaris-amd64-oraclerel`:
https://build.golang.org/log/994848e126b84203d2e9cf370cc1422391b2f2c8
https://build.golang.org/log/6b98efebf1b18f405596509eabf42a557cad2bb6

```
--- FAIL: TestCgoLockOSThreadExit (85.74s)
    crash_test.go:95: testprogcgo LockOSThreadAlt exit status: exit status 2
    proc_test.go:900: want "OK\n", got "SIGQUIT: quit (ASCII FS)\nPC=0x546c80 m=0 sigcode=0\n\ngoroutine 1 [running, locked to thread]:\nruntime.gopark(0x4663d8, 0xc0000d0120, 0xc0000f1313, 0x1)\n\t/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/runtime/proc.go:305 +0xe0 fp=0xc00006ee58 sp=0xc00006ee38 pc=0x546c80\ntime.Sleep(0xf4240)\n\t/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/runtime/time.go:247 +0xba fp=0xc00006ee98 sp=0xc00006ee58 pc=0x56343a\nmain.LockOSThreadAlt()\n\t/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/runtime/testdata/testprogcgo/lockosthread.go:97 +0xd2 fp=0xc00006eee0 sp=0xc00006ee98 pc=0x5da7b2\nmain.main()\n\t/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/runtime/testdata/testprogcgo/main.go:34 +0x1cc fp=0xc00006ef88 sp=0xc00006eee0 pc=0x5d785c\nruntime.main()\n\t/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/runtime/proc.go:203 +0x212 fp=0xc00006efe0 sp=0xc00006ef88 pc=0x546892\nruntime.goexit()\n\t/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/runtime/asm_amd64.s:1375 +0x1 fp=0xc00006efe8 sp=0xc00006efe0 pc=0x573961\n\nrax    0x0\nrbx    0x546c80\nrcx    0x7fffbf6c2a40\nrdx    0x0\nrdi    0x0\nrsi    0x0\nrbp    0xc00006ee48\nrsp    0xc00006ee38\nr8     0x1\nr9     0x0\nr10    0x0\nr11    0x11\nr12    0xffffffffffffffff\nr13    0x3\nr14    0x2\nr15    0x400\nrip    0x546c80\nrflags 0x10216\ncs     0x53\nfs     0x0\ngs     0x0\n"
FAIL
FAIL	runtime	114.551s
```

The root cause may be related to #35274.

CC @aclements @ianlancetaylor

**Comment by ianlancetaylor** [comment]
Could be #35294.
