### ISSUE TITLE
runtime: "index out of range" in netpoll on aix-ppc64

### ISSUE THREAD

**Issue by bcmills** [golang/go#35282]
`aix-ppc64` (https://build.golang.org/log/03aa1c6a639c7b8f81c703178ff6ea2ca930e53a):

```
fatal error: index out of range

runtime stack:
runtime.throw(0x1002672cc, 0x12)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/runtime/panic.go:1045 +0x68
runtime.panicCheck1(0x10002f480, 0x1002672cc, 0x12)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/runtime/panic.go:34 +0xdc
runtime.goPanicIndex(0x0, 0x0)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/runtime/panic.go:87 +0x40
runtime.netpoll(0x1c2752, 0x10001000002cf00)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/runtime/netpoll_aix.go:164 +0x3f0
runtime.findrunnable(0xa0001000002aa00, 0x0)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/runtime/proc.go:2347 +0x790
runtime.schedule()
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/runtime/proc.go:2542 +0x3e0
runtime.park_m(0xa00010000000c00)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/runtime/proc.go:2682 +0xc8
runtime.mcall(0xa00010000000c00)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/runtime/asm_ppc64x.s:202 +0x58

goroutine 1 [runnable]:
runtime.netpollGenericInit(...)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/runtime/netpoll.go:108
internal/poll.runtime_pollServerInit()
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/runtime/netpoll.go:103 +0x74
sync.(*Once).doSlow(0x110063ad0, 0x10027ba78)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/sync/once.go:66 +0x148
sync.(*Once).Do(...)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/sync/once.go:57
internal/poll.(*pollDesc).init(0xa000100006dc078, 0xa000100006dc060, 0x100000000000003, 0xa000100006dc060)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/internal/poll/fd_poll_runtime.go:38 +0x158
internal/poll.(*FD).Init(0xa000100006dc060, 0x100260e56, 0x4, 0x100000000000000, 0x0, 0x100000000000d98)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/internal/poll/fd_unix.go:63 +0x94
os.newFile(0x3, 0xffffffffffff8c0, 0x50, 0x1, 0x3)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/os/file_unix.go:151 +0xf0
os.openFileNolog(0xffffffffffff8c0, 0x50, 0x302, 0x1b6000141e0, 0x1000ef034, 0x7000000000000002, 0x1002651bb)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/os/file_unix.go:222 +0xe8
os.OpenFile(0xffffffffffff8c0, 0x50, 0x302, 0x1b600000000, 0x1, 0x1, 0x40)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/os/file.go:303 +0x58
os.Create(...)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/os/file.go:292
testing.(*M).before(0xa0001000000a080)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/testing/testing.go:1279 +0x1e4
testing.(*M).Run(0xa0001000000a080, 0x0)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/testing/testing.go:1129 +0xc0
main.main()
	_testmain.go:520 +0x130
FAIL	math/big	0.099s
```

CC @ianlancetaylor @aclements

**Comment by ianlancetaylor** [comment]
CC @Helflym
