### ISSUE TITLE
runtime: TestCrashDumpsAllThreads flakes

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#35356]
https://storage.googleapis.com/go-build-log/e4992e62/linux-amd64_2c1df239.log

```
--- FAIL: TestCrashDumpsAllThreads (0.98s)
    crash_unix_test.go:152: found 3 instances of main.loop; expected 4
```

[2019-11-04T18:53:43-210e367/darwin-amd64-race](https://build.golang.org/log/05f53140b89337ef848d51e83ffb8e19aabd27e0)
[2019-11-04T05:27:25-fb29e22/linux-386](https://build.golang.org/log/e0f56ae02480d020a086395353f1da024e9aea9d)
[2019-11-04T05:27:25-fb29e22/netbsd-amd64-8_0](https://build.golang.org/log/1b94d86effe47655bb0068e7a614cbb618c10449)
[2019-11-03T05:01:00-4497d7e/darwin-amd64-10_12](https://build.golang.org/log/085f522dbb46a856dd8dd529933fcf9c374ed5de)
[2019-11-03T01:44:46-d2c039f/linux-386-clang](https://build.golang.org/log/27d4e01726d366820369e2c02c236352ebdea1ff)
[2019-11-02T21:51:23-7955ece/linux-amd64-sid](https://build.golang.org/log/f677332cb89670e23ab4d845b0a1029a1bf20f2e)
[2019-11-01T16:05:22-8d45e61/freebsd-386-11_2](https://build.golang.org/log/cfc36ddb12c81898f6c0c04aa5cbaefe9fa463ac)

Maybe yet another flake fixed by https://go-review.googlesource.com/c/go/+/204800?

**Comment by bcmills** [comment]
Still flaky after CL 204800.

`linux-386-clang`: https://build.golang.org/log/4982801962e94bcbe3dd7a01114769650eaab38b

CC @aclements @mknyszek @cherrymui @ianlancetaylor

**Comment by ianlancetaylor** [comment]
This has been happening sporadically for some time, but it seems to have definitely picked up recently.

[2019-11-01T16:05:22-8d45e61/freebsd-386-11_2](https://build.golang.org/log/cfc36ddb12c81898f6c0c04aa5cbaefe9fa463ac)
[2019-11-02T21:51:23-7955ece/linux-amd64-sid](https://build.golang.org/log/f677332cb89670e23ab4d845b0a1029a1bf20f2e)
[2019-11-03T01:44:46-d2c039f/linux-386-clang](https://build.golang.org/log/27d4e01726d366820369e2c02c236352ebdea1ff)
[2019-11-03T05:01:00-4497d7e/darwin-amd64-10_12](https://build.golang.org/log/085f522dbb46a856dd8dd529933fcf9c374ed5de)
[2019-11-04T05:27:25-fb29e22/linux-386](https://build.golang.org/log/e0f56ae02480d020a086395353f1da024e9aea9d)
[2019-11-04T05:27:25-fb29e22/netbsd-amd64-8_0](https://build.golang.org/log/1b94d86effe47655bb0068e7a614cbb618c10449)
[2019-11-04T18:53:43-210e367/darwin-amd64-race](https://build.golang.org/log/05f53140b89337ef848d51e83ffb8e19aabd27e0)
[2019-11-04T22:52:25-74af7fc/linux-amd64-race](https://build.golang.org/log/23ad7cb9dd9b554f990cc6dc75a458097f3a20c8)
[2019-11-04T23:41:34-383b447/darwin-amd64-race](https://build.golang.org/log/2b01adb66c7b244de0ac81f773a8051fef9ad251)
[2019-11-05T00:17:34-04e80fb/linux-386-387](https://build.golang.org/log/5ebbe07957e823d828c43e9c5005a103a4a575ca)
[2019-11-05T01:01:31-376c4ce/freebsd-386-11_2](https://build.golang.org/log/1d8cd5f0e0aeae267ee8c51a34756fdfdab133d5)
[2019-11-05T02:49:48-2ff746d/linux-arm64-packet](https://build.golang.org/log/2db6c2d1ec52ccb4cd2bec2a5662f35b44e161cc)
[2019-11-05T03:42:00-11db7e4/linux-arm](https://build.golang.org/log/e9b8afcf96f7b50613ecccb76c2c82fd5e104409)
[2019-11-05T18:37:06-c3cef0b/freebsd-amd64-race](https://build.golang.org/log/12f3f638f39f31937ccdbddf0f49ea4a7bfe72cb)
[2019-11-05T18:58:41-f07cbc7/freebsd-amd64-race](https://build.golang.org/log/f6cde59d28371b02202a97f813f0def876a111de)
[2019-11-05T20:21:34-552987f/linux-386-longtest](https://build.golang.org/log/e6e36c79bac97b1cf008c08fe5e240384b09c9ad)
[2019-11-06T02:49:10-de70de6/freebsd-amd64-race](https://build.golang.org/log/1cbe730456e5b73d881623c456d05c587b7d774e)
[2019-11-06T09:09:59-0c5d545/linux-amd64-jessie](https://build.golang.org/log/d02bfe5752b72bd3872f9b484ebd7e39f0c709a5)
[2019-11-06T14:33:39-f891b7c/linux-386-clang](https://build.golang.org/log/57e83e9992e919133c7fb8e2ffff71516b47c037)
[2019-11-06T16:17:30-a5936a4/linux-amd64-nocgo](https://build.golang.org/log/183ed18694bc47675f15480397b3d72b06118a9c)
[2019-11-06T17:03:51-a2b1dc8/freebsd-amd64-race](https://build.golang.org/log/a179ee943da9a0179e22df359f1cd26a7809ad07)
[2019-11-06T18:27:09-3c29796/linux-386-clang](https://build.golang.org/log/4982801962e94bcbe3dd7a01114769650eaab38b)

**Comment by ianlancetaylor** [comment]
My current guess is that this has changed due to signal preemption.  The test only works if each running M is hit with a `SIGQUIT` while it is running a tight loop.  The test is checking that the stack trace for each thread shows the loop.  If the thread is preempted when it receives the `SIGQUIT`, it will instead show a track trace in the runtime with the thread stopped at `gcstopm`.

**Comment by ianlancetaylor** [comment]
CC @aclements @cherrymui

**Comment by aclements** [comment]
In principle, non-cooperative preemption should make this test more robust,
since we should be able to get all the stacks even without
GOTRACEBACK=crash. That's obviously not quite working.

**Comment by cherrymui** [comment]
If the SIGQUIT lands right after asyncPreempt2 switches to the system stack, but before CASing the G status out of _Grunning, I guess this can result in `goroutine running on other thread; stack unavailable` on the G and also not being trace backed on the M (as it is running on its G0)? (But the failure stack traces don't look like this.)

**Comment by ianlancetaylor** [comment]
The test is expecting to see that theoretically unpreemptible loop appears the expected number of times in the stack trace.  But if the loop is preempted, then the stack trace of that M will show something else, not the loop.  So the test will fail.

Non-cooperative preemption will make real code more robust, but it doesn't make this specific test more robust.

@cherrymui It's normal to see `goroutine running on other thread` in the first set of stack traces.  The expectation of the test is that you will then see one more stack trace per thread.  The test expects those additional stack traces to fill in the references to the loop.  But if the M is preempted when the program dies, then we don't see a reference to the loop in its stack.

**Comment by cherrymui** [comment]
@ianlancetaylor when the goroutine is preempted, it will show something like
```
        goroutine 6 [runnable]:
        runtime.asyncPreempt2()
        	/workdir/go/src/runtime/preempt.go:289 +0x62 fp=0xc000030630 sp=0xc000030610 pc=0x42ba62
        runtime.asyncPreempt()
        	/workdir/go/src/runtime/preempt_amd64.s:45 +0xdb fp=0xc0000307b8 sp=0xc000030630 pc=0x4589fb
        main.loop(0x0, 0xc00005e060)
        	/workdir/tmp/go-build869718673/main.go:36 +0x2d fp=0xc0000307d0 sp=0xc0000307b8 pc=0x48e3cd
        runtime.goexit()
        	/workdir/go/src/runtime/asm_amd64.s:1375 +0x1 fp=0xc0000307d8 sp=0xc0000307d0 pc=0x4570d1
        created by main.main
        	/workdir/tmp/go-build869718673/main.go:17 +0xac
```

The test counts the number of "main.loop" appearances, so this is counted correctly. On that thread, the additional stack trace (what I meant by saying "being trace backed on the M") will show that M's G0 stack, which does not include main.loop.

**Comment by cherrymui** [comment]
So, I think,
- if the goroutine is not preempted, the first set of stack traces will have `goroutine running on other thread`, and the additional stack trace will show one with `main.loop`.
- if the goroutine is preempted, the first set of stack traces will show `main.loop` (by tracing back through runtime.asyncPreempt), and the additional stack trace will show its G0 stack, which does not include `main.loop`.

So either way, it should be counted as 1 appearance (except in the case that the SIGQUIT lands in the small window I mentioned in my previous comment).

**Comment by ianlancetaylor** [comment]
I think that what is happening when the test fails is that 1) the signal is sent; 2) the goroutine is reported as `goroutine running on other thread`; 3) the goroutine is preempted and the M enters `schedule`; 4) the M that was running the goroutine is signaled; 5) the M reports a stack trace up through `schedule`; 6) nothing reports `main.loop` because that goroutine was already reported in step 2 and the M is now doing something else.

**Comment by cherrymui** [comment]
@ianlancetaylor I thing you're right. This can result in a missing `main.loop`.

**Comment by bcmills** [comment]
Still flaky (with the same failure mode) after [CL 205720](https://golang.org/cl/205720), albeit with what seems to be a lower failure rate:
[2020-05-12T15:01:56-a0698a6/darwin-amd64-10_15](https://build.golang.org/log/340f23a20a20c3345d741b6643bf50abf5c6807f)
[2019-12-06T23:44:28-76d2f6c/freebsd-amd64-11_2](https://build.golang.org/log/8856651cce9e775126b3c67e066a32b3b5df4594)

**Comment by 4a6f656c** [comment]
Not sure if directly related, however this test currently fails 100% of the time on the openbsd/mips64 builder:

https://build.golang.org/log/b88cd54aa3ccb3e2bf03f5958dd593291803b00e

**Comment by bcmills** [comment]
[2020-12-07T02:31:33-e10c94a/freebsd-amd64-11_2](https://build.golang.org/log/c57644f4aa800d2ad11acd0771172d03681310b8)
[2020-10-26T14:50:38-532c199/dragonfly-amd64-5_8](https://build.golang.org/log/00926c5cb6e0f328b2eabc9668afc7eebc80faad)
[2020-10-01T15:16:43-89f687d/freebsd-386-12_0](https://build.golang.org/log/886fc46daf72e2c445d4be584ec8de0da0aef63d)

**Comment by cherrymui** [comment]
The runtime waits for 5 seconds for the SIGQUIT signal to bounce between all threads. All failure cases above seem to take longer than 5 seconds to finish, and it doesn't include all Ms. For those cases, I guess it is just that 5 seconds is not long enough to have the signal bounce between all threads (maybe the system is quite busy, because all.bash launches many processes?).

**Comment by odeke-em** [comment]
Still flaky, but shouldn’t hold up a release. Punting to Go1.17. Thank you everyone.

**Comment by ianlancetaylor** [comment]
[2021-04-16T21:50:38-9481789/freebsd-amd64-11_2](https://build.golang.org/log/4534e9ff8029af653686befd99572dea6ceb75b6)
[2021-04-06T23:39:42-972e883/linux-ppc64-buildlet](https://build.golang.org/log/3bb0e5390de7d13d531ddd84cc071212226f4f30)
[2021-03-08T19:07:25-7419a86/freebsd-arm64-dmgk](https://build.golang.org/log/df9f7ad1b123e32070da70b7661a73ba0a93dc5c)

**Comment by cherrymui** [comment]
I think my analysis above gives a possible reason. But I don't know what we want to do to fix. Do we want to increase the 5 seconds waiting time?

**Comment by ianlancetaylor** [comment]
Let's try dropping the `t.Parallel` so that there is hopefully less going on during this test.  I'll send you a CL that does that and also tries to fold the test into testprog.
