### ISSUE TITLE
x/mobile: tests for android application fail

### ISSUE THREAD

**Issue by champo** [golang/go#35403]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/juancivile/Library/Caches/go-build"
GOENV="/Users/juancivile/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/juancivile/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/t8/b_612wks48sc7dht74z1y8_m0000gn/T/go-build413151292=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Built an `aar` using `GO111MODULE=off gomobile bind -target=android -o libs/libwallet.aar github.com/muun/libwallet`. I then included the aar in an android gradle project. Running the app and triggering the gomobile code works perfectly. However, running the tests fails with the following stacktrace:
```
java.lang.NoClassDefFoundError: libwallet/HDPublicKey

	at io.muun.apollo.domain.LibwalletBridge.createAddressV3(LibwalletBridge.java:87)
	at io.muun.apollo.domain.action.AddressActions.getExternalMuunAddress(AddressActions.java:97)
	at io.muun.apollo.domain.action.AddressActions.getExternalAddress(AddressActions.java:55)
	at io.muun.apollo.domain.action.AddressActionsTest.getExternalAddress(AddressActionsTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:79)
	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:85)
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ClassNotFoundException: libwallet.HDPublicKey
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 32 more
```

After some research, I believe that the problem is gomobile produces libraries for android targets but it doesn't produce one for OS X. Since tests run in a regular java process, it fails to find a compatible shared library in the aar.

The aar is included in the gradle file like this:
```diff
--- a/android/apollo/build.gradle
+++ b/android/apollo/build.gradle
@@ -1,6 +1,9 @@
 repositories {
     google()
     maven { url 'https://maven.fabric.io/public' }  // Needed for crashlytics dependency
+    flatDir {
+        dirs "${project.projectDir}/libs"
+    }
 }

 apply plugin: 'com.android.library'
@@ -92,6 +95,7 @@ preBuild.dependsOn "libwallet"

 dependencies {
     api project(':common')
+    implementation files('libs/libwallet.aar')

     // Android support:
     api 'androidx.appcompat:appcompat:1.0.2'
```

### What did you expect to see?

Green tests

### What did you see instead?

Stacktrace above

**Comment by bcmills** [comment]
CC @steeve @hyangah

**Comment by ClementFr49** [comment]
Same issue with go 1.22.4 & gomobile@latest.
I'm building android aar with this cmd on macOS Version 14.5 : 

> gomobile bind -target android -androidapi 26 -o target/$(ArtifactName).aar -javapkg $(PackageNameAndroid) $(Packagetobuild)

The given aar contains jni : 

- x86
- x86_64
- arm64-v8a
- armeabi-v7a

I'm using the android test implementation jupiter junit 5.11.0 (*testImplementation("org.junit.jupiter:junit-jupiter:5.11.0*)

**Is there a fix or any another way of fixing the problem?**
