### ISSUE TITLE
cmd/link/internal/ld: TestDynSymShInfo failure on darwin-amd64-10_11 builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#35497]
```
#!watchflakes
post <- pkg == "cmd/link/internal/ld" && test == "TestDynSymShInfo" && `index out of range`
```

[2019-11-11T12:40:04-f07059d/darwin-amd64-10_11](https://build.golang.org/log/cc20f26a35ae6a2d9295873b36aa5395cf9dce87)

```
--- FAIL: TestDynSymShInfo (0.58s)
    elf_test.go:45: [/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/bin/go build -o /var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/tmp/go-build-issue33358069072635/issue33358 /var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/tmp/go-build-issue33358069072635/issue33358.go]: exit status 2:
        # command-line-arguments
        panic: runtime error: index out of range [824666141056] with length 39
        
        goroutine 1 [running]:
        cmd/internal/dwarf.HasChildren(...)
        	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/src/cmd/internal/dwarf/dwarf.go:1039
        cmd/link/internal/ld.reversetree(0xc001f2dfc0)
        	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/src/cmd/link/internal/ld/dwarf.go:320 +0xdd
        cmd/link/internal/ld.reversetree(0x1471db0)
        	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/src/cmd/link/internal/ld/dwarf.go:321 +0xb9
        cmd/link/internal/ld.dwarfGenerateDebugSyms(0xc000586000)
        	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/src/cmd/link/internal/ld/dwarf.go:1826 +0x34c
        cmd/link/internal/ld.(*Link).dodata(0xc000586000)
        	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/src/cmd/link/internal/ld/data.go:1765 +0x343e
        cmd/link/internal/ld.Main(0x14672e0, 0x10, 0x20, 0x1, 0x7, 0x10, 0x12a0282, 0x1b, 0x129c552, 0x14, ...)
        	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/src/cmd/link/internal/ld/main.go:248 +0xcb7
        main.main()
        	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/src/cmd/link/main.go:65 +0x1bc
FAIL
FAIL	cmd/link/internal/ld	4.921s
```

CC @thanm @cherrymui @jeremyfaller

**Comment by thanm** [comment]
Interesting; I'll take an initial look.

**Comment by bcmills** [comment]
That version of macOS seems pretty flaky overall, so don't sink too much time into it if you have better things to do.

(Mostly I just wanted to have this filed should it recur.)

**Comment by thanm** [comment]
Something is out of whack here -- when I try to reproduce with a gomote I get:

```
$ gomote run user-thanm-darwin-amd64-10_11-0 /bin/bash run-on-gomote.sh
=== RUN   TestDynSymShInfo
=== PAUSE TestDynSymShInfo
=== CONT  TestDynSymShInfo
    TestDynSymShInfo: elf_test.go:55: The system may not support ELF, skipped.
--- SKIP: TestDynSymShInfo (0.46s)
```

This is a little misleading -- it's not skipping the test entirely, in that it does build and link a small test program, but then once it figures out the resulting binary is not an ELF, it then invokes test.Skip.

The failure in https://build.golang.org/log/cc20f26a35ae6a2d9295873b36aa5395cf9dce87 happens
before that point, however.

With that said, I ran it a couple of hundred times and didn't see any failures to link or crashes... which makes me think there is some flaky behavior going on.

**Comment by thanm** [comment]
@bcmills agree, it is probably a flake.  Let's wait and see if it happens again...
