### ISSUE TITLE
proxy.golang.org outage

### ISSUE THREAD

**Issue by howardjohn** [golang/go#35516]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.13
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
amd64 linux
</pre></details>

### What did you do?

Tried to build various repos, like istio.io/istio, with `GOPROXY=https://proxy.golang.org`.

### What did you expect to see?

Build to succeed

### What did you see instead?

Various intermittent errors like:

```
go: cloud.google.com/go@v0.38.0: Get https://proxy.golang.org/cloud.google.com/go/@v/v0.38.0.mod: dial tcp: i/o timeout
```
```
go: contrib.go.opencensus.io/exporter/prometheus@v0.1.0: Get https://proxy.golang.org/contrib.go.opencensus.io/exporter/prometheus/@v/v0.1.0.mod: dial tcp: i/o timeout
```

And a bazel one:
```
Analyzing: target //src/envoy:envoy_tar (469 packages loaded, 32920 targets configured)
ERROR: An error occurred during the fetch of repository 'org_golang_x_tools':
   Traceback (most recent call last):
	File "/home/bootstrap/.cache/bazel/_bazel_root/45ae47b4a0e12d1e81c831ece04d820d/external/bazel_tools/tools/build_defs/repo/git.bzl", line 177
		_clone_or_update(ctx)
	File "/home/bootstrap/.cache/bazel/_bazel_root/45ae47b4a0e12d1e81c831ece04d820d/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
		git_repo(ctx, directory)
	File "/home/bootstrap/.cache/bazel/_bazel_root/45ae47b4a0e12d1e81c831ece04d820d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
		_update(ctx, git_repo)
	File "/home/bootstrap/.cache/bazel/_bazel_root/45ae47b4a0e12d1e81c831ece04d820d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 103, in _update
		fetch(ctx, git_repo)
	File "/home/bootstrap/.cache/bazel/_bazel_root/45ae47b4a0e12d1e81c831ece04d820d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 129, in fetch
		_git_maybe_shallow(ctx, <5 more arguments>)
	File "/home/bootstrap/.cache/bazel/_bazel_root/45ae47b4a0e12d1e81c831ece04d820d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 171, in _git_maybe_shallow
		_error(ctx.name, <2 more arguments>)
	File "/home/bootstrap/.cache/bazel/_bazel_root/45ae47b4a0e12d1e81c831ece04d820d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 181, in _error
		fail(<1 more arguments>)
```

There does not seem to be any sort of status page for the proxy to indicate issues either

**Comment by heschik** [comment]
The error `dial tcp: i/o timeout` indicates a problem in the network connection between your host and Google's edge servers, not anything specific to proxy.golang.org. We haven't had any other reports of this, so it might be worth investigating if there's a networking problem of some kind.

**Comment by howardjohn** [comment]
@heschik ah maybe its an internal GCP issue -- we are running this from GKE. I will look into it (and added `direct` as a fallback). Thanks!
