### ISSUE TITLE
os/exec: test fails with "runtime: netpoll: break fd ready for -2" on OpenBSD 6.2 builders

### ISSUE THREAD

**Issue by bcmills** [golang/go#35566]
[CL 206939](https://golang.org/cl/206939), a test-only change, introduced a regression on the OpenBSD 6.2 builders (https://build.golang.org/log/edea2d1e1ca4fabe71e3cf98868411e29cfb42cb):

```
fd 3 open at test start
fd 4 open at test start
fd 5 open at test start
runtime: netpoll: break fd ready for -2
fatal error: runtime: netpoll: break fd ready for something unexpected

runtime stack:
runtime.throw(0x83494b2, 0x39)
	/tmp/workdir/go/src/runtime/panic.go:1106 +0x64
runtime.netpoll(0x0, 0x0, 0xac)
	/tmp/workdir/go/src/runtime/netpoll_kqueue.go:140 +0x35d
runtime.sysmon()
	/tmp/workdir/go/src/runtime/proc.go:4526 +0x34e
runtime.mstart1()
	/tmp/workdir/go/src/runtime/proc.go:1133 +0x8f
runtime.mstart()
	/tmp/workdir/go/src/runtime/proc.go:1098 +0x4f

goroutine 1 [runnable]:
testing.(*M).before(0x8855a40)
	/tmp/workdir/go/src/testing/testing.go:1262
testing.(*M).Run(0x8855a40, 0x0)
	/tmp/workdir/go/src/testing/testing.go:1158 +0x77
main.main()
	_testmain.go:108 +0xfe
FAIL	os/exec	0.108s
```

**Comment by ianlancetaylor** [comment]
CL 207078
