### ISSUE TITLE
runtime/pprof: slice bounds out of range [6:5] in appendLocsForStack

### ISSUE THREAD

**Issue by eliasnaur** [golang/go#35573]
From https://farmer.golang.org/temporarylogs?name=android-arm64-corellium&rev=54cf7760203c2b138d9ecf653cd3b2402444cf9b&st=0xc0037da160

```
panic: runtime error: slice bounds out of range [6:5]

goroutine 51 [running]:
runtime/pprof.(*profileBuilder).appendLocsForStack(0x40000a5ce0, 0x400001cca0, 0x0, 0x4, 0x4000286050, 0x5, 0x3f6, 0x0, 0x1, 0x4)
	/data/data/com.termux/files/usr/tmp/workdir-host-android-arm64-corellium-android/go/src/runtime/pprof/proto.go:397 +0x5ac
runtime/pprof.(*profileBuilder).build(0x40000a5ce0)
	/data/data/com.termux/files/usr/tmp/workdir-host-android-arm64-corellium-android/go/src/runtime/pprof/proto.go:362 +0xf4
runtime/pprof.profileWriter(0x771c67e380, 0x400034a4e0)
	/data/data/com.termux/files/usr/tmp/workdir-host-android-arm64-corellium-android/go/src/runtime/pprof/pprof.go:779 +0xd0
created by runtime/pprof.StartCPUProfile
	/data/data/com.termux/files/usr/tmp/workdir-host-android-arm64-corellium-android/go/src/runtime/pprof/pprof.go:750 +0x114
```

With GOTRACEBACK=crash:

https://farmer.golang.org/temporarylogs?name=android-arm64-corellium&rev=62581ee982bef250a1b53af2e3591f1193fe27ee&st=0xc005d9b600

```
panic: runtime error: slice bounds out of range [6:5]

goroutine 10886 [running]:
panic(0x7b5d176580, 0x4007b41f40)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/panic.go:1054 +0x3ec fp=0x4000049cd0 sp=0x4000049c20 pc=0x7b5cf554a4
runtime.goPanicSliceB(0x6, 0x5)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/panic.go:116 +0x88 fp=0x4000049d20 sp=0x4000049cd0 pc=0x7b5cf53790
runtime/pprof.(*profileBuilder).appendLocsForStack(0x4008312c60, 0x4007b41f20, 0x0, 0x4, 0x4008330050, 0x5, 0x3f6, 0x0, 0x4, 0x4)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/pprof/proto.go:397 +0x5ac fp=0x4000049df0 sp=0x4000049d20 pc=0x7b5d086594
runtime/pprof.(*profileBuilder).build(0x4008312c60)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/pprof/proto.go:362 +0xf4 fp=0x4000049f40 sp=0x4000049df0 pc=0x7b5d085c5c
runtime/pprof.profileWriter(0x7b5d192020, 0x40000fe858)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/pprof/pprof.go:779 +0xd0 fp=0x4000049fc0 sp=0x4000049f40 pc=0x7b5d083888
runtime.goexit()
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/asm_arm64.s:1148 +0x4 fp=0x4000049fc0 sp=0x4000049fc0 pc=0x7b5cf8408c
created by runtime/pprof.StartCPUProfile
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/pprof/pprof.go:750 +0x114

goroutine 1 [chan receive]:
runtime.gopark(0x7b5d18d120, 0x4000023b58, 0x170e, 0x2)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/proc.go:304 +0xc8 fp=0x4000097b10 sp=0x4000097af0 pc=0x7b5cf57dc0
runtime.chanrecv(0x4000023b00, 0x4000097c28, 0x4000000101, 0x7b5cfff724)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/chan.go:563 +0x290 fp=0x4000097ba0 sp=0x4000097b10 pc=0x7b5cf2be78
runtime.chanrecv1(0x4000023b00, 0x4000097c28)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/chan.go:433 +0x20 fp=0x4000097bd0 sp=0x4000097ba0 pc=0x7b5cf2bbd8
testing.(*T).Run(0x4007d7d560, 0x7b5d09dbdf, 0x15, 0x7b5d18d3f0, 0x5dcc7101)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/testing/testing.go:1006 +0x2b8 fp=0x4000097c80 sp=0x4000097bd0 pc=0x7b5cfff740
testing.runTests.func1(0x40000c6000)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/testing/testing.go:1247 +0x6c fp=0x4000097cd0 sp=0x4000097c80 pc=0x7b5d002d54
testing.tRunner(0x40000c6000, 0x4000097dd8)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/testing/testing.go:954 +0xc4 fp=0x4000097d20 sp=0x4000097cd0 pc=0x7b5cfff40c
testing.runTests(0x400000e3c0, 0x7b5d2c13c0, 0x1a, 0x1a, 0x0)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/testing/testing.go:1245 +0x24c fp=0x4000097e00 sp=0x4000097d20 pc=0x7b5d000974
testing.(*M).Run(0x40000a8680, 0x0)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/testing/testing.go:1162 +0x144 fp=0x4000097f00 sp=0x4000097e00 pc=0x7b5cfffc2c
main.main()
	_testmain.go:94 +0x144 fp=0x4000097f70 sp=0x4000097f00 pc=0x7b5d098c1c
runtime.main()
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/proc.go:203 +0x21c fp=0x4000097fd0 sp=0x4000097f70 pc=0x7b5cf579e4
runtime.goexit()
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/asm_arm64.s:1148 +0x4 fp=0x4000097fd0 sp=0x4000097fd0 pc=0x7b5cf8408c

goroutine 2 [force gc (idle)]:
runtime.gopark(0x7b5d18d2f8, 0x7b5d2d8460, 0x1411, 0x1)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/proc.go:304 +0xc8 fp=0x4000036fa0 sp=0x4000036f80 pc=0x7b5cf57dc0
runtime.goparkunlock(...)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/proc.go:310
runtime.forcegchelper()
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/proc.go:253 +0xb0 fp=0x4000036fd0 sp=0x4000036fa0 pc=0x7b5cf57c78
runtime.goexit()
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/asm_arm64.s:1148 +0x4 fp=0x4000036fd0 sp=0x4000036fd0 pc=0x7b5cf8408c
created by runtime.init.5
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/proc.go:242 +0x28

goroutine 3 [GC sweep wait]:
runtime.gopark(0x7b5d18d2f8, 0x7b5d2d8600, 0x140c, 0x1)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/proc.go:304 +0xc8 fp=0x40000377a0 sp=0x4000037780 pc=0x7b5cf57dc0
runtime.goparkunlock(...)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/proc.go:310
runtime.bgsweep(0x400001a1c0)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/mgcsweep.go:89 +0x170 fp=0x40000377d0 sp=0x40000377a0 pc=0x7b5cf45cf8
runtime.goexit()
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/asm_arm64.s:1148 +0x4 fp=0x40000377d0 sp=0x40000377d0 pc=0x7b5cf8408c
created by runtime.gcenable
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/mgc.go:214 +0x4c

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x7b5d18d2f8, 0x7b5d2d85c0, 0x140d, 0x1)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/proc.go:304 +0xc8 fp=0x4000034740 sp=0x4000034720 pc=0x7b5cf57dc0
runtime.goparkunlock(...)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/proc.go:310
runtime.bgscavenge(0x400001a1c0)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/mgcscavenge.go:274 +0x35c fp=0x40000347d0 sp=0x4000034740 pc=0x7b5cf449c4
runtime.goexit()
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/asm_arm64.s:1148 +0x4 fp=0x40000347d0 sp=0x40000347d0 pc=0x7b5cf8408c
created by runtime.gcenable
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/mgc.go:215 +0x6c

goroutine 5 [finalizer wait]:
runtime.gopark(0x7b5d18d2f8, 0x7b5d2f5128, 0x4000011410, 0x1)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/proc.go:304 +0xc8 fp=0x4000036730 sp=0x4000036710 pc=0x7b5cf57dc0
runtime.goparkunlock(...)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/proc.go:310
runtime.runfinq()
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/mfinal.go:175 +0xac fp=0x40000367d0 sp=0x4000036730 pc=0x7b5cf3c204
runtime.goexit()
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/asm_arm64.s:1148 +0x4 fp=0x40000367d0 sp=0x40000367d0 pc=0x7b5cf8408c
created by runtime.createfing
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/mfinal.go:156 +0x64

goroutine 10870 [chan receive]:
runtime.gopark(0x7b5d18d120, 0x4000022478, 0x7b5d0d170e, 0x2)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/proc.go:304 +0xc8 fp=0x4000038d60 sp=0x4000038d40 pc=0x7b5cf57dc0
runtime.chanrecv(0x4000022420, 0x0, 0x701, 0x40000fe668)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/chan.go:563 +0x290 fp=0x4000038df0 sp=0x4000038d60 pc=0x7b5cf2be78
runtime.chanrecv1(0x4000022420, 0x0)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/chan.go:433 +0x20 fp=0x4000038e20 sp=0x4000038df0 pc=0x7b5cf2bbd8
testing.(*T).Parallel(0x40000c7b00)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/testing/testing.go:849 +0x16c fp=0x4000038eb0 sp=0x4000038e20 pc=0x7b5cfff194
runtime/pprof.TestEmptyCallStack(0x40000c7b00)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/pprof/pprof_test.go:1009 +0x9c fp=0x4000038f70 sp=0x4000038eb0 pc=0x7b5d08e564
testing.tRunner(0x40000c7b00, 0x7b5d18d498)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/testing/testing.go:954 +0xc4 fp=0x4000038fc0 sp=0x4000038f70 pc=0x7b5cfff40c
runtime.goexit()
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/asm_arm64.s:1148 +0x4 fp=0x4000038fc0 sp=0x4000038fc0 pc=0x7b5cf8408c
created by testing.(*T).Run
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/testing/testing.go:1005 +0x29c

goroutine 8 [GC worker (idle)]:
runtime.gopark(0x7b5d18d190, 0x400001c890, 0x1418, 0x0)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/proc.go:304 +0xc8 fp=0x4000038750 sp=0x4000038730 pc=0x7b5cf57dc0
runtime.gcBgMarkWorker(0x4000028000)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/mgc.go:1874 +0xe0 fp=0x40000387d0 sp=0x4000038750 pc=0x7b5cf3f948
runtime.goexit()
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/asm_arm64.s:1148 +0x4 fp=0x40000387d0 sp=0x40000387d0 pc=0x7b5cf8408c
created by runtime.gcBgMarkStartWorkers
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/mgc.go:1822 +0x70

goroutine 10885 [chan receive]:
runtime.gopark(0x7b5d18d120, 0x40000222f8, 0x170e, 0x2)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/proc.go:304 +0xc8 fp=0x4000048dc0 sp=0x4000048da0 pc=0x7b5cf57dc0
runtime.chanrecv(0x40000222a0, 0x0, 0x4000001f01, 0x400001b328)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/chan.go:563 +0x290 fp=0x4000048e50 sp=0x4000048dc0 pc=0x7b5cf2be78
runtime.chanrecv1(0x40000222a0, 0x0)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/chan.go:433 +0x20 fp=0x4000048e80 sp=0x4000048e50 pc=0x7b5cf2bbd8
runtime/pprof.StopCPUProfile()
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/pprof/pprof.go:795 +0xa0 fp=0x4000048ec0 sp=0x4000048e80 pc=0x7b5d0839d8
runtime/pprof.TestAtomicLoadStore64(0x4007d7d560)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/pprof/pprof_test.go:1102 +0x1e4 fp=0x4000048f70 sp=0x4000048ec0 pc=0x7b5d08ed0c
testing.tRunner(0x4007d7d560, 0x7b5d18d3f0)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/testing/testing.go:954 +0xc4 fp=0x4000048fc0 sp=0x4000048f70 pc=0x7b5cfff40c
runtime.goexit()
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/asm_arm64.s:1148 +0x4 fp=0x4000048fc0 sp=0x4000048fc0 pc=0x7b5cf8408c
created by testing.(*T).Run
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/testing/testing.go:1005 +0x29c

goroutine 10754 [chan send]:
runtime.gopark(0x7b5d18d120, 0x4000022718, 0x160f, 0x2)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/proc.go:304 +0xc8 fp=0x40075f9ef0 sp=0x40075f9ed0 pc=0x7b5cf57dc0
runtime.chansend(0x40000226c0, 0x7b5d0dcd9c, 0x1, 0x7b5d093dc8, 0x7b5d18d1e8)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/chan.go:252 +0x1bc fp=0x40075f9f70 sp=0x40075f9ef0 pc=0x7b5cf2b374
runtime.chansend1(0x40000226c0, 0x7b5d0dcd9c)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/chan.go:142 +0x28 fp=0x40075f9fb0 sp=0x40075f9f70 pc=0x7b5cf2b1b0
runtime/pprof.TestMorestack.func1.1(0x40000226c0)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/pprof/pprof_test.go:549 +0x30 fp=0x40075f9fd0 sp=0x40075f9fb0 pc=0x7b5d093dc8
runtime.goexit()
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/asm_arm64.s:1148 +0x4 fp=0x40075f9fd0 sp=0x40075f9fd0 pc=0x7b5cf8408c
created by runtime/pprof.TestMorestack.func1
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/pprof/pprof_test.go:547 +0x6c
FAIL	runtime/pprof	6.337s
```

Note that the android/arm and android/arm64 builders have been offline for about a week.

**Comment by hyangah** [comment]
Sorry for the breakage. Can I access the builder with TRY or gomote?

**Comment by cherrymui** [comment]
Probably the same as #35538

**Comment by eliasnaur** [comment]
Seems so.

**Comment by eliasnaur** [comment]
@hyangah You can use the `TRY=android-arm64,android-arm` aliases when the builders catch up. They're annoying to use from gomote.
