### ISSUE TITLE
runtime: TestAsyncPreempt failed on linux-mips64le-mengzhuo builder

### ISSUE THREAD

**Issue by mengzhuo** [golang/go#35742]
https://build.golang.org/log/aaa52433010dbd029e385ff21e1f9ac17bc7bd51
https://build.golang.org/log/5f0776a2c6b9c6697e9908610bb96c65e52e84ad
https://build.golang.org/log/04d37ca2ab2f4df3cdc7e4591c635c8081ec2b5a

Possibly related to https://go-review.googlesource.com/q/b89b4623eb70cbdc6b0aea43a5a826b7a26f20a7

```
--- FAIL: TestAsyncPreempt (60.01s)
    crash_test.go:95: testprog AsyncPreempt exit status: exit status 2
    proc_test.go:367: want OK
        , got SIGQUIT: quit
        PC=0x83204 m=0 sigcode=0
        
        goroutine 0 [idle]:
        runtime.futex(0x21c0b0, 0x80, 0x0, 0x0, 0xc000000000, 0x1, 0x52038, 0xc000080150, 0x520b8, 0x21c0b0, ...)
        	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/sys_linux_mips64x.s:410 +0x1c
        runtime.futexsleep(0x21c0b0, 0x0, 0xffffffffffffffff)
        	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/os_linux.go:44 +0x40
        runtime.notesleep(0x21c0b0)
        	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/lock_futex.go:151 +0xc4
        runtime.stopm()
        	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/proc.go:1864 +0xf8
        runtime.exitsyscall0(0xc000000180)
        	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/proc.go:3267 +0x174
        runtime.mcall(0x7f59c)
        	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/asm_mips64x.s:150 +0x54
        
        goroutine 1 [runnable]:
        runtime.GC()
        	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/mgc.go:1088 +0x78
        main.AsyncPreempt()
        	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/testdata/testprog/preempt.go:48 +0x144
        main.main()
        	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/testdata/testprog/main.go:34 +0x200
        
        goroutine 6 [runnable]:
        main.AsyncPreempt.func1(0xc000010108)
        	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/testdata/testprog/preempt.go:28
        created by main.AsyncPreempt
        	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/testdata/testprog/preempt.go:26 +0xb8
        
        goroutine 7 [running]:
        	goroutine running on other thread; stack unavailable
        created by main.AsyncPreempt
        	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/testdata/testprog/preempt.go:34 +0xe0
        
        r0   0x0	r1   0x1
        r2   0x144a	r3   0x21bba0
        r4   0x21c0b0	r5   0x80
        r6   0x0	r7   0x0
        r8   0x0	r9   0x0
        r10  0x1	r11  0x0
        r12  0x1	r13  0x0
        r14  0x1597b4	r15  0x1597ba
        r16  0x0	r17  0x0
        r18  0xf1	r19  0x30
        r20  0xc000072038	r21  0x0
        r22  0x1421d8	r23  0x210000
        r24  0x3f	r25  0xfffe75c410
        r26  0x0	r27  0x0
        r28  0x0	r29  0xfffbb21e48
        r30  0x21bba0	r31  0x45cc8
        pc   0x83204	link 0x45cc8
        lo   0xffffffff4325c53f	hi   0x2
```

@cherrymui @aclements

**Comment by cherrymui** [comment]
Dup of #35608
