### ISSUE TITLE
cmd/link: crash with -E <nonexisting symbol>

### ISSUE THREAD

**Issue by eliasnaur** [golang/go#36103]
<pre>
$ go version
go version devel +3a3093d5c7 Mon Dec 9 21:50:59 2019 +0000 linux/amd64
</pre>

```
$ cat main.go
package main

func main() {
}
$ go build -ldflags="-E nonexistent" main.go 
# command-line-arguments
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
cmd/link/internal/ld.(*Link).pclntab(0xc000082480)
	/home/elias/dev/go-tip/src/cmd/link/internal/ld/pcln.go:374 +0x1e40
cmd/link/internal/ld.Main(0x8912a0, 0x10, 0x20, 0x1, 0x7, 0x10, 0x6bddc3, 0x1b, 0x6b9e74, 0x14, ...)
	/home/elias/dev/go-tip/src/cmd/link/internal/ld/main.go:243 +0xc62
main.main()
	/home/elias/dev/go-tip/src/cmd/link/main.go:68 +0x1bc
```

**Comment by cherrymui** [comment]
Hmmm. `-E nonexistent` clearly won't work. What would you expect? A clean exit with an error?

**Comment by eliasnaur** [comment]
Sorry for not being clear. An error about the missing symbol would be nice, but since this is arguably a dusty corner of the linker, not panicing is fine.
