### ISSUE TITLE
panic: runtime error: comparing uncomparable type when error has interface field populated by a slice

### ISSUE THREAD

**Issue by jonbodner** [golang/go#36115]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.13.5
</pre>

### Does this issue reproduce with the latest release?

Yes, also on the playground.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jon/.cache/go-build"
GOENV="/home/jon/.config/go/env"
GOEXE=""
GOFLAGS=" -mod="
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY="REDACTED"
GONOSUMDB="REDACTED"
GOOS="linux"
GOPATH="/home/jon/go"
GOPRIVATE="REDACTED"
GOPROXY="direct"
GOROOT="/usr/local/go-1.13.5"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go-1.13.5/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="REDACTED"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build488327732=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

This code panics: https://play.golang.org/p/e1ITgr1D3sz

This code works as expected: https://play.golang.org/p/Pfa6Q_AEiMX

The only difference is that in the first case, the type of the `stuff` field in `MyErr` is `wrapper` (an interface) and in the second case, the type of the `stuff` field in `MyErr` is `wrapperImpl` (a type based on`[]int`).

### What did you expect to see?

should print out 
```
true
false
false
```

### What did you see instead?

```
true
false
panic: runtime error: comparing uncomparable type main.wrapperImpl

goroutine 1 [running]:
errors.Is(0x15dd50, 0x40a110, 0x15dd50, 0x40a120, 0x1, 0x40a0d0)
	/usr/local/go/src/errors/wrap.go:38 +0x260
main.main()
	/tmp/sandbox823409423/prog.go:36 +0x2c0
```

It looks like isComparable on wrap.go:36 should have been set to false.

**Comment by jonbodner** [comment]
Never mind, this is just the behavior of interfaces and == . I've re-written the code that triggered this so it won't happen.
