### ISSUE TITLE
net/http: apparent deadlock in TestServerGracefulClose on solaris and illumos

### ISSUE THREAD

**Issue by bcmills** [golang/go#36178]
```
#!watchflakes
post <- pkg == "net/http" && test == "TestServerGracefulClose" && `panic: test timed out`
```

[2019-12-16T20:38:31-f7f9866/illumos-amd64](https://build.golang.org/log/f240b506c629e4ab79af93b252326e90ae4ee7c7)
[2019-11-04T15:18:34-d3660e8/illumos-amd64](https://build.golang.org/log/af8196803dfc4536cb299870bd49cba7d80f444f)
[2019-10-04T20:09:41-60dc159/illumos-amd64-joyent](https://build.golang.org/log/8c5b1d481866510e68fe53bbb13044b966dac5e2)

```
goroutine 7503 [IO wait, 2 minutes]:
internal/poll.runtime_pollWait(0xfffffbffeecafb48, 0x77, 0xc001c1dca0)
	/var/tmp/workdir-host-illumos-amd64-jclulow/go/src/runtime/netpoll.go:203 +0x6d
internal/poll.(*pollDesc).wait(0xc0001ed118, 0x77, 0x470300, 0x4fc360, 0xffffffffffffffff)
	/var/tmp/workdir-host-illumos-amd64-jclulow/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitWrite(...)
	/var/tmp/workdir-host-illumos-amd64-jclulow/go/src/internal/poll/fd_poll_runtime.go:96
internal/poll.(*FD).Write(0xc0001ed100, 0xc001b8e000, 0x50003b, 0x58c000, 0x0, 0x0, 0x0)
	/var/tmp/workdir-host-illumos-amd64-jclulow/go/src/internal/poll/fd_unix.go:276 +0x290
net.(*netFD).Write(0xc0001ed100, 0xc001b8e000, 0x50003b, 0x58c000, 0xc000227f48, 0xc000054228, 0xc000054220)
	/var/tmp/workdir-host-illumos-amd64-jclulow/go/src/net/fd_unix.go:220 +0x4f
net.(*conn).Write(0xc000180020, 0xc001b8e000, 0x50003b, 0x58c000, 0x0, 0x0, 0x0)
	/var/tmp/workdir-host-illumos-amd64-jclulow/go/src/net/net.go:196 +0x8e
net/http_test.TestServerGracefulClose.func2(0xa5cc40, 0xc000180020, 0xc001b8e000, 0x50003b, 0x58c000, 0xc00032c3c0)
	/var/tmp/workdir-host-illumos-amd64-jclulow/go/src/net/http/serve_test.go:3100 +0x5b
created by net/http_test.TestServerGracefulClose
	/var/tmp/workdir-host-illumos-amd64-jclulow/go/src/net/http/serve_test.go:3099 +0x35e
```

CC @bradfitz @ianlancetaylor @jclulow

**Comment by bcmills** [comment]
`greplogs -l -e 'goroutine \d+ \[.*, \d+ minutes\]:\n(.+\n\t.*\n)*net\.\(\*conn\)\.Write.*\n\t.+\nnet/http_test\.TestServerGracefulClose'`
[2022-05-05T01:32:18-b922055/solaris-amd64-oraclerel](https://build.golang.org/log/94ce93c2ce47065bc3af5e7dd7571d87bdf57c6a)
[2021-09-23T15:51:39-24c2ee7/illumos-amd64](https://build.golang.org/log/0a11c11c18102b194e0cdf49c9a7ab38ebd09369)
[2020-12-03T19:02:05-9b0e8a2/illumos-amd64](https://build.golang.org/log/d7561b8b83c6bfcc17597ad896f214466b753a45)
[2019-12-16T20:38:31-f7f9866/illumos-amd64](https://build.golang.org/log/f240b506c629e4ab79af93b252326e90ae4ee7c7)
[2019-11-04T15:18:34-d3660e8/illumos-amd64](https://build.golang.org/log/af8196803dfc4536cb299870bd49cba7d80f444f)
[2019-10-04T20:09:41-60dc159/illumos-amd64-joyent](https://build.golang.org/log/8c5b1d481866510e68fe53bbb13044b966dac5e2)

**Comment by bcmills** [comment]
(CC @rorth)
