### ISSUE TITLE
x/tools/gopls: not working

### ISSUE THREAD

**Issue by sjf3** [golang/go#37119]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?
click install new go please when it popped up in vs code then restart vs code

#### Build info

```
golang.org/x/tools/gopls v0.3.1
    golang.org/x/tools/gopls@v0.3.1 h1:yNTWrf4gc4Or0UecjOas5pzOa3BL0WDDyKDV4Wz5VaM=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/sergi/go-diff@v1.0.0 h1:Kpca3qRNrduNnOQeazBd0ysaKrUJiIuISHxogkT9RPQ=
    golang.org/x/mod@v0.1.1-0.20191105210325-c90efee705ee h1:WG0RUwxtNT4qqaXX3DPA8zHFNm/D9xaBpxzHt1WcA/E=
    golang.org/x/sync@v0.0.0-20190423024810-112230192c58 h1:8gQV6CLnAEikrhgkHFbMAEhagSSnXWGV915qUMm9mrU=
    golang.org/x/tools@v0.0.0-20200204151227-34c67990bfe7 h1:hWZVyLW37WdETuLIGQMvQIhMfXXAOANmAIEAluZMy3c=
    golang.org/x/xerrors@v0.0.0-20191011141410-1b5146add898 h1:/atklqdjdhuosWIl6AIbOeHJjicWYPqR9bpxqxYG2pA=
    honnef.co/go/tools@v0.0.1-2019.2.3 h1:3JgtbtFHMiCmsznwGVTUWbgGov+pVqnlf1dEJTNAXeM=
    mvdan.cc/xurls/v2@v2.1.0 h1:KaMb5GLhlcSX+e+qhbRJODnUUBvlw01jt4yrjFIHAuA=
```

#### Go info

```
go version go1.13.4 darwin/amd64

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/sfleeman/Library/Caches/go-build"
GOENV="/Users/sfleeman/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY="github.com/<redacted>"
GONOSUMDB="github.com/<redacted>"
GOOS="darwin"
GOPATH="/Users/<redacted>/go"
GOPRIVATE="github.com/RedVentures"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/<redacted>/go/src/github.com/<redacted>/<redacted>/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/24/sx13x65d1xd1mlpy_z33l_r88l7m4g/T/go-build773498168=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by stamblerre** [comment]
Can you please share the output of `gopls -rpc.trace -v check path/to/file.go`?

**Comment by sjf3** [comment]
> Can you please share the output of `gopls -rpc.trace -v check path/to/file.go`?

020/02/07 13:51:07 Info:2020/02/07 13:51:07 Build info
----------
golang.org/x/tools/gopls v0.3.1
    golang.org/x/tools/gopls@v0.3.1 h1:yNTWrf4gc4Or0UecjOas5pzOa3BL0WDDyKDV4Wz5VaM=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/sergi/go-diff@v1.0.0 h1:Kpca3qRNrduNnOQeazBd0ysaKrUJiIuISHxogkT9RPQ=
    golang.org/x/mod@v0.1.1-0.20191105210325-c90efee705ee h1:WG0RUwxtNT4qqaXX3DPA8zHFNm/D9xaBpxzHt1WcA/E=
    golang.org/x/sync@v0.0.0-20190423024810-112230192c58 h1:8gQV6CLnAEikrhgkHFbMAEhagSSnXWGV915qUMm9mrU=
    golang.org/x/tools@v0.0.0-20200204151227-34c67990bfe7 h1:hWZVyLW37WdETuLIGQMvQIhMfXXAOANmAIEAluZMy3c=
    golang.org/x/xerrors@v0.0.0-20191011141410-1b5146add898 h1:/atklqdjdhuosWIl6AIbOeHJjicWYPqR9bpxqxYG2pA=
    honnef.co/go/tools@v0.0.1-2019.2.3 h1:3JgtbtFHMiCmsznwGVTUWbgGov+pVqnlf1dEJTNAXeM=
    mvdan.cc/xurls/v2@v2.1.0 h1:KaMb5GLhlcSX+e+qhbRJODnUUBvlw01jt4yrjFIHAuA=

Go info
-------
go version go1.13.4 darwin/amd64

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/sfleeman/Library/Caches/go-build"
GOENV="/Users/sfleeman/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY="github.com/RedVentures"
GONOSUMDB="github.com/RedVentures"
GOOS="darwin"
GOPATH="/Users/sfleeman/go"
GOPRIVATE="github.com/RedVentures"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/24/sx13x65d1xd1mlpy_z33l_r88l7m4g/T/go-build054596692=/tmp/go-build -gno-record-gcc-switches -fno-common"
2020/02/07 13:51:08 Info:2020/02/07 13:51:08 go/packages.Load
	snapshot = 0
	query = [./... builtin]
	packages = 2

**Comment by stamblerre** [comment]
Thanks! Looks like `gopls` is able to type-check your package fine. Can you share the logs from when completion or hover fail? Information on how to capture logs is here: https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs. Make sure to add the `-rpc.trace` flag in your settings so that there is more detailed output.

**Comment by sjf3** [comment]
Trace - 13:57:56.872 PM] Sending notification '$/cancelRequest'.
Params: {"id":17}


[Trace - 13:57:56.873 PM] Received response 'textDocument/hover - (17)' in 51ms.
Result: {}


2020/02/07 13:57:56 : context canceled
[Trace - 13:57:56.874 PM] Received notification 'window/logMessage'.
Params: {"type":1,"message":"2020/02/07 13:57:56 : context canceled"}


[Error - 1:57:56 PM] 2020/02/07 13:57:56 : context canceled
[Trace - 13:57:57.022 PM] Sending request 'textDocument/hover - (18)'.
Params: {"textDocument":{"uri":"file:///Users/<redacted>/go/src/github.com/<redacted>/internal/service/service.go"},"position":{"line":1243,"character":33}}


[Trace - 13:57:57.986 PM] Received response 'textDocument/hover - (18)' in 964ms.
Result: {}


[Trace - 13:57:57.986 PM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2020/02/07 13:57:57 go/packages.Load\n\tsnapshot = 1\n\tquery = [file=/Users/<redacted>/internal/service/service.go]\n\tpackages = 0"}


[Info  - 1:57:57 PM] 2020/02/07 13:57:57 go/packages.Load
	snapshot = 1
	query = [file=/Users/<redacted>/go/src/github.com/<redacted>/<redacted>/internal/service/service.go]
	packages = 0

**Comment by hujianxin** [comment]
@stamblerre Hi, I found gopls will crash after jumping to a definition which not belong to current project.
Here is my vscode log, In this example, I open a go file, and `command + click` on `context.Context`, After jumpint to definition of Context, gopls crashed.
```
[Info  - 11:23:33 AM] 2020/02/08 11:23:33 Build info
----------
golang.org/x/tools/gopls master
    golang.org/x/tools/gopls@v0.3.1 h1:yNTWrf4gc4Or0UecjOas5pzOa3BL0WDDyKDV4Wz5VaM=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.2.0 h1:KU7oHjnv3XNWfa5COkzUifxZmxp1TyI7ImMXqFxLwvQ=
    golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e h1:vcxGaoTs7kV8m5Np9uUNQin4BrLOthgV7252N8V+FwY=
    golang.org/x/tools@v0.0.0-20200207001614-6fdc5776f4bb h1:e2097s5ZlmbJkGiqRuZb4/YoM3h8n6Ih8hdaA2ujek8=
    golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543 h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=
    honnef.co/go/tools@v0.0.1-2019.2.3 h1:3JgtbtFHMiCmsznwGVTUWbgGov+pVqnlf1dEJTNAXeM=
    mvdan.cc/xurls/v2@v2.1.0 h1:KaMb5GLhlcSX+e+qhbRJODnUUBvlw01jt4yrjFIHAuA=

Go info
-------
go version go1.13.4 darwin/amd64

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/hujianxin/Library/Caches/go-build"
GOENV="/Users/hujianxin/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/hujianxin/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/hujianxin/g/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/Users/hujianxin/g/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/hujianxin/g/go-fds/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sf/nh5lvmv114j1sdvhy0d3rztm0000gn/T/go-build876479546=/tmp/go-build -gno-record-gcc-switches -fno-common"

[Info  - 11:23:34 AM] 2020/02/08 11:23:34 go/packages.Load
	snapshot = 0
	query = [./... builtin]
	packages = 24
[Error - 11:23:43 AM] Request textDocument/codeAction failed.
  Message: method "textDocument/codeAction" did not reply
  Code: -32603 
panic: unexpected parse mode for context

goroutine 4482 [running]:
golang.org/x/tools/internal/lsp/cache.expectMode(...)
	/Users/hujianxin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200207001614-6fdc5776f4bb/internal/lsp/cache/snapshot.go:378
golang.org/x/tools/internal/lsp/cache.(*snapshot).shouldCheck(0xc0004c0240, 0xc0077e4008, 0x1, 0x1, 0x0, 0xc000dd90f0, 0xc000dd9160, 0x171638e)
	/Users/hujianxin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200207001614-6fdc5776f4bb/internal/lsp/cache/snapshot.go:206 +0x2d9
golang.org/x/tools/internal/lsp/cache.(*snapshot).packageHandles(0xc0004c0240, 0x1a5ec80, 0xc003f93740, 0xc0004e3b00, 0x33, 0xc0077e4008, 0x1, 0x1, 0x100def6, 0xc003f936b0, ...)
	/Users/hujianxin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200207001614-6fdc5776f4bb/internal/lsp/cache/snapshot.go:133 +0x67
golang.org/x/tools/internal/lsp/cache.(*snapshot).PackageHandles(0xc0004c0240, 0x1a5ec80, 0xc003f936b0, 0x1a5cc40, 0xc000415760, 0x12e969d, 0x1852f00, 0xc004037200, 0xc001bec000, 0xbf87a84fccd9b7f8)
	/Users/hujianxin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200207001614-6fdc5776f4bb/internal/lsp/cache/snapshot.go:85 +0x2ec
golang.org/x/tools/internal/lsp/source.getParsedFile(0x1a5ec80, 0xc003f936b0, 0x1a6eee0, 0xc0004c0240, 0x1a5cc40, 0xc000415760, 0x195c090, 0x1a5ec80, 0xc003f936b0, 0xc004037200, ...)
	/Users/hujianxin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200207001614-6fdc5776f4bb/internal/lsp/source/util.go:71 +0x7d
golang.org/x/tools/internal/lsp/source.AllImportsFixes(0x1a5ec80, 0xc003f936b0, 0x1a6eee0, 0xc0004c0240, 0x1a5cc40, 0xc000415760, 0x0, 0xc0000ad720, 0x1, 0x1, ...)
	/Users/hujianxin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200207001614-6fdc5776f4bb/internal/lsp/source/format.go:83 +0x183
golang.org/x/tools/internal/lsp.(*Server).codeAction(0xc0002b8f60, 0x1a5ec80, 0xc002ebeb10, 0xc0010ea700, 0xc0010ea700, 0x0, 0x0, 0x0, 0xc000463550)
	/Users/hujianxin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200207001614-6fdc5776f4bb/internal/lsp/code_action.go:74 +0x951
golang.org/x/tools/internal/lsp.(*Server).CodeAction(0xc0002b8f60, 0x1a5ec80, 0xc002ebeb10, 0xc0010ea700, 0xc0010ea700, 0x0, 0x0, 0xc0003b8780, 0x1129d0001128f)
	/Users/hujianxin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200207001614-6fdc5776f4bb/internal/lsp/server_gen.go:12 +0x4d
golang.org/x/tools/internal/lsp/protocol.serverHandler.Deliver(0x1a7cfa0, 0xc0002b8f60, 0x1a5ec80, 0xc002ebeb10, 0xc0037d8b80, 0xc001043200, 0x1fa0000)
	/Users/hujianxin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200207001614-6fdc5776f4bb/internal/lsp/protocol/tsserver.go:433 +0x25ff
golang.org/x/tools/internal/jsonrpc2.(*Conn).Run.func1(0xc0086e49c0, 0xc0037d8b80, 0xc0002b8ea0, 0x1a5ec80, 0xc002ebeb10, 0x0, 0x0, 0xc00279bff0)
	/Users/hujianxin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200207001614-6fdc5776f4bb/internal/jsonrpc2/jsonrpc2.go:370 +0x170
created by golang.org/x/tools/internal/jsonrpc2.(*Conn).Run
	/Users/hujianxin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200207001614-6fdc5776f4bb/internal/jsonrpc2/jsonrpc2.go:354 +0x877
[Info  - 11:23:43 AM] Connection to server got closed. Server will restart.
[Error - 11:23:43 AM] Request textDocument/foldingRange failed.
Error: Connection got disposed.
	at Object.dispose (/Users/hujianxin/.vscode/extensions/ms-vscode.go-0.13.0/node_modules/vscode-jsonrpc/lib/main.js:876:25)
	at Object.dispose (/Users/hujianxin/.vscode/extensions/ms-vscode.go-0.13.0/node_modules/vscode-languageclient/lib/client.js:71:35)
	at LanguageClient.handleConnectionClosed (/Users/hujianxin/.vscode/extensions/ms-vscode.go-0.13.0/node_modules/vscode-languageclient/lib/client.js:2153:42)
	at LanguageClient.handleConnectionClosed (/Users/hujianxin/.vscode/extensions/ms-vscode.go-0.13.0/node_modules/vscode-languageclient/lib/main.js:151:15)
	at closeHandler (/Users/hujianxin/.vscode/extensions/ms-vscode.go-0.13.0/node_modules/vscode-languageclient/lib/client.js:2140:18)
	at CallbackList.invoke (/Users/hujianxin/.vscode/extensions/ms-vscode.go-0.13.0/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/hujianxin/.vscode/extensions/ms-vscode.go-0.13.0/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at closeHandler (/Users/hujianxin/.vscode/extensions/ms-vscode.go-0.13.0/node_modules/vscode-jsonrpc/lib/main.js:226:26)
	at CallbackList.invoke (/Users/hujianxin/.vscode/extensions/ms-vscode.go-0.13.0/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/hujianxin/.vscode/extensions/ms-vscode.go-0.13.0/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at StreamMessageReader.fireClose (/Users/hujianxin/.vscode/extensions/ms-vscode.go-0.13.0/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at Socket.<anonymous> (/Users/hujianxin/.vscode/extensions/ms-vscode.go-0.13.0/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
	at Socket.emit (events.js:205:15)
	at Pipe.<anonymous> (net.js:586:12)
[Info  - 11:23:43 AM] 2020/02/08 11:23:43 Build info
----------
golang.org/x/tools/gopls master
    golang.org/x/tools/gopls@v0.3.1 h1:yNTWrf4gc4Or0UecjOas5pzOa3BL0WDDyKDV4Wz5VaM=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.2.0 h1:KU7oHjnv3XNWfa5COkzUifxZmxp1TyI7ImMXqFxLwvQ=
    golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e h1:vcxGaoTs7kV8m5Np9uUNQin4BrLOthgV7252N8V+FwY=
    golang.org/x/tools@v0.0.0-20200207001614-6fdc5776f4bb h1:e2097s5ZlmbJkGiqRuZb4/YoM3h8n6Ih8hdaA2ujek8=
    golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543 h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=
    honnef.co/go/tools@v0.0.1-2019.2.3 h1:3JgtbtFHMiCmsznwGVTUWbgGov+pVqnlf1dEJTNAXeM=
    mvdan.cc/xurls/v2@v2.1.0 h1:KaMb5GLhlcSX+e+qhbRJODnUUBvlw01jt4yrjFIHAuA=
```
