### ISSUE TITLE
runtime: apparent deadlock in TestGdbAutotmpTypes

### ISSUE THREAD

**Issue by bcmills** [golang/go#37366]
```
go version devel +a224fa7fb9 Fri Feb 21 13:27:59 2020 -0500 linux/amd64
```

I ran `run.bash` on my local workstation to test https://golang.org/cl/211358, and got a `runtime` test failure that does not seem to be in any way related to the change — and looks an awful lot like a deadlock in `TestGdbAutotmpTypes`.

The test passed on a subsequent run.

I think there are two action items for this:

- [ ] Fix the test to emit some kind of useful diagnostic in case of a timeout. (That should be much easier now that the [`(*testing.T).Deadline`](https://tip.golang.org/pkg/testing/#T.Deadline) method is merged.)
- [ ] Figure out the root cause of the deadlock and fix it.

CC @dr2chase 

<details>

```
panic: test timed out after 9m0s

goroutine 154647 [running]:
panic(0x629de0, 0xc000b86010)
        /usr/local/google/home/bcmills/go/src/runtime/panic.go:1060 +0x420 fp=0xc000258f88 sp=0xc000258ee0 pc=0x436890
testing.(*M).startAlarm.func1()
        /usr/local/google/home/bcmills/go/src/testing/testing.go:1479 +0xdf fp=0xc000258fe0 sp=0xc000258f88 pc=0x4e9e4f
runtime.goexit()
        /usr/local/google/home/bcmills/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000258fe8 sp=0xc000258fe0 pc=0x46dde1
created by time.goFunc
        /usr/local/google/home/bcmills/go/src/time/sleep.go:168 +0x44

goroutine 1 [chan receive, 8 minutes, locked to thread]:
runtime.gopark(0x69d768, 0xc00008fc78, 0x170e, 0x2)
        /usr/local/google/home/bcmills/go/src/runtime/proc.go:304 +0xe0 fp=0xc000050b60 sp=0xc000050b40 pc=0x4396a0
runtime.chanrecv(0xc00008fc20, 0x0, 0xc000415101, 0xc000080101)
        /usr/local/google/home/bcmills/go/src/runtime/chan.go:525 +0x2e7 fp=0xc000050bf0 sp=0xc000050b60 pc=0x407807
runtime.chanrecv1(0xc00008fc20, 0x0)
        /usr/local/google/home/bcmills/go/src/runtime/chan.go:407 +0x2b fp=0xc000050c20 sp=0xc000050bf0 pc=0x4074cb
testing.tRunner.func1(0xc0000de000)
        /usr/local/google/home/bcmills/go/src/testing/testing.go:957 +0x238 fp=0xc000050cc8 sp=0xc000050c20 pc=0x4e9978
testing.tRunner(0xc0000de000, 0xc000050da8)
        /usr/local/google/home/bcmills/go/src/testing/testing.go:996 +0x10b fp=0xc000050d18 sp=0xc000050cc8 pc=0x4e566b
testing.runTests(0xc0000a60a0, 0x870000, 0x153, 0x153, 0xbf8c2c32819f2ada, 0x7dba860a67, 0x873580, 0x203000)
        /usr/local/google/home/bcmills/go/src/testing/testing.go:1298 +0x2d8 fp=0xc000050dd8 sp=0xc000050d18 pc=0x4e7028
testing.(*M).Run(0xc0000d8000, 0x0)
        /usr/local/google/home/bcmills/go/src/testing/testing.go:1210 +0x1a7 fp=0xc000050ed0 sp=0xc000050dd8 pc=0x4e5f47
runtime_test.TestMain(0xc0000d8000)
        /usr/local/google/home/bcmills/go/src/runtime/crash_test.go:28 +0x2f fp=0xc000050f20 sp=0xc000050ed0 pc=0x57ef3f
main.main()
        _testmain.go:1192 +0x135 fp=0xc000050f88 sp=0xc000050f20 pc=0x604fd5
runtime.main()
        /usr/local/google/home/bcmills/go/src/runtime/proc.go:203 +0x212 fp=0xc000050fe0 sp=0xc000050f88 pc=0x4392c2
runtime.goexit()
        /usr/local/google/home/bcmills/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000050fe8 sp=0xc000050fe0 pc=0x46dde1

goroutine 2 [force gc (idle), 2 minutes]:
runtime.gopark(0x69da78, 0x872da0, 0x1411, 0x1)
        /usr/local/google/home/bcmills/go/src/runtime/proc.go:304 +0xe0 fp=0xc000042fb0 sp=0xc000042f90 pc=0x4396a0
runtime.goparkunlock(...)
        /usr/local/google/home/bcmills/go/src/runtime/proc.go:310
runtime.forcegchelper()
        /usr/local/google/home/bcmills/go/src/runtime/proc.go:253 +0xb7 fp=0xc000042fe0 sp=0xc000042fb0 pc=0x439557
runtime.goexit()
        /usr/local/google/home/bcmills/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000042fe8 sp=0xc000042fe0 pc=0x46dde1
created by runtime.init.6
        /usr/local/google/home/bcmills/go/src/runtime/proc.go:242 +0x35

goroutine 3 [GC sweep wait]:
runtime.gopark(0x69da78, 0x8731c0, 0x140c, 0x1)
        /usr/local/google/home/bcmills/go/src/runtime/proc.go:304 +0xe0 fp=0xc0000437a8 sp=0xc000043788 pc=0x4396a0
runtime.goparkunlock(...)
        /usr/local/google/home/bcmills/go/src/runtime/proc.go:310
runtime.bgsweep(0xc000018150)
        /usr/local/google/home/bcmills/go/src/runtime/mgcsweep.go:89 +0x131 fp=0xc0000437d8 sp=0xc0000437a8 pc=0x424fc1
runtime.goexit()
        /usr/local/google/home/bcmills/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0000437e0 sp=0xc0000437d8 pc=0x46dde1
created by runtime.gcenable
        /usr/local/google/home/bcmills/go/src/runtime/mgc.go:214 +0x5c

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x69da78, 0x873180, 0x140d, 0x1)
        /usr/local/google/home/bcmills/go/src/runtime/proc.go:304 +0xe0 fp=0xc000043f78 sp=0xc000043f58 pc=0x4396a0
runtime.goparkunlock(...)
        /usr/local/google/home/bcmills/go/src/runtime/proc.go:310
runtime.bgscavenge(0xc000018150)
        /usr/local/google/home/bcmills/go/src/runtime/mgcscavenge.go:285 +0x20f fp=0xc000043fd8 sp=0xc000043f78 pc=0x42366f
runtime.goexit()
        /usr/local/google/home/bcmills/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000043fe0 sp=0xc000043fd8 pc=0x46dde1
created by runtime.gcenable
        /usr/local/google/home/bcmills/go/src/runtime/mgc.go:215 +0x7e

goroutine 18 [finalizer wait, 6 minutes]:
runtime.gopark(0x69da78, 0x89d5a0, 0xc0000d1410, 0x1)
        /usr/local/google/home/bcmills/go/src/runtime/proc.go:304 +0xe0 fp=0xc0001b4758 sp=0xc0001b4738 pc=0x4396a0
runtime.goparkunlock(...)
        /usr/local/google/home/bcmills/go/src/runtime/proc.go:310
runtime.runfinq()
        /usr/local/google/home/bcmills/go/src/runtime/mfinal.go:175 +0xa3 fp=0xc0001b47e0 sp=0xc0001b4758 pc=0x41ab83
runtime.goexit()
        /usr/local/google/home/bcmills/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0001b47e8 sp=0xc0001b47e0 pc=0x46dde1
created by runtime.createfing
        /usr/local/google/home/bcmills/go/src/runtime/mfinal.go:156 +0x61

goroutine 23445 [chan send, 8 minutes]:
runtime.gopark(0x69d768, 0xc00008fdf8, 0x62160f, 0x2)
        /usr/local/google/home/bcmills/go/src/runtime/proc.go:304 +0xe0 fp=0xc000254e20 sp=0xc000254e00 pc=0x4396a0
runtime.chansend(0xc00008fda0, 0xc000254f0f, 0xc00008e001, 0x4e9a93, 0x69f8e0)
        /usr/local/google/home/bcmills/go/src/runtime/chan.go:236 +0x22d fp=0xc000254ea0 sp=0xc000254e20 pc=0x406bed
runtime.chansend1(0xc00008fda0, 0xc000329f0f)
        /usr/local/google/home/bcmills/go/src/runtime/chan.go:127 +0x35 fp=0xc000254ed8 sp=0xc000254ea0 pc=0x4069b5
testing.tRunner.func1(0xc0003f7e60)
        /usr/local/google/home/bcmills/go/src/testing/testing.go:982 +0x353 fp=0xc000254f80 sp=0xc000254ed8 pc=0x4e9a93
testing.tRunner(0xc0003f7e60, 0x69ec28)
        /usr/local/google/home/bcmills/go/src/testing/testing.go:996 +0x10b fp=0xc000254fd0 sp=0xc000254f80 pc=0x4e566b
runtime.goexit()
        /usr/local/google/home/bcmills/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000254fd8 sp=0xc000254fd0 pc=0x46dde1
created by testing.(*T).Run
        /usr/local/google/home/bcmills/go/src/testing/testing.go:1043 +0x357

goroutine 23444 [chan send, 8 minutes]:
runtime.gopark(0x69d768, 0xc00008fd38, 0x62160f, 0x2)
        /usr/local/google/home/bcmills/go/src/runtime/proc.go:304 +0xe0 fp=0xc000180e20 sp=0xc000180e00 pc=0x4396a0
runtime.chansend(0xc00008fce0, 0xc000180f0f, 0xc00008e001, 0x4e9a93, 0x69f8e0)
        /usr/local/google/home/bcmills/go/src/runtime/chan.go:236 +0x22d fp=0xc000180ea0 sp=0xc000180e20 pc=0x406bed
runtime.chansend1(0xc00008fce0, 0xc00032bf0f)
        /usr/local/google/home/bcmills/go/src/runtime/chan.go:127 +0x35 fp=0xc000180ed8 sp=0xc000180ea0 pc=0x4069b5
testing.tRunner.func1(0xc0003f7d40)
        /usr/local/google/home/bcmills/go/src/testing/testing.go:982 +0x353 fp=0xc000180f80 sp=0xc000180ed8 pc=0x4e9a93
testing.tRunner(0xc0003f7d40, 0x69ec20)
        /usr/local/google/home/bcmills/go/src/testing/testing.go:996 +0x10b fp=0xc000180fd0 sp=0xc000180f80 pc=0x4e566b
runtime.goexit()
        /usr/local/google/home/bcmills/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000180fd8 sp=0xc000180fd0 pc=0x46dde1
created by testing.(*T).Run
        /usr/local/google/home/bcmills/go/src/testing/testing.go:1043 +0x357

goroutine 23443 [syscall, 8 minutes]:
syscall.Syscall6(0xf7, 0x1, 0x1e307, 0xc0003259d8, 0x1000004, 0x0, 0x0, 0x6dafe8, 0x40, 0xc000325a18)
        /usr/local/google/home/bcmills/go/src/syscall/asm_linux_amd64.s:41 +0x5 fp=0xc000325988 sp=0xc000325980 pc=0x4ada75
os.(*Process).blockUntilWaitable(0xc0005303f0, 0x203000, 0x422d55, 0x1)
        /usr/local/google/home/bcmills/go/src/os/wait_waitid.go:31 +0x98 fp=0xc000325a78 sp=0xc000325988 pc=0x4c2f68
os.(*Process).wait(0xc0005303f0, 0x69d560, 0x69d568, 0x69d558)
        /usr/local/google/home/bcmills/go/src/os/exec_unix.go:22 +0x39 fp=0xc000325af0 sp=0xc000325a78 pc=0x4be309
os.(*Process).Wait(...)
        /usr/local/google/home/bcmills/go/src/os/exec.go:125
os/exec.(*Cmd).Wait(0xc0002d6000, 0x0, 0x0)
        /usr/local/google/home/bcmills/go/src/os/exec/exec.go:502 +0x60 fp=0xc000325b68 sp=0xc000325af0 pc=0x527f70
os/exec.(*Cmd).Run(0xc0002d6000, 0xc0002d4240, 0xc0002d6000)
        /usr/local/google/home/bcmills/go/src/os/exec/exec.go:340 +0x5c fp=0xc000325b90 sp=0xc000325b68 pc=0x52740c
os/exec.(*Cmd).CombinedOutput(0xc0002d6000, 0x3, 0xc000325e68, 0xf, 0xf, 0xc0002d6000)
        /usr/local/google/home/bcmills/go/src/os/exec/exec.go:562 +0x91 fp=0xc000325bc0 sp=0xc000325b90 pc=0x5282c1
runtime_test.TestGdbAutotmpTypes(0xc0003f7c20)
        /usr/local/google/home/bcmills/go/src/runtime/runtime-gdb_test.go:463 +0x822 fp=0xc000325f80 sp=0xc000325bc0 pc=0x5d20f2
testing.tRunner(0xc0003f7c20, 0x69ec10)
        /usr/local/google/home/bcmills/go/src/testing/testing.go:992 +0xdc fp=0xc000325fd0 sp=0xc000325f80 pc=0x4e563c
runtime.goexit()
        /usr/local/google/home/bcmills/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000325fd8 sp=0xc000325fd0 pc=0x46dde1
created by testing.(*T).Run
        /usr/local/google/home/bcmills/go/src/testing/testing.go:1043 +0x357

goroutine 144644 [GC worker (idle)]:
runtime.gopark(0x69d880, 0xc0002cb8d0, 0xc0002e1418, 0x0)
        /usr/local/google/home/bcmills/go/src/runtime/proc.go:304 +0xe0 fp=0xc0002e4760 sp=0xc0002e4740 pc=0x4396a0
runtime.gcBgMarkWorker(0xc00002f000)
        /usr/local/google/home/bcmills/go/src/runtime/mgc.go:1865 +0xff fp=0xc0002e47d8 sp=0xc0002e4760 pc=0x41e58f
runtime.goexit()
        /usr/local/google/home/bcmills/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0002e47e0 sp=0xc0002e47d8 pc=0x46dde1
created by runtime.gcBgMarkStartWorkers
        /usr/local/google/home/bcmills/go/src/runtime/mgc.go:1813 +0x77

goroutine 144641 [GC worker (idle)]:
runtime.gopark(0x69d880, 0xc000f47c90, 0xc0001b1418, 0x0)
        /usr/local/google/home/bcmills/go/src/runtime/proc.go:304 +0xe0 fp=0xc0001b3760 sp=0xc0001b3740 pc=0x4396a0
runtime.gcBgMarkWorker(0xc000031800)
        /usr/local/google/home/bcmills/go/src/runtime/mgc.go:1865 +0xff fp=0xc0001b37d8 sp=0xc0001b3760 pc=0x41e58f
runtime.goexit()
        /usr/local/google/home/bcmills/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0001b37e0 sp=0xc0001b37d8 pc=0x46dde1
created by runtime.gcBgMarkStartWorkers
        /usr/local/google/home/bcmills/go/src/runtime/mgc.go:1813 +0x77

goroutine 144640 [GC worker (idle), 2 minutes]:
runtime.gopark(0x69d880, 0xc000f478e0, 0xc000641418, 0x0)
        /usr/local/google/home/bcmills/go/src/runtime/proc.go:304 +0xe0 fp=0xc000646760 sp=0xc000646740 pc=0x4396a0
runtime.gcBgMarkWorker(0xc00002c800)
        /usr/local/google/home/bcmills/go/src/runtime/mgc.go:1865 +0xff fp=0xc0006467d8 sp=0xc000646760 pc=0x41e58f
runtime.goexit()
        /usr/local/google/home/bcmills/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0006467e0 sp=0xc0006467d8 pc=0x46dde1
created by runtime.gcBgMarkStartWorkers
        /usr/local/google/home/bcmills/go/src/runtime/mgc.go:1813 +0x77

goroutine 147342 [IO wait, 8 minutes]:
runtime.gopark(0x69da30, 0x7f0cb8a45a90, 0xc000501b02, 0x5)
        /usr/local/google/home/bcmills/go/src/runtime/proc.go:304 +0xe0 fp=0xc0004864d0 sp=0xc0004864b0 pc=0x4396a0
runtime.netpollblock(0x7f0cb8a45a68, 0x72, 0xc000268120)
        /usr/local/google/home/bcmills/go/src/runtime/netpoll.go:419 +0x9a fp=0xc000486508 sp=0xc0004864d0 pc=0x43238a
internal/poll.runtime_pollWait(0x7f0cb8a45a68, 0x72, 0xffffffffffffffff)
        /usr/local/google/home/bcmills/go/src/runtime/netpoll.go:203 +0x55 fp=0xc000486530 sp=0xc000486508 pc=0x431955
internal/poll.(*pollDesc).wait(0xc000380738, 0x72, 0x401, 0x4e0, 0xffffffffffffffff)
        /usr/local/google/home/bcmills/go/src/internal/poll/fd_poll_runtime.go:87 +0x45 fp=0xc000486560 sp=0xc000486530 pc=0x4b93d5
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/google/home/bcmills/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000380720, 0xc000268120, 0x4e0, 0x4e0, 0x0, 0x0, 0x0)
        /usr/local/google/home/bcmills/go/src/internal/poll/fd_unix.go:169 +0x19b fp=0xc0004865d0 sp=0xc000486560 pc=0x4b9ddb
os.(*File).read(...)
        /usr/local/google/home/bcmills/go/src/os/file_unix.go:263
os.(*File).Read(0xc0000b4028, 0xc000268120, 0x4e0, 0x4e0, 0x14, 0x0, 0x0)
        /usr/local/google/home/bcmills/go/src/os/file.go:116 +0x71 fp=0xc000486640 sp=0xc0004865d0 pc=0x4be9f1
bytes.(*Buffer).ReadFrom(0xc0002d4240, 0x6e5980, 0xc0000b4028, 0x7f0cb80a41d0, 0xc0002d4240, 0x70000000063c601)
        /usr/local/google/home/bcmills/go/src/bytes/buffer.go:204 +0xb1 fp=0xc0004866b0 sp=0xc000486640 pc=0x4d73a1
io.copyBuffer(0x6e5780, 0xc0002d4240, 0x6e5980, 0xc0000b4028, 0x0, 0x0, 0x0, 0xffffffffffffffff, 0xc0004867b8, 0x5eebb6)
        /usr/local/google/home/bcmills/go/src/io/io.go:391 +0x2fc fp=0xc000486728 sp=0xc0004866b0 pc=0x4a3e1c
io.Copy(...)
        /usr/local/google/home/bcmills/go/src/io/io.go:364
os/exec.(*Cmd).writerDescriptor.func1(0x2f, 0xc00087a000)
        /usr/local/google/home/bcmills/go/src/os/exec/exec.go:310 +0x63 fp=0xc0004867a0 sp=0xc000486728 pc=0x528f33
os/exec.(*Cmd).Start.func1(0xc0002d6000, 0xc0002420e0)
        /usr/local/google/home/bcmills/go/src/os/exec/exec.go:436 +0x27 fp=0xc0004867d0 sp=0xc0004867a0 pc=0x528fb7
runtime.goexit()
        /usr/local/google/home/bcmills/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0004867d8 sp=0xc0004867d0 pc=0x46dde1
created by os/exec.(*Cmd).Start
        /usr/local/google/home/bcmills/go/src/os/exec/exec.go:435 +0x608

goroutine 144660 [chan send, 8 minutes]:
runtime.gopark(0x69d768, 0xc000024418, 0x62160f, 0x2)
        /usr/local/google/home/bcmills/go/src/runtime/proc.go:304 +0xe0 fp=0xc0010ece20 sp=0xc0010ece00 pc=0x4396a0
runtime.chansend(0xc0000243c0, 0xc0010ecf0f, 0xc00008e001, 0x4e9a93, 0x69f8e0)
        /usr/local/google/home/bcmills/go/src/runtime/chan.go:236 +0x22d fp=0xc0010ecea0 sp=0xc0010ece20 pc=0x406bed
runtime.chansend1(0xc0000243c0, 0xc0010ecf0f)
        /usr/local/google/home/bcmills/go/src/runtime/chan.go:127 +0x35 fp=0xc0010eced8 sp=0xc0010ecea0 pc=0x4069b5
testing.tRunner.func1(0xc0000de6c0)
        /usr/local/google/home/bcmills/go/src/testing/testing.go:982 +0x353 fp=0xc0010ecf80 sp=0xc0010eced8 pc=0x4e9a93
testing.tRunner(0xc0000de6c0, 0x69eb08)
        /usr/local/google/home/bcmills/go/src/testing/testing.go:996 +0x10b fp=0xc0010ecfd0 sp=0xc0010ecf80 pc=0x4e566b
runtime.goexit()
        /usr/local/google/home/bcmills/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0010ecfd8 sp=0xc0010ecfd0 pc=0x46dde1
created by testing.(*T).Run
        /usr/local/google/home/bcmills/go/src/testing/testing.go:1043 +0x357

goroutine 144658 [GC worker (idle)]:
runtime.gopark(0x69d880, 0xc000f47ca0, 0xc0002e1418, 0x0)
        /usr/local/google/home/bcmills/go/src/runtime/proc.go:304 +0xe0 fp=0xc0002eef60 sp=0xc0002eef40 pc=0x4396a0
runtime.gcBgMarkWorker(0xc000036800)
        /usr/local/google/home/bcmills/go/src/runtime/mgc.go:1865 +0xff fp=0xc0002eefd8 sp=0xc0002eef60 pc=0x41e58f
runtime.goexit()
        /usr/local/google/home/bcmills/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0002eefe0 sp=0xc0002eefd8 pc=0x46dde1
created by runtime.gcBgMarkStartWorkers
        /usr/local/google/home/bcmills/go/src/runtime/mgc.go:1813 +0x77

goroutine 144645 [GC worker (idle)]:
runtime.gopark(0x69d880, 0xc0002cb8e0, 0xc000521418, 0x0)
        /usr/local/google/home/bcmills/go/src/runtime/proc.go:304 +0xe0 fp=0xc00052cf60 sp=0xc00052cf40 pc=0x4396a0
runtime.gcBgMarkWorker(0xc000034000)
        /usr/local/google/home/bcmills/go/src/runtime/mgc.go:1865 +0xff fp=0xc00052cfd8 sp=0xc00052cf60 pc=0x41e58f
runtime.goexit()
        /usr/local/google/home/bcmills/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00052cfe0 sp=0xc00052cfd8 pc=0x46dde1
created by runtime.gcBgMarkStartWorkers
        /usr/local/google/home/bcmills/go/src/runtime/mgc.go:1813 +0x77

goroutine 143713 [chan receive, 8 minutes]:
runtime.gopark(0x69d768, 0xc00008e178, 0x170e, 0x2)
        /usr/local/google/home/bcmills/go/src/runtime/proc.go:304 +0xe0 fp=0xc0002e5ef8 sp=0xc0002e5ed8 pc=0x4396a0
runtime.chanrecv(0xc00008e120, 0x0, 0x69d801, 0xc000025d40)
        /usr/local/google/home/bcmills/go/src/runtime/chan.go:525 +0x2e7 fp=0xc0002e5f88 sp=0xc0002e5ef8 pc=0x407807
runtime.chanrecv1(0xc00008e120, 0x0)
        /usr/local/google/home/bcmills/go/src/runtime/chan.go:407 +0x2b fp=0xc0002e5fb8 sp=0xc0002e5f88 pc=0x4074cb
testing.runTests.func1.1(0xc0000de000)
        /usr/local/google/home/bcmills/go/src/testing/testing.go:1305 +0x3b fp=0xc0002e5fd8 sp=0xc0002e5fb8 pc=0x4e9c5b
runtime.goexit()
        /usr/local/google/home/bcmills/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0002e5fe0 sp=0xc0002e5fd8 pc=0x46dde1
created by testing.runTests.func1
        /usr/local/google/home/bcmills/go/src/testing/testing.go:1305 +0xac

goroutine 143587 [chan send, 8 minutes]:
runtime.gopark(0x69d768, 0xc0004e6718, 0x62160f, 0x2)
        /usr/local/google/home/bcmills/go/src/runtime/proc.go:304 +0xe0 fp=0xc000256e20 sp=0xc000256e00 pc=0x4396a0
runtime.chansend(0xc0004e66c0, 0xc000256f0f, 0xc00008e001, 0x4e9a93, 0x69f8e0)
        /usr/local/google/home/bcmills/go/src/runtime/chan.go:236 +0x22d fp=0xc000256ea0 sp=0xc000256e20 pc=0x406bed
runtime.chansend1(0xc0004e66c0, 0xc000256f0f)
        /usr/local/google/home/bcmills/go/src/runtime/chan.go:127 +0x35 fp=0xc000256ed8 sp=0xc000256ea0 pc=0x4069b5
testing.tRunner.func1(0xc0003f65a0)
        /usr/local/google/home/bcmills/go/src/testing/testing.go:982 +0x353 fp=0xc000256f80 sp=0xc000256ed8 pc=0x4e9a93
testing.tRunner(0xc0003f65a0, 0x69f460)
        /usr/local/google/home/bcmills/go/src/testing/testing.go:996 +0x10b fp=0xc000256fd0 sp=0xc000256f80 pc=0x4e566b
runtime.goexit()
        /usr/local/google/home/bcmills/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000256fd8 sp=0xc000256fd0 pc=0x46dde1
created by testing.(*T).Run
        /usr/local/google/home/bcmills/go/src/testing/testing.go:1043 +0x357

goroutine 124685 [GC worker (idle)]:
runtime.gopark(0x69d880, 0xc0000b0040, 0xc000471418, 0x0)
        /usr/local/google/home/bcmills/go/src/runtime/proc.go:304 +0xe0 fp=0xc000475f60 sp=0xc000475f40 pc=0x4396a0
runtime.gcBgMarkWorker(0xc00002a000)
        /usr/local/google/home/bcmills/go/src/runtime/mgc.go:1865 +0xff fp=0xc000475fd8 sp=0xc000475f60 pc=0x41e58f
runtime.goexit()
        /usr/local/google/home/bcmills/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000475fe0 sp=0xc000475fd8 pc=0x46dde1
created by runtime.gcBgMarkStartWorkers
        /usr/local/google/home/bcmills/go/src/runtime/mgc.go:1813 +0x77
FAIL    runtime 540.043s
```

</details>

**Comment by heschik** [comment]
What makes this a deadlock? Seems to be a hang waiting for `gdb` on ` /usr/local/google/home/bcmills/go/src/runtime/runtime-gdb_test.go:463` ?

**Comment by bcmills** [comment]
I dunno — I guess it could be a hang rather than a deadlock?

Here's what appears to be the same failure mode on a builder:
[2020-01-19T20:36:10-df2999e/linux-mips64le-mengzhuo](https://build.golang.org/log/16ec7b5c105081d79b5aa26ca5f0eb4551c26bc2)

**Comment by bcmills** [comment]
The lack of useful diagnostic for this test on failure also impacts #43825.

**Comment by bcmills** [comment]
`greplogs -l -e 'goroutine \d+ \[syscall, \d+ minutes\]:\n(?:.+\n\t.+\n)*os/exec.*\n\t.+\nruntime_test\.TestGdbAutotmpTypes' --since=2022-01-21`
[2022-08-19T18:39:56-bf4e35b/linux-riscv64-jsing](https://build.golang.org/log/9995c636833c0c241808afa0e0433eae49dfbe5b)
[2022-03-25T19:04:59-2bbf383/solaris-amd64-oraclerel](https://build.golang.org/log/7abedc726c419ecd05628fd72b15fe2457e902fb)
