### ISSUE TITLE
cmd/compile: "internal compile error: … curfn mismatch" on darwin-amd64-10_11 builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#37407]
[2020-02-22T04:31:20-f9c51e3/darwin-amd64-10_11](https://build.golang.org/log/59214fc2506943a7d0a87d8d4e867428174ea718)

It's not obvious to me whether this is Darwin filesystem flakiness or a regression introduced in the recent cmd/compile refactoring. We should determine which is the case prior to the 1.15 release.

```
# fmt
<unknown line number>: internal compiler error: curfn mismatch: <N> != <node DCLFUNC>

goroutine 1 [running]:
runtime/debug.Stack(0x1a07de0, 0xc000122008, 0x0)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/src/runtime/debug/stack.go:24 +0x9d
cmd/compile/internal/gc.Fatalf(0x18a2f01, 0x18, 0xc000715278, 0x2, 0x2)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/src/cmd/compile/internal/gc/subr.go:193 +0x291
cmd/compile/internal/gc.(*Escape).newLoc(0xc0008a6780, 0xc0000cf0e0, 0xc000715300, 0xc0008aa4e0)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/src/cmd/compile/internal/gc/escape.go:1058 +0x329
cmd/compile/internal/gc.(*Escape).initFunc(0xc0008a6780, 0xc00012c6e0)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/src/cmd/compile/internal/gc/escape.go:182 +0xaf
cmd/compile/internal/gc.escapeFuncs(0xc0008a3390, 0xc, 0xe, 0xc000013201)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/src/cmd/compile/internal/gc/escape.go:156 +0xe3
cmd/compile/internal/gc.(*bottomUpVisitor).visit(0xc000715818, 0xc00012c6e0, 0xc000715428)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/src/cmd/compile/internal/gc/scc.go:118 +0x295
cmd/compile/internal/gc.(*bottomUpVisitor).visit.func1(0xc00038ff80, 0xc0007156a0)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/src/cmd/compile/internal/gc/scc.go:81 +0xaf
cmd/compile/internal/gc.inspect(0xc00038ff80, 0xc0007156a0)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/src/cmd/compile/internal/gc/syntax.go:949 +0xfc
cmd/compile/internal/gc.inspectList(0xc000442660, 0xc0007156a0)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/src/cmd/compile/internal/gc/syntax.go:962 +0x58
cmd/compile/internal/gc.inspect(0xc00038ef80, 0xc0007156a0)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/src/cmd/compile/internal/gc/syntax.go:956 +0xc8
cmd/compile/internal/gc.inspectList(0xc000442780, 0xc0007156a0)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/src/cmd/compile/internal/gc/syntax.go:962 +0x58
cmd/compile/internal/gc.inspect(0xc00038ef00, 0xc0007156a0)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/src/cmd/compile/internal/gc/syntax.go:956 +0xc8
cmd/compile/internal/gc.inspectList(0xc000442800, 0xc0007156a0)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/src/cmd/compile/internal/gc/syntax.go:962 +0x58
cmd/compile/internal/gc.inspect(0xc000379c80, 0xc0007156a0)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/src/cmd/compile/internal/gc/syntax.go:955 +0xac
cmd/compile/internal/gc.inspectList(0xc000442920, 0xc0007156a0)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/src/cmd/compile/internal/gc/syntax.go:962 +0x58
cmd/compile/internal/gc.inspect(0xc000379880, 0xc0007156a0)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/src/cmd/compile/internal/gc/syntax.go:956 +0xc8
cmd/compile/internal/gc.inspectList(0xc0004466a0, 0xc0007156a0)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/src/cmd/compile/internal/gc/syntax.go:962 +0x58
cmd/compile/internal/gc.inspect(0xc000378880, 0xc0007156a0)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/src/cmd/compile/internal/gc/syntax.go:956 +0xc8
cmd/compile/internal/gc.inspectList(0xc000446980, 0xc0007156a0)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/src/cmd/compile/internal/gc/syntax.go:962 +0x58
cmd/compile/internal/gc.(*bottomUpVisitor).visit(0xc000715818, 0xc00012d080, 0x0)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/src/cmd/compile/internal/gc/scc.go:76 +0x13d
cmd/compile/internal/gc.(*bottomUpVisitor).visit.func1(0xc0004bc880, 0xc0007157d0)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/src/cmd/compile/internal/gc/scc.go:81 +0xaf
cmd/compile/internal/gc.inspect(0xc0004bc880, 0xc0007157d0)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/src/cmd/compile/internal/gc/syntax.go:949 +0xfc
cmd/compile/internal/gc.inspectList(0xc0004460e0, 0xc0007157d0)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/src/cmd/compile/internal/gc/syntax.go:962 +0x58
cmd/compile/internal/gc.(*bottomUpVisitor).visit(0xc000715818, 0xc0004c0000, 0xbf8c49a51444cff0)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/src/cmd/compile/internal/gc/scc.go:76 +0x13d
cmd/compile/internal/gc.visitBottomUp(0xc0006f0000, 0xb2, 0xc0, 0x18ba398)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/src/cmd/compile/internal/gc/scc.go:58 +0x95
cmd/compile/internal/gc.escapes(...)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/src/cmd/compile/internal/gc/esc.go:13
cmd/compile/internal/gc.Main(0x18ba218)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/src/cmd/compile/internal/gc/main.go:675 +0x30a6
main.main()
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/src/cmd/compile/main.go:52 +0xac

go tool dist: FAILED: /private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir-host-darwin-10_11/go/pkg/tool/darwin_amd64/go_bootstrap install -gcflags=all= -ldflags=all= -a -i cmd/asm cmd/cgo cmd/compile cmd/link: exit status 2
```

CC @randall77 @josharian

**Comment by josharian** [comment]
This is exceedingly likely to be a duplicate of #37406.

**Comment by bcmills** [comment]
Duplicate of #37406
