### ISSUE TITLE
runtime: "interface {} is nil, not *main.T" on linux-amd64-noopt builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#37401]
[2020-02-22T04:31:41-059a5ac/linux-amd64-noopt](https://build.golang.org/log/9df8661fd5326a034504b9834d9e49931fdc7b41)
```
# go run run.go -- fixedbugs/issue13169.go
exit status 1
panic: interface conversion: interface {} is nil, not *main.T

goroutine 34 [running]:
main.main.func2(0xc00008c060, 0xc00008c0c0)
	/workdir/go/test/fixedbugs/issue13169.go:40 +0xc0
created by main.main
	/workdir/go/test/fixedbugs/issue13169.go:38 +0xd4
exit status 2

FAIL	fixedbugs/issue13169.go	1.089s
```

See previously #13169 (CC @aclements, @randall77, @mknyszek).

Perhaps some operation that the runtime assumes to be atomic no longer is in `noopt` mode? (#36110 may be related; CC @cherrymui)

**Comment by cherrymui** [comment]
> Perhaps some operation that the runtime assumes to be atomic no longer is in noopt mode?

I didn't mean that some atomic operations are not atomic in noopt mode. I meant it may be not intrinsified, which affects where the safe points are. That is specific to #36110.

**Comment by ianlancetaylor** [comment]
These seems to have happened exactly once.  Moving milestone to unplanned in case it ever happens again.
