### ISSUE TITLE
cmd/vet: apparent memory corruption in TestVet/httpresponse

### ISSUE THREAD

**Issue by bcmills** [golang/go#37690]
I see two different failures in `TestVet/httpresponse` that both seem to be symptoms of memory corruption:

[2020-03-05T11:56:33-cc6a8bd/darwin-amd64-10_15](https://build.golang.org/log/73f9474bfd9b72078d6eddfaadaa059b4022de35)
```
--- FAIL: TestVet (1.72s)
    --- FAIL: TestVet/httpresponse (4.11s)
        vet_test.go:162: error check failed: 
            Unmatched Errors:
            unexpected fault address 0xe487
            fatal error: fault
            [signal SIGSEGV: segmentation violation code=0x1 addr=0xe487 pc=0x100a7b0]
            goroutine 11 [running]:
            runtime.throw(0x1355e67, 0x5)
            	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/runtime/panic.go:1112 +0x72 fp=0xc000f20a98 sp=0xc000f20a68 pc=0x1032392
            runtime.sigpanic()
            	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/runtime/signal_unix.go:718 +0x3cc fp=0xc000f20ac8 sp=0xc000f20a98 pc=0x1047c4c
            runtime.convI2I(0x1302c40, 0xe487, 0xc0001e1ab0, 0x113a32a, 0x13c98e0)
            	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/runtime/iface.go:439 +0x30 fp=0xc000f20af8 sp=0xc000f20ac8 pc=0x100a7b0
            go/ast.walkStmtList(0x13c7d20, 0xc00055f4c0, 0xc000219e00, 0x4a5c7, 0xc0004d4da0)
            	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/go/ast/walk.go:32 +0x72 fp=0xc000f20b40 sp=0xc000f20af8 pc=0x11370c2
            go/ast.Walk(0x13c7d20, 0xc00055f4c0, 0x13c98e0, 0xc000216aa0)
            	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/go/ast/walk.go:224 +0x1adf fp=0xc000f20d08 sp=0xc000f20b40 pc=0x1138ccf
            go/ast.Walk(0x13c7d20, 0xc00055f4c0, 0x13c9fa0, 0xc00021e100)
            	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/go/ast/walk.go:231 +0x1c7c fp=0xc000f20ed0 sp=0xc000f20d08 pc=0x1138e6c
            go/ast.walkStmtList(0x13c7d20, 0xc00055f4c0, 0xc0001eec00, 0x5, 0x8)
            	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/go/ast/walk.go:32 +0x9e fp=0xc000f20f18 sp=0xc000f20ed0 pc=0x11370ee
            go/ast.Walk(0x13c7d20, 0xc00055f4c0, 0x13c98e0, 0xc000216b10)
            	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/go/ast/walk.go:224 +0x1adf fp=0xc000f210e0 sp=0xc000f20f18 pc=0x1138ccf
            go/ast.Walk(0x13c7d20, 0xc00055f4c0, 0x13c9fa0, 0xc00021e140)
            	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/go/ast/walk.go:231 +0x1c7c fp=0xc000f212a8 sp=0xc000f210e0 pc=0x1138e6c
            go/ast.walkStmtList(0x13c7d20, 0xc00055f4c0, 0xc00021e200, 0x3, 0x4)
            	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/go/ast/walk.go:32 +0x9e fp=0xc000f212f0 sp=0xc000f212a8 pc=0x11370ee
            go/ast.Walk(0x13c7d20, 0xc00055f4c0, 0x13c98e0, 0xc000216b40)
            	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/go/ast/walk.go:224 +0x1adf fp=0xc000f214b8 sp=0xc000f212f0 pc=0x1138ccf
            go/ast.Walk(0x13c7d20, 0xc00055f4c0, 0x13c9fa0, 0xc00021e300)
            	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/go/ast/walk.go:231 +0x1c7c fp=0xc000f21680 sp=0xc000f214b8 pc=0x1138e6c
            go/ast.walkStmtList(0x13c7d20, 0xc00055f4c0, 0xc00021a200, 0xe, 0x10)
            	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/go/ast/walk.go:32 +0x9e fp=0xc000f216c8 sp=0xc000f21680 pc=0x11370ee
            go/ast.Walk(0x13c7d20, 0xc00055f4c0, 0x13c98e0, 0xc0002177a0)
            	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/go/ast/walk.go:224 +0x1adf fp=0xc000f21890 sp=0xc000f216c8 pc=0x1138ccf
            go/ast.Walk(0x13c7d20, 0xc00055f4c0, 0x13c9de0, 0xc0002177d0)
            	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/go/ast/walk.go:344 +0xd98 fp=0xc000f21a58 sp=0xc000f21890 pc=0x1137f88
            go/ast.walkDeclList(0x13c7d20, 0xc00055f4c0, 0xc0001ccc00, 0x2b, 0x40)
            	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/go/ast/walk.go:38 +0x9e fp=0xc000f21aa0 sp=0xc000f21a58 pc=0x11371be
            go/ast.Walk(0x13c7d20, 0xc00055f4c0, 0x13c9d60, 0xc0001ef900)
            	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/go/ast/walk.go:353 +0x264e fp=0xc000f21c68 sp=0xc000f21aa0 pc=0x113983e
            go/ast.Inspect(...)
            	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/go/ast/walk.go:385
            cmd/vendor/golang.org/x/tools/go/ast/inspector.traverse(0xc0000b7c00, 0x14, 0x20, 0x5e60ebe9, 0xc000039d10, 0x10b28a6)
            	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/cmd/vendor/golang.org/x/tools/go/ast/inspector/inspector.go:157 +0x14c fp=0xc000f21cc8 sp=0xc000f21c68 pc=0x128dd2c
            cmd/vendor/golang.org/x/tools/go/ast/inspector.New(...)
            	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/cmd/vendor/golang.org/x/tools/go/ast/inspector/inspector.go:49
            cmd/vendor/golang.org/x/tools/go/analysis/passes/inspect.run(0xc000d37680, 0xe57336f, 0x15cf080, 0x0, 0x0)
            	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/cmd/vendor/golang.org/x/tools/go/analysis/passes/inspect/inspect.go:48 +0x45 fp=0xc000f21d20 sp=0xc000f21cc8 pc=0x128ebc5
            cmd/vendor/golang.org/x/tools/go/analysis/unitchecker.run.func5.1()
            	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/cmd/vendor/golang.org/x/tools/go/analysis/unitchecker/unitchecker.go:350 +0x6d8 fp=0xc000f21e68 sp=0xc000f21d20 pc=0x126f2e8
            sync.(*Once).doSlow(0xc000f152c0, 0xc000039f28)
            	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/sync/once.go:66 +0xec fp=0xc000f21eb8 sp=0xc000f21e68 pc=0x107938c
            sync.(*Once).Do(...)
            	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/sync/once.go:57
            cmd/vendor/golang.org/x/tools/go/analysis/unitchecker.run.func5(0x15c7f40, 0x0)
            	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/cmd/vendor/golang.org/x/tools/go/analysis/unitchecker/unitchecker.go:303 +0x1b3 fp=0xc000f21fa8 sp=0xc000f21eb8 pc=0x126f853
            cmd/vendor/golang.org/x/tools/go/analysis/unitchecker.run.func6.1(0xc0012e5f80, 0xc0012cb4b0, 0x15c7f40)
            	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/cmd/vendor/golang.org/x/tools/go/analysis/unitchecker/unitchecker.go:362 +0x33 fp=0xc000f21fc8 sp=0xc000f21fa8 pc=0x126f8a3
            runtime.goexit()
            	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000f21fd0 sp=0xc000f21fc8 pc=0x1060841
            created by cmd/vendor/golang.org/x/tools/go/analysis/unitchecker.run.func6
            	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/cmd/vendor/golang.org/x/tools/go/analysis/unitchecker/unitchecker.go:361 +0xa3
```

[2020-02-25T21:08:47-46f9aea/linux-mips64le-mengzhuo](https://build.golang.org/log/a5d8095256878a5e4b6dfbf9b961177eb9e0cc91)
```
--- FAIL: TestVet (1.80s)
    --- FAIL: TestVet/httpresponse (6.91s)
        vet_test.go:162: error check failed: 
            Unmatched Errors:
            runtime: pointer 0xc000966570 to unused region of span span.base()=0xc000338000 span.limit=0xc00033a000 span.state=1
            runtime: found in object at *(0xc000000180+0x28)
            object=0xc000000180 s.base()=0xc000000000 s.limit=0xc000001f80 s.spanclass=42 s.elemsize=384 s.state=mSpanInUse
             *(object+0) = 0xc00092a000
             *(object+8) = 0xc00096a000
             *(object+16) = 0xc00092a380
             *(object+24) = 0xffffffffffffffff
             *(object+32) = 0x0
             *(object+40) = 0xc000966570 <==
             *(object+48) = 0xc000180000
             *(object+56) = 0xc000965ac0
             *(object+64) = 0x83078
             *(object+72) = 0xc000000180
             *(object+80) = 0x0
             *(object+88) = 0x0
             *(object+96) = 0x0
             *(object+104) = 0x0
             *(object+112) = 0x0
             *(object+120) = 0xd6e38
             *(object+128) = 0xc000969fd8
             *(object+136) = 0x0
             *(object+144) = 0x4
             *(object+152) = 0x1
             *(object+160) = 0x0
             *(object+168) = 0xd43a7635f9e5
             *(object+176) = 0x1000000000001
             *(object+184) = 0x10000
             *(object+192) = 0x0
             *(object+200) = 0x0
             *(object+208) = 0x0
             *(object+216) = 0x0
             *(object+224) = 0x0
             *(object+232) = 0x0
             *(object+240) = 0x0
             *(object+248) = 0x0
             *(object+256) = 0x0
             *(object+264) = 0x0
             *(object+272) = 0x0
             *(object+280) = 0x82f94
             *(object+288) = 0x0
             *(object+296) = 0x4ee30
             *(object+304) = 0x0
             *(object+312) = 0x0
             *(object+320) = 0x0
             *(object+328) = 0x0
             *(object+336) = 0x0
             *(object+344) = 0x0
             *(object+352) = 0x0
             *(object+360) = 0x0
             *(object+368) = 0xffffffffffffffc0
             *(object+376) = 0x0
            fatal error: found bad pointer in Go heap (incorrect use of unsafe or cgo?)
            runtime stack:
            runtime.throw(0x3d2625, 0x3e)
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/panic.go:1112 +0x6c fp=0xc000191e40 sp=0xc000191e18 pc=0x4c144
            runtime.badPointer(0xffced17e00, 0xc000966570, 0xc000000180, 0x28)
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/mbitmap.go:380 +0x2c4 fp=0xc000191e80 sp=0xc000191e40 pc=0x2695c
            runtime.findObject(0xc000966570, 0xc000000180, 0x28, 0xfff5a6c108, 0xc000021e98, 0x1)
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/mbitmap.go:416 +0xb8 fp=0xc000191eb0 sp=0xc000191e80 pc=0x26a18
            runtime.scanobject(0xc000000180, 0xc000021e98)
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/mgcmark.go:1274 +0x2f0 fp=0xc000191f48 sp=0xc000191eb0 pc=0x34ae0
            runtime.gcDrainN(0xc000021e98, 0x10000, 0xd43a803fdc76)
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/mgcmark.go:1126 +0x1a0 fp=0xc000191f70 sp=0xc000191f48 pc=0x344e0
            runtime.gcAssistAlloc1(0xc000000180, 0x10000)
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/mgcmark.go:531 +0x140 fp=0xc000191fb8 sp=0xc000191f70 pc=0x32b10
            runtime.gcAssistAlloc.func1()
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/mgcmark.go:442 +0x44 fp=0xc000191fd0 sp=0xc000191fb8 pc=0x80124
            runtime.systemstack(0x4d2)
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/asm_mips64x.s:206 +0xa8 fp=0xc000191fd8 sp=0xc000191fd0 pc=0x83140
            runtime.mstart()
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/proc.go:1042 fp=0xc000191fd8 sp=0xc000191fd8 pc=0x525b0
            goroutine 1 [GC assist marking]:
            runtime.systemstack_switch()
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/asm_mips64x.s:158 +0x8 fp=0xc000965ac8 sp=0xc000965ac0 pc=0x83078
            runtime.gcAssistAlloc(0xc000000180)
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/mgcmark.go:441 +0x1b8 fp=0xc000965b20 sp=0xc000965ac8 pc=0x32800
            runtime.mallocgc(0x40, 0x39a4c0, 0xc000873201, 0xc000873200)
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/malloc.go:939 +0x8dc fp=0xc000965be0 sp=0xc000965b20 pc=0x1d00c
            runtime.newobject(0x39a4c0, 0xc000423f20)
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/malloc.go:1176 +0x4c fp=0xc000965c08 sp=0xc000965be0 pc=0x1d334
            go/types.(*Checker).updateExprType(0xc0001a2000, 0x440620, 0xc0002dc820, 0x43d620, 0x636d60, 0x1)
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/go/types/expr.go:470 +0x2e0 fp=0xc000965d28 sp=0xc000965c08 pc=0x2617f8
            go/types.(*Checker).convertUntyped(0xc0001a2000, 0xc00088f200, 0x43d620, 0x636d60)
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/go/types/expr.go:578 +0x4cc fp=0xc000965de8 sp=0xc000965d28 pc=0x26268c
            go/types.(*Checker).assignment(0xc0001a2000, 0xc00088f200, 0x43d620, 0x636d60, 0x3c45bc, 0x10)
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/go/types/assignments.go:46 +0x17c fp=0xc000965ee8 sp=0xc000965de8 pc=0x24c12c
            go/types.(*Checker).initVar(0xc0001a2000, 0xc0002ae230, 0xc00088f200, 0x3c45bc, 0x10, 0xc00088ed00, 0x7)
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/go/types/assignments.go:124 +0x194 fp=0xc000965f50 sp=0xc000965ee8 pc=0x24cd84
            go/types.(*Checker).initVars(0xc0001a2000, 0xc000105c20, 0x2, 0x2, 0xc0002dc880, 0x2, 0x2, 0x5ab4)
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/go/types/assignments.go:247 +0x534 fp=0xc000966060 sp=0xc000965f50 pc=0x24dd84
            go/types.(*Checker).stmt(0xc0001a2000, 0x3, 0x440de0, 0xc0002dc8a0)
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/go/types/stmt.go:447 +0x3838 fp=0xc000966b48 sp=0xc000966060 pc=0x283f90
            go/types.(*Checker).stmtList(0xc0001a2000, 0x3, 0xc0002c9c40, 0x1, 0x1)
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/go/types/stmt.go:120 +0xe8 fp=0xc000966ba0 sp=0xc000966b48 pc=0x27f148
            go/types.(*Checker).stmt(0xc0001a2000, 0x3, 0x4406a0, 0xc0002d3ef0)
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/go/types/stmt.go:484 +0x4234 fp=0xc000967688 sp=0xc000966ba0 pc=0x28498c
            go/types.(*Checker).stmt(0xc0001a2000, 0x3, 0x440b60, 0xc0002de4c0)
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/go/types/stmt.go:496 +0x45cc fp=0xc000968170 sp=0xc000967688 pc=0x284d24
            go/types.(*Checker).stmtList(0xc0001a2000, 0x3, 0xc00007b200, 0x8, 0x8)
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/go/types/stmt.go:120 +0xe8 fp=0xc0009681c8 sp=0xc000968170 pc=0x27f148
            go/types.(*Checker).stmt(0xc0001a2000, 0x3, 0x4406a0, 0xc0002e26c0)
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/go/types/stmt.go:484 +0x4234 fp=0xc000968cb0 sp=0xc0009681c8 pc=0x28498c
            go/types.(*Checker).stmt(0xc0001a2000, 0x0, 0x4409a0, 0xc0002dec80)
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/go/types/stmt.go:735 +0x1d38 fp=0xc000969798 sp=0xc000968cb0 pc=0x282490
            go/types.(*Checker).stmtList(0xc0001a2000, 0x0, 0xc000292a00, 0x9, 0x10)
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/go/types/stmt.go:120 +0xe8 fp=0xc0009697f0 sp=0xc000969798 pc=0x27f148
            go/types.(*Checker).funcBody(0xc0001a2000, 0xc00012d020, 0xc0002ca844, 0x6, 0xc0000dee10, 0xc0002e26f0, 0x0, 0x0)
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/go/types/stmt.go:42 +0x154 fp=0xc000969928 sp=0xc0009697f0 pc=0x27ea74
            go/types.(*Checker).funcDecl.func1()
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/go/types/decl.go:662 +0x74 fp=0xc000969970 sp=0xc000969928 pc=0x29083c
            go/types.(*Checker).processDelayed(0xc0001a2000, 0x0)
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/go/types/check.go:283 +0x5c fp=0xc000969990 sp=0xc000969970 pc=0x257994
            go/types.(*Checker).checkFiles(0xc0001a2000, 0xc000410ec0, 0x5, 0x8, 0x0, 0x0)
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/go/types/check.go:259 +0xc4 fp=0xc0009699d8 sp=0xc000969990 pc=0x25788c
            go/types.(*Checker).Files(...)
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/go/types/check.go:248
            go/types.(*Config).Check(0xc000410f00, 0xc000016260, 0x1c, 0xc00006c0c0, 0xc000410ec0, 0x5, 0x8, 0xc000349400, 0x0, 0xc00005c0b0, ...)
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/go/types/api.go:348 +0x148 fp=0xc000969a48 sp=0xc0009699d8 pc=0x24be28
            cmd/vendor/golang.org/x/tools/go/analysis/unitchecker.run(0xc00006c0c0, 0xc00005c000, 0xc0001d0840, 0x16, 0x16, 0x447120, 0xc0001c0658, 0xc00008dc18, 0xc0001b0e40, 0x3c2b30)
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/vendor/golang.org/x/tools/go/analysis/unitchecker/unitchecker.go:235 +0x408 fp=0xc000969c00 sp=0xc000969a48 pc=0x2c3cd8
            cmd/vendor/golang.org/x/tools/go/analysis/unitchecker.Run(0xfffb85fa14, 0x4a, 0xc0001d0840, 0x16, 0x16)
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/vendor/golang.org/x/tools/go/analysis/unitchecker/unitchecker.go:131 +0xf0 fp=0xc000969ec0 sp=0xc000969c00 pc=0x2c32c8
            cmd/vendor/golang.org/x/tools/go/analysis/unitchecker.Main(0xc0001d0840, 0x16, 0x16)
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/vendor/golang.org/x/tools/go/analysis/unitchecker/unitchecker.go:118 +0x2b8 fp=0xc000969f40 sp=0xc000969ec0 pc=0x2c2ff8
            main.main()
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/vet/main.go:35 +0x3e4 fp=0xc000969f80 sp=0xc000969f40 pc=0x3127b4
            runtime.main()
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/proc.go:204 +0x2cc fp=0xc000969fd8 sp=0xc000969f80 pc=0x4f0fc
            runtime.goexit()
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/asm_mips64x.s:646 +0x4 fp=0xc000969fd8 sp=0xc000969fd8 pc=0x8540c
```

Since `cmd/vet` uses `go/types`, this may be the same corruption observed in #37602.

CC @matloob @griesemer

**Comment by jayconrod** [comment]
Another one from a couple days ago:

https://build.golang.org/log/d3bb28b805bae2e11caa09e8915243f3ba91a96d

**Comment by ianlancetaylor** [comment]
These are all the possible failures I see in the build logs.

[2020-04-28T18:41:07-39380e8/linux-mips64le-mengzhuo](https://build.golang.org/log/d3bb28b805bae2e11caa09e8915243f3ba91a96d)
[2020-03-05T11:56:33-cc6a8bd/darwin-amd64-10_15](https://build.golang.org/log/73f9474bfd9b72078d6eddfaadaa059b4022de35)
[2020-02-25T21:08:47-46f9aea/linux-mips64le-mengzhuo](https://build.golang.org/log/a5d8095256878a5e4b6dfbf9b961177eb9e0cc91)
[2020-01-07T19:53:19-7d98da8/plan9-386-0intro](https://build.golang.org/log/d123a99a61df1d6bd16ce44b3bf3314d05df7e91)
[2020-01-02T23:00:12-a65f088/plan9-386-0intro](https://build.golang.org/log/f2484c82c8d32b873dae577b98a73ff9d8bf635f)
[2019-11-09T00:36:15-bde1968/plan9-386-0intro](https://build.golang.org/log/020d1ae685dce343bd8a1a90008aa2258988ca4c)
[2019-10-24T08:47:14-722b0e3/plan9-386-0intro](https://build.golang.org/log/a150c5b98a04710c0a80b876882668502bec9492)
[2019-07-03T23:08:27-adcb2b1/plan9-386-0intro](https://build.golang.org/log/f92b8aca190f975459d9117c52646c1f4164fe9c)
[2019-06-24T21:26:46-5f7e9ce/plan9-386-0intro](https://build.golang.org/log/08cc5f46847fb1dccd0a2fb2bb6c8a10bcd12664)

**Comment by ianlancetaylor** [comment]
Rolling forward to 1.16.

**Comment by jayconrod** [comment]
I couldn't find any recent occurrences of this, so closing the issue as obsolete. The most similar one I saw was this one, where it seems to be running out of memory:

https://build.golang.org/log/6fc90d327776abc66c34c0956d283ab5e4e6235d
