### ISSUE TITLE
runtime: TestGdbPythonCgo is flaky on linux-mips64le-rtrk builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#37794]
[2020-03-10T16:25:09-9f74f0a/linux-mips64le-rtrk](https://build.golang.org/log/831e6d961dc437580e7a28b21de9eda7f58bc052)
[2020-02-01T06:01:05-866920a/linux-mips64le-rtrk](https://build.golang.org/log/ad72868121a4b2d90e55564ce3555ccb31990fb1)
[2019-11-27T16:41:28-b11d02e/linux-mips64le-rtrk](https://build.golang.org/log/29671fce6fe13a427763ea98c037a631cb003738)
[2019-11-19T02:41:53-2d8c199/linux-mips64le-rtrk](https://build.golang.org/log/edacd43bb72f84c16e2aedd1f92d82a3662564cb)
[2019-11-15T18:31:19-398f9e1/linux-mips64le-rtrk](https://build.golang.org/log/093f96e39ec0226e76e0911e3b6e9413282060ca)
[2019-11-13T15:52:21-bf49905/linux-mips64le-rtrk](https://build.golang.org/log/e70febbaa80764d873d914f0588b3d46edfd3e02)
[2019-11-12T22:30:48-995ade8/linux-mips64le-rtrk](https://build.golang.org/log/12463488e52cafb2ce5ab8b9f0d1caec3ebf2196)

CC @ianlancetaylor @bogojevic @milanknezevic 

```
##### GOMAXPROCS=2 runtime -cpu=1,2,4 -quick
--- FAIL: TestGdbPythonCgo (6.02s)
    runtime-gdb_test.go:69: gdb version 8.2
    runtime-gdb_test.go:236: gdb output: Loading Go Runtime support.
        Loading Go Runtime support.
        Breakpoint 1 at 0x1200ad4b4: file /tmp/gobuilder-mips64le/tmp/go-build883242937/main.go, line 15.
        Couldn't get registers: No such process.
        BEGIN info goroutines
        Traceback (most recent call last):
          File "/tmp/gobuilder-mips64le/go/src/runtime/runtime-gdb.py", line 442, in invoke
            for ptr in SliceValue(gdb.parse_and_eval("'runtime.allgs'")):
          File "/tmp/gobuilder-mips64le/go/src/runtime/runtime-gdb.py", line 91, in __getitem__
            if i < 0 or i >= self.len:
          File "/tmp/gobuilder-mips64le/go/src/runtime/runtime-gdb.py", line 84, in len
            return int(self.val['len'])
        gdb.MemoryError: Cannot access memory at address 0x120193958
        Error occurred in Python command: Cannot access memory at address 0x120193958
        END
        BEGIN print mapvar
        No symbol "mapvar" in current context.
        END
        BEGIN print strvar
        No symbol "strvar" in current context.
        END
        BEGIN info locals
        No frame selected.
        END
        BEGIN goroutine 1 bt
        Traceback (most recent call last):
          File "/tmp/gobuilder-mips64le/go/src/runtime/runtime-gdb.py", line 536, in invoke
            self.invoke_per_goid(goid, cmd)
          File "/tmp/gobuilder-mips64le/go/src/runtime/runtime-gdb.py", line 539, in invoke_per_goid
            pc, sp = find_goroutine(goid)
          File "/tmp/gobuilder-mips64le/go/src/runtime/runtime-gdb.py", line 467, in find_goroutine
            for ptr in SliceValue(gdb.parse_and_eval("'runtime.allgs'")):
          File "/tmp/gobuilder-mips64le/go/src/runtime/runtime-gdb.py", line 91, in __getitem__
            if i < 0 or i >= self.len:
          File "/tmp/gobuilder-mips64le/go/src/runtime/runtime-gdb.py", line 84, in len
            return int(self.val['len'])
        gdb.MemoryError: Cannot access memory at address 0x120193958
        Error occurred in Python command: Cannot access memory at address 0x120193958
        END
        BEGIN goroutine 2 bt
        Traceback (most recent call last):
          File "/tmp/gobuilder-mips64le/go/src/runtime/runtime-gdb.py", line 536, in invoke
            self.invoke_per_goid(goid, cmd)
          File "/tmp/gobuilder-mips64le/go/src/runtime/runtime-gdb.py", line 539, in invoke_per_goid
            pc, sp = find_goroutine(goid)
          File "/tmp/gobuilder-mips64le/go/src/runtime/runtime-gdb.py", line 467, in find_goroutine
            for ptr in SliceValue(gdb.parse_and_eval("'runtime.allgs'")):
          File "/tmp/gobuilder-mips64le/go/src/runtime/runtime-gdb.py", line 91, in __getitem__
            if i < 0 or i >= self.len:
          File "/tmp/gobuilder-mips64le/go/src/runtime/runtime-gdb.py", line 84, in len
            return int(self.val['len'])
        gdb.MemoryError: Cannot access memory at address 0x120193958
        Error occurred in Python command: Cannot access memory at address 0x120193958
        END
        BEGIN goroutine all bt
        Traceback (most recent call last):
          File "/tmp/gobuilder-mips64le/go/src/runtime/runtime-gdb.py", line 530, in invoke
            for ptr in SliceValue(gdb.parse_and_eval("'runtime.allgs'")):
          File "/tmp/gobuilder-mips64le/go/src/runtime/runtime-gdb.py", line 91, in __getitem__
            if i < 0 or i >= self.len:
          File "/tmp/gobuilder-mips64le/go/src/runtime/runtime-gdb.py", line 84, in len
            return int(self.val['len'])
        gdb.MemoryError: Cannot access memory at address 0x120193958
        Error occurred in Python command: Cannot access memory at address 0x120193958
        END
        Breakpoint 2 at 0x1200ad55c: file /tmp/gobuilder-mips64le/tmp/go-build883242937/main.go, line 20.
        Cannot execute this command while the selected thread is running.
        BEGIN goroutine 1 bt at the end
        Traceback (most recent call last):
          File "/tmp/gobuilder-mips64le/go/src/runtime/runtime-gdb.py", line 536, in invoke
            self.invoke_per_goid(goid, cmd)
          File "/tmp/gobuilder-mips64le/go/src/runtime/runtime-gdb.py", line 539, in invoke_per_goid
            pc, sp = find_goroutine(goid)
          File "/tmp/gobuilder-mips64le/go/src/runtime/runtime-gdb.py", line 467, in find_goroutine
            for ptr in SliceValue(gdb.parse_and_eval("'runtime.allgs'")):
          File "/tmp/gobuilder-mips64le/go/src/runtime/runtime-gdb.py", line 91, in __getitem__
            if i < 0 or i >= self.len:
          File "/tmp/gobuilder-mips64le/go/src/runtime/runtime-gdb.py", line 84, in len
            return int(self.val['len'])
        gdb.MemoryError: Cannot access memory at address 0x120193958
        Error occurred in Python command: Cannot access memory at address 0x120193958
        END
        
    runtime-gdb_test.go:265: info goroutines failed: Traceback (most recent call last):
          File "/tmp/gobuilder-mips64le/go/src/runtime/runtime-gdb.py", line 442, in invoke
            for ptr in SliceValue(gdb.parse_and_eval("'runtime.allgs'")):
          File "/tmp/gobuilder-mips64le/go/src/runtime/runtime-gdb.py", line 91, in __getitem__
            if i < 0 or i >= self.len:
          File "/tmp/gobuilder-mips64le/go/src/runtime/runtime-gdb.py", line 84, in len
            return int(self.val['len'])
        gdb.MemoryError: Cannot access memory at address 0x120193958
        Error occurred in Python command: Cannot access memory at address 0x120193958
FAIL
FAIL	runtime	177.962s
```

**Comment by bcmills** [comment]
See also #35743, #20821.

**Comment by bcmills** [comment]
[2020-09-15T14:51:32-f1c400a/linux-mips64le-rtrk](https://build.golang.org/log/7bae25137c9c06114a2d4ca36565deb772aabf70)
[2020-08-28T20:01:41-54e18f1/linux-mips64le-rtrk](https://build.golang.org/log/b3eca055cfda272dd89dff595812d2f92e67d72a)
[2020-03-25T20:14:03-e8be350/linux-mips64le-rtrk](https://build.golang.org/log/91f145158fc2cb666232010d73c7bd3fc2b884fa)

**Comment by bcmills** [comment]
`greplogs --dashboard -md -l -e '(?ms)FAIL: TestGdbPythonCgo .*Cannot access memory at address' --since=2020-09-17`

[2022-01-07T18:20:24-ade5488/linux-mips64le-rtrk](https://build.golang.org/log/812340e071dd7c39a2ad4cf28ebd7c5f63fcfda8)
[2021-12-20T15:13:56-7c94355/linux-mips64le-rtrk](https://build.golang.org/log/49a52c7881ed65e405589fd3786301780b2b6602)
[2021-12-07T21:54:30-cf1ec17/linux-mips64le-rtrk](https://build.golang.org/log/504b2843bdd596b7e48bcb866088f427fe955498)
[2021-11-13T00:23:16-39bc666/linux-mips64le-rtrk](https://build.golang.org/log/fcdfc9f0920c2ae1bd64b2d568abcf6337f2549c)
[2021-09-17T21:29:32-3fa7dbe/linux-mips64le-rtrk](https://build.golang.org/log/c9add59678307e2a7a6d832bbe7db74cf88ef29c)
[2021-05-26T22:43:54-1d5298d/linux-mips64le-rtrk](https://build.golang.org/log/cd74963ca3e80df4bd17199f0d9478ca299307ed)
[2021-04-02T01:13:58-41e8a9f/linux-mips64le-rtrk](https://build.golang.org/log/d04fbfaaed6eb65312f44f0054aa74411b820ef1)
[2021-03-23T05:11:39-e7aa0f9/linux-mips64le-rtrk](https://build.golang.org/log/9fafe3faf28d37ee69dc7e127b7545dfcad7625a)

**Comment by bcmills** [comment]
This test is still flaking regularly, creating noise in the dashboard and potentially masking other issues.

@bogojevic, @milanknezevic: is this a known bug for the `gdb` version installed on this builder? Is the `gdb` binary current, and if not can it be upgraded to see whether the underlying problem has been fixed?

**Comment by bcmills** [comment]
There is already a skip on this builder for `mipsle` and `mips64` due to #18784. 😠
