### ISSUE TITLE
sync/atomic: TestSwapPointer violates checkptr rules

### ISSUE THREAD

**Issue by randall77** [golang/go#38210]
When running the race detector on the linux/arm64 builder, I get this error:
```
fatal error: checkptr: pointer arithmetic result points to invalid allocation

goroutine 24 [running]:
runtime.throw(0x1f986e, 0x40)
	/workdir/go/src/runtime/panic.go:1116 +0x54 fp=0x4000050dc0 sp=0x4000050d90 pc=0x6946c
runtime.checkptrArithmetic(0x4000000000, 0x0, 0x0, 0x0)
	/workdir/go/src/runtime/checkptr.go:43 +0xbc fp=0x4000050df0 sp=0x4000050dc0 pc=0x3e924
sync/atomic_test.TestSwapPointer(0x40001526c0)
	/workdir/go/src/sync/atomic/atomic_test.go:168 +0x10c fp=0x4000050ec0 sp=0x4000050df0 pc=0x18be64
```

The test is clearly doing things that violate the checkptr rules. It constructs pointers which are powers of 2, starting at 2^16, and makes sure SwapPointer handles them correctly. But one of those powers of two, `0x4000000000`, just happens to point to a bad place in the heap.

This test probably needs to be rewritten to use valid pointers.

This is blocking the building of new race detector syso files for 1.15, so this issue is blocking 1.15 as well.

cc: @mdempsky

**Comment by randall77** [comment]
@dvyukov who wrote the original test.
