### ISSUE TITLE
x/sys/windows/svc/mgr: "checkptr: converted pointer straddles multiple allocations"

### ISSUE THREAD

**Issue by bcmills** [golang/go#38355]
https://build.golang.org/log/4a338e2056cedf9dae88f398a18c4418852cfccb

```
fatal error: checkptr: converted pointer straddles multiple allocations

goroutine 6 [running]:
runtime.throw(0x653a77, 0x3a)
	C:/workdir/go/src/runtime/panic.go:1116 +0x79 fp=0xc000059b30 sp=0xc000059b00 pc=0x472dc9
runtime.checkptrAlignment(0xc0001a8440, 0x611080, 0x1)
	C:/workdir/go/src/runtime/checkptr.go:20 +0xc5 fp=0xc000059b60 sp=0xc000059b30 pc=0x443865
golang.org/x/sys/windows/svc/mgr.toString(...)
	C:/workdir/gopath/src/golang.org/x/sys/windows/svc/mgr/config.go:53
golang.org/x/sys/windows/svc/mgr.(*Service).Config(0xc000004660, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	C:/workdir/gopath/src/golang.org/x/sys/windows/svc/mgr/config.go:113 +0x7e1 fp=0xc000059d10 sp=0xc000059b60 pc=0x5f0841
golang.org/x/sys/windows/svc/mgr_test.TestOpenLanManServer(0xc000062280)
	C:/workdir/gopath/src/golang.org/x/sys/windows/svc/mgr/mgr_test.go:37 +0x279 fp=0xc000059ed0 sp=0xc000059d10 pc=0x5f36b9
testing.tRunner(0xc000062280, 0x654648)
	C:/workdir/go/src/testing/testing.go:1022 +0x1f3 fp=0xc000059fd0 sp=0xc000059ed0 pc=0x575e33
runtime.goexit()
	C:/workdir/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000059fd8 sp=0xc000059fd0 pc=0x4a7ed1
created by testing.(*T).Run
	C:/workdir/go/src/testing/testing.go:1073 +0x6ab

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000062140, 0x64be28, 0x14, 0x654648, 0x0)
	C:/workdir/go/src/testing/testing.go:1074 +0x6e3
testing.runTests.func1(0xc000062140)
	C:/workdir/go/src/testing/testing.go:1342 +0xae
testing.tRunner(0xc000062140, 0xc000187ce0)
	C:/workdir/go/src/testing/testing.go:1022 +0x1f3
testing.runTests(0xc0000045e0, 0x7b8480, 0x2, 0x2, 0xbf9c2ec3a6e18978, 0x8bb313f171, 0x7c0ac0, 0xc000066e58)
	C:/workdir/go/src/testing/testing.go:1340 +0x58b
testing.(*M).Run(0xc000018080, 0x0)
	C:/workdir/go/src/testing/testing.go:1250 +0x3ae
main.main()
	_testmain.go:47 +0x221
FAIL	golang.org/x/sys/windows/svc/mgr	0.063s
```

CC @alexbrainman @zx2c4; see also #34972.

**Comment by andybons** [comment]
@bcmills should this be a release blocker?

**Comment by bcmills** [comment]
I don't think this needs to be a release-blocker: nothing in the standard library imports this package.

(It would be _nice_ if we could fix this ahead of the release, though.)
