### ISSUE TITLE
go/test2json: panic in goroutine results in missing Action=Fail TestEvent

### ISSUE THREAD

**Issue by dnephin** [golang/go#38382]
Related to #37555

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOOS=linux
GOARCH=amd64
</pre></details>

### What did you do?

```go
package mypkg

import (
	"testing"
	"time"
)

func Test_PanicInGoroutine(t *testing.T) {
	go func() { panic("panicing in a goroutine") }()
	time.Sleep(10 * time.Millisecond)
}
```

```
$ go test 
panic: panicing in a goroutine

goroutine 7 [running]:
gotest.tools/gotestsum/tmp2.Test_PanicInGoroutine.func1()
	/home/daniel/pers/code/gotestsum/tmp2/main_test.go:9 +0x39
created by gotest.tools/gotestsum/tmp2.Test_PanicInGoroutine
	/home/daniel/pers/code/gotestsum/tmp2/main_test.go:9 +0x35
FAIL	gotest.tools/gotestsum/tmp2	0.003s
FAIL
```

```
$ go test -json
{"Time":"2020-04-11T18:36:29.705478289-04:00","Action":"run","Package":"gotest.tools/gotestsum/tmp2","Test":"Test_PanicInGoroutine"}
{"Time":"2020-04-11T18:36:29.705575001-04:00","Action":"output","Package":"gotest.tools/gotestsum/tmp2","Test":"Test_PanicInGoroutine","Output":"=== RUN   Test_PanicInGoroutine\n"}
{"Time":"2020-04-11T18:36:29.707652936-04:00","Action":"output","Package":"gotest.tools/gotestsum/tmp2","Test":"Test_PanicInGoroutine","Output":"panic: panicing in a goroutine\n"}
{"Time":"2020-04-11T18:36:29.707663408-04:00","Action":"output","Package":"gotest.tools/gotestsum/tmp2","Test":"Test_PanicInGoroutine","Output":"\n"}
{"Time":"2020-04-11T18:36:29.707666872-04:00","Action":"output","Package":"gotest.tools/gotestsum/tmp2","Test":"Test_PanicInGoroutine","Output":"goroutine 7 [running]:\n"}
{"Time":"2020-04-11T18:36:29.707669584-04:00","Action":"output","Package":"gotest.tools/gotestsum/tmp2","Test":"Test_PanicInGoroutine","Output":"gotest.tools/gotestsum/tmp2.Test_PanicInGoroutine.func1()\n"}
{"Time":"2020-04-11T18:36:29.707675539-04:00","Action":"output","Package":"gotest.tools/gotestsum/tmp2","Test":"Test_PanicInGoroutine","Output":"\t/home/daniel/pers/code/gotestsum/tmp2/main_test.go:9 +0x39\n"}
{"Time":"2020-04-11T18:36:29.707688443-04:00","Action":"output","Package":"gotest.tools/gotestsum/tmp2","Test":"Test_PanicInGoroutine","Output":"created by gotest.tools/gotestsum/tmp2.Test_PanicInGoroutine\n"}
{"Time":"2020-04-11T18:36:29.707695646-04:00","Action":"output","Package":"gotest.tools/gotestsum/tmp2","Test":"Test_PanicInGoroutine","Output":"\t/home/daniel/pers/code/gotestsum/tmp2/main_test.go:9 +0x35\n"}
{"Time":"2020-04-11T18:36:29.707843506-04:00","Action":"output","Package":"gotest.tools/gotestsum/tmp2","Output":"FAIL\tgotest.tools/gotestsum/tmp2\t0.003s\n"}
{"Time":"2020-04-11T18:36:29.707855313-04:00","Action":"fail","Package":"gotest.tools/gotestsum/tmp2","Elapsed":0.003}
```

### What did you expect to see?

In go1.13 and earlier I received the following TestEvent:

```
{"Time":"2020-04-11T22:37:41.54673436Z","Action":"fail","Package":"gotest.tools/gotestsum/tmp2","Test":"Test_PanicInGoroutine","Elapsed":0.004}
```

### What did you see instead?

That event was missing. There is an `Action=fail` for the package, but none for the test.

**Comment by andybons** [comment]
@bcmills @jayconrod @matloob

**Comment by bcmills** [comment]
The new output seems correct to me. The goroutine that panics may not be related in any way to the test that was running during the panic, so the failure should not be attributed to that specific test.

(Consider, for example: https://play.golang.org/p/C9JJsDkzOhM.)

**Comment by jayconrod** [comment]
+1. Not sure whether this was changed intentionally, but the new behavior seems more correct. A panic in a goroutine other than the one running a test can't always be attributed to a specific test. It could have been started by a parallel test, a previous test, `TestMain`, or something else.

**Comment by dnephin** [comment]
Shouldn't any test which has a `Action=run` have a corresponding `Action=pass` or `fail` ? That seemed to be the case in previous versions of Go. This test has failed, but there is no `Action=fail` for the test.

**Comment by bcmills** [comment]
> Shouldn't any test which has an `Action=run` have a corresponding `Action=pass` or `fail` ?

No. If the process exits before the test function completes, and nothing in the test so far has invoked [`(*T).Fail`](https://golang.org/pkg/testing/#T.Fail) then the test has neither passed nor failed, so it would be inaccurate to report any result for it. (#29062 is related.)

**Comment by bcmills** [comment]
> The panic is already associated with the test. The output TestEvent has the test name on it.

Aha, _that_ is a bug!

**Comment by bcmills** [comment]
But maybe that bug is more helpful than it is harmful: the goroutine isn't _necessarily_ associated with the currently-running test, but background-goroutine panics probably do relate to the running test more often than not.

**Comment by dmitshur** [comment]
Based on the conversation above, I believe it's safe to remove WaitingForInfo label by now. If that isn't true, please feel free to add it again and specify what information is needed.

**Comment by rsc** [comment]
I believe this output is correct, per the discussion above. The test function did not explicitly fail. The test died instead. That's a different kind of outcome, and it has a different kind of output.

**Comment by dnephin** [comment]
But a panic generally **does** result in an explicit fail event. Consider these two examples using go1.19.2:

```go
func Test_PanicInGoroutine(t *testing.T) {
	go func() { panic("panicing in a goroutine") }()
	time.Sleep(10 * time.Millisecond)
}
```

**Output:** (no fail event for the test)
```
{"Time":"2022-10-15T13:02:00.320120402-04:00","Action":"run","Package":"gotest.tools/v3/tmp","Test":"Test_PanicInGoroutine"}
{"Time":"2022-10-15T13:02:00.320163078-04:00","Action":"output","Package":"gotest.tools/v3/tmp","Test":"Test_PanicInGoroutine","Output":"=== RUN   Test_PanicInGoroutine\n"}
{"Time":"2022-10-15T13:02:00.322259556-04:00","Action":"output","Package":"gotest.tools/v3/tmp","Test":"Test_PanicInGoroutine","Output":"panic: panicing in a goroutine\n"}
{"Time":"2022-10-15T13:02:00.322267286-04:00","Action":"output","Package":"gotest.tools/v3/tmp","Test":"Test_PanicInGoroutine","Output":"\n"}
{"Time":"2022-10-15T13:02:00.322269464-04:00","Action":"output","Package":"gotest.tools/v3/tmp","Test":"Test_PanicInGoroutine","Output":"goroutine 7 [running]:\n"}
{"Time":"2022-10-15T13:02:00.322271383-04:00","Action":"output","Package":"gotest.tools/v3/tmp","Test":"Test_PanicInGoroutine","Output":"gotest.tools/v3/tmp.Test_PanicInGoroutine.func1()\n"}
{"Time":"2022-10-15T13:02:00.322273757-04:00","Action":"output","Package":"gotest.tools/v3/tmp","Test":"Test_PanicInGoroutine","Output":"\t/home/daniel/pers/code/gotest.tools/tmp/main_test.go:9 +0x27\n"}
{"Time":"2022-10-15T13:02:00.322275633-04:00","Action":"output","Package":"gotest.tools/v3/tmp","Test":"Test_PanicInGoroutine","Output":"created by gotest.tools/v3/tmp.Test_PanicInGoroutine\n"}
{"Time":"2022-10-15T13:02:00.322277138-04:00","Action":"output","Package":"gotest.tools/v3/tmp","Test":"Test_PanicInGoroutine","Output":"\t/home/daniel/pers/code/gotest.tools/tmp/main_test.go:9 +0x25\n"}
{"Time":"2022-10-15T13:02:00.322411598-04:00","Action":"output","Package":"gotest.tools/v3/tmp","Output":"FAIL\tgotest.tools/v3/tmp\t0.003s\n"}
{"Time":"2022-10-15T13:02:00.322419607-04:00","Action":"fail","Package":"gotest.tools/v3/tmp","Elapsed":0.003}
```

compare this to

```go
func Test_PanicInTest(t *testing.T) {
	panic("panicing in a test")
}
```

**Output**: (includes a test fail event)

```
{"Time":"2022-10-15T13:02:50.132424104-04:00","Action":"run","Package":"gotest.tools/v3/tmp","Test":"Test_PanicInTest"}
{"Time":"2022-10-15T13:02:50.132473025-04:00","Action":"output","Package":"gotest.tools/v3/tmp","Test":"Test_PanicInTest","Output":"=== RUN   Test_PanicInTest\n"}
{"Time":"2022-10-15T13:02:50.132484758-04:00","Action":"output","Package":"gotest.tools/v3/tmp","Test":"Test_PanicInTest","Output":"--- FAIL: Test_PanicInTest (0.00s)\n"}
{"Time":"2022-10-15T13:02:50.134605362-04:00","Action":"output","Package":"gotest.tools/v3/tmp","Test":"Test_PanicInTest","Output":"panic: panicing in a test [recovered]\n"}
{"Time":"2022-10-15T13:02:50.134613159-04:00","Action":"output","Package":"gotest.tools/v3/tmp","Test":"Test_PanicInTest","Output":"\tpanic: panicing in a test\n"}
{"Time":"2022-10-15T13:02:50.134615738-04:00","Action":"output","Package":"gotest.tools/v3/tmp","Test":"Test_PanicInTest","Output":"\n"}
{"Time":"2022-10-15T13:02:50.134617376-04:00","Action":"output","Package":"gotest.tools/v3/tmp","Test":"Test_PanicInTest","Output":"goroutine 6 [running]:\n"}
{"Time":"2022-10-15T13:02:50.134619005-04:00","Action":"output","Package":"gotest.tools/v3/tmp","Test":"Test_PanicInTest","Output":"testing.tRunner.func1.2({0x503180, 0x5517b8})\n"}
{"Time":"2022-10-15T13:02:50.134623868-04:00","Action":"output","Package":"gotest.tools/v3/tmp","Test":"Test_PanicInTest","Output":"\t/opt/go1.19/src/testing/testing.go:1396 +0x24e\n"}
{"Time":"2022-10-15T13:02:50.134625589-04:00","Action":"output","Package":"gotest.tools/v3/tmp","Test":"Test_PanicInTest","Output":"testing.tRunner.func1()\n"}
{"Time":"2022-10-15T13:02:50.134626971-04:00","Action":"output","Package":"gotest.tools/v3/tmp","Test":"Test_PanicInTest","Output":"\t/opt/go1.19/src/testing/testing.go:1399 +0x39f\n"}
{"Time":"2022-10-15T13:02:50.134628421-04:00","Action":"output","Package":"gotest.tools/v3/tmp","Test":"Test_PanicInTest","Output":"panic({0x503180, 0x5517b8})\n"}
{"Time":"2022-10-15T13:02:50.134629781-04:00","Action":"output","Package":"gotest.tools/v3/tmp","Test":"Test_PanicInTest","Output":"\t/opt/go1.19/src/runtime/panic.go:884 +0x212\n"}
{"Time":"2022-10-15T13:02:50.134631198-04:00","Action":"output","Package":"gotest.tools/v3/tmp","Test":"Test_PanicInTest","Output":"gotest.tools/v3/tmp.Test_PanicInTest(0x0?)\n"}
{"Time":"2022-10-15T13:02:50.134632618-04:00","Action":"output","Package":"gotest.tools/v3/tmp","Test":"Test_PanicInTest","Output":"\t/home/daniel/pers/code/gotest.tools/tmp/main_test.go:8 +0x27\n"}
{"Time":"2022-10-15T13:02:50.134634435-04:00","Action":"output","Package":"gotest.tools/v3/tmp","Test":"Test_PanicInTest","Output":"testing.tRunner(0xc000007860, 0x52f338)\n"}
{"Time":"2022-10-15T13:02:50.134635847-04:00","Action":"output","Package":"gotest.tools/v3/tmp","Test":"Test_PanicInTest","Output":"\t/opt/go1.19/src/testing/testing.go:1446 +0x10b\n"}
{"Time":"2022-10-15T13:02:50.134637274-04:00","Action":"output","Package":"gotest.tools/v3/tmp","Test":"Test_PanicInTest","Output":"created by testing.(*T).Run\n"}
{"Time":"2022-10-15T13:02:50.134713803-04:00","Action":"output","Package":"gotest.tools/v3/tmp","Test":"Test_PanicInTest","Output":"\t/opt/go1.19/src/testing/testing.go:1493 +0x35f\n"}
{"Time":"2022-10-15T13:02:50.134873903-04:00","Action":"fail","Package":"gotest.tools/v3/tmp","Test":"Test_PanicInTest","Elapsed":0}
{"Time":"2022-10-15T13:02:50.134885688-04:00","Action":"output","Package":"gotest.tools/v3/tmp","Output":"FAIL\tgotest.tools/v3/tmp\t0.003s\n"}
{"Time":"2022-10-15T13:02:50.134890572-04:00","Action":"fail","Package":"gotest.tools/v3/tmp","Elapsed":0.003}
```

In both cases the test did not explicitly fail, but in one case we get the correct events, and the other we do not.

How are tools that use the `test2json` output supposed to deal with this? Are they expected to have to parse the full output to figure out that the test panicked? Isn't the purpose of the `Action` field in events to communicate the result of a test? A lack of any pass or fail for a test case seems ambiguous. 

@rsc could I ask you to reconsider this?
