### ISSUE TITLE
x/sys/windows/svc/mgr: checkptr: converted pointer straddles multiple allocations on windows-amd64-race builders

### ISSUE THREAD

**Issue by andybons** [golang/go#38705]
Example failure log: https://build.golang.org/log/34d1ea78afca069b89f8d88d949a245ed2276bc0

```
ok  	golang.org/x/sys/cpu	1.055s
?   	golang.org/x/sys/unix	[no test files]
ok  	golang.org/x/sys/windows	1.064s
?   	golang.org/x/sys/windows/mkwinsyscall	[no test files]
ok  	golang.org/x/sys/windows/registry	1.049s
ok  	golang.org/x/sys/windows/svc	1.044s
?   	golang.org/x/sys/windows/svc/debug	[no test files]
ok  	golang.org/x/sys/windows/svc/eventlog	1.043s
?   	golang.org/x/sys/windows/svc/example	[no test files]
fatal error: checkptr: converted pointer straddles multiple allocations

goroutine 19 [running]:
runtime.throw(0x6577b2, 0x3a)
	C:/workdir/go/src/runtime/panic.go:1116 +0x79 fp=0xc000053b28 sp=0xc000053af8 pc=0x473119
runtime.checkptrAlignment(0xc000168440, 0x613060, 0x1)
	C:/workdir/go/src/runtime/checkptr.go:20 +0xc5 fp=0xc000053b58 sp=0xc000053b28 pc=0x443895
golang.org/x/sys/windows/svc/mgr.toString(...)
	C:/workdir/gopath/src/golang.org/x/sys/windows/svc/mgr/config.go:53
golang.org/x/sys/windows/svc/mgr.(*Service).Config(0xc000110620, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	C:/workdir/gopath/src/golang.org/x/sys/windows/svc/mgr/config.go:113 +0x7dd fp=0xc000053d08 sp=0xc000053b58 pc=0x5f414d
golang.org/x/sys/windows/svc/mgr_test.TestOpenLanManServer(0xc000112280)
	C:/workdir/gopath/src/golang.org/x/sys/windows/svc/mgr/mgr_test.go:37 +0x2d7 fp=0xc000053ed0 sp=0xc000053d08 pc=0x5f7077
testing.tRunner(0xc000112280, 0x658380)
	C:/workdir/go/src/testing/testing.go:1035 +0x1f3 fp=0xc000053fd0 sp=0xc000053ed0 pc=0x578863
runtime.goexit()
	C:/workdir/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000053fd8 sp=0xc000053fd0 pc=0x4a55f1
created by testing.(*T).Run
	C:/workdir/go/src/testing/testing.go:1086 +0x6ab

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000112140, 0x64fb33, 0x14, 0x658380, 0x0)
	C:/workdir/go/src/testing/testing.go:1087 +0x6e3
testing.runTests.func1(0xc000112140)
	C:/workdir/go/src/testing/testing.go:1355 +0xae
testing.tRunner(0xc000112140, 0xc000141ce0)
	C:/workdir/go/src/testing/testing.go:1035 +0x1f3
testing.runTests(0xc0001105a0, 0x7bd480, 0x2, 0x2, 0xbfa1e517b53e2f58, 0x8bb3050afd, 0x7c5ae0, 0x1)
	C:/workdir/go/src/testing/testing.go:1353 +0x58b
testing.(*M).Run(0xc000172000, 0x0)
	C:/workdir/go/src/testing/testing.go:1263 +0x3a9
main.main()
	_testmain.go:47 +0x221
FAIL	golang.org/x/sys/windows/svc/mgr	0.046s
FAIL
```

/cc @zx2c4 @alexbrainman

**Comment by alexbrainman** [comment]
@andybons dup of #38355 ?

Alex

**Comment by andybons** [comment]
@alexbrainman sigh. I <3 GitHub search. Thanks.

**Comment by andybons** [comment]
Duplicate of #38355
