### ISSUE TITLE
cmd/go: test timeouts without useful debugging output on darwin builders

### ISSUE THREAD

**Issue by bcmills** [golang/go#38768]
There are numerous occasional test timeouts on the `darwin-amd64-race` builder in the logs.

I note that the `windows-amd64-race` builder sets `GO_TEST_TIMEOUT_SCALE=2`:
https://github.com/golang/build/blob/916311cec4e1738aae572fe49767cebdc0351144/dashboard/builders.go#L2067

I suspect that we may need to do the same for the `darwin-amd64-race` builder to reduce flakiness.

CC @andybons 

[2020-04-27T23:05:16-42c4899/darwin-amd64-race](https://build.golang.org/log/a17781c34fce0f73f5d9cfffe93437aa80eddad4)
[2020-04-17T04:26:54-29d925d/darwin-amd64-race](https://build.golang.org/log/6a90beedd0089308953739222b4af9d5b014f17e)
[2020-04-16T15:31:20-4eaf855/darwin-amd64-race](https://build.golang.org/log/ab0a7649d79dcf71301d1c2d9e26dc3dd581884c)
[2020-04-10T18:45:24-37470c0/darwin-amd64-race](https://build.golang.org/log/ca21c3d6b27efe227f34b6e4e84dd96bf4d02fe9)
[2019-10-11T16:34:01-ba108c9/darwin-amd64-race](https://build.golang.org/log/160cb757981d5c1e4df1d94ff36b54eccd9922f7)
[2019-10-04T21:22:55-5f4aa5d/darwin-amd64-race](https://build.golang.org/log/f1bbcc56f8b0a11004fddd58fdf1942d658c9e1c)
[2019-09-24T04:19:31-e29d276/darwin-amd64-race](https://build.golang.org/log/96aa6d382799b872cbedeb56e3b9d2076acc6546)
[2019-09-16T22:14:49-115e4c9/darwin-amd64-race](https://build.golang.org/log/55dbba50af52c16a8c77fe9287b1567604ad7eaa)
[2019-09-06T21:22:26-8a8cf5b/darwin-amd64-race](https://build.golang.org/log/06e7ec855e55f254cddb9881def65b248227bf1e)
[2019-06-29T13:17:15-623d653/darwin-amd64-race](https://build.golang.org/log/59b0187fa480f2dfb600af0838e7c8265dee1cd7)
[2019-06-28T20:10:05-2e0cd2a/darwin-amd64-race](https://build.golang.org/log/5e8ddac828d08c9c7fd2988787cec018bfb1fa8f)
[2019-06-28T20:09:48-91c385b/darwin-amd64-race](https://build.golang.org/log/0372bc5893f973bf9c9e676a175f86423fbbf26c)
[2019-06-28T20:00:59-3b040b7/darwin-amd64-race](https://build.golang.org/log/7cab47444786102d70d9604e62ae02c1fc0e0c31)
[2019-06-27T20:43:26-f205ae3/darwin-amd64-race](https://build.golang.org/log/8f0742f4dcd2867cc147ab639fbe3e4861862916)
[2019-06-26T20:17:35-9acd2d6/darwin-amd64-race](https://build.golang.org/log/25f998ba0d29c80b2ae78f13fb2fbeb9e090625b)
[2019-06-26T18:38:59-06f709a/darwin-amd64-race](https://build.golang.org/log/9e535b013d42914b30bcd6f36fc6f82b91c26196)
[2019-06-26T16:35:14-60f14fd/darwin-amd64-race](https://build.golang.org/log/5faefe533b1a3362822f0c9f65c44bd6a4eddae6)
[2019-06-26T03:59:57-adf8883/darwin-amd64-race](https://build.golang.org/log/b43ecab963d64d5fc985581bf55a577f268cfc1e)
[2019-06-25T21:30:39-343b7fa/darwin-amd64-race](https://build.golang.org/log/ba74ef5cc6a4269151b0cc41187e88410487df84)
[2019-06-25T17:51:25-a6ad626/darwin-amd64-race](https://build.golang.org/log/aa6fac9a159eff5da5013b8bf117adb25130e307)
[2019-06-25T16:43:17-3f83c83/darwin-amd64-race](https://build.golang.org/log/97a5681b75360244a4fa42b50e1202ce935d7523)
[2019-06-24T21:26:46-5f7e9ce/darwin-amd64-race](https://build.golang.org/log/308c8b3f1f787406ea9a5e437ddf7b6063f4b341)
[2019-06-14T16:46:12-80f8913/darwin-amd64-race](https://build.golang.org/log/e2658f615d34c70534decfc6f087bf89cab3f39a)
[2019-06-13T17:12:09-f83c44e/darwin-amd64-race](https://build.golang.org/log/bee98b36ee7f892d671992f388c9990b82490582)
[2019-06-13T14:14:02-55d31e1/darwin-amd64-race](https://build.golang.org/log/6b77d8e9609953a7f299e44bc35bfd5f8773f1a6)
[2019-06-13T03:58:11-418c7d8/darwin-amd64-race](https://build.golang.org/log/b9763725a1f18feb2cc1d4aa221fa0474d4f3b45)
[2019-06-12T22:17:38-c0c6cee/darwin-amd64-race](https://build.golang.org/log/e6506c3faf0d40b81c1e43d9a6587bfc6bb74c5f)
[2019-06-12T18:03:46-f44404e/darwin-amd64-race](https://build.golang.org/log/fa9f22fcb38bdb5302dc1ebc3c1d7d862cf6e791)
[2019-06-11T17:54:27-9f76566/darwin-amd64-race](https://build.golang.org/log/2da29c548fce41b41235b032c89a303ca8a082e0)
[2019-06-10T23:23:39-ef84fa0/darwin-amd64-race](https://build.golang.org/log/7d428b0cfbcab441070b6bb430f9f70a3411201c)
[2019-06-10T20:32:36-5ce1819/darwin-amd64-race](https://build.golang.org/log/2885a1bbec67b815c975a65c45a4610ce177512d)
[2019-06-10T16:19:39-8f296f5/darwin-amd64-race](https://build.golang.org/log/62b5c702e02c81c47e548e478dbab8dfd3d53890)
[2019-06-05T17:53:53-e9a136d/darwin-amd64-race](https://build.golang.org/log/9947bf3611fb35c6c00166d6937169a68f43f7b3)
[2019-06-05T17:25:56-195e753/darwin-amd64-race](https://build.golang.org/log/5ef2db6617abcaba80b97dae1ce5eedbb4c1a5ec)
[2019-06-05T00:53:14-ac921da/darwin-amd64-race](https://build.golang.org/log/7dbb6e77c6406d449b15531241fb8076641504c6)
[2019-05-24T21:34:53-385b2e0/darwin-amd64-race](https://build.golang.org/log/e282b84f052be1f59ba308319ff5df0ad0384e4c)
[2019-05-17T22:32:30-1ab063c/darwin-amd64-race](https://build.golang.org/log/d00058aaf4e0ed84e145ebce9ae352cdf02fbdf0)
[2019-05-13T17:01:25-db2bf15/darwin-amd64-race](https://build.golang.org/log/52c34c976f66ee4d74a78ef0b8105b58c9e8764b)
[2019-05-09T21:13:46-56c1cf3/darwin-amd64-race](https://build.golang.org/log/755dfc3140e9859ba9440bbfc138e40aa975b500)
[2019-05-09T21:13:23-60f6763/darwin-amd64-race](https://build.golang.org/log/b998124bd878c004f457e600f49eb0eb8487005c)
[2019-05-09T21:13:19-fe67ce2/darwin-amd64-race](https://build.golang.org/log/fe2f0c70ac8adcb275b1ee1d9a10cfebea5e2582)
[2019-05-09T15:32:36-b6f59cb/darwin-amd64-race](https://build.golang.org/log/b7b816e45f17239d73a19d1286691df66f57d33c)
[2019-04-30T18:29:07-888bac1/darwin-amd64-race](https://build.golang.org/log/def1e7e61a239530b088fbce3cc5ca961aa27c55)
[2019-04-29T22:35:35-98c5a56/darwin-amd64-race](https://build.golang.org/log/58b633c294267e70b9498877e2a5a6cf9169152a)
[2019-04-29T04:05:29-d016330/darwin-amd64-race](https://build.golang.org/log/29b96105f5e42606dbb1dca49980561874f2947c)

**Comment by bcmills** [comment]
This seems to be one of the larger sources of dashboard flakes at the moment (CC @golang/osp-team).

[2020-08-24T19:20:59-bb99874/darwin-amd64-race](https://build.golang.org/log/fc82a84c9a83f067030295584ba4144ed7acd904)
[2020-08-22T12:35:47-8acbe4c/darwin-amd64-race](https://build.golang.org/log/88e1514b365eb7e10b9740d8b933bbeae9b9955f)
[2020-08-20T15:21:34-822dca4/darwin-amd64-race](https://build.golang.org/log/f223aaae412096ba5cf735506e2be9a8b75540b4)
[2020-08-16T14:23:50-d303630/darwin-amd64-race](https://build.golang.org/log/d5b7cc0c328a821b7eb43c1a21f3539e1cc89adc)
[2020-06-03T22:07:42-429d2c5/darwin-amd64-race](https://build.golang.org/log/d4ba827a14c613412a756c6c47c44f40152fc269)
[2020-05-09T23:17:17-c9442dc/darwin-amd64-race](https://build.golang.org/log/604f898cf98d6f31a2579a9ce2275ed6156b96c9)
[2020-05-07T23:22:45-78aa4af/darwin-amd64-race](https://build.golang.org/log/d51983629a1340a61b11573df4f4c44c40b3f26a)
[2020-05-02T20:20:16-2d323f9/darwin-amd64-race](https://build.golang.org/log/5ddb2c03c6a62b3b72dafbc6b9cc5ddc425202f7)
[2020-05-01T15:02:30-e3b0e3d/darwin-amd64-race](https://build.golang.org/log/c26c9ea60f04fa10f78e0b027dc78374cfc71d5e)

**Comment by bcmills** [comment]
Looks like it's not just the `darwin-amd64-race` builder. We might need to rework the timeout logic in the `cmd/go` tests to get more useful information.

[2021-02-19T00:04:56-bb6efb9/darwin-amd64-race](https://build.golang.org/log/d889ae862e97f5aaeb545952aa9ffbbe3322e749)
[2021-02-18T18:12:04-f3c2208/darwin-amd64-race](https://build.golang.org/log/b7a493a0c25dd5551bf97dd707d27f721224d242)
[2021-01-20T09:06:08-928bda4/darwin-amd64-race](https://build.golang.org/log/a4950158f70436c8683732728459f7ee3ad8da1e)
[2021-01-07T17:51:29-e60cffa/darwin-amd64-race](https://build.golang.org/log/094ed80021be354733680e7e519a9236a77010f6)
[2021-01-07T17:49:47-6da2d3b/darwin-amd64-race](https://build.golang.org/log/cfe17c3824e55044abed9e913192ec095474bf29)
[2020-12-22T18:36:29-c06a354/darwin-amd64-10_15](https://build.golang.org/log/37899b59cf732292dbd69eac6ed5513502e6e42b)
[2020-12-02T20:17:57-2d0258d/darwin-amd64-race](https://build.golang.org/log/1a9f3f2d20f763625bc67245a179a0844603cd48)
[2020-12-01T21:41:39-7430266/darwin-amd64-race](https://build.golang.org/log/7bafda1892b91f2593914bc0e862de6930243db4)
[2020-11-19T19:35:35-add4593/darwin-amd64-10_15](https://build.golang.org/log/a26c9f3309d31e3e55e5df3dbaa1a3973d290c47)
[2020-11-12T13:47:13-9ef65ff/darwin-amd64-race](https://build.golang.org/log/f925f5af4b161ee3092ccec3138873792d8437f2)
[2020-11-07T16:59:55-5e371e0/darwin-amd64-race](https://build.golang.org/log/a83eb69fb44377997250fe6144ba78fe3d22b111)
[2020-10-22T23:00:42-f1aa0b0/darwin-amd64-race](https://build.golang.org/log/30a911894878893031e58ff7813930b1302dc869)
[2020-10-19T15:00:02-2a206c7/darwin-amd64-race](https://build.golang.org/log/499dc5537319c545057e0294e062532fd782cbd0)
[2020-10-15T18:26:33-497ea06/darwin-amd64-race](https://build.golang.org/log/0db8bb0213532b2c1f33d82404e8b00b5c34dd1a)
[2020-10-13T17:36:36-ad53103/darwin-amd64-race](https://build.golang.org/log/a2a422b021264813d0a828ba2476bb97f4bf9c23)
[2020-10-08T08:53:13-542693e/darwin-amd64-race](https://build.golang.org/log/59c9ec129fdb625f4234c9fbc80f42f162dcc7cd)
[2020-09-29T16:12:04-39a426d/darwin-amd64-race](https://build.golang.org/log/42da77f6475d70e9b940ae0c7ba07289033154fb)
[2020-09-27T02:23:55-7bb6fed/darwin-amd64-race](https://build.golang.org/log/046e2b18a9afc4e04e2b030d7a3e3f265f628a80)
[2020-09-19T05:13:19-ccf581f/netbsd-386-9_0](https://build.golang.org/log/2ab0f954e1dc493ae7d9639f131cf5ee0c1eb8bd)
[2020-09-15T18:48:09-3ab825d/darwin-amd64-race](https://build.golang.org/log/1693eb53177ccd61a37574906905566cb8d40ef4)
[2020-08-28T16:40:41-ae7b6a3/darwin-amd64-10_15](https://build.golang.org/log/4c8dd7b8431203cc43d07e733e8b2931e4d3f0a7)
[2020-08-27T21:13:46-2963443/darwin-amd64-race](https://build.golang.org/log/a28d51e7b7d825d6262ec92ae2ed6e9929fd2f9b)
[2020-08-25T14:47:39-02f4452/darwin-amd64-race](https://build.golang.org/log/a9f342eec0584d8307f10d4494ebe655b26dd3bf)
[2020-08-24T19:20:59-bb99874/darwin-amd64-race](https://build.golang.org/log/fc82a84c9a83f067030295584ba4144ed7acd904)
[2020-08-22T12:35:47-8acbe4c/darwin-amd64-race](https://build.golang.org/log/88e1514b365eb7e10b9740d8b933bbeae9b9955f)
[2020-08-20T15:21:34-822dca4/darwin-amd64-race](https://build.golang.org/log/f223aaae412096ba5cf735506e2be9a8b75540b4)
[2020-08-16T14:23:50-d303630/darwin-amd64-race](https://build.golang.org/log/d5b7cc0c328a821b7eb43c1a21f3539e1cc89adc)
[2020-06-03T22:07:42-429d2c5/darwin-amd64-race](https://build.golang.org/log/d4ba827a14c613412a756c6c47c44f40152fc269)

**Comment by bcmills** [comment]
CL 302052 “fixes” this issue in the sense that the timeouts will probably continue to occur, but should produce more useful debugging output when that happens. If it is successful in that regard, we can file a separate issue for whatever failure mode that uncovers.

**Comment by bcmills** [comment]
Still not useful, but we're narrowing in on it, I think.
Looks like we also need to add useful timeouts for `(*testgoData).run`:
```
goroutine 117 [syscall, 5 minutes]:
syscall.syscall6(0x10d7940, 0x3e89, 0xc0006a7ad8, 0x0, 0xc000c881b0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/runtime/sys_darwin.go:41 +0x2e
syscall.wait4(0x3e89, 0xc0006a7ad8, 0x0, 0xc000c881b0, 0xc000c881b0, 0xc0006a7af8, 0x1050558)
	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/syscall/zsyscall_darwin_amd64.go:43 +0xa5
syscall.Wait4(0x3e89, 0xc0006a7b40, 0x0, 0xc000c881b0, 0x105026a, 0xc000666170, 0xc0005ae240)
	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/syscall/syscall_bsd.go:145 +0x66
os.(*Process).wait(0xc0001900f0, 0xc0007e41e0, 0xc0007e4210, 0xc0007e4160)
	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/os/exec_unix.go:44 +0x159
os.(*Process).Wait(...)
	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/os/exec.go:129
os/exec.(*Cmd).Wait(0xc0007e4160, 0x0, 0x0)
	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/os/exec/exec.go:507 +0x105
os/exec.(*Cmd).Run(0xc0007e4160, 0x81, 0xc0006680c0)
	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/os/exec/exec.go:341 +0x8a
cmd/go_test.(*testgoData).doRun(0xc00050e0b0, 0xc0006680c0, 0x4, 0x4, 0x40, 0xc0006680c0)
	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/cmd/go/go_test.go:411 +0x518
cmd/go_test.(*testgoData).run(0xc00050e0b0, 0xc0006680c0, 0x4, 0x4)
	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/cmd/go/go_test.go:427 +0xa6
cmd/go_test.TestCacheCoverage(0xc0004fe480)
	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/cmd/go/go_test.go:2318 +0x3c5
testing.tRunner(0xc0004fe480, 0x1b01cd0)
	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/testing/testing.go:1236 +0x22e
created by testing.(*T).Run
	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/testing/testing.go:1281 +0x78c
```

https://build.golang.org/log/ad208dadaa44cdaade5cf4e5d39ab96f78ab183d

**Comment by bcmills** [comment]
https://build.golang.org/log/ebdf7a853ae4dba70c0d76c53f5885501cd54668 has what seems to be a fairly useful trace; it seems to indicate that `os.Interrupt` is not succeeding in terminating a `go` subprocess.

**Comment by ianlancetaylor** [comment]
Are we going to do anything else here for 1.17?  Thanks.

**Comment by bcmills** [comment]
I'm planning to investigate this further during the freeze. I've managed to pare down the failure output enough that most of what remains is goroutines stuck in `os/exec` and `syscall`, and I suspect that it boils down to a platform bug of some sort (and/or a bug in the `os` package on macOS).

**Comment by Thor-Bjorgvinsson** [comment]
Could this halting command issue on mac be related? https://github.com/golang/go/issues/38824

**Comment by Integralist** [comment]
I've been seeing similar with `.Run()` when using GitHub's Actions CI. I've only been able to replicate once on my local macOS but it's very regular to see it timeout on macOS in the CI environment.

**Comment by bcmills** [comment]
It's been a year since the last of these timeouts. I'm calling this “probably fixed”, either by an intervening runtime change or by an intervening update to the race detector.

`greplogs -l -e '(?ms)\Adarwin-(?:amd64|arm64)-race.*panic: test timed out' --since=2021-04-27`
[2021-05-26T22:43:54-1d5298d/darwin-amd64-race](https://build.golang.org/log/2ea825ba2da482204347b6d90f43b13f5a2c65f7)
