### ISSUE TITLE
TestReverseProxyWebSocketCancelation panics

### ISSUE THREAD

**Issue by AndrewGMorgan** [golang/go#38863]
### What version of Go are you using (`go version`)?

HEAD in the master branch.

<pre>
$ go version
go version devel +53f27474a4 Sun May 3 07:23:32 2020 +0000 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/agm/.cache/go-build"
GOENV="/home/agm/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/agm/gopath/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/agm/gopath"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/agm/gits/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/agm/gits/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
GOAMD64="alignedjumps"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/agm/gits/go/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build935017853=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

<pre>
agm@penguin:~/gits/go/src$ ../bin/go test -c net/http/httputil 
agm@penguin:~/gits/go/src$ ./httputil.test --test.run TestReverseProxyWebSocketCancelation --test.count 100 --test.v 1
</pre>

### What did you expect to see?

no panics

### What did you see instead?

<pre>
[...]
2020/05/04 17:27:08 http: panic serving 127.0.0.1:43774: Log in goroutine after TestReverseProxyWebSocketCancelation has completed
goroutine 1538 [running]:
net/http.(*conn).serve.func1(0xc0004ad220)
        /home/agm/gits/go/src/net/http/server.go:1773 +0x147
panic(0x7129c0, 0xc000180000)
        /home/agm/gits/go/src/runtime/panic.go:975 +0x3e9
testing.(*common).logDepth(0xc0005b0dc0, 0xc0002a85a0, 0x5a, 0x3)
        /home/agm/gits/go/src/testing/testing.go:687 +0x4e5
testing.(*common).log(...)
        /home/agm/gits/go/src/testing/testing.go:669
testing.(*common).Errorf(0xc0005b0dc0, 0x788736, 0x1f, 0xc000346b88, 0x2, 0x2)
        /home/agm/gits/go/src/testing/testing.go:718 +0x85
net/http/httputil.TestReverseProxyWebSocketCancelation.func2(0x7ed4c0, 0xc0002276c0, 0xc0002a3700)
        /home/agm/gits/go/src/net/http/httputil/reverseproxy_test.go:1227 +0x4eb
net/http.HandlerFunc.ServeHTTP(0xc0005fa990, 0x7ed4c0, 0xc0002276c0, 0xc0002a3700)
        /home/agm/gits/go/src/net/http/server.go:2013 +0x44
net/http.serverHandler.ServeHTTP(0xc000415c00, 0x7ed4c0, 0xc0002276c0, 0xc0002a3700)
        /home/agm/gits/go/src/net/http/server.go:2814 +0xa3
net/http.(*conn).serve(0xc0004ad220, 0x7edb40, 0xc00044d700)
        /home/agm/gits/go/src/net/http/server.go:1896 +0x8ad
created by net/http.(*Server).Serve
        /home/agm/gits/go/src/net/http/server.go:2940 +0x36c
[...]
</pre>

**Comment by AndrewGMorgan** [comment]
FWIW I've been recently running into this issue with my unrelated development patch:

   https://go-review.googlesource.com/c/go/+/210639

and so I've been looking into it as a possible regression there. However, the issue reproduces against the master branch, so I've begun looking at it in that context.
