### ISSUE TITLE
x/build/cmd/gitmirror: 10 minute timeout on git fetch is incorrectly implemented, so git fetch may still block forever

### ISSUE THREAD

**Issue by dmitshur** [golang/go#38887]
Every now and then, `gitmirror` gets into a bad state where one of the repositories (usually, the main "go" repo) gets stuck and reports a "repo go: hung? no activity since last success <time> ago" problem on https://farmer.golang.org/#health.

This problem happens rarely (some number of times a year~). There are two instances of gitmirror [in production](https://github.com/golang/build/blob/c34742b3b844637fb46dab3597cbf20391b764c3/cmd/gitmirror/rc-prod.yaml#L6), so as long as at least one is in a good state, mirroring continues to operate without a problem. When it happens, it's easy to spot via https://farmer.golang.org/#health and restart an instance by deleting the problematic pod (a new pod will automatically spin up by the replication controller).

This is a tracking issue for this problem to see how often it happens, investigate as needed and fix it.

Previously:

- Issue #37828
- Issue #35124
- Issue #35120

Relevant CLs:

- [CL 205860](https://golang.org/cl/205860)
- [CL 203057](https://golang.org/cl/203057)
- [CL 227858](https://golang.org/cl/227858)

It happened again today:

![image](https://user-images.githubusercontent.com/1924134/81116564-9e2a7080-8ef3-11ea-8218-cfbe4ef0668a.png)

I've captured some logs and restarted one of the instances (having two bad instances meant that the Go repo was no longer being mirrored). I'll restart the other one in a bit, after doing some more investigation.

/cc @cagedmantis @toothrot @bcmills

**Comment by dmitshur** [comment]
This time, I was able to gather enough information and figure it out! 🎉

[CL 203057](https://golang.org/cl/203057) added a 10 minute timeout to the `git fetch` command execution. My intention there was to not let it run for more than 10 minutes, ever. I was not aware that `Wait` may still continue to block if a the command runs a subprocess. `git fetch` is a high level git command, it runs a lower level one (e.g., `git-fetch-pack` or so). As a result, it was still possible for `git fetch` to block forever in some cases.

Also see #21922 (and many similar issues).

There's an accepted proposal #23019 to try to change `Wait` behavior.

### Details

The `/debug/watcher/go` endpoint of `gitmirror` reported:

```
2020-05-05T20:40:22Z   2h44m17s ago         running git fetch origin, attempt 2
2020-05-05T20:37:29Z   2h47m11s ago         running git fetch origin
2020-05-05T20:37:29Z   2h47m11s ago         got update tickle
2020-05-05T20:37:29Z   2h47m11s ago         waiting
2020-05-05T20:37:29Z   2h47m11s ago         did sync to github
2020-05-05T20:37:28Z   2h47m12s ago         syncing to github
2020-05-05T20:37:28Z   2h47m12s ago         ran git fetch
2020-05-05T20:34:08Z   2h50m31s ago         running git fetch origin
```

"attempt 2" meant attempt 1 failed, and this was the corresponding error message:

```
2020/05/05 20:40:17 go: git fetch: exit status 128

error: RPC failed; HTTP 502 curl 22 The requested URL returned error: 502 
fatal: the remote end hung up unexpectedly
```

It seems the Gerrit server was having a temporary issue at that moment. It's likely attempt 2 failed for a similar reason, except it got stuck.

The goroutine dump (via the `/debug/goroutines` endpoint) was very insightful:

```
goroutine 151 [chan receive, 160 minutes]:
os/exec.(*Cmd).Wait(0xc00040ab00, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:515 +0x125
os/exec.(*Cmd).Run(0xc00040ab00, 0xc00009ce70, 0xc00040ab00)
	/usr/local/go/src/os/exec/exec.go:341 +0x5c
os/exec.(*Cmd).CombinedOutput(0xc00040ab00, 0x3, 0xc00039fd68, 0x3, 0x3, 0xc00040ab00)
	/usr/local/go/src/os/exec/exec.go:567 +0x91
main.(*Repo).fetch.func2(0x0, 0x0)
	/go/src/golang.org/x/build/cmd/gitmirror/gitmirror.go:508 +0x1c0
main.try(0x3, 0xc00039fe08, 0x18, 0xef32a0)
	/go/src/golang.org/x/build/cmd/gitmirror/gitmirror.go:642 +0x63
main.(*Repo).fetch(0xc000360000, 0x0, 0x0)
	/go/src/golang.org/x/build/cmd/gitmirror/gitmirror.go:499 +0xd6
main.(*Repo).Loop(0xc000360000)
	/go/src/golang.org/x/build/cmd/gitmirror/gitmirror.go:448 +0x7f
main.runGitMirror.func1(0xc00002e7d6, 0x2)
	/go/src/golang.org/x/build/cmd/gitmirror/gitmirror.go:153 +0x2bb
created by main.runGitMirror
	/go/src/golang.org/x/build/cmd/gitmirror/gitmirror.go:162 +0x342
```

Line 515 of [src/os/exec/exec.go](https://github.com/golang/go/blob/go1.14.2/src/os/exec/exec.go#L515) in Go 1.14.2 is:

https://github.com/golang/go/blob/96745b980cfde139e8611772e2bc0c59a8e6cdf7/src/os/exec/exec.go#L515

Note that it's stuck in `cmd.Wait` for 160 minutes.

Until #23019 is resolved, the fix in `cmd/gitmirror` is to ensure `git fetch` isn't allowed to run for more than 10 minutes in a way that is functional.

**Comment by bcmills** [comment]
This seems like another case where the behavior of `exec.CommandContext` is very suboptimal.

Per https://pkg.go.dev/os?tab=doc#Process.Kill:
> This only kills the Process itself, not any other processes it may have started.

That process-only behavior is generally ok for `SIGINT`, because the process has the opportunity to do its own signal-propagation to its subprocesses.

However, with `SIGKILL` the process has no such opportunity to forward the signal, because the signal cannot be caught. (Instead, the alternative there is for the Go program to use the less-portable [`syscall.Kill`](http://man7.org/linux/man-pages/man2/kill.2.html) to send the signal to the whole group.)

**Comment by dmitshur** [comment]
I just noticed it happened again, only 6 days since the last time:

![image](https://user-images.githubusercontent.com/1924134/81740837-975baa80-946b-11ea-99af-eb0f52d42f55.png)

Because both instances were stuck on the Go repo, it meant that commits at https://go.googlesource.com/go weren't made available on the https://github.com/golang/go mirror during that time. Those commits were still being tested at https://build.golang.org though.

I restarted the two gitmirror instances to fix the problem now:

```bash
~ $ kubectl get pods | grep gitmirror
gitmirror-rc-7bsh4                         1/1     Running   0          6d20h
gitmirror-rc-l5cxp                         1/1     Running   0          6d23h
~ $ kubectl delete pod gitmirror-rc-7bsh4 && sleep 60 && kubectl delete pod gitmirror-rc-l5cxp
pod "gitmirror-rc-7bsh4" deleted
pod "gitmirror-rc-l5cxp" deleted
```

It's not hard, but if this continues to happen this frequently without us noticing, automating the fix will be more worthwhile.

**Comment by dmitshur** [comment]
Again, today:

![image](https://user-images.githubusercontent.com/1924134/97643415-f9aa6680-1a1d-11eb-9f8e-3b2c06fec416.png)

That's 5 months 17 days since last reported occurrence.

Fixed using same procedure as in https://github.com/golang/go/issues/38887#issuecomment-627571674.

CC @golang/release.

**Comment by dmitshur** [comment]
December edition:

![image](https://user-images.githubusercontent.com/1924134/101556814-aa931200-3989-11eb-83d5-e16937236d39.png)

That's 1 months 9 days since last reported occurrence.

Fixed using same procedure as in https://github.com/golang/go/issues/38887#issuecomment-627571674.

**Comment by dmitshur** [comment]
February, 2021 edition:

![image](https://user-images.githubusercontent.com/1924134/109237958-9e586d00-77a0-11eb-8e07-6b5871906bc6.png)

2 months 17 days since last. Fixed with `kubectl delete pod gitmirror-rc-6p6lf`.

Doing some [xkcd.com/1205](https://xkcd.com/1205/) math here, assuming this task is done monthly and takes a couple of minutes, that gives a budget of a couple hours to automate this (that is, to fix the [diagnosed](https://github.com/golang/go/issues/38887#issuecomment-624366528) bug). So both doing this by hand and automating are quite close in cost.

**Comment by dmitshur** [comment]
April 7, 2021 edition:

![image](https://user-images.githubusercontent.com/1924134/113906566-62062c80-97a2-11eb-88c4-f188d88a2cc2.png)

1 month 13 days since last. Fixed with `kubectl delete pod gitmirror-rc-cbhf4`.

**Comment by cagedmantis** [comment]
`instance gitmirror-rc-fqrxd: repo exp: hung? no activity since last success 1h8m32.429381987s ago`
#45554 was filed.

**Comment by dmitshur** [comment]
May 27, 2021 edition:

![image](https://user-images.githubusercontent.com/1924134/119918396-5d562d00-bf36-11eb-91aa-c4846e8e5d36.png)

Fixed as before with `kubectl delete pod gitmirror-rc-423aca9388b272046d4bc507a0414e1f-v27xm`. (CC @heschi FYI; also see last paragraph in https://github.com/golang/go/issues/38887#issuecomment-786328521.)

**Comment by heschi** [comment]
And again today.
