### ISSUE TITLE
runtime: aix-ppc64 failing with "fatal error: index out of range" as of CL 146719

### ISSUE THREAD

**Issue by bcmills** [golang/go#38929]
[2020-05-07T19:22:19-6f52790/aix-ppc64](https://build.golang.org/log/3a8cf664844e9f78eaf4921316a95e4ccdf605ec)
[2020-05-07T17:50:24-6ed4661/aix-ppc64](https://build.golang.org/log/2ff8442bd3d4845fe84ccbc46053d9cc555a21ab)

```
fatal error: index out of range

goroutine 4296 [running]:
runtime.throw(0x1003e8548, 0x12)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/runtime/panic.go:1116 +0x68 fp=0xa00010000e39838 sp=0xa00010000e397f8 pc=0x1000396e8
runtime.panicCheck1(0x100016fa8, 0x1003e8548, 0x12)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/runtime/panic.go:34 +0xd8 fp=0xa00010000e39878 sp=0xa00010000e39838 pc=0x100036e08
runtime.goPanicIndexU(0x3d80000044, 0x400000)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/runtime/panic.go:91 +0x40 fp=0xa00010000e398d0 sp=0xa00010000e39878 pc=0x100036f60
runtime.heapBitsForAddr(...)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/runtime/mbitmap.go:340
runtime.bulkBarrierPreWriteSrcOnly(0x110374e40, 0x0, 0x0)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/runtime/mbitmap.go:684 +0x228 fp=0xa00010000e39950 sp=0xa00010000e398d0 pc=0x100016fa8
runtime.makeslicecopy(0x110032b70, 0x0, 0x0, 0x0, 0xa00010000e185c0)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/runtime/slice.go:65 +0x174 fp=0xa00010000e399b0 sp=0xa00010000e39950 pc=0x100053124
net/http.http2cloneHeader(0xa000100006b8780, 0x240)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/net/http/h2_bundle.go:6216 +0xfc fp=0xa00010000e39a80 sp=0xa00010000e399b0 pc=0x1002822fc
net/http.(*http2responseWriterState).writeHeader(0xa000100007f2500, 0xc8)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/net/http/h2_bundle.go:6208 +0x8c fp=0xa00010000e39ae8 sp=0xa00010000e39a80 pc=0x10028213c
net/http.(*http2responseWriter).WriteHeader(...)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/net/http/h2_bundle.go:6199
net/http.(*http2responseWriter).write(0xa0001000010e088, 0x10, 0x0, 0x0, 0x0, 0x1003e6594, 0x10, 0x110091f10, 0x100000110091f10, 0xa00000027113100)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/net/http/h2_bundle.go:6246 +0x1b0 fp=0xa00010000e39b48 sp=0xa00010000e39ae8 pc=0x100282640
net/http.(*http2responseWriter).WriteString(0xa0001000010e088, 0x1003e6594, 0x10, 0xa00000027113100, 0xa0001000010e088, 0x100000000000040)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/net/http/h2_bundle.go:6236 +0x4c fp=0xa00010000e39bb8 sp=0xa00010000e39b48 pc=0x10028245c
io.WriteString(0xa00000026ef6998, 0xa0001000010e088, 0x1003e6594, 0x10, 0xa0001000010e088, 0xa00010000cc46c0, 0x27)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/io/io.go:295 +0x80 fp=0xa00010000e39c28 sp=0xa00010000e39bb8 pc=0x10007c4b0
net/http_test.testServerNoHeader.func1(0x1100d84a0, 0xa0001000010e088, 0xa00010000d36600)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/net/http/serve_test.go:2834 +0xe0 fp=0xa00010000e39c90 sp=0xa00010000e39c28 pc=0x1003a4560
net/http.HandlerFunc.ServeHTTP(0xa00010000334000, 0x1100d84a0, 0xa0001000010e088, 0xa00010000d36600)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/net/http/server.go:2013 +0x54 fp=0xa00010000e39cc8 sp=0xa00010000e39c90 pc=0x1002a5764
net/http.serverHandler.ServeHTTP(0xa00010000cc0000, 0x1100d84a0, 0xa0001000010e088, 0xa00010000d36600)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/net/http/server.go:2814 +0xc8 fp=0xa00010000e39d18 sp=0xa00010000e39cc8 pc=0x1002a8a08
net/http.initALPNRequest.ServeHTTP(0x1100d91a0, 0xa000100004cc390, 0xa00010000d9e000, 0xa00010000cc0000, 0x1100d84a0, 0xa0001000010e088, 0xa00010000d36600)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/net/http/server.go:3386 +0x78 fp=0xa00010000e39ea0 sp=0xa00010000e39d18 pc=0x1002ab278
net/http.(*initALPNRequest).ServeHTTP(0xa00010000686120, 0x1100d84a0, 0xa0001000010e088, 0xa00010000d36600)
	<autogenerated>:1 +0x8c fp=0xa00010000e39ef8 sp=0xa00010000e39ea0 pc=0x1002f23cc
net/http.Handler.ServeHTTP-fm(0x1100d84a0, 0xa0001000010e088, 0xa00010000d36600)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/net/http/server.go:87 +0x5c fp=0xa00010000e39f38 sp=0xa00010000e39ef8 pc=0x1002f3a0c
net/http.(*http2serverConn).runHandler(0xa000100000c9200, 0xa0001000010e088, 0xa00010000d36600, 0xa000100006861c0)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/net/http/h2_bundle.go:5718 +0x94 fp=0xa00010000e39fa0 sp=0xa00010000e39f38 pc=0x100280124
runtime.goexit()
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/runtime/asm_ppc64x.s:884 +0x4 fp=0xa00010000e39fa0 sp=0xa00010000e39fa0 pc=0x100071ab4
created by net/http.(*http2serverConn).processHeaders
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/net/http/h2_bundle.go:5452 +0x4d8
```

This started as of [CL 146719](https://golang.org/cl/146719), which appears to be related.

CC @martisch @randall77 

Marking as release-blocker since this is a 1.15 regression. (CC @andybons)

**Comment by martisch** [comment]
That seems strange.

Its failing in `heapBitsForAddr`:
https://github.com/golang/go/blob/67c2dcbc592f3ee03aa89ddcb1f07715b047f4b2/src/runtime/mbitmap.go#L340

which we get from `bulkBarrierPreWriteSrcOnly`:
https://github.com/golang/go/blob/67c2dcbc592f3ee03aa89ddcb1f07715b047f4b2/src/runtime/mbitmap.go#L684

which we get from `makeslicecopy` were we just alloced that dst memory area:
https://github.com/golang/go/blob/6ed4661807b219781d1aa452b7f210e21ad1974b/src/runtime/slice.go#L61

@mknyszek

**Comment by martisch** [comment]
ah. tolen, fromlen are both 0. So its hitting the fastpath in mallocgc:

https://github.com/golang/go/blob/a13691966ad571ed9e434d591a2d612c51349fd1/src/runtime/malloc.go#L906

I check why it doesnt happen in copy and we need to catch the case of len=0 before calling writebarriers.
