### ISSUE TITLE
build: fails on WSL

### ISSUE THREAD

**Issue by stevenh** [golang/go#38950]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/data/go/bin"
GOCACHE="/home/steveh/.cache/go-build"
GOENV="/home/steveh/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/data/go:/home/steveh/code"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/steveh/code/go/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build772923501=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
Run: ./all.bash

### What did you expect to see?
The build complets

### What did you see instead?
```
./all.bash
Building Go cmd/dist using /usr/local/go. (go1.14.2 linux/amd64)
Building Go toolchain1 using /usr/local/go.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
panic: invalid argument

goroutine 1 [running]:
bootstrap/cmd/link/internal/ld.Main(0x89f2c0, 0x20, 0x20, 0x1, 0x7, 0x10, 0x0, 0x0, 0x6d23cc, 0x1b, ...)
        /home/user/code/go/src/cmd/link/internal/ld/main.go:320 +0x1eba
main.main()
        /home/user/code/go/src/cmd/link/main.go:68 +0x163

go tool dist: FAILED: /home/user/code/go/pkg/tool/linux_amd64/link -extld=gcc -o /home/user/code/go/pkg/tool/linux_amd64/go_bootstrap /tmp/go-tool-dist-965633972/cmd/go/_go_.a: exit status 2
Building Go toolchain2 using go_bootstrap and Go toolchain1.
go tool dist: FAILED: /home/user/code/go/pkg/tool/linux_amd64/go_bootstrap install -gcflags=all= -ldflags=all= -i cmd/asm cmd/cgo cmd/compile cmd/link: fork/exec /home/user/code/go/pkg/tool/linux_amd64/go_bootstrap: exec format error
```

**Comment by stevenh** [comment]
For reference this was caused by: https://github.com/golang/go/commit/8ab37b1bafdd0040530f976f45c417029cda6965
