### ISSUE TITLE
runtime: apparent TestEnsureDropM deadlock on openbsd-386-62 builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#39039]
[2020-05-12T19:15:34-cb11c98/openbsd-386-62](https://build.golang.org/log/e1493eca23402d4858687540ee6cd95b48a46164)

```
--- FAIL: TestEnsureDropM (120.07s)
    crash_test.go:95: testprogcgo EnsureDropM exit status: exit status 2
    crash_cgo_test.go:174: expected "OK\n", got SIGQUIT: quit
        PC=0x1c05a717 m=6 sigcode=0
        
        goroutine 0 [idle]:
        runtime.thrsleep(0x3c42cacc, 0x3, 0x0, 0x0, 0x3c42cacc, 0x4, 0x1c041aa2, 0x7c28a9ec, 0x0, 0x0, ...)
        	/tmp/workdir/go/src/runtime/sys_openbsd_386.s:384 +0x7
        runtime.semasleep(0xffffffff, 0xffffffff, 0x3c42c900)
        	/tmp/workdir/go/src/runtime/os_openbsd.go:167 +0xcc
        runtime.notesleep(0x3c1223fc)
        	/tmp/workdir/go/src/runtime/lock_sema.go:181 +0xda
        runtime.templateThread()
        	/tmp/workdir/go/src/runtime/proc.go:1863 +0xd4
        runtime.mstart1()
        	/tmp/workdir/go/src/runtime/proc.go:1156 +0x8f
        runtime.mstart()
        	/tmp/workdir/go/src/runtime/proc.go:1121 +0x4f
        
        goroutine 1 [syscall]:
        main._Cfunc_CheckM()
        	_cgo_gotypes.go:127 +0x2d
        main.EnsureDropM()
        	/tmp/workdir/go/src/runtime/testdata/testprogcgo/dropm.go:57 +0x14
        main.main()
        	/tmp/workdir/go/src/runtime/testdata/testprogcgo/main.go:34 +0x148
        
        eax    0x4
        ebx    0xffffffff
        ecx    0x0
        edx    0x3c42cacc
        edi    0x1c031b40
        esi    0x3c400d20
        ebp    0x1
        esp    0x7c28a9c4
        eip    0x1c05a717
        eflags 0x206
        cs     0x2b
        fs     0x7c24005b
        gs     0x9720063
FAIL
FAIL	runtime	186.395s
```

CC @ianlancetaylor

**Comment by bcmills** [comment]
Possibly related to the `TestCrashDumpsAllThreads` flakes reported in https://github.com/golang/go/issues/35356#issuecomment-627417866.

**Comment by 4a6f656c** [comment]
@bcmills - the OpenBSD 6.2 builders have been turned off and as such, I believe this can be closed.
