### ISSUE TITLE
ERROR: An error occurred during the fetch of repository 'org_golang_x_tools':

### ISSUE THREAD

**Issue by PradeepJigalur** [golang/go#39215]
### What version of Go are you using (`go version`)?
1.13.3

### Does this issue reproduce with the latest release?
NA

### What operating system and processor architecture are you using (`go env`)?
Centos

### What did you do?
was trying to download go repository failed

go_repository(
    name = "org_golang_x_tools",
    importpath = "golang.org/x/tools",
    sum = "h1:/e+gpKk9r3dJobndpTytxS2gOy6m5uvpg+ISQoEcusQ=",
    version = "v0.0.0-20190311212946-11955173bddd",
)

### What did you expect to see?

it should be downloed

### What did you see instead?

 Error downloading [https://mirror.bazel.build/github.com/golang/tools/archive/57f3fb51f5075e8af9f6ae8bd25e374f4e6b92ed.zip, https://github.com/golang/tools/archive/57f3fb51f5075e8af9f6ae8bd25e374f4e6b92ed.zip]

**Comment by bsiegert** [comment]
This looks like a bazel problem, not a Go problem.

Also, what are you trying to build? Is it open source? Can you link to the source code?

Can you share more detail w.r.t. the output? "Error downloading" could be anything.

**Comment by PradeepJigalur** [comment]
external/bazel_tools/tools/build_defs/repo/http.bzl:336:16: in <toplevel>
WARNING: Download from https://mirror.bazel.build/github.com/golang/tools/archive/57f3fb51f5075e8af9f6ae8bd25e374f4e6b92ed.zip failed: class java.net.ConnectException Connection refused (Connection refused)
WARNING: Download from https://github.com/golang/tools/archive/57f3fb51f5075e8af9f6ae8bd25e374f4e6b92ed.zip failed: class java.net.ConnectException Connection refused (Connection refused)
ERROR: An error occurred during the fetch of repository 'org_golang_x_tools':
java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/golang/tools/archive/57f3fb51f5075e8af9f6ae8bd25e374f4e6b92ed.zip, https://github.com/golang/tools/archive/57f3fb51f5075e8af9f6ae8bd25e374f4e6b92ed.zip] to b-build-bazel/0537c9eb120fc9993b6a9b432632dde3/external/org_golang_x_tools/57f3fb51f5075e8af9f6ae8bd25e374f4e6b92ed.zip: Connection refused (Connection refused)
Printing stack trace: com.google.devtools.build.lib.syntax.EvalExceptionWithStackTrace: java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/golang/tools/archive/57f3fb51f5075e8af9f6ae8bd25e374f4e6b92ed.zip, https://github.com/golang/tools/archive/57f3fb51f5075e8af9f6ae8bd25e374f4e6b92ed.zip] to b-build-bazel/0537c9eb120fc9993b6a9b432632dde3/external/org_golang_x_tools/57f3fb51f5075e8af9f6ae8bd25e374f4e6b92ed.zip: Connection refused (Connection refused)
2020-05-22 07:57:43 | 	at com.google.devtools.build.lib.syntax.Eval.maybeTransformException(Eval.java:826)
2020-05-22 07:57:43 | 	at com.google.devtools.build.lib.syntax.Eval.eval(Eval.java:425)
2020-05-22 07:57:43 | 	at com.google.devtools.build.lib.syntax.Eval.execAssignment(Eval.java:80)
2020-05-22 07:57:43 | 	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:241)
2020-05-22 07:57:43 | 	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:231)
2020-05-22 07:57:43 | 	at com.google.devtools.build.lib.syntax.Eval.execStatements(Eval.java:53)
2020-05-22 07:57:43 | 	at com.google.devtools.build.lib.syntax.Eval.execFunctionBody(Eval.java:37)
2020-05-22 07:57:43 | 	at com.google.devtools.build.lib.syntax.StarlarkFunction.fastcall(StarlarkFunction.java:115)
2020-05-22 07:57:43 | 	at com.google.devtools.build.lib.syntax.Starlark.fastcall(Starlark.java:359)
2020-05-22 07:57:43 | 	at com.google.devtools.build.lib.syntax.Starlark.call(Starlark.java:334)
2020-05-22 07:57:43 | 	at com.google.devtools.build.lib.bazel.repository.skylark.SkylarkRepositoryFunction.fetch(SkylarkRepositoryFunction.java:203)
2020-05-22 07:57:43 | 	at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.fetchRepository(RepositoryDelegatorFunction.java:298)
2020-05-22 07:57:43 | 	at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:225)
2020-05-22 07:57:43 | 	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
2020-05-22 07:57:43 | 	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
2020-05-22 07:57:43 | 	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
2020-05-22 07:57:43 | 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
2020-05-22 07:57:43 | 	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1040)
2020-05-22 07:57:43 | 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)
2020-05-22 07:57:43 | 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
2020-05-22 07:57:43 | 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
2020-05-22 07:57:43 | Caused by: com.google.devtools.build.lib.rules.repository.RepositoryFunction$RepositoryFunctionException: java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/golang/tools/archive/57f3fb51f5075e8af9f6ae8bd25e374f4e6b92ed.zip, https://github.com/golang/tools/archive/57f3fb51f5075e8af9f6ae8bd25e374f4e6b92ed.zip] to b-build-bazel/0537c9eb120fc9993b6a9b432632dde3/external/org_golang_x_tools/57f3fb51f5075e8af9f6ae8bd25e374f4e6b92ed.zip: Connection refused (Connection refused)
2020-05-22 07:57:43 | 	at com.google.devtools.build.lib.bazel.repository.skylark.SkylarkRepositoryContext.downloadAndExtract(SkylarkRepositoryContext.java:849)
2020-05-22 07:57:43 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-05-22 07:57:43 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-05-22 07:57:43 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-05-22 07:57:43 | 	at java.lang.reflect.Method.invoke(Method.java:498)
2020-05-22 07:57:43 | 	at com.google.devtools.build.lib.syntax.MethodDescriptor.call(MethodDescriptor.java:130)
2020-05-22 07:57:43 | 	at com.google.devtools.build.lib.syntax.BuiltinCallable.fastcall(BuiltinCallable.java:73)
2020-05-22 07:57:43 | 	at com.google.devtools.build.lib.syntax.Starlark.fastcall(Starlark.java:359)
2020-05-22 07:57:43 | 	at com.google.devtools.build.lib.syntax.Eval.doEval(Eval.java:588)
2020-05-22 07:57:43 | 	at com.google.devtools.build.lib.syntax.Eval.eval(Eval.java:423)
2020-05-22 07:57:43 | 	... 19 more
2020-05-22 07:57:43 | Caused by: java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/golang/tools/archive/57f3fb51f5075e8af9f6ae8bd25e374f4e6b92ed.zip, https://github.com/golang/tools/archive/57f3fb51f5075e8af9f6ae8bd25e374f4e6b92ed.zip] to b-build-bazel/0537c9eb120fc9993b6a9b432632dde3/external/org_golang_x_tools/57f3fb51f5075e8af9f6ae8bd25e374f4e6b92ed.zip: Connection refused (Connection refused)
2020-05-22 07:57:43 | 	at com.google.devtools.build.lib.bazel.repository.downloader.HttpDownloader.download(HttpDownloader.java:129)
2020-05-22 07:57:43 | 	at com.google.devtools.build.lib.bazel.repository.downloader.DelegatingDownloader.download(DelegatingDownloader.java:61)
2020-05-22 07:57:43 | 	at com.google.devtools.build.lib.bazel.repository.downloader.DownloadManager.download(DownloadManager.java:189)
2020-05-22 07:57:43 | 	at com.google.devtools.build.lib.bazel.repository.skylark.SkylarkRepositoryContext.downloadAndExtract(SkylarkRepositoryContext.java:829)
2020-05-22 07:57:43 | 	... 28 more
2020-05-22 07:57:43 | 	Suppressed: java.net.ConnectException: Connection refused (Connection refused)
2020-05-22 07:57:43 | 		at java.net.PlainSocketImpl.socketConnect(Native Method)
2020-05-22 07:57:43 | 		at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
2020-05-22 07:57:43 | 		at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
2020-05-22 07:57:43 | 		at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
2020-05-22 07:57:43 | 		at java.net.Socket.connect(Socket.java:589)
2020-05-22 07:57:43 | 		at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
2020-05-22 07:57:43 | 		at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
2020-05-22 07:57:43 | 		at sun.net.www.http.HttpClient$1.run(HttpClient.java:515)
2020-05-22 07:57:43 | 		at sun.net.www.http.HttpClient$1.run(HttpClient.java:513)
2020-05-22 07:57:43 | 		at java.security.AccessController.doPrivileged(Native Method)
2020-05-22 07:57:43 | 		at sun.net.www.http.HttpClient.privilegedOpenServer(HttpClient.java:512)
2020-05-22 07:57:43 | 		at sun.net.www.http.HttpClient.openServer(HttpClient.java:553)
2020-05-22 07:57:43 | 		at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
2020-05-22 07:57:43 | 		at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
2020-05-22 07:57:43 | 		at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
2020-05-22 07:57:43 | 		at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1199)
2020-05-22 07:57:43 | 		at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
2020-05-22 07:57:43 | 		at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
2020-05-22 07:57:43 | 		at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)
2020-05-22 07:57:43 | 		at com.google.devtools.build.lib.bazel.repository.downloader.HttpConnector.connect(HttpConnector.java:129)
2020-05-22 07:57:43 | 		at com.google.devtools.build.lib.bazel.repository.downloader.HttpConnectorMultiplexer.establishConnection(HttpConnectorMultiplexer.java:352)
2020-05-22 07:57:43 | 		at com.google.devtools.build.lib.bazel.repository.downloader.HttpConnectorMultiplexer.connect(HttpConnectorMultiplexer.java:137)
2020-05-22 07:57:43 | 		at com.google.devtools.build.lib.bazel.repository.downloader.HttpDownloader.download(HttpDownloader.java:92)
2020-05-22 07:57:43 | 		... 31 more
2020-05-22 07:57:43 | 		Suppressed: java.net.ConnectException: Connection refused (Connection refused)
2020-05-22 07:57:43 | 			... 54 more
2020-05-22 07:57:43 | 		Suppressed: java.net.ConnectException: Connection refused (Connection refused)
2020-05-22 07:57:43 | 			... 54 more
2020-05-22 07:57:43 | 		Suppressed: java.net.ConnectException: Connection refused (Connection refused)
2020-05-22 07:57:43 | 			... 54 more
2020-05-22 07:57:43 | 		Suppressed: java.net.ConnectException: Connection refused (Connection refused)
2020-05-22 07:57:43 | 			... 54 more
2020-05-22 07:57:43 | 		Suppressed: java.net.ConnectException: Connection refused (Connection refused)
2020-05-22 07:57:43 | 			... 54 more
2020-05-22 07:57:43 | 		Suppressed: java.net.ConnectException: Connection refused (Connection refused)
2020-05-22 07:57:43 | 			... 54 more
2020-05-22 07:57:43 | 		Suppressed: java.net.ConnectException: Connection refused (Connection refused)
2020-05-22 07:57:43 | 			... 54 more
2020-05-22 07:57:43 | 	Suppressed: java.net.ConnectException: Connection refused (Connection refused)
2020-05-22 07:57:43 | 		at java.net.PlainSocketImpl.socketConnect(Native Method)
2020-05-22 07:57:43 | 		at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
2020-05-22 07:57:43 | 		at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
2020-05-22 07:57:43 | 		at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
2020-05-22 07:57:43 | 		at java.net.Socket.connect(Socket.java:589)
2020-05-22 07:57:43 | 		at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
2020-05-22 07:57:43 | 		at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
2020-05-22 07:57:43 | 		at sun.net.www.http.HttpClient$1.run(HttpClient.java:515)
2020-05-22 07:57:43 | 		at sun.net.www.http.HttpClient$1.run(HttpClient.java:513)
2020-05-22 07:57:43 | 		at java.security.AccessController.doPrivileged(Native Method)
2020-05-22 07:57:43 | 		at sun.net.www.http.HttpClient.privilegedOpenServer(HttpClient.java:512)
2020-05-22 07:57:43 | 		at sun.net.www.http.HttpClient.openServer(HttpClient.java:553)
2020-05-22 07:57:43 | 		at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
2020-05-22 07:57:43 | 		at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
2020-05-22 07:57:43 | 		at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
2020-05-22 07:57:43 | 		at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1199)
2020-05-22 07:57:43 | 		at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
2020-05-22 07:57:43 | 		at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
2020-05-22 07:57:43 | 		at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)
2020-05-22 07:57:43 | 		at com.google.devtools.build.lib.bazel.repository.downloader.HttpConnector.connect(HttpConnector.java:129)
2020-05-22 07:57:43 | 		at com.google.devtools.build.lib.bazel.repository.downloader.HttpConnectorMultiplexer.establishConnection(HttpConnectorMultiplexer.java:352)
2020-05-22 07:57:43 | 		at com.google.devtools.build.lib.bazel.repository.downloader.HttpConnectorMultiplexer.connect(HttpConnectorMultiplexer.java:137)
2020-05-22 07:57:43 | 		at com.google.devtools.build.lib.bazel.repository.downloader.HttpDownloader.download(HttpDownloader.java:92)
2020-05-22 07:57:43 | 		... 31 more
2020-05-22 07:57:43 | 		Suppressed: java.net.ConnectException: Connection refused (Connection refused)
2020-05-22 07:57:43 | 			... 54 more
2020-05-22 07:57:43 | 		Suppressed: java.net.ConnectException: Connection refused (Connection refused)
2020-05-22 07:57:43 | 			... 54 more
2020-05-22 07:57:43 | 		Suppressed: java.net.ConnectException: Connection refused (Connection refused)
2020-05-22 07:57:43 | 			... 54 more
2020-05-22 07:57:43 | 		Suppressed: java.net.ConnectException: Connection refused (Connection refused)
2020-05-22 07:57:43 | 			... 54 more
2020-05-22 07:57:43 | 		Suppressed: java.net.ConnectException: Connection refused (Connection refused)
2020-05-22 07:57:43 | 			... 54 more
2020-05-22 07:57:43 | 		Suppressed: java.net.ConnectException: Connection refused (Connection refused)
2020-05-22 07:57:43 | 			... 54 more
2020-05-22 07:57:43 | 		Suppressed: java.net.ConnectException: Connection refused (Connection refused)
2020-05-22 07:57:43 | 			... 54 more

**Comment by bsiegert** [comment]
The URLs work for me. I suppose that this is a local problem. And again: this is a problem with your local environment, or perhaps with Bazel, not with Go.

**Comment by andybons** [comment]
This seems like a Bazel-specific issue. Please use the appropriate channels to raise the question with that team. Thank you.
