### ISSUE TITLE
runtime: TestGdbPythonCgo, TestGdbPython are failing on linux/mips64le

### ISSUE THREAD

**Issue by dmitshur** [golang/go#39368]
Spotted on the `linux-mips64le-mengzhuo` builder:

- https://build.golang.org/log/d16c4bfea213937d39864d5d41a932c3c9bd99ef
- https://build.golang.org/log/01a53fef937a30208496408a8d35580e2c32e89b
- https://build.golang.org/log/974de169c6a577a63dfe0b7d13624486bd990330

```
--- FAIL: TestGdbPythonCgo (4.08s)
    runtime-gdb_test.go:79: gdb version 8.1
    runtime-gdb_test.go:273: gdb output:
        [...]
    runtime-gdb_test.go:319: print slicemap failed: $2 = map[string][]string = {[0x1200d446e "e"] = {array = 0xc0001161b0, len = 3, cap = 3}, [0x1200d446a "a"] = {array = 0xc000116180, len = 3, cap = 3}}
--- FAIL: TestGdbPython (2.22s)
    runtime-gdb_test.go:79: gdb version 8.1
    runtime-gdb_test.go:273: gdb output:
        [...]
    runtime-gdb_test.go:319: print slicemap failed: $2 = map[string][]string = {[0xe2baa "a"] = {array = 0xc00005a180, len = 3, cap = 3}, [0xe2bae "e"] = {array = 0xc00005a1b0, len = 3, cap = 3}}
FAIL
FAIL	runtime	46.844s
```

This is occurring as of [CL 235926](https://golang.org/cl/235926). It's not happening on other ports, so it may be related to the builder.

(Not blocking the 1.15 release because the linux/mips64le port is not included in the list at https://golang.org/wiki/PortingPolicy#first-class-ports.)

/cc @dr2chase @mengzhuo

**Comment by dr2chase** [comment]
I think I have a fix for that.

**Comment by siebenmann** [comment]
This commit (3949cae4410aa05bc76ccab598ad63618b10416e) causes build failures for me on amd64 Fedora 31 with a `gdb --version` of `Fedora 8.3.50.20190824-30.fc31`. What I see is:

```
--- FAIL: TestGdbPython (0.68s)
    runtime-gdb_test.go:77: gdb version 8.3
    runtime-gdb_test.go:270: gdb output:
        Loading Go Runtime support.
        Traceback (most recent call last):
          File "/data/code/go-lang/go/src/runtime/runtime-gdb.py", line 33, in <module>
            majorgdbversion = int(splitgdbversion[0])
        ValueError: invalid literal for int() with base 10: 'Fedora 8'
        Loaded  Script                                                                 
        Yes     /data/code/go-lang/go/src/runtime/runtime-gdb.py                       
        Breakpoint 1 at 0x49ac38: file /tmpfs/cks-gobuild/go-build918948481/main.go, line 26.
        hi
        
        Thread 1 "a.exe" hit Breakpoint 1, main.main () at /tmpfs/cks-gobuild/go-build918948481/main.go:26
        26              gslice = slicevar
        BEGIN info goroutines
        Undefined info command: "goroutines".  Try "help info".
        END
        BEGIN print mapvar
        $1 = (map[string]string) 0xc000104f48
        END
        BEGIN print slicemap
        $2 = (map[string][]string) 0xc00007c150
        END
        BEGIN print strvar
        $3 = 0x4be101 "abc"
        END
        BEGIN print chanint
        $4 = (chan int) 0xc00002a0b0
        END
        BEGIN print chanstr
        $5 = (chan string) 0xc0000301e0
        END
        BEGIN info locals
        mapvar = 0xc000104f48
        chanstr = 0xc0000301e0
        chanint = 0xc00002a0b0
        strvar = 0x4be101 "abc"
        slicemap = 0xc00007c150
        ptrvar = <optimized out>
        slicevar = {array = 0xc00011c000, len = 824634229168, cap = 824634229120}
        END
        BEGIN goroutine 1 bt
        Undefined command: "goroutine".  Try "help".
        END
        BEGIN goroutine all bt
        Undefined command: "goroutine".  Try "help".
        END
        No breakpoint at main.go:15.
        Breakpoint 2 at 0x49adb1: file /tmpfs/cks-gobuild/go-build918948481/main.go, line 29.
        map[a:[b c d] e:[f g h]], 99, spongepants
        
        Thread 1 "a.exe" hit Breakpoint 2, main.main () at /tmpfs/cks-gobuild/go-build918948481/main.go:29
        29      }  // END_OF_PROGRAM
        BEGIN goroutine 1 bt at the end
        Undefined command: "goroutine".  Try "help".
        END
    runtime-gdb_test.go:302: info goroutines failed: Undefined info command: "goroutines".  Try "help info".
--- FAIL: TestGdbPythonCgo (1.73s)
    runtime-gdb_test.go:77: gdb version 8.3
    runtime-gdb_test.go:270: gdb output:
        Loading Go Runtime support.
        Traceback (most recent call last):
          File "/data/code/go-lang/go/src/runtime/runtime-gdb.py", line 33, in <module>
            majorgdbversion = int(splitgdbversion[0])
        ValueError: invalid literal for int() with base 10: 'Fedora 8'
        Loading Go Runtime support.
        Traceback (most recent call last):
          File "/data/code/go-lang/go/src/runtime/runtime-gdb.py", line 33, in <module>
            majorgdbversion = int(splitgdbversion[0])
        ValueError: invalid literal for int() with base 10: 'Fedora 8'
        Breakpoint 1 at 0x49c738: file /tmpfs/cks-gobuild/go-build903045418/main.go, line 27.
        [Thread debugging using libthread_db enabled]
        Using host libthread_db library "/lib64/libthread_db.so.1".
        hi
        
        Thread 1 "a.exe" hit Breakpoint 1, main.main () at /tmpfs/cks-gobuild/go-build903045418/main.go:27
        27              gslice = slicevar
        BEGIN info goroutines
        Undefined info command: "goroutines".  Try "help info".
        END
        BEGIN print mapvar
        $1 = (map[string]string) 0xc000064f48
        END
        BEGIN print slicemap
        $2 = (map[string][]string) 0xc00011e150
        END
        BEGIN print strvar
        $3 = 0x4c1121 "abc"
        END
        BEGIN print chanint
        $4 = (chan int) 0xc00013e000
        END
        BEGIN print chanstr
        $5 = (chan string) 0xc000138120
        END
        BEGIN info locals
        mapvar = 0xc000064f48
        chanstr = 0xc000138120
        chanint = 0xc00013e000
        strvar = 0x4c1121 "abc"
        slicemap = 0xc00011e150
        ptrvar = <optimized out>
        slicevar = {array = 0xc000142000, len = 824634892720, cap = 824634892672}
        END
        BEGIN goroutine 1 bt
        Undefined command: "goroutine".  Try "help".
        END
        BEGIN goroutine all bt
        Undefined command: "goroutine".  Try "help".
        END
        No breakpoint at main.go:15.
        Breakpoint 2 at 0x49c8b1: file /tmpfs/cks-gobuild/go-build903045418/main.go, line 30.
        map[a:[b c d] e:[f g h]], 99, spongepants
        
        Thread 1 "a.exe" hit Breakpoint 2, main.main () at /tmpfs/cks-gobuild/go-build903045418/main.go:30
        30      }  // END_OF_PROGRAM
        BEGIN goroutine 1 bt at the end
        Undefined command: "goroutine".  Try "help".
        END
    runtime-gdb_test.go:302: info goroutines failed: Undefined info command: "goroutines".  Try "help info".
FAIL
FAIL    runtime 31.549s
```

Switching back to the commit immediately before it builds successfully; moving forward to this commit causes the failure.

**Comment by dr2chase** [comment]
Fixed by https://go-review.googlesource.com/c/go/+/236280

Slowbot tested on
```
linux-amd64
linux-amd64-fedora
linux-amd64-jessie
linux-amd64-sid
linux-mips64le-mengzhuo
linux-s390x-ibm
```

**Comment by dmitshur** [comment]
Thank you @dr2chase.

**Comment by dr2chase** [comment]
Sorry about the hiccups.  I'll never trust a version "number" again.
