### ISSUE TITLE
runtime: "fatal error: all goroutines are asleep - deadlock!" with GC assist wait

### ISSUE THREAD

**Issue by prattmic** [golang/go#39390]
[2020-06-02T21:19:07-ee776b4/freebsd-386-11_2](https://build.golang.org/log/a52682319e4acceb9aa1804f128b3f941c6eb007):
```
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0x39123438)
        /tmp/workdir/go/src/runtime/sema.go:56 +0x30
sync.(*WaitGroup).Wait(0x39123430)
        /tmp/workdir/go/src/sync/waitgroup.go:130 +0x76
cmd/compile/internal/gc.compileFunctions()
        /tmp/workdir/go/src/cmd/compile/internal/gc/pgen.go:392 +0x190
cmd/compile/internal/gc.Main(0x87a6314)
        /tmp/workdir/go/src/cmd/compile/internal/gc/main.go:757 +0x30d6
main.main()
        /tmp/workdir/go/src/cmd/compile/main.go:52 +0x8d

goroutine 22 [GC assist wait]:
cmd/compile/internal/ssa.cse(0x39168540)
        /tmp/workdir/go/src/cmd/compile/internal/ssa/cse.go:52 +0x301
cmd/compile/internal/ssa.Compile(0x39168540)
        /tmp/workdir/go/src/cmd/compile/internal/ssa/compile.go:93 +0x873
cmd/compile/internal/gc.buildssa(0x3933c5b0, 0x3, 0x0)
        /tmp/workdir/go/src/cmd/compile/internal/gc/ssa.go:460 +0xa5d
cmd/compile/internal/gc.compileSSA(0x3933c5b0, 0x3)
        /tmp/workdir/go/src/cmd/compile/internal/gc/pgen.go:317 +0x4c
cmd/compile/internal/gc.compileFunctions.func2(0x3943a7c0, 0x39123430, 0x3)
        /tmp/workdir/go/src/cmd/compile/internal/gc/pgen.go:382 +0x35
created by cmd/compile/internal/gc.compileFunctions
        /tmp/workdir/go/src/cmd/compile/internal/gc/pgen.go:380 +0xf7
```

This is a failure on `freebsd-386-11_2`. I don't see any recent similar failures.

cc @mknyszek @aclements

**Comment by prattmic** [comment]
Very similar failure:
[2020-03-15T08:18:17-7b2f0ba/freebsd-arm-paulzhol](https://build.golang.org/log/8c6cba874080c6152ff54eebd56fe7aa331951d6)

No GC assist wait:
[2020-02-26T18:00:53-025a4fa/plan9-386-0intro](https://build.golang.org/log/4baab90b680b38bb7dca971ed6fc54b08bef38cb)
[2019-10-25T20:21:24-dcad830/plan9-arm](https://build.golang.org/log/47c2cb7b4f32a451d91c6e25db4702728cd398d0):

**Comment by prattmic** [comment]
@aclements pointed out that it is perhaps possible for GC goroutines to not be actively running yet (because the scheduler hasn't quite noticed) while there is a GC assist wait. But the mcount() check in checkdead seems like it should consider an M that hasn't yet considered GC work to still be running.
