### ISSUE TITLE
runtime: "morestack on g0" in TestSegv on darwin-amd64-race builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#39457]
[2020-06-08T17:59:37-2603d9a/darwin-amd64-race](https://build.golang.org/log/e285b11c53cb164b27ef1bdf459cb6743137c34b)

```
--- FAIL: TestSegv (0.00s)
    --- FAIL: TestSegv/Segv (0.02s)
        crash_test.go:105: /var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/tmp/go-build172134279/testprogcgo.exe SegvInCgo exit status: exit status 2
        crash_cgo_test.go:569: fatal: morestack on g0
            SIGTRAP: trace trap
            PC=0x406b702 m=0 sigcode=1
            
            goroutine 0 [idle]:
            runtime.abort()
            	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/runtime/asm_amd64.s:860 +0x2
            runtime.morestack()
            	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/runtime/asm_amd64.s:416 +0x25
            
            goroutine 19 [syscall]:
            runtime.cgocall(0x4123600, 0xc00003a7c0, 0x4123600)
            	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/runtime/cgocall.go:133 +0x5b fp=0xc00003a790 sp=0xc00003a758 pc=0x400503b
            main._Cfunc_nop()
            	_cgo_gotypes.go:329 +0x45 fp=0xc00003a7c0 sp=0xc00003a790 pc=0x411a2a5
            main.SegvInCgo.func1(0xc00008e120)
            	/private/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/runtime/testdata/testprogcgo/segv.go:46 +0x30 fp=0xc00003a7d8 sp=0xc00003a7c0 pc=0x41224b0
            runtime.goexit()
            	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00003a7e0 sp=0xc00003a7d8 pc=0x406b8e1
            created by main.SegvInCgo
            	/private/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/runtime/testdata/testprogcgo/segv.go:43 +0x5c
            
            goroutine 1 [sleep]:
            time.Sleep(0x3b9aca00)
            	/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/runtime/time.go:188 +0xbf
            main.SegvInCgo()
            	/private/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/runtime/testdata/testprogcgo/segv.go:55 +0x9c
            main.main()
            	/private/var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/runtime/testdata/testprogcgo/main.go:34 +0x1da
            
            rax    0x17
            rbx    0xc00003a710
            rcx    0x4265d40
            rdx    0x0
            rdi    0x2
            rsi    0xc00003a6b0
            rbp    0xc00003a780
            rsp    0xc00003a738
            r8     0x4265d40
            r9     0x0
            r10    0xc00003a710
            r11    0x202
            r12    0xf1
            r13    0x0
            r14    0x418de44
            r15    0x0
            rip    0x406b702
            rflags 0x202
            cs     0x2b
            fs     0x0
            gs     0x0
            
        crash_cgo_test.go:571: expected crash from signal
FAIL
FAIL	runtime	69.144s
```

CC @aclements @ianlancetaylor

**Comment by cherrymui** [comment]
On darwin/amd64, to work around a kernel issue we rewrite SI_USER SIGEGV to kernel-generated: https://tip.golang.org/src/runtime/signal_darwin_amd64.go#L72 . So, in this case, an actual user-sent SIGSEGV will be treated as kernel-generated signal, and cause it to inject a sigpanic. If the signal lands at a bad time, e.g. we're right in the middle of a stack switch, where the g and the stack don't match, bad things will happen.

I'm not sure what the best solution is. A few possibilities:
- do nothing (maybe skip/relax the test). It isn't too bad in that it will crash the program anyway (sigpanic will throw for this particular bad address), unless PanicOnFault is set.
- remove the workaround (at least the sigcode part, we could still change the faulting address).  A malformed address will be treated as user-sent SIGSEGV, which will crash the program now. PanicOnFault is still a problem.

Not sure what to do with PanicOnFault. Due to the kernel issue, it seems we cannot distinguish malformed address vs. user-sent SIGSEGV. We have to make both recoverable or non-recoverable...

(The workaround was added for OS X 10.9. The kernel issue seems still there for macOS 10.15...)

**Comment by cherrymui** [comment]
Another possibility: when switching from user stack to system stack (e.g. in systemstack, asmcgocall, etc.), we always do (1) set user g's `g.throwsplit` to true, (2) change SP, (3) change the g register to g0. And do it in the opposite order when switching back. This might solve the immediate SIGSEGV-landing-in-stack-switch problem. Not sure if there is any other problem. Seems pretty complicated, though.

**Comment by bcmills** [comment]
[2020-08-18T04:22:33-6133883/darwin-amd64-10_12](https://build.golang.org/log/42f45a21f987363f49ec32966f258cf7cb852468)
[2020-08-14T23:04:16-5a18e0b/darwin-amd64-10_15](https://build.golang.org/log/8d8d81c854126395329fab73cc5e276da40178f8)
[2020-06-16T19:29:32-844bf11/darwin-amd64-race](https://build.golang.org/log/a311949574e815f5a8810e4025660c5f76d4971d)

**Comment by bcmills** [comment]
Hmm... Why do we ignore user-generated `SIGSEGV` signals in the first place? I explicitly sent a program `SIGSEGV` on the command line, I would generally expect to get a core dump (since that is the `SIG_DFL` behavior of the signal to begin with).

**Comment by ianlancetaylor** [comment]
We don't ignore user-generated `SIGSEGV` signals.  That's the point of the test.  I'm not sure what you are saying here.

The test failure logs suggest that the problem is that we somehow think that we are out of stack space while handling a signal.  I'm not sure how that could happen.

**Comment by cherrymui** [comment]
In my experience, "morestack on g0" is usually not we are actually running out of stack space on g0, but somehow the SP and and the G (and so the stack bounds) don't match. My comment above mentioned some possibilities, e.g. signal lands right in the middle of a stack switch.

As @ianlancetaylor said, we don't ignore user-generated SIGSEGV (we did it in the past, but not now). The specialness of darwin is that we treat user-generated SIGSEGV (which should crash the runtime) as kernel-generated (which causes a panic), due to a kernel bug ( https://tip.golang.org/src/runtime/signal_darwin_amd64.go#L72 ). Because of that, we inject a `sigpanic` call, instead of just throw, and somewhere down the panic path there are non-nosplit functions that check stack bounds. If the G and stack bounds don't match, it could crash like this.

**Comment by bcmills** [comment]
[2021-02-21T02:25:41-0f66fb7/darwin-amd64-10_14](https://build.golang.org/log/1cfc4bd6d03a8041d8d6918a22d01a0f331683e7)
[2020-12-14T22:28:10-48906a6/darwin-amd64-10_14](https://build.golang.org/log/5abea5ebec2a0569d25f400c8bd5cb8a5db0866b)
[2020-10-27T03:11:45-a19cf51/darwin-amd64-10_15](https://build.golang.org/log/60e41fa08fc2fab20e8aeb2534d2ac77eccfd584)
[2020-10-17T00:32:32-11cfb48/darwin-amd64-10_15](https://build.golang.org/log/762a86b378fa283f5402d220bfff216531a14d0d)

**Comment by bcmills** [comment]
[2021-06-07T15:16:23-e3176bb/darwin-amd64-noregabi](https://build.golang.org/log/20ded2fb4b72d24c9743b6bea8d82d89cea379e1)
[2021-04-30T05:18:37-9c72078/darwin-amd64-10_15](https://build.golang.org/log/2cb5ff85c6bc95b6ae7711d06239a7cace0949b3)
[2021-04-14T21:00:20-23f8c20/darwin-amd64-11_0](https://build.golang.org/log/f679b0da18dec81bc0829745bce5d534a7f0cf5b)
[2021-04-06T03:31:38-d8306ee/darwin-amd64-10_15](https://build.golang.org/log/6133355272bccbed1ee2da0a6210296284a949f5)
[2021-04-02T21:57:58-f25d78f/darwin-amd64-10_15](https://build.golang.org/log/e41b2512d11e62b010c6194fc3419aa5fd28ea17)

**Comment by bcmills** [comment]
`greplogs --dashboard -md -l -e 'FAIL: TestSegv .*(?:\n    .*)*fatal: morestack on g0' --since=2021-06-08`

[2022-02-01T21:46:52-36b81ac/darwin-amd64-10_15](https://build.golang.org/log/46aa6f2258ab9c8151f3fb712ca18d191609f7af)
[2022-01-10T20:53:01-55d10ac/darwin-amd64-12_0](https://build.golang.org/log/8b71f2bc33dd35e54b9b47948c39ff56c892eaf4)
[2021-11-09T18:23:16-55e6e82/darwin-amd64-10_15](https://build.golang.org/log/c46032025851b000e280854ddae87cbef6d99fd1)
[2021-11-05T22:28:56-87a3fc5/darwin-amd64-10_14](https://build.golang.org/log/4c5a9700a474fd519f310ef5874821add80c7c67)
[2021-10-27T16:39:27-4f73fd0/darwin-amd64-race](https://build.golang.org/log/3e4550ed9c7dbce1ac67819d9a318d9914f0804b)
[2021-09-17T21:29:32-3fa7dbe/darwin-amd64-10_15](https://build.golang.org/log/2588344f88ca9d8f03c4a519adbb390c03aff804)
[2021-09-12T16:46:58-ad97d20/darwin-amd64-10_15](https://build.golang.org/log/4c511503a7672a792a115cbda886290274f70c24)
[2021-09-09T12:57:26-66f0d35/darwin-amd64-10_14](https://build.golang.org/log/2b89098251de5cdfcfa8ed1d641fc3884ca59fa1)
[2021-09-02T19:36:22-a8aa6cf/darwin-amd64-noregabi](https://build.golang.org/log/ed24d79a1473ab3211b252b50dc39f7152808019)
[2021-08-27T20:43:31-72c003e/darwin-amd64-noregabi](https://build.golang.org/log/6493cb2122590b090602270cec6db6d59a83b077)
[2021-08-19T00:26:22-c85695a/darwin-amd64-11_0](https://build.golang.org/log/736b282ef05a314b19e020344bc59ff0527bce8b)
[2021-08-18T08:26:44-8b471db/darwin-amd64-11_0](https://build.golang.org/log/a4fbcbef108ea1dcbdcb06d3324f5fafca4e99ac)
[2021-08-15T19:08:56-6ed9463/darwin-amd64-race](https://build.golang.org/log/d8835d87a49666e187e17b8157e2da45bec31d19)
[2021-06-30T16:44:19-0fa3265/darwin-amd64-race](https://build.golang.org/log/275acd64a21f1ddb6fa1b4dbdeea58d8a13af68c)
[2021-06-17T04:32:50-97cee43/darwin-amd64-race](https://build.golang.org/log/8922de1acc87dda017e8334286ab5802e7d4a55c)

**Comment by evanw** [comment]
I have a user report about this error on a Windows machine with [esbuild](github.com/evanw/esbuild), which is written in Go but doesn't use cgo: https://github.com/evanw/esbuild/issues/2031. I searched and found this issue and that report seemed potentially related, so I'm posting about it here in case it helps.

**Comment by cherrymui** [comment]
@evanw that looks like a different issue. Could you open a new issue? Thanks.

This issue is very specific to darwin (macOS) when a program receives an external SIGSEGV signal (e.g. by `kill` command or syscall).
