### ISSUE TITLE
runtime: SIGSEGV during sigpanic in TestCgoCallbackGC on netbsd-386-9_0 builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#39595]
[2020-06-12T17:25:26-7d975ae/netbsd-386-9_0](https://build.golang.org/log/862ed3ce6f311e40e8321f3bb863c3acb52dc6b8)

```
--- FAIL: TestCgoCallbackGC (0.71s)
    crash_test.go:105: /tmp/go-build517568832/testprogcgo.exe CgoCallbackGC exit status: exit status 2
    crash_cgo_test.go:70: expected "OK\n", but got:
        fatal error: unexpected signal during runtime execution
        [signal SIGSEGV: segmentation violation code=0x1 addr=0xcd42f9e0 pc=0xada54001]
        
        runtime stack:
        runtime.throw(0x81765a7, 0x2a)
        	/tmp/workdir/go/src/runtime/panic.go:1116 +0x64
        runtime.sigpanic()
        	/tmp/workdir/go/src/runtime/signal_unix.go:704 +0x38e
        
        goroutine 14 [syscall]:
        runtime.cgocall(0x8138c38, 0x85677dc, 0x85677dc)
        	/tmp/workdir/go/src/runtime/cgocall.go:133 +0x61 fp=0x85677c8 sp=0x85677b0 pc=0x804c971
        main._Cfunc_foo()
        	_cgo_gotypes.go:228 +0x2d fp=0x85677dc sp=0x85677c8 pc=0x81317fd
        main.CgoCallbackGC.func2(0x8502080)
        	/tmp/workdir/go/src/runtime/testdata/testprogcgo/callback.go:85 +0x14 fp=0x85677e8 sp=0x85677dc pc=0x8136984
        runtime.goexit()
        	/tmp/workdir/go/src/runtime/asm_386.s:1333 +0x1 fp=0x85677ec sp=0x85677e8 pc=0x80a35f1
        created by main.CgoCallbackGC
        	/tmp/workdir/go/src/runtime/testdata/testprogcgo/callback.go:84 +0xde
```

Possibly related to #37605.

CC @ianlancetaylor @cherrymui @bsiegert

**Comment by bcmills** [comment]
[2020-07-16T23:38:32-4469f54/netbsd-386-9_0](https://build.golang.org/log/f18143c6dfb97090a6dceff796ed97185b7e213d)
[2020-06-12T17:25:26-7d975ae/netbsd-386-9_0](https://build.golang.org/log/862ed3ce6f311e40e8321f3bb863c3acb52dc6b8)

**Comment by bcmills** [comment]
[2020-12-22T15:59:17-4d27c4c/netbsd-386-9_0](https://build.golang.org/log/3186b95699e026f7ddb5447fbeb59bc92f4bfd56)
[2020-08-18T04:11:37-6dad1b4/netbsd-386-9_0](https://build.golang.org/log/287b3407892bbb7907154fff8c381b1142f6e2ef)

**Comment by bcmills** [comment]
A possible connection between this issue and #32023: a failure on this builder, but with that failure mode:
[2021-02-25T01:30:37-ff614b1/netbsd-386-9_0](https://build.golang.org/log/7add18b35b6c12f1eedc1ae6847f7500ed3ba164)
