### ISSUE TITLE
cmd/go2go: SIGSEGV while comparing exported variables

### ISSUE THREAD

**Issue by kovetskiy** [golang/go#39878]
go version devel +4dfbf5ab9c7 Thu Jun 25 02:57:14 2020 +0000 linux/amd64

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x620049]

goroutine 1 [running]:
go/types.(*Package).Scope(...)
        /usr/lib/go/src/go/types/package.go:42
go/go2go.(*translator).instantiationTypes(0xc000167698, 0xc00011a380, 0x0, 0xc00000c3e0, 0x2, 0xc000126ba0, 0xc000167010, 0x526bec, 0x650900)
        /usr/lib/go/src/go/go2go/rewrite.go:1035 +0x109
go/go2go.(*translator).translateFunctionInstantiation(0xc000167698, 0xc0000685e0)
        /usr/lib/go/src/go/go2go/rewrite.go:872 +0xa7
go/go2go.(*translator).translateExpr(0xc000167698, 0xc0000685e0)
        /usr/lib/go/src/go/go2go/rewrite.go:680 +0x3cc
go/go2go.(*translator).translateStmt(0xc000167698, 0xc0000685f0)
        /usr/lib/go/src/go/go2go/rewrite.go:575 +0x3ac
go/go2go.(*translator).translateBlockStmt(0xc000167698, 0xc000010bd0)
        /usr/lib/go/src/go/go2go/rewrite.go:544 +0x57
go/go2go.(*translator).translateFuncDecl(0xc000167698, 0xc00011a3e0)
        /usr/lib/go/src/go/go2go/rewrite.go:534 +0xc5
go/go2go.(*translator).translate(0xc000167698, 0xc000024200)
        /usr/lib/go/src/go/go2go/rewrite.go:461 +0x391
go/go2go.rewriteAST(0xc00011a240, 0xc0000743c0, 0x0, 0x0, 0xc00007f6d0, 0xc000024200, 0x7f48a7eba201, 0xc000144420, 0x817bc0)
        /usr/lib/go/src/go/go2go/rewrite.go:257 +0xe5
go/go2go.rewriteFile(0xc000016460, 0x17, 0xc00011a240, 0xc0000743c0, 0x0, 0x0, 0xc00007f6d0, 0xc0000164e0, 0x20, 0xc000024200, ...)
        /usr/lib/go/src/go/go2go/rewrite.go:221 +0xb8
go/go2go.rewriteFilesInPath(0xc0000743c0, 0x0, 0x0, 0xc000016460, 0x17, 0xc000068490, 0x1, 0x1, 0x0, 0x0, ...)
        /usr/lib/go/src/go/go2go/go2go.go:106 +0xbd1
go/go2go.rewriteToPkgs(0xc0000743c0, 0x0, 0x0, 0xc000016460, 0x17, 0xc0000101a0, 0xc000016460, 0x17, 0x7ffe50c6ac41, 0x8)
        /usr/lib/go/src/go/go2go/go2go.go:46 +0x165
go/go2go.Rewrite(...)
        /usr/lib/go/src/go/go2go/go2go.go:30
main.translate(0xc0000743c0, 0xc000016460, 0x17)
        /usr/lib/go/src/cmd/go2go/translate.go:15 +0x47
main.main()
        /usr/lib/go/src/cmd/go2go/main.go:54 +0xb25

```

```
package main

import "errors"

var (
	A = errors.New("a")
	B = errors.New("b")
)

func main() {
	x(A, B)
}

func x(type T comparable)(a, b T) {
	_ = a == b
}

```

**Comment by kovetskiy** [comment]
Also checked on
go version devel +1b08acee45f Thu Jun 25 23:22:18 2020 +0000 linux/amd64

**Comment by ianlancetaylor** [comment]
Thanks for the test case.  This is now fixed on the dev.go2go branch.
