### ISSUE TITLE
segmentation error when using sync.Map.Load()

### ISSUE THREAD

**Issue by TUTUBIG** [golang/go#40865]
```
unexpected fault address 0x0 fatal error: fault [signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x45a81f]
goroutine 16 [running]:
runtime.throw(0xec2328, 0x5)
   /usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc001321c98 sp=0xc001321c68 pc=0x42da32 
runtime.sigpanic()
   /usr/local/go/src/runtime/signal_unix.go:401 +0x3de fp=0xc001321cc8 sp=0xc001321c98 pc=0x44250e 
aeshashbody()
   /usr/local/go/src/runtime/asm_amd64.s:1143 +0x38f fp=0xc001321cd0 sp=0xc001321cc8 pc=0x45a81f 
runtime.nilinterhash(0xc001321dc0, 0x0, 0x0)
   /usr/local/go/src/runtime/alg.go:171 +0xb5 fp=0xc001321d18 sp=0xc001321cd0 pc=0x403325 
runtime.mapaccess2(0xd72f00, 0x0, 0xc001321dc0, 0x10, 0xdc5040)
   /usr/local/go/src/runtime/map.go:465 +0x25d fp=0xc001321d60 sp=0xc001321d18 pc=0x40dc4d 
sync.(*Map).Load(0xc0003a3d70, 0xd3d5c0, 0xc001321ed8, 0xc001a3f680, 0xc001a19dd0, 0x1) 
  /usr/local/go/src/sync/map.go:104 +0xa9 fp=0xc001321de0 sp=0xc001321d60 pc=0x4676d9
```

what this reason should be？

**Comment by TUTUBIG** [comment]
go 1.14 running in Docker container

**Comment by randall77** [comment]
A fault at runtime/asm_amd64.s:1143 seems impossible. The instruction there:
```
	AESENC	X2, X2
```
can't fault.

Are you sure it is go 1.14? I also checked 1.14.1 and 1.14.2, same deal.

**Comment by networkimprov** [comment]
@TUTUBIG please fill in the issue template from https://github.com/golang/go/issues/new/choose

It's really difficult to diagnose problems with incomplete information.

Please provide a complete program to reproduce the problem if possible.

**Comment by TUTUBIG** [comment]
i'll close this issue now and maybe reopen it if this problem come out again
