### ISSUE TITLE
x/net/http2: delayed test failure in TestTransportPingWhenReading

### ISSUE THREAD

**Issue by bcmills** [golang/go#41299]
```
panic: Fail in goroutine after TestTransportPingWhenReading/two_pings_in_each_serverResponseInterval has completed

goroutine 14781 [running]:
testing.(*common).Fail(0xba2bb5e0)
	/workdir/go/src/testing/testing.go:680 +0x105
testing.(*common).Error(0xba2bb5e0, 0xb8bbcfcc, 0x1, 0x1)
	/workdir/go/src/testing/testing.go:780 +0x62
golang.org/x/net/http2.testTransportPingWhenReading.func2.1(0xb8c80498, 0xb894a5a0, 0xb8922da0, 0xba2bb5e0, 0x3b9aca00, 0x0)
	/workdir/gopath/src/golang.org/x/net/http2/transport_test.go:3514 +0x30b
created by golang.org/x/net/http2.testTransportPingWhenReading.func2
	/workdir/gopath/src/golang.org/x/net/http2/transport_test.go:3500 +0x33d
exitcode=2FAIL	golang.org/x/net/http2	26.736s
```

[2020-09-04T19:48:48-62affa3/android-386-emu](https://build.golang.org/log/fc8483c675962b5b06d412ddda1ff2082eb79509)
[2020-09-04T19:48:48-62affa3/linux-ppc64le-buildlet](https://build.golang.org/log/31c8fa9d15497c0ad7f3c0fbc9ea8f3521407e8b)
[2020-08-22T12:43:28-c890458/dragonfly-amd64-5_8](https://build.golang.org/log/2415fdcf9f39a2096c694d900a49b31138073320)
[2020-08-22T12:43:28-c890458/freebsd-arm-paulzhol](https://build.golang.org/log/555463009e584a6bd8502a3a3cf6db5bc01e334c)
[2020-08-22T12:43:28-c890458/freebsd-arm64-dmgk](https://build.golang.org/log/006fc97735f854cfc249d228f8207edf326403e4)
[2020-08-22T12:43:28-c890458/linux-arm](https://build.golang.org/log/fcf9f007c77036fe0c936873e6969ab93fe4b420)
[2020-08-22T12:43:28-c890458/linux-ppc64le-buildlet](https://build.golang.org/log/f9c1a4d9e9320691ae05f7fba372292eaf667e53)
[2020-08-13T13:45:08-3edf25e/darwin-amd64-10_12](https://build.golang.org/log/d014a5e874958e75a55b076ef8b2b5c218c6082a)
[2020-08-13T13:45:08-3edf25e/darwin-amd64-nocgo](https://build.golang.org/log/979cdb0a9eb6d159dfa3af0fc7174ce9593305d6)
[2020-08-13T13:45:08-3edf25e/freebsd-arm64-dmgk](https://build.golang.org/log/c838cf12e06dfeddc4bcdec77d022fc4d63b24bb)
[2020-08-13T13:45:08-3edf25e/linux-ppc64-buildlet](https://build.golang.org/log/68f4bac24691b5d3cf6ae2cdf0cfb554720b3e4c)
[2020-08-13T13:45:08-3edf25e/linux-ppc64le-buildlet](https://build.golang.org/log/5a36656f3b46a299596b22bfa70a4f16330d9f7c)
[2020-07-07T03:43:11-ab34263/freebsd-arm64-dmgk](https://build.golang.org/log/e32167561504d6ae755ae358f84bead2aa6dcb26)
[2020-06-25T00:16:55-4c52546/linux-ppc64-buildlet](https://build.golang.org/log/2d90d56950764190722916483a0e65781b91fe0b)
[2020-06-25T00:16:55-4c52546/linux-s390x-ibm](https://build.golang.org/log/50c4b4a553bea2929a3e372b671fe8f4c3990c08)
[2020-06-25T00:16:55-4c52546/plan9-386-0intro](https://build.golang.org/log/55b5de5f7d1f79ee07af8d9cbbd31b270523d44b)
[2020-06-25T00:16:55-4c52546/plan9-amd64-9front](https://build.golang.org/log/d4da41b55b6e8971ee553a54b917716d28c0576d)
[2020-06-02T11:40:24-627f964/dragonfly-amd64](https://build.golang.org/log/c2e87a6eb41c054286f246eae1c213e489c46bca)
[2020-06-02T11:40:24-627f964/freebsd-arm64-dmgk](https://build.golang.org/log/e194d8d22e57a4f8d76a84ab003342921e183bef)
[2020-06-02T11:40:24-627f964/linux-mips-rtrk](https://build.golang.org/log/02a8abb3a1eeb57854835342398993194b660427)
[2020-06-02T11:40:24-627f964/linux-s390x-ibm](https://build.golang.org/log/fb10ee666c2158e0bee33165cd2d562dbb606770)
[2020-06-02T11:40:24-627f964/plan9-386-0intro](https://build.golang.org/log/30c62b69f86b4ce0ded83a4a4a233a417abd9176)
[2020-06-02T11:40:24-627f964/plan9-amd64-9front](https://build.golang.org/log/8ba98f4d4b9142314a9401e3436cf8faa4ca4c3d)
[2020-06-02T11:40:24-627f964/solaris-amd64-oraclerel](https://build.golang.org/log/7397665a5c809a34ef051cd3c8f5e41093c01c9c)
[2020-05-28T22:51:25-3c3fba1/freebsd-arm64-dmgk](https://build.golang.org/log/4c15cca639c6bec1437f6485be739d38d27cf7a8)
[2020-05-28T22:51:25-3c3fba1/linux-ppc64le-buildlet](https://build.golang.org/log/7367891d04bcff4cc530edb19e7bcad3f957f969)
[2020-05-20T18:23:14-0ba52f6/android-386-emu](https://build.golang.org/log/4a5484788c091c8d1bfe2b3923c722c5e548f2ba)
[2020-05-20T18:23:14-0ba52f6/darwin-amd64-10_12](https://build.golang.org/log/d3e2ddd6dc345f50c4395047980c70cd5a7609c7)
[2020-05-20T18:23:14-0ba52f6/darwin-amd64-10_15](https://build.golang.org/log/7dfab741ad7c73f4c9e97b3bee863891ca21a6f3)
[2020-05-20T18:23:14-0ba52f6/freebsd-arm64-dmgk](https://build.golang.org/log/7ad8c2150c243c15ae3e19a7f927c63327c73b9a)
[2020-05-20T18:23:14-0ba52f6/linux-ppc64-buildlet](https://build.golang.org/log/2bafe12fb42cfbf96294d5e6f807723b596b1f99)
[2020-05-20T18:23:14-0ba52f6/linux-ppc64le-buildlet](https://build.golang.org/log/495efb2cecb7e9d5446979445c8398ec1d6b9630)
[2020-05-20T18:23:14-0ba52f6/plan9-386-0intro](https://build.golang.org/log/cc0167afa94ee5877dbb4870624e8cdd9c81fa96)

It looks like the test server starts a [goroutine](https://github.com/golang/net/blob/62affa334b73ec65ed44a326519ac12c421905e3/http2/transport_test.go#L3500-L3518) but does not wait for it to complete before the server function exits.

CC @caesarxuchao @bradfitz @fraenkel @neild

**Comment by bcmills** [comment]
Unfortunately, the fix for this seems to have been incomplete:
[2020-10-31T05:49:03-ff519b6/aix-ppc64](https://build.golang.org/log/917fe2d3478091193c8ffb342c2a7b50be0697fd)
[2020-10-31T05:49:03-ff519b6/android-amd64-emu](https://build.golang.org/log/7bde7d624617d1dd7ec84d5554392a36ffe6fd35)
[2020-10-31T05:49:03-ff519b6/freebsd-arm-paulzhol](https://build.golang.org/log/1904191eb5c341dc7eac24101fde0fa63c113a19)
[2020-10-31T05:49:03-ff519b6/linux-s390x-ibm](https://build.golang.org/log/5a9d9bf7eeb4f351c2f7cd1cd97345313784d2f1)
[2020-10-31T05:49:03-ff519b6/solaris-amd64-oraclerel](https://build.golang.org/log/f22c1b7cb93f16a601b45f93f8a73d4d4ce59b8d)
[2020-10-29T22:17:08-28c70e6/aix-ppc64](https://build.golang.org/log/9ca10adfa3c4b1a22c1e43cc80d75c412c74ae5f)
[2020-10-29T22:17:08-28c70e6/android-386-emu](https://build.golang.org/log/f7472fab3a6e17cfa030419e13330291306337d7)
[2020-10-29T22:17:08-28c70e6/dragonfly-amd64-5_8](https://build.golang.org/log/f50fe49622f9a8f0d57b8f9da2b7715a7a39af00)
[2020-10-29T22:17:08-28c70e6/freebsd-arm-paulzhol](https://build.golang.org/log/8961f10279bd8791d8487044721af60a4bdfa1ee)
[2020-10-29T22:17:08-28c70e6/freebsd-arm64-dmgk](https://build.golang.org/log/a3424ab32db80cbcb165b89b5b8f7cf12bcecc53)
[2020-10-29T22:17:08-28c70e6/linux-ppc64le-buildlet](https://build.golang.org/log/18f2ade6562709f0e8da1959d303e8cb8bbd6e01)
[2020-10-29T05:33:32-8adf50f/dragonfly-amd64](https://build.golang.org/log/5029ace267a6ba8e20e459453c520b3ca2faa30f)
[2020-10-29T03:25:33-e049550/dragonfly-amd64-5_8](https://build.golang.org/log/6739c75731d7f7df32818a6241ad17c905ceb8a1)
[2020-10-29T03:25:33-e049550/linux-ppc64-buildlet](https://build.golang.org/log/504b29e6c6c2bea312376b67252987cd5507803b)
[2020-10-27T13:37:19-8eef523/aix-ppc64](https://build.golang.org/log/7500e95896f8d9a8edfef8a575250c0eb813d52e)
[2020-10-27T13:37:19-8eef523/linux-mipsle-rtrk](https://build.golang.org/log/2d81d2414b6cb354cd1b8a1e1298b3a5fabdc080)
[2020-10-27T13:37:19-8eef523/linux-ppc64-buildlet](https://build.golang.org/log/a281191891a4c37b3c088fb866715f5bb3be3d32)
[2020-10-27T13:37:19-8eef523/linux-ppc64le-buildlet](https://build.golang.org/log/e1e4a4143b8e007abe1fe495c84041515c03d153)
[2020-10-26T09:15:29-146b70c/freebsd-arm-paulzhol](https://build.golang.org/log/3998aed1725d5e33b82190b6722ba94a18c1ea56)
[2020-10-26T09:15:29-146b70c/freebsd-arm64-dmgk](https://build.golang.org/log/89e0f8e019f8290967255886cc0ec9a0f57c3879)
[2020-10-26T09:15:29-146b70c/linux-ppc64-buildlet](https://build.golang.org/log/5e1ddf09799b76a1f1f2facfe26cf23437bb52bd)
