### ISSUE TITLE
cmd/compile:  internal compiler error: 'makeToplevelFunction': not lowered: v109, StructMake1 STRUCT UNSAFEPTR

### ISSUE THREAD

**Issue by OneOfOne** [golang/go#41736]
```sh
┏━ oneofone@voyager ❰~❱ 
┗━● go get -u github.com/go-delve/delve/...
go: found github.com/go-delve/delve/... in github.com/go-delve/delve v1.5.0
go: github.com/mattn/go-isatty upgrade => v0.0.12
go: github.com/peterh/liner upgrade => v1.2.0
go: github.com/spf13/cobra upgrade => v1.0.0
go: github.com/spf13/pflag upgrade => v1.0.5
go: github.com/sirupsen/logrus upgrade => v1.7.0
go: golang.org/x/arch upgrade => v0.0.0-20200826200359-b19915210f00
go: golang.org/x/sys upgrade => v0.0.0-20200930185726-fdedc70b468f
go: github.com/mattn/go-colorable upgrade => v0.1.7
go: github.com/google/go-dap upgrade => v0.3.0
go: github.com/konsorten/go-windows-terminal-sequences upgrade => v1.0.3
go: go.starlark.net upgrade => v0.0.0-20200929122913-88a10930eb75
go: gopkg.in/yaml.v2 upgrade => v2.3.0
go: github.com/mattn/go-runewidth upgrade => v0.0.9
# go.starlark.net/starlark
code/go/pkg/mod/go.starlark.net@v0.0.0-20200929122913-88a10930eb75/starlark/eval.go:463:14: internal compiler error: 'makeToplevelFunction': not lowered: v109, StructMake1 STRUCT UNSAFEPTR

goroutine 81 [running]:
runtime/debug.Stack(0xd6ef00, 0xc00000e018, 0x0)
	/usr/src/go/src/runtime/debug/stack.go:24 +0x9f
cmd/compile/internal/gc.Fatalf(0xc0006ede80, 0x8, 0xc0024f1980, 0x2, 0x2)
	/usr/src/go/src/cmd/compile/internal/gc/subr.go:199 +0x1b0
cmd/compile/internal/gc.(*ssafn).Fatalf(0xc000480a20, 0x1cf0e100000003, 0xc53802, 0x2, 0xc00188b3f0, 0x1, 0x1)
	/usr/src/go/src/cmd/compile/internal/gc/ssa.go:6987 +0x1a5
cmd/compile/internal/ssa.(*Func).Fatalf(...)
	/usr/src/go/src/cmd/compile/internal/ssa/func.go:652
cmd/compile/internal/ssa.checkLower(0xc00230cf20)
	/usr/src/go/src/cmd/compile/internal/ssa/lower.go:36 +0x41a
cmd/compile/internal/ssa.Compile(0xc00230cf20)
	/usr/src/go/src/cmd/compile/internal/ssa/compile.go:93 +0x9cd
cmd/compile/internal/gc.buildssa(0xc00013f340, 0x1, 0x0)
	/usr/src/go/src/cmd/compile/internal/gc/ssa.go:464 +0xd5a
cmd/compile/internal/gc.compileSSA(0xc00013f340, 0x1)
	/usr/src/go/src/cmd/compile/internal/gc/pgen.go:319 +0x5d
cmd/compile/internal/gc.compileFunctions.func2(0xc00194ac00, 0xc00092f6f0, 0x1)
	/usr/src/go/src/cmd/compile/internal/gc/pgen.go:384 +0x4d
created by cmd/compile/internal/gc.compileFunctions
	/usr/src/go/src/cmd/compile/internal/gc/pgen.go:382 +0x129


┏━ oneofone@voyager ❰~❱
┗━● go version
go version devel +5756b35601 2020-10-01 19:13:03 +0000 linux/amd64
```

**Comment by cherrymui** [comment]
@dr2chase probably related to call lowering.

**Comment by dr2chase** [comment]
Totally related to call lowering.
Give me a few minutes....

**Comment by dr2chase** [comment]
PS @cherrymui can you have a look at https://go-review.googlesource.com/c/go/+/252338/6 ?
I made the requested changes in the latest patch set, it might be helpful in a case like this (if the problematic file happens to be vendored or in a module etc).

**Comment by cherrymui** [comment]
Done.

**Comment by dr2chase** [comment]
That CL there needs a review, will keep the lights on for now.  Thanks to @andybons for "big scary features need revert switches" (this is the same switch I use for binary search dev testing, so I know it works).
