### ISSUE TITLE
net: apparent deadlock in TestVariousDeadlines on arm64

### ISSUE THREAD

**Issue by bcmills** [golang/go#41863]
[2020-10-07T20:07:07-83dfc0d/linux-arm64-aws](https://build.golang.org/log/d35d88733b6bf4211c2781806ec8b25d8b39c859)
[2020-09-30T05:39:59-3caaadd/linux-arm64-aws](https://build.golang.org/log/07b3365a4e3ac8b5c2aee270d589379e1bf673a5)
[2020-09-25T18:07:42-74c3b50/linux-arm64-aws](https://build.golang.org/log/5680114886d5558f350d0190a4c05381d5814934)
[2020-09-24T18:18:20-4285094/linux-arm64-aws](https://build.golang.org/log/cf4291366f40a0803937ae89b571fa54c0b18bf3)
[2020-09-18T17:21:06-d91d076/linux-arm64-aws](https://build.golang.org/log/68b4a2e6e0783a134c051243af28be69912b5f5c)
[2020-09-16T16:07:00-37aa653/linux-arm64-aws](https://build.golang.org/log/2199ba9fd4e18095eddaea2c44c3a6a1790c6a3a)
[2020-09-13T19:17:09-66e66e7/linux-arm64-aws](https://build.golang.org/log/caaaceea03cf43434af67de22d8a157eed3a72e9)
[2020-09-11T14:22:17-6e3df74/linux-arm64-aws](https://build.golang.org/log/6297017691ded2c2629ac005f2715388a5761693)
[2020-08-25T20:04:27-8381408/linux-arm64-aws](https://build.golang.org/log/596c3fd72c84a009318e97aa392e35e110a290cc)

<details>

```
panic: test timed out after 3m0s

goroutine 41077 [running]:
testing.(*M).startAlarm.func1()
	/workdir/go/src/testing/testing.go:1680 +0xc8
created by time.goFunc
	/workdir/go/src/time/sleep.go:167 +0x40

goroutine 1 [chan receive, 2 minutes]:
testing.tRunner.func1(0x4000001980)
	/workdir/go/src/testing/testing.go:1139 +0x218
testing.tRunner(0x4000001980, 0x400011dd28)
	/workdir/go/src/testing/testing.go:1177 +0x10c
testing.runTests(0x400000e048, 0x408520, 0xee, 0xee, 0xbfd7a67a7982b084, 0x29e8dec58a, 0x40bbe0, 0x40000467b0)
	/workdir/go/src/testing/testing.go:1489 +0x29c
testing.(*M).Run(0x400011e000, 0x0)
	/workdir/go/src/testing/testing.go:1397 +0x1b4
net.TestMain(0x400011e000)
	/workdir/go/src/net/main_test.go:52 +0x30
main.main()
	_testmain.go:589 +0x160

goroutine 4061 [chan send, 2 minutes]:
testing.tRunner.func1.1(0x4000253ec0, 0x0, 0x0, 0x400044e600, 0x4000253e01)
	/workdir/go/src/testing/testing.go:1103 +0x50
testing.tRunner.func1(0x400044e600)
	/workdir/go/src/testing/testing.go:1164 +0x30c
testing.tRunner(0x400044e600, 0x284d88)
	/workdir/go/src/testing/testing.go:1177 +0x10c
created by testing.(*T).Run
	/workdir/go/src/testing/testing.go:1218 +0x244

goroutine 4459 [chan send, 2 minutes]:
testing.tRunner.func1.1(0x400025eec0, 0x0, 0x0, 0x4000518600, 0x400025ee01)
	/workdir/go/src/testing/testing.go:1103 +0x50
testing.tRunner.func1(0x4000518600)
	/workdir/go/src/testing/testing.go:1164 +0x30c
testing.tRunner(0x4000518600, 0x2848d0)
	/workdir/go/src/testing/testing.go:1177 +0x10c
created by testing.(*T).Run
	/workdir/go/src/testing/testing.go:1218 +0x244

goroutine 4062 [chan send, 2 minutes]:
testing.tRunner.func1.1(0x40002b5ec0, 0x0, 0x0, 0x400044e780, 0x40002b5e01)
	/workdir/go/src/testing/testing.go:1103 +0x50
testing.tRunner.func1(0x400044e780)
	/workdir/go/src/testing/testing.go:1164 +0x30c
testing.tRunner(0x400044e780, 0x284d70)
	/workdir/go/src/testing/testing.go:1177 +0x10c
created by testing.(*T).Run
	/workdir/go/src/testing/testing.go:1218 +0x244

goroutine 4506 [chan receive, 2 minutes]:
testing.runTests.func1.1(0x4000001980)
	/workdir/go/src/testing/testing.go:1496 +0x30
created by testing.runTests.func1
	/workdir/go/src/testing/testing.go:1496 +0xa8

goroutine 4058 [chan receive, 2 minutes]:
net.(*localServer).teardown(0x40002bcc60, 0x400012c678, 0x17488)
	/workdir/go/src/net/mockserver_test.go:107 +0xec
runtime.Goexit()
	/workdir/go/src/runtime/panic.go:641 +0x110
testing.(*common).FailNow(0x400044e180)
	/workdir/go/src/testing/testing.go:734 +0x38
testing.(*common).Fatalf(0x400044e180, 0x27ae25, 0x1d, 0x4000556ec8, 0x1, 0x1)
	/workdir/go/src/testing/testing.go:808 +0x78
net.testVariousDeadlines(0x400044e180)
	/workdir/go/src/net/timeout_test.go:891 +0x79c
net.TestVariousDeadlines(0x400044e180)
	/workdir/go/src/net/timeout_test.go:772 +0x34
testing.tRunner(0x400044e180, 0x2850f0)
	/workdir/go/src/testing/testing.go:1173 +0xdc
created by testing.(*T).Run
	/workdir/go/src/testing/testing.go:1218 +0x244

goroutine 6060 [IO wait, 2 minutes]:
internal/poll.runtime_pollWait(0xffff9283b3b8, 0x72, 0x3e0550)
	/workdir/go/src/runtime/netpoll.go:220 +0x44
internal/poll.(*pollDesc).wait(0x4000452598, 0x72, 0x400051c600, 0x1, 0x1)
	/workdir/go/src/internal/poll/fd_poll_runtime.go:87 +0x38
internal/poll.(*pollDesc).waitRead(...)
	/workdir/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0x4000452580, 0x400051c67f, 0x1, 0x1, 0x0, 0x0, 0x0)
	/workdir/go/src/internal/poll/fd_unix.go:166 +0x164
net.(*netFD).Read(0x4000452580, 0x400051c67f, 0x1, 0x1, 0x40001bff28, 0x1e7a14, 0x1)
	/workdir/go/src/net/fd_posix.go:55 +0x44
net.(*conn).Read(0x40000101a0, 0x400051c67f, 0x1, 0x1, 0x0, 0x0, 0x0)
	/workdir/go/src/net/net.go:183 +0x74
net.testVariousDeadlines.func1(0x40002bcc60, 0x2c4368, 0x400000e648)
	/workdir/go/src/net/timeout_test.go:818 +0x6c
net.(*localServer).buildup.func1(0x285310, 0x40002bcc60)
	/workdir/go/src/net/mockserver_test.go:95 +0x40
created by net.(*localServer).buildup
	/workdir/go/src/net/mockserver_test.go:94 +0x44

goroutine 6078 [IO wait, 2 minutes]:
internal/poll.runtime_pollWait(0xffff9283bf18, 0x72, 0x3e0550)
	/workdir/go/src/runtime/netpoll.go:220 +0x44
internal/poll.(*pollDesc).wait(0x40001e8498, 0x72, 0x4000162000, 0x2000, 0x2000)
	/workdir/go/src/internal/poll/fd_poll_runtime.go:87 +0x38
internal/poll.(*pollDesc).waitRead(...)
	/workdir/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0x40001e8480, 0x4000162000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
	/workdir/go/src/internal/poll/fd_unix.go:166 +0x164
net.(*netFD).Read(0x40001e8480, 0x4000162000, 0x2000, 0x2000, 0x1, 0x2fc8fbec5b, 0x0)
	/workdir/go/src/net/fd_posix.go:55 +0x44
net.(*conn).Read(0x40001c0260, 0x4000162000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
	/workdir/go/src/net/net.go:183 +0x74
io/ioutil.devNull.ReadFrom(0x0, 0x2c0588, 0x40001c0260, 0x23b040, 0x1, 0xffff91561620)
	/workdir/go/src/io/ioutil/ioutil.go:144 +0x84
io.copyBuffer(0x2c08c8, 0x43b430, 0x2c0588, 0x40001c0260, 0x0, 0x0, 0x0, 0x0, 0x2c0548, 0x40001e4a00)
	/workdir/go/src/io/io.go:397 +0x288
io.Copy(...)
	/workdir/go/src/io/io.go:370
net.testVariousDeadlines.func2(0x2c7470, 0x40001c0260, 0x400001dea0, 0x400044e180, 0x4000413320)
	/workdir/go/src/net/timeout_test.go:877 +0x114
created by net.testVariousDeadlines
	/workdir/go/src/net/timeout_test.go:872 +0x508
FAIL	net	180.023s
```

</details>

See previously #37883, #19519 (`TestVariousDeadlines`); #41326 (`net` deadlock on `linux-arm64-aws`).

CC @cagedmantis (`linux-arm64-aws`), @mikioh @bradfitz @ianlancetaylor (`net`)

**Comment by bcmills** [comment]
[2021-01-08T17:08:44-e65c543/linux-arm64-aws](https://build.golang.org/log/5356d4ad77f7088333c2a2cf9ba37f1de158f406)
[2020-11-21T07:37:02-f734259/linux-arm64-aws](https://build.golang.org/log/96c746aea647fced879cf434a0f34f36d9707399)
[2020-10-29T16:26:43-25d28ec/android-arm64-corellium](https://build.golang.org/log/ee8ee57187a1936609b1f18a50f5518f07eef5a4)
[2020-10-28T13:25:44-72dec90/linux-arm64-aws](https://build.golang.org/log/9a23a49521629d37ee03c74d05894a27a96b8e9b)
[2020-10-26T21:48:03-80c6b92/linux-arm64-aws](https://build.golang.org/log/1fcf7c32f32ce8b40570c9b12e9dd92df6300537)
[2020-10-26T21:47:54-d39a89f/linux-arm64-aws](https://build.golang.org/log/55cfa218347fa14beb9747a0fa2f8b497fd288f8)
[2020-10-26T18:10:04-ad863ba/linux-arm64-aws](https://build.golang.org/log/60c8b916ac34846c12d030ed398f2ed957340f2f)
[2020-10-26T17:26:40-d677899/linux-arm64-aws](https://build.golang.org/log/34175c59ea1d11ca67ecab08094267336752ac90)
[2020-10-21T23:40:29-9a49f77/linux-arm64-aws](https://build.golang.org/log/35edac5f327e369d170b37c853f30aaac9d796de)
[2020-10-21T00:22:37-cfb087c/linux-arm64-aws](https://build.golang.org/log/ee1b7c47bf667c521053a93eded0d44fdf96caa1)
[2020-10-20T02:32:42-7bb721b/linux-arm64-aws](https://build.golang.org/log/511a2cffe1a5405618f309ad687551263a7ed545)

**Comment by bcmills** [comment]
Now that #45064 is addressed this builder runs as a TryBot, and the test has started flaking in TryBot runs:
https://storage.googleapis.com/go-build-log/39ad506d/linux-arm64-aws_5dc1efb9.log

**Comment by bcmills** [comment]
[2021-05-07T03:55:29-f5423ea/linux-arm64-aws](https://build.golang.org/log/1d1c8aedce83a71c8f27681ab71c544afad99b95)
[2021-04-23T21:48:41-a6d3dc4/linux-arm64-aws](https://build.golang.org/log/158ccee9a33b3f39aac6e236830e672756be39be)

**Comment by bcmills** [comment]
https://storage.googleapis.com/go-build-log/a5065fed/linux-arm64-aws_fe4b1a78.log (a TryBot)

**Comment by bcmills** [comment]
[2021-06-07T21:12:46-909dd5e/linux-arm64-aws](https://build.golang.org/log/f91838a6c1a2fcc8c54a4d425b878459af13b71b)

**Comment by bcmills** [comment]
https://storage.googleapis.com/go-build-log/82562e9f/linux-arm64-aws_2cdea579.log (a TryBot on `release-branch.go1.16`)

**Comment by bcmills** [comment]
https://storage.googleapis.com/go-build-log/50416916/linux-arm64-aws_46a4baa6.log (a TryBot on the main branch)

**Comment by bcmills** [comment]
This was likely a symptom of #45211.
