### ISSUE TITLE
runtime: debugBP = true crashes compiler compilation on Windows

### ISSUE THREAD

**Issue by egonelbre** [golang/go#41995]
Using 8cd75f3da094931c59636b85a87b4f680a208799 (and also 1.15.3) with enabling `debugBP = true` it crashes the compiler compilation on Windows. On Linux, it compiles fine.

Reporting to ensure that this isn't an indication of a bug somewhere.

Here's the line I changed:
https://github.com/golang/go/blob/28e549dec3954b36d0c83442be913d8709d7e5ae/src/runtime/stack.go#L119

Crash:
```
c:\Go.tip\src>make.bat
Building Go cmd/dist using C:\Go\
Building Go toolchain1 using C:\Go\.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
runtime: found invalid top frame pointer
bp=0xc0009d53d8 min=0xc00080e000 max=0xc000810000
fatal error: bad top frame pointer

runtime stack:
runtime.throw(0x85fbcf, 0x15)
        c:/Go.tip/src/runtime/panic.go:1121 +0x79
runtime.adjustctxt(0xc000914780, 0x298dfc28)
        c:/Go.tip/src/runtime/stack.go:727 +0x168
runtime.copystack(0xc000914780, 0x4000)
        c:/Go.tip/src/runtime/stack.go:894 +0x1a8
runtime.newstack()
        c:/Go.tip/src/runtime/stack.go:1078 +0x2b6
runtime.morestack()
        c:/Go.tip/src/runtime/asm_amd64.s:449 +0x97

goroutine 158 [copystack]:
runtime.gcMarkDone()
        c:/Go.tip/src/runtime/mgc.go:1444 +0x32c fp=0xc00080f388 sp=0xc00080f380 pc=0x41d38c
runtime.gcAssistAlloc(0xc000914780)
        c:/Go.tip/src/runtime/mgcmark.go:455 +0x225 fp=0xc00080f3e8 sp=0xc00080f388 pc=0x4201a5
runtime.mallocgc(0x60, 0x80dfa0, 0x1, 0xc000b3e000)
        c:/Go.tip/src/runtime/malloc.go:959 +0xa9c fp=0xc00080f488 sp=0xc00080f3e8 pc=0x40e4bc
runtime.growslice(0x80dfa0, 0xc000b3e000, 0x2, 0x2, 0x3, 0x0, 0x1, 0x2)
        c:/Go.tip/src/runtime/slice.go:230 +0x209 fp=0xc00080f4f0 sp=0xc00080f488 pc=0x44cac9
go/build.(*Context).Import(0xad2e60, 0x856278, 0x1, 0xc0008c60a8, 0x13, 0x0, 0xc000000008, 0xc00040dc78, 0xc000a06d58)
        c:/Go.tip/src/go/build/build.go:917 +0x279c fp=0xc00080fbc8 sp=0xc00080f4f0 pc=0x5a641c
go/build.(*Context).ImportDir(...)
        c:/Go.tip/src/go/build/build.go:458
cmd/go/internal/load.loadPackageData.func2(0xad2560, 0x7df1c0)
        c:/Go.tip/src/cmd/go/internal/load/pkg.go:795 +0x5e5 fp=0xc00080fca8 sp=0xc00080fbc8 pc=0x6d6245
cmd/go/internal/par.(*Cache).Do(0xad2560, 0x7df1c0, 0xc0007e6050, 0xc00040dea8, 0x818fe0, 0xc000668090)
        c:/Go.tip/src/cmd/go/internal/par/work.go:128 +0xff fp=0xc00080fd08 sp=0xc00080fca8 pc=0x5f947f
cmd/go/internal/load.loadPackageData(0xc000332287, 0x5, 0xc00012c091, 0x5, 0xc0003d6060, 0x13, 0xc00000c410, 0x9, 0xc00008c201, 0x1, ...)
        c:/Go.tip/src/cmd/go/internal/load/pkg.go:787 +0x4d7 fp=0xc00080ff20 sp=0xc00080fd08 pc=0x6c4077
cmd/go/internal/load.(*preload).preloadImports.func1(0xc000172000, 0x1, 0xc0007ac5c0, 0xc000332287, 0x5)
        c:/Go.tip/src/cmd/go/internal/load/pkg.go:945 +0xa6 fp=0xc00080ffb8 sp=0xc00080ff20 pc=0x6d6506
runtime.goexit()
        c:/Go.tip/src/runtime/asm_amd64.s:1376 +0x1 fp=0xc00080ffc0 sp=0xc00080ffb8 pc=0x46b4a1
created by cmd/go/internal/load.(*preload).preloadImports
        c:/Go.tip/src/cmd/go/internal/load/pkg.go:944 +0x19e

...
```

**Comment by egonelbre** [comment]
Note, this also happens with latest `go.tip`.

**Comment by egonelbre** [comment]
@zx2c4 maybe you know the answer to the question, whether `debugCheckBP` is intended to work on Windows.

**Comment by networkimprov** [comment]
cc @alexbrainman

**Comment by egonelbre** [comment]
Going over the old bug reports - it seems there's still a crash:

```
runtime: found invalid frame pointer
bp=0xab6a3ff5f8 min=0xc00015e000 max=0xc000160000
fatal error: bad frame pointer

runtime stack:
runtime.throw({0x13c858b?, 0xab6a3ff3a0?})
        C:/Go.tip/src/runtime/panic.go:1108 +0x4d fp=0xab6a3ff320 sp=0xab6a3ff2f0 pc=0xee536d
runtime.adjustframe(0xab6a3ff3e8?, 0xab6a3ff448)
        C:/Go.tip/src/runtime/stack.go:682 +0x2e5 fp=0xab6a3ff3b0 sp=0xab6a3ff320 pc=0xec2aa5
runtime.copystack(0xc0001681c0, 0x800000002?)
        C:/Go.tip/src/runtime/stack.go:935 +0x2e5 fp=0xab6a3ff4a8 sp=0xab6a3ff3b0 pc=0xec3105
runtime.newstack()
        C:/Go.tip/src/runtime/stack.go:1116 +0x485 fp=0xab6a3ff5e0 sp=0xab6a3ff4a8 pc=0xec36e5
runtime.morestack()
        C:/Go.tip/src/runtime/asm_amd64.s:621 +0x79 fp=0xab6a3ff5e8 sp=0xab6a3ff5e0 pc=0xeeb6d9

goroutine 388327 gp=0xc0001681c0 m=14 mp=0xc000101008 [copystack, locked to thread]:
runtime_test.forceStackCopy.func1(0x7c)
        C:/Go.tip/src/runtime/syscall_windows_test.go:691 +0xa5 fp=0xc00003b438 sp=0xc00003b430 pc=0x127fd85
runtime_test.forceStackCopy.func1(0x7d)
        C:/Go.tip/src/runtime/syscall_windows_test.go:697 +0x83 fp=0xc00003b550 sp=0xc00003b438 pc=0x127fd63
runtime_test.forceStackCopy.func1(0x7e)
        C:/Go.tip/src/runtime/syscall_windows_test.go:697 +0x83 fp=0xc00003b668 sp=0xc00003b550 pc=0x127fd63
runtime_test.forceStackCopy.func1(0x7f)
        C:/Go.tip/src/runtime/syscall_windows_test.go:697 +0x83 fp=0xc00003b780 sp=0xc00003b668 pc=0x127fd63
runtime_test.forceStackCopy.func1(0x80)
        C:/Go.tip/src/runtime/syscall_windows_test.go:697 +0x83 fp=0xc00003b898 sp=0xc00003b780 pc=0x127fd63
runtime_test.forceStackCopy()
        C:/Go.tip/src/runtime/syscall_windows_test.go:699 +0x3a fp=0xc00003b8c8 sp=0xc00003b898 pc=0x127fcba
runtime_test.TestReturnAfterStackGrowInCallback.func1(0xffffffffff)
        C:/Go.tip/src/runtime/syscall_windows_test.go:743 +0x14 fp=0xc00003b8d8 sp=0xc00003b8c8 pc=0x128d614
runtime.call16(0x0, 0x13f6df0, 0xc00003b928, 0x0, 0x0, 0x8, 0xc00003bb58)
        C:/Go.tip/src/runtime/asm_amd64.s:775 +0x48 fp=0xc00003b8f8 sp=0xc00003b8d8 pc=0xeebac8
runtime.callbackWrap(0xab6a3ff620)
        C:/Go.tip/src/runtime/syscall_windows.go:396 +0x205 fp=0xc00003bcd0 sp=0xc00003b8f8 pc=0xec9005
runtime.cgocallbackg1(0xec8e00, 0xab6a3ff620, 0x0)
        C:/Go.tip/src/runtime/cgocall.go:444 +0x295 fp=0xc00003bd88 sp=0xc00003bcd0 pc=0xe6e2f5
runtime.cgocallbackg(0xec8e00, 0xab6a3ff620, 0x0)
        C:/Go.tip/src/runtime/cgocall.go:350 +0x167 fp=0xc00003be20 sp=0xc00003bd88 pc=0xe6df47
runtime.cgocallbackg(0xec8e00, 0xab6a3ff620, 0x0)
        <autogenerated>:1 +0x2e fp=0xc00003be48 sp=0xc00003be20 pc=0xef200e
runtime.cgocallback(0xc00015fed8, 0xee1cb2, 0xeeede0)
        C:/Go.tip/src/runtime/asm_amd64.s:1084 +0xec fp=0xc00003be70 sp=0xc00003be48 pc=0xeed36c
runtime.systemstack_switch()
        C:/Go.tip/src/runtime/asm_amd64.s:479 +0x8 fp=0xc00003be80 sp=0xc00003be70 pc=0xeeb5a8
runtime.cgocall(0xeeede0, 0xc000101348)
        C:/Go.tip/src/runtime/cgocall.go:185 +0x72 fp=0xc00003bee8 sp=0xc00003be80 pc=0xee1cb2
runtime.syscall_syscalln(0xc000101008?, 0xc00058b5b0?, {0xc00058b5b0?, 0xee2979?, 0xe6eef7?})
        C:/Go.tip/src/runtime/syscall_windows.go:521 +0x4e fp=0xc00003bf08 sp=0xc00003bee8 pc=0xec910e
syscall.SyscallN(0xc00015ff01?, {0xc00058b5b0?, 0xe7c945?, 0x10?})
        C:/Go.tip/src/runtime/syscall_windows.go:500 +0x1e fp=0xc00003bf40 sp=0xc00003bf08 pc=0xee93fe
syscall.(*Proc).Call(0xc0000f25b0?, {0xc00058b5b0?, 0x0?, 0x0?})
        C:/Go.tip/src/syscall/dll_windows.go:167 +0x1c fp=0xc00003bf80 sp=0xc00003bf40 pc=0xf025dc
runtime_test.TestReturnAfterStackGrowInCallback.func2()
        C:/Go.tip/src/runtime/syscall_windows_test.go:759 +0x6b fp=0xc00003bfe0 sp=0xc00003bf80 pc=0x128042b
runtime.goexit({})
        C:/Go.tip/src/runtime/asm_amd64.s:1700 +0x1 fp=0xc00003bfe8 sp=0xc00003bfe0 pc=0xeed5c1
created by runtime_test.TestReturnAfterStackGrowInCallback in goroutine 388325
        C:/Go.tip/src/runtime/syscall_windows_test.go:758 +0x4c5
```

But, could be just that TestReturnAfterStackGrowInCallback isn't correctly setup for that flag.
