### ISSUE TITLE
x/sys/unix: "out of memory in thread_start" during TestPpoll on linux-386

### ISSUE THREAD

**Issue by bcmills** [golang/go#42209]
<details>

```
runtime/cgo: out of memory in thread_start
SIGABRT: abort
PC=0xf7fb0b19 m=4 sigcode=4294967290

goroutine 0 [idle]:
runtime: unknown pc 0xf7fb0b19
stack: frame={sp:0xe6b18f80, fp:0x0} stack=[0xe6319730,0xe6b19330)
e6b18f00:  00000000  00000000  00000000  00000000 
e6b18f10:  00000000  00000000  00000000  00000000 
e6b18f20:  00000000  00000000  00000000  00000000 
e6b18f30:  00000000  00000000  00000000  00000000 
e6b18f40:  00000000  00000000  00000000  00000000 
e6b18f50:  00000000  00000000  00000000  00000000 
e6b18f60:  00000000  00000000  00000000  00000000 
e6b18f70:  00000000  00000000  00000000  00000000 
e6b18f80: <e6b18f90  00000000  e6b18f90  f7df9df0 
e6b18f90:  00000000  00000000  00000000  00000000 
e6b18fa0:  00000000  00000000  00000000  00000000 
e6b18fb0:  00000000  00000000  00000000  00000000 
e6b18fc0:  00000000  00000000  00000000  00000000 
e6b18fd0:  00000000  00000000  00000000  00000000 
e6b18fe0:  00000000  f7fbb4d0  f7de134c  08219287 
e6b18ff0:  00000000  00000000  00000000  00000000 
runtime: unknown pc 0xf7fb0b19
stack: frame={sp:0xe6b18f80, fp:0x0} stack=[0xe6319730,0xe6b19330)
e6b18f00:  00000000  00000000  00000000  00000000 
e6b18f10:  00000000  00000000  00000000  00000000 
e6b18f20:  00000000  00000000  00000000  00000000 
e6b18f30:  00000000  00000000  00000000  00000000 
e6b18f40:  00000000  00000000  00000000  00000000 
e6b18f50:  00000000  00000000  00000000  00000000 
e6b18f60:  00000000  00000000  00000000  00000000 
e6b18f70:  00000000  00000000  00000000  00000000 
e6b18f80: <e6b18f90  00000000  e6b18f90  f7df9df0 
e6b18f90:  00000000  00000000  00000000  00000000 
e6b18fa0:  00000000  00000000  00000000  00000000 
e6b18fb0:  00000000  00000000  00000000  00000000 
e6b18fc0:  00000000  00000000  00000000  00000000 
e6b18fd0:  00000000  00000000  00000000  00000000 
e6b18fe0:  00000000  f7fbb4d0  f7de134c  08219287 
e6b18ff0:  00000000  00000000  00000000  00000000 

goroutine 1 [runnable]:
testing.(*T).Run(0x9082460, 0x81df38a, 0xb, 0x81eb498, 0x401)
	/workdir/go/src/testing/testing.go:1219 +0x236
testing.runTests.func1(0x90015e0)
	/workdir/go/src/testing/testing.go:1491 +0x5a
testing.tRunner(0x90015e0, 0x9129eec)
	/workdir/go/src/testing/testing.go:1173 +0xb7
testing.runTests(0x900e100, 0x82ec7a0, 0x3a, 0x3a, 0x8ef8d664, 0xbfdd17d3, 0xb2d56a52, 0x8b, 0x82ef0e0, 0x901c48c)
	/workdir/go/src/testing/testing.go:1489 +0x25a
testing.(*M).Run(0x913e000, 0x0)
	/workdir/go/src/testing/testing.go:1397 +0x178
main.main()
	_testmain.go:159 +0x104

goroutine 71 [runnable]:
golang.org/x/sys/unix_test.TestPpoll.func1(0x9194380, 0x9192480)
	/workdir/gopath/src/golang.org/x/sys/unix/syscall_linux_test.go:106 +0x90
created by golang.org/x/sys/unix_test.TestPpoll
	/workdir/gopath/src/golang.org/x/sys/unix/syscall_linux_test.go:105 +0xa5

eax    0x0
ebx    0x2
ecx    0xe6b18f90
edx    0x0
edi    0x0
esi    0x8
ebp    0xe6b18f90
esp    0xe6b18f80
eip    0xf7fb0b19
eflags 0x282
cs     0x23
fs     0x0
gs     0x63
FAIL	golang.org/x/sys/unix	0.117s
```

</details>

[2020-10-22T20:17:47-fb209a7/linux-386-longtest](https://build.golang.org/log/24c19b8476f84ddd0bbde6713d6c2e1d62f5af1e)
[2020-10-18T23:04:17-eeed37f/linux-386-longtest](https://build.golang.org/log/0727c5d9259d6c4f169e6753617d473611295d1b)
[2020-10-17T00:35:18-b09fb70/linux-386](https://build.golang.org/log/3b9cf75b82f359c232d208d02bb0fb8eba6ddb98)
[2020-10-16T16:01:50-f659759/linux-386-longtest](https://build.golang.org/log/44425d088b4027793683ea7b66d88c47fe6f97f1)
[2020-10-14T08:05:44-cc95f25/linux-386-longtest](https://build.golang.org/log/e8b60dd668312ebcecbfd68b870dbe5ba44b266c)
[2020-10-13T13:26:46-2da7054/linux-386-longtest](https://build.golang.org/log/5accf027e7abdde4de31288234c69062ed49cd7d)
[2020-09-30T18:57:26-fdedc70/linux-386](https://build.golang.org/log/f587422b3f5a3e4011e7af83a33207c1e4b5a617)
[2020-09-18T17:44:21-af09f73/linux-386-longtest](https://build.golang.org/log/f166fcf9dcdfd7f6792af5ee728b13f07e86ada9)
[2020-09-09T08:10:42-eff7692/linux-386-longtest](https://build.golang.org/log/685df986a17ae496c7af1ebc2e33854e50e04396)
[2020-09-08T13:41:30-d2e65c1/linux-386-longtest](https://build.golang.org/log/93f63685ef38e10a02714b5aa09319a3e20406c4)
[2020-08-31T18:03:12-196b9ba/linux-386-longtest](https://build.golang.org/log/713617e5d289985d0728d49985388e992319ecc9)
[2020-08-26T17:35:25-f9321e4/linux-386](https://build.golang.org/log/45716b316097c46e07742e60af1bd545ec6022ef)
[2020-08-14T20:00:57-3d37ad5/linux-386-longtest](https://build.golang.org/log/d6ed1abf0024440f1255aafc1a9e1ddf9f7c76a1)
[2020-06-25T21:21:54-ddb9806/linux-386](https://build.golang.org/log/c4437cbcb51bbfaf9c97db3885ad0ac52f592856)
[2020-06-25T21:21:54-ddb9806/linux-386-longtest](https://build.golang.org/log/3920a225ff523efedfe9d7674286f4dcdfa2c03b)
[2020-06-22T21:40:17-ed371f2/linux-386-longtest](https://build.golang.org/log/04654bc56fedd30cdc5a62a2895b2a5c2abcedf7)
[2020-06-15T19:00:26-2780627/linux-386](https://build.golang.org/log/3c4cca00023513f871d04dc62e99d58f3aa84249)
[2020-05-19T10:57:57-fe76b77/linux-386-longtest](https://build.golang.org/log/eb9a0774c70882e502ed609902a444066361ee5c)
[2020-05-01T14:52:40-bc7a7d4/linux-386](https://build.golang.org/log/7083ca3228e2689b565a42213f47377f5ad8afb0)
[2020-03-02T15:01:41-5c8b2ff/linux-386](https://build.golang.org/log/00b4447fad517b03fdfa3c09ac0a24b347099221)

This test was added for #16052, but it's not at all clear to me why the test would fail in this way.

CC @tklauser @kortschak @ianlancetaylor

**Comment by kortschak** [comment]
I've tried to replicate this, but I don't have 386 hardware here and it does not fail on amd64 architecture with GOARCH=386. Sorry.
