### ISSUE TITLE
x/net/html: Parsed HTML cannot be rendered

### ISSUE THREAD

**Issue by empijei** [golang/go#42458]
This bug was found by fuzzing. See master issue #27848

### What version of Go are you using (`go version`)?
1.15

### Does this issue reproduce with the latest release?
Yes

### What did you do?
[Playground](https://play.golang.org/p/DI9kx_Ifx-g)

Code:
```
package main

import (
	"bytes"
	"fmt"
	"io/ioutil"

	"golang.org/x/net/html"
)

const crasher = "<svg><meta>\x00\x0a"

func main(){
FuzzParse([]byte(crasher))
}

// FuzzParse is the Fuzz target to validate that html can be deserialized and re serialized.
func FuzzParse(b []byte) {
	nodes, err := html.ParseFragment(bytes.NewReader(b), nil)
	if err != nil {
		return
	}
	for _, n := range nodes {
		if err := html.Render(ioutil.Discard, n); err != nil {
			fmt.Println(err)
			panic("cannot render parsed HTML")
		}
	}
}
```

### What did you expect to see?
No panic

### What did you see instead?
```
html: void element <meta> has child nodes
panic: cannot render parsed HTML

goroutine 1 [running]:
main.FuzzParse(0xc00002c050, 0xd, 0xd)
	/tmp/sandbox363235051/prog.go:26 +0x1b7
main.main()
	/tmp/sandbox363235051/prog.go:14 +0x68
```

**Comment by kennygrant** [comment]
The content provided inside the meta element doesn't matter, any content will trigger this error. 

e.g.  "<svg><meta>content"

This is invalid html on two counts: svg doesn't allow a meta element AFAIK, and the html meta element is a [void element](https://html.spec.whatwg.org/multipage/syntax.html#void-elements) and should not contain content. So an error seems appropriate, though the html package does make an effort to fix up broken html on parse, and thus trying it without the svg tag does not report an error and silently fixes the html in ParseFragment to reparent the content (so no error reported on render). 

The error seems to be down to the svg context - without that, the content is moved on parse to the parent of the meta tag or the body tag, with the svg, the content is moved to the body along with the meta but is left inside the meta tag (maybe because it is treated as an unknown tag within svg?), which results in the error. So it is left as-is and meta is treated as an html tag (which it is), so produces this error on rendering node:html: void element <meta> has child nodes - from line 178 of [net/html/render.go](https://github.com/golang/net/blob/c7110b5ffcbb/html/render.go#L178).

Here is some example code which prints the tree generated by ParseFragment prior to the error from Render:

https://play.golang.org/p/y9apxrBDuHr

```
Testing: 
<meta>content
<html><meta>content
<html><a><meta>content
<html><h1><meta>content
<svg><meta>content

Output: 
nodes:html (c:head) head (c:meta) meta body (c:content) content 
html:<html><head><meta/></head><body>content</body></html>
nodes:html (c:head) head (c:meta) meta body (c:content) content 
html:<html><head><meta/></head><body>content</body></html>
nodes:html (c:head) head body (c:a) a (c:meta) meta content 
html:<html><head></head><body><a><meta/>content</a></body></html>
nodes:html (c:head) head body (c:h1) h1 (c:meta) meta content 
html:<html><head></head><body><h1><meta/>content</h1></body></html>
nodes:html (c:head) head body (c:svg) svg (c:meta) meta (c:content) content 
error rendering node:html: void element <meta> has child nodes
```

As there is no crash or hang, this is invalid input anyway, and the error on render tells you what is wrong, I'd be inclined to leave this one as-is. It is slightly inconsistent as in an html context the same problem will be silently fixed in ParseFragment.

**Comment by empijei** [comment]
If we decide that this package doesn't have to be able to render every tree that it accepts to parse I agree with you.

I just don't thing that decision has been made (nor the opposite one).
