### ISSUE TITLE
runtime: TestCrashDumpsAllThreads fails on openbsd/mips64

### ISSUE THREAD

**Issue by 4a6f656c** [golang/go#42464]
The `TestCrashDumpsAllThreads` test fails consistently on openbsd/mips64:

```
--- FAIL: TestCrashDumpsAllThreads (3.99s)
    crash_unix_test.go:150: found 0 instances of main.loop; expected 4
    crash_unix_test.go:151: SIGQUIT: quit
        PC=0x85fdc m=5 sigcode=0
        
        goroutine 0 [idle]:
        runtime.thrsleep(0xc000118350, 0x314e58c00, 0x0, 0x0, 0xc000118350, 0x20000000, 0x5e75c, 0x4e00027000000, 0x0, 0xc00011a180, ...)
        	/home/gopher/build/go/src/runtime/sys_openbsd_mips64.s:329 +0x1c fp=0xc000111d20 sp=0xc000111d20 pc=0x85fdc
        runtime.semasleep(0xffffffffffffffff, 0xc00011a180)
        	/home/gopher/build/go/src/runtime/os_openbsd.go:167 +0xe0 fp=0xc000111d80 sp=0xc000111d20 pc=0x479e8
        runtime.notesleep(0xc000118150)
        	/home/gopher/build/go/src/runtime/lock_sema.go:181 +0x128 fp=0xc000111db0 sp=0xc000111d80 pc=0x1b9c0
        runtime.mPark()
        	/home/gopher/build/go/src/runtime/proc.go:1273 +0x28 fp=0xc000111dc8 sp=0xc000111db0 pc=0x51fd8
        runtime.stopm()
        	/home/gopher/build/go/src/runtime/proc.go:2185 +0xbc fp=0xc000111de8 sp=0xc000111dc8 pc=0x53d5c
        runtime.findrunnable(0xc000058000, 0x0)
        	/home/gopher/build/go/src/runtime/proc.go:2844 +0x960 fp=0xc000111f28 sp=0xc000111de8 pc=0x55970
        runtime.schedule()
        	/home/gopher/build/go/src/runtime/proc.go:3051 +0x360 fp=0xc000111f98 sp=0xc000111f28 pc=0x57308
        runtime.park_m(0xc000000180)
        	/home/gopher/build/go/src/runtime/proc.go:3200 +0xa8 fp=0xc000111fc0 sp=0xc000111f98 pc=0x57950
        runtime.mcall(0x0)
        	/home/gopher/build/go/src/runtime/asm_mips64x.s:150 +0x54 fp=0xc000111fd0 sp=0xc000111fc0 pc=0x823bc
        
        goroutine 1 [select (no cases)]:
        runtime.gopark(0x0, 0x0, 0xa10000000000000, 0x1)
        	/home/gopher/build/go/src/runtime/proc.go:336 +0x110 fp=0xc0000bce90 sp=0xc0000bce78 pc=0x4ed78
        runtime.block()
        	/home/gopher/build/go/src/runtime/select.go:103 +0x54 fp=0xc0000bceb8 sp=0xc0000bce90 pc=0x62064
        main.main()
        	/home/gopher/build/tmp/go-build438851373/main.go:31 +0x23c fp=0xc0000bcf80 sp=0xc0000bceb8 pc=0xcbb04
        runtime.main()
        	/home/gopher/build/go/src/runtime/proc.go:225 +0x30c fp=0xc0000bcfd8 sp=0xc0000bcf80 pc=0x4e824
        runtime.goexit()
        	/home/gopher/build/go/src/runtime/asm_mips64x.s:631 +0x4 fp=0xc0000bcfd8 sp=0xc0000bcfd8 pc=0x847d4
        
        goroutine 2 [force gc (idle)]:
        runtime.gopark(0xfbe10, 0x195f30, 0x1114000000000000, 0x1)
        	/home/gopher/build/go/src/runtime/proc.go:336 +0x110 fp=0xc000038fb0 sp=0xc000038f98 pc=0x4ed78
        runtime.goparkunlock(...)
        	/home/gopher/build/go/src/runtime/proc.go:342
        runtime.forcegchelper()
        	/home/gopher/build/go/src/runtime/proc.go:276 +0x108 fp=0xc000038fd8 sp=0xc000038fb0 pc=0x4eba8
        runtime.goexit()
        	/home/gopher/build/go/src/runtime/asm_mips64x.s:631 +0x4 fp=0xc000038fd8 sp=0xc000038fd8 pc=0x847d4
        created by runtime.init.5
        	/home/gopher/build/go/src/runtime/proc.go:264 +0x48
        
        goroutine 3 [GC sweep wait]:
        runtime.gopark(0xfbe10, 0x196060, 0xc14000000000000, 0x1)
        	/home/gopher/build/go/src/runtime/proc.go:336 +0x110 fp=0xc0000397a8 sp=0xc000039790 pc=0x4ed78
        runtime.goparkunlock(...)
        	/home/gopher/build/go/src/runtime/proc.go:342
        runtime.bgsweep(0xc00003c000)
        	/home/gopher/build/go/src/runtime/mgcsweep.go:163 +0xe0 fp=0xc0000397d0 sp=0xc0000397a8 pc=0x37260
        runtime.goexit()
        	/home/gopher/build/go/src/runtime/asm_mips64x.s:631 +0x4 fp=0xc0000397d0 sp=0xc0000397d0 pc=0x847d4
        created by runtime.gcenable
        	/home/gopher/build/go/src/runtime/mgc.go:217 +0x74
        
        goroutine 4 [GC scavenge wait]:
        runtime.gopark(0xfbe10, 0x196100, 0xd14000000000000, 0x1)
        	/home/gopher/build/go/src/runtime/proc.go:336 +0x110 fp=0xc000039f78 sp=0xc000039f60 pc=0x4ed78
        runtime.goparkunlock(...)
        	/home/gopher/build/go/src/runtime/proc.go:342
        runtime.bgscavenge(0xc00003c000)
        	/home/gopher/build/go/src/runtime/mgcscavenge.go:265 +0x12c fp=0xc000039fd0 sp=0xc000039f78 pc=0x34d4c
        runtime.goexit()
        	/home/gopher/build/go/src/runtime/asm_mips64x.s:631 +0x4 fp=0xc000039fd0 sp=0xc000039fd0 pc=0x847d4
        created by runtime.gcenable
        	/home/gopher/build/go/src/runtime/mgc.go:218 +0x9c
        
        goroutine 5 [finalizer wait]:
        runtime.gopark(0xfbe10, 0x1c1360, 0x1014000000000000, 0x1)
        	/home/gopher/build/go/src/runtime/proc.go:336 +0x110 fp=0xc000038750 sp=0xc000038738 pc=0x4ed78
        runtime.goparkunlock(...)
        	/home/gopher/build/go/src/runtime/proc.go:342
        runtime.runfinq()
        	/home/gopher/build/go/src/runtime/mfinal.go:175 +0xf0 fp=0xc0000387d8 sp=0xc000038750 pc=0x29d68
        runtime.goexit()
        	/home/gopher/build/go/src/runtime/asm_mips64x.s:631 +0x4 fp=0xc0000387d8 sp=0xc0000387d8 pc=0x847d4
        created by runtime.createfing
        	/home/gopher/build/go/src/runtime/mfinal.go:156 +0xb0
        
        goroutine 6 [running]:
        	goroutine running on other thread; stack unavailable
        created by main.main
        	/home/gopher/build/tmp/go-build438851373/main.go:17 +0xbc
        
        goroutine 7 [running]:
        	goroutine running on other thread; stack unavailable
        created by main.main
        	/home/gopher/build/tmp/go-build438851373/main.go:17 +0xbc
        
        goroutine 8 [running]:
        	goroutine running on other thread; stack unavailable
        created by main.main
        	/home/gopher/build/tmp/go-build438851373/main.go:17 +0xbc
        
        goroutine 9 [running]:
        	goroutine running on other thread; stack unavailable
        created by main.main
        	/home/gopher/build/tmp/go-build438851373/main.go:17 +0xbc
        
        r0   0x0	r1   0x0
        r2   0x58	r3   0xc000118350
        r4   0xc000118350	r5   0x3
        r6   0x0	r7   0x0
        r8   0xc000118350	r9   0x0
        r10  0x0	r11  0x10
        r12  0x1	r13  0x1
        r14  0x0	r15  0x1
        r16  0x0	r17  0x1
        r18  0x1	r19  0x0
        r20  0x4adbb40a8	r21  0xc000192000
        r22  0x0	r23  0x0
        r24  0x0	r25  0x0
        r26  0x0	r27  0x0
        r28  0x0	r29  0xc000111d20
        r30  0xc00011a180	r31  0x479e8
        pc   0x85fdc	link 0x479e8
        lo   0x0	hi   0x3
        
        -----
```

I plan on disabling this test so we can resolve the remaining issues for this port - this issue is to track investigation of the cause and eventual re-enabling of the test.

**Comment by mengzhuo** [comment]
Another one.
https://build.golang.org/log/6e8e622f180dcd1dcbd00747d987147fb909aeba

```
# cmd/link/internal/loadxcoff
SIGQUIT: quit
PC=0x9680c m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex()
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/sys_linux_mips64x.s:458 +0x1c
runtime.futexsleep(0x1199c18, 0x0, 0xffffffffffffffff)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/os_linux.go:44 +0x40
runtime.notesleep(0x1199c18)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/lock_futex.go:160 +0xd0
runtime.mPark()
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/proc.go:1441 +0x28
runtime.stopm()
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/proc.go:2406 +0xbc
runtime.findrunnable()
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/proc.go:2982 +0xd18
runtime.schedule()
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/proc.go:3355 +0x334
runtime.park_m(0xc000500ea0)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/proc.go:3504 +0x1c4
runtime.mcall()
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/asm_mips64x.s:143 +0x50

goroutine 1 [semacquire, 261 minutes]:
sync.runtime_Semacquire(0xc00052b784)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/sema.go:56 +0x4c
sync.(*WaitGroup).Wait(0xc00052b784)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/sync/waitgroup.go:130 +0xc0
cmd/compile/internal/gc.compileFunctions()
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/gc/compile.go:153 +0x2d8
cmd/compile/internal/gc.Main(0xb3e8a0)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/gc/main.go:287 +0x1704
main.main()
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/main.go:55 +0x1a0

goroutine 8 [semacquire]:
cmd/compile/internal/ssa.zcse(0xc000083a00)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/ssa/zcse.go:23 +0x604
cmd/compile/internal/ssa.Compile(0xc000083a00)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/ssa/compile.go:96 +0xc6c
cmd/compile/internal/ssagen.buildssa(0xc000138420, 0x1)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/ssagen/ssa.go:642 +0x1ae4
cmd/compile/internal/ssagen.Compile(0xc000138420, 0x1)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/ssagen/pgen.go:165 +0x54
cmd/compile/internal/gc.compileFunctions.func2.1(0xc000166480, 0xc000138420, 0xc00000f960, 0xc00052b784)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/gc/compile.go:136 +0x64
created by cmd/compile/internal/gc.compileFunctions.func2
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/gc/compile.go:134 +0x98

goroutine 10 [semacquire]:
cmd/compile/internal/ssa.(*Func).newValue(0xc0000011e0, 0x985, 0xc00037e380, 0xc0007b6c30, {0x0, 0x0})
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/ssa/func.go:219 +0x260
cmd/compile/internal/ssa.(*Block).NewValue0(0xc0007b6c30, {0x0, 0x0}, 0x985, 0xc00037e380)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/ssa/func.go:375 +0x64
cmd/compile/internal/ssa.rewriteValuegeneric_OpConstString(0xc0007877e0)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/ssa/rewritegeneric.go:3765 +0x588
cmd/compile/internal/ssa.rewriteValuegeneric(0xc0007877e0)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/ssa/rewritegeneric.go:50 +0x21f0
cmd/compile/internal/ssa.applyRewrite(0xc0000011e0, 0xb3ebd8, 0xb3ec50, 0x1)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/ssa/rewrite.go:129 +0xd3c
cmd/compile/internal/ssa.opt(0xc0000011e0)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/ssa/opt.go:9 +0x64
cmd/compile/internal/ssa.Compile(0xc0000011e0)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/ssa/compile.go:96 +0xc6c
cmd/compile/internal/ssagen.buildssa(0xc0001386e0, 0x0)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/ssagen/ssa.go:642 +0x1ae4
cmd/compile/internal/ssagen.Compile(0xc0001386e0, 0x0)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/ssagen/pgen.go:165 +0x54
cmd/compile/internal/gc.compileFunctions.func2.1(0xc000166480, 0xc0001386e0, 0xc00000f960, 0xc00052b784)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/gc/compile.go:136 +0x64
created by cmd/compile/internal/gc.compileFunctions.func2
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/gc/compile.go:134 +0x98

goroutine 14 [semacquire]:
cmd/internal/obj.Addrel(...)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/internal/obj/data.go:205
cmd/internal/obj.(*LSym).writeAddr(0xc0008b8800, 0xc000174400, 0x4e, 0x4, 0xc00058d280, 0x0, 0x1)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/internal/obj/data.go:121 +0x270
cmd/internal/obj.(*LSym).WriteAddr(...)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/internal/obj/data.go:135
cmd/internal/obj.dwCtxt.AddDWARFAddrSectionOffset({0xc000174400}, {0xc6c9c0, 0xc0008b8800}, {0xafc720, 0xc00058d280}, 0x0)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/internal/obj/dwarf.go:256 +0xc0
cmd/internal/dwarf.putattr({0xc80e20, 0xc000174400}, {0xc6c9c0, 0xc0008b8800}, 0x10, 0x10, 0x6, 0x0, {0xafc720, 0xc00058d280})
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/internal/dwarf/dwarf.go:996 +0x908
cmd/internal/dwarf.putvar({0xc80e20, 0xc000174400}, 0xc000939cd0, 0xc0009851f0, {0xc6c9c0, 0x0}, 0x3, 0xffffffffffffffff, {0xc00052d620, 0x0, ...})
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/internal/dwarf/dwarf.go:1589 +0x314
cmd/internal/dwarf.putscope({0xc80e20, 0xc000174400}, 0xc000939cd0, {0xc0008bf240, 0x1, 0x1}, 0x0, 0x3, {0xc00052d620, 0x0, ...})
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/internal/dwarf/dwarf.go:1427 +0x6c0
cmd/internal/dwarf.putPrunedScopes({0xc80e20, 0xc000174400}, 0xc000939cd0, 0x3)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/internal/dwarf/dwarf.go:1172 +0x130
cmd/internal/dwarf.PutDefaultFunc({0xc80e20, 0xc000174400}, 0xc000939cd0)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/internal/dwarf/dwarf.go:1399 +0x48c
cmd/internal/obj.(*Link).populateDWARF(0xc000174400, {0xaff6e0, 0xc000720580}, 0xc000724280, {0xfffbd1b874, 0x1b})
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/internal/obj/dwarf.go:383 +0x49c
cmd/internal/obj.Flushplist(0xc000174400, 0xc000939f50, 0xc0009823d0, {0xfffbd1b874, 0x1b})
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/internal/obj/plist.go:140 +0x65c
cmd/compile/internal/objw.(*Progs).Flush(...)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/objw/prog.go:124
cmd/compile/internal/ssagen.Compile(0xc000720580, 0x3)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/ssagen/pgen.go:190 +0x67c
cmd/compile/internal/gc.compileFunctions.func2.1(0xc000166480, 0xc000720580, 0xc00000f960, 0xc00052b784)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/gc/compile.go:136 +0x64
created by cmd/compile/internal/gc.compileFunctions.func2
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/gc/compile.go:134 +0x98

goroutine 49 [semacquire]:
cmd/compile/internal/ssa.schedule(0xc00037a1a0)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/ssa/schedule.go:112 +0x154
cmd/compile/internal/ssa.Compile(0xc00037a1a0)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/ssa/compile.go:96 +0xc6c
cmd/compile/internal/ssagen.buildssa(0xc0007209a0, 0x2)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/ssagen/ssa.go:642 +0x1ae4
cmd/compile/internal/ssagen.Compile(0xc0007209a0, 0x2)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/ssagen/pgen.go:165 +0x54
cmd/compile/internal/gc.compileFunctions.func2.1(0xc000166480, 0xc0007209a0, 0xc00000f960, 0xc00052b784)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/gc/compile.go:136 +0x64
created by cmd/compile/internal/gc.compileFunctions.func2
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/gc/compile.go:134 +0x98

goroutine 50 [chan receive]:
cmd/compile/internal/gc.compileFunctions.func2.1(0xc000166480, 0xc000720b00, 0xc00000f960, 0xc00052b784)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/gc/compile.go:135 +0x48
created by cmd/compile/internal/gc.compileFunctions.func2
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/gc/compile.go:134 +0x98

goroutine 52 [chan receive]:
cmd/compile/internal/gc.compileFunctions.func2.1(0xc000166480, 0xc000720dc0, 0xc00000f960, 0xc00052b784)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/gc/compile.go:135 +0x48
created by cmd/compile/internal/gc.compileFunctions.func2
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/gc/compile.go:134 +0x98

goroutine 53 [chan receive]:
cmd/compile/internal/gc.compileFunctions.func2.1(0xc000166480, 0xc000720f20, 0xc00000f960, 0xc00052b784)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/gc/compile.go:135 +0x48
created by cmd/compile/internal/gc.compileFunctions.func2
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/gc/compile.go:134 +0x98

goroutine 54 [chan receive]:
cmd/compile/internal/gc.compileFunctions.func2.1(0xc000166480, 0xc000721080, 0xc00000f960, 0xc00052b784)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/gc/compile.go:135 +0x48
created by cmd/compile/internal/gc.compileFunctions.func2
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/gc/compile.go:134 +0x98

goroutine 55 [chan receive]:
cmd/compile/internal/gc.compileFunctions.func2.1(0xc000166480, 0xc0007211e0, 0xc00000f960, 0xc00052b784)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/gc/compile.go:135 +0x48
created by cmd/compile/internal/gc.compileFunctions.func2
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/gc/compile.go:134 +0x98

goroutine 56 [chan receive]:
cmd/compile/internal/gc.compileFunctions.func2.1(0xc000166480, 0xc000721340, 0xc00000f960, 0xc00052b784)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/gc/compile.go:135 +0x48
created by cmd/compile/internal/gc.compileFunctions.func2
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/gc/compile.go:134 +0x98

goroutine 57 [chan receive]:
cmd/compile/internal/gc.compileFunctions.func2.1(0xc000166480, 0xc0007214a0, 0xc00000f960, 0xc00052b784)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/gc/compile.go:135 +0x48
created by cmd/compile/internal/gc.compileFunctions.func2
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/gc/compile.go:134 +0x98

goroutine 58 [chan receive]:
cmd/compile/internal/gc.compileFunctions.func2.1(0xc000166480, 0xc000721600, 0xc00000f960, 0xc00052b784)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/gc/compile.go:135 +0x48
created by cmd/compile/internal/gc.compileFunctions.func2
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/gc/compile.go:134 +0x98

goroutine 59 [chan receive]:
cmd/compile/internal/gc.compileFunctions.func2.1(0xc000166480, 0xc000721760, 0xc00000f960, 0xc00052b784)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/gc/compile.go:135 +0x48
created by cmd/compile/internal/gc.compileFunctions.func2
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/gc/compile.go:134 +0x98

goroutine 60 [chan receive]:
cmd/compile/internal/gc.compileFunctions.func2.1(0xc000166480, 0xc0007218c0, 0xc00000f960, 0xc00052b784)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/gc/compile.go:135 +0x48
created by cmd/compile/internal/gc.compileFunctions.func2
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/gc/compile.go:134 +0x98

goroutine 61 [chan receive]:
cmd/compile/internal/gc.compileFunctions.func2.1(0xc000166480, 0xc000721a20, 0xc00000f960, 0xc00052b784)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/gc/compile.go:135 +0x48
created by cmd/compile/internal/gc.compileFunctions.func2
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/cmd/compile/internal/gc/compile.go:134 +0x98

r0   0x0	r1   0xc0007b9230
r2   0x144a	r3   0x11992a0
r4   0x1199c18	r5   0x80
r6   0x0	r7   0x0
r8   0x0	r9   0x0
r10  0xc000039ed0	r11  0x1
r12  0x0	r13  0xc0007bd208
r14  0x1	r15  0x1
r16  0xfffbd196d0	r17  0x1199ac0
r18  0x0	r19  0x1
r20  0x1199d50	r21  0x0
r22  0xb3fbc8	r23  0x1110000
r24  0x117c9302a54798	r25  0xdb28a5d49ab09
r26  0x0	r27  0x0
r28  0x0	r29  0xfffbd19520
r30  0x11992a0	r31  0x4fd40
pc   0x9680c	link 0x4fd40
lo   0x0	hi   0x1
go tool dist: FAILED: /tmp/workdir-host-linux-mipsle-mengzhuo/go/pkg/tool/linux_mips64le/go_bootstrap install -gcflags=all= -ldflags=all= -a -i cmd/asm cmd/cgo cmd/compile cmd/link: exit status 2
```
