### ISSUE TITLE
fmt: printing a map with unsafe.Pointer keys crashes

### ISSUE THREAD

**Issue by hanlins** [golang/go#42622]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.14
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
`darwin/amd64`, should be consistent for all platforms.
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

This is the code for reproduce:
```golang
package main

import (
	"fmt"
	"reflect"
)

func main() {
	str1 := "str1"
	str2 := "str2"
	m := map[reflect.Value]struct{}{}
	m[reflect.ValueOf(&str1)] = struct{}{}
	fmt.Printf("#1: map: %+v\n", m)
	m[reflect.ValueOf(&str2)] = struct{}{}
	// panic here
	fmt.Printf("#2: map: %+v\n", m)
}

```

Here's the output:
```
➜  node go run main.go
#1: map: map[<*string Value>:{}]
panic: bad type in compare: unsafe.Pointer

goroutine 1 [running]:
internal/fmtsort.compare(0x10acf20, 0xc00000c148, 0xba, 0x10acf20, 0xc00000c128, 0xba, 0xba)
	/Users/hanlins/.gvm/gos/go1.14/src/internal/fmtsort/sort.go:181 +0x13b6
internal/fmtsort.compare(0x10cdb00, 0xc00000c140, 0x99, 0x10cdb00, 0xc00000c120, 0x99, 0xc000062240)
	/Users/hanlins/.gvm/gos/go1.14/src/internal/fmtsort/sort.go:158 +0xea8
internal/fmtsort.(*SortedMap).Less(0xc000062240, 0x1, 0x0, 0x20)
	/Users/hanlins/.gvm/gos/go1.14/src/internal/fmtsort/sort.go:27 +0x87
sort.insertionSort(0x10eca40, 0xc000062240, 0x0, 0x2)
	/Users/hanlins/.gvm/gos/go1.14/src/sort/sort.go:27 +0xc4
sort.stable(0x10eca40, 0xc000062240, 0x2)
	/Users/hanlins/.gvm/gos/go1.14/src/sort/sort.go:368 +0x86
sort.Stable(0x10eca40, 0xc000062240)
	/Users/hanlins/.gvm/gos/go1.14/src/sort/sort.go:357 +0x53
internal/fmtsort.Sort(0x10b3ea0, 0xc000062180, 0x15, 0x99)
	/Users/hanlins/.gvm/gos/go1.14/src/internal/fmtsort/sort.go:71 +0x434
fmt.(*pp).printValue(0xc000064ea0, 0x10b3ea0, 0xc000062180, 0x15, 0x76, 0x0)
	/Users/hanlins/.gvm/gos/go1.14/src/fmt/print.go:773 +0xcd4
fmt.(*pp).printArg(0xc000064ea0, 0x10b3ea0, 0xc000062180, 0x76)
	/Users/hanlins/.gvm/gos/go1.14/src/fmt/print.go:716 +0x292
fmt.(*pp).doPrintf(0xc000064ea0, 0x10cf10c, 0x9, 0xc00006cf40, 0x1, 0x1)
	/Users/hanlins/.gvm/gos/go1.14/src/fmt/print.go:1030 +0x15a
fmt.Fprintf(0x10ec360, 0xc00000e018, 0x10cf10c, 0x9, 0xc00006cf40, 0x1, 0x1, 0x1d, 0x0, 0x0)
	/Users/hanlins/.gvm/gos/go1.14/src/fmt/print.go:204 +0x72
fmt.Printf(...)
	/Users/hanlins/.gvm/gos/go1.14/src/fmt/print.go:213
main.main()
	/Users/hanlins/test/node/main.go:16 +0x2dc
exit status 2
```

### What did you expect to see?
The behavior for storing values of same type (e.g. `reflect.Value`) should be consistent. Either it should reject storing `reflect.Value` during compilation (since it contains `unsafe.Pointer` that is non-comparable), or it should be able to correctly handle `reflect.Value` as key.

### What did you see instead?
If multiple `reflect.Value` of same type being stored, it will panic when iterating the map keys (e.g. print the map). It would be nice to make `unsafe.Pointer` comparable just like `uintptr` to mitigate the issue.

Similar to https://github.com/golang/go/issues/33610

**Comment by ianlancetaylor** [comment]
Thanks.  Simpler test case that also crashes at runtime:

```Go
package main

import (
	"fmt"
	"unsafe"
)

var v1, v2 int

func main() {
	m := make(map[unsafe.Pointer]bool)
	m[unsafe.Pointer(&v1)] = true
	m[unsafe.Pointer(&v2)] = true
	fmt.Println(m)
	
}
```
