### ISSUE TITLE
time: test timeout in TestAfterFunc on linux-s390x-ibm builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#43067]
[2020-12-08T01:46:45-9c91cab/linux-s390x-ibm](https://build.golang.org/log/be12aab3e9f6b31097a8836a8d920dd5438b7283)

```
panic: test timed out after 3m0s

goroutine 39 [running]:
testing.(*M).startAlarm.func1()
	/data/golang/workdir/go/src/testing/testing.go:1702 +0xda
created by time.goFunc
	/data/golang/workdir/go/src/time/sleep.go:169 +0x42

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000082300, 0x1ed080, 0xd, 0x264e18, 0x1000000000f426a)
	/data/golang/workdir/go/src/testing/testing.go:1241 +0x2b6
testing.runTests.func1(0xc000001200)
	/data/golang/workdir/go/src/testing/testing.go:1513 +0x7e
testing.tRunner(0xc000001200, 0xc000051dd0)
	/data/golang/workdir/go/src/testing/testing.go:1195 +0xd8
testing.runTests(0xc00000c510, 0x392a20, 0x6d, 0x6d, 0xbfebd562060a492f, 0x29e8e0786a, 0x396180, 0x28dbd6)
	/data/golang/workdir/go/src/testing/testing.go:1511 +0x2e6
testing.(*M).Run(0xc000140000, 0x0)
	/data/golang/workdir/go/src/testing/testing.go:1419 +0x1d8
main.main()
	_testmain.go:373 +0x142

goroutine 30 [chan receive]:
testing.(*T).Parallel(0xc000149980)
	/data/golang/workdir/go/src/testing/testing.go:1061 +0x104
time_test.TestParseYday(0xc000149980)
	/data/golang/workdir/go/src/time/format_test.go:762 +0x30
testing.tRunner(0xc000149980, 0x2650b8)
	/data/golang/workdir/go/src/testing/testing.go:1195 +0xd8
created by testing.(*T).Run
	/data/golang/workdir/go/src/testing/testing.go:1240 +0x296

goroutine 49 [chan receive]:
time_test.TestAfterFunc(0xc000082300)
	/data/golang/workdir/go/src/time/sleep_test.go:62 +0x108
testing.tRunner(0xc000082300, 0x264e18)
	/data/golang/workdir/go/src/testing/testing.go:1195 +0xd8
created by testing.(*T).Run
	/data/golang/workdir/go/src/testing/testing.go:1240 +0x296
FAIL	time	180.003s
```

This is the only one of these failures I've seen, so I'm not sure whether it's just a slow builder (CC @ruixin-bao @rajaskakodkar), another runtime timer bug (CC @prattmic @ianlancetaylor), or perhaps some other recently-added slow test pushing the running time over the limit.

**Comment by jonathan-albrecht-ibm** [comment]
@bcmills, I had a look at the linux-s390x-ibm builders this morning. 
There are two hosts and on each of them I checked out and built the latest go master (commit e508c1c67b02dceea146ce3472c0f8ce9e60632c).
I ran the 'time' tests with `go test -count=10 time` 3 times (30 runs total) on each host and got 6.3s/run consistently.

I don't think it looks like a slow builder but let me know if I'm missing something or if I can try anything else. I'm new so any pointers are appreciated.

**Comment by prattmic** [comment]
A timeout in time test is quite similar to #42515, so it could be another timer bug, though probably not the exact same one, as that one seems to be netbsd-specific.
