### ISSUE TITLE
x/tools/gopls: crash in commonDir with filepath case differences

### ISSUE THREAD

**Issue by samj7792** [golang/go#43520]
gopls version: v0.6.1
gopls flags: 
extension version: 0.20.1
environment: Visual Studio Code

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>
Saving file causes glitched imports. To be honest I'm not totally sure.

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>
[Info  - 9:06:24 AM] 2020/12/31 09:06:24 go/packages.Load
	snapshot=0
	directory=/Users/samueljackson/Documents/Code/SJ/redux
	query=[builtin github.com/t1cg/SJ/redux/...]
	packages=11

[Error - 9:06:24 AM] 2020/12/31 09:06:24 creating workspace dir: mkdir /var/folders/vg/4t5qpjw57jx1rtfbd46t0dxw0000gn/T/gopls-3749.workspace: file exists

[Error - 9:06:24 AM] 2020/12/31 09:06:24 unable to compute error positions: no parsed file for file:///Users/samueljackson/Documents/Code/SJ/redux/api/customfunctions/post_login.go in github.com/t1cg/SJ/redux/api/customfunctions
	package="github.com/t1cg/SJ/redux/api/customfunctions"

golist_overlay.go:451: commonDir saw map[/Users/samueljackson/Documents/Code/SJ/redux/api/customFunctions:true /Users/samueljackson/Documents/Code/SJ/redux/api/customfunctions:true] for [/Users/samueljackson/Documents/Code/SJ/redux/api/customfunctions/get_record.go /Users/samueljackson/Documents/Code/SJ/redux/api/customfunctions/get_records.go /Users/samueljackson/Documents/Code/SJ/redux/api/customfunctions/post_register.go /Users/samueljackson/Documents/Code/SJ/redux/api/customFunctions/post_login.go]
[Error - 9:06:24 AM] Connection to server got closed. Server will not be restarted.
[Error - 9:06:24 AM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:94609:27)
	at Object.dispose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:10537:35)
	at LanguageClient.handleConnectionClosed (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:12816:42)
	at LanguageClient.handleConnectionClosed (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:67230:15)
	at closeHandler (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:12803:18)
	at CallbackList.invoke (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22491:39)
	at Emitter.fire (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22553:36)
	at closeHandler (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93821:26)
	at CallbackList.invoke (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22491:39)
	at Emitter.fire (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22553:36)
	at StreamMessageReader.fireClose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93208:27)
	at Socket.<anonymous> (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93293:42)
	at Socket.emit (events.js:228:7)
	at Pipe.<anonymous> (net.js:664:12)
[Error - 9:06:24 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:94609:27)
	at Object.dispose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:10537:35)
	at LanguageClient.handleConnectionClosed (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:12816:42)
	at LanguageClient.handleConnectionClosed (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:67230:15)
	at closeHandler (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:12803:18)
	at CallbackList.invoke (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22491:39)
	at Emitter.fire (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22553:36)
	at closeHandler (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93821:26)
	at CallbackList.invoke (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22491:39)
	at Emitter.fire (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22553:36)
	at StreamMessageReader.fireClose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93208:27)
	at Socket.<anonymous> (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93293:42)
	at Socket.emit (events.js:228:7)
	at Pipe.<anonymous> (net.js:664:12)
[Error - 9:06:24 AM] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:94609:27)
	at Object.dispose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:10537:35)
	at LanguageClient.handleConnectionClosed (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:12816:42)
	at LanguageClient.handleConnectionClosed (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:67230:15)
	at closeHandler (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:12803:18)
	at CallbackList.invoke (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22491:39)
	at Emitter.fire (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22553:36)
	at closeHandler (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93821:26)
	at CallbackList.invoke (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22491:39)
	at Emitter.fire (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22553:36)
	at StreamMessageReader.fireClose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93208:27)
	at Socket.<anonymous> (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93293:42)
	at Socket.emit (events.js:228:7)
	at Pipe.<anonymous> (net.js:664:12)
[Error - 9:06:24 AM] Request textDocument/foldingRange failed.
Error: Connection got disposed.
	at Object.dispose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:94609:27)
	at Object.dispose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:10537:35)
	at LanguageClient.handleConnectionClosed (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:12816:42)
	at LanguageClient.handleConnectionClosed (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:67230:15)
	at closeHandler (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:12803:18)
	at CallbackList.invoke (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22491:39)
	at Emitter.fire (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22553:36)
	at closeHandler (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93821:26)
	at CallbackList.invoke (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22491:39)
	at Emitter.fire (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22553:36)
	at StreamMessageReader.fireClose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93208:27)
	at Socket.<anonymous> (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93293:42)
	at Socket.emit (events.js:228:7)
	at Pipe.<anonymous> (net.js:664:12)
[Error - 9:06:24 AM] Request textDocument/codeLens failed.
Error: Connection got disposed.
	at Object.dispose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:94609:27)
	at Object.dispose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:10537:35)
	at LanguageClient.handleConnectionClosed (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:12816:42)
	at LanguageClient.handleConnectionClosed (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:67230:15)
	at closeHandler (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:12803:18)
	at CallbackList.invoke (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22491:39)
	at Emitter.fire (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22553:36)
	at closeHandler (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93821:26)
	at CallbackList.invoke (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22491:39)
	at Emitter.fire (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22553:36)
	at StreamMessageReader.fireClose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93208:27)
	at Socket.<anonymous> (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93293:42)
	at Socket.emit (events.js:228:7)
	at Pipe.<anonymous> (net.js:664:12)
[Error - 9:06:24 AM] Request textDocument/codeLens failed.
Error: Connection got disposed.
	at Object.dispose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:94609:27)
	at Object.dispose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:10537:35)
	at LanguageClient.handleConnectionClosed (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:12816:42)
	at LanguageClient.handleConnectionClosed (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:67230:15)
	at closeHandler (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:12803:18)
	at CallbackList.invoke (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22491:39)
	at Emitter.fire (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22553:36)
	at closeHandler (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93821:26)
	at CallbackList.invoke (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22491:39)
	at Emitter.fire (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22553:36)
	at StreamMessageReader.fireClose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93208:27)
	at Socket.<anonymous> (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93293:42)
	at Socket.emit (events.js:228:7)
	at Pipe.<anonymous> (net.js:664:12)
[Error - 9:06:24 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:94609:27)
	at Object.dispose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:10537:35)
	at LanguageClient.handleConnectionClosed (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:12816:42)
	at LanguageClient.handleConnectionClosed (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:67230:15)
	at closeHandler (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:12803:18)
	at CallbackList.invoke (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22491:39)
	at Emitter.fire (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22553:36)
	at closeHandler (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93821:26)
	at CallbackList.invoke (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22491:39)
	at Emitter.fire (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22553:36)
	at StreamMessageReader.fireClose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93208:27)
	at Socket.<anonymous> (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93293:42)
	at Socket.emit (events.js:228:7)
	at Pipe.<anonymous> (net.js:664:12)

Failed to auto-collect gopls trace: unrecognized crash pattern.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by heschik** [comment]
It would be hard to put this together with a full trace, but without one I think it's too much for me.

We expect the go command and the editor to send us canonical cased file names. There is one known exception described in https://github.com/golang/go/issues/36904#issuecomment-601412780, but we check for that explicitly and anyway it seems unlikely VS Code was opened to the `customFunctions` directory. I would tend to blame VS Code, but without a trace I can't prove it.

I don't think a fix to `go/packages` is appropriate, since it's getting bad input. Changing the panic to an error should be an improvement -- if nothing else, saving all the files should avoid the problem, so it's transient by definition. We could do the `checkPathCase` call more often, but I think I'd rather wait until we have a better understanding of the problem.

I'll change the panic to an error unless someone objects.
