### ISSUE TITLE
runtime: hang in TestGdbAutotmpTypes on linux-mips64le-mengzhuo builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#43825]
[2021-01-15T20:37:59-ec94701/linux-mips64le-mengzhuo](https://build.golang.org/log/f337fafab7c36e82748cd9490ab33af719f89968)
[2020-11-07T16:59:55-5e371e0/linux-mips64le-mengzhuo](https://build.golang.org/log/2508b5b3b5607246fcdce956af6789eb908d099e)
[2020-11-03T00:50:57-ebc1b8e/linux-mips64le-mengzhuo](https://build.golang.org/log/2d37b61d9746e2772f40e594dc779e047baa01d9)
[2020-09-23T03:14:03-83bc1ed/linux-mips64le-mengzhuo](https://build.golang.org/log/9e36d24b97d8b4536d658c7693dca8cc0dcd309c)

```
goroutine 23895 [syscall, 11 minutes]:
syscall.Syscall6(0x1475, 0x1, 0x4c33, 0xc0013839c8, 0x1000004, 0x0, 0x0, 0x0, 0x1200554c4, 0x120163fd8)
	/tmp/farm/go/src/syscall/asm_linux_mips64x.s:40 +0x10 fp=0xc001383970 sp=0xc001383968 pc=0x1200a6a78
os.(*Process).blockUntilWaitable(0xc00014a4e0, 0x0, 0x1, 0xc00045a300)
	/tmp/farm/go/src/os/wait_waitid.go:32 +0x88 fp=0xc001383a58 sp=0xc001383970 pc=0x1200c9058
os.(*Process).wait(0xc00014a4e0, 0x30, 0x1202d3ee0, 0x1202d3ee8)
	/tmp/farm/go/src/os/exec_unix.go:22 +0x4c fp=0xc001383ac8 sp=0xc001383a58 pc=0x1200c2324
os.(*Process).Wait(...)
	/tmp/farm/go/src/os/exec.go:129
os/exec.(*Cmd).Wait(0xc000670420, 0x0, 0x0)
	/tmp/farm/go/src/os/exec/exec.go:507 +0x68 fp=0xc001383b40 sp=0xc001383ac8 pc=0x120164568
os/exec.(*Cmd).Run(0xc000670420, 0xc00006eb10, 0xc000670420)
	/tmp/farm/go/src/os/exec/exec.go:341 +0x78 fp=0xc001383b60 sp=0xc001383b40 pc=0x120163b58
os/exec.(*Cmd).CombinedOutput(0xc000670420, 0x3, 0xc001383e78, 0xf, 0xf, 0xc000670420)
	/tmp/farm/go/src/os/exec/exec.go:567 +0xbc fp=0xc001383b88 sp=0xc001383b60 pc=0x120164944
runtime_test.TestGdbAutotmpTypes(0xc0003d1800)
	/tmp/farm/go/src/runtime/runtime-gdb_test.go:513 +0x6d4 fp=0xc001383f80 sp=0xc001383b88 pc=0x1202098ec
testing.tRunner(0xc0003d1800, 0x1202d56e8)
	/tmp/farm/go/src/testing/testing.go:1194 +0xf8 fp=0xc001383fc8 sp=0xc001383f80 pc=0x12011b5c8
runtime.goexit()
	/tmp/farm/go/src/runtime/asm_mips64x.s:631 +0x4 fp=0xc001383fc8 sp=0xc001383fc8 pc=0x1200905bc
created by testing.(*T).Run
	/tmp/farm/go/src/testing/testing.go:1239 +0x2dc
```

CC @mengzhuo; see previously #37366, #39204

**Comment by mengzhuo** [comment]
linux-mips64le-mengzhuo builder has been shutdown and removed from farm.
Issue closed.
