### ISSUE TITLE
crypto/tls: apparent deadlock in (*Conn).Handshake via TestHostnameInSNI on arm64

### ISSUE THREAD

**Issue by bcmills** [golang/go#43915]
[2021-01-25T22:54:28-e6b6d10/android-arm64-corellium](https://build.golang.org/log/11babc2b56ecfd5ce52846b4412161abc2739b81)
[2020-10-15T18:07:26-3c9488e/linux-arm64-aws](https://build.golang.org/log/d062cba94cb74b7209173593b45fcd1d97ff7113)

<details>

```
panic: test timed out after 3m0s

goroutine 194 [running]:
testing.(*M).startAlarm.func1()
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/testing/testing.go:1701 +0xc0
created by time.goFunc
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/time/sleep.go:180 +0x38

goroutine 1 [chan receive, 2 minutes]:
testing.(*T).Run(0x40000f8780, 0x62e2ddffe4, 0x11, 0x62e31104f8, 0x600f5001)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/testing/testing.go:1240 +0x22c
testing.runTests.func1(0x4000001c80)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/testing/testing.go:1512 +0x6c
testing.tRunner(0x4000001c80, 0x40003fbc48)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/testing/testing.go:1194 +0xc4
testing.runTests(0x400000e4c8, 0x62e32b7580, 0x90, 0x90, 0xbffbf2115111fdbf, 0x29ead26018, 0x62e32bb7c0, 0x0)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/testing/testing.go:1510 +0x27c
testing.(*M).Run(0x40000b8080, 0x0)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/testing/testing.go:1418 +0x19c
crypto/tls.runMain(0x40000b8080, 0x0)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/crypto/tls/handshake_test.go:388 +0x508
crypto/tls.TestMain(0x40000b8080)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/crypto/tls/handshake_test.go:334 +0x74
main.main()
	_testmain.go:339 +0x148

goroutine 6 [IO wait, 2 minutes]:
internal/poll.runtime_pollWait(0x70e714e8e8, 0x72, 0x0)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/netpoll.go:222 +0x3c
internal/poll.(*pollDesc).wait(0x40000b8118, 0x72, 0x0, 0x0, 0x62e2ddc79d)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/internal/poll/fd_poll_runtime.go:87 +0x30
internal/poll.(*pollDesc).waitRead(...)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0x40000b8100, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/internal/poll/fd_unix.go:401 +0x1a4
net.(*netFD).accept(0x40000b8100, 0x37e11d600, 0x0, 0x0)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/net/fd_unix.go:172 +0x24
net.(*TCPListener).accept(0x400000e168, 0x400004dfa8, 0x1, 0x62e304583c)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/net/tcpsock_posix.go:139 +0x24
net.(*TCPListener).Accept(0x400000e168, 0x400004dfa8, 0x4000010138, 0x0, 0x0)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/net/tcpsock.go:261 +0x50
crypto/tls.localServer(0x62e311b940, 0x400000e168)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/crypto/tls/handshake_test.go:248 +0x54
created by crypto/tls.runMain
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/crypto/tls/handshake_test.go:360 +0x204

goroutine 184 [semacquire, 2 minutes]:
internal/poll.runtime_Semacquire(0x4000495128)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/sema.go:61 +0x30
internal/poll.(*FD).Close(0x4000495100, 0x4000495100, 0x0)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/internal/poll/fd_unix.go:115 +0x78
net.(*netFD).Close(0x4000495100, 0x0, 0x0)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/net/fd_posix.go:37 +0x40
net.(*conn).Close(0x4000010130, 0x0, 0x0)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/net/net.go:207 +0x4c
crypto/tls.TestHostnameInSNI(0x40000f8780)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/crypto/tls/handshake_client_test.go:1401 +0x264
testing.tRunner(0x40000f8780, 0x62e31104f8)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/testing/testing.go:1194 +0xc4
created by testing.(*T).Run
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/testing/testing.go:1239 +0x210

goroutine 186 [IO wait, 2 minutes]:
internal/poll.runtime_pollWait(0x70e714e718, 0x72, 0xffffffffffffffff)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/netpoll.go:222 +0x3c
internal/poll.(*pollDesc).wait(0x4000495118, 0x72, 0x200, 0x205, 0xffffffffffffffff)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/internal/poll/fd_poll_runtime.go:87 +0x30
internal/poll.(*pollDesc).waitRead(...)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0x4000495100, 0x4000224000, 0x205, 0x205, 0x0, 0x0, 0x0)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/internal/poll/fd_unix.go:166 +0x178
net.(*netFD).Read(0x4000495100, 0x4000224000, 0x205, 0x205, 0xffffa4d318024b01, 0x62e2e53901, 0xffffffffff853301)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/net/fd_posix.go:55 +0x3c
net.(*conn).Read(0x4000010130, 0x4000224000, 0x205, 0x205, 0x0, 0x0, 0x0)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/net/net.go:183 +0x68
crypto/tls.(*atLeastReader).Read(0x4000204810, 0x4000224000, 0x205, 0x205, 0x400003ec00, 0x62e30009b8, 0x0)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/crypto/tls/conn.go:776 +0x50
bytes.(*Buffer).ReadFrom(0x40000c9e78, 0x62e31176b8, 0x4000204810, 0x62e2ffe22c, 0x62e30c9f00, 0x62e3103060)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/bytes/buffer.go:204 +0x9c
crypto/tls.(*Conn).readFromUntil(0x40000c9c00, 0x62e3117918, 0x4000010130, 0x5, 0x4000010130, 0x0)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/crypto/tls/conn.go:798 +0xc8
crypto/tls.(*Conn).readRecordOrCCS(0x40000c9c00, 0x0, 0x100, 0x100)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/crypto/tls/conn.go:605 +0xd0
crypto/tls.(*Conn).readRecord(...)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/crypto/tls/conn.go:573
crypto/tls.(*Conn).readHandshake(0x40000c9c00, 0x40004c7216, 0x40004c7200, 0x100, 0x180)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/crypto/tls/conn.go:1008 +0x40
crypto/tls.(*Conn).clientHandshake(0x40000c9c00, 0x0, 0x0)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/crypto/tls/handshake_client.go:171 +0x1d0
crypto/tls.(*Conn).Handshake(0x40000c9c00, 0x0, 0x0)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/crypto/tls/conn.go:1391 +0xdc
crypto/tls.TestHostnameInSNI.func1(0x62e311e778, 0x4000010130, 0x62e2ddd2a8, 0x9)
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/crypto/tls/handshake_client_test.go:1387 +0xe0
created by crypto/tls.TestHostnameInSNI
	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/crypto/tls/handshake_client_test.go:1386 +0xe0
FAIL	crypto/tls	180.053s
```

</details>

Possibly a duplicate of #38870; see also #39406. (CC @FiloSottile @katiehockman @rolandshoemaker)

**Comment by bcmills** [comment]
[2021-03-15T23:47:56-661f3f1/linux-arm64-aws](https://build.golang.org/log/e3df3e0ef26a2dd73e286d43a35bc7a0788c0bf1)
[2021-03-05T22:14:48-a829114/linux-arm64-aws](https://build.golang.org/log/ba66e9b20d025d76a0ee1f7b47b1cb671735fc7f)

**Comment by bcmills** [comment]
[2021-05-04T14:38:36-5e4f9b0/linux-arm64-aws](https://build.golang.org/log/e0fde6389205f38ef028676841bcf16865e0e4bd)
[2021-05-03T16:23:09-7b768d4/linux-arm64-aws](https://build.golang.org/log/351135e3bf19ad0131317bcb7edd27c186e3f9c1)
[2021-04-29T17:08:05-e03cca6/linux-arm64-aws](https://build.golang.org/log/7e87313e68e532979b2dc8b4c8b0c303805ff23d)
[2021-04-29T11:37:05-c4c68fb/linux-arm64-aws](https://build.golang.org/log/8150f7f3775a2cf6c3cbd7cc1a2dadcd8d2c9a33)
[2021-04-22T17:47:59-537cde0/linux-arm64-aws](https://build.golang.org/log/2aa838e803876bc1264640d88d8d4ba18fe41303)
[2021-04-16T16:36:57-2f0e5bf/linux-arm64-packet](https://build.golang.org/log/f59cc1a80122cd938a7511dc878e56b0536bcd78)
[2021-04-14T03:15:00-2d4ba26/linux-arm64-packet](https://build.golang.org/log/79854a477d20da1ea7e997415cd68dda0b31e766)
[2021-04-09T18:49:05-c3faff7/linux-arm64-aws](https://build.golang.org/log/7e581b3d818c83188e70806012a2e7d0cbd9bd5d)
[2021-04-09T18:49:05-c3faff7/linux-arm64-packet](https://build.golang.org/log/0d1020188f736412d0e19f2e08125ce288839909)
[2021-04-09T14:33:44-a690a5d/android-arm64-corellium](https://build.golang.org/log/913e7863aff653d35d558a2f19d075bde107dd4e)
[2021-04-08T18:47:17-96a6745/linux-arm64-packet](https://build.golang.org/log/8a1b9ef6dde3d39fc22a9f8ef5aef9cfd2349ca9)

**Comment by bcmills** [comment]
Looks like this only ever occurs on `arm64` builders. That's curious.

**Comment by bcmills** [comment]
This looks like an earlier report of #45211.
