### ISSUE TITLE
x/debug/internal/gocore: TestLT and TestMappings failing on openbsd-amd64 builders

### ISSUE THREAD

**Issue by bcmills** [golang/go#43927]
[2020-12-08T15:29:29-c934e1b/openbsd-amd64-64](https://build.golang.org/log/a400b68ac7d3a58b354054def575d8204a61c6fb)
[2020-12-08T15:29:29-c934e1b/openbsd-amd64-68](https://build.golang.org/log/5c4a405e17102d758521cf62647719ea42f0a5df)

```
--- FAIL: TestMappings (0.01s)
    --- FAIL: TestMappings/useExePath=false (0.01s)
        core_test.go:57: opcode=0xf8, want 0x31
        core_test.go:69: class_to_size[1]=0, want 8
    --- FAIL: TestMappings/useExePath=true (0.00s)
        core_test.go:57: opcode=0xf8, want 0x31
        core_test.go:69: class_to_size[1]=0, want 8
FAIL
FAIL	golang.org/x/debug/internal/core	0.093s
--- FAIL: TestLT (0.07s)
panic: runtime error: makeslice: len out of range [recovered]
	panic: runtime error: makeslice: len out of range

goroutine 6 [running]:
testing.tRunner.func1.2(0x585220, 0x5ea300)
	/tmp/workdir/go/src/testing/testing.go:1144 +0x332
testing.tRunner.func1(0xc000001380)
	/tmp/workdir/go/src/testing/testing.go:1147 +0x4b6
panic(0x585220, 0x5ea300)
	/tmp/workdir/go/src/runtime/panic.go:965 +0x1b9
golang.org/x/debug/internal/gocore.region.String(0xc000088160, 0x4aaa70, 0xc0002f76d0, 0xc, 0xc00046ce50)
	/tmp/workdir/gopath/src/golang.org/x/debug/internal/gocore/region.go:121 +0x96
golang.org/x/debug/internal/gocore.Core(0xc0000b0000, 0xd, 0x5b72e1, 0x8)
	/tmp/workdir/gopath/src/golang.org/x/debug/internal/gocore/process.go:155 +0x299
golang.org/x/debug/internal/gocore.loadExample(0xc000001380, 0x0)
	/tmp/workdir/gopath/src/golang.org/x/debug/internal/gocore/gocore_test.go:40 +0xeb
golang.org/x/debug/internal/gocore.TestLT(0xc000001380)
	/tmp/workdir/gopath/src/golang.org/x/debug/internal/gocore/dominator_test.go:16 +0x45
testing.tRunner(0xc000001380, 0x5c2968)
	/tmp/workdir/go/src/testing/testing.go:1194 +0xef
created by testing.(*T).Run
	/tmp/workdir/go/src/testing/testing.go:1239 +0x2b3
FAIL	golang.org/x/debug/internal/gocore	0.162s
```

Given the timing, I'm inclined to suspect [CL 270380](https://golang.org/cl/270380) in the main Go repo (CC @4a6f656c, @randall77, @ianlancetaylor, @cherrymui).

**Comment by bcmills** [comment]
I think this is a release-blocker for Go 1.16 via #11811 (CC @golang/release).

**Comment by toothrot** [comment]
We may end up not considering it a release-blocker, as openbsd-amd64 is not a [First-Class Port](https://github.com/golang/go/wiki/PortingPolicy#first-class-ports).

**Comment by 4a6f656c** [comment]
I've confirmed that this is due to CL 270380 - I'll have a closer look.
