### ISSUE TITLE
TestScript/list_test_err: sigpanic in runtime.wantAsyncPreempt

### ISSUE THREAD

**Issue by zx2c4** [golang/go#44234]
Here's a flake from windows/386:

```

ok  	cmd/fix	3.489s
go test proxy running at GOPROXY=http://127.0.0.1:51034/mod
--- FAIL: TestScript (0.01s)
    --- FAIL: TestScript/list_test_err (0.48s)
        script_test.go:213: 
            # issue 28491: errors in test source files should not prevent
            # "go list -test" from returning useful information.
            # go list prints information for package, internal test,
            # external test, but not testmain package when there is a
            # syntax error in test sources. (0.245s)
            # go list -e prints information for all test packages.
            # The syntax error is shown in the package error field. (0.208s)
            > go list -e -test -deps -f '{{.ImportPath}} {{.Error | printf "%q"}}' syntaxerr
            [stderr]
            fatal error: unexpected signal during runtime execution
            [signal 0xc0000005 code=0x0 addr=0x65 pc=0x4348c9]
            
            runtime stack:
            runtime.throw(0x93829b, 0x2a)
            	C:/workdir/go/src/runtime/panic.go:1117 +0x64
            runtime.sigpanic()
            	C:/workdir/go/src/runtime/signal_windows.go:234 +0x292
            runtime.wantAsyncPreempt(0x0, 0x110)
            	C:/workdir/go/src/runtime/preempt.go:344 +0x19
            runtime.preemptM(0x12c80000)
            	C:/workdir/go/src/runtime/os_windows.go:1303 +0x223
            runtime.preemptone(0x12c20a00, 0xffffff00)
            	C:/workdir/go/src/runtime/proc.go:5292 +0x7c
            runtime.preemptall(0x12c233a8)
            	C:/workdir/go/src/runtime/proc.go:5254 +0x4d
            runtime.forEachP(0x967090)
            	C:/workdir/go/src/runtime/proc.go:1490 +0xed
            runtime.gcMarkDone.func1()
            	C:/workdir/go/src/runtime/mgc.go:1524 +0x52
            runtime.systemstack(0x0)
            	C:/workdir/go/src/runtime/asm_386.s:389 +0x41
            
            goroutine 11 [GC worker (idle)]:
            runtime.systemstack_switch()
            	C:/workdir/go/src/runtime/asm_386.s:356 fp=0x12c2af78 sp=0x12c2af74 pc=0x45e2e0
            runtime.gcMarkDone()
            	C:/workdir/go/src/runtime/mgc.go:1517 +0xdc fp=0x12c2afa4 sp=0x12c2af78 pc=0x418ccc
            runtime.gcBgMarkWorker()
            	C:/workdir/go/src/runtime/mgc.go:2045 +0x26f fp=0x12c2aff0 sp=0x12c2afa4 pc=0x41a27f
            runtime.goexit()
            	C:/workdir/go/src/runtime/asm_386.s:1332 +0x1 fp=0x12c2aff4 sp=0x12c2aff0 pc=0x45f901
            created by runtime.gcBgMarkStartWorkers
            	C:/workdir/go/src/runtime/mgc.go:1835 +0x2d
            
            goroutine 1 [runnable]:
            cmd/go/internal/load.(*PackageError).Error(0x0, 0x8e5cc0, 0x0)
            	C:/workdir/go/src/cmd/go/internal/load/pkg.go:418 +0x1d
            fmt.(*pp).handleMethods(0x12c78120, 0x71, 0x12e7d301)
            	C:/workdir/go/src/fmt/print.go:620 +0x197
            fmt.(*pp).printArg(0x12c78120, 0x8e5cc0, 0x0, 0x71)
            	C:/workdir/go/src/fmt/print.go:709 +0x1a3
            fmt.(*pp).doPrintf(0x12c78120, 0x12d1e083, 0x2, 0x12f69d10, 0x1, 0x1)
            	C:/workdir/go/src/fmt/print.go:1026 +0x124
            fmt.Sprintf(0x12d1e083, 0x2, 0x12f69d10, 0x1, 0x1, 0x0, 0x0)
            	C:/workdir/go/src/fmt/print.go:219 +0x52
            reflect.Value.call(0x8a6240, 0x966d2c, 0x13, 0x91d377, 0x4, 0x12f09fb0, 0x2, 0x2, 0x12f09f98, 0x18, ...)
            	C:/workdir/go/src/reflect/value.go:476 +0x6f3
            reflect.Value.Call(0x8a6240, 0x966d2c, 0x13, 0x12f09f98, 0x2, 0x2, 0x12c80000, 0x5, 0x12c26000)
            	C:/workdir/go/src/reflect/value.go:337 +0x7a
            text/template.safeCall(0x8a6240, 0x966d2c, 0x13, 0x12f09f98, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
            	C:/workdir/go/src/text/template/funcs.go:365 +0x9e
            text/template.(*state).evalCall(0x12e7d7e4, 0x8815e0, 0x12dec840, 0x16, 0x8a6240, 0x966d2c, 0x13, 0x9e9c94, 0x12d929f0, 0x12d1e07b, ...)
            	C:/workdir/go/src/text/template/exec.go:725 +0x529
            text/template.(*state).evalFunction(0x12e7d7e4, 0x8815e0, 0x12dec840, 0x16, 0x12d92a08, 0x9e9c94, 0x12d929f0, 0x12d102e0, 0x2, 0x2, ...)
            	C:/workdir/go/src/text/template/exec.go:580 +0x10f
            text/template.(*state).evalCommand(0x12e7d7e4, 0x8815e0, 0x12dec840, 0x16, 0x12d929f0, 0x8e5cc0, 0x12dec9e4, 0x196, 0x8e5cc0, 0x12dec9e4, ...)
            	C:/workdir/go/src/text/template/exec.go:467 +0xc7
            text/template.(*state).evalPipeline(0x12e7d7e4, 0x8815e0, 0x12dec840, 0x16, 0x12d001b0, 0x0, 0x0, 0x198)
            	C:/workdir/go/src/text/template/exec.go:436 +0xf5
            text/template.(*state).walk(0x12e7d7e4, 0x8815e0, 0x12dec840, 0x16, 0x9e9c1c, 0x12d92a20)
            	C:/workdir/go/src/text/template/exec.go:255 +0x292
            text/template.(*state).walk(0x12e7d7e4, 0x8815e0, 0x12dec840, 0x16, 0x9e9d84, 0x12d92948)
            	C:/workdir/go/src/text/template/exec.go:264 +0xcc
            text/template.(*Template).execute(0x12db43e0, 0x9e3028, 0x12d049d8, 0x8815e0, 0x12dec840, 0x0, 0x0)
            	C:/workdir/go/src/text/template/exec.go:220 +0x13e
            text/template.(*Template).Execute(...)
            	C:/workdir/go/src/text/template/exec.go:203
            cmd/go/internal/list.runList.func4(0x8815e0, 0x12dec840)
            	C:/workdir/go/src/cmd/go/internal/list/list.go:383 +0x49
            cmd/go/internal/list.runList(0x9e811c, 0x12d12010, 0xc43fa0, 0x12d3e038, 0x1, 0x1)
            	C:/workdir/go/src/cmd/go/internal/list/list.go:711 +0xfb0
            main.main()
            	C:/workdir/go/src/cmd/go/main.go:195 +0x780
            [exit status 2]
            FAIL: testdata\script\list_test_err.txt:21: unexpected command failure
            
FAIL
FAIL	cmd/go	72.735s
FAIL
go tool dist: Failed: exit status 1


Error: tests failed: dist test failed: go_test:cmd/go: exit status 1
```

Full log: https://storage.googleapis.com/go-build-log/b93cee92/windows-386-2008_1c2803ef.log

cc @bcmills

**Comment by zx2c4** [comment]
Whoops, false alarm, was looking at wrong CL.
