### ISSUE TITLE
runtime, cmd/compile: SIGILL during fixedbugs/issue11656.go on aix-ppc64

### ISSUE THREAD

**Issue by bcmills** [golang/go#44583]
```
# go run run.go -- fixedbugs/issue11656.go
exit status 2
SIGILL: illegal instruction
PC=0xa0001000007156c m=0 sigcode=30
instruction bytes: 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0

goroutine 1 [running]:
runtime: unknown pc 0xa0001000007156c
stack: frame={sp:0xa00010000071538, fp:0x0} stack=[0xa00010000070000,0xa00010000072000)
0x0a00010000071438:  0x0000000000000000  0x00000001000136ac <runtime.heapBits.initSpan+0x00000000000000cc> 
0x0a00010000071448:  0x0000000000000000  0x0000000000000000 
0x0a00010000071458:  0x0000000000000000  0x0a00000026965100 
0x0a00010000071468:  0x0000000000004000  0x0a00000026b5ffff 
0x0a00010000071478:  0x0000000000000800  0x0a00000026965300 
0x0a00010000071488:  0x0000000000004000  0x0a00000026b5ffff 
0x0a00010000071498:  0x00000001000161e0 <runtime.(*mcentral).grow+0x0000000000000180>  0x0000000000000000 
0x0a000100000714a8:  0x000000010001293c <runtime.heapBits.forwardOrBoundary+0x000000000000006c>  0x0000000100026d50 <runtime.(*mheap).alloc+0x0000000000000070> 
0x0a000100000714b8:  0x0a00000026965100  0x0000000000000200 
0x0a000100000714c8:  0x0a00000026b5ffff  0x0000000000000800 
0x0a000100000714d8:  0x0a00000026965300  0x0000000000004000 
0x0a000100000714e8:  0x0a00000026b5ffff  0x0000000000000800 
0x0a000100000714f8:  0x0000400000004000  0x0000000026c91800 
0x0a00010000071508:  0x0000000000000800  0x0000000000000800 
0x0a00010000071518:  0x0000000000000700  0x0a00000026965300 
0x0a00010000071528:  0x0a00000026b5ffff  0x0000000100015e90 <runtime.(*mcentral).cacheSpan+0x0000000000000380> 
0x0a00010000071538: <0x0000000100090df8 <main.f+0x00000000000000a8>  0x0000000000004000 
0x0a00010000071548:  0x0a00000026b5ffff  0x0a00000026965100 
0x0a00010000071558:  0x0000000000004000  0x0a00010000071568 
0x0a00010000071568:  0xf800000000000000  0x0000000000000000 
0x0a00010000071578:  0x0000000000000000  0x0000000000000000 
0x0a00010000071588:  0x0000000000000000  0x0000000000000000 
0x0a00010000071598:  0x0000000000000000  0x0000000000000000 
0x0a000100000715a8:  0x0a00010000071560  0x0000000100090df8 <main.f+0x00000000000000a8> 
0x0a000100000715b8:  0x0a00000026b5ffff  0x0000000000000400 
0x0a000100000715c8:  0x0000000100015270 <runtime.(*mcache).refill+0x00000000000001b0>  0x0000000000000000 
0x0a000100000715d8:  0x000000010000bd74 <runtime.mallocgc+0x0000000000000634>  0x0a00000026c91800 
0x0a000100000715e8:  0x0000000000000000  0x000000011004a610 
0x0a000100000715f8:  0x000000011004a5c0  0x000000010000b59c <runtime.(*mcache).nextFree+0x000000000000009c> 
0x0a00010000071608:  0x00000000000000d0  0x0a00000026964f00 
0x0a00010000071618:  0x000000010000b5b0 <runtime.(*mcache).nextFree+0x00000000000000b0>  0x0000000110051fe8 
0x0a00010000071628:  0x0000000100090df8 <main.f+0x00000000000000a8>  0x0000000000004000 
runtime: unknown pc 0xa0001000007156c
stack: frame={sp:0xa00010000071538, fp:0x0} stack=[0xa00010000070000,0xa00010000072000)
0x0a00010000071438:  0x0000000000000000  0x00000001000136ac <runtime.heapBits.initSpan+0x00000000000000cc> 
0x0a00010000071448:  0x0000000000000000  0x0000000000000000 
0x0a00010000071458:  0x0000000000000000  0x0a00000026965100 
0x0a00010000071468:  0x0000000000004000  0x0a00000026b5ffff 
0x0a00010000071478:  0x0000000000000800  0x0a00000026965300 
0x0a00010000071488:  0x0000000000004000  0x0a00000026b5ffff 
0x0a00010000071498:  0x00000001000161e0 <runtime.(*mcentral).grow+0x0000000000000180>  0x0000000000000000 
0x0a000100000714a8:  0x000000010001293c <runtime.heapBits.forwardOrBoundary+0x000000000000006c>  0x0000000100026d50 <runtime.(*mheap).alloc+0x0000000000000070> 
0x0a000100000714b8:  0x0a00000026965100  0x0000000000000200 
0x0a000100000714c8:  0x0a00000026b5ffff  0x0000000000000800 
0x0a000100000714d8:  0x0a00000026965300  0x0000000000004000 
0x0a000100000714e8:  0x0a00000026b5ffff  0x0000000000000800 
0x0a000100000714f8:  0x0000400000004000  0x0000000026c91800 
0x0a00010000071508:  0x0000000000000800  0x0000000000000800 
0x0a00010000071518:  0x0000000000000700  0x0a00000026965300 
0x0a00010000071528:  0x0a00000026b5ffff  0x0000000100015e90 <runtime.(*mcentral).cacheSpan+0x0000000000000380> 
0x0a00010000071538: <0x0000000100090df8 <main.f+0x00000000000000a8>  0x0000000000004000 
0x0a00010000071548:  0x0a00000026b5ffff  0x0a00000026965100 
0x0a00010000071558:  0x0000000000004000  0x0a00010000071568 
0x0a00010000071568:  0xf800000000000000  0x0000000000000000 
0x0a00010000071578:  0x0000000000000000  0x0000000000000000 
0x0a00010000071588:  0x0000000000000000  0x0000000000000000 
0x0a00010000071598:  0x0000000000000000  0x0000000000000000 
0x0a000100000715a8:  0x0a00010000071560  0x0000000100090df8 <main.f+0x00000000000000a8> 
0x0a000100000715b8:  0x0a00000026b5ffff  0x0000000000000400 
0x0a000100000715c8:  0x0000000100015270 <runtime.(*mcache).refill+0x00000000000001b0>  0x0000000000000000 
0x0a000100000715d8:  0x000000010000bd74 <runtime.mallocgc+0x0000000000000634>  0x0a00000026c91800 
0x0a000100000715e8:  0x0000000000000000  0x000000011004a610 
0x0a000100000715f8:  0x000000011004a5c0  0x000000010000b59c <runtime.(*mcache).nextFree+0x000000000000009c> 
0x0a00010000071608:  0x00000000000000d0  0x0a00000026964f00 
0x0a00010000071618:  0x000000010000b5b0 <runtime.(*mcache).nextFree+0x00000000000000b0>  0x0000000110051fe8 
0x0a00010000071628:  0x0000000100090df8 <main.f+0x00000000000000a8>  0x0000000000004000 

r0   0x0	r1   0xa00010000071538
r2   0x110015c40	r3   0xa00010000071560
r4   0x0	r5   0x1
r6   0x1	r7   0x11004e780
r8   0x0	r9   0x0
r10  0x2	r11  0xa00010000071560
r12  0xa00010000071568	r13  0x1100647e0
r14  0x8	r15  0x1000cf118
r16  0xa00010000094020	r17  0x0
r18  0xa00010000094000	r19  0xffffffffffffffff
r20  0xa000100000715a8	r21  0xa00010000094020
r22  0x0	r23  0x0
r24  0x16	r25  0xd0
r26  0xbadc0ffee0ddf00d	r27  0xbadc0ffee0ddf00d
r28  0xbadc0ffee0ddf00d	r29  0xbadc0ffee0ddf00d
r30  0xa00010000000180	r31  0x10
pc   0xa0001000007156c	ctr  0x0
link 0x100090ddc	xer  0x20000000
ccr  0x44420222	trap 0x0

FAIL	fixedbugs/issue11656.go	1.126s
```

[2021-02-24T15:12:08-07c6583/aix-ppc64](https://build.golang.org/log/f8f09d4101d086193d21f5610a19b3073b952da1)
[2021-02-23T04:13:10-378f73e/aix-ppc64](https://build.golang.org/log/08a51f6564b345effa55becf4cd5cb2b7a22a7d8)

CC @mknyszek @jeremyfaller @trex58

**Comment by gbbr** [comment]
Hi there! Not sure if related, but we're getting `SIGILL` at startup too, when `goenvs()` runs in the runtime:
```
$ gdb ./datadog-agent/trace-agent core.20971810.25160320 
GNU gdb (GDB) 8.1.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "powerpc64-ibm-aix6.1.0.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./datadog-agent/trace-agent...done.

warning: core file may not match specified executable file.
Core was generated by `trace-agent'.
Program terminated with signal SIGILL, Illegal instruction.
#0  0x000000010004d034 in runtime.goenvs_unix () at /opt/freeware/lib/golang/src/runtime/runtime1.go:85
85              envs = make([]string, n)
(gdb) where
#0  0x000000010004d034 in runtime.goenvs_unix () at /opt/freeware/lib/golang/src/runtime/runtime1.go:85
#1  0x000000010006dacc in runtime.ensureSigM.func1 () at /opt/freeware/lib/golang/src/runtime/signal_unix.go:875
#2  0x0000d431e0ddf00d in ?? ()
(gdb) quit
```
There is a `TODO` there which is concerning:
https://github.com/golang/go/blob/go1.14/src/runtime/runtime1.go#L85

**Comment by dmitshur** [comment]
aix/ppc64 looks green on the dashboard recently. Maybe this is resolved or just rare?

I'll move this to Backlog since it doesn't seem this is actively being worked on for Go 1.17 specifically.

**Comment by bcmills** [comment]
`greplogs --dashboard -md -l -e '# go run .* fixedbugs/issue11656\.go\nexit status 2\nSIGILL: illegal instruction'`

[2022-01-06T21:38:57-c5540e5/aix-ppc64](https://build.golang.org/log/2167858316fbb2fcd35867bef098d6920707c044)
[2021-10-15T21:46:06-ed1c8db/aix-ppc64](https://build.golang.org/log/5bc3292774f69305965e3976df5410319045c6cd)
[2021-10-05T18:39:53-7e69c5d/aix-ppc64](https://build.golang.org/log/b65ec5ecbbe7cc57a552bab9e3e007a8c125a6b9)
[2021-04-12T22:19:11-841bc14/aix-ppc64](https://build.golang.org/log/7a4653fc13a34d5c755c93fb2b7128bd2cacb4cd)
[2021-04-09T17:49:01-2698be4/aix-ppc64](https://build.golang.org/log/0dfda436dae8336335fbc07ebb0c0f86d0054fcb)
[2021-03-13T18:35:01-1767d2c/aix-ppc64](https://build.golang.org/log/3d15bfc12dcfa16f66c1ee966713daadae421a39)
[2021-02-24T18:03:45-dc4698f/aix-ppc64](https://build.golang.org/log/0af03ef94f5a19c459c9724efd916fbd01f50124)
[2021-02-24T15:12:08-07c6583/aix-ppc64](https://build.golang.org/log/f8f09d4101d086193d21f5610a19b3073b952da1)
[2021-02-23T04:13:10-378f73e/aix-ppc64](https://build.golang.org/log/08a51f6564b345effa55becf4cd5cb2b7a22a7d8)

**Comment by bcmills** [comment]
Marking as release-blocker because this is showing up fairly frequently in the builders. If no one is actively working on this issue, the test should be skipped on this platform to avoid masking other regressions.

**Comment by cherrymui** [comment]
I wonder if there is some cache coherence thing? We write some bytes in memory then execute them, but the I-cache may be still holding the old content which may be an illegal instruction?
