### ISSUE TITLE
url.Parse twice maybe lead to panic

### ISSUE THREAD

**Issue by cor0ps** [golang/go#44631]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 linux/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
[root@cor0ps ~]# go env
GO111MODULE="off"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/usr/local/sbin/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/bin:/opt/go/"
GOPRIVATE=""
GOPROXY="https://mirrors.aliyun.com/goproxy/"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2374357860=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

https://play.golang.org/p/aGhEYiEiSfN
panic: parse "//%20f": invalid URL escape "%20"

goroutine 1 [running]:
main.main()
	/tmp/sandbox000750098/prog.go:23 +0x269

### What did you expect to see?

first parse  and second parse  need same

### What did you see instead?

panic: parse "//%20f": invalid URL escape "%20"

goroutine 1 [running]:
main.main()
	/tmp/sandbox000750098/prog.go:23 +0x269

**Comment by seankhliao** [comment]
unfortunate, but I think it's working as intended.
EscapedPath ignores the RawPath because it isn't a valid escaped form.
