### ISSUE TITLE
runtime: unexpected signal during async preemption on windows/amd64

### ISSUE THREAD

**Issue by zx2c4** [golang/go#44679]
With @rsc's arm64 changes, I'm getting reports of crashes on amd64 involving signals during async preemption:

```
2021-02-28 10:31:31.978278: [TUN] fatal error: unexpected signal during runtime execution
2021-02-28 10:31:31.981817: [TUN] [signal 0xc0000005 code=0x0 addr=0xb1 pc=0xaf626a]
2021-02-28 10:31:31.981817: [TUN] runtime stack:
2021-02-28 10:31:31.981817: [TUN] runtime.throw(0xeffc67, 0x2a)
2021-02-28 10:31:31.981817: [TUN] runtime/panic.go:1117 +0x79
2021-02-28 10:31:31.981817: [TUN] runtime.sigpanic()
2021-02-28 10:31:31.981817: [TUN] runtime/signal_windows.go:237 +0x317
2021-02-28 10:31:31.981817: [TUN] runtime.wantAsyncPreempt(...)
2021-02-28 10:31:31.981817: [TUN] runtime/preempt.go:344
2021-02-28 10:31:31.981817: [TUN] runtime.preemptM(0xc000035400)
2021-02-28 10:31:31.981817: [TUN] runtime/os_windows.go:1306 +0x24a
2021-02-28 10:31:31.981817: [TUN] runtime.preemptone(0xc000027800, 0xf9061ffdc8)
2021-02-28 10:31:31.981817: [TUN] runtime/proc.go:5307 +0xb2
2021-02-28 10:31:31.981817: [TUN] runtime.retake(0x2de1c0936154, 0x200000000)
2021-02-28 10:31:31.981817: [TUN] runtime/proc.go:5214 +0x245
2021-02-28 10:31:31.981817: [TUN] runtime.sysmon()
2021-02-28 10:31:31.981817: [TUN] runtime/proc.go:5156 +0x196
2021-02-28 10:31:31.981817: [TUN] runtime.mstart1()
2021-02-28 10:31:31.981817: [TUN] runtime/proc.go:1317 +0xda
2021-02-28 10:31:31.981817: [TUN] runtime.mstart0()
2021-02-28 10:31:31.981817: [TUN] runtime/proc.go:1275 +0x6d
2021-02-28 10:31:31.981817: [TUN] runtime.mstart(0x7ffe62037034, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ffe634fd241, 0x0, 0x0, 0x0, ...)
2021-02-28 10:31:31.981817: [TUN] runtime/asm_amd64.s:256 +0x5
2021-02-28 10:31:31.981817: [TUN] goroutine 1 [syscall, locked to thread]:
2021-02-28 10:31:31.981817: [TUN] syscall.Syscall(0x7ffe615c7c00, 0x1, 0xc00010fc58, 0x0, 0x0, 0x0, 0x0, 0x0)
2021-02-28 10:31:31.981817: [TUN] runtime/syscall_windows.go:332 +0xe9
2021-02-28 10:31:31.981817: [TUN] golang.org/x/sys/windows.StartServiceCtrlDispatcher(0xc00010fc58, 0xf1e5a8, 0xc000043540)
2021-02-28 10:31:31.981817: [TUN] golang.org/x/sys@v0.0.0-20210225134936-a50acf3fe073/windows/zsyscall_windows.go:1154 +0x8a
2021-02-28 10:31:31.981817: [TUN] golang.org/x/sys/windows/svc.Run(0xc000012258, 0x18, 0xf7cf00, 0xc000037cf0, 0x8, 0xc000012258)
2021-02-28 10:31:31.981817: [TUN] golang.org/x/sys@v0.0.0-20210225134936-a50acf3fe073/windows/svc/service.go:366 +0x1c8
```

Cc @aclements who wrote preemption support.

**Comment by zx2c4** [comment]
Looking more carefully,

```go
func wantAsyncPreempt(gp *g) bool {
	// Check both the G and the P.
	return (gp.preempt || gp.m.p != 0 && gp.m.p.ptr().preempt) && readgstatus(gp)&^_Gscan == _Grunning
}
```

Is this panicking because gp.m.p.ptr() points somewhere bogus?

**Comment by zx2c4** [comment]
Ahhh more likely is that gp is bogus. That comes from:

```go

	// Does it want a preemption and is it safe to preempt?
	gp := gFromSP(mp, c.sp())
	if wantAsyncPreempt(gp) {
```

**Comment by zx2c4** [comment]
@rsc might be an issue with https://github.com/golang/go/commit/ece954d8b8e13a76de891c8078c27c5e7f884f9f#diff-fc175f04ebb256c1d34c14d27b8915f38928b71df55a35bfbd86fcb4618ff5a9

Maybe it's simply enough to check for nil... I'll send a CL.

**Comment by zx2c4** [comment]
I've deployed https://golang.org/cl/297390 and it evidently fixes the crash users were seeing.

**Comment by networkimprov** [comment]
@gopherbot add OS-Windows

**Comment by bcmills** [comment]
Is https://build.golang.org/log/995be8dc15fe8289ca78257701e522e5b5d51336 (`windows-386`) likely to be due to the same root cause?

**Comment by bcmills** [comment]
Another `windows-386` TryBot failure with `unexpected signal during runtime execution` in `runtime.wantAsyncPreempt`:
https://storage.googleapis.com/go-build-log/764770a7/windows-386-2008_4820c228.log

**Comment by zx2c4** [comment]
Looks familiar. https://golang.org/cl/297390 fixes the issue, but I'm not able to reproduce it myself to get more info supporting that CL.

**Comment by zx2c4** [comment]
CC @cherrymui
