### ISSUE TITLE
runtime: fatal error: newproc1: new g is not Gdead

### ISSUE THREAD

**Issue by urbanishimwe** [golang/go#44722]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.8 linux/amd64
</pre>

### What did you do?

Started a new goroutine
https://github.com/buger/goreplay/blob/master/tcp/tcp_message.go#L213

### What did you expect to see?

runtime to hopefully starts a new goroutine silently.

### What did you see instead?

```
fatal error: newproc1: new g is not Gdead

runtime stack:
runtime.throw(0xe34de1, 0x1c)
	/snap/go/7013/src/runtime/panic.go:1116 +0x72
runtime.newproc1(0xe62b50, 0xc000063d00, 0x18, 0xc00008a900, 0xc086fa, 0xc000063b18)
	/snap/go/7013/src/runtime/proc.go:3606 +0x43e
runtime.newproc.func1()
	/snap/go/7013/src/runtime/proc.go:3555 +0x53
runtime.systemstack(0x7f9e50000020)
	/snap/go/7013/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
	/snap/go/7013/src/runtime/proc.go:1116
              .........
              .........
              .........
              .........
              .........
              .........
goroutine 3544668469065756977 [??? (scan), locked to thread]:
fatal error: unexpected signal during runtime execution
panic during panic
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x463b10]

runtime stack:
runtime.throw(0xe4629e, 0x2a)
	/snap/go/7013/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
	/snap/go/7013/src/runtime/signal_unix.go:726 +0x4ac
runtime.traceback1(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc000556000, 0x0)
	/snap/go/7013/src/runtime/traceback.go:712 +0x50
runtime.traceback(...)
	/snap/go/7013/src/runtime/traceback.go:690
runtime.tracebackothers(0xc0002d4180)
	/snap/go/7013/src/runtime/traceback.go:944 +0x165
runtime.dopanic_m(0xc0002d4180, 0x43bdd2, 0x7f9e73f19da0, 0x1)
	/snap/go/7013/src/runtime/panic.go:1322 +0x2bf
runtime.fatalthrow.func1()
	/snap/go/7013/src/runtime/panic.go:1171 +0x5f
runtime.fatalthrow()
	/snap/go/7013/src/runtime/panic.go:1168 +0x57
runtime.throw(0xe34de1, 0x1c)
	/snap/go/7013/src/runtime/panic.go:1116 +0x72
runtime.newproc1(0xe62b50, 0xc000063d00, 0x18, 0xc00008a900, 0xc086fa, 0xc000063b18)
	/snap/go/7013/src/runtime/proc.go:3606 +0x43e
runtime.newproc.func1()
	/snap/go/7013/src/runtime/proc.go:3555 +0x53
runtime.systemstack(0x7f9e50000020)
	/snap/go/7013/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
	/snap/go/7013/src/runtime/proc.go:1116
```

**Comment by networkimprov** [comment]
Are you able to reproduce this error? If so, could you create a small program that demonstrates it?
