### ISSUE TITLE
dev.go2go: nil dereference in T(0) conversion

### ISSUE THREAD

**Issue by adonovan** [golang/go#44762]
This program https://go2goplay.golang.org/p/OiIPqlYuHqM:

```
type I interface {
	type int8, int16
}

func f[T I]() {
	T(0) // panic in go/types
}
```

causes this crash:
```
goroutine 1 [running]:
go/types.(*Checker).handleBailout(0xc0000d4280, 0xc00010fbe0)
	/usr/local/go-faketime/src/go/types/check.go:249 +0x98
panic(0x64f100, 0x7fd8f0)
	/usr/local/go-faketime/src/runtime/panic.go:969 +0x175
go/types.is(0x6d9680, 0x0, 0x2, 0x6d9700)
	/usr/local/go-faketime/src/go/types/predicates.go:35 +0xc6
go/types.isInteger(0x6d9680, 0x0, 0xc00010e588)
	/usr/local/go-faketime/src/go/types/predicates.go:43 +0x3e
go/types.representableConst(0x6dc800, 0x7f79a0, 0xc0000d4280, 0x0, 0xc0000b0528, 0x56e9f5)
	/usr/local/go-faketime/src/go/types/expr.go:211 +0x91
go/types.(*Checker).conversion(0xc0000d4280, 0xc0000b0500, 0x6d9940, 0xc000086d80)
	/usr/local/go-faketime/src/go/types/conversions.go:24 +0xc9
```

**Comment by griesemer** [comment]
I cannot reproduce this with `go/types` in the `master` branch. The `go/types` version in `dev.go2go` will need to be updated eventually.

cc: @findleyr

**Comment by findleyr** [comment]
dev.go2go (and the go2go playground) have been updated, and the program above no longer panics.
