### ISSUE TITLE
cmd/link/internal/ld: hang in TestRuntimeTypeAttrExternal on netbsd-386-9_0

### ISSUE THREAD

**Issue by bcmills** [golang/go#44801]
```
goroutine 36 [syscall, 2 minutes]:
syscall.Syscall6(0x1da2, 0x84c3da0, 0x0, 0x98e4000, 0x0, 0x0, 0x0, 0x0, 0x50, 0xbbabe538)
	/tmp/workdir/go/src/syscall/asm_unix_386.s:43 +0x5
syscall.wait4(0x1da2, 0x84c3da0, 0x0, 0x98e4000, 0x50, 0x8223200, 0x1)
	/tmp/workdir/go/src/syscall/zsyscall_netbsd_386.go:35 +0x5b
syscall.Wait4(0x1da2, 0x84c3dc4, 0x0, 0x98e4000, 0x9d880a0, 0xffffff10, 0xbffffff)
	/tmp/workdir/go/src/syscall/syscall_bsd.go:145 +0x3b
os.(*Process).wait(0x91ac060, 0x674, 0x824da80, 0x824da84)
	/tmp/workdir/go/src/os/exec_unix.go:44 +0x66
os.(*Process).Wait(...)
	/tmp/workdir/go/src/os/exec.go:129
os/exec.(*Cmd).Wait(0x9da2420, 0x0, 0x0)
	/tmp/workdir/go/src/os/exec/exec.go:507 +0x4d
os/exec.(*Cmd).Run(0x9da2420, 0x8eca060, 0x9da2420)
	/tmp/workdir/go/src/os/exec/exec.go:341 +0x43
os/exec.(*Cmd).CombinedOutput(0x9da2420, 0x26, 0x0, 0x0, 0x0, 0x9da2420)
	/tmp/workdir/go/src/os/exec/exec.go:567 +0x75
cmd/link/internal/ld.testRuntimeTypeAttr(0x8a01420, 0x8244829, 0x1b)
	/tmp/workdir/go/src/cmd/link/internal/ld/dwarf_test.go:983 +0x191
cmd/link/internal/ld.TestRuntimeTypeAttrExternal(0x8a01420)
	/tmp/workdir/go/src/cmd/link/internal/ld/dwarf_test.go:957 +0x53
testing.tRunner(0x8a01420, 0x824d818)
	/tmp/workdir/go/src/testing/testing.go:1194 +0xbf
created by testing.(*T).Run
	/tmp/workdir/go/src/testing/testing.go:1239 +0x214
```

Looks to me like the external (system) linker wedged somehow.

[2021-03-05T02:30:31-b62da08/netbsd-386-9_0](https://build.golang.org/log/a90168a43a8ff7c7132c9c356d53b2868ad5d79a)

CC @bsiegert @coypoop

**Comment by bsiegert** [comment]
This is a shot in the dark, but I do remember some deadlock issues in the linker in NetBSD 9.0 that have been fixed in 9.1. We saw them most often in Rust code.

How about I send a CL to update the builder to 9.1? This will get us more bugfixes as well.
