### ISSUE TITLE
cmd/compile: runtime crashes with regabi enabled

### ISSUE THREAD

**Issue by cherrymui** [golang/go#44821]
Recently (starting today), there are a few runtime crashes on the regabi builder:
https://build.golang.org/log/f9d8af48f86cba5eb0cd273ef0c587b86aafd8ad
https://build.golang.org/log/200dd9847dd300305c07e6dff1931b743bc8228d
https://build.golang.org/log/e9c33ec32863a8ff520df1499a99e314ebfc4380

And I just ran into one locally (with some pending CLs)
```
##### GOMAXPROCS=2 runtime -cpu=1,2,4 -quick
runtime: unexpected return pc for fmt.(*pp).doPrintf called from 0x0
stack: frame={sp:0xc000723a00, fp:0xc000723af0} stack=[0xc000723000,0xc000724000)
0x000000c000723900:  0x0000000001055bc6 <runtime.sigpanic+0x00000000000003e6>  0x0000000001243b80 
0x000000c000723910:  0x00000000014185f0  0x00000000013f6c68 
0x000000c000723920:  0x0000000001409040  0x000000c000723b48 
0x000000c000723930:  0x00000000010f3756 <testing.(*common).frameSkip+0x00000000000003b6>  0x000000c00072399d 
0x000000c000723940:  0x000000c000723b58  0x000000000130bdd5 
0x000000c000723950:  0x0000000000000018  0x000000c0007239f0 
0x000000c000723960:  0x00000000010d7018 <fmt.(*pp).printArg+0x0000000000000198>  0x0000000000000030 
0x000000c000723970:  0x000000000000002f  0x0000000001182be0 <runtime_test.runTestProg+0x0000000000000000> 
0x000000c000723980:  0x00000000013e9c18  0x0000000001409040 
0x000000c000723990:  0x0000000000000001  0x000100c000723a10 
0x000000c0007239a0:  0x0000000000000004  0x0000000000000001 
0x000000c0007239b0:  0x0000000001231cc0  0x0000000001010500 <runtime.mallocgc+0x0000000000000300> 
0x000000c0007239c0:  0x000000c00041cc30  0x000000c000723a20 
0x000000c0007239d0:  0x000000c00041d380  0x0000000000000008 
0x000000c0007239e0:  0x0000000000000005  0x000000c0006f4820 
0x000000c0007239f0:  0x000000c000723ae0  0x00000000010da75f <fmt.(*pp).doPrintf+0x000000000000015f> 
0x000000c000723a00: <0x000000c00041cc30  0x0000000000000080 
0x000000c000723a10:  0x0000000000000002  0x0000000000000073 
0x000000c000723a20:  0x0000000000000000  0x0000000000000000 
0x000000c000723a30:  0x0000000000000000  0x0000000000000000 
0x000000c000723a40:  0x0000000000000001  0x000000c000029e28 
0x000000c000723a50:  0x0000000000000001  0x000000c000029e60 
0x000000c000723a60:  0x0000000000000080  0x000000c000029000 
0x000000c000723a70:  0x0000000000000080  0x0000000000000007 
0x000000c000723a80:  0x0000000001301fe0  0x0000000000000000 
0x000000c000723a90:  0x0000000000000000  0x2e676e6974736574 
0x000000c000723aa0:  0x0000000000000000  0x00000000010b150d <strconv.genericFtoa+0x000000000000044d> 
0x000000c000723ab0:  0x000000c00005be00  0x0000000001425ae0 
0x000000c000723ac0:  0x000000c00005be00  0x000000c00005be00 
0x000000c000723ad0:  0x0000000000000000  0x000000c00005be00 
0x000000c000723ae0:  0x0000000000000000 !0x0000000000000000 
0x000000c000723af0: >0x0000000000000000  0x0000000000000000 
0x000000c000723b00:  0x000000c00005be00  0x0000000000000000 
0x000000c000723b10:  0x000000c00005be00  0x0000000000000000 
0x000000c000723b20:  0x0000000000000080  0x000000c000029000 
0x000000c000723b30:  0x0000000000000080  0x0000000000000007 
0x000000c000723b40:  0x000000c000029e28  0x000000c000723cf0 
0x000000c000723b50:  0x00000000010f3d3c <testing.(*common).decorate+0x000000000000021c>  0x00000000012e0c70 
0x000000c000723b60:  0x000000c00041e1e0  0x0000000001289f07 
0x000000c000723b70:  0x0000000000000007  0x000000c000723c20 
0x000000c000723b80:  0x0000000000000002  0x0000000000000002 
0x000000c000723b90:  0x0000000000000008  0x000000000000002f 
0x000000c000723ba0:  0x0000000001182be0 <runtime_test.runTestProg+0x0000000000000000>  0x00000000013e9c18 
0x000000c000723bb0:  0x0000000001409040  0x0000000000000066 
0x000000c000723bc0:  0x0000000000000006  0x000000000000002f 
0x000000c000723bd0:  0x0000000001010045 <runtime.(*mcache).nextFree+0x0000000000000085>  0x000000000000000d 
0x000000c000723be0:  0x0000000000000001  0x000000c000029e28 
fatal error: unknown caller pc

runtime stack:
runtime.throw(0x128e8cd, 0x11)
	/Users/cherryyz/src/go/src/runtime/panic.go:1126 +0x74 fp=0x700003ec1b60 sp=0x700003ec1b30 pc=0x103da94
runtime.gentraceback(0x1055bc6, 0xc000723908, 0x0, 0xc000102a80, 0x0, 0x0, 0x7fffffff, 0x700003ec1f08, 0x0, 0x0, ...)
	/Users/cherryyz/src/go/src/runtime/traceback.go:271 +0x1c93 fp=0x700003ec1eb0 sp=0x700003ec1b60 pc=0x1068f93
runtime.addOneOpenDeferFrame.func1()
	/Users/cherryyz/src/go/src/runtime/panic.go:718 +0x88 fp=0x700003ec1f30 sp=0x700003ec1eb0 pc=0x103c308
runtime.systemstack(0x80000)
	/Users/cherryyz/src/go/src/runtime/asm_amd64.s:358 +0x49 fp=0x700003ec1f38 sp=0x700003ec1f30 pc=0x1078149

goroutine 177548 [running]:
runtime.systemstack_switch()
	/Users/cherryyz/src/go/src/runtime/asm_amd64.s:325 fp=0xc0007236e0 sp=0xc0007236d8 pc=0x10780e0
runtime.addOneOpenDeferFrame(0xc000102a80, 0x1055bc6, 0xc000723908)
	/Users/cherryyz/src/go/src/runtime/panic.go:717 +0x7a fp=0xc000723720 sp=0xc0007236e0 pc=0x103c23a
panic(0x1243b80, 0x14185f0)
	/Users/cherryyz/src/go/src/runtime/panic.go:932 +0x127 fp=0xc000723908 sp=0xc000723720 pc=0x103d1e7
runtime.panicmem(...)
	/Users/cherryyz/src/go/src/runtime/panic.go:213
runtime.sigpanic()
	/Users/cherryyz/src/go/src/runtime/signal_unix.go:735 +0x3e6 fp=0xc000723968 sp=0xc000723908 pc=0x1055bc6
fmt.(*pp).printArg(0xc00041cc30, 0x80, 0x2, 0x73)
	/Users/cherryyz/src/go/src/fmt/print.go:660 +0x198 fp=0xc000723a00 sp=0xc000723968 pc=0x10d7018
runtime: unexpected return pc for fmt.(*pp).doPrintf called from 0x0
stack: frame={sp:0xc000723a00, fp:0xc000723af0} stack=[0xc000723000,0xc000724000)
0x000000c000723900:  0x0000000001055bc6 <runtime.sigpanic+0x00000000000003e6>  0x0000000001243b80 
0x000000c000723910:  0x00000000014185f0  0x00000000013f6c68 
0x000000c000723920:  0x0000000001409040  0x000000c000723b48 
0x000000c000723930:  0x00000000010f3756 <testing.(*common).frameSkip+0x00000000000003b6>  0x000000c00072399d 
0x000000c000723940:  0x000000c000723b58  0x000000000130bdd5 
0x000000c000723950:  0x0000000000000018  0x000000c0007239f0 
0x000000c000723960:  0x00000000010d7018 <fmt.(*pp).printArg+0x0000000000000198>  0x0000000000000030 
0x000000c000723970:  0x000000000000002f  0x0000000001182be0 <runtime_test.runTestProg+0x0000000000000000> 
0x000000c000723980:  0x00000000013e9c18  0x0000000001409040 
0x000000c000723990:  0x0000000000000001  0x000100c000723a10 
0x000000c0007239a0:  0x0000000000000004  0x0000000000000001 
0x000000c0007239b0:  0x0000000001231cc0  0x0000000001010500 <runtime.mallocgc+0x0000000000000300> 
0x000000c0007239c0:  0x000000c00041cc30  0x000000c000723a20 
0x000000c0007239d0:  0x000000c00041d380  0x0000000000000008 
0x000000c0007239e0:  0x0000000000000005  0x000000c0006f4820 
0x000000c0007239f0:  0x000000c000723ae0  0x00000000010da75f <fmt.(*pp).doPrintf+0x000000000000015f> 
0x000000c000723a00: <0x000000c00041cc30  0x0000000000000080 
0x000000c000723a10:  0x0000000000000002  0x0000000000000073 
0x000000c000723a20:  0x0000000000000000  0x0000000000000000 
0x000000c000723a30:  0x0000000000000000  0x0000000000000000 
0x000000c000723a40:  0x0000000000000001  0x000000c000029e28 
0x000000c000723a50:  0x0000000000000001  0x000000c000029e60 
0x000000c000723a60:  0x0000000000000080  0x000000c000029000 
0x000000c000723a70:  0x0000000000000080  0x0000000000000007 
0x000000c000723a80:  0x0000000001301fe0  0x0000000000000000 
0x000000c000723a90:  0x0000000000000000  0x2e676e6974736574 
0x000000c000723aa0:  0x0000000000000000  0x00000000010b150d <strconv.genericFtoa+0x000000000000044d> 
0x000000c000723ab0:  0x000000c00005be00  0x0000000001425ae0 
0x000000c000723ac0:  0x000000c00005be00  0x000000c00005be00 
0x000000c000723ad0:  0x0000000000000000  0x000000c00005be00 
0x000000c000723ae0:  0x0000000000000000 !0x0000000000000000 
0x000000c000723af0: >0x0000000000000000  0x0000000000000000 
0x000000c000723b00:  0x000000c00005be00  0x0000000000000000 
0x000000c000723b10:  0x000000c00005be00  0x0000000000000000 
0x000000c000723b20:  0x0000000000000080  0x000000c000029000 
0x000000c000723b30:  0x0000000000000080  0x0000000000000007 
0x000000c000723b40:  0x000000c000029e28  0x000000c000723cf0 
0x000000c000723b50:  0x00000000010f3d3c <testing.(*common).decorate+0x000000000000021c>  0x00000000012e0c70 
0x000000c000723b60:  0x000000c00041e1e0  0x0000000001289f07 
0x000000c000723b70:  0x0000000000000007  0x000000c000723c20 
0x000000c000723b80:  0x0000000000000002  0x0000000000000002 
0x000000c000723b90:  0x0000000000000008  0x000000000000002f 
0x000000c000723ba0:  0x0000000001182be0 <runtime_test.runTestProg+0x0000000000000000>  0x00000000013e9c18 
0x000000c000723bb0:  0x0000000001409040  0x0000000000000066 
0x000000c000723bc0:  0x0000000000000006  0x000000000000002f 
0x000000c000723bd0:  0x0000000001010045 <runtime.(*mcache).nextFree+0x0000000000000085>  0x000000000000000d 
0x000000c000723be0:  0x0000000000000001  0x000000c000029e28 
fmt.(*pp).doPrintf(0x0, 0x0, 0xc00005be00, 0x0, 0xc00005be00, 0x0)
	/Users/cherryyz/src/go/src/fmt/print.go:1026 +0x15f fp=0xc000723af0 sp=0xc000723a00 pc=0x10da75f
created by testing.(*T).Run
	/Users/cherryyz/src/go/src/testing/testing.go:1281 +0x2a5
```

I only saw them with regabi enabled. So I guess it may be related.

**Comment by cherrymui** [comment]
There might be other causes. E.g. #44823 can materialize as clobbering return address.

**Comment by cherrymui** [comment]
Still having failures after #44823 is fixed. I'll look into it.
