### ISSUE TITLE
runtime: runtime.GC can return without finishing sweep

### ISSUE THREAD

**Issue by aclements** [golang/go#45315]
`runtime.TestGCTestIsReachable` has been flaky since I added it. The failures look like:

```
##### GOMAXPROCS=2 runtime -cpu=1,2,4 -quick
runtime: object 0 was not swept
fatal error: IsReachable failed

goroutine 176934 [running]:
runtime.throw(0x688d74, 0x12)
	/workdir/go/src/runtime/panic.go:1126 +0x74 fp=0xc000276628 sp=0xc0002765f8 pc=0x43e334
runtime.gcTestIsReachable(0xc00108e200, 0x10, 0x10, 0x4)
	/workdir/go/src/runtime/mgc.go:2397 +0x2ad fp=0xc000276690 sp=0xc000276628 pc=0x423a0d
runtime.GCTestIsReachable(...)
	/workdir/go/src/runtime/export_test.go:1256
runtime_test.TestGCTestIsReachable(0xc00090d380)
	/workdir/go/src/runtime/gc_test.go:249 +0x25c fp=0xc000276780 sp=0xc000276690 pc=0x58a8fc
testing.tRunner(0xc00090d380, 0x69c980)
	/workdir/go/src/testing/testing.go:1235 +0x102 fp=0xc0002767d0 sp=0xc000276780 pc=0x4eee02
runtime.goexit()
	/workdir/go/src/runtime/asm_amd64.s:1454 +0x1 fp=0xc0002767d8 sp=0xc0002767d0 pc=0x47b861
created by testing.(*T).Run
	/workdir/go/src/testing/testing.go:1280 +0x3ab
```

Some examples:

https://build.golang.org/log/6664ed5c503173b3f29eb85cb093baa61fb04838
https://build.golang.org/log/5608852a242f93bb2f36b6a56bebdefda3797e82
https://build.golang.org/log/231e6d68ccc2b858f8b002b45596356d8beb856c

I'm sure this has something to do with GC scheduling.

I haven't had any luck reproducing this locally. I'm now trying on the gomotes.

```sh
gopool create -setup 'gomote push $VM && gomote run $VM go/src/make.bash && gomote run $VM go/bin/go test -c -o ../src/runtime/runtime.test runtime' linux-amd64-sid
stress2 -p 5 gopool run 'gomote run $VM go/src/runtime/runtime.test -test.short -test.cpu=1,2,4'
```

**Comment by aclements** [comment]
Some progress. `runtime.GC()` is successfully waiting for the mark to complete, but returning before the sweep is complete. We could work around this in IsReachable, but this is actually a bug in`runtime.GC()`.

**Comment by aclements** [comment]
I think I understand what's going on. Sweeping tracks two different types of completion: "we've swept or started sweeping all spans" (confusingly called `mheap_.sweepdone`) and "all spans have been swept". GC correctness depends on `mheap_.sweepdone` and we get that one right, but `runtime.GC()` and a few other minor things depend on the latter condition, and we get that wrong.

For "all spans have been swept", we track that we've exited all calls to `sweepone` and there are no more spans that haven't started sweeping, but that's not the only way that spans get swept. Hence, the final `sweepone` could exit with no more spans in the queue and declare that all spans have been swept, but there could still be concurrent sweeps from *other* sources working on the last few spans. In `TestGCTestIsReachable`, the result is that `runtime.GC()` returns while the span with all the test's objects is actively being swept.

**Comment by bcmills** [comment]
Do you expect to have a fix soon, or can the test be disabled until it is fixed?
I'm concerned that the failure rate on the builders could mask regressions that lead to other low-frequency failures.

**Comment by aclements** [comment]
I just committed a workaround in `TestGCTestIsReachable` that should stop the test flakes.

**Comment by networkimprov** [comment]
Backport candidate?

**Comment by aclements** [comment]
I'm not sure this is really important enough to backport. It's incredibly difficult to trigger and difficult to observe even if you do trigger it. The most likely user effect is that you may observe a heap profile after calling `runtime.GC()` that's wrong by a few spans worth of memory.

**Comment by mknyszek** [comment]
As per https://github.com/golang/go/issues/46500#issuecomment-872556305 this is unfortunately still possible. I will fix #46500 with an extra `runtime.GC` call, but this should be resolved.

https://github.com/golang/go/issues/46500#issuecomment-876721111 sketches out a fix. I'll re-upload the fix sketch CL too with this issue attached.

**Comment by aclements** [comment]
@mknyszek , I think your analysis in https://github.com/golang/go/issues/46500#issuecomment-872556305 is exactly right. `sweepLocker` covers the window while the span is locked for sweeping, but that window doesn't include the actual termination check (sweep list is empty), so we can still race.

Combining `sweepers` and `sweepDrained`, as you [proposed](https://github.com/golang/go/issues/46500#issuecomment-876721111) seems like a reasonable solution, though I haven't looked at your code draft yet. I will say that if you make `sweepDrained` the low bit, then you don't need as many CAS operations.
