### ISSUE TITLE
cmd/compile: internal compiler error while building targets for kubernetes with master go on ppc64le architechture

### ISSUE THREAD

**Issue by Rajalakshmi-Girish** [golang/go#45327]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +e6ac2df2b1 Thu Apr 1 05:43:24 2021 +0000 linux/ppc64le
</pre>

### Does this issue reproduce with the latest release?
No
### What operating system and processor architecture are you using (`go env`)?
Linux/ppc64le
### What did you do?
Building targets for kubernetes using the latest golang in master branch

  - Install golang from master branch of go
  -  git clone https://github.com/kubernetes/kubernetes
  - KUBE_BUILD_PLATFORMS=linux/ppc64le make cross

### What did you expect to see?
Kubernetes binaries build without error

### What did you see instead?
Below Compilation error:
```
[root@rajalakshmi-workspace kubernetes]# KUBE_BUILD_PLATFORMS=linux/ppc64le make cross
+++ [0401 08:18:56] Building go targets for linux/ppc64le:
    ./vendor/k8s.io/code-generator/cmd/prerelease-lifecycle-gen
Generating prerelease lifecycle code for 27 targets
+++ [0401 08:19:03] Building go targets for linux/ppc64le:
    ./vendor/k8s.io/code-generator/cmd/deepcopy-gen
Generating deepcopy code for 227 targets
+++ [0401 08:19:15] Building go targets for linux/ppc64le:
    ./vendor/k8s.io/code-generator/cmd/defaulter-gen
Generating defaulter code for 89 targets
+++ [0401 08:19:28] Building go targets for linux/ppc64le:
    ./vendor/k8s.io/code-generator/cmd/conversion-gen
Generating conversion code for 124 targets
+++ [0401 08:19:56] Building go targets for linux/ppc64le:
    ./vendor/k8s.io/kube-openapi/cmd/openapi-gen
Generating openapi code for KUBE
Generating openapi code for AGGREGATOR
Generating openapi code for APIEXTENSIONS
Generating openapi code for CODEGEN
Generating openapi code for SAMPLEAPISERVER
+++ [0401 08:20:17] Building go targets for linux/ppc64le:
    ./vendor/github.com/go-bindata/go-bindata/go-bindata
+++ [0401 08:20:19] Building go targets for linux/ppc64le:
    cmd/kube-proxy
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/kubelet
    cmd/kubeadm
    cmd/kube-scheduler
    vendor/k8s.io/kube-aggregator
    vendor/k8s.io/apiextensions-apiserver
    cluster/gce/gci/mounter
# k8s.io/kubernetes/vendor/google.golang.org/grpc/balancer/roundrobin
vendor/google.golang.org/grpc/balancer/roundrobin/roundrobin.go:48:15: internal compiler error: '(*rrPickerBuilder).Build': not lowered: v154, Store SSA PTR STRUCT SSA

goroutine 35 [running]:
runtime/debug.Stack(0xadae38, 0xc00000e018, 0x0)
        /root/go/src/runtime/debug/stack.go:24 +0x8c
cmd/compile/internal/base.FatalfAt(0x300f000000002, 0xc0004d3d78, 0x8, 0xc000498d20, 0x2, 0x2)
        /root/go/src/cmd/compile/internal/base/print.go:227 +0x1d4
cmd/compile/internal/base.Fatalf(...)
        /root/go/src/cmd/compile/internal/base/print.go:196
cmd/compile/internal/ssagen.(*ssafn).Fatalf(0xc000473c80, 0x300f000000002, 0x9734a3, 0x2, 0xc000480ac0, 0x1, 0x1)
        /root/go/src/cmd/compile/internal/ssagen/ssa.go:7356 +0x1bc
cmd/compile/internal/ssa.(*Func).Fatalf(...)
        /root/go/src/cmd/compile/internal/ssa/func.go:656
cmd/compile/internal/ssa.checkLower(0xc0003e76c0)
        /root/go/src/cmd/compile/internal/ssa/lower.go:41 +0x39c
cmd/compile/internal/ssa.Compile(0xc0003e76c0)
        /root/go/src/cmd/compile/internal/ssa/compile.go:96 +0xafc
cmd/compile/internal/ssagen.buildssa(0xc0000de580, 0x0, 0x0)
        /root/go/src/cmd/compile/internal/ssagen/ssa.go:638 +0x1548
cmd/compile/internal/ssagen.Compile(0xc0000de580, 0x0)
        /root/go/src/cmd/compile/internal/ssagen/pgen.go:151 +0x44
cmd/compile/internal/gc.compileFunctions.func2.1(0xc00017a000, 0xc0000de580, 0xc000132358, 0xc00012a264)
        /root/go/src/cmd/compile/internal/gc/compile.go:130 +0x50
created by cmd/compile/internal/gc.compileFunctions.func2
        /root/go/src/cmd/compile/internal/gc/compile.go:128 +0x80

# k8s.io/kubernetes/vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2017-05-10/resources
vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2017-05-10/resources/deployments.go:800:22: internal compiler error: 'DeploymentsClient.Validate': not lowered: v418, Store SSA PTR STRUCT SSA

goroutine 93 [running]:
runtime/debug.Stack(0xadae38, 0xc00000e018, 0x0)
        /root/go/src/runtime/debug/stack.go:24 +0x8c
cmd/compile/internal/base.FatalfAt(0x32016100000004, 0xc001f2dd78, 0x8, 0xc0003c4260, 0x2, 0x2)
        /root/go/src/cmd/compile/internal/base/print.go:227 +0x1d4
cmd/compile/internal/base.Fatalf(...)
        /root/go/src/cmd/compile/internal/base/print.go:196
cmd/compile/internal/ssagen.(*ssafn).Fatalf(0xc001e96c90, 0x32016100000004, 0x9734a3, 0x2, 0xc000bf8c70, 0x1, 0x1)
        /root/go/src/cmd/compile/internal/ssagen/ssa.go:7356 +0x1bc
cmd/compile/internal/ssa.(*Func).Fatalf(...)
        /root/go/src/cmd/compile/internal/ssa/func.go:656
cmd/compile/internal/ssa.checkLower(0xc001e5e9c0)
        /root/go/src/cmd/compile/internal/ssa/lower.go:41 +0x39c
cmd/compile/internal/ssa.Compile(0xc001e5e9c0)
        /root/go/src/cmd/compile/internal/ssa/compile.go:96 +0xafc
cmd/compile/internal/ssagen.buildssa(0xc0000ddce0, 0x3, 0x0)
        /root/go/src/cmd/compile/internal/ssagen/ssa.go:638 +0x1548
cmd/compile/internal/ssagen.Compile(0xc0000ddce0, 0x3)
        /root/go/src/cmd/compile/internal/ssagen/pgen.go:151 +0x44
cmd/compile/internal/gc.compileFunctions.func2.1(0xc0013a8d00, 0xc0000ddce0, 0xc001479110, 0xc0003d67a0)
        /root/go/src/cmd/compile/internal/gc/compile.go:130 +0x50
created by cmd/compile/internal/gc.compileFunctions.func2
        /root/go/src/cmd/compile/internal/gc/compile.go:128 +0x80

# k8s.io/kubernetes/vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2019-06-01/storage
vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2019-06-01/storage/accounts.go:1024:22: internal compiler error: 'AccountsClient.RegenerateKey': not lowered: v378, Store SSA PTR STRUCT SSA

goroutine 151 [running]:
runtime/debug.Stack(0xadae38, 0xc000140008, 0x0)
        /root/go/src/runtime/debug/stack.go:24 +0x8c
cmd/compile/internal/base.FatalfAt(0x40016100000002, 0xc004055d78, 0x8, 0xc003ce04c0, 0x2, 0x2)
        /root/go/src/cmd/compile/internal/base/print.go:227 +0x1d4
cmd/compile/internal/base.Fatalf(...)
        /root/go/src/cmd/compile/internal/base/print.go:196
cmd/compile/internal/ssagen.(*ssafn).Fatalf(0xc00418b020, 0x40016100000002, 0x9734a3, 0x2, 0xc001a910d0, 0x1, 0x1)
        /root/go/src/cmd/compile/internal/ssagen/ssa.go:7356 +0x1bc
cmd/compile/internal/ssa.(*Func).Fatalf(...)
        /root/go/src/cmd/compile/internal/ssa/func.go:656
cmd/compile/internal/ssa.checkLower(0xc003cee340)
        /root/go/src/cmd/compile/internal/ssa/lower.go:41 +0x39c
cmd/compile/internal/ssa.Compile(0xc003cee340)
        /root/go/src/cmd/compile/internal/ssa/compile.go:96 +0xafc
cmd/compile/internal/ssagen.buildssa(0xc0008e42c0, 0x2, 0x0)
        /root/go/src/cmd/compile/internal/ssagen/ssa.go:638 +0x1548
cmd/compile/internal/ssagen.Compile(0xc0008e42c0, 0x2)
        /root/go/src/cmd/compile/internal/ssagen/pgen.go:151 +0x44
cmd/compile/internal/gc.compileFunctions.func2.1(0xc000be7880, 0xc0008e42c0, 0xc0006bc8f8, 0xc000741d80)
        /root/go/src/cmd/compile/internal/gc/compile.go:130 +0x50
created by cmd/compile/internal/gc.compileFunctions.func2
        /root/go/src/cmd/compile/internal/gc/compile.go:128 +0x80

# k8s.io/kubernetes/vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-12-01/compute
vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-12-01/compute/virtualmachinescalesets.go:390:22: internal compiler error: 'VirtualMachineScaleSetsClient.DeleteInstances': not lowered: v96, Store SSA PTR STRUCT SSA

goroutine 620 [running]:
runtime/debug.Stack(0xadae38, 0xc00000e018, 0x0)
        /root/go/src/runtime/debug/stack.go:24 +0x8c
cmd/compile/internal/base.FatalfAt(0x1861610000001f, 0xc00624fd78, 0x8, 0xc000686540, 0x2, 0x2)
        /root/go/src/cmd/compile/internal/base/print.go:227 +0x1d4
cmd/compile/internal/base.Fatalf(...)
        /root/go/src/cmd/compile/internal/base/print.go:196
cmd/compile/internal/ssagen.(*ssafn).Fatalf(0xc006236180, 0x1861610000001f, 0x9734a3, 0x2, 0xc00089a0b0, 0x1, 0x1)
        /root/go/src/cmd/compile/internal/ssagen/ssa.go:7356 +0x1bc
cmd/compile/internal/ssa.(*Func).Fatalf(...)
        /root/go/src/cmd/compile/internal/ssa/func.go:656
cmd/compile/internal/ssa.checkLower(0xc006110b60)
        /root/go/src/cmd/compile/internal/ssa/lower.go:41 +0x39c
cmd/compile/internal/ssa.Compile(0xc006110b60)
        /root/go/src/cmd/compile/internal/ssa/compile.go:96 +0xafc
cmd/compile/internal/ssagen.buildssa(0xc0014eef20, 0x1, 0x0)
        /root/go/src/cmd/compile/internal/ssagen/ssa.go:638 +0x1548
cmd/compile/internal/ssagen.Compile(0xc0014eef20, 0x1)
        /root/go/src/cmd/compile/internal/ssagen/pgen.go:151 +0x44
cmd/compile/internal/gc.compileFunctions.func2.1(0xc003e0b880, 0xc0014eef20, 0xc003f49420, 0xc0008ebdc0)
        /root/go/src/cmd/compile/internal/gc/compile.go:130 +0x50
created by cmd/compile/internal/gc.compileFunctions.func2
        /root/go/src/cmd/compile/internal/gc/compile.go:128 +0x80

# k8s.io/kubernetes/vendor/github.com/Azure/azure-sdk-for-go/services/network/mgmt/2019-06-01/network
vendor/github.com/Azure/azure-sdk-for-go/services/network/mgmt/2019-06-01/network/watchers.go:969:22: internal compiler error: 'WatchersClient.GetVMSecurityRules': not lowered: v96, Store SSA PTR STRUCT SSA

goroutine 1312 [running]:
runtime/debug.Stack(0xadae38, 0xc0001a6008, 0x0)
        /root/go/src/runtime/debug/stack.go:24 +0x8c
cmd/compile/internal/base.FatalfAt(0x3c916100000055, 0xc00a89dd78, 0x8, 0xc000ac99c0, 0x2, 0x2)
        /root/go/src/cmd/compile/internal/base/print.go:227 +0x1d4
cmd/compile/internal/base.Fatalf(...)
        /root/go/src/cmd/compile/internal/base/print.go:196
cmd/compile/internal/ssagen.(*ssafn).Fatalf(0xc00a72be90, 0x3c916100000055, 0x9734a3, 0x2, 0xc0017d3920, 0x1, 0x1)
        /root/go/src/cmd/compile/internal/ssagen/ssa.go:7356 +0x1bc
cmd/compile/internal/ssa.(*Func).Fatalf(...)
        /root/go/src/cmd/compile/internal/ssa/func.go:656
cmd/compile/internal/ssa.checkLower(0xc00bbdd040)
        /root/go/src/cmd/compile/internal/ssa/lower.go:41 +0x39c
cmd/compile/internal/ssa.Compile(0xc00bbdd040)
        /root/go/src/cmd/compile/internal/ssa/compile.go:96 +0xafc
cmd/compile/internal/ssagen.buildssa(0xc002bd66e0, 0x1, 0x0)
        /root/go/src/cmd/compile/internal/ssagen/ssa.go:638 +0x1548
cmd/compile/internal/ssagen.Compile(0xc002bd66e0, 0x1)
        /root/go/src/cmd/compile/internal/ssagen/pgen.go:151 +0x44
cmd/compile/internal/gc.compileFunctions.func2.1(0xc00464f000, 0xc002bd66e0, 0xc004aa0550, 0xc0008b35b0)
        /root/go/src/cmd/compile/internal/gc/compile.go:130 +0x50
created by cmd/compile/internal/gc.compileFunctions.func2
        /root/go/src/cmd/compile/internal/gc/compile.go:128 +0x80

!!! [0401 08:23:06] Call tree:
!!! [0401 08:23:06]  1: /root/kubernetes/hack/lib/golang.sh:715 kube::golang::build_some_binaries(...)
!!! [0401 08:23:06]  2: /root/kubernetes/hack/lib/golang.sh:870 kube::golang::build_binaries_for_platform(...)
!!! [0401 08:23:06]  3: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0401 08:23:06] Call tree:
!!! [0401 08:23:06]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0401 08:23:06] Call tree:
!!! [0401 08:23:06]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
make[1]: *** [Makefile:92: all] Error 1
make: *** [Makefile:512: cross] Error 1
[root@rajalakshmi-workspace kubernetes]#
```

**Comment by laboger** [comment]
I believe this is fixed with https://go-review.googlesource.com/c/go/+/282315 or something similar.

**Comment by Rajalakshmi-Girish** [comment]
Similar issue 
https://github.com/golang/go/issues/43551

**Comment by Rajalakshmi-Girish** [comment]
> 
> 
> I believe this is fixed with https://go-review.googlesource.com/c/go/+/282315 or something similar.

Yes seems to have fixed. I dont see the error now.

**Comment by dr2chase** [comment]
Thanks for checking.
