### ISSUE TITLE
[dev.typeparams]: internal compiler error: Nil type for v

### ISSUE THREAD

**Issue by JAicewizard** [golang/go#46472]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.17-f32f4f58d9 Mon May 31 03:22:58 2021 +0000 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jaap/.cache/go-build"
GOENV="/home/jaap/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/jaap/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jaap/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/jaap/Projects/goroot"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/jaap/Projects/goroot/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel go1.17-f32f4f58d9 Mon May 31 03:22:58 2021 +0000"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/jaap/Projects/tt/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2903782367=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

main.go
```
package main

import (
	"fmt"
)

func foo[T any](d T) {
	switch v := interface{}(d).(type) {
	case string:
		fmt.Println(v=="x")
	}

}
func main() {
	foo("x")
}
```

go run -gcflags='-G=3' main.go

### What did you expect to see?
```
True
```

### What did you see instead?
<details><summary>stacktrace</summary><br><pre>
```
# command-line-arguments
<unknown line number>: internal compiler error: Nil type for v

goroutine 1 [running]:
runtime/debug.Stack()
        /home/jaap/Projects/goroot/src/runtime/debug/stack.go:24 +0x65
cmd/compile/internal/base.FatalfAt({0xcf2924, 0x0}, {0xc0000285f0, 0xe}, {0x0, 0x0, 0x0})
        /home/jaap/Projects/goroot/src/cmd/compile/internal/base/print.go:227 +0x154
cmd/compile/internal/base.Fatalf(...)
        /home/jaap/Projects/goroot/src/cmd/compile/internal/base/print.go:196
cmd/compile/internal/noder.(*subster).node.func1({0xe531e0, 0xc0003b26c0})
        /home/jaap/Projects/goroot/src/cmd/compile/internal/noder/stencil.go:369 +0x279
cmd/compile/internal/ir.(*TypeSwitchGuard).editChildren(0xc00039d590, 0xc00000cac8)
        /home/jaap/Projects/goroot/src/cmd/compile/internal/ir/node_gen.go:1334 +0x3d
cmd/compile/internal/ir.EditChildren(...)
        /home/jaap/Projects/goroot/src/cmd/compile/internal/ir/visit.go:185
cmd/compile/internal/noder.(*subster).node.func1({0xe54ba8, 0xc00039d380})
        /home/jaap/Projects/goroot/src/cmd/compile/internal/noder/stencil.go:375 +0x30f
cmd/compile/internal/ir.(*SwitchStmt).editChildren(0xc0000f8480, 0xc00000cac8)
        /home/jaap/Projects/goroot/src/cmd/compile/internal/ir/node_gen.go:1262 +0x58
cmd/compile/internal/ir.EditChildren(...)
        /home/jaap/Projects/goroot/src/cmd/compile/internal/ir/visit.go:185
cmd/compile/internal/noder.(*subster).node.func1({0xe54950, 0xc0000f8400})
        /home/jaap/Projects/goroot/src/cmd/compile/internal/noder/stencil.go:375 +0x30f
cmd/compile/internal/noder.(*subster).node(0xc0003ad590, {0xe54950, 0xc0000f8400})
        /home/jaap/Projects/goroot/src/cmd/compile/internal/noder/stencil.go:541 +0xa5
cmd/compile/internal/noder.(*subster).list(0x13a6248, {0xc0003a45e0, 0x1, 0xc0000c4550})
        /home/jaap/Projects/goroot/src/cmd/compile/internal/noder/stencil.go:561 +0x8e
cmd/compile/internal/noder.(*irgen).genericSubst(0xc000324990, 0xc0003ad540, 0xc000373790, {0xc0000ba2d0, 0x1, 0x1}, 0x0)
        /home/jaap/Projects/goroot/src/cmd/compile/internal/noder/stencil.go:312 +0x7a5
cmd/compile/internal/noder.(*irgen).getInstantiation(0xc000324990, 0xc000373790, {0xc0000ba2d0, 0x1, 0x1}, 0x8)
        /home/jaap/Projects/goroot/src/cmd/compile/internal/noder/stencil.go:219 +0x1cf
cmd/compile/internal/noder.(*irgen).getInstantiationForNode(0xc00037d860, 0xc00037d860)
        /home/jaap/Projects/goroot/src/cmd/compile/internal/noder/stencil.go:197 +0xe5
cmd/compile/internal/noder.(*irgen).stencil.func1({0xe527b8, 0xc000324ea0})
        /home/jaap/Projects/goroot/src/cmd/compile/internal/noder/stencil.go:89 +0xda
cmd/compile/internal/ir.Visit.func1({0xe527b8, 0xc000324ea0})
        /home/jaap/Projects/goroot/src/cmd/compile/internal/ir/visit.go:105 +0x30
cmd/compile/internal/ir.doNodes({0xc0003a4630, 0x1, 0xc0000285bb}, 0xc00000ca98)
        /home/jaap/Projects/goroot/src/cmd/compile/internal/ir/node_gen.go:1456 +0x67
cmd/compile/internal/ir.(*Func).doChildren(0xe52f88, 0xc0003a6580)
        /home/jaap/Projects/goroot/src/cmd/compile/internal/ir/func.go:151 +0x2e
cmd/compile/internal/ir.DoChildren(...)
        /home/jaap/Projects/goroot/src/cmd/compile/internal/ir/visit.go:94
cmd/compile/internal/ir.Visit.func1({0xe52f88, 0xc0003a6580})
        /home/jaap/Projects/goroot/src/cmd/compile/internal/ir/visit.go:106 +0x57
cmd/compile/internal/ir.Visit({0xe52f88, 0xc0003a6580}, 0xc0003b05a0)
        /home/jaap/Projects/goroot/src/cmd/compile/internal/ir/visit.go:108 +0xb8
cmd/compile/internal/noder.(*irgen).stencil(0xc000324990)
        /home/jaap/Projects/goroot/src/cmd/compile/internal/noder/stencil.go:74 +0x1a5
cmd/compile/internal/noder.(*irgen).generate(0xc000324990, {0xc00009a820, 0x2, 0xc0003a4090})
        /home/jaap/Projects/goroot/src/cmd/compile/internal/noder/irgen.go:185 +0x26c
cmd/compile/internal/noder.check2({0xc00009a820, 0x0, 0x2})
        /home/jaap/Projects/goroot/src/cmd/compile/internal/noder/irgen.go:78 +0x5da
cmd/compile/internal/noder.LoadPackage({0xc0000c0120, 0x2, 0x0})
        /home/jaap/Projects/goroot/src/cmd/compile/internal/noder/noder.go:80 +0x30b
cmd/compile/internal/gc.Main(0xd1ab98)
        /home/jaap/Projects/goroot/src/cmd/compile/internal/gc/main.go:192 +0xb35
main.main()
        /home/jaap/Projects/goroot/src/cmd/compile/main.go:55 +0xdd

```
</pre></details>

**Comment by JAicewizard** [comment]
This seems to be fixed, thanks for the super fast patch. Works for me as well!

**Comment by mdempsky** [comment]
The CL hasn't been submitted yet.

**Comment by JAicewizard** [comment]
oh I thought it was marked as merged. sorry!

**Comment by dr2chase** [comment]
I think this is fixed now, so I'll close the bug.
