### ISSUE TITLE
x/build/cmd/tip: needs updating after recent x/website/cmd/golangorg changes

### ISSUE THREAD

**Issue by dmitshur** [golang/go#46775]
From https://farmer.golang.org/#health (thanks @cagedmantis for reporting):

> - [tip.golang.org website](https://farmer.golang.org/status/tip) [[docs](https://github.com/golang/build/tree/master/cmd/tip)]:
>   - _tipstatus page reports error: waitReady: timed out waiting for process at localhost:8082: Get http://localhost:8082/pkg/fmt: dial tcp 127.0.0.1:8082: connect: connection refused

The problem is that x/build/cmd/tip has become incompatible with the latest version of x/website/cmd/golangorg. More specifically, [CL 323891](https://golang.org/cl/323891) made a change to how website content is found:

```diff
-var Content = subdir(embedded, "_content")
+var Content = findContent()
```

The new version doesn't work with how `tip` calls `golangorg`, causing the new version not to start up:

```
go=219fe9d5/website=91e49064: 2021/06/15 18:46:36 starting golangorg ...
go=219fe9d5/website=91e49064: 2021/06/15 18:46:36 panic: cannot find _content

goroutine 1 [running]:
go=219fe9d5/website=91e49064: 2021/06/15 18:46:36 golang.org/x/website.findContent()
	/build/tip/b/website/content.go:32 +0xc5
golang.org/x/website.init()
	/build/tip/b/website/content.go:16 +0x17
go=219fe9d5/website=91e49064: 2021/06/15 18:46:36 process in /build/tip/b exited: exit status 2 (*exec.ExitError)
go=219fe9d5/website=91e49064: 2021/06/15 18:46:36 ProcessState.Sys() = 512
```

This should be easy to fix, but it's worth thinking about what change is more likely to keep working as further x/website CLs continue to land.

CC @golang/release, @rsc.

**Comment by dmitshur** [comment]
I think the fix is to set `golangorg.Dir` to `websiteDir` (the root of x/website repo checkout), so the `golangorg` process starts in a directory where it finds _content.

We can also preemptively change the health check from "http://%v/pkg/fmt" to something that will still return 200 OK after [CL 327849](https://golang.org/cl/327849), like "http://%v/src/fmt".
