### ISSUE TITLE
cmd/link:  panic: runtime error: makeslice: cap out of range

### ISSUE THREAD

**Issue by RaynorGu** [golang/go#47455]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/raynor/.cache/go-build"
GOENV="/home/raynor/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/raynor/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/raynor/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.6"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/raynor/git/go_shared_build/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1655817667=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
```
raynor@DESKTOP-7TTOU8H:~/git/go_shared_build$ go install -buildmode=shared -linkshared std
raynor@DESKTOP-7TTOU8H:~/git/go_shared_build$
raynor@DESKTOP-7TTOU8H:~/git/go_shared_build$ go install -buildmode=shared -linkshared shared/pkg0
# /tmp/go-build2695248807/b002/libshared-pkg0.so
panic: runtime error: makeslice: cap out of range

goroutine 1 [running]:
cmd/link/internal/loader.(*Loader).LoadSyms(0xc000700000, 0x87f340)
        /usr/local/go/src/cmd/link/internal/loader/loader.go:2188 +0x125
cmd/link/internal/ld.(*Link).loadlib(0xc00014e000)
        /usr/local/go/src/cmd/link/internal/ld/lib.go:558 +0x3de
cmd/link/internal/ld.Main(0x87f340, 0x20, 0x20, 0x1, 0x7, 0x10, 0x0, 0x0, 0x6e86a7, 0x1b, ...)
        /usr/local/go/src/cmd/link/internal/ld/main.go:244 +0xdbc
main.main()
        /usr/local/go/src/cmd/link/main.go:68 +0x258
raynor@DESKTOP-7TTOU8H:~/git/go_shared_build$ go list ./...
shared
shared/pkg0
shared/pkg1
raynor@DESKTOP-7TTOU8H:~/git/go_shared_build$ cat pkg0/pkg0.go
package pkg0

var (
  X int
  Y int
)

func Init() {
  X = 1
  Y = 2
}

```

### What did you expect to see?

```
raynor@DESKTOP-7TTOU8H:~/git/go_shared_build$ go install -buildmode=shared -linkshared shared/pkg0
# /tmp/go-build2695248807/b002/libshared-pkg0.so
panic: runtime error: makeslice: cap out of range

goroutine 1 [running]:
cmd/link/internal/loader.(*Loader).LoadSyms(0xc000700000, 0x87f340)
        /usr/local/go/src/cmd/link/internal/loader/loader.go:2188 +0x125
cmd/link/internal/ld.(*Link).loadlib(0xc00014e000)
        /usr/local/go/src/cmd/link/internal/ld/lib.go:558 +0x3de
cmd/link/internal/ld.Main(0x87f340, 0x20, 0x20, 0x1, 0x7, 0x10, 0x0, 0x0, 0x6e86a7, 0x1b, ...)
        /usr/local/go/src/cmd/link/internal/ld/main.go:244 +0xdbc
main.main()
        /usr/local/go/src/cmd/link/main.go:68 +0x258
```
### What did you see instead?
install success

**Comment by mengzhuo** [comment]
I can reproduce this issue.

It seems that 

https://github.com/golang/go/blob/b7a85e0003cedb1b48a1fd3ae5b746ec6330102e/src/cmd/link/internal/loader/loader.go#L2204-#L2210

passing `symSize == 0` which causing this issue.

@cherrymui

**Comment by grolfcry** [comment]
Close to https://github.com/golang/go/issues/47183 or similar

**Comment by alexanius** [comment]
Same issue with 1.18.3 version

**Comment by GouthamBanala** [comment]
Seeing issues on go version go1.20 linux/amd64

**Comment by logrusorgru** [comment]
> Obsoleted by #47788

Isn't it declined https://github.com/golang/go/issues/47788#issuecomment-959789543 ?

**Comment by cherrymui** [comment]
Per https://github.com/golang/go/issues/47788#issuecomment-954890659

> We've decided to leave -buildmode=shared alone (not delete it) for Go 1.18,
but it's not going to work any better than it does today.
In particular, we're not fixing any bugs in it anymore, ...

So it still applies. Thanks.

**Comment by logrusorgru** [comment]
It's about empty list
```diff
+	if len(l.objs) == goObjStart { // e.g. len(l.objs[goObjStart:]) == 0
+		return
+	}
	var symSize, hashedSize, hashed64Size int
	for _, o := range l.objs[goObjStart:] {
		symSize += o.r.ndef + o.r.nhasheddef/2 + o.r.nhashed64def/2 + o.r.NNonpkgdef()
		hashedSize += o.r.nhasheddef / 2
		hashed64Size += o.r.nhashed64def / 2
	}
	// Index 0 is invalid for symbols.
	l.objSyms = make([]objSym, 1, symSize)
```
I'm currently not sure it's correct, but it's work.
