### ISSUE TITLE
gccgo: building go 1.17 fails

### ISSUE THREAD

**Issue by dilyanpalauzov** [golang/go#47779]
Building go 1.17 fails.  The point is, that /usr/local/bin/go is `go 1.16.7 (not gcc)` and `$PATH` sets preference to `/usr/local/bin/go` over `/usr/bin/go` .  `/usr/bin/go` is gccgo 1.16.5, while `/usr/local/bin/go` is notgcc go 1.16.7.  But src/make.all does not honour `/usr/local/bin/go` .

```
d@d:/git/go/src release-branch.go1.17=$ ./all.bash         
Building Go cmd/dist using /usr. (go1.16.5 gccgo (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1) linux/amd64)
Building Go toolchain1 using /usr.                                             
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
/git/go/src/runtime/internal/sys/intrinsics_common.go:142:2: "".Ctz64: invalid instruction: 00049 (/git/go/src/runtime/internal/sys/intrinsics.go:44)   MOVQ C
X, "".~r1+16(DX)                                                               
/git/go/src/runtime/internal/sys/intrinsics_common.go:142:2: "".Ctz32: invalid instruction: 00042 (/git/go/src/runtime/internal/sys/intrinsics.go:54)   MOVQ A
X, "".~r1+16(DX)                                                               
/git/go/src/runtime/internal/sys/intrinsics_common.go:142:2: "".Len64: invalid instruction: 00105 (/git/go/src/runtime/internal/sys/intrinsics_common.go:61) M
OVQ     DX, "".n+40(CX)                                                        
/git/go/src/runtime/internal/sys/intrinsics_common.go:142:2: "".LeadingZeros64: invalid instruction: 00027 (/git/go/src/runtime/internal/sys/intrinsics_common
.go:130)        MOVQ    CX, "".~r1+16(AX)
                                                                               
go tool dist: FAILED: /git/go/pkg/tool/linux_amd64/compile -std -pack -o /tmp/go-tool-dist-064036409/runtime/internal/sys/_go_.a -p runtime/internal/sys -impo
rtcfg /tmp/go-tool-dist-064036409/runtime/internal/sys/importcfg /git/go/src/runtime/internal/sys/arch.go /git/go/src/runtime/internal/sys/arch_amd64.go /git/
go/src/runtime/internal/sys/intrinsics.go /git/go/src/runtime/internal/sys/intrinsics_common.go /git/go/src/runtime/internal/sys/sys.go /git/go/src/runtime/in
ternal/sys/zgoarch_amd64.go /git/go/src/runtime/internal/sys/zgoos_linux.go /git/go/src/runtime/internal/sys/zversion.go: exit status 2
go tool dist: open /tmp/go-tool-dist-064036409/runtime/internal/sys/_go_.a: no such file or directory
go tool dist: open /tmp/go-tool-dist-064036409/internal/cpu/_go_.a: no such file or directory
go tool dist: open /tmp/go-tool-dist-064036409/runtime/internal/atomic/_go_.a: no such file or directory                                                      /git/go/src/internal/cpu/cpu_x86.go:46:17: internal compiler error: 'doinit': panic during regalloc while compiling doinit:                                                                                                                                                                                                 
interface conversion: ssa.Location is nil, not *        bootstrap_1cmd_1compile_1internal_1ssa  ssa.Register
                                                                               
goroutine 1 [running]:                                                         
bootstrap/cmd/compile/internal/ssa.Compile..func1                      
        /git/go/src/cmd/compile/internal/ssa/compile.go:44         
panic                                                                          
        ../../../libgo/go/runtime/panic.go:708                     
bootstrap_1cmd_1compile_1internal_1ssa.regAllocState.regalloc       
        /git/go/src/cmd/compile/internal/ssa/regalloc.go:1578       
bootstrap/cmd/compile/internal/ssa.regalloc                             
        /git/go/src/cmd/compile/internal/ssa/regalloc.go:148                 
bootstrap_1cmd_1compile_1internal_1ssa.Compile    
        /git/go/src/cmd/compile/internal/ssa/compile.go:96
bootstrap/cmd/compile/internal/ssagen.buildssa
        /git/go/src/cmd/compile/internal/ssagen/ssa.go:642
bootstrap_1cmd_1compile_1internal_1ssagen.Compile
        /git/go/src/cmd/compile/internal/ssagen/pgen.go:165
bootstrap/cmd/compile/internal/gc.compileFunctions..func6
        /git/go/src/cmd/compile/internal/gc/compile.go:153
bootstrap/cmd/compile/internal/gc.compileFunctions..func2
        /git/go/src/cmd/compile/internal/gc/compile.go:125
bootstrap/cmd/compile/internal/gc.compileFunctions..func5
        /git/go/src/cmd/compile/internal/gc/compile.go:152
bootstrap/cmd/compile/internal/gc.compileFunctions
        /git/go/src/cmd/compile/internal/gc/compile.go:163
bootstrap_1cmd_1compile_1internal_1gc.Main
        /git/go/src/cmd/compile/internal/gc/main.go:287
main.main
        /git/go/src/cmd/compile/main.go:55



Please file a bug report including a short program that triggers the error.
https://golang.org/issue/new

go tool dist: FAILED: /git/go/pkg/tool/linux_amd64/compile -std -pack -o /tmp/go-tool-dist-064036409/internal/cpu/_go_.a -p internal/cpu -importcfg /tmp/go-to
ol-dist-064036409/internal/cpu/importcfg -asmhdr /tmp/go-tool-dist-064036409/internal/cpu/go_asm.h -symabis /tmp/go-tool-dist-064036409/internal/cpu/symabis /
git/go/src/internal/cpu/cpu.go /git/go/src/internal/cpu/cpu_amd64.go /git/go/src/internal/cpu/cpu_x86.go: exit status 2

d@d:/git/go/src release-branch.go1.17=$ go version
go version go1.16.7 linux/amd64
d@d:/git/go/src release-branch.go1.17=$ which go
/usr/local/bin/go
d@d:/git/go/src release-branch.go1.17=$ /usr/local/bin/go version
go version go1.16.7 linux/amd64
d@d:/git/go/src release-branch.go1.17=$ 
```

**Comment by cherrymui** [comment]
If you want to bootstrap with a specific toolchain, you may want to set GOROOT_BOOTSTRAP environment variable to point to it.

**Comment by ianlancetaylor** [comment]
Pretty sure the bootstrap failure starting with gccgo is a dup of #47771, so closing.  Please comment if you disagree.
