### ISSUE TITLE
gccgo: bootstrap with gccgo fails

### ISSUE THREAD

**Issue by stevenpackardblp** [golang/go#47771]
### What version of Go are you using (`go version`)?

Compiling 1.17 release source code using GCC 9.3 gccgo.

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

linux amd64

### What did you do?

Attempting to build the 1.17 release using GCC 9.3 gccgo fails with:

```console
cd src && \
    GOOS=linux GOARCH=amd64 \
    GOROOT=/tmp/go-1.17 \
    GOROOT_FINAL=/opt/lib/go-1.17 \
    GOROOT_BOOTSTRAP=/opt/lib/go \
    GCCGO=gccgo \
    ./make.bash
Building Go cmd/dist using /opt/lib/go. (go1.12.2 gccgo (9.3.0-2+b20210731T06443745) 9.3.0 linux/amd64)
Building Go toolchain1 using /opt/lib/go.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=1 addr=0 pc=6238351]

goroutine 1 [running]:
types.fieldsHasTParam
	/tmp/go-1.17/src/cmd/compile/internal/types/type.go:1734
bootstrap..z2fcmd..z2fcompile..z2finternal..z2ftypes.NewSignature
	/tmp/go-1.17/src/cmd/compile/internal/types/type.go:1816
typecheck.tcFuncType
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/type.go:91
typecheck.typecheck1
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/typecheck.go:572
typecheck.typecheck
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/typecheck.go:373
typecheck.typecheckNtype
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/typecheck.go:269
typecheck.typecheckdef
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/typecheck.go:1870
typecheck.typecheck1
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/typecheck.go:480
typecheck.typecheck
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/typecheck.go:373
bootstrap..z2fcmd..z2fcompile..z2finternal..z2ftypecheck.AssignExpr
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/typecheck.go:31
typecheck.tcFunc
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/func.go:374
typecheck.typecheck1
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/typecheck.go:903
typecheck.typecheck
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/typecheck.go:373
bootstrap..z2fcmd..z2fcompile..z2finternal..z2ftypecheck.Stmt
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/typecheck.go:33
bootstrap..z2fcmd..z2fcompile..z2finternal..z2fnoder.LoadPackage
	/tmp/go-1.17/src/cmd/compile/internal/noder/noder.go:118
bootstrap..z2fcmd..z2fcompile..z2finternal..z2fgc.Main
	/tmp/go-1.17/src/cmd/compile/internal/gc/main.go:192
main.main
	/tmp/go-1.17/src/cmd/compile/main.go:55

go tool dist: FAILED: /tmp/go-1.17/pkg/tool/linux_amd64/compile -std -pack -o /tmp/go-tool-dist-828520844/runtime/internal/sys/_go_.a -p runtime/internal/sys -importcfg /tmp/go-tool-dist-828520844/runtime/internal/sys/importcfg /tmp/go-1.17/src/runtime/internal/sys/arch.go /tmp/go-1.17/src/runtime/internal/sys/arch_amd64.go /tmp/go-1.17/src/runtime/internal/sys/intrinsics.go /tmp/go-1.17/src/runtime/internal/sys/intrinsics_common.go /tmp/go-1.17/src/runtime/internal/sys/sys.go /tmp/go-1.17/src/runtime/internal/sys/zgoarch_amd64.go /tmp/go-1.17/src/runtime/internal/sys/zgoos_linux.go /tmp/go-1.17/src/runtime/internal/sys/zversion.go: exit status 2
go tool dist: open /tmp/go-tool-dist-828520844/internal/goexperiment/_go_.a: no such file or directory
go tool dist: open /tmp/go-tool-dist-828520844/runtime/internal/sys/_go_.a: no such file or directory
go tool dist: open /tmp/go-tool-dist-828520844/internal/cpu/_go_.a: no such file or directory
go tool dist: open /tmp/go-tool-dist-828520844/runtime/internal/atomic/_go_.a: no such file or directory
go tool dist: open /tmp/go-tool-dist-828520844/internal/abi/_go_.a: no such file or directory
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=1 addr=0 pc=6238351]

goroutine 1 [running]:
types.fieldsHasTParam
	/tmp/go-1.17/src/cmd/compile/internal/types/type.go:1734
bootstrap..z2fcmd..z2fcompile..z2finternal..z2ftypes.NewSignature
	/tmp/go-1.17/src/cmd/compile/internal/types/type.go:1816
typecheck.newSig
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/builtin.go:215
typecheck.runtimeTypes
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/builtin.go:232
bootstrap..z2fcmd..z2fcompile..z2finternal..z2ftypecheck.InitRuntime
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/syms.go:72
bootstrap..z2fcmd..z2fcompile..z2finternal..z2fgc.Main
	/tmp/go-1.17/src/cmd/compile/internal/gc/main.go:266
main.main
	/tmp/go-1.17/src/cmd/compile/main.go:55

go tool dist: FAILED: /tmp/go-1.17/pkg/tool/linux_amd64/compile -std -pack -o /tmp/go-tool-dist-828520844/internal/goexperiment/_go_.a -p internal/goexperiment -importcfg /tmp/go-tool-dist-828520844/internal/goexperiment/importcfg /tmp/go-1.17/src/internal/goexperiment/exp_fieldtrack_off.go /tmp/go-1.17/src/internal/goexperiment/exp_preemptibleloops_off.go /tmp/go-1.17/src/internal/goexperiment/exp_regabi_off.go /tmp/go-1.17/src/internal/goexperiment/exp_regabiargs_off.go /tmp/go-1.17/src/internal/goexperiment/exp_regabidefer_off.go /tmp/go-1.17/src/internal/goexperiment/exp_regabig_off.go /tmp/go-1.17/src/internal/goexperiment/exp_regabireflect_off.go /tmp/go-1.17/src/internal/goexperiment/exp_regabiwrappers_off.go /tmp/go-1.17/src/internal/goexperiment/exp_staticlockranking_off.go /tmp/go-1.17/src/internal/goexperiment/flags.go: exit status 2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=1 addr=0 pc=6238351]

goroutine 1 [running]:
types.fieldsHasTParam
	/tmp/go-1.17/src/cmd/compile/internal/types/type.go:1734
bootstrap..z2fcmd..z2fcompile..z2finternal..z2ftypes.NewSignature
	/tmp/go-1.17/src/cmd/compile/internal/types/type.go:1816
typecheck.tcFuncType
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/type.go:91
typecheck.typecheck1
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/typecheck.go:572
typecheck.typecheck
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/typecheck.go:373
typecheck.typecheckNtype
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/typecheck.go:269
typecheck.typecheckdef
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/typecheck.go:1870
typecheck.typecheck1
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/typecheck.go:480
typecheck.typecheck
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/typecheck.go:373
bootstrap..z2fcmd..z2fcompile..z2finternal..z2ftypecheck.AssignExpr
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/typecheck.go:31
typecheck.tcFunc
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/func.go:374
typecheck.typecheck1
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/typecheck.go:903
typecheck.typecheck
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/typecheck.go:373
bootstrap..z2fcmd..z2fcompile..z2finternal..z2ftypecheck.Stmt
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/typecheck.go:33
bootstrap..z2fcmd..z2fcompile..z2finternal..z2fnoder.LoadPackage
	/tmp/go-1.17/src/cmd/compile/internal/noder/noder.go:118
bootstrap..z2fcmd..z2fcompile..z2finternal..z2fgc.Main
	/tmp/go-1.17/src/cmd/compile/internal/gc/main.go:192
main.main
	/tmp/go-1.17/src/cmd/compile/main.go:55

go tool dist: FAILED: /tmp/go-1.17/pkg/tool/linux_amd64/compile -std -pack -o /tmp/go-tool-dist-828520844/internal/cpu/_go_.a -p internal/cpu -importcfg /tmp/go-tool-dist-828520844/internal/cpu/importcfg -asmhdr /tmp/go-tool-dist-828520844/internal/cpu/go_asm.h -symabis /tmp/go-tool-dist-828520844/internal/cpu/symabis /tmp/go-1.17/src/internal/cpu/cpu.go /tmp/go-1.17/src/internal/cpu/cpu_amd64.go /tmp/go-1.17/src/internal/cpu/cpu_x86.go: exit status 2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=1 addr=0 pc=6238351]

goroutine 1 [running]:
types.fieldsHasTParam
	/tmp/go-1.17/src/cmd/compile/internal/types/type.go:1734
bootstrap..z2fcmd..z2fcompile..z2finternal..z2ftypes.NewSignature
	/tmp/go-1.17/src/cmd/compile/internal/types/type.go:1816
typecheck.tcFuncType
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/type.go:91
typecheck.typecheck1
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/typecheck.go:572
typecheck.typecheck
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/typecheck.go:373
typecheck.typecheckNtype
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/typecheck.go:269
typecheck.typecheckdef
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/typecheck.go:1870
typecheck.typecheck1
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/typecheck.go:480
typecheck.typecheck
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/typecheck.go:373
bootstrap..z2fcmd..z2fcompile..z2finternal..z2ftypecheck.AssignExpr
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/typecheck.go:31
typecheck.tcFunc
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/func.go:374
typecheck.typecheck1
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/typecheck.go:903
typecheck.typecheck
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/typecheck.go:373
bootstrap..z2fcmd..z2fcompile..z2finternal..z2ftypecheck.Stmt
	/tmp/go-1.17/src/cmd/compile/internal/typecheck/typecheck.go:33
bootstrap..z2fcmd..z2fcompile..z2finternal..z2fnoder.LoadPackage
	/tmp/go-1.17/src/cmd/compile/internal/noder/noder.go:118
bootstrap..z2fcmd..z2fcompile..z2finternal..z2fgc.Main
	/tmp/go-1.17/src/cmd/compile/internal/gc/main.go:192
main.main
	/tmp/go-1.17/src/cmd/compile/main.go:55

go tool dist: FAILED: /tmp/go-1.17/pkg/tool/linux_amd64/compile -std -pack -o /tmp/go-tool-dist-828520844/internal/abi/_go_.a -p internal/abi -importcfg /tmp/go-tool-dist-828520844/internal/abi/importcfg /tmp/go-1.17/src/internal/abi/abi.go /tmp/go-1.17/src/internal/abi/abi_generic.go: exit status 2
```

### What did you expect to see?

Successful build.

### What did you see instead?

Failed build due to segmentation faults.

**Comment by mknyszek** [comment]
CC @ianlancetaylor @thanm via https://dev.golang.org/owners

**Comment by thanm** [comment]
Gccgo 9.3 corresponds to Go 1.12, which is well beyond the support window for Go (we only support the last 2 prior releases).

With that said, I also see a build failure when I try to use tip gccgo, albeit with a slightly different failure mode:

```
LD_LIBRARY_PATH=/ssd/gcc-trunk/cross/lib64 GOROOT_BOOTSTRAP=/ssd/gcc-trunk/cross  bash make.bash
Building Go cmd/dist using /ssd/gcc-trunk/cross. (unknown linux/amd64)
Building Go toolchain1 using /ssd/gcc-trunk/cross.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
/ssd2/go.master/src/runtime/internal/sys/intrinsics_common.go:142:2: "".Ctz64: invalid instruction: 00049 (/ssd2/go.master/src/runtime/internal/sys/intrinsics.go:44)	MOVQ	CX, "".~r1+16(DX)
/ssd2/go.master/src/runtime/internal/sys/intrinsics_common.go:142:2: "".Ctz32: invalid instruction: 00042 (/ssd2/go.master/src/runtime/internal/sys/intrinsics.go:54)	MOVQ	AX, "".~r1+16(DX)
/ssd2/go.master/src/runtime/internal/sys/intrinsics_common.go:142:2: "".Len64: invalid instruction: 00105 (/ssd2/go.master/src/runtime/internal/sys/intrinsics_common.go:61)	MOVQ	DX, "".n+40(CX)
/ssd2/go.master/src/runtime/internal/sys/intrinsics_common.go:142:2: "".LeadingZeros64: invalid instruction: 00027 (/ssd2/go.master/src/runtime/internal/sys/intrinsics_common.go:130)	MOVQ	CX, "".~r1+16(AX)

go tool dist: FAILED: /ssd2/go.master/pkg/tool/linux_amd64/compile -std -pack -o /tmp/go-tool-dist-2914131847/runtime/internal/sys/_go_.a -p runtime/internal/sys -importcfg /tmp/go-tool-dist-2914131847/runtime/internal/sys/importcfg /ssd2/go.master/src/runtime/internal/sys/arch.go /ssd2/go.master/src/runtime/internal/sys/arch_amd64.go /ssd2/go.master/src/runtime/internal/sys/intrinsics.go /ssd2/go.master/src/runtime/internal/sys/intrinsics_common.go /ssd2/go.master/src/runtime/internal/sys/sys.go /ssd2/go.master/src/runtime/internal/sys/zgoarch_amd64.go /ssd2/go.master/src/runtime/internal/sys/zgoos_linux.go /ssd2/go.master/src/runtime/internal/sys/zversion.go: exit status 2
go tool dist: open /tmp/go-tool-dist-2914131847/runtime/internal/sys/_go_.a: no such file or directory
go tool dist: open /tmp/go-tool-dist-2914131847/internal/cpu/_go_.a: no such file or directory
/ssd2/go.master/src/internal/cpu/cpu_x86.go:46:17: internal compiler error: 'doinit': panic during regalloc while compiling doinit:

interface conversion: ssa.Location is nil, not *	bootstrap_1cmd_1compile_1internal_1ssa	ssa.Register

goroutine 1 [running]:
bootstrap/cmd/compile/internal/ssa.Compile..func1
	/ssd2/go.master/src/cmd/compile/internal/ssa/compile.go:44
panic
	../../../gcc-trunk/libgo/go/runtime/panic.go:715
bootstrap_1cmd_1compile_1internal_1ssa.regAllocState.regalloc
	/ssd2/go.master/src/cmd/compile/internal/ssa/regalloc.go:1578
bootstrap/cmd/compile/internal/ssa.regalloc
	/ssd2/go.master/src/cmd/compile/internal/ssa/regalloc.go:148
bootstrap_1cmd_1compile_1internal_1ssa.Compile
	/ssd2/go.master/src/cmd/compile/internal/ssa/compile.go:96
bootstrap/cmd/compile/internal/ssagen.buildssa
	/ssd2/go.master/src/cmd/compile/internal/ssagen/ssa.go:642
bootstrap_1cmd_1compile_1internal_1ssagen.Compile
	/ssd2/go.master/src/cmd/compile/internal/ssagen/pgen.go:165
bootstrap/cmd/compile/internal/gc.compileFunctions..func6
	/ssd2/go.master/src/cmd/compile/internal/gc/compile.go:153
bootstrap/cmd/compile/internal/gc.compileFunctions..func2
	/ssd2/go.master/src/cmd/compile/internal/gc/compile.go:125
bootstrap/cmd/compile/internal/gc.compileFunctions..func5
	/ssd2/go.master/src/cmd/compile/internal/gc/compile.go:152
bootstrap/cmd/compile/internal/gc.compileFunctions
	/ssd2/go.master/src/cmd/compile/internal/gc/compile.go:163
bootstrap_1cmd_1compile_1internal_1gc.Main
	/ssd2/go.master/src/cmd/compile/internal/gc/main.go:287
main.main
	/ssd2/go.master/src/cmd/compile/main.go:55



goroutine 1 [running]:
runtime_1debug.Stack
	../../../gcc-trunk/libgo/go/runtime/debug/stack.go:24
bootstrap_1cmd_1compile_1internal_1base.FatalfAt
	/ssd2/go.master/src/cmd/compile/internal/base/print.go:227
bootstrap_1cmd_1compile_1internal_1base.Fatalf
	 /ssd2/go.master/src/cmd/compile/internal/base/print.go:196
bootstrap_1cmd_1compile_1internal_1ssagen.ssafn.Fatalf
	/ssd2/go.master/src/cmd/compile/internal/ssagen/ssa.go:7604
bootstrap_1cmd_1compile_1internal_1ssa.Func.Fatalf
	/ssd2/go.master/src/cmd/compile/internal/ssa/func.go:773
bootstrap/cmd/compile/internal/ssa.Compile..func1
	/ssd2/go.master/src/cmd/compile/internal/ssa/compile.go:44
panic
	../../../gcc-trunk/libgo/go/runtime/panic.go:715
bootstrap_1cmd_1compile_1internal_1ssa.regAllocState.regalloc
	/ssd2/go.master/src/cmd/compile/internal/ssa/regalloc.go:1578
bootstrap/cmd/compile/internal/ssa.regalloc
	/ssd2/go.master/src/cmd/compile/internal/ssa/regalloc.go:148
bootstrap_1cmd_1compile_1internal_1ssa.Compile
	/ssd2/go.master/src/cmd/compile/internal/ssa/compile.go:96
bootstrap/cmd/compile/internal/ssagen.buildssa
	/ssd2/go.master/src/cmd/compile/internal/ssagen/ssa.go:642
bootstrap_1cmd_1compile_1internal_1ssagen.Compile
	/ssd2/go.master/src/cmd/compile/internal/ssagen/pgen.go:165
bootstrap/cmd/compile/internal/gc.compileFunctions..func6
	/ssd2/go.master/src/cmd/compile/internal/gc/compile.go:153
bootstrap/cmd/compile/internal/gc.compileFunctions..func2
	/ssd2/go.master/src/cmd/compile/internal/gc/compile.go:125
bootstrap/cmd/compile/internal/gc.compileFunctions..func5
	/ssd2/go.master/src/cmd/compile/internal/gc/compile.go:152
bootstrap/cmd/compile/internal/gc.compileFunctions
	/ssd2/go.master/src/cmd/compile/internal/gc/compile.go:163
bootstrap_1cmd_1compile_1internal_1gc.Main
	/ssd2/go.master/src/cmd/compile/internal/gc/main.go:287
main.main
	/ssd2/go.master/src/cmd/compile/main.go:55


go tool dist: FAILED: /ssd2/go.master/pkg/tool/linux_amd64/compile -std -pack -o /tmp/go-tool-dist-2914131847/internal/cpu/_go_.a -p internal/cpu -importcfg /tmp/go-tool-dist-2914131847/internal/cpu/importcfg -asmhdr /tmp/go-tool-dist-2914131847/internal/cpu/go_asm.h -symabis /tmp/go-tool-dist-2914131847/internal/cpu/symabis /ssd2/go.master/src/internal/cpu/cpu.go /ssd2/go.master/src/internal/cpu/cpu_amd64.go /ssd2/go.master/src/internal/cpu/cpu_x86.go: exit status 2
```

**Comment by R3belWithoutAPause** [comment]
While i'm not getting any segfaults i am getting what looks like the same build failure as @thanm above. I'm running on Slackware64-current and building go 1.17  from source fails with the following output:

`Building Go cmd/dist using /usr. (go1.16.5 gccgo (GCC) 11.2.0 linux/amd64)
Building Go toolchain1 using /usr.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
/tmp/SBo/package-google-go-lang/usr/lib64/go1.17/go/src/runtime/internal/sys/intrinsics_common.go:142:2: "".Ctz64: invalid instruction: 00049 (/tmp/SBo/package-google-go-lang/usr/lib64/go1.17/go/src/runtime/internal/sys/intrinsics.go:44)   MOVQ    CX, "".~r1+16(DX)
/tmp/SBo/package-google-go-lang/usr/lib64/go1.17/go/src/runtime/internal/sys/intrinsics_common.go:142:2: "".Ctz32: invalid instruction: 00042 (/tmp/SBo/package-google-go-lang/usr/lib64/go1.17/go/src/runtime/internal/sys/intrinsics.go:54)   MOVQ    AX, "".~r1+16(DX)
/tmp/SBo/package-google-go-lang/usr/lib64/go1.17/go/src/runtime/internal/sys/intrinsics_common.go:142:2: "".Len64: invalid instruction: 00105 (/tmp/SBo/package-google-go-lang/usr/lib64/go1.17/go/src/runtime/internal/sys/intrinsics_common.go:61)    MOVQ    DX, "".n+40(CX)
/tmp/SBo/package-google-go-lang/usr/lib64/go1.17/go/src/runtime/internal/sys/intrinsics_common.go:142:2: "".LeadingZeros64: invalid instruction: 00027 (/tmp/SBo/package-google-go-lang/usr/lib64/go1.17/go/src/runtime/internal/sys/intrinsics_common.go:130)  MOVQ      CX, "".~r1+16(AX)

go tool dist: FAILED: /tmp/SBo/package-google-go-lang/usr/lib64/go1.17/go/pkg/tool/linux_amd64/compile -std -pack -o /tmp/go-tool-dist-704368278/runtime/internal/sys/_go_.a -p runtime/internal/sys -importcfg /tmp/go-tool-dist-704368278/runtime/internal/sys/importcfg /tmp/SBo/package-google-go-lang/usr/lib64/go1.17/go/src/runtime/internal/sys/arch.go /tmp/SBo/package-google-go-lang/usr/lib64/go1.17/go/src/runtime/internal/sys/arch_amd64.go /tmp/SBo/package-google-go-lang/usr/lib64/go1.17/go/src/runtime/internal/sys/intrinsics.go /tmp/SBo/package-google-go-lang/usr/lib64/go1.17/go/src/runtime/internal/sys/intrinsics_common.go /tmp/SBo/package-google-go-lang/usr/lib64/go1.17/go/src/runtime/internal/sys/sys.go /tmp/SBo/package-google-go-lang/usr/lib64/go1.17/go/src/runtime/internal/sys/zgoarch_amd64.go /tmp/SBo/package-google-go-lang/usr/lib64/go1.17/go/src/runtime/internal/sys/zgoos_linux.go /tmp/SBo/package-google-go-lang/usr/lib64/go1.17/go/src/runtime/internal/sys/zversion.go: exit status 2
go tool dist: open /tmp/go-tool-dist-704368278/runtime/internal/sys/_go_.a: no such file or directory
go tool dist: open /tmp/go-tool-dist-704368278/runtime/internal/atomic/_go_.a: no such file or directory
go tool dist: open /tmp/go-tool-dist-704368278/internal/cpu/_go_.a: no such file or directory
/tmp/SBo/package-google-go-lang/usr/lib64/go1.17/go/src/internal/cpu/cpu_x86.go:46:17: internal compiler error: 'doinit': panic during regalloc while compiling doinit:

interface conversion: ssa.Location is nil, not *        bootstrap_1cmd_1compile_1internal_1ssa  ssa.Register

goroutine 1 [running]:
bootstrap/cmd/compile/internal/ssa.Compile..func1
        /tmp/SBo/package-google-go-lang/usr/lib64/go1.17/go/src/cmd/compile/internal/ssa/compile.go:44
panic
        :0
bootstrap_1cmd_1compile_1internal_1ssa.regAllocState.regalloc
        /tmp/SBo/package-google-go-lang/usr/lib64/go1.17/go/src/cmd/compile/internal/ssa/regalloc.go:1578
bootstrap/cmd/compile/internal/ssa.regalloc
        /tmp/SBo/package-google-go-lang/usr/lib64/go1.17/go/src/cmd/compile/internal/ssa/regalloc.go:148
bootstrap_1cmd_1compile_1internal_1ssa.Compile
        /tmp/SBo/package-google-go-lang/usr/lib64/go1.17/go/src/cmd/compile/internal/ssa/compile.go:96
bootstrap/cmd/compile/internal/ssagen.buildssa
        /tmp/SBo/package-google-go-lang/usr/lib64/go1.17/go/src/cmd/compile/internal/ssagen/ssa.go:642
bootstrap_1cmd_1compile_1internal_1ssagen.Compile
        /tmp/SBo/package-google-go-lang/usr/lib64/go1.17/go/src/cmd/compile/internal/ssagen/pgen.go:165
bootstrap/cmd/compile/internal/gc.compileFunctions..func6
        /tmp/SBo/package-google-go-lang/usr/lib64/go1.17/go/src/cmd/compile/internal/gc/compile.go:153
bootstrap/cmd/compile/internal/gc.compileFunctions..func2
        /tmp/SBo/package-google-go-lang/usr/lib64/go1.17/go/src/cmd/compile/internal/gc/compile.go:125
bootstrap/cmd/compile/internal/gc.compileFunctions..func5
        /tmp/SBo/package-google-go-lang/usr/lib64/go1.17/go/src/cmd/compile/internal/gc/compile.go:152
bootstrap/cmd/compile/internal/gc.compileFunctions
        /tmp/SBo/package-google-go-lang/usr/lib64/go1.17/go/src/cmd/compile/internal/gc/compile.go:163
bootstrap_1cmd_1compile_1internal_1gc.Main
        /tmp/SBo/package-google-go-lang/usr/lib64/go1.17/go/src/cmd/compile/internal/gc/main.go:287
main.main
        /tmp/SBo/package-google-go-lang/usr/lib64/go1.17/go/src/cmd/compile/main.go:55



Please file a bug report including a short program that triggers the error.
https://golang.org/issue/new

go tool dist: FAILED: /tmp/SBo/package-google-go-lang/usr/lib64/go1.17/go/pkg/tool/linux_amd64/compile -std -pack -o /tmp/go-tool-dist-704368278/internal/cpu/_go_.a -p internal/cpu -importcfg /tmp/go-tool-dist-704368278/internal/cpu/importcfg -asmhdr /tmp/go-tool-dist-704368278/internal/cpu/go_asm.h -symabis /tmp/go-tool-dist-704368278/internal/cpu/symabis /tmp/SBo/package-google-go-lang/usr/lib64/go1.17/go/src/internal/cpu/cpu.go /tmp/SBo/package-google-go-lang/usr/lib64/go1.17/go/src/internal/cpu/cpu_amd64.go /tmp/SBo/package-google-go-lang/usr/lib64/go1.17/go/src/internal/cpu/cpu_x86.go: exit status 2`

If it's any use, 1.16.7 compiles fine using the same build script.

**Comment by ianlancetaylor** [comment]
I found at least one problem.  The gofrontend miscompiled `append(s, make(typ, ln)...)` when the type contains a pointer and the capacity of the slice does not increase: it did not correctly zero out the new slice elements.

**Comment by ianlancetaylor** [comment]
Fixing that problem lets bootstrap succeed at least with tip gccgo.

**Comment by R3belWithoutAPause** [comment]
I'm new to Go so please excuse me not knowing what to do here. I added the file issue47771.go to test/fixedbugs but recompiling still produces the same error. Have i missed something ?

**Comment by ianlancetaylor** [comment]
To be clear, the new file issue47771.go is a test case, not a fix.  The fix is a change to the Go frontend of GCC.

I have now committed the fix to GCC trunk, GCC 11 branch, and GCC 10 branch.  However, it will take a little while for to fix to flow through into new releases of gccgo.

**Comment by greatdreams** [comment]
Compiling 1.16 release source code using  gccgo-10 is successful, but fail to compile 1.17 release source code.

**Comment by ianlancetaylor** [comment]
@greatdreams The fix is not yet available in a released version of GCC 10.  It will be in GCC 10.4.
