### ISSUE TITLE
gc: generics: "runtime error: slice bounds out of range" during compilation

### ISSUE THREAD

**Issue by kylelemons** [golang/go#47948]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.18-e1fcf88 Wed Aug 25 03:13:06 2021 +0000 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

I rebuilt using `gotip download` and it still reproduces

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\kyle\AppData\Local\go-build
set GOENV=C:\Users\kyle\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\kyle\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\kyle\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Users\kyle\sdk\gotip
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Users\kyle\sdk\gotip\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=devel go1.18-e1fcf88 Wed Aug 25 03:13:06 2021 +0000
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=C:\Users\kyle\dev\generics_exp\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\kyle\AppData\Local\Temp\go-build1116736757=/tmp/go-build -gno-record-gcc-switches
GOROOT/bin/go version: go version devel go1.18-e1fcf88 Wed Aug 25 03:13:06 2021 +0000 windows/amd64
GOROOT/bin/go tool compile -V: compile version devel go1.18-e1fcf88 Wed Aug 25 03:13:06 2021 +0000
</pre></details>

### What did you do?

Minimal repro:

```
package genassert

import (
	"context"
	"time"
)

type I interface {
}

func F[T comparable](t I) {
	ctx, cancel := context.WithTimeout(context.TODO(), 5*time.Second)
	_, _ = ctx, cancel
}

func init() {
	F[int](nil)
}
```

Original case:
https://gist.github.com/kylelemons/cf3c1cee1ce92017b41cec08d752a290

### What did you expect to see?

This code should either compile or produce an error explaining what is wrong.

The code works on the playground:
https://go2goplay.golang.org/p/zUCzoXckN63

### What did you see instead?

A compile-time panic:

```
panic: runtime error: slice bounds out of range [:-1]

goroutine 1 [running]:
cmd/compile/internal/typecheck.genericTypeName(...)
	C:/Users/kyle/sdk/gotip/src/cmd/compile/internal/typecheck/subr.go:1349
cmd/compile/internal/typecheck.(*Tsubster).Typ(0xc0006dd218, 0xc00016bce0)
	C:/Users/kyle/sdk/gotip/src/cmd/compile/internal/typecheck/subr.go:1059 +0x139d
cmd/compile/internal/noder.(*subster).localvar(0xc0006dd200, 0xc00037e410)
	C:/Users/kyle/sdk/gotip/src/cmd/compile/internal/noder/stencil.go:759 +0x69
cmd/compile/internal/noder.(*irgen).genericSubst(0xc000444000, 0xc00039d770, 0xc000414ea0, {0xc00010f768, 0x1, 0x1}, 0x1, 0xc000478e00)
	C:/Users/kyle/sdk/gotip/src/cmd/compile/internal/noder/stencil.go:694 +0x72e
cmd/compile/internal/noder.(*irgen).getInstantiation(0xc000444000, 0xc000414ea0, {0xc00010f698, 0x1, 0x1}, 0x30)
	C:/Users/kyle/sdk/gotip/src/cmd/compile/internal/noder/stencil.go:608 +0x33d
cmd/compile/internal/noder.(*irgen).instantiateMethods(0xc000444000)
	C:/Users/kyle/sdk/gotip/src/cmd/compile/internal/noder/stencil.go:511 +0x248
cmd/compile/internal/noder.(*irgen).stencil(0xc000444000)
	C:/Users/kyle/sdk/gotip/src/cmd/compile/internal/noder/stencil.go:50 +0x9b
cmd/compile/internal/noder.(*irgen).generate(0xc000444000, {0xc000074b50, 0x2, 0x2030000})
	C:/Users/kyle/sdk/gotip/src/cmd/compile/internal/noder/irgen.go:286 +0x2d8
cmd/compile/internal/noder.check2({0xc000074b50, 0x2, 0x2})
	C:/Users/kyle/sdk/gotip/src/cmd/compile/internal/noder/irgen.go:92 +0x16d
cmd/compile/internal/noder.LoadPackage({0xc0000c40f0, 0x2, 0x0})
	C:/Users/kyle/sdk/gotip/src/cmd/compile/internal/noder/noder.go:90 +0x365
cmd/compile/internal/gc.Main(0x15b21a8)
	C:/Users/kyle/sdk/gotip/src/cmd/compile/internal/gc/main.go:190 +0xaf3
main.main()
	C:/Users/kyle/sdk/gotip/src/cmd/compile/main.go:55 +0xdd

Compilation finished with exit code 2
```

**Comment by kylelemons** [comment]
Sorry, the minimal repro was wrong, I've removed it for now

**Comment by kylelemons** [comment]
False alarm, the repro was fine.  Here it is again:

```
package genassert

import (
	"context"
	"time"
)

func F[T comparable]() {
	ctx, cancel := context.WithTimeout(context.TODO(), 5*time.Second)
	_, _ = ctx, cancel
}

func init() {
	F[int]()
}
```

run using go test with
```
package genassert

import (
	"testing"
)

func TestF(t *testing.T) {
}

```

panic:
```
GOROOT=C:\Users\kyle\sdk\gotip #gosetup
GOPATH=C:\Users\kyle\go #gosetup
C:\Users\kyle\sdk\gotip\bin\go.exe test -c -o C:\Users\kyle\AppData\Local\Temp\GoLand\___go_test_generics_exp_genassert_repro.test.exe generics_exp/genassert_repro #gosetup
# generics_exp/genassert_repro [generics_exp/genassert_repro.test]
panic: runtime error: slice bounds out of range [:-1]

goroutine 1 [running]:
cmd/compile/internal/typecheck.genericTypeName(...)
	C:/Users/kyle/sdk/gotip/src/cmd/compile/internal/typecheck/subr.go:1349
cmd/compile/internal/typecheck.(*Tsubster).Typ(0xc000818d98, 0xc0003965b0)
	C:/Users/kyle/sdk/gotip/src/cmd/compile/internal/typecheck/subr.go:1059 +0x139d
cmd/compile/internal/noder.(*subster).localvar(0xc000818d80, 0xc00039c0d0)
	C:/Users/kyle/sdk/gotip/src/cmd/compile/internal/noder/stencil.go:759 +0x69
cmd/compile/internal/noder.(*irgen).genericSubst(0xc000454000, 0xc0003955e0, 0xc0000ac8f0, {0xc000095170, 0x1, 0x1}, 0x0, 0xc000090d00)
	C:/Users/kyle/sdk/gotip/src/cmd/compile/internal/noder/stencil.go:694 +0x72e
cmd/compile/internal/noder.(*irgen).getInstantiation(0xc000454000, 0xc0000ac8f0, {0xc000095168, 0x1, 0x1}, 0x0)
	C:/Users/kyle/sdk/gotip/src/cmd/compile/internal/noder/stencil.go:608 +0x33d
cmd/compile/internal/noder.(*irgen).stencil.func1({0x16fbd18, 0xc000391170})
	C:/Users/kyle/sdk/gotip/src/cmd/compile/internal/noder/stencil.go:109 +0x2df
cmd/compile/internal/ir.Visit.func1({0x16fbd18, 0xc000391170})
	C:/Users/kyle/sdk/gotip/src/cmd/compile/internal/ir/visit.go:105 +0x30
cmd/compile/internal/ir.doNodes({0xc000099950, 0x1, 0x0}, 0xc00039a1e0)
	C:/Users/kyle/sdk/gotip/src/cmd/compile/internal/ir/node_gen.go:1512 +0x67
cmd/compile/internal/ir.(*Func).doChildren(0x16fc678, 0xc00009a2c0)
	C:/Users/kyle/sdk/gotip/src/cmd/compile/internal/ir/func.go:152 +0x2e
cmd/compile/internal/ir.DoChildren(...)
	C:/Users/kyle/sdk/gotip/src/cmd/compile/internal/ir/visit.go:94
cmd/compile/internal/ir.Visit.func1({0x16fc678, 0xc00009a2c0})
	C:/Users/kyle/sdk/gotip/src/cmd/compile/internal/ir/visit.go:106 +0x57
cmd/compile/internal/ir.Visit({0x16fc678, 0xc00009a2c0}, 0xc000090cc0)
	C:/Users/kyle/sdk/gotip/src/cmd/compile/internal/ir/visit.go:108 +0xb8
cmd/compile/internal/noder.(*irgen).stencil(0xc000454000)
	C:/Users/kyle/sdk/gotip/src/cmd/compile/internal/noder/stencil.go:91 +0x26a
cmd/compile/internal/noder.(*irgen).generate(0xc000454000, {0xc000076b70, 0x2, 0x2030000})
	C:/Users/kyle/sdk/gotip/src/cmd/compile/internal/noder/irgen.go:286 +0x2d8
cmd/compile/internal/noder.check2({0xc000076b70, 0x2, 0x2})
	C:/Users/kyle/sdk/gotip/src/cmd/compile/internal/noder/irgen.go:92 +0x16d
cmd/compile/internal/noder.LoadPackage({0xc00013c0f0, 0x2, 0x0})
	C:/Users/kyle/sdk/gotip/src/cmd/compile/internal/noder/noder.go:90 +0x365
cmd/compile/internal/gc.Main(0x15b21a8)
	C:/Users/kyle/sdk/gotip/src/cmd/compile/internal/gc/main.go:190 +0xaf3
main.main()
	C:/Users/kyle/sdk/gotip/src/cmd/compile/main.go:55 +0xdd

Compilation finished with exit code 2
```

**Comment by korzhao** [comment]
simpler:
```
type CancelFunc func()

func F[T any]() {
	_ = CancelFunc(func() {
		
	})
}
func main() {
	F[int]()
}
```
