### ISSUE TITLE
cmd/compile: "panic: interface conversion" when compiling a test that calls a generic function

### ISSUE THREAD

**Issue by bcmills** [golang/go#48094]
### What version of Go are you using (`go version`)?

<pre>
~/src/github.com/bcmills/unsafeslice$ gotip version
go version devel go1.18-f118d145a Tue Aug 31 08:41:16 2021 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

N/A

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/usr/local/google/home/bcmills/.cache/go-build"
GOENV="/usr/local/google/home/bcmills/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/usr/local/google/home/bcmills/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/usr/local/google/home/bcmills"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/google/home/bcmills/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/google/home/bcmills/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel go1.18-e11c94efcb Mon Aug 30 15:39:06 2021 -0400"
GCCGO="/usr/local/google/home/bcmills/bin/gccgo"
AR="ar"
CC="gcc"
CXX="c++"
CGO_ENABLED="1"
GOMOD="/usr/local/google/home/bcmills/src/github.com/bcmills/unsafeslice/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2906345833=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

In the root of the repository at https://github.com/bcmills/unsafeslice/commit/849066caf28406f55c56d79265767233bedb7669, run `go test .`.

### What did you expect to see?

A successful test run, or a test failure, or a compile error indicating a problem in my code.

### What did you see instead?
`panic: interface conversion: types.Object is nil, not *ir.Name`

<details>

```
# github.com/bcmills/unsafeslice_test [github.com/bcmills/unsafeslice.test]
panic: interface conversion: types.Object is nil, not *ir.Name

goroutine 1 [running]:
cmd/compile/internal/typecheck.(*importReader).node(0xc000886240)
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/typecheck/iimport.go:1272 +0x3a5a
cmd/compile/internal/typecheck.(*importReader).expr(0xc000886240)
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/typecheck/iimport.go:1225 +0x1d
cmd/compile/internal/typecheck.(*importReader).node(0xc000886240)
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/typecheck/iimport.go:1496 +0x1925
cmd/compile/internal/typecheck.(*importReader).expr(0xc000886240)
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/typecheck/iimport.go:1225 +0x1d
cmd/compile/internal/typecheck.(*importReader).node(0xc000886240)
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/typecheck/iimport.go:1464 +0x306f
cmd/compile/internal/typecheck.(*importReader).expr(0x0)
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/typecheck/iimport.go:1225 +0x1d
cmd/compile/internal/typecheck.(*importReader).exprList(0xc000886240)
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/typecheck/iimport.go:1215 +0x47
cmd/compile/internal/typecheck.(*importReader).node(0xc000886240)
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/typecheck/iimport.go:1496 +0x1945
cmd/compile/internal/typecheck.(*importReader).expr(0xc000886240)
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/typecheck/iimport.go:1225 +0x1d
cmd/compile/internal/typecheck.(*importReader).node(0xc000886240)
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/typecheck/iimport.go:1604 +0x1150
cmd/compile/internal/typecheck.(*importReader).stmtList(0xc000886240)
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/typecheck/iimport.go:1163 +0x5b
cmd/compile/internal/typecheck.(*importReader).node(0xc000886240)
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/typecheck/iimport.go:1641 +0x1d12
cmd/compile/internal/typecheck.(*importReader).stmtList(0x8)
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/typecheck/iimport.go:1163 +0x5b
cmd/compile/internal/typecheck.(*importReader).funcBody(0xc000886240, 0xc000973340)
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/typecheck/iimport.go:1084 +0x92
cmd/compile/internal/typecheck.(*importReader).doInline(0xc79360, 0xc000973340)
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/typecheck/iimport.go:1048 +0x99
cmd/compile/internal/typecheck.ImportBody(0xc000973340)
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/typecheck/iimport.go:80 +0x206
cmd/compile/internal/noder.checkFetchBody(0xc000123a00)
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/noder/stencil.go:560 +0x96
cmd/compile/internal/noder.(*irgen).getGfInfo(0xc000131000, 0xc000123a00)
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/noder/stencil.go:1666 +0x69
cmd/compile/internal/noder.(*irgen).getDictionarySym(0xc000131000, 0xc000123a00, {0xc0004dd020, 0x5be907, 0x1}, 0x10)
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/noder/stencil.go:1417 +0x16d
cmd/compile/internal/noder.(*irgen).getDictionarySym(0xc000131000, 0xc000435d40, {0xc0004dcf60, 0x1, 0x1}, 0x1)
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/noder/stencil.go:1496 +0x1072
cmd/compile/internal/noder.(*irgen).getDictionaryValue(0xc000901980, 0xc00038b030, {0xc0004dcf60, 0xc00046fa40, 0xc0004dcfb0}, 0xb0)
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/noder/stencil.go:1613 +0x25
cmd/compile/internal/noder.(*irgen).getDictOrSubdict(0xc000131000, 0xc000435d40, {0xe68c38, 0xc000148e10}, 0x1, {0xc0004dcf60, 0xc000131000, 0xe69598}, 0x98)
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/noder/stencil.go:548 +0x13d
cmd/compile/internal/noder.(*irgen).stencil.func1({0xe68c38, 0xc000148e10})
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/noder/stencil.go:110 +0x32c
cmd/compile/internal/ir.Visit.func1({0xe68c38, 0xc000148e10})
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/ir/visit.go:105 +0x30
cmd/compile/internal/ir.(*AssignStmt).doChildren(0xc000577ae0, 0xc000599068)
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/ir/node_gen.go:152 +0x82
cmd/compile/internal/ir.DoChildren(...)
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/ir/visit.go:94
cmd/compile/internal/ir.Visit.func1({0xe68850, 0xc000577ae0})
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/ir/visit.go:106 +0x57
cmd/compile/internal/ir.doNodes({0xc000900480, 0x3, 0x0}, 0xc000599068)
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/ir/node_gen.go:1512 +0x67
cmd/compile/internal/ir.(*Func).doChildren(0xe69598, 0xc0008db1e0)
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/ir/func.go:152 +0x2e
cmd/compile/internal/ir.DoChildren(...)
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/ir/visit.go:94
cmd/compile/internal/ir.Visit.func1({0xe69598, 0xc0008db1e0})
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/ir/visit.go:106 +0x57
cmd/compile/internal/ir.Visit({0xe69598, 0xc0008db1e0}, 0xc000901880)
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/ir/visit.go:108 +0xb8
cmd/compile/internal/noder.(*irgen).stencil(0xc000131000)
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/noder/stencil.go:91 +0x26a
cmd/compile/internal/noder.(*irgen).generate(0xc000131000, {0xc00000d8a8, 0x3, 0x0})
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/noder/irgen.go:294 +0x2d8
cmd/compile/internal/noder.check2({0xc00000d8a8, 0x3, 0x3})
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/noder/irgen.go:92 +0x177
cmd/compile/internal/noder.LoadPackage({0xc00001e200, 0x3, 0x0})
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/noder/noder.go:90 +0x335
cmd/compile/internal/gc.Main(0xd21740)
	/usr/local/google/home/bcmills/go/src/cmd/compile/internal/gc/main.go:190 +0xaf3
main.main()
	/usr/local/google/home/bcmills/go/src/cmd/compile/main.go:55 +0xdd
FAIL	github.com/bcmills/unsafeslice [build failed]
FAIL
```

CC @mdempsky @findleyr @griesemer

**Comment by cuonglm** [comment]
It seems to me that https://go-review.googlesource.com/c/go/+/335413 which changed `unsafe.Sizeof` (and other unsafe functions) to become builtins cause this problem.

**Comment by griesemer** [comment]
[CL 335413](https://golang.org/cl/335413) makes `unsafe.Sizeof` a variable for types that depend on type parameters which is what we need to do if we want to be able to use `unsafe.Sizeof` in those cases. Not having looked at this issue in detail, there's probably some work in the compiler that needs to be done as well.

**Comment by cuonglm** [comment]
> [CL 335413](https://golang.org/cl/335413) makes `unsafe.Sizeof` a variable for types that depend on type parameters which is what we need to do if we want to be able to use `unsafe.Sizeof` in those cases. Not having looked at this issue in detail, there's probably some work in the compiler that needs to be done as well.

Yeah, I think we need to update the import/export to support this case.

Unified IR is also affected cc @mdempsky
