### ISSUE TITLE
fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by crcms** [golang/go#48269]
Note:  **... It means that I hide my own local file path.**
### What version of Go are you using (`go version`)?

<pre>
go version go1.17 darwin/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="..."
GOENV="..."
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="..."
GONOPROXY="github.com"
GONOSUMDB=""
GOOS="darwin"
GOPATH="..."
GOPRIVATE=""
GOPROXY=""
GOROOT="/usr/local/Cellar/go/1.17/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.17/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="..."
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/th/lb2hs5y10db6v51qbx5q2nk40000gp/T/go-build265588239=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Only run go run main.go

### What did you expect to see?

Normal running

### What did you see instead?
Note: **The same code, I am running in the Window platform, and the current problem is only on the Mac.**
```text
go run main.go 
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff68e1170a]

runtime stack:
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff68e1170a
stack: frame={sp:0x7ffeefbff668, fp:0x7ffeefbff6b8} stack=[0x7ffeefb80708,0x7ffeefbff770)
0x00007ffeefbff568:  0x01007ffeefbff588  0x0000000000000004 
0x00007ffeefbff578:  0x000000000000001f  0x00007fff68e1170a 
0x00007ffeefbff588:  0x0b01dfacedebac1e  0x0000000000000001 
0x00007ffeefbff598:  0x0000000004036bf1 <runtime.throw+0x0000000000000071>  0x00007ffeefbff638 
0x00007ffeefbff5a8:  0x0000000004aa8ec0  0x00007ffeefbff5f0 
0x00007ffeefbff5b8:  0x0000000004036ea8 <runtime.fatalthrow.func1+0x0000000000000048>  0x000000000524a1a0 
0x00007ffeefbff5c8:  0x0000000000000001  0x0000000000000001 
0x00007ffeefbff5d8:  0x00007ffeefbff638  0x0000000004036bf1 <runtime.throw+0x0000000000000071> 
0x00007ffeefbff5e8:  0x000000000524a1a0  0x00007ffeefbff628 
0x00007ffeefbff5f8:  0x0000000004036e30 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbff608 
0x00007ffeefbff608:  0x0000000004036e60 <runtime.fatalthrow.func1+0x0000000000000000>  0x000000000524a1a0 
0x00007ffeefbff618:  0x0000000004036bf1 <runtime.throw+0x0000000000000071>  0x00007ffeefbff638 
0x00007ffeefbff628:  0x00007ffeefbff658  0x0000000004036bf1 <runtime.throw+0x0000000000000071> 
0x00007ffeefbff638:  0x00007ffeefbff640  0x0000000004036c20 <runtime.throw.func1+0x0000000000000000> 
0x00007ffeefbff648:  0x0000000004ab4a40  0x000000000000002a 
0x00007ffeefbff658:  0x00007ffeefbff6a8  0x000000000404d516 <runtime.sigpanic+0x0000000000000396> 
0x00007ffeefbff668: <0x0000000004ab4a40  0x00007ffeefbff690 
0x00007ffeefbff678:  0x00007ffeefbff6e8  0x0000000004027c26 <runtime.(*mheap).allocSpan+0x0000000000000546> 
0x00007ffeefbff688:  0x000000c0002d2000  0x0000000000002000 
0x00007ffeefbff698:  0x0000000000000008  0x00007ffeefbff6f8 
0x00007ffeefbff6a8:  0x00007ffeefbff6f0 !0x00007fff68e1170a 
0x00007ffeefbff6b8: >0x00007ffeefbff6f0  0x00000000051c4000 
0x00007ffeefbff6c8:  0x00000000000004ae  0x00000000043ed265 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005> 
0x00007ffeefbff6d8:  0x000000000406ccdf <runtime.syscall+0x000000000000001f>  0x000000c0001a5710 
0x00007ffeefbff6e8:  0x000000000406c64c <runtime.nanotime_trampoline+0x000000000000000c>  0x000000c0001a56e0 
0x00007ffeefbff6f8:  0x000000000406ab10 <runtime.asmcgocall+0x0000000000000070>  0x0000000000000001 
0x00007ffeefbff708:  0x0000000004001200  0x1200000000001018 
0x00007ffeefbff718:  0x0000000000000000  0x000000000527ecb8 
0x00007ffeefbff728:  0x0000000000000948  0x000000c0000001a0 
0x00007ffeefbff738:  0x0000000004068c29 <runtime.systemstack+0x0000000000000049>  0x0000000000000004 
0x00007ffeefbff748:  0x0000000004ba98b0  0x000000000524a1a0 
0x00007ffeefbff758:  0x00007ffeefbff7a0  0x0000000004068b25 <runtime.mstart+0x0000000000000005> 
0x00007ffeefbff768:  0x0000000004068add <runtime.rt0_go+0x000000000000013d> 
runtime.throw({0x4ab4a40, 0x7ffeefbff690})
        /usr/local/Cellar/go/1.17/libexec/src/runtime/panic.go:1198 +0x71
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff68e1170a
stack: frame={sp:0x7ffeefbff668, fp:0x7ffeefbff6b8} stack=[0x7ffeefb80708,0x7ffeefbff770)
0x00007ffeefbff568:  0x01007ffeefbff588  0x0000000000000004 
0x00007ffeefbff578:  0x000000000000001f  0x00007fff68e1170a 
0x00007ffeefbff588:  0x0b01dfacedebac1e  0x0000000000000001 
0x00007ffeefbff598:  0x0000000004036bf1 <runtime.throw+0x0000000000000071>  0x00007ffeefbff638 
0x00007ffeefbff5a8:  0x0000000004aa8ec0  0x00007ffeefbff5f0 
0x00007ffeefbff5b8:  0x0000000004036ea8 <runtime.fatalthrow.func1+0x0000000000000048>  0x000000000524a1a0 
0x00007ffeefbff5c8:  0x0000000000000001  0x0000000000000001 
0x00007ffeefbff5d8:  0x00007ffeefbff638  0x0000000004036bf1 <runtime.throw+0x0000000000000071> 
0x00007ffeefbff5e8:  0x000000000524a1a0  0x00007ffeefbff628 
0x00007ffeefbff5f8:  0x0000000004036e30 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbff608 
0x00007ffeefbff608:  0x0000000004036e60 <runtime.fatalthrow.func1+0x0000000000000000>  0x000000000524a1a0 
0x00007ffeefbff618:  0x0000000004036bf1 <runtime.throw+0x0000000000000071>  0x00007ffeefbff638 
0x00007ffeefbff628:  0x00007ffeefbff658  0x0000000004036bf1 <runtime.throw+0x0000000000000071> 
0x00007ffeefbff638:  0x00007ffeefbff640  0x0000000004036c20 <runtime.throw.func1+0x0000000000000000> 
0x00007ffeefbff648:  0x0000000004ab4a40  0x000000000000002a 
0x00007ffeefbff658:  0x00007ffeefbff6a8  0x000000000404d516 <runtime.sigpanic+0x0000000000000396> 
0x00007ffeefbff668: <0x0000000004ab4a40  0x00007ffeefbff690 
0x00007ffeefbff678:  0x00007ffeefbff6e8  0x0000000004027c26 <runtime.(*mheap).allocSpan+0x0000000000000546> 
0x00007ffeefbff688:  0x000000c0002d2000  0x0000000000002000 
0x00007ffeefbff698:  0x0000000000000008  0x00007ffeefbff6f8 
0x00007ffeefbff6a8:  0x00007ffeefbff6f0 !0x00007fff68e1170a 
0x00007ffeefbff6b8: >0x00007ffeefbff6f0  0x00000000051c4000 
0x00007ffeefbff6c8:  0x00000000000004ae  0x00000000043ed265 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005> 
0x00007ffeefbff6d8:  0x000000000406ccdf <runtime.syscall+0x000000000000001f>  0x000000c0001a5710 
0x00007ffeefbff6e8:  0x000000000406c64c <runtime.nanotime_trampoline+0x000000000000000c>  0x000000c0001a56e0 
0x00007ffeefbff6f8:  0x000000000406ab10 <runtime.asmcgocall+0x0000000000000070>  0x0000000000000001 
0x00007ffeefbff708:  0x0000000004001200  0x1200000000001018 
0x00007ffeefbff718:  0x0000000000000000  0x000000000527ecb8 
0x00007ffeefbff728:  0x0000000000000948  0x000000c0000001a0 
0x00007ffeefbff738:  0x0000000004068c29 <runtime.systemstack+0x0000000000000049>  0x0000000000000004 
0x00007ffeefbff748:  0x0000000004ba98b0  0x000000000524a1a0 
0x00007ffeefbff758:  0x00007ffeefbff7a0  0x0000000004068b25 <runtime.mstart+0x0000000000000005> 
0x00007ffeefbff768:  0x0000000004068add <runtime.rt0_go+0x000000000000013d> 
runtime.sigpanic()
        /usr/local/Cellar/go/1.17/libexec/src/runtime/signal_unix.go:719 +0x396

goroutine 1 [syscall, locked to thread]:
syscall.syscall(0x43ed260, 0x1, 0x40487413, 0xc0001a57a0)
        /usr/local/Cellar/go/1.17/libexec/src/runtime/sys_darwin.go:22 +0x3b fp=0xc0001a5710 sp=0xc0001a56f0 pc=0x40676db
syscall.syscall(0x4076106, 0x8, 0xc0001a57c8, 0x4076038)
        <autogenerated>:1 +0x26 fp=0xc0001a5758 sp=0xc0001a5710 pc=0x406d4a6
golang.org/x/sys/unix.ioctl(0x4a8cf40, 0x4, 0x10000000000c8)
        .../vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go:690 +0x39 fp=0xc0001a5788 sp=0xc0001a5758 pc=0x43eca59
golang.org/x/sys/unix.IoctlGetTermios(...)
        .../vendor/golang.org/x/sys/unix/ioctl.go:73
github.com/mattn/go-isatty.IsTerminal(0x4a8cf40)
        .../vendor/github.com/mattn/go-isatty/isatty_bsd.go:10 +0x50 fp=0xc0001a57f8 sp=0xc0001a5788 pc=0x471c4d0
github.com/fatih/color.init()
        .../vendor/github.com/fatih/color/color.go:21 +0x7a fp=0xc0001a5830 sp=0xc0001a57f8 pc=0x471e4fa
runtime.doInit(0x51ce260)
        /usr/local/Cellar/go/1.17/libexec/src/runtime/proc.go:6498 +0x123 fp=0xc0001a5968 sp=0xc0001a5830 pc=0x40467c3
runtime.doInit(0x51d2f60)
        /usr/local/Cellar/go/1.17/libexec/src/runtime/proc.go:6475 +0x71 fp=0xc0001a5aa0 sp=0xc0001a5968 pc=0x4046711
runtime.doInit(0x51d4020)
        /usr/local/Cellar/go/1.17/libexec/src/runtime/proc.go:6475 +0x71 fp=0xc0001a5bd8 sp=0xc0001a5aa0 pc=0x4046711
runtime.doInit(0x51d3bc0)
        /usr/local/Cellar/go/1.17/libexec/src/runtime/proc.go:6475 +0x71 fp=0xc0001a5d10 sp=0xc0001a5bd8 pc=0x4046711
runtime.doInit(0x51c8060)
        /usr/local/Cellar/go/1.17/libexec/src/runtime/proc.go:6475 +0x71 fp=0xc0001a5e48 sp=0xc0001a5d10 pc=0x4046711
runtime.doInit(0x51c8560)
        /usr/local/Cellar/go/1.17/libexec/src/runtime/proc.go:6475 +0x71 fp=0xc0001a5f80 sp=0xc0001a5e48 pc=0x4046711
runtime.main()
        /usr/local/Cellar/go/1.17/libexec/src/runtime/proc.go:238 +0x1e6 fp=0xc0001a5fe0 sp=0xc0001a5f80 pc=0x4039506
runtime.goexit()
        /usr/local/Cellar/go/1.17/libexec/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0001a5fe8 sp=0xc0001a5fe0 pc=0x406ae01
```

**Comment by fsouza** [comment]
See https://github.com/golang/go/issues/47776#issuecomment-901385865

**Comment by crcms** [comment]
@fsouza thanks
