### ISSUE TITLE
x/tools/go/ssa: panic with Go 1.17 slice-to-array conversions when converting to a newtype

### ISSUE THREAD

**Issue by ainar-g** [golang/go#48281]
This is probably related to #46987.  Consider this code:

```go
package main

import (
	"fmt"
)

type arr [2]int

func main() {
	s := []int{1, 2, 3, 4}
	fmt.Println(*(*arr)(s))
}
```

This program works and produces the intended output with Go 1.17.  But checking it with any SSA-based analyser seems to trigger a panic.  For example, using `nilness`:

```none
goroutine 195 [running]:
golang.org/x/tools/go/ssa.emitConv(0xc0000fac80, {0x7c6120, 0xc00049cea0}, {0x7bf368, 0xc000078810})
        /home/ainar/go/pkg/mod/golang.org/x/tools@v0.1.6-0.20210908235426-076821bd2bbc/go/ssa/emit.go:252 +0x8ee
golang.org/x/tools/go/ssa.(*builder).expr0(0x6fe800, 0xc0000fac80, {0x7bfac8, 0xc0001163c0}, {0x7, {0x7bf368, 0xc000078810}, {0x0, 0x0}})
        /home/ainar/go/pkg/mod/golang.org/x/tools@v0.1.6-0.20210908235426-076821bd2bbc/go/ssa/builder.go:573 +0x925
golang.org/x/tools/go/ssa.(*builder).expr(0x0, 0xc0000fac80, {0x7bfac8, 0xc0001163c0})
        /home/ainar/go/pkg/mod/golang.org/x/tools@v0.1.6-0.20210908235426-076821bd2bbc/go/ssa/builder.go:530 +0x19f
```

But if you replace a newtype with a type alias, it works:

```diff
-type arr [2]int
+type arr = [2]int
```

**Comment by ainar-g** [comment]
Thanks again for a quick response!  I confim that the issue is fixed on the `master` branch.
