### ISSUE TITLE
x/playground: Faking the network example periodically deadlocking

### ISSUE THREAD

**Issue by matthewmueller** [golang/go#48394]
### Problem

While reading about how "Faking the Network" works on the Go playground at https://go.dev/blog/playground, I'm running into this error the following error almost every time. 

```
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7f5332a0ee88, 0x72)
	/usr/local/go-faketime/src/runtime/netpoll.go:229 +0x89
internal/poll.(*pollDesc).wait(0xc0000c0000, 0x0, 0x0)
	/usr/local/go-faketime/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go-faketime/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc0000c0000)
	/usr/local/go-faketime/src/internal/poll/fd_unix.go:402 +0x22c
net.(*netFD).accept(0xc0000c0000)
	/usr/local/go-faketime/src/net/fd_unix.go:173 +0x35
net.(*TCPListener).accept(0xc0000ac030)
	/usr/local/go-faketime/src/net/tcpsock_posix.go:140 +0x28
net.(*TCPListener).Accept(0xc0000ac030)
	/usr/local/go-faketime/src/net/tcpsock.go:262 +0x3d
main.main()
	/tmp/sandbox825819739/prog.go:24 +0x102
```

Here's a screenshot:

![CleanShot 2021-09-14 at 22 40 49](https://user-images.githubusercontent.com/170299/133366905-64f164ff-458a-4416-9067-4025ff002c06.png)

It does occassionally work and responds with with `Hello, network`.

**Comment by seankhliao** [comment]
cc @toothrot

**Comment by toothrot** [comment]
Thanks, this is likely a bug in the faketime patch, as you mentioned. Our new(-ish) sandbox containers do not require the faketime patch anymore, but we've yet to remove it from Go, or update the playground for its removal, as it also impacts how program output is parsed.

I'm not positive on any ETA for resolving this.

**Comment by bcap** [comment]
Recent reddit thread on r/golang about this: https://www.reddit.com/r/golang/comments/y1z0he/headscratching_deadlock_problem/

**Comment by bcap** [comment]
> Our new(-ish) sandbox containers do not require the faketime patch anymore, but we've yet to remove it from Go, or update the playground for its removal, as it also impacts how program output is parsed.

@toothrot this was roughly 1y ago. How is the situation now? Can faketime be removed from golang playground?
