### ISSUE TITLE
cmd/compile: internal compiler error: Unexpected op with CALL during stenciling: CONVNOP

### ISSUE THREAD

**Issue by tdakkota** [golang/go#48604]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.18-d413908320 Fri Sep 24 07:22:13 2021 +0000 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
No

### What operating system and processor architecture are you using (`go env`)?

- `windows/amd64`
- `linux/amd64` (godbolt)

### What did you do?

https://play.golang.org/p/4dJ8lJioCVH

https://go.godbolt.org/z/vMGjY15b3

### What did you expect to see?

Successful compilation.

### What did you see instead?

<details>
  <summary> Stack trace  </summary> 

```
example.go:14:28: internal compiler error: Unexpected op with CALL during stenciling: CONVNOP

goroutine 1 [running]:
runtime/debug.Stack()
	/root/master/go/src/runtime/debug/stack.go:24 +0x65
cmd/compile/internal/base.FatalfAt({0xcfc280, 0x0}, {0xc0000aaa80, 0x32}, {0x0, 0x0, 0x0})
	/root/master/go/src/cmd/compile/internal/base/print.go:227 +0x154
cmd/compile/internal/noder.(*subster).node.func1({0xe4d818, 0xc0003163f0})
	/root/master/go/src/cmd/compile/internal/noder/stencil.go:1097 +0xba8
cmd/compile/internal/ir.(*ConvExpr).editChildren(0xc0003d1c20, 0xc0003d4108)
	/root/master/go/src/cmd/compile/internal/ir/node_gen.go:445 +0x58
cmd/compile/internal/ir.EditChildren(...)
	/root/master/go/src/cmd/compile/internal/ir/visit.go:185
cmd/compile/internal/noder.(*subster).node.func1({0xe4dd90, 0xc0003d0be0})
	/root/master/go/src/cmd/compile/internal/noder/stencil.go:955 +0x448
cmd/compile/internal/ir.(*AssignStmt).editChildren(0xc0003d1bd0, 0xc0003d4108)
	/root/master/go/src/cmd/compile/internal/ir/node_gen.go:163 +0xb5
cmd/compile/internal/ir.EditChildren(...)
	/root/master/go/src/cmd/compile/internal/ir/visit.go:185
cmd/compile/internal/noder.(*subster).node.func1({0xe4d430, 0xc0003d0b90})
	/root/master/go/src/cmd/compile/internal/noder/stencil.go:955 +0x448
cmd/compile/internal/noder.(*subster).node(0xc0003d3a40, {0xe4d430, 0xc0003d0b90})
	/root/master/go/src/cmd/compile/internal/noder/stencil.go:1166 +0xa5
cmd/compile/internal/noder.(*subster).list(0x13b9620, {0xc0003c2ca0, 0x2, 0xc0000805a0})
	/root/master/go/src/cmd/compile/internal/noder/stencil.go:1418 +0x8e
cmd/compile/internal/noder.(*irgen).genericSubst(0xc0003ce000, 0xc0003d1a90, 0xc0003cd1e0, {0xc0000ac808, 0x1, 0x1}, 0x0, 0xc0003d40a8)
	/root/master/go/src/cmd/compile/internal/noder/stencil.go:762 +0xce6
cmd/compile/internal/noder.(*irgen).getInstantiation(0xc0003ce000, 0xc0003cd1e0, {0xc0000ac800, 0x1, 0x1}, 0xc8)
	/root/master/go/src/cmd/compile/internal/noder/stencil.go:640 +0x2b0
cmd/compile/internal/noder.(*irgen).stencil.func1({0xe4d818, 0xc000316480})
	/root/master/go/src/cmd/compile/internal/noder/stencil.go:108 +0x2df
cmd/compile/internal/ir.Visit.func1({0xe4d818, 0xc000316480})
	/root/master/go/src/cmd/compile/internal/ir/visit.go:105 +0x30
cmd/compile/internal/ir.doNodes({0xc00008d340, 0x1, 0x0}, 0xc0003d4090)
	/root/master/go/src/cmd/compile/internal/ir/node_gen.go:1512 +0x67
cmd/compile/internal/ir.(*Func).doChildren(0xe4e178, 0xc0003bec60)
	/root/master/go/src/cmd/compile/internal/ir/func.go:152 +0x2e
cmd/compile/internal/ir.DoChildren(...)
	/root/master/go/src/cmd/compile/internal/ir/visit.go:94
cmd/compile/internal/ir.Visit.func1({0xe4e178, 0xc0003bec60})
	/root/master/go/src/cmd/compile/internal/ir/visit.go:106 +0x57
cmd/compile/internal/ir.Visit({0xe4e178, 0xc0003bec60}, 0xc0003ca680)
	/root/master/go/src/cmd/compile/internal/ir/visit.go:108 +0xb8
cmd/compile/internal/noder.(*irgen).stencil(0xc0003ce000)
	/root/master/go/src/cmd/compile/internal/noder/stencil.go:90 +0x238
cmd/compile/internal/noder.(*irgen).generate(0xc0003ce000, {0xc00008cb40, 0x2, 0xb})
	/root/master/go/src/cmd/compile/internal/noder/irgen.go:301 +0x359
cmd/compile/internal/noder.check2({0xc00008cb40, 0x2, 0x2})
	/root/master/go/src/cmd/compile/internal/noder/irgen.go:93 +0x175
cmd/compile/internal/noder.LoadPackage({0xc0000b2110, 0x2, 0x0})
	/root/master/go/src/cmd/compile/internal/noder/noder.go:90 +0x335
cmd/compile/internal/gc.Main(0xd0ba30)
	/root/master/go/src/cmd/compile/internal/gc/main.go:190 +0xaf3
main.main()
	/root/master/go/src/cmd/compile/main.go:55 +0xdd
```
</details>

**Comment by ALTree** [comment]
cc @randall77 @danscales
