### ISSUE TITLE
os: on NetBSD, *Process.Wait sometimes deadlocks after cmd.Process.Signal returns "process already finished"

### ISSUE THREAD

**Issue by bcmills** [golang/go#48789]
I've noticed a recurring pattern in `cmd/go` test failures on NetBSD builders, and I believe that it indicates a bug in either `os.Process` or the kernel itself on that platform.

The `cmd/go` tests start processes running “in the background” using `os/exec`, and use a [`waitOrStop`](https://github.com/golang/go/blob/a05a7d49a9b7975d89bc5851cff55b64f64242c3/src/cmd/go/script_test.go#L1149-L1208) function to terminate any remaining processes at the conclusion of each test.

The `waitOrStop` function starts a goroutine, then blocks on `cmd.Wait()`. The background goroutine blocks until either the call to `cmd.Wait` completes or the `Context` is canceled, then sends a signal to the process. If that signal fails with `os: process already finished`, then we assume that the process actually _has_ already finished, and the background goroutine simply blocks until the call to `cmd.Wait` (inevitably) returns.

That all happens here:
https://github.com/golang/go/blob/a05a7d49a9b7975d89bc5851cff55b64f64242c3/src/cmd/go/script_test.go#L1164-L1206

----

What I'm seeing on (some of?) the NetBSD builders is that after `cmd.Process.Signal` fails with `process already finished`, the call to `cmd.Wait` continues to block, seemingly forever.

The relevant goroutine traces are:
```
goroutine 1536 [syscall, 8 minutes]:
syscall.Syscall6(0x42d7, 0x9117f20, 0x0, 0x8f1a5a0, 0x0, 0x0, 0x0)
	/tmp/workdir/go/src/syscall/asm_unix_386.s:44 +0x5 fp=0x9117ecc sp=0x9117ec8 pc=0x80bc1e5
syscall.wait4(0x42d7, 0x9117f20, 0x0, 0x8f1a5a0)
	/tmp/workdir/go/src/syscall/zsyscall_netbsd_386.go:35 +0x5b fp=0x9117f04 sp=0x9117ecc pc=0x80b8f3b
syscall.Wait4(0x42d7, 0x9117f44, 0x0, 0x8f1a5a0)
	/tmp/workdir/go/src/syscall/syscall_bsd.go:145 +0x3b fp=0x9117f28 sp=0x9117f04 pc=0x80b6abb
os.(*Process).wait(0x8e98150)
	/tmp/workdir/go/src/os/exec_unix.go:44 +0xf2 fp=0x9117f60 sp=0x9117f28 pc=0x80e2762
os.(*Process).Wait(...)
	/tmp/workdir/go/src/os/exec.go:132
os/exec.(*Cmd).Wait(0x8c7bc30)
	/tmp/workdir/go/src/os/exec/exec.go:507 +0x4d fp=0x9117f9c sp=0x9117f60 pc=0x817eedd
cmd/go_test.waitOrStop({0x874073c, 0x8dc2300}, 0x8c7bc30, {0x873f89c, 0x869bd38}, 0x6472661e3)
	/tmp/workdir/go/src/cmd/go/script_test.go:1203 +0x11a fp=0x9117fc0 sp=0x9117f9c pc=0x85800ea
cmd/go_test.(*testScript).startBackground.func1()
	/tmp/workdir/go/src/cmd/go/script_test.go:1143 +0x5f fp=0x9117ff0 sp=0x9117fc0 pc=0x857ff8f
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_386.s:1311 +0x1 fp=0x9117ff4 sp=0x9117ff0 pc=0x80ab241
created by cmd/go_test.(*testScript).startBackground
	/tmp/workdir/go/src/cmd/go/script_test.go:1142 +0x390

goroutine 1537 [chan send, 8 minutes]:
runtime.gopark(0x869b798, 0x8dbc430, 0xf, 0x16, 0x2)
	/tmp/workdir/go/src/runtime/proc.go:366 +0xf6 fp=0x90e8f04 sp=0x90e8ef0 pc=0x807f376
runtime.chansend(0x8dbc400, 0x87302f0, 0x1, 0x8580314)
	/tmp/workdir/go/src/runtime/chan.go:258 +0x2f4 fp=0x90e8f48 sp=0x90e8f04 pc=0x804db54
runtime.chansend1(0x8dbc400, 0x87302f0)
	/tmp/workdir/go/src/runtime/chan.go:144 +0x24 fp=0x90e8f60 sp=0x90e8f48 pc=0x804d854
cmd/go_test.waitOrStop.func1()
	/tmp/workdir/go/src/cmd/go/script_test.go:1176 +0x184 fp=0x90e8ff0 sp=0x90e8f60 pc=0x8580314
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_386.s:1311 +0x1 fp=0x90e8ff4 sp=0x90e8ff0 pc=0x80ab241
created by cmd/go_test.waitOrStop
	/tmp/workdir/go/src/cmd/go/script_test.go:1165 +0x10e
```

Note that goroutine 1537 is blocked at `script_test.go:1176`, which is the send on `errc` after `cmd.Process.Signal` fails with `os: process already finished`.

Goroutine 1536 is blocked at the call to `cmd.Wait`, which is itself blocked on `syscall.Wait4`.

----

The failure rate with these symptoms is fairly high: something on the order of 20 failures per month.

`greplogs --dashboard -md -l -e '(?m)panic: test timed out.*(?:.*\n)*.*\[syscall, .* minutes\]:\n(?:.+\n\t.+\n)*syscall\.Wait.*\n\t.+\n(?:.+\n\t.+\n)*cmd/go_test\.waitOrStop'`

<details>

[2021-10-04T22:46:23-17674e2/netbsd-386-9_0](https://build.golang.org/log/35759db67babf226768cb78d8934f427fe16b4ab)
[2021-10-04T18:15:09-9f8d558/netbsd-386-9_0](https://build.golang.org/log/ea38acf730200c9efeeaaa4c6b16c265ccdca471)
[2021-09-30T19:56:06-eb9f090/netbsd-386-9_0](https://build.golang.org/log/1c51fcffff88f079b1544ccaed797e754ca16d61)
[2021-09-29T15:23:27-aeb4fba/netbsd-amd64-9_0](https://build.golang.org/log/31b5c670489b6a8194b91b0823508b79312912a7)
[2021-09-28T17:18:36-ff7b041/netbsd-amd64-9_0](https://build.golang.org/log/864a5b837701786eb5a093db3075ab2ed1bebc15)
[2021-09-28T15:26:21-583eeaa/netbsd-386-9_0](https://build.golang.org/log/f652f9875b9d24f03b774c467ee434b734539acc)
[2021-09-27T18:57:20-3d795ea/netbsd-amd64-9_0](https://build.golang.org/log/fb469bc0f0623083002ec8ff549da69e5f6fb857)
[2021-09-22T16:24:17-74ba70b/netbsd-amd64-9_0](https://build.golang.org/log/70073dfb40f2969a3466596e3bf59a4a4ccd9d87)
[2021-09-22T15:00:53-91c2318/netbsd-amd64-9_0](https://build.golang.org/log/27fe7e87708b07220b8aff699a6d5e9522cb2019)
[2021-09-21T20:39:31-48cf96c/netbsd-386-9_0](https://build.golang.org/log/7802c58d814ac0809073feaf13e565838dfc1efc)
[2021-09-20T23:04:13-d7e3e44/netbsd-arm64-bsiegert](https://build.golang.org/log/2ef51366a79a63d6bab6163a94d87cb74d97e530)
[2021-09-20T00:13:47-a83a558/netbsd-amd64-9_0](https://build.golang.org/log/5ab6db36b8e9b8367af7bf88aedd1ae18c9579e8)
[2021-09-17T19:32:44-74e384f/netbsd-amd64-9_0](https://build.golang.org/log/56a0391848189e1dc27ad3c5c8557d56d0b21da2)
[2021-09-16T23:57:40-8d2a9c3/netbsd-386-9_0](https://build.golang.org/log/e9a5d43e7011f081f07f9100659c1aff7107da7b)
[2021-09-16T19:38:19-bcdc61d/netbsd-amd64-9_0](https://build.golang.org/log/cea044ddf4e1ac685ab1a2117b4005dc5c50cbb5)
[2021-09-10T17:11:39-5a4b9f9/netbsd-amd64-9_0](https://build.golang.org/log/0a7fb96a25fc6a092c1722164f05b0d477ce7233)
[2021-09-09T16:32:28-a53e3d5/netbsd-amd64-9_0](https://build.golang.org/log/2cf5fabbf0f621fb0be56879827d957954fabd7d)
[2021-09-08T11:57:03-9295723/netbsd-386-9_0](https://build.golang.org/log/297c9f9f6fba30c33247f8261dcb9d2a0610c4e5)
[2021-09-07T03:56:13-6226020/netbsd-386-9_0](https://build.golang.org/log/a670549c2176a6cabc70534361b58f5c768f8e17)
[2021-09-04T10:58:11-5ec298d/netbsd-386-9_0](https://build.golang.org/log/c2a82180b5599f61b223b0bb56c589adcb128c42)
[2021-08-31T16:43:46-6815235/netbsd-386-9_0](https://build.golang.org/log/83a9b2f695b88fb0055c3f1cddb8857f59140ac9)
[2021-08-30T22:07:49-b06cfe9/netbsd-386-9_0](https://build.golang.org/log/556956cccde2fc6dcf337853b7baadb5439884b7)
[2021-08-27T05:13:44-2c60a99/netbsd-386-9_0](https://build.golang.org/log/52456c13eafebc2fe3568aa3318c56031bc8fc00)
[2021-08-24T22:23:12-54cdef1/netbsd-386-9_0](https://build.golang.org/log/d60078b1bd2a31a18c30dea7d48dce7dc484937f)
[2021-08-23T21:22:58-8157960/netbsd-386-9_0](https://build.golang.org/log/23b7225a903214a191f5c6b22a6ad3dd82662519)
[2021-08-23T21:22:58-8157960/netbsd-arm64-bsiegert](https://build.golang.org/log/0cb1bc422186729ee0f31a3e566311db7cc14251)
[2021-08-22T21:43:43-1958582/netbsd-386-9_0](https://build.golang.org/log/c3946a2da37e2c7c7d191911dd1f7fd3414a9561)
[2021-08-20T03:25:17-c92c2c9/netbsd-386-9_0](https://build.golang.org/log/c364e366977c5837be757678b2757f64e85c7342)
[2021-08-19T20:50:13-65074a4/netbsd-amd64-9_0](https://build.golang.org/log/faad96d5f15fab0456c212e4c615e3a7fa18dd56)
[2021-08-18T21:19:22-c2bd9ee/netbsd-386-9_0](https://build.golang.org/log/a271686423f66fe06a52a12ea3a1339d43571d09)
[2021-08-18T20:11:28-165ebd8/netbsd-386-9_0](https://build.golang.org/log/2ad9832d1160e038f48daf01e0d25db468a36adf)
[2021-08-17T16:22:15-cf12b0d/netbsd-386-9_0](https://build.golang.org/log/4e6a0f1a78481ddde73b406156c025c8ebe242a0)
[2021-08-17T15:00:04-3001b0a/netbsd-386-9_0](https://build.golang.org/log/c5770eee6b4539acc66ed2624a364561bf91921c)
[2021-08-17T04:37:32-a304273/netbsd-386-9_0](https://build.golang.org/log/1e106aa18562f56d18161c71960ea6d7d849a8af)
[2021-08-17T01:29:37-1951afc/netbsd-386-9_0](https://build.golang.org/log/9f70ce94b775eec654d740ad22d0f87c3e0f9ac2)
[2021-08-16T18:44:38-56a919f/netbsd-386-9_0](https://build.golang.org/log/13dda6ae5c1eacdf87ab31a03c4c27fdc98f3202)
[2021-08-16T18:44:32-ff36d11/netbsd-amd64-9_0](https://build.golang.org/log/24f92e7f39b71ddefb7c8e24040f494d3f9bd6db)
[2021-08-16T13:38:52-a192ef8/netbsd-386-9_0](https://build.golang.org/log/85b9971f3bd1a47e4e79c68fb059075559b5ac8d)
[2021-08-12T17:43:16-39634e7/netbsd-386-9_0](https://build.golang.org/log/1353091958def0b190cd3c818ab72492525e2dfa)
[2021-08-09T20:06:35-f1dce31/netbsd-386-9_0](https://build.golang.org/log/63fee0b5078619091e28619bdd6cdc0b11c7227e)
[2021-08-06T16:51:12-70546f6/netbsd-386-9_0](https://build.golang.org/log/2dda0b83e6017b58955cc8f58f266e1c1f1c6320)
[2021-07-28T03:27:13-b39e0f4/netbsd-386-9_0](https://build.golang.org/log/ff7e1913a37add7a2df7eecc87c55c026be6220f)
[2021-07-15T20:39:22-0941dbc/netbsd-amd64-9_0](https://build.golang.org/log/44cd66afb0a993cad395ebcc959ddc5cee98aff5)
[2021-06-29T16:57:13-3463852/netbsd-386-9_0](https://build.golang.org/log/5082af8e2ace9e4a440b380317f87b47eda0befe)
[2021-06-28T20:51:30-956c81b/netbsd-386-9_0](https://build.golang.org/log/97958c457becadf5e5e8fdb67559b76a989ed810)
[2021-06-24T03:45:33-a9bb382/netbsd-386-9_0](https://build.golang.org/log/53dc1b9f294e433c14463ae38959e86ed63ecbeb)
[2021-06-15T20:59:42-d77f4c0/netbsd-amd64-9_0](https://build.golang.org/log/155262b61fa1f95626f59cb21ecd18ce558e1287)
[2021-06-11T20:31:30-16b5d76/netbsd-386-9_0](https://build.golang.org/log/f11252fd4ec59759c43ef7ed05481d433f269758)
[2021-06-09T17:11:44-df35ade/netbsd-386-9_0](https://build.golang.org/log/837288e0ede6f125d6379e1f558d218f15029dcc)
[2021-06-09T15:09:13-139e935/netbsd-386-9_0](https://build.golang.org/log/cf93b94799cbef4117bb397055fbfb6c2242b78b)
[2021-05-21T17:43:46-4fda54c/netbsd-arm64-bsiegert](https://build.golang.org/log/c82d732b97b00830d6b1171e8509ed6ae9af9797)
[2021-05-21T17:35:47-8876b9b/netbsd-386-9_0](https://build.golang.org/log/7d2972f4e1eda6b80a23ace8833f8f4855824a13)
[2021-05-17T16:02:12-b1aff42/netbsd-386-9_0](https://build.golang.org/log/30fd24f45193fd423c8e3ba1b95d5135087ffec2)
[2021-05-12T15:23:09-0388670/netbsd-386-9_0](https://build.golang.org/log/61f06037b1e2d0bed7d63de1dbd00c661aa20c76)
[2021-05-12T02:04:57-1a0ea1a/netbsd-386-9_0](https://build.golang.org/log/02e138919461c79af9c09f1fcd1e6f5df4151b3f)
[2021-05-11T18:22:54-9b84814/netbsd-386-9_0](https://build.golang.org/log/906c24cdc8cf2583e3238eb97e2bccbff462fd95)
[2021-05-10T13:16:56-2870259/netbsd-386-9_0](https://build.golang.org/log/c141c93e5fca7417eb37c4880e0da769db80ee2f)
[2021-05-06T16:00:55-6c591f7/netbsd-386-9_0](https://build.golang.org/log/a8488dd86bf176258f61bad24fc292261207bd70)
[2020-09-19T05:13:19-ccf581f/netbsd-386-9_0](https://build.golang.org/log/2ab0f954e1dc493ae7d9639f131cf5ee0c1eb8bd)

</details>

**Comment by bcmills** [comment]
@bsiegert, @coypoop: do you know who might be able to look into this on the NetBSD side?

@ianlancetaylor, @tklauser: is this possibly related to #13987?

**Comment by bcmills** [comment]
#44801 may be related, in that it involves a hang in `os.Process.Wait`.

**Comment by ianlancetaylor** [comment]
I see two possible sequences that could lead to this.

First, `wait6(P_PID, p.Pid, nil, WEXITED|WNOWAIT, nil, nil)` might return with no error, and then `wait4(p.Pid, &status, 0, &rusage)` hangs without returning.

Second, `kill(p.Pid, SIGQUIT)` might return `ESRCH`, but `wait4(p.Pid, &status, 0, &rusage)` might hang without returning.

Neither should be possible.  The first case seems more likely.  If we don't see a response from somebody familiar with NetBSD we should probably move the `netbsd` build tag from os/wait_wait6.go to os/wait_unimp.go.  CC @tklauser since CL 315281 changed the os package to start using wait_wait6.go on NetBSD.

**Comment by tklauser** [comment]
The first case seems more likely to me too, given that the failure seems to have started occuring only after https://golang.org/cl/315281 was submitted on 2021-05-02.

I'll send a CL to move the `netbsd` build tag from os/wait_wait6.go to os/wait_unimp.go.

**Comment by bsiegert** [comment]
@bcmills Have you seen more deadlocks since the commit above landed at the beginning of October?

**Comment by bcmills** [comment]
Looks like the deadlocks ended at that CL. 👍

The only failures I can find involving `cmd/go_test.waitOrStop` since Oct. 6 look like memory corruption (#49209) rather than deadlocks.

`greplogs --dashboard -md -l -e \(\?ms\)\\Anetbsd.\*cmd/go_test\\.waitOrStop --since=2021-10-06`

[2021-11-05T16:51:14-c58417b/netbsd-amd64-9_0](https://build.golang.org/log/e6e5649c7ba431896f930ad83c1a303d58681b40)
[2021-11-04T20:24:01-99699d1/netbsd-386-9_0](https://build.golang.org/log/2a2b1ef9a95bb76b651463c4e1d7b2be24ddafc8)
[2021-11-03T19:32:33-74f99d0/netbsd-amd64-9_0](https://build.golang.org/log/60cc5ce0383bf39465d9fc551989700451ca05ce)
[2021-10-27T21:34:46-de1abf7/netbsd-386-9_0](https://build.golang.org/log/ebefc504a5071f1c1032d7495205481e46e30069)
[2021-10-19T07:45:46-ee92daa/netbsd-amd64-9_0](https://build.golang.org/log/bb08435ad7fc32de871ae7c2bad605450f9e9c95)
[2021-10-06T23:19:38-f375844/netbsd-amd64-9_0](https://build.golang.org/log/e253402ecf83682feae5291993a504819504fafa)
[2021-10-06T23:01:01-4ffa2f1/netbsd-amd64-9_0](https://build.golang.org/log/1e0d805a8abc461840da2d88a14f4504acc31f28)
[2021-10-06T20:30:12-4a37a1d/netbsd-amd64-9_0](https://build.golang.org/log/48a4ac48c676046ad1a52109771b1c4d25a2d6e9)
[2021-10-06T20:21:49-f580b75/netbsd-386-9_0](https://build.golang.org/log/5943ee002529ce19023d34dcab8f13a18546969c)

**Comment by bcmills** [comment]
We believe that the `netbsd-amd64-9_0-n2` builder is not affected by #49209, so it looks like this deadlock still occurs.

`greplogs --dashboard -md -l -e '(?ms)\Anetbsd-[a-z0-9_-]+-n2 .*cmd/go_test\.waitOrStop' --since=2021-11-01`

[2021-12-14T01:48:22-1afa432/netbsd-amd64-9_0-n2](https://build.golang.org/log/7bafbacead14697c696cafdd52cb8a4bb177db23)

```
goroutine 3696 [chan receive, 2 minutes]:
runtime.gopark(0x18?, 0xf1ed60?, 0x0?, 0xc0?, 0x0?)
	/tmp/workdir/go/src/runtime/proc.go:366 +0xd6 fp=0xc000597e10 sp=0xc000597df0 pc=0x438c96
runtime.chanrecv(0xc00092a600, 0xc000597f20, 0x1)
	/tmp/workdir/go/src/runtime/chan.go:577 +0x56c fp=0xc000597ea0 sp=0xc000597e10 pc=0x407b4c
runtime.chanrecv1(0xc00002de00?, 0x38?)
	/tmp/workdir/go/src/runtime/chan.go:440 +0x18 fp=0xc000597ec8 sp=0xc000597ea0 pc=0x407578
os/exec.(*Cmd).Wait(0xc000824160)
	/tmp/workdir/go/src/os/exec/exec.go:515 +0x188 fp=0xc000597f40 sp=0xc000597ec8 pc=0x552168
cmd/go_test.waitOrStop({0xbd8d08?, 0xc00091d740}, 0xc000824160, {0xbd73e8?, 0xbd06c0}, 0x646b83877)
	/tmp/workdir/go/src/cmd/go/script_test.go:1288 +0x137 fp=0xc000597f90 sp=0xc000597f40 pc=0x9c0417
cmd/go_test.(*testScript).startBackground.func1()
	/tmp/workdir/go/src/cmd/go/script_test.go:1161 +0x4d fp=0xc000597fe0 sp=0xc000597f90 pc=0x9c004d
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000597fe8 sp=0xc000597fe0 pc=0x467f61
created by cmd/go_test.(*testScript).startBackground
	/tmp/workdir/go/src/cmd/go/script_test.go:1160 +0x43b

goroutine 3697 [chan send, 2 minutes]:
runtime.gopark(0x47cbb2?, 0x47ab18?, 0x25?, 0x0?, 0x50e6?)
	/tmp/workdir/go/src/runtime/proc.go:366 +0xd6 fp=0xc000443e28 sp=0xc000443e08 pc=0x438c96
runtime.chansend(0xc0000d49c0, 0xc000443f80, 0x1, 0xc000443eb8?)
	/tmp/workdir/go/src/runtime/chan.go:258 +0x425 fp=0xc000443eb0 sp=0xc000443e28 pc=0x406ca5
runtime.chansend1(0xc000443f90?, 0xbd73e8?)
	/tmp/workdir/go/src/runtime/chan.go:144 +0x1d fp=0xc000443ee0 sp=0xc000443eb0 pc=0x40685d
cmd/go_test.waitOrStop.func1()
	/tmp/workdir/go/src/cmd/go/script_test.go:1285 +0x2cf fp=0xc000443fe0 sp=0xc000443ee0 pc=0x9c07af
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000443fe8 sp=0xc000443fe0 pc=0x467f61
created by cmd/go_test.waitOrStop
	/tmp/workdir/go/src/cmd/go/script_test.go:1250 +0x12d
```

**Comment by bcmills** [comment]
Hmm, maybe not! That send is here:
https://cs.opensource.google/go/go/+/master:src/cmd/go/script_test.go;l=1285;drc=2580d0e08d5e9f979b943758d3c49877fb2324cb

which is not on the `os.ErrProcessDone` path.
