### ISSUE TITLE
cmd/compile: another "unreachable method called" bug

### ISSUE THREAD

**Issue by randall77** [golang/go#49049]
Another case where we're not marking methods as used correctly.

```
package main

type A[T any] interface {
	m()
}

type Z struct {
	a,b int
}

func (z *Z) m() {
}

func test[T any]() {
	var a A[T] = &Z{}
	f := a.m
	f()
}
func main() {
	test[string]()
}
```
```
$ go run ~/gowork/tmp1.go
fatal error: unreachable method called. linker bug?

goroutine 1 [running]:
runtime.throw({0x1063317, 0x100ac07})
	/Users/khr/sandbox/ro3/src/runtime/panic.go:965 +0x71 fp=0xc000052710 sp=0xc0000526e0 pc=0x102aa91
runtime.unreachableMethod()
	/Users/khr/sandbox/ro3/src/runtime/iface.go:525 +0x25 fp=0xc000052730 sp=0xc000052710 pc=0x1008925
main.A[...].m-fm()
	/Users/khr/gowork/tmp1.go:4 +0x2b fp=0xc000052748 sp=0xc000052730 pc=0x1053bab
main.test[...](...)
	/Users/khr/gowork/tmp1.go:16
main.main()
	/Users/khr/gowork/tmp1.go:19 +0x5f fp=0xc000052780 sp=0xc000052748 pc=0x1053b5f
runtime.main()
	/Users/khr/sandbox/ro3/src/runtime/proc.go:255 +0x227 fp=0xc0000527e0 sp=0xc000052780 pc=0x102d1a7
runtime.goexit()
	/Users/khr/sandbox/ro3/src/runtime/asm_amd64.s:1446 +0x1 fp=0xc0000527e8 sp=0xc0000527e0 pc=0x1050e81
```

@danscales @cherrymui

**Comment by danscales** [comment]
@randall77 

We transform the METHVALUE to a closure (in order to include the dictionary arg) in the "modify" pass, after stenciling.  So, the METHVALUE is available at the right time (after stenciling, hence right before the modify pass), but the reason why we are not setting "closureRequired" is because a is an interface (see IsInterfaceMethod() check in same line checking for OMETHVALUE around line 156 in stencil.go).  Since a is already an interface, we don't need to do the closure, right?  We just get the function from the itab (which will be a generic wrapper that includes the dictionary).

Maybe I'm missing something, but it seems like this is another example of a parameterized interface confusing the linker dead-code elimination (but in a slightly different way?)
