### ISSUE TITLE
x/build/maintner: nil pointer dereference panic during GoFindTryWork

### ISSUE THREAD

**Issue by dmitshur** [golang/go#49286]
maintnerd appears to be in a crash-loop due to:

```
2021/11/02 13:59:51 gerrit code.googlesource.com/gocloud: ran git ls-remote in 1.617s
2021/11/02 13:59:51 gerrit go.googlesource.com/playground: ran git ls-remote in 2.802s
2021/11/02 13:59:51 gerrit go.googlesource.com/go: ran git fetch origin in 8.233s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xa02274]

goroutine 1595 [running]:
golang.org/x/build/maintner.(*GerritProject).CL(...)
	/go/src/golang.org/x/build/maintner/gerrit.go:218
golang.org/x/build/maintner/maintnerd/maintapi.goFindTryWork({0xc94018, 0xc01fa804e0}, 0x0, 0xc0003a2360)
	/go/src/golang.org/x/build/maintner/maintnerd/maintapi/api.go:325 +0x374
golang.org/x/build/maintner/maintnerd/maintapi.apiService.GoFindTryWork({0xafa960}, {0xc94050, 0xc0188bfe90}, 0x10f8e08)
	/go/src/golang.org/x/build/maintner/maintnerd/maintapi/api.go:287 +0x2b7
golang.org/x/build/maintner/maintnerd/apipb._MaintnerService_GoFindTryWork_Handler({0xb5d9c0, 0xc0003a2360}, {0xc94050, 0xc0188bfe90}, 0xc000228690, 0x0)
	/go/src/golang.org/x/build/maintner/maintnerd/apipb/api.pb.go:820 +0x170
```

**Comment by bcmills** [comment]
Looks like the missing nil-check is here:
https://github.com/golang/build/blob/fd71dbe823f0b189f48e47111c2c2d425eb81f7b/maintner/maintnerd/maintapi/api.go#L325

Maybe a CL against a repo that `maintner` hasn't yet been updated to index?

**Comment by dmitshur** [comment]
This might be related to a new repository in the process of being added, and maintapi not supporting that case.

Sent [CL 360734](https://golang.org/cl/360734) for now.

**Comment by dmitshur** [comment]
This is mitigated so removing Soon label.
