### ISSUE TITLE
cmd/compile: nil pointer dereference panic in type2 on invalid tp instantiation

### ISSUE THREAD

**Issue by ALTree** [golang/go#49296]
```
$ gotip version
go version devel go1.18-58fb05a24a Tue Nov 2 16:19:52 2021 +0000 linux/amd64
```
```
package p

func f[T interface{[]int}]() {
	_ = T(1)
}
```
```
$ gotip tool compile test.go

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xb6f288]

goroutine 1 [running]:
cmd/compile/internal/types2.(*Checker).handleBailout(0xc000404c60, 0xc000117648)
	/home/alberto/go/src/cmd/compile/internal/types2/check.go:271 +0x8b
panic({0xc955a0, 0x12ecd50})
	/home/alberto/go/src/runtime/panic.go:838 +0x207
cmd/compile/internal/types2.is({0xe79c10?, 0x0?}, 0x2)
	/home/alberto/go/src/cmd/compile/internal/types2/predicates.go:31 +0x48
cmd/compile/internal/types2.isInteger(...)
....
```

cc @griesemer

**Comment by griesemer** [comment]
Minor oversight. Fix forthcoming.
