### ISSUE TITLE
net/http: failures ending in "Timeout." in testTransportAndServerSharedBodyRace

### ISSUE THREAD

**Issue by bcmills** [golang/go#49336]
```
#!watchflakes
post <- pkg == "net/http" && `testTransportAndServerSharedBodyRace` && `Timeout\.$`
```

These failures are rare but ongoing.

```
2021/11/03 22:22:26 httptest.Server blocked in Close after 5 seconds, waiting for connections:
  *net.TCPConn 0x14000528240 127.0.0.1:59158 in state active
1 second passes in backend, proxygone= false
goroutine 10950 [running]:
net/http_test.testTransportAndServerSharedBodyRace.func5.1()
	/tmp/buildlet/go/src/net/http/serve_test.go:3959 +0x54
created by time.goFunc
	/tmp/buildlet/go/src/time/sleep.go:176 +0x3c
…
2021/11/03 22:22:28 Timeout.
FAIL	net/http	10.800s
```

`greplogs --dashboard -md -l -e \(\?ms\)testTransportAndServerSharedBodyRace.\*Timeout\\.\$`

[2021-11-04T02:12:52-bd49a99/darwin-arm64-11_0-toothrot](https://build.golang.org/log/c449b18967d58a400f6e67513defacf822be347b)
[2021-10-01T14:30:33-8d494b0/linux-riscv64-jsing](https://build.golang.org/log/f5d424cb11f731a65822e989ea0cfa3866e4a525)
[2021-09-28T18:58:50-9c43872/linux-riscv64-jsing](https://build.golang.org/log/9e059d006a9c186fd2ba52481d21da50a227da4b)
[2021-09-02T09:25:10-6705191/linux-riscv64-jsing](https://build.golang.org/log/50015677417f31be72a081d9cd36fa9feb54e504)
[2021-08-21T11:23:14-8fff20f/netbsd-arm-bsiegert](https://build.golang.org/log/51f85e1eb7bb47fbd56f4097c2df467e3f51e107)
[2020-10-20T17:53:02-10a1a1a/darwin-amd64-race](https://build.golang.org/log/91d8623e3926bc75d0d8ae23495560d202ba9081)
[2020-10-01T19:13:03-5756b35/darwin-amd64-race](https://build.golang.org/log/ce3499c569a0c13f93e034799e04f68278f16afe)
[2020-08-24T06:03:06-ffbd852/darwin-amd64-nocgo](https://build.golang.org/log/57dbaccdf7209897c8101982e208de4935011767)
[2020-04-28T19:49:53-71e0cd8/darwin-amd64-race](https://build.golang.org/log/61b2f5f17b78476c2bd6386f357153732539344b)

CC @neild

**Comment by neild** [comment]
Might just be slow/overloaded machines taking more than 5s to `Close` a server? Perhaps we should just triple the timeout and see if the problem goes away.

**Comment by bcmills** [comment]
I'll be pretty surprised if that fixes it, but it at least seems worth trying!

**Comment by bcmills** [comment]
`watchflakes` found another one of these in #57600 (CC @neild).

**Comment by bcmills** [comment]
This particular failure mode should be fixed by [CL 476035](https://go.dev/cl/476035). It is possible that that will uncover further failure modes, but `watchflakes` can file issues for those if they occur.

**Comment by bcmills** [comment]
`e175f27f` is on `release-branch.go1.20` (#59483)
