### ISSUE TITLE
runtime: apparent deadlock in TestPanicSystemstack

### ISSUE THREAD

**Issue by bcmills** [golang/go#49388]
`greplogs --dashboard -md -l -e \(\?m\)io\\.ReadFull.\*\\n\\t.\*\\nruntime_test\\.TestPanicSystemstack`

[2021-11-04T23:35:26-256a8fc/linux-amd64-longtest](https://build.golang.org/log/6040766fe3e6b6605b90ed1dc717578a9fa02a78)
[2021-11-04T20:42:35-1f9dce7/linux-amd64-longtest](https://build.golang.org/log/c13f435f1b959dc811af3f3691d933d6b323afac)

(See previously #33626.)

@mknyszek, possibly another test issue relating to the GC pacing changes?

**Comment by mknyszek** [comment]
Possibly. I'll look into it.

**Comment by aclements** [comment]
Also on a trybot for [CL 361212](https://golang.org/cl/361212): https://storage.googleapis.com/go-build-log/7e5a8966/linux-amd64-longtest_e945e4f4.log

**Comment by mknyszek** [comment]
This is failing awfully consistently now, though I'm not sure why or what changed.

**Comment by mknyszek** [comment]
I can reproduce this locally on tip now.

**Comment by mknyszek** [comment]
OK! I have a stack trace from the subprocess that's getting stuck.

```
    crash_unix_test.go:187: subprocess failed; output:
         x
        SIGQUIT: quit
        PC=0x474481 m=0 sigcode=0

        goroutine 0 [idle]:
        runtime.futex()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/sys_linux_amd64.s:552 +0x21 fp=0x7ffc67f5e290 sp=0x7ffc67f5e288 pc=0x474481
        runtime.futexsleep(0x1e?, 0x3a00?, 0x652514?)
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/os_linux.go:56 +0x36 fp=0x7ffc67f5e2e0 sp=0x7ffc67f5e290 pc=0x4368f6
        runtime.lock2(0x82a328)
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/lock_futex.go:106 +0x79 fp=0x7ffc67f5e328 sp=0x7ffc67f5e2e0 pc=0x40d699
        runtime.lockWithRank(...)
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/lockrank_off.go:22
        runtime.lock(...)
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/lock_futex.go:47
        runtime.blockOnSystemStackInternal()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/export_test.go:422 +0x4b fp=0x7ffc67f5e348 sp=0x7ffc67f5e328 pc=0x46968b
        runtime.systemstack()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/asm_amd64.s:477 +0x49 fp=0x7ffc67f5e350 sp=0x7ffc67f5e348 pc=0x4703e9

        goroutine 1 [running, locked to thread]:
        runtime.systemstack_switch()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/asm_amd64.s:444 fp=0xc00004cce0 sp=0xc00004ccd8 pc=0x470380
        runtime.BlockOnSystemStack(...)
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/export_test.go:416
        runtime_test.testPanicSystemstackInternal()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/crash_unix_test.go:228 +0x25 fp=0xc00004ccf8 sp=0xc00004cce0 pc=0x56a4e5
        runtime_test.init.2()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/crash_unix_test.go:223 +0x65 fp=0xc00004cd20 sp=0xc00004ccf8 pc=0x56a4a5
        runtime.doInit(0x7dc040)
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/proc.go:6395 +0x126 fp=0xc00004ce50 sp=0xc00004cd20 pc=0x449c66
        runtime.doInit(0x7d8700)
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/proc.go:6372 +0x71 fp=0xc00004cf80 sp=0xc00004ce50 pc=0x449bb1
        runtime.main()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/proc.go:238 +0x1e6 fp=0xc00004cfe0 sp=0xc00004cf80 pc=0x43cb86
        runtime.goexit()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/asm_amd64.s:1579 +0x1 fp=0xc00004cfe8 sp=0xc00004cfe0 pc=0x4725a1

        goroutine 2 [force gc (idle)]:
        runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/proc.go:366 +0xd6 fp=0xc00003efb0 sp=0xc00003ef90 pc=0x43cf96
        runtime.goparkunlock(...)
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/proc.go:372
        runtime.forcegchelper()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/proc.go:306 +0xad fp=0xc00003efe0 sp=0xc00003efb0 pc=0x43ce2d
        runtime.goexit()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/asm_amd64.s:1579 +0x1 fp=0xc00003efe8 sp=0xc00003efe0 pc=0x4725a1
        created by runtime.init.6
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/proc.go:294 +0x25

        goroutine 3 [GC sweep wait]:
        runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/proc.go:366 +0xd6 fp=0xc00003f790 sp=0xc00003f770 pc=0x43cf96
        runtime.goparkunlock(...)
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/proc.go:372
        runtime.bgsweep(0x0?)
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/mgcsweep.go:278 +0x8e fp=0xc00003f7c8 sp=0xc00003f790 pc=0x42848e
        runtime.gcenable.func1()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/mgc.go:177 +0x26 fp=0xc00003f7e0 sp=0xc00003f7c8 pc=0x41de26
        runtime.goexit()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/asm_amd64.s:1579 +0x1 fp=0xc00003f7e8 sp=0xc00003f7e0 pc=0x4725a1
        created by runtime.gcenable
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/mgc.go:177 +0x6b

        goroutine 4 [GC scavenge wait]:
        runtime.gopark(0xb67c103353bc?, 0x10000?, 0x0?, 0x0?, 0x0?)
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/proc.go:366 +0xd6 fp=0xc00003ff38 sp=0xc00003ff18 pc=0x43cf96
        runtime.goparkunlock(...)
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/proc.go:372
        runtime.bgscavenge(0x0?)
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/mgcscavenge.go:351 +0x288 fp=0xc00003ffc8 sp=0xc00003ff38 pc=0x426348
        runtime.gcenable.func2()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/mgc.go:178 +0x26 fp=0xc00003ffe0 sp=0xc00003ffc8 pc=0x41ddc6
        runtime.goexit()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/asm_amd64.s:1579 +0x1 fp=0xc00003ffe8 sp=0xc00003ffe0 pc=0x4725a1
        created by runtime.gcenable
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/mgc.go:178 +0xaa

        goroutine 18 [finalizer wait]:
        runtime.gopark(0x7fbcc0?, 0xc0000861a0?, 0x70?, 0xe7?, 0x449bb1?)
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/proc.go:366 +0xd6 fp=0xc00003e630 sp=0xc00003e610 pc=0x43cf96
        runtime.goparkunlock(...)
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/proc.go:372
        runtime.runfinq()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/mfinal.go:177 +0xb3 fp=0xc00003e7e0 sp=0xc00003e630 pc=0x41ceb3
        runtime.goexit()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/asm_amd64.s:1579 +0x1 fp=0xc00003e7e8 sp=0xc00003e7e0 pc=0x4725a1
        created by runtime.createfing
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/mfinal.go:157 +0x45

        goroutine 19 [GC worker (idle)]:
        runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/proc.go:366 +0xd6 fp=0xc00003a758 sp=0xc00003a738 pc=0x43cf96
        runtime.gcBgMarkWorker()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/mgc.go:1198 +0xe5 fp=0xc00003a7e0 sp=0xc00003a758 pc=0x41ff05
        runtime.goexit()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/asm_amd64.s:1579 +0x1 fp=0xc00003a7e8 sp=0xc00003a7e0 pc=0x4725a1
        created by runtime.gcBgMarkStartWorkers
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/mgc.go:1122 +0x25

        goroutine 20 [GC worker (idle)]:
        runtime.systemstack_switch()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/asm_amd64.s:444 fp=0xc00003af58 sp=0xc00003af50 pc=0x470380
        runtime.gcBgMarkWorker()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/mgc.go:1254 +0x1b1 fp=0xc00003afe0 sp=0xc00003af58 pc=0x41ffd1
        runtime.goexit()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/asm_amd64.s:1579 +0x1 fp=0xc00003afe8 sp=0xc00003afe0 pc=0x4725a1
        created by runtime.gcBgMarkStartWorkers
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/mgc.go:1122 +0x25

        goroutine 5 [runnable]:
        runtime_test.testPanicSystemstackInternal()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/crash_unix_test.go:227 fp=0xc0000407e0 sp=0xc0000407d8 pc=0x56a4c0
        runtime.goexit()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/asm_amd64.s:1579 +0x1 fp=0xc0000407e8 sp=0xc0000407e0 pc=0x4725a1
        created by runtime_test.init.2
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/crash_unix_test.go:222 +0x5f

        rax    0xca
        rbx    0x2
        rcx    0x474483
        rdx    0x2
        rdi    0x82a328
        rsi    0x80
        rbp    0x7ffc67f5e2d0
        rsp    0x7ffc67f5e288
        r8     0x0
        r9     0x0
        r10    0x0
        r11    0x286
        r12    0x2
        r13    0xc00002d900
        r14    0x7fb8e0
        r15    0x7f4103a09404
        rip    0x474481
        rflags 0x286
        cs     0x33
        fs     0x0
        gs     0x0

        -----

        SIGQUIT: quit
        PC=0x474483 m=2 sigcode=0

        goroutine 0 [idle]:
        runtime.futex()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/sys_linux_amd64.s:553 +0x23 fp=0x7f41038dfc90 sp=0x7f41038dfc88 pc=0x474483
        runtime.futexsleep(0xb6b7f1cd3cdf?, 0x42480?, 0x7f41038dfd20?)
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/os_linux.go:62 +0xaf fp=0x7f41038dfce0 sp=0x7f41038dfc90 pc=0x43696f
        runtime.notetsleep_internal(0x7fc1d8, 0xdf8475800)
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/lock_futex.go:201 +0xc5 fp=0x7f41038dfd20 sp=0x7f41038dfce0 pc=0x40db25
        runtime.notetsleep(0xb6b7f1cd2f74?, 0x7f4100000002?)
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/lock_futex.go:224 +0x34 fp=0x7f41038dfd40 sp=0x7f41038dfd20 pc=0x40dc74
        runtime.sysmon()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/proc.go:5273 +0x1db fp=0x7f41038dfda8 sp=0x7f41038dfd40 pc=0x447cbb
        runtime.mstart1()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/proc.go:1398 +0x93 fp=0x7f41038dfdd0 sp=0x7f41038dfda8 pc=0x43f7d3
        runtime.mstart0()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/proc.go:1356 +0x79 fp=0x7f41038dfe00 sp=0x7f41038dfdd0 pc=0x43f719
        runtime.mstart()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/asm_amd64.s:375 +0x5 fp=0x7f41038dfe08 sp=0x7f41038dfe00 pc=0x4702e5
        rax    0xfffffffffffffffc
        rbx    0x0
        rcx    0x474483
        rdx    0x0
        rdi    0x7fc1d8
        rsi    0x80
        rbp    0x7f41038dfcd0
        rsp    0x7f41038dfc88
        r8     0x0
        r9     0x0
        r10    0x7f41038dfcc0
        r11    0x246
        r12    0x7f41038dfcc0
        r13    0x7ffc67f5df7f
        r14    0xc0000029c0
        r15    0x7f41038e0640
        rip    0x474483
        rflags 0x246
        cs     0x33
        fs     0x0
        gs     0x0

        -----

        SIGQUIT: quit
        PC=0x474481 m=3 sigcode=0

        goroutine 0 [idle]:
        runtime.futex()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/sys_linux_amd64.s:552 +0x21 fp=0x7f4102f3eb90 sp=0x7f4102f3eb88 pc=0x474481
        runtime.futexsleep(0xc00002c000?, 0x0?, 0x0?)
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/os_linux.go:56 +0x36 fp=0x7f4102f3ebe0 sp=0x7f4102f3eb90 pc=0x4368f6
        runtime.notesleep(0xc000042a50)
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/lock_futex.go:159 +0x87 fp=0x7f4102f3ec18 sp=0x7f4102f3ebe0 pc=0x40d9e7
        runtime.mPark()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/proc.go:1432 +0x2a fp=0x7f4102f3ec38 sp=0x7f4102f3ec18 pc=0x43f8ca
        runtime.stopm()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/proc.go:2402 +0x78 fp=0x7f4102f3ec60 sp=0x7f4102f3ec38 pc=0x440df8
        runtime.findrunnable()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/proc.go:2978 +0x865 fp=0x7f4102f3ed50 sp=0x7f4102f3ec60 pc=0x4422c5
        runtime.schedule()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/proc.go:3361 +0x239 fp=0x7f4102f3ed98 sp=0x7f4102f3ed50 pc=0x4431f9
        runtime.park_m(0xc0000871e0?)
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/proc.go:3510 +0x14d fp=0x7f4102f3edc8 sp=0x7f4102f3ed98 pc=0x44374d
        runtime.mcall()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/asm_amd64.s:433 +0x43 fp=0x7f4102f3edd8 sp=0x7f4102f3edc8 pc=0x470363
        rax    0xca
        rbx    0x0
        rcx    0x474483
        rdx    0x0
        rdi    0xc000042a50
        rsi    0x80
        rbp    0x7f4102f3ebd0
        rsp    0x7f4102f3eb88
        r8     0x0
        r9     0x0
        r10    0x0
        r11    0x286
        r12    0x0
        r13    0x1
        r14    0xc000002ea0
        r15    0xffffffffffffffff
        rip    0x474481
        rflags 0x286
        cs     0x33
        fs     0x0
        gs     0x0

        -----

        SIGQUIT: quit
        PC=0x4745e7 m=4 sigcode=0

        goroutine 0 [idle]:
        runtime.osyield()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/sys_linux_amd64.s:651 +0x7 fp=0x7f410273dbd0 sp=0x7f410273dbc8 pc=0x4745e7
        runtime.suspendG(0xc0000021a0)
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/preempt.go:250 +0x3ae fp=0x7f410273dc40 sp=0x7f410273dbd0 pc=0x43b2ae
        runtime.markroot.func1()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/mgcmark.go:235 +0x8d fp=0x7f410273dc90 sp=0x7f410273dc40 pc=0x421aed
        runtime.markroot(0xc00002f738, 0x14, 0x1)
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/mgcmark.go:216 +0x19c fp=0x7f410273dd20 sp=0x7f410273dc90 pc=0x42183c
        runtime.gcDrain(0xc00002f738, 0xb)
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/mgcmark.go:1049 +0x39f fp=0x7f410273dd80 sp=0x7f410273dd20 pc=0x4237bf
        runtime.gcBgMarkWorker.func2()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/mgc.go:1284 +0x85 fp=0x7f410273ddd0 sp=0x7f410273dd80 pc=0x4202e5
        runtime.systemstack()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/asm_amd64.s:477 +0x49 fp=0x7f410273ddd8 sp=0x7f410273ddd0 pc=0x4703e9
        rax    0x0
        rbx    0xc000042d80
        rcx    0x4745e7
        rdx    0x94f3b7a
        rdi    0x1
        rsi    0x310c5
        rbp    0x7f410273dc30
        rsp    0x7f410273dbc8
        r8     0xb6b7f20cad5b
        r9     0x201b01
        r10    0x7ffc67fca080
        r11    0x212
        r12    0x7f410273dbb0
        r13    0x32
        r14    0xc000003520
        r15    0x7f410273e640
        rip    0x4745e7
        rflags 0x212
        cs     0x33
        fs     0x0
        gs     0x0

        -----

        SIGQUIT: quit
        PC=0x474481 m=5 sigcode=0

        goroutine 0 [idle]:
        runtime.futex()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/sys_linux_amd64.s:552 +0x21 fp=0x7f4101efcd00 sp=0x7f4101efccf8 pc=0x474481
        runtime.futexsleep(0x7f4101efcd68?, 0x0?, 0x8?)
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/os_linux.go:56 +0x36 fp=0x7f4101efcd50 sp=0x7f4101efcd00 pc=0x4368f6
        runtime.notesleep(0x82a878)
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/lock_futex.go:159 +0x87 fp=0x7f4101efcd88 sp=0x7f4101efcd50 pc=0x40d9e7
        runtime.templateThread()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/proc.go:2379 +0x71 fp=0x7f4101efcda8 sp=0x7f4101efcd88 pc=0x440cf1
        runtime.mstart1()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/proc.go:1398 +0x93 fp=0x7f4101efcdd0 sp=0x7f4101efcda8 pc=0x43f7d3
        runtime.mstart0()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/proc.go:1356 +0x79 fp=0x7f4101efce00 sp=0x7f4101efcdd0 pc=0x43f719
        runtime.mstart()
        	/usr/local/google/home/mknyszek/toolchain/src/runtime/asm_amd64.s:375 +0x5 fp=0x7f4101efce08 sp=0x7f4101efce00 pc=0x4702e5
        rax    0xca
        rbx    0x0
        rcx    0x474483
        rdx    0x0
        rdi    0x82a878
        rsi    0x80
        rbp    0x7f4101efcd40
        rsp    0x7f4101efccf8
        r8     0x0
        r9     0x0
        r10    0x0
        r11    0x286
        r12    0xc0000861a0
        r13    0x7ffc67f5e01f
        r14    0xc0000861a0
        r15    0x7f4101efd640
        rip    0x474481
        rflags 0x286
        cs     0x33
        fs     0x0
        gs     0x0

--- FAIL: TestPanicSystemstack (257.24s)
```

**Comment by mknyszek** [comment]
In the stack trace above, the problem is that goroutine 5 is runnable, but hasn't blocked itself on a lock yet. We see then also what appears to be a... mark background worker, trying to suspend something. If it's trying to suspend the one that's already blocked on a lock, then we have a problem.

However an even bigger problem is: why is *any* part of the GC executing right now? The runtime is still running init functions at this point and the GC should *not* be enabled.

**Comment by mknyszek** [comment]
Oh, haha. Naturally the GC is indeed enabled during user init tasks, just not the runtime ones. So it's fine for the GC to be running during init (which, uh, makes sense).

I think this fix is straightforward. A test that involves goroutines deadlocking themselves on runtime locks *definitely* should not be running any garbage collections while they're deadlocking themselves.

**Comment by mknyszek** [comment]
Hrm, actually, I don't have quite the whole picture here. Why *doesn't* goroutine 5 execute? It shouldn't really matter if the GC is running -- if the workers get stuck trying to suspend something, or a goroutine is trying to STW, it's really fine, as long as the two `x\n` strings get printed.

Maybe the problem is that `GOMAXPROCS=2`? If, say, that GC worker is spinning trying to preempt a goroutine it'll never get to, meanwhile the other goroutine is sitting on the other P blocked in a non-preemptible state... I think that leaves zero to actually execute that last goroutine.

Actually, this makes sense. Maybe a better fix here is to just increase `GOMAXPROCS` in the test? Or maybe having the GC on for this sort of thing is just asking for trouble?
