### ISSUE TITLE
x/tools/internal/lsp/source: test failures with diffs on "//@complete" lines

### ISSUE THREAD

**Issue by bcmills** [golang/go#49463]
`greplogs --dashboard -md -l -e \(\?m\)-.\*//@complete.\*\\n.\*\\+.\*\\\{\\}//@complete.\*\\n\(\?:.\*\\n\)\*FAIL\\s+golang.org/x/tools/internal/lsp/source`

<details>

[2021-11-08T14:49:56-0c60b7c-ab31dbc/plan9-386-0intro](https://build.golang.org/log/cf98774bc949bf8362207dec699a31b70267c1f3)
[2021-11-07T04:57:22-0c60b7c-9e6ad46/plan9-386-0intro](https://build.golang.org/log/150ae529d00ea93d6bc988d901a59cd0e1072d09)
[2021-11-05T22:03:24-4ab7496-035963c/freebsd-amd64-race](https://build.golang.org/log/cc30aac107e6bbcc258cf8fb8bc0c4a8792bd6f1)
[2021-11-05T21:48:25-4ab7496-6b223e8/freebsd-amd64-race](https://build.golang.org/log/a8bbde94c4e3d64d0a40c389ec413ccfad5e7ae7)
[2021-11-04T23:35:26-6f75aad-256a8fc/freebsd-386-12_2](https://build.golang.org/log/e0d49cf606ecb1eb4af1add6d381d6057383c7b9)
[2021-11-04T17:07:48-84e69e7-5772877/plan9-386-0intro](https://build.golang.org/log/6c8fed1306852bbd3c6ae56d5d25b20bcb3ab960)
[2021-11-04T14:54:46-84e69e7-00d6d20/plan9-amd64-0intro](https://build.golang.org/log/b3aa378e4f9c3993b107a432a08a5cf5b13c3602)
[2021-11-04T07:05:31-84e69e7-2622235/plan9-386-0intro](https://build.golang.org/log/0d844fa0e666746dca5f7c1f9dae9905cfad4f06)
[2021-11-04T07:05:31-84e69e7-2622235/plan9-amd64-0intro](https://build.golang.org/log/dc51141a5f4106c8c7c9450b3861e1b06ed31780)
[2021-11-01T13:54:03-42daa65-4a84298/freebsd-amd64-race](https://build.golang.org/log/4768af3b6621101afa46ba7de1b8d68797ce9175)
[2021-10-29T23:15:00-a2be0cd-8dfb447/netbsd-amd64-9_0](https://build.golang.org/log/97e96d0a5ec4a393a507c1b62af7e14aed59e288)
[2021-10-29T21:19:39-a2be0cd-994049a/netbsd-amd64-9_0](https://build.golang.org/log/5bbf7d280a3fe593e5dfde150b37155fa4bf1be1)
[2021-10-29T19:32:59-170abdd-9004433/freebsd-amd64-12_2](https://build.golang.org/log/ced7f01994d8b0c769049bd2f03f18373263337a)
[2021-10-26T18:40:06-9626607-11b64b4/freebsd-amd64-race](https://build.golang.org/log/b9129a2f2b34648479bbc5d1667b2d34eb040fe4)
[2021-10-26T18:33:39-244f92e-76cef81/plan9-386-0intro](https://build.golang.org/log/e12487eb95e21f14c6eb32c8c7c99a957c8d218e)
[2021-10-23T16:18:19-affba50-16318df/plan9-386-0intro](https://build.golang.org/log/555c53f8f02c5b65cdbc5389a4e29003774ef90d)
[2021-10-23T12:44:47-316ba0b-b0f7eb6/freebsd-amd64-12_2](https://build.golang.org/log/31174075c597badb579ef0c90dfd1b80c0a97ef7)
[2021-10-16T14:50:21-98f6e03-680caf1/plan9-386-0intro](https://build.golang.org/log/0deb6621d72afd65a0924354707daada0c7e50d7)
[2021-10-15T21:46:06-98f6e03-ed1c8db/freebsd-amd64-race](https://build.golang.org/log/fe88f785c3d196a8f637147e5dc5defc52884c9e)
[2021-10-15T20:29:48-98f6e03-85cbdda/freebsd-amd64-race](https://build.golang.org/log/053ef1c98d3549873155f1dbaaed1e6a1519ea0d)
[2021-10-12T22:26:24-074820e-732f6fa/freebsd-amd64-race](https://build.golang.org/log/5ae114a8deecb980201ea60ba0e992530ed0e4f5)
[2021-10-10T15:11:26-1af23bd-d2d21d9/plan9-386-0intro](https://build.golang.org/log/ebb00c0b349fff47fd658b1263e8d73faebd0cfc)
[2021-10-04T17:17:11-ccaa907-cc5e3de/plan9-386-0intro](https://build.golang.org/log/808f8ac223ccafada7c865a20810b5cc7ff12a5e)
[2021-09-24T19:46:09-939195f-cfd0868/plan9-386-0intro](https://build.golang.org/log/b7b1220c1285d3b44b5d854d31d89d9e7bc8253b)
[2021-09-24T18:21:14-6d1e33f-f6b5ffb/plan9-386-0intro](https://build.golang.org/log/67c6db267375a23c2caa161bf22551e955c82873)
[2021-09-22T20:53:48-efaec4e-41bb744/plan9-386-0intro](https://build.golang.org/log/998fa4d395e4ef8716c6f7f1fe8030a27da18438)
[2021-09-22T19:37:42-efaec4e-5b75a9b/plan9-386-0intro](https://build.golang.org/log/80c9879b33406298e46ea6873bbfc83aab4a46ee)
[2021-09-22T16:53:49-efaec4e-e128749/plan9-386-0intro](https://build.golang.org/log/f97b92f530e803a327c04e90464d687d57113379)
[2021-09-09T09:06:46-076821b-b86e8dd/plan9-386-0intro](https://build.golang.org/log/b91e50acbd0c7e57d8cb7e5b3a7faa2ae6747d97)
[2021-09-02T19:56:24-3b801c8-065f380/plan9-386-0intro](https://build.golang.org/log/d3f157b922029b26da3295bd22a5314bbd0c1864)
[2021-08-17T02:54:26-6932d22-29ec74f/plan9-386-0intro](https://build.golang.org/log/93a81edfbadf66e90bb4c04b4c8b15b009424804)
[2021-08-16T23:57:10-10bcabd-2a19333/plan9-386-0intro](https://build.golang.org/log/80b1e56f565df4d8453485edabf92d668a91eca5)
[2021-08-15T15:51:49-a55d515-48dfddb/plan9-386-0intro](https://build.golang.org/log/77a4844ed56a32fc12af50b203cc0bf5f2f0776d)
[2021-08-05T20:22:31-f367f01-fd45e26/plan9-386-0intro](https://build.golang.org/log/ed1a9a126a83f0a3a55962536b08a9a916141886)
[2021-08-04T21:03:22-f367f01-6e73886/plan9-386-0intro](https://build.golang.org/log/ac330d2a080259c71d8cb7c98b6deb69bbb27315)
[2021-08-02T22:22:46-3395cb0-ba93baa/freebsd-amd64-race](https://build.golang.org/log/15b87fc9a720e59a33072ecbfdc20796e671d1f4)
[2021-07-29T15:30:38-ab1fe72-70fd4e4/plan9-386-0intro](https://build.golang.org/log/f5e3f04b6bbb7893cde983ba539e3d22cf3585c9)
[2021-07-29T13:34:27-ab1fe72-9eee0ed/plan9-386-0intro](https://build.golang.org/log/6e0116159575bc6a5de98c64497c1921814d8b28)
[2021-07-28T20:09:10-07bc1bf-9eee0ed/plan9-386-0intro](https://build.golang.org/log/bd29f41221096e4607ed93a121062b2861d6a7de)
[2021-07-22T20:47:59-c740bfd-052da57/plan9-386-0intro](https://build.golang.org/log/43e733208169bee014ddfcec59976a9dd00f2791)
[2021-07-21T23:55:41-412ee17-3e48c03/freebsd-amd64-race](https://build.golang.org/log/06d55553c40eab9b07b0ad7e033caa276dd9a13a)
[2021-07-16T02:43:48-6e9046b-aa4e0f5/plan9-386-0intro](https://build.golang.org/log/fcb940d987006b03f975cc4ce854dc9083354ab7)
[2021-07-13T20:49:08-5061c41-a985897/plan9-386-0intro](https://build.golang.org/log/6abb228c33c063137dda2798574213f9b9b67085)
[2021-07-13T20:15:39-ef97713-a985897/plan9-386-0intro](https://build.golang.org/log/656633a8a22a913d2115043c6811add88e41107c)
[2021-07-13T16:40:23-8e85a28-a985897/plan9-386-0intro](https://build.golang.org/log/409fe94eff9d118f06947c33258d576d7aae1679)
[2021-07-08T21:02:30-64bd808-3d1d066/linux-arm64-packet](https://build.golang.org/log/7559c8ee77c93d4b72dd23a2a285d044dfa83616)
[2021-07-08T19:56:07-71eae3a-3d1d066/linux-arm64-packet](https://build.golang.org/log/fb991b61b2087fb565e4a0a57604d1f0752dc13d)
[2021-07-02T16:25:10-7edcfe5-6125d0c/plan9-386-0intro](https://build.golang.org/log/43231c5778a615b7b699351f5d18b439f0dfc66b)
[2021-07-02T16:14:50-7edcfe5-03761ed/plan9-386-0intro](https://build.golang.org/log/7d20a3fc99dfc18793fbe44a9468ecc3df721ab1)
[2021-07-01T19:09:57-20dafe5-03761ed/plan9-386-0intro](https://build.golang.org/log/54764a20c2dda20e3ce21d5c2b2a3762e485d399)
[2021-06-27T05:06:30-12f8456-c95464f/plan9-386-0intro](https://build.golang.org/log/e66060eb5956f6913ba0c5531d8e82726b1dadee)
[2021-06-25T23:53:21-12f8456-ed01cea/plan9-386-0intro](https://build.golang.org/log/43cac74170a58039e35c2d15bf9309a9398efd4d)
[2021-06-24T00:39:41-d824a74-73496e0/plan9-386-0intro](https://build.golang.org/log/d353a0d49b36b5b010da2d6b9bc5c133bfd231a8)
[2021-06-23T15:16:55-d824a74-0ebd5a8/plan9-386-0intro](https://build.golang.org/log/1b4fa959400849a21408c13b91a7d56a1bcda048)
[2021-06-17T14:53:37-463a76b-4dede02/plan9-386-0intro](https://build.golang.org/log/1dbd741f429413c0312f2443b68e4aa39d8587ac)
[2021-06-17T04:32:50-463a76b-97cee43/plan9-386-0intro](https://build.golang.org/log/e78b0e0be18bdeac2a9e946e5aeb7bff9f1a5346)
[2021-06-11T17:18:39-4b484fb-e2dc6dd/plan9-386-0intro](https://build.golang.org/log/4ac60150b7a80cd79c6f8f79ce82a04dea0d4e9a)
[2021-06-11T15:30:39-490eac8-2f11284/plan9-386-0intro](https://build.golang.org/log/10d9a2fc96ba61b287ab4e160fe7467355419e67)
[2021-06-08T22:35:56-4e58f8f-bcecae2/plan9-386-0intro](https://build.golang.org/log/d141bda1c2d61a94e54ce89449997018c743eb6a)
[2021-06-08T20:45:46-4e58f8f-6551763/plan9-386-0intro](https://build.golang.org/log/9e1aef4cf5555899e4b6270cbd1f074dd1244fb5)
[2021-06-04T17:45:44-7295a4e-831f937/plan9-386-0intro](https://build.golang.org/log/292a73c75a04500605ba363e207921f0b8c4665f)
[2021-06-04T17:45:44-7295a4e-831f937/plan9-amd64-0intro](https://build.golang.org/log/21a48ba44304764b690c5a3987ec9c60690d79d2)
[2021-05-30T17:47:50-6123e5f-3b770f2/plan9-386-0intro](https://build.golang.org/log/c93c83cfa6bc7eadde7f3c8401dacc742514bec4)
[2021-05-26T23:33:38-a3eb095-3075ffc/plan9-386-0intro](https://build.golang.org/log/bf73fa918aae242e95d7b900e5c744f4d09d54c1)
[2021-05-26T22:54:09-a3eb095-a62c087/plan9-386-0intro](https://build.golang.org/log/3d36a2b8dc32553c7bd5a37562820e74bb77f8bf)
[2021-05-20T20:37:02-2275bb5-baa934d/plan9-386-0intro](https://build.golang.org/log/117cb996ab0cec0151e479f7f6a9b4b18fd7c20a)
[2021-05-20T18:25:17-2275bb5-7c692cc/plan9-386-0intro](https://build.golang.org/log/a93502b7b78dc4d08325b8b84aeda8e0c8f54380)
[2021-05-20T17:40:58-3063790-7c692cc/plan9-386-0intro](https://build.golang.org/log/f026250a916e7041b981642410ab969fb0d52896)
[2021-05-20T15:46:45-3063790-9636878/linux-arm-scaleway](https://build.golang.org/log/c55e77d58f2a2542795f21aab45fcc6d196ab78d)
[2021-05-18T07:50:25-6da3d7a-8b0901f/netbsd-arm64-bsiegert](https://build.golang.org/log/fe164cc8216ed47a9709882758fecc78221765da)
[2021-05-17T17:18:20-8f301ca-04cd717/linux-arm-scaleway](https://build.golang.org/log/3ca9cdb82966fb5c13af564442adb59d2f65063d)
[2021-05-15T02:39:08-09ab05b-ce92a20/plan9-386-0intro](https://build.golang.org/log/d943d9a83c3169a89770ff29c31576244aa9bffb)
[2021-05-13T13:20:04-cd1be5d-07d8cba/linux-arm-scaleway](https://build.golang.org/log/67c59a238379d80f59bd7dcb6421037f026a2f01)
[2021-05-11T03:28:22-18795da-326a792/plan9-386-0intro](https://build.golang.org/log/f9f618b0fefcf3295b57a535427789caeadcfe36)
[2021-05-11T03:28:22-18795da-07d8cba/linux-arm-scaleway](https://build.golang.org/log/4f2fc91689ce041998efa127351d30a1e04b64df)
[2021-05-10T19:19:34-ecb7392-dc50683/plan9-386-0intro](https://build.golang.org/log/c8e263cd55e105f53ae69c998840b8bc46d65fcb)
[2021-05-06T20:30:00-c0140e8-4dbad79/plan9-386-0intro](https://build.golang.org/log/72db192ad502c8883c64e8941f0a7acb1a6e7b73)
[2021-05-06T19:28:34-c0140e8-07d8cba/linux-arm-scaleway](https://build.golang.org/log/3fed87560ebb22a6b3f6b24aac8dda1f79e78882)
[2021-05-06T02:57:18-f4a4129-ba7cac4/linux-arm-scaleway](https://build.golang.org/log/008198173552dbb5faad812abaee095fbeb49d08)
[2021-05-05T22:35:07-dd255f2-ba7cac4/linux-arm-scaleway](https://build.golang.org/log/1b2b9c324778c637c5664a0ceb337ee8a9a2ddfb)
[2021-05-05T20:44:55-68c6cab-ce04f86/linux-arm-scaleway](https://build.golang.org/log/b493e6d80f96bf79e0ba5ff66363ecf233edaf4d)
[2021-05-05T16:20:51-250398d-c0a7ecf/linux-arm-scaleway](https://build.golang.org/log/b9da8ed5f6ac18a2aa9bda8735cfaf3175a129e3)
[2021-05-04T21:16:16-f03daea-cd28ca3/plan9-386-0intro](https://build.golang.org/log/85fd53ef4869f0cc2013d9945aceaf1bf77cb32b)
[2021-05-04T19:12:24-f03daea-8c3d217/plan9-386-0intro](https://build.golang.org/log/39e0078153fd3f275a110e15b88624e745d5cc89)
[2021-05-03T21:45:16-42984c4-72ccabc/linux-arm-scaleway](https://build.golang.org/log/8a991044a9160386adc83a49241e39f39bfb14f4)
[2021-05-03T16:38:18-062bf4e-72ccabc/linux-arm-scaleway](https://build.golang.org/log/40f2c688b87d257a4dcc88830d2ab2e5c89dc74b)
[2021-05-03T16:07:20-def0263-72ccabc/linux-arm-scaleway](https://build.golang.org/log/ef2c6bb423620401b679dcbe84a3f014cc85b1fb)
[2021-05-03T01:35:44-7a6108e-2c9f5a1/plan9-386-0intro](https://build.golang.org/log/c2d8a66ab6f9ded38db5a0535c66356db67672df)
[2021-05-02T20:59:26-7a6108e-bb09f8a/plan9-386-0intro](https://build.golang.org/log/04ff599a99ec63b4de7fdb7abbd1366375da8d06)
[2021-05-02T18:22:19-7a6108e-0d32d9e/plan9-386-0intro](https://build.golang.org/log/e32bf655a8b890cfaa89d6c9573e1bd2a52f8e61)
[2021-05-01T19:17:47-7a6108e-053fe2f/plan9-386-0intro](https://build.golang.org/log/d48473c087bf624c9f645c996e631b9f86b0309d)
[2021-04-30T20:08:34-7a6108e-72ccabc/linux-arm-scaleway](https://build.golang.org/log/6091b92e579a82be89914680535bfcb0dc32867a)
[2021-04-30T16:06:43-9b9633e-72ccabc/linux-arm-scaleway](https://build.golang.org/log/e4e6db2f3678814675ef9fef75dd12ebc59203db)
[2021-04-29T18:45:57-28c1392-72ccabc/linux-arm-scaleway](https://build.golang.org/log/731da5df3a76143e6a8cf04ef7e5d5d4bb1a7dc7)
[2021-04-29T11:37:05-800adbe-c4c68fb/plan9-386-0intro](https://build.golang.org/log/05abed10b5c8619f10c937413e09008ca88dcc50)
[2021-04-29T04:59:52-800adbe-6afa0ae/plan9-386-0intro](https://build.golang.org/log/61541157207b3d22ac25debbb0e7344a29452b48)
[2021-04-28T21:52:02-800adbe-d4adea2/linux-arm-scaleway](https://build.golang.org/log/3f1ded9e7ebf397b577ac18abb0299d24f63aac0)
[2021-04-27T22:46:28-7c72a84-983dea9/plan9-386-0intro](https://build.golang.org/log/a5e2ff824217c2546f808d2c97855caa086e3a4f)
[2021-04-27T20:55:22-7c72a84-b9dfaf7/plan9-386-0intro](https://build.golang.org/log/f984d8ec341e4247948405e06ff387d0a3334236)
[2021-04-27T19:53:45-d0768c9-b9dfaf7/plan9-386-0intro](https://build.golang.org/log/b472a84969bd7b04b5902d2a4bec14f91e73fede)
[2021-04-27T04:02:17-735ed62-06c9756/linux-arm-scaleway](https://build.golang.org/log/3215752882d94a2b7dc22dc5f36b261c67f7bed6)

</details>

**Comment by bcmills** [comment]
@findleyr, given the platforms involved I suspect that this may be a misreported crash in some subprocess.

FreeBSD may or may not still have memory corruption issues (#46272, #49347), and the `plan9` builders are often on pretty shaky ground too.

**Comment by hyangah** [comment]
I checked a few recent logs and observed different failure patterns. I also think `//@complete` is a redherring (that's a part of trace that indicates gopls couldn't fix broken sources completely).

* FreeBSD: subprocess killed?

[2021-11-05T22:03:24-4ab7496-035963c/freebsd-amd64-race](https://build.golang.org/log/cc30aac107e6bbcc258cf8fb8bc0c4a8792bd6f1)
[2021-11-05T21:48:25-4ab7496-6b223e8/freebsd-amd64-race](https://build.golang.org/log/a8bbde94c4e3d64d0a40c389ec413ccfad5e7ae7)

```
signal: killed
FAIL	golang.org/x/tools/go/packages	192.661s
...
FAIL
:: Running /tmp/workdir/go/bin/go with args ["/tmp/workdir/go/bin/go" "test" "-short" "-race" "golang.org/x/tools/gopls/..."] and env ["PATH=/tmp/workdir/go/bin:/bin:/sbin:/usr/bin:/usr/local/bin" "PWD=/" "HOME=/" "RC_PID=36" "WORKDIR=/tmp/workdir" "GOROOT_BOOTSTRAP=/tmp/workdir/go1.4" "GO_BUILDER_NAME=freebsd-amd64-race" "GOROOT=/tmp/workdir/go" "GOPATH=/tmp/workdir/gopath" "GOPROXY=http://gk3-services-nap-yh2ma9qv-91853bd1-6dg1.c.symbolic-datum-552.internal:30157" "TMPDIR=/tmp/workdir/tmp" "GOCACHE=/tmp/workdir/gocache"] in dir /tmp/workdir/gopath/src/golang.org/x/tools/gopls
```

[2021-11-04T23:35:26-6f75aad-256a8fc/freebsd-386-12_2](https://build.golang.org/log/e0d49cf606ecb1eb4af1add6d381d6057383c7b9)
[2021-11-01T13:54:03-42daa65-4a84298/freebsd-amd64-race](https://build.golang.org/log/4768af3b6621101afa46ba7de1b8d68797ce9175)

```
*** Test killed with quit: ran too long (11m0s).
FAIL	golang.org/x/tools/internal/lsp/source	660.046s
```

* Plan9: difference in file system? Heavy use of `t.Helper` in gopls tests prevent me finding the exact failure location easily :-( 

[2021-11-08T14:49:56-0c60b7c-ab31dbc/plan9-386-0intro](https://build.golang.org/log/cf98774bc949bf8362207dec699a31b70267c1f3)
[2021-11-07T04:57:22-0c60b7c-9e6ad46/plan9-386-0intro](https://build.golang.org/log/150ae529d00ea93d6bc988d901a59cd0e1072d09)
[2021-11-04T17:07:48-84e69e7-5772877/plan9-386-0intro](https://build.golang.org/log/6c8fed1306852bbd3c6ae56d5d25b20bcb3ab960)
[2021-11-04T14:54:46-84e69e7-00d6d20/plan9-amd64-0intro](https://build.golang.org/log/b3aa378e4f9c3993b107a432a08a5cf5b13c3602)
[2021-11-04T07:05:31-84e69e7-2622235/plan9-386-0intro](https://build.golang.org/log/0d844fa0e666746dca5f7c1f9dae9905cfad4f06)
[2021-11-04T07:05:31-84e69e7-2622235/plan9-amd64-0intro](https://build.golang.org/log/dc51141a5f4106c8c7c9450b3861e1b06ed31780)

Combination of the following failures
```
--- FAIL: TestLSP (55.46s)
    --- FAIL: TestLSP/MultiModule (10.76s)
        lsp_test.go:35: rename /tmp/TestLSP_MultiModule3398047324/lsp/go.mod testmodule/go.mod: invalid argument
FAIL
FAIL	golang.org/x/tools/internal/lsp	55.513s

...
--- FAIL: TestSource (58.97s)
    --- FAIL: TestSource/MultiModule (9.00s)
        source_test.go:36: rename /tmp/TestSource_MultiModule231230237/lsp/go.mod testmodule/go.mod: invalid argument
FAIL
FAIL	golang.org/x/tools/internal/lsp/source	67.921s
...

--- FAIL: TestUnknownRevision (4.70s)
    --- FAIL: TestUnknownRevision/bad (0.80s)
        --- FAIL: TestUnknownRevision/bad/default (0.39s)
            --- FAIL: TestUnknownRevision/bad/default/singleton (0.39s)
                modfile_test.go:561: All files must be saved first (unsaved: [/tmp/gopls-regtest-2501435137/TestUnknownRevision/bad/default/singleton/work/a/go.mod]).
        --- FAIL: TestUnknownRevision/bad/nested (0.41s)
            --- FAIL: TestUnknownRevision/bad/nested/singleton (0.41s)
                modfile_test.go:561: All files must be saved first (unsaved: [/tmp/gopls-regtest-2501435137/TestUnknownRevision/bad/nested/singleton/work/a/go.mod]).
               
FAIL
FAIL	golang.org/x/tools/gopls/internal/regtest/modfile	37.297s
```

* NetBSD: maybe tree was unstable back then?

[2021-10-29T23:15:00-a2be0cd-8dfb447/netbsd-amd64-9_0](https://build.golang.org/log/97e96d0a5ec4a393a507c1b62af7e14aed59e288)
[2021-10-29T21:19:39-a2be0cd-994049a/netbsd-amd64-9_0](https://build.golang.org/log/5bbf7d280a3fe593e5dfde150b37155fa4bf1be1)

```
*** Test killed with quit: ran too long (11m0s).
FAIL	golang.org/x/tools/internal/lsp/source	660.202s
```
But given the error like this occurred in a different test (stringer), not sure how stable the builder at the revision was.
```
mspan.sweep: state=1 sweepgen=9 mheap.sweepgen=10
fatal error: mspan.sweep: bad span state

goroutine 3 [running]:
runtime.throw({0x9b3efe?, 0x7f7ff7aa95d8?})
	/tmp/workdir/go/src/runtime/panic.go:992 +0x71 fp=0xc000045658 sp=0xc000045628 pc=0x4337f1
runtime.(*sweepLocked).sweep(0xd84e40?, 0x0?)
	/tmp/workdir/go/src/runtime/mgcsweep.go:486 +0xbbb fp=0xc000045740 sp=0xc000045658 pc=0x424cdb
runtime.sweepone()
	/tmp/workdir/go/src/runtime/mgcsweep.go:369 +0xf0 fp=0xc000045790 sp=0xc000045740 pc=0x423e50
runtime.bgsweep(0x0?)
	/tmp/workdir/go/src/runtime/mgcsweep.go:281 +0x105 fp=0xc0000457c8 sp=0xc000045790 pc=0x423c05
runtime.gcenable.func1()
	/tmp/workdir/go/src/runtime/mgc.go:177 +0x26 fp=0xc0000457e0 sp=0xc0000457c8 pc=0x419dc6
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:1446 +0x1 fp=0xc0000457e8 sp=0xc0000457e0 pc=0x4623c1
created by runtime.gcenable
	/tmp/workdir/go/src/runtime/mgc.go:177 +0x6b
```
or
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x280 pc=0x40c9ce]

goroutine 15044 [running]:
runtime.throw({0xaea372?, 0xc000048900?})
	/tmp/workdir/go/src/runtime/panic.go:965 +0x71 fp=0xc000c5d508 sp=0xc000c5d4d8 pc=0x435611
runtime.sigpanic()
	/tmp/workdir/go/src/runtime/signal_unix.go:781 +0x3a9 fp=0xc000c5d558 sp=0xc000c5d508 pc=0x44ba49
runtime.unlock2(0xbf07b0?)
	/tmp/workdir/go/src/runtime/lock_sema.go:115 +0x4e fp=0xc000c5d580 sp=0xc000c5d558 pc=0x40c9ce
runtime.unlockWithRank(...)
	/tmp/workdir/go/src/runtime/lockrank_off.go:31
runtime.unlock(...)
	/tmp/workdir/go/src/runtime/lock_sema.go:97
runtime.(*pollCache).free(0x104b2b0, 0x7f7ff7a8e310)
	/tmp/workdir/go/src/runtime/netpoll.go:199 +0x45 fp=0xc000c5d598 sp=0xc000c5d580 pc=0x431345
internal/poll.runtime_pollClose(0xc000c5d5f0?)
	/tmp/workdir/go/src/runtime/netpoll.go:192 +0x4e fp=0xc000c5d5b8 sp=0xc000c5d598 pc=0x4618ae
internal/poll.(*pollDesc).close(...)
	/tmp/workdir/go/src/internal/poll/fd_poll_runtime.go:51
internal/poll.(*FD).destroy(0xc00ef25aa0)
	/tmp/workdir/go/src/internal/poll/fd_unix.go:76 +0x2e fp=0xc000c5d5e0 sp=0xc000c5d5b8 pc=0x498f6e
internal/poll.(*FD).decref(0x7f7ff7a8e310?)
	/tmp/workdir/go/src/internal/poll/fd_mutex.go:213 +0x53 fp=0xc000c5d600 sp=0xc000c5d5e0 pc=0x497df3
internal/poll.(*FD).Close(0xc00ef25aa0)
	/tmp/workdir/go/src/internal/poll/fd_unix.go:106 +0x4f fp=0xc000c5d628 sp=0xc000c5d600 pc=0x49902f
os.(*file).close(0xc00ef25aa0)
	/tmp/workdir/go/src/os/file_unix.go:252 +0xad fp=0xc000c5d680 sp=0xc000c5d628 pc=0x4a50ad
os.(*File).Close(0xc00bcba000?)
	/tmp/workdir/go/src/os/file_posix.go:25 +0x25 fp=0xc000c5d698 sp=0xc000c5d680 pc=0x4a3965
os/exec.(*Cmd).closeDescriptors(...)
	/tmp/workdir/go/src/os/exec/exec.go:320
os/exec.(*Cmd).Start(0xc00bcb02c0)
	/tmp/workdir/go/src/os/exec/exec.go:434 +0x843 fp=0xc000c5d870 sp=0xc000c5d698 pc=0x5499a3
golang.org/x/tools/internal/gocommand.runCmdContext({0xca3d70, 0xc00666b840}, 0xc00bcb02c0)
	/tmp/workdir/gopath/src/golang.org/x/tools/internal/gocommand/invoke.go:230 +0x46 fp=0xc000c5d918 sp=0xc000c5d870 pc=0x68da66
golang.org/x/tools/internal/gocommand.(*Invocation).run(0xc000aabbc0, {0xca3d70, 0xc00666b840}, {0xc9f740?, 0xc00bcb6450}, {0xc9f740?, 0xc00bcb6480})
	/tmp/workdir/gopath/src/golang.org/x/tools/internal/gocommand/invoke.go:224 +0x104d fp=0xc000c5da40 sp=0xc000c5d918 pc=0x68d74d
golang.org/x/tools/internal/gocommand.(*Invocation).runWithFriendlyError(0xc000aabb88?, {0xca3d70, 0xc00666b840}, {0xc9f740?, 0xc00bcb6450?}, {0xc9f740?, 0xc00bcb6480?})
	/tmp/workdir/gopath/src/golang.org/x/tools/internal/gocommand/invoke.go:146 +0x65 fp=0xc000c5daf0 sp=0xc000c5da40 pc=0x68c4e5
golang.org/x/tools/internal/gocommand.(*Runner).runConcurrent(0xc00b763ca0, {0xca3d70, 0xc00666b840}, {{0xab068e, 0x4}, {0xc00666ba40, 0x4, 0x4}, {0x104b060, 0x0, ...}, ...})
	/tmp/workdir/gopath/src/golang.org/x/tools/internal/gocommand/invoke.go:97 +0x1e5 fp=0xc000c5dbc0 sp=0xc000c5daf0 pc=0x68be45
golang.org/x/tools/internal/gocommand.(*Runner).RunRaw(0x7f7fcc742de8?, {0xca3d70, 0xc00666b840}, {{0xab068e, 0x4}, {0xc00666ba40, 0x4, 0x4}, {0x104b060, 0x0, ...}, ...})
	/tmp/workdir/gopath/src/golang.org/x/tools/internal/gocommand/invoke.go:72 +0x90 fp=0xc000c5dce8 sp=0xc000c5dbc0 pc=0x68ba50
golang.org/x/tools/go/internal/packagesdriver.GetSizesGolist({0xca3d70, 0xc00666b840}, {{0xab068e, 0x4}, {0xc00666ba40, 0x4, 0x4}, {0x104b060, 0x0, 0x0}, ...}, ...)
	/tmp/workdir/gopath/src/golang.org/x/tools/go/internal/packagesdriver/sizes.go:22 +0x11c fp=0xc000c5de50 sp=0xc000c5dce8 pc=0x805bbc
golang.org/x/tools/go/packages.goListDriver.func1()
	/tmp/workdir/gopath/src/golang.org/x/tools/go/packages/golist.go:157 +0x178 fp=0xc000c5dfe0 sp=0xc000c5de50 pc=0x819498
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:1446 +0x1 fp=0xc000c5dfe8 sp=0xc000c5dfe0 pc=0x466fa1
created by golang.org/x/tools/go/packages.goListDriver
	/tmp/workdir/gopath/src/golang.org/x/tools/go/packages/golist.go:155 +0x32a

```

**Comment by findleyr** [comment]
Thanks @hyangah for that investigation!

A few thoughts:
```
FAIL	golang.org/x/tools/internal/lsp/source	660.046s
```

This test is not particularly slow (8s on my desktop, IIRC).  Such a timeout indicates a builder problem to me, or *maybe* a deadlock, but I would be surprised at the latter.

```
--- FAIL: TestUnknownRevision/bad/default/singleton (0.39s)
                modfile_test.go:561: All files must be saved first
```
This looks like a race.

**Comment by bcmills** [comment]
> NetBSD: maybe tree was unstable back then?

Was and still is: those look like #49453 and/or #49209.

**Comment by bcmills** [comment]
(At a higher level: I suspect that we shouldn't dig too hard into this one until the runtime instability on the BSDs has been resolved.)

**Comment by findleyr** [comment]
The BSDs are still unstable recently, but we should not close this issue yet.

**Comment by findleyr** [comment]
These tests no longer exist.
