### ISSUE TITLE
x/review/git-codereview: frequent timeouts on openbsd-386 builder since 2021-10-19

### ISSUE THREAD

**Issue by bcmills** [golang/go#49529]
<details>

```
panic: test timed out after 10m0s

goroutine 5622 [running]:
testing.(*M).startAlarm.func1()
	/tmp/workdir/go/src/testing/testing.go:1999 +0xc5
created by time.goFunc
	/tmp/workdir/go/src/time/sleep.go:176 +0x29

goroutine 1 [chan receive]:
testing.(*T).Run(0x608010e0, {0x83a29ba, 0x16}, 0x83beb70)
	/tmp/workdir/go/src/testing/testing.go:1457 +0x38d
testing.runTests.func1(0x608010e0)
	/tmp/workdir/go/src/testing/testing.go:1809 +0x58
testing.tRunner(0x608010e0, 0x608a7e38)
	/tmp/workdir/go/src/testing/testing.go:1409 +0x10d
testing.runTests(0x6080c2d0, {0x85e73c0, 0x48, 0x48}, {0xc05b5fbfb2fbac79, 0x8bb65fd067, 0x85eab40})
	/tmp/workdir/go/src/testing/testing.go:1807 +0x3a0
testing.(*M).Run(0x60882190)
	/tmp/workdir/go/src/testing/testing.go:1689 +0x675
main.main()
	_testmain.go:189 +0x17f

goroutine 5439 [chan receive]:
golang.org/x/review/git-codereview.cmdPending({0x60984100, 0x2, 0x2})
	/tmp/workdir/gopath/src/golang.org/x/review/git-codereview/pending.go:148 +0x59c
golang.org/x/review/git-codereview.syncBranchContinue({0x839bbeb, 0xa}, 0x608ea0c0, 0x6096aa00)
	/tmp/workdir/gopath/src/golang.org/x/review/git-codereview/sync.go:407 +0x135b
golang.org/x/review/git-codereview.cmdSyncBranch({0x60a62370, 0x1, 0x1})
	/tmp/workdir/gopath/src/golang.org/x/review/git-codereview/sync.go:170 +0x46f
golang.org/x/review/git-codereview.main()
	/tmp/workdir/gopath/src/golang.org/x/review/git-codereview/review.go:141 +0x3cc
golang.org/x/review/git-codereview.testMain(0x609c3950, {0x608e1ecc, 0x2, 0x2})
	/tmp/workdir/gopath/src/golang.org/x/review/git-codereview/util_test.go:359 +0x304
golang.org/x/review/git-codereview.TestSyncBranchConflict(0x609c3950)
	/tmp/workdir/gopath/src/golang.org/x/review/git-codereview/sync_test.go:367 +0x5eb
testing.tRunner(0x609c3950, 0x83beb70)
	/tmp/workdir/go/src/testing/testing.go:1409 +0x10d
created by testing.(*T).Run
	/tmp/workdir/go/src/testing/testing.go:1456 +0x36e

goroutine 5585 [runnable]:
syscall.syscall(0x80b8b80, 0x6092a250, 0x609fade8, 0x0)
	/tmp/workdir/go/src/runtime/sys_openbsd3.go:24 +0x20
syscall.Stat({0x6092a1c8, 0x8}, 0x609fade8)
	/tmp/workdir/go/src/syscall/zsyscall_openbsd_386.go:1439 +0xc7
os.statNolog.func1(...)
	/tmp/workdir/go/src/os/stat_unix.go:32
os.ignoringEINTR(...)
	/tmp/workdir/go/src/os/file_posix.go:245
os.statNolog({0x6092a1c8, 0x8})
	/tmp/workdir/go/src/os/stat_unix.go:31 +0x4c
os.Stat({0x6092a1c8, 0x8})
	/tmp/workdir/go/src/os/stat.go:13 +0x37
os/exec.findExecutable({0x6092a1c8, 0x8})
	/tmp/workdir/go/src/os/exec/lp_unix.go:21 +0x27
os/exec.LookPath({0x8399d5b, 0x3})
	/tmp/workdir/go/src/os/exec/lp_unix.go:54 +0x229
os/exec.Command({0x8399d5b, 0x3}, {0x6083aee0, 0x5, 0x5})
	/tmp/workdir/go/src/os/exec/exec.go:175 +0x1ac
golang.org/x/review/git-codereview.cmdOutputDirErr({0x8399a2c, 0x1}, {0x8399d5b, 0x3}, {0x6083aee0, 0x5, 0x5})
	/tmp/workdir/gopath/src/golang.org/x/review/git-codereview/review.go:258 +0x112
golang.org/x/review/git-codereview.cmdOutputDir({0x8399a2c, 0x1}, {0x8399d5b, 0x3}, {0x6083aee0, 0x5, 0x5})
	/tmp/workdir/gopath/src/golang.org/x/review/git-codereview/review.go:223 +0x61
golang.org/x/review/git-codereview.cmdOutput(...)
	/tmp/workdir/gopath/src/golang.org/x/review/git-codereview/review.go:212
golang.org/x/review/git-codereview.ListFiles(0x60890180)
	/tmp/workdir/gopath/src/golang.org/x/review/git-codereview/branch.go:529 +0xda
golang.org/x/review/git-codereview.(*pendingBranch).load(0x60810210)
	/tmp/workdir/gopath/src/golang.org/x/review/git-codereview/pending.go:47 +0x1ac
golang.org/x/review/git-codereview.cmdPending.func2()
	/tmp/workdir/gopath/src/golang.org/x/review/git-codereview/pending.go:139 +0x3b
created by golang.org/x/review/git-codereview.cmdPending
	/tmp/workdir/gopath/src/golang.org/x/review/git-codereview/pending.go:136 +0x517
FAIL	golang.org/x/review/git-codereview	600.285s
```

</details>

`greplogs --dashboard -md -l -e '(?ms)\Aopenbsd.*panic: test timed out.*FAIL\s+golang\.org/x/review' --since=2021-06-01`

<details>

[2021-11-11T11:47:33-39ade5b-c49627e/openbsd-386-68](https://build.golang.org/log/3467218241a8e263c57894f35287e144a4f4ec3b)
[2021-11-10T21:53:03-39ade5b-229b909/openbsd-386-68](https://build.golang.org/log/f1d995f568425b2b0ce3b0e866d801507b6b9970)
[2021-11-10T17:15:54-39ade5b-8a3be15/openbsd-386-68](https://build.golang.org/log/eefddf524e93df35f679b51d8f2137f3e92a5537)
[2021-11-10T00:45:37-39ade5b-ec86bb5/openbsd-386-68](https://build.golang.org/log/d4fc4523c94ce21d4d124a3b28996b8086a1655e)
[2021-11-09T20:47:54-39ade5b-a096316/openbsd-386-68](https://build.golang.org/log/5f3d50e580b2636c0f7b59cf266fcec955b6378f)
[2021-11-09T18:37:32-39ade5b-01103d5/openbsd-386-68](https://build.golang.org/log/55d940c2b6ca61ac6c9315d4da14f01c94b6e606)
[2021-11-09T02:28:30-39ade5b-6dcf83d/openbsd-386-68](https://build.golang.org/log/d5328cff446a9aa7d25adf66eeeeddc20bde440a)
[2021-11-08T17:30:10-39ade5b-6a9d811/openbsd-386-68](https://build.golang.org/log/62ec593d78d36a04e012971dd77590361442f590)
[2021-11-07T04:57:22-39ade5b-9e6ad46/openbsd-386-68](https://build.golang.org/log/2cc3de266bdac42ada896f36453fe45f49619b1d)
[2021-11-06T19:41:15-39ade5b-61d789d/openbsd-386-68](https://build.golang.org/log/3c99d620b88698f45ff9d84af2d8b5fec5dfbec6)
[2021-11-05T22:57:08-39ade5b-09e8de7/openbsd-386-68](https://build.golang.org/log/7ece841b9f216883973efc1d62f2d680031ef96a)
[2021-11-05T21:18:28-39ade5b-4c7cafd/openbsd-386-68](https://build.golang.org/log/cb4b4f8c73d26d85440624ebf19aa631d692c56a)
[2021-11-05T17:52:30-39ade5b-df18377/openbsd-386-68](https://build.golang.org/log/c60fa88a02df786d8bacffe14948693e5ad8edad)
[2021-11-05T16:35:00-39ade5b-f249fa2/openbsd-386-68](https://build.golang.org/log/d0fae74897a2fc4b0657928a3f4a7faba5577522)
[2021-11-04T02:57:53-39ade5b-2cf85b1/openbsd-386-68](https://build.golang.org/log/2322a770229a398a18fd6928f80cab2a98a07d62)
[2021-11-04T02:12:52-39ade5b-bd49a99/openbsd-386-68](https://build.golang.org/log/f571acf56f1f636c4322990ae030dd5c1315ebe1)
[2021-11-04T01:44:54-39ade5b-d9bb5f6/openbsd-386-68](https://build.golang.org/log/63d359ac64e116f9925287a90659f96a05498a12)
[2021-11-03T21:45:33-39ade5b-d3f5dd5/openbsd-386-68](https://build.golang.org/log/3f0c1c6f2ebf2c2a13adae13ea59c59b6e0f81d0)
[2021-11-03T18:37:22-39ade5b-cfd016d/openbsd-386-68](https://build.golang.org/log/b006997dd1880b8b7ca43e05e6041eac675bc505)
[2021-11-03T00:21:24-39ade5b-8f0ca7d/openbsd-386-68](https://build.golang.org/log/f443bbeb1c94ee8524f7b4d21694c0ec6172ac45)
[2021-11-02T18:35:35-39ade5b-c702f91/openbsd-386-68](https://build.golang.org/log/e8909dbfba2155825c752004341b362ad7b7f76a)
[2021-11-02T18:01:20-39ade5b-629ffeb/openbsd-386-68](https://build.golang.org/log/1b4bbe6048d884afe91c054c61bb6d5ea5e5759e)
[2021-11-02T15:51:21-39ade5b-c3cb1ec/openbsd-386-68](https://build.golang.org/log/fc5d772ff801d898f9b80a4acb5174f637f4f5d4)
[2021-11-02T03:55:19-39ade5b-6f1e9a9/openbsd-386-68](https://build.golang.org/log/7df703c7d5e031783f191677bde6d6f51e7ca4e4)
[2021-10-31T18:39:05-39ade5b-89c5270/openbsd-386-68](https://build.golang.org/log/80fef5c10b31dd8495b51edca85a536a5e424e11)
[2021-10-31T18:13:09-39ade5b-fd09e88/openbsd-386-68](https://build.golang.org/log/6eaf291437c5a684d2e10803a4aa1ae670cb8370)
[2021-10-29T18:56:29-39ade5b-6afdf01/openbsd-386-68](https://build.golang.org/log/ecaeafbec338a9d85c5c550eeb569c49cbf93342)
[2021-10-28T21:17:17-39ade5b-f6f024f/openbsd-386-68](https://build.golang.org/log/c040546b7b68000e1bb06693fb3d043a42b6b95b)
[2021-10-28T18:17:57-39ade5b-f229e70/openbsd-386-68](https://build.golang.org/log/9f2ba652bd723dc7f14e76f8b7ce2c9a7b9d1829)
[2021-10-28T16:54:58-39ade5b-6bd0e7f/openbsd-386-68](https://build.golang.org/log/a4318dd9b364ecc5219e616dda548d1ff7b1906d)
[2021-10-28T15:35:25-39ade5b-278b9b3/openbsd-386-68](https://build.golang.org/log/061462cd6583319e100f5562c112827fbc3c8e42)
[2021-10-28T15:08:31-39ade5b-5c98bcb/openbsd-386-68](https://build.golang.org/log/0cf17b29ffd00e53ecf8d9988d5f4dc3c6a11d66)
[2021-10-27T22:17:35-39ade5b-79ff663/openbsd-386-68](https://build.golang.org/log/564dfe9f0fa7e6f54ce53dff337d1f9494013c9a)
[2021-10-27T16:59:43-39ade5b-c0ac39c/openbsd-386-68](https://build.golang.org/log/33cd698a8d778fdd5baf77195cf45f836e35e0ae)
[2021-10-27T13:12:49-39ade5b-cfb5321/openbsd-386-68](https://build.golang.org/log/f890a240e410b4b1ffc3055c07845ca4e1d3259e)
[2021-10-27T08:50:27-39ade5b-bdefb77/openbsd-386-68](https://build.golang.org/log/4ca6060eb2fc90e5338e94fae26069b33477a58e)
[2021-10-26T05:05:24-39ade5b-23fdd7f/openbsd-386-68](https://build.golang.org/log/b01353c1b696e3683a4aa0824d95d56d4a543d6b)
[2021-10-19T07:37:24-39ade5b-8838a3b/openbsd-386-64](https://build.golang.org/log/fb3aaacb771866d142461c185dd267b53cc3460b)

</details>

**Comment by bcmills** [comment]
This looks like a regression within the Go 1.18 development window, so marking as release-blocker.

**Comment by bcmills** [comment]
Nothing in the failure logs gives me any reason to believe that anything is deadlocked. I wonder if `git` itself is just too slow on this platform.

I doubt that many folks are actively working in the Go repos on 32-bit OpenBSD, so I suggest we just stop running this repo on this builder.
