### ISSUE TITLE
fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by andig** [golang/go#49543]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.2 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/andig/Library/Caches/go-build"
GOENV="/Users/andig/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/andig/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/andig/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.17.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.17.2/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.17.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/andig/htdocs/evcc/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sv/rs_453y57xj86xsbz3kw1mbc0000gn/T/go-build3373630272=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version go1.17.2 darwin/arm64
GOROOT/bin/go tool compile -V: compile version go1.17.2
uname -v: Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101
ProductName:	macOS
ProductVersion:	12.0.1
BuildVersion:	21A559
lldb --version: lldb-1300.0.32.4
Swift version 5.5.1-dev
</pre></details>

### What did you do?

Execute custom program (no cgo, many modules):

    go run -race main.go charger --log trace -c cfg/easee.yaml

### What did you expect to see?

No error

### What did you see instead?

Dump below. This has not happened before and not since.

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=0x4000000000000000 pc=0x1aa94bec4]

runtime stack:
runtime.throw({0x102513827, 0x2a})
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/runtime/panic.go:1198 +0x54
runtime.sigpanic()
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/runtime/signal_unix.go:719 +0x230

goroutine 43 [syscall]:
runtime.cgocall(0x100fed140, 0xc000304ce8)
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/runtime/cgocall.go:156 +0x68 fp=0xc000304cb0 sp=0xc000304c70 pc=0x10102a2b8
net._C2func_getaddrinfo(0xc00043c022, 0x0, 0xc000700900, 0xc000310868)
	_cgo_gotypes.go:97 +0x64 fp=0xc000304ce0 sp=0xc000304cb0 pc=0x101289614
net.cgoLookupIPCNAME.func1({0xc00043c022, 0xe, 0xe}, 0xc000700900, 0xc000310868)
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/net/cgo_unix.go:163 +0xd4 fp=0xc000304d40 sp=0xc000304ce0 pc=0x10128bb04
net.cgoLookupIPCNAME({0x1024cb5a7, 0x3}, {0x1024e3ffb, 0xd})
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/net/cgo_unix.go:163 +0x260 fp=0xc000304f10 sp=0xc000304d40 pc=0x10128b1b0
net.cgoIPLookup(0xc0003082a0, {0x1024cb5a7, 0x3}, {0x1024e3ffb, 0xd})
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/net/cgo_unix.go:220 +0x4c fp=0xc000304fb0 sp=0xc000304f10 pc=0x10128bbac
runtime.goexit()
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/runtime/asm_arm64.s:1133 +0x4 fp=0xc000304fb0 sp=0xc000304fb0 pc=0x101096fc4
created by net.cgoLookupIP
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/net/cgo_unix.go:230 +0xa4

goroutine 1 [select]:
google.golang.org/grpc.(*pickerWrapper).pick(0xc0002f6990, {0x103657a38, 0xc0002f75c0}, 0x1, {{0x1024e328d, 0x12}, {0x103657a38, 0xc0002f75c0}})
	/Users/andig/go/pkg/mod/google.golang.org/grpc@v1.39.0/picker_wrapper.go:103 +0x160
google.golang.org/grpc.(*ClientConn).getTransport(0xc0000f0a80, {0x103657a38, 0xc0002f75c0}, 0x1, {0x1024e328d, 0x12})
	/Users/andig/go/pkg/mod/google.golang.org/grpc@v1.39.0/clientconn.go:938 +0x7c
google.golang.org/grpc.(*clientStream).newAttemptLocked(0xc0004d1d40, {0x0, 0x0}, 0x0)
	/Users/andig/go/pkg/mod/google.golang.org/grpc@v1.39.0/stream.go:404 +0x574
google.golang.org/grpc.newClientStreamWithParams({0x103657a00, 0xc0002b3a40}, 0x104248320, 0xc0000f0a80, {0x1024e328d, 0x12}, {0x0, 0x0, 0x0, 0x0, ...}, ...)
	/Users/andig/go/pkg/mod/google.golang.org/grpc@v1.39.0/stream.go:328 +0x15e4
google.golang.org/grpc.newClientStream.func2({0x103657a00, 0xc0002b3a40}, 0x103616ca0)
	/Users/andig/go/pkg/mod/google.golang.org/grpc@v1.39.0/stream.go:184 +0x130
google.golang.org/grpc.newClientStream({0x103657a00, 0xc0002b3a40}, 0x104248320, 0xc0000f0a80, {0x1024e328d, 0x12}, {0x0, 0x0, 0x0})
	/Users/andig/go/pkg/mod/google.golang.org/grpc@v1.39.0/stream.go:212 +0x608
google.golang.org/grpc.invoke({0x103657a00, 0xc0002b3a40}, {0x1024e328d, 0x12}, {0x1034c4f20, 0xc0004bb640}, {0x1034fcd00, 0xc0004bb680}, 0xc0000f0a80, {0x0, ...})
	/Users/andig/go/pkg/mod/google.golang.org/grpc@v1.39.0/call.go:66 +0x8c
google.golang.org/grpc.(*ClientConn).Invoke(0xc0000f0a80, {0x103657a00, 0xc0002b3a40}, {0x1024e328d, 0x12}, {0x1034c4f20, 0xc0004bb640}, {0x1034fcd00, 0xc0004bb680}, {0x0, ...})
	/Users/andig/go/pkg/mod/google.golang.org/grpc@v1.39.0/call.go:37 +0x25c
github.com/evcc-io/evcc/api/proto/pb.(*authClient).IsAuthorized(0xc00051f178, {0x103657a00, 0xc0002b3a40}, 0xc0004bb640, {0x0, 0x0, 0x0})
	/Users/andig/htdocs/evcc/api/proto/pb/auth_grpc.pb.go:34 +0xcc
github.com/evcc-io/evcc/cmd.configureSponsorship({0xc0005ae340, 0xcc})
	/Users/andig/htdocs/evcc/cmd/setup.go:84 +0x214
github.com/evcc-io/evcc/cmd.configureEnvironment({{0xc00019abd2, 0xe}, {0x16ee13888, 0x5}, {0xc0005ae340, 0xcc}, 0x0, 0x0, 0x0, 0x2540be400, ...})
	/Users/andig/htdocs/evcc/cmd/setup.go:51 +0x4c
github.com/evcc-io/evcc/cmd.runCharger(0x1042231a0, {0xc0004bb3c0, 0x0, 0x4})
	/Users/andig/htdocs/evcc/cmd/charger.go:33 +0x33c
github.com/spf13/cobra.(*Command).execute(0x1042231a0, {0xc0004bb380, 0x4, 0x4})
	/Users/andig/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x9c4
github.com/spf13/cobra.(*Command).ExecuteC(0x104223920)
	/Users/andig/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x5b0
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/andig/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/evcc-io/evcc/cmd.Execute()
	/Users/andig/htdocs/evcc/cmd/root.go:134 +0x4c
main.main()
	/Users/andig/htdocs/evcc/main.go:33 +0x58

goroutine 8 [select]:
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc00031fc70)
	/Users/andig/go/pkg/mod/google.golang.org/grpc@v1.39.0/balancer_conn_wrappers.go:71 +0x114
created by google.golang.org/grpc.newCCBalancerWrapper
	/Users/andig/go/pkg/mod/google.golang.org/grpc@v1.39.0/balancer_conn_wrappers.go:62 +0x418

goroutine 9 [select]:
net.(*Resolver).lookupIPAddr(0x104248360, {0x103657a00, 0xc0003081e0}, {0x1024cb5a7, 0x3}, {0x1024e3ffb, 0xd})
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/net/lookup.go:302 +0x7b0
net.(*Resolver).internetAddrList(0x104248360, {0x103657a00, 0xc0003081e0}, {0x1024cb5a7, 0x3}, {0x1024e3ffb, 0x12})
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/net/ipsock.go:288 +0x7a8
net.(*Resolver).resolveAddrList(0x104248360, {0x103657a00, 0xc0003081e0}, {0x1024cc084, 0x4}, {0x1024cb5a7, 0x3}, {0x1024e3ffb, 0x12}, {0x0, ...})
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/net/dial.go:221 +0x55c
net.(*Dialer).DialContext(0xc000448af8, {0x103657a00, 0xc0003081e0}, {0x1024cb5a7, 0x3}, {0x1024e3ffb, 0x12})
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/net/dial.go:406 +0x550
google.golang.org/grpc/internal/transport.proxyDial({0x103657a00, 0xc0003081e0}, {0x1024e3ffb, 0x12}, {0x1024dd0fa, 0xe})
	/Users/andig/go/pkg/mod/google.golang.org/grpc@v1.39.0/internal/transport/proxy.go:125 +0xe0
google.golang.org/grpc/internal/transport.dial({0x103657a00, 0xc0003081e0}, 0x0, {{0x1024e3ffb, 0x12}, {0x1024e3ffb, 0x12}, 0x0, 0x0, {0x0, ...}}, ...)
	/Users/andig/go/pkg/mod/google.golang.org/grpc@v1.39.0/internal/transport/http2_client.go:162 +0x310
google.golang.org/grpc/internal/transport.newHTTP2Client({0x103657a00, 0xc0003081e0}, {0x103657990, 0xc0004bb500}, {{0x1024e3ffb, 0x12}, {0x1024e3ffb, 0x12}, 0x0, 0x0, ...}, ...)
	/Users/andig/go/pkg/mod/google.golang.org/grpc@v1.39.0/internal/transport/http2_client.go:195 +0x110
google.golang.org/grpc/internal/transport.NewClientTransport(...)
	/Users/andig/go/pkg/mod/google.golang.org/grpc@v1.39.0/internal/transport/transport.go:574
google.golang.org/grpc.(*addrConn).createTransport(0xc00003e2c0, {{0x1024e3ffb, 0x12}, {0x1024e3ffb, 0x12}, 0x0, 0x0, {0x0, 0x0}}, {{0x1024dd0fa, ...}, ...}, ...)
	/Users/andig/go/pkg/mod/google.golang.org/grpc@v1.39.0/clientconn.go:1328 +0x5fc
google.golang.org/grpc.(*addrConn).tryAllAddrs(0xc00003e2c0, {0xc0004bb580, 0x1, 0x1}, {0xc05bb03a1b9ebd60, 0x4aade28c7, 0x104249940})
	/Users/andig/go/pkg/mod/google.golang.org/grpc@v1.39.0/clientconn.go:1258 +0x3e8
google.golang.org/grpc.(*addrConn).resetTransport(0xc00003e2c0)
	/Users/andig/go/pkg/mod/google.golang.org/grpc@v1.39.0/clientconn.go:1173 +0x274
created by google.golang.org/grpc.(*addrConn).connect
	/Users/andig/go/pkg/mod/google.golang.org/grpc@v1.39.0/clientconn.go:849 +0xdc

goroutine 42 [select]:
net.cgoLookupIP({0x103657990, 0xc00004e0c0}, {0x1024cb5a7, 0x3}, {0x1024e3ffb, 0xd})
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/net/cgo_unix.go:231 +0x138
net.(*Resolver).lookupIP(0x104248360, {0x103657990, 0xc00004e0c0}, {0x1024cb5a7, 0x3}, {0x1024e3ffb, 0xd})
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/net/lookup_unix.go:97 +0xe0
net.glob..func1({0x103657990, 0xc00004e0c0}, 0xc00007e100, {0x1024cb5a7, 0x3}, {0x1024e3ffb, 0xd})
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/net/hook.go:23 +0x64
net.(*Resolver).lookupIPAddr.func1()
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/net/lookup.go:296 +0x100
internal/singleflight.(*Group).doCall(0x104248370, 0xc0004f00a0, {0xc00014e078, 0x11}, 0xc00004e100)
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/internal/singleflight/singleflight.go:95 +0x34
created by internal/singleflight.(*Group).DoChan
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/internal/singleflight/singleflight.go:88 +0x44c
exit status 2
```

**Comment by andig** [comment]
I believe this might be caused by a race condition in the programs code. Closing for time being until those are resolved.

**Comment by andig** [comment]
Also seeing:

```
main(14254,0x16b80f000) malloc: Heap corruption detected, free list is damaged at 0x60000000c180
*** Incorrect guard value: 0
main(14254,0x16b80f000) malloc: *** set a breakpoint in malloc_error_break to debug
SIGABRT: abort
PC=0x1aaa719b8 m=8 sigcode=0

goroutine 0 [idle]:
runtime: unknown pc 0x1aaa719b8
stack: frame={sp:0x16b80e350, fp:0x0} stack=[0x16b78f328,0x16b80ef28)
0x000000016b80e250:  0x0000000200ad6e9c  0x0000000203cb80e0
0x000000016b80e260:  0x36315e62413100ed  0x0030303066303862
0x000000016b80e270:  0x0000000000000005  0x0000000000000000
0x000000016b80e280:  0x000000000000000a  0x0000000000000000
0x000000016b80e290:  0x0000000000000070  0x0000000000000000
0x000000016b80e2a0:  0x0000000000000000  0x00000001aa8e1ecd
0x000000016b80e2b0:  0x0000000108cb0000  0x0000000000000000
0x000000016b80e2c0:  0x000000016b80e330  0xef050001aaabcdac
0x000000016b80e2d0:  0x000000016b80e460  0x000000016b80e368
0x000000016b80e2e0:  0x0000000000000005  0x000000016b80f000
0x000000016b80e2f0:  0x000000016b43f81d  0x0000000000000000
0x000000016b80e300:  0x0000000000000000  0x000000016b80f000
0x000000016b80e310:  0x000000016b43f81d  0x0000000108cb0000
0x000000016b80e320:  0x0000000000000043  0x00000001aa8e1ed8
0x000000016b80e330:  0x000000016b43f81d  0x0000000108cb0000
0x000000016b80e340:  0x0000000000000043  0x00000001aa8e1ed8
0x000000016b80e350: <0x000000016b80e460  0x0000000108cac028
0x000000016b80e360:  0x000000016b80e398  0x000000016b80f000
0x000000016b80e370:  0x000000016b80e3b0  0x8a460001aa9e2314
0x000000016b80e380:  0x0000000000000000  0xffffffff08cac000
0x000000016b80e390:  0x000000016b80e460  0x00000001fffff9df
0x000000016b80e3a0:  0x0000000000000000  0x0000000000000043
0x000000016b80e3b0:  0x000000016b80e430  0x67068001aa8c7a1c
0x000000016b80e3c0:  0x000000016b43f81d  0x00000000000037ae
0x000000016b80e3d0:  0x000000016b80f000  0x000060000160c3ee
0x000000016b80e3e0:  0x0000000000000005  0x00000000001ff800
0x000000016b80e3f0:  0x0000000000000060  0x0000000000000005
0x000000016b80e400:  0x000060000000c000  0x0000000081052805
0x000000016b80e410:  0x0000000108c4b058  0x000060000000c000
0x000000016b80e420:  0x000060000260c300  0x000000016b80f0e0
0x000000016b80e430:  0x000000016b80e450  0x45388001aa8dcc8c
0x000000016b80e440:  0x000000000000001c  0x000000016b80e460
runtime: unknown pc 0x1aaa719b8
stack: frame={sp:0x16b80e350, fp:0x0} stack=[0x16b78f328,0x16b80ef28)
0x000000016b80e250:  0x0000000200ad6e9c  0x0000000203cb80e0
0x000000016b80e260:  0x36315e62413100ed  0x0030303066303862
0x000000016b80e270:  0x0000000000000005  0x0000000000000000
0x000000016b80e280:  0x000000000000000a  0x0000000000000000
0x000000016b80e290:  0x0000000000000070  0x0000000000000000
0x000000016b80e2a0:  0x0000000000000000  0x00000001aa8e1ecd
0x000000016b80e2b0:  0x0000000108cb0000  0x0000000000000000
0x000000016b80e2c0:  0x000000016b80e330  0xef050001aaabcdac
0x000000016b80e2d0:  0x000000016b80e460  0x000000016b80e368
0x000000016b80e2e0:  0x0000000000000005  0x000000016b80f000
0x000000016b80e2f0:  0x000000016b43f81d  0x0000000000000000
0x000000016b80e300:  0x0000000000000000  0x000000016b80f000
0x000000016b80e310:  0x000000016b43f81d  0x0000000108cb0000
0x000000016b80e320:  0x0000000000000043  0x00000001aa8e1ed8
0x000000016b80e330:  0x000000016b43f81d  0x0000000108cb0000
0x000000016b80e340:  0x0000000000000043  0x00000001aa8e1ed8
0x000000016b80e350: <0x000000016b80e460  0x0000000108cac028
0x000000016b80e360:  0x000000016b80e398  0x000000016b80f000
0x000000016b80e370:  0x000000016b80e3b0  0x8a460001aa9e2314
0x000000016b80e380:  0x0000000000000000  0xffffffff08cac000
0x000000016b80e390:  0x000000016b80e460  0x00000001fffff9df
0x000000016b80e3a0:  0x0000000000000000  0x0000000000000043
0x000000016b80e3b0:  0x000000016b80e430  0x67068001aa8c7a1c
0x000000016b80e3c0:  0x000000016b43f81d  0x00000000000037ae
0x000000016b80e3d0:  0x000000016b80f000  0x000060000160c3ee
0x000000016b80e3e0:  0x0000000000000005  0x00000000001ff800
0x000000016b80e3f0:  0x0000000000000060  0x0000000000000005
0x000000016b80e400:  0x000060000000c000  0x0000000081052805
0x000000016b80e410:  0x0000000108c4b058  0x000060000000c000
0x000000016b80e420:  0x000060000260c300  0x000000016b80f0e0
0x000000016b80e430:  0x000000016b80e450  0x45388001aa8dcc8c
0x000000016b80e440:  0x000000000000001c  0x000000016b80e460

goroutine 12 [syscall]:
runtime.cgocall(0x1049c1140, 0xc00048e4e8)
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/runtime/cgocall.go:156 +0x68 fp=0xc00048e4b0 sp=0xc00048e470 pc=0x1049fe2b8
net._C2func_getaddrinfo(0xc0000e8360, 0x0, 0xc000597ec0, 0xc0000102f0)
	_cgo_gotypes.go:97 +0x64 fp=0xc00048e4e0 sp=0xc00048e4b0 pc=0x104c5c604
net.cgoLookupIPCNAME.func1({0xc0000e8360, 0x10, 0x10}, 0xc000597ec0, 0xc0000102f0)
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/net/cgo_unix.go:163 +0xd4 fp=0xc00048e540 sp=0xc00048e4e0 pc=0x104c5eaf4
net.cgoLookupIPCNAME({0x105e9dde7, 0x3}, {0xc0000498c0, 0xf})
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/net/cgo_unix.go:163 +0x260 fp=0xc00048e710 sp=0xc00048e540 pc=0x104c5e1a0
net.cgoIPLookup(0xc0001bb9e0, {0x105e9dde7, 0x3}, {0xc0000498c0, 0xf})
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/net/cgo_unix.go:220 +0x4c fp=0xc00048e7b0 sp=0xc00048e710 pc=0x104c5eb9c
runtime.goexit()
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/runtime/asm_arm64.s:1133 +0x4 fp=0xc00048e7b0 sp=0xc00048e7b0 pc=0x104a6aba4
created by net.cgoLookupIP
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/net/cgo_unix.go:230 +0xa4
```

**Comment by andig** [comment]
And:

```
main(15090,0x16b58f000) malloc: Heap corruption detected, free list is damaged at 0x600003070180
*** Incorrect guard value: 0
main(15090,0x16b58f000) malloc: *** set a breakpoint in malloc_error_break to debug
SIGABRT: abort
PC=0x1aaa719b8 m=11 sigcode=0

goroutine 0 [idle]:
crypto/x509/internal/macos.syscall(0x105097cc0, 0x0, 0xc000888890, 0x0, 0x0, 0x0, 0x0)
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/runtime/sys_darwin.go:95 +0x14 fp=0xc0008887f0 sp=0xc0008887c0 pc=0x104e8bc84
crypto/x509/internal/macos.SecTrustSettingsCopyCertificates(0x0)
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/crypto/x509/internal/macos/security.go:71 +0x5c fp=0xc000888880 sp=0xc0008887f0 pc=0x10509762c
crypto/x509.loadSystemRoots()
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/crypto/x509/root_darwin.go:36 +0xfc fp=0xc000888b10 sp=0xc000888880 pc=0x1050a5a3c
crypto/x509.initSystemRoots()
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/crypto/x509/root.go:27 +0x2c fp=0xc000888b50 sp=0xc000888b10 pc=0x1050a581c
sync.(*Once).doSlow(0x10806e718, 0x1074073f8)
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/sync/once.go:68 +0xbc fp=0xc000888c20 sp=0xc000888b50 pc=0x104e9ce6c
sync.(*Once).Do(0x10806e718, 0x1074073f8)
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/sync/once.go:59 +0x54 fp=0xc000888c40 sp=0xc000888c20 pc=0x104e9cd94
crypto/x509.systemRootsPool(...)
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/crypto/x509/root.go:22
crypto/x509.(*Certificate).Verify(0xc0008ae000, {{0xc0007120a8, 0xf}, 0xc000796c60, 0x0, {0xc05bb7f51ab34808, 0x18a9f055, 0x10803d940}, {0x0, 0x0, ...}, ...})
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/crypto/x509/verify.go:750 +0x2a8 fp=0xc000888e30 sp=0xc000888c40 pc=0x1050abc88
crypto/tls.(*Conn).verifyServerCertificate(0xc00089c000, {0xc000794f60, 0x4, 0x4})
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/crypto/tls/handshake_client.go:868 +0x7b8 fp=0xc000889240 sp=0xc000888e30 pc=0x1050ddc58
crypto/tls.(*clientHandshakeState).doFullHandshake(0xc000889b68)
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/crypto/tls/handshake_client.go:513 +0x298 fp=0xc000889600 sp=0xc000889240 pc=0x1050d93a8
crypto/tls.(*clientHandshakeState).handshake(0xc000889b68)
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/crypto/tls/handshake_client.go:431 +0x594 fp=0xc0008899c0 sp=0xc000889600 pc=0x1050d8af4
crypto/tls.(*Conn).clientHandshake(0xc00089c000, {0x10744b430, 0xc0003f63c0})
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/crypto/tls/handshake_client.go:230 +0x5c4 fp=0xc000889cf0 sp=0xc0008899c0 pc=0x1050d6df4
crypto/tls.(*Conn).clientHandshake-fm({0x10744b430, 0xc0003f63c0})
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/crypto/tls/handshake_client.go:145 +0x54 fp=0xc000889d40 sp=0xc000889cf0 pc=0x105128594
crypto/tls.(*Conn).handshakeContext(0xc00089c000, {0x10744b4a0, 0xc00013a3c0})
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/crypto/tls/conn.go:1445 +0x24c fp=0xc000889f40 sp=0xc000889d40 pc=0x1050d45dc
crypto/tls.(*Conn).HandshakeContext(...)
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/crypto/tls/conn.go:1395
net/http.(*persistConn).addTLS.func2(0x0, 0xc00089c000, {0x10744b4a0, 0xc00013a3c0}, 0xc0003fe2d0, 0xc0007944e0)
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/net/http/transport.go:1534 +0x88 fp=0xc000889fa0 sp=0xc000889f40 pc=0x1052610c8
runtime.goexit()
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/runtime/asm_arm64.s:1133 +0x4 fp=0xc000889fa0 sp=0xc000889fa0 pc=0x104e8eba4
created by net/http.(*persistConn).addTLS
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/net/http/transport.go:1530 +0x4b8
```

**Comment by andig** [comment]
And:

```
objc[16564]: Attempt to use unknown class 0x203cee298.
SIGABRT: abort
PC=0x1aaa93eb8 m=10 sigcode=0

goroutine 0 [idle]:
runtime: unknown pc 0x1aaa93eb8
stack: frame={sp:0x16fccddf0, fp:0x0} stack=[0x16fc4f328,0x16fccef28)
0x000000016fccdcf0:  0x000000016fccdd50  0xaf078001aa8b93a4
0x000000016fccdd00:  0x0000000010000003  0x000000016fccf0e0
0x000000016fccdd10:  0x0000000200ad6e9c  0x0000000003000207
0x000000016fccdd20:  0x0000000000000020  0x0000000000000000
0x000000016fccdd30:  0x000000016fccf0e0  0x0000000203cf8000
0x000000016fccdd40:  0x0000000104a4c000  0x000000000000002a
0x000000016fccdd50:  0x000000016fccdd70  0xf7580001aa8b92c0
0x000000016fccdd60:  0x000000000000002a  0x0000000000000001
0x000000016fccdd70:  0x000000016fccddb0  0xf4038001aa8d6770
0x000000016fccdd80:  0x0000000000000020  0x0000000200ad6000
0x000000016fccdd90:  0x000000016fccf0e0  0x0000000200ad6e2c
0x000000016fccdda0:  0x000000000000002a  0x0000600001b74000
0x000000016fccddb0:  0x000000016fccdde0  0x9c2d0001aa96af24
0x000000016fccddc0:  0x000000016fccf0e0  0x0000000200ad6e2c
0x000000016fccddd0:  0x0000600001b74000  0x0000000000000000
0x000000016fccdde0:  0x000000016fccde40  0x261b8001aa949c80
0x000000016fccddf0: <0x0000000000000000  0x0000002000000000
0x000000016fccde00:  0x0000000000000020  0x0000000080080001
0x000000016fccde10:  0x0000000203cee298  0x0000600000474000
0x000000016fccde20:  0x0000000000000001  0x0000000000000080
0x000000016fccde30:  0x000000016fccde40  0xc43f8001aaa967fc
0x000000016fccde40:  0x000000016fccde90  0x02790001aa955d6c
0x000000016fccde50:  0x00000000000040b4  0x0000600001b74000
0x000000016fccde60:  0x0000000203cee298  0x0000600000474000
0x000000016fccde70:  0x0000600001b74080  0x0000600001b74000
0x000000016fccde80:  0x00000001f4ccd9f8  0x0000000000000003
0x000000016fccde90:  0x000000016fccdeb0  0x85488001aa955cf4
0x000000016fccdea0:  0x00000001f4ccd9f8  0x000000016fccdec0
0x000000016fccdeb0:  0x000000016fcce470  0x4d108001aa930cf4
0x000000016fccdec0:  0x0000000203cee298  0x0000000000000000
0x000000016fccded0:  0x0000000000000000  0x0000000000000000
0x000000016fccdee0:  0x0000000000000000  0x0000000000000000
runtime: unknown pc 0x1aaa93eb8
stack: frame={sp:0x16fccddf0, fp:0x0} stack=[0x16fc4f328,0x16fccef28)
0x000000016fccdcf0:  0x000000016fccdd50  0xaf078001aa8b93a4
0x000000016fccdd00:  0x0000000010000003  0x000000016fccf0e0
0x000000016fccdd10:  0x0000000200ad6e9c  0x0000000003000207
0x000000016fccdd20:  0x0000000000000020  0x0000000000000000
0x000000016fccdd30:  0x000000016fccf0e0  0x0000000203cf8000
0x000000016fccdd40:  0x0000000104a4c000  0x000000000000002a
0x000000016fccdd50:  0x000000016fccdd70  0xf7580001aa8b92c0
0x000000016fccdd60:  0x000000000000002a  0x0000000000000001
0x000000016fccdd70:  0x000000016fccddb0  0xf4038001aa8d6770
0x000000016fccdd80:  0x0000000000000020  0x0000000200ad6000
0x000000016fccdd90:  0x000000016fccf0e0  0x0000000200ad6e2c
0x000000016fccdda0:  0x000000000000002a  0x0000600001b74000
0x000000016fccddb0:  0x000000016fccdde0  0x9c2d0001aa96af24
0x000000016fccddc0:  0x000000016fccf0e0  0x0000000200ad6e2c
0x000000016fccddd0:  0x0000600001b74000  0x0000000000000000
0x000000016fccdde0:  0x000000016fccde40  0x261b8001aa949c80
0x000000016fccddf0: <0x0000000000000000  0x0000002000000000
0x000000016fccde00:  0x0000000000000020  0x0000000080080001
0x000000016fccde10:  0x0000000203cee298  0x0000600000474000
0x000000016fccde20:  0x0000000000000001  0x0000000000000080
0x000000016fccde30:  0x000000016fccde40  0xc43f8001aaa967fc
0x000000016fccde40:  0x000000016fccde90  0x02790001aa955d6c
0x000000016fccde50:  0x00000000000040b4  0x0000600001b74000
0x000000016fccde60:  0x0000000203cee298  0x0000600000474000
0x000000016fccde70:  0x0000600001b74080  0x0000600001b74000
0x000000016fccde80:  0x00000001f4ccd9f8  0x0000000000000003
0x000000016fccde90:  0x000000016fccdeb0  0x85488001aa955cf4
0x000000016fccdea0:  0x00000001f4ccd9f8  0x000000016fccdec0
0x000000016fccdeb0:  0x000000016fcce470  0x4d108001aa930cf4
0x000000016fccdec0:  0x0000000203cee298  0x0000000000000000
0x000000016fccded0:  0x0000000000000000  0x0000000000000000
0x000000016fccdee0:  0x0000000000000000  0x0000000000000000

goroutine 21 [syscall]:
runtime.cgocall(0x100619140, 0xc000079ce8)
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/runtime/cgocall.go:156 +0x68 fp=0xc000079cb0 sp=0xc000079c70 pc=0x1006562b8
net._C2func_getaddrinfo(0xc000016022, 0x0, 0xc000366660, 0xc000010880)
	_cgo_gotypes.go:97 +0x64 fp=0xc000079ce0 sp=0xc000079cb0 pc=0x1008b4604
net.cgoLookupIPCNAME.func1({0xc000016022, 0xe, 0xe}, 0xc000366660, 0xc000010880)
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/net/cgo_unix.go:163 +0xd4 fp=0xc000079d40 sp=0xc000079ce0 pc=0x1008b6af4
net.cgoLookupIPCNAME({0x101af5da7, 0x3}, {0x101b0e7fe, 0xd})
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/net/cgo_unix.go:163 +0x260 fp=0xc000079f10 sp=0xc000079d40 pc=0x1008b61a0
net.cgoIPLookup(0xc000112360, {0x101af5da7, 0x3}, {0x101b0e7fe, 0xd})
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/net/cgo_unix.go:220 +0x4c fp=0xc000079fb0 sp=0xc000079f10 pc=0x1008b6b9c
runtime.goexit()
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/runtime/asm_arm64.s:1133 +0x4 fp=0xc000079fb0 sp=0xc000079fb0 pc=0x1006c2ba4
created by net.cgoLookupIP
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/net/cgo_unix.go:230 +0xa4
```

**Comment by reusee** [comment]
I believe it's the same issue to https://github.com/golang/go/issues/49138
