### ISSUE TITLE
runtime: apparent deadlock in TestFakeTime on solaris-amd64-oraclerel starting 2021-11-05

### ISSUE THREAD

**Issue by bcmills** [golang/go#49614]
```
goroutine 252574 [syscall, 1 minutes]:
runtime.syscall_wait4(0x5944, 0xc0006d6000, 0x0, 0xc0006d8000)
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/runtime/syscall_solaris.go:312 +0x86 fp=0xc000075d50 sp=0xc000075cf8 pc=0x46db26
syscall.Wait4(0x5944?, 0xc0006d6000?, 0x0?, 0xc0006d8000?)
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/syscall/syscall_solaris.go:245 +0x2c fp=0xc000075d98 sp=0xc000075d50 pc=0x47b5ec
os.(*Process).wait(0xc00017e000)
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/os/exec_unix.go:43 +0x85 fp=0xc000075df0 sp=0xc000075d98 pc=0x494aa5
os.(*Process).Wait(...)
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/os/exec.go:132
os/exec.(*Cmd).Wait(0xc00012e580)
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/os/exec/exec.go:507 +0x54 fp=0xc000075e68 sp=0xc000075df0 pc=0x4ea614
os/exec.(*Cmd).Run(0xc00012e580?)
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/os/exec/exec.go:341 +0x39 fp=0xc000075e88 sp=0xc000075e68 pc=0x4e9779
runtime_test.TestFakeTime(0xc0003ab520)
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/runtime/time_test.go:39 +0x16f fp=0xc000075f70 sp=0xc000075e88 pc=0x5dc70f
testing.tRunner(0xc0003ab520, 0x662910)
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/testing/testing.go:1410 +0x102 fp=0xc000075fc0 sp=0xc000075f70 pc=0x4dd042
testing.(*T).Run.func1()
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/testing/testing.go:1457 +0x2a fp=0xc000075fe0 sp=0xc000075fc0 pc=0x4ddeea
runtime.goexit()
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/runtime/asm_amd64.s:1579 +0x1 fp=0xc000075fe8 sp=0xc000075fe0 pc=0x470fe1
created by testing.(*T).Run
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/testing/testing.go:1457 +0x35f
```

`greplogs --dashboard -md -l -e 'goroutine \d+ \[.*, \d+ minutes\]:\n(?:.+\n\t.+\n)*os/exec.*\n\t.+\nruntime_test\.TestFakeTime'`

[2021-11-15T23:01:05-d156101/solaris-amd64-oraclerel](https://build.golang.org/log/82a2d194190bda562daef52f4eeefc23e402ba09)
[2021-11-15T21:22:18-c8d7c5f/solaris-amd64-oraclerel](https://build.golang.org/log/888ecac844c3521e01dfc14ddc3020dc747b4e15)
[2021-11-13T02:30:25-c546052/solaris-amd64-oraclerel](https://build.golang.org/log/362c91728f5eca7369bb752c37f6f39e37cabd1d)
[2021-11-12T23:34:09-fdee1b2/solaris-amd64-oraclerel](https://build.golang.org/log/c6085fd01e06c45973eed803d880251cf8d7d791)
[2021-11-12T18:14:22-8b66b3d/solaris-amd64-oraclerel](https://build.golang.org/log/71fcd7ff421ba7119de434645913a935930ecda0)
[2021-11-11T21:27:05-c3c4a2b/solaris-amd64-oraclerel](https://build.golang.org/log/7a5ea692511d1af3b7ca9a19a483b059eb8a1123)
[2021-11-11T19:44:13-d60a4e6/solaris-amd64-oraclerel](https://build.golang.org/log/587b7bb811be66edbed322ddc99be7ac33d27154)
[2021-11-09T22:58:24-578ada4/solaris-amd64-oraclerel](https://build.golang.org/log/186d2eec82b705213ebeae4d32db2e58ae06df0a)
[2021-11-09T22:14:26-1c86bee/solaris-amd64-oraclerel](https://build.golang.org/log/42098d786da8c54e4ae8e8d86d8f0644e9a200e5)
[2021-11-09T21:26:25-b93220c/solaris-amd64-oraclerel](https://build.golang.org/log/76446702117f1d1158e0aff0628b0f53b339191c)
[2021-11-08T22:05:00-67e2294/solaris-amd64-oraclerel](https://build.golang.org/log/2299329ee75fd2b4cc64f3e6cd9ae6681cdf61d4)
[2021-11-06T19:41:15-61d789d/solaris-amd64-oraclerel](https://build.golang.org/log/1f919cc7a6adf24dd5418a12efa3d518323cb697)
[2021-11-06T16:43:43-3544082/solaris-amd64-oraclerel](https://build.golang.org/log/ce59b7c06954c13f4b0329e7fc8b5f564eb68d63)
[2021-11-05T22:56:55-2f71c86/solaris-amd64-oraclerel](https://build.golang.org/log/05025557f20eec81015927d528a13bc7c293a17f)
[2021-11-05T19:48:29-c353f1b/solaris-amd64-oraclerel](https://build.golang.org/log/68f8b3d58b79360ff26d3755b913b5ec4a86a546)
(Note the ~1-year gap here.)
[2020-11-30T20:08:34-a45e12f/darwin-amd64-race](https://build.golang.org/log/589f739f992b2a06d8b1fef797009c02070c51bb)
(Note the ~1-year gap here too.)
[2019-11-06T15:08:19-cf3be9b/openbsd-amd64-62](https://build.golang.org/log/8a8cc2c6102b1e462afc71845e75d6b3e5d3e281)
[2019-11-06T13:55:04-6dc250f/darwin-amd64-nocgo](https://build.golang.org/log/79dabe3ed1f34b88cb9dd15c6a3ceac2672122d6)
[2019-11-06T09:08:53-6108998/darwin-386-10_14](https://build.golang.org/log/5c8fddb787f78b97e1175b4b14444db1b1dbe11c)
[2019-11-06T02:52:51-f71bd51/linux-arm](https://build.golang.org/log/cb826170928a492b25d9d4e4d219c968fce16057)

**Comment by ianlancetaylor** [comment]
I can totally recreate this on Solaris with `go test -test.short -test.run=TestFakeTime -test.count=100 -test.timeout=30s runtime`.  Interesting.  On my Linux laptop that command takes 0.345 seconds, on Solaris it invariably times out.

**Comment by ianlancetaylor** [comment]
It's the test program itself that is hanging.

(The `runTestProg` function puts a timeout on each test, so this failure may be causing #44422 by taking so long that it pushes the overall test into timeout.  Maybe.)

**Comment by ianlancetaylor** [comment]
If I set `GOGC=off` the test consistently completes.  CC @mknyszek

**Comment by ianlancetaylor** [comment]
I have a patch.
