### ISSUE TITLE
runtime: unexpected return pc for runtime.sigpanic

### ISSUE THREAD

**Issue by josharian** [golang/go#49655]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.18-0440fb8334 Wed Nov 17 21:26:25 2021 +0000 darwin/arm64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN="/Users/josh/bin"
GOCACHE="/Users/josh/Library/Caches/go-build"
GOENV="/Users/josh/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/josh/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/josh"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/josh/go/tip"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/josh/go/tip/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="devel go1.18-0440fb8334 Wed Nov 17 21:26:25 2021 +0000"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/josh/go/tip/src/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3q/psxh45px453fyswltj1s69940000gn/T/go-build2080494718=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

* Clone https://github.com/tailscale/tailscale/
* `git checkout 5b5f032c9a99ecedd34eacbe7365d5cb1a783656`
* `go test -c -race ./wgengine/magicsock`
* `stress ./magicsock.test -test.run=NONE`

### What did you expect to see?

No failures.

### What did you see instead?

Lots of failures. Reproduces rapidly. Sample:

```
SIGABRT: abort
PC=0x1c354d9b8 m=0 sigcode=0

goroutine 0 [idle]:
runtime: unknown pc 0x1c354d9b8
stack: frame={sp:0x16ef23040, fp:0x0} stack=[0x16eea43a8,0x16ef23420)
0x000000016ef22f40:  0x0000000100f23d24 <runtime.persistentalloc.func1+0x0000000000000034>  0x0000000102894000 
0x000000016ef22f50:  0x3031000000081945  0x0030383538303832 
0x000000016ef22f60:  0x0000000000000009  0x0000000000000000 
0x000000016ef22f70:  0x000000000000000a  0x0000000000000000 
0x000000016ef22f80:  0x0000000000000070  0x0000000000000000 
0x000000016ef22f90:  0x0000000000000000  0x00000001c33bdecd 
0x000000016ef22fa0:  0x0000000102794000  0x0000000000000000 
0x000000016ef22fb0:  0x000000016ef23020  0x45408001c3598dac 
0x000000016ef22fc0:  0x000000016ef23150  0x000000016ef23058 
0x000000016ef22fd0:  0x0000000000000009  0x0000000102808580 
0x000000016ef22fe0:  0x00000001027fc22a  0x0000000000000000 
0x000000016ef22ff0:  0x0000000000000000  0x0000000102808580 
0x000000016ef23000:  0x00000001027fc22a  0x0000000102794000 
0x000000016ef23010:  0x0000000000000043  0x00000001c33bded8 
0x000000016ef23020:  0x000000016ef23040  0x5d568001c3596748 
0x000000016ef23030:  0x0000000000000043  0x000000016ef23050 
0x000000016ef23040: <0x000000016ef23150  0x0000000102790028 
0x000000016ef23050:  0x000000016ef23088  0x0000000102808580 
0x000000016ef23060:  0x000000016ef230a0  0xde340001c34be314 
0x000000016ef23070:  0x0000000000000000  0xffffffff02790000 
0x000000016ef23080:  0x000000016ef23150  0x00000001fffff9df 
0x000000016ef23090:  0x0000000000000000  0x0000000000000043 
0x000000016ef230a0:  0x000000016ef23120  0x13280001c33a3a1c 
0x000000016ef230b0:  0x00000001027fc22a  0x00000000000092bb 
0x000000016ef230c0:  0x0000000102808580  0x0000000000008000 
0x000000016ef230d0:  0x0000000000000009  0x00000000001ff800 
0x000000016ef230e0:  0x0000000000000020  0x0000000000000001 
0x000000016ef230f0:  0x000060000306c000  0x00000000818fb809 
0x000000016ef23100:  0x00000001026ef058  0x000060000306c000 
0x000000016ef23110:  0x0000600003269bc0  0x0000000102808660 
0x000000016ef23120:  0x000000016ef23140  0xaf4c8001c33b8c8c 
0x000000016ef23130:  0x0000000100f66280 <runtime.stackalloc+0x00000000000001b0>  0x000000016ef23150 
runtime: unknown pc 0x1c354d9b8
stack: frame={sp:0x16ef23040, fp:0x0} stack=[0x16eea43a8,0x16ef23420)
0x000000016ef22f40:  0x0000000100f23d24 <runtime.persistentalloc.func1+0x0000000000000034>  0x0000000102894000 
0x000000016ef22f50:  0x3031000000081945  0x0030383538303832 
0x000000016ef22f60:  0x0000000000000009  0x0000000000000000 
0x000000016ef22f70:  0x000000000000000a  0x0000000000000000 
0x000000016ef22f80:  0x0000000000000070  0x0000000000000000 
0x000000016ef22f90:  0x0000000000000000  0x00000001c33bdecd 
0x000000016ef22fa0:  0x0000000102794000  0x0000000000000000 
0x000000016ef22fb0:  0x000000016ef23020  0x45408001c3598dac 
0x000000016ef22fc0:  0x000000016ef23150  0x000000016ef23058 
0x000000016ef22fd0:  0x0000000000000009  0x0000000102808580 
0x000000016ef22fe0:  0x00000001027fc22a  0x0000000000000000 
0x000000016ef22ff0:  0x0000000000000000  0x0000000102808580 
0x000000016ef23000:  0x00000001027fc22a  0x0000000102794000 
0x000000016ef23010:  0x0000000000000043  0x00000001c33bded8 
0x000000016ef23020:  0x000000016ef23040  0x5d568001c3596748 
0x000000016ef23030:  0x0000000000000043  0x000000016ef23050 
0x000000016ef23040: <0x000000016ef23150  0x0000000102790028 
0x000000016ef23050:  0x000000016ef23088  0x0000000102808580 
0x000000016ef23060:  0x000000016ef230a0  0xde340001c34be314 
0x000000016ef23070:  0x0000000000000000  0xffffffff02790000 
0x000000016ef23080:  0x000000016ef23150  0x00000001fffff9df 
0x000000016ef23090:  0x0000000000000000  0x0000000000000043 
0x000000016ef230a0:  0x000000016ef23120  0x13280001c33a3a1c 
0x000000016ef230b0:  0x00000001027fc22a  0x00000000000092bb 
0x000000016ef230c0:  0x0000000102808580  0x0000000000008000 
0x000000016ef230d0:  0x0000000000000009  0x00000000001ff800 
0x000000016ef230e0:  0x0000000000000020  0x0000000000000001 
0x000000016ef230f0:  0x000060000306c000  0x00000000818fb809 
0x000000016ef23100:  0x00000001026ef058  0x000060000306c000 
0x000000016ef23110:  0x0000600003269bc0  0x0000000102808660 
0x000000016ef23120:  0x000000016ef23140  0xaf4c8001c33b8c8c 
0x000000016ef23130:  0x0000000100f66280 <runtime.stackalloc+0x00000000000001b0>  0x000000016ef23150 

goroutine 1 [running, locked to thread]:
runtime.systemstack_switch()
	/Users/josh/go/tip/src/runtime/asm_arm64.s:194 +0x8 fp=0xc0000565d0 sp=0xc0000565c0 pc=0x100f7d5c8
runtime.newproc(0xc000056628?)
	/Users/josh/go/tip/src/runtime/proc.go:4230 +0x4c fp=0xc000056610 sp=0xc0000565d0 pc=0x100f56a5c
runtime.init.6()
	/Users/josh/go/tip/src/runtime/proc.go:294 +0x28 fp=0xc000056630 sp=0xc000056610 pc=0x100f4ddf8
runtime.doInit(0x101a169c0)
	/Users/josh/go/tip/src/runtime/proc.go:6396 +0x138 fp=0xc000056770 sp=0xc000056630 pc=0x100f5bc68
runtime.main()
	/Users/josh/go/tip/src/runtime/proc.go:204 +0x134 fp=0xc0000567d0 sp=0xc000056770 pc=0x100f4db14
runtime.goexit()
	/Users/josh/go/tip/src/runtime/asm_arm64.s:1259 +0x4 fp=0xc0000567d0 sp=0xc0000567d0 pc=0x100f7fd34

r0      0x0
r1      0x0
r2      0x0
r3      0x0
r4      0x0
r5      0x0
r6      0x1
r7      0x102790028
r8      0xdd6bb3b2d3fdb1f4
r9      0xdd6bb3b3d17d3474
r10     0xcccccccccccccccd
r11     0xa
r12     0x0
r13     0x33
r14     0x1a00000
r15     0xc00000303f
r16     0x148
r17     0x21d967530
r18     0x0
r19     0x6
r20     0x102808580
r21     0x103
r22     0x16ef23150
r23     0x102790000
r24     0x0
r25     0x0
r26     0x1027fc22a
r27     0x102808580
r28     0x9
r29     0x16ef23060
lr      0x1c358115c
sp      0x16ef23040
pc      0x1c354d9b8
fault   0x1c354d9b8


ERROR: exit status 2
```

**Comment by cherrymui** [comment]
What version of macOS do you use? If it is macOS 12, could it be #49138 ?

Is it reproducible with older version of Go?

**Comment by josharian** [comment]
Yep, looks like it is #49138. Thanks, @cherrymui.
