### ISSUE TITLE
misc/cgo/testplugin: test failing on macOS 12 (arm64) on the 1.17 release branch

### ISSUE THREAD

**Issue by dmitshur** [golang/go#49926]
On the 1.17 release branch (but not the 1.16 branch nor tip), the macOS 12 (arm64) builder has been failing since it was brought up.

Failures look like:

```
--- FAIL: TestIssue25756pie (1.20s)
    plugin_test.go:274: ./issue25756pie.exe: exit status 2
        panic: plugin.Open("life"): plugin was built with a different version of package sync/atomic
        
        goroutine 1 [running]:
        panic({0x10476ed20, 0x14000012270})
        	/tmp/buildlet/go/src/runtime/panic.go:1147 +0x41c fp=0x14000105ea0 sp=0x14000105dc0 pc=0x10469c74c
[...]
```

From https://build.golang.org/log/8d6c23e736ff876b9ec8c34f4dd3bb6ed497c56e. See https://build.golang.org/?branch=release-branch.go1.17.

This may be a problem with Go, with the builder (it still has a known issue set, #49149), or macOS 12.

CC @golang/release, @mknyszek (in case this is related to #49923).

**Comment by dmitshur** [comment]
Maybe this is a duplicate of #46239.

**Comment by dmitshur** [comment]
This is indeed the same as #46239. That test has a skip that applies to the macOS 11 builder, which explains why it only fails on the macOS 12 one, due to the different name:

```Go
if os.Getenv("GO_BUILDER_NAME") == "darwin-arm64-11_0-toothrot" {
	t.Skip("broken on darwin/arm64 builder in sharded mode; see issue 46239")
}
```

Closing in favor of #46239 which has more information.
