### ISSUE TITLE
affected/package: 

### ISSUE THREAD

**Issue by gus** [golang/go#50177]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18beta1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, assuming the latest version is `gotip`.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/dev/.cache/go-build"
GOENV="/home/dev/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/dev/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/dev/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/dev/sdk/go1.18beta1"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/dev/sdk/go1.18beta1/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18beta1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/workspace/dev/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build929647144=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you see instead?

<pre>
# command-line-arguments
./issue.go:22:14: internal compiler error: found illegal assignment FUNC-func(int) error -> main.Fn[int]; 

Please file a bug report including a short program that triggers the error.
https://golang.org/issue/new
</pre>

**Comment by ianlancetaylor** [comment]
Thanks.  Can you please include a short program that triggers the error?

**Comment by gus** [comment]
> Thanks. Can you please include a short program that triggers the error?

Sorry, accidentally hit `tab+enter` on accident. Issue updated with more details.

**Comment by ianlancetaylor** [comment]
CC @danscales @randall77 

(Compilation succeeds with `GOEXPERIMENT=unified`)

```
foo.go:22:14: internal compiler error: found illegal assignment FUNC-func(int) error -> main.Fn[int]; 

goroutine 1 [running]:
runtime/debug.Stack()
	/home/iant/go/src/runtime/debug/stack.go:24 +0x65
cmd/compile/internal/base.FatalfAt({0x0?, 0x0?}, {0xd36a84, 0x27}, {0xc000436c30, 0x3, 0x3})
	/home/iant/go/src/cmd/compile/internal/base/print.go:227 +0x1ca
cmd/compile/internal/base.Fatalf(...)
	/home/iant/go/src/cmd/compile/internal/base/print.go:196
cmd/compile/internal/noder.assignconvfn({0xe91250, 0xc0004277c0}, 0xc000439ab0)
	/home/iant/go/src/cmd/compile/internal/noder/transform.go:426 +0x1b2
cmd/compile/internal/noder.transformCompLit(0xc00013b300)
	/home/iant/go/src/cmd/compile/internal/noder/transform.go:980 +0x9f1
cmd/compile/internal/noder.(*irgen).compLit(0xc000152240, {0xe8d0b0, 0xc00013af80}, 0xc000407c70)
	/home/iant/go/src/cmd/compile/internal/noder/expr.go:372 +0x276
cmd/compile/internal/noder.(*irgen).expr0(0xc000152240, {0xe8d0b0, 0xc00013af80}, {0xe8e008?, 0xc000407c70?})
	/home/iant/go/src/cmd/compile/internal/noder/expr.go:107 +0x585
cmd/compile/internal/noder.(*irgen).expr(0xc000152240, {0xe8e008?, 0xc000407c70?})
	/home/iant/go/src/cmd/compile/internal/noder/expr.go:81 +0x5e8
cmd/compile/internal/noder.(*irgen).exprs(0xc000437360?, {0xc000437350, 0x1, 0xc00006cc30?})
	/home/iant/go/src/cmd/compile/internal/noder/expr.go:329 +0x8e
cmd/compile/internal/noder.(*irgen).exprList(0x0?, {0xe8e008?, 0xc000407c70?})
	/home/iant/go/src/cmd/compile/internal/noder/expr.go:312 +0x85
cmd/compile/internal/noder.(*irgen).stmt(0xc000152240, {0xe8de88?, 0xc000035c40?})
	/home/iant/go/src/cmd/compile/internal/noder/stmt.go:79 +0x418
cmd/compile/internal/noder.(*irgen).stmts(0xc000438a80?, {0xc000035cc0?, 0x3, 0xc00006d4a0?})
	/home/iant/go/src/cmd/compile/internal/noder/stmt.go:19 +0xaf
cmd/compile/internal/noder.(*irgen).funcBody(0xc000152240, 0xc000413080, 0xb4d7a0?, 0xc000035ac0, 0xc000035b00)
	/home/iant/go/src/cmd/compile/internal/noder/func.go:45 +0x25f
cmd/compile/internal/noder.(*irgen).funcDecl.func1()
	/home/iant/go/src/cmd/compile/internal/noder/decl.go:145 +0xf5
cmd/compile/internal/noder.(*irgen).generate(0xc000152240, {0xc00000e430, 0x1, 0x203000?})
	/home/iant/go/src/cmd/compile/internal/noder/irgen.go:280 +0x227
cmd/compile/internal/noder.check2({0xc00000e430, 0x1, 0x1})
	/home/iant/go/src/cmd/compile/internal/noder/irgen.go:92 +0x16d
cmd/compile/internal/noder.LoadPackage({0xc00001e1f0, 0x1, 0x0?})
	/home/iant/go/src/cmd/compile/internal/noder/noder.go:90 +0x335
cmd/compile/internal/gc.Main(0xd4a7e8)
	/home/iant/go/src/cmd/compile/internal/gc/main.go:191 +0xb13
main.main()
	/home/iant/go/src/cmd/compile/main.go:55 +0xdd
```

**Comment by randall77** [comment]
I don't think this will work currently. We don't allow local type declarations (or functions for that matter) with generic parameters.
Or at least, we shouldn't. Definitely needs a better error message.

Somewhat related to #47631 except it's a generic type declaration in a non-generic function, instead of a non-generic type declaration in a generic function.

**Comment by gus** [comment]
Thanks, @randall77 . More than happy to be told not to do this as I didn't really like the way the test was looking anyway; but `gopls` wasn't complaining, so I forged ahead. I will add that if the signature for `fn` in both `X` types is the same, then the code compiles (and works if you add a `main` function to the example).

**Comment by randall77** [comment]
@gri @ianlancetaylor @findleyr @danscales 

I guess we need to decide whether we support local declarations of generic types in non-generic functions. Maybe we could? I'm not sure if this doesn't work because we never tried it, or because it's not supposed to work, or because it should work but doesn't. Opinions welcome.

I have a CL ready to officially make this an error like for #47631, but that's only if we decide it is the right thing to do.

**Comment by danscales** [comment]
It looks like we are confusing the two local named types X incorrectly.  If you rename the second local type to Y, things work fine.  We don't have the same confusion for non-generic local types, so must be some generic-only state.  I will take a further look.

However, I would say, for this release, it is probably less confusing to the user and reduces the number of possible unusual cases if we disallow local generic type declarations in non-generic functions.

**Comment by ianlancetaylor** [comment]
I think that eventually we should support local declarations of generic types in non-generic functions, but I think it's fine if we don't support that in 1.18.

**Comment by danscales** [comment]
The problem is that instantiations of local types need to be popped from the symbol table when leaving the scope of the local type, else they might get used for an instantiation of a later same-name local type.  I have the relatively simple fix above, but still need to think about other possible issues, since local generic types was not a focus for the code and we have no tests.
