### ISSUE TITLE
The DLL that calls cgo reports an error

### ISSUE THREAD

**Issue by xiao-cao-x** [golang/go#50304]
I wrote a DLL in C++, this DLL exported a function, the function is LoadLibrary to load a CGO DLL and call the method.
Then I used Go to load this C++ DLL to call the function, and an error was reported.

This is the main program that loads the C++ DLL
```go
package main

import (
	"syscall"
	"unsafe"
)

var dll = syscall.NewLazyDLL("TestDLL.dll")

func init() {
	err := dll.Load()
	if err != nil {
		log.Fatalln(err)
	}
}

func int32Ptr(i int32) uintptr {
	return uintptr(i)
}

func ptrBool(p uintptr) bool {
	return p == 1
}

func AddPlugin(dllPath string) bool {
	proc := dll.NewProc("AddPlugin")
	ret, _, _ := proc.Call(stringPtr(dllPath))

	return ptrBool(ret)
}

func main() {
	AddPlugin("plugin.dll")
}
```

This is the DLL of CGO: plugin.dll
```go
package main

import "C"
import "fmt"

//export TestCallback
func TestCallback(msg int32) {
	fmt.Println("TestCallback:", msg)
}

func main() {
	fmt.Println("PluginMain")
}


```

This is C++DLL

```cpp
extern "C" {

	typedef void (*Callback)(int msg);
	bool AddPlugin(const char* dllPath) {
		printf("dllPath:%s\n", dllPath);
		HMODULE hDll = LoadLibraryA(dllPath);
		if (nullptr != hDll) {
			Callback callback = (Callback)GetProcAddress(hDll, "TestCallback");
			callback(123);

		}

		return true;
	}
}
```
```
LIBRARY
	EXPORTS
		AddPlugin
```
```console
fatal error: bad sweepgen in refill

goroutine 1 [running, locked to thread]:
runtime.throw({0x53a32cdd, 0x15b25a38f00})
        V:/Dev/Tools/SDK/Go/src/runtime/panic.go:1198 +0x76 fp=0xc000117
860 sp=0xc000117830 pc=0x539a3716
runtime.(*mcache).refill(0x15b259d0108, 0x4c)
        V:/Dev/Tools/SDK/Go/src/runtime/mcache.go:156 +0x24e fp=0xc00011
78b0 sp=0xc000117860 pc=0x5398452e
runtime.(*mcache).nextFree(0x15b259d0108, 0x4c)
        V:/Dev/Tools/SDK/Go/src/runtime/malloc.go:880 +0x85 fp=0xc000117
8f8 sp=0xc0001178b0 pc=0x5397bb65
runtime.mallocgc(0x800, 0x53a253a0, 0x1)
        V:/Dev/Tools/SDK/Go/src/runtime/malloc.go:1071 +0x4e8 fp=0xc0001
17978 sp=0xc0001178f8 pc=0x5397c1e8
runtime.makeslice(0x0, 0x0, 0x0)
        V:/Dev/Tools/SDK/Go/src/runtime/slice.go:98 +0x52 fp=0xc0001179a
0 sp=0xc000117978 pc=0x539b5172
sync.(*Pool).pinSlow(0x53a102e0)
        V:/Dev/Tools/SDK/Go/src/sync/pool.go:227 +0x185 fp=0xc000117a38 
sp=0xc0001179a0 pc=0x539d4525
sync.(*Pool).pin(0x53a102e0)
        V:/Dev/Tools/SDK/Go/src/sync/pool.go:206 +0x4e fp=0xc000117a50 s
p=0xc000117a38 pc=0x539d436e
sync.(*Pool).Get(0x53a102e0)
        V:/Dev/Tools/SDK/Go/src/sync/pool.go:128 +0x25 fp=0xc000117a88 s
p=0xc000117a50 pc=0x539d40a5
fmt.newPrinter()
        V:/Dev/Tools/SDK/Go/src/fmt/print.go:137 +0x25 fp=0xc000117ab0 s
p=0xc000117a88 pc=0x539f7565
fmt.Fprintln({0x53a50660, 0x0}, {0xc000117b28, 0x2, 0x2})
        V:/Dev/Tools/SDK/Go/src/fmt/print.go:263 +0x36 fp=0xc000117b00 s
p=0xc000117ab0 pc=0x539f7836
fmt.Println(...)
        V:/Dev/Tools/SDK/Go/src/fmt/print.go:274
main.TestCallback(...)
        D:/Golang/src/dll_loader/plugin/plugin.go:8
_cgoexp_14ef28ecb6d2_TestCallback(0x15b259d9218)
        _cgo_gotypes.go:37 +0x71 fp=0xc000117b58 sp=0xc000117b00 pc=0x539fcc51  
runtime.cgocallbackg1(0x539fcbe0, 0xf45205, 0x0)
        V:/Dev/Tools/SDK/Go/src/runtime/cgocall.go:306 +0x29a fp=0xc0001
17c28 sp=0xc000117b58 pc=0x53973c9a
runtime.cgocallbackg(0xc00004a000, 0x300000002, 0xc00004a000)
        V:/Dev/Tools/SDK/Go/src/runtime/cgocall.go:232 +0x106 fp=0xc0001
17cc0 sp=0xc000117c28 pc=0x53973926
runtime.cgocallbackg(0x539fcbe0, 0x434dff8fc, 0x0)
        <autogenerated>:1 +0x36 fp=0xc000117ce8 sp=0xc000117cc0 pc=0x539cef56   
runtime: unexpected return pc for runtime.cgocallback called from 0xf8b0c0      
stack: frame={sp:0xc000117ce8, fp:0xc000117d10} stack=[0xc000110000,0xc000118000
)
0x000000c000117be8:  0x000000c000117c18  0x00000000539c8705 <runtime.exitsyscall
+0x0000000000000105>
0x000000c000117bf8:  0x000000c00004a000  0x000000c000117bd8
0x000000c000117c08:  0x0000000000000000  0x0000000053a38c88
0x000000c000117c18:  0x000000c000117cb0  0x0000000053973926 <runtime.cgocallback
g+0x0000000000000106>
0x000000c000117c28:  0x00000000539fcbe0 <_cgoexp_14ef28ecb6d2_TestCallback+0x000
0000000000000>  0x0000000000f45205
0x000000c000117c38:  0x0000000000000000  0x0000000000f3322a
0x000000c000117c48:  0x0000000000000000  0x00007ff96ca01080
0x000000c000117c58:  0x0000000000000001  0x000000c000117d98
0x000000c000117c68:  0x00007ff96ca01080  0x0000000000000000
0x000000c000117c78:  0x0000000000000000  0x000000c000117d18
0x000000c000117c88:  0x000000c00004a000  0x0000000001080a60
0x000000c000117c98:  0x0000000000030000  0x00000000539fcbe0 <_cgoexp_14ef28ecb6d
2_TestCallback+0x0000000000000000>
0x000000c000117ca8:  0x0000000434dff8fc  0x000000c000117cd8
0x000000c000117cb8:  0x00000000539cef56 <runtime.cgocallbackg+0x0000000000000036
>  0x000000c00004a000
0x000000c000117cc8:  0x0000000300000002  0x000000c00004a000
0x000000c000117cd8:  0x0000000434dff7b8  0x00000000539ccd77 <runtime.cgocallback
+0x00000000000000d7>
0x000000c000117ce8: <0x00000000539fcbe0 <_cgoexp_14ef28ecb6d2_TestCallback+0x000
0000000000000>  0x0000000434dff8fc
0x000000c000117cf8:  0x0000000000000000  0x000000c000117d18
0x000000c000117d08: !0x0000000000f8b0c0 >0x0000000000f3328c
0x000000c000117d18:  0x0000000000f8eca0  0x0000000001080d40
0x000000c000117d28:  0x0000015b259dbb88  0x0000000000000010
0x000000c000117d38:  0x0000000001080a60  0x000000c000117d78
0x000000c000117d48:  0x0000000000f89b54  0x0000000000f8eca0
0x000000c000117d58:  0x0000000001080d40  0x0100000000000000
0x000000c000117d68:  0x0000000001080a60  0x0000000000fe7340
0x000000c000117d78:  0x000000c000117dc8  0x0000000000f8fb4b
0x000000c000117d88:  0x00007ff96ca01080  0x0000000000000001
0x000000c000117d98:  0x000000c00000a330  0x0000000000000000
0x000000c000117da8:  0x0000000000000000  0x0000000000000000
0x000000c000117db8:  0x0000000000000000  0x0000000000000000
0x000000c000117dc8:  0x000000c000117eb8  0x0000000000fa99c6
0x000000c000117dd8:  0x00007ff96ca01080  0x0000000000f3bd94
0x000000c000117de8:  0x0000000000000009  0x000000c00010e480 
0x000000c000117df8:  0x000000c000051e38  0x0000000000ffe6d0
0x000000c000117e08:  0x0101005b25a38724
runtime.cgocallback(0xf3328c, 0xf8eca0, 0x1080d40)
        V:/Dev/Tools/SDK/Go/src/runtime/asm_amd64.s:915 +0xd7 fp=0xc0001
17d10 sp=0xc000117ce8 pc=0x539ccd77

goroutine 1 [runnable, locked to thread]:
syscall.(*LazyDLL).NewProc(...)
        V:/Dev/Tools/SDK/Go/src/syscall/dll_windows.go:276
syscall.init()
        V:/Dev/Tools/SDK/Go/src/syscall/zsyscall_windows.go:136 +0x2c52 
```

**Comment by xiao-cao-x** [comment]
plugin.dll can be called separately.
```cpp
#include <Windows.h>
typedef void (*Callback)(int msg);
int main() {
	HMODULE hDll = LoadLibraryA("D:\\Golang\\src\\dll_loader\\plugin\\plugin.dll");
	if (nullptr != hDll) {
		Callback callback = (Callback)GetProcAddress(hDll, "TestCallback");
		callback(123);
	}
	return 0;
}
```

**Comment by xiao-cao-x** [comment]
plugin.dll can be called separately.
```cpp
#include <Windows.h>
typedef void (*Callback)(int msg);
int main() {
	HMODULE hDll = LoadLibraryA("plugin.dll");
	if (nullptr != hDll) {
		Callback callback = (Callback)GetProcAddress(hDll, "TestCallback");
		callback(123);
	}
	return 0;
}
```

**Comment by xiao-cao-x** [comment]
go version: 1.17.1

**Comment by ianlancetaylor** [comment]
If I am understanding correctly, you are using a Go program to open a C++ DLL and the C++ DLL opens a Go DLL.  I'm sorry, this won't work on Windows.  There can only be one copy of the Go runtime in the program image on Windows, but you are trying to have two.

I'm going to close this because I don't know of any way to make this work.  Sorry.

**Comment by xiao-cao-x** [comment]
> If I am understanding correctly, you are using a Go program to open a C++ DLL and the C++ DLL opens a Go DLL. I'm sorry, this won't work on Windows. There can only be one copy of the Go runtime in the program image on Windows, but you are trying to have two.
> 
> I'm going to close this because I don't know of any way to make this work. Sorry.

Can I open multiple Go DLLs in the same program?

**Comment by ianlancetaylor** [comment]
> Can I open multiple Go DLLs in the same program?

My guess is that that would not work on Windows, but I don't actually know for sure.
