### ISSUE TITLE
cmd/compile: compiler error: Dictionary should have already been generated

### ISSUE THREAD

**Issue by csgura** [golang/go#50561]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.18-3d3f5d91 Wed Jan 12 01:49:33 2022 +0000 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

The Gotip Playground

### What did you do?
https://gotipplay.golang.org/p/CNITc5Yr7c1

I ran `gotip build`
( `gotip run main.go` does not generate the error. ) 

### What did you expect to see?
No Error

### What did you see instead?
```
# goerror
<autogenerated>:1: internal compiler error: Dictionary should have already been generated: goerror/fp..dict.Try[*goerror/diameter.ByteBuffer].IsSuccess

goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
cmd/compile/internal/base.FatalfAt({0x2ab00?, 0xc0?}, {0xd3f7f7, 0x34}, {0xc0000be750, 0x2, 0x2})
	/usr/local/go/src/cmd/compile/internal/base/print.go:227 +0x1ca
cmd/compile/internal/base.Fatalf(...)
	/usr/local/go/src/cmd/compile/internal/base/print.go:196
cmd/compile/internal/reflectdata.getDictionary(0xc0004a6370, {0xc0000acb80?, 0x1, 0x1})
	/usr/local/go/src/cmd/compile/internal/reflectdata/reflect.go:2072 +0x2dd
cmd/compile/internal/reflectdata.methodWrapper(0xc0000db8f0, 0xc0004a63c0, 0x95?)
	/usr/local/go/src/cmd/compile/internal/reflectdata/reflect.go:1910 +0xefd
cmd/compile/internal/reflectdata.methods(0xc0000db8f0)
	/usr/local/go/src/cmd/compile/internal/reflectdata/reflect.go:351 +0x3c5
cmd/compile/internal/reflectdata.uncommonSize(...)
	/usr/local/go/src/cmd/compile/internal/reflectdata/reflect.go:79
cmd/compile/internal/reflectdata.dcommontype(0xc00002c4f0?, 0xc0000db8f0)
	/usr/local/go/src/cmd/compile/internal/reflectdata/reflect.go:725 +0x1cc
cmd/compile/internal/reflectdata.writeType(0xc0004a4ee0?)
	/usr/local/go/src/cmd/compile/internal/reflectdata/reflect.go:1150 +0x307
cmd/compile/internal/reflectdata.dcommontype(0x7f0bcc9e725b?, 0xc0004a4ee0)
	/usr/local/go/src/cmd/compile/internal/reflectdata/reflect.go:698 +0xbc
cmd/compile/internal/reflectdata.writeType(0x138ff00?)
	/usr/local/go/src/cmd/compile/internal/reflectdata/reflect.go:1175 +0x10aa
cmd/compile/internal/reflectdata.writeType(0xc0003fa540?)
	/usr/local/go/src/cmd/compile/internal/reflectdata/reflect.go:1021 +0x13cd
cmd/compile/internal/reflectdata.writeType(0xc0003e0930?)
	/usr/local/go/src/cmd/compile/internal/reflectdata/reflect.go:1057 +0xd54
cmd/compile/internal/reflectdata.writeType(0xc0004b6a10?)
	/usr/local/go/src/cmd/compile/internal/reflectdata/reflect.go:990 +0x3ca
cmd/compile/internal/reflectdata.writeType(0xc00039d500?)
	/usr/local/go/src/cmd/compile/internal/reflectdata/reflect.go:1159 +0x100a
cmd/compile/internal/reflectdata.WriteRuntimeTypes()
	/usr/local/go/src/cmd/compile/internal/reflectdata/reflect.go:1266 +0x3d8
cmd/compile/internal/gc.dumpdata()
	/usr/local/go/src/cmd/compile/internal/gc/obj.go:118 +0x6e
cmd/compile/internal/gc.Main(0xd4bd20)
	/usr/local/go/src/cmd/compile/internal/gc/main.go:328 +0x11ab
main.main()
	/usr/local/go/src/cmd/compile/main.go:55 +0xdd
```

**Comment by ALTree** [comment]
Another issue with a similar error: #48185.

cc @danscales
