### ISSUE TITLE
go/fix: timeout in TestRewrite

### ISSUE THREAD

**Issue by bcmills** [golang/go#50581]
```
goroutine 30 [syscall]:
syscall.Syscall6(0x4286, 0x8493abc, 0x0, 0x84ba4b0, 0x0, 0x0, 0x0)
	/tmp/workdir/go/src/syscall/asm_unix_386.s:43 +0x5 fp=0x8493a68 sp=0x8493a64 pc=0x80afb25
syscall.wait4(0x4286, 0x8493abc, 0x0, 0x84ba4b0)
	/tmp/workdir/go/src/syscall/zsyscall_netbsd_386.go:34 +0x5b fp=0x8493aa0 sp=0x8493a68 pc=0x80ae63b
syscall.Wait4(0x4286, 0x8493ae0, 0x0, 0x84ba4b0)
	/tmp/workdir/go/src/syscall/syscall_bsd.go:144 +0x3b fp=0x8493ac4 sp=0x8493aa0 pc=0x80ae3fb
os.(*Process).wait(0x84b49f0)
	/tmp/workdir/go/src/os/exec_unix.go:43 +0x82 fp=0x8493af8 sp=0x8493ac4 pc=0x80c45a2
os.(*Process).Wait(...)
	/tmp/workdir/go/src/os/exec.go:132
os/exec.(*Cmd).Wait(0x84c6580)
	/tmp/workdir/go/src/os/exec/exec.go:507 +0x4d fp=0x8493b3c sp=0x8493af8 pc=0x812cbfd
os/exec.(*Cmd).Run(0x84c6580)
	/tmp/workdir/go/src/os/exec/exec.go:341 +0x43 fp=0x8493b4c sp=0x8493b3c pc=0x812bfe3
cmd/fix.typecheck.func1(0x84e2080, 0x8493dc4)
	/tmp/workdir/go/src/cmd/fix/typecheck.go:174 +0x38c fp=0x8493c78 sp=0x8493b4c pc=0x8176bcc
cmd/fix.typecheck(0x8493dc4, 0x84e2080)
	/tmp/workdir/go/src/cmd/fix/typecheck.go:207 +0x13b fp=0x8493d6c sp=0x8493c78 pc=0x8175d7b
cmd/fix.typefix(0x84e2080, 0x81bc910)
	/tmp/workdir/go/src/cmd/fix/cftype.go:43 +0xa1 fp=0x8493e9c sp=0x8493d6c pc=0x816f7a1
cmd/fix.eglfixDisp(0x84e2080)
	/tmp/workdir/go/src/cmd/fix/egltype.go:30 +0x25 fp=0x8493eac sp=0x8493e9c pc=0x8170945
cmd/fix.parseFixPrint(0x851f860, 0x81bc914, {0x84b0c78, 0x13}, {0x84e40c0, 0x3d}, 0x1)
	/tmp/workdir/go/src/cmd/fix/main_test.go:66 +0x339 fp=0x8493f38 sp=0x8493eac pc=0x817d129
cmd/fix.TestRewrite.func1(0x851f860)
	/tmp/workdir/go/src/cmd/fix/main_test.go:122 +0x2e4 fp=0x8493f9c sp=0x8493f38 pc=0x817d704
testing.tRunner(0x851f860, 0x840c678)
	/tmp/workdir/go/src/testing/testing.go:1440 +0x10d fp=0x8493fe4 sp=0x8493f9c pc=0x80ff98d
testing.(*T).Run.func1()
	/tmp/workdir/go/src/testing/testing.go:1487 +0x28 fp=0x8493ff0 sp=0x8493fe4 pc=0x8100768
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_386.s:1311 +0x1 fp=0x8493ff4 sp=0x8493ff0 pc=0x80a72b1
created by testing.(*T).Run
	/tmp/workdir/go/src/testing/testing.go:1487 +0x36e
```

`greplogs --dashboard -md -l -e '(?ms)panic: test timed out.*^cmd/fix\.TestRewrite'`

[2022-01-12T16:50:38-83bfdb6/netbsd-386-9_0-n2](https://build.golang.org/log/4b89c1c3924622b542b1d02328b7223ede23227d)
[2021-10-22T00:57:18-9ff91b9/netbsd-arm-bsiegert](https://build.golang.org/log/73a84fec9a58f4da36103a74a2232d630b7f25d9)
[2021-04-08T02:17:20-a8e5553/netbsd-386-9_0](https://build.golang.org/log/d573accc40f86748b9b36928eb64f6c2ff3743c9)
[2020-10-26T17:26:23-a5088e7/freebsd-amd64-race](https://build.golang.org/log/2d3ea23e6e04c1bdf851d1309a12536299ba4ae7)

**Comment by bcmills** [comment]
This is another test that would benefit from #50436. It may share a root cause with #50138.

**Comment by bcmills** [comment]
(And the `freebsd` failure from 2020 is plausibly #46272.)
