### ISSUE TITLE
runtime: frequent TestSegv failures on linux-mips64le-mengzhuo

### ISSUE THREAD

**Issue by bcmills** [golang/go#50605]
(Pulled out from #49182; CC @prattmic @cherrymui.)

`runtime.TestSegv` is still failing periodically on the `linux-mips64le-mengzhuo` builder (CC @mengzhuo).

A skip was added on `386` for #50504, but that skip does not apply to `mips64le`. It also isn't obvious to me why this doesn't show up on the other MIPS builders (especially `linux-mips64le-rtrk`).

```
--- FAIL: TestSegv (0.00s)
    --- FAIL: TestSegv/SegvInCgo (0.01s)
        testenv.go:361: [/tmp/workdir-host-linux-mipsle-mengzhuo/tmp/go-build3370841287/testprogcgo.exe SegvInCgo] exit status: exit status 2
        crash_cgo_test.go:616: SIGSEGV: segmentation violation
            PC=0xfff089cc6c m=3 sigcode=0
            
            goroutine 0 [idle]:
            runtime: unknown pc 0xfff089cc6c
            stack: frame={sp:0xffc905e518, fp:0x0} stack=[0xffc885ecc0,0xffc905e8c0)
            0x000000ffc905e418:  0x000000ffbb7fb1d0  0x000000fff08b8000 
            0x000000ffc905e428:  0x000000fff08c0030  0x000000fff0892d04 
            0x000000ffc905e438:  0x0000000000000004  0x000000fff08b8000 
            0x000000ffc905e448:  0x000000ffbb7fb290  0x000000fff09115d8 
            0x000000ffc905e458:  0x0000000000000007  0x0000000000804000 
            0x000000ffc905e468:  0x000000ffbaff8000  0x000000fff08b8000 
            0x000000ffc905e478:  0x000000013d1283b0  0x0000000120154530 
            0x000000ffc905e488:  0x000000ffc905e6f8  0x0000000000000000 
            0x000000ffc905e498:  0x0000000000000400  0x010000ffc9b18700 
            0x000000ffc905e4a8:  0x0000300000000000  0x000000ffc9d13fff 
            0x000000ffc905e4b8:  0x0000000000000400  0x000000012001fd50 <runtime.(*mcentral).grow+0x0000000000000180> 
            0x000000ffc905e4c8:  0x000000ffc9b18600  0x0000000000000100 
            0x000000ffc905e4d8:  0x000000ffc9d13fff  0x98ba71403ce9ad00 
            0x000000ffc905e4e8:  0x000000ffc9b18700  0x00000000000f4240 
            0x000000ffc905e4f8:  0x000000013d1283b0  0x0000000001406f40 
            0x000000ffc905e508:  0x000000ffc905e6f8  0x000000013d1283b0 
            0x000000ffc905e518: <0x0000000120154530  0x000000ffc905e6b8 
            0x000000ffc905e528:  0x000000000000000b  0x000000012028bf90 
            0x000000ffc905e538:  0x00000000000f4240  0x000000012015440c 
            0x000000ffc905e548:  0x000000ffc9b18600  0x0000300000000000 
            0x000000ffc905e558:  0x000000ffc9d13fff  0x000000ffc905e6b8 
            0x000000ffc905e568:  0x000000013d1283b0  0x0000000000000030 
            0x000000ffc905e578:  0x0000000000000000  0x0000000000000000 
            0x000000ffc905e588:  0x000000c0000821a0  0x000000ffc905e518 
            0x000000ffc905e598:  0x0000000120260000  0x98ba71403ce9ad00 
            0x000000ffc905e5a8:  0x000000012028bf90  0x0000000120154664 
            0x000000ffc905e5b8:  0x0000000000000000  0x0000000000000000 
            0x000000ffc905e5c8:  0x0000000000000001  0x000000012001ece0 <runtime.(*mcache).refill+0x0000000000000210> 
            0x000000ffc905e5d8:  0x0000000000000000  0x000000012001ed28 <runtime.(*mcache).refill+0x0000000000000258> 
            0x000000ffc905e5e8:  0x00000001202ad4c8  0x00000001200122bc <runtime.(*mcache).nextFree+0x00000000000000b4> 
            0x000000ffc905e5f8:  0x00000001200122d4 <runtime.(*mcache).nextFree+0x00000000000000cc>  0x0000000000002000 
            0x000000ffc905e608:  0x0000000000000178  0x0000000000000020 
            runtime: unknown pc 0xfff089cc6c
            stack: frame={sp:0xffc905e518, fp:0x0} stack=[0xffc885ecc0,0xffc905e8c0)
            0x000000ffc905e418:  0x000000ffbb7fb1d0  0x000000fff08b8000 
            0x000000ffc905e428:  0x000000fff08c0030  0x000000fff0892d04 
            0x000000ffc905e438:  0x0000000000000004  0x000000fff08b8000 
            0x000000ffc905e448:  0x000000ffbb7fb290  0x000000fff09115d8 
            0x000000ffc905e458:  0x0000000000000007  0x0000000000804000 
            0x000000ffc905e468:  0x000000ffbaff8000  0x000000fff08b8000 
            0x000000ffc905e478:  0x000000013d1283b0  0x0000000120154530 
            0x000000ffc905e488:  0x000000ffc905e6f8  0x0000000000000000 
            0x000000ffc905e498:  0x0000000000000400  0x010000ffc9b18700 
            0x000000ffc905e4a8:  0x0000300000000000  0x000000ffc9d13fff 
            0x000000ffc905e4b8:  0x0000000000000400  0x000000012001fd50 <runtime.(*mcentral).grow+0x0000000000000180> 
            0x000000ffc905e4c8:  0x000000ffc9b18600  0x0000000000000100 
            0x000000ffc905e4d8:  0x000000ffc9d13fff  0x98ba71403ce9ad00 
            0x000000ffc905e4e8:  0x000000ffc9b18700  0x00000000000f4240 
            0x000000ffc905e4f8:  0x000000013d1283b0  0x0000000001406f40 
            0x000000ffc905e508:  0x000000ffc905e6f8  0x000000013d1283b0 
            0x000000ffc905e518: <0x0000000120154530  0x000000ffc905e6b8 
            0x000000ffc905e528:  0x000000000000000b  0x000000012028bf90 
            0x000000ffc905e538:  0x00000000000f4240  0x000000012015440c 
            0x000000ffc905e548:  0x000000ffc9b18600  0x0000300000000000 
            0x000000ffc905e558:  0x000000ffc9d13fff  0x000000ffc905e6b8 
            0x000000ffc905e568:  0x000000013d1283b0  0x0000000000000030 
            0x000000ffc905e578:  0x0000000000000000  0x0000000000000000 
            0x000000ffc905e588:  0x000000c0000821a0  0x000000ffc905e518 
            0x000000ffc905e598:  0x0000000120260000  0x98ba71403ce9ad00 
            0x000000ffc905e5a8:  0x000000012028bf90  0x0000000120154664 
            0x000000ffc905e5b8:  0x0000000000000000  0x0000000000000000 
            0x000000ffc905e5c8:  0x0000000000000001  0x000000012001ece0 <runtime.(*mcache).refill+0x0000000000000210> 
            0x000000ffc905e5d8:  0x0000000000000000  0x000000012001ed28 <runtime.(*mcache).refill+0x0000000000000258> 
            0x000000ffc905e5e8:  0x00000001202ad4c8  0x00000001200122bc <runtime.(*mcache).nextFree+0x00000000000000b4> 
            0x000000ffc905e5f8:  0x00000001200122d4 <runtime.(*mcache).nextFree+0x00000000000000cc>  0x0000000000002000 
            0x000000ffc905e608:  0x0000000000000178  0x0000000000000020 
            
            goroutine 1 [sleep]:
            time.Sleep(0x3b9aca00)
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/time.go:194 +0x1a4
            main.SegvInCgo()
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/testdata/testprogcgo/segv.go:56 +0x118
            main.main()
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/testdata/testprogcgo/main.go:34 +0x200
            
            goroutine 6 [runnable]:
            main._Cfunc_nop()
            	_cgo_gotypes.go:356 +0x54
            main.SegvInCgo.func1()
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/testdata/testprogcgo/segv.go:47 +0x44
            created by main.SegvInCgo
            	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/testdata/testprogcgo/segv.go:44 +0xbc
            
            r0   0x0	r1   0xc00008c000
            r2   0x0	r3   0x1
            r4   0x3	r5   0xffc905e5b8
            r6   0x0	r7   0x0
            r8   0xfff0910a58	r9   0xffbb8028d0
            r10  0xffc9d14000	r11  0x4000000
            r12  0x0	r13  0x38
            r14  0x0	r15  0x0
            r16  0x0	r17  0x13d1283b0
            r18  0x30	r19  0x0
            r20  0x0	r21  0xc0000821a0
            r22  0xffc905e518	r23  0x120260000
            r24  0x15f697930316c9	r25  0xfff089cc20
            r26  0x10	r27  0x0
            r28  0xfff08c0030	r29  0xffc905e518
            r30  0xc000002ea0	r31  0x120154664
            pc   0xfff089cc6c	link 0x120154664
            lo   0x0	hi   0x0
            
        crash_cgo_test.go:640: unexpectedly saw "runtime: " in output
FAIL
FAIL	runtime	41.325s
```

`greplogs --dashboard -md -l -e '(?ms)\Alinux-mips.*FAIL: TestSegv'`

[2022-01-13T23:35:37-e550c30/linux-mips64le-mengzhuo](https://build.golang.org/log/6c43723ca3be6ebae981f01380a3def583675792)
[2021-12-04T04:41:31-cd5f2cf/linux-mips64le-mengzhuo](https://build.golang.org/log/e5ba4aec35956e74cd1f22e784cefee2d5734971)
[2021-11-24T21:11:45-b77f5f9/linux-mips64le-mengzhuo](https://build.golang.org/log/5a0560b2a80c156786c8e79fa45c4d58f17008b7)
[2021-11-17T04:55:12-1d004fa/linux-mips64le-mengzhuo](https://build.golang.org/log/2ba30a59a0d9153badba232475f2fb813c85cbc7)
[2021-11-12T23:07:01-c8d6ee1/linux-mips64le-mengzhuo](https://build.golang.org/log/739256d02145d0f287d96f69e45ed5e767b660e8)
[2021-11-04T14:54:46-00d6d20/linux-mips64le-mengzhuo](https://build.golang.org/log/47c8218fe2b44cb42b70a4b1501bcbaeb9374139)

**Comment by bcmills** [comment]
(If we add a skip for this test, this issue can be moved to the Backlog milestone.)

**Comment by mengzhuo** [comment]
> (If we add a skip for this test, this issue can be moved to the Backlog milestone.)

I'll take a look.

**Comment by bcmills** [comment]
A similar failure also occurred on `linux-amd64-clang` and on `netbsd-arm-bsiegert`, so either there are multiple underlying causes or this failure mode is platform-independent. Consolidating issues on the theory that it's the latter.

**Comment by bcmills** [comment]
Duplicate of #50979
