### ISSUE TITLE
cmd/compile: MOVWreg missing sign-extension following a Copy from a floating-point LoadReg

### ISSUE THREAD

**Issue by bcmills** [golang/go#50671]
```
runtime: out of memory: cannot allocate 28862184423424-byte block (3932160 in use)
fatal error: out of memory

goroutine 6 [running]:
runtime.throw({0x1e98f5, 0xd})
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/panic.go:992 +0x6c fp=0xc0000bb848 sp=0xc0000bb820 pc=0x52c44
runtime.(*mcache).allocLarge(0xfff3af4108, 0x1a4000000960, 0x1)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/mcache.go:215 +0x2dc fp=0xc0000bb890 sp=0xc0000bb848 pc=0x29cf4
runtime.mallocgc(0x1a4000000960, 0x1d6600, 0x1)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/malloc.go:1096 +0x5b4 fp=0xc0000bb910 sp=0xc0000bb890 pc=0x1e324
runtime.makeslice(0x1d6600, 0x11800000064, 0x11800000064)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/slice.go:103 +0x94 fp=0xc0000bb938 sp=0xc0000bb910 pc=0x71014
golang.org/x/image/draw.newDistrib(0x2e6510, 0x64, 0x118)
	/tmp/workdir-host-linux-mipsle-mengzhuo/gopath/src/golang.org/x/image/draw/scale.go:248 +0xc4 fp=0xc0000bba28 sp=0xc0000bb938 pc=0x1981a4
golang.org/x/image/draw.(*Kernel).newScaler(0x2e6510, 0x64, 0x64, 0x118, 0x168, 0x0)
	/tmp/workdir-host-linux-mipsle-mengzhuo/gopath/src/golang.org/x/image/draw/scale.go:142 +0x50 fp=0xc0000bbad8 sp=0xc0000bba28 pc=0x197d20
golang.org/x/image/draw.(*Kernel).Scale(0x2e6510, {0x21f080, 0xc00006a940}, {{0x0, 0x0}, {0x64, 0x64}}, {0x21ecb0, 0xc0000a2080}, {{0x0, ...}, ...}, ...)
	/tmp/workdir-host-linux-mipsle-mengzhuo/gopath/src/golang.org/x/image/draw/scale.go:126 +0x80 fp=0xc0000bbb58 sp=0xc0000bbad8 pc=0x197bb0
golang.org/x/image/draw.testInterp(0xc000084680, 0x64, 0x64, {0x1e789d, 0x4}, {0x1e9499, 0xc}, {0x1e973b, 0xd})
	/tmp/workdir-host-linux-mipsle-mengzhuo/gopath/src/golang.org/x/image/draw/scale_test.go:83 +0xa50 fp=0xc0000bbf18 sp=0xc0000bbb58 pc=0x19a578
golang.org/x/image/draw.TestScaleDown(0xc000084680)
	/tmp/workdir-host-linux-mipsle-mengzhuo/gopath/src/golang.org/x/image/draw/scale_test.go:119 +0x90 fp=0xc0000bbf68 sp=0xc0000bbf18 pc=0x19ab18
testing.tRunner(0xc000084680, 0x1f3b60)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/testing/testing.go:1440 +0x13c fp=0xc0000bbfc0 sp=0xc0000bbf68 pc=0xfbed4
testing.(*T).Run.func1()
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/testing/testing.go:1487 +0x68 fp=0xc0000bbfd8 sp=0xc0000bbfc0 pc=0xfd0c8
runtime.goexit()
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/asm_mips64x.s:617 +0x4 fp=0xc0000bbfd8 sp=0xc0000bbfd8 pc=0x90074
created by testing.(*T).Run
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/testing/testing.go:1487 +0x494

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0000844e0, {0x1e97fe, 0xd}, 0x1f3b60)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/testing/testing.go:1488 +0x4b4
testing.runTests.func1(0xc0000844e0)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/testing/testing.go:1840 +0x9c
testing.tRunner(0xc0000844e0, 0xc000043cf8)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/testing/testing.go:1440 +0x13c
testing.runTests(0xc00000c078, {0x2eb340, 0xe, 0xe}, {0xc071da63e247fe9a, 0x8bb2d7b1d6, 0x2f4380})
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/testing/testing.go:1838 +0x520
testing.(*M).Run(0xc00007a140)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/testing/testing.go:1720 +0x730
main.main()
	_testmain.go:187 +0x24c
FAIL	golang.org/x/image/draw	0.066s
```

`greplogs --dashboard -md -l -e '(?ms)\Alinux-mips64le-mengzhuo.*runtime: out of memory'`

[2022-01-18T14:56:19-6944b10-5b3ebc8/linux-mips64le-mengzhuo](https://build.golang.org/log/54a49c40d0fc2555d10bd0fbd064a658d6d23937)

This failure looks like memory corruption to me, because the failing allocation is for a “28862184423424-byte block” (26.2 <strong>TiB</strong>). It's not obvious to me whether the corruption is due to a bug in `x/image/draw` itself, or in the compiler, runtime, and/or platform.

(CC @mengzhuo)

**Comment by cherrymui** [comment]
```
runtime.makeslice(0x1d6600, 0x11800000064, 0x11800000064)
	/tmp/workdir-host-linux-mipsle-mengzhuo/go/src/runtime/slice.go:103 +0x94 fp=0xc0000bb938 sp=0xc0000bb910 pc=0x71014
```

That argument is enormously large. It seems it should be 0x64. Maybe it is a compiler bug.

**Comment by cherrymui** [comment]
```
v9 (233) = Arg <int32> {dw} : dw[int32] (dw[int32])
...
v174 (234) = LoadReg <int32> v9 : F2
...
v321 (248) = Copy <int32> v174 : R1
v27 (+248) = MOVWreg <int> v321 : R1 (sources.len[int], sources.cap[int])
...
v234 (+248) = MOVVstore <mem> [16] v2 v27 v233
v180 (+248) = MOVVstore <mem> [24] v2 v27 v234
v30 (248) = CALLstatic <mem> {AuxCall{runtime.makeslice}} [32] v180
```
It is supposed to call `makeslice` with len/cap being `dw` with proper extension. The `MOWWreg` is supposed to do that. But it has an optimization that if the input is from a `LoadReg` with proper type, it should be already extended, so it won't extend again. Normally if the LoadReg is loaded into an integer register it is indeed properly extended. But in this case it is loaded into a floating point register (!) (due to another use as floating point) then moved to an integer register, which does not have the proper extension.

**Comment by bcmills** [comment]
@cherrymui, I made a stab at updating the title based on your diagnosis. Does it look accurate? 😅

**Comment by cherrymui** [comment]
Thanks. Yeah, it looks right.
