### ISSUE TITLE
x/tools/internal/lsp: "concurrent map read and map write" in (*snapshot).getFileLocked

### ISSUE THREAD

**Issue by bcmills** [golang/go#50747]
```
fatal error: concurrent map read and map write

goroutine 108 [running]:
runtime.throw(0x9707de, 0x21)
	/tmp/workdir-host-freebsd-arm64-dmgk/go/src/runtime/panic.go:1117 +0x4c fp=0x400050f730 sp=0x400050f700 pc=0x43c4c
runtime.mapaccess2_faststr(0x81b180, 0x400046eb10, 0x400046bc80, 0x79, 0x72, 0x4000000002)
	/tmp/workdir-host-freebsd-arm64-dmgk/go/src/runtime/map_faststr.go:116 +0x410 fp=0x400050f7a0 sp=0x400050f730 pc=0x22c70
golang.org/x/tools/internal/lsp/cache.(*snapshot).getFileLocked(0x400037e200, 0xb83440, 0x400046f0e0, 0x400046f230, 0x81b240, 0x400046e930, 0x40003f3830, 0x40003f3830)
	/tmp/workdir-host-freebsd-arm64-dmgk/gopath/src/golang.org/x/tools/internal/lsp/cache/snapshot.go:1318 +0x54 fp=0x400050f800 sp=0x400050f7a0 pc=0x6ab694
golang.org/x/tools/internal/lsp/cache.(*snapshot).GetVersionedFile(0x400037e200, 0xb83440, 0x400046f0e0, 0x400046bc80, 0x79, 0x0, 0x0, 0x0, 0x0)
	/tmp/workdir-host-freebsd-arm64-dmgk/gopath/src/golang.org/x/tools/internal/lsp/cache/snapshot.go:1309 +0xb8 fp=0x400050f880 sp=0x400050f800 pc=0x6ab4f8
golang.org/x/tools/internal/lsp/mod.Diagnostics(0xb83440, 0x400046f0e0, 0xb97d38, 0x400037e200, 0x0, 0x0, 0x0)
	/tmp/workdir-host-freebsd-arm64-dmgk/gopath/src/golang.org/x/tools/internal/lsp/mod/diagnostics.go:26 +0x3a8 fp=0x400050fa20 sp=0x400050f880 pc=0x64a148
golang.org/x/tools/internal/lsp.(*Server).diagnose(0x400028f7a0, 0xb83ad0, 0x40004d8d80, 0xb97d38, 0x400037e200, 0x0)
	/tmp/workdir-host-freebsd-arm64-dmgk/gopath/src/golang.org/x/tools/internal/lsp/diagnostics.go:197 +0x24c fp=0x400050ff10 sp=0x400050fa20 pc=0x70aa0c
golang.org/x/tools/internal/lsp.(*Server).diagnoseDetached(0x400028f7a0, 0xb97d38, 0x400037e200)
	/tmp/workdir-host-freebsd-arm64-dmgk/gopath/src/golang.org/x/tools/internal/lsp/diagnostics.go:91 +0x90 fp=0x400050ff70 sp=0x400050ff10 pc=0x709d60
golang.org/x/tools/internal/lsp.(*Server).addFolders.func3(0x400028f7a0, 0xb97d38, 0x400037e200, 0x400038af70, 0x40004d8240, 0x400038a400)
	/tmp/workdir-host-freebsd-arm64-dmgk/gopath/src/golang.org/x/tools/internal/lsp/general.go:264 +0x30 fp=0x400050ffa0 sp=0x400050ff70 pc=0x7263e0
runtime.goexit()
	/tmp/workdir-host-freebsd-arm64-dmgk/go/src/runtime/asm_arm64.s:1130 +0x4 fp=0x400050ffa0 sp=0x400050ffa0 pc=0x77a04
created by golang.org/x/tools/internal/lsp.(*Server).addFolders
	/tmp/workdir-host-freebsd-arm64-dmgk/gopath/src/golang.org/x/tools/internal/lsp/general.go:263 +0x80c
```

`greplogs --dashboard -md -l -e 'fatal error: concurrent map read and map write\n\ngoroutine \d+ \[running\]:\n(?:.+\n\t.+\n)*golang\.org/x/tools/internal/lsp/cache'`

[2022-01-20T20:23:52-80963bc-378766a/freebsd-arm64-dmgk](https://build.golang.org/log/490fb47b193018d951ce95e267a3cbde5c28d773)

CC @findleyr

**Comment by bcmills** [comment]
One of the runnable goroutines in that log is here, in `(*snapshot).loadWorkspace`:
https://cs.opensource.google/go/x/tools/+/master:internal/lsp/cache/view.go;l=645;drc=7424a4db47b8e19a8d1c162aced1b0c5d421dd3a

Two lines above that is a call to `locateTemplateFiles`, which has a suspiciously-unsynchronized write:
https://cs.opensource.google/go/x/tools/+/master:internal/lsp/cache/view.go;l=403;drc=7424a4db47b8e19a8d1c162aced1b0c5d421dd3a

That write is in the `initialize` path, so I suspect that somehow we are attempting to read from the snapshot before it has finished initializing.

**Comment by findleyr** [comment]
Thanks for the investigation, I believe you are right.

This is an old bug, caught by a new test. Fix incoming.
