### ISSUE TITLE
runtime: continuing TestSegv/SegvInCgo failures with "unknown pc"

### ISSUE THREAD

**Issue by bcmills** [golang/go#50979]
```
#!watchflakes
post <- pkg == "runtime" && test == "TestSegv" && `SegvInCgo` && `unknown pc`
```

```
--- FAIL: TestSegv (0.00s)
    --- FAIL: TestSegv/SegvInCgo (0.15s)
        testenv.go:361: [/var/gobuilder/buildlet/tmp/go-build403866584/testprogcgo.exe SegvInCgo] exit status: exit status 2
        crash_cgo_test.go:596: SIGSEGV: segmentation violation
            PC=0x6e267e74 m=2 sigcode=0
            
            goroutine 0 [idle]:
            runtime: unknown pc 0x6e267e74
            stack: frame={sp:0x5d9cddd8, fp:0x0} stack=[0x5d5ce388,0x5d9cdf88)
            0x5d9cdd58:  0x00122318  0x5d9cddf4  0x5d9cdd84  0x5d9cdd70 
            0x5d9cdd68:  0x6e2eb950  0x6e2e8380  0x6dec0000  0x00000000 
            0x5d9cdd78:  0x5d9cdda4  0x5d9cdd88  0x6e2eba88  0x6e2e90a8 
            0x5d9cdd88:  0x000f4240 <net.(*resolverConfig).tryUpdate+0x00000264>  0x5d9cddec  0x01406f40  0x6df6a000 
            0x5d9cdd98:  0x5d9cdde4  0x5d9cdda8  0x001222a0  0x6e2eba20 
            0x5d9cdda8:  0x5d9cdddc  0x5d9cddb8  0x6e1b3088  0x6e1f7b30 
            0x5d9cddb8:  0x00000001  0x5d9cddf4  0x5d9cde10  0x6df6a000 
            0x5d9cddc8:  0x0021da48  0x0042e240  0x000000f0  0x004025a0 
            0x5d9cddd8: <0x5d9cde3c  0x5d9cdde8  0x00122470  0x6e2e9838 
            0x5d9cdde8:  0x000000f0  0x6dec0000  0x00400000  0x22220002 
            0x5d9cddf8:  0x00000000  0x00000000  0xffffffff  0xffffffff 
            0x5d9cde08:  0xffffffff  0xffffffff  0x00000000  0x00000000 
            0x5d9cde18:  0x00000000  0x00000000  0x00000000  0x5d9e621e 
            0x5d9cde28:  0x00000040  0x00000000  0x0021dbd8  0x5d9cde40 
            0x5d9cde38:  0x0007b888 <runtime.asmcgocall+0x000000ac>  0x001223e8  0x00245974  0x00000000 
            0x5d9cde48:  0x00000001  0x00423901  0x5d9cde5c  0x00000000 
            runtime: unknown pc 0x6e267e74
            stack: frame={sp:0x5d9cddd8, fp:0x0} stack=[0x5d5ce388,0x5d9cdf88)
            0x5d9cdd58:  0x00122318  0x5d9cddf4  0x5d9cdd84  0x5d9cdd70 
            0x5d9cdd68:  0x6e2eb950  0x6e2e8380  0x6dec0000  0x00000000 
            0x5d9cdd78:  0x5d9cdda4  0x5d9cdd88  0x6e2eba88  0x6e2e90a8 
            0x5d9cdd88:  0x000f4240 <net.(*resolverConfig).tryUpdate+0x00000264>  0x5d9cddec  0x01406f40  0x6df6a000 
            0x5d9cdd98:  0x5d9cdde4  0x5d9cdda8  0x001222a0  0x6e2eba20 
            0x5d9cdda8:  0x5d9cdddc  0x5d9cddb8  0x6e1b3088  0x6e1f7b30 
            0x5d9cddb8:  0x00000001  0x5d9cddf4  0x5d9cde10  0x6df6a000 
            0x5d9cddc8:  0x0021da48  0x0042e240  0x000000f0  0x004025a0 
            0x5d9cddd8: <0x5d9cde3c  0x5d9cdde8  0x00122470  0x6e2e9838 
            0x5d9cdde8:  0x000000f0  0x6dec0000  0x00400000  0x22220002 
            0x5d9cddf8:  0x00000000  0x00000000  0xffffffff  0xffffffff 
            0x5d9cde08:  0xffffffff  0xffffffff  0x00000000  0x00000000 
            0x5d9cde18:  0x00000000  0x00000000  0x00000000  0x5d9e621e 
            0x5d9cde28:  0x00000040  0x00000000  0x0021dbd8  0x5d9cde40 
            0x5d9cde38:  0x0007b888 <runtime.asmcgocall+0x000000ac>  0x001223e8  0x00245974  0x00000000 
            0x5d9cde48:  0x00000001  0x00423901  0x5d9cde5c  0x00000000 
            
            goroutine 1 [sleep]:
            time.Sleep(0x3b9aca00)
            	/var/gobuilder/buildlet/go/src/runtime/time.go:194 +0x170
            main.SegvInCgo()
            	/var/gobuilder/buildlet/go/src/runtime/testdata/testprogcgo/segv.go:56 +0xcc
            main.main()
            	/var/gobuilder/buildlet/go/src/runtime/testdata/testprogcgo/main.go:34 +0x158
            
            goroutine 6 [runnable]:
            main._Cfunc_nop()
            	_cgo_gotypes.go:364 +0x38
            main.SegvInCgo.func1()
            	/var/gobuilder/buildlet/go/src/runtime/testdata/testprogcgo/segv.go:47 +0x20
            created by main.SegvInCgo
            	/var/gobuilder/buildlet/go/src/runtime/testdata/testprogcgo/segv.go:44 +0x74
            
            trap    0x0
            error   0x0
            oldmask 0x0
            r0      0x0
            r1      0x0
            r2      0x0
            r3      0x0
            r4      0x0
            r5      0x5d9cde10
            r6      0x6df6a000
            r7      0x21da48
            r8      0x42e240
            r9      0xf0
            r10     0x4025a0
            fp      0x5d9cdde4
            ip      0x6e300674
            sp      0x5d9cddd8
            lr      0x6e2e983c
            pc      0x6e267e74
            cpsr    0x400d0010
            fault   0x0
            
        crash_cgo_test.go:622: unexpectedly saw "runtime: " in output
FAIL
FAIL	runtime	155.487s
```

`greplogs --dashboard -md -l -e '\Anetbsd-.*(?:\n.*)*FAIL: TestSegv/SegvInCgo .*(?:\n    .*)*unknown pc' --since=2022-01-07`

[2022-02-01T16:10:04-93fe469/netbsd-arm-bsiegert](https://build.golang.org/log/e71058b3a2f428c2437bfa78fd5702a096eed9aa)

It is not obvious to me whether this has the same underlying cause as #50605.
(See previously #49182; CC @prattmic @cherrymui.)

**Comment by bcmills** [comment]
`greplogs --dashboard -md -l -e 'FAIL: TestSegv/SegvInCgo .*(?:\n .*)*runtime: unknown pc' --since=2022-02-07`

[2022-02-10T15:23:05-452f24a/linux-riscv64-unmatched](https://build.golang.org/log/b1cbe5f51778c3f00a10b486413568b28604852d)

**Comment by bcmills** [comment]
Four flakes in a month during the testing-lull that is the code freeze makes me think this test is too noisy to leave enabled in the `runtime` package.

If we aren't going to be able to fix it ahead of the 1.18 release, I think it at least needs a skip.

**Comment by bcmills** [comment]
This failure mode is now skipped, so this is no longer a 1.18 release-blocker. (I'll leave it up to @cherrymui and @prattmic to decide whether to prioritize a fix or move it to the Backlog.)

**Comment by bcmills** [comment]
@prattmic, it looks like the change in the `throw` print in [CL 390034](https://go.dev/cl/390034) cause the skip for this test to no longer take effect. Could you update the skip?

`greplogs --dashboard -md -l -e 'FAIL: TestSegv/SegvInCgo .*(?:\n .*)*unknown pc' --since=2022-03-01`

[2022-03-08T21:16:53-c3c7477/linux-mips64le-mengzhuo](https://build.golang.org/log/42eb5c7e7f9182b3daf6b32642f499fea2181c2c)
[2022-03-07T16:24:54-cc9d3f5/linux-mips64le-mengzhuo](https://build.golang.org/log/ab973896622c4275e78087c86cb88b4915472e43)

**Comment by prattmic** [comment]
Apologies, I thought I checked for these references, but didn't do a good job.

**Comment by heschi** [comment]
ping -- what's the status of this issue?

**Comment by prattmic** [comment]
The failures here should be skipped, but we'd still like to investigate. Not a release blocker, though.

**Comment by ianlancetaylor** [comment]
Rolling forward to 1.20.  Please comment if you disagree.  Thanks.

**Comment by bcmills** [comment]
@golang/runtime, this failure mode should either be fixed or skipped, and there is an open CL (https://go.dev/cl/430375) that does the latter.

Marking as release-blocker pending a decision to either investigate and fix or merge the skip. Please don't leave flaky tests running if they aren't actively being worked on.

**Comment by bcmills** [comment]
Hmm.... Actually, looking a that CL it is for `TestSegv/Segv`, not `TestSegv/SegvInCgo`. 🤔

**Comment by mknyszek** [comment]
Looking at recent failures, I think this continues to not be a release blocker, but it has flaked a bunch of times on some ports:

[2022-11-21T17:11:59-d685946/openbsd-amd64-68](https://build.golang.org/log/252884cbe30c748e43321d34dcee721f89c2bb90)
[2022-11-17T19:55:28-81c9b1d/openbsd-arm-jsing](https://build.golang.org/log/686b6a6411a4a3f7ae13ec18dbc155b6a39d19bd)
[2022-11-08T08:14:37-0b7aa9f/openbsd-386-70](https://build.golang.org/log/4599bf361026c95b999cc9ca92f81af5c88d9042)
[2022-11-07T10:42:25-a9767ea/openbsd-386-70](https://build.golang.org/log/4d095491d9880d25915b8c1ab8aa6649be3f38af)
[2022-11-04T12:56:08-d65c059/openbsd-386-70](https://build.golang.org/log/f6ef37257dc3e00152a50d5ca0223bd7764f5278)
[2022-10-18T20:45:51-54ad7f3/openbsd-arm64-jsing](https://build.golang.org/log/834b65927b7811fe87907afc18baee8c2c1fdc14)
[2022-10-17T18:22:06-3e100a2/openbsd-arm64-jsing](https://build.golang.org/log/982656bec542f3dc77007fb3dc57455ea22b2cea)
[2022-09-21T15:30:20-e246cf6/linux-ppc64le-power9osu](https://build.golang.org/log/09faa5b25b23ce84e51a6c5042f11a073b80c56b)

**Comment by cherrymui** [comment]
For the openbsd failures
```
    --- FAIL: TestSegv/Segv (0.09s)
        crash_test.go:58: /tmp/workdir/tmp/go-build3686268924/testprogcgo.exe Segv: exit status 2
        crash_cgo_test.go:618: fatal error: unexpected signal during runtime execution
            [signal SIGSEGV: segmentation violation code=0x14 addr=0xe0000000b pc=0x2a15a3c4a]
            
            runtime stack:
            runtime.throw({0x248e92?, 0x0?})
            	/tmp/workdir/go/src/runtime/panic.go:1047 +0x5d fp=0x266840070 sp=0x266840040 pc=0x35cd7d
            runtime.sigpanic()
            	/tmp/workdir/go/src/runtime/signal_unix.go:821 +0x3e9 fp=0x2668400d0 sp=0x266840070 pc=0x373889
            runtime.syscall()
            	/tmp/workdir/go/src/runtime/sys_openbsd_amd64.s:466 +0x1f fp=0x2668400e0 sp=0x2668400d0 pc=0x392a3f

            goroutine 1 [syscall]:
            syscall.syscall(0x3b55a0, 0x1f0e, 0xb, 0x0)
            	/tmp/workdir/go/src/runtime/sys_openbsd3.go:24 +0x3b fp=0xc00005be48 sp=0xc00005be28 pc=0x38d77b
            syscall.syscall(0x32e1f8?, 0xc00007c0c0?, 0x0?, 0x43c201?)
            	<autogenerated>:1 +0x26 fp=0xc00005be90 sp=0xc00005be48 pc=0x393406
            syscall.Kill(0xc0ffffffff?, 0x0?)
            	/tmp/workdir/go/src/syscall/zsyscall_openbsd_amd64.go:893 +0x2f fp=0xc00005bec0 sp=0xc00005be90 pc=0x3b412f
```

`sigpanic` is called, which means the Go signal handler treats it as a kernel-issued SIGSEGV, instead of a user-sent one.

@golang/openbsd do you know if the OpenBSD kernel may report a user-sent SIGSEGV as kernel-sent (i.e. the signal code being not SI_USER)? Thanks.

**Comment by laboger** [comment]
I think this is the same problem as #52963 and @pmur created a CL to skip this failure https://go.dev/cl/430375.

There is a Go signal handler that tries to do a Go backtrace but gets sent to a thread running C code which won't work.

**Comment by bcmills** [comment]
If the Go signal handler is trying to obtain a backtrace, does the test binary need to call [`runtime.SetCgoTraceback`](https://pkg.go.dev/runtime#SetCgoTraceback) with some appropriate callback to ensure that it can backtrace a signal delivered to a C stack?

(It looks like the fact that the thread is running C code is an intentional part of the test.)

Or is the problem that the thread is running C code without _any_ Go frames on the stack? In that case, would it help to thread-lock the `C.nop()` goroutine and use `syscall.Tgkill` (where available) to deliver the signal to that thread in particular? (Compare #19326.)

**Comment by laboger** [comment]
This is not easily reproducible. I think @pmur was able to make it fail and found that it was on a stack that was running only C code. But the Go stacktracer only works for a Go stackframe at least on PPC64. Slot 0 of the frame is the LR value in Go, but it is the caller's stack pointer in C and that is why you get the unknown PC error when running C code.

See @cherrymui's suggestion in the CL for fixing the test.
