### ISSUE TITLE
os/signal: timeouts in TestNotifyContextNotifications on solaris-amd64-oraclerel

### ISSUE THREAD

**Issue by bcmills** [golang/go#51054]
```
#!watchflakes
post <- pkg == "os/signal" && test == "TestNotifyContextNotifications"
```

```
goroutine 73 [syscall]:
runtime.syscall_wait4(0x4317, 0xc00022247c, 0x0, 0xc000260990)
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/runtime/syscall_solaris.go:312 +0x86 fp=0xc0000bbd38 sp=0xc0000bbce0 pc=0x462026
syscall.Wait4(0x203000?, 0xc000204750?, 0xc000229608?, 0x40c945?)
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/syscall/syscall_solaris.go:247 +0x2c fp=0xc0000bbd80 sp=0xc0000bbd38 pc=0x46e2cc
os.(*Process).wait(0xc000248330)
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/os/exec_unix.go:43 +0x85 fp=0xc0000bbdd8 sp=0xc0000bbd80 pc=0x4832a5
os.(*Process).Wait(...)
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/os/exec.go:132
os/exec.(*Cmd).Wait(0xc00025edc0)
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/os/exec/exec.go:507 +0x54 fp=0xc0000bbe50 sp=0xc0000bbdd8 pc=0x4c7a94
os/exec.(*Cmd).Run(0x5?)
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/os/exec/exec.go:341 +0x39 fp=0xc0000bbe70 sp=0xc0000bbe50 pc=0x4c6bf9
os/exec.(*Cmd).CombinedOutput(0xc00025edc0)
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/os/exec/exec.go:567 +0x96 fp=0xc0000bbe98 sp=0xc0000bbe70 pc=0x4c7db6
os/signal.TestNotifyContextNotifications.func2(0xc000278ea0)
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/os/signal/signal_test.go:749 +0x191 fp=0xc0000bbf70 sp=0xc0000bbe98 pc=0x4cf871
testing.tRunner(0xc000278ea0, 0xc0002184f0)
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/testing/testing.go:1440 +0x102 fp=0xc0000bbfc0 sp=0xc0000bbf70 pc=0x4bb6c2
testing.(*T).Run.func1()
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/testing/testing.go:1487 +0x2a fp=0xc0000bbfe0 sp=0xc0000bbfc0 pc=0x4bc56a
runtime.goexit()
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0000bbfe8 sp=0xc0000bbfe0 pc=0x4653a1
created by testing.(*T).Run
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/testing/testing.go:1487 +0x35f
```

`greplogs --dashboard -md -l -e 'panic: test timed out .*\n(?:\ngoroutine \d+ .*:\n(.+\n)*)*^os/signal\.TestNotifyContextNotifications' --since=2021-01-01`

[2022-02-04T20:44:18-02224c8/solaris-amd64-oraclerel](https://build.golang.org/log/2292fe2723350bcaf0fff645f1732183f0d68290)
[2021-11-29T19:45:58-f598e29/solaris-amd64-oraclerel](https://build.golang.org/log/52f4c606f957ef9d5f45621b5bc4f8a3b56c42b3)
[2021-11-17T04:31:45-633d8c1/solaris-amd64-oraclerel](https://build.golang.org/log/ba534a8f022e344cf7333756b96b39a978a9a32e)
[2021-10-31T15:36:50-243c5ae/solaris-amd64-oraclerel](https://build.golang.org/log/46376f5a06765153aefb43ca5ca2dce27fbb9cca)
[2021-10-01T18:18:46-0d65c27/solaris-amd64-oraclerel](https://build.golang.org/log/b749e4067289e0209c2afb04e41afcb1c2920891)
[2021-10-01T17:18:34-dab16c1/solaris-amd64-oraclerel](https://build.golang.org/log/350e6957cd6d5809763f75ca2ea6ce8b1f78dfae)
[2021-10-01T16:17:08-f19b2d5/solaris-amd64-oraclerel](https://build.golang.org/log/79e01f5c24f94a22ef3d542a087bf81def2ca41d)
[2021-10-01T14:06:36-96d3ba8/solaris-amd64-oraclerel](https://build.golang.org/log/24785f752996eb76b1ab3f74ec399f190a046295)
[2021-09-17T20:26:51-974b016/solaris-amd64-oraclerel](https://build.golang.org/log/1ae11b3a81b6ff68ba76bae9d57d57e029238b54)
[2021-08-16T23:32:14-8ff16c1/solaris-amd64-oraclerel](https://build.golang.org/log/4c29c620e8024a6acc8be5a337137e7a251ca043)
[2021-08-16T14:26:45-b0fba64/solaris-amd64-oraclerel](https://build.golang.org/log/3110b51ceee875e2b07b115b6dbb34ffc40f6b5c)
[2021-04-28T19:52:58-07e006d/solaris-amd64-oraclerel](https://build.golang.org/log/835e1abe0c655a4eba686e746c377ce097647458)
[2021-04-26T18:54:39-0d1280c/solaris-amd64-oraclerel](https://build.golang.org/log/2d214baef5a55deb610067f135f09a47304d365e)
[2021-04-23T21:42:57-c0e1301/solaris-amd64-oraclerel](https://build.golang.org/log/be427541ae7ad6f8772c75cf9fb4424c54d68bd2)
[2021-04-22T16:15:44-d3853fb/solaris-amd64-oraclerel](https://build.golang.org/log/cdb7d40f340b6c21120e675ad0f3083840587bf3)
[2021-04-16T16:36:57-2f0e5bf/solaris-amd64-oraclerel](https://build.golang.org/log/b985b4637b29fecee57e9dda546f3cf3b3ff2908)
[2021-04-16T16:11:09-04e1176/solaris-amd64-oraclerel](https://build.golang.org/log/53496d51ba1427505d3a3f01503ff42e9cfaf202)
[2021-04-15T12:38:11-dba2eab/solaris-amd64-oraclerel](https://build.golang.org/log/875498f50c43ab47280bb8bd7e9dcb43e5e47cbd)
[2021-04-06T04:48:09-a25c584/solaris-amd64-oraclerel](https://build.golang.org/log/416be2d8d0afceacd601534a9731dcc522c70c02)
[2021-03-18T14:09:57-db4adb1/solaris-amd64-oraclerel](https://build.golang.org/log/49dde6fd7cd68994b78814920ea191a98c246678)

This is the same test that was observed to be flaky in #41561 (CC @henvic, @ianlancetaylor, @cherrymui).

**Comment by bcmills** [comment]
It's interesting that the test is blocked on this subprocess in particular, because we explicitly plumb in a value for the `-test.timeout` flag that should be short enough to complete before the test finishes:
https://cs.opensource.google/go/go/+/master:src/os/signal/signal_test.go;l=746-748;drc=e3eaedb5cf623d0836533573db4140749da42768

**Comment by henvic** [comment]
Thanks for pinging me, @bcmills.
I'll try to reproduce it on a Solaris VM during this weekend.

**Comment by bcmills** [comment]
One more this month:

`greplogs --dashboard -md -l -e 'panic: test timed out .*\n(?:\ngoroutine \d+ .*:\n(.+\n)*)*^os/signal\.TestNotifyContextNotifications' --since=2022-02-08`

[2022-03-07T18:19:44-7dc6c5e/solaris-amd64-oraclerel](https://build.golang.org/log/2e53bcbcbdb225ef5b3dd5a294320ff89e3ad30c)

I notice that we're not actually calling `t.Parallel()` in the subtests. I wonder if the test is actually timing out in the first subtest, and then starting the second subtest without actually having enough time left to clean up.

It occurs to me that the `os/exec` changes proposed in #50436 would probably help here too: if either subtest times out, we ought to terminate the subprocess with `SIGQUIT` to figure out what it's stuck on.

**Comment by henvic** [comment]
\* `t.Parallel()` is called in TestNotifyContextNotifications immediately after the `checkNotifyContext` conditional.

I was able to reproduce this (building checked out @ commit 0261fa616a16dc37b862691f79c7b4d301dfbe4a) when running all.bash on a `SunOS solaris 5.11 11.4.0.15.0 i86pc i386 i86pc` virtual machine. In my case, it's happening about once every ~20 runs or so. I wasn't able to identify cause. Weirdly, increasing the memory of the virtual machine seems to have reduced the number of times this happened.

**Comment by bcmills** [comment]
> I wasn't able to identify cause. Weirdly, increasing the memory of the virtual machine seems to have reduced the number of times this happened.

Since `solaris/amd64` is not a [first class port](https://go.dev/wiki/PortingPolicy#first-class-ports), if we can't identify the cause of the failure it would be ok to skip the test on that platform.

`greplogs --dashboard -md -l -e 'panic: test timed out .*\n(?:\ngoroutine \d+ .*:\n(.+\n)*)*^os/signal\.TestNotifyContextNotifications' --since=2022-03-08`

[2022-03-28T19:46:07-1a9972e/solaris-amd64-oraclerel](https://build.golang.org/log/99c284999b9289f7c75713b3f8524a738ee0cee4)

**Comment by bcmills** [comment]
[CL 398454](https://go.dev/cl/398454) might fix this. I'll keep an eye on it.

**Comment by bcmills** [comment]
The thrilling conclusion, from https://build.golang.org/log/efc839b64c4b5ef269ecf21fa28685fbeb600e18:
```
--- FAIL: TestNotifyContextNotifications (0.00s)
    --- FAIL: TestNotifyContextNotifications/once (0.00s)
        signal_test.go:741: starting test with less than 22s remaining
    --- FAIL: TestNotifyContextNotifications/multiple (0.00s)
        signal_test.go:741: starting test with less than 22s remaining
FAIL
FAIL	os/signal	158.438s
```

The large `settleTime` that we had to set on `solaris` is just too slow. I guess for the interim we can try scaling it back, but longer term we should rework the tests not to send signals to the main test process to begin with. 🤔

**Comment by ianlancetaylor** [comment]
Rolling forward to 1.20.  Please comment if you disagree.  Thanks.
