### ISSUE TITLE
net: TestLookupContextCancel failure with nil-error conversion panic on windows-arm64-10

### ISSUE THREAD

**Issue by bcmills** [golang/go#51084]
```
--- FAIL: TestLookupContextCancel (0.00s)
panic: interface conversion: error is nil, not *net.DNSError [recovered]
	panic: interface conversion: error is nil, not *net.DNSError

goroutine 185 [running]:
panic({0x7ff6c6976fa0, 0x4000257920})
	C:/workdir/go/src/runtime/panic.go:941 +0x3d8 fp=0x400006db50 sp=0x400006da90 pc=0x7ff6c67b6658
testing.tRunner.func1.2({0x7ff6c6976fa0, 0x4000257920})
	C:/workdir/go/src/testing/testing.go:1389 +0x1c8 fp=0x400006dc00 sp=0x400006db50 pc=0x7ff6c68651d8
testing.tRunner.func1()
	C:/workdir/go/src/testing/testing.go:1392 +0x380 fp=0x400006dd70 sp=0x400006dc00 pc=0x7ff6c6864d40
runtime.deferCallSave(0x400006de50, 0x40000c9f88?)
	C:/workdir/go/src/runtime/panic.go:750 +0x94 fp=0x400006dd80 sp=0x400006dd70 pc=0x7ff6c67b6224
runtime.runOpenDeferFrame(0x4000064050?, 0x4000064000)
	C:/workdir/go/src/runtime/panic.go:723 +0x1b8 fp=0x400006ddd0 sp=0x400006dd80 pc=0x7ff6c67b6048
panic({0x7ff6c6976fa0, 0x4000257920})
	C:/workdir/go/src/runtime/panic.go:838 +0x20c fp=0x400006de90 sp=0x400006ddd0 pc=0x7ff6c67b648c
runtime.panicdottypeE(...)
	C:/workdir/go/src/runtime/iface.go:262
runtime.panicdottypeI(0x7ff6c6b33900?, 0x7ff6c697a2c0, 0x7ff6c6978340)
	C:/workdir/go/src/runtime/iface.go:272 +0x78 fp=0x400006dec0 sp=0x400006de90 pc=0x7ff6c6789618
net.TestLookupContextCancel(0x40001a4ea0)
	C:/workdir/go/src/net/lookup_test.go:891 +0x230 fp=0x400006df60 sp=0x400006dec0 pc=0x7ff6c69031b0
testing.tRunner(0x40001a4ea0, 0x7ff6c69bd7a0)
	C:/workdir/go/src/testing/testing.go:1439 +0x110 fp=0x400006dfb0 sp=0x400006df60 pc=0x7ff6c68648f0
testing.(*T).Run.func1()
	C:/workdir/go/src/testing/testing.go:1486 +0x30 fp=0x400006dfd0 sp=0x400006dfb0 pc=0x7ff6c6865660
runtime.goexit()
	C:/workdir/go/src/runtime/asm_arm64.s:1259 +0x4 fp=0x400006dfd0 sp=0x400006dfd0 pc=0x7ff6c67e62b4
created by testing.(*T).Run
	C:/workdir/go/src/testing/testing.go:1486 +0x328
```

`greplogs --dashboard -md -l -e 'FAIL: TestLookupContextCancel .*\npanic: interface conversion'`

[2022-02-08T08:41:09-c856fbf/windows-arm64-10](https://build.golang.org/log/4c72c3aee2190398e0393cacc50de821aa0c4585)

**Comment by bcmills** [comment]
I can reproduce the problem reliably by adding a `time.Sleep` [here](https://cs.opensource.google/go/go/+/master:src/net/lookup.go;l=324;drc=2580d0e08d5e9f979b943758d3c49877fb2324cb) and running the test with `-count=10`.
