### ISSUE TITLE
x/crypto/acme/autocert: renewal test failures due to connection errors on windows/arm64

### ISSUE THREAD

**Issue by bcmills** [golang/go#51080]
`greplogs --dashboard -md -l -e FAIL\\s+golang\\.org/x/crypto/acme/autocert --since=2021-01-01 --omit=.\*-n2d`

[2022-02-08T08:41:09-20e1d8d-c856fbf/windows-arm64-10](https://build.golang.org/log/1a19e22ad826bedeb5a939c6130f368f9979208a)
```
panic: close of closed channel

goroutine 476 [running]:
runtime.Goexit()
	C:/workdir/go/src/runtime/panic.go:482 +0x190
testing.(*common).FailNow(0x4000234820)
	C:/workdir/go/src/testing/testing.go:864 +0x48
testing.(*common).Fatalf(0x4000234820, {0x7ff6a835e0c5?, 0x0?}, {0x400033be80?, 0xeda0b3426?, 0x0?})
	C:/workdir/go/src/testing/testing.go:948 +0x64
golang.org/x/crypto/acme/autocert.TestRenewFromCacheAlreadyRenewed.func2(0x2f3c74aa43a?, {0x7ff6a83f1b28?, 0x40001e1740?})
	C:/workdir/gopath/src/golang.org/x/crypto/acme/autocert/renewal_test.go:208 +0x634
golang.org/x/crypto/acme/autocert.(*domainRenewal).renew(0x400011a680)
	C:/workdir/gopath/src/golang.org/x/crypto/acme/autocert/renewal.go:71 +0x1e0
created by time.goFunc
	C:/workdir/go/src/time/sleep.go:176 +0x3c
FAIL	golang.org/x/crypto/acme/autocert	7.099s
```

[2022-02-07T20:21:30-30dcbda-49030c8/windows-arm64-11](https://build.golang.org/log/5ae2fe49bea3ee0d7793c039e603692da0c23467)
```
--- FAIL: TestRenewFromCache (2.35s)
    ca.go:253: GET /
    ca.go:253: POST /new-reg
    ca.go:253: POST /new-order
    ca.go:253: POST /authz/0
    ca.go:253: POST /challenge/tls-alpn-01/0
    ca.go:569: validated "tls-alpn-01" for "example.org", err: <nil>
    ca.go:570: authz 0 is now valid
    ca.go:599: order 0 is now ready
    ca.go:253: POST /authz/0
    ca.go:253: POST /orders/0
    ca.go:253: POST /new-cert/0
    renewal_test.go:70: testDidRenewLoop: Get "http://127.0.0.1:50039": dial tcp 127.0.0.1:50039: connectex: No connection could be made because the target machine actively refused it.
    renewal_test.go:77: testDidRenewLoop: next = 36m2.864378606s; want >= 2112h0m0s
    ca.go:253: HEAD /new-nonce
    renewal_test.go:87: cache leaf.NotAfter = 2022-02-08 04:25:30 +0000 UTC; want > 2022-05-06 21:24:30.835158 -0700 PDT m=+7603206.680959301
    renewal_test.go:102: state leaf.NotAfter = 2022-02-08 04:25:30 +0000 UTC; want > 2022-05-06 21:24:30.835158 -0700 PDT m=+7603206.680959301
FAIL
FAIL	golang.org/x/crypto/acme/autocert	9.467s
```

[2022-02-07T18:43:23-30dcbda-fbcc30a/windows-arm64-10](https://build.golang.org/log/f65a6638d6816d5966b39061c592560519ec5766)
```
--- FAIL: TestRenewFromCache (2.47s)
    ca.go:253: GET /
    renewal_test.go:70: testDidRenewLoop: Get "http://127.0.0.1:49913": dial tcp 127.0.0.1:49913: connectex: No connection could be made because the target machine actively refused it.
    renewal_test.go:77: testDidRenewLoop: next = 48m56.057939107s; want >= 2112h0m0s
    ca.go:253: POST /new-reg
    ca.go:253: POST /new-order
    ca.go:253: POST /authz/0
    renewal_test.go:87: cache leaf.NotAfter = 2022-02-08 02:12:57 +0000 UTC; want > 2022-05-06 19:11:57.5448975 -0700 PDT m=+7603206.549318601
    renewal_test.go:102: state leaf.NotAfter = 2022-02-08 02:12:57 +0000 UTC; want > 2022-05-06 19:11:57.5448975 -0700 PDT m=+7603206.549318601
    ca.go:253: POST /challenge/tls-alpn-01/0
    ca.go:569: validated "tls-alpn-01" for "example.org", err: <nil>
    ca.go:570: authz 0 is now valid
    ca.go:599: order 0 is now ready
FAIL
FAIL	golang.org/x/crypto/acme/autocert	9.367s
```

(attn @bradfitz @rolandshoemaker @FiloSottile per `dev.golang.org/owners`)

**Comment by bcmills** [comment]
Given the timing of these failures, I suspect that the `connectex: No connection could be made` failure mode may stem from [CL 381715](https://go.dev/cl/381715).

This is a release-blocker via #11811. (The tests can be fixed, or can have skips added. Given the recency of that CL, we might consider reverting it if that is reasonably straightforward.)

**Comment by bcmills** [comment]
Still failing (as expected) after the above CL, with the same failure modes (plus once instance of #51019).

`greplogs --dashboard -md -l -e FAIL\\s+golang\\.org/x/crypto/acme/autocert --since=2022-02-09`

[2022-02-11T04:50:35-f4118a5-9fdcfb7/windows-arm64-11](https://build.golang.org/log/fcf2ce978a5938651ff98fb11220354ffe59b0e2)
[2022-02-11T00:30:56-f4118a5-30501bb/windows-arm64-10](https://build.golang.org/log/710a301b86319a6e3e0b37c941d4141ba5fbbad2)
[2022-02-10T15:23:05-f4118a5-452f24a/windows-arm64-10](https://build.golang.org/log/53c458da003ed1cbb8c33fdf494000a381298c84)
[2022-02-10T15:23:05-f4118a5-452f24a/windows-arm64-11](https://build.golang.org/log/18fe6b2476f229424a6a49889af5430b8f46b72c)
[2022-02-10T15:16:21-f4118a5-cd6e0d7/windows-arm64-10](https://build.golang.org/log/facec414982366ca62fcb6c466e6f0aca92f9a50)
[2022-02-10T15:16:21-f4118a5-656d3f4/windows-arm64-11](https://build.golang.org/log/e2a37b4cd515a486b28d88c79882affe2635d209)
[2022-02-09T15:49:31-65fa2f7-be0d049/windows-arm64-10](https://build.golang.org/log/f42fc2560bb2cacbb970150ea4e9ba25d14a44da)

**Comment by qmuntal** [comment]
The offending test has failed for several years, closing.
