### ISSUE TITLE
run cgo command will crash

### ISSUE THREAD

**Issue by Athxx** [golang/go#51296]
### What version of Go are you using (`go version`)?

<pre>
$ go version
`go version go1.16.14 linux/amd64` and `go version go1.17.7 linux/amd64`
</pre>

### Does this issue reproduce with the latest release?
no

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/www/app/go/bin"
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/gopath/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/gopath"
GOPRIVATE=""
GOPROXY="https://goproxy.io,direct"
GOROOT="/www/app/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/www/app/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.7"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build667456912=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I just run a `CGO` process and some time will crash.

### What did you expect to see?
I wanna expect to run it well, I tried versions 1.17.7 and 1.16.14, but they are the same, but when I use 1.16.14, it will crash less than 1.17.7

and I'd upgrade to the latest version of `golang.org/x/sys`. 

### What did you see instead?
this is v1.16.14 errors
```shell
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fea2232b4b1]
runtime stack:
runtime.throw({0xe0070b, 0x7fea228e704c})
#011/www/app/go/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
#011/www/app/go/src/runtime/signal_unix.go:719 +0x396
goroutine 1 [syscall]:
runtime.cgocall(0xc3fd30, 0xc0005ddad8)
#011/www/app/go/src/runtime/cgocall.go:156 +0x5c fp=0xc0005ddab0 sp=0xc0005dda78 pc=0x406bdc
svr/cmd/xkProc._Cfunc_slmExecDirect(0x1af6a70, 0x1af6a70, 0x7fe9e000e8a0, 0x5d)
#011_cgo_gotypes.go:167 +0x4c fp=0xc0005ddad8 sp=0xc0005ddab0 pc=0x83428c
svr/cmd/xkProc.(*SlmApp).Open(0xc0001461f8)
#011/www/slm/srv/svr/cmd/xkProc/slmApp.go:145 +0x454 fp=0xc0005ddbf0 sp=0xc0005ddad8 pc=0x8362f4
svr/cmd/xkProc.Run({0x7fff1c11d91f, 0x1b}, {0x7fff1c11d942, 0x24})
#011/www/slm/srv/svr/cmd/xkProc/main.go:63 +0x435 fp=0xc0005ddd00 sp=0xc0005ddbf0 pc=0x8352b5
main.main.func2(0xc000566500, {0xdda5eb, 0x4, 0x4})
#011/www/slm/srv/svr/main.go:36 +0x2f fp=0xc0005ddd30 sp=0xc0005ddd00 pc=0xc3f88f
github.com/spf13/cobra.(*Command).execute(0xc000566500, {0xc00013c2c0, 0x4, 0x4})
#011/root/gopath/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x5f8 fp=0xc0005dddf0 sp=0xc0005ddd30 pc=0xc34778
github.com/spf13/cobra.(*Command).ExecuteC(0xc00043aa00)
#011/root/gopath/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc fp=0xc0005ddea8 sp=0xc0005dddf0 pc=0xc34e7c
github.com/spf13/cobra.(*Command).Execute(...)
#011/root/gopath/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
main.main()
#011/www/slm/srv/svr/main.go:69 +0x3f0 fp=0xc0005ddf80 sp=0xc0005ddea8 pc=0xc3f7f0
runtime.main()
#011/www/app/go/src/runtime/proc.go:255 +0x227 fp=0xc0005ddfe0 sp=0xc0005ddf80 pc=0x43bb67
runtime.goexit()
```

**Comment by ianlancetaylor** [comment]
This stack backtrace is saying that your C code is dereferencing a `NULL` pointer.  That is either a problem in your C code or in the way that you are calling it.  The stack backtrace is only showing you the Go code, not the C code.

It may or may not help to import "github.com/ianlancetaylor/cgosymbolizer" somewhere in your program.  If that works--and it may not--it will show you a C stack backtrace pointing to the location where the pointer is being dereferenced.

If you are convinced that this is a problem with the Go tools and not with your code, we will need a way to reproduce the problem ourselves.

**Comment by Athxx** [comment]
ok, I'll try and give you feedback. And I can confirm C code is fine, cause I debug C code it's all done, and return the correct parameters. anyway I'll send you the log after I catch logs

**Comment by Athxx** [comment]
@ianlancetaylor this log is what I add `github.com/ianlancetaylor/cgosymbolizer`, and it shows some logs, but these codes all are serialize functions. and all functions are returned, but it still crashes.
```
Feb 22 11:30:34 xk slm[3014950]: fatal error: unexpected signal during runtime execution
Feb 22 11:30:34 xk slm[3014950]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7f1eb5455fa0]
Feb 22 11:30:34 xk slm[3014950]: runtime stack:
Feb 22 11:30:34 xk slm[3014950]: runtime.throw(0xf88bf9, 0x2a)
Feb 22 11:30:34 xk slm[3014950]: #011/www/app/go/src/runtime/panic.go:1117 +0x72
Feb 22 11:30:34 xk slm[3014950]: runtime.sigpanic()
Feb 22 11:30:34 xk slm[3014950]: #011/www/app/go/src/runtime/signal_unix.go:718 +0x2e5
Feb 22 11:30:34 xk slm[3014950]: goroutine 12 [syscall]:
Feb 22 11:30:34 xk slm[3014950]: _ZNK7SlmText13serialContentEP15RtsSerialAccept
Feb 22 11:30:34 xk slm[3014950]: #011/www/slm/srv/core/soulma/coredata/slm_text.cpp:31 pc=0x7f1eb5455fa0
Feb 22 11:30:34 xk slm[3014950]: _ZN12OxWorkHandle13serialNewItemEPK9RtsObjectP14OxSerialAcceptRjP16RtsSerialCollectP12OxConnection
Feb 22 11:30:34 xk slm[3014950]: #011/www/slm/srv/core/foundation/coopserver/oxworkhandle.cpp:873 pc=0x7f1eb5b09281
Feb 22 11:30:34 xk slm[3014950]: _ZN12OxWorkHandle16serialNewObjectsEP14OxSerialAcceptP16RtsSerialCollectP13OxCoopContext
Feb 22 11:30:34 xk slm[3014950]: #011/www/slm/srv/core/foundation/coopserver/oxworkhandle.cpp:835 pc=0x7f1eb5b09450
Feb 22 11:30:34 xk slm[3014950]: _ZN12OxWorkHandle9queryInitEP13OxCoopContextP14OxSerialAcceptb
Feb 22 11:30:34 xk slm[3014950]: #011/www/slm/srv/core/foundation/coopserver/oxworkhandle.cpp:572 pc=0x7f1eb5b09790
Feb 22 11:30:34 xk slm[3014950]: _ZN12OxWorkHandle26queryInitDataWithWorkspaceEP9OxRequest
Feb 22 11:30:34 xk slm[3014950]: #011/www/slm/srv/core/foundation/coopserver/oxworkhandle.cpp:78 pc=0x7f1eb5b0d89e
Feb 22 11:30:34 xk slm[3014950]: runtime.cgocall(0xd78120, 0xc00040de78, 0x0)
Feb 22 11:30:34 xk slm[3014950]: #011/www/app/go/src/runtime/cgocall.go:154 +0x5b fp=0xc00040de48 sp=0xc00040de10 pc=0x40805b
Feb 22 11:30:34 xk slm[3014950]: svr/cmd/xkProc._Cfunc_slmQueryInit(0x7f1e80000e40, 0x7f1e80000e20, 0x7f1e80000e60, 0xc000000000, 0x0)
Feb 22 11:30:34 xk slm[3014950]: #011_cgo_gotypes.go:229 +0x48 fp=0xc00040de78 sp=0xc00040de48 pc=0x8aac68
Feb 22 11:30:34 xk slm[3014950]: svr/cmd/xkProc.onRqtQueryInit(0xc0003ea0da, 0x10, 0x10)
Feb 22 11:30:34 xk slm[3014950]: #011/www/slm/srv/svr/cmd/xkProc/slmApp.go:184 +0x3ff fp=0xc00040df20 sp=0xc00040de78 pc=0x8acebf
Feb 22 11:30:34 xk slm[3014950]: svr/cmd/xkProc.(*SlmApp).pump(0xc000464400, 0xc0003ea0d8, 0x12, 0x12)
Feb 22 11:30:34 xk slm[3014950]: #011/www/slm/srv/svr/cmd/xkProc/slmApp.go:82 +0xb5 fp=0xc00040df60 sp=0xc00040df20 pc=0x8abdd5
Feb 22 11:30:34 xk slm[3014950]: svr/cmd/xkProc.(*SlmApp).Run(0xc000464400, 0x7ffefdb86942, 0x24)
Feb 22 11:30:34 xk slm[3014950]: #011/www/slm/srv/svr/cmd/xkProc/slmApp.go:122 +0x18b fp=0xc00040dfc8 sp=0xc00040df60 pc=0x8ac22b
Feb 22 11:30:34 xk slm[3014950]: runtime.goexit()
Feb 22 11:30:34 xk slm[3014950]: #011/www/app/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc00040dfd0 sp=0xc00040dfc8 pc=0x4729c1
Feb 22 11:30:34 xk slm[3014950]: created by svr/cmd/xkProc.Run
Feb 22 11:30:34 xk slm[3014950]: #011/www/slm/srv/svr/cmd/xkProc/main.go:63 +0x534
Feb 22 11:30:34 xk slm[3014950]: goroutine 1 [chan receive]:
```

**Comment by ianlancetaylor** [comment]
That stack backtrace shows you the exact place in the C++ code where the NULL dereference occurs.  Does that help at all to understand the problem?

You say that "all functions are returned," but they are not.  The crash occurs while executing `SlmText::serialContent(RtsSerialAccept*) const` in file soulma/coredata/slm_text.cpp at line 31.  That function doesn't return, and neither does its callers as seen above.

**Comment by Athxx** [comment]
appreciate your patient answer
