### ISSUE TITLE
x/tools/internal/jsonrpc2_v2: "panic: close of closed channel" in idleListener.run

### ISSUE THREAD

**Issue by bcmills** [golang/go#51435]
```
#!watchflakes
post <- pkg == "golang.org/x/tools/internal/jsonrpc2_v2" && 
        `panic: close of closed channel` && `\(\*idleListener\)\.run`
```
panic: close of closed channel

goroutine 200 [running]:
golang.org/x/tools/internal/jsonrpc2_v2.(*idleListener).run(0x5dba6090)
	/tmp/workdir/gopath/src/golang.org/x/tools/internal/jsonrpc2_v2/serve.go:276 +0x168
created by golang.org/x/tools/internal/jsonrpc2_v2.NewIdleListener
	/tmp/workdir/gopath/src/golang.org/x/tools/internal/jsonrpc2_v2/serve.go:185 +0x136
FAIL	golang.org/x/tools/internal/jsonrpc2_v2	1.607s
```

`greplogs --dashboard -md -l -e '(?ms)panic: close of closed channel.*FAIL\s+golang\.org/x/tools/internal/jsonrpc2_v2'`

[2022-03-02T15:39:07-abbbcaf-40e24a9/openbsd-386-68](https://build.golang.org/log/2b108c1fce127ee077fc14f7dd88d6a44d89c4cd)
[2022-02-15T19:04:00-be40034-b5af5c0/openbsd-386-68](https://build.golang.org/log/5da4dfa703d1f2c44511cbc5c9d0ebc7831bcbe0)
[2022-01-04T22:27:20-15409b5-f154f8b/openbsd-amd64-68](https://build.golang.org/log/40c620d4d7c13ec534c3533c671cf529c990f5ac)
[2021-12-09T13:44:55-e06c107-de690c2/openbsd-386-70-n2](https://build.golang.org/log/dcbe0cd8fb9b7440f657b5a013d1bd7851a94875)
[2021-12-06T21:14:21-feb39d0-d16a575/openbsd-amd64-68](https://build.golang.org/log/087673868df53a8cb9d1526ca75cb9e516113769)
[2021-11-01T14:45:28-42daa65-82f902a/freebsd-amd64-12_2](https://build.golang.org/log/458efad28fe972b0ad49c0477e9babab89b067ea)
[2021-10-21T17:03:18-4100dac-2ac3bdf/openbsd-amd64-68](https://build.golang.org/log/397ef5361eb807778da4f593b64637c6f37c06b8)
[2021-10-19T23:13:35-81f084e-2be5b84/netbsd-amd64-9_0](https://build.golang.org/log/a4ac3f84e2ae8f0083e7101928edfa37a99cd008)
[2021-05-18T22:36:55-17b3466-eeadce2/openbsd-amd64-68](https://build.golang.org/log/d9a1b51af28c8c14b3f0d00485c3dcd00ba844f4)
[2021-05-13T12:32:21-57c3a74-a63cded/openbsd-386-68](https://build.golang.org/log/f4c1b55feda7a1741bebae62edb1f0033ba60496)
[2021-05-12T14:43:27-be4aaae-485474d/openbsd-amd64-68](https://build.golang.org/log/9bd8037f2a514178807acbe0ff580c72d5c6d1b0)

**Comment by adonovan** [comment]
Will be fixed (or rendered obsolete) by https://go-review.googlesource.com/c/tools/+/388597/.

**Comment by heschi** [comment]
[2022-06-28T18:11:31-e5b3324-d5bf960/openbsd-amd64-70](https://build.golang.org/log/5b93f4c1e5d56e49dad9745cb58fb21d02dcf38a)

**Comment by ZekeLu** [comment]
https://github.com/golang/tools/commit/bc4e384f856e909b9ea0fcea24d662e254af38a3 does not contain https://github.com/golang/tools/commit/371ef162f2d8dc59b777cf3705f6afe18d3d6b5c yet. So the found flake is not new. This issue can be closed.
