### ISSUE TITLE
cmd/compile/internal/ir: build panic due to bad interface conversion

### ISSUE THREAD

**Issue by a8m** [golang/go#51555]
### What version of Go are you using (`go version`)?

<pre>
go version go1.17.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

No.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mashraki/Library/Caches/go-build"
GOENV="/Users/mashraki/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/mashraki/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/mashraki/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.17.1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.17.1/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="<private>"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8k/gv05jm297vb3twhgg34z93680000gn/T/go-build1331236325=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Tried to build the following non-correct Go code (by mistake). 

```go
package main

func main() {
	var v interface{} = nil
	v.(nil)
}
```

### What did you expect to see?

```
nil is not a type
```

### What did you see instead?

```
# command-line-arguments
panic: interface conversion: *ir.NilExpr is not ir.Ntype: missing method CanBeNtype

goroutine 1 [running]:
cmd/compile/internal/typecheck.typecheckNtype(...)
	/usr/local/Cellar/go/1.17.1/libexec/src/cmd/compile/internal/typecheck/typecheck.go:269
cmd/compile/internal/typecheck.tcDotType(0xc0000a21e0)
	/usr/local/Cellar/go/1.17.1/libexec/src/cmd/compile/internal/typecheck/expr.go:548 +0x11c
cmd/compile/internal/typecheck.typecheck1({0x1a4bd98, 0xc0000a21e0}, 0x1)
	/usr/local/Cellar/go/1.17.1/libexec/src/cmd/compile/internal/typecheck/typecheck.go:692 +0xf17
cmd/compile/internal/typecheck.typecheck({0x1a4bd98, 0xc0000a21e0}, 0x1)
	/usr/local/Cellar/go/1.17.1/libexec/src/cmd/compile/internal/typecheck/typecheck.go:373 +0x4b0
cmd/compile/internal/typecheck.typecheckslice({0xc0000b2140, 0x3, 0xc0000be048}, 0x11c10c9)
	/usr/local/Cellar/go/1.17.1/libexec/src/cmd/compile/internal/typecheck/typecheck.go:179 +0x68
cmd/compile/internal/typecheck.Stmts(...)
	/usr/local/Cellar/go/1.17.1/libexec/src/cmd/compile/internal/typecheck/typecheck.go:36
cmd/compile/internal/typecheck.FuncBody(0xc0000a6160)
	/usr/local/Cellar/go/1.17.1/libexec/src/cmd/compile/internal/typecheck/typecheck.go:59 +0x65
cmd/compile/internal/noder.LoadPackage({0xc000198130, 0x2, 0x0})
	/usr/local/Cellar/go/1.17.1/libexec/src/cmd/compile/internal/noder/noder.go:145 +0x8f6
cmd/compile/internal/gc.Main(0x1912b48)
	/usr/local/Cellar/go/1.17.1/libexec/src/cmd/compile/internal/gc/main.go:192 +0xb2e
main.main()
	/usr/local/Cellar/go/1.17.1/libexec/src/cmd/compile/main.go:55 +0xdd
````

### Playground

https://go.dev/play/p/PnukKepwouj

**Comment by cuonglm** [comment]
The crash was introduced in https://go-review.googlesource.com/c/go/+/280637, but the other problem is https://go-review.googlesource.com/c/go/+/272650, which makes the compiler from reporting:

```
main.go:5:5: nil is not a type
```

to:

```
main.go:5:3: v.(nil) evaluated but not used
```

Not sure it's worth to fix and backport to go1.17

cc @mdempsky

**Comment by a8m** [comment]
I don't have a strong justification for this code block, besides, it was added by mistake, but the compiler crashed by it and didn't report the error. It is hard to understand what was the root cause from the developer's point of view in this case.

**Comment by mdempsky** [comment]
@cuonglm If the problem is only that we crash on invalid code, then I agree we probably don't need to worry about a fix unless it's very easy.

It's a little concerning that CL 272650 changed the error message though. Can we double check that there's no invalid code that Go 1.17 (incorrectly) accepts?

**Comment by cuonglm** [comment]
> @cuonglm If the problem is only that we crash on invalid code, then I agree we probably don't need to worry about a fix unless it's very easy.
> 
> It's a little concerning that CL 272650 changed the error message though. Can we double check that there's no invalid code that Go 1.17 (incorrectly) accepts?

I think it can't happen. Even `v.(nil)` passed `typecheck` phase, we still be able to catch it in `walkExpr`, since when that `NilExpr` will be detected as untyped, and the compiler will crash.
