### ISSUE TITLE
cmd/compile: able to use interface with type constraints

### ISSUE THREAD

**Issue by dsnet** [golang/go#51578]
I'm a little behind on the latest with generics, but my understanding is that interfaces with type sets can currently only be used as type constraints.

If so, I would [expect the following to not compile](https://gotipplay.golang.org/p/0E6chDfG4bV):
```go
type TypeSet interface{ int | string }

func main() {
	t := reflect.TypeOf((*TypeSet)(nil)).Elem()
	fmt.Println(t)
	fmt.Println(t.Kind())
	fmt.Println(t.NumMethod())

	v := reflect.New(t).Elem()
	v.Set(reflect.ValueOf([]byte("hello"))) // this should panic
	fmt.Println(v.Elem().Type())
}
```
However, not only does it compile, it also executes with incorrect results:
```
main.TypeSet
interface
0
[]uint8
```

The `v.Set(reflect.ValueOf([]byte("hello")))` is expected to panic since the underlying interface is specified to only hold `int` or `string`.

\cc @mdempsky @griesemer @ianlancetaylor

**Comment by griesemer** [comment]
The declaration
```Go
type TypeSet interface{ int | string }
```
is ok, but one shouldn't be able to use this type in the conversion of `nil`. Looks like a simple oversight. Investigating.

**Comment by dsnet** [comment]
Also, compiling with `GOEXPERIMENT=unified` produces an internal compiler error:
```
<unknown line number>: internal compiler error: panic: unexpected type: 10

goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go.tip/src/runtime/debug/stack.go:24 +0x65
cmd/compile/internal/base.FatalfAt({0x222d0?, 0xc0?}, {0xd0a13b, 0x9}, {0xc0005b63c8, 0x1, 0x1})
	/usr/local/go.tip/src/cmd/compile/internal/base/print.go:227 +0x1d7
cmd/compile/internal/base.Fatalf(...)
	/usr/local/go.tip/src/cmd/compile/internal/base/print.go:196
cmd/compile/internal/gc.handlePanic()
	/usr/local/go.tip/src/cmd/compile/internal/gc/main.go:48 +0x85
panic({0xc79220, 0xc00010b410})
	/usr/local/go.tip/src/runtime/panic.go:838 +0x207
cmd/compile/internal/noder.(*reader).doTyp(0xc0000b9a20)
	/usr/local/go.tip/src/cmd/compile/internal/noder/reader.go:415 +0x2bd
cmd/compile/internal/noder.(*pkgReader).typIdx(0xc0000360c0, {0xc0005b6690?, 0xf2?}, 0xc000137c20, 0x1)
	/usr/local/go.tip/src/cmd/compile/internal/noder/reader.go:350 +0x171
cmd/compile/internal/noder.(*reader).typWrapped(0xc0000b98c0, 0x1?)
	/usr/local/go.tip/src/cmd/compile/internal/noder/reader.go:322 +0x45
cmd/compile/internal/noder.(*reader).typ(...)
	/usr/local/go.tip/src/cmd/compile/internal/noder/reader.go:316
cmd/compile/internal/noder.(*reader).interfaceType(0xc0000b98c0)
	/usr/local/go.tip/src/cmd/compile/internal/noder/reader.go:467 +0x285
cmd/compile/internal/noder.(*reader).doTyp(0xc0000b98c0)
	/usr/local/go.tip/src/cmd/compile/internal/noder/reader.go:445 +0x249
cmd/compile/internal/noder.(*pkgReader).typIdx(0xc0000360c0, {0xc0005b68d0?, 0xff?}, 0xc000137c20, 0x0)
	/usr/local/go.tip/src/cmd/compile/internal/noder/reader.go:350 +0x171
cmd/compile/internal/noder.(*reader).typWrapped(0xc0000b9600, 0xc0?)
	/usr/local/go.tip/src/cmd/compile/internal/noder/reader.go:322 +0x45
cmd/compile/internal/noder.(*pkgReader).objIdx(0xc0000360c0, 0x6?, {0x0, 0x0, 0x0}, {0x13afe60, 0x0, 0x0})
	/usr/local/go.tip/src/cmd/compile/internal/noder/reader.go:661 +0x5d2
cmd/compile/internal/noder.(*reader).obj(0xc0000b91e0)
	/usr/local/go.tip/src/cmd/compile/internal/noder/reader.go:564 +0x1ee
cmd/compile/internal/noder.(*reader).doTyp(0xc0000b91e0)
	/usr/local/go.tip/src/cmd/compile/internal/noder/reader.go:421 +0x59
cmd/compile/internal/noder.(*pkgReader).typIdx(0xc0000360c0, {0xc0000b9080?, 0xc0?}, 0xc000136140, 0x1)
	/usr/local/go.tip/src/cmd/compile/internal/noder/reader.go:350 +0x171
cmd/compile/internal/noder.(*reader).typWrapped(0xc0000b9080, 0x80?)
	/usr/local/go.tip/src/cmd/compile/internal/noder/reader.go:322 +0x45
cmd/compile/internal/noder.(*reader).typ(0x7fa308fb7d30?)
	/usr/local/go.tip/src/cmd/compile/internal/noder/reader.go:316 +0x1e
cmd/compile/internal/noder.(*reader).doTyp(0xc0000b9080)
	/usr/local/go.tip/src/cmd/compile/internal/noder/reader.go:437 +0x145
cmd/compile/internal/noder.(*pkgReader).typIdx(0xc0000360c0, {0xc000429a20?, 0x80?}, 0xc000136140, 0x1)
	/usr/local/go.tip/src/cmd/compile/internal/noder/reader.go:350 +0x171
cmd/compile/internal/noder.(*reader).typWrapped(0xc000429a20, 0x20?)
	/usr/local/go.tip/src/cmd/compile/internal/noder/reader.go:322 +0x45
cmd/compile/internal/noder.(*reader).typ(0x4eadc2?)
	/usr/local/go.tip/src/cmd/compile/internal/noder/reader.go:316 +0x1e
cmd/compile/internal/noder.(*reader).expr(0xc000429a20)
	/usr/local/go.tip/src/cmd/compile/internal/noder/reader.go:1668 +0xcb7
cmd/compile/internal/noder.(*reader).exprs(0xc000429a20)
	/usr/local/go.tip/src/cmd/compile/internal/noder/reader.go:1768 +0x8d
cmd/compile/internal/noder.(*reader).expr(0xc000429a20)
	/usr/local/go.tip/src/cmd/compile/internal/noder/reader.go:1663 +0xe85
cmd/compile/internal/noder.(*reader).expr(0xc000429a20)
	/usr/local/go.tip/src/cmd/compile/internal/noder/reader.go:1656 +0xd5b
cmd/compile/internal/noder.(*reader).exprs(0xc000429a20)
	/usr/local/go.tip/src/cmd/compile/internal/noder/reader.go:1768 +0x8d
cmd/compile/internal/noder.(*reader).exprList(0xc000429a20)
	/usr/local/go.tip/src/cmd/compile/internal/noder/reader.go:1758 +0x2f
cmd/compile/internal/noder.(*reader).stmt1(0xc000429a20?, 0x30?, 0xc0005b77e0)
	/usr/local/go.tip/src/cmd/compile/internal/noder/reader.go:1222 +0xba
cmd/compile/internal/noder.(*reader).stmts(0xc000429a20)
	/usr/local/go.tip/src/cmd/compile/internal/noder/reader.go:1199 +0xa5
cmd/compile/internal/noder.(*reader).funcBody.func1()
	/usr/local/go.tip/src/cmd/compile/internal/noder/reader.go:984 +0x52
cmd/compile/internal/ir.WithFunc(0x586?, 0xb7?)
	/usr/local/go.tip/src/cmd/compile/internal/ir/func.go:293 +0xab
cmd/compile/internal/noder.(*reader).funcBody(0xc000429a20, 0xc0004298c0)
	/usr/local/go.tip/src/cmd/compile/internal/noder/reader.go:977 +0xaf
cmd/compile/internal/noder.pkgReaderIndex.funcBody({0xc0000360c0?, 0xc00013f928?, 0xc000136140?}, 0xc000700000?)
	/usr/local/go.tip/src/cmd/compile/internal/noder/reader.go:970 +0x3c
cmd/compile/internal/noder.readBodies(0xc0001746c0)
	/usr/local/go.tip/src/cmd/compile/internal/noder/unified.go:150 +0xca
cmd/compile/internal/noder.unified({0xc00011c430?, 0x0?, 0x2?})
	/usr/local/go.tip/src/cmd/compile/internal/noder/unified.go:119 +0x42a
cmd/compile/internal/noder.LoadPackage({0xc000124100, 0x1, 0x0?})
	/usr/local/go.tip/src/cmd/compile/internal/noder/noder.go:73 +0x2b4
cmd/compile/internal/gc.Main(0xd398b0)
	/usr/local/go.tip/src/cmd/compile/internal/gc/main.go:190 +0xb13
main.main()
	/usr/local/go.tip/src/cmd/compile/main.go:55 +0xdd
```

**Comment by griesemer** [comment]
Simpler reproducer:
```Go
var _ = (*interface{int})(nil)
```
should not be permitted.
