### ISSUE TITLE
cmd/compile/internal/test: timeouts in TestIntendedInlining

### ISSUE THREAD

**Issue by bcmills** [golang/go#52081]
```
goroutine 321 [syscall, 2 minutes]:
runtime.syscall_wait4(0x1c96, 0xc0004c8010, 0x0, 0xc001148090)
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/runtime/syscall_solaris.go:294 +0x86 fp=0xc000738e60 sp=0xc000738e08 pc=0x464ee6
syscall.Wait4(0x49634d?, 0x7fffbf523d68?, 0x0?, 0xc00038cd00?)
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/syscall/syscall_solaris.go:250 +0x2c fp=0xc000738ea8 sp=0xc000738e60 pc=0x47468c
os.(*Process).wait(0xc0000aa060)
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/os/exec_unix.go:43 +0x85 fp=0xc000738f00 sp=0xc000738ea8 pc=0x49efa5
os.(*Process).Wait(...)
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/os/exec.go:132
os/exec.(*Cmd).Wait(0xc0010b8c60)
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/os/exec/exec.go:507 +0x54 fp=0xc000738f78 sp=0xc000738f00 pc=0x533c74
os/exec.(*Cmd).Run(0xc00075c820?)
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/os/exec/exec.go:341 +0x39 fp=0xc000738f98 sp=0xc000738f78 pc=0x532dd9
cmd/compile/internal/test.TestIntendedInlining.func1()
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/cmd/compile/internal/test/inl_test.go:228 +0x2f fp=0xc000738fe0 sp=0xc000738f98 pc=0x779aef
runtime.goexit()
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000738fe8 sp=0xc000738fe0 pc=0x468261
created by cmd/compile/internal/test.TestIntendedInlining
	/tmp/workdir-host-solaris-oracle-amd64-oraclerel/go/src/cmd/compile/internal/test/inl_test.go:227 +0x1445
```

`greplogs --dashboard -md -l -e 'panic: test timed out(?:.*\n)*^goroutine \d+ \[syscall, \d+ minutes\]:\n(.+\n\t.+\n)*cmd/compile/internal/test\.TestIntendedInlining'`

[2022-03-31T12:55:38-821420d/solaris-amd64-oraclerel](https://build.golang.org/log/aee0dbd68fa5903845700c97c0c9e1db9bc111d9)
[2021-04-29T16:31:18-5a8435d/freebsd-amd64-race](https://build.golang.org/log/a631fe316e561ff5cac1f784a60fa9e339098f27)
[2021-04-23T21:43:06-e5a6c52/freebsd-386-11_4](https://build.golang.org/log/1e5a5aef24ebdcdc72fedc4c076052b546952778)

(CC @mvdan)

**Comment by bcmills** [comment]
This test is normally skipped in short mode, but for some reason not on the Go builders:
https://cs.opensource.google/go/go/+/master:src/cmd/compile/internal/test/inl_test.go;l=23-25;drc=4a37a1d49fd472665b59b581fe6563a9e578fd71

Maybe we should just drop the builder-specific part of that condition? 🤔

**Comment by bcmills** [comment]
`greplogs --dashboard -md -l -e 'panic: test timed out(?:.*\n)*^goroutine \d+ \[syscall, \d+ minutes\]:\n(.+\n\t.+\n)*cmd/compile/internal/test\.TestIntendedInlining' --since=2022-03-31`

[2022-03-31T12:55:38-821420d/solaris-amd64-oraclerel](https://build.golang.org/log/aee0dbd68fa5903845700c97c0c9e1db9bc111d9)
