### ISSUE TITLE
net: hang in Netsh tests on windows-arm64-10

### ISSUE THREAD

**Issue by bcmills** [golang/go#52082]
```
goroutine 49 [syscall, 2 minutes, locked to thread]:
runtime.cgocall(0x7ff727ba62e0, 0x40000802c0)
	C:/workdir/go/src/runtime/cgocall.go:157 +0x44 fp=0x40001e97e0 sp=0x40001e97a0 pc=0x7ff727b43514
syscall.SyscallN(0x7ffeb9adf280?, {0x40001e9890?, 0x3?, 0x0?})
	C:/workdir/go/src/runtime/syscall_windows.go:538 +0xec fp=0x40001e9860 sp=0x40001e97e0 pc=0x7ff727ba27bc
syscall.Syscall(0xa?, 0x40000b6205?, 0x40001e9998?, 0x7ff727b4bca4?, 0x39?)
	C:/workdir/go/src/runtime/syscall_windows.go:476 +0x30 fp=0x40001e98b0 sp=0x40001e9860 pc=0x7ff727ba25a0
syscall.WaitForSingleObject(0x40000b6640?, 0xffffffff)
	C:/workdir/go/src/syscall/zsyscall_windows.go:1145 +0x64 fp=0x40001e9900 sp=0x40001e98b0 pc=0x7ff727bb8fb4
os.(*Process).wait(0x40000db590)
	C:/workdir/go/src/os/exec_windows.go:18 +0x50 fp=0x40001e99a0 sp=0x40001e9900 pc=0x7ff727bdef10
os.(*Process).Wait(...)
	C:/workdir/go/src/os/exec.go:132
os/exec.(*Cmd).Wait(0x40000e2000)
	C:/workdir/go/src/os/exec/exec.go:507 +0x44 fp=0x40001e9a20 sp=0x40001e99a0 pc=0x7ff727c2d054
os/exec.(*Cmd).Run(0x3?)
	C:/workdir/go/src/os/exec/exec.go:341 +0x38 fp=0x40001e9a40 sp=0x40001e9a20 pc=0x7ff727c2c0d8
os/exec.(*Cmd).CombinedOutput(0x40000e2000)
	C:/workdir/go/src/os/exec/exec.go:567 +0xb8 fp=0x40001e9a70 sp=0x40001e9a40 pc=0x7ff727c2d378
net.runCmd({0x40001e9c88?, 0x2, 0x2})
	C:/workdir/go/src/net/net_windows_test.go:185 +0x180 fp=0x40001e9bc0 sp=0x40001e9a70 pc=0x7ff727cd4510
net.checkNetsh(0x40000b4680)
	C:/workdir/go/src/net/net_windows_test.go:208 +0x60 fp=0x40001e9cb0 sp=0x40001e9bc0 pc=0x7ff727cd4ab0
net.TestInterfaceAddrsWithNetsh(0x40000b4680)
	C:/workdir/go/src/net/net_windows_test.go:433 +0x28 fp=0x40001e9f60 sp=0x40001e9cb0 pc=0x7ff727cd6108
testing.tRunner(0x40000b4680, 0x7ff727d7ae78)
	C:/workdir/go/src/testing/testing.go:1439 +0x10c fp=0x40001e9fb0 sp=0x40001e9f60 pc=0x7ff727c22bbc
testing.(*T).Run.func1()
	C:/workdir/go/src/testing/testing.go:1486 +0x2c fp=0x40001e9fd0 sp=0x40001e9fb0 pc=0x7ff727c2390c
runtime.goexit()
	C:/workdir/go/src/runtime/asm_arm64.s:1151 +0x4 fp=0x40001e9fd0 sp=0x40001e9fd0 pc=0x7ff727ba5754
created by testing.(*T).Run
	C:/workdir/go/src/testing/testing.go:1486 +0x328
```

`greplogs --dashboard -md -l -e 'goroutine \d+ \[syscall, \d+ minutes.*\]:\n(?:.+\n\t.+\n)*net\.TestInterfaceAddrs'`

[2022-03-31T04:40:46-3943d97/windows-arm64-10](https://build.golang.org/log/5a650e5d333fb12c09d3bb2a6c4917a51710e3b4)
[2021-10-25T17:18:40-bc0eb57/windows-arm64-10](https://build.golang.org/log/318a2f4a4bc4172c294e71b5c04f647800872a38)
[2021-10-09T23:29:26-b99abf3/windows-arm64-10](https://build.golang.org/log/588b329358eecf6fb2519d7efdaebadcda4d42bb)
[2021-06-09T15:44:42-e6dda19/windows-arm64-aws](https://build.golang.org/log/f1c5b96f98a357b6b56a5d95e0d500608ff0a67d)
[2021-06-08T20:19:17-da4a640/windows-arm64-aws](https://build.golang.org/log/40550ec85d63dd21f97e818b6028dc0f7509e7a8)

**Comment by bcmills** [comment]
Marking as release-blocker because this is an ongoing source of failures on the builders.

Since `windows/arm64` is not a [first class port](https://go.dev/wiki/PortingPolicy#first-class-ports) — and especially since hasn't failed yet on the `windows-arm64-11` builder (and kind of looks to me like a platform bug) — I suggest that we skip this test on the `windows-arm64-10` builder and see whether it ever recurs on Windows 11.

**Comment by bcmills** [comment]
Widening the regexp a bit to catch related tests:

`greplogs --dashboard -md -l -e 'goroutine \d+ \[syscall, \d+ minutes.*\]:\n(?:.+\n\t.+\n)*net\.Test.*Netsh'`

[2022-03-31T04:40:46-3943d97/windows-arm64-10](https://build.golang.org/log/5a650e5d333fb12c09d3bb2a6c4917a51710e3b4)
[2021-10-25T17:18:40-bc0eb57/windows-arm64-10](https://build.golang.org/log/318a2f4a4bc4172c294e71b5c04f647800872a38)
[2021-10-13T18:15:48-40f82f8/windows-arm64-10](https://build.golang.org/log/2679560bee7e20baf48820a7136349a22b947064)
[2021-10-11T12:42:06-59b2f51/windows-arm64-10](https://build.golang.org/log/81c61ee9c5745ccf8ca0771a579394ca1f676394)
[2021-10-09T23:29:26-b99abf3/windows-arm64-10](https://build.golang.org/log/588b329358eecf6fb2519d7efdaebadcda4d42bb)
[2021-09-09T01:07:21-42563f8/windows-arm64-10](https://build.golang.org/log/f4fa6c70061921e4bef658a15953062ccd15c8a6)
[2021-06-29T16:57:13-3463852/windows-arm64-aws](https://build.golang.org/log/06efa45cd16d3b11e9fe8faac8d9123dd48d55e4)
[2021-06-24T03:20:33-86d72fa/windows-arm64-aws](https://build.golang.org/log/88468dab19622c5a8457e1b881d0bdf0321ef74f)
[2021-06-09T15:44:42-e6dda19/windows-arm64-aws](https://build.golang.org/log/f1c5b96f98a357b6b56a5d95e0d500608ff0a67d)
[2021-06-08T20:19:17-da4a640/windows-arm64-aws](https://build.golang.org/log/40550ec85d63dd21f97e818b6028dc0f7509e7a8)
[2021-06-04T09:39:32-0214440/windows-arm64-aws](https://build.golang.org/log/114dd7cb01f6dff2b45a65de548a8c32fddfe597)
