### ISSUE TITLE
x/vuln/vulncheck/internal/gosym: panic in TestLineFromAline on release-branch.go1.17 on 32-bit platforms

### ISSUE THREAD

**Issue by bcmills** [golang/go#52218]
```
--- FAIL: TestLineFromAline (0.00s)
panic: runtime error: slice bounds out of range [76:68] [recovered]
	panic: runtime error: slice bounds out of range [76:68]

goroutine 20 [running]:
testing.tRunner.func1.2({0x81b3d60, 0xa176680})
	/workdir/go/src/testing/testing.go:1209 +0x2ab
testing.tRunner.func1(0xa0825a0)
	/workdir/go/src/testing/testing.go:1212 +0x27d
panic({0x81b3d60, 0xa176680})
	/workdir/go/src/runtime/panic.go:1038 +0x1c5
golang.org/x/vuln/vulncheck/internal/gosym.funcData.funcdataOffset({0xa0a60a0, {0xa240480, 0x44, 0x44}}, 0x3)
	/workdir/gopath/src/golang.org/x/vuln/vulncheck/internal/gosym/pclntab.go:584 +0x127
golang.org/x/vuln/vulncheck/internal/gosym.(*LineTable).go12Funcs(0xa0a60a0)
	/workdir/gopath/src/golang.org/x/vuln/vulncheck/internal/gosym/pclntab.go:373 +0x1f6
golang.org/x/vuln/vulncheck/internal/gosym.NewTable({0x82ebda0, 0x0, 0x0}, 0xa0a60a0)
	/workdir/gopath/src/golang.org/x/vuln/vulncheck/internal/gosym/symtab.go:519 +0x5f1
golang.org/x/vuln/vulncheck/internal/gosym.parse({0xffb79ccc, 0x2f}, 0xa0f6180, 0xa0825a0)
	/workdir/gopath/src/golang.org/x/vuln/vulncheck/internal/gosym/pclntab_test.go:82 +0x3d7
golang.org/x/vuln/vulncheck/internal/gosym.crack({0xffb79ccc, 0x2f}, 0xa0825a0)
	/workdir/gopath/src/golang.org/x/vuln/vulncheck/internal/gosym/pclntab_test.go:62 +0xae
golang.org/x/vuln/vulncheck/internal/gosym.getTable(0xa0825a0)
	/workdir/gopath/src/golang.org/x/vuln/vulncheck/internal/gosym/pclntab_test.go:51 +0x42
golang.org/x/vuln/vulncheck/internal/gosym.TestLineFromAline(0xa0825a0)
	/workdir/gopath/src/golang.org/x/vuln/vulncheck/internal/gosym/pclntab_test.go:94 +0x32
testing.tRunner(0xa0825a0, 0x81cd5d0)
	/workdir/go/src/testing/testing.go:1259 +0xe6
created by testing.(*T).Run
	/workdir/go/src/testing/testing.go:1306 +0x33a
FAIL	golang.org/x/vuln/vulncheck/internal/gosym	0.009s
FAIL
```

`greplogs --dashboard -md -l -e 'FAIL: TestLineFromAline .*(?:\n.*)*panic: runtime error: slice bounds out of range' --since=2022-01-01`

[2022-04-07T17:51:26-1784cc9-7139e8b/freebsd-386-11_4](https://build.golang.org/log/e9a033b9f1d82b3635cc51b6092ced37b9d355df)
[2022-04-07T17:51:26-1784cc9-7139e8b/freebsd-386-12_3](https://build.golang.org/log/d8afcf92f18031913ad02df336528516e9b073fa)
[2022-04-07T17:51:26-1784cc9-7139e8b/freebsd-386-13_0](https://build.golang.org/log/b17ffc8f0244c3a4d21629ac45122a040754249a)
[2022-04-07T17:51:26-1784cc9-7139e8b/linux-386](https://build.golang.org/log/10daddd852cbe45d39bb7a89eee7a74277c4db8b)
[2022-04-07T17:51:26-1784cc9-7139e8b/linux-386-buster](https://build.golang.org/log/0c78b61c0c549813f99833d5068224b69827a583)
[2022-04-07T17:51:26-1784cc9-7139e8b/linux-386-clang](https://build.golang.org/log/b394eb4f008e76aa66b4ed02879a47d88fc76479)
[2022-04-07T17:51:26-1784cc9-7139e8b/linux-386-sid](https://build.golang.org/log/e5a09c27f702b894e92f07b18206de67b7da9119)
[2022-04-07T17:51:26-1784cc9-7139e8b/linux-386-stretch](https://build.golang.org/log/90b5fe64b959b46d0bdaf14910801928382670a0)
[2022-04-07T17:51:26-1784cc9-7139e8b/linux-arm-aws](https://build.golang.org/log/c2cffe0fc860a789560fc3c14c5ae9b7e02be978)
[2022-04-07T17:51:26-1784cc9-7139e8b/netbsd-386-9_0](https://build.golang.org/log/6fad0738c1373a119e4e1c61fad1af1ab9107456)
[2022-04-07T17:51:26-1784cc9-7139e8b/openbsd-386-68](https://build.golang.org/log/9b827f1d8d0d59727bbbe0fa261dbf05a0061110)
[2022-04-07T17:51:26-1784cc9-7139e8b/openbsd-386-70](https://build.golang.org/log/ee69cd7646aedee74a7228c18db2a50d243619fd)

This failure mode appears to have been introduced in [CL 398755](https://go.dev/cl/398755) (attn @jba; CC @golang/security). It isn't obvious to me why it wasn't caught by the TryBots for that CL.

**Comment by bcmills** [comment]
This is nominally a release-blocker for Go 1.17.9 via #11811, but since it appears to have been introduced by an `x/vuln` commit I think it would be reasonable to cut the planned security release even if it is not addressed by then.

(That said, since the security release is now planned for Tuesday I don't see why it would be an issue to fix by then.)
