### ISSUE TITLE
affected/runtime: go generic assert compile escape

### ISSUE THREAD

**Issue by elvizlai** [golang/go#52228]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 darwin/amd64
same behavior on linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/elvizlai/Library/Caches/go-build"
GOENV="/Users/elvizlai/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/elvizlai/.godeps/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/elvizlai/.godeps"
GOPRIVATE=""
GOPROXY="https://goproxy.cn|https://goproxy.io|https://goproxy.baidu.com/|https://mirrors.tencent.com/go/|direct"
GOROOT="/Users/elvizlai/.g/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/elvizlai/.g/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/elvizlai/temp/go-issue/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hs/cwct781947971m14gv8vm8s00000gn/T/go-build695014846=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
go run main.go

```
package main

type SomeInterface interface {
	Whatever()
}

func X[T any]() T {
	var m T

	// for this example, this block should never run
	if _, ok := any(m).(SomeInterface); ok {
		var dst SomeInterface
		_, _ = dst.(T) // remove this works fine
		return dst.(T)
	}

	return m
}

type holder struct{}

func main() {
	X[holder]()
}

```

### What did you expect to see?
run then exist 0

### What did you see instead?
```
panic: interface conversion: main.SomeInterface is nil, not main.holder

goroutine 1 [running]:
main.X[...](...)
	/Users/elvizlai/temp/go-issue/main.go:14
main.main()
	/Users/elvizlai/temp/go-issue/main.go:23 +0x65
exit status 2
```

**Comment by mengzhuo** [comment]
cc @griesemer

**Comment by elvizlai** [comment]
maybe a helpful tricks in X func: wrap dst with any(dst) can “fix” panic.

**Comment by wdvxdr1123** [comment]
may related with #51700, I noticed they both failed with two type assert.

**Comment by ianlancetaylor** [comment]
@gopherbot Please open backport to 1.18

This is valid code that is being compiled incorrectly.

**Comment by ianlancetaylor** [comment]
CC @randall77 @mdempsky
