### ISSUE TITLE
reflect: can set map elem with string key of a different string type

### ISSUE THREAD

**Issue by kortschak** [golang/go#52379]
Original report [here](https://groups.google.com/g/golang-nuts/c/GhfT2tr4Zso/m/ummu2Pj9AgAJ).

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/home/user/bin"
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/user/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/user/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/user/go/src/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2354676463=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Run https://go.dev/play/p/b7kheLRQpLL on go1.18

### What did you expect to see?

Something like this
```
panic: reflect.Value.SetMapIndex: value of type string is not assignable to type main.CustomString

goroutine 1 [running]:
reflect.Value.assignTo({0x4701c0, 0xc000010050, 0x7f34d3c33108}, {0x47f0b5, 0x19}, 0x46fd40, 0x0)
	/usr/local/go-faketime/src/reflect/value.go:2810 +0x2ad
reflect.Value.SetMapIndex({0x472460, 0xc000012120, 0x0}, {0x4701c0, 0xc000010050, 0x98}, {0x46fb40, 0x494e88, 0x82})
	/usr/local/go-faketime/src/reflect/value.go:2045 +0xf6
main.main()
	/tmp/sandbox3220972237/prog.go:9 +0x218

Program exited.
```

### What did you see instead?

```
Program exited.
```

### Additional information

The same behaviour not-surprisingly exists for map access (https://go.dev/play/p/3KtoQGNVvgR).

Bisected to
```
23832ba2e2fb396cda1dacf3e8afcb38ec36dcba is the first bad commit
commit 23832ba2e2fb396cda1dacf3e8afcb38ec36dcba
Author: Joe Tsai <joetsai@digital-static.net>
Date:   Thu Aug 26 19:13:22 2021 -0700

    reflect: optimize for maps with string keys
    
    Over 80% of all Go map types use a string as the key.
    The Go runtime already has a specialized implementation for such maps
    in runtime/map_faststr.go. However, the Go reflection implementation
    has not historically made use of that implementation.
    
    This CL plumbs the appropriate logic to be accessible from Go reflection
    so that it can benefit as well.
    
        name                            old time/op    new time/op    delta
        Map/StringKeys/MapIndex-4       4.65us ± 5%    2.95us ± 3%  -36.50%  (p=0.016 n=4+5)
        Map/StringKeys/SetMapIndex-4    7.47us ± 5%    5.27us ± 2%  -29.40%  (p=0.008 n=5+5)
        Map/Uint64Keys/MapIndex-4       3.79us ± 3%    3.75us ± 2%     ~     (p=0.548 n=5+5)
        Map/Uint64Keys/SetMapIndex-4    6.13us ± 3%    6.09us ± 1%     ~     (p=0.746 n=5+5)
    
    Change-Id: I5495d48948d8caf2d004a03ae1820ab5f8729670
    Reviewed-on: https://go-review.googlesource.com/c/go/+/345486
    Trust: Joe Tsai <joetsai@digital-static.net>
    Run-TryBot: Joe Tsai <joetsai@digital-static.net>
    TryBot-Result: Go Bot <gobot@golang.org>
    Reviewed-by: Keith Randall <khr@golang.org>

:040000 040000 bcb02e8bffb89cc2119b282573cc327ac59a8b34 ef1bf8cdefa674b136a3360601c8985b915b4582 M	src
```

It looks like this change does not include a check for assignability.

**Comment by kortschak** [comment]
The obvious change of re-adding the `assignTo` call but retaining the other changes doesn't completely wipe out the gains from the previous change.

```diff
diff --git a/src/reflect/value.go b/src/reflect/value.go
index dcc359dae4..f4aeb1d6ca 100644
--- a/src/reflect/value.go
+++ b/src/reflect/value.go
@@ -1598,13 +1598,13 @@ func (v Value) MapIndex(key Value) Value {
        // considered unexported. This is consistent with the
        // behavior for structs, which allow read but not write
        // of unexported fields.
+       key = key.assignTo("reflect.Value.MapIndex", tt.key, nil)
 
        var e unsafe.Pointer
-       if key.kind() == String && tt.key.Kind() == String && tt.elem.size <= maxValSize {
+       if key.kind() == String && tt.elem.size <= maxValSize {
                k := *(*string)(key.ptr)
                e = mapaccess_faststr(v.typ, v.pointer(), k)
        } else {
-               key = key.assignTo("reflect.Value.MapIndex", tt.key, nil)
                var k unsafe.Pointer
                if key.flag&flagIndir != 0 {
                        k = key.ptr
@@ -2213,7 +2213,8 @@ func (v Value) SetMapIndex(key, elem Value) {
        key.mustBeExported()
        tt := (*mapType)(unsafe.Pointer(v.typ))
 
-       if key.kind() == String && tt.key.Kind() == String && tt.elem.size <= maxValSize {
+       key = key.assignTo("reflect.Value.SetMapIndex", tt.key, nil)
+       if key.kind() == String && tt.elem.size <= maxValSize {
                k := *(*string)(key.ptr)
                if elem.typ == nil {
                        mapdelete_faststr(v.typ, v.pointer(), k)
@@ -2231,7 +2232,6 @@ func (v Value) SetMapIndex(key, elem Value) {
                return
        }
 
-       key = key.assignTo("reflect.Value.SetMapIndex", tt.key, nil)
        var k unsafe.Pointer
        if key.flag&flagIndir != 0 {
                k = key.ptr
```

```
name                          old time/op    new time/op    delta
Map/StringKeys/MapIndex-8       3.35µs ± 1%    4.23µs ± 2%  +26.16%  (p=0.000 n=9+9)
Map/StringKeys/SetMapIndex-8    6.32µs ± 2%    7.39µs ± 5%  +16.91%  (p=0.000 n=10+10)
Map/Uint64Keys/MapIndex-8       4.55µs ± 1%    4.51µs ± 1%   -0.82%  (p=0.025 n=10+10)
Map/Uint64Keys/SetMapIndex-8    7.27µs ± 1%    6.93µs ± 3%   -4.73%  (p=0.000 n=10+10)
MapIterNext-8                    138ns ± 1%     142ns ±10%     ~     (p=1.000 n=10+10)
```

I'm happy to send this change unless there are better options.

**Comment by ianlancetaylor** [comment]
@gopherbot Please open backport to 1.18.

The reflect package incorrectly accepts this case.  This should be fixed so that we don't have programs that work with the current release and fail with the next release.

Earlier releases correctly panic.

**Comment by kortschak** [comment]
No worries. Happy to do that.
