### ISSUE TITLE
x/vulndb/internal/worker: test failing since CL 382994

### ISSUE THREAD

**Issue by bcmills** [golang/go#52626]
```
panic: no concrete method: func (*crypto/elliptic.nistCurve[*crypto/elliptic/internal/nistec.P224Point]).Add(x1 *math/big.Int, y1 *math/big.Int, x2 *math/big.Int, y2 *math/big.Int) (*math/big.Int, *math/big.Int)

goroutine 2270 [running]:
golang.org/x/tools/go/ssa.(*Program).declaredFunc(0xc0004b28f0, 0xc012700c30)
	/workdir/gopath/pkg/mod/golang.org/x/tools@v0.1.8/go/ssa/methods.go:124 +0xf9
golang.org/x/tools/go/ssa.(*Program).addMethod(0x11c0f70?, 0xc00f976a50, 0xc00e3b6cd0)
	/workdir/gopath/pkg/mod/golang.org/x/tools@v0.1.8/go/ssa/methods.go:86 +0x14a
golang.org/x/tools/go/ssa.(*Program).needMethods(0xc0004b28f0, {0x11c0f70?, 0xc012237a10?}, 0x0)
	/workdir/gopath/pkg/mod/golang.org/x/tools@v0.1.8/go/ssa/methods.go:173 +0x785
golang.org/x/tools/go/ssa.(*Program).needMethodsOf(0xc0004b28f0, {0x11c0f70?, 0xc012237a10?})
	/workdir/gopath/pkg/mod/golang.org/x/tools@v0.1.8/go/ssa/methods.go:145 +0x70
golang.org/x/tools/go/ssa.emitConv(0xc00ba7a000, {0x11c8c58, 0xc00e72eae0}, {0x11c0f48?, 0xc000678e00})
	/workdir/gopath/pkg/mod/golang.org/x/tools@v0.1.8/go/ssa/emit.go:210 +0x405
golang.org/x/tools/go/ssa.(*builder).stmt(0x0?, 0xc00ba7a000, {0x11c3f70?, 0xc011fffc40?})
	/workdir/gopath/pkg/mod/golang.org/x/tools@v0.1.8/go/ssa/builder.go:2054 +0x1fa8
golang.org/x/tools/go/ssa.(*builder).stmtList(0xc00e3fc840?, 0x0?, {0xc011fffc60?, 0x2, 0xc00da7b940?})
	/workdir/gopath/pkg/mod/golang.org/x/tools@v0.1.8/go/ssa/builder.go:796 +0x67
golang.org/x/tools/go/ssa.(*builder).stmt(0xc00ba7a000?, 0xc00ba7a000, {0x11c39d0?, 0xc0121004b0?})
	/workdir/gopath/pkg/mod/golang.org/x/tools@v0.1.8/go/ssa/builder.go:2111 +0x1391
golang.org/x/tools/go/ssa.(*builder).buildFunction(0xe82080?, 0xc00ba7a000)
	/workdir/gopath/pkg/mod/golang.org/x/tools@v0.1.8/go/ssa/builder.go:2204 +0x47a
golang.org/x/tools/go/ssa.(*builder).buildFuncDecl(0xe82080?, 0xc00f4d81e0, 0xc0121004e0)
	/workdir/gopath/pkg/mod/golang.org/x/tools@v0.1.8/go/ssa/builder.go:2234 +0x154
golang.org/x/tools/go/ssa.(*Package).build(0xc00f4d81e0)
	/workdir/gopath/pkg/mod/golang.org/x/tools@v0.1.8/go/ssa/builder.go:2350 +0xd25
sync.(*Once).doSlow(0xc001be9830?, 0xc001bf1248?)
	/workdir/go/src/sync/once.go:70 +0xc2
sync.(*Once).Do(...)
	/workdir/go/src/sync/once.go:61
golang.org/x/tools/go/ssa.(*Package).Build(...)
	/workdir/gopath/pkg/mod/golang.org/x/tools@v0.1.8/go/ssa/builder.go:2269
golang.org/x/tools/go/ssa.(*Program).Build.func1(0x0?)
	/workdir/gopath/pkg/mod/golang.org/x/tools@v0.1.8/go/ssa/builder.go:2253 +0x4c
created by golang.org/x/tools/go/ssa.(*Program).Build
	/workdir/gopath/pkg/mod/golang.org/x/tools@v0.1.8/go/ssa/builder.go:2252 +0x19c
FAIL	golang.org/x/vulndb/internal/worker	2.942s
```

`greplogs --dashboard -md -l -e 'panic: no concrete method: func \(\*crypto/elliptic\.nistCurve' --since=2022-01-01`

[2022-04-29T20:16:31-4bd1791-3ce203d/linux-amd64](https://build.golang.org/log/e42c7f1cd4d7933dc2f7f6e4f4905fc661b6eeab)
[2022-04-29T20:16:31-4bd1791-3ce203d/linux-amd64-longtest](https://build.golang.org/log/08edb6e60f4797709997c8abad55980cb604a4ef)
[2022-04-29T18:35:07-4bd1791-8c5917c/linux-amd64](https://build.golang.org/log/014f9c19648def1d90301a738eb1d444fe430403)
[2022-04-29T18:35:07-4bd1791-8c5917c/linux-amd64-longtest](https://build.golang.org/log/96f05372fcdb5ce71dd2ce8effa32229bd7faef1)
[2022-04-29T02:01:27-4bd1791-e7c56fe/linux-amd64](https://build.golang.org/log/3615c42353b0e2db232bedfda1dd019e339dbcbe)
[2022-04-29T02:01:27-4bd1791-e7c56fe/linux-amd64-longtest](https://build.golang.org/log/a367005f47262fef186472724be68bf49744921a)
[2022-04-29T01:45:33-4bd1791-a5dd684/linux-amd64](https://build.golang.org/log/6dfde623eb6b91286c53c46b10d78f2c7f66f71e)
[2022-04-29T01:45:33-4bd1791-a5dd684/linux-amd64-longtest](https://build.golang.org/log/633a940a371118b348246e147534a9d72b4b90ce)
[2022-04-29T01:00:55-4bd1791-e7b0559/linux-amd64](https://build.golang.org/log/cff937e750112235102e878657fe42016ba144be)
[2022-04-29T01:00:55-4bd1791-e7b0559/linux-amd64-longtest](https://build.golang.org/log/ff23cb5a2c01fbb252328932552125e2bd4b9284)
[2022-04-28T23:35:11-4bd1791-cb6fc99/linux-amd64](https://build.golang.org/log/04f3b835575c2ef19553a30046bb51bc8c480e4c)
[2022-04-28T23:35:11-4bd1791-cb6fc99/linux-amd64-longtest](https://build.golang.org/log/95abf9546f30edd34ee3275852682010ed15a021)
[2022-04-28T23:16:44-682b022-cb6fc99/linux-amd64](https://build.golang.org/log/59d2cd85edc2ce0845e2e062332701c92c733946)
[2022-04-28T23:16:44-682b022-cb6fc99/linux-amd64-longtest](https://build.golang.org/log/ba0dfa21d40a2d6bb9a18bd4d001cd07afdc3269)
[2022-04-28T20:14:34-682b022-c90a19a/linux-amd64](https://build.golang.org/log/8ec07fb1ae274f0eaf81736b3dd8df3903094ea3)
[2022-04-28T20:14:34-682b022-c90a19a/linux-amd64-longtest](https://build.golang.org/log/0574ada184e9a188c115f6d1f3cdb1bb6be713e9)
[2022-04-28T20:11:37-682b022-74f0009/linux-amd64](https://build.golang.org/log/0fee1f815938e5f8b36ba6e93eced2fb811c1b83)
[2022-04-28T20:11:37-682b022-74f0009/linux-amd64-longtest](https://build.golang.org/log/2fdfaa8045913ae172570a6f0bb8cf369c2f70ac)
[2022-04-28T18:41:25-682b022-96a1ad2/linux-amd64](https://build.golang.org/log/a16496ff10821ebc39fda1af1e6a0066661c67c5)
[2022-04-28T18:41:25-682b022-96a1ad2/linux-amd64-longtest](https://build.golang.org/log/83a20bcb737c149846add6977f7fbe6219cf3d2a)
[2022-04-28T18:28:44-682b022-123e271/linux-amd64](https://build.golang.org/log/bcc4f95b269cbe7ec876e7ef134967e927da8be6)
[2022-04-28T18:28:44-682b022-123e271/linux-amd64-longtest](https://build.golang.org/log/586c58a7325b83a8d97a08f87b79639ae6be7f53)
[2022-04-28T18:02:40-682b022-c15d0a9/linux-amd64](https://build.golang.org/log/2c3f15a00ff420131bf309c32fc5f9e0feb69675)
[2022-04-28T18:02:40-682b022-c15d0a9/linux-amd64-longtest](https://build.golang.org/log/e6b1c4b28f3fb5ebaaf0ac5f2263f45a3043ed77)
[2022-04-28T17:14:41-682b022-4289bd3/linux-amd64](https://build.golang.org/log/a2ab724fca059670f3ec84c48757aacff23cb761)
[2022-04-28T17:14:41-682b022-4289bd3/linux-amd64-longtest](https://build.golang.org/log/0492820a241ff8d958df407390b3b6d0ea41763c)
[2022-04-28T16:50:31-682b022-29bbca5/linux-amd64](https://build.golang.org/log/c9f13ec527186b48f8035bcab3f97428f2572cee)
[2022-04-28T16:50:31-682b022-29bbca5/linux-amd64-longtest](https://build.golang.org/log/382a0be2b6d496933172f9c9ee833b69e6f6ed44)
[2022-04-28T16:29:07-682b022-4bb45f7/linux-amd64](https://build.golang.org/log/93c21e8433599e54528c5ab662ee9d05ab7cb63c)
[2022-04-28T16:29:07-682b022-4bb45f7/linux-amd64-longtest](https://build.golang.org/log/4d0488dba7f87d9bd589436455a8af968115b6a7)
[2022-04-28T16:00:39-682b022-17371ee/linux-amd64](https://build.golang.org/log/632613534bdab66007f20d549e9cc658a650e836)
[2022-04-28T16:00:39-682b022-17371ee/linux-amd64-longtest](https://build.golang.org/log/3dba92ff6a9f91f6301246c594db7715a601964a)
[2022-04-28T15:11:42-682b022-4d35071/linux-amd64](https://build.golang.org/log/df27732fa26e00a48a6acf5efb7458523a11c753)
[2022-04-28T15:11:42-682b022-4d35071/linux-amd64-longtest](https://build.golang.org/log/46ff4f093b4d8a9b04e91abf5148baecd5d40416)
[2022-04-27T21:19:21-682b022-89044b6/linux-amd64](https://build.golang.org/log/d248313116ad756d0fe782aa51c73094dec8517a)
[2022-04-27T21:19:21-682b022-89044b6/linux-amd64-longtest](https://build.golang.org/log/9cc3d56b1b295b8b0ea6f7d22fd2fba03f561afd)
[2022-04-27T17:24:48-421e78b-89044b6/linux-amd64](https://build.golang.org/log/d276d91bfd31d82c95927fc3260b987b21121e66)
[2022-04-27T17:24:48-421e78b-89044b6/linux-amd64-longtest](https://build.golang.org/log/c2a7f6f8b6d0bd72fb61ff04fd8b1813f7dc0d96)
[2022-04-27T17:20:34-421e78b-f0ee7fd/linux-amd64-longtest](https://build.golang.org/log/fdcd52021b22fb915f5875e478ff92279f81f89f)
[2022-04-27T15:22:15-421e78b-0b5218c/linux-amd64](https://build.golang.org/log/a4198585ac9dd6c109c2a3ddc1d3dc47597d3fff)
[2022-04-27T15:22:15-421e78b-0b5218c/linux-amd64-longtest](https://build.golang.org/log/7534a504c5acc621baadf831f06182c7d854533a)
[2022-04-27T14:23:28-421e78b-f0c0e0f/linux-amd64](https://build.golang.org/log/bc0efce97353c5213d6e98de20a8c5b4db1991c1)
[2022-04-27T14:23:28-421e78b-f0c0e0f/linux-amd64-longtest](https://build.golang.org/log/585a48ec1fb8a895592ef80807761bce76cb224a)

**Comment by bcmills** [comment]
(attn @jba; CC @golang/security)

**Comment by bcmills** [comment]
(This is a release-blocker for Go 1.19 via #11811.)

**Comment by jba** [comment]
https://go.dev/cl/402674 should fix.

**Comment by dmitshur** [comment]
https://build.golang.org/?repo=golang.org%2fx%2fvulndb shows the fix is effective, thanks, closing.
