### ISSUE TITLE
x/net/http2: apparent deadlock in TestTransportResponseHeaderTimeout_Body on windows-386-2008

### ISSUE THREAD

**Issue by bcmills** [golang/go#52655]
```
panic: test timed out after 10m0s
…
goroutine 10660 [semacquire, 9 minutes]:
sync.runtime_Semacquire(0x13397808)
	C:/workdir/go/src/runtime/sema.go:56 +0x36
sync.(*WaitGroup).Wait(0x13397800)
	C:/workdir/go/src/sync/waitgroup.go:136 +0x87
golang.org/x/net/http2.(*clientTester).run(0x130e9110)
	C:/workdir/gopath/src/golang.org/x/net/http2/transport_test.go:860 +0x190
golang.org/x/net/http2.testTransportResponseHeaderTimeout(0x130ea0f0, 0x1)
	C:/workdir/gopath/src/golang.org/x/net/http2/transport_test.go:2216 +0x151
golang.org/x/net/http2.TestTransportResponseHeaderTimeout_Body(0x130ea0f0)
	C:/workdir/gopath/src/golang.org/x/net/http2/transport_test.go:2164 +0x26
testing.tRunner(0x130ea0f0, 0x823e98)
	C:/workdir/go/src/testing/testing.go:1449 +0x113
created by testing.(*T).Run
	C:/workdir/go/src/testing/testing.go:1496 +0x374
```

`greplogs -l -e 'panic: test timed out after (?:.*\n)*golang\.org/x/net/http2\.TestTransportResponseHeaderTimeout' --since=2021-01-01`
[2022-05-01T00:24:25-2871e0c-d09ca2c/windows-386-2008](https://build.golang.org/log/ce93c3e449a526a3ec0838a97c5ee13916cefda1)

(CC @neild @tombergan)

**Comment by Jorropo** [comment]
If it's new, probably related to one of [go-review.googlesource.com/c/go/+/403136](https://go-review.googlesource.com/c/go/+/403136)'s bumped commits.

**Comment by qmuntal** [comment]
This failure hasn't reproduced in 4 years, closing.
