### ISSUE TITLE
os/exec: panic in `(*Cmd).Start.func2` on openbsd-amd64-68

### ISSUE THREAD

**Issue by bcmills** [golang/go#52801]
https://storage.googleapis.com/go-build-log/84130882/openbsd-amd64-68_97af332c.log (a TryBot):
```
            > go test -v foo_test.go
            [stderr]
            panic: runtime error: invalid memory address or nil pointer dereference
            [signal SIGSEGV: segmentation violation code=0x1 addr=0x1 pc=0x55f005]
            
            goroutine 441 [running]:
            panic({0xa57620, 0xf64e30})
            	/tmp/workdir/go/src/runtime/panic.go:969 +0x3ba fp=0xc00073a778 sp=0xc00073a6b8 pc=0x437bda
            runtime.panicmem(...)
            	/tmp/workdir/go/src/runtime/panic.go:242
            runtime.sigpanic()
            	/tmp/workdir/go/src/runtime/signal_unix.go:823 +0x336 fp=0xc00073a7c8 sp=0xc00073a778 pc=0x44e396
            os/exec.(*Cmd).Start.func2()
            	/tmp/workdir/go/src/os/exec/exec.go:537 +0x25 fp=0xc00073a7e0 sp=0xc00073a7c8 pc=0x55f005
            runtime.goexit()
            	/tmp/workdir/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00073a7e8 sp=0xc00073a7e0 pc=0x46bba1
            created by os/exec.(*Cmd).Start
            	/tmp/workdir/go/src/os/exec/exec.go:535 +0x6be
```

**Comment by bcmills** [comment]
Marking as release-blocker until I can determine whether this is related to [CL 401896](https://go.dev/cl/401896).

**Comment by bcmills** [comment]
`greplogs -l -e \\s+os/exec\\.\\\(\\\*Cmd\\\)\\.Start\\.func2\\\(\\\)`
[2022-05-08T17:26:10-df57592/plan9-amd64-0intro](https://build.golang.org/log/ad6431b76007033fbd8c17583d5bbcf0edaf7b35)
[2021-12-13T16:44:13-27fc764-acc65b4/netbsd-amd64-9_0-n2d](https://build.golang.org/log/9e9b4ef80631f1b0fdf1035078383fcc9a5a0c6c)

(But neither of those matches this failure mode.)

**Comment by bcmills** [comment]
`greplogs -l -e '(?ms)panic: runtime error: invalid memory address.*^os/exec\.\(\*Cmd\)\.Start' --since=2022-05-08`

(0 matching logs)

Looks to me like this was some kind of memory corruption. AFAICT it is not a systematic problem with the `os/exec` change.
