### ISSUE TITLE
net/http: apparent deadlock in TestIdentityTransferEncoding_h1 via syscall.Open on plan9-arm

### ISSUE THREAD

**Issue by bcmills** [golang/go#52896]
```
#!watchflakes
post <- builder ~ `^plan9` && `goroutine \d+ \[syscall, \d+ minutes\]:\n(.+\n\t.+\n)*syscall\.Open`
```

```
goroutine 1974 [chan receive, 17 minutes]:
runtime.gopark(0x4af1e8, 0x1105a370, 0xe, 0x17, 0x2)
	/boot/workdir/go/src/runtime/proc.go:363 +0x100 fp=0x111c5cb4 sp=0x111c5ca0 pc=0x3f158
runtime.chanrecv(0x1105a340, 0x111c5d54, 0x1)
	/boot/workdir/go/src/runtime/chan.go:583 +0x528 fp=0x111c5d00 sp=0x111c5cb4 pc=0x5ab0
runtime.chanrecv1(0x1105a340, 0x111c5d54)
	/boot/workdir/go/src/runtime/chan.go:442 +0x20 fp=0x111c5d14 sp=0x111c5d00 pc=0x5558
internal/poll.(*asyncIO).Wait(...)
	/boot/workdir/go/src/internal/poll/fd_io_plan9.go:85
internal/poll.(*FD).Read(0x11058b80, 0x1102a798, {0x10ffa000, 0x1000, 0x1000})
	/boot/workdir/go/src/internal/poll/fd_plan9.go:79 +0x194 fp=0x111c5d64 sp=0x111c5d14 pc=0x99444
net.(*netFD).Read(0x11058b80, {0x10ffa000, 0x1000, 0x1000})
	/boot/workdir/go/src/net/fd_plan9.go:86 +0x98 fp=0x111c5d94 sp=0x111c5d64 pc=0x1e8e44
net.(*conn).Read(0x1102a748, {0x10ffa000, 0x1000, 0x1000})
	/boot/workdir/go/src/net/net.go:182 +0x48 fp=0x111c5dc4 sp=0x111c5d94 pc=0x1f5bec
net/http.(*persistConn).Read(0x10fb9a40, {0x10ffa000, 0x1000, 0x1000})
	/boot/workdir/go/src/net/http/transport.go:1928 +0x16c fp=0x111c5df8 sp=0x111c5dc4 pc=0x2e14b4
bufio.(*Reader).Read(0x112077a0, {0x10fe4804, 0x1fc, 0x1fc})
	/boot/workdir/go/src/bufio/bufio.go:237 +0x228 fp=0x111c5e1c sp=0x111c5df8 pc=0xf965c
net/http.(*body).readLocked(0x11207800, {0x10fe4804, 0x1fc, 0x1fc})
	/boot/workdir/go/src/net/http/transfer.go:845 +0x4c fp=0x111c5e48 sp=0x111c5e1c pc=0x2d6c0c
net/http.(*body).Read(0x11207800, {0x10fe4804, 0x1fc, 0x1fc})
	/boot/workdir/go/src/net/http/transfer.go:837 +0xe8 fp=0x111c5e7c sp=0x111c5e48 pc=0x2d6b18
net/http.(*bodyEOFSignal).Read(0x11207830, {0x10fe4804, 0x1fc, 0x1fc})
	/boot/workdir/go/src/net/http/transport.go:2773 +0xc0 fp=0x111c5eb8 sp=0x111c5e7c pc=0x2e56d0
io.ReadAll({0x537110, 0x11207830})
	/boot/workdir/go/src/io/io.go:666 +0xe4 fp=0x111c5ef8 sp=0x111c5eb8 pc=0x949c0
net/http_test.testIdentityTransferEncoding(0x10f825a0, 0x0)
	/boot/workdir/go/src/net/http/clientserver_test.go:1611 +0x290 fp=0x111c5f8c sp=0x111c5ef8 pc=0x34c7f0
net/http_test.TestIdentityTransferEncoding_h1(0x10f825a0)
	/boot/workdir/go/src/net/http/clientserver_test.go:1586 +0x24 fp=0x111c5f98 sp=0x111c5f8c pc=0x34c51c
testing.tRunner(0x10f825a0, 0x4ae924)
	/boot/workdir/go/src/testing/testing.go:1446 +0x118 fp=0x111c5fe0 sp=0x111c5f98 pc=0xf3a28
testing.(*T).Run.func1()
	/boot/workdir/go/src/testing/testing.go:1493 +0x30 fp=0x111c5fec sp=0x111c5fe0 pc=0xf4880
runtime.goexit()
	/boot/workdir/go/src/runtime/asm_arm.s:824 +0x4 fp=0x111c5fec sp=0x111c5fec pc=0x6edb4
created by testing.(*T).Run
	/boot/workdir/go/src/testing/testing.go:1493 +0x3a0

…

goroutine 11972 [syscall, 17 minutes]:
syscall.Syscall(0xe, 0x11286498, 0x0, 0x0)
	/boot/workdir/go/src/syscall/asm_plan9_arm.s:16 +0x8 fp=0x1181bd38 sp=0x1181bca4 pc=0x7c810
syscall.open({0x11286480, 0x12}, 0x0)
	/boot/workdir/go/src/syscall/zsyscall_plan9_arm.go:61 +0x88 fp=0x1181bd6c sp=0x1181bd38 pc=0x7b83c
syscall.Open({0x11286480, 0x12}, 0x0)
	/boot/workdir/go/src/syscall/syscall_plan9.go:384 +0x64 fp=0x1181bd90 sp=0x1181bd6c pc=0x7b3f4
os.openFileNolog({0x11286480, 0x12}, 0x0, 0x0)
	/boot/workdir/go/src/os/file_plan9.go:118 +0xd8 fp=0x1181bdd0 sp=0x1181bd90 pc=0x9e6b8
os.OpenFile({0x11286480, 0x12}, 0x0, 0x0)
	/boot/workdir/go/src/os/file.go:337 +0x48 fp=0x1181bdf0 sp=0x1181bdd0 pc=0x9d944
os.Open(...)
	/boot/workdir/go/src/os/file.go:317
net.(*netFD).acceptPlan9(0x11112780)
	/boot/workdir/go/src/net/ipsock_plan9.go:262 +0x110 fp=0x1181beb8 sp=0x1181bdf0 pc=0x1f1818
net.(*TCPListener).accept(0x1118af70)
	/boot/workdir/go/src/net/tcpsock_plan9.go:48 +0x20 fp=0x1181bef4 sp=0x1181beb8 pc=0x1f9d08
net.(*TCPListener).Accept(0x1118af70)
	/boot/workdir/go/src/net/tcpsock.go:288 +0x3c fp=0x1181bf10 sp=0x1181bef4 pc=0x1f92a4
net/http.(*onceCloseListener).Accept(0x11119720)
	<autogenerated>:1 +0x34 fp=0x1181bf28 sp=0x1181bf10 pc=0x3115cc
net/http.(*Server).Serve(0x10c78ab0, {0x538bcc, 0x1118af70})
	/boot/workdir/go/src/net/http/server.go:3040 +0x344 fp=0x1181bfc4 sp=0x1181bf28 pc=0x2cc104
net/http/httptest.(*Server).goServe.func1()
	/boot/workdir/go/src/net/http/httptest/server.go:310 +0x74 fp=0x1181bfec sp=0x1181bfc4 pc=0x316f1c
runtime.goexit()
	/boot/workdir/go/src/runtime/asm_arm.s:824 +0x4 fp=0x1181bfec sp=0x1181bfec pc=0x6edb4
created by net/http/httptest.(*Server).goServe
	/boot/workdir/go/src/net/http/httptest/server.go:308 +0x74
```

(attn @millerresearch; CC @golang/plan9)

**Comment by bcmills** [comment]
`greplogs -l -e 'goroutine \d+ \[syscall, \d+ minutes\]:\n(.+\n\t.+\n)*syscall\.Open' --since=2022-01-01`
[2022-05-12T21:40:53-2136e15/plan9-arm](https://build.golang.org/log/a5e101bc0c651bc7ec7bd153ec979cb3e4c1ec23)
[2022-05-01T00:24:25-aafffac-d09ca2c/plan9-386-0intro](https://build.golang.org/log/c3bf5194e2ec7a9bb9eb54c9dd49e99c3ffadd84)
[2022-04-04T15:58:39-7d125fe-c8110c3/plan9-386-0intro](https://build.golang.org/log/5941e45bafb013f36b636eafb655135c8e2d60a5)
[2022-02-17T17:37:03-fd59bdf-eaf0405/plan9-arm](https://build.golang.org/log/908843825a9f5da11dbab6a839ff4ab468824951)

**Comment by millerresearch** [comment]
All the logs from this year are `TestServerWriteTimeout` deadlocks (duplicate of #57114), fixed by CL 470215.

**Comment by millerresearch** [comment]
This should not have been reopened: the deadlock situation in the log caught by `watchflakes` is different from the ones seen in this issue (no I/O or deadlock cancellation is going on). I've opened a new issue #59306 for this deadlock.
