### ISSUE TITLE
cmd/nm: TestGoExec failure with 'makeslice: len out of range' on plan9-arm

### ISSUE THREAD

**Issue by bcmills** [golang/go#52895]
```
#!watchflakes
post <- goos == "plan9" && pkg == "cmd/nm" && test == "TestGoExec" && `makeslice: len out of range`
```

```
--- FAIL: TestGoExec (6.37s)
    nm_test.go:156: go tool nm: exit status: 'testnm.exe 47355: 2'
        panic: runtime error: makeslice: len out of range
        
        goroutine 1 [running]:
        panic({0x11a110, 0x168f04})
        	/boot/workdir/go/src/runtime/panic.go:969 +0x400 fp=0x1087dcf8 sp=0x1087dc98 pc=0x37f60
        runtime.panicmakeslicelen(...)
        	/boot/workdir/go/src/runtime/slice.go:29
        runtime.makeslice(0x123338, 0x70700100, 0x70700100)
        	/boot/workdir/go/src/runtime/slice.go:98 +0xec fp=0x1087dd0c sp=0x1087dcf8 pc=0x4c79c
        debug/pe.readCOFFSymbols(0x10890060, {0x16946c, 0x10800460})
        	/boot/workdir/go/src/debug/pe/symbol.go:60 +0xf8 fp=0x1087dd4c sp=0x1087dd0c pc=0xfdac0
        debug/pe.NewFile({0x1691a8, 0x10818348})
        	/boot/workdir/go/src/debug/pe/file.go:108 +0x3d4 fp=0x1087de00 sp=0x1087dd4c pc=0xfa220
        cmd/internal/objfile.openPE({0x1691a8, 0x10818348})
        	/boot/workdir/go/src/cmd/internal/objfile/pe.go:22 +0x24 fp=0x1087de1c sp=0x1087de00 pc=0x105bec
        cmd/internal/objfile.Open({0x3fffff98, 0x1f})
        	/boot/workdir/go/src/cmd/internal/objfile/objfile.go:81 +0x1a4 fp=0x1087de7c sp=0x1087de1c pc=0x105714
        main.nm({0x3fffff98, 0x1f})
        	/boot/workdir/go/src/cmd/nm/nm.go:102 +0x38 fp=0x1087df78 sp=0x1087de7c pc=0x108064
        main.main()
        	/boot/workdir/go/src/cmd/nm/nm.go:88 +0x284 fp=0x1087dfb8 sp=0x1087df78 pc=0x107f9c
        runtime.main()
        	/boot/workdir/go/src/runtime/proc.go:250 +0x2ac fp=0x1087dfec sp=0x1087dfb8 pc=0x3acec
        runtime.goexit()
        	/boot/workdir/go/src/runtime/asm_arm.s:824 +0x4 fp=0x1087dfec sp=0x1087dfec pc=0x636c4
```

`greplogs -l -e 'FAIL: TestGoExec .*(?:\n[ ]+.*)* makeslice: len out of range'`
[2022-05-12T22:32:42-016d755/plan9-arm](https://build.golang.org/log/27e6637f5468d2e40beafb5efc2c830b3146d97b)

(attn @golang/plan9; see previously #25820)

**Comment by bcmills** [comment]
Curiosly2 two more of these. Looks like a new failure mode?

`greplogs -l -e 'FAIL: TestGoExec .*(?:\n[ ]+.*)* makeslice: len out of range' --since=2022-05-13`
[2022-05-13T15:23:38-5a4ba6d/plan9-arm](https://build.golang.org/log/513e44c1bb99a2dba95b0cf8356dd15bb7f7a6f6)
[2022-05-13T14:14:26-b553f51/plan9-arm](https://build.golang.org/log/35b273485f61616869b76d153dacdce4c5e27c08)
