### ISSUE TITLE
runtime: "fatal error: workbuf is empty" on openbsd-amd64-68

### ISSUE THREAD

**Issue by bcmills** [golang/go#53176]
```
fatal error: workbuf is empty

runtime stack:
runtime.throw({0xa07e04?, 0x20300000427965?})
	/tmp/workdir/go/src/runtime/panic.go:1047 +0x5d fp=0x2d5c193b8 sp=0x2d5c19388 pc=0x435cfd
runtime.(*workbuf).checknonempty(0x2d5c193e8?)
	/tmp/workdir/go/src/runtime/mgcwork.go:337 +0x36 fp=0x2d5c193d8 sp=0x2d5c193b8 pc=0x427556
runtime.trygetfull()
	/tmp/workdir/go/src/runtime/mgcwork.go:429 +0x65 fp=0x2d5c193f8 sp=0x2d5c193d8 pc=0x427965
runtime.(*gcWork).tryGet(0xc000035238)
	/tmp/workdir/go/src/runtime/mgcwork.go:215 +0x5b fp=0x2d5c19428 sp=0x2d5c193f8 pc=0x4272db
runtime.gcDrain(0xc000035238, 0x7)
	/tmp/workdir/go/src/runtime/mgcmark.go:1084 +0x185 fp=0x2d5c19488 sp=0x2d5c19428 pc=0x4204e5
runtime.gcBgMarkWorker.func2()
	/tmp/workdir/go/src/runtime/mgc.go:1323 +0x6d fp=0x2d5c194d8 sp=0x2d5c19488 pc=0x41cfad
runtime.systemstack()
	/tmp/workdir/go/src/runtime/asm_amd64.s:492 +0x49 fp=0x2d5c194e0 sp=0x2d5c194d8 pc=0x464089

goroutine 19 [GC worker (idle)]:
runtime.systemstack_switch()
	/tmp/workdir/go/src/runtime/asm_amd64.s:459 fp=0xc000042750 sp=0xc000042748 pc=0x464020
runtime.gcBgMarkWorker()
	/tmp/workdir/go/src/runtime/mgc.go:1291 +0x1ae fp=0xc0000427e0 sp=0xc000042750 pc=0x41cc8e
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000427e8 sp=0xc0000427e0 pc=0x466261
created by runtime.gcBgMarkStartWorkers
	/tmp/workdir/go/src/runtime/mgc.go:1159 +0x25
```

`greplogs -l -e 'fatal error: workbuf is empty' --since=2022-02-02`
[2022-05-25T16:16:01-4e4db1e/openbsd-amd64-68](https://build.golang.org/log/b605e8bc3571eee39b8ac28340fa75cb216cdb8e)

With N=1 failures since the OpenBSD builders became stable again, it's not at all clear to me whether this is a platform-specific failure mode. Leaving on the Backlog to collect more data.

(CC @golang/runtime @golang/openbsd)

**Comment by bcmills** [comment]
Duplicate of #34988
