### ISSUE TITLE
cmd/compile: panic in generics (types from different scopes on interface conversion)

### ISSUE THREAD

**Issue by ernado** [golang/go#53376]
### What version of Go are you using (`go version`)?

go version go1.18.3 linux/amd64

### Does this issue reproduce with the latest release?

~~Yes, also on `go version devel go1.19-55590f3a2b`~~ **Works on tip**

But works on 1.18.2, so prorably a regression?

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

```
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ernado/.cache/go-build"
GOENV="/home/ernado/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/src/ernado/types-from-different-scope/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build506888335=/tmp/go-build -gno-record-gcc-switches"
```

</pre></details>

### What did you do?

https://go.dev/play/p/WSzdK-I-g2o

```go
type Appender[T any] interface {
	Append(v T)
}

type StrAppender struct{}

func (StrAppender) Append(v string) {}

func newStrAppender() Appender[string] {
	return StrAppender{}
}

// this works
func appendAllGood[T any, C Appender[T]](c C, v ...T) C {
	for _, vv := range v {
		c.Append(vv)
	}
	return c
}

// this panics on go1.18.3, go1.19, but works on go1.18.2
func appendAllBad[T any](c Appender[T], v ...T) Appender[T] {
	for _, vv := range v {
		c.Append(vv) // <- panic: interface conversion: 
		// pkg.Appender[go.shape.string_0] is pkg.StrAppender, not pkg.StrAppender 
		// (types from different scopes)
	}
	return c
}
```

### What did you expect to see?
No panic

### What did you see instead?
```
panic: interface conversion: main.Appender[go.shape.string_0] is main.StrAppender, not main.StrAppender (types from different scopes)

goroutine 1 [running]:
main.appendAllBad[...](...)
	/tmp/sandbox1272243070/prog.go:28
main.main()
	/tmp/sandbox1272243070/prog.go:37 +0x116

Program exited.
```

**Comment by ianlancetaylor** [comment]
CC @randall77 @mdempsky

**Comment by mdempsky** [comment]
Looks to be working at tip?

**Comment by ernado** [comment]
@mdempsky 
```console
ernado@nexus:/src/ernado/types-from-different-scope$ /src/go/bin/go version
go version devel go1.19-cad477c922 Tue Jun 14 14:49:40 2022 +0000 linux/amd64
ernado@nexus:/src/ernado/types-from-different-scope$ /src/go/bin/go test
--- FAIL: TestBad (0.00s)
panic: interface conversion: pkg.Appender[go.shape.string_0] is pkg.StrAppender, not pkg.StrAppender (types from different scopes) [recovered]
        panic: interface conversion: pkg.Appender[go.shape.string_0] is pkg.StrAppender, not pkg.StrAppender (types from different scopes)

goroutine 7 [running]:
testing.tRunner.func1.2({0x503040, 0xc0000103f0})
        /usr/local/go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
        /usr/local/go/src/testing/testing.go:1392 +0x39f
panic({0x503040, 0xc0000103f0})
        /usr/local/go/src/runtime/panic.go:838 +0x207
types-from-different-scope.appendAllBad[...](...)
        /src/ernado/types-from-different-scope/main_test.go:26
types-from-different-scope.TestBad(0xc0000e4340?)
        /src/ernado/types-from-different-scope/main_test.go:38 +0x2e
testing.tRunner(0xc0000e4680, 0x528670)
        /usr/local/go/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1486 +0x35f
exit status 2
FAIL    types-from-different-scope      0.003s
```

Not working on cad477c922

**Comment by ernado** [comment]
Sorry @mdempsky, actually this works on tip (cad477c922), got some very weird go env

**Comment by ianlancetaylor** [comment]
Working at tip, so closing.  Thanks.
