### ISSUE TITLE
x/tools/internal/lsp/cmd: `panic: inheriting destroyed handle cache.actionHandleKey`

### ISSUE THREAD

**Issue by bcmills** [golang/go#53430]
```
panic: inheriting destroyed handle cache.actionHandleKey{0xab, 0x81, 0x94, 0x58, 0x1d, 0x87, 0xdd, 0xf6, 0xdf, 0xb6, 0x50, 0xe8, 0x91, 0xae, 0xec, 0x38, 0x8c, 0x4e, 0x15, 0xc5, 0xc2, 0x87, 0x71, 0x9b, 0x74, 0x48, 0xa2, 0xb8, 0xdc, 0x1f, 0x36, 0x22} (type cache.actionHandleKey) into generation v6/80

goroutine 26589 [running]:
golang.org/x/tools/internal/memoize.(*Generation).Inherit(0xc1e3a0?, 0xc0016a1980)
	/tmp/workdir/gopath/src/golang.org/x/tools/internal/memoize/memoize.go:249 +0x14d
golang.org/x/tools/internal/lsp/cache.(*snapshot).clone(0xc00927ea20, {0xf41e60, 0xc004a1b630}, {0xf41840, 0xc003e927e0}, 0xc003ac58c0, 0x0)
	/tmp/workdir/gopath/src/golang.org/x/tools/internal/lsp/cache/snapshot.go:1979 +0x1e5c
golang.org/x/tools/internal/lsp/cache.(*View).invalidateContent(0xc002db6420, {0xf41840?, 0xc003a49f20?}, 0x80?, 0x60?)
	/tmp/workdir/gopath/src/golang.org/x/tools/internal/lsp/cache/view.go:723 +0x190
golang.org/x/tools/internal/lsp/cache.(*Session).DidModifyFiles(0xc0010fe080, {0xf41840, 0xc003a49f20}, {0xc00aa37400, 0x1, 0x1})
	/tmp/workdir/gopath/src/golang.org/x/tools/internal/lsp/cache/session.go:502 +0x3aa
golang.org/x/tools/internal/lsp.(*Server).processModifications(0xc001c54000, {0xf41840, 0xc003a49f20}, {0xc008c384b0, 0x1, 0x1}, 0x0, 0xc00249e900)
	/tmp/workdir/gopath/src/golang.org/x/tools/internal/lsp/text_synchronization.go:293 +0x1a8
golang.org/x/tools/internal/lsp.(*Server).didModifyFiles(0xc001c54000, {0xf41840, 0xc003a49f20}, {0xc008c384b0?, 0x1, 0x1}, 0x0)
	/tmp/workdir/gopath/src/golang.org/x/tools/internal/lsp/text_synchronization.go:225 +0x5a6
golang.org/x/tools/internal/lsp.(*Server).didOpen(0xc001c54000, {0xf41840, 0xc003a49f20}, 0xc005343b80)
	/tmp/workdir/gopath/src/golang.org/x/tools/internal/lsp/text_synchronization.go:94 +0x27a
golang.org/x/tools/internal/lsp.(*Server).DidOpen(0xc00a9c2dc0?, {0xf41840?, 0xc003a49f20?}, 0xbc7be0?)
	/tmp/workdir/gopath/src/golang.org/x/tools/internal/lsp/server_gen.go:92 +0x25
golang.org/x/tools/internal/lsp/protocol.serverDispatch({0xf41840, 0xc003a49f20}, {0xf4d070, 0xc001c54000}, 0xc00387d140, {0xf41a38, 0xc003a49dd0})
	/tmp/workdir/gopath/src/golang.org/x/tools/internal/lsp/protocol/tsserver.go:161 +0x11e2
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1({0xf41840, 0xc003a49f20}, 0xc00387d140, {0xf41a38, 0xc003a49dd0})
	/tmp/workdir/gopath/src/golang.org/x/tools/internal/lsp/protocol/protocol.go:157 +0x90
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1({0xf41840, 0xc003a49f20}, 0xc00387d140, {0xf41a38?, 0xc003a49dd0?})
	/tmp/workdir/gopath/src/golang.org/x/tools/internal/lsp/lsprpc/lsprpc.go:511 +0xa43
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1({0xf41840, 0xc003a49f20}, 0xc004092108, {0xf41a38?, 0xc003a49dd0?})
	/tmp/workdir/gopath/src/golang.org/x/tools/internal/jsonrpc2/handler.go:35 +0xf6
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2()
	/tmp/workdir/gopath/src/golang.org/x/tools/internal/jsonrpc2/handler.go:103 +0xa3
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	/tmp/workdir/gopath/src/golang.org/x/tools/internal/jsonrpc2/handler.go:100 +0x20a
FAIL	golang.org/x/tools/internal/lsp/cmd	44.190s
```

`greplogs -l -e 'panic: inheriting destroyed handle cache\.actionHandleKey'`
[2022-06-15T21:24:24-654a14b-91baf5c/openbsd-amd64-68](https://build.golang.org/log/54416b9c8c1df8ac260386a3cb8218a76f92c95f)

**Comment by hyangah** [comment]
```
openbsd-amd64-68 at 91baf5ceccc363c21925aee8611c2c279806238b building tools at 654a14b5274602698564a5e9710c0778be664c7a
```

I believe this is a known issue and the commit 654a14b was reverted in https://go-review.googlesource.com/c/tools/+/412694
cc @adonovan
