### ISSUE TITLE
http: nil *bytes.Buffer causes panic

### ISSUE THREAD

**Issue by kaedys** [golang/go#53630]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.3 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOVERSION="go1.18.3"
GOAMD64="v1"
</pre></details>

### What did you do?

https://goplay.space/#9Nm802LonLY

```
	fmt.Println(runtime.Version())

	// Function input
	var (
		method  = http.MethodGet
		uri     = "http://www.google.com"
		payload interface{}
	)

	// Create a var for the body, but only instantiate it and marshal to it if a body payload was included
	var b *bytes.Buffer
	if payload != nil {
		b = new(bytes.Buffer)
		if err := json.NewEncoder(b).Encode(payload); err != nil {
			panic(err)
		}
	}

	// This panics if payload is nil
	if _, err := http.NewRequest(method, uri, b); err != nil {
		panic(err)
	}
```

### What did you expect to see?
No panic.

### What did you see instead?
```
T+00.000000001panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x519e24]

goroutine 1 [running]:
bytes.(*Buffer).Len(...)
	/usr/local/go-faketime/src/bytes/buffer.go:73
net/http.NewRequestWithContext({0x58b3c0?, 0xc0000ba020}, {0x555e61?, 0x1?}, {0x55a129?, 0x15?}, {0x58a8e0, 0x0?})
	/usr/local/go-faketime/src/net/http/request.go:893 +0x564
net/http.NewRequest(...)
	/usr/local/go-faketime/src/net/http/request.go:831
main.main()
	/tmp/sandbox3656163977/prog.go:31 +0x9b
```

I understand _why_ this is happening,.  I'm providing anil pointer to a bytes.Buffer to the io.Reader interface argument to NewRequest, so the [`body != nil`](https://cs.opensource.google/go/go/+/refs/tags/go1.18.3:src/net/http/request.go;l=890) check in the NewRequestWithContext() call sees it as non-nil, because a nil pointer in an interface isn't nil (there are, of course, _many_ feature requests and proposals out here for handling the confusion around a nil interface check better for Go 2+).

However, this _feels_ like valid code.  I have a var type that fulfills the io.Reader interface, but I'm only instantiating it and filling it if I have a body.  If not, my call to request includes a `nil` in the body argument slot, but it's a _typed_ `nil`, unlike the keyword `nil`. 
 My options here would be to have to conditionally provide an _explicit_ nil to the NewRequest call (and then pre-declare the return vars from it, since the call would be inside an `if/else` block, so short-form declaration wouldn't work), or conditionally store the body in a separate var (ex. an `io.Reader`) to pass to the request.  I also need the var to be a `bytes.Buffer` (or pointer to such) later to make use of some of the bytes.Buffer methods (ex. `String()` to get the JSON output without consuming the reader contents), so I cannot simply use an `io.ReadWriter` as that var. 

It seems unnecessarily arduous and roundabout to have to include such conditional logic to get around the fact that NewRequestWithContext treats an explicit `nil` and a nil pointer of 3 very specific core library types differently, and panics in the latter case.  As such, from a robustness perspective, I believe that there should be a second nil check in each of the explicit-pointer-type cases in the above linked switch in NewRequestWithContext, and the operations therein only performed if the _pointer_ is also non-nil.  ie changing this:
```
	if body != nil {
		switch v := body.(type) {
		case *bytes.Buffer:
			req.ContentLength = int64(v.Len())
			buf := v.Bytes()
			req.GetBody = func() (io.ReadCloser, error) {
				r := bytes.NewReader(buf)
				return io.NopCloser(r), nil
			}
		// ...
		}
	}
```
into this:
```
	if body != nil {
		switch v := body.(type) {
		case *bytes.Buffer:
			if v != nil {
				req.ContentLength = int64(v.Len())
				buf := v.Bytes()
				req.GetBody = func() (io.ReadCloser, error) {
					r := bytes.NewReader(buf)
					return io.NopCloser(r), nil
				}
			}
		// ...
		}
	}
```

This feels like a fairly low risk and low side-effect change, and since such calls currently cause a panic, I do not believe making such a change would violate the Go 1.0 compatibility guarantee either.

**Comment by kaedys** [comment]
Not strictly any pointer, just the 3 types explicitly checked for in that switch case.  Those 3 types are handled specially, for reasons of ease of use, which means that those 3 types specifically can cause a panic in that section where _any other type of pointer_, if nil, would not cause a panic.  I fail to see how this is just a "working as intended" situation.

**Comment by kaedys** [comment]
Also, as I pointed out, I need the other methods of the `bytes.Buffer` type, so I'd have to use a secondary variable of type `io.Reader` and conditionally store into it, which is an unnecessarily complex workaround for a failure by the core library to check if a pointer being accessed is non-nil.

**Comment by ianlancetaylor** [comment]
OK,  I do see now that there are only a few types that matter, but still this is not the kind of change we are going to make.  The language clearly distinguishes between a `nil` interface value and a `nil` pointer of a specific type stored in an interface value.  This is unfortunately a source of confusion for new Go programmers, but we don't make it less confusing by treating it inconsistently.

I'm sorry it makes your code a bit more complicated.  It would not be hard for you to use a wrapper around `http.Request` that tests for the property that you care about.
