### ISSUE TITLE
runtime,misc/cgo/test: timeout in TestSetgidStress on linux/amd64

### ISSUE THREAD

**Issue by bcmills** [golang/go#53641]
```
##### ../misc/cgo/test
ok  	misc/cgo/test	2.556s
ok  	misc/cgo/test	2.474s
SIGQUIT: quit
PC=0x472ee1 m=0 sigcode=0

…

goroutine 7 [runnable]:
runtime.gopark(0xc00019a060?, 0xc000058ee8?, 0x9f?, 0x46?, 0x7f0df652b108?)
	/workdir/go/src/runtime/proc.go:363 +0xd6 fp=0xc000058e68 sp=0xc000058e48 pc=0x440a36
runtime.chanrecv(0xc0000ca000, 0x0, 0x1)
	/workdir/go/src/runtime/chan.go:583 +0x49b fp=0xc000058ef8 sp=0xc000058e68 pc=0x40de9b
runtime.chanrecv1(0x6eb980?, 0x3e8?)
	/workdir/go/src/runtime/chan.go:442 +0x18 fp=0xc000058f20 sp=0xc000058ef8 pc=0x40d9d8
misc/cgo/test.testSetgidStress(0x4862d7?)
	/workdir/go/misc/cgo/test/setgid2_linux.go:33 +0x9c fp=0xc000058f58 sp=0xc000058f20 pc=0x56119c
misc/cgo/test.TestSetgidStress(0x0?)
	/workdir/go/misc/cgo/test/cgo_linux_test.go:23 +0x19 fp=0xc000058f70 sp=0xc000058f58 pc=0x526519
testing.tRunner(0xc0000c8000, 0x5b9500)
	/workdir/go/src/testing/testing.go:1446 +0x10b fp=0xc000058fc0 sp=0xc000058f70 pc=0x4d6a4b
testing.(*T).Run.func1()
	/workdir/go/src/testing/testing.go:1493 +0x2a fp=0xc000058fe0 sp=0xc000058fc0 pc=0x4d78ea
runtime.goexit()
	/workdir/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000058fe8 sp=0xc000058fe0 pc=0x471001
created by testing.(*T).Run
	/workdir/go/src/testing/testing.go:1493 +0x35f

…
*** Test killed with quit: ran too long (11m0s).
FAIL	misc/cgo/test	660.128s
```

`greplogs -l -e 'goroutine \d+ .*:\n(?:.+\n\t.+\n)*misc/cgo/test\.TestSetgidStress'`
[2022-06-30T21:57:02-aad9382/linux-amd64-sid](https://build.golang.org/log/9bfeb0f4a0062c8923eb41686f730082dfa6f6cc)

**Comment by bcmills** [comment]
This test was added a couple days ago (in [CL 412474](https://go.dev/cl/412474) for #53374), so the error rate could potentially be high (we don't have many test runs that include this test).

As such, marking as release-blocker until the test can be fixed or skipped.

(attn @cherrymui @aclements; CC @golang/runtime)

**Comment by bcmills** [comment]
One more recurrence this week, on the `-longtest` builder:
`greplogs -l -e 'goroutine \d+ .*:\n(?:.+\n\t.+\n)*misc/cgo/test\.TestSetgidStress' --since=2022-07-02`
[2022-07-26T20:27:23-faf4e97/linux-amd64-longtest](https://build.golang.org/log/fdf5beddd880fd3753510461debd0ef826ac43de)
