### ISSUE TITLE
cmd/go: TestScript hang on Windows

### ISSUE THREAD

**Issue by heschi** [golang/go#53724]
[2022-07-01T15:37:46-9a4d535/windows-amd64-longtest](https://build.golang.org/log/1393ef3bf6fe94d867d1ac7c1b10fc0740ddbb7b)

I can't figure out what was going on here. Seems like everything is waiting on a Parallel call except for:

```
goroutine 718 [chan receive, 44 minutes]:
runtime.gopark(0xc000dba000?, 0x94b83b?, 0xc0?, 0x7b?, 0x94b83b?)
	C:/workdir/go/src/runtime/proc.go:363 +0xd6 fp=0xc000df9b18 sp=0xc000df9af8 pc=0x36e176
runtime.chanrecv(0xc00049fb00, 0x0, 0x1)
	C:/workdir/go/src/runtime/chan.go:583 +0x49b fp=0xc000df9ba8 sp=0xc000df9b18 pc=0x33733b
runtime.chanrecv1(0xc0001f1680?, 0x0?)
	C:/workdir/go/src/runtime/chan.go:442 +0x18 fp=0xc000df9bd0 sp=0xc000df9ba8 pc=0x336e38
cmd/go_test.(*testScript).cmdExec(0xc0001f1680, {0x0, 0x0}, {0xc0010d08a0, 0x6, 0x6})
	C:/workdir/go/src/cmd/go/script_test.go:802 +0x29f fp=0xc000df9c40 sp=0xc000df9bd0 pc=0x94805f
cmd/go_test.(*testScript).cmdGo(0x9b5820?, {0x0, 0x0}, {0xc0001be980?, 0x5?, 0x1?})
	C:/workdir/go/src/cmd/go/script_test.go:864 +0x11c fp=0xc000df9cb0 sp=0xc000df9c40 pc=0x9488bc
cmd/go_test.(*testScript).run(0xc0001f1680)
	C:/workdir/go/src/cmd/go/script_test.go:447 +0x6a9 fp=0xc000df9ed0 sp=0xc000df9cb0 pc=0x944369
cmd/go_test.TestScript.func1(0xc000d7fd40)
	C:/workdir/go/src/cmd/go/script_test.go:97 +0x1fa fp=0xc000df9f70 sp=0xc000df9ed0 pc=0x94297a
testing.tRunner(0xc000d7fd40, 0xc000afdec0)
	C:/workdir/go/src/testing/testing.go:1446 +0x10b fp=0xc000df9fc0 sp=0xc000df9f70 pc=0x46392b
testing.(*T).Run.func1()
	C:/workdir/go/src/testing/testing.go:1493 +0x2a fp=0xc000df9fe0 sp=0xc000df9fc0 pc=0x4647ca
runtime.goexit()
	C:/workdir/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000df9fe8 sp=0xc000df9fe0 pc=0x39d3a1
created by testing.(*T).Run
	C:/workdir/go/src/testing/testing.go:1493 +0x35f
```

**Comment by heschi** [comment]
cc @bcmills
