### ISSUE TITLE
x/website: Inside the Go Playground - Faking the network example error

### ISSUE THREAD

**Issue by gempellm** [golang/go#53731]
### What is the URL of the page with the issue?
 https://go.dev/blog/playground
 
 
### What is your user agent?
 [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36]

 
 
### Screenshot
 
![image](https://user-images.githubusercontent.com/43187449/177731072-3db6fa81-5bd7-4fa4-a3dd-a34c7a5c04d4.png)
 
 
 
### What did you do?
 
I ran the "Faking the network" example.
 
 
 
### What did you expect to see?
 "Hello, network" output.
 
 
### What did you see instead?
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7f371e984ef8, 0x72)
	/usr/local/go-faketime/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc000106000?, 0x512e00?, 0x0)
	/usr/local/go-faketime/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go-faketime/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Accept(0xc000106000)
	/usr/local/go-faketime/src/internal/poll/fd_unix.go:614 +0x22c
net.(*netFD).accept(0xc000106000)
	/usr/local/go-faketime/src/net/fd_unix.go:172 +0x35
net.(*TCPListener).accept(0xc00000c078)
	/usr/local/go-faketime/src/net/tcpsock_posix.go:139 +0x28
net.(*TCPListener).Accept(0xc00000c078)
	/usr/local/go-faketime/src/net/tcpsock.go:288 +0x3d
main.main()
	/tmp/sandbox207294729/prog.go:24 +0xfe

goroutine 6 [IO wait]:
internal/poll.runtime_pollWait(0x7f371e984e08, 0x77)
	/usr/local/go-faketime/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc000106100?, 0x4ec595?, 0x0)
	/usr/local/go-faketime/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitWrite(...)
	/usr/local/go-faketime/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).WaitWrite(...)
	/usr/local/go-faketime/src/internal/poll/fd_unix.go:741
net.(*netFD).connect(0xc000106100, {0x512e00?, 0xc000018030}, {0xc000071948?, 0x40bd25?}, {0x512978?, 0xc000108060?})
	/usr/local/go-faketime/src/net/fd_unix.go:141 +0x716
net.(*netFD).dial(0xc000106100, {0x512e00, 0xc000018030}, {0x512f60?, 0x0?}, {0x512f60?, 0xc0000126c0}, 0x0?)
	/usr/local/go-faketime/src/net/sock_posix.go:149 +0x394
net.socket({0x512e00, 0xc000018030}, {0x4ec595, 0x3}, 0x2, 0x1, 0x0?, 0x38?, {0x512f60, 0x0}, ...)
	/usr/local/go-faketime/src/net/sock_posix.go:70 +0x2b2
net.internetSocket({0x512e00, 0xc000018030}, {0x4ec595, 0x3}, {0x512f60, 0x0}, {0x512f60, 0xc0000126c0}, 0xc000018250?, 0x0, ...)
	/usr/local/go-faketime/src/net/ipsock_posix.go:142 +0xf8
net.(*sysDialer).doDialTCP(0xc000106080, {0x512e00, 0xc000018030}, 0x0, 0x9?)
	/usr/local/go-faketime/src/net/tcpsock_posix.go:65 +0xa5
net.(*sysDialer).dialTCP(0x1?, {0x512e00?, 0xc000018030?}, 0x0?, 0x0?)
	/usr/local/go-faketime/src/net/tcpsock_posix.go:61 +0x59
net.(*sysDialer).dialSingle(0xc000106080, {0x512e00, 0xc000018030}, {0x512bd0?, 0xc0000126c0})
	/usr/local/go-faketime/src/net/dial.go:583 +0x28b
net.(*sysDialer).dialSerial(0xc000106080, {0x512e00, 0xc000018030}, {0xc0000104e0?, 0x1, 0x4ec681?})
	/usr/local/go-faketime/src/net/dial.go:551 +0x312
net.(*Dialer).DialContext(0xc000071ef8, {0x512e00, 0xc000018030}, {0x4ec595, 0x3}, {0x4ee065, 0xe})
	/usr/local/go-faketime/src/net/dial.go:428 +0x736
net.(*Dialer).Dial(...)
	/usr/local/go-faketime/src/net/dial.go:351
net.Dial({0x4ec595?, 0x0?}, {0x4ee065?, 0x0?})
	/usr/local/go-faketime/src/net/dial.go:319 +0x7a
main.dial()
	/tmp/sandbox207294729/prog.go:34 +0x46
created by main.main
	/tmp/sandbox207294729/prog.go:22 +0xee

Program exited.

**Comment by ZekeLu** [comment]
duplicate of #48394

**Comment by seankhliao** [comment]
Duplicate of #48394
