### ISSUE TITLE
go 1.18: SIGILL illegal instruction on result of `go install`

### ISSUE THREAD

**Issue by hherman1** [golang/go#53841]
**While I was going through this I bumped to 1.18.4 and it fixed the issue. I'm guessing this is duplicative then, but filing just to be sure.**

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 darwin/amd64

# after I upgraded to latest
$ go version
go version go1.18.4 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?

Just tried, and no, it doesnt!

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/hherman/Library/Caches/go-build"
GOENV="/Users/hherman/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/hherman/go/pkg/mod"
GONOPROXY="github.palantir.build"
GONOSUMDB="github.palantir.build"
GOOS="darwin"
GOPATH="/Users/hherman/go"
GOPRIVATE="github.palantir.build"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Volumes/git/cq/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/v0/vr0fg9n561xb_v9vf1lbv4zn0846hc/T/go-build1613071698=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

Ran a CLI which made an HTTP PUT request to a local server on port 8443 with a self signed certificate.

### What did you expect to see?

Result from my CLI

### What did you see instead?

```
SIGILL: illegal instruction
PC=0x7ff801bdf03a m=20 sigcode=1
instruction bytes: 0xf 0xb 0x48 0x8d 0x5 0x88 0xee 0x20 0x0 0x48 0x89 0x5 0xc6 0xe9 0x58 0x41

goroutine 0 [idle]:
crypto/x509/internal/macos.syscall(0xc00000e240?, 0x0?, 0x11ddfc0?, 0xc000c092f0?, 0x100c22b?, 0x13b2be0?, 0xc00000e240?)
	/usr/local/go/src/runtime/sys_darwin.go:99 +0x58 fp=0xc000c092a0 sp=0xc000c09240 pc=0x1060758
crypto/x509/internal/macos.CFRelease(0xc000c09348?)
	/usr/local/go/src/crypto/x509/internal/macos/corefoundation.go:152 +0x34 fp=0xc000c092e8 sp=0xc000c092a0 pc=0x11dd3d4
crypto/x509/internal/macos.ReleaseCFArray(0xc000c09360?)
	/usr/local/go/src/crypto/x509/internal/macos/corefoundation.go:204 +0x2c fp=0xc000c09318 sp=0xc000c092e8 pc=0x11dd60c
crypto/x509.(*Certificate).systemVerify.func1()
	/usr/local/go/src/crypto/x509/root_darwin.go:14 +0x26 fp=0xc000c09330 sp=0xc000c09318 pc=0x11e6d46
runtime.deferreturn()
	/usr/local/go/src/runtime/panic.go:436 +0x33 fp=0xc000c09370 sp=0xc000c09330 pc=0x1033173
crypto/x509.(*Certificate).systemVerify(0xc00075a580, 0xc000c09718)
	/usr/local/go/src/crypto/x509/root_darwin.go:35 +0x477 fp=0xc000c095c8 sp=0xc000c09370 pc=0x11e6637
crypto/x509.(*Certificate).Verify(0xc00075a580, {{0xc000a5f7d0, 0x9}, 0xc000b0fc20, 0x0, {0xc0abd8ccdcbd2d80, 0x5ef7677, 0x1f39460}, {0x0, 0x0, ...}, ...})
	/usr/local/go/src/crypto/x509/verify.go:747 +0x4c7 fp=0xc000c09718 sp=0xc000c095c8 pc=0x11ea6e7
crypto/tls.(*Conn).verifyServerCertificate(0xc000022380, {0xc00000e1f8, 0x1, 0x1})
	/usr/local/go/src/crypto/tls/handshake_client.go:868 +0x658 fp=0xc000c099a0 sp=0xc000c09718 pc=0x1205238
crypto/tls.(*clientHandshakeStateTLS13).readServerCertificate(0xc000c09d98)
	/usr/local/go/src/crypto/tls/handshake_client_tls13.go:457 +0x2d1 fp=0xc000c09bb0 sp=0xc000c099a0 pc=0x1207ab1
crypto/tls.(*clientHandshakeStateTLS13).handshake(0xc000c09d98)
	/usr/local/go/src/crypto/tls/handshake_client_tls13.go:87 +0x1d9 fp=0xc000c09be8 sp=0xc000c09bb0 pc=0x1205bf9
crypto/tls.(*Conn).clientHandshake(0xc000022380, {0x153a030, 0xc00072d080})
	/usr/local/go/src/crypto/tls/handshake_client.go:219 +0x578 fp=0xc000c09e78 sp=0xc000c09be8 pc=0x1200bd8
crypto/tls.(*Conn).clientHandshake-fm({0x153a030?, 0xc00072d080?})
	<autogenerated>:1 +0x39 fp=0xc000c09ea0 sp=0xc000c09e78 pc=0x1223279
crypto/tls.(*Conn).handshakeContext(0xc000022380, {0x153a068, 0xc0000260c8})
	/usr/local/go/src/crypto/tls/conn.go:1452 +0x3d1 fp=0xc000c09f70 sp=0xc000c09ea0 pc=0x11feb91
crypto/tls.(*Conn).HandshakeContext(...)
	/usr/local/go/src/crypto/tls/conn.go:1402
net/http.(*persistConn).addTLS.func2()
	/usr/local/go/src/net/http/transport.go:1537 +0x71 fp=0xc000c09fe0 sp=0xc000c09f70 pc=0x1282991
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000c09fe8 sp=0xc000c09fe0 pc=0x10639c1
created by net/http.(*persistConn).addTLS
	/usr/local/go/src/net/http/transport.go:1533 +0x345

goroutine 50 [syscall]:
crypto/x509/internal/macos.syscall(0xc00000e240?, 0x0?, 0x11ddfc0?, 0xc000c092f0?, 0x100c22b?, 0x13b2be0?, 0xc00000e240?)
	/usr/local/go/src/runtime/sys_darwin.go:99 +0x58 fp=0xc000c092a0 sp=0xc000c09240 pc=0x1060758
crypto/x509/internal/macos.CFRelease(0xc000c09348?)
	/usr/local/go/src/crypto/x509/internal/macos/corefoundation.go:152 +0x34 fp=0xc000c092e8 sp=0xc000c092a0 pc=0x11dd3d4
crypto/x509/internal/macos.ReleaseCFArray(0xc000c09360?)
	/usr/local/go/src/crypto/x509/internal/macos/corefoundation.go:204 +0x2c fp=0xc000c09318 sp=0xc000c092e8 pc=0x11dd60c
crypto/x509.(*Certificate).systemVerify.func1()
	/usr/local/go/src/crypto/x509/root_darwin.go:14 +0x26 fp=0xc000c09330 sp=0xc000c09318 pc=0x11e6d46
runtime.deferreturn()
	/usr/local/go/src/runtime/panic.go:436 +0x33 fp=0xc000c09370 sp=0xc000c09330 pc=0x1033173
crypto/x509.(*Certificate).systemVerify(0xc00075a580, 0xc000c09718)
	/usr/local/go/src/crypto/x509/root_darwin.go:35 +0x477 fp=0xc000c095c8 sp=0xc000c09370 pc=0x11e6637
crypto/x509.(*Certificate).Verify(0xc00075a580, {{0xc000a5f7d0, 0x9}, 0xc000b0fc20, 0x0, {0xc0abd8ccdcbd2d80, 0x5ef7677, 0x1f39460}, {0x0, 0x0, ...}, ...})
	/usr/local/go/src/crypto/x509/verify.go:747 +0x4c7 fp=0xc000c09718 sp=0xc000c095c8 pc=0x11ea6e7
crypto/tls.(*Conn).verifyServerCertificate(0xc000022380, {0xc00000e1f8, 0x1, 0x1})
	/usr/local/go/src/crypto/tls/handshake_client.go:868 +0x658 fp=0xc000c099a0 sp=0xc000c09718 pc=0x1205238
crypto/tls.(*clientHandshakeStateTLS13).readServerCertificate(0xc000c09d98)
	/usr/local/go/src/crypto/tls/handshake_client_tls13.go:457 +0x2d1 fp=0xc000c09bb0 sp=0xc000c099a0 pc=0x1207ab1
crypto/tls.(*clientHandshakeStateTLS13).handshake(0xc000c09d98)
	/usr/local/go/src/crypto/tls/handshake_client_tls13.go:87 +0x1d9 fp=0xc000c09be8 sp=0xc000c09bb0 pc=0x1205bf9
crypto/tls.(*Conn).clientHandshake(0xc000022380, {0x153a030, 0xc00072d080})
	/usr/local/go/src/crypto/tls/handshake_client.go:219 +0x578 fp=0xc000c09e78 sp=0xc000c09be8 pc=0x1200bd8
crypto/tls.(*Conn).clientHandshake-fm({0x153a030?, 0xc00072d080?})
	<autogenerated>:1 +0x39 fp=0xc000c09ea0 sp=0xc000c09e78 pc=0x1223279
crypto/tls.(*Conn).handshakeContext(0xc000022380, {0x153a068, 0xc0000260c8})
	/usr/local/go/src/crypto/tls/conn.go:1452 +0x3d1 fp=0xc000c09f70 sp=0xc000c09ea0 pc=0x11feb91
crypto/tls.(*Conn).HandshakeContext(...)
	/usr/local/go/src/crypto/tls/conn.go:1402
net/http.(*persistConn).addTLS.func2()
	/usr/local/go/src/net/http/transport.go:1537 +0x71 fp=0xc000c09fe0 sp=0xc000c09f70 pc=0x1282991
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000c09fe8 sp=0xc000c09fe0 pc=0x10639c1
created by net/http.(*persistConn).addTLS
	/usr/local/go/src/net/http/transport.go:1533 +0x345

goroutine 1 [select]:
net/http.(*Transport).getConn(0x1f327c0, 0xc0007acc80, {{}, 0x0, {0xc00079df20, 0x5}, {0xc000a5f7d0, 0xe}, 0x0})
	/usr/local/go/src/net/http/transport.go:1375 +0x5c6
net/http.(*Transport).roundTrip(0x1f327c0, 0xc000779900)
	/usr/local/go/src/net/http/transport.go:581 +0x76f
net/http.(*Transport).RoundTrip(0x100e985?, 0x15371c0?)
	/usr/local/go/src/net/http/roundtrip.go:17 +0x19
net/http.send(0xc000779900, {0x15371c0, 0x1f327c0}, {0x13e26c0?, 0x1?, 0x0?})
	/usr/local/go/src/net/http/client.go:252 +0x5d8
net/http.(*Client).send(0x1f39020, 0xc000779900, {0x203000?, 0xc0007d13e0?, 0x0?})
	/usr/local/go/src/net/http/client.go:176 +0x9b
net/http.(*Client).do(0x1f39020, 0xc000779900)
	/usr/local/go/src/net/http/client.go:725 +0x8f5
net/http.(*Client).Do(...)
	/usr/local/go/src/net/http/client.go:593
main.Env.exec({{0xc0007ca340?, 0x0?}, {0xc000a5f780?, 0xc0007ab988?}}, {0x153a068, 0xc0000260c8}, 0x13888e0?, {{0xc0006e3610, 0x8}, {0xc0006e3618, ...}, ...}, ...)
	/Volumes/git/cq/main.go:612 +0x5d9
main.commands.func1(0xc0005d6500?, {0x13f144a?, 0x2?, 0x2?})
	/Volumes/git/cq/main.go:433 +0x2d2
github.com/spf13/cobra.(*Command).execute(0xc0005d6500, {0xc000786ac0, 0x2, 0x2})
	/Users/hherman/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x1f333e0)
	/Users/hherman/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/hherman/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.run()
	/Volumes/git/cq/main.go:85 +0x265
main.main()
	/Volumes/git/cq/main.go:35 +0x19

goroutine 9 [chan receive]:
net/http.(*persistConn).addTLS(0xc00095b560, {0x153a068?, 0xc0000260c8}, {0xc000a5f7d0, 0x9}, 0x0)
	/usr/local/go/src/net/http/transport.go:1543 +0x365
net/http.(*Transport).dialConn(0x1f327c0, {0x153a068, 0xc0000260c8}, {{}, 0x0, {0xc00079df20, 0x5}, {0xc000a5f7d0, 0xe}, 0x0})
	/usr/local/go/src/net/http/transport.go:1617 +0x9e5
net/http.(*Transport).dialConnFor(0x0?, 0xc00014a370)
	/usr/local/go/src/net/http/transport.go:1449 +0xb0
created by net/http.(*Transport).queueForDial
	/usr/local/go/src/net/http/transport.go:1418 +0x3d2

rax    0x7ff801dedea6
rbx    0xc000c09250
rcx    0x0
rdx    0x0
rdi    0x0
rsi    0x0
rbp    0x700004257ec0
rsp    0x700004257eb8
r8     0x0
r9     0x0
r10    0x7ff842f96d38
r11    0x11ddee0
r12    0x0
r13    0x8
r14    0xc0006c91e0
r15    0x2400712
rip    0x7ff801bdf03a
rflags 0x10246
cs     0x2b
fs     0x0
gs     0x0
cq: exit exit status 2
SIGILL: illegal instruction
PC=0x7ff801bdf03a m=17 sigcode=1
instruction bytes: 0xf 0xb 0x48 0x8d 0x5 0x88 0xee 0x20 0x0 0x48 0x89 0x5 0xc6 0xe9 0x58 0x41

goroutine 0 [idle]:
crypto/x509/internal/macos.syscall(0xc00000e240?, 0x0?, 0x11ddfc0?, 0xc0005512f0?, 0x100c22b?, 0x13b2be0?, 0xc00000e240?)
	/usr/local/go/src/runtime/sys_darwin.go:99 +0x58 fp=0xc0005512a0 sp=0xc000551240 pc=0x1060758
crypto/x509/internal/macos.CFRelease(0xc000551348?)
	/usr/local/go/src/crypto/x509/internal/macos/corefoundation.go:152 +0x34 fp=0xc0005512e8 sp=0xc0005512a0 pc=0x11dd3d4
crypto/x509/internal/macos.ReleaseCFArray(0xc000551360?)
	/usr/local/go/src/crypto/x509/internal/macos/corefoundation.go:204 +0x2c fp=0xc000551318 sp=0xc0005512e8 pc=0x11dd60c
crypto/x509.(*Certificate).systemVerify.func1()
	/usr/local/go/src/crypto/x509/root_darwin.go:14 +0x26 fp=0xc000551330 sp=0xc000551318 pc=0x11e6d46
runtime.deferreturn()
	/usr/local/go/src/runtime/panic.go:436 +0x33 fp=0xc000551370 sp=0xc000551330 pc=0x1033173
crypto/x509.(*Certificate).systemVerify(0xc0007a8580, 0xc000551718)
	/usr/local/go/src/crypto/x509/root_darwin.go:35 +0x477 fp=0xc0005515c8 sp=0xc000551370 pc=0x11e6637
crypto/x509.(*Certificate).Verify(0xc0007a8580, {{0xc000439790, 0x9}, 0xc0007fdc80, 0x0, {0xc0abd8d0782f0e80, 0x5bd29d5, 0x1f39460}, {0x0, 0x0, ...}, ...})
	/usr/local/go/src/crypto/x509/verify.go:747 +0x4c7 fp=0xc000551718 sp=0xc0005515c8 pc=0x11ea6e7
crypto/tls.(*Conn).verifyServerCertificate(0xc000022380, {0xc00000e1f8, 0x1, 0x1})
	/usr/local/go/src/crypto/tls/handshake_client.go:868 +0x658 fp=0xc0005519a0 sp=0xc000551718 pc=0x1205238
crypto/tls.(*clientHandshakeStateTLS13).readServerCertificate(0xc000551d98)
	/usr/local/go/src/crypto/tls/handshake_client_tls13.go:457 +0x2d1 fp=0xc000551bb0 sp=0xc0005519a0 pc=0x1207ab1
crypto/tls.(*clientHandshakeStateTLS13).handshake(0xc000551d98)
	/usr/local/go/src/crypto/tls/handshake_client_tls13.go:87 +0x1d9 fp=0xc000551be8 sp=0xc000551bb0 pc=0x1205bf9
crypto/tls.(*Conn).clientHandshake(0xc000022380, {0x153a030, 0xc0009344c0})
	/usr/local/go/src/crypto/tls/handshake_client.go:219 +0x578 fp=0xc000551e78 sp=0xc000551be8 pc=0x1200bd8
crypto/tls.(*Conn).clientHandshake-fm({0x153a030?, 0xc0009344c0?})
	<autogenerated>:1 +0x39 fp=0xc000551ea0 sp=0xc000551e78 pc=0x1223279
crypto/tls.(*Conn).handshakeContext(0xc000022380, {0x153a068, 0xc0000260c8})
	/usr/local/go/src/crypto/tls/conn.go:1452 +0x3d1 fp=0xc000551f70 sp=0xc000551ea0 pc=0x11feb91
crypto/tls.(*Conn).HandshakeContext(...)
	/usr/local/go/src/crypto/tls/conn.go:1402
net/http.(*persistConn).addTLS.func2()
	/usr/local/go/src/net/http/transport.go:1537 +0x71 fp=0xc000551fe0 sp=0xc000551f70 pc=0x1282991
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000551fe8 sp=0xc000551fe0 pc=0x10639c1
created by net/http.(*persistConn).addTLS
	/usr/local/go/src/net/http/transport.go:1533 +0x345

goroutine 50 [syscall]:
crypto/x509/internal/macos.syscall(0xc00000e240?, 0x0?, 0x11ddfc0?, 0xc0005512f0?, 0x100c22b?, 0x13b2be0?, 0xc00000e240?)
	/usr/local/go/src/runtime/sys_darwin.go:99 +0x58 fp=0xc0005512a0 sp=0xc000551240 pc=0x1060758
crypto/x509/internal/macos.CFRelease(0xc000551348?)
	/usr/local/go/src/crypto/x509/internal/macos/corefoundation.go:152 +0x34 fp=0xc0005512e8 sp=0xc0005512a0 pc=0x11dd3d4
crypto/x509/internal/macos.ReleaseCFArray(0xc000551360?)
	/usr/local/go/src/crypto/x509/internal/macos/corefoundation.go:204 +0x2c fp=0xc000551318 sp=0xc0005512e8 pc=0x11dd60c
crypto/x509.(*Certificate).systemVerify.func1()
	/usr/local/go/src/crypto/x509/root_darwin.go:14 +0x26 fp=0xc000551330 sp=0xc000551318 pc=0x11e6d46
runtime.deferreturn()
	/usr/local/go/src/runtime/panic.go:436 +0x33 fp=0xc000551370 sp=0xc000551330 pc=0x1033173
crypto/x509.(*Certificate).systemVerify(0xc0007a8580, 0xc000551718)
	/usr/local/go/src/crypto/x509/root_darwin.go:35 +0x477 fp=0xc0005515c8 sp=0xc000551370 pc=0x11e6637
crypto/x509.(*Certificate).Verify(0xc0007a8580, {{0xc000439790, 0x9}, 0xc0007fdc80, 0x0, {0xc0abd8d0782f0e80, 0x5bd29d5, 0x1f39460}, {0x0, 0x0, ...}, ...})
	/usr/local/go/src/crypto/x509/verify.go:747 +0x4c7 fp=0xc000551718 sp=0xc0005515c8 pc=0x11ea6e7
crypto/tls.(*Conn).verifyServerCertificate(0xc000022380, {0xc00000e1f8, 0x1, 0x1})
	/usr/local/go/src/crypto/tls/handshake_client.go:868 +0x658 fp=0xc0005519a0 sp=0xc000551718 pc=0x1205238
crypto/tls.(*clientHandshakeStateTLS13).readServerCertificate(0xc000551d98)
	/usr/local/go/src/crypto/tls/handshake_client_tls13.go:457 +0x2d1 fp=0xc000551bb0 sp=0xc0005519a0 pc=0x1207ab1
crypto/tls.(*clientHandshakeStateTLS13).handshake(0xc000551d98)
	/usr/local/go/src/crypto/tls/handshake_client_tls13.go:87 +0x1d9 fp=0xc000551be8 sp=0xc000551bb0 pc=0x1205bf9
crypto/tls.(*Conn).clientHandshake(0xc000022380, {0x153a030, 0xc0009344c0})
	/usr/local/go/src/crypto/tls/handshake_client.go:219 +0x578 fp=0xc000551e78 sp=0xc000551be8 pc=0x1200bd8
crypto/tls.(*Conn).clientHandshake-fm({0x153a030?, 0xc0009344c0?})
	<autogenerated>:1 +0x39 fp=0xc000551ea0 sp=0xc000551e78 pc=0x1223279
crypto/tls.(*Conn).handshakeContext(0xc000022380, {0x153a068, 0xc0000260c8})
	/usr/local/go/src/crypto/tls/conn.go:1452 +0x3d1 fp=0xc000551f70 sp=0xc000551ea0 pc=0x11feb91
crypto/tls.(*Conn).HandshakeContext(...)
	/usr/local/go/src/crypto/tls/conn.go:1402
net/http.(*persistConn).addTLS.func2()
	/usr/local/go/src/net/http/transport.go:1537 +0x71 fp=0xc000551fe0 sp=0xc000551f70 pc=0x1282991
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000551fe8 sp=0xc000551fe0 pc=0x10639c1
created by net/http.(*persistConn).addTLS
	/usr/local/go/src/net/http/transport.go:1533 +0x345

goroutine 1 [select]:
net/http.(*Transport).getConn(0x1f327c0, 0xc000905ac0, {{}, 0x0, {0xc00045b8c0, 0x5}, {0xc000439790, 0xe}, 0x0})
	/usr/local/go/src/net/http/transport.go:1375 +0x5c6
net/http.(*Transport).roundTrip(0x1f327c0, 0xc00096bf00)
	/usr/local/go/src/net/http/transport.go:581 +0x76f
net/http.(*Transport).RoundTrip(0x100e985?, 0x15371c0?)
	/usr/local/go/src/net/http/roundtrip.go:17 +0x19
net/http.send(0xc00096bf00, {0x15371c0, 0x1f327c0}, {0x13e26c0?, 0x1?, 0x0?})
	/usr/local/go/src/net/http/client.go:252 +0x5d8
net/http.(*Client).send(0x1f39020, 0xc00096bf00, {0x203000?, 0xc000c63470?, 0x0?})
	/usr/local/go/src/net/http/client.go:176 +0x9b
net/http.(*Client).do(0x1f39020, 0xc00096bf00)
	/usr/local/go/src/net/http/client.go:725 +0x8f5
net/http.(*Client).Do(...)
	/usr/local/go/src/net/http/client.go:593
main.Env.exec({{0xc000900860?, 0x0?}, {0xc000439740?, 0xc000471988?}}, {0x153a068, 0xc0000260c8}, 0x13888e0?, {{0xc00037f410, 0x8}, {0xc00037f418, ...}, ...}, ...)
	/Volumes/git/cq/main.go:612 +0x5d9
main.commands.func1(0xc000799180?, {0x13f144a?, 0x2?, 0x2?})
	/Volumes/git/cq/main.go:433 +0x2d2
github.com/spf13/cobra.(*Command).execute(0xc000799180, {0xc000b744e0, 0x2, 0x2})
	/Users/hherman/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x1f333e0)
	/Users/hherman/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/hherman/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.run()
	/Volumes/git/cq/main.go:85 +0x265
main.main()
	/Volumes/git/cq/main.go:35 +0x19

goroutine 11 [chan receive]:
net/http.(*persistConn).addTLS(0xc00030f9e0, {0x153a068?, 0xc0000260c8}, {0xc000439790, 0x9}, 0x0)
	/usr/local/go/src/net/http/transport.go:1543 +0x365
net/http.(*Transport).dialConn(0x1f327c0, {0x153a068, 0xc0000260c8}, {{}, 0x0, {0xc00045b8c0, 0x5}, {0xc000439790, 0xe}, 0x0})
	/usr/local/go/src/net/http/transport.go:1617 +0x9e5
net/http.(*Transport).dialConnFor(0x0?, 0xc000142370)
	/usr/local/go/src/net/http/transport.go:1449 +0xb0
created by net/http.(*Transport).queueForDial
	/usr/local/go/src/net/http/transport.go:1418 +0x3d2

rax    0x7ff801dedea6
rbx    0xc000551250
rcx    0x0
rdx    0x0
rdi    0x0
rsi    0x0
rbp    0x70000632bec0
rsp    0x70000632beb8
r8     0x0
r9     0x0
r10    0x7ff842f96d38
r11    0x11ddee0
r12    0x0
r13    0x8
r14    0xc00087fa00
r15    0x2400712
rip    0x7ff801bdf03a
rflags 0x10246
cs     0x2b
fs     0x0
gs     0x0
```

**Comment by seankhliao** [comment]
macos version?

**Comment by randall77** [comment]
Not sure what would cause this? Can you post a reproducer? Without one, it will be hard to make progress.

Or, if you could bisect to figure out what CL fixed it for you, that might shed some light on the cause.

**Comment by radhus** [comment]
This looks like the same crash as in #54590, reproducer exists there.
