### ISSUE TITLE
x/tools/go/pointer: TestInput panics with index out of range

### ISSUE THREAD

**Issue by cherrymui** [golang/go#54101]
[2022-07-22T21:31:20-a2a2477-c5da4fb/windows-amd64-longtest](https://build.golang.org/log/db36ae31bb8a3d6ad838c69ec92e2aef049a70cc)

```
--- FAIL: TestInput (150.23s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 402 [running]:
testing.tRunner.func1.2({0x16aca60, 0xc3ba4f9e90})
	C:/workdir/go/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
	C:/workdir/go/src/testing/testing.go:1399 +0x39f
panic({0x16aca60, 0xc3ba4f9e90})
	C:/workdir/go/src/runtime/panic.go:884 +0x212
golang.org/x/tools/go/pointer_test.doOneInput(0x16d0c27?, {0xc0134c6d00, 0x8fa}, {0xc3c27928c0, 0x47})
	C:/workdir/gopath/src/golang.org/x/tools/go/pointer/pointer_test.go:216 +0x2213
golang.org/x/tools/go/pointer_test.TestInput(0xc002db1520)
	C:/workdir/gopath/src/golang.org/x/tools/go/pointer/pointer_test.go:641 +0x37d
testing.tRunner(0xc002db1520, 0x16e4518)
	C:/workdir/go/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	C:/workdir/go/src/testing/testing.go:1493 +0x35f
FAIL	golang.org/x/tools/go/pointer	154.846s
```

**Comment by cherrymui** [comment]
cc @timothy-king

**Comment by timothy-king** [comment]
I think this is a flake. Unassigning myself for now. I'll take a deeper look if it crops up again.

**Comment by adonovan** [comment]
x/tools/go/pointer was deleted; see #59676.
