### ISSUE TITLE
cmd/compile: panic during early deadcode while compiling

### ISSUE THREAD

**Issue by dsxack** [golang/go#54125]
### What version of Go are you using (`go version`)?

<pre>
go version go1.19rc2 darwin/arm64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/dmitriysmotrov/Library/Caches/go-build"
GOENV="/Users/dmitriysmotrov/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/dmitriysmotrov/.gvm/pkgsets/go1.19rc2/global/pkg/mod"
GONOPROXY="git.omprussia.ru"
GONOSUMDB="git.omprussia.ru"
GOOS="darwin"
GOPATH="/Users/dmitriysmotrov/.gvm/pkgsets/go1.19rc2/global"
GOPRIVATE="git.omprussia.ru"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/dmitriysmotrov/.gvm/gos/go1.19rc2"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/dmitriysmotrov/.gvm/gos/go1.19rc2/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19rc2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/z5/8ts06jv92yjc5sp5mdsdzr2h0000gn/T/go-build592114221=/tmp/go-build -gno-record-gcc-switches -fno-common
</pre></details>

### What did you do?

go install github.com/gopasspw/gopass@latest

### What did you expect to see?

program is installed without errors

### What did you see instead?

```
# github.com/hashicorp/errwrap
.gvm/pkgsets/go1.19rc2/global/pkg/mod/github.com/hashicorp/errwrap@v1.1.0/errwrap.go:72:35: internal compiler error: 'ContainsType': panic during early deadcode while compiling ContainsType:

runtime error: invalid memory address or nil pointer dereference

goroutine 16 [running]:
cmd/compile/internal/ssa.Compile.func1()
	/Users/dmitriysmotrov/.gvm/gos/go1.19rc2/src/cmd/compile/internal/ssa/compile.go:50 +0x6c
panic({0x104aceee0, 0x104fcba50})
	/Users/dmitriysmotrov/.gvm/gos/go1.19rc2/src/runtime/panic.go:884 +0x204
cmd/compile/internal/ssa.deadcode(0x140002fcfc0)
	/Users/dmitriysmotrov/.gvm/gos/go1.19rc2/src/cmd/compile/internal/ssa/deadcode.go:273 +0x6c4
cmd/compile/internal/ssa.Compile(0x140002fcfc0)
	/Users/dmitriysmotrov/.gvm/gos/go1.19rc2/src/cmd/compile/internal/ssa/compile.go:98 +0x8e8
cmd/compile/internal/ssagen.buildssa(0x140005363c0, 0x3)
	/Users/dmitriysmotrov/.gvm/gos/go1.19rc2/src/cmd/compile/internal/ssagen/ssa.go:574 +0x1c50
cmd/compile/internal/ssagen.Compile(0x140005363c0, 0x1048d4dd4?)
	/Users/dmitriysmotrov/.gvm/gos/go1.19rc2/src/cmd/compile/internal/ssagen/pgen.go:183 +0x30
cmd/compile/internal/gc.compileFunctions.func4.1(0x0?)
	/Users/dmitriysmotrov/.gvm/gos/go1.19rc2/src/cmd/compile/internal/gc/compile.go:153 +0x3c
cmd/compile/internal/gc.compileFunctions.func3.1()
	/Users/dmitriysmotrov/.gvm/gos/go1.19rc2/src/cmd/compile/internal/gc/compile.go:140 +0x48
created by cmd/compile/internal/gc.compileFunctions.func3
	/Users/dmitriysmotrov/.gvm/gos/go1.19rc2/src/cmd/compile/internal/gc/compile.go:138 +0x7c



Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new
```

**Comment by cherrymui** [comment]
What version of macOS are you using? Thanks.

**Comment by andig** [comment]
No panic for me on M1/ 12.4:

```
go1.19rc2 install github.com/gopasspw/gopass@latest
go: downloading github.com/gopasspw/gopass v1.14.3
go: downloading github.com/urfave/cli/v2 v2.8.1
go: downloading github.com/blang/semver/v4 v4.0.0
go: downloading bitbucket.org/creachadair/stringset v0.0.10
go: downloading github.com/mattn/go-tty v0.0.4
go: downloading github.com/schollz/closestmatch v0.0.0-20190308193919-1fbe626be92e
go: downloading filippo.io/age v1.0.0
go: downloading github.com/twpayne/go-pinentry v0.2.0
go: downloading github.com/ProtonMail/go-crypto v0.0.0-20220517143526-88bb52951d5b
go: downloading github.com/caspr-io/yamlpath v0.0.0-20200722075116-502e8d113a9b
go: downloading github.com/muesli/crunchy v0.4.0
go: downloading github.com/martinhoefling/goxkcdpwgen v0.1.1
go: downloading github.com/jsimonetti/pwscheme v0.0.0-20220125093853-4d9895f5db73
go: downloading golang.org/x/net v0.0.0-20220524220425-1d687d428aca
go: downloading github.com/atotto/clipboard v0.1.4
go: downloading github.com/mitchellh/go-ps v1.0.0
go: downloading github.com/gokyle/twofactor v1.0.1
go: downloading github.com/skip2/go-qrcode v0.0.0-20200617195104-da1b6568686e
go: downloading filippo.io/edwards25519 v1.0.0
go: downloading github.com/hashicorp/errwrap v1.1.0
go: downloading github.com/rs/zerolog v1.26.1
go: downloading go.uber.org/multierr v1.8.0
go: downloading github.com/xrash/smetrics v0.0.0-20201216005158-039620a65673
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.2
go: downloading rsc.io/qr v0.2.0
go: downloading go.uber.org/atomic v1.9.0
```

**Comment by dsxack** [comment]
@cherrymui macOS Ventura beta 13.0 (22A5311f)

**Comment by cherrymui** [comment]
See #53800 . It is a bug in the beta  OS. Thanks.

**Comment by dsxack** [comment]
Thank you.
