### ISSUE TITLE
x/tools/go/analysis/passes/printf: panic analysing some wrong format pattern

### ISSUE THREAD

**Issue by timonwong** [golang/go#54828]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

```go
package main

import "fmt"

func main() {
	fmt.Printf("%[3]*.[2*[1]f", 1, 2, 3)
}
```

### What did you expect to see?

The analyzer should shows error: "format has invalid argument index [2*[1]"

### What did you see instead?

Panic:

```
panic: runtime error: slice bounds out of range [7:3]

goroutine 574 [running]:
golang.org/x/tools/go/analysis/passes/printf.(*formatState).parseIndex(0x14005d16d80)
        /Users/timonwong/Projects/Casual/go-x-tools/go/analysis/passes/printf/printf.go:682 +0x310
golang.org/x/tools/go/analysis/passes/printf.(*formatState).parsePrecision(0x14005d16d80)
        /Users/timonwong/Projects/Casual/go-x-tools/go/analysis/passes/printf/printf.go:717 +0xbc
golang.org/x/tools/go/analysis/passes/printf.parsePrintfVerb(0x140060600d0, 0x1400a30f780, {0x14005d32340, 0x8}, {0x14009edd8d1, 0xd}, 0x1, 0x1)
        /Users/timonwong/Projects/Casual/go-x-tools/go/analysis/passes/printf/printf.go:753 +0x3fc
golang.org/x/tools/go/analysis/passes/printf.checkPrintf(0x140060600d0?, 0x2, 0x1400a30f780, 0x1010621e8?)
        /Users/timonwong/Projects/Casual/go-x-tools/go/analysis/passes/printf/printf.go:592 +0x178
golang.org/x/tools/go/analysis/passes/printf.checkCall.func1({0x1011a5828?, 0x1400a30f780})
        /Users/timonwong/Projects/Casual/go-x-tools/go/analysis/passes/printf/printf.go:481 +0x68
golang.org/x/tools/go/ast/inspector.(*Inspector).Preorder(0x1400a294768, {0x14000297a28?, 0x1?, 0x140048ed880?}, 0x14009e53a38)
        /Users/timonwong/Projects/Casual/go-x-tools/go/ast/inspector/inspector.go:77 +0xa8
golang.org/x/tools/go/analysis/passes/printf.checkCall(0x140060600d0)
        /Users/timonwong/Projects/Casual/go-x-tools/go/analysis/passes/printf/printf.go:476 +0x90
golang.org/x/tools/go/analysis/passes/printf.run(0x101166bc0?)
        /Users/timonwong/Projects/Casual/go-x-tools/go/analysis/passes/printf/printf.go:141 +0x70
golang.org/x/tools/go/analysis/internal/checker.(*action).execOnce(0x14008532dc0)
        /Users/timonwong/Projects/Casual/go-x-tools/go/analysis/internal/checker/checker.go:731 +0x940
sync.(*Once).doSlow(0x14009e49f98?, 0x1010b8238?)
        /opt/homebrew/Cellar/go/1.19/libexec/src/sync/once.go:74 +0x104
sync.(*Once).Do(...)
        /opt/homebrew/Cellar/go/1.19/libexec/src/sync/once.go:65
golang.org/x/tools/go/analysis/internal/checker.(*action).exec(0x14009d90f78?)
        /Users/timonwong/Projects/Casual/go-x-tools/go/analysis/internal/checker/checker.go:619 +0x40
golang.org/x/tools/go/analysis/internal/checker.execAll.func1(0x0?)
        /Users/timonwong/Projects/Casual/go-x-tools/go/analysis/internal/checker/checker.go:607 +0x24
created by golang.org/x/tools/go/analysis/internal/checker.execAll
        /Users/timonwong/Projects/Casual/go-x-tools/go/analysis/internal/checker/checker.go:613 +0x168
```

**Comment by timonwong** [comment]
I've submitted PR here: https://github.com/golang/tools/pull/395

**Comment by heschi** [comment]
cc @matloob @timothy-king @guodongli-google @zpavlinovic
