### ISSUE TITLE
x/tools: timeout in TestManuallyCreatingXTest

### ISSUE THREAD

**Issue by mknyszek** [golang/go#54934]
[2022-09-02T05:05:13-33c1ddd-8e35910/darwin-arm64-12](https://build.golang.org/log/0a8f493d3fb8e24f293c7a993566e49225c6cfa9)

CC @golang/tools-team

**Comment by adonovan** [comment]
The test is waiting for a stuck `go list` subprocess to finishing printing package metadata for a diagnostics operation:

```
goroutine 17832 [chan receive, 9 minutes]:
os/exec.(*Cmd).Wait(0x14006543340)
	/tmp/buildlet/go/src/os/exec/exec.go:608 +0x1c4
golang.org/x/tools/internal/gocommand.runCmdContext.func1()
	/tmp/buildlet/gopath/src/golang.org/x/tools/internal/gocommand/invoke.go:243 +0x28
created by golang.org/x/tools/internal/gocommand.runCmdContext
	/tmp/buildlet/gopath/src/golang.org/x/tools/internal/gocommand/invoke.go:242 +0xa0

goroutine 16649 [chan receive, 9 minutes]:
golang.org/x/tools/internal/gocommand.runCmdContext({0x102c71410, 0x14003fb9920}, 0x14006543340)
	/tmp/buildlet/gopath/src/golang.org/x/tools/internal/gocommand/invoke.go:260 +0x19c
golang.org/x/tools/internal/gocommand.(*Invocation).run(0x140056a1108, {0x102c71410, 0x14003fb9920}, {0x102c69978?, 0x14002165e30}, {0x102c69978?, 0x14002165e60})
	/tmp/buildlet/gopath/src/golang.org/x/tools/internal/gocommand/invoke.go:232 +0xcc4
golang.org/x/tools/internal/gocommand.(*Invocation).runWithFriendlyError(0x140056a10d0?, {0x102c71410, 0x14003fb9920}, {0x102c69978?, 0x14002165e30?}, {0x102c69978?, 0x14002165e60?})
	/tmp/buildlet/gopath/src/golang.org/x/tools/internal/gocommand/invoke.go:154 +0x40
golang.org/x/tools/internal/gocommand.(*Runner).runConcurrent(0x140043fb3e0, {0x102c71410, 0x14003fb9920}, {{0x10280a05f, 0x4}, {0x14006ffc540, 0x9, 0xe}, {0x1032060a8, 0x0, ...}, ...})
	/tmp/buildlet/gopath/src/golang.org/x/tools/internal/gocommand/invoke.go:98 +0xf8
golang.org/x/tools/internal/gocommand.(*Runner).RunRaw(0x14000366fc0?, {0x102c71410, 0x14003fb9920}, {{0x10280a05f, 0x4}, {0x14006ffc540, 0x9, 0xe}, {0x1032060a8, 0x0, ...}, ...})
	/tmp/buildlet/gopath/src/golang.org/x/tools/internal/gocommand/invoke.go:73 +0x64
golang.org/x/tools/go/packages.(*golistState).invokeGo(0x14006245720?, {0x10280a05f?, 0x4?}, {0x14006ffc540?, 0x9, 0xe?})
	/tmp/buildlet/gopath/src/golang.org/x/tools/go/packages/golist.go:945 +0x25c
golang.org/x/tools/go/packages.(*golistState).createDriverResponse(0x14006245720, {0x14006929a40, 0x1, 0x1})
	/tmp/buildlet/gopath/src/golang.org/x/tools/go/packages/golist.go:453 +0x78
golang.org/x/tools/go/packages.goListDriver(0x14006ffc468, {0x14001df78a0, 0x1, 0x140061d58b0?})
	/tmp/buildlet/gopath/src/golang.org/x/tools/go/packages/golist.go:199 +0x6ec
golang.org/x/tools/go/packages.defaultDriver(0x140058c38c0?, {0x14001df78a0, 0x1, 0x1})
	/tmp/buildlet/gopath/src/golang.org/x/tools/go/packages/packages.go:271 +0x54
golang.org/x/tools/go/packages.Load(0x140027ea280?, {0x14001df78a0, 0x1, 0x1})
	/tmp/buildlet/gopath/src/golang.org/x/tools/go/packages/packages.go:254 +0x48
golang.org/x/tools/internal/lsp/cache.(*snapshot).load(0x140027ea280, {0x102c71448, 0x14002d74f60}, 0x0, {0x14001df7890, 0x1, 0x140056a30c8?})
	/tmp/buildlet/gopath/src/golang.org/x/tools/internal/lsp/cache/load.go:120 +0xb40
golang.org/x/tools/internal/lsp/cache.(*snapshot).reloadWorkspace(0x140027ea280, {0x102c71448, 0x14002d74f60})
	/tmp/buildlet/gopath/src/golang.org/x/tools/internal/lsp/cache/snapshot.go:1522 +0x208
golang.org/x/tools/internal/lsp/cache.(*snapshot).awaitLoadedAllErrors(0x140027ea280, {0x102c71448, 0x14002d74f60})
	/tmp/buildlet/gopath/src/golang.org/x/tools/internal/lsp/cache/snapshot.go:1457 +0x180
golang.org/x/tools/internal/lsp/cache.(*snapshot).awaitLoaded(0x140027ea280, {0x102c71448?, 0x14002d74f60?})
	/tmp/buildlet/gopath/src/golang.org/x/tools/internal/lsp/cache/snapshot.go:1344 +0x38
golang.org/x/tools/internal/lsp/cache.(*snapshot).activePackageHandles(0x0?, {0x102c71448, 0x14002d74f60})
	/tmp/buildlet/gopath/src/golang.org/x/tools/internal/lsp/cache/snapshot.go:1071 +0x2c
golang.org/x/tools/internal/lsp/cache.(*snapshot).ActivePackages(0x14000192780?, {0x102c71448, 0x14002d74f60})
	/tmp/buildlet/gopath/src/golang.org/x/tools/internal/lsp/cache/snapshot.go:1055 +0x2c
golang.org/x/tools/internal/lsp/mod.DiagnosticsForMod({0x102c71448, 0x14002d74f60}, {0x102c7d1f8, 0x140027ea280}, {0x12ac07298, 0x14004599100})
	/tmp/buildlet/gopath/src/golang.org/x/tools/internal/lsp/mod/diagnostics.go:89 +0x6b4
golang.org/x/tools/internal/lsp/mod.Diagnostics({0x102c71448, 0x14002d74d20}, {0x102c7d1f8, 0x140027ea280})
	/tmp/buildlet/gopath/src/golang.org/x/tools/internal/lsp/mod/diagnostics.go:31 +0x248
golang.org/x/tools/internal/lsp.(*Server).diagnose(0x140047197a0, {0x102c71448, 0x14002977d70}, {0x102c7d1f8, 0x140027ea280}, 0x0)
	/tmp/buildlet/gopath/src/golang.org/x/tools/internal/lsp/diagnostics.go:226 +0x24c
golang.org/x/tools/internal/lsp.(*Server).diagnoseSnapshot(0x140047197a0, {0x102c7d1f8, 0x140027ea280}, {0x14000e3ac70, 0x1, 0x1}, 0x78?)
	/tmp/buildlet/gopath/src/golang.org/x/tools/internal/lsp/diagnostics.go:153 +0x238
golang.org/x/tools/internal/lsp.(*Server).diagnoseSnapshots.func1({0x102c7d1f8?, 0x140027ea280?}, {0x14000e3ac70?, 0x102614690?, 0x14000192820?})
	/tmp/buildlet/gopath/src/golang.org/x/tools/internal/lsp/diagnostics.go:130 +0x78
created by golang.org/x/tools/internal/lsp.(*Server).diagnoseSnapshots
	/tmp/buildlet/gopath/src/golang.org/x/tools/internal/lsp/diagnostics.go:128 +0x6c
```

**Comment by bcmills** [comment]
Duplicate of #54461
