### ISSUE TITLE
x/perf: regressions dashboard broken

### ISSUE THREAD

**Issue by prattmic** [golang/go#55158]
https://perf.golang.org/dashboard/?benchmark=regressions is broken due to a panic in the handler:

```
2022/09/19 21:52:14 http2: panic serving 10.102.129.129:15437: runtime error: index out of range [341] with length 341
goroutine 2971853 [running]:
net/http.(*http2serverConn).runHandler.func1()
 /usr/local/go/src/net/http/h2_bundle.go:5896 +0x125
panic({0xeb82c0, 0xc0004128b8})
 /usr/local/go/src/runtime/panic.go:838 +0x207
golang.org/x/build/perf/app.renameBenchmarksWithRegressions({0xc0000a8700, 0xcf, 0xcf?}, 0xb7782e?)
 /app/perf/app/dashboard.go:394 +0x4bd
golang.org/x/build/perf/app.groupBenchmarkResults(0xf6c917?, 0x1)
 /app/perf/app/dashboard.go:426 +0x65
golang.org/x/build/perf/app.fetchAllBenchmarks({0x10a8b10, 0xc000b2b3c0}, {0x10a8d78, 0xc0007345c0}, 0x48?, {0x450797?, 0x23?, 0x1b8e440?}, {0xc0c25702dd2d545a, 0x1e0f2939c9606, ...})
 /app/perf/app/dashboard.go:272 +0x1a5
2022-09-19 14:52:14.146 PDT
...
```

I don't immediately see why this is occurring, but perhaps we have 2 benchmarks with the same name, leading to a collision in the regressions map. I can take a longer look later.

cc @dr2chase @mknyszek

**Comment by prattmic** [comment]
This has actually resolved itself, even when extending the view to 90 days, which is odd.
