### ISSUE TITLE
runtime: corruption in tests

### ISSUE THREAD

**Issue by rsc** [golang/go#55167]
```
#!watchflakes
default <- (log ~ `runtime.throw\(` || log ~ `^\s*fatal error:`) &&
	builder != "plan9-386-0intro" &&
	builder != "plan9-amd64-0intro" &&
	builder != "plan9-arm" &&
	builder != "linux-loong64-3a5000" &&
	!(builder ~ `(gotip|go1\.\d\d)-` && date < "2024-01-18")
```

This issue gathers flakes caused by runtime.throw, which should "never happen" and usually indicates some kind of corruption.

**Comment by rsc** [comment]
These are old failures. The goal for this bug is to be reopened each time there's a new otherwise uncategorized runtime.throw, and then we make a more specific issue for it, and close this one. And then the next time there's an uncategorized runtime.throw, watchflakes posts and reopens. So I will close this one right now.

**Comment by cherrymui** [comment]
This is #54596 . I updated pattern there.

For this issue, does watchflakes suppose to reopen it as it found a new failure? @rsc

**Comment by aclements** [comment]
> 2022-11-03 17:41 linux-amd64-staticlockranking go@5c0d314a os/signal.TestSignalTrace ([log](https://build.golang.org/log/af083d40156b011db2e0cadd6040692cf579967c))

This is #56554. I've added a pattern to that issue.

**Comment by bcmills** [comment]
That last one looks like a false-positive for this issue — maybe we need to update the regexp to only match `fatal error:` at the start of a line?

**Comment by cherrymui** [comment]
> maybe we need to update the regexp to only match fatal error: at the start of a line?

Makes sense. Done. Thanks.

**Comment by bcmills** [comment]
Filed #57170 for the above failure.

**Comment by bcmills** [comment]
The two `netbsd-arm-bsiegert` failures in November look like #57170.

**Comment by bcmills** [comment]
Split the `lock ordering problem` failures out into #58277.

**Comment by bcmills** [comment]
The `windows-amd64-race` issues might be related to #53539?

**Comment by bcmills** [comment]
Filed #58714 for the `windows-amd64-race` `checkptr` failures.

**Comment by bcmills** [comment]
Filed #58715 for the `darwin` `allocNeedsZero` failures.

**Comment by bcmills** [comment]
`loong64` is very noisy. Excluding from this issue so that `watchflakes` will file a new one for it.

**Comment by mknyszek** [comment]
Summarizing the recent failures, excluding the ppc64 failures (which were already tracked and resolved elsewhere):

<details><summary>2023-05-22 21:02 ios-arm64-corellium go@53e0616c net/http (<a href="https://build.golang.org/log/b1850ef66d91eceb717c6321c9f5ce696f0e133c">log</a>)</summary>

    fatal error: unexpected signal during runtime execution
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1b0fe8cc0]
    
    runtime stack:
    runtime.throw({0x1052a39b7?, 0x1fb0a6528?})
    	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/panic.go:1077 +0x40 fp=0x16b5ecee0 sp=0x16b5eceb0 pc=0x104f12b90
    runtime.sigpanic()
    	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/signal_unix.go:836 +0x380 fp=0x16b5ecf40 sp=0x16b5ecee0 pc=0x104f2a510
    runtime: g 0: unexpected return pc for runtime.sigpanic called from 0x1b0fe8cc4
    stack: frame={sp:0x16b5ecee0, fp:0x16b5ecf40} stack=[0x16b4f0328,0x16b5eef28)
    ...
    0x000000016b5ecfa0:  0x00000001fba50000  0x0000000000000030 
    0x000000016b5ecfb0:  0x000000000000001c  0x0000000000000001 
    0x000000016b5ecfc0:  0x000000010582ca00  0x0000000105824040 
    0x000000016b5ecfd0:  0x000000016b5ed408  0x000000010582ca00 
    0x000000016b5ecfe0:  0x000000016b5ed0b0  0x00000001fa955b08 
    0x000000016b5ecff0:  0x0000000000000001  0x00000001fb0a6528 
    0x000000016b5ed000:  0x000000016b5ed4a0  0x000000016b5eda18 
    0x000000016b5ed010:  0x0000000000000000  0x000000000000001c 
    0x000000016b5ed020:  0x0000000000000000  0x0000000000000007 
    0x000000016b5ed030:  0x000000016b5ed0a0  0x00000001a8360048 
</details>

<details><summary>2023-06-01 23:34 linux-mips64le-rtrk go@40c7be9b bootstrap/cmd/compile/internal/devirtualize [build] (<a href="https://build.golang.org/log/52dd0e9c3c40db8f5ce98ff7369362ade1c042e3">log</a>)</summary>

    fatal error: unexpected signal during runtime execution
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x33680]
    
    runtime stack:
    runtime.throw({0xb2e39b, 0x2a})
    	/tmp/genbootstrap-3894857761/go-linux-mips64le-bootstrap/src/runtime/panic.go:1198 +0x6c
    runtime.sigpanic()
    	/tmp/genbootstrap-3894857761/go-linux-mips64le-bootstrap/src/runtime/signal_unix.go:719 +0x328
    runtime.readgstatus(...)
    	/tmp/genbootstrap-3894857761/go-linux-mips64le-bootstrap/src/runtime/proc.go:889
    runtime.markroot(0xc00002f698, 0x2a)
    	/tmp/genbootstrap-3894857761/go-linux-mips64le-bootstrap/src/runtime/mgcmark.go:198 +0x228
    runtime.gcDrain(0xc00002f698, 0x3)
    	/tmp/genbootstrap-3894857761/go-linux-mips64le-bootstrap/src/runtime/mgcmark.go:1013 +0x534
    runtime.gcBgMarkWorker.func2()
    	/tmp/genbootstrap-3894857761/go-linux-mips64le-bootstrap/src/runtime/mgc.go:1269 +0xe4
    runtime.systemstack()
    	/tmp/genbootstrap-3894857761/go-linux-mips64le-bootstrap/src/runtime/asm_mips64x.s:191 +0x7c
</details>

<details><summary>2023-06-07 02:51 freebsd-arm-paulzhol go@ea51e92c (<a href="https://build.golang.org/log/acc474319f59955977b7073717dc03200874404f">log</a>)</summary>

    unexpected fault address 0x4d6149
    fatal error: fault
    [signal SIGBUS: bus error code=0x3 addr=0x4d6149 pc=0x1609c0]
    
    goroutine 4945 [running]:
    panic during panic
    SIGBUS: bus error
    PC=0x7cbd8 m=9 sigcode=3
    
    /tmp/workdir-host-freebsd-arm-paulzhol/go/src/make.bash: line 226:  1079 Bus error               ./cmd/dist/dist bootstrap -a $vflag $GO_DISTFLAGS "$@"
</details>

**Comment by bcmills** [comment]
Filed or updated:
- #60449
- #60850 
- #60888 
- #60889

**Comment by prattmic** [comment]
I have split the deadlock issue to #61454.

**Comment by bcmills** [comment]
Updated #60449 to include the above failure on `darwin/amd64`.

**Comment by mknyszek** [comment]
Filed:
- #62099
- #62100
- #62101
- #62102
- #62104
- #62105
- #62106

Untriaged (for my own tracking):
2023-08-11 01:59 linux-riscv64-unmatched go@33cdafed ([log](https://build.golang.org/log/b45cf7f549a39161fa18d0e15e657017c03c98da))
2023-08-07 06:21 linux-amd64-nocgo sys@60ecf133 go@288fd6eb x/sys/unix ([log](https://build.golang.org/log/4cee93eab8377380f0ae86725d81f691af91b3c3))
2023-08-01 14:26 linux-riscv64-unmatched go@d4b46b09 cmd/trace [build] ([log](https://build.golang.org/log/02e635dde7be042c3db8962404d52b2d8d4eefe2))
2023-08-07 19:27 linux-amd64-wsl tools@f42bca8e go@2c95fa4f x/tools/gopls/internal/lsp.TestLSP ([log](https://build.golang.org/log/e37b98b5db287da9a93d1d8712f4525d212bbfa6))

**Comment by mknyszek** [comment]
Filed https://github.com/golang/go/issues/62251 for freebsd/arm.
Updated https://github.com/golang/go/issues/60449 for the Darwin issues.

**Comment by mknyszek** [comment]
Carry forward:
2023-08-07 06:21 linux-amd64-nocgo sys@60ecf133 go@288fd6eb x/sys/unix ([log](https://build.golang.org/log/4cee93eab8377380f0ae86725d81f691af91b3c3))
2023-08-07 19:27 linux-amd64-wsl tools@f42bca8e go@2c95fa4f x/tools/gopls/internal/lsp.TestLSP ([log](https://build.golang.org/log/e37b98b5db287da9a93d1d8712f4525d212bbfa6))

**Comment by mknyszek** [comment]
Oh... this hasn't been showing up in triage, and I see why now. Ugh. Sorry about that. I'll make sure this gets done. (I've been also meaning to categorize the "unrecognized failures" issue; I'll handle this one and that one today.)

**Comment by mknyszek** [comment]
The OpenBSD failures are #63385.
The Darwin failures are #60449.
The linux-ppc64 failures are #64290.
The linux-386-longtest failure is fixed (I'm not certain if that had a bug or if it was fixed shortly after landing those CLs, but it's definitely not a problem now).

I think that covers everything except a few one-offs that we should just carry forward:
2023-09-05 22:26 linux-riscv64-unmatched go@972cc3e7 test.Test ([log](https://build.golang.org/log/8a5bdad61f98829330c45a41ff2636f79642a0af))
2023-11-21 19:26 linux-amd64-staticlockranking go@2e77b51d runtime.TestStackSwitchCallback ([log](https://build.golang.org/log/32f9bc97d127c07d2058b31ff5dc00b792b76290))

Carrying forward from last time:
2023-08-07 06:21 linux-amd64-nocgo sys@60ecf133 go@288fd6eb x/sys/unix ([log](https://build.golang.org/log/4cee93eab8377380f0ae86725d81f691af91b3c3))
2023-08-07 19:27 linux-amd64-wsl tools@f42bca8e go@2c95fa4f x/tools/gopls/internal/lsp.TestLSP ([log](https://build.golang.org/log/e37b98b5db287da9a93d1d8712f4525d212bbfa6))

**Comment by cherrymui** [comment]
Moved the last failure to #60449.
