### ISSUE TITLE
regexp: panic nil pointer dereference 

### ISSUE THREAD

**Issue by cuiweixie** [golang/go#56067]
### What version of Go are you using (`go version`)?

<pre>
$ go version
master
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

```
package main

import "regexp"

func main() {
	r, _ := regexp.Compile(`(?m)^ambiguous import: found package image in multiple modules:\s+image\s+.+\\(`)
	println(r.FindString(`ambiguous import: found package image in multiple modules:
	image ($WORK/gopath/src/a)
	 (/Users/xiecui/code/go/src/go/src/image)
`))
}

```

### What did you expect to see?

do not panic

### What did you see instead?
panic

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x90 pc=0x100f15500]

goroutine 1 [running]:
regexp.(*Regexp).doExecute(0x100f1ffca?, {0x0?, 0x0?}, {0x0?, 0x1010585b8?, 0x1400008c011?}, {0x100f20068?, 0x14000002228?}, 0x1400009cf28?, 0x100ea4064?, ...)
        /Users/xiecui/code/go/src/go/src/regexp/exec.go:527 +0x50
regexp.(*Regexp).FindString(0x100f1ffca?, {0x100f20068, 0x82})
        /Users/xiecui/code/go/src/go/src/regexp/regexp.go:852 +0x5c
main.main()
        /Users/xiecui/code/go/go_compiler/code/so/a.go:7 +0x40

```

**Comment by ianlancetaylor** [comment]
Check the error result of `regexp.Compile`.
