### ISSUE TITLE
affected/package: 

### ISSUE THREAD

**Issue by aathan** [golang/go#56341]
### What version of Go are you using (`go version`)?
go version go1.18.4 linux/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOVERSION="go1.18.4"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build911168599=/tmp/go-build -gno-record-gcc-switches"

### What did you do?

golang sometimes reports a double unlock of sync.Mutex *together* with a SIGSEGV. The latter seems unrelated to the double unlock, and may instead by the result of the panic reporting itself.

```
fatal error: sync: unlock of unlocked mutex
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6e5c99]
goroutine 117571030 [running]:
runtime.throw({0x7a220a?, 0xc02a7dd100?})
  /usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc0218e5610 sp=0xc0218e55e0 pc=0x435031
sync.throw({0x7a220a?, 0xc000130060?})
  /usr/local/go/src/runtime/panic.go:978 +0x1e fp=0xc0218e5630 sp=0xc0218e5610 pc=0x45fbbe
sync.(*Mutex).unlockSlow(0xc0359a3748, 0xffffffff)
  /usr/local/go/src/sync/mutex.go:220 +0x3c fp=0xc0218e5658 sp=0xc0218e5630 pc=0x476c5c
sync.(*Mutex).Unlock(...)
  /usr/local/go/src/sync/mutex.go:214
...

additional traces and goroutine dumps have been omitted for brevity and to maintain privacy

```

The code that generates this error is in a high-load server golang process that otherwise behaves as expected. While the double unlock may be factual, the associated SIGSEGV reported above seems unrelated to the sync.Mutex issue, which may be a bonafide race & logic error.

That's because the code that generates the panic dump is very similar in structure to the example code below, where a struct with an UnlockMe() "method" calls a contained sync.Mutex's Unlock(). As you can see below, calling such a struct's implementation of UnlockMe() on a nil struct pointer generates a panic at the dereference to access the contained mutex, never reaching the point in the sync.Mutex implementation that calls fatal("unlock of unlocked...")

Looking at the golang runtime and sync implementation the fact that the string “unlock of unlocked mutex” is emitted indicates that `unlockSlow() got to the point of calling fatal(), which I don't think could have happened if there were a nil struct pointer involved.

So where is the indicated SIGSEGV arising? I have not spelunked getg(), which is where the `gp` struct from which the signal is read comes from.

I first thought maybe golang panics by generating a spurious SIGSEGV (in C `*(int *)0=0`)? However, other panics, such as those in my examples below, do not report a SIGSEGV in the panic dumps.

A simple Unlock() of an unlocked mutex looks like this (main_simple() below):

```
fatal error: sync: unlock of unlocked mutex

goroutine 6 [running]:
runtime.throw({0x4a9fd6?, 0x0?})
	/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc000048748 sp=0xc000048718 pc=0x430791
sync.throw({0x4a9fd6?, 0x0?})
	/usr/local/go/src/runtime/panic.go:978 +0x1e fp=0xc000048768 sp=0xc000048748 pc=0x4594be

```

An Unlock of a Mutex in a struct `f` pointer where f==nil via f.m.Unlock()looks like this (main_direct() below):

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4556d6]

goroutine 1 [running]:
main.main()
	foo.go:59 +0x16
exit status 2

```
And finally unlocking a mutex contained in a struct pointed to by an `f==nil` pointer via a "method" of that struct looks like this:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4556d6]

goroutine 1 [running]:
main.(*foo).UnlockMe(...)
	foo.go:xx
main.main()
	foo.go:yy +0x16
```

Example code generating above errors:

```
type foo struct {
  a int
  b int
  m sync.Mutex
}

func (f *foo) UnlockMe(){
  f.m.Unlock()
}

func main_simple() {
  var m *sync.Mutex
  m.Unlock()
}

func main_direct() {
  var f *foo
  f.m.Unlock()
}

func main_via_f() {
  var f *foo
  f.UnlockMe()
}
```

Relevant source code from golang runtime:

```
func (m *Mutex) Unlock() {
	if race.Enabled {
		_ = m.state
		race.Release(unsafe.Pointer(m))
	}

	// Fast path: drop lock bit.
	new := atomic.AddInt32(&m.state, -mutexLocked)
	if new != 0 {
		// Outlined slow path to allow inlining the fast path.
		// To hide unlockSlow during tracing we skip one extra frame when tracing GoUnblock.
		m.unlockSlow(new)
	}
}

func (m *Mutex) unlockSlow(new int32) {
	if (new+mutexLocked)&mutexLocked == 0 {
		fatal("sync: unlock of unlocked mutex")
	}
...
func fatalthrow(t throwType) {
	pc := getcallerpc()
	sp := getcallersp()
	gp := getg()
...

		if dopanic_m(gp, pc, sp) {
...
func dopanic_m(gp *g, pc, sp uintptr) bool {
	if gp.sig != 0 {
		signame := signame(gp.sig)
		if signame != "" {
			print("[signal ", signame)
		} else {
			print("[signal ", hex(gp.sig))
		}
		print(" code=", hex(gp.sigcode0), " addr=", hex(gp.sigcode1), " pc=", hex(gp.sigpc), "]\n")
	}
```

So as we can see the SIGSEGV panic output comes from gp.sig, and gp comes from getg() ... which I have not tracked down the implementation of. However, the panic is started by the double unlock of the mutex. Where does the SIGSEGV come from though?

**Comment by fengyoulin** [comment]
Sorry, can you give any code that reproduces this problem?

**Comment by aathan** [comment]
@fengyoulin .... it's really non-trivial to reproduce the activity of this complex system. The only educated guess I have, which I mentioned above, is that the processing of the panic and/or any unwinding of active goroutines that happens while the panic is being emitted, then generates a fatal() (via extra Unlock) that "takes over" the error being reported.

I didn't think it would be simple to reproduce but it is:

```
go run foo.go
fatal error: sync: unlock of unlocked mutex
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x455758]
```

```
package main

import (
  "sync"
)

func main() {
  defer func() {
    var m sync.Mutex
    m.Unlock()
  }()
  var i *int
  var ii int
  *i=ii
}
```

So what this appears to be is a case of an double Unlock *during* a SIGSEGV panic.

I can't comment on whether the error reporting is therefore as intended, but it seems to me that the root cause is the SIGSEGV, and the double unlock then becomes the reported error, with the actual source of the initial panic somewhere in the call stack.

Perhaps this is less of a bug, and more of an unfortunate feature, since there is no explicit highlighting of the stack position that caused the defer unwinding other than the programmer knowing to look for the

```
runtime.sigpanic()
```

in the stack.

**Comment by fengyoulin** [comment]
Thanks. It looks like this: SIGSEGV triggered by user code is not a fatal error, but is converted to panic, which executes all defer functions. Here's the code in the defer function that double unlocks the mutex, which is some kind of fatal error, and kills the process. If so, it might be confusing, but it shouldn't be a bug. Or you can provide a more comprehensive stack trace for further analysis.

**Comment by aathan** [comment]
I'm not sure I agree with that statement. Ultimately, I think this issue has to do with how well golang supports and reports on exceptions that raise additional exceptions during handling of an (the first) exception.

There is both a presentation/reporting issue here, as well as (possibly) a problem with information loss.

The presentation issue is the way golang presents this exception chain: The programmer is given the impression that the double unlock is the root cause of the program's termination. It may be the proximal cause in the sense that it's the last exception seen, but it is in fact not the root cause. If the programmer were to fix the double unlock, which is also at the top of the emitted call stack, they might stop there, thinking they solved the problem ... in fact however, the root cause, the nil dereference, which is buried in the output, would still remain.

The (possible) information loss issue has to do with whether a fatal(message string) or panic(message string) that causes another fatal() or panic() would have been reported by golang such that BOTH error messages strings are available to the programmer when emitted.

From what I can tell in the runtime source code, the only reason the SIGSEGV appeared in the error report is that it was a signal. What if a double unlock of a different lock caused a double unlock of a second disparate lock in the defer() unwinding? Would the programmer see both double unlocks reported?

My guess is no, and I would consider that a bug or at least a high priority feature to add.

---

Getting back to your assessment that the SIGSEGV is not a fatal error, I think that's incorrect: A nil pointer reference is in fact a fatal error. It would terminate the program if it is not caught. The double unlock is ALSO a fatal error. Similarly, if it is not caught, it will result in program termination.

Caveat: I'm not super experienced with exception handling in go, but I'm assuming that both the double unlock and the nil dereference can be stopped from terminating the program by a recover()? In other words, they are in the same class of "catchable" error?

---

Looking at how other language handle the situation: Python (in late 2.x and in its 3.x versions), when exception processing raises another exception, the exceptions are clearly reported as the stack trace that caused one exception, and then separately, the stack trace which caused the following exception.

So, while I agree that perhaps this issue is not a bug per-se, since both the SIGSEGV and the double unlock appear "somewhere" in the output, golang's representation of the situation requires the programmer to dig -- and to be knowledgeable enough to understand which exception started the chain.

**Comment by aathan** [comment]
@dr2chase ok, and/but I can also add that:

```
func main() {
  defer func() {
    fmt.Println("hi")
    var m sync.Mutex
    m.Unlock()
  }()
  var m sync.Mutex
  m.Unlock()
}
```

does NOT call the defer()ed function (i.e., it's considered unrecoverable). Arguably, however, it's even more recoverable than a nil pointer error. I can imagine many ways and many programs that could perform useful shutdown processing after an extra Unlock.

Should some consideration be given to this issue?

Separately, should this issue at least be turned into a feature request to cause the panic reporting to at least highlight stack frames of other panic() fatal() sig...() calls etc in order to improve programmers' lives?

**Comment by fengyoulin** [comment]
As you can see, in golang a double unlock is a fatal or unrecoverable error, but a nil pointer dereference is not and can be handled by panic/recover. Incorrect synchronization logic between goroutines can lead to data corruption in the global scope, so it is more serious. The runtime always prints the error that caused the process to exit on the first line. Since we can always study the whole thing in the full stack trace, there is no need to print a very user friendly summary message on fatal errors.

Or, if you think it's really necessary, you can make a proposal.
