### ISSUE TITLE
debug/elf: index out of range triggered by DynamicSymbols()

### ISSUE THREAD

**Issue by rockdaboot** [golang/go#56429]
A malformed ELF file (generated through fuzzing, attached) caused this issue when calling DynamicSymbols().

### Stacktrace ###
```
/home/tim/src/go/bin/go test -run=FuzzGetBuildID/af27d09108d1449f--- FAIL: FuzzGetBuildID (0.08s)
    --- FAIL: FuzzGetBuildID/af27d09108d1449f (0.00s)
panic: runtime error: index out of range [1] with length 1 [recovered]
        panic: runtime error: index out of range [1] with length 1

goroutine 37 [running]:
testing.tRunner.func1.2({0xfe4dc0, 0xc000040e58})
        /home/tim/src/go/src/testing/testing.go:1451 +0x24e
testing.tRunner.func1()
        /home/tim/src/go/src/testing/testing.go:1454 +0x39f
panic({0xfe4dc0, 0xc000040e58})
        /home/tim/src/go/src/runtime/panic.go:884 +0x213
encoding/binary.littleEndian.Uint16(...)
        /home/tim/src/go/src/encoding/binary/binary.go:62
debug/elf.(*File).gnuVersion(0xc0005fed20, 0xc0001bc7e0?)
        /home/tim/src/go/src/debug/elf/file.go:1578 +0x77
debug/elf.(*File).DynamicSymbols(0xc0000cec80?)
        /home/tim/src/go/src/debug/elf/file.go:1457 +0xaa
github.com/optimyze/prodfiler/libpf/pfelf.GetDynamicSymbols(0xc0005fed20?)
        /home/tim/go/src/github.com/elastic/prodfiler/libpf/pfelf/pfelf.go:540 +0x19
github.com/optimyze/prodfiler/libpf/pfelf_test.FuzzGetBuildID.func1(0x0?, {0xc0003e7800?, 0x0?, 0x46c059?})
        /home/tim/go/src/github.com/elastic/prodfiler/libpf/pfelf/pfelf_test.go:80 +0xe9
reflect.Value.call({0xebb0a0?, 0x10e0920?, 0x13?}, {0x1057b29, 0x4}, {0xc000321e60, 0x2, 0x2?})
        /home/tim/src/go/src/reflect/value.go:586 +0xb09
reflect.Value.Call({0xebb0a0?, 0x10e0920?, 0x16fb7c0?}, {0xc000321e60?, 0x1054300?, 0xc0005be8b8?})
        /home/tim/src/go/src/reflect/value.go:370 +0xbc
testing.(*F).Fuzz.func1.1(0xc00043f208?)
        /home/tim/src/go/src/testing/fuzz.go:336 +0x3f3
testing.tRunner(0xc0004ca340, 0xc0004c4090)
        /home/tim/src/go/src/testing/testing.go:1501 +0x10b
created by testing.(*F).Fuzz.func1
        /home/tim/src/go/src/testing/fuzz.go:323 +0x5b9
exit status 2
FAIL    github.com/optimyze/prodfiler/libpf/pfelf       0.182s
```

The Go version is from latest `master` (commit 939f9fd64a740ef770a0ca3588f8c193dceebe83).
```
$ go version
go version devel go1.20-939f9fd64a Wed Oct 26 05:51:33 2022 +0000 linux/amd64
```

Looking at the code
```Go
func (f *File) gnuVersion(i int) (library string, version string) { 
        // Each entry is two bytes.
        i = (i + 1) * 2
        if i >= len(f.gnuVersym) {
                return
        }
        j := int(f.ByteOrder.Uint16(f.gnuVersym[i:])) <--- this line triggers the panic (L1578)
        if j < 2 || j >= len(f.gnuNeed) {
                return
        }
        n := &f.gnuNeed[j]
        return n.File, n.Name
}       
```

Here we can see that if `len(f.gnuVersym)` is 3 and the input value `i` is 0, a slice of len 1 is passed to `Uint16()`. But Uint16 requires the slice to have a len of at least two bytes.

I also wonder if it is intentional that a 0 input accesses the second array entry of f.gnuVersym instead of the first (is there a off-by-one issue hidden here ?).

### Reproducer, ELF corpus ###
[af27d09108d1449f.gz](https://github.com/golang/go/files/9867682/af27d09108d1449f.gz)

Passing this file to `elf.Open()` and then calling `DynamicSymbols()` triggers the issue.

**Comment by rockdaboot** [comment]
cc @ZekeLu (I consider you an expert here 😃)

**Comment by ZekeLu** [comment]
I'm not an  expert :joy:, but I will give it a try if no one beats me.

> I also wonder if it is intentional that a 0 input accesses the second array entry of f.gnuVersym instead of the first (is there a off-by-one issue hidden here ?).

This one is intentional. See the doc: https://pkg.go.dev/debug/elf#File.DynamicSymbols

> For compatibility with Symbols, DynamicSymbols omits the null symbol at index 0. After retrieving the symbols as symtab, an externally supplied index x corresponds to symtab[x-1], not symtab[x].

**Comment by heschi** [comment]
cc @golang/compiler
