### ISSUE TITLE
x/tools/internal/jsonrpc2_v2: frequent flakes on the -race builders

### ISSUE THREAD

**Issue by findleyr** [golang/go#56510]
This flake is very prevalent following recent changes to the jsonrpc2_v2 package:

```
panic: jsonrpc2: &jsonrpc2_test.handler{conn:(*jsonrpc2.Connection)(0xc00042c6c0), accumulator:0, waiters:(chan map[string]chan struct {})(0xc00042acc0), calls:map[string]*jsonrpc2.AsyncCall{}} produced a duplicate "wait" Response

goroutine 59 [running]:
golang.org/x/tools/internal/jsonrpc2_v2.(*Connection).internalErrorf(0xc00042c6c0, {0x6c8ab7, 0x24}, {0xc000177e18, 0x2, 0x2})
	/workdir/gopath/src/golang.org/x/tools/internal/jsonrpc2_v2/conn.go:724 +0x21b
golang.org/x/tools/internal/jsonrpc2_v2.(*Connection).processResult(0xc000412900?, {0x68e1e0, 0xc000412900}, 0xc000165c80, {0x0, 0x0}, {0x70b5c0?, 0xc0000a82a0?})
	/workdir/gopath/src/golang.org/x/tools/internal/jsonrpc2_v2/conn.go:631 +0xe53
golang.org/x/tools/internal/jsonrpc2_v2.(*Connection).handleAsync(0xc00042c6c0)
	/workdir/gopath/src/golang.org/x/tools/internal/jsonrpc2_v2/conn.go:613 +0x65
created by golang.org/x/tools/internal/jsonrpc2_v2.(*Connection).acceptRequest.func2
	/workdir/gopath/src/golang.org/x/tools/internal/jsonrpc2_v2/conn.go:576 +0x28f
```

CC @bcmills @adonovan

**Comment by bcmills** [comment]
Oops, I see the bug. Missed a `return` [here](https://cs.opensource.google/go/x/tools/+/master:internal/jsonrpc2_v2/conn.go;l=609;drc=3e8da475a3daa320ae0d991de6ea687ec21acb35). I'll send a CL shortly.

**Comment by findleyr** [comment]
Thanks, this is preventing my landing a critical fix (https://go.dev/cl/446815). I was going to turn off these tests but if you can quickly fix forward, that works as well.
