### ISSUE TITLE
go run: panic: modindex.GetPackage called with empty modroot

### ISSUE THREAD

**Issue by mappu** [golang/go#56536]
Hi,

On Go 1.19.3 windows-amd64, with a directory structure like this:

- *pwd here outside of module*
   - my-module/
      - go.mod
      - vendor/
         - github.com/xxxx/xxxx/
             - xxxx.go

I tried to do `go run -mod=vendor my-module/vendor/github.com/xxxx/xxxx/xxxx.go` and got this panic:

```
panic: modindex.GetPackage called with empty modroot

goroutine 8 [running]:
cmd/go/internal/modindex.GetModule({0x0, 0x0})
        c:/go/src/cmd/go/internal/modindex/read.go:157 +0x125
cmd/go/internal/modindex.GetPackage({0x0, 0x0}, {0xc000200060, 0x28})
        c:/go/src/cmd/go/internal/modindex/read.go:135 +0x31
cmd/go/internal/modload.scanDir({0x0?, 0x21?}, {0xc000200060, 0x28}, 0x0?)
        c:/go/src/cmd/go/internal/modload/load.go:2105 +0x4b
cmd/go/internal/modload.(*loader).load(0xc0001a7040, {0x15efa90, 0xc00001c090}, 0xc00
01a7450)
        c:/go/src/cmd/go/internal/modload/load.go:1734 +0x35f
cmd/go/internal/modload.(*loader).pkg.func1.1()
        c:/go/src/cmd/go/internal/modload/load.go:1517 +0x29
cmd/go/internal/par.(*Queue).Add.func1()
        c:/go/src/cmd/go/internal/par/queue.go:58 +0x7d
created by cmd/go/internal/par.(*Queue).Add
        c:/go/src/cmd/go/internal/par/queue.go:56 +0x225
```

What I did was probably confusing and wrong, sure, but i think a panic is unexpected

**Comment by bcmills** [comment]
> What I did was probably confusing and wrong, sure, but i think a panic is unexpected

Agreed — if `xxxx.go` is a standalone source file (that doesn't import anything outside of `std`), then the command should probably succeed (despite the misleading `-mod=vendor`?), but it probably shouldn't try to use the modindex.

**Comment by bcmills** [comment]
@seankhliao, in this case `my-module/vendor/github.com/xxxx/xxxx/xxxx.go` is probably treated as a file path, since the file does exist.

**Comment by seankhliao** [comment]
don't we require `./` (or similar) for file paths not in the current directory

**Comment by bcmills** [comment]
No, that's only for package paths.

```
$ go mod init example
go: creating new go.mod: module example

$ mkdir foo

$ cat > foo/main.go
package main

func main() {
        println("hello, world!")
}

$ go run foo/main.go
hello, world!
```

**Comment by matloob** [comment]
Weirdly enough, I'm getting a different panic message: `panic: internal error: rs.graph is unexpectedly nil with -mod=vendor`

I was able to get the panic: `modindex.GetPackage called with empty modroot`, but can't reproduce it anymore.

I'll start with fixing the panic I'm getting and see if it uncovers the other panic.
