### ISSUE TITLE
net: TestDNSNameLength panics when running it alone

### ISSUE THREAD

**Issue by mateusz834** [golang/go#56542]
```
[mateusz@arch src]$ go version
go version devel go1.20-2af48cbb7d Thu Nov 3 12:16:35 2022 +0000 linux/amd64
```
While running [`go test net`](https://pastebin.com/VuXHVSPY) I don't get any failures, but when I only run the TestDNSNameLength, it panics.
```
[mateusz@arch src]$ go test -run=DNSNameLen -v net
=== RUN   TestDNSNameLength
--- FAIL: TestDNSNameLength (0.00s)
panic: runtime error: slice bounds out of range [1:0] [recovered]
	panic: runtime error: slice bounds out of range [1:0]

goroutine 6 [running]:
testing.tRunner.func1.2({0x677700, 0xc00001e510})
	/home/mateusz/code/go/src/testing/testing.go:1512 +0x24e
testing.tRunner.func1()
	/home/mateusz/code/go/src/testing/testing.go:1515 +0x39f
panic({0x677700, 0xc00001e510})
	/home/mateusz/code/go/src/runtime/panic.go:884 +0x213
net.TestDNSNameLength(0xc00011c4e0)
	/home/mateusz/code/go/src/net/dnsconfig_unix_test.go:298 +0x539
testing.tRunner(0xc00011c4e0, 0x6a0f40)
	/home/mateusz/code/go/src/testing/testing.go:1562 +0x10b
created by testing.(*T).Run
	/home/mateusz/code/go/src/testing/testing.go:1611 +0x3df
FAIL	net	0.005s
FAIL
```

**Comment by mateusz834** [comment]
It does not panic when I run these two tests in row:
```
go test -run="DNSReadConfig|DNSNameLength" -v net
```

**Comment by mateusz834** [comment]
It probably happens because we modify the shared variable here:
https://github.com/golang/go/blob/2af48cbb7d85e5fdc635e75b99f949010c607786/src/net/dnsconfig_unix_test.go#L177-L182
