### ISSUE TITLE
cmd/compile: internal compiler error:  'init': Value live at entry. It shouldn't be. func init, node size, value nil

### ISSUE THREAD

**Issue by Rajalakshmi-Girish** [golang/go#56821]
### What version of Go are you using (`go version`)?
This error is seen with latest master golang

<pre>
$ go version
started after commit b1678e508b
Seen with go version go1.20-5c834a2eb0
</pre>

### Does this issue reproduce with the latest release?
No

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
1. git clone https://github.com/openshift/origin
2. cd origin
3. make GO_REQUIRED_MIN_VERSION:= WHAT=cmd/openshift-tests

### What did you expect to see?
Tests should be successful

### What did you see instead?
```
[root@raji-workspace origin]# make GO_REQUIRED_MIN_VERSION:= WHAT=cmd/openshift-                                                                             tests
go build -mod=vendor -trimpath -ldflags "-X github.com/openshift/origin/pkg/version.versionFromGit="v4.1.0-6003-g403f0a4" -X github.com/openshift/origin/pkg/version.commitFromGit="403f0a4fe2" -X github.com/openshift/origin/pkg/version.gitTreeState="clean" -X github.com/openshift/origin/pkg/version.buildDate="2022-11-17T17:37:11Z" " github.com/openshift/origin/cmd/openshift-tests
go build github.com/docker/docker/pkg/pools: # github.com/docker/docker/pkg/pools
github.com/docker/docker@v20.10.17+incompatible/pkg/pools/pools.go:26:49: internal compiler error: 'init': Value live at entry. It shouldn't be. func init, node size, value nil

goroutine 20 [running]:
runtime/debug.Stack()
        /root/go_master/go/src/runtime/debug/stack.go:24 +0x6c
cmd/compile/internal/base.FatalfAt({0x7908e0?, 0xc0?}, {0xc0007b8690, 0x46}, {0xc000842080, 0x4, 0x4})
        /root/go_master/go/src/cmd/compile/internal/base/print.go:227 +0x270
cmd/compile/internal/base.Fatalf(...)
        /root/go_master/go/src/cmd/compile/internal/base/print.go:196
cmd/compile/internal/ssagen.(*ssafn).Fatalf(0x6d113c?, {0x6b21ec?, 0x0?}, {0x98db4d, 0x40}, {0xc00082fd40, 0x3, 0xc000790901?})
        /root/go_master/go/src/cmd/compile/internal/ssagen/ssa.go:7831 +0x19c
cmd/compile/internal/ssagen.(*state).Fatalf(0x95be62?, {0x98db4d?, 0xc0006c3a88?}, {0xc00082fd40?, 0x25b1c?, 0xc000370700?})
        /root/go_master/go/src/cmd/compile/internal/ssagen/ssa.go:936 +0xb4
cmd/compile/internal/ssagen.(*state).variable(0xc0006c1100, {0xad2d88, 0xc000656fd0}, 0xaccc58?)
        /root/go_master/go/src/cmd/compile/internal/ssagen/ssa.go:6528 +0x194
cmd/compile/internal/ssagen.(*state).exprCheckPtr(0xc0006c1100, {0xad2d88?, 0xc000656fd0?}, 0x1)
        /root/go_master/go/src/cmd/compile/internal/ssagen/ssa.go:2684 +0x184
cmd/compile/internal/ssagen.(*state).expr(...)
        /root/go_master/go/src/cmd/compile/internal/ssagen/ssa.go:2642
cmd/compile/internal/ssagen.(*state).stmt(0xc0006c1100, {0xad17f8, 0xc0006885f0?})
        /root/go_master/go/src/cmd/compile/internal/ssagen/ssa.go:1675 +0x4678
cmd/compile/internal/ssagen.(*state).stmtList(...)
        /root/go_master/go/src/cmd/compile/internal/ssagen/ssa.go:1421
cmd/compile/internal/ssagen.(*state).stmt(0xc0006c1100, {0xad1a20, 0xc00068a280?})
        /root/go_master/go/src/cmd/compile/internal/ssagen/ssa.go:1441 +0x41d8
cmd/compile/internal/ssagen.(*state).stmtList(...)
        /root/go_master/go/src/cmd/compile/internal/ssagen/ssa.go:1421
cmd/compile/internal/ssagen.(*state).stmt(0xc0006c1100, {0xad17f8, 0xc000660dc0?})
        /root/go_master/go/src/cmd/compile/internal/ssagen/ssa.go:1436 +0x144
cmd/compile/internal/ssagen.(*state).stmtList(...)
        /root/go_master/go/src/cmd/compile/internal/ssagen/ssa.go:1421
cmd/compile/internal/ssagen.buildssa(0xc0004c7180, 0x2)
        /root/go_master/go/src/cmd/compile/internal/ssagen/ssa.go:552 +0x1c84
cmd/compile/internal/ssagen.Compile(0xc0004c7180, 0x0?)
        /root/go_master/go/src/cmd/compile/internal/ssagen/pgen.go:185 +0x48
cmd/compile/internal/gc.compileFunctions.func5.1(0x0?)
        /root/go_master/go/src/cmd/compile/internal/gc/compile.go:171 +0x4c
cmd/compile/internal/gc.compileFunctions.func3.1()
        /root/go_master/go/src/cmd/compile/internal/gc/compile.go:153 +0x44
created by cmd/compile/internal/gc.compileFunctions.func3
        /root/go_master/go/src/cmd/compile/internal/gc/compile.go:152 +0x1f4

make: *** [vendor/github.com/openshift/build-machinery-go/make/targets/golang/build.mk:16: build] Error 1
[root@raji-workspace origin]
```

**Comment by cuonglm** [comment]
Seems duplicated of https://github.com/golang/go/issues/56778

**Comment by cuonglm** [comment]
Confirm that 81c9b1d65f3e416e134a30484c4bd6563aa825b5 fixed this.
