### ISSUE TITLE
runtime: `failed to create new OS thread` when building toolchain2 on openbsd-mips64-jsing since CL 447175

### ISSUE THREAD

**Issue by bcmills** [golang/go#56839]
Since https://go.dev/cl/447175, the `openbsd-mips64-jsing` builder has been failing every run for the main Go repo.

As far as I can tell the failure mode is always `failed to create new OS thread` while building toolchain2,
but the `errno` value varies from run to run (and seems to be bogus).

https://build.golang.org/log/f6d3242e8e0d9549fbe403a7d40dad494e90688b:
```
Building Go toolchain2 using go_bootstrap and Go toolchain1.
runtime: failed to create new OS thread (have 1 already; errno=-394359)
fatal error: runtime.newosproc

runtime stack:
runtime.throw({0x5547ea, 0x11})
	/home/gopher/build/go/src/runtime/panic.go:1047 +0x58 fp=0xfffffc2568 sp=0xfffffc2540 pc=0x55c60
runtime.newosproc(0xc00004c000)
	/home/gopher/build/go/src/runtime/os_openbsd_syscall.go:49 +0x1f4 fp=0xfffffc25d8 sp=0xfffffc2568 pc=0x525e4
runtime.newm1(0xc00004c000)
	/home/gopher/build/go/src/runtime/proc.go:2244 +0x110 fp=0xfffffc2610 sp=0xfffffc25d8 pc=0x5ed98
runtime.newm(0x5909c8, 0x0, 0xffffffffffffffff)
	/home/gopher/build/go/src/runtime/proc.go:2219 +0x1b8 fp=0xfffffc2640 sp=0xfffffc2610 pc=0x5ec18
runtime.main.func1()
	/home/gopher/build/go/src/runtime/proc.go:171 +0x54 fp=0xfffffc2660 sp=0xfffffc2640 pc=0x5907c
runtime.systemstack()
	/home/gopher/build/go/src/runtime/asm_mips64x.s:189 +0x80 fp=0xfffffc2668 sp=0xfffffc2660 pc=0x933b8

goroutine 1 [running]:
runtime.systemstack_switch()
	/home/gopher/build/go/src/runtime/asm_mips64x.s:150 +0x8 fp=0xc000048780 sp=0xc000048778 pc=0x93318
runtime.main()
	/home/gopher/build/go/src/runtime/proc.go:170 +0x98 fp=0xc0000487d8 sp=0xc000048780 pc=0x59128
runtime.goexit()
	/home/gopher/build/go/src/runtime/asm_mips64x.s:624 +0x4 fp=0xc0000487d8 sp=0xc0000487d8 pc=0x9575c
go tool dist: FAILED: /home/gopher/build/go/pkg/tool/openbsd_mips64/go_bootstrap install cmd/asm cmd/cgo cmd/compile cmd/link: exit status 2
```

(attn @4a6f656c @golang/openbsd; CC @ianlancetaylor @mknyszek)

**Comment by ianlancetaylor** [comment]
I assume that the fix is https://go.dev/cl/451257.
