### ISSUE TITLE
cmd/go: get panics with "can't find reason for requirement on"

### ISSUE THREAD

**Issue by clarkmcc** [golang/go#57037]
### What version of Go are you using (`go version`)?

<pre>
$ go version 
go version go1.19.3 darwin/arm64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/owner/Library/Caches/go-build"
GOENV="/Users/owner/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/owner/go/pkg/mod"
GONOPROXY="github.com/foobar/*"
GONOSUMDB="github.com/foobar/*"
GOOS="darwin"
GOPATH="/Users/owner/go"
GOPRIVATE="github.com/foobar/*"
GOPROXY="direct"
GOROOT="/opt/homebrew/opt/go/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/opt/go/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/owner/Documents/software-development/foobar/repositories/go-common/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ml/kr1jx1fj6wjgssyg3fkpgw980000gn/T/go-build3363955347=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
Ran `go get cloud.google.com/go/storage`

### What did you expect to see?
Successful download of the module

### What did you see instead?
```
$ go get cloud.google.com/go/storage
go: downloading cloud.google.com/go/storage v1.28.0
go: downloading cloud.google.com/go v0.107.0
go: downloading cloud.google.com/go/iam v0.5.0
go: downloading cloud.google.com/go/compute/metadata v0.2.1
go: downloading github.com/googleapis/gax-go/v2 v2.6.0
go: downloading golang.org/x/oauth2 v0.0.0-20221014153046-6fdb5e3db783
go: downloading google.golang.org/api v0.102.0
go: downloading google.golang.org/genproto v0.0.0-20221024183307-1bc688fe9f3e
go: downloading cloud.google.com/go/compute v1.12.1
go: downloading google.golang.org/grpc v1.50.1
go: downloading golang.org/x/net v0.0.0-20221014081412-f15817d10f9b
go: downloading github.com/googleapis/enterprise-certificate-proxy v0.2.0
panic: internal error: can't find reason for requirement on github.com/stretchr/testify@v1.6.1

goroutine 1 [running]:
cmd/go/internal/modget.(*resolver).updateBuildList.func1({{0x140005ab580?, 0x140003cce10?}, {0x140001a29a0?, 0x1400029c6e0?}})
        /opt/homebrew/Cellar/go/1.19.3/libexec/src/cmd/go/internal/modget/get.go:1760 +0xf8
cmd/go/internal/modget.(*resolver).updateBuildList(0x14000438200, {0x104b0a510, 0x140001a2000}, {0x0, 0x0, 0x0})
        /opt/homebrew/Cellar/go/1.19.3/libexec/src/cmd/go/internal/modget/get.go:1765 +0x450
cmd/go/internal/modget.(*resolver).applyUpgrades(0x14000438200, {0x104b0a510, 0x140001a2000}, {0x0?, 0x1?, 0x104aef8a0?})
        /opt/homebrew/Cellar/go/1.19.3/libexec/src/cmd/go/internal/modget/get.go:1312 +0xc0
cmd/go/internal/modget.runGet({0x104b0a510, 0x140001a2000}, 0x140001bc348?, {0x1400019e1a0, 0x1, 0x1})
        /opt/homebrew/Cellar/go/1.19.3/libexec/src/cmd/go/internal/modget/get.go:351 +0x3c8
main.invoke(0x104dfe280, {0x1400019e190, 0x2, 0x2})
        /opt/homebrew/Cellar/go/1.19.3/libexec/src/cmd/go/main.go:225 +0x2f8
main.main()
        /opt/homebrew/Cellar/go/1.19.3/libexec/src/cmd/go/main.go:179 +0x7ac
```

**Comment by clarkmcc** [comment]
Probably related to https://github.com/golang/go/issues/47979

**Comment by clarkmcc** [comment]
Duplicate of https://github.com/golang/go/issues/56494
