### ISSUE TITLE
x/image/font/plan9font: slice bounds out of range again

### ISSUE THREAD

**Issue by catenacyber** [golang/go#57258]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/root/.go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/root/.go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/src/ngolo-fuzzing/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2481516251=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Run https://go.dev/play/p/QLmvnEMNep8?v=gotip

### What did you expect to see?

The program finishing and printing Hello

### What did you see instead?

```
panic: runtime error: index out of range [78] with length 39

goroutine 1 [running]:
golang.org/x/image/font/plan9font.decompress(0xc000074f0f?, {{0x30?, 0x51?}, {0x7fce6be82648?, 0x423680?}}, {0xc000074f57?, 0x9, 0xc000040578?})
	/tmp/gopath2421614365/pkg/mod/golang.org/x/image@v0.2.0/font/plan9font/plan9font.go:572 +0x4b0
golang.org/x/image/font/plan9font.parseImage({0xc000074ef8, 0x68, 0x68})
	/tmp/gopath2421614365/pkg/mod/golang.org/x/image@v0.2.0/font/plan9font/plan9font.go:493 +0x5e5
golang.org/x/image/font/plan9font.ParseSubfont({0xc000074ef8?, 0x7fce6be77108?, 0xc000062011?}, 0x20)
	/tmp/gopath2421614365/pkg/mod/golang.org/x/image@v0.2.0/font/plan9font/plan9font.go:322 +0x3a
main.main()
	/tmp/sandbox3391557176/prog.go:12 +0x133

Program exited.
```

Found by https://github.com/catenacyber/ngolo-fuzzing with oss-fuzz : 
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=54236

cc @nigeltao cf https://github.com/golang/go/issues/56931

**Comment by catenacyber** [comment]
Getting also out of memory with https://go.dev/play/p/08U5XZ6yM4z?v=gotip or https://go.dev/play/p/JDeJv_SfEYn?v=gotip by the way
