### ISSUE TITLE
fatal error: found bad pointer in Go heap (incorrect use of unsafe or cgo?)

### ISSUE THREAD

**Issue by 249043822** [golang/go#57450]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.17.3
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

the kube-apiserver startup failed once and we are not clear how to reproduce this

```
W1222 04:26:28.508357       1 feature_gate.go:237] Setting GA feature gate ServerSideApply=false. It will be removed in a future release.
W1222 04:26:28.508422       1 feature_gate.go:237] Setting GA feature gate StorageObjectInUseProtection=false. It will be removed in a future release.
runtime: pointer 0xc006cadb18 to unallocated span span.base()=0xc006caa000 span.limit=0xc006cb2000 span.state=0
runtime: found in object at *(0xc001081dc8+0x0)
object=0xc001081dc8 s.base()=0xc001080000 s.limit=0xc001082000 s.spanclass=2 s.elemsize=8 s.state=mSpanInUse
 *(object+0) = 0xc006cadb18 <==
fatal error: found bad pointer in Go heap (incorrect use of unsafe or cgo?)

runtime stack:
runtime.throw({0x289dc4f, 0x6})
        /usr/local/go/src/runtime/panic.go:1198 +0x71 fp=0xc003f8fdf8 sp=0xc003f8fdc8 pc=0x435e31
runtime.badPointer(0x7f82547c3848, 0xc0068aa820, 0xc001081dc8, 0x10000c000000001)
        /usr/local/go/src/runtime/mbitmap.go:367 +0x150 fp=0xc003f8fe48 sp=0xc003f8fdf8 pc=0x4141f0
runtime.findObject(0xc006be7d20, 0xc003f8ff08, 0x41c8f0)
        /usr/local/go/src/runtime/mbitmap.go:409 +0xa6 fp=0xc003f8fe80 sp=0xc003f8fe48 pc=0x414386
runtime.scanobject(0xc000088e98, 0xc000088e98)
        /usr/local/go/src/runtime/mgcmark.go:1280 +0x190 fp=0xc003f8ff18 sp=0xc003f8fe80 pc=0x41ed10
runtime.gcDrain(0xc000088e98, 0x3)
        /usr/local/go/src/runtime/mgcmark.go:1047 +0x1ba fp=0xc003f8ff70 sp=0xc003f8ff18 pc=0x41e59a
runtime.gcBgMarkWorker.func2()
        /usr/local/go/src/runtime/mgc.go:1269 +0xa5 fp=0xc003f8ffc0 sp=0xc003f8ff70 pc=0x41b7a5
runtime.systemstack()
        /usr/local/go/src/runtime/asm_amd64.s:383 +0x49 fp=0xc003f8ffc8 sp=0xc003f8ffc0 pc=0x467089

goroutine 104 [GC worker (idle)]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:350 fp=0xc00036df60 sp=0xc00036df58 pc=0x467020
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1256 +0x1b1 fp=0xc00036dfe0 sp=0xc00036df60 pc=0x41b451
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00036dfe8 sp=0xc00036dfe0 pc=0x469101
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1124 +0x25

goroutine 1 [chan receive, 7 minutes]:
runtime.gopark(0xc002cb1a28, 0x40d374, 0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/proc.go:366 +0xd6 fp=0xc00263b9a8 sp=0xc00263b988 pc=0x4388d6
runtime.chanrecv(0xc0001dd560, 0x0, 0x1)
        /usr/local/go/src/runtime/chan.go:576 +0x56c fp=0xc00263ba38 sp=0xc00263b9a8 pc=0x40692c
runtime.chanrecv1(0xc002cc3900, 0xc002e8bfb0)
        /usr/local/go/src/runtime/chan.go:439 +0x18 fp=0xc00263ba60 sp=0xc00263ba38 pc=0x406358
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.preparedGenericAPIServer.Run({0xc0024c7000}, 0xc0001dd560)
        /home/k8s/orchestration/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/genericapiserver.go:441 +0x4aa fp=0xc00263bc20 sp=0xc00263ba60 pc=0x198b94a
k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver.preparedAPIAggregator.Run(...)
        /home/k8s/orchestration/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go:378
k8s.io/kubernetes/cmd/kube-apiserver/app.Run({0xc0007482c0}, 0x4480c80)
        /home/k8s/orchestration/_output/local/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:175 +0x15d fp=0xc00263bd70 sp=0xc00263bc20 pc=0x222f3bd
k8s.io/kubernetes/cmd/kube-apiserver/app.NewAPIServerCommand.func2(0xc000c04f00, {0xc0007d7c00, 0x3a, 0x3f})
        /home/k8s/orchestration/_output/local/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:133 +0xa5 fp=0xc00263bdb8 sp=0xc00263bd70 pc=0x222f205
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc000c04f00, {0xc00004d010, 0x3a, 0x3f})
        /home/k8s/orchestration/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:852 +0x60e fp=0xc00263be78 sp=0xc00263bdb8 pc=0x693fee
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000c04f00)
        /home/k8s/orchestration/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:960 +0x3ad fp=0xc00263bf30 sp=0xc00263be78 pc=0x69464d
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /home/k8s/orchestration/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:897
main.main()
        _output/local/go/src/k8s.io/kubernetes/cmd/kube-apiserver/apiserver.go:46 +0xd9 fp=0xc00263bf80 sp=0xc00263bf30 pc=0x2233e99
runtime.main()
        /usr/local/go/src/runtime/proc.go:255 +0x227 fp=0xc00263bfe0 sp=0xc00263bf80 pc=0x438507
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00263bfe8 sp=0xc00263bfe0 pc=0x469101

goroutine 2 [force gc (idle), 7 minutes]:
runtime.gopark(0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/proc.go:366 +0xd6 fp=0xc00012afb0 sp=0xc00012af90 pc=0x4388d6
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:372
runtime.forcegchelper()
        /usr/local/go/src/runtime/proc.go:306 +0xad fp=0xc00012afe0 sp=0xc00012afb0 pc=0x43876d
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00012afe8 sp=0xc00012afe0 pc=0x469101
created by runtime.init.7
        /usr/local/go/src/runtime/proc.go:294 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x444c601, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/proc.go:366 +0xd6 fp=0xc00012b7b0 sp=0xc00012b790 pc=0x4388d6
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:372
runtime.bgsweep()
        /usr/local/go/src/runtime/mgcsweep.go:182 +0xd8 fp=0xc00012b7e0 sp=0xc00012b7b0 pc=0x422e58
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00012b7e8 sp=0xc00012b7e0 pc=0x469101
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:181 +0x55

```

the full log
[log.log](https://github.com/golang/go/files/10291602/log.log)

**Comment by liggitt** [comment]
Is this reproducible? If so, is it reproducible on a current go version (go1.18 or go1.19)?

**Comment by 249043822** [comment]
we have used this k8s for a long time, now it's the first time met this error,  and haven't reproduced again

**Comment by ianlancetaylor** [comment]
If this happened only once and can't be reproduced, then my first guess would be some sort of memory failure causing a bad pointer to appear.

I'm not sure there is anything we can do without at least one more failure.
