### ISSUE TITLE
cmd/compile: internal compiler error: 'Float64D3': no register available..." (1.20 regression?) 

### ISSUE THREAD

**Issue by thepudds** [golang/go#57846]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version devel go1.20-66689c7 Tue Jan 17 15:26:07 2023 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Not with go1.19, but yes with go1.20rc3 and tip.

### What did you do?

Ran many public modules through vet as part of testing #57173 and the related https://go.dev/cl/455195. Some modules failed to compile with internal compiler error.

Example:

```
git clone -b v1.3.0 https://github.com/vbsw/slices
cd ./slices/count
go build ./...
```

### What did you see?

```
./count.go:320:22: internal compiler error: 'Float64D3': no register available for v0 = OpInvalid <<T>>
```

Call stack:

```
goroutine 118 [running]:
runtime/debug.Stack()
        /home/thepudds1460/sdk/gotip/src/runtime/debug/stack.go:24 +0x65
cmd/compile/internal/base.FatalfAt({0x193d1d8?, 0xc0?}, {0xc001659e90, 0x22}, {0xc00160fae0, 0x2, 0x2})
        /home/thepudds1460/sdk/gotip/src/cmd/compile/internal/base/print.go:227 +0x1d7
cmd/compile/internal/base.Fatalf(...)
        /home/thepudds1460/sdk/gotip/src/cmd/compile/internal/base/print.go:196
cmd/compile/internal/ssagen.(*ssafn).Fatalf(0xf?, {0x6be93ef8?, 0x7f08?}, {0xdd69e6, 0x1c}, {0xc001930700, 0x1, 0x0?})
        /home/thepudds1460/sdk/gotip/src/cmd/compile/internal/ssagen/ssa.go:7831 +0x177
cmd/compile/internal/ssa.(*Func).Fatalf(0xc0016bca80, {0xdd69e6, 0x1c}, {0xc001930700, 0x1, 0x1})
        /home/thepudds1460/sdk/gotip/src/cmd/compile/internal/ssa/func.go:722 +0x28b
cmd/compile/internal/ssa.(*regAllocState).allocReg(0xc0016ffc80, 0xc000781810?, 0xc000781810?)
        /home/thepudds1460/sdk/gotip/src/cmd/compile/internal/ssa/regalloc.go:404 +0xde
cmd/compile/internal/ssa.(*regAllocState).regalloc(0xc0016ffc80, 0xc0016bca80)
        /home/thepudds1460/sdk/gotip/src/cmd/compile/internal/ssa/regalloc.go:1567 +0x46c7
cmd/compile/internal/ssa.regalloc(0xc0016bca80?)
        /home/thepudds1460/sdk/gotip/src/cmd/compile/internal/ssa/regalloc.go:148 +0x45
cmd/compile/internal/ssa.Compile(0xc0016bca80)
        /home/thepudds1460/sdk/gotip/src/cmd/compile/internal/ssa/compile.go:97 +0x963
cmd/compile/internal/ssagen.buildssa(0xc0006b2140, 0x0)
        /home/thepudds1460/sdk/gotip/src/cmd/compile/internal/ssagen/ssa.go:572 +0x2027
cmd/compile/internal/ssagen.Compile(0xc0006b2140, 0x0?)
        /home/thepudds1460/sdk/gotip/src/cmd/compile/internal/ssagen/pgen.go:185 +0x4c
cmd/compile/internal/gc.compileFunctions.func5.1(0x0?)
        /home/thepudds1460/sdk/gotip/src/cmd/compile/internal/gc/compile.go:171 +0x3a
cmd/compile/internal/gc.compileFunctions.func3.1()
        /home/thepudds1460/sdk/gotip/src/cmd/compile/internal/gc/compile.go:153 +0x32
created by cmd/compile/internal/gc.compileFunctions.func3
        /home/thepudds1460/sdk/gotip/src/cmd/compile/internal/gc/compile.go:152 +0x245
```

**Comment by cherrymui** [comment]
cc @golang/compiler

**Comment by cuonglm** [comment]
git bisec point to 5f7abeca5a584a847033bbd1bc1123872bb0925e cc @randall77

**Comment by thepudds** [comment]
I saw two other flavors of internal compiler error using tip against a larger number of public modules, but one of the errors looks like it was reported a few days ago (#57778).

It seems the other internal compiler error I saw does not reproduce with `go build` or `go vet`, but does happen when using `golang.org/x/tools/go/analysis/singlechecker` (which is how I originally saw the problem), so that one is probably a lower priority. I'll file a separate issue once I have time to poke at it slightly more:

```
<unknown line number>: internal compiler error: have package "main" (0xc0003ff9a0), 
want package "github.com/maxbrunsfeld/counterfeiter/v6" (0xc0003ff950)
```
