### ISSUE TITLE
crypto/rand: TestRead: panic on js/wasm 

### ISSUE THREAD

**Issue by johanbrandhorst** [golang/go#58145]
The NodeJS 18 builder is panicing in in `TestRead` in the `crypto/rand` package with the error `panic: JavaScript error: The requested length exceeds 65,536 bytes [recovered]`. The full traceback is:

```
--- FAIL: TestRead (0.00s)
panic: JavaScript error: The requested length exceeds 65,536 bytes [recovered]
	panic: JavaScript error: The requested length exceeds 65,536 bytes

goroutine 6 [running]:
panic({0x37900, 0x41e250})
	/workdir/go/src/runtime/panic.go:1015 +0x65 fp=0x45b9f0 sp=0x45b930 pc=0x123a0065
testing.tRunner.func1.2({0x37900, 0x41e250})
	/workdir/go/src/testing/testing.go:1526 +0x1b fp=0x45baa8 sp=0x45b9f0 pc=0x17bc001b
testing.tRunner.func1()
	/workdir/go/src/testing/testing.go:1529 +0x37 fp=0x45bc08 sp=0x45baa8 pc=0x17bb0037
runtime.deferCallSave(0x45bce8, 0x444fa0)
	/workdir/go/src/runtime/panic.go:796 +0xe fp=0x45bc20 sp=0x45bc08 pc=0x1238000e
runtime.runOpenDeferFrame(0x40e1e0)
	/workdir/go/src/runtime/panic.go:769 +0x33 fp=0x45bc68 sp=0x45bc20 pc=0x12370033
panic({0x37900, 0x41e250})
	/workdir/go/src/runtime/panic.go:912 +0x36 fp=0x45bd28 sp=0x45bc68 pc=0x123a0036
syscall/js.Value.Call({{}, 0x7ff800010000000d, 0x412190}, {0x408b0, 0xf}, {0x444e48, 0x1, 0x1})
	/workdir/go/src/syscall/js/js.go:389 +0x31 fp=0x45bde8 sp=0x45bd28 pc=0x15310031
crypto/rand.(*reader).Read(0x1f47f8, {0x480000, 0x186a0, 0x186a0})
	/workdir/go/src/crypto/rand/rand_js.go:25 +0x3 fp=0x45be70 sp=0x45bde8 pc=0x19ad0003
io.ReadAtLeast({0x69698, 0x1f47f8}, {0x480000, 0x186a0, 0x186a0}, 0x186a0)
	/workdir/go/src/io/io.go:332 +0x7 fp=0x45bec8 sp=0x45be70 pc=0x15ca0007
io.ReadFull(...)
	/workdir/go/src/io/io.go:351
crypto/rand.TestRead(0x400ea0)
	/workdir/go/src/crypto/rand/rand_test.go:20 +0x10 fp=0x45bf70 sp=0x45bec8 pc=0x19b00010
testing.tRunner(0x400ea0, 0x495f8)
	/workdir/go/src/testing/testing.go:1576 +0x10 fp=0x45bfc8 sp=0x45bf70 pc=0x17b90010
testing.(*T).Run.func1()
	/workdir/go/src/testing/testing.go:1629 +0x2 fp=0x45bfe0 sp=0x45bfc8 pc=0x17bf0002
runtime.goexit()
	/workdir/go/src/runtime/asm_wasm.s:399 +0x1 fp=0x45bfe8 sp=0x45bfe0 pc=0x148b0001
created by testing.(*T).Run
	/workdir/go/src/testing/testing.go:1629 +0x55

goroutine 1 [chan receive]:
runtime.gopark(0x497c0, 0x438138, 0xe, 0x17, 0x2)
	/workdir/go/src/runtime/proc.go:381 +0x26 fp=0x4599f8 sp=0x4599d0 pc=0x12640026
runtime.chanrecv(0x4380e0, 0x459aef, 0x1)
	/workdir/go/src/runtime/chan.go:583 +0x7f fp=0x459a80 sp=0x4599f8 pc=0x106a007f
runtime.chanrecv1(0x4380e0, 0x459aef)
	/workdir/go/src/runtime/chan.go:442 +0x2 fp=0x459aa8 sp=0x459a80 pc=0x10690002
testing.(*T).Run(0x400d00, {0x3ee99, 0x8}, 0x495f8)
	/workdir/go/src/testing/testing.go:1630 +0x56 fp=0x459b60 sp=0x459aa8 pc=0x17be0056
testing.runTests.func1(0x400d00)
	/workdir/go/src/testing/testing.go:2036 +0x3 fp=0x459ba8 sp=0x459b60 pc=0x17ca0003
testing.tRunner(0x400d00, 0x459cb0)
	/workdir/go/src/testing/testing.go:1576 +0x10 fp=0x459c00 sp=0x459ba8 pc=0x17b90010
testing.runTests(0x40a060, {0x1cb020, 0xa, 0xa}, {0xc0ee22d047ed6b40, 0x29e92a5c01, 0x1d60a0})
	/workdir/go/src/testing/testing.go:2034 +0x56 fp=0x459cd8 sp=0x459c00 pc=0x17c90056
testing.(*M).Run(0x4620a0)
	/workdir/go/src/testing/testing.go:1906 +0x74 fp=0x459f10 sp=0x459cd8 pc=0x17c20074
main.main()
	_testmain.go:71 +0x17 fp=0x459f88 sp=0x459f10 pc=0x19c40017
runtime.main()
	/workdir/go/src/runtime/proc.go:250 +0x30 fp=0x459fe0 sp=0x459f88 pc=0x125e0030
runtime.goexit()
	/workdir/go/src/runtime/asm_wasm.s:399 +0x1 fp=0x459fe8 sp=0x459fe0 pc=0x148b0001

goroutine 2 [force gc (idle)]:
runtime.gopark(0x49ad0, 0x1d5cb0, 0x11, 0x14, 0x1)
	/workdir/go/src/runtime/proc.go:381 +0x26 fp=0x432fb8 sp=0x432f90 pc=0x12640026
runtime.goparkunlock(...)
	/workdir/go/src/runtime/proc.go:387
runtime.forcegchelper()
	/workdir/go/src/runtime/proc.go:305 +0x1f fp=0x432fe0 sp=0x432fb8 pc=0x1261001f
runtime.goexit()
	/workdir/go/src/runtime/asm_wasm.s:399 +0x1 fp=0x432fe8 sp=0x432fe0 pc=0x148b0001
created by runtime.init.5
	/workdir/go/src/runtime/proc.go:293 +0x2

goroutine 3 [GC sweep wait]:
runtime.gopark(0x49ad0, 0x1d6020, 0xc, 0x14, 0x1)
	/workdir/go/src/runtime/proc.go:381 +0x26 fp=0x433798 sp=0x433770 pc=0x12640026
runtime.goparkunlock(...)
	/workdir/go/src/runtime/proc.go:387
runtime.bgsweep(0x438000)
	/workdir/go/src/runtime/mgcsweep.go:278 +0xf fp=0x4337d0 sp=0x433798 pc=0x117f000f
runtime.gcenable.func1()
	/workdir/go/src/runtime/mgc.go:178 +0x2 fp=0x4337e0 sp=0x4337d0 pc=0x11130002
runtime.goexit()
	/workdir/go/src/runtime/asm_wasm.s:399 +0x1 fp=0x4337e8 sp=0x4337e0 pc=0x148b0001
created by runtime.gcenable
	/workdir/go/src/runtime/mgc.go:178 +0x8

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x49ad0, 0x1d6120, 0xd, 0x14, 0x2)
	/workdir/go/src/runtime/proc.go:381 +0x26 fp=0x433f80 sp=0x433f58 pc=0x12640026
runtime.goparkunlock(...)
	/workdir/go/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x1d6120)
	/workdir/go/src/runtime/mgcscavenge.go:399 +0xc fp=0x433fa8 sp=0x433f80 pc=0x1166000c
runtime.bgscavenge(0x438000)
	/workdir/go/src/runtime/mgcscavenge.go:627 +0x4 fp=0x433fd0 sp=0x433fa8 pc=0x116b0004
runtime.gcenable.func2()
	/workdir/go/src/runtime/mgc.go:179 +0x2 fp=0x433fe0 sp=0x433fd0 pc=0x11120002
runtime.goexit()
	/workdir/go/src/runtime/asm_wasm.s:399 +0x1 fp=0x433fe8 sp=0x433fe0 pc=0x148b0001
created by runtime.gcenable
	/workdir/go/src/runtime/mgc.go:179 +0xe

goroutine 5 [finalizer wait]:
runtime.gopark(0x49800, 0x1f4710, 0x10, 0x14, 0x1)
	/workdir/go/src/runtime/proc.go:381 +0x26 fp=0x432738 sp=0x432710 pc=0x12640026
runtime.runfinq()
	/workdir/go/src/runtime/mfinal.go:193 +0x1e fp=0x4327e0 sp=0x432738 pc=0x110a001e
runtime.goexit()
	/workdir/go/src/runtime/asm_wasm.s:399 +0x1 fp=0x4327e8 sp=0x4327e0 pc=0x148b0001
created by runtime.createfing
	/workdir/go/src/runtime/mfinal.go:163 +0xd

goroutine 7 [waiting]:
runtime.gopark(0x0, 0x0, 0x0, 0x0, 0x1)
	/workdir/go/src/runtime/proc.go:381 +0x26 fp=0x434790 sp=0x434768 pc=0x12640026
runtime.handleEvent()
	/workdir/go/src/runtime/lock_js.go:257 +0x1b fp=0x4347e0 sp=0x434790 pc=0x10a6001b
runtime.goexit()
	/workdir/go/src/runtime/asm_wasm.s:399 +0x1 fp=0x4347e8 sp=0x4347e0 pc=0x148b0001
created by runtime.beforeIdle
	/workdir/go/src/runtime/lock_js.go:207 +0x1a
FAIL	crypto/rand	0.235s
ok  	crypto/rc4	0.258s
FAIL
go tool dist: Failed: exit status 1


Error: tests failed: dist test failed: go_test:crypto/md5: exit status 1
```

A log of the failure can be found here: https://farmer.golang.org/temporarylogs?name=js-wasm-node18&rev=4c5d97990e4a39bd3e903f8e318b7234db3ba91f&st=0xc016a73180.

This is likely related to the recent change to use the NodeJS `crypto` library directly: https://go-review.googlesource.com/c/go/+/463975.

**Comment by dmitshur** [comment]
CC @golang/js, @golang/security.
