### ISSUE TITLE
cmd/compile: internal compiler error: two final stores on ssa/check

### ISSUE THREAD

**Issue by ALTree** [golang/go#58161]
```
$ gotip version
go version devel go1.21-f66581ead6 Tue Jan 31 07:55:26 2023 +0000 linux/amd64
```
```
package main

func F[G int]() int {
	return len(make([]int, copy([]G{}, []G{})))
}

func main() {
	F[int]()
}
```
```
$ GOARCH=s390x gotip build -gcflags=-d=ssa/check/seed=1 crash.go

# command-line-arguments
./crash.go:3:6: internal compiler error: 'F[int]': two final stores - simultaneous live stores v62 = MakeResult <mem> v58 v56 = StaticCall <mem> {AuxCall{runtime.makeslice}} [32] v17

goroutine 1 [running]:
runtime/debug.Stack()
	./gotip/src/runtime/debug/stack.go:24 +0x5e
cmd/compile/internal/base.FatalfAt({0x403680?, 0xc0?}, {0xc00002d580, 0x37}, {0xc00042e720, 0x3, 0x3})
	./gotip/src/cmd/compile/internal/base/print.go:227 +0x1d7
cmd/compile/internal/base.Fatalf(...)
	./gotip/src/cmd/compile/internal/base/print.go:196
cmd/compile/internal/ssagen.(*ssafn).Fatalf(0x0?, {0x765cb928?, 0x7fc0?}, {0xd58b0a, 0x31}, {0xc000420380, 0x2, 0x0?})
	./gotip/src/cmd/compile/internal/ssagen/ssa.go:7832 +0x16a
cmd/compile/internal/ssa.(*Func).Fatalf(0xc00040c1c0, {0xd58b0a, 0x31}, {0xc000420380, 0x2, 0x2})
	./gotip/src/cmd/compile/internal/ssa/func.go:722 +0x288
cmd/compile/internal/ssa.(*Block).Fatalf(...)
	./gotip/src/cmd/compile/internal/ssa/block.go:412
cmd/compile/internal/ssa.dse(0xc00040c1c0)
	./gotip/src/cmd/compile/internal/ssa/deadstore.go:67 +0x6c5
cmd/compile/internal/ssa.Compile(0xc00040c1c0)
	./gotip/src/cmd/compile/internal/ssa/compile.go:97 +0x95e
cmd/compile/internal/ssagen.buildssa(0xc0003f23c0, 0x0)
	./gotip/src/cmd/compile/internal/ssagen/ssa.go:572 +0x2007
cmd/compile/internal/ssagen.Compile(0xc0003f23c0, 0x13d0520?)
	./gotip/src/cmd/compile/internal/ssagen/pgen.go:185 +0x45
cmd/compile/internal/gc.compileFunctions.func5.1(0x7fc0765c2101?)
	./gotip/src/cmd/compile/internal/gc/compile.go:171 +0x35
cmd/compile/internal/gc.compileFunctions.func2(0xc0004201c0?)
	./gotip/src/cmd/compile/internal/gc/compile.go:125 +0x19
cmd/compile/internal/gc.compileFunctions.func5({0xc000420180, 0x3, 0x4?})
	./gotip/src/cmd/compile/internal/gc/compile.go:170 +0x62
cmd/compile/internal/gc.compileFunctions()
	./gotip/src/cmd/compile/internal/gc/compile.go:181 +0x1ef
cmd/compile/internal/gc.Main(0xd66af8)
	./gotip/src/cmd/compile/internal/gc/main.go:326 +0x136a
main.main()
	./gotip/src/cmd/compile/main.go:57 +0xdd
```

Doesn't crash on go1.19.5.

**Comment by randall77** [comment]
Very likely this is https://go-review.googlesource.com/c/go/+/454036 . I don't think the `clobberIfDead` logic is quite right in this case. It leaves the original `makeslice` call intact.
@Jorropo

**Comment by Jorropo** [comment]
@randall77 ah indeed, I did not knew Call nodes could be passed to `MakeResult`.
I fixed it there: https://go-review.googlesource.com/c/go/+/463846
