### ISSUE TITLE
misc/cgo/testplugin: test consistently failing on `android-arm-corellium` and `android-arm64-corellium`

### ISSUE THREAD

**Issue by bcmills** [golang/go#58170]
https://build.golang.org/log/f536915f21090bf85a867d60e5e0a62652429986:
```
##### ../misc/cgo/testplugin
mkdir -p $TMPDIR/src/testplugin
rsync -a testdata/ $TMPDIR/src/testplugin
echo 'module testplugin' > $TMPDIR/src/testplugin/go.mod
mkdir -p $TMPDIR/alt/src/testplugin
rsync -a altpath/testdata/ $TMPDIR/alt/src/testplugin
echo 'module testplugin' > $TMPDIR/alt/src/testplugin/go.mod
cd $TMPDIR/alt/src/testplugin
( GOPATH=$TMPDIR/alt PWD=$TMPDIR/alt/src/testplugin /data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/bin/go build -gcflags '' -buildmode=plugin -o $TMPDIR/src/testplugin/plugin-mismatch.so ./plugin-mismatch )
cd $TMPDIR/src/testplugin
( GOPATH=$TMPDIR PWD=$TMPDIR/src/testplugin LD_LIBRARY_PATH=$TMPDIR/src/testplugin /data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/bin/go build -gcflags '' -buildmode=plugin ./plugin1 )
( GOPATH=$TMPDIR PWD=$TMPDIR/src/testplugin LD_LIBRARY_PATH=$TMPDIR/src/testplugin /data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/bin/go build -gcflags '' -buildmode=plugin ./plugin2 )
cp plugin2.so plugin2-dup.so
( GOPATH=$TMPDIR PWD=$TMPDIR/src/testplugin LD_LIBRARY_PATH=$TMPDIR/src/testplugin /data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/bin/go build -gcflags '' -buildmode=plugin -o=sub/plugin1.so ./sub/plugin1 )
( GOPATH=$TMPDIR PWD=$TMPDIR/src/testplugin LD_LIBRARY_PATH=$TMPDIR/src/testplugin /data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/bin/go build -gcflags '' -buildmode=plugin -o=unnamed1.so ./unnamed1/main.go )
( GOPATH=$TMPDIR PWD=$TMPDIR/src/testplugin LD_LIBRARY_PATH=$TMPDIR/src/testplugin /data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/bin/go build -gcflags '' -buildmode=plugin -o=unnamed2.so ./unnamed2/main.go )
( GOPATH=$TMPDIR PWD=$TMPDIR/src/testplugin LD_LIBRARY_PATH=$TMPDIR/src/testplugin /data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/bin/go build -gcflags '' -o host.exe ./host )
( GOPATH=$TMPDIR PWD=$TMPDIR/src/testplugin LD_LIBRARY_PATH=$TMPDIR/src/testplugin /data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/bin/go run -gcflags '' ./checkdwarf/main.go plugin2.so plugin2.UnexportedNameReuse )
( GOPATH=$TMPDIR PWD=$TMPDIR/src/testplugin LD_LIBRARY_PATH=$TMPDIR/src/testplugin /data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/bin/go run -gcflags '' ./checkdwarf/main.go ./host.exe main.main )
( GOPATH=$TMPDIR PWD=$TMPDIR/src/testplugin LD_LIBRARY_PATH=$TMPDIR/src/testplugin ./host.exe )
( GOPATH=$TMPDIR PWD=$TMPDIR/src/testplugin LD_LIBRARY_PATH=$TMPDIR/src/testplugin /data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/bin/go build -gcflags '' -buildmode=plugin ./iface_a )
( GOPATH=$TMPDIR PWD=$TMPDIR/src/testplugin LD_LIBRARY_PATH=$TMPDIR/src/testplugin /data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/bin/go build -gcflags '' -buildmode=plugin ./iface_b )
( GOPATH=$TMPDIR PWD=$TMPDIR/src/testplugin LD_LIBRARY_PATH=$TMPDIR/src/testplugin /data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/bin/go build -gcflags '' -o iface.exe ./iface )
( GOPATH=$TMPDIR PWD=$TMPDIR/src/testplugin LD_LIBRARY_PATH=$TMPDIR/src/testplugin ./iface.exe )
--- FAIL: TestUniqueTypesAndItabs (2.35s)
    plugin_test.go:201: ./iface.exe: exit status 2
        panic: empty interfaces not equal
        
        goroutine 1 [running]:
        panic({0x555cb2d180?, 0x555cb4b000?})
        	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/panic.go:1015 +0x3fc fp=0x40000b5e60 sp=0x40000b5d90 pc=0x555ca7a07c
        main.main()
        	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/tmp/plugin_test261215192/src/testplugin/iface/main.go:33 +0x5fc fp=0x40000b5f70 sp=0x40000b5e60 pc=0x555cb1d8bc
        runtime.main()
        	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/proc.go:250 +0x200 fp=0x40000b5fd0 sp=0x40000b5f70 pc=0x555ca7cd00
        runtime.goexit()
        	/data/data/com.termux/files/home/tmpdir/workdir-host-android-arm64-corellium-android/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x40000b5fd0 sp=0x40000b5fd0 pc=0x555caaa0e4
```

**Comment by bcmills** [comment]
I think this started failing as of [CL 463992](https://go.dev/cl/463992), which made `cmd/dist` consistent with the rest of the toolchain w.r.t. whether `plugin` mode is supported.

It appears that `plugin` mode doesn't work on these platforms after all.
