### ISSUE TITLE
fatal error: unexpected signal during runtime execution [signal SIGSEGV: segmentation violation code=0x2 addr=0xc002000000 pc=0x46e698]  Linux version 5.10.135-yocto-standard 

### ISSUE THREAD

**Issue by harsh8118** [golang/go#58377]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/harshg/.cache/go-build"
GOENV="/home/harshg/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/harshg/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/harshg/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3092080171=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
system is idle for ~24hrs and crash seen

### What did you expect to see?

No crash

### What did you see instead?
process crashed

2023-01-26T12:17:31.348707766Z stderr F fatal error: unexpected signal during runtime execution
2023-01-26T12:17:31.350770573Z stderr F [signal SIGSEGV: segmentation violation code=0x2 addr=0xc002000000 pc=0x46e698]
2023-01-26T12:17:31.350783358Z stderr F 
2023-01-26T12:17:31.350791878Z stderr F runtime stack:
2023-01-26T12:17:31.350859849Z stderr F runtime.throw({0xf29d09?, 0x1?})
2023-01-26T12:17:31.350880127Z stderr F 	/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7f2c8285a428 sp=0x7f2c8285a3f8 pc=0x43967d
2023-01-26T12:17:31.350908984Z stderr F runtime.sigpanic()
2023-01-26T12:17:31.350930898Z stderr F 	/usr/local/go/src/runtime/signal_unix.go:819 +0x369 fp=0x7f2c8285a478 sp=0x7f2c8285a428 pc=0x44ff29
2023-01-26T12:17:31.350940863Z stderr F runtime.memmove()
2023-01-26T12:17:31.35095777Z stderr F 	/usr/local/go/src/runtime/memmove_amd64.s:111 +0xb8 fp=0x7f2c8285a480 sp=0x7f2c8285a478 pc=0x46e698
2023-01-26T12:17:31.350995582Z stderr F runtime.syncadjustsudogs(0xc00027e000, 0x718, 0x7f2c8285a548)
2023-01-26T12:17:31.351052701Z stderr F 	/usr/local/go/src/runtime/stack.go:840 +0xeb fp=0x7f2c8285a4c0 sp=0x7f2c8285a480 pc=0x452eeb
2023-01-26T12:17:31.351068333Z stderr F runtime.copystack(0xc00027e000, 0x7f2c8285a840?)
2023-01-26T12:17:31.351077094Z stderr F 	/usr/local/go/src/runtime/stack.go:909 +0x372 fp=0x7f2c8285a678 sp=0x7f2c8285a4c0 pc=0x4532f2
2023-01-26T12:17:31.351085068Z stderr F runtime.shrinkstack(0xc00027e000)
2023-01-26T12:17:31.351092812Z stderr F 	/usr/local/go/src/runtime/stack.go:1214 +0x126 fp=0x7f2c8285a698 sp=0x7f2c8285a678 pc=0x454146
2023-01-26T12:17:31.351100353Z stderr F runtime.scanstack(0xc00027e000, 0xc000053240)
2023-01-26T12:17:31.351108085Z stderr F 	/usr/local/go/src/runtime/mgcmark.go:775 +0xe7 fp=0x7f2c8285a8a0 sp=0x7f2c8285a698 pc=0x420f47
2023-01-26T12:17:31.351116233Z stderr F runtime.markroot.func1()
2023-01-26T12:17:31.35112403Z stderr F 	/usr/local/go/src/runtime/mgcmark.go:240 +0xc5 fp=0x7f2c8285a8f0 sp=0x7f2c8285a8a0 pc=0x41fe65
2023-01-26T12:17:31.351144752Z stderr F runtime.markroot(0xc000053240, 0x61, 0x1)
2023-01-26T12:17:31.351157325Z stderr F 	/usr/local/go/src/runtime/mgcmark.go:213 +0x1a5 fp=0x7f2c8285a990 sp=0x7f2c8285a8f0 pc=0x41fb05
2023-01-26T12:17:31.351165171Z stderr F runtime.gcDrain(0xc000053240, 0x2)
2023-01-26T12:17:31.351172805Z stderr F 	/usr/local/go/src/runtime/mgcmark.go:1069 +0x39f fp=0x7f2c8285a9f0 sp=0x7f2c8285a990 pc=0x421bdf
2023-01-26T12:17:31.351180521Z stderr F runtime.gcBgMarkWorker.func2()
2023-01-26T12:17:31.351188183Z stderr F 	/usr/local/go/src/runtime/mgc.go:1323 +0x154 fp=0x7f2c8285aa40 sp=0x7f2c8285a9f0 pc=0x41e1b4
2023-01-26T12:17:31.351195687Z stderr F runtime.systemstack()
2023-01-26T12:17:31.351215412Z stderr F 	/usr/local/go/src/runtime/asm_amd64.s:492 +0x49 fp=0x7f2c8285aa48 sp=0x7f2c8285aa40 pc=0x46b589
2023-01-26T12:17:31.351227986Z stderr F 
2023-01-26T12:17:31.351235766Z stderr F goroutine 16 [GC worker (idle)]:
2023-01-26T12:17:31.351243438Z stderr F runtime.systemstack_switch()
2023-01-26T12:17:31.35126511Z stderr F 	/usr/local/go/src/runtime/asm_amd64.s:459 fp=0xc0004ad750 sp=0xc0004ad748 pc=0x46b520
2023-01-26T12:17:31.351275229Z stderr F runtime.gcBgMarkWorker()
2023-01-26T12:17:31.351283027Z stderr F 	/usr/local/go/src/runtime/mgc.go:1295 +0x205 fp=0xc0004ad7e0 sp=0xc0004ad750 pc=0x41dda5
2023-01-26T12:17:31.35129095Z stderr F runtime.goexit()
2023-01-26T12:17:31.351379968Z stderr F 	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0004ad7e8 sp=0xc0004ad7e0 pc=0x46d741
2023-01-26T12:17:31.351393791Z stderr F created by runtime.gcBgMarkStartWorkers
2023-01-26T12:17:31.351401948Z stderr F 	/usr/local/go/src/runtime/mgc.go:1159 +0x25

**Comment by bcmills** [comment]
Looks like memory corruption.
* Have you run the program under the race detector?
* Do you have cgo dependencies? Have you tested them with fuzzing and sanitizers? Do they register signal handlers that might interfere with the Go runtime?
* Does your machine have ECC memory? (Is it possible that your machine had an uncorrected thermal bit-flip that corrupted the heap?)

**Comment by harsh8118** [comment]
Hi,
I am yet to try it with race detector.
I don't have any cgo dependencies.
Not sure about ECC memory I will check and update this.
