### ISSUE TITLE
x/net/http2: panic: flow control update exceeds maximum window size

### ISSUE THREAD

**Issue by WillSewell** [golang/go#58456]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1132651924=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Calling `golang.org/x/net/http2.transportResponseBody.Close` sometimes results in

```
panic: flow control update exceeds maximum window size
goroutine 242605551 [running]:
golang.org/x/net/http2.(*inflow).add(...)
        /go-tmp/src/github.com/monzo/wearedev/vendor/golang.org/x/net/http2/flow.go:42
golang.org/x/net/http2.transportResponseBody.Close({0x13b6580?})
        /go-tmp/src/github.com/monzo/wearedev/vendor/golang.org/x/net/http2/transport.go:2562 +0x298
```

I can see this panic was recently added [here](https://go-review.googlesource.com/c/net/+/448155/6/http2/flow.go#42).

### What did you expect to see?

An error to be returned.

### What did you see instead?

A panic.

**Comment by seankhliao** [comment]
cc @neild @tombergan

**Comment by bcmills** [comment]
Possibly related to #57578?
