### ISSUE TITLE
runtime: endless traceback when panic in generics funtion

### ISSUE THREAD

**Issue by SilverRainZ** [golang/go#58513]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.21-261fe25c83 Sat Feb 11 16:16:34 2023 +0000 darwin/amd64
</pre>

- Introduced in 833367e98af838a2511ee7e4e19dc8f1da7b8ed7 (I found it by `git bisect`)
- Still can be reproduced in 261fe25c83a94fc3defe064baed3944cd3d16959 (master)

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

Run the following code:

```go
package main

const (
	ALL = -1
)

type Iter[T any] interface {
	Next(n int) []T
}

type sliceIter[T any] struct {
	s []T
}

func (i *sliceIter[T]) Next(n int) []T {
	if n == ALL || n > len(i.s) {
		n = len(i.s)
	}
	next := make([]T, n)
	copy(next, i.s[:n])
	i.s = i.s[n:]
	return next
}

// FromSlice constructs an Iter from slice s, in order from left to right.
// An empty Iter (without element) is returned if the given slice is empty
// or nil.
func FromSlice[T any](s []T) Iter[T] {
	return &sliceIter[T]{s}
}

type mapIter[T1, T2 any] struct {
	f func(T1) T2
	i Iter[T1]
}

func (i *mapIter[T1, T2]) Next(n int) []T2 {
	vs := i.i.Next(n)
	if len(vs) == 0 {
		return nil
	}
	next := make([]T2, len(vs))
	for j := range next {
		next[j] = i.f(vs[j])
	}
	return next
}

// Map applies function f to each element of iterator i with Type T1.
// Results of f are returned as a new Iter with Type T2.
func Map[T1, T2 any](f func(T1) T2, i Iter[T1]) Iter[T2] {
	return &mapIter[T1, T2]{f, i}
}

// ToSlice collects elements of iterator to a slice.
//
// If the iterator is empty, empty slice []T{} is returned.
func ToSlice[T any](i Iter[T]) []T {
	all := i.Next(ALL)
	if all == nil {
		return []T{} // Always returns a slice
	} else {
		return all
	}
}

func typeAssert[To, From any](v From) To {
	return any(v).(To)
}

func TypeAssert[To, From any](i Iter[From]) Iter[To] {
	return Map(typeAssert[To, From], i)
}

func main() {
	_ = ToSlice(
		TypeAssert[string](
			FromSlice([]int{1})))
}

```

### What did you expect to see?

Program panics and exits. Output by go1.19.4:

```
$ go run main.go
panic: interface conversion: interface {} is int, not string

goroutine 1 [running]:
main.typeAssert[...](...)
        /Users/bytedance/workspace/traceback/main.go:68
main.(*mapIter[...]).Next(0xc000090018?, 0xc00004e701)
        /Users/bytedance/workspace/traceback/main.go:44 +0x92
main.ToSlice[...]({0x107b8e8?, 0xc000090018?})
        /Users/bytedance/workspace/traceback/main.go:59 +0x2e
main.main()
        /Users/bytedance/workspace/traceback/main.go:76 +0x69
exit status 2
```

### What did you see instead?

Program panics as expected, but print stack endlessly.

```
$ ~/git/go/bin/go run main.go
panic: interface conversion: interface {} is int, not string

goroutine 1 [running]:
main.typeAssert[...](0xc00001c001?)
	/Users/bytedance/workspace/traceback/main.go:68 +0x45
main.TypeAssert[...](...)
	/Users/bytedance/workspace/traceback/main.go:72
main.TypeAssert[...](...)
	/Users/bytedance/workspace/traceback/main.go:72
main.TypeAssert[...](...)
	/Users/bytedance/workspace/traceback/main.go:72
main.TypeAssert[...](...)
	/Users/bytedance/workspace/traceback/main.go:72
main.TypeAssert[...](...)
	/Users/bytedance/workspace/traceback/main.go:72
main.TypeAssert[...](...)
	/Users/bytedance/workspace/traceback/main.go:72
main.TypeAssert[...](...)
	/Users/bytedance/workspace/traceback/main.go:72
main.TypeAssert[...](...)
	/Users/bytedance/workspace/traceback/main.go:72
main.TypeAssert[...](...)
	/Users/bytedance/workspace/traceback/main.go:72
main.TypeAssert[...](...)
	/Users/bytedance/workspace/traceback/main.go:72
main.TypeAssert[...](...)
	/Users/bytedance/workspace/traceback/main.go:72
main.TypeAssert[...](...)
	/Users/bytedance/workspace/traceback/main.go:72
main.TypeAssert[...](...)
	/Users/bytedance/workspace/traceback/main.go:72
main.TypeAssert[...](...)
	/Users/bytedance/workspace/traceback/main.go:72
main.TypeAssert[...](...)
	/Users/bytedance/workspace/traceback/main.go:72
main.TypeAssert[...](...)
	/Users/bytedance/workspace/traceback/main.go:72
main.TypeAssert[...](...)
```

**Comment by ianlancetaylor** [comment]
CC @golang/runtime @mdempsky

**Comment by mdempsky** [comment]
I think this is #54625.

**Comment by mdempsky** [comment]
Minimized test case:

```
package main

func assert[To any](v any) {
	_ = v.(To)
}

func Assert[To any]() func(any) {
	return assert[To]
}

func main() {
	var fn func(any)
	fn = Assert[string]()
	fn(1)
}
```

I'm beginning to suspect this is instead another instance of #46234, but for the synthetic function literals that the unified frontend generates in some cases.

**Comment by mdempsky** [comment]
Extending the same kludge from 6a801d3082c6ab28372c115d13ef0c238e3535ae to synthetic closures fixes the issue. That's probably the easiest solution for backporting to 1.20.

@gopherbot Please backport to Go 1.20.
