### ISSUE TITLE
cmd/link: unexpected fault in bootstrap toolchain

### ISSUE THREAD

**Issue by prattmic** [golang/go#58530]
```
#!watchflakes
post <- `unexpected fault` && `compiler_bootstrap`
```

https://go.dev/cl/468302 got this failure in trybots:

https://storage.googleapis.com/go-build-log/efd861d1/windows-amd64-longtest_9ff2b55d.log

```
Building Go cmd/dist using C:\workdir\go1.4. (go1.17.13 windows/amd64)
Building Go toolchain1 using C:\workdir\go1.4.
# bootstrap/cmd/asm
unexpected fault address 0xffffffffffffffff
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0xffffffffffffffff pc=0x12c28e4]

goroutine 1 [running]:
runtime.throw({0x1530041, 0xc000d23b8a})
	/tmp/genbootstrap-3894857761/go-windows-amd64-bootstrap/src/runtime/panic.go:1198 +0x76 fp=0xc00009c620 sp=0xc00009c5f0 pc=0x12e7f76
runtime.sigpanic()
	/tmp/genbootstrap-3894857761/go-windows-amd64-bootstrap/src/runtime/signal_windows.go:260 +0x10c fp=0xc00009c668 sp=0xc00009c620 pc=0x12fc4ac
runtime.mapaccess2_faststr(0x14f7660, 0xc00050e000, {0xc0032d9e00, 0x2e})
	/tmp/genbootstrap-3894857761/go-windows-amd64-bootstrap/src/runtime/map_faststr.go:191 +0x164 fp=0xc00009c6d0 sp=0xc00009c668 pc=0x12c28e4
cmd/link/internal/loader.(*loadState).addSym(0xc00068c000, {0xc0032d9e00, 0x2e}, 0x1, 0xc000024100, 0x1865, 0xc000059400, 0xc000d02fe2)
	/tmp/genbootstrap-3894857761/go-windows-amd64-bootstrap/src/cmd/link/internal/loader/loader.go:451 +0x575 fp=0xc00009c830 sp=0xc00009c6d0 pc=0x13b96f5
cmd/link/internal/loader.(*loadState).preloadSyms(0xc00009cb78, 0xc000024100, 0xc00009c998)
	/tmp/genbootstrap-3894857761/go-windows-amd64-bootstrap/src/cmd/link/internal/loader/loader.go:2176 +0x2aa fp=0xc00009c900 sp=0xc00009c830 pc=0x13bf86a
cmd/link/internal/loader.(*Loader).LoadSyms(0xc00068c000, 0xc0000c2ae0)
	/tmp/genbootstrap-3894857761/go-windows-amd64-bootstrap/src/cmd/link/internal/loader/loader.go:2225 +0x42c fp=0xc00009cc00 sp=0xc00009c900 pc=0x13c01ac
cmd/link/internal/ld.(*Link).loadlib(0xc000118000)
	/tmp/genbootstrap-3894857761/go-windows-amd64-bootstrap/src/cmd/link/internal/ld/lib.go:577 +0x46e fp=0xc00009ccb0 sp=0xc00009cc00 pc=0x144d80e
cmd/link/internal/ld.Main(_, {0x20, 0x20, 0x1, 0x7, 0x10, 0x0, {0x0, 0x0}, {0x153ce37, ...}, ...})
	/tmp/genbootstrap-3894857761/go-windows-amd64-bootstrap/src/cmd/link/internal/ld/main.go:249 +0xd8b fp=0xc00009cf28 sp=0xc00009ccb0 pc=0x1469a2b
main.main()
	/tmp/genbootstrap-3894857761/go-windows-amd64-bootstrap/src/cmd/link/main.go:69 +0x1005 fp=0xc00009df80 sp=0xc00009cf28 pc=0x14d3985
runtime.main()
	/tmp/genbootstrap-3894857761/go-windows-amd64-bootstrap/src/runtime/proc.go:255 +0x217 fp=0xc00009dfe0 sp=0xc00009df80 pc=0x12ea537
runtime.goexit()
	/tmp/genbootstrap-3894857761/go-windows-amd64-bootstrap/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00009dfe8 sp=0xc00009dfe0 pc=0x1316181
# bootstrap/cmd/link/internal/ld
C:\workdir\go\src\cmd\link\internal\ld\data.go:1773: internal compiler error: '(*dodataState).allocateDataSections': panic during early deadcode while compiling (*dodataState).allocateDataSections:

runtime error: index out of range [1311744] with length 6192

goroutine 45 [running]:
cmd/compile/internal/ssa.Compile.func1()
	/tmp/genbootstrap-3894857761/go-windows-amd64-bootstrap/src/cmd/compile/internal/ssa/compile.go:48 +0x71
panic({0x14f8540, 0xc0005ba9f0})
	/tmp/genbootstrap-3894857761/go-windows-amd64-bootstrap/src/runtime/panic.go:1038 +0x215
cmd/compile/internal/ssa.liveValues(0xc00192c000, {0xc0042242c0, 0x2b4, 0x0})
	/tmp/genbootstrap-3894857761/go-windows-amd64-bootstrap/src/cmd/compile/internal/ssa/deadcode.go:114 +0xeb0
cmd/compile/internal/ssa.deadcode(0xc00192c000)
	/tmp/genbootstrap-3894857761/go-windows-amd64-bootstrap/src/cmd/compile/internal/ssa/deadcode.go:215 +0x1c5
cmd/compile/internal/ssa.Compile(0xc00192c000)
	/tmp/genbootstrap-3894857761/go-windows-amd64-bootstrap/src/cmd/compile/internal/ssa/compile.go:96 +0x9e7
cmd/compile/internal/ssagen.buildssa(0xc000e022c0, 0x3)
	/tmp/genbootstrap-3894857761/go-windows-amd64-bootstrap/src/cmd/compile/internal/ssagen/ssa.go:642 +0x1e50
cmd/compile/internal/ssagen.Compile(0xc000e022c0, 0xc000403f90)
	/tmp/genbootstrap-3894857761/go-windows-amd64-bootstrap/src/cmd/compile/internal/ssagen/pgen.go:165 +0x4c
cmd/compile/internal/gc.compileFunctions.func4.1(0x0)
	/tmp/genbootstrap-3894857761/go-windows-amd64-bootstrap/src/cmd/compile/internal/gc/compile.go:153 +0x3a
cmd/compile/internal/gc.compileFunctions.func3.1()
	/tmp/genbootstrap-3894857761/go-windows-amd64-bootstrap/src/cmd/compile/internal/gc/compile.go:140 +0x4d
created by cmd/compile/internal/gc.compileFunctions.func3
	/tmp/genbootstrap-3894857761/go-windows-amd64-bootstrap/src/cmd/compile/internal/gc/compile.go:138 +0x7f



Please file a bug report including a short program that triggers the error.
https://golang.org/issue/new
go tool dist: FAILED: C:\workdir\go1.4\bin\go install -tags=math_big_pure_go compiler_bootstrap purego bootstrap/cmd/...: exit status 2
```

cc @golang/compiler

**Comment by cherrymui** [comment]
Maybe similar to #56337 ?

**Comment by mknyszek** [comment]
In triage, I'm not sure there's anything actionable now.
