### ISSUE TITLE
cmd/link: crossbuild panic GOOS=openbsd GOARCH=mips64

### ISSUE THREAD

**Issue by sylr** [golang/go#58596]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.20.1
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

See https://github.com/sylr/yage/actions/runs/4217364884/jobs/7321088119

```bash
CGO_ENABLED=0 GOOS=linux GOARCH=mips64 /opt/hostedtoolcache/go/1.20.1/x64/bin/go build -tags static,crossbuild -trimpath -ldflags '-s -w -X sylr.dev/yage/v2/cmd.Version=v1.2.0-11-g9d89744 -extldflags ""' -o dist/yage-v1.2.0-11-g9d89744-linux-mips64
CGO_ENABLED=0 GOOS=openbsd GOARCH=mips64 /opt/hostedtoolcache/go/1.20.1/x64/bin/go build -tags static,crossbuild -trimpath -ldflags '-s -w -X sylr.dev/yage/v2/cmd.Version=v1.2.0-11-g9d89744 -extldflags ""' -o dist/yage-v1.2.0-11-g9d89744-openbsd-mips64
# sylr.dev/yage/v2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x55f086]

goroutine 1 [running]:
cmd/link/internal/ld.dynrelocsym(0xc000106000, 0x7f5cfb7c85a7?)
	/usr/local/go/src/cmd/link/internal/ld/data.go:917 +0x306
cmd/link/internal/ld.(*dodataState).dynreloc(0xc00074e500, 0xc000106000)
	/usr/local/go/src/cmd/link/internal/ld/data.go:935 +0x9b
cmd/link/internal/ld.(*Link).dodata(0xc000106000, {0xc001c80000, 0x2bd55, 0x2bd55})
	/usr/local/go/src/cmd/link/internal/ld/data.go:1566 +0x45d
cmd/link/internal/ld.Main(_, {0x8, 0x20, 0x1, 0x1d, 0x1f, 0x0, {0x0, 0x0}, {0x68cee3, ...}, ...})
	/usr/local/go/src/cmd/link/internal/ld/main.go:338 +0x153b
main.main()
	/usr/local/go/src/cmd/link/main.go:72 +0xedb
make: *** [Makefile:184: dist/yage-v1.2.0-11-g9d89744-openbsd-mips64] Error 1
Error: Process completed with exit code 2.
```

**Comment by ianlancetaylor** [comment]
CC @thanm @cherrymui @golang/mips

**Comment by thanm** [comment]
This is a dup of #58240.
