### ISSUE TITLE
go vet --vettool panic: assertion failed in go 1.20.1 darwin/arm64 while it should say: export data is newer version - update tool

### ISSUE THREAD

**Issue by jtorvald** [golang/go#58644]
I figured out what the issue is but I leave what I wrote initially below since I think the error message can be improved and not just panic.

When trying the same example on an Intel Mac I got a useful output that made me resolve the issue.
Maybe the arm code can be fixed to give a useful error message.

Below is on go 1.20.1 darwin/amd64
```
$ go vet --vettool=$(which sqlrows) ./...
# internal/abi
sqlrows: /usr/local/go/src/internal/abi/abi.go:8:2: could not import internal/goarch (cannot import "internal/goarch" (unknown iexport format version 2), export data is newer version - update tool)
# runtime/internal/math
sqlrows: /usr/local/go/src/runtime/internal/math/math.go:7:8: could not import internal/goarch (cannot import "internal/goarch" (unknown iexport format version 2), export data is newer version - update tool)
# internal/bytealg
sqlrows: /usr/local/go/src/internal/bytealg/bytealg.go:8:2: could not import internal/cpu (cannot import "internal/cpu" (unknown iexport format version 2), export data is newer version - update tool)
# runtime/internal/sys
sqlrows: /usr/local/go/src/runtime/internal/sys/consts.go:8:2: could not import internal/goarch (cannot import "internal/goarch" (unknown iexport format version 2), export data is newer version - update tool)
# runtime
sqlrows: /usr/local/go/src/runtime/alg.go:8:2: could not import internal/cpu (cannot import "internal/cpu" (unknown iexport format version 2), export data is newer version - update tool)
```

-- BELOW THE ISSUE I WANTED TO FILE --
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.1 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/developer/Library/Caches/go-build"
GOENV="/Users/developer/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/developer/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/developer/go/"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/developer/Projects/go/vettooltest/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/jn/094l6wv16cbcnw_4mqy2mdrh0000gn/T/go-build1110892134=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
I had this error in a big project so I tried to make a minimal working example and the code below results in the same issue.
It is not dependent on sqlrows, it also gives the same error with bodyclose for example.

```
echo "package main\nfunc main(){\n}" > main.go
go mod init example.com/foo
go mod tidy
go vet --vettool=$(which sqlrows)
```

### What did you expect to see?
The tool to work.

### What did you see instead?

<details><summary><code>go vet --vettool=$(which sqlrows)</code> Panic Output</summary><br><pre>
```
# runtime/internal/atomic
panic: assertion failed [recovered]
	panic: assertion failed

goroutine 1 [running]:
go/types.(*Checker).handleBailout(0x14000138380, 0x1400020bae8)
	/usr/local/go/src/go/types/check.go:302 +0x9c
panic({0x104556500, 0x1045afb80})
	/usr/local/go/src/runtime/panic.go:884 +0x204
internal/pkgbits.assert(...)
	/usr/local/go/src/internal/pkgbits/support.go:11
internal/pkgbits.NewPkgDecoder({0x1400010e6f4, 0xc}, {0x140002c4c00, 0xaee})
	/usr/local/go/src/internal/pkgbits/decoder.go:72 +0x354
go/internal/gcimporter.Import(0x1?, 0x0?, {0x1400010e6f4, 0xc}, {0x0?, 0x1045693c0?}, 0x140002999a0?)
	/usr/local/go/src/go/internal/gcimporter/gcimporter.go:169 +0x5c0
go/importer.(*gcimports).ImportFrom(0x1400020b168?, {0x1400010e6f4?, 0x1044c8e80?}, {0x0?, 0x1045692c0?}, 0x14000122240?)
	/usr/local/go/src/go/importer/importer.go:102 +0x4c
go/importer.(*gcimports).Import(0x104563a40?, {0x1400010e6f4?, 0x1400010e7a1?})
	/usr/local/go/src/go/importer/importer.go:95 +0x2c
golang.org/x/tools/go/analysis/unitchecker.run.func2({0x1400010e7a1?, 0x140002b1140?})
	/Users/developer/go/pkg/mod/golang.org/x/tools@v0.0.0-20190401205534-4c644d7e323d/go/analysis/unitchecker/unitchecker.go:220 +0x6c
golang.org/x/tools/go/analysis/unitchecker.importerFunc.Import(0x140001448c0?, {0x1400010e7a1?, 0x140002b1140?})
	/Users/developer/go/pkg/mod/golang.org/x/tools@v0.0.0-20190401205534-4c644d7e323d/go/analysis/unitchecker/unitchecker.go:388 +0x30
go/types.(*Checker).importPackage(0x14000138380, {0x1045b0b38, 0x1400010c240}, {0x1400010e7a1, 0xc}, {0x14000168040, 0x29})
	/usr/local/go/src/go/types/resolver.go:162 +0x1b8
go/types.(*Checker).collectObjects.func1({0x1045b14b8?, 0x14000110ff0?})
	/usr/local/go/src/go/types/resolver.go:263 +0x3b4
go/types.(*Checker).walkDecl(0x14000168040?, {0x1045b2a58?, 0x14000113940?}, 0x1400020b9b0)
	/usr/local/go/src/go/types/decl.go:396 +0x204
go/types.(*Checker).walkDecls(...)
	/usr/local/go/src/go/types/decl.go:383
go/types.(*Checker).collectObjects(0x14000138380)
	/usr/local/go/src/go/types/resolver.go:253 +0xa44
go/types.(*Checker).checkFiles(0x14000138380, {0x140002a1d80?, 0x140002b9630?, 0x0?})
	/usr/local/go/src/go/types/check.go:329 +0xa4
go/types.(*Checker).Files(...)
	/usr/local/go/src/go/types/check.go:307
go/types.(*Config).Check(0x1045632c0?, {0x1400012e0d8?, 0x14000026057?}, 0x5?, {0x140002a1d80, 0x6, 0x8}, 0x10427f89c?)
	/usr/local/go/src/go/types/api.go:411 +0x70
golang.org/x/tools/go/analysis/unitchecker.run(0x14000113900, 0x14000124630, {0x14000114548, 0x1, 0x0?})
	/Users/developer/go/pkg/mod/golang.org/x/tools@v0.0.0-20190401205534-4c644d7e323d/go/analysis/unitchecker/unitchecker.go:234 +0x340
golang.org/x/tools/go/analysis/unitchecker.Run({0x16bb8b623?, 0x1?}, {0x14000114548, 0x1, 0x1})
	/Users/developer/go/pkg/mod/golang.org/x/tools@v0.0.0-20190401205534-4c644d7e323d/go/analysis/unitchecker/unitchecker.go:130 +0x90
golang.org/x/tools/go/analysis/unitchecker.Main({0x14000114548, 0x1, 0x1})
	/Users/developer/go/pkg/mod/golang.org/x/tools@v0.0.0-20190401205534-4c644d7e323d/go/analysis/unitchecker/unitchecker.go:117 +0x2e8
main.main()
	/Users/developer/Projects/go/sqlrows/main_go112.go:19 +0x5c
# internal/abi
panic: assertion failed [recovered]
	panic: assertion failed

goroutine 1 [running]:
go/types.(*Checker).handleBailout(0x140001e6380, 0x14000299ae8)
	/usr/local/go/src/go/types/check.go:302 +0x9c
panic({0x1052d2500, 0x10532bb80})
	/usr/local/go/src/runtime/panic.go:884 +0x204
internal/pkgbits.assert(...)
	/usr/local/go/src/internal/pkgbits/support.go:11
internal/pkgbits.NewPkgDecoder({0x140001a4b70, 0xf}, {0x140002ac000, 0xc4c})
	/usr/local/go/src/internal/pkgbits/decoder.go:72 +0x354
go/internal/gcimporter.Import(0x1?, 0x0?, {0x140001a4b70, 0xf}, {0x0?, 0x1052e53c0?}, 0x1400029a090?)
	/usr/local/go/src/go/internal/gcimporter/gcimporter.go:169 +0x5c0
go/importer.(*gcimports).ImportFrom(0x14000299168?, {0x140001a4b70?, 0x105244e80?}, {0x0?, 0x1052e52c0?}, 0x140001cca20?)
	/usr/local/go/src/go/importer/importer.go:102 +0x4c
go/importer.(*gcimports).Import(0x1052dfa40?, {0x140001a4b70?, 0x140001ae109?})
	/usr/local/go/src/go/importer/importer.go:95 +0x2c
golang.org/x/tools/go/analysis/unitchecker.run.func2({0x140001ae109?, 0x140001ab9c0?})
	/Users/developer/go/pkg/mod/golang.org/x/tools@v0.0.0-20190401205534-4c644d7e323d/go/analysis/unitchecker/unitchecker.go:220 +0x6c
golang.org/x/tools/go/analysis/unitchecker.importerFunc.Import(0x14000299218?, {0x140001ae109?, 0x140001ab9c0?})
	/Users/developer/go/pkg/mod/golang.org/x/tools@v0.0.0-20190401205534-4c644d7e323d/go/analysis/unitchecker/unitchecker.go:388 +0x30
go/types.(*Checker).importPackage(0x140001e6380, {0x10532cb38, 0x140001aa340}, {0x140001ae109, 0xf}, {0x140001d80c0, 0x1e})
	/usr/local/go/src/go/types/resolver.go:162 +0x1b8
go/types.(*Checker).collectObjects.func1({0x10532d4b8?, 0x14000187aa0?})
	/usr/local/go/src/go/types/resolver.go:263 +0x3b4
go/types.(*Checker).walkDecl(0x140001d80c0?, {0x10532ea58?, 0x140001a3d00?}, 0x140002999b0)
	/usr/local/go/src/go/types/decl.go:396 +0x204
go/types.(*Checker).walkDecls(...)
	/usr/local/go/src/go/types/decl.go:383
go/types.(*Checker).collectObjects(0x140001e6380)
	/usr/local/go/src/go/types/resolver.go:253 +0xa44
go/types.(*Checker).checkFiles(0x140001e6380, {0x1400029a080?, 0x14000181e50?, 0x0?})
	/usr/local/go/src/go/types/check.go:329 +0xa4
go/types.(*Checker).Files(...)
	/usr/local/go/src/go/types/check.go:307
go/types.(*Config).Check(0x1052df2c0?, {0x140001a4b60?, 0x14000026057?}, 0x5?, {0x1400029a080, 0x2, 0x2}, 0x104ffb89c?)
	/usr/local/go/src/go/types/api.go:411 +0x70
golang.org/x/tools/go/analysis/unitchecker.run(0x140001a3c80, 0x140001dc420, {0x1400019c5b0, 0x1, 0x0?})
	/Users/developer/go/pkg/mod/golang.org/x/tools@v0.0.0-20190401205534-4c644d7e323d/go/analysis/unitchecker/unitchecker.go:234 +0x340
golang.org/x/tools/go/analysis/unitchecker.Run({0x16ae0f63b?, 0x1?}, {0x1400019c5b0, 0x1, 0x1})
	/Users/developer/go/pkg/mod/golang.org/x/tools@v0.0.0-20190401205534-4c644d7e323d/go/analysis/unitchecker/unitchecker.go:130 +0x90
golang.org/x/tools/go/analysis/unitchecker.Main({0x1400019c5b0, 0x1, 0x1})
	/Users/developer/go/pkg/mod/golang.org/x/tools@v0.0.0-20190401205534-4c644d7e323d/go/analysis/unitchecker/unitchecker.go:117 +0x2e8
main.main()
	/Users/developer/Projects/go/sqlrows/main_go112.go:19 +0x5c
# runtime/internal/sys
panic: assertion failed [recovered]
	panic: assertion failed

goroutine 1 [running]:
go/types.(*Checker).handleBailout(0x14000176380, 0x1400020bae8)
	/usr/local/go/src/go/types/check.go:302 +0x9c
panic({0x102a16500, 0x102a6fb80})
	/usr/local/go/src/runtime/panic.go:884 +0x204
internal/pkgbits.assert(...)
	/usr/local/go/src/internal/pkgbits/support.go:11
internal/pkgbits.NewPkgDecoder({0x14000132b70, 0xf}, {0x140002c2000, 0xc4c})
	/usr/local/go/src/internal/pkgbits/decoder.go:72 +0x354
go/internal/gcimporter.Import(0x1?, 0x0?, {0x14000132b70, 0xf}, {0x0?, 0x102a293c0?}, 0x140002ac7b0?)
	/usr/local/go/src/go/internal/gcimporter/gcimporter.go:169 +0x5c0
go/importer.(*gcimports).ImportFrom(0x1400020b168?, {0x14000132b70?, 0x102988e80?}, {0x0?, 0x102a292c0?}, 0x1400015cfc0?)
	/usr/local/go/src/go/importer/importer.go:102 +0x4c
go/importer.(*gcimports).Import(0x102a23a40?, {0x14000132b70?, 0x1400013c139?})
	/usr/local/go/src/go/importer/importer.go:95 +0x2c
golang.org/x/tools/go/analysis/unitchecker.run.func2({0x1400013c139?, 0x140002abea0?})
	/Users/developer/go/pkg/mod/golang.org/x/tools@v0.0.0-20190401205534-4c644d7e323d/go/analysis/unitchecker/unitchecker.go:220 +0x6c
golang.org/x/tools/go/analysis/unitchecker.importerFunc.Import(0x140001508c0?, {0x1400013c139?, 0x140002abea0?})
	/Users/developer/go/pkg/mod/golang.org/x/tools@v0.0.0-20190401205534-4c644d7e323d/go/analysis/unitchecker/unitchecker.go:388 +0x30
go/types.(*Checker).importPackage(0x14000176380, {0x102a70b38, 0x140001382e0}, {0x1400013c139, 0xf}, {0x14000136120, 0x26})
	/usr/local/go/src/go/types/resolver.go:162 +0x1b8
go/types.(*Checker).collectObjects.func1({0x102a714b8?, 0x1400010db30?})
	/usr/local/go/src/go/types/resolver.go:263 +0x3b4
go/types.(*Checker).walkDecl(0x14000136120?, {0x102a72a58?, 0x14000131c80?}, 0x1400020b9b0)
	/usr/local/go/src/go/types/decl.go:396 +0x204
go/types.(*Checker).walkDecls(...)
	/usr/local/go/src/go/types/decl.go:383
go/types.(*Checker).collectObjects(0x14000176380)
	/usr/local/go/src/go/types/resolver.go:253 +0xa44
go/types.(*Checker).checkFiles(0x14000176380, {0x140002a3a80?, 0x140002aea00?, 0x0?})
	/usr/local/go/src/go/types/check.go:329 +0xa4
go/types.(*Checker).Files(...)
	/usr/local/go/src/go/types/check.go:307
go/types.(*Config).Check(0x102a232c0?, {0x1400013c120?, 0x14000026057?}, 0x5?, {0x140002a3a80, 0x7, 0x8}, 0x10273f89c?)
	/usr/local/go/src/go/types/api.go:411 +0x70
golang.org/x/tools/go/analysis/unitchecker.run(0x14000131c40, 0x1400016a4d0, {0x14000122588, 0x1, 0x0?})
	/Users/developer/go/pkg/mod/golang.org/x/tools@v0.0.0-20190401205534-4c644d7e323d/go/analysis/unitchecker/unitchecker.go:234 +0x340
golang.org/x/tools/go/analysis/unitchecker.Run({0x16d6cb62b?, 0x1?}, {0x14000122588, 0x1, 0x1})
	/Users/developer/go/pkg/mod/golang.org/x/tools@v0.0.0-20190401205534-4c644d7e323d/go/analysis/unitchecker/unitchecker.go:130 +0x90
golang.org/x/tools/go/analysis/unitchecker.Main({0x14000122588, 0x1, 0x1})
	/Users/developer/go/pkg/mod/golang.org/x/tools@v0.0.0-20190401205534-4c644d7e323d/go/analysis/unitchecker/unitchecker.go:117 +0x2e8
main.main()
	/Users/developer/Projects/go/sqlrows/main_go112.go:19 +0x5c
# runtime/internal/math
panic: assertion failed [recovered]
	panic: assertion failed

goroutine 1 [running]:
go/types.(*Checker).handleBailout(0x140000c6380, 0x140000a3ae8)
	/usr/local/go/src/go/types/check.go:302 +0x9c
panic({0x102e9a500, 0x102ef3b80})
	/usr/local/go/src/runtime/panic.go:884 +0x204
internal/pkgbits.assert(...)
	/usr/local/go/src/internal/pkgbits/support.go:11
internal/pkgbits.NewPkgDecoder({0x14000026810, 0xf}, {0x14000286000, 0xc4c})
	/usr/local/go/src/internal/pkgbits/decoder.go:72 +0x354
go/internal/gcimporter.Import(0x1?, 0x0?, {0x14000026810, 0xf}, {0x0?, 0x102ead3c0?}, 0x1400007d860?)
	/usr/local/go/src/go/internal/gcimporter/gcimporter.go:169 +0x5c0
go/importer.(*gcimports).ImportFrom(0x140000a3168?, {0x14000026810?, 0x102e0ce80?}, {0x0?, 0x102ead2c0?}, 0x140000005a0?)
	/usr/local/go/src/go/importer/importer.go:102 +0x4c
go/importer.(*gcimports).Import(0x102ea7a40?, {0x14000026810?, 0x1400002a1f9?})
	/usr/local/go/src/go/importer/importer.go:95 +0x2c
golang.org/x/tools/go/analysis/unitchecker.run.func2({0x1400002a1f9?, 0x1400001eea0?})
	/Users/developer/go/pkg/mod/golang.org/x/tools@v0.0.0-20190401205534-4c644d7e323d/go/analysis/unitchecker/unitchecker.go:220 +0x6c
golang.org/x/tools/go/analysis/unitchecker.importerFunc.Import(0x14000088480?, {0x1400002a1f9?, 0x1400001eea0?})
	/Users/developer/go/pkg/mod/golang.org/x/tools@v0.0.0-20190401205534-4c644d7e323d/go/analysis/unitchecker/unitchecker.go:388 +0x30
go/types.(*Checker).importPackage(0x140000c6380, {0x102ef4b38, 0x1400001e320}, {0x1400002a1f9, 0xf}, {0x1400002e210, 0x27})
	/usr/local/go/src/go/types/resolver.go:162 +0x1b8
go/types.(*Checker).collectObjects.func1({0x102ef54b8?, 0x1400009b4d0?})
	/usr/local/go/src/go/types/resolver.go:263 +0x3b4
go/types.(*Checker).walkDecl(0x1400002e210?, {0x102ef6a58?, 0x140000a5a40?}, 0x140000a39b0)
	/usr/local/go/src/go/types/decl.go:396 +0x204
go/types.(*Checker).walkDecls(...)
	/usr/local/go/src/go/types/decl.go:383
go/types.(*Checker).collectObjects(0x140000c6380)
	/usr/local/go/src/go/types/resolver.go:253 +0xa44
go/types.(*Checker).checkFiles(0x140000c6380, {0x1400000e690?, 0x140000aa780?, 0x0?})
	/usr/local/go/src/go/types/check.go:329 +0xa4
go/types.(*Checker).Files(...)
	/usr/local/go/src/go/types/check.go:307
go/types.(*Config).Check(0x102ea72c0?, {0x1400002a1e0?, 0x14000026057?}, 0x5?, {0x1400000e690, 0x1, 0x1}, 0x102bc389c?)
	/usr/local/go/src/go/types/api.go:411 +0x70
golang.org/x/tools/go/analysis/unitchecker.run(0x140000a5a00, 0x140000b4420, {0x1400000e578, 0x1, 0x0?})
	/Users/developer/go/pkg/mod/golang.org/x/tools@v0.0.0-20190401205534-4c644d7e323d/go/analysis/unitchecker/unitchecker.go:234 +0x340
golang.org/x/tools/go/analysis/unitchecker.Run({0x16d24762b?, 0x1?}, {0x1400000e578, 0x1, 0x1})
	/Users/developer/go/pkg/mod/golang.org/x/tools@v0.0.0-20190401205534-4c644d7e323d/go/analysis/unitchecker/unitchecker.go:130 +0x90
golang.org/x/tools/go/analysis/unitchecker.Main({0x1400000e578, 0x1, 0x1})
	/Users/developer/go/pkg/mod/golang.org/x/tools@v0.0.0-20190401205534-4c644d7e323d/go/analysis/unitchecker/unitchecker.go:117 +0x2e8
main.main()
	/Users/developer/Projects/go/sqlrows/main_go112.go:19 +0x5c
# internal/bytealg
panic: assertion failed [recovered]
	panic: assertion failed

goroutine 1 [running]:
go/types.(*Checker).handleBailout(0x140000b6380, 0x140000fbae8)
	/usr/local/go/src/go/types/check.go:302 +0x9c
panic({0x104a7e500, 0x104ad7b80})
	/usr/local/go/src/runtime/panic.go:884 +0x204
internal/pkgbits.assert(...)
	/usr/local/go/src/internal/pkgbits/support.go:11
internal/pkgbits.NewPkgDecoder({0x14000026804, 0xc}, {0x14000296c00, 0xaee})
	/usr/local/go/src/internal/pkgbits/decoder.go:72 +0x354
go/internal/gcimporter.Import(0x1?, 0x0?, {0x14000026804, 0xc}, {0x0?, 0x104a913c0?}, 0x140000ef090?)
	/usr/local/go/src/go/internal/gcimporter/gcimporter.go:169 +0x5c0
go/importer.(*gcimports).ImportFrom(0x140000fb168?, {0x14000026804?, 0x1049f0e80?}, {0x0?, 0x104a912c0?}, 0x14000000360?)
	/usr/local/go/src/go/importer/importer.go:102 +0x4c
go/importer.(*gcimports).Import(0x104a8ba40?, {0x14000026804?, 0x140000268b1?})
	/usr/local/go/src/go/importer/importer.go:95 +0x2c
golang.org/x/tools/go/analysis/unitchecker.run.func2({0x140000268b1?, 0x140002868e0?})
	/Users/developer/go/pkg/mod/golang.org/x/tools@v0.0.0-20190401205534-4c644d7e323d/go/analysis/unitchecker/unitchecker.go:220 +0x6c
golang.org/x/tools/go/analysis/unitchecker.importerFunc.Import(0x1400011e680?, {0x140000268b1?, 0x140002868e0?})
	/Users/developer/go/pkg/mod/golang.org/x/tools@v0.0.0-20190401205534-4c644d7e323d/go/analysis/unitchecker/unitchecker.go:388 +0x30
go/types.(*Checker).importPackage(0x140000b6380, {0x104ad8b38, 0x1400001e280}, {0x140000268b1, 0xc}, {0x1400002e1e0, 0x22})
	/usr/local/go/src/go/types/resolver.go:162 +0x1b8
go/types.(*Checker).collectObjects.func1({0x104ad94b8?, 0x1400009d260?})
	/usr/local/go/src/go/types/resolver.go:263 +0x3b4
go/types.(*Checker).walkDecl(0x1400002e1e0?, {0x104adaa58?, 0x1400009ba40?}, 0x140000fb9b0)
	/usr/local/go/src/go/types/decl.go:396 +0x204
go/types.(*Checker).walkDecls(...)
	/usr/local/go/src/go/types/decl.go:383
go/types.(*Checker).collectObjects(0x140000b6380)
	/usr/local/go/src/go/types/resolver.go:253 +0xa44
go/types.(*Checker).checkFiles(0x140000b6380, {0x14000280880?, 0x1400028c500?, 0x0?})
	/usr/local/go/src/go/types/check.go:329 +0xa4
go/types.(*Checker).Files(...)
	/usr/local/go/src/go/types/check.go:307
go/types.(*Config).Check(0x104a8b2c0?, {0x14000026810?, 0x14000026057?}, 0x5?, {0x14000280880, 0x8, 0x8}, 0x1047a789c?)
	/usr/local/go/src/go/types/api.go:411 +0x70
golang.org/x/tools/go/analysis/unitchecker.run(0x1400009ba00, 0x140000a4420, {0x1400000e560, 0x1, 0x0?})
	/Users/developer/go/pkg/mod/golang.org/x/tools@v0.0.0-20190401205534-4c644d7e323d/go/analysis/unitchecker/unitchecker.go:234 +0x340
golang.org/x/tools/go/analysis/unitchecker.Run({0x16b663633?, 0x1?}, {0x1400000e560, 0x1, 0x1})
	/Users/developer/go/pkg/mod/golang.org/x/tools@v0.0.0-20190401205534-4c644d7e323d/go/analysis/unitchecker/unitchecker.go:130 +0x90
golang.org/x/tools/go/analysis/unitchecker.Main({0x1400000e560, 0x1, 0x1})
	/Users/developer/go/pkg/mod/golang.org/x/tools@v0.0.0-20190401205534-4c644d7e323d/go/analysis/unitchecker/unitchecker.go:117 +0x2e8
main.main()
	/Users/developer/Projects/go/sqlrows/main_go112.go:19 +0x5c
# runtime
panic: assertion failed [recovered]
	panic: assertion failed

goroutine 1 [running]:
go/types.(*Checker).handleBailout(0x140001f0380, 0x140016a3ae8)
	/usr/local/go/src/go/types/check.go:302 +0x9c
panic({0x1029ce500, 0x102a27b80})
	/usr/local/go/src/runtime/panic.go:884 +0x204
internal/pkgbits.assert(...)
	/usr/local/go/src/internal/pkgbits/support.go:11
internal/pkgbits.NewPkgDecoder({0x140001a4bc0, 0xc}, {0x14000ed8c00, 0xaee})
	/usr/local/go/src/internal/pkgbits/decoder.go:72 +0x354
go/internal/gcimporter.Import(0x1?, 0x0?, {0x140001a4bc0, 0xc}, {0x0?, 0x1029e13c0?}, 0x14000e9b880?)
	/usr/local/go/src/go/internal/gcimporter/gcimporter.go:169 +0x5c0
go/importer.(*gcimports).ImportFrom(0x3?, {0x140001a4bc0?, 0x140001d1238?}, {0x0?, 0x140001d1200?}, 0x140000021a0?)
	/usr/local/go/src/go/importer/importer.go:102 +0x4c
go/importer.(*gcimports).Import(0x1029dba40?, {0x140001a4bc0?, 0x140001a4d31?})
	/usr/local/go/src/go/importer/importer.go:95 +0x2c
golang.org/x/tools/go/analysis/unitchecker.run.func2({0x140001a4d31?, 0x14000ec4580?})
	/Users/developer/go/pkg/mod/golang.org/x/tools@v0.0.0-20190401205534-4c644d7e323d/go/analysis/unitchecker/unitchecker.go:220 +0x6c
golang.org/x/tools/go/analysis/unitchecker.importerFunc.Import(0x14000e963c0?, {0x140001a4d31?, 0x14000ec4580?})
	/Users/developer/go/pkg/mod/golang.org/x/tools@v0.0.0-20190401205534-4c644d7e323d/go/analysis/unitchecker/unitchecker.go:388 +0x30
go/types.(*Checker).importPackage(0x140001f0380, {0x102a28b38, 0x140001aa2e0}, {0x140001a4d31, 0xc}, {0x140001a80c0, 0x19})
	/usr/local/go/src/go/types/resolver.go:162 +0x1b8
go/types.(*Checker).collectObjects.func1({0x102a294b8?, 0x14000187bc0?})
	/usr/local/go/src/go/types/resolver.go:263 +0x3b4
go/types.(*Checker).walkDecl(0x140001a80c0?, {0x102a2aa58?, 0x140001a3d00?}, 0x140016a39b0)
	/usr/local/go/src/go/types/decl.go:396 +0x204
go/types.(*Checker).walkDecls(...)
	/usr/local/go/src/go/types/decl.go:383
go/types.(*Checker).collectObjects(0x140001f0380)
	/usr/local/go/src/go/types/resolver.go:253 +0xa44
go/types.(*Checker).checkFiles(0x140001f0380, {0x140016a4000?, 0x14000eb9b80?, 0x0?})
	/usr/local/go/src/go/types/check.go:329 +0xa4
go/types.(*Checker).Files(...)
	/usr/local/go/src/go/types/check.go:307
go/types.(*Config).Check(0x1029db2c0?, {0x140001a4b70?, 0x14000026057?}, 0x5?, {0x140016a4000, 0x85, 0x100}, 0x1026f789c?)
	/usr/local/go/src/go/types/api.go:411 +0x70
golang.org/x/tools/go/analysis/unitchecker.run(0x140001a3c80, 0x140001e6630, {0x1400019c5a0, 0x1, 0x0?})
	/Users/developer/go/pkg/mod/golang.org/x/tools@v0.0.0-20190401205534-4c644d7e323d/go/analysis/unitchecker/unitchecker.go:234 +0x340
golang.org/x/tools/go/analysis/unitchecker.Run({0x16d713643?, 0x1?}, {0x1400019c5a0, 0x1, 0x1})
	/Users/developer/go/pkg/mod/golang.org/x/tools@v0.0.0-20190401205534-4c644d7e323d/go/analysis/unitchecker/unitchecker.go:130 +0x90
golang.org/x/tools/go/analysis/unitchecker.Main({0x1400019c5a0, 0x1, 0x1})
	/Users/developer/go/pkg/mod/golang.org/x/tools@v0.0.0-20190401205534-4c644d7e323d/go/analysis/unitchecker/unitchecker.go:117 +0x2e8
main.main()
	/Users/developer/Projects/go/sqlrows/main_go112.go:19 +0x5c
</pre></details>

**Comment by bcmills** [comment]
This looks like a bug in `sqlrows`, not in `go vet` — note the bottom frame of that stack trace:
```
/Users/developer/Projects/go/sqlrows/main_go112.go
```
