### ISSUE TITLE
affected/package: net

### ISSUE THREAD

**Issue by peredwardsson** [golang/go#58656]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.1 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Latest I have access to!

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
 go env                                                          (base) 
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/peredwardsson/Library/Caches/go-build"
GOENV="/Users/peredwardsson/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/peredwardsson/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/peredwardsson/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.20.1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.20.1/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=[redacted]
GOWORK=[redacted]
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/kc/g39dt3qn1xvd2r8kxh8ypmx40000gn/T/go-build4088942653=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

https://go.dev/play/p/xZUGXOyvAq3
Intermittently reproducible here. Try again if it doesn't fail on you.

### What did you expect to see?
Output whenever there is data sent to the UDP stream. For instance, using this gstreamer pipeline:
```
gst-launch-1.0 videotestsrc ! video/x-raw,width=640,height=480,format=I420 ! vp8enc error-resilient=partitions keyframe-max-dist=10 auto-alt-ref=true cpu-used=5 deadline=1 ! rtpvp8pay ! udpsink host=127.0.0.1 port=5004
```

### What did you see instead?
2009/11/10 23:00:00 Listening on  127.0.0.1:5004
2009/11/10 23:00:00 Starting goroutine to listen for data...
panic: read udp 127.0.0.1:5004: use of closed network connection

goroutine 6 [running]:
main.start.func2()
	/tmp/sandbox2130129412/prog.go:44 +0x1c7
created by main.start
	/tmp/sandbox2130129412/prog.go:35 +0x26a

Program exited.

**Comment by peredwardsson** [comment]
Problem is that listener goes out of scope and is being used in the go routine. Minding this, it works fine.
