### ISSUE TITLE
runtime/coverage: `slice bounds out of range` in `(*emitState).VisitFuncs`

### ISSUE THREAD

**Issue by bcmills** [golang/go#58936]
```
#!watchflakes
post <- log ~ `panic: runtime error: slice bounds out of range` && log ~ `\s*runtime/coverage\.\(\*emitState\)\.VisitFuncs`
```

(Pulled out from https://github.com/golang/go/issues/55311#issuecomment-1460641424.)

<details><summary>2023-02-27 19:43 linux-arm64-longtest go@002bc94e cmd/go.TestScript (<a href="https://build.golang.org/log/a0df368bcbccf443009d16c36bd49718bbda3fce">log</a>)</summary>

    vcs-test.golang.org rerouted to http://127.0.0.1:40571
    https://vcs-test.golang.org rerouted to https://127.0.0.1:44117
    go test proxy running at GOPROXY=http://127.0.0.1:39707/mod
    2023/02/27 20:09:52 http: TLS handshake error from 127.0.0.1:39140: read tcp 127.0.0.1:44117->127.0.0.1:39140: read: connection reset by peer
    2023/02/27 20:09:52 http: TLS handshake error from 127.0.0.1:39110: EOF
    2023/02/27 20:09:52 http: TLS handshake error from 127.0.0.1:39170: EOF
    2023/02/27 20:09:55 http: TLS handshake error from 127.0.0.1:51238: EOF
    --- FAIL: TestScript (0.07s)
        --- FAIL: TestScript/cover_pkgall_imports (5.98s)
            script_test.go:134: 2023-02-27T20:10:24Z
    ...
                panic: runtime error: slice bounds out of range [:4294970564] with capacity 28534
    
                goroutine 1 [running]:
                panic({0x1ca960?, 0x40000160f0?})
                	/tmp/workdir/go/src/runtime/panic.go:1015 +0x5cc fp=0x40000cb330 sp=0x40000cb280 pc=0x7206c
                runtime.goPanicSliceAcap(0x100000cc4, 0x6f76)
                	/tmp/workdir/go/src/runtime/panic.go:139 +0xa8 fp=0x40000cb370 sp=0x40000cb330 pc=0x6f118
                runtime/coverage.(*emitState).VisitFuncs(0x40000aa140, 0x4000028770)
                	/tmp/workdir/go/src/runtime/coverage/emit.go:541 +0x698 fp=0x40000cb4b0 sp=0x40000cb370 pc=0x162c98
                internal/coverage/encodecounter.(*CoverageDataWriter).writeCounters(0x40000789c0, {0x20e438, 0x40000aa140})
    ...
                testing.(*M).Run.func4()
                	/tmp/workdir/go/src/testing/testing.go:1901 +0x28 fp=0x40000cbc90 sp=0x40000cbc70 pc=0x17da78
                testing.(*M).Run(0x40000aa0a0)
                	/tmp/workdir/go/src/testing/testing.go:1948 +0xe70 fp=0x40000cbee0 sp=0x40000cbc90 pc=0x17d770
                main.main()
                	_testmain.go:78 +0x1f0 fp=0x40000cbf70 sp=0x40000cbee0 pc=0x19b620
                runtime.main()
                	/tmp/workdir/go/src/runtime/proc.go:250 +0x398 fp=0x40000cbfd0 sp=0x40000cbf70 pc=0x76628
                runtime.goexit()
                	/tmp/workdir/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x40000cbfd0 sp=0x40000cbfd0 pc=0xcd644
</details>

I feel like this might already have a fix CL, but I can't seem to find it..?

(attn @thanm)

**Comment by thanm** [comment]
Thanks, I will take a look.

**Comment by mknyszek** [comment]
Hey @thanm, doing a sweep over all Go 1.21 issues. Any updates here? Is this resolved? Thanks.

**Comment by thanm** [comment]
This is still unresolved as far as I know. Thanks.

**Comment by winglq** [comment]
Hi,
We've met the slice out of range issue in our code.
I did some analysis on this.  The coverage data is stored at 0x163c2fa as following, it's not 4bytes aligened.
```
root@perf-dev:~/lq/jfs/cmd/meta# objdump -x meta.test |grep covctrs
000000000163c2fa l     O .noptrbss      0000000000000000              runtime.covctrs
0000000001650408 l     O .noptrbss      0000000000000000              runtime.ecovctrs
```
I watched the address of the value which leads to out of range using gdb and it was changed by the following assemble codes.

```
   0x0000000000a204d7 <+23>:    mov    %rax,0x70(%rsp)
   0x0000000000a204dc <+28>:    movl   $0x1,0xc1bf9a(%rip)        # 0x163c480 <jfs/cmd/meta.goCover_3af296631fdd__131>
=> 0x0000000000a204e6 <+38>:    mov    0xaea51c(%rip),%edx        # 0x150aa08 <jfs/cmd/meta.goCover_3af296631fdd_P>
```
address 0x163c480 is 4byte aligned, this is not correct as the slice starts from an unaligned address and each elment is 4 bytes length, but we got an address aligned element.
Currently I did not found out which code leads to the issue, hope this could provide some information to you.

**Comment by winglq** [comment]
After some investigating I found the unalignment is due to a global buffer which is not 4byte aligned in code.

**Comment by dillon-giacoppo** [comment]
This issue looks similar to https://github.com/golang/go/issues/73495 and can be triggered by user defined global variables that are not 4-byte aligned affecting alignment of `runtime.covctrs`.

On darwin/arm64 it did not result in a slice bounds error but a:

```
unexpected fault address 0x100b64f8d
fatal error: fault
[signal SIGBUS: bus error code=0x1 addr=0x100b64f8d pc=0x100947294]

goroutine 1 gp=0x140000021c0 m=0 mp=0x100b38380 [running]:
runtime.throw({0x1009886c1?, 0x14000141388?})
        /opt/homebrew/opt/go/libexec/src/runtime/panic.go:1094 +0x34 fp=0x14000141110 sp=0x140001410e0 pc=0x1008a1f24
runtime.sigpanic()
        /opt/homebrew/opt/go/libexec/src/runtime/signal_unix.go:922 +0x164 fp=0x14000141170 sp=0x14000141110 pc=0x1008a37e4
sync/atomic.(*Uint32).Load(...)
        /opt/homebrew/opt/go/libexec/src/sync/atomic/type.go:147
internal/coverage/cfile.(*emitState).VisitFuncs(0x140001008c0, 0x1400000e378)
        /opt/homebrew/opt/go/libexec/src/internal/coverage/cfile/emit.go:468 +0x114 fp=0x140001413f0 sp=0x14000141180 pc=0x100947294
internal/coverage/encodecounter.(*CoverageDataWriter).writeCounters(0x140001360f0, {0x100a1d620, 0x140001008c0}, 0x14000104260)
```

Large global arrays seem to get placed just before `runtime.covctrs` and when not 4-byte aligned cause the panic:

```
10032f840 B testing.memStats
100330ee0 B runtime.memstats
100332f40 B zz.badStruct
10039c82d B runtime.covctrs
10039c840 B runtime.ecovctrs
10039c840 B runtime.end
10039c840 B runtime.enoptrbss
```

As noted on the other issue, on `go1.26rc1` it seems the alignment is fixed only incidentally due to `crypto/internal/fips140/drbg.memory` getting placed after and correcting alignment. I am not sure what heuristic is used for ordering the addresses here and if the fix is stable or likely to break on other global sizes:

```
100361fc0 B zz.badStruct
100369e40 B crypto/internal/fips140/drbg.memory
102369e40 B runtime.covctrs
102369e50 B runtime.ecovctrs
102369e50 B runtime.enoptrbss
102369e50 B runtime.end
```

**Comment by randall77** [comment]
Simple repro (from 73495):

tmp.go
```
package p
var badSlice [8265]byte
func init() {
    badSlice[0] = 0
}
```
tmp_test.go
```
package p
import "testing"
func TestFoo(t *testing.T) {
}
```
```
go test -cover tmp.go tmp_test.go
```
Seems to fail on amd64 and arm64. In slightly different ways, but I think both are related to an unaligned atomic access.
