### ISSUE TITLE
affected/package: golang.org/x/text/cases Caser.String panics

### ISSUE THREAD

**Issue by bo-er** [golang/go#59520]
### What version of Go are you using (`go version`)?

<pre>
go version go1.20.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
YES

### What did you do?

Run this code:
```
var titleCases = cases.Title(language.AmericanEnglish)

func Title(s string) string {
	return titleCases.String(s)
}

var names = []string{"steve", "jack", "brown", "eve", "stephen", "lucy"}

func main() {

	for r := 0; r < 100; r++ {
		var wg sync.WaitGroup
		for i := 0; i < len(names); i++ {
			name := names[i]
			wg.Add(1)
			go func() {
				fmt.Println(Title(name))
				wg.Done()
			}()
		}
		wg.Wait()
	}
}
```
output:
```
Brown
Steve
Jack
Stephen
Eve
Stephen
Lucy
Steve
Jack
Brown
Eve
Stephen
Lucy
Steve
Jack
Brown
Eve
Lucy
Eve
Stephen
Jack
Brown
Eve
Stephen
Lucy
Steve
Jack
Eve
Brown
Eve
Stephen
Lucy
Steve
Jack
Brown
Steve
Stephen
Eve
Eve
Jack
Brown
Lucy
Jack
Lucy
Steve
brown
Steve
Steve
Steve
Brown
Brown
Brown
Stephen
Steve
Brown
Jack
Brown
eve
Stephen
Lucy
Lucy
Jack
Brown
Jack
Stephen
Eve
Stephen
Jack
Stephen
Eve
Jack
Brown
Eve
Eve
Stephen
Eve
panic: runtime error: index out of range [-1]

goroutine 94 [running]:
golang.org/x/text/cases.(*context).copyXOR(0x0?)
        /Users/steve/Documents/GIT/DMPTechStack/vendor/golang.org/x/text/cases/context.go:143 +0x117
golang.org/x/text/cases.title(0xc0001100a0?)
        /Users/steve/Documents/GIT/DMPTechStack/vendor/golang.org/x/text/cases/context.go:283 +0x1b4
golang.org/x/text/cases.(*titleCaser).Transform(0xc0001100a0, {0xc00020c900?, 0x0?, 0x0?}, {0xc00020c980?, 0x0?, 0x0?}, 0x0?)
        /Users/steve/Documents/GIT/DMPTechStack/vendor/golang.org/x/text/cases/map.go:354 +0x263
golang.org/x/text/transform.String({0x128cfc8, 0xc0001100a0}, {0x10c88ef, 0x7})
        /Users/steve/Documents/GIT/DMPTechStack/vendor/golang.org/x/text/transform/transform.go:601 +0x1f3
golang.org/x/text/cases.Caser.String(...)
        /Users/steve/Documents/GIT/DMPTechStack/vendor/golang.org/x/text/cases/cases.go:51
main.Title(...)
        /Users/steve/Documents/GIT/DMPTechStack/test/main.go:30
main.main.func1()
        /Users/steve/Documents/GIT/DMPTechStack/test/main.go:43 +0x70
created by main.main
        /Users/steve/Documents/GIT/DMPTechStack/test/main.go:41 +0x5d
exit status 2
```

### What did you expect to see?
The program should not panic

### What did you see instead?
The program panics

**Comment by fzipp** [comment]
https://pkg.go.dev/golang.org/x/text/cases#Caser

> A Caser may be stateful and should therefore not be shared between goroutines.
