### ISSUE TITLE
runtime: TestCgoTracebackSigpanic consistently times out on ios

### ISSUE THREAD

**Issue by bcmills** [golang/go#59912]
```
#!watchflakes
post <- goos == "ios" && pkg == "runtime" && test == "TestCgoTracebackSigpanic" && `test timed out`
```

https://build.golang.org/log/d9272f9538114ea902ecc2420eb3f48f3085107e:
```
--- FAIL: TestCgoTracebackSigpanic (119.92s)
    exec.go:200: test timed out while running command: /tmp/workdir-host-ios-arm64-corellium-ios/tmp/go-build1905640258/testprogcgo.exe TracebackSigpanic
    crash_cgo_test.go:532: /tmp/workdir-host-ios-arm64-corellium-ios/tmp/go-build1905640258/testprogcgo.exe TracebackSigpanic: exit status 2
    crash_cgo_test.go:533: SIGQUIT: quit
        PC=0x1b9e36580 m=2 sigcode=0
        
        goroutine 0 [idle]:
        runtime.pthread_cond_timedwait_relative_np(0x130048800, 0x1300487c0, 0x16f7c2dd8)
        	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/sys_darwin.go:512 +0x20 fp=0x16f7c2da0 sp=0x16f7c2d70 pc=0x100825f50
        runtime.semasleep(0xdf8475800)
        	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/os_darwin.go:60 +0xf4 fp=0x16f7c2e00 sp=0x16f7c2da0 pc=0x1008038d4
        runtime.notetsleep_internal(0x100a1d1c0, 0xdf8475800, 0x16f7c2e78?, 0x100814794?)
        	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/lock_sema.go:232 +0x128 fp=0x16f7c2e40 sp=0x16f7c2e00 pc=0x1007db958
        runtime.notetsleep(0x1422773bad8?, 0x130048480?)
        	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/lock_sema.go:283 +0x4c fp=0x16f7c2e80 sp=0x16f7c2e40 pc=0x1007dbb1c
        runtime.sysmon()
        	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/proc.go:5444 +0x20c fp=0x16f7c2ee0 sp=0x16f7c2e80 pc=0x10081480c
        runtime.mstart1()
        	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/proc.go:1508 +0x88 fp=0x16f7c2f10 sp=0x16f7c2ee0 pc=0x10080b8c8
        runtime.mstart0()
        	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/proc.go:1465 +0x64 fp=0x16f7c2f40 sp=0x16f7c2f10 pc=0x10080b824
        runtime.mstart()
        	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/asm_arm64.s:128 +0x10 fp=0x16f7c2f50 sp=0x16f7c2f40 pc=0x100838db0
        
        goroutine 1 [syscall]:
        runtime.cgocall(0x1008db7c8, 0x130042e78)
        	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/cgocall.go:157 +0x44 fp=0x130042e40 sp=0x130042e00 pc=0x1007d4734
        main._Cfunc_f1()
        	_cgo_gotypes.go:361 +0x34 fp=0x130042e70 sp=0x130042e40 pc=0x1008d0a44
        main.TracebackSigpanic()
        	/private/var/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/testdata/testprogcgo/sigpanic.go:27 +0x1c fp=0x130042e90 sp=0x130042e70 pc=0x1008d739c
        main.main()
        	/private/var/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/testdata/testprogcgo/main.go:34 +0x11c fp=0x130042f30 sp=0x130042e90 pc=0x1008d040c
        runtime.main()
        	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/proc.go:267 +0x2bc fp=0x130042fd0 sp=0x130042f30 pc=0x100808cac
        runtime.goexit()
        	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/asm_arm64.s:1197 +0x4 fp=0x130042fd0 sp=0x130042fd0 pc=0x10083b544
        
        goroutine 2 [force gc (idle)]:
        runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/proc.go:398 +0xc8 fp=0x130043f90 sp=0x130043f70 pc=0x100809108
        runtime.goparkunlock(...)
        	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/proc.go:404
        runtime.forcegchelper()
        	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/proc.go:322 +0xb8 fp=0x130043fd0 sp=0x130043f90 pc=0x100808f68
        runtime.goexit()
        	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/asm_arm64.s:1197 +0x4 fp=0x130043fd0 sp=0x130043fd0 pc=0x10083b544
        created by runtime.init.6 in goroutine 1
        	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/proc.go:310 +0x24
        
        goroutine 3 [GC sweep wait]:
        runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/proc.go:398 +0xc8 fp=0x130044f60 sp=0x130044f40 pc=0x100809108
        runtime.goparkunlock(...)
        	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/proc.go:404
        runtime.bgsweep(0x0?)
        	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/mgcsweep.go:280 +0xa0 fp=0x130044fb0 sp=0x130044f60 pc=0x1007f4790
        runtime.gcenable.func1()
        	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/mgc.go:178 +0x28 fp=0x130044fd0 sp=0x130044fb0 pc=0x1007e9198
        runtime.goexit()
        	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/asm_arm64.s:1197 +0x4 fp=0x130044fd0 sp=0x130044fd0 pc=0x10083b544
        created by runtime.gcenable in goroutine 1
        	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/mgc.go:178 +0x6c
        
        goroutine 4 [GC scavenge wait]:
        runtime.gopark(0x130072000?, 0x10090d150?, 0x1?, 0x0?, 0x1300031e0?)
        	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/proc.go:398 +0xc8 fp=0x130045f50 sp=0x130045f30 pc=0x100809108
        runtime.goparkunlock(...)
        	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/proc.go:404
        runtime.(*scavengerState).park(0x100a1c5a0)
        	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/mgcscavenge.go:425 +0x5c fp=0x130045f80 sp=0x130045f50 pc=0x1007f201c
        runtime.bgscavenge(0x0?)
        	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/mgcscavenge.go:653 +0x44 fp=0x130045fb0 sp=0x130045f80 pc=0x1007f2574
        runtime.gcenable.func2()
        	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/mgc.go:179 +0x28 fp=0x130045fd0 sp=0x130045fb0 pc=0x1007e9138
        runtime.goexit()
        	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/asm_arm64.s:1197 +0x4 fp=0x130045fd0 sp=0x130045fd0 pc=0x10083b544
        created by runtime.gcenable in goroutine 1
        	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/mgc.go:179 +0xac
        
        goroutine 5 [finalizer wait]:
        runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/proc.go:398 +0xc8 fp=0x13003ed80 sp=0x13003ed60 pc=0x100809108
        runtime.runfinq()
        	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/mfinal.go:193 +0x10c fp=0x13003efd0 sp=0x13003ed80 pc=0x1007e82ac
        runtime.goexit()
        	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/asm_arm64.s:1197 +0x4 fp=0x13003efd0 sp=0x13003efd0 pc=0x10083b544
        created by runtime.createfing in goroutine 1
        	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/mfinal.go:163 +0x80
        
        r0      0x104
        r1      0x0
        r2      0x0
        r3      0x0
        r4      0x0
        r5      0xa0
        r6      0x3b
        r7      0x3b9ac7b9
        r8      0x200
        r9      0x101
        r10     0x1300487d8
        r11     0x2
        r12     0x0
        r13     0x0
        r14     0x0
        r15     0x2
        r16     0x131
        r17     0x0
        r18     0x0
        r19     0x1300487c0
        r20     0x130048800
        r21     0x1
        r22     0x3b9ac7b9
        r23     0x3b
        r24     0x0
        r25     0x101
        r26     0x200
        r27     0x100a50000
        r28     0x1300029c0
        r29     0x16f7c2d00
        lr      0x1d64fd334
        sp      0x16f7c2c70
        pc      0x1b9e36580
        fault   0x1b9e36580
        
FAIL
FAIL	runtime	166.831s
```

(attn @golang/ios; CC @golang/runtime)

**Comment by bcmills** [comment]
See also #58794, #57595.
