### ISSUE TITLE
runtime: TestSegv/SegvInCgo timeout on ios-arm64-corellium

### ISSUE THREAD

**Issue by bcmills** [golang/go#59947]
From https://storage.googleapis.com/go-build-log/721ce2a9/ios-arm64-corellium_2cc89f52.log (a SlowBot on [CL 491835](https://go.dev/cl/491835)):
```
--- FAIL: TestSegv (0.00s)
    --- FAIL: TestSegv/SegvInCgo (146.88s)
        exec.go:200: test timed out while running command: /tmp/workdir-host-ios-arm64-corellium-ios/tmp/go-build2227660142/testprogcgo.exe SegvInCgo
        crash_cgo_test.go:647: /tmp/workdir-host-ios-arm64-corellium-ios/tmp/go-build2227660142/testprogcgo.exe SegvInCgo: exit status 2
        crash_cgo_test.go:648: SIGQUIT: quit
            PC=0x1b3002580 m=2 sigcode=0
            
            goroutine 0 [idle]:
            runtime.pthread_cond_timedwait_relative_np(0x130048800, 0x1300487c0, 0x16f556dd8)
            	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/sys_darwin.go:512 +0x20 fp=0x16f556da0 sp=0x16f556d70 pc=0x100a91f50
            runtime.semasleep(0xdf8475800)
            	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/os_darwin.go:60 +0xf4 fp=0x16f556e00 sp=0x16f556da0 pc=0x100a6f8d4
            runtime.notetsleep_internal(0x100c891c0, 0xdf8475800, 0x16f556e78?, 0x100a80794?)
            	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/lock_sema.go:232 +0x128 fp=0x16f556e40 sp=0x16f556e00 pc=0x100a47958
            runtime.notetsleep(0x13a0a117e45?, 0x130048480?)
            	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/lock_sema.go:283 +0x4c fp=0x16f556e80 sp=0x16f556e40 pc=0x100a47b1c
            runtime.sysmon()
            	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/proc.go:5444 +0x20c fp=0x16f556ee0 sp=0x16f556e80 pc=0x100a8080c
            runtime.mstart1()
            	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/proc.go:1508 +0x88 fp=0x16f556f10 sp=0x16f556ee0 pc=0x100a778c8
            runtime.mstart0()
            	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/proc.go:1465 +0x64 fp=0x16f556f40 sp=0x16f556f10 pc=0x100a77824
            runtime.mstart()
            	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/asm_arm64.s:128 +0x10 fp=0x16f556f50 sp=0x16f556f40 pc=0x100aa4db0
            
            goroutine 1 [syscall]:
            runtime.cgocall(0x100b475b8, 0x130042e68)
            	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/cgocall.go:157 +0x44 fp=0x130042e30 sp=0x130042df0 pc=0x100a40734
            main._Cfunc_pause()
            	_cgo_gotypes.go:446 +0x34 fp=0x130042e60 sp=0x130042e30 pc=0x100b3cc94
            main.SegvInCgo()
            	/private/var/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/testdata/testprogcgo/segv.go:54 +0x8c fp=0x130042e90 sp=0x130042e60 pc=0x100b42f6c
            main.main()
            	/private/var/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/testdata/testprogcgo/main.go:34 +0x11c fp=0x130042f30 sp=0x130042e90 pc=0x100b3c40c
            runtime.main()
            	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/proc.go:267 +0x2bc fp=0x130042fd0 sp=0x130042f30 pc=0x100a74cac
            runtime.goexit()
            	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/asm_arm64.s:1197 +0x4 fp=0x130042fd0 sp=0x130042fd0 pc=0x100aa7544

…

            goroutine 19 [syscall]:
            runtime.cgocall(0x100b47590, 0x13003ffb8)
            	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/cgocall.go:157 +0x44 fp=0x13003ff80 sp=0x13003ff40 pc=0x100a40734
            main._Cfunc_nop()
            	_cgo_gotypes.go:434 +0x30 fp=0x13003ffb0 sp=0x13003ff80 pc=0x100b3cc40
            main.SegvInCgo.func1()
            	/private/var/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/testdata/testprogcgo/segv.go:45 +0x24 fp=0x13003ffd0 sp=0x13003ffb0 pc=0x100b42fb4
            runtime.goexit()
            	/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/asm_arm64.s:1197 +0x4 fp=0x13003ffd0 sp=0x13003ffd0 pc=0x100aa7544
            created by main.SegvInCgo in goroutine 1
            	/private/var/tmp/workdir-host-ios-arm64-corellium-ios/go/src/runtime/testdata/testprogcgo/segv.go:42 +0x6c
```

(attn @golang/ios; CC @golang/runtime)

**Comment by bcmills** [comment]
This is likely related to at least one of:
- #39457
- #49182
- #50979
