### ISSUE TITLE
x/tools/go/ssa: panic in (*FieldAddr).String

### ISSUE THREAD

**Issue by timothy-king** [golang/go#59983]
Writing the function `g.c` from `ssa/builder_generic_test.go` (included below) panics with the stack trace:
```
panic: interface conversion: types.Type is *types.Pointer, not *types.Struct [recovered]
	panic: interface conversion: types.Type is *types.Pointer, not *types.Struct

goroutine 36 [running]:
testing.tRunner.func1.2({0x130bc20, 0xc000326ab0})
	/Users/taking/sdk/gotip/src/testing/testing.go:1545 +0x238
testing.tRunner.func1()
	/Users/taking/sdk/gotip/src/testing/testing.go:1548 +0x39f
panic({0x130bc20?, 0xc000326ab0?})
	/Users/taking/sdk/gotip/src/runtime/panic.go:913 +0x21f
golang.org/x/tools/go/ssa.(*FieldAddr).String(0xc000317860)
	/Users/taking/gorepos/tools/go/ssa/print.go:262 +0x149
golang.org/x/tools/go/ssa.WriteFunction(0xc000103a60?, 0xc0002e1800)
	/Users/taking/gorepos/tools/go/ssa/func.go:645 +0xc04
golang.org/x/tools/go/ssa.(*Function).WriteTo(0xc000103e10?, {0x13d8ca0, 0xc0000a4010})
	/Users/taking/gorepos/tools/go/ssa/func.go:570 +0x3c
golang.org/x/tools/go/ssa_test.TestGenericBodies.func1(0xc000205d40)
	/Users/taking/gorepos/tools/go/ssa/builder_generic_test.go:495 +0x62a
testing.tRunner(0xc000205d40, 0xc00031b7d0)
```

The package `g` is:
```
package g
type S struct{ f int }
func c[P *S]() []P { return []P{{f: 1}} }
```

**Comment by timothy-king** [comment]
Fixed in https://go.dev/cl/494978.
