### ISSUE TITLE
`golang.org/x/tools/go/callgraph/rta` `addRuntimeType()` hit unhandled type panic

### ISSUE THREAD

**Issue by magodo** [golang/go#60137]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes after running `go get golang.org/x/tools@master`

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/magodo/.cache/go-build"
GOENV="/home/magodo/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/magodo/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/magodo/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/magodo/github/azure-rest-api-cov-terraform/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3253597505=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

1. Download the target module to be analyzed, in my case, it is https://github.com/hashicorp/terraform-provider-azurerm, say it is at *pathA*
2. Build following code, which basically build callgraph using rta for the whole program of above project:

    ```go
	package main

	import (
		"fmt"
		"log"
		"os"

		"golang.org/x/tools/go/callgraph/rta"
		"golang.org/x/tools/go/packages"
		"golang.org/x/tools/go/ssa"
		"golang.org/x/tools/go/ssa/ssautil"
	)

	const (
		pkgPathAzureRMProvider = "github.com/hashicorp/terraform-provider-azurerm"
	)

	func main() {
		dir := os.Args[1]
		cfg := packages.Config{Dir: dir, Mode: packages.LoadAllSyntax}

		pkgs, err := packages.Load(&cfg, "./...")
		if err != nil {
			log.Fatal(err)
		}

		if packages.PrintErrors(pkgs) > 0 {
			log.Fatal("packages contain errors")
		}

		prog, _ := ssautil.AllPackages(pkgs, 0)
		prog.Build()

		// Build the call graph from the main function
		main, err := mainPackage(prog.AllPackages())
		if err != nil {
			log.Fatal(err)
		}
		rta.Analyze([]*ssa.Function{main.Func("main")}, true)
	}

	func mainPackage(pkgs []*ssa.Package) (*ssa.Package, error) {
		for _, p := range pkgs {
			if p != nil && p.Pkg.Name() == "main" && p.Pkg.Path() == pkgPathAzureRMProvider && p.Func("main") != nil {
				return p, nil
			}
		}
		return nil, fmt.Errorf("no main package")
	}
    ```
3. Run it: `go run main.go $pathA`

### What did you expect to see?

Finishes with no error

### What did you see instead?

```
panic: Point

goroutine 1 [running]:
golang.org/x/tools/go/callgraph/rta.(*rta).addRuntimeType(0xc1d480fcc0, {0x6fcc30?, 0xc00625e210?}, 0x0)
        /home/magodo/go/pkg/mod/golang.org/x/tools@v0.9.1/go/callgraph/rta/rta.go:457 +0x885
golang.org/x/tools/go/callgraph/rta.(*rta).addRuntimeType(0xc1d480fcc0, {0x6fcbe0?, 0xc016d816f8?}, 0x1)
        /home/magodo/go/pkg/mod/golang.org/x/tools@v0.9.1/go/callgraph/rta/rta.go:453 +0x825
golang.org/x/tools/go/callgraph/rta.(*rta).addRuntimeType(0xc1d480fcc0, {0x6fcb68?, 0xc00f47fc40?}, 0x0)
        /home/magodo/go/pkg/mod/golang.org/x/tools@v0.9.1/go/callgraph/rta/rta.go:430 +0x6eb
golang.org/x/tools/go/callgraph/rta.(*rta).addRuntimeType(0xc1d480fcc0, {0x6fcbb8?, 0xc005fc6150?}, 0x1)
        /home/magodo/go/pkg/mod/golang.org/x/tools@v0.9.1/go/callgraph/rta/rta.go:448 +0x8a5
golang.org/x/tools/go/callgraph/rta.(*rta).addRuntimeType(0xc1d480fcc0, {0x6fcb18?, 0xc016c4dea0?}, 0x0)
        /home/magodo/go/pkg/mod/golang.org/x/tools@v0.9.1/go/callgraph/rta/rta.go:441 +0x778
golang.org/x/tools/go/callgraph/rta.(*rta).addRuntimeType(0xc1d480fcc0, {0x6fcb40?, 0xc004f5d1a0?}, 0x0)
        /home/magodo/go/pkg/mod/golang.org/x/tools@v0.9.1/go/callgraph/rta/rta.go:413 +0x5e7
golang.org/x/tools/go/callgraph/rta.(*rta).visitFunc(0xc03001fcc0?, 0xc0004dea80)
        /home/magodo/go/pkg/mod/golang.org/x/tools@v0.9.1/go/callgraph/rta/rta.go:248 +0x190
golang.org/x/tools/go/callgraph/rta.Analyze({0xc0025dbe50, 0x1, 0x6a071e?}, 0x1)
        /home/magodo/go/pkg/mod/golang.org/x/tools@v0.9.1/go/callgraph/rta/rta.go:300 +0x451
main.main()
        /home/magodo/tmp/callgraph/main.go:39 +0x36f
```

Apparently, there are some new types not handled appropriately by rta: https://cs.opensource.google/go/x/tools/+/master:go/callgraph/rta/rta.go;l=456, and the unhandled type is `TypeParameter`.

**Comment by magodo** [comment]
The issue is due to I didn't used the mode `ssa.InstantiateGenerics` when building ssa packages.
