### ISSUE TITLE
net: frequent timeouts in `TestSplice/tcp-to-tcp` on `linux-amd64-wsl`

### ISSUE THREAD

**Issue by bcmills** [golang/go#60258]
```
#!watchflakes
post <- pkg == "net" && builder ~ `.*-wsl` && log ~ `test timed out` && log ~ `TestSplice/tcp-to-tcp \(\d+m\d+s\)`
```

As far as I can tell this always co-occurs with #60257. That may be important.
It is often (but not always) the `/big` subtest that times out.

https://build.golang.org/log/a1e647502ffe3ced34891a80b7bc714aebdf2ab3:

<details>

```
--- FAIL: TestTCPListener (0.00s)
    listen_test.go:72: skipping tcp  test
    listen_test.go:72: skipping tcp 0.0.0.0 test
    listen_test.go:72: skipping tcp ::ffff:0.0.0.0 test
    listen_test.go:72: skipping tcp :: test
    listen_test.go:90: tcp 127.0.0.1 should fail
panic: test timed out after 3m0s
running tests:
	TestSplice (2m58s)
	TestSplice/tcp-to-tcp (2m58s)
	TestSplice/tcp-to-tcp/big (2m58s)
…
goroutine 960 [syscall, 2 minutes]:
syscall.Syscall6(0x7fbac6abe808?, 0xc0000dbaf8?, 0x4673c5?, 0xc0000dbb08?, 0x405486?, 0xc0000dbb20?, 0x494747?)
	/tmp/workdir-host-linux-amd64-wsl/go/src/syscall/syscall_linux.go:91 +0x30 fp=0xc0000dbad0 sp=0xc0000dba48 pc=0x47fef0
syscall.Splice(0xc0000ed480?, 0xc0002993e0?, 0xc0000dbb00?, 0x4f45f2?, 0x7fffe714db3f?, 0x46?)
	/tmp/workdir-host-linux-amd64-wsl/go/src/syscall/zsyscall_linux_amd64.go:1356 +0x45 fp=0xc0000dbb30 sp=0xc0000dbad0 pc=0x47ed25
internal/poll.splice(...)
	/tmp/workdir-host-linux-amd64-wsl/go/src/internal/poll/splice_linux.go:154
internal/poll.splicePump(0xc0000ed480, 0xc0000ed300?, 0x7000)
	/tmp/workdir-host-linux-amd64-wsl/go/src/internal/poll/splice_linux.go:129 +0x1a5 fp=0xc0000dbbd8 sp=0xc0000dbb30 pc=0x49c2a5
internal/poll.Splice(0xc0000dbcd8?, 0x40e9c5?, 0x7fffffffffffffff)
	/tmp/workdir-host-linux-amd64-wsl/go/src/internal/poll/splice_linux.go:59 +0x1f7 fp=0xc0000dbc70 sp=0xc0000dbbd8 pc=0x49bbd7
net.splice(0x0?, {0x6ee4c0?, 0xc0003d40d8?})
	/tmp/workdir-host-linux-amd64-wsl/go/src/net/splice_linux.go:39 +0xdf fp=0xc0000dbcd0 sp=0xc0000dbc70 pc=0x5727df
net.(*TCPConn).readFrom(0xc0003d40f8, {0x6ee4c0, 0xc0003d40d8})
	/tmp/workdir-host-linux-amd64-wsl/go/src/net/tcpsock_posix.go:48 +0x28 fp=0xc0000dbd00 sp=0xc0000dbcd0 pc=0x574a48
net.(*TCPConn).ReadFrom(0xc0003d40f8, {0x6ee4c0?, 0xc0003d40d8?})
	/tmp/workdir-host-linux-amd64-wsl/go/src/net/tcpsock.go:130 +0x30 fp=0xc0000dbd40 sp=0xc0000dbd00 pc=0x572e10
io.copyBuffer({0x6ee480, 0xc0003d40f8}, {0x6ee4c0, 0xc0003d40d8}, {0x0, 0x0, 0x0})
	/tmp/workdir-host-linux-amd64-wsl/go/src/io/io.go:413 +0x147 fp=0xc0000dbdc0 sp=0xc0000dbd40 pc=0x491ba7
io.Copy(...)
	/tmp/workdir-host-linux-amd64-wsl/go/src/io/io.go:386
net.spliceTestCase.test({{0x692331, 0x3}, {0x692331, 0x3}, 0x500000, 0x40000000, 0x0}, 0xc00041cb60)
	/tmp/workdir-host-linux-amd64-wsl/go/src/net/splice_test.go:89 +0x3e5 fp=0xc0000dbf20 sp=0xc0000dbdc0 pc=0x5ea125
net.spliceTestCase.test-fm(0xc000322760?)
	<autogenerated>:1 +0x3e fp=0xc0000dbf70 sp=0xc0000dbf20 pc=0x62289e
testing.tRunner(0xc00041cb60, 0xc0000cec00)
	/tmp/workdir-host-linux-amd64-wsl/go/src/testing/testing.go:1595 +0xff fp=0xc0000dbfc0 sp=0xc0000dbf70 pc=0x4e5f1f
testing.(*T).Run.func1()
	/tmp/workdir-host-linux-amd64-wsl/go/src/testing/testing.go:1648 +0x25 fp=0xc0000dbfe0 sp=0xc0000dbfc0 pc=0x4e6ea5
runtime.goexit()
	/tmp/workdir-host-linux-amd64-wsl/go/src/runtime/asm_amd64.s:1622 +0x1 fp=0xc0000dbfe8 sp=0xc0000dbfe0 pc=0x46c6e1
created by testing.(*T).Run in goroutine 984
	/tmp/workdir-host-linux-amd64-wsl/go/src/testing/testing.go:1648 +0x3ad
```

</details>

(attn @golang/wsl; CC @qmuntal @ianlancetaylor @neild)

**Comment by bcmills** [comment]
These seem to have stopped in May. Maybe fixed?
