### ISSUE TITLE
html.EscapeString  panic

### ISSUE THREAD

**Issue by qiannianshaonian** [golang/go#60280]
go version is v1.19.5

panic: runtime error: index out of range [102] with length 102
goroutine 61748698 [running]:
strings.(*byteStringReplacer).Replace(0xc000577980, {0xc00c486000, 0x5e})
/usr/local/go/src/strings/replace.go:534 +0x197
strings.(*Replacer).Replace(0x11bd680?, {0xc00c486000?, 0x13cec54?})
/usr/local/go/src/strings/replace.go:97 +0x6e
html.EscapeString(...)
/usr/local/go/src/html/escape.go:179

**Comment by mitar** [comment]
And what is the input to the call? Can you provide a reproduction?

**Comment by mvdan** [comment]
Fill the bug template please.

**Comment by qiannianshaonian** [comment]
> And what is the input to the call? Can you provide a reproduction?

Please wait
the captured exception data has been added.
If any exceptions occur later,
relevant information will be provided
