### ISSUE TITLE
cmd/compile: closure function change name when inlining

### ISSUE THREAD

**Issue by rsc** [golang/go#60324]
```
% cat x.go
package main

func f(x int) func() {
	return func() {
		panic(x)
	}
}

func main() {
	f(1)()
}
% go run -gcflags=-l x.go
panic: 1

goroutine 1 [running]:
main.f.func1()
	/private/tmp/x.go:5 +0x26
main.main()
	/private/tmp/x.go:10 +0x22
exit status 2
% go run x.go
panic: 1

goroutine 1 [running]:
main.main.func1(...)
	/private/tmp/x.go:5
main.main()
	/private/tmp/x.go:10 +0x28
exit status 2
% 
```

Without inlining, the stack shows `main.f.func1` panicking, which is approximately correct: it's the 1st closure inside main.f.

With inlining, the stack instead shows `main.main.func1`, because now it's the 1st closure inside main.main due to inlining of f. However, that's a much less useful name, since the closure is still lexically inside main.f. If there is some way to preserve the old name even when inlining, that would be a good idea.

This is the source of a Kubernetes test failure using Go 1.21, because a more complicated function was not being inlined in Go 1.20 but is being inlined in Go 1.21 after CL 492017. The test expected to see "newHandler" on the stack when a closure lexically inside newHandler panicked.

If there's something we can do here, we probably should, both to keep the closure names helpful and to keep tests like the Kubernetes one passing.

**Comment by thediveo** [comment]
not only k8s, but for instance leaky go routine tests may fail b/c whitelisting doesn't work correctly anymore.

**Comment by thanm** [comment]
Hi Austin, since you are the original author of CL 479095, assigning this bug to you. If you would prefer that I work on this particular cleanup, please assign back to me. Thanks, Than.

**Comment by aarzilli** [comment]
This was noticed before: #55980

**Comment by mdempsky** [comment]
> If there is some way to preserve the old name even when inlining, that would be a good idea.

Is it okay if we just arrange that the `runtime.Func` for the inlined closure reports the original closure's link symbol name, instead of the duplicate's own name?

**Comment by rsc** [comment]
For what it's worth, we have the name of the lexically enclosing function at the point of the closure creation, because if the program crashed at that PC we would show that frame in the stack trace marked [inlined].

**Comment by mdempsky** [comment]
Yes, it's easy to track the original closure symbol name. That's not a problem.

What I'm trying to understand is what you want done with that.

We currently duplicate the closure and underlying function text, because they can be optimized differently due to different escape analysis and variable capture. So the duplicated closure needs its own linker symbol.

**Comment by rsc** [comment]
Does it? I thought the linker addressed all the symbols by table index now, so if we made it a symbol internal to the package being compiled, it would not collide with any others with the same name.

**Comment by mdempsky** [comment]
> What I'm trying to understand is what you want done with that.

**Comment by rsc** [comment]
I am interpreting the previous comment as my not having answered your questions, so I will elaborate a bit here.

The function names reported in profiles, stack traces, symbol tables, disassembly, and so on should not depend on how aggressively we inline. That is, the names that we get with no inlining at all are the "official" names, and inlining should preserve them.

I understand that, in terms of the example at the top, if we do:

```
func main() {
    f(1)()
    f(2)()
    f(3)()
}
```

that there will be three copies of the actual text symbol generated when f is inlined, and that the texts may actually differ across the 3 calls. But I think the new linker's ability to address symbols by table index instead of name should mean that it's completely fine to have those three text symbols all use the same name: the original name they'd have used without inlining.

**Comment by mdempsky** [comment]
@cherrymui How do we create multiple obj.LSyms that are kept separately but all end up with the same linkname in the symbol tables?

**Comment by mdempsky** [comment]
> The names carry useful information that has been lost since unified IR started inlining these kinds of functions.

Please retract that accusation. The stack trace for your test program is the same in Go 1.19 as in Go 1.20: https://go.dev/play/p/yjP9hrxZ_K0?v=goprev

**Comment by rsc** [comment]
It was not an accusation, but I apologize nonetheless. My memory was that one of unified IR's important inlining advances was to enable inlining of closure-containing functions. I misremembered - we [started inlining those in Go 1.17](https://go.dev/doc/go1.17#compiler), so obviously that must have been with the original IR. In any event, as unified IR has made it possible to do more aggressive inlining, we lose more and more of this information. _This is not a criticism of unified IR._ My point is only to explain the context of how we got here. All the changes individually make sense, but this is a rough edge where they aren't quite working well enough together.

**Comment by mdempsky** [comment]
> I apologize nonetheless.

Thank you.

> but this is a rough edge where they aren't quite working well enough together.

Ack. That's what I'm trying to understand: how *should* this work?

As I've [said already](https://github.com/golang/go/issues/60324#issuecomment-1557590407), we need multiple linker symbols (i.e., obj.LSyms), because in general the inlined closure can get optimized differently than the original closure.

You suggest the multiple obj.LSyms should just have identical names in the symbol tables, etc (i.e., use the same linknames). That's not something we do anywhere else in the compiler to my knowledge, so I don't know how to invoke cmd/internal/obj to make that happen. Hence why I asked @cherrymui how to do that.

However, I remember she's on vacation, so if any other linker experts can advise on this, that would be great. @golang/compiler

**Comment by mdempsky** [comment]
> I think it would be good enough for Go 1.21 if we embed the inlining stack in the name (eliding package names)

Thanks, that seems doable for 1.21.

**Comment by prattmic** [comment]
I agree that we should improve the names of inlined closures and the suggestion in https://github.com/golang/go/issues/60324#issuecomment-1557684028 seems like a reasonable short-term compromise. 

If that is easy to do at the end of the cycle, great, but I'd push back a bit on this being a release-blocking issue that needs an immediate fix right before the freeze. We know that this is an existing issue that gets more annoying as we are more aggressive with inlining closures, but are we actually that much aggressive than before?

CL 479095 states that it increases inlinability by +0.6%. It doesn't say how much it increases inlinability of closures specifically, which is probably the more important metric. But at first glance, it looks like we got unlucky with one specific test rather than us getting sharply more aggressive and causing widespread issues.

**Comment by mdempsky** [comment]
Russ's suggested naming change ("main.main.func1" -> "main.main.f.func1") has been implemented and submitted for Go 1.21.

I'm happy to implement further changes for Go 1.22, pending advice from the linker devs on how to best approach that.

**Comment by thanm** [comment]
Thanks Matthew.

**Comment by aclements** [comment]
Do we *want* the symbols to have the non-unique names? There's a tension: we go to some effort to make runtime tracebacks reflect the language, not the implementation, which suggests those should show the "original" name of the closure, even if that's non-unique; but at the same time developers sometimes need to map that to an ELF/etc symbol, in which case you really want them to be unique (the PC offset traceback prints doesn't do you much good without a unique symbol name!).

We could change how we show closures and/or inlining in runtime tracebacks. Is there just a nicer way to present this information? I don't have any answers, but maybe thinking about that bigger picture will inspire someone. 🙂

**Comment by mdempsky** [comment]
One possible solution would be to ensure the closure is never optimized differently when inlined, so we can just always reuse the same underlying function all the time.

With how things are currently implemented, it's certainly *possible* that the closure gets optimized differently. But I don't have an example off hand to demonstrate that we do.

**Comment by rsc** [comment]
Thanks for the CL @mdempsky. 

I've confirmed that the fix changes the stack frame in question in the failing Kubernetes test from
`k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.TestTimeout.func5` 
to being named
`k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.TestTimeout.newHandler.func5`
which makes the test ([which wanted to see 'newHandler'](https://github.com/kubernetes/kubernetes/blob/v1.27.1/staging/src/k8s.io/apiserver/pkg/server/filters/timeout_test.go#L177)) pass again. 

I've changed this to the Go 1.22 milestone, and I agree with @austin that there is a question about whether we should stop at these not-unique names.

It was a release blocker for Go 1.21 because there was no way to test for the presence of a function on a call stack (in, for example, a test of panic behavior) that worked reliably across changes to the amount of inlining. That was breaking real tests with no obvious answer for how to rewrite them to be more robust. Now we have the guarantee that the lexically enclosing function name is preserved. Yes, it was not a new bug in Go 1.21 (as we established, it first started in Go 1.17), but Go 1.21 changes made the problem worse. I appreciate the fix.

**Comment by mdempsky** [comment]
> Do you want multiple symbols with the same name but could have potentially different content?

Potentially different content, yes.

> If you want different content, I think one possibility is to mark the symbol Static.

Thanks, I'll experiment with that.

(Caveat to both of these that I think in practice the content *is* actually always the same, or at least very nearly always the same, and probably the better solution here is to just ensure that they are in fact always the same and then reuse a single symbol.)

**Comment by mdempsky** [comment]
I'd like to suggest a revision to how we rename inlined closures. In particular, here are my thoughts:

1. Users care most about where the closure came from in the source, not as it was optimized. So we should prioritize the original (i.e., pre-inlined) closure name.
2. I *don't* think users particularly care about how a closure ended up cloned into a particular function (but I could be wrong).

In [implemented suggestion](https://github.com/golang/go/issues/60324#issuecomment-1557684028) the original closure is name `pkg.h.func1`, but then it gets renamed to (e.g.) `pkg.F.f.g.h.func4`, which isn't intuitive for users to decode. It also makes it very difficult for tools to correlate these symbols.

I suggest instead that we name the inlined closures `pkg.h.func1@F.1`, `pkg.h.func1@F.2`, `pkg.h.func1@F.3`, and `pkg.h.func1@F.4`.

If we want to preserve the transitive inlining breadcrumbs, I suggest we name them like `pkg.h.func1@F.f.g.1`.

If the closures were inlined across package boundaries, then we'll name them `pkg.h.func1@pkg2.G.1` instead, to ensure unique symbols.

**Comment by aarzilli** [comment]
IIRC `@` has a special meaning in symbol names.

**Comment by dr2chase** [comment]
If we could find a less special special character, I think this would be a nice improvement to the status quo.

**Comment by mdempsky** [comment]
@aarzilli Thanks, @cherrymui reminded me of that privately. I'm happy for an alternative character if anyone has suggestions. ("foo@bar" just seemed the instinctual suggestion for suggesting that foo was inlined at bar.)

**Comment by aarzilli** [comment]
My personal opinion is that (aside from the `@` issue) the inlining breadcrumbs don't carry enough value to justify the noise they introduce. I think this suggestion is the better one:

> I suggest instead that we name the inlined closures `pkg.h.func1@F.1`, `pkg.h.func1@F.2`, `pkg.h.func1@F.3`, and `pkg.h.func1@F.4`.

**Comment by thediveo** [comment]
not exactly thrilled when closure func names change (again), because in the Gomega go routine leak checker (https://github.com/onsi/gomega/blob/55a33f3ff7b97c9f999d641bb6f92621d1c2edcf/gleak/have_leaked_matcher.go#L44) we need to maintain an ignore list of known background go routines from stdlib and testing. I think that we luckily have avoided hardcoding closure funcs using `...` in the ignores. However, changes discussed here always keep me wary...

**Comment by thediveo** [comment]
- line noise ... then it most probably is a valid TECO command.
- would exposing the names of local variables be a problem? what in case the func is returned immediately, so there's no name to associate with?

**Comment by aarzilli** [comment]
One thing to keep in mind is that, I think, the `[X]` breaks any parser for symbol names that has been updated to work with generics, including [debug/gosym](https://cs.opensource.google/go/go/+/refs/tags/go1.21.0:src/debug/gosym/symtab.go;l=42). 

>This will add churn to the overall user experience, as every change here does. Do we have evidence that the changes made for Go 1.21 aren't good enough?

One thing is that the `.funcN` convention has always been ambiguous (is `pkg.A.func1` a closure in function `pkg.A` or is it a method of type `pkg.A`?).

It would be nice if a delimiter other than `.` was used here but this is also at odds with backwards compatibility.

Another thing is that the inlining breadcrumbs aren't all that user friendly either, I think. If I didn't know about this thread `pkg.A.B.func3` would make me look at `pkg.A` when I should really be looking at `B` (possibly in a different package?).

**Comment by thediveo** [comment]
unless you name all your packages pkg, A, B, etc., it usually becomes quite obvious where the package in the name is, more so as it is an import path with github.com, or some other TLD.

**Comment by mdempsky** [comment]
To recap prior history here:

On [May 20th](https://github.com/golang/go/issues/60324#issue-1718285047), @rsc raised the issue that `a.F.func1` could get renamed to `b.G.func2` in stack traces due to inlining, which is understandably confusing to users because the names `a.F.func1` and `b.G.func2` share nothing of significance in common.

Aside: He also tagged this as a release blocker (4 days before the Go 1.21 release freeze), and later reiterated how important the original function literal names were and misattributed the regression to my individual contributions that had recently shipped in Go 1.20, even though though the renaming has been present since inlining functions with closures was implemented for Go 1.17 by a different contributor:

https://github.com/golang/go/blob/1760d736f61265b3c78a6a48f2e1904341806643/test/inline.go#L115

On [May 22nd at 10:06am](https://github.com/golang/go/issues/60324#issuecomment-1557590407), I explained the present need to assign new linker symbol names for the inlined closures, and asked how @rsc wanted to resolve this issue.

After several messages speculating on linker capabilities and without a linker expert to advise, on [May 22nd at 11:16am](https://github.com/golang/go/issues/60324#issuecomment-1557684028), @rsc proposed his "breadcrumb" scheme: instead of renaming `a.F.func1` to `b.G.func2`, we should instead rename it to `b.G.F.func2`. He described this as "good enough for Go 1.21," conveying that it was an acceptable solution for looming release freeze, and which we could revisit in the future.

Accordingly, I'm now suggesting for Go 1.22 that instead of renaming `a.F.func1` to `b.G.F.func2`, we rename it to `a.F.func1` + some unique suffix (if/when necessary). I've put forth several concrete suggestions of suffix (notably starting with `@`), but I'm not attached to any.

> The changes suggested above do not seem to be taking into account the user experience for non-expert Go programmers.

Between Go 1.17 (2021-08-16) and May 20th (2023), how much user experience feedback did we receive that function literals changing names were a problem? I don't recall seeing any.

By contrast, last week (10 days after Go 1.21 was released) a user reported the breadcrumb naming as a bug: https://github.com/golang/go/issues/62132. That was my motivation for revisiting this issue.

> It seems like a change here is only worthwhile if it is obviously dramatically better or it addresses something in the status quo that is demonstrably not good enough. I don't see either one of those here.

You said the name `a.F.func1` carries "useful information." By renaming it to `a.F.func1`+suffix, we preserve all of that information. It's also trivial to extend any pattern matching for `a.F.func1` to also match `a.F.func1`+suffix.

The breadcrumb scheme of renaming to `b.G.F.func2` as used in Go 1.21 preserves only a small portion of that information, and is impossible to relate back to `a.F.func1` without additional out-of-band information, making pattern matching much more difficult.

@thediveo Do you think renaming `a.F.func1` to `b.G.F.func2` is "good enough" for Gomega? Do you think changing it to `a.F.func1`+suffix would be "obviously dramatically better"?

> The transitive inlining "breadcrumbs" within a package seem important to me to preserve as well.

Your initial request was that we shouldn't rename `a.F.func1` at all. Understandable: inlining is an implementation detail, and we strive to hide implementation details from users.

Barely an hour after I explained the present technical need for renaming, you instead proposed renaming to `b.G.F.func2` and now say that naming "seems important."

Are you "speculating" or do you have "evidence" that the inlining breadcrumbs are important? What non-expert user experience changed your mind in such a short period of time?

> The choice of delimiter matters too.

I agree. But I'll remind that you're the one who put forth using `.` as the delimiter originally. And who also casually dismissed Alan's suggestion back in https://github.com/golang/go/issues/8291#issuecomment-66096501 to utilize more delimiters. Meanwhile, we've had to deal with tedious symbol collision issues like #37762, because simply using `.` everywhere turns out to not always "just work fine."

Moreover, in the same comment you both defend that choice of delimiter as the status quo ("I don't see either one of those [reasons to change] here"), while also suggesting to change the delimiter to `@` without even acknowledging that was my suggestion.

I continue to feel discouraged by the inconsistent standards that different project contributors are held to.

For example, when I proposed adding `GOEXPERIMENT=typeparams` in #43931 to allow smoother compiler development and end-user testing of generics while we waited for #43651 to be accepted, it was initially [shot down](https://github.com/golang/go/issues/43931#issuecomment-768490280) with "I don't think we can land code on master before a proposal is accepted. That goes against the spirit of the proposal process and the rules we ask others to follow for proposed changes." After 7 users+contributors wrote 10 comments in support of the proposal, @rsc locked the discussion for a week as "too heated." #43931 was ultimately accepted, but not until *after* #43651 was accepted.

Yet in #57969, @rsc proposed adding `GOEXPERIMENT=loopvar` explicitly "before we get to a formal proposal" and accepted just 16 days later, still without a formal proposal. And then again in #61717, @rsc proposed adding `GOEXPERIMENT=range` and accepted it merely *7* days later, while #61405 is still being discussed.

Did "the rules we ask others to follow" change? Am I supposed to just pretend there's no double standard going on here?

**Comment by ianlancetaylor** [comment]
> Are we sure that C toolchains will break if we use @ here?

In an ELF object file, the `@` character is used to separate a symbol name from the symbol version.  So, yes, you're going to get odd behavior if you pass an object file with symbol names containing '@' characters to an ELF linker.

**Comment by thediveo** [comment]
>  Do you think renaming a.F.func1 to b.G.F.func2 is "good enough" for Gomega? Do you think changing it to a.F.func1+suffix would be "obviously dramatically better"?

ad 1. should work as we would add the new pattern next to the existing one, both coexisting without interference. 

ad 2. I lived halfway happily with the existing scheme but hadn't an urge for longer symbol names.

**Comment by rsc** [comment]
@ianlancetaylor 
> In an ELF object file, the @ character is used to separate a symbol name from the symbol version. So, yes, you're going to get odd behavior if you pass an object file with symbol names containing '@' characters to an ELF linker.

I understand that, but I also noted "The symbols would not be exported in any way, so I would hope a C linker would leave them alone." That is, I think that the vast majority of our symbols are or can be generated as STB_LOCAL, and in particular any closure functions can definitely be set STB_LOCAL. If we use the @ syntax in STB_LOCAL names, will that still affect ELF linkers?

**Comment by ianlancetaylor** [comment]
Technically you're right that an ELF linker shouldn't care about @ in a local symbol name.  But it seems like a bad idea to count on such symbols being handled cleanly by the various ELF linkers and by the various ELF tools in general.  I would only try that if it were fairly important to use @.  None of the @ support is standardized or seriously documented (Sun introduced symbol versioning, and they documented it well, but the @ support is a GNU extension that lets people skip writing actual version definition files).

If you really want the @ then an option would be to only use the @ in the debug info, and use a mangled name in the ELF symbol table.

**Comment by rsc** [comment]
Sounds good, thanks for the extra details.

**Comment by rsc** [comment]
> One thing is that the .funcN convention has always been ambiguous (is pkg.A.func1 a closure in function pkg.A or is it a method of type pkg.A?).

That's not ambiguity, because pkg.A can only be one of those two things.
We don't say that pkg.A itself is ambiguous because it might be a function or it might be a type. 
We assume it's okay to need to know what kind of thing A is.
And if we know what kind of thing A is, then we know what kind of thing A.func1 is.

> Another thing is that the inlining breadcrumbs aren't all that user friendly either, I think. If I didn't know about this thread pkg.A.B.func3 would make me look at pkg.A when I should really be looking at B (possibly in a different package?).

I agree with Matthew's observation that it would be more helpful to reverse the breadcrumbs. My point was that if we have F inlined into G inlined into H as well as F inlined into J inlined into K, it is much more helpful to name them with some representation that includes (F,G,H) and (F,J,K) than it is to name them F$1 and F$2.

**Comment by aarzilli** [comment]
> That's not ambiguity, because pkg.A can only be one of those two things.
> We don't say that pkg.A itself is ambiguous because it might be a function or it might be a type.
> We assume it's okay to need to know what kind of thing A is.
> And if we know what kind of thing A is, then we know what kind of thing A.func1 is.

Ok, but for example debug/gosym doesn't know that and gets them wrong.

**Comment by rsc** [comment]
@aarzilli Do you mean just debug/gosym.BaseName, or other code in debug/gosym too? What do you use BaseName for?

**Comment by aclements** [comment]
If we were to make the inlining breadcrumbs unambiguously parseable from the symbol name, then in a traceback, we could print only the "original" name by default, and include the full name if and only if we're showing full PCs in the traceback (I'm thinking as additional information at the end of the line, not replacing the original name). That seems to be the exact case where the actual symbol name may matter. Perhaps we suppress the PC offset if we're only printing the original name to avoid confusion. This is a more refined version of the point I made in https://github.com/golang/go/issues/60324#issuecomment-1559843162.

**Comment by aarzilli** [comment]
> @aarzilli Do you mean just debug/gosym.Sym.BaseName, or other code in debug/gosym too? What do you use BaseName for?

BaseName and ReceiverName. Delve doesn't use debug/gosym, exactly, but it has its own equivalent reimplementation. It uses it to find functions with a partial name match (for example to set a breakpoint). It has never needed to work correctly with closures, so far, but it would be nice to know that it could.

Looking around with sourcegraph I can't find many users of debug/gosym, but for example [GoRE](https://github.com/goretk/gore/blob/develop/file.go#L233) could be affected by this problem as well. Hard to say if there are other half-reimplementations floating around that are affected.

Personally, as a user of go, I agree that `$` is too noisy as a delimiter but `,` or `-` are also unambiguous and not too noisy. I don't see the value of the inlining breadcrumbs at all.

**Comment by aclements** [comment]
It occurs to me that this case of inlining is just one example of function multicompilation/multiversioning. In this case, we're compiling multiple versions of the function because they may be optimized differently in different inlining contexts. But this is a technique we've considered for other things, like multiversioning for escape analysis and for access to CPU features that are detected at runtime.

In fact, there's another case where we do this already: GC shape stenciling. We had to disambiguate the symbols in that case, too. But in that case we decided to [hide the disambiguator](https://cs.opensource.google/go/go/+/master:src/runtime/traceback.go;l=749;drc=caf9e15fb76631ca692f4779135aec5b82a68370) in tracebacks and only show the "user" name. I think that was the right choice (though we still show PCs, which might be a mistake 😅). In that case, the disambiguator was pretty meaningless to users, and I could see an argument that the inlining breadcrumbs are more meaningful, but I'm not sure I buy that these cases are so different.

**Comment by mitar** [comment]
> It occurs to me that this case of inlining is just one example of function multicompilation/multiversioning. 

Aren't generics the same? So maybe it would be neat to include in stack traces also the concrete type for which a generic function got compiled?

**Comment by aclements** [comment]
> Aren't generics the same?

Sorry, that's exactly what I meant by "GC shape stenciling" (I can see how that wouldn't be obvious!)

The thing is, the symbol name doesn't include the concrete type for which a generic function got instantiated. What it includes is [much more abstract](https://go.googlesource.com/proposal/+/refs/heads/master/design/generics-implementation-gcshape.md) and not particularly helpful to the user.

**Comment by bric3** [comment]
Hi just to weigh in on this comment by @mdempsky  https://github.com/golang/go/issues/60324#issuecomment-1686914585.

> It also makes it very difficult for tools to correlate these symbols

I agree to the whole comment because I'm writing such tool within the IDE, and it is sometimes not possible to correctly resolve the symbol there. Stack traces in particular have the file name, but this might be transformed (trimmed, or else, e.g. Bazel does that with the default ruleset).

Having a marker to identify inlines so it's possible to handle them (maybe skip them) could help.

**Comment by aclements** [comment]
That symbol name is remarkably unpleasant!

For reference, it comes from [this function](https://github.com/go-delve/delve/blob/530afae62e50383eacbe0a1e643ab42a48b30c01/_fixtures/rangeoverfunc.go#L81), which has four levels of range-over-func loops. Each of these is an [`OfSliceIndex` iterator](https://github.com/go-delve/delve/blob/530afae62e50383eacbe0a1e643ab42a48b30c01/_fixtures/rangeoverfunc.go#L285), which is itself quite simple, other than having two type parameters.

Even ignoring all of the type parameters in the symbol name (several of which *could* be different, but aren't in this particular case), our current naming scheme clearly scales super-linearly here, which is rather concerning:

```
main.TestMultiCont0.TestMultiCont0.OfSliceIndex[
   go.shape.int,go.shape.[]int
].func1.TestMultiCont0-range1.TestMultiCont0.TestMultiCont0.OfSliceIndex[
   go.shape.int,go.shape.[]int
].func1.TestMultiCont0-range1.OfSliceIndex[
   go.shape.int,go.shape.[]int
].func2.TestMultiCont0.TestMultiCont0.OfSliceIndex[
   go.shape.int,go.shape.[]int
].func1.TestMultiCont0-range1-range5.TestMultiCont0.TestMultiCont0.OfSliceIndex[
   go.shape.int,go.shape.[]int
].func1.TestMultiCont0-range1.TestMultiCont0.TestMultiCont0.OfSliceIndex[
   go.shape.int,go.shape.[]int
].func1.TestMultiCont0-range1.OfSliceIndex[
   go.shape.int,go.shape.[]int
].func2.TestMultiCont0.TestMultiCont0.OfSliceIndex[
   go.shape.int,go.shape.[]int
].func1.TestMultiCont0-range1-range5.OfSliceIndex[
   go.shape.int,go.shape.[]int
].func3.TestMultiCont0.TestMultiCont0.OfSliceIndex[
   go.shape.int,go.shape.[]int
].func1.TestMultiCont0-range1.TestMultiCont0.TestMultiCont0.OfSliceIndex[
   go.shape.int,go.shape.[]int
].func1.TestMultiCont0-range1.OfSliceIndex[
   go.shape.int,go.shape.[]int
].func2.TestMultiCont0.TestMultiCont0.OfSliceIndex[
   go.shape.int,go.shape.[]int
].func1.TestMultiCont0-range1-range5-range8.OfSliceIndex[
   go.shape.int,go.shape.[]int
].func4
```

**Comment by thediveo** [comment]
I wonder if James Joyce would have been able to pack a novel into these symbols using carefully crafted closures......?

**Comment by cherrymui** [comment]
Thanks @aarzilli for the CL! It originally appeared to be a good idea to me. But as I read and think more, I'm less sure about it, given the complexity of the CL. I think the fundamental issue is that we need a name that is user friendly, and we need a name for symbol resolution. At least for closures, I think it is still achievable to use one name for both.

Reading the comment above, it is clear that for the closure name, the source-level function where the closure is defined is important. This is the name that users want to see. The physical function that contains the closure after inlining seems not that important, and we could omit it (if we can make symbol resolution work). So we probably want to name the closures along this line.

We need some mechanism to make symbol resolution work, when the closure containing function is inlined into multiple places. Currently we rely on naming it uniquely so different inlined versions of the closure get different names. But this is where the clutter comes from. Given that we now use indices for symbol resolution in the linker, I think this doesn't really require unique names. Not all symbols are solved by indices. But for closures, I think it is 100% index-resolvable. After inlining, closures can only be directly referenced in the containing package (it can be passed to other packages as a value, but that is not a direct symbol reference), and indices are sufficient for this case. It might be an issue for external linking if the closure symbols have the same name, but I think we can solve that by marking the them static. This way, we can make the closure have the same name regardless of inlining, determined by the source-level containing function.

One place is that currently the compiler doesn't like two symbols with the same name in the _same_ package, even if they are resolved solely by index. But that is an internal detail we can fix.

If for some reason using the same name doesn't work, or it confuses users or tools, we can try using a name that is mainly based on the  source-level containing function, with a short suffix for deduplication. Say, for a closure defined in `p.F` in the source code, an inlined version of it may be named `p.F.func1..inl.<hash>`, where `<hash>` is a short hash of the inline stack. Or we could let the linker fill in a unique suffix at link time. We could choose to omit the suffix in DWARF and in traceback printing, to make it more user friendly.

For the next step I'm going to try making the closure symbols static and ensure they are always resolved by index. If that works, we can start changing the names, without worrying about uniqueness.

Thanks.
