### ISSUE TITLE
x/tools/gopls: panic exporting invalid constant declaration

### ISSUE THREAD

**Issue by youryharchenko** [golang/go#60605]
gopls version: v0.12.2 (go1.19.6)
gopls flags: 
update flags: proxy
extension version: 0.38.0
go version: 1.19.6
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Sat, 03 Jun 2023 11:15:12 GMT
restart history:
Sat, 03 Jun 2023 11:10:13 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

const EPSILON float64 = 1e-

<pre>panic: internal error: assertion failed

goroutine 842 [running]:
golang.org/x/tools/internal/gcimporter.iexportCommon.func1()
	  iexport.go:93  0x8a
panic({0xd7df60, 0x115b670})
	  panic.go:884  0x212
golang.org/x/tools/internal/gcimporter.assert(...)
	  iexport.go:1141
golang.org/x/tools/internal/gcimporter.constantToFloat({0x1165398%3F, 0x1713530%3F})
	  iexport.go:967  0x147
golang.org/x/tools/internal/gcimporter.(*exportWriter).value(0xc00141c9c0, {0x1161098%3F, 0x16c0000}, {0x1165398, 0x1713530})
	  iexport.go:930  0x31e
golang.org/x/tools/internal/gcimporter.(*iexporter).doDecl(0xc000ea20f0, {0x116d6b8%3F, 0xc001698cc0%3F})
	  iexport.go:481  0x32d
golang.org/x/tools/internal/gcimporter.iexportCommon({0x115d0a0, 0xc001824870}, 0xc000b5a080, 0x0, 0x1, 0x2, {0xc0011e1c90, 0x1, 0x0%3F})
	  iexport.go:139  0x35c
golang.org/x/tools/internal/gcimporter.IExportShallow(0xdc06a0%3F, 0xc000247810)
	  iexport.go:43  0x75
golang.org/x/tools/gopls/internal/lsp/cache.(*typeCheckBatch).checkPackage.func1()
	  check.go:646  0x2b1
created by golang.org/x/tools/gopls/internal/lsp/cache.(*typeCheckBatch).checkPackage
	  check.go:638  0x305
[Error - 2:14:43 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by griesemer** [comment]
This is the assertion that fails (iexport.go:967):
```
// Value too large to represent as a fraction => inaccessible.
// TODO(gri): add big.Float accessor to constant.Value.
_, ok := f.SetString(x.ExactString())
assert(ok)
```
`ExactString` must be returning a string that cannot be parsed successfully by `SetString`.

The following code
```Go
package p
const _ float64 = 1e-
```
crashes gopls for me (see also #60649). The `1e-` leads to an unknown constant, the `ExactString` of which is "unknown". This cannot be handled by `SetString`.

**Comment by griesemer** [comment]
The `exportWriter.value` method should probably check if the constant value `v` is known in the first place. If it is not, it should treat it like having invalid type.

**Comment by findleyr** [comment]
Thanks for investigating! I'll fix the x/tools exporter.
