### ISSUE TITLE
os: GOOS=wasip1 returns non-IsNotExist errors on non-existent files

### ISSUE THREAD

**Issue by bradfitz** [golang/go#60732]
I'm trying to run some code with to-be Go 1.21's wasip1/wasm support.

We have some code:

```go
	cfgPath := filepath.Join(s.rootPath, "tailscaled.log.conf")
	lpc, err := logpolicy.ConfigFromFile(cfgPath)
	switch {
	case os.IsNotExist(err):
		lpc = logpolicy.NewConfig(logtail.CollectionNode)
		if err := lpc.Save(cfgPath); err != nil {
			return fmt.Errorf("logpolicy.Config.Save for %v: %w", cfgPath, err)
		}
	case err != nil:
		return fmt.Errorf("logpolicy.LoadConfig for %v: %w", cfgPath, err)
	}
```

And instead of hitting that `os.IsNotExist` path, it's going into the `case err != nil` path with:

```
$ wasmtime run --env=HOME=$HOME --dir=. ~/go/bin/wasip1_wasm/tshello
2023/06/12 00:28:09 tsnet: logpolicy.LoadConfig for tailscaled.log.conf: open tailscaled.log.conf: Bad file number
```

It's possible I'm holding `wasmtime` wrong, but "Bad file number" doesn't tell me much. Is that a not found error or a sandbox violation error, or ...?

/cc @johanbrandhorst

**Comment by johanbrandhorst** [comment]
CC @golang/wasm

**Comment by cuonglm** [comment]
It seems to me that using `.` as argument to `--dir` causes `wasmtime` confusing:

```
$ wasmtime run --dir=. main     
8 Bad file number
[] open ./non-existent-file: Bad file number
```

vs:

```
$ wasmtime run --dir=$PWD main
44 No such file or directory
[] open ./non-existent-file: No such file or directory
```

**Comment by achille-roussel** [comment]
I believe this is working "as intended" based on the documentation in https://github.com/bytecodealliance/wasmtime/blob/main/docs/WASI-tutorial.md#executing-in-wasmtime-runtime

Like @cuonglm reported, `wasmtime --dir=.` does not expose a directory with a path equal to `$PWD`, it exposes a directory named `.` pointing to the current working directory, which then defeats the current directory emulation that we do on GOOS=wasip1 (due to WASI not having the concept of working directory).

It's possible that there is a better way to handle this runtime-specific behavior tho, "Bad file number" is difficult to interpret correctly as a user. At the same time, I would like to avoid making too many special cases in Go, especially because there is no convention to reliably detect which wasm runtime is in use from the guest side.

Maybe we can try to align on the behavior of other compilers (e.g. TinyGo, Zig, Rust), so it's not "more broken" with Go.

**Comment by HarikrishnanBalagopal** [comment]
@achille-roussel I am facing a similar issue, PTAL if https://github.com/golang/go/issues/63466 is intended behaviour or not.

**Comment by achille-roussel** [comment]
@HarikrishnanBalagopal, it appears the difference comes from TinyGo and Go possibly using different default working directories.

Unfortunately, there is no concept of working directory in the wasip1 specification, so it's expected that different compilers will end up with diverging behaviors.

Go interprets the `PWD` environment variable to set the default. Have you tried setting `PWD=/` when running the program?

**Comment by HarikrishnanBalagopal** [comment]
> @HarikrishnanBalagopal, it appears the difference comes from TinyGo and Go possibly using different default working directories.
> 
> Unfortunately, there is no concept of working directory in the wasip1 specification, so it's expected that different compilers will end up with diverging behaviors.
> 
> Go interprets the `PWD` environment variable to set the default. Have you tried setting `PWD=/` when running the program?

That seems to fail even earlier
```
time="2023-10-09T19:14:14Z" level=info msg="start 8!!"
time="2023-10-09T19:14:14Z" level=info msg="just before Getwd, environment variable FOO is bar"
time="2023-10-09T19:14:14Z" level=info msg="just before Getwd, environment variable PWD is /"
time="2023-10-09T19:14:14Z" level=info msg="just before Getwd, environment variable MYPWD is /"
time="2023-10-09T19:14:14Z" level=info msg="pwd: ''"
panic: stat .: Bad file number

goroutine 1 [running]:
main.must(...)
        /Users/haribala/Documents/code/remote/github.com/HarikrishnanBalagopal/test-wasi-fs-browser/main.go:11
main.main()
        /Users/haribala/Documents/code/remote/github.com/HarikrishnanBalagopal/test-wasi-fs-browser/main.go:22 +0x7d
```

The JS Code is as shown in the README https://github.com/bjorn3/browser_wasi_shim#usage
```js
const env = ["FOO=bar", "PWD=/", "MYPWD=/"];
......
const wasi = new WASI(args, env, fds);
```

**Comment by HarikrishnanBalagopal** [comment]
@achille-roussel Nice! I also just got it to work by changing the JS code a bit

Old code
```js
        new PreopenDirectory(".", {
```

New code
```js
        new PreopenDirectory("/", {
```


```
time="2023-10-09T19:47:50Z" level=info msg="start 13!!"
time="2023-10-09T19:47:51Z" level=info msg="just before Getwd, environment variable FOO is bar"
time="2023-10-09T19:47:51Z" level=info msg="just before Getwd, environment variable PWD is "
time="2023-10-09T19:47:51Z" level=info msg="just before Getwd, environment variable MYPWD is /"
time="2023-10-09T19:47:51Z" level=info msg="pwd: '/'"
time="2023-10-09T19:47:51Z" level=info msg="f: - dep.json"
time="2023-10-09T19:47:51Z" level=info msg="f: - example.c"
time="2023-10-09T19:47:51Z" level=info msg="f: - hello.rs"
time="2023-10-09T19:47:51Z" level=info msg="just before ReadFile, environment variable FOO is bar"
time="2023-10-09T19:47:51Z" level=info msg="just before ReadFile, environment variable PWD is "
time="2023-10-09T19:47:51Z" level=info msg="just before ReadFile, environment variable MYPWD is /"
time="2023-10-09T19:47:51Z" level=info msg="The contents are:\n{\"a\": 42, \"b\": 12}"
time="2023-10-09T19:47:51Z" level=info msg=done
```

**Comment by achille-roussel** [comment]
@HarikrishnanBalagopal based on your examples, I think the guidelines here are the following:

- the runtime should set the `PWD` environment variable explicitly (default to `PWD=/` is acceptable)
- the preopen for the root directory should be named `/` (and not `.`)

If you can contribute, having working examples of a simple program like yours demonstrating how to run on different runtimes would be a great addition to the [wiki](https://github.com/golang/go/wiki/WebAssembly#wasi-gooswasip1-port) as well!

**Comment by iamrajiv** [comment]
Hi @HarikrishnanBalagopal and @achille-roussel,

I tested these issues locally and applied the suggested fixes. I also created a document explaining the details and have opened a PR here: https://github.com/golang/wiki/pull/75. Could you please review it?

Regarding Wasmer, I didn’t add a section for it because I’m currently blocked by this issue, which needs to be resolved first: https://github.com/golang/go/issues/59907.
