### ISSUE TITLE
net: ListenPacket crashes on wasip1/wasm

### ISSUE THREAD

**Issue by bradfitz** [golang/go#60739]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.21-1fd3cc7cd0 Sun Jun 11 00:41:42 2023 +0000 darwin/arm64
</pre>

### What did you do?

```
panic: interface conversion: net.sockaddr is *net.UDPAddr, not *net.TCPAddr

goroutine 1 [running]:
net.fakelistener(0x1c8a420, {0x2e1f60, 0x1d0e570})
        /Users/bradfitz/hack/go/src/net/net_fake.go:58 +0x1f
net.socket({0x2e08b8, 0xb60420}, {0x1ce350, 0x4}, 0x3, 0x2, 0x0, 0x1, {0x2e1f60, 0x1d0e570}, ...)
        /Users/bradfitz/hack/go/src/net/net_fake.go:51 +0x7
net.internetSocket({0x2e08b8, 0xb60420}, {0x1ce350, 0x4}, {0x2e1f60, 0x1d0e570}, {0x0, 0x0}, 0x2, 0x0, ...)
        /Users/bradfitz/hack/go/src/net/ipsock_posix.go:142 +0x3
net.(*sysListener).listenUDP(0x1d0d008, {0x2e08b8, 0xb60420}, 0x1d0e570)
        /Users/bradfitz/hack/go/src/net/udpsock_posix.go:226 +0x7
net.(*ListenConfig).ListenPacket(0x1c0a3c0, {0x2e08b8, 0xb60420}, {0x1ce350, 0x4}, {0x1c0c648, 0x2})
        /Users/bradfitz/hack/go/src/net/dial.go:753 +0x1f
tailscale.com/types/nettype.packetListenerAdapter.ListenPacket({{0x2d9700, 0x1c0a3c0}}, {0x2e08b8, 0xb60420}, {0x1ce350, 0x4}, {0x1c0c648, 0x2})
        /Users/bradfitz/src/tailscale.com/types/nettype/nettype.go:54 +0x4
```

It assumes TCP:

```go
func socket(ctx context.Context, net string, family, sotype, proto int, ipv6only bool, laddr, raddr sockaddr, ctrlCtxFn func(context.Context, string, string, syscall.RawConn) error) (*netFD, error) {
	fd := &netFD{family: family, sotype: sotype, net: net}
	if laddr != nil && raddr == nil {
		return fakelistener(fd, laddr)
	}
	fd2 := &netFD{family: family, sotype: sotype, net: net}
	return fakeconn(fd, fd2, raddr)
}

func fakelistener(fd *netFD, laddr sockaddr) (*netFD, error) {
	l := laddr.(*TCPAddr)
	fd.laddr = &TCPAddr{
		IP:   l.IP,
		Port: nextPort(),
		Zone: l.Zone,
	}
	fd.fakeNetFD = &fakeNetFD{
		listener: true,
		laddr:    fd.laddr,
		incoming: make(chan *netFD, 1024),
	}
	listenersMu.Lock()
	listeners[fd.laddr.(*TCPAddr).String()] = fd
	listenersMu.Unlock()
	return fd, nil
}
```

/cc @golang/wasm

**Comment by seankhliao** [comment]
related #60012

**Comment by johanbrandhorst** [comment]
I think https://go-review.googlesource.com/c/go/+/502315 should address this
