### ISSUE TITLE
x/text: Index out of range error from golang.org/x/text/unicode/norm (runtime panic)

### ISSUE THREAD

**Issue by alasdairforsythe** [golang/go#60860]
go version go1.20.5 linux/arm64

I can confirm this runtime panic occurs on v0.9 and v0.10 of x/text.
```
panic: runtime error: index out of range [32] with length 32

goroutine 1 [running]:
golang.org/x/text/unicode/norm.(*reorderBuffer).insertOrdered(...)
        /root/tokenize/v3/vendor/golang.org/x/text/unicode/norm/composition.go:201
golang.org/x/text/unicode/norm.(*reorderBuffer).insertSingle(0x4000028280, {{0x11712b, 0x2}, {0x0, 0x0, 0x0}}, 0x0?, {0x0, 0x2, 0x0, ...})
        /root/tokenize/v3/vendor/golang.org/x/text/unicode/norm/composition.go:269 +0x160
golang.org/x/text/unicode/norm.(*reorderBuffer).insertCGJ(...)
        /root/tokenize/v3/vendor/golang.org/x/text/unicode/norm/composition.go:274
golang.org/x/text/unicode/norm.decomposeSegment(0x4000028280, 0x1, 0x1)
        /root/tokenize/v3/vendor/golang.org/x/text/unicode/norm/normalize.go:540 +0x3f0
golang.org/x/text/unicode/norm.doAppend(0x4000028280, {0x400014e000?, 0xfc2?, 0x2500?}, 0x0?)
        /root/tokenize/v3/vendor/golang.org/x/text/unicode/norm/normalize.go:235 +0x270
golang.org/x/text/unicode/norm.(*normWriter).Write(0x4000028280, {0x4022a80000?, 0x2939ecaf?, 0x29395ef2?})
        /root/tokenize/v3/vendor/golang.org/x/text/unicode/norm/readwriter.go:30 +0xf8
main.norm_UTF8_NFD({0x4022a80000, 0x293a1d4e, 0x339815bd})
        /root/tokenize/v3/getalltokens.go:126 +0x1a4
main.main()
        /root/tokenize/v3/getalltokens.go:994 +0x998
```

```
func norm_UTF8_NFD(input []byte) ([]byte, error) {
	normalized := bytes.NewBuffer(make([]byte, 0, len(input) + (len(input) / 3) + 4))
	normalizer := norm.NFD.Writer(normalized)
	_, err := normalizer.Write(input) // ------------- This is line 126 -------------
	if err != nil {
		return nil, err
	}
	err = normalizer.Close()
	if err != nil {
		return nil, err
	}
	return normalized.Bytes(), nil
}
```
If you want the exact input causing the error, it's 600MB of text. I can send it somewhere if it's required.

**Comment by seankhliao** [comment]
can you upload a zipped file of input here?

**Comment by ianlancetaylor** [comment]
CC @mpvl

**Comment by alasdairforsythe** [comment]
[Here ](https://bot.co/normoutofrange.zip) is a zip containing the text file that causes the issue and a small code sample that reproduces the error.

**Comment by alasdairforsythe** [comment]
Since v0.11 the error is now `panic: runtime error: index out of range [1] with length 1` (instead of 32)

Any timeline on the fix for this? Currently I'm having to work around it.

**Comment by mbwmbw1337** [comment]
I see the same issue. Cross-linking: https://github.com/ledgerwatch/erigon/issues/8235
