### ISSUE TITLE
runtime: frequent TestBreakpoint timeouts on plan9-amd64-0intro

### ISSUE THREAD

**Issue by bcmills** [golang/go#61087]
```
#!watchflakes
post <- goos == "plan9" && pkg == "runtime" && test == "TestBreakpoint"
```

https://build.golang.org/log/ea934fa51d0c0cfd54392cf5a60d72483dda50e2:
```
panic: test timed out after 6m0s
running tests:
	TestBreakpoint (5m50s)
…
goroutine 23057 [syscall, 5 minutes]:
syscall.Syscall6(0x32, 0x4, 0x488d0c8d, 0x373, 0xffffffffffffffff, 0xffffffffffffffff, 0x0)
	/tmp/workdir-gnot/go/src/syscall/asm_plan9_amd64.s:63 +0x10 fp=0x49236cf0 sp=0x49236c38 pc=0x2821d0
syscall.Pread(0x488c4c40?, {0x488d0c8d?, 0x49236eec?, 0x2?}, 0x12?)
	/tmp/workdir-gnot/go/src/syscall/zsyscall_plan9_amd64.go:218 +0x5e fp=0x49236d68 sp=0x49236cf0 pc=0x281c7e
syscall.Read(...)
	/tmp/workdir-gnot/go/src/syscall/syscall_plan9.go:170
os.(*File).read(0x48728440, {0x488d0c8d, 0x373, 0x373})
	/tmp/workdir-gnot/go/src/os/file_plan9.go:286 +0xeb fp=0x49236dd8 sp=0x49236d68 pc=0x29f68b
os.(*File).Read(0x49f2fd70?, {0x488d0c8d, 0x373, 0x373})
	/tmp/workdir-gnot/go/src/os/file.go:118 +0x65 fp=0x49236e20 sp=0x49236dd8 pc=0x29d485
bytes.(*Buffer).ReadFrom(0x49f2fd70, {0x6c1c80, 0x48728440})
	/tmp/workdir-gnot/go/src/bytes/buffer.go:211 +0x98 fp=0x49236e78 sp=0x49236e20 pc=0x2d9b98
io.copyBuffer({0x6c1d00, 0x49f2fd70}, {0x6c1c80, 0x48728440}, {0x0, 0x0, 0x0})
	/tmp/workdir-gnot/go/src/io/io.go:416 +0x147 fp=0x49236ef8 sp=0x49236e78 pc=0x297707
io.Copy(...)
	/tmp/workdir-gnot/go/src/io/io.go:389
os/exec.(*Cmd).writerDescriptor.func1()
	/tmp/workdir-gnot/go/src/os/exec/exec.go:560 +0x34 fp=0x49236f58 sp=0x49236ef8 pc=0x330a94
os/exec.(*Cmd).Start.func2(0x48871f20?)
	/tmp/workdir-gnot/go/src/os/exec/exec.go:717 +0x2c fp=0x49236fc8 sp=0x49236f58 pc=0x33180c
os/exec.(*Cmd).Start.func3()
	/tmp/workdir-gnot/go/src/os/exec/exec.go:729 +0x27 fp=0x49236fe0 sp=0x49236fc8 pc=0x3317a7
runtime.goexit()
	/tmp/workdir-gnot/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0x49236fe8 sp=0x49236fe0 pc=0x273a61
created by os/exec.(*Cmd).Start in goroutine 23055
	/tmp/workdir-gnot/go/src/os/exec/exec.go:716 +0xa65
```

(attn @golang/plan9)

**Comment by bcmills** [comment]
The symptoms here look very similar to #60793: an `exec.Cmd` is blocked on reading a pipe from a child process that has crashed or otherwise terminated.

**Comment by 0intro** [comment]
CC @millerresearch

**Comment by psilva261** [comment]
Actually when running `src/runtime/testdata/testprog Breakpoint` directly the output is:

```
sys: breakpoint pc=0x25e200
PC=0x25e200

goroutine 1 [running]:
testprog 19395: suicide: sys: floating point in note handler pc=0x202860
testprog 19395: sys: floating point in note handler pc=0x202860
```

It's similar to https://github.com/golang/go/issues/24387 where `internal/bytealg.IndexByteString` is called which uses floating point instructions in the note handler. I'll create a CL for that.
