### ISSUE TITLE
x/build: create host-openbsd-amd64-72 (VM Image: openbsd-amd64-72) LUCI image

### ISSUE THREAD

**Issue by cagedmantis** [golang/go#61090]
Create the LUCI openbsd-amd64-72 image.

This should serve as a prototype for running LUCI under a BSD type OS.

/cc @golang/release

**Comment by cagedmantis** [comment]
The initial swarming bot error encountered:

```
12883 2023-06-30 17:14:07.528 E: ts_mon monitoring is disabled because the endpoint provided is invalid or not supported:
12883 2023-06-30 17:14:07.530 E: os.utilities.get_hostname_short() failed
Traceback (most recent call last):
  File "/home/gopher/.swarming/swarming_bot.1.zip/bot_code/bot_main.py", line 385, in _get_botid_safe
    return os_utilities.get_hostname_short()
  File "/home/gopher/.swarming/swarming_bot.1.zip/utils/tools.py", line 211, in wrapper
    v = func(*args)
  File "/home/gopher/.swarming/swarming_bot.1.zip/api/os_utilities.py", line 421, in get_hostname_short
    return get_hostname().split('.', 1)[0]
  File "/home/gopher/.swarming/swarming_bot.1.zip/utils/tools.py", line 211, in wrapper
    v = func(*args)
  File "/home/gopher/.swarming/swarming_bot.1.zip/api/os_utilities.py", line 399, in get_hostname
    if platforms.is_gce() and not os.path.isfile('/.dockerenv'):
AttributeError: module 'api.platforms' has no attribute 'is_gce'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/gopher/.swarming/swarming_bot.1.zip/__main__.py", line 336, in <module>
  File "/home/gopher/.swarming/swarming_bot.1.zip/__main__.py", line 324, in main
  File "/home/gopher/.swarming/swarming_bot.1.zip/__main__.py", line 203, in CMDstart_bot
  File "/home/gopher/.swarming/swarming_bot.1.zip/bot_code/bot_main.py", line 2215, in main
  File "/home/gopher/.swarming/swarming_bot.1.zip/bot_code/bot_main.py", line 1127, in _run_bot
  File "/home/gopher/.swarming/swarming_bot.1.zip/bot_code/bot_main.py", line 1165, in _run_bot_inner
AttributeError: module 'api.platforms' has no attribute 'is_gce'
Sending the crash report ... done.
Report URL: https://chromium-swarm.appspot.com/restricted/ereporter2/errors/5221411539779584
Process exited due to exception
module 'api.platforms' has no attribute 'is_gce'
2023/06/30 10:14:07 command execution /usr/local/bin/python3 /home/gopher/.swarming/swarming_bot.zip start_bot: exit status 1
```
