### ISSUE TITLE
cmd/compile: internal compiler error in unaligned pointer write 

### ISSUE THREAD

**Issue by brutalsavage** [golang/go#61187]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.21-6260049fa2
</pre>

### Does this issue reproduce with the latest release?

Reproduces on the most recent developer release branch, can see the later go-playground link

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/.cache/go-build'
GOENV='/home/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/home/goroot'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/home/goroot/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='devel go1.21-6260049fa2'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build531354456=/tmp/go-build -gno-record-gcc-switches'

</pre></details>

### What did you do?

modifying unsafe.Pointer data leads to internal compiler error. (i.e `go build` the following code)

```go
package main

import (
	"fmt"
	"reflect"
	"unsafe"
)

var slice = []byte{'H', 'e', 'l', 'l', 'o', ','}

func main() {
	ptr := uintptr(unsafe.Pointer(&slice)) + 100
	header := (*reflect.SliceHeader)(unsafe.Pointer(ptr))
	header.Data += 1 // comment this line does not lead to internal compiler error
	fmt.Printf("%d %d\n", cap(slice), header.Cap)
}
```
[go.dev](https://go.dev/play/p/k2o6tkIbp5O?v=gotip) link to reproduce.

### What did you expect to see?

Does not lead to internal compiler error

### What did you see instead?

```
<unknown line number>: internal compiler error: 'main': unaligned pointer write

goroutine 9 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
cmd/compile/internal/base.FatalfAt({0x431324?, 0xc0?}, {0xc0006b3168, 0x1d}, {0xc0006b3190, 0x1, 0x1})
	/usr/local/go/src/cmd/compile/internal/base/print.go:230 +0x1d7
cmd/compile/internal/base.Fatalf(...)
	/usr/local/go/src/cmd/compile/internal/base/print.go:199
cmd/compile/internal/ssagen.(*ssafn).Fatalf(0xc0006b31f8?, {0xcc3080?, 0x0?}, {0xd7d5f0, 0x17}, {0x0, 0x0, 0x6?})
	/usr/local/go/src/cmd/compile/internal/ssagen/ssa.go:7997 +0x16a
cmd/compile/internal/ssa.(*Value).Fatalf(...)
	/usr/local/go/src/cmd/compile/internal/ssa/value.go:454
cmd/compile/internal/ssa.mightContainHeapPointer(0xc0003daae0?, 0x8, 0xc0005e86f0, 0x1?)
	/usr/local/go/src/cmd/compile/internal/ssa/writebarrier.go:57 +0x12f
cmd/compile/internal/ssa.needwb(...)
	/usr/local/go/src/cmd/compile/internal/ssa/writebarrier.go:95
cmd/compile/internal/ssa.writebarrier(0xc00043bba0)
	/usr/local/go/src/cmd/compile/internal/ssa/writebarrier.go:201 +0x47ba
cmd/compile/internal/ssa.Compile(0xc00043bba0)
	/usr/local/go/src/cmd/compile/internal/ssa/compile.go:97 +0x9ab
cmd/compile/internal/ssagen.buildssa(0xc000486000, 0x3)
	/usr/local/go/src/cmd/compile/internal/ssagen/ssa.go:568 +0x2b09
cmd/compile/internal/ssagen.Compile(0xc000486000, 0x0?)
	/usr/local/go/src/cmd/compile/internal/ssagen/pgen.go:187 +0x45
cmd/compile/internal/gc.compileFunctions.func5.1(0xc000401ac0?)
	/usr/local/go/src/cmd/compile/internal/gc/compile.go:184 +0x34
cmd/compile/internal/gc.compileFunctions.func3.1()
	/usr/local/go/src/cmd/compile/internal/gc/compile.go:166 +0x30
created by cmd/compile/internal/gc.compileFunctions.func3 in goroutine 8
	/usr/local/go/src/cmd/compile/internal/gc/compile.go:165 +0x23a


Go build failed.
```

**Comment by Nasfame** [comment]
Code is working as expected when slice is init in main()

https://go.dev/play/p/Xl-Bg3tYTz-?v=gotip

**Comment by randall77** [comment]
We could theoretically allow this to pass by removing the "offset must be a multiple of the pointer size" check. But there's really a multiple of invalid uses of unsafe here, so I'm not inclined to do that for this case. (Unless this example came up in a more realistic case? Please reopen if you have such a case.)

Note that this code doesn't obviously need a write barrier, as it is storing only `uintptr`s. The reason a write barrier appears is that the compiler promotes `reflect.SliceHeader.Data` from a `uintptr` to an `unsafe.Pointer` internally. Define your own similar type and this won't happen.

**Comment by Nasfame** [comment]
<s> Git-Bisect:  https://github.com/golang/go/commit/9088c691dac424540f562d6271c5ee479e9f9d80 </s>

Bisect: 6b5b7b3240ed635f58d25d292a345450c0937979 is the first bad commit


```
git bisect start
# status: waiting for both good and bad commits
# bad: [36ea4f9680f8296f1c7d0cf7dbb1b3a9d572754a] log/slog: fix faulty test
git bisect bad 36ea4f9680f8296f1c7d0cf7dbb1b3a9d572754a
# status: waiting for good commit(s), bad commit known
# good: [e827d41c0a2ea392c117a790cdfed0022e419424] [release-branch.go1.20] go1.20.5
git bisect good e827d41c0a2ea392c117a790cdfed0022e419424
# good: [9088c691dac424540f562d6271c5ee479e9f9d80] cmd/compile: ensure temp register mask isn't empty
git bisect good 9088c691dac424540f562d6271c5ee479e9f9d80
# bad: [d8117459c513e048eb72f11988d5416110dff359] [release-branch.go1.21] go1.21rc2
git bisect bad d8117459c513e048eb72f11988d5416110dff359
# bad: [830f54b70ed2ce0c28c8db30876aba67beed7ee3] go/build/constraint: add GoVersion
git bisect bad 830f54b70ed2ce0c28c8db30876aba67beed7ee3
# bad: [52af6550c92b1023e64c48e7b0fd947e539fb30f] os: don't try to put directory into non-blocking mode
git bisect bad 52af6550c92b1023e64c48e7b0fd947e539fb30f
# good: [23c0121e4eb259cc1087d0f79a0803cbc71f500b] cmd/go/internal/script: retry ETXTBSY errors in scripts
git bisect good 23c0121e4eb259cc1087d0f79a0803cbc71f500b
# good: [0cd309e12818f988693bf8e4d9f1453331dcf9f2] go/internal/gcimporter: restore Go 1.19 Package.SetImports behavior
git bisect good 0cd309e12818f988693bf8e4d9f1453331dcf9f2
# bad: [ecff9c9335584a58ff6c45e71876ba60d982676c] cmd/internal/obj/arm64: invert SP check
git bisect bad ecff9c9335584a58ff6c45e71876ba60d982676c
# bad: [d3daeb5267b626db36adf2f39c36f6caf94447e3] runtime: remove the restriction that write barrier ptrs come in pairs
git bisect bad d3daeb5267b626db36adf2f39c36f6caf94447e3
# good: [0e42632301f17ae384e2cc1edb273860ed8f9fac] cmd/compile: share compiler allocations of similar shapes
git bisect good 0e42632301f17ae384e2cc1edb273860ed8f9fac
# bad: [cd77738198ffe0c4a1db58352c89f9b2d2a4e85e] cmd/link: don't switch to gold on ARM Linux
git bisect bad cd77738198ffe0c4a1db58352c89f9b2d2a4e85e
# bad: [518889b35cb07f3e71963f2ccfc0f96ee26a51ce] cmd/compile: ensure InitMem comes after Args
git bisect bad 518889b35cb07f3e71963f2ccfc0f96ee26a51ce
# bad: [44d22e75dd9a0cbffbb04c9ce6d6bf9030634cc1] cmd/compile: detect write barrier completion differently
git bisect bad 44d22e75dd9a0cbffbb04c9ce6d6bf9030634cc1
# bad: [6b5b7b3240ed635f58d25d292a345450c0937979] cmd/compile: reorganize write barrier code a bit
git bisect bad 6b5b7b3240ed635f58d25d292a345450c0937979
# first bad commit: [6b5b7b3240ed635f58d25d292a345450c0937979] cmd/compile: reorganize write barrier code a bit
```

**Comment by Nasfame** [comment]
@randall77 is this a bug?

**Comment by ianlancetaylor** [comment]
This is not, perhaps, an important bug, but it is a bug.  The compiler should not crash.  We don't need to compile this kind of code but we should print an error message, not crash.
