### ISSUE TITLE
x/tools/gopls: panic in OriginMethod

### ISSUE THREAD

**Issue by mrtroian** [golang/go#61196]
gopls version: v0.12.4 (go1.20.5)
gopls flags: 
update flags: proxy
extension version: 0.39.0
go version: 1.20.5
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Thu, 29 Jun 2023 19:06:21 GMT
restart history:
Thu, 29 Jun 2023 19:06:09 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>
gopls server started crashing after update.
It crashes right after launching VSCode or installing Go extension.

I've tried:

- downgrade to previous release of gopls
- downgrade to previous of that
- update go (1.19.8->1.20.5)
- Go extension nightly version
- Update/Reinstall VSCode
- reinstall gopls via CLI
- Checked out other issues on Github, a lot of crashes, nothing that looks like my case

<pre>panic: interface conversion: types.Object is nil, not *types.Func

goroutine 5265 [running]:
golang.org/x/tools/internal/typeparams.OriginMethod(0x14009adc240)
	  common.go:128  0x258
golang.org/x/tools/gopls/internal/lsp/source/methodsets.(*indexBuilder).build.func2(0x14009a59f00, 0x14009adc240)
	  methodsets.go:248  0x1c4
golang.org/x/tools/gopls/internal/lsp/source/methodsets.methodSetInfo({0x105076dd0, 0x14007dd6d90}, 0x140041dfb08)
	  methodsets.go:309  0x1f0
golang.org/x/tools/gopls/internal/lsp/source/methodsets.(*indexBuilder).build(0x140041dfbe0, 0x140037f9940, 0x14009a8c640)
	  methodsets.go:261  0x4f0
golang.org/x/tools/gopls/internal/lsp/source/methodsets.NewIndex(...)
	  methodsets.go:98
golang.org/x/tools/gopls/internal/lsp/cache.(*syntaxPackage).methodsets.func1()
	  pkg.go:74  0x40
sync.(*Once).doSlow(0x140040e1ca8%3F, 0x1044a7b10%3F)
	  once.go:74  0x104
sync.(*Once).Do(...)
	  once.go:65
golang.org/x/tools/gopls/internal/lsp/cache.(*syntaxPackage).methodsets(0x14007db60f0%3F)
	  pkg.go:73  0x50
golang.org/x/tools/gopls/internal/lsp/cache.(*typeCheckBatch).checkPackage.func1()
	  check.go:649  0xe4
created by golang.org/x/tools/gopls/internal/lsp/cache.(*typeCheckBatch).checkPackage
	  check.go:646  0x228
[Error - 22:06:19] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
The CL above should make this panic more useful. Could you please build gopls @ master, and provide us the improved panic?

```
git clone https://go.googlesource.com/tools
cd tools/gopls
go install
```

Thank you!

**Comment by findleyr** [comment]
Closing this as I am pretty sure it is a consequence of #61561, and should have been largely mitigated by gopls@v0.13.0 (and fixed using go@master).
