### ISSUE TITLE
cmd/go: crash in bad usage

### ISSUE THREAD

**Issue by rsc** [golang/go#61258]
```
% go get go@go1.21
panic: bad requirement: rootModules[4] = go

goroutine 1 [running]:
cmd/go/internal/modload.newRequirements(0x1, {0xc0003d4600?, 0xb, 0x10}, 0xc00030c0c0)
	/Users/rsc/go/src/cmd/go/internal/modload/buildlist.go:135 +0x53c
cmd/go/internal/modload.editRequirements({0x178b418, 0x1b33b40}, 0xc00008e140, {0x0, 0x0, 0x15deb80?}, {0xc0002028e0, 0x1, 0xc000248160?})
	/Users/rsc/go/src/cmd/go/internal/modload/edit.go:564 +0x1609
cmd/go/internal/modload.EditBuildList({0x178b418, 0x1b33b40}, {0x0, 0x0, 0x0}, {0xc0002028e0, 0x1, 0x1})
	/Users/rsc/go/src/cmd/go/internal/modload/buildlist.go:640 +0x85
cmd/go/internal/modget.(*resolver).updateBuildList(0xc000376000, {0x178b418, 0x1b33b40}, {0x0, 0x0, 0x0})
	/Users/rsc/go/src/cmd/go/internal/modget/get.go:1857 +0x293
cmd/go/internal/modget.(*resolver).resolveQueries(0xc000376000, {0x178b418, 0x1b33b40}, {0xc00006c0b0, 0x1, 0x15b8520?})
	/Users/rsc/go/src/cmd/go/internal/modget/get.go:1300 +0x228
cmd/go/internal/modget.runGet({0x178b418, 0x1b33b40}, 0xc0000286d8?, {0xc000022200, 0x1, 0x1})
	/Users/rsc/go/src/cmd/go/internal/modget/get.go:335 +0x454
main.invoke(0x1af8460, {0xc0000221f0, 0x2, 0x2})
	/Users/rsc/go/src/cmd/go/main.go:264 +0x5f1
main.main()
	/Users/rsc/go/src/cmd/go/main.go:182 +0x778
```

**Comment by bcmills** [comment]
I suspect this line is the cause:
https://cs.opensource.google/go/go/+/refs/heads/master:src/cmd/go/internal/modload/query.go;l=716-718;drc=6a063b01b0b0effa787c5aed90b585b409fe4688

It is probably causing `modload.QueryPattern` to return a spurious nil error.
