### ISSUE TITLE
x/tools/gopls: panic in internal/lsp/cache.typeCheckBatch.importMap

### ISSUE THREAD

**Issue by danp** [golang/go#61512]
Using https://github.com/golang/tools/commit/7ba569039c81baacb447d86606fa51f4bc46c20e. Have had gopls crashes occasionally since I pulled tools tip over the last few days but haven't been able to track them down. After turning debug things on I had a crash and got this:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1030de768]

goroutine 2316805 [running]:
golang.org/x/tools/gopls/internal/lsp/cache.(*typeCheckBatch).importMap.func1(0x1035260a0?)
	/Users/dan/go/src/golang.org/x/tools/gopls/internal/lsp/cache/check.go:706 +0x98
golang.org/x/tools/gopls/internal/lsp/cache.(*typeCheckBatch).importMap(0x1401fa584b0, {0x14012acebd0, 0x2b})
	/Users/dan/go/src/golang.org/x/tools/gopls/internal/lsp/cache/check.go:715 +0x8c
golang.org/x/tools/gopls/internal/lsp/cache.(*typeCheckBatch).importPackage(0x1401fa584b0, {0x103644868, 0x14020345c20}, 0x1400786cfc0, {0x14034872c80, 0xc3, 0x140})
	/Users/dan/go/src/golang.org/x/tools/gopls/internal/lsp/cache/check.go:541 +0x150
golang.org/x/tools/gopls/internal/lsp/cache.(*typeCheckBatch).getImportPackage(0x1401fa584b0, {0x103644868, 0x14020345c20}, {0x14012acebd0, 0x2b})
	/Users/dan/go/src/golang.org/x/tools/gopls/internal/lsp/cache/check.go:473 +0x5d8
golang.org/x/tools/gopls/internal/lsp/cache.(*snapshot).forEachPackageInternal.func1()
	/Users/dan/go/src/golang.org/x/tools/gopls/internal/lsp/cache/check.go:395 +0x30
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/Users/dan/Library/Caches/go-mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x58
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 2315848
	/Users/dan/Library/Caches/go-mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0x98
```

Seems to be triggered when I change branches but not always.

**Comment by danp** [comment]
Possibly related to https://github.com/golang/tools/commit/ffc82f3af7f0ec291ed962da8774262b95cc5c9b?

**Comment by findleyr** [comment]
Thanks very much for the report!
