### ISSUE TITLE
cmd/link: segfaults occuring when using lld as default linker on linux/arm64

### ISSUE THREAD

**Issue by kraj** [golang/go#61872]
Following crash is seen When using lld as default linker on aarch64/linux, it works fine if BFD linker is used.
The default linker has to be selected systemwide and not just for building the application ( crucible in this case )
some other apps which show same problem are gosu, syzkaller and influxdb.  This is aarch64/linux/lld specific and can be seen on musl or glibc bullds. I am using yocto project to build this. I can get more information. If someone can guide me on what to extract which will be useful.

Here is the segfault detail. 

```
# github.com/usbarmory/crucible/cmd/crucible
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x57829a]

goroutine 1 [running]:
cmd/link/internal/ld.decodetypeGcmask(0xc00011e000, 0xc000036ea8?)
	TOPDIR/build/tmp/work/x86_64-linux/go-cross-cortexa57/1.20.7-r0/recipe-sysroot-native/usr/lib/aarch64-yoe-linux-musl/go/src/cmd/link/internal/ld/decodesym.go:251 +0x37a
cmd/link/internal/ld.(*GCProg).AddSym(0xc00186d860, 0x86a)
	TOPDIR/build/tmp/work/x86_64-linux/go-cross-cortexa57/1.20.7-r0/recipe-sysroot-native/usr/lib/aarch64-yoe-linux-musl/go/src/cmd/link/internal/ld/data.go:1317 +0x18e
cmd/link/internal/ld.(*dodataState).allocateDataSections(0xc000592a00, 0xc00011e000)
	TOPDIR/build/tmp/work/x86_64-linux/go-cross-cortexa57/1.20.7-r0/recipe-sysroot-native/usr/lib/aarch64-yoe-linux-musl/go/src/cmd/link/internal/ld/data.go:1844 +0x4998
cmd/link/internal/ld.(*Link).dodata(0xc00011e000, {0xc001c88000, 0x1a4ac, 0x1a4ac})
	TOPDIR/build/tmp/work/x86_64-linux/go-cross-cortexa57/1.20.7-r0/recipe-sysroot-native/usr/lib/aarch64-yoe-linux-musl/go/src/cmd/link/internal/ld/data.go:1634 +0xb07
cmd/link/internal/ld.Main(_, {0x10, 0x20, 0x1, 0x1f, 0x1e, 0x7c00000, {0x69331a, 0x14}, {0x69711d, ...}, ...})
	TOPDIR/build/tmp/work/x86_64-linux/go-cross-cortexa57/1.20.7-r0/recipe-sysroot-native/usr/lib/aarch64-yoe-linux-musl/go/src/cmd/link/internal/ld/main.go:338 +0x153b
main.main()
	TOPDIR/build/tmp/work/x86_64-linux/go-cross-cortexa57/1.20.7-r0/recipe-sysroot-native/usr/lib/aarch64-yoe-linux-musl/go/src/cmd/link/main.go:72 +0xedb
WARNING: TOPDIR/build/tmp/work/cortexa57-yoe-linux-musl/crucible/2023.04.12-r0/temp/run.do_compile.2587767:174 exit 1 from 'aarch64-yoe-linux-musl-go install -linkshared -p 10 -v -ldflags="-r /usr/lib/go/pkg/linux_arm64_dynlink  -I /lib/ld-musl-aarch64.so.1  -extldflags '-target aarch64-yoe-linux-musl  -mcpu=cortex-a57 -march=armv8-a+crc -mbranch-protection=standard -mlittle-endian --dyld-prefix=/usr -Qunused-arguments -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=TOPDIR/build/tmp/work/cortexa57-yoe-linux-musl/crucible/2023.04.12-r0/recipe-sysroot -Wl,-rpath-link=TOPDIR/build/tmp/work/cortexa57-yoe-linux-musl/crucible/2023.04.12-r0/recipe-sysroot/usr/lib/go/pkg/linux_arm64_dynlink -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed   -fmacro-prefix-map=TOPDIR/build/tmp/work/cortexa57-yoe-linux-musl/crucible/2023.04.12-r0/crucible-2023.04.12=/usr/src/debug/crucible/2023.04.12-r0  -fdebug-prefix-map=TOPDIR/build/tmp/work/cortexa57-yoe-linux-musl/crucible/2023.04.12-r0/crucible-2023.04.12=/usr/src/debug/crucible/2023.04.12-r0  -fmacro-prefix-map=TOPDIR/build/tmp/work/cortexa57-yoe-linux-musl/crucible/2023.04.12-r0/build=/usr/src/debug/crucible/2023.04.12-r0  -fdebug-prefix-map=TOPDIR/build/tmp/work/cortexa57-yoe-linux-musl/crucible/2023.04.12-r0/build=/usr/src/debug/crucible/2023.04.12-r0  -fdebug-prefix-map=TOPDIR/build/tmp/work/cortexa57-yoe-linux-musl/crucible/2023.04.12-r0/recipe-sysroot=  -fmacro-prefix-map=TOPDIR/build/tmp/work/cortexa57-yoe-linux-musl/crucible/2023.04.12-r0/recipe-sysroot=  -fdebug-prefix-map=TOPDIR/build/tmp/work/cortexa57-yoe-linux-musl/crucible/2023.04.12-r0/recipe-sysroot-native=  -Wl,-z,relro,-z,now   -fuse-ld=lld'" -trimpath -modcacherw -buildmode=pie `go_list_packages`'
```

**Comment by mknyszek** [comment]
CC @golang/compiler
