### ISSUE TITLE
cmd/go,  run go get -u or go mod tidy panic

### ISSUE THREAD

**Issue by it512** [golang/go#61877]
### What version of Go are you using (`go version`)?

<pre>
$ go version. 1.21.0
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/mikewang/.cache/go-build'
GOENV='/home/mikewang/.config/go/env'
GOEXE=''
GOEXPERIMENT='arenas'
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/mikewang/go/pkg/mod'
GONOPROXY='gitlab.it9i.com'
GONOSUMDB='gitlab.it9i.com'
GOOS='linux'
GOPATH='/home/mikewang/go'
GOPRIVATE='gitlab.it9i.com'
GOPROXY='https://goproxy.cn,direct'
GOROOT='/home/mikewang/go1.21.0'
GOSUMDB='sum.golang.google.cn'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/home/mikewang/go1.21.0/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.0'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/mikewang/go_w/goodsfamily/gis-comp/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build4138640415=/tmp/go-build -gno-record-gcc-switches'
</pre></details>

### What did you do?

<img width="745" alt="image" src="https://github.com/golang/go/assets/17774530/25288cf9-213d-4e1c-9e75-436cb0b8ccbb">

**Comment by bcmills** [comment]
Can you post (redacted) output from `go get -x`?
My working hypothesis is that we are missing a `Close` call on an HTTP response body on some path.

**Comment by it512** [comment]
mikewang@VM-24-16-ubuntu:~/go_w/goodsfamily/gis-comp$ go get -x gitlab.it9i.com/comp/psdk/quit
# get https://gitlab.it9i.com/?go-get=1
# get https://gitlab.it9i.com/comp/psdk?go-get=1
# get https://gitlab.it9i.com/comp/psdk/quit?go-get=1
# get https://gitlab.it9i.com/comp?go-get=1
# get https://gitlab.it9i.com/?go-get=1: Get "http://gitlab.it9i.com/users/sign_in": redirected from secure URL https://gitlab.it9i.com/?go-get=1 to insecure URL http://gitlab.it9i.com/users/sign_in
# get https://gitlab.it9i.com/comp?go-get=1: Get "http://gitlab.it9i.com/users/sign_in": redirected from secure URL https://gitlab.it9i.com/comp?go-get=1 to insecure URL http://gitlab.it9i.com/users/sign_in
# get https://gitlab.it9i.com/comp/psdk?go-get=1: 200 OK (1.657s)
mkdir -p /home/mikewang/go/pkg/mod/cache/vcs # git3 http://gitlab.it9i.com/comp/psdk.git
# lock /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949.lock
# /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949 for git3 http://gitlab.it9i.com/comp/psdk.git
cd /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949; git ls-remote -q origin
# get https://gitlab.it9i.com/comp/psdk/quit?go-get=1: 200 OK (1.717s)
# get https://gitlab.it9i.com/comp/psdk?go-get=1
# get https://gitlab.it9i.com/comp/psdk?go-get=1: 200 OK (0.388s)
4.535s # cd /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949; git ls-remote -q origin
cd /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949; git -c log.showsignature=false log --no-decorate -n1 '--format=format:%H %ct %D' 19c151beeb3cc60f3031024cd4a914967db73cf2 --
0.002s # cd /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949; git -c log.showsignature=false log --no-decorate -n1 '--format=format:%H %ct %D' 19c151beeb3cc60f3031024cd4a914967db73cf2 --
cd /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949; git for-each-ref --format %(refname) refs/tags --merged 19c151beeb3cc60f3031024cd4a914967db73cf2
0.001s # cd /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949; git for-each-ref --format %(refname) refs/tags --merged 19c151beeb3cc60f3031024cd4a914967db73cf2
cd /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949; git -c log.showsignature=false log --no-decorate -n1 '--format=format:%H %ct %D' 19c151beeb3c --
0.001s # cd /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949; git -c log.showsignature=false log --no-decorate -n1 '--format=format:%H %ct %D' 19c151beeb3c --
cd /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949; git for-each-ref --format %(refname) refs/tags --merged 19c151beeb3cc60f3031024cd4a914967db73cf2
0.001s # cd /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949; git for-each-ref --format %(refname) refs/tags --merged 19c151beeb3cc60f3031024cd4a914967db73cf2
cd /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949; git cat-file blob 19c151beeb3cc60f3031024cd4a914967db73cf2:quit/go.mod
0.001s # cd /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949; git cat-file blob 19c151beeb3cc60f3031024cd4a914967db73cf2:quit/go.mod
cd /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949; git cat-file blob 19c151beeb3cc60f3031024cd4a914967db73cf2:go.mod
0.001s # cd /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949; git cat-file blob 19c151beeb3cc60f3031024cd4a914967db73cf2:go.mod
panic: internal error: net token acquired but not released

goroutine 5 [running]:
cmd/go/internal/base.(*netTokenChecker).panicUnreleased(0x0?)
	cmd/go/internal/base/limit.go:83 +0x25
mikewang@VM-24-16-ubuntu:~/go_w/goodsfamily/gis-comp$

**Comment by it512** [comment]
mikewang@VM-24-16-ubuntu:~/go_w/goodsfamily/gis-comp$ cat ~/.gitconfig 

[user]
	email = it512@msn.com
	name = it512
[url "https://root:****@gitlab.***.com/"] ----------------- use https 
	insteadOf = https://gitlab.***com/

and run go get -x 
-------------------------------------------

# get https://gitlab.it9i.com/?go-get=1
# get https://gitlab.it9i.com/comp/psdk?go-get=1
# get https://gitlab.it9i.com/comp/psdk/quit?go-get=1
# get https://gitlab.it9i.com/comp?go-get=1
# get https://gitlab.it9i.com/comp/psdk/quit?go-get=1: 200 OK (1.263s)
# get https://gitlab.it9i.com/comp/psdk?go-get=1
# get https://gitlab.it9i.com/?go-get=1: Get "http://gitlab.it9i.com/users/sign_in": redirected from secure URL https://gitlab.it9i.com/?go-get=1 to insecure URL http://gitlab.it9i.com/users/sign_in
# get https://gitlab.it9i.com/comp?go-get=1: Get "http://gitlab.it9i.com/users/sign_in": redirected from secure URL https://gitlab.it9i.com/comp?go-get=1 to insecure URL http://gitlab.it9i.com/users/sign_in
# get https://gitlab.it9i.com/comp/psdk?go-get=1: 200 OK (1.564s)
mkdir -p /home/mikewang/go/pkg/mod/cache/vcs # git3 http://gitlab.it9i.com/comp/psdk.git
# lock /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949.lock
# /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949 for git3 http://gitlab.it9i.com/comp/psdk.git
cd /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949; git ls-remote -q origin
# get https://gitlab.it9i.com/comp/psdk?go-get=1: 200 OK (0.337s)
3.832s # cd /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949; git ls-remote -q origin
cd /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949; git -c log.showsignature=false log --no-decorate -n1 '--format=format:%H %ct %D' 19c151beeb3cc60f3031024cd4a914967db73cf2 --
0.002s # cd /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949; git -c log.showsignature=false log --no-decorate -n1 '--format=format:%H %ct %D' 19c151beeb3cc60f3031024cd4a914967db73cf2 --
cd /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949; git for-each-ref --format %(refname) refs/tags --merged 19c151beeb3cc60f3031024cd4a914967db73cf2
0.001s # cd /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949; git for-each-ref --format %(refname) refs/tags --merged 19c151beeb3cc60f3031024cd4a914967db73cf2
cd /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949; git -c log.showsignature=false log --no-decorate -n1 '--format=format:%H %ct %D' 19c151beeb3c --
0.001s # cd /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949; git -c log.showsignature=false log --no-decorate -n1 '--format=format:%H %ct %D' 19c151beeb3c --
cd /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949; git for-each-ref --format %(refname) refs/tags --merged 19c151beeb3cc60f3031024cd4a914967db73cf2
0.001s # cd /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949; git for-each-ref --format %(refname) refs/tags --merged 19c151beeb3cc60f3031024cd4a914967db73cf2
cd /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949; git cat-file blob 19c151beeb3cc60f3031024cd4a914967db73cf2:quit/go.mod
0.001s # cd /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949; git cat-file blob 19c151beeb3cc60f3031024cd4a914967db73cf2:quit/go.mod
cd /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949; git cat-file blob 19c151beeb3cc60f3031024cd4a914967db73cf2:go.mod
0.001s # cd /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949; git cat-file blob 19c151beeb3cc60f3031024cd4a914967db73cf2:go.mod
go: downloading gitlab.it9i.com/comp/psdk v0.0.0-20230808164723-19c151beeb3c
cd /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949; git cat-file blob 19c151beeb3cc60f3031024cd4a914967db73cf2:go.mod
0.001s # cd /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949; git cat-file blob 19c151beeb3cc60f3031024cd4a914967db73cf2:go.mod
cd /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949; git cat-file blob 19c151beeb3cc60f3031024cd4a914967db73cf2:go.mod
0.001s # cd /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949; git cat-file blob 19c151beeb3cc60f3031024cd4a914967db73cf2:go.mod
cd /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949; git cat-file blob 19c151beeb3cc60f3031024cd4a914967db73cf2:go.mod
0.001s # cd /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949; git cat-file blob 19c151beeb3cc60f3031024cd4a914967db73cf2:go.mod
cd /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949; git -c core.autocrlf=input -c core.eol=lf archive --format=zip --prefix=prefix/ 19c151beeb3cc60f3031024cd4a914967db73cf2
0.004s # cd /home/mikewang/go/pkg/mod/cache/vcs/4c89efdc50b5b0793d402c976db5dc6d0ddce712c63c60b3865bf20ec452a949; git -c core.autocrlf=input -c core.eol=lf archive --format=zip --prefix=prefix/ 19c151beeb3cc60f3031024cd4a914967db73cf2
panic: internal error: net token acquired but not released

goroutine 5 [running]:
cmd/go/internal/base.(*netTokenChecker).panicUnreleased(0x0?)
	cmd/go/internal/base/limit.go:83 +0x25

**Comment by bcmills** [comment]
@gopherbot, please backport to Go 1.21. This is a regression that triggers an internal error.
