### ISSUE TITLE
cmd/link: -buildmode=shared fails to initialize some global data

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#61973]
Running these commands with tip fails:

```
> go install -buildmode=shared std
> go build -linkshared hello.go
> ./hello
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fad99183f93]

goroutine 1 [running]:
os.(*File).write(...)
	/home/iant/go/src/os/file_posix.go:46
os.(*File).Write(0x0, {0xc000014120?, 0xd, 0x7fad9908a565?})
	/home/iant/go/src/os/file.go:183 +0x53
fmt.Fprintln({0x565428daeb48, 0x0}, {0xc000366720, 0x1, 0x1})
	/home/iant/go/src/fmt/print.go:305 +0x6f
fmt.Println(...)
	/home/iant/go/src/fmt/print.go:314
```

A similar failure occurs if I add

```Go
func init() {
	if os.Stdout == nil {
		panic("os.Stdout is nil")
	}
}
```

to cmd/cgo/internal/testshared/testdata/depBase/dep.go. With that addition, the panic occurs running `go test cmd/cgo/internal/testshared`.

It appears that at least in some cases global variables are not being initialized when using `-buildmode=shared`.

**Comment by mknyszek** [comment]
In triage, Ian said this is a new failure.
