### ISSUE TITLE
cmd/compile: internal compiler error: (...) value ~R0 (v85) incorrectly live at entry

### ISSUE THREAD

**Issue by aarzilli** [golang/go#62211]
```
$ go version
go version devel go1.22-63ab68ddc5 Tue Aug 22 12:05:36 2023 +0000 linux/amd64
```

Building this reproduction program https://go.dev/play/p/DF9uLw2Vrs9?v=gotip results in this internal compiler error:

```
# command-line-arguments
./repro.go:16:6: internal compiler error: 'checkCertCmd': value ~R0 (v85) incorrectly live at entry

goroutine 17 [running]:
runtime/debug.Stack()
        /usr/local/go-tip/src/runtime/debug/stack.go:24 +0x5e
cmd/compile/internal/base.FatalfAt({0x66b368?, 0xc0?}, {0xc000670000, 0x2d}, {0xc0006426c0, 0x3, 0x3})
        /usr/local/go-tip/src/cmd/compile/internal/base/print.go:230 +0x1d7
cmd/compile/internal/base.Fatalf(...)
        /usr/local/go-tip/src/cmd/compile/internal/base/print.go:199
cmd/compile/internal/ssagen.(*ssafn).Fatalf(0x0?, {0x5?, 0x0?}, {0xd85d53, 0x27}, {0xc0006460e0, 0x2, 0xc00066b401?})
        /usr/local/go-tip/src/cmd/compile/internal/ssagen/ssa.go:8012 +0x16a
cmd/compile/internal/ssagen.(*state).Fatalf(0xce2380?, {0xd85d53?, 0xc00059d430?}, {0xc0006460e0?, 0xebf9e8?, 0xc00065a210?})
        /usr/local/go-tip/src/cmd/compile/internal/ssagen/ssa.go:935 +0x67
cmd/compile/internal/ssagen.(*simplePhiState).insertPhis(0xc00066b900)
        /usr/local/go-tip/src/cmd/compile/internal/ssagen/phi.go:486 +0x2a5
cmd/compile/internal/ssagen.(*state).insertPhis(...)
        /usr/local/go-tip/src/cmd/compile/internal/ssagen/phi.go:45
cmd/compile/internal/ssagen.buildssa(0xc000403e40, 0x2)
        /usr/local/go-tip/src/cmd/compile/internal/ssagen/ssa.go:571 +0x2b6b
cmd/compile/internal/ssagen.Compile(0xc000403e40, 0x0?)
        /usr/local/go-tip/src/cmd/compile/internal/ssagen/pgen.go:216 +0x45
cmd/compile/internal/gc.compileFunctions.func5.1(0x0?)
        /usr/local/go-tip/src/cmd/compile/internal/gc/compile.go:186 +0x34
cmd/compile/internal/gc.compileFunctions.func3.1()
        /usr/local/go-tip/src/cmd/compile/internal/gc/compile.go:168 +0x30
created by cmd/compile/internal/gc.compileFunctions.func3 in goroutine 8
        /usr/local/go-tip/src/cmd/compile/internal/gc/compile.go:167 +0x23a
```

**Comment by mdempsky** [comment]
Thanks for the report.

**Comment by mdempsky** [comment]
Simplified test case: https://go.dev/play/p/SPdDcqGaA9C?v=gotip

The issue is the new deadcode elimination identifies `x || true` is always true, and so it prunes:

```
func f() bool {
  if x || true {
    return true
  }
  return true
}
```

into just:

```
func f() bool {
  if x || true {
    return true
  }
  // no return!
}
```

This then causes the inliner to trigger special optimizations for functions with a single "return" statement, which then seems to cause confusion for phi insertion during ssagen, because the result parameter (internally named `~R0`) never gets initialized in the "no return" path, and it can't tell yet that that path isn't actually reachable.
