### ISSUE TITLE
cmd/compile: internal compiler error: panic during expand calls [on ARM and other 32bit archs]

### ISSUE THREAD

**Issue by ALTree** [golang/go#63462]
```
$ gotip version
go version devel go1.22-2744155 Sun Oct 8 23:15:25 2023 +0000 linux/amd64
```
```
package main

import "strings"

func main() {
        for b := "" < strings.Join([]string{}, "") && true; ; {
                _ = b
        }
}
```
```
$ GOARCH=arm gotip build crash.go

# command-line-arguments
./crash.go:6:45: internal compiler error: 'main': panic during expand calls while compiling main:

runtime error: invalid memory address or nil pointer dereference

goroutine 9 [running]:
cmd/compile/internal/ssa.Compile.func1()
        ./gotip/src/cmd/compile/internal/ssa/compile.go:49 +0x6c
panic({0xd31300?, 0x140e500?})
        ./gotip/src/runtime/panic.go:765 +0x132
cmd/compile/internal/ssa.(*Value).AddArgs(...)
        ./gotip/src/cmd/compile/internal/ssa/value.go:313
cmd/compile/internal/ssa.(*expandState).rewriteSelectOrArg.func1(0xc000422780?, 0x0?, {0xc000447158?, 0x2, 0x0?})
        ./gotip/src/cmd/compile/internal/ssa/expand_calls.go:488 +0x13e
cmd/compile/internal/ssa.(*expandState).rewriteSelectOrArg(0xc000447c60, {0x2, 0x61c0}, 0xc00059f3e0, 0xc000568f40, 0x0, 0x0, 0xc000422780, {0xc000569170, 0x0, ...})
        ./gotip/src/cmd/compile/internal/ssa/expand_calls.go:681 +0x17cd

...
```

cc @golang/compiler

**Comment by cuonglm** [comment]
A simple reproducer:

```
package p

func f() {
	for b := "" < join([]string{}, "") && true; ; {
		_ = b
	}
}

//go:noinline
func join(elems []string, sep string) string {
	return ""
}
```

**Comment by cuonglm** [comment]
Related #63433

cc @dr2chase
