### ISSUE TITLE
runtime: TestG0StackOverflow fails on OpenBSD

### ISSUE THREAD

**Issue by mauri870** [golang/go#63794]
https://build.golang.org/log/597e50ab4c5b1e58fa8aa5a05676ecac63aa0668

Started seeing this happening on builds for different CLs:

```
crash_test.go:805: === RUN   TestG0StackOverflow
        SIGSEGV: segmentation violation
        PC=0x477d50 m=0 sigcode=2 addr=0x477d50
        
        goroutine 0 [idle]:
        runtime.switchToCrashStack0()
        	/tmp/workdir/go/src/runtime/asm_amd64.s:559 +0x30 fp=0xb9e530 sp=0xb9e520 pc=0x477d50
        
        goroutine 6 [running]:
        runtime.systemstack_switch()
        	/tmp/workdir/go/src/runtime/asm_amd64.s:474 +0x8 fp=0xc000058670 sp=0xc000058660 pc=0x477c68
        runtime.G0StackOverflow(...)
        	/tmp/workdir/go/src/runtime/export_test.go:691
        runtime_test.TestG0StackOverflow(0xc000164340)
        	/tmp/workdir/go/src/runtime/crash_test.go:824 +0x365 fp=0xc000058770 sp=0xc000058670 pc=0x6fb925
        testing.tRunner(0xc000164340, 0x889ff0)
        	/tmp/workdir/go/src/testing/testing.go:1682 +0xfb fp=0xc0000587c0 sp=0xc000058770 pc=0x502b3b
        testing.(*T).Run.gowrap1()
        	/tmp/workdir/go/src/testing/testing.go:1735 +0x25 fp=0xc0000587e0 sp=0xc0000587c0 pc=0x503aa5
        runtime.goexit({})
        	/tmp/workdir/go/src/runtime/asm_amd64.s:1694 +0x1 fp=0xc0000587e8 sp=0xc0000587e0 pc=0x479ca1
        created by testing.(*T).Run in goroutine 1
        	/tmp/workdir/go/src/testing/testing.go:1735 +0x390
```

**Comment by mauri870** [comment]
attn @golang/openbsd

**Comment by mauri870** [comment]
Should be fixed once [CL 537975](https://go-review.googlesource.com/c/go/+/537975) is merged

**Comment by 4a6f656c** [comment]
[CL#538457](https://go-review.googlesource.com/c/go/+/538457) makes this work on OpenBSD.
