### ISSUE TITLE
fatal error: exitsyscall: syscall frame is no longer valid

### ISSUE THREAD

**Issue by NicoNex** [golang/go#63829]
### What version of Go are you using (`go version`)?
go version go1.21.3 linux/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
```
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/speedking/.cache/go-build'
GOENV='/home/speedking/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/speedking/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/speedking/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/lib/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/lib/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.3'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/speedking/Documenti/goreport/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2363871711=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?
I called `longjmp` from a C function called by a Go function.
To reproduce the crash create three files called `main.go`, `test.c` and `test.h`

#### main.go
```go
package main

// #include "test.h"
import "C"

//export go_stop_loop
func go_stop_loop() {
	C.stop_loop()
}

func main() {
	C.run_loop()
}
```

#### test.c
```c
#include <setjmp.h>
#include "_cgo_export.h"

jmp_buf env;

void stop_loop() {
	longjmp(env, 1);
}

void run_loop() {
	if (setjmp(env) == 1) {
		return;
	}

	for (int i = 0;; i++) {
		if (i == 100) {
			go_stop_loop();
		}
	}
}
```

#### test.h
```c
#pragma once

void run_loop();
void stop_loop();

```

### What did you expect to see?
Nothing.

### What did you see instead?
```
fatal error: exitsyscall: syscall frame is no longer valid

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x45aaf0, 0xc00004c500)
	/usr/lib/go/src/runtime/cgocall.go:157 +0x4b fp=0xc00004c4d8 sp=0xc00004c4a0 pc=0x40490b
main._Cfunc_stop_loop()
	_cgo_gotypes.go:51 +0x3f fp=0xc00004c500 sp=0xc00004c4d8 pc=0x45a9df
main.go_stop_loop(...)
	/home/speedking/Documenti/goreport/main.go:8
_cgoexp_68f9e50c1ad9_go_stop_loop(0x380?)
	_cgo_gotypes.go:61 +0x10 fp=0xc00004c510 sp=0xc00004c500 pc=0x45aa50
runtime.cgocallbackg1(0x45aa40, 0xc0000140e0?, 0x0)
	/usr/lib/go/src/runtime/cgocall.go:329 +0x2c2 fp=0xc00004c5e0 sp=0xc00004c510 pc=0x404e02
runtime.cgocallbackg(0x470b64?, 0x2d?, 0xc00004c6c0?)
	/usr/lib/go/src/runtime/cgocall.go:245 +0x109 fp=0xc00004c670 sp=0xc00004c5e0 pc=0x404aa9
runtime.throw.func1()
	/usr/lib/go/src/runtime/panic.go:1073 fp=0xc00004c678 sp=0xc00004c670 pc=0x42e4e0
runtime: g 1: unexpected return pc for runtime.throw.func1 called from 0x470b64
stack: frame={sp:0xc00004c670, fp:0xc00004c678} stack=[0xc00004c000,0xc00004c800)
0x000000c00004c570:  0x0000000000000010  0x000000c0000061a0 
0x000000c00004c580:  0x000000c00004c568  0x00007fff5aa30847 
0x000000c00004c590:  0x0000000000404ec0 <runtime.cgocallbackg1.func3+0x0000000000000000>  0x000000c00004c555 
0x000000c00004c5a0:  0x000000c0000061a0  0x0000000200000003 
0x000000c00004c5b0:  0x000000c0000061a0  0x000000c00004c590 
0x000000c00004c5c0:  0x0000000000000000  0x0000000000471eb8 
0x000000c00004c5d0:  0x000000c00004c660  0x0000000000404aa9 <runtime.cgocallbackg+0x0000000000000109> 
0x000000c00004c5e0:  0x000000000045aa40 <_cgoexp_68f9e50c1ad9_go_stop_loop+0x0000000000000000>  0x000000c0000140e0 
0x000000c00004c5f0:  0x0000000000000000  0x000000000040490b <runtime.cgocall+0x000000000000004b> 
0x000000c00004c600:  0x0000000000000000  0x00000000004565f2 <runtime.systemstack+0x0000000000000032> 
0x000000c00004c610:  0x000000c00004c650  0x000000000042e7c5 <runtime.fatalthrow+0x0000000000000065> 
0x000000c00004c620:  0x000000c00004c630  0x000000c0000061a0 
0x000000c00004c630:  0x000000000042e800 <runtime.fatalthrow.func1+0x0000000000000000>  0x000000c0000061a0 
0x000000c00004c640:  0x000000000042e4bc <runtime.throw+0x000000000000005c>  0x000000c00004c660 
0x000000c00004c650:  0x000000c00004c680  0x000000000042e4bc <runtime.throw+0x000000000000005c> 
0x000000c00004c660:  0x000000c00004c668  0x000000000042e4e0 <runtime.throw.func1+0x0000000000000000> 
0x000000c00004c670: <0x0000000000470b64 >0x000000000000002d 
0x000000c00004c680:  0x000000c00004c6c0  0x000000000045537e <runtime.exitsyscall+0x000000000000025e> 
0x000000c00004c690:  0x0000000000470b64  0x000000000045aa40 <_cgoexp_68f9e50c1ad9_go_stop_loop+0x0000000000000000> 
0x000000c00004c6a0:  0x00007fff5aa30847  0x0000000000000000 
0x000000c00004c6b0:  0x000000000040490b <runtime.cgocall+0x000000000000004b>  0x00000000004565a8 <runtime.systemstack_switch+0x0000000000000008> 
0x000000c00004c6c0:  0x000000c00004c6f8  0x0000000000404965 <runtime.cgocall+0x00000000000000a5> 
0x000000c00004c6d0:  0x000000000045aae0  0x000000c00004c730 
0x000000c00004c6e0:  0x0000000000000001  0x000000010040490b 
0x000000c00004c6f0:  0x00000000004d4f40  0x000000c00004c720 
0x000000c00004c700:  0x000000000045a97f <main._Cfunc_run_loop+0x000000000000003f>  0x000000000045aae0 
0x000000c00004c710:  0x000000c00004c730  0x000000c00004c730 
0x000000c00004c720:  0x000000c00004c730  0x000000000045aa0f <main.main+0x000000000000000f> 
0x000000c00004c730:  0x000000c00004c7d0  0x0000000000430e9b <runtime.main+0x00000000000002bb> 
0x000000c00004c740:  0x000000c00001c120  0x0000000000000000 
0x000000c00004c750:  0x0000000000000000  0x0000000000000000 
0x000000c00004c760:  0x0100000000000000  0x0000000000000001 
0x000000c00004c770:  0x0000000000000005 

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc00004cfa8 sp=0xc00004cf88 pc=0x4312ee
runtime.goparkunlock(...)
	/usr/lib/go/src/runtime/proc.go:404
runtime.forcegchelper()
	/usr/lib/go/src/runtime/proc.go:322 +0xb3 fp=0xc00004cfe0 sp=0xc00004cfa8 pc=0x431173
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00004cfe8 sp=0xc00004cfe0 pc=0x456b21
created by runtime.init.6 in goroutine 1
	/usr/lib/go/src/runtime/proc.go:310 +0x1a

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc00004d778 sp=0xc00004d758 pc=0x4312ee
runtime.goparkunlock(...)
	/usr/lib/go/src/runtime/proc.go:404
runtime.bgsweep(0x0?)
	/usr/lib/go/src/runtime/mgcsweep.go:280 +0x94 fp=0xc00004d7c8 sp=0xc00004d778 pc=0x41e814
runtime.gcenable.func1()
	/usr/lib/go/src/runtime/mgc.go:200 +0x25 fp=0xc00004d7e0 sp=0xc00004d7c8 pc=0x413ba5
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00004d7e8 sp=0xc00004d7e0 pc=0x456b21
created by runtime.gcenable in goroutine 1
	/usr/lib/go/src/runtime/mgc.go:200 +0x66

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000076000?, 0x4833d0?, 0x1?, 0x0?, 0xc0000071e0?)
	/usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc00004df70 sp=0xc00004df50 pc=0x4312ee
runtime.goparkunlock(...)
	/usr/lib/go/src/runtime/proc.go:404
runtime.(*scavengerState).park(0x4d4ac0)
	/usr/lib/go/src/runtime/mgcscavenge.go:425 +0x49 fp=0xc00004dfa0 sp=0xc00004df70 pc=0x41c0a9
runtime.bgscavenge(0x0?)
	/usr/lib/go/src/runtime/mgcscavenge.go:653 +0x3c fp=0xc00004dfc8 sp=0xc00004dfa0 pc=0x41c63c
runtime.gcenable.func2()
	/usr/lib/go/src/runtime/mgc.go:201 +0x25 fp=0xc00004dfe0 sp=0xc00004dfc8 pc=0x413b45
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00004dfe8 sp=0xc00004dfe0 pc=0x456b21
created by runtime.gcenable in goroutine 1
	/usr/lib/go/src/runtime/mgc.go:201 +0xa5
```

**Comment by cherrymui** [comment]
Thanks for the issue. But changing the stack like using `longjmp` while we have Go frames on the stack is not supported. Thanks.

**Comment by NicoNex** [comment]
> Thanks for the issue. But changing the stack like using `longjmp` while we have Go frames on the stack is not supported. Thanks.

Is there any way to avoid this crash? Unfortunately I cannot avoid using `longjmp` in my project.

**Comment by cherrymui** [comment]
You can use longjmp that is not visible to Go, e.g. on a stack that doesn't have any Go frames, or within one cgo call that doesn't call back into Go.
