### ISSUE TITLE
x/tools/gopls: panic with 'instantiated ident not found'

### ISSUE THREAD

**Issue by ForrestLinjianLi** [golang/go#63933]
gopls version: v0.14.1 (go1.21.3)
gopls flags: 
update flags: proxy
extension version: 0.39.1
go version: 1.21.3
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Fri, 03 Nov 2023 00:14:18 GMT
restart history:
Thu, 02 Nov 2023 19:11:31 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: instantiated ident not found

goroutine 9211 [running]:
go/types.(*Checker).handleBailout(0xc0002c9a40, 0xc006ff3578)
	  check.go:336  0x88
panic({0xdfb3c0%3F, 0x1220aa0%3F})
	  panic.go:914  0x21f
go/types.instantiatedIdent(...)
	  check.go:594
go/types.(*Checker).recordInstance(0x0%3F, {0x12292c0%3F, 0xc00af28dc0%3F}, {0xc00a09bca0%3F, 0xc00a09bca0%3F, 0x1%3F}, {0x1225f68%3F, 0xc0010c7740%3F})
	  check.go:570  0x1de
go/types.(*Checker).instantiateSignature(0xc0002c9a40, 0x17af6, {0x12292c0, 0xc00af28dc0}, 0xc0010c7700, {0xc00a09bca0, 0x1, 0x1}, {0x0, 0x0, ...})
	  call.go:153  0x2f9
go/types.(*Checker).arguments(0xc0002c9a40, 0xc00af28e40, 0xc0010137c0, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, {0xc00c013350, ...}, ...)
	  call.go:635  0x15ea
go/types.(*Checker).callExpr(0xc0002c9a40, 0xc0010c7580, 0xc00af28e40)
	  call.go:302  0x86d
go/types.(*Checker).exprInternal(0xc0002c9a40, {0x0, 0x0}, 0xc0010c7580, {0x12292c0, 0xc00af28e40%3F}, {0x0%3F, 0x0%3F})
	  expr.go:1359  0x1809
go/types.(*Checker).rawExpr(0xc0002c9a40, {0x0, 0x0}, 0xc0010c7580, {0x12292c0%3F, 0xc00af28e40%3F}, {0x0%3F, 0x0%3F}, 0x0)
	  expr.go:965  0x1a5
go/types.(*Checker).multiExpr(0x678185%3F, {0x12292c0%3F, 0xc00af28e40}, 0x1)
	  expr.go:1517  0x85
go/types.(*Checker).initVars(0xe42ae0%3F, {0xc00a09bc20%3F, 0x2, 0x2}, {0xc00b705e20%3F, 0x1, 0x1}, {0x0, 0x0})
	  assignments.go:398  0x12c
go/types.(*Checker).shortVarDecl(0xc0002c9a40, {0x1223680, 0xc000aa3908}, {0xc008d696c0, 0x2, 0xc00af28800%3F}, {0xc00b705e20%3F, 0x1, 0x1})
	  assignments.go:546  0xbce
go/types.(*Checker).stmt(0xc0002c9a40, 0x0, {0x12293e0%3F, 0xc00af28e80%3F})
	  stmt.go:476  0xee5
go/types.(*Checker).stmtList(0xc0002c9a40%3F, 0x0, {0xc000faf900%3F, 0x0%3F, 0x120%3F})
	  stmt.go:124  0x85
go/types.(*Checker).funcBody(0xc0002c9a40, 0xc00b57ade0, {0xc00084a330%3F, 0xc000180c80%3F}, 0xc0010c4c40, 0xc000a92810, {0x0, 0x0})
	  stmt.go:44  0x345
go/types.(*Checker).funcDecl.func1()
	  decl.go:826  0x39
go/types.(*Checker).processDelayed(0xc0002c9a40, 0x0)
	  check.go:439  0x15c
go/types.(*Checker).checkFiles(0xc0002c9a40, {0xc00b3c7990, 0x1, 0x1})
	  check.go:383  0x245
go/types.(*Checker).Files(...)
	  check.go:341
golang.org/x/tools/gopls/internal/lsp/cache.doTypeCheck({0x122ae08, 0xc001fe30b0}, 0xc007d7fe60, {{0xc0006cd3b0, 0x43}, {0xc0006cd3b0, 0x43}, {0xc001652a88, 0x4}, {0xc00a9e1c40, ...}, ...})
	  check.go:1562  0x8a5
golang.org/x/tools/gopls/internal/lsp/cache.typeCheckImpl({0x122ae08, 0xc001fe2f30}, 0xc000d9a060%3F, {{0xc0006cd3b0, 0x43}, {0xc0006cd3b0, 0x43}, {0xc001652a88, 0x4}, {0xc00a9e1c40, ...}, ...})
	  check.go:1420  0x205
golang.org/x/tools/gopls/internal/lsp/cache.(*typeCheckBatch).checkPackage(0xc00a309ed8%3F, {0x122ae08, 0xc0007dcab0}, 0xc00c022a20)
	  check.go:674  0x245
golang.org/x/tools/gopls/internal/lsp/cache.(*typeCheckBatch).handleSyntaxPackage(0xc007d7fe60, {0x122ae08, 0xc0007dcab0}, 0xc0080e9e30%3F, {0xc0006cd3b0, 0x43})
	  check.go:532  0x42a
golang.org/x/tools/gopls/internal/lsp/cache.(*snapshot).forEachPackageInternal.func2()
	  check.go:394  0x2b
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:75  0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 720
	  errgroup.go:72  0x96
[Error - 5:14:09 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by adonovan** [comment]
The stack indicates that a call f(g), where g itself has a generic function type, was instantiated, and the syntax of g was found not to be one of the following forms: `id`, pkg.F`, `F[T]`, `pkg.F[T]`, `F[T, T2]`, `pkg.F[T, T2].

I wonder whether it's possible that g was an anonymous function (FuncLit)? A better panic message would help.

Paging go/types experts @findleyr, @gri.

**Comment by adonovan** [comment]
Let's reopen this as we're waiting for information from crash reports from the field, and that could take several weeks.

**Comment by findleyr** [comment]
> Let's reopen this as we're waiting for information from crash reports from the field, and that could take several weeks.

We probably won't get more data on this until the v0.15.0-pre.1 prerelease. But yes, this is definitely a real bug (albeit rare) as we've seen this in a couple google internal reports as well. Still need more info to diagnose.

**Comment by findleyr** [comment]
Repro'ed successfully (!) in https://github.com/golang/vscode-go/issues/3114, thanks to @szesch's https://github.com/szesch/go-63933.

Notably, this reproduces at go1.21.5, but not at master, so it may have been fixed. Investigating the root cause and bisecting the fix.

**Comment by findleyr** [comment]
This bug was inadvertently fixed in https://go.dev/cl/543176, though the root cause is addressed in https://go.dev/cl/554395.

This was a latent bug that was activated by reverse type inference in Go 1.21. Since it will be fixed by Go 1.22, I don't think we need to back-port.

**Comment by findleyr** [comment]
Moved this to the Go 1.23 milestone, since it's not directly a gopls bug, it's already mitigated in 1.22, and we're not going to back-port the fix.
