### ISSUE TITLE
cmd/go: cannot compile tip on Mac, panic: godebug: Value of name not listed in godebugs.All: gotypesalias

### ISSUE THREAD

**Issue by kevinburke** [golang/go#64106]
### What version of Go are you using (`go version`)?

I'm attempting to compile commit 7a6ddbb425218b2f4866478d0c673ba82c8438e6 on Mac with an ARM chip using Go 1.21.4 as a bootstrap.

### Does this issue reproduce with the latest release?

No

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/kburke/Library/Caches/go-build'
GOENV='/Users/kburke/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/kburke/pkg/mod'
GONOPROXY='github.com/segmentio'
GONOSUMDB='github.com/segmentio'
GOOS='darwin'
GOPATH='/Users/kburke'
GOPRIVATE='github.com/segmentio'
GOPROXY='direct'
GOROOT='/Users/kburke/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/Users/kburke/go/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='devel go1.22-0ccbf6306c Tue Nov 7 17:27:06 2023 +0000'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD=''
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/9s/w0d5_1fx71j5f225g95vtx340000gn/T/go-build73708175=/tmp/go-build -gno-record-gcc-switches -fno-common'
</pre></details>

### What did you do?

Run `GOROOT_BOOTSTRAP="${HOME}/go1.21" ./make.bash`

### What did you expect to see?

Compiled Go tip.

### What did you see instead?

The following panic (timestamps were added by github.com/kevinburke/tss and measure time since the last line of output).

go tool dist: FAILED: /Users/kburke/go/pkg/tool/darwin_arm64/compile -std -pack -o /var/folders/9s/w0d5_1fx71j5f225g95vtx340000gn/T/go-tool-dist-3514003405/internal/godebugs/_go_.a -p internal/godebugs -importcfg /var/folders/9s/w0d5_1fx71j5f225g95vtx340000gn/T/go-tool-dist-3514003405/internal/godebugs/importcfg /Users/kburke/go/src/internal/godebugs/table.go: exit status 2
  12.32s  341.7ms <unknown line number>: internal compiler error: panic: godebug: Value of name not listed in godebugs.All: gotypesalias
  12.32s    0.0ms
  12.32s    0.0ms goroutine 1 [running]:
  12.32s    0.0ms runtime/debug.Stack()
  12.32s    0.0ms 	/Users/kburke/go/src/runtime/debug/stack.go:24 +0x64
  12.32s    0.0ms bootstrap/cmd/compile/internal/base.FatalfAt({0x1d0d98?, 0x140?}, {0x104b285b7, 0x9}, {0x140001d0d18, 0x1, 0x1})
  12.32s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/base/print.go:225 +0x1fc
  12.32s    0.0ms bootstrap/cmd/compile/internal/base.Fatalf(...)
  12.32s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/base/print.go:194
  12.32s    0.0ms bootstrap/cmd/compile/internal/gc.handlePanic()
  12.32s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/gc/main.go:52 +0x90
  12.32s    0.0ms panic({0x104c86a60?, 0x14000120b20?})
  12.32s    0.0ms 	/Users/kburke/go/src/runtime/panic.go:914 +0x218
  12.32s    0.0ms internal/godebug.(*Setting).Value.func1()
  12.32s    0.0ms 	/Users/kburke/go/src/internal/godebug/godebug.go:141 +0xd8
  12.32s    0.0ms sync.(*Once).doSlow(0x140001d0f88?, 0x104a42c84?)
  12.32s    0.0ms 	/Users/kburke/go/src/sync/once.go:74 +0x100
  12.32s    0.0ms sync.(*Once).Do(...)
  12.32s    0.0ms 	/Users/kburke/go/src/sync/once.go:65
  12.32s    0.0ms internal/godebug.(*Setting).Value(0x1051292a0)
  12.32s    0.0ms 	/Users/kburke/go/src/internal/godebug/godebug.go:138 +0x50
  12.32s    0.0ms bootstrap/cmd/compile/internal/types2.NewChecker(0x16b91a95a?, 0x1400044b1a0, 0x0?)
  12.32s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/types2/check.go:259 +0x60
  12.32s    0.0ms bootstrap/cmd/compile/internal/types2.(*Config).Check(0x104caa400?, {0x16b91a95a?, 0x1400000e0b7?}, {0x14000122558, 0x1, 0x1}, 0x140001d1088?)
  12.32s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/types2/api.go:461 +0x58
  12.32s    0.0ms bootstrap/cmd/compile/internal/noder.checkFiles({0x0, {0x0, 0x0}}, {0x140001224f8, 0x1, 0x104c7eda0?})
  12.32s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/noder/irgen.go:88 +0x49c
  12.32s    0.0ms bootstrap/cmd/compile/internal/noder.writePkgStub({0x0?, {0x0?, 0x0?}}, {0x140001224f8, 0x1, 0x1})
  12.32s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/noder/unified.go:296 +0x48
  12.32s    0.0ms bootstrap/cmd/compile/internal/noder.unified({0x0?, {0x0?, 0x0?}}, {0x140001224f8?, 0x104c75f00?, 0x0?})
  12.32s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/noder/unified.go:172 +0x98
  12.32s    0.0ms bootstrap/cmd/compile/internal/noder.LoadPackage({0x14000126130, 0x1, 0x1})
  12.32s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/noder/noder.go:77 +0x3ac
  12.32s    0.0ms bootstrap/cmd/compile/internal/gc.Main(0x104d27a20)
  12.32s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/gc/main.go:197 +0xb08
  12.32s    0.0ms main.main()
  12.32s    0.0ms 	/Users/kburke/go/src/cmd/compile/main.go:57 +0x110
  12.32s    0.0ms
  12.32s    0.0ms
go tool dist: FAILED: /Users/kburke/go/pkg/tool/darwin_arm64/compile -std -pack -o /var/folders/9s/w0d5_1fx71j5f225g95vtx340000gn/T/go-tool-dist-3514003405/internal/coverage/rtcov/_go_.a -p internal/coverage/rtcov -importcfg /var/folders/9s/w0d5_1fx71j5f225g95vtx340000gn/T/go-tool-dist-3514003405/internal/coverage/rtcov/importcfg /Users/kburke/go/src/internal/coverage/rtcov/rtcov.go: exit status 2
go tool dist: FAILED: /Users/kburke/go/pkg/tool/darwin_arm64/compile -std -pack -o /var/folders/9s/w0d5_1fx71j5f225g95vtx340000gn/T/go-tool-dist-3514003405/internal/goarch/_go_.a -p internal/goarch -importcfg /var/folders/9s/w0d5_1fx71j5f225g95vtx340000gn/T/go-tool-dist-3514003405/internal/goarch/importcfg /Users/kburke/go/src/internal/goarch/goarch.go /Users/kburke/go/src/internal/goarch/goarch_arm64.go /Users/kburke/go/src/internal/goarch/zgoarch_arm64.go: exit status 2
  12.32s    0.2ms <unknown line number>: internal compiler error: panic: godebug: Value of name not listed in godebugs.All: gotypesalias
  12.32s    0.0ms
  12.32s    0.0ms goroutine 1 [running]:
  12.32s    0.0ms runtime/debug.Stack()
  12.32s    0.0ms 	/Users/kburke/go/src/runtime/debug/stack.go:24 +0x64
  12.32s    0.0ms bootstrap/cmd/compile/internal/base.FatalfAt({0x158d98?, 0x140?}, {0x102bf45b7, 0x9}, {0x14000158d18, 0x1, 0x1})
  12.32s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/base/print.go:225 +0x1fc
  12.32s    0.0ms bootstrap/cmd/compile/internal/base.Fatalf(...)
  12.32s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/base/print.go:194
  12.32s    0.0ms bootstrap/cmd/compile/internal/gc.handlePanic()
  12.32s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/gc/main.go:52 +0x90
  12.32s    0.0ms panic({0x102d52a60?, 0x1400008e920?})
  12.32s    0.0ms 	/Users/kburke/go/src/runtime/panic.go:914 +0x218
  12.32s    0.0ms internal/godebug.(*Setting).Value.func1()
  12.32s    0.0ms 	/Users/kburke/go/src/internal/godebug/godebug.go:141 +0xd8
  12.32s    0.0ms sync.(*Once).doSlow(0x14000158f88?, 0x102b0ec84?)
  12.32s    0.0ms 	/Users/kburke/go/src/sync/once.go:74 +0x100
  12.32s    0.0ms sync.(*Once).Do(...)
  12.32s    0.0ms 	/Users/kburke/go/src/sync/once.go:65
  12.32s    0.0ms internal/godebug.(*Setting).Value(0x1031f52a0)
  12.32s    0.0ms 	/Users/kburke/go/src/internal/godebug/godebug.go:138 +0x50
  12.32s    0.0ms bootstrap/cmd/compile/internal/types2.NewChecker(0x16d84e940?, 0x140003a1aa0, 0x0?)
  12.32s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/types2/check.go:259 +0x60
  12.32s    0.0ms bootstrap/cmd/compile/internal/types2.(*Config).Check(0x102d76400?, {0x16d84e940?, 0x1400000e0b7?}, {0x140000b6548, 0x1, 0x1}, 0x14000159088?)
  12.32s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/types2/api.go:461 +0x58
  12.32s    0.0ms bootstrap/cmd/compile/internal/noder.checkFiles({0x0, {0x0, 0x0}}, {0x140000b64d8, 0x1, 0x102d4ada0?})
  12.32s    0.0msgo tool dist: FAILED: /Users/kburke/go/pkg/tool/darwin_arm64/compile -std -pack -o /var/folders/9s/w0d5_1fx71j5f225g95vtx340000gn/T/go-tool-dist-3514003405/internal/goos/_go_.a -p internal/goos -importcfg /var/folders/9s/w0d5_1fx71j5f225g95vtx340000gn/T/go-tool-dist-3514003405/internal/goos/importcfg /Users/kburke/go/src/internal/goos/goos.go /Users/kburke/go/src/internal/goos/unix.go /Users/kburke/go/src/internal/goos/zgoos_darwin.go: exit status 2
 	/Users/kburke/go/src/cmd/compile/internal/noder/irgen.go:88 +0x49c
  12.32s    0.0ms bootstrap/cmd/compile/internal/noder.writePkgStub({0x0?, {0x0?, 0x0?}}, {0x140000b64d8, 0x1, 0x1})
  12.32s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/noder/unified.go:296 +0x48
  12.32s    0.0ms bootstrap/cmd/compile/internal/noder.unified({0x0?, {0x0?, 0x0?}}, {0x140000b64d8?, 0x102d41f00?, 0x0?})
  12.32s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/noder/unified.go:172 +0x98
  12.32s    0.0ms bootstrap/cmd/compile/internal/noder.LoadPackage({0x140000ba130, 0x1, 0x1})
  12.32s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/noder/noder.go:77 +0x3ac
  12.32s    0.0ms bootstrap/cmd/compile/internal/gc.Main(0x102df3a20)
  12.32s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/gc/main.go:197 +0xb08
  12.32s    0.0ms main.main()
  12.32s    0.0ms 	/Users/kburke/go/src/cmd/compile/main.go:57 +0x110
  12.32s    0.0ms
  12.32s    0.0ms
  12.33s    0.3ms <unknown line number>: internal compiler error: panic: godebug: Value of name not listed in godebugs.All: gotypesalias
  12.33s    0.0ms
  12.33s    0.0ms goroutine 1 [running]:
  12.33s    0.0ms runtime/debug.Stack()
  12.33s    0.0ms 	/Users/kburke/go/src/runtime/debug/stack.go:24 +0x64
  12.33s    0.0ms bootstrap/cmd/compile/internal/base.FatalfAt({0x38ed98?, 0x140?}, {0x1011845b7, 0x9}, {0x1400038ed18, 0x1, 0x1})
  12.33s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/base/print.go:225 +0x1fc
  12.33s    0.0ms bootstrap/cmd/compile/internal/base.Fatalf(...)
  12.33s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/base/print.go:194
  12.33s    0.0ms bootstrap/cmd/compile/internal/gc.handlePanic()
  12.33s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/gc/main.go:52 +0x90
  12.33s    0.0ms panic({0x1012e2a60?, 0x140000940a0?})
  12.33s    0.0ms 	/Users/kburke/go/src/runtime/panic.go:914 +0x218
  12.33s    0.0ms internal/godebug.(*Setting).Value.func1()
  12.33s    0.0ms 	/Users/kburke/go/src/internal/godebug/godebug.go:141 +0xd8
  12.33s    0.0ms sync.(*Once).doSlow(0x1400038ef88?, 0x10109ec84?)
  12.33s    0.0ms 	/Users/kburke/go/src/sync/once.go:74 +0x100
  12.33s    0.0ms sync.(*Once).Do(...)
  12.33s    0.0ms 	/Users/kburke/go/src/sync/once.go:65
  12.33s    0.0ms internal/godebug.(*Setting).Value(0x1017852a0)
  12.33s    0.0ms 	/Users/kburke/go/src/internal/godebug/godebug.go:138 +0x50
  12.33s    0.0ms bootstrap/cmd/compile/internal/types2.NewChecker(0x16f2be8f8?, 0x14000092de0, 0x0?)
  12.33s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/types2/check.go:259 +0x60
  12.33s    0.0ms bootstrap/cmd/compile/internal/types2.(*Config).Check(0x101306400?, {0x16f2be8f8?, 0x1400000e0b7?}, {0x14000098060, 0x3, 0x3}, 0x1400038f088?)
  12.33s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/types2/api.go:461 +0x58
  12.33s    0.0ms bootstrap/cmd/compile/internal/noder.checkFiles({0x0, {0x0, 0x0}}, {0x14000412468, 0x3, 0x1012dada0?})
  12.33s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/noder/irgen.go:88 +0x49c
  12.33s    0.0ms bootstrap/cmd/compile/internal/noder.writePkgStub({0x0?, {0x0?, 0x0?}}, {0x14000412468, 0x3, 0x3})
  12.33s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/noder/unified.go:296 +0x48
  12.33s    0.0ms bootstrap/cmd/compile/internal/noder.unified({0x0?, {0x0?, 0x0?}}, {0x14000412468?, 0x1012d1f00?, 0x0?})
  12.33s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/noder/unified.go:172 +0x98
  12.33s    0.0ms bootstrap/cmd/compile/internal/noder.LoadPackage({0x1400001e150, 0x3, 0x3})
  12.33s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/noder/noder.go:77 +0x3ac
  12.33s    0.0ms bootstrap/cmd/compile/internal/gc.Main(0x101383a20)
  12.33s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/gc/main.go:197 +0xb08
  12.33s    0.0ms main.main()
  12.33s    0.0ms 	/Users/kburke/go/src/cmd/compile/main.go:57 +0x110
  12.33s    0.0ms
  12.33s    0.0ms
  12.33s    0.0ms <unknown line number>: internal compiler error: panic: godebug: Value of name not listed in godebugs.All: gotypesalias
  12.33s    0.0ms
  12.33s    0.0ms goroutine 1 [running]:
  12.33s    0.0ms runtime/debug.Stack()
  12.33s    0.0ms 	/Users/kburke/go/src/runtime/debug/stack.go:24 +0x64
  12.33s    0.0ms bootstrap/cmd/compile/internal/base.FatalfAt({0x158d98?, 0x140?}, {0x1029885b7, 0x9}, {0x14000158d18, 0x1, 0x1})
  12.33s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/base/print.go:225 +0x1fc
  12.33s    0.0ms bootstrap/cmd/compile/internal/base.Fatalf(...)
  12.33s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/base/print.go:194
  12.33s    0.0ms bootstrap/cmd/compile/internal/gc.handlePanic()
  12.33s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/gc/main.go:52 +0x90
  12.33s    0.0ms panic({0x102ae6a60?, 0x140000360a0?})
  12.33s    0.0ms 	/Users/kburke/go/src/runtime/panic.go:914 +0x218
  12.33s    0.0ms internal/godebug.(*Setting).Value.func1()
  12.33s    0.0ms 	/Users/kburke/go/src/internal/godebug/godebug.go:141 +0xd8
  12.33s    0.0ms sync.(*Once).doSlow(0x14000158f88?, 0x1028a2c84?)
  12.33s    0.0ms 	/Users/kburke/go/src/sync/once.go:74 +0x100
  12.33s    0.0ms sync.(*Once).Do(...)
  12.33s    0.0ms 	/Users/kburke/go/src/sync/once.go:65
  12.33s    0.0ms internal/godebug.(*Setting).Value(0x102f892a0)
  12.33s    0.0ms 	/Users/kburke/go/src/internal/godebug/godebug.go:138 +0x50
  12.33s    0.0ms bootstrap/cmd/compile/internal/types2.NewChecker(0x16daba906?, 0x1400007c180, 0x0?)
  12.33s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/types2/check.go:259 +0x60
  12.33s    0.0ms bootstrap/cmd/compile/internal/types2.(*Config).Check(0x102b0a400?, {0x16daba906?, 0x1400000e0b7?}, {0x1400000c078, 0x3, 0x3}, 0x14000159088?)
  12.33s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/types2/api.go:461 +0x58
  12.33s    0.0ms bootstrap/cmd/compile/internal/noder.checkFiles({0x0, {0x0, 0x0}}, {0x140003c4450, 0x3, 0x102adeda0?})
  12.33s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/noder/irgen.go:88 +0x49c
  12.33s    0.0ms bootstrap/cmd/compile/internal/noder.writePkgStub({0x0?, {0x0?, 0x0?}}, {0x140003c4450, 0x3, 0x3})
  12.33s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/noder/unified.go:296 +0x48
  12.33s    0.0ms bootstrap/cmd/compile/internal/noder.unified({0x0?, {0x0?, 0x0?}}, {0x140003c4450?, 0x102ad5f00?, 0x0?})
  12.33s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/noder/unified.go:172 +0x98
  12.33s    0.0ms bootstrap/cmd/compile/internal/noder.LoadPackage({0x140000d0090, 0x3, 0x3})
  12.33s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/noder/noder.go:77 +0x3ac
  12.33s    0.0ms bootstrap/cmd/compile/internal/gc.Main(0x102b87a20)
  12.33s    0.0ms 	/Users/kburke/go/src/cmd/compile/internal/gc/main.go:197 +0xb08
  12.33s    0.0ms main.main()
  12.33s    0.0ms 	/Users/kburke/go/src/cmd/compile/main.go:57 +0x110
  12.33s    0.0ms
  12.33s    0.0ms

**Comment by prattmic** [comment]
cc @golang/compiler @griesemer

**Comment by cherrymui** [comment]
Also seems to cause failures on a few builders, e.g.
https://build.golang.org/log/098dae74eeda5fb2090f6613e3960c05e5229438
https://build.golang.org/log/e4570cdda09255016e2d4772ac0c4e16578fbb99

They bootstrap with Go 1.21rc and Go 1.21.0, respectively.

Perhaps bootstrapping with Go 1.21.x is broken? Go 1.20.x seems fine.

**Comment by tomasaschan** [comment]
I'm seeing this with `gotip download` and my local `go` toolchain 1.21.4 now, on dd88f23. Is there a workaround available, other than replacing my global go toolchain with an older version?

<details>
<summary>Full build output</summary>

```shell
λ gotip download
Updating the go development tree...
From https://go.googlesource.com/go
 * branch            master     -> FETCH_HEAD
HEAD is now at dd88f23 math/big: implement Rat.FloatPrec
Building Go cmd/dist using /usr/local/go. (go1.21.4 linux/amd64)
Building Go toolchain1 using /usr/local/go.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
<unknown line number>: internal compiler error: panic: godebug: Value of name not listed in godebugs.All: gotypesalias

goroutine 1 [running]:
runtime/debug.Stack()
        /home/tomasl/sdk/gotip/src/runtime/debug/stack.go:24 +0x5e
bootstrap/cmd/compile/internal/base.FatalfAt({0x96e68?, 0xc0?}, {0xbb3d88, 0x9}, {0xc000096e40, 0x1, 0x1})
        /home/tomasl/sdk/gotip/src/cmd/compile/internal/base/print.go:225 +0x1d7
bootstrap/cmd/compile/internal/base.Fatalf(...)
        /home/tomasl/sdk/gotip/src/cmd/compile/internal/base/print.go:194
bootstrap/cmd/compile/internal/gc.handlePanic()
        /home/tomasl/sdk/gotip/src/cmd/compile/internal/gc/main.go:52 +0x90
panic({0xb0ac60?, 0xc0000bc9b0?})
        /home/tomasl/sdk/gotip/src/runtime/panic.go:914 +0x21f
internal/godebug.(*Setting).Value.func1()
        /home/tomasl/sdk/gotip/src/internal/godebug/godebug.go:141 +0xb9
sync.(*Once).doSlow(0xa2089e?, 0xbb6d69?)
        /home/tomasl/sdk/gotip/src/sync/once.go:74 +0xbf
sync.(*Once).Do(...)
        /home/tomasl/sdk/gotip/src/sync/once.go:65
internal/godebug.(*Setting).Value(0x10fb040)
        /home/tomasl/sdk/gotip/src/internal/godebug/godebug.go:138 +0x48
bootstrap/cmd/compile/internal/types2.NewChecker(0x7ffd325c5405?, 0xc0003aff80, 0x0?)
        /home/tomasl/sdk/gotip/src/cmd/compile/internal/types2/check.go:259 +0x65
bootstrap/cmd/compile/internal/types2.(*Config).Check(0xb2e580?, {0x7ffd325c5405?, 0xc0000120e7?}, {0xc0003d04b0, 0x3, 0x3}, 0x418408?)
        /home/tomasl/sdk/gotip/src/cmd/compile/internal/types2/api.go:461 +0x52
bootstrap/cmd/compile/internal/noder.checkFiles({0x0, {0x0, 0x0}}, {0xc0003d0438, 0x3, 0x10?})
        /home/tomasl/sdk/gotip/src/cmd/compile/internal/noder/irgen.go:88 +0x5b8
bootstrap/cmd/compile/internal/noder.writePkgStub({0x0?, {0x0?, 0x0?}}, {0xc0003d0438, 0x3, 0x3})
        /home/tomasl/sdk/gotip/src/cmd/compile/internal/noder/unified.go:296 +0x6a
bootstrap/cmd/compile/internal/noder.unified({0x0?, {0x0?, 0x0?}}, {0xc0003d0438?, 0xafa040?, 0x0?})
        /home/tomasl/sdk/gotip/src/cmd/compile/internal/noder/unified.go:172 +0x9a
bootstrap/cmd/compile/internal/noder.LoadPackage({0xc0000cc090, 0x3, 0x3})
        /home/tomasl/sdk/gotip/src/cmd/compile/internal/noder/noder.go:77 +0x450
bootstrap/cmd/compile/internal/gc.Main(0xbec2e8)
        /home/tomasl/sdk/gotip/src/cmd/compile/internal/gc/main.go:197 +0xbbd
main.main()
        /home/tomasl/sdk/gotip/src/cmd/compile/main.go:57 +0xf9


go tool dist: FAILED: /home/tomasl/sdk/gotip/pkg/tool/linux_amd64/compile -std -pack -o /tmp/go-tool-dist-1402310999/internal/goos/_go_.a -p internal/goos -importcfg /tmp/go-tool-dist-1402310999/internal/goos/importcfg /home/tomasl/sdk/gotip/src/internal/goos/goos.go /home/tomasl/sdk/gotip/src/internal/goos/unix.go /home/tomasl/sdk/gotip/src/internal/goos/zgoos_linux.go: exit status 2
<unknown line number>: internal compiler error: panic: godebug: Value of name not listed in godebugs.All: gotypesalias

goroutine 1 [running]:
runtime/debug.Stack()
        /home/tomasl/sdk/gotip/src/runtime/debug/stack.go:24 +0x5e
bootstrap/cmd/compile/internal/base.FatalfAt({0x386e68?, 0xc0?}, {0xbb3d88, 0x9}, {0xc000386e40, 0x1, 0x1})
        /home/tomasl/sdk/gotip/src/cmd/compile/internal/base/print.go:225 +0x1d7
bootstrap/cmd/compile/internal/base.Fatalf(...)
        /home/tomasl/sdk/gotip/src/cmd/compile/internal/base/print.go:194
bootstrap/cmd/compile/internal/gc.handlePanic()
        /home/tomasl/sdk/gotip/src/cmd/compile/internal/gc/main.go:52 +0x90
panic({0xb0ac60?, 0xc00003e9b0?})
        /home/tomasl/sdk/gotip/src/runtime/panic.go:914 +0x21f
internal/godebug.(*Setting).Value.func1()
        /home/tomasl/sdk/gotip/src/internal/godebug/godebug.go:141 +0xb9
sync.(*Once).doSlow(0xa2089e?, 0xbb6d69?)
        /home/tomasl/sdk/gotip/src/sync/once.go:74 +0xbf
sync.(*Once).Do(...)
        /home/tomasl/sdk/gotip/src/sync/once.go:65
internal/godebug.(*Setting).Value(0x10fb040)
        /home/tomasl/sdk/gotip/src/internal/godebug/godebug.go:138 +0x48
bootstrap/cmd/compile/internal/types2.NewChecker(0x7ffeeb106445?, 0xc0003e7aa0, 0x0?)
        /home/tomasl/sdk/gotip/src/cmd/compile/internal/types2/check.go:259 +0x65
bootstrap/cmd/compile/internal/types2.(*Config).Check(0xb2e580?, {0x7ffeeb106445?, 0xc0000120e7?}, {0xc000058548, 0x1, 0x1}, 0x418408?)
        /home/tomasl/sdk/gotip/src/cmd/compile/internal/types2/api.go:461 +0x52
bootstrap/cmd/compile/internal/noder.checkFiles({0x0, {0x0, 0x0}}, {0xc0000584d8, 0x1, 0x10?})
        /home/tomasl/sdk/gotip/src/cmd/compile/internal/noder/irgen.go:88 +0x5b8
bootstrap/cmd/compile/internal/noder.writePkgStub({0x0?, {0x0?, 0x0?}}, {0xc0000584d8, 0x1, 0x1})
        /home/tomasl/sdk/gotip/src/cmd/compile/internal/noder/unified.go:296 +0x6a
bootstrap/cmd/compile/internal/noder.unified({0x0?, {0x0?, 0x0?}}, {0xc0000584d8?, 0xafa040?, 0x0?})
        /home/tomasl/sdk/gotip/src/cmd/compile/internal/noder/unified.go:172 +0x9a
bootstrap/cmd/compile/internal/noder.LoadPackage({0xc0000221d0, 0x1, 0x1})
        /home/tomasl/sdk/gotip/src/cmd/compile/internal/noder/noder.go:77 +0x450
bootstrap/cmd/compile/internal/gc.Main(0xbec2e8)
        /home/tomasl/sdk/gotip/src/cmd/compile/internal/gc/main.go:197 +0xbbd
main.main()
        /home/tomasl/sdk/gotip/src/cmd/compile/main.go:57 +0xf9


go tool dist: FAILED: /home/tomasl/sdk/gotip/pkg/tool/linux_amd64/compile -std -pack -o /tmp/go-tool-dist-1402310999/internal/coverage/rtcov/_go_.a -p internal/coverage/rtcov -importcfg /tmp/go-tool-dist-1402310999/internal/coverage/rtcov/importcfg /home/tomasl/sdk/gotip/src/internal/coverage/rtcov/rtcov.go: exit status 2
<unknown line number>: internal compiler error: panic: godebug: Value of name not listed in godebugs.All: gotypesalias

goroutine 1 [running]:
runtime/debug.Stack()
        /home/tomasl/sdk/gotip/src/runtime/debug/stack.go:24 +0x5e
bootstrap/cmd/compile/internal/base.FatalfAt({0x130e68?, 0xc0?}, {0xbb3d88, 0x9}, {0xc000130e40, 0x1, 0x1})
        /home/tomasl/sdk/gotip/src/cmd/compile/internal/base/print.go:225 +0x1d7
bootstrap/cmd/compile/internal/base.Fatalf(...)
        /home/tomasl/sdk/gotip/src/cmd/compile/internal/base/print.go:194
bootstrap/cmd/compile/internal/gc.handlePanic()
        /home/tomasl/sdk/gotip/src/cmd/compile/internal/gc/main.go:52 +0x90
panic({0xb0ac60?, 0xc00003eba0?})
        /home/tomasl/sdk/gotip/src/runtime/panic.go:914 +0x21f
internal/godebug.(*Setting).Value.func1()
        /home/tomasl/sdk/gotip/src/internal/godebug/godebug.go:141 +0xb9
sync.(*Once).doSlow(0xa2089e?, 0xbb6d69?)
        /home/tomasl/sdk/gotip/src/sync/once.go:74 +0xbf
sync.(*Once).Do(...)
        /home/tomasl/sdk/gotip/src/sync/once.go:65
internal/godebug.(*Setting).Value(0x10fb040)
        /home/tomasl/sdk/gotip/src/internal/godebug/godebug.go:138 +0x48
bootstrap/cmd/compile/internal/types2.NewChecker(0x7ffd4776045d?, 0xc0003a5200, 0x0?)
        /home/tomasl/sdk/gotip/src/cmd/compile/internal/types2/check.go:259 +0x65
bootstrap/cmd/compile/internal/types2.(*Config).Check(0xb2e580?, {0x7ffd4776045d?, 0xc0000120e7?}, {0xc000058570, 0x1, 0x1}, 0x418408?)
        /home/tomasl/sdk/gotip/src/cmd/compile/internal/types2/api.go:461 +0x52
bootstrap/cmd/compile/internal/noder.checkFiles({0x0, {0x0, 0x0}}, {0xc000058510, 0x1, 0x10?})
        /home/tomasl/sdk/gotip/src/cmd/compile/internal/noder/irgen.go:88 +0x5b8
bootstrap/cmd/compile/internal/noder.writePkgStub({0x0?, {0x0?, 0x0?}}, {0xc000058510, 0x1, 0x1})
        /home/tomasl/sdk/gotip/src/cmd/compile/internal/noder/unified.go:296 +0x6a
bootstrap/cmd/compile/internal/noder.unified({0x0?, {0x0?, 0x0?}}, {0xc000058510?, 0xafa040?, 0x0?})
        /home/tomasl/sdk/gotip/src/cmd/compile/internal/noder/unified.go:172 +0x9a
bootstrap/cmd/compile/internal/noder.LoadPackage({0xc0000221d0, 0x1, 0x1})
        /home/tomasl/sdk/gotip/src/cmd/compile/internal/noder/noder.go:77 +0x450
bootstrap/cmd/compile/internal/gc.Main(0xbec2e8)
        /home/tomasl/sdk/gotip/src/cmd/compile/internal/gc/main.go:197 +0xbbd
main.main()
        /home/tomasl/sdk/gotip/src/cmd/compile/main.go:57 +0xf9


go tool dist: FAILED: /home/tomasl/sdk/gotip/pkg/tool/linux_amd64/compile -std -pack -o /tmp/go-tool-dist-1402310999/internal/godebugs/_go_.a -p internal/godebugs -importcfg /tmp/go-tool-dist-1402310999/internal/godebugs/importcfg /home/tomasl/sdk/gotip/src/internal/godebugs/table.go: exit status 2
gotip: failed to build go: exit status 2
```

</details>

**Comment by mfrw** [comment]
> I'm seeing this with `gotip download` and my local `go` toolchain 1.21.4 now, on [dd88f23](https://github.com/golang/go/commit/dd88f23a2006307f835f42063b5168ec56c2c428). Is there a workaround available, other than replacing my global go toolchain with an older version?
> 
> Full build output

If it is feasible, the one-liner `patch` in CL: https://go.dev/cl/542135, seems to fix it.

**Comment by tomasaschan** [comment]
Ah, I didn't realize I could apply that locally without `gotip download` overwriting it. Nice, thanks!
