### ISSUE TITLE
debug/elf: slice out of bounds in DynValue

### ISSUE THREAD

**Issue by catenacyber** [golang/go#64446]
### Go version

go version go1.21.0 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/root/.cache/go-build'
GOENV='/root/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/root/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/root/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/root/.go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/root/.go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.0'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/src/ngolo-fuzzing/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3715343815=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

Run https://go.dev/play/p/tzNXO9vLH62

Found by ngolo-fuzzing https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=64344

### What did you expect to see?

Hello world

### What did you see instead?

```
panic: runtime error: slice bounds out of range [:4] with capacity 2

goroutine 1 [running]:
debug/elf.(*File).DynValue(0xc000134000, 0x0)
	/usr/local/go-faketime/src/debug/elf/file.go:1657 +0x365
main.main()
	/tmp/sandbox2925716336/prog.go:13 +0x136

Program exited.
```

**Comment by dmitshur** [comment]
CC @golang/compiler.
