### ISSUE TITLE
x/build: failed to start OpenBSD-riscv64 LUCI builder

### ISSUE THREAD

**Issue by mengzhuo** [golang/go#64797]
### Go version

NA

### What operating system and processor architecture are you using (`go env`)?

```shell
GO111MODULE=''
GOARCH='riscv64'
GOBIN=''
GOCACHE='/home/swarming/.cache/go-build'
GOENV='/home/swarming/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='riscv64'
GOHOSTOS='openbsd'
GOINSECURE=''
GOMODCACHE='/home/swarming/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='openbsd'
GOPATH='/home/swarming/go'
GOPRIVATE=''
GOPROXY='https://goproxy.cn'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/openbsd_riscv64'
GOVCS=''
GOVERSION='go1.21.1'
GCCGO='gccgo'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -pthread -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1232448274=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

I had setup the build as Wiki required, however it failed to run
https://chromium-swarm.appspot.com/task?id=6699b177ea20f010
```
Traceback (most recent call last):
  File "/home/swarming/.swarming/swarming_bot.1.zip/client/run_isolated.py", line 860, in map_and_run
    with data.install_packages_fn(run_dir, cas_client_dir) as cipd_info:
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/swarming/.swarming/swarming_bot.1.zip/client/run_isolated.py", line 1195, in install_client_and_packages
    with client_manager as client:
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/swarming/.swarming/swarming_bot.1.zip/client/cipd.py", line 471, in get_client
    instance_id = resolve_version(
  File "/home/swarming/.swarming/swarming_bot.1.zip/client/cipd.py", line 345, in resolve_version
    _check_response(res, 'Could not resolve version %s:%s', package_name, version)
  File "/home/swarming/.swarming/swarming_bot.1.zip/client/cipd.py", line 332, in _check_response
    raise Error('%s: %s' % (fmt % args, res.get('error_message') or
cipd.Error: Could not resolve version infra/tools/cipd/openbsd-riscv64:git_revision:ec494f363fdfd8cdd5926baad4508d562b7353d4: no such package: infra/tools/cipd/openbsd-riscv64
Could not resolve version infra/tools/cipd/openbsd-riscv64:git_revision:ec494f363fdfd8cdd5926baad4508d562b7353d4: no such package: infra/tools/cipd/openbsd-riscv64
```

### What did you expect to see?

Builder complete all tasks.

### What did you see instead?

NA

**Comment by thanm** [comment]
Hi @mengzhuo I think it looks like there are some setups missing on the LUCI side -- from your stack trace it appears that the bootstrap swarm is trying to download a CIPD binary for your GOOS/GOARCH, but I don't see an entry for it in the CIPD datebase, e.g. https://chrome-infra-packages.appspot.com/p/infra/tools/cipd .  I think Dmitri mentioned this in https://github.com/golang/go/issues/64176#issuecomment-1834401616 .

**Comment by thanm** [comment]
Am going to dup this against #64176, this isn't a new problem (just the before-mentioned CIPD setup that has to get pushed through). Thanks.

**Comment by thanm** [comment]
Dup of #64176.
