### ISSUE TITLE
x/telemetry/cmd/gotelemetry: view command is broken

### ISSUE THREAD

**Issue by hyangah** [golang/go#65553]
Currently graphs in gotelemetry view server don't render.

```
% go version -m ~/go/bin/gotelemetry
/Users/hakim/go/bin/gotelemetry: go1.21.4
	path	golang.org/x/telemetry/cmd/gotelemetry
	mod	golang.org/x/telemetry	v0.0.0-20240206184024-a188beea2487	h1:ADj2y3cw0FR33yFh0hQ7PRvDsgkNyBdzsdPXMH5t/Pc=
	dep	golang.org/x/mod	v0.14.0	h1:dGoOF9QVLYng8IHTm7BAyWqCqSheQ5pYWGhzW00YJr0=
```

The developer console contains:

```
Uncaught TypeError: t.Counters is not iterable
    at C3 (index.min.js:61:17104)
    at window.onload (index.min.js:61:16536)
```

**Comment by hyangah** [comment]
Caused by my `go` that happened to create a counter file but didn't collect any data.
We need to fix the TS code to handle the empty counter case.

```
 "Charts": {
  "Programs": [
   {
    "ID": "charts:cmd/go",
    "Name": "cmd/go",
    "Counters": null,
    "Active": false
   },
   ...
```
