### ISSUE TITLE
x/net/http2: should not panic if func "called after Handler finished"

### ISSUE THREAD

**Issue by markus-wa** [golang/go#65844]
The way the stdlib `http` package handles duplicate calls to `WriteHeader` is by logging them, e.g.

```
2024/02/21 14:01:46 http: superfluous response.WriteHeader call from main.main.func1 (main.go:17)
```

The `x/net/http2` pkg instead panics in the same situation.
This is problematic as it makes it more difficult to implement something like a timeout middleware.

http example:

```go
package main

import (
    "context"
    "fmt"
    "net/http"
    "time"
)

// longRunningHandler simulates a task that takes 2 seconds to complete
func longRunningHandler(w http.ResponseWriter, r *http.Request) {
    time.Sleep(2 * time.Second)
    w.WriteHeader(200)
    fmt.Fprintln(w, "Operation completed")
}

// timeoutMiddleware wraps an http.Handler and adds a timeout of 1 second
func timeoutMiddleware(next http.Handler) http.Handler {
    return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
        ctx, cancel := context.WithTimeout(r.Context(), 1*time.Second)
        defer cancel()

        finished := make(chan bool)
        go func() {
            next.ServeHTTP(w, r.WithContext(ctx))
            finished <- true
        }()

        select {
        case <-finished:
            // Request finished within timeout
        case <-ctx.Done():
            // Timeout occurred
            http.Error(w, "Request timed out", http.StatusGatewayTimeout)
        }
    })
}

func main() {
    mux := http.NewServeMux()
    mux.Handle("/", timeoutMiddleware(http.HandlerFunc(longRunningHandler)))

    server := &http.Server{
        Addr:    ":8080",
        Handler: mux,
    }

    fmt.Println("Starting H2C server on :8080")
    if err := server.ListenAndServe(); err != nil {
        fmt.Println("Server error:", err)
    }
}
```

This works fine with

     curl localhost:8080

http2 example:

```go
package main

import (
    "context"
    "fmt"
    "net/http"
    "time"

    "golang.org/x/net/http2"
    "golang.org/x/net/http2/h2c"
)

// longRunningHandler simulates a task that takes 2 seconds to complete
func longRunningHandler(w http.ResponseWriter, r *http.Request) {
    time.Sleep(2 * time.Second)
    w.WriteHeader(200)
    fmt.Fprintln(w, "Operation completed")
}

// timeoutMiddleware wraps an http.Handler and adds a timeout of 1 second
func timeoutMiddleware(next http.Handler) http.Handler {
    return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
        ctx, cancel := context.WithTimeout(r.Context(), 1*time.Second)
        defer cancel()

        finished := make(chan bool)
        go func() {
            next.ServeHTTP(w, r.WithContext(ctx))
            finished <- true
        }()

        select {
        case <-finished:
            // Request finished within timeout
        case <-ctx.Done():
            // Timeout occurred
            http.Error(w, "Request timed out", http.StatusGatewayTimeout)
        }
    })
}

func main() {
    mux := http.NewServeMux()
    mux.Handle("/", timeoutMiddleware(http.HandlerFunc(longRunningHandler)))

    server := &http.Server{
        Addr:    ":8080",
        Handler: h2c.NewHandler(mux, &http2.Server{}),
    }

    fmt.Println("Starting H2C server on :8080")
    if err := server.ListenAndServe(); err != nil {
        fmt.Println("Server error:", err)
    }
}
```

This crashes the server:

    curl --http2-prior-knowledge localhost:8080

**Comment by panjf2000** [comment]
Could you provide the stack info when the crash happened? Thanks!

**Comment by panjf2000** [comment]
Also the output of `go env` would be helpful for the diagnosis.

**Comment by markus-wa** [comment]
:warning: The below is just one occasion where this happens - sometimes the panic happens elsewhere, e.g. in `func (w *responseWriter) FlushError() error {`

stack trace

```terminal
$ go run  cmd/main.go
Starting H2C server on :8080
panic: WriteHeader called after Handler finished

goroutine 34 [running]:
golang.org/x/net/http2.(*responseWriter).WriteHeader(0x77359400?, 0xc000048748?)
        /home/mark/go/pkg/mod/golang.org/x/net@v0.10.0/http2/server.go:2843 +0x34
main.longRunningHandler({0x71f288, 0xc0000d2000}, 0x6284e0?)
        /home/mark/dev/esportal/cbb/services/cbb/cmd/main.go:16 +0x3b
net/http.HandlerFunc.ServeHTTP(0xc0000c8100?, {0x71f288?, 0xc0000d2000?}, 0xc0000487d0?)
        /usr/lib/go/src/net/http/server.go:2136 +0x29
main.main.timeoutMiddleware.func1.1()
        /home/mark/dev/esportal/cbb/services/cbb/cmd/main.go:28 +0x69
created by main.main.timeoutMiddleware.func1 in goroutine 19
        /home/mark/dev/esportal/cbb/services/cbb/cmd/main.go:27 +0x165
exit status 2
```

`go env`

```bash
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/mark/.cache/go-build'
GOENV='/home/mark/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/mark/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/mark/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/lib/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/lib/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.7'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/mark/dev/esportal/cbb/services/cbb/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1119853708=/tmp/go-build -gno-record-gcc-switches'
```

**Comment by panjf2000** [comment]
The relevant commits for `net/http`: [flesh out http server](https://github.com/golang/go/commit/e73acc1b35f3490f3d800b4bf49da79630e808fc) and [bufio:](https://github.com/golang/go/commit/9aa28f9231bf8239027d8d2eda230f090eddaf83), [Break responseWriter into small and large parts](https://github.com/golang/net/commit/729bd7279cb0d415a6d940031ffe173aa61ccd15) for `x/net/http2`.

Although I see no particular reasons for `x/net/http2` to behave differently from `net/http`, I wonder why you would create a new goroutine for your handler in middleware, this is not the usual pattern that people would do with `net/http`, could you explain it a bit?

**Comment by markus-wa** [comment]
@panjf2000 Well, `http.TimeoutHandler` also creates a goroutine - I don't know how you would implement a custom timeout middleware without a goroutine to be honest.

But that said, `http.TimeoutHandler` actually works with the current `x/net/http2` implementation - so maybe my implementation is just too naive and I just need to use that approach of using something like a `timeoutWriter` - but this seems like a very easy mistake to make and one where we could spare users pain by aligning implementations.

I guess I mostly filed this issue to raise awareness of the differences between the two and that it can lead to confusion and  very hard to debug problems. e.g. calling `curl` with or without `--http2-prior-knowledge` will either crash the server or "work" with the same code, which is quite a stark difference.

**Comment by panjf2000** [comment]
Thanks for the explanation and you're right about `http.TimeoutHandler`. But still, something like that is not the common pattern, may I ask why you chose to implement your handmade timeout handler instead of using `http.TimeoutHandler`, any particular reasons behind this?

Nevertheless, I do agree with you about the inconsistency between `net/http` and `x/net/http2` leading to confusion for users. Maybe we should consider keeping this synchronized on this behavior? @neild

**Comment by markus-wa** [comment]
@panjf2000 we've had a case where we wanted a different http status code when timeouts were coming from our app rather than from somewhere on the way (pretty non-standard indeed). Other usecases I could imagine would be things like running some code (e.g. metrics / logging) when a timeout occurs.
