### ISSUE TITLE
cmd/vet: unitchecker panic checking left shift with float

### ISSUE THREAD

**Issue by hajimehoshi** [golang/go#65939]
### Go version

go1.22

### Output of `go env` in your module/workspace:

```shell
n/a
```

### What did you do?

Run this: https://go.dev/play/p/oVYKMHyztHy

```go
package main

func main() {
	a := 1
	println(a << 2.0)
}
```

### What did you see happen?

Panic:

```
# [play]
panic: 2 not an Int

goroutine 25 [running]:
go/constant.Int64Val({0x7ba0b8?, 0xc000111140?})
	go/constant/value.go:516 +0x109
cmd/vendor/golang.org/x/tools/go/analysis/passes/shift.checkLongShift(0xc000122b60, {0x7b83d0, 0xc000015f50}, {0x7b9548, 0xc00005f2a0}, {0x7b9998, 0xc00005f2c0})
	cmd/vendor/golang.org/x/tools/go/analysis/passes/shift/shift.go:92 +0xbe
cmd/vendor/golang.org/x/tools/go/analysis/passes/shift.run.func2({0x7b83d0, 0xc000015f50})
	cmd/vendor/golang.org/x/tools/go/analysis/passes/shift/shift.go:64 +0x105
cmd/vendor/golang.org/x/tools/go/ast/inspector.(*Inspector).Preorder(0xc0001820a8, {0xc000147bd0?, 0x969ae0?, 0x30?}, 0xc0000a7c10)
	cmd/vendor/golang.org/x/tools/go/ast/inspector/inspector.go:82 +0x8f
cmd/vendor/golang.org/x/tools/go/analysis/passes/shift.run(0xc000122b60)
	cmd/vendor/golang.org/x/tools/go/analysis/passes/shift/shift.go:55 +0x159
cmd/vendor/golang.org/x/tools/go/analysis/unitchecker.run.func2.1()
	cmd/vendor/golang.org/x/tools/go/analysis/unitchecker/unitchecker.go:382 +0x8ce
sync.(*Once).doSlow(0x6ee9e0?, 0xc00011e480?)
	sync/once.go:74 +0xc2
sync.(*Once).Do(...)
	sync/once.go:65
cmd/vendor/golang.org/x/tools/go/analysis/unitchecker.run.func2(0x968de0)
	cmd/vendor/golang.org/x/tools/go/analysis/unitchecker/unitchecker.go:333 +0x19e
cmd/vendor/golang.org/x/tools/go/analysis/unitchecker.run.func3.1(0x0?)
	cmd/vendor/golang.org/x/tools/go/analysis/unitchecker/unitchecker.go:404 +0x23
created by cmd/vendor/golang.org/x/tools/go/analysis/unitchecker.run.func3 in goroutine 1
	cmd/vendor/golang.org/x/tools/go/analysis/unitchecker/unitchecker.go:403 +0x47
```

### What did you expect to see?

`4` is printed

**Comment by bcmills** [comment]
(attn @timothy-king)
