### ISSUE TITLE
x/tools/gopls: nil panic loading analysisNode.summary

### ISSUE THREAD

**Issue by jstbyte** [golang/go#66732]
gopls version: v0.15.2/go1.20.1
gopls flags: 
update flags: proxy
extension version: 0.41.2
environment: Visual Studio Code win32
initialization error: undefined
issue timestamp: Sun, 07 Apr 2024 03:13:55 GMT
restart history:
Sun, 07 Apr 2024 03:01:06 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0x163a7fc]

goroutine 186 [running]:
golang.org/x/tools/gopls/internal/cache.(*Snapshot).Analyze(0x0, {0x1e17ad8, 0xc00082df50}, 0xc000219bf0, {0xc00017f800, 0xcc, 0xc000867d88%3F}, 0xc00048ea20)
	  analysis.go:461  0x139c
golang.org/x/tools/gopls/internal/golang.Analyze({0x1e17ad8, 0xc00082df50}, 0xc00007e240, 0xc0005a5560%3F, 0x1a4f8a0%3F)
	  diagnostics.go:42  0x16b
golang.org/x/tools/gopls/internal/server.(*server).diagnose.func6()
	  diagnostics.go:507  0xc5
created by golang.org/x/tools/gopls/internal/server.(*server).diagnose
	  diagnostics.go:502  0x10a5
</pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 2,
    "TestdataFiles": 0,
    "GoFiles": 1,
    "ModFiles": 1,
    "Dirs": 1
  },
  "GOARCH": "amd64",
  "GOOS": "windows",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.20.1",
  "GoplsVersion": "v0.15.2",
  "InitialWorkspaceLoadDuration": "1.8348831s",
  "MemStats": {
    "HeapAlloc": 2531088,
    "HeapInUse": 5169152,
    "TotalAlloc": 12289392
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 2,
      "Largest": 60,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.22.2",
        "AllPackages": {
          "Packages": 1,
          "LargestPackage": 1,
          "CompiledGoFiles": 1,
          "Modules": 1
        },
        "WorkspacePackages": {
          "Packages": 1,
          "LargestPackage": 1,
          "CompiledGoFiles": 1,
          "Modules": 1
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

Dups: 3DjTOg

**Comment by adonovan** [comment]
This stack `3DjTOg` was [reported by telemetry](https://storage.googleapis.com/prod-telemetry-merged/2024-08-29.json):

"root analysisNode has nil summary"

```
gopls/bug
golang.org/x/tools/gopls/internal/util/bug.report:+35
golang.org/x/tools/gopls/internal/util/bug.Report:=68
golang.org/x/tools/gopls/internal/cache.(*Snapshot).Analyze:+263
golang.org/x/tools/gopls/internal/golang.Analyze:+12
golang.org/x/tools/gopls/internal/server.(*server).diagnose.func6:+5
runtime.goexit:+0
```
```
golang.org/x/tools/gopls@v0.16.2-pre.1 go1.22.2 linux/amd64 other,vscode-insiders (1)
```

Issue created by golang.org/x/tools/gopls/internal/telemetry/cmd/stacks.

**Comment by findleyr** [comment]
This may still be a problem but I'm bumping to v0.18.0 as the analysis driver has changed significantly; let's reevaluate after v0.17.0.

**Comment by findleyr** [comment]
Moving this to the backlog until we get more actionable reports. (Either more reports, or _more actionable_ reports).

**Comment by adonovan** [comment]
This hasn't appeared since gopls 16.
