### ISSUE TITLE
runtime/pprof: TestLabelSystemstack failure on linux-arm

### ISSUE THREAD

**Issue by mknyszek** [golang/go#67023]
```
#!watchflakes
post <- pkg == "runtime/pprof" && test == "TestLabelSystemstack"
```

**Comment by mknyszek** [comment]
In triage, this looks like a timer failed to fire. A `time.Sleep` of 100 milliseconds never woke up. I wonder if this is fixed in the new timer changes?

**Comment by mknyszek** [comment]
Given that we rewrote the timer implementation on tip, this only happened once, and only on Go 1.21, let's just wait for more failures.

**Comment by prattmic** [comment]
Note that there are 2 different 100ms sleeps, both of which failed to wake.

```
goroutine 26699 [sleep, 9 minutes]:
runtime.gopark(0x1e38c4, 0x184a030, 0x13, 0x13, 0x1)
	/home/swarming/.swarming/w/ir/x/w/goroot/src/runtime/proc.go:398 +0x104 fp=0x158ff8c sp=0x158ff78 pc=0x53078
time.Sleep(0x5f5e100)
	/home/swarming/.swarming/w/ir/x/w/goroot/src/runtime/time.go:195 +0x16c fp=0x158ffa8 sp=0x158ff8c pc=0x8886c
runtime/pprof.profileWriter({0x211d3c, 0x1a67a58})
	/home/swarming/.swarming/w/ir/x/w/goroot/src/runtime/pprof/pprof.go:809 +0x58 fp=0x158ffe0 sp=0x158ffa8 pc=0x16e07c
runtime/pprof.StartCPUProfile.func2()
	/home/swarming/.swarming/w/ir/x/w/goroot/src/runtime/pprof/pprof.go:794 +0x30 fp=0x158ffec sp=0x158ffe0 pc=0x16dfa4
runtime.goexit()
	/home/swarming/.swarming/w/ir/x/w/goroot/src/runtime/asm_arm.s:859 +0x4 fp=0x158ffec sp=0x158ffec pc=0x8a760
created by runtime/pprof.StartCPUProfile in goroutine 26698
	/home/swarming/.swarming/w/ir/x/w/goroot/src/runtime/pprof/pprof.go:794 +0x13c

goroutine 26698 [sleep, 9 minutes]:
runtime.gopark(0x1e38c4, 0x184a060, 0x13, 0x13, 0x1)
	/home/swarming/.swarming/w/ir/x/w/goroot/src/runtime/proc.go:398 +0x104 fp=0x148dd0c sp=0x148dcf8 pc=0x53078
time.Sleep(0x5f5e100)
	/home/swarming/.swarming/w/ir/x/w/goroot/src/runtime/time.go:195 +0x16c fp=0x148dd28 sp=0x148dd0c pc=0x8886c
runtime/pprof.parallelLabelHog({0x21249c, 0x1a67a70}, 0x5f5e100, 0x64)
	/home/swarming/.swarming/w/ir/x/w/goroot/src/runtime/pprof/pprof_test.go:1992 +0xfc fp=0x148dd44 sp=0x148dd28 pc=0x18d670
runtime/pprof.TestLabelSystemstack.func1.1({0x21249c, 0x1a67a70})
	/home/swarming/.swarming/w/ir/x/w/goroot/src/runtime/pprof/pprof_test.go:1885 +0x3c fp=0x148dd5c sp=0x148dd44 pc=0x18ce90
runtime/pprof.Do({0x21245c, 0x318ba0}, {{0x15f7d20, 0x1, 0x1}}, 0x148ddd0)
	/home/swarming/.swarming/w/ir/x/w/goroot/src/runtime/pprof/runtime.go:51 +0xbc fp=0x148dd98 sp=0x148dd5c pc=0x17a860
runtime/pprof.TestLabelSystemstack.func1(0x5f5e100)
	/home/swarming/.swarming/w/ir/x/w/goroot/src/runtime/pprof/pprof_test.go:1884 +0x1d0 fp=0x148ddfc sp=0x148dd98 pc=0x18ce18
runtime/pprof.testCPUProfile(0x17be000, 0x148df74, 0x148def0)
	/home/swarming/.swarming/w/ir/x/w/goroot/src/runtime/pprof/pprof_test.go:484 +0x268 fp=0x148de9c sp=0x148ddfc pc=0x181868
runtime/pprof.TestLabelSystemstack(0x17be000)
	/home/swarming/.swarming/w/ir/x/w/goroot/src/runtime/pprof/pprof_test.go:1883 +0xd4 fp=0x148df94 sp=0x148de9c pc=0x18c178
testing.tRunner(0x17be000, 0x1e34f0)
	/home/swarming/.swarming/w/ir/x/w/goroot/src/testing/testing.go:1595 +0x124 fp=0x148dfe0 sp=0x148df94 pc=0xff968
testing.(*T).Run.func1()
	/home/swarming/.swarming/w/ir/x/w/goroot/src/testing/testing.go:1648 +0x30 fp=0x148dfec sp=0x148dfe0 pc=0x10095c
runtime.goexit()
	/home/swarming/.swarming/w/ir/x/w/goroot/src/runtime/asm_arm.s:859 +0x4 fp=0x148dfec sp=0x148dfec pc=0x8a760
created by testing.(*T).Run in goroutine 1
	/home/swarming/.swarming/w/ir/x/w/goroot/src/testing/testing.go:1648 +0x3f0
```
