### ISSUE TITLE
x/text/cmd/gotext: gotext extract panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by aimuz** [golang/go#67249]
### Go version

go version go1.22.2 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE='on'
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/aimuz/Library/Caches/go-build'
GOENV='/Users/aimuz/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/aimuz/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/aimuz/go'
GOPRIVATE=''
GOPROXY='https://mirror.authgo.cn/go,https://goproxy.io,https://proxy.golang.org,direct'
GOROOT='/opt/homebrew/opt/go/libexec'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/opt/homebrew/opt/go/libexec/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.22.2'
GCCGO='gccgo'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD='/Users/aimuz/workspaces/github.com/aimuz/go-template/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/76/g87hkglj42j6vxywmyqq0_8h0000gn/T/go-build529514588=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

go run golang.org/x/text/cmd/gotext extract

### What did you see happen?

panic

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x1008106e8]

goroutine 1 [running]:
main.config()
        /Users/aimuz/go/pkg/mod/golang.org/x/text@v0.14.0/cmd/gotext/main.go:55 +0xd8
main.main()
        /Users/aimuz/go/pkg/mod/golang.org/x/text@v0.14.0/cmd/gotext/main.go:154 +0x2d0

```

### What did you expect to see?

Normal operation, no panic

**Comment by aimuz** [comment]
https://github.com/golang/go/issues/62697

**Comment by cherrymui** [comment]
Thanks. Closing as a dup of #62697.
