### ISSUE TITLE
x/text/message/pipeline: TestFullCycle/ssa fails with "panic: Cannot range over: func(yield func(E) bool)" on Go tip

### ISSUE THREAD

**Issue by dmitshur** [golang/go#67348]
As visible on the [x/text by Go commit](https://ci.chromium.org/p/golang/g/x-text-gotip-by-go/console) LUCI view, `TestFullCycle/ssa` started to fail on all builders where it runs as of [CL 568477](https://go.dev/cl/568477) with:

```
=== RUN   TestFullCycle/ssa
panic: Cannot range over: func(yield func(E) bool)

goroutine 859 [running]:
golang.org/x/tools/go/ssa.(*builder).rangeStmt(0xc000ceddf8, 0xc00465d380, 0xc0006a3ce0, 0x0)
	/home/swarming/.swarming/w/ir/x/w/gopath/pkg/mod/golang.org/x/tools@v0.6.0/go/ssa/builder.go:2096 +0x774
golang.org/x/tools/go/ssa.(*builder).stmt(0xc000ceddf8, 0xc00465d380, {0x991b40?, 0xc0006a3ce0?})
	/home/swarming/.swarming/w/ir/x/w/gopath/pkg/mod/golang.org/x/tools@v0.6.0/go/ssa/builder.go:2315 +0x205
golang.org/x/tools/go/ssa.(*builder).stmtList(...)
	/home/swarming/.swarming/w/ir/x/w/gopath/pkg/mod/golang.org/x/tools@v0.6.0/go/ssa/builder.go:946
golang.org/x/tools/go/ssa.(*builder).stmt(0xc000ceddf8, 0xc00465d380, {0x9919c0?, 0xc000ba8d80?})
	/home/swarming/.swarming/w/ir/x/w/gopath/pkg/mod/golang.org/x/tools@v0.6.0/go/ssa/builder.go:2277 +0xe47
golang.org/x/tools/go/ssa.(*builder).buildFunctionBody(0xc000ceddf8, 0xc00465d380)
	/home/swarming/.swarming/w/ir/x/w/gopath/pkg/mod/golang.org/x/tools@v0.6.0/go/ssa/builder.go:2391 +0x433
golang.org/x/tools/go/ssa.(*builder).buildFunction(0x6ee160?, 0xc00465d380)
	/home/swarming/.swarming/w/ir/x/w/gopath/pkg/mod/golang.org/x/tools@v0.6.0/go/ssa/builder.go:2326 +0x28
golang.org/x/tools/go/ssa.(*builder).buildCreated(0xc000ceddf8)
	/home/swarming/.swarming/w/ir/x/w/gopath/pkg/mod/golang.org/x/tools@v0.6.0/go/ssa/builder.go:2413 +0x25
golang.org/x/tools/go/ssa.(*Package).build(0xc00629d100)
	/home/swarming/.swarming/w/ir/x/w/gopath/pkg/mod/golang.org/x/tools@v0.6.0/go/ssa/builder.go:2606 +0xc25
sync.(*Once).doSlow(0x997ea0?, 0xc003cb8720?)
	/home/swarming/.swarming/w/ir/x/w/goroot/src/sync/once.go:74 +0xb4
sync.(*Once).Do(...)
	/home/swarming/.swarming/w/ir/x/w/goroot/src/sync/once.go:65
golang.org/x/tools/go/ssa.(*Package).Build(...)
	/home/swarming/.swarming/w/ir/x/w/gopath/pkg/mod/golang.org/x/tools@v0.6.0/go/ssa/builder.go:2477
golang.org/x/tools/go/ssa.(*Program).Build.func1(0xc003cb8ba0?)
	/home/swarming/.swarming/w/ir/x/w/gopath/pkg/mod/golang.org/x/tools@v0.6.0/go/ssa/builder.go:2462 +0x45
created by golang.org/x/tools/go/ssa.(*Program).Build in goroutine 22
	/home/swarming/.swarming/w/ir/x/w/gopath/pkg/mod/golang.org/x/tools@v0.6.0/go/ssa/builder.go:2461 +0x187
```

Example failing build is https://ci.chromium.org/b/8748389409025708577.

CC @mpvl, @ianlancetaylor.

**Comment by adonovan** [comment]
This issue should have been addressed by CL 584295. I guess x/text needs to update its x/tools dependency. I'll do that.
