### ISSUE TITLE
x/tools/gopls: panic during internal/cache.(*analysisNode).typeCheck (crash)

### ISSUE THREAD

**Issue by bakhankov** [golang/go#67595]
gopls version: v0.15.3/go1.21.6
gopls flags: 
update flags: proxy
extension version: 0.41.4
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Wed, 22 May 2024 10:06:06 GMT
restart history:
Wed, 22 May 2024 10:05:56 GMT: activation (enabled: true)

gopls stopped on VSCode start

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa67e73]

goroutine 12560 [running]:
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck(0xc002cfe840, {0xc005d8d140, 0x8, 0x8})
	  analysis.go:1078  0xaf3
golang.org/x/tools/gopls/internal/cache.(*analysisNode).run(0xc002cfe840, {0x124c7e8%3F, 0xc00576f350})
	  analysis.go:826  0x206
golang.org/x/tools/gopls/internal/cache.(*analysisNode).runCached(0xc002cfe840, {0x124c7e8%3F, 0xc00576f350})
	  analysis.go:687  0x12d
golang.org/x/tools/gopls/internal/cache.(*Snapshot).Analyze.func6.1()
	  analysis.go:397  0xc9
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 12559
	  errgroup.go:75  0x96
</pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 9626,
    "TestdataFiles": 12,
    "GoFiles": 5599,
    "ModFiles": 2,
    "Dirs": 1498
  },
  "GOARCH": "amd64",
  "GOOS": "linux",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.21.6",
  "GoplsVersion": "v0.15.3",
  "InitialWorkspaceLoadDuration": "1.240260707s",
  "MemStats": {
    "HeapAlloc": 148121704,
    "HeapInUse": 229654528,
    "TotalAlloc": 1659043360
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 5500,
      "Largest": 1654451,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.21.6",
        "AllPackages": {
          "Packages": 1073,
          "LargestPackage": 200,
          "CompiledGoFiles": 5805,
          "Modules": 137
        },
        "WorkspacePackages": {
          "Packages": 244,
          "LargestPackage": 200,
          "CompiledGoFiles": 1101,
          "Modules": 1
        },
        "Diagnostics": 28
      }
    ]
  }
}

</details>

```
(go env: {GOOS:linux GOARCH:amd64 GOCACHE:/home/***/.cache/go-build GOMODCACHE:/home/***/go/pkg/mod GOPATH:/home/***/go GOPRIVATE:https://gitlab.***.dev/lib/go GOFLAGS: GO111MODULE: GoVersion:21 GoVersionOutput:go version go1.21.6 linux/amd64
 GOWORK: GOPACKAGESDRIVER:})
(env overlay: map[])


[Info  - 12:06:05 PM] 2024/05/22 12:06:05 go/packages.Load golang/vscode-go#1
	snapshot=0
	directory=file:///home/***/projects/***
	query=[/home/***/projects/***/... builtin]
	packages=310

[Info  - 12:06:05 PM] 2024/05/22 12:06:05 go/packages.Load golang/vscode-go#1: updating metadata for 1073 packages

[Error - 12:06:05 PM] Request textDocument/semanticTokens/range failed.
  Message: semantictokens are disabled
  Code: 0 
[Error - 12:06:05 PM] Request textDocument/semanticTokens/full failed.
  Message: semantictokens are disabled
  Code: 0 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa67e73]

goroutine 12560 [running]:
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck(0xc002cfe840, {0xc005d8d140, 0x8, 0x8})
	/home/***/go/pkg/mod/golang.org/x/tools/gopls@v0.15.3/internal/cache/analysis.go:1078 +0xaf3
golang.org/x/tools/gopls/internal/cache.(*analysisNode).run(0xc002cfe840, {0x124c7e8?, 0xc00576f350})
	/home/***/go/pkg/mod/golang.org/x/tools/gopls@v0.15.3/internal/cache/analysis.go:826 +0x206
golang.org/x/tools/gopls/internal/cache.(*analysisNode).runCached(0xc002cfe840, {0x124c7e8?, 0xc00576f350})
	/home/***/go/pkg/mod/golang.org/x/tools/gopls@v0.15.3/internal/cache/analysis.go:687 +0x12d
golang.org/x/tools/gopls/internal/cache.(*Snapshot).Analyze.func6.1()
	/home/***/go/pkg/mod/golang.org/x/tools/gopls@v0.15.3/internal/cache/analysis.go:397 +0xc9
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/home/***/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:78 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 12559
	/home/***/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:75 +0x96
[Error - 12:06:06 PM] 
```

**Comment by hyangah** [comment]
Duplicate of #64227
