### ISSUE TITLE
x/net/quic: tests failing on Plan 9 builders because of unimplemented UDP features

### ISSUE THREAD

**Issue by millerresearch** [golang/go#68288]
### Go version

gotip

### Output of `go env` in your module/workspace:

```shell
GOARCH=arm
GOBIN=
GOCACHE=/home/swarming/.swarming/w/ir/x/w/gocache
GOHOSTARCH=amd64
GOHOSTOS=linux
GOMAXPROCS=4
GOOS=plan9
GOPATH=/home/swarming/.swarming/w/ir/x/w/gopath
GOPLSCACHE=/home/swarming/.swarming/w/ir/x/w/goplscache
GOROOT=
GOROOT_BOOTSTRAP=/home/swarming/.swarming/w/ir/cache/tools/go_bootstrap
GOTOOLCHAIN=local
GO_BUILDER_NAME=x_net-gotip-plan9-arm
```

### What did you do?

In `x/net`, Plan 9 arm builder attempted to run `go test -json -short ./...`

### What did you see happen?

Several tests always fail, some to the extent of nil-dereference panics.

```
--- FAIL: TestConnect (10.01s)
    endpoint_test.go:23: closed connection: CONNECTION_REFUSED: "handshake timeout"
--- FAIL: TestConnectDefaultTLSConfig (10.02s)
    endpoint_test.go:29: closed connection: CONNECTION_REFUSED: "handshake timeout"
--- FAIL: TestStreamTransfer (10.02s)
    endpoint_test.go:34: closed connection: CONNECTION_REFUSED: "handshake timeout"
--- FAIL: TestStreamsCreateConcurrency (10.06s)
    conn_streams_test.go:480: closed connection: CONNECTION_REFUSED: "handshake timeout"
--- FAIL: TestUDPSourceUnspecified (0.04s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal sys: trap: fault read code=0x0 addr=0x4 pc=0x391e88]

goroutine 1737 [running]:
testing.tRunner.func1.2({0x3db9a0, 0x68e630})
	/home/swarming/.swarming/w/ir/x/w/goroot/src/testing/testing.go:1632 +0x254
testing.tRunner.func1()
	/home/swarming/.swarming/w/ir/x/w/goroot/src/testing/testing.go:1635 +0x3d4
panic({0x3db9a0, 0x68e630})
	/home/swarming/.swarming/w/ir/x/w/goroot/src/runtime/panic.go:785 +0xfc
golang.org/x/net/quic.TestUDPSourceUnspecified.func1(0xe46608, {0x10908c8, 0x1090910, {{{0x0, 0xffff7f000001}, {0xc16030}}, 0xf33d}, 0x111c500})
	/home/swarming/.swarming/w/ir/x/w/targetrepo3461126964/quic/udp_test.go:30 +0x190
golang.org/x/net/quic.runUDPTest.func1(0xe46608)
	/home/swarming/.swarming/w/ir/x/w/targetrepo3461126964/quic/udp_test.go:178 +0x584
testing.tRunner(0xe46608, 0xd0c4b0)
	/home/swarming/.swarming/w/ir/x/w/goroot/src/testing/testing.go:1690 +0x124
created by testing.(*T).Run in goroutine 1736
	/home/swarming/.swarming/w/ir/x/w/goroot/src/testing/testing.go:1743 +0x3d4
--- FAIL: TestUDPSourceUnspecified/udp4/udp/unspec (0.02s)
    udp_test.go:21: 127.0.0.1:62269
FAIL	golang.org/x/net/quic	61.339s

```

### What did you expect to see?

Expected the failing tests to be skipped on Plan 9, because they depend on the unimplemented `ReadMsgUDP` function.

I think it might be possible to implement the missing UDP functionality, but meanwhile these tests should really be skipped. Also it might be good to avoid the nil dereference panic by checking for reading from a closed `test.dgramc` channel in places like this:

```
udp_test.c:29,30:
                got := <-test.dgramc
                if !bytes.Equal(got.b, data) {

```

**Comment by thanm** [comment]
Thanks for the report. Would you be willing to send a CL for this?
