### ISSUE TITLE
cmd/internal/obj:  symbol redeclared panics during InitTextSym

### ISSUE THREAD

**Issue by y1yang0** [golang/go#68962]
### Go version

go1.24

### Output of `go env` in your module/workspace:

```shell
hidden
```

### What did you do?

When compiling the automatically generated code(https://github.com/alibaba/opentelemetry-go-auto-instrumentation/pull/52/), a panic occurred:

```
/test.go:5:47: internal compiler error: panic: runtime error: invalid memory address or nil pointer dereference

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new
```

reproduce:
```go
package otel_rules
import _ "unsafe"
import otel_debug "runtime/debug"
//go:linkname OtelPrintStack0 otel_debug.OtelPrintStack
func OtelPrintStack0() { otel_debug.PrintStack() }
//go:linkname OtelPrintStack1 otel_debug.OtelPrintStack
func OtelPrintStack1() { otel_debug.PrintStack() } 
```

further reduce:
```go
import _ "unsafe"

//go:linkname a main.c
func a() {}

func c() {}
```

### What did you see happen?

compiler panic

### What did you expect to see?

not panic

**Comment by ianlancetaylor** [comment]
Stack trace:

```
# command-line-arguments
foo.go:5:47: internal compiler error: panic: runtime error: invalid memory address or nil pointer dereference

goroutine 1 [running]:
runtime/debug.Stack()
	../../go/src/runtime/debug/stack.go:26 +0x5e
cmd/compile/internal/base.FatalfAt({0xe96d8?, 0xc0?}, {0xe36239, 0x9}, {0xc0000e9708, 0x1, 0x1})
	../../go/src/cmd/compile/internal/base/print.go:230 +0x1ea
cmd/compile/internal/base.Fatalf(...)
	../../go/src/cmd/compile/internal/base/print.go:195
cmd/compile/internal/gc.handlePanic()
	../../go/src/cmd/compile/internal/gc/main.go:54 +0x8a
panic({0xdaee20?, 0x14e8b40?})
	../../go/src/runtime/panic.go:785 +0x132
cmd/internal/obj.(*Link).InitTextSym(...)
	../../go/src/cmd/internal/obj/plist.go:186
cmd/compile/internal/ir.setupTextLSym(0xfaf078?, 0xc0003f7a01?)
	../../go/src/cmd/compile/internal/ir/abi.go:77 +0x244
cmd/compile/internal/ir.InitLSym(0xc0003c7400, 0x1)
	../../go/src/cmd/compile/internal/ir/abi.go:32 +0xea
cmd/compile/internal/gc.prepareFunc(0xc0003c7400)
	../../go/src/cmd/compile/internal/gc/compile.go:95 +0x25
cmd/compile/internal/gc.enqueueFunc(0xc0003c7400)
	../../go/src/cmd/compile/internal/gc/compile.go:76 +0x268
cmd/compile/internal/gc.Main(0xe711d8)
	../../go/src/cmd/compile/internal/gc/main.go:300 +0x123b
main.main()
	../../go/src/cmd/compile/main.go:57 +0xf9
```
