### ISSUE TITLE
runtime: provide a way to opt in to stack trace printing for process-terminating signals in secure-mode binaries on Unix OSes

### ISSUE THREAD

**Issue by cespare** [golang/go#69868]
### Go version

go version go1.23.1 linux/amd64

### Output of `go env` in your module/workspace:

```shell
n/a
```

### What did you do?

Consider two trivial go programs. First, `sleep.go`:

```
//go:build ignore

package main

import "time"

func main() {
	time.Sleep(time.Hour)
}
```

Second, `panic.go`:

```
//go:build ignore

package main

func main() {
	panic("asdf")
}
```

First, run `sleep.go` and then interrupt it by hitting `C-\` (SIGQUIT):

```
$ rm -f sleep && go build -o sleep sleep.go && ./sleep
^\SIGQUIT: quit
PC=0x46c46e m=0 sigcode=128

goroutine 0 gp=0x50da00 m=0 mp=0x50e660 [idle]:
... lots of stack trace elided...
rflags 0x246
cs     0x33
```

Next, run `panic.go` in the same way:

```
$ rm -f panic && go build -o panic panic.go && ./panic
panic: asdf

goroutine 1 [running]:
main.main()
        /home/caleb/w/_scratch/x/panic.go:6 +0x25
```

All normal stuff. Now let's do the same thing but with a binary that has `CAP_SYS_ADMIN`:

```
$ rm -f sleep && go build -o sleep sleep.go && sudo setcap 'cap_sys_admin+ep' ./sleep && ./sleep
^\SIGQUIT: quit
```

```
$ rm -f panic && go build -o panic panic.go && sudo setcap 'cap_sys_admin+ep' ./panic && ./panic
panic: asdf
```

In both cases (SIGQUIT and a normal panic), printing stack traces is suppressed by the Go runtime. This is a [security measure](https://pkg.go.dev/runtime#hdr-Security) implemented last year in #60272.

If I want to bypass this stack trace suppression anyway, I can do so for panics by calling `runtime/debug.SetTraceback`. For example, If I add the line

    debug.SetTraceback("single")

to `panic.go`, then it restores the normal unprivileged panic stack trace printing behavior:

```
$ rm -f panic && go build -o panic panic.go && sudo setcap 'cap_sys_admin+ep' ./panic && ./panic
panic: asdf

goroutine 1 [running]:
main.main()
        /home/caleb/w/_scratch/x/panic.go:9 +0x32
```

However, as far as I know, there is no equivalent way to opt in to the default signal-handling stack trace printing behavior. If I want to print stack traces on SIGQUIT, I'd have to listen for the signal and do it myself.

### What did you see happen?

No way to turn on stack trace printing for process-terminating signals for this `CAP_SYS_ADMIN` binary.

### What did you expect to see?

I believe there should be a way to ask the runtime to print stack traces on SIGQUIT when running in secure mode. One way to to this would be to piggyback on `debug.SetTraceback` and restore the signal stack trace printing behavior when `SetTraceback` is called with some value other than "none" (or perhaps only when called with "all" or "single", or perhaps only when called with "all").

Alternatively, we can provide a new API such as `runtime/debug.SetSignalTraceback(bool)`.

cc:

* @golang/security 
* @rolandshoemaker who implemented this security measure
* @ianlancetaylor who made a related comment over at https://github.com/golang/go/issues/62474#issuecomment-1709314643

**Comment by cespare** [comment]
#68103 is an interesting related bug. It looks like the `debug.SetTraceback` trick only works for panics and not fatal errors.

**Comment by ianlancetaylor** [comment]
CC @golang/runtime @golang/security

**Comment by rolandshoemaker** [comment]
I'm somewhat concerned about all of a sudden giving debug.SetTraceback security properties which it previously didn't. Everyone who has set a non-default traceback value will, all of a sudden, have disabled a security feature that may not be aware of.

In general, letting this be a switch set in code is somewhat complicated from a security perspective. What the developer wants and expects is likely to be somewhat different from what the person deploying the binary wants/expects, especially if they are using the various capability restriction/elevation features. In particular I'm not sure if there is really a way to make it clear to users whether the developer has called debug.SetTraceback, and as such if potentially sensitive data will be elided or not.

**Comment by cespare** [comment]
It's currently the case today that `debug.SetTraceback` lets the user disable (one part of) this security measure. People who wrote code before 2023 that called `debug.SetTraceback` never got the security measure insofar as it applies to internal panics. So we're already in the world you're talking about.

> What the developer wants and expects is likely to be somewhat different from what the person deploying the binary wants/expects,

I'm definitely sympathetic to this idea. However, the change in #60272 causes the program to completely ignore GOTRACEBACK (rather than, say, setting a different default value). So the knob that's most easily available to the deployer of the binary (an environment variable) cannot control this setting; the only (partial) knob that's available is `debug.SetTraceback`.

For my needs, I don't particularly care whether the solution is `debug.SetTraceback`, some new `runtime/debug` function, `GOTRACEBACK`, some new environment variable, or some other way entirely. But I need to be able to turn these stack traces back on.

**Comment by griesemer** [comment]
This probably needs a proposal to move forward.

**Comment by cespare** [comment]
I can turn this into a proposal, but I'd appreciate some feedback about what direction the runtime/security folks would find most palatable.

By the way, I should say that from my perspective as a user, I'm not asking for a new feature but rather a fix for a regression. We had a program that produced stack traces when it crashed, but since the changes in #60272, it has produced useless empty output instead. This includes cases where tests deadlock and produce no output when they are killed with SIGQUIT, making them impossible to debug. (The test binary is given CAP_SYS_ADMIN in order to exercise certain containerization functionality.)

**Comment by mknyszek** [comment]
In compiler/runtime triage, we think this might be best as a new API (not exactly sure what form it should take), though whatever we do needs @rolandshoemaker's input.

**Comment by zzkcode** [comment]
Same background, but I have more curious about the coredump file generated behavior here: even in the Secure-Mode, Linux can generate coredump on a suid file by changing the `/proc/sys/fs/suid_dumpable` to a none-zero value. However, a cgo-crash will exit directly without checking the suid_dumpable status. Is it possible if Go could let kernel decide to generate coredump when suid_dumpable is enabled instead of exiting process directly?

## Example

```Go
// cgo-crash.go
package main

/*
#include <stdio.h>

void crash() {
    int *p = NULL;
    *p = 1024;
}
*/
import "C"

import "runtime/debug"

func main() {
  debug.SetTraceback("crash")
  C.crash()
}
```

```bash
$ go build -o cgo-crash cgo-crash.go
$ setcap 'cap_sys_admin+ep' cgo-crash
$ echo 1 > /proc/sys/fs/suid_dumpable

// switch to non-root before execution
$ su xxx
$ ulimit -c unlimited
$ ./cgo-crash
SIGSEGV: segmentation violation // this won't generate coredump
```

Compare to a pure C program, this could have coredump generated.

```C
// main.c
#include <stdio.h>

int main() {
  int *p = NULL;
  *p = 1024;

  return 0;
}
```

```bash
$ gcc -g main.c
$ setcap 'cap_sys_admin+ep' a.out
$ echo 1 > /proc/sys/fs/suid_dumpable

// switch to non-root before execution
$ su xxx
$ ulimit -c unlimited
$ ./a.out
Segmentation fault (core dumped) // this will generate coredump
```

## Reference

- [PR_SET_DUMPABLE](https://man7.org/linux/man-pages/man2/PR_SET_DUMPABLE.2const.html)

**Comment by mejedi** [comment]
It would be nice if `GOTRACEBACK` environment variable could be re-enabled for processes running with elevated privileges (opt-in). Maybe introduce a variable in `runtime` and check it during initialization?  One can alter the variable as needed via `-ldflags`.

**Comment by cespare** [comment]
@rolandshoemaker could you please review this thread and say which options seem the best to you?

**Comment by mejedi** [comment]
After some thought process, I have a feeling that maybe there's a better solution, at least for my use case.

I am mostly concerned about containerized apps. Since an app is in a container, it is insulated from evil-doers that could attempt to sabotage it and extract sensitive info. Hence I don't benefit from Golang's "secure mode". I am running with elevated capabilities for things such as eBPF, as a non-root user. The way capabilities are obtained trigger "secure mode". Go tracebacks are suppressed, `GOTRACEBACK` environment variable is ignored.

From user's PoV, containerized apps with capabilities shouldn't be a special case. Being able to configure traceback mode externally via an environment variable is a useful feature. It is suboptimal if apps with capabilities have it broken outright or consult a different environment variable.

I might have a need to collect a crash dump one day using `GOTRACEBACK=crash`. But it won't work even if we convince Golang team to provide an opt-out. The kernel has its own notion of "secure mode", and ~~AFAIK it can't be cleared~~ (Upd: there are ways to re-enable core dumps). ~~Hence in the end, Golang opt-out is not worth it.~~

A better solution is to obtain capabilities in a way that doesn't trigger "secure mode".

The challenge is that Linux capabilities are way more complex than Docker/k8s present them. It is not a single set you can [`--cap-add`](https://docs.docker.com/engine/containers/run/#runtime-privilege-and-linux-capabilities) to, but [multiple sets with complex semantics](https://man7.org/linux/man-pages/man7/capabilities.7.html) (scroll to "Thread capability sets").

*Ambient* capabilities would be a great fit for Docker, but unfortunately it predates them. It is using *Inheritable* instead. 
```
Ambient (since Linux 4.3)
              This is a set of capabilities that are preserved across an
              [execve(2)](https://man7.org/linux/man-pages/man2/execve.2.html)
              of a program that is not privileged.
Inheritable
              This is a set of capabilities preserved across an
              [execve(2)](https://man7.org/linux/man-pages/man2/execve.2.html).
              Inheritable capabilities remain inheritable
              when executing any program, and inheritable capabilities
              are added to the permitted set when executing a program
              that has the corresponding bits set in the file inheritable
              set.
```
A "privileged" program in this context is a program with *some capabilities attached to its executable file*.

So unless running as root, for Docker's `--cap-add` to take effect, one has to assign capabilities to the app's executable file. But if an executable has capabilities assigned, a "secure mode" is triggered (both in-kernel and for Golang runtime).

I doubt if it is possible to "fix" Docker/k8s at this point. The second best option would be using a [loader program](https://github.com/kubernetes/kubernetes/issues/56374#issuecomment-2733111068):
  * loader is an entry-point in container image, has file capabilities;
  * loader configures ambient capabilities, launches app.
 
The end result is that "secure mode" is triggered for the loader, but not the app itself. It works w/o Golang providing an opt out.

Update: related Docker/k8s issues
 * https://github.com/kubernetes/kubernetes/issues/56374
 * https://github.com/moby/moby/pull/26979
It was started 10 years ago and went nowhere :(

**Comment by ignoramous** [comment]
> A better solution is to obtain capabilities in a way that doesn't trigger "secure mode".

> @rolandshoemaker could you please review this thread and say which options seem the best to you?

Unfortunately, from what I can tell, Android apps have `AT_SECURE` set; at least all of the ones I develop seem to return `AT_SECURE` as `1` (reading bytes in `/proc/self/auxv` on non-rooted Androids).

This means, on Go runtime fatal / throws and a few kinds of panics, only one line is output to logcat (Android's stderr) which makes it hard to tell just what went wrong. Android, does use libunwinder for native apps, and the Android RunTime has its own unwinder; both of which traceback seemingly oblivious to `AT_SECURE`. I am sure there's security benefits to the Go runtime being this rigid about GOTRACEBACK, but may be, just for `goos.IsAndroid` (and if `uid` > `10000`), `AT_SECURE` could be ignored?
