### ISSUE TITLE
x/tools/gopls: panic in token.File.Name within PackageDocHTML (telemetry)

### ISSUE THREAD

**Issue by adonovan** [golang/go#70149]
```
#!stacks
"runtime.sigpanic" && "go/token.(*File).Name:=114" && "golang.PackageDocHTML:+12"
```
```go
	for _, f := range pkg.Syntax() {
		fileMap[pkg.FileSet().File(f.Pos()).Name()] = f // panic
	}
```
Issue created by [stacks](https://pkg.go.dev/golang.org/x/tools/gopls/internal/telemetry/cmd/stacks).

This stack `BQeQrg` was [reported by telemetry](https://storage.googleapis.com/prod-telemetry-merged/2024-10-28.json):

- `gopls/bug`
- [`golang.org/x/tools/gopls/internal/util/bug.report:+35`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/util/bug/bug.go;l=109)
- [`golang.org/x/tools/gopls/internal/util/bug.Report:+1`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/util/bug/bug.go;l=68)
- [`golang.org/x/tools/gopls/internal/server.(*server).initWeb.withPanicHandler.func10.1:+2`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/server/server.go;l=534)
- [`runtime.gopanic:+50`](https://cs.opensource.google/go/go/+/go1.23.2:src/runtime/panic.go;l=785)
- `runtime.panicmem:=262`
- [`runtime.sigpanic:+19`](https://cs.opensource.google/go/go/+/go1.23.2:src/runtime/signal_unix.go;l=900)
- [`go/token.(*File).Name:=114`](https://cs.opensource.google/go/go/+/go1.23.2:src/go/token/position.go;l=114)
- [`golang.org/x/tools/gopls/internal/golang.PackageDocHTML:+12`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/golang/pkgdoc.go;l=284)
- [`golang.org/x/tools/gopls/internal/server.(*server).initWeb.func6:+40`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/server/server.go;l=350)
- [`net/http.HandlerFunc.ServeHTTP:+1`](https://cs.opensource.google/go/go/+/go1.23.2:src/net/http/server.go;l=2220)
- [`golang.org/x/tools/gopls/internal/server.(*server).initWeb.StripPrefix.func11:+10`](https://cs.opensource.google/go/go/+/go1.23.2:src/net/http/server.go;l=2282)
- [`net/http.HandlerFunc.ServeHTTP:+1`](https://cs.opensource.google/go/go/+/go1.23.2:src/net/http/server.go;l=2220)
- [`net/http.(*ServeMux).ServeHTTP:+14`](https://cs.opensource.google/go/go/+/go1.23.2:src/net/http/server.go;l=2747)
- [`golang.org/x/tools/gopls/internal/server.(*server).initWeb.StripPrefix.func9:+10`](https://cs.opensource.google/go/go/+/go1.23.2:src/net/http/server.go;l=2282)
- [`net/http.HandlerFunc.ServeHTTP:+1`](https://cs.opensource.google/go/go/+/go1.23.2:src/net/http/server.go;l=2220)
- [`golang.org/x/tools/gopls/internal/server.(*server).initWeb.withPanicHandler.func10:+7`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/server/server.go;l=537)
```
golang.org/x/tools/gopls@v0.16.2 go1.23.2 linux/amd64 neovim (1)
```

**Comment by IlyasYOY** [comment]
@adonovan Hello! I guess I found a bug. May I contribute a fix? 

I created empty file: 
<img width="1462" alt="image" src="https://github.com/user-attachments/assets/eb920bca-dc93-42d1-aad5-bde66e159804">

Then I called action: 
<img width="1462" alt="image" src="https://github.com/user-attachments/assets/efd0a0d5-2b34-41a4-86b5-58eb3c27e58e">

After that I have the same stacktrace in my neovim log: 

```
[START][2024-11-01 21:02:04] LSP logging initiated
[ERROR][2024-11-01 21:02:04] ...lsp/handlers.lua:623	"2024/11/01 21:02:04 imports fixes: allImportsFixes: /Users/ilyasyoy/Projects/IlyasYOY/main.go:1:2: expected ';', found 'EOF' (and 2 more errors)\n\tfile=\"/Users/ilyasyoy/Projects/IlyasYOY/main.go\"\n"
[ERROR][2024-11-01 21:02:05] .../vim/lsp/rpc.lua:770	"rpc"	"gopls"	"stderr"	"server.go:3489: http: panic serving 127.0.0.1:61794: runtime error: invalid memory address or nil pointer dereference\ngoroutine 128 [running]:\nnet/http.(*conn).serve.func1()\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/server.go:1947 +0xb0\npanic({0x101962300?, 0x102119110?})\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/runtime/panic.go:785 +0x124\ngo/token.(*File).Name(...)\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/go/token/position.go:114\ngolang.org/x/tools/gopls/internal/golang.PackageDocHTML({0x1015eb532, 0x1}, 0x14000499da0, {0x101a95c40, 0x1400051c8c0})\n\t/Users/ilyasyoy/go/pkg/mod/golang.org/x/tools/gopls@v0.16.2/internal/golang/pkgdoc.go:284 +0x160\ngolang.org/x/tools/gopls/internal/server.(*server).initWeb.func6({0x101a99798, 0x140001d0380}, 0x140000aac80)\n\t/Users/ilyasyoy/go/pkg/mod/golang.org/x/tools/gopls@v0.16.2/internal/server/server.go:350 +0x27c\nnet/http.HandlerFunc.ServeHTTP(0x0?, {0x101a99798?, 0x140001d0380?}, 0x5?)\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/server.go:2220 +0x38\ngolang.org/x/tools/gopls/internal/server.(*server).initWeb.StripPrefix.func11({0x101a99798, 0x140001d0380}, 0x140000aab40)\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/server.go:2282 +0x228\nnet/http.HandlerFunc.ServeHTTP(0x1400050e178?, {0x101a99798?, 0x140001d0380?}, 0x10155f2dc?)\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/server.go:2220 +0x38\nnet/http.(*ServeMux).ServeHTTP(0x0?, {0x101a99798, 0x140001d0380}, 0x140000aab40)\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/server.go:2747 +0x1b4\ngolang.org/x/tools/gopls/internal/server.(*server).initWeb.StripPrefix.func9({0x101a99798, 0x140001d0380}, 0x140000aaa00)\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/server.go:2282 +0x228\nnet/http.HandlerFunc.ServeHTTP(0x0?, {0x101a99798?, 0x140001d0380?}, 0x10?)\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/server.go:2220 +0x38\ngolang.org/x/tools/gopls/internal/server.(*server).initWeb.withPanicHandler.func10({0x101a99798?, 0x140001d0380?}, 0x140000c3b28?)\n\t/Users/ilyasyoy/go/pkg/mod/golang.org/x/tools/gopls@v0.16.2/internal/server/server.go:537 +0x74\nnet/http.HandlerFunc.ServeHTTP(0x1400050e098?, {0x101a99798?, 0x140001d0380?}, 0x100f40504?)\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/server.go:2220 +0x38\nnet/http.(*ServeMux).ServeHTTP(0x0?, {0x101a99798, 0x140001d0380}, 0x140000aaa00)\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/server.go:2747 +0x1b4\nnet/http.serverHandler.ServeHTTP({0x140005a3590?}, {0x101a99798?, 0x140001d0380?}, 0x6?)\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/server.go:3210 +0xbc\nnet/http.(*conn).serve(0x140000ffc20, {0x101a9b0e8, 0x140005a2de0})\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/server.go:2092 +0x4fc\ncreated by net/http.(*Server).Serve in goroutine 200\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/server.go:3360 +0x3dc\n"
[ERROR][2024-11-01 21:02:06] .../vim/lsp/rpc.lua:770	"rpc"	"gopls"	"stderr"	"server.go:3489: http: panic serving 127.0.0.1:61795: runtime error: invalid memory address or nil pointer dereference\ngoroutine 209 [running]:\nnet/http.(*conn).serve.func1()\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/server.go:1947 +0xb0\npanic({0x101962300?, 0x102119110?})\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/runtime/panic.go:785 +0x124\ngo/token.(*File).Name(...)\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/go/token/position.go:114\ngolang.org/x/tools/gopls/internal/golang.PackageDocHTML({0x1015eb532, 0x1}, 0x14000499da0, {0x101a95c40, 0x1400051c8c0})\n\t/Users/ilyasyoy/go/pkg/mod/golang.org/x/tools/gopls@v0.16.2/internal/golang/pkgdoc.go:284 +0x160\ngolang.org/x/tools/gopls/internal/server.(*server).initWeb.func6({0x101a99798, 0x140001d0460}, 0x140000aaf00)\n\t/Users/ilyasyoy/go/pkg/mod/golang.org/x/tools/gopls@v0.16.2/internal/server/server.go:350 +0x27c\nnet/http.HandlerFunc.ServeHTTP(0x0?, {0x101a99798?, 0x140001d0460?}, 0x5?)\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/server.go:2220 +0x38\ngolang.org/x/tools/gopls/internal/server.(*server).initWeb.StripPrefix.func11({0x101a99798, 0x140001d0460}, 0x140000aadc0)\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/server.go:2282 +0x228\nnet/http.HandlerFunc.ServeHTTP(0x1400050e178?, {0x101a99798?, 0x140001d0460?}, 0x10155f2dc?)\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/server.go:2220 +0x38\nnet/http.(*ServeMux).ServeHTTP(0x0?, {0x101a99798, 0x140001d0460}, 0x140000aadc0)\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/server.go:2747 +0x1b4\ngolang.org/x/tools/gopls/internal/server.(*server).initWeb.StripPrefix.func9({0x101a99798, 0x140001d0460}, 0x1400025c140)\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/server.go:2282 +0x228\nnet/http.HandlerFunc.ServeHTTP(0x0?, {0x101a99798?, 0x140001d0460?}, 0x10?)\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/server.go:2220 +0x38\ngolang.org/x/tools/gopls/internal/server.(*server).initWeb.withPanicHandler.func10({0x101a99798?, 0x140001d0460?}, 0x140004f5b28?)\n\t/Users/ilyasyoy/go/pkg/mod/golang.org/x/tools/gopls@v0.16.2/internal/server/server.go:537 +0x74\nnet/http.HandlerFunc.ServeHTTP(0x1400050e098?, {0x101a99798?, 0x140001d0460?}, 0x100f40504?)\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/server.go:2220 +0x38\nnet/http.(*ServeMux).ServeHTTP(0x0?, {0x101a99798, 0x140001d0460}, 0x1400025c140)\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/server.go:2747 +0x1b4\nnet/http.serverHandler.ServeHTTP({0x140004e6600?}, {0x101a99798?, 0x140001d0460?}, 0x6?)\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/server.go:3210 +0xbc\nnet/http.(*conn).serve(0x140000ffcb0, {0x101a9b0e8, 0x140005a2de0})\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/server.go:2092 +0x4fc\ncreated by net/http.(*Server).Serve in goroutine 200\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/server.go:3360 +0x3dc\n"
[ERROR][2024-11-01 21:02:06] .../vim/lsp/rpc.lua:770	"rpc"	"gopls"	"stderr"	"server.go:3489: http: panic serving 127.0.0.1:61796: runtime error: invalid memory address or nil pointer dereference\ngoroutine 187 [running]:\nnet/http.(*conn).serve.func1()\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/server.go:1947 +0xb0\npanic({0x101962300?, 0x102119110?})\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/runtime/panic.go:785 +0x124\ngo/token.(*File).Name(...)\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/go/token/position.go:114\ngolang.org/x/tools/gopls/internal/golang.PackageDocHTML({0x1015eb532, 0x1}, 0x14000499da0, {0x101a95c40, 0x1400051c8c0})\n\t/Users/ilyasyoy/go/pkg/mod/golang.org/x/tools/gopls@v0.16.2/internal/golang/pkgdoc.go:284 +0x160\ngolang.org/x/tools/gopls/internal/server.(*server).initWeb.func6({0x101a99798, 0x140001d0540}, 0x140000ab2c0)\n\t/Users/ilyasyoy/go/pkg/mod/golang.org/x/tools/gopls@v0.16.2/internal/server/server.go:350 +0x27c\nnet/http.HandlerFunc.ServeHTTP(0x0?, {0x101a99798?, 0x140001d0540?}, 0x5?)\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/server.go:2220 +0x38\ngolang.org/x/tools/gopls/internal/server.(*server).initWeb.StripPrefix.func11({0x101a99798, 0x140001d0540}, 0x140000ab180)\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/server.go:2282 +0x228\nnet/http.HandlerFunc.ServeHTTP(0x1400050e178?, {0x101a99798?, 0x140001d0540?}, 0x10155f2dc?)\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/server.go:2220 +0x38\nnet/http.(*ServeMux).ServeHTTP(0x0?, {0x101a99798, 0x140001d0540}, 0x140000ab180)\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/server.go:2747 +0x1b4\ngolang.org/x/tools/gopls/internal/server.(*server).initWeb.StripPrefix.func9({0x101a99798, 0x140001d0540}, 0x140000ab040)\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/server.go:2282 +0x228\nnet/http.HandlerFunc.ServeHTTP(0x0?, {0x101a99798?, 0x140001d0540?}, 0x10?)\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/server.go:2220 +0x38\ngolang.org/x/tools/gopls/internal/server.(*server).initWeb.withPanicHandler.func10({0x101a99798?, 0x140001d0540?}, 0x140004f5b28?)\n\t/Users/ilyasyoy/go/pkg/mod/golang.org/x/tools/gopls@v0.16.2/internal/server/server.go:537 +0x74\nnet/http.HandlerFunc.ServeHTTP(0x1400050e098?, {0x101a99798?, 0x140001d0540?}, 0x100f40504?)\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/server.go:2220 +0x38\nnet/http.(*ServeMux).ServeHTTP(0x0?, {0x101a99798, 0x140001d0540}, 0x140000ab040)\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/server.go:2747 +0x1b4\nnet/http.serverHandler.ServeHTTP({0x140005a3bc0?}, {0x101a99798?, 0x140001d0540?}, 0x6?)\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/server.go:3210 +0xbc\nnet/http.(*conn).serve(0x140003f5050, {0x101a9b0e8, 0x140005a2de0})\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/server.go:2092 +0x4fc\ncreated by net/http.(*Server).Serve in goroutine 200\n\t/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/server.go:3360 +0x3dc\n"
```

I guess the fix might be here: https://github.com/Homebrew/brew/blob/70672606c6ac07a5e8f75abeda7b8736e8285dbe/Cellar/go/1.23.2/libexec/src/go/ast/ast.go#L1057

There is no package in file so the documentation might not be generated.
