### ISSUE TITLE
crypto/ecdsa: Sign() panics if public key is not set

### ISSUE THREAD

**Issue by guidovranken** [golang/go#70468]
### Go version

go version devel go1.24-7c7170e Wed Nov 20 18:27:31 2024 +0000 linux/amd64

### Output of `go env` in your module/workspace:

```shell
AR='ar'
CC='clang-15'
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_ENABLED='1'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
CXX='clang++-15'
GCCGO='gccgo'
GO111MODULE=''
GOAMD64='v1'
GOARCH='amd64'
GOAUTH='netrc'
GOBIN=''
GOCACHE='/home/jhg/.cache/go-build'
GODEBUG=''
GOENV='/home/jhg/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFIPS140='off'
GOFLAGS=''
GOGCCFLAGS='-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1928511716=/tmp/go-build -gno-record-gcc-switches'
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMOD='/home/jhg/oss-fuzz-379773077/p/go.mod'
GOMODCACHE='/home/jhg/oss-fuzz-379773077/go-dev/packages/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/jhg/oss-fuzz-379773077/go-dev/packages'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/home/jhg/oss-fuzz-379773077/go-dev'
GOSUMDB='sum.golang.org'
GOTELEMETRY='local'
GOTELEMETRYDIR='/home/jhg/.config/go/telemetry'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/home/jhg/oss-fuzz-379773077/go-dev/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='devel go1.24-7c7170e Wed Nov 20 18:27:31 2024 +0000'
GOWORK=''
PKG_CONFIG='pkg-config'
```

### What did you do?

```go
package main

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/sha256"
	"fmt"
	"math/big"
)

func main() {
	priv, ok := new(big.Int).SetString("123", 10)
	if ok == false {
		panic("Cannot decode bignum")
	}
	var priv_ecdsa ecdsa.PrivateKey
	priv_ecdsa.D = priv
	priv_ecdsa.PublicKey.Curve = elliptic.P256()

	msg := "hello, world"
	hash := sha256.Sum256([]byte(msg))

	r, s, err := ecdsa.Sign(rand.Reader, &priv_ecdsa, hash[:])
	fmt.Println(err)
	fmt.Println(r.String())
	fmt.Println(s.String())
}
```

### What did you see happen?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x4c2117]

goroutine 1 [running]:
math/big.(*Int).Sign(...)
	/home/jhg/oss-fuzz-379773077/go-dev/src/math/big/int.go:48
crypto/ecdsa.pointFromAffine({0x56bc88?, 0x646070?}, 0x0, 0x0)
	/home/jhg/oss-fuzz-379773077/go-dev/src/crypto/ecdsa/ecdsa.go:402 +0x37
crypto/ecdsa.privateKeyToFIPS[...](0xc0002d02c0, 0xc0002dff18)
	/home/jhg/oss-fuzz-379773077/go-dev/src/crypto/ecdsa/ecdsa.go:391 +0x38
crypto/ecdsa.signFIPS[...](0xc0002d02c0, 0xc0002c8df8, {0x56b020?, 0x66c280}, {0xc0002dfed8, 0x20, 0x20})
	/home/jhg/oss-fuzz-379773077/go-dev/src/crypto/ecdsa/ecdsa.go:234 +0x46
crypto/ecdsa.SignASN1({0x56b020, 0x66c280}, 0xc0002dff18, {0xc0002dfed8, 0x20, 0x20})
	/home/jhg/oss-fuzz-379773077/go-dev/src/crypto/ecdsa/ecdsa.go:220 +0x229
crypto/ecdsa.Sign({0x56b020?, 0x66c280?}, 0xbf7cbadf074d6483?, {0xc0002c8ed8?, 0xc0002c8ef8?, 0xc?})
	/home/jhg/oss-fuzz-379773077/go-dev/src/crypto/ecdsa/ecdsa_legacy.go:60 +0x37
main.main()
	/home/jhg/oss-fuzz-379773077/p/x.go:23 +0xf4
```

### What did you expect to see?

No panic and output like:

```
<nil>
40753909606936490861524166827361514810969838335424734688996005945565630866707
3003946056421339230760555414094068582110502790139132375823642300394845145720
```

**Comment by guidovranken** [comment]
This used to always work. Presumably broken due to https://github.com/golang/go/commit/9776d028f4b99b9a935dae9f63f32871b77c49af or any of the related commits.

**Comment by ianlancetaylor** [comment]
CC @golang/security

**Comment by ianlancetaylor** [comment]
This was caused by https://go.dev/cl/628677.

**Comment by ianlancetaylor** [comment]
@FiloSottile What is the status of this issue? Should this be fixed for 1.25? Thanks.

**Comment by FiloSottile** [comment]
This fell off the radar. My mistake.

However now that it shipped, I wonder if we should just let it be: we'd have fixed it to avoid potentially breaking applications that are upgrading to Go 1.24, not because this is documented to work anywhere. It doesn't look like anyone else ended up hitting it, though?

**Comment by seankhliao** [comment]
closing since it appears to be fine in the current supported releases...

**Comment by zamicol** [comment]
We had the same problem in Coze with the latest version of Go.

https://github.com/Cyphrme/Coze/pull/30

**Comment by zamicol** [comment]
Thanks for the work on the refactor.  I wanted to share this experience to inform future discussion/decisions/docs.

We had the same problem in Coze with the latest versions of Go (Go 1.24+) which we fixed. Previous versions worked fine: https://github.com/Cyphrme/Coze/pull/30

I believe ianlancetaylor is correct that this breaking change was introduced by https://go-review.googlesource.com/c/go/+/628677, meaning this was introduced in Go 1.24.

Signing an ECDSA message mathematically requires only the private scalar (d) and the curve parameters. The public key coordinates (X, Y) are not needed for the signing operation itself. This is convenient for minimal storage (e.g., private keys on disk without duplicating the public part).

The old behavior (Go ≤1.23) allowed this: Load/store just d (and curve), construct an *ecdsa.PrivateKey with PublicKey.X and PublicKey.Y left as nil, and call ecdsa.Sign (and SignASN1).  Public components are not used during signing. Even though ecdsa.GenerateKey always populates the public key, when reading from disk or elsewhere, the public components are not needed, so it's not necessary to load the public components. As FiloSottile noted, "The joys of malleable key types... worked by chance", but in cases like loading minimal private keys from trusted storage, this was a deliberate and safe pattern.

I have not yet dug deeply into the code for this change, but it leaves me with a few questions:

 1. The new code requires X and Y to be non-nil, but is it possible to set completely bogus X and Y values?  Would signing still proceed happily (as long as they're non-nil big.Ints)?

 2. Wouldn't validation involve checking that the public components are actually on the curve (curve.IsOnCurve(X, Y)), and/or that the correct public point corresponding to D (i.e., base point × D)?

In short, does this change actually protect against malformed or mismatched public components? At a glance, this appears to be a structural requirement change (non-nil fields) but it's not providing semantic validation.  If an application or Go itself has already done the best that's possible to insure that keys are well-formed, the question is that are we gaining any protections from this new change?  (Also keeping in mind that any validation at the time of signing adds more overhead.  Unless it's really needed, revalidating just adds unnecessary overhead.) 

From reviewing the code (not exhaustively), it appears privateKeyToFIPS -> pointFromAffine simply dereferences X and Y without calling IsOnCurve or verifying they match the scalar multiple of the base point. So the panic prevents nil derefs but allows completely invalid public points.  If this validation is important, and Go isn't doing it, should we expect libraries (or applications) to perform this operation themselves?

---
For Coze, the fix was:

> Go 1.24+'s FIPS-compliant ecdsa.Sign implementation now requires the PublicKey.X and PublicKey.Y fields to be populated, not just the Curve. Previously, these were nil which caused a panic in the new privateKeyToFIPS → pointFromAffine code path.
>
> The fix extracts X and Y from the existing c.X field (stored as X||Y) when available, falling back to ScalarBaseMult computation only when c.X is not populated. This maintains performance for the common case where the full key is available.

**Comment by FiloSottile** [comment]
In general, you can **never** assume that making some fields of a struct nil will keep working in the future, unless the comments specify they may be nil. The current code might not use them, but we can't defensively write all code to check for the nil-ness of every public field in every type. Same for setting them to bogus values, we always protect from malformed *encodings* while parsing from disk or from the network, but if you go out of your way to mess with the internal field, you are on your own. (Still, this is why I strongly prefer opaque types, and why we are moving to those where possible.)

FWIW, we do check if X, Y are on the curve, look at crypto/internal/fips140/ecdsa.NewPublicKey. We do not check if they match the private key, though, because again you are not supposed to mess with these fields.

The right solution is to stop touching low-level deprecated fields, and instead call ecdsa.ParseRawPrivateKey. It should work perfectly with that Coze code, just pass D to it.
