### ISSUE TITLE
Output can't run in crontab

### ISSUE THREAD

**Issue by yxgms** [golang/go#70521]
### Go version

go version go1.23.2 windows/amd64

### Output of `go env` in your module/workspace:

```shell
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\abc\AppData\Local\go-build
set GOENV=C:\Users\abc\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\abc\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\abc\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=D:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=D:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.23.2
set GODEBUG=
set GOTELEMETRY=local
set GOTELEMETRYDIR=C:\Users\abc\AppData\Roaming\go\telemetry
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=D:\abc\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\abc\AppData\Local\Temp\go-build3008884582=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

simple code 
```
package main

import (
	"fmt"
	"log"
	"os"
	"os/exec"
	"time"
)

func checkErr(err error) {
	if err != nil {
		panic(err)
	}
}

func main() {
	a := time.Now().Format("2006-01-02_15-04-05")
	sh := fmt.Sprintf("/tmp/iptb_%s.sh", a)
	gen(sh)
	str := fmt.Sprintf("chmod +x %s && %s", sh, sh)
	cmd := exec.Command("sh", "-c", str)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	checkErr(cmd.Run())

	log.Println("OK...")
}

func gen(fn string) {
	f, err := os.Create(fn)
	checkErr(err)
	defer f.Close()
	_, err = f.WriteString("#!/bin/sh\n\nset -e\n\n")
	checkErr(err)
	_, err = f.WriteString("iptables -A INPUT -s 218.92.0.181/32 -j DROP\n")
	checkErr(err)
}
```

cross build
```
GOOS='linux' GOARCH='amd64' go build -trimpath -ldflags="-s -w" -o abc
```

run it in terminal (a debian machine)
```
root@hd:~# pwd
/root
root@hd:~# ./abc
2024/11/22 05:18:16 OK...
```

all good for now.

add it to crontab
```
*/2 * * * * /root/abc > /tmp/abc.log 2>&1
```

run failed, log shows
```
root@hd:~# cat /tmp/abc.log
/tmp/iptb_2024-11-22_05-20-01.sh: 5: iptables: not found
panic: exit status 127

goroutine 1 [running]:
main.checkErr(...)
 ***/m.go:13
main.main()
 ***/m.go:25 +0x225
```

I must have installed **iptables**

### What did you see happen?

same binary can run in terminal but can't run in crontab, iptables: not found.

### What did you expect to see?

be same, can run in crontab too.

**Comment by yxgms** [comment]
my mistake, sorry.
