### ISSUE TITLE
syscall/js: failure at startup with log imported

### ISSUE THREAD

**Issue by rsc** [golang/go#70785]
rsc/tmp/wasmshell is a trivial little Go wasm program.
You can run it with:

```
git clone https://github.com/rsc/tmp
cd tmp/wasmshell
go generate
go run serve.go
```

and then visit http://localhost:8001/index.html in your browser.
If you put your cursor in the text box and hit control-enter, whatever text you've put in the box is rot13'ed.
Trivial as I said.

But try adding `import _ "log"` to main.go and then `go generate` (that rebuilds the program and writes main.wasm, which the page is downloading) and reload the page.

If you look in the JS console you will see:

```
panic: syscall/js: call of Value.Int on undefined
wasm_exec.js:22 
wasm_exec.js:22 goroutine 1 [running]:
wasm_exec.js:22 syscall/js.Value.float({{}, 0x0, 0x0}, {0x255e5, 0x9})
wasm_exec.js:22 	/Users/rsc/go/src/syscall/js/js.go:523 +0x10
wasm_exec.js:22 syscall/js.Value.Int(...)
wasm_exec.js:22 	/Users/rsc/go/src/syscall/js/js.go:540
wasm_exec.js:22 syscall.init()
wasm_exec.js:22 	/Users/rsc/go/src/syscall/fs_js.go:32 +0x37
```

That line appears to be nodeDIRECTORY in

```
var (
	nodeWRONLY    = constants.Get("O_WRONLY").Int()
	nodeRDWR      = constants.Get("O_RDWR").Int()
	nodeCREATE    = constants.Get("O_CREAT").Int()
	nodeTRUNC     = constants.Get("O_TRUNC").Int()
	nodeAPPEND    = constants.Get("O_APPEND").Int()
	nodeEXCL      = constants.Get("O_EXCL").Int()
	nodeDIRECTORY = constants.Get("O_DIRECTORY").Int()
)
```

I am confused about why that one is failing and not the others.
If I delete just nodeDIRECTORY and its one use, then my program stops crashing in init.

Sure enough, if I look at fs.constants in my browser (recent Chrome), there is no O\_DIRECTORY.

**Comment by rsc** [comment]
Duplicate of #70723. Thanks @gabyhelp.
