### ISSUE TITLE
x/crypto/sha3: sha3 broken on s390x

### ISSUE THREAD

**Issue by jcajka** [golang/go#70810]
### Go version

go version go1.23.2 linux/s390x

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='s390x'
GOBIN=''
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='s390x'
GOHOSTOS='linux'
GOINSECURE=''
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPRIVATE=''
GOPROXY='direct'
GOROOT='/usr/lib/golang'
GOSUMDB='off'
GOTMPDIR=''
GOTOOLCHAIN='local'
GOTOOLDIR='/usr/lib/golang/pkg/tool/linux_s390x'
GOVCS=''
GOVERSION='go1.23.2'
GODEBUG=''
GCCGO='gccgo'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -march=z196 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build429958401=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

go test ./...

### What did you see happen?

[snip]
panic: test timed out after 10m0s
	running tests:
		TestCSHAKELargeS (9m59s)

goroutine 27 [running]:
testing.(*M).startAlarm.func1()
	/usr/lib/golang/src/testing/testing.go:2373 +0x464
created by time.goFunc
	/usr/lib/golang/src/time/sleep.go:215 +0x42

goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc00009a680, {0x1f3110, 0x10}, 0x1fec40)
	/usr/lib/golang/src/testing/testing.go:1751 +0x48e
testing.runTests.func1(0xc00009a680)
	/usr/lib/golang/src/testing/testing.go:2168 +0x62
testing.tRunner(0xc00009a680, 0xc00008eca0)
	/usr/lib/golang/src/testing/testing.go:1690 +0x132
testing.runTests(0xc000092180, {0x319cc0, 0xc, 0xc}, {0xc1cee04b5ea3e990, 0x8bb2cd7205, 0x31e7e0})
	/usr/lib/golang/src/testing/testing.go:2166 +0x4b4
testing.(*M).Run(0xc0000a00a0)
	/usr/lib/golang/src/testing/testing.go:2034 +0x704
main.main()
	_testmain.go:95 +0xd8

goroutine 14 [runnable]:
golang.org/x/crypto/sha3.(*asmState).Read(0xc00072c008, {0xc000732000, 0x200003e8, 0x200003e8})
	/home/jcajka/upstream/crypto/sha3/sha3_s390x.go:194 +0x3d6
golang.org/x/crypto/sha3.TestCSHAKELargeS(0xc00009a4e0)
	/home/jcajka/upstream/crypto/sha3/sha3_test.go:470 +0xf8
testing.tRunner(0xc00009a4e0, 0x1fec40)
	/usr/lib/golang/src/testing/testing.go:1690 +0x132
created by testing.(*T).Run in goroutine 1
	/usr/lib/golang/src/testing/testing.go:1743 +0x46e
FAIL	golang.org/x/crypto/sha3	600.056s
[snip]

### What did you expect to see?

All tests passing. 
It seems that the failure have been introduced in commit https://github.com/golang/crypto/commit/80ea76eb17c0c52f5d5d04e833d6aeb6b062d81d I have suspicion that it might also be related to the removal of the s390x ASM in https://github.com/golang/crypto/commit/59b5a86796b9d310b31d416f56d93b5ce30da22b In that context of losing the optimized path, have you reached out to the original contributor before removing/disabling it?

**Comment by ianlancetaylor** [comment]
CC @golang/security @golang/s390x

**Comment by FiloSottile** [comment]
> I have suspicion that it might also be related to the removal of the s390x ASM in [golang/crypto@59b5a86](https://github.com/golang/crypto/commit/59b5a86796b9d310b31d416f56d93b5ce30da22b) In that context of losing the optimized path, have you reached out to the original contributor before removing/disabling it?

It was tracked in #64897 and reintroduced in CL 554435.

**Comment by jcajka** [comment]
@FiloSottile oh... sorry missed that, cool that it is back.

**Comment by jcajka** [comment]
Just to be clear timeout is still a present issue.

**Comment by jas4711** [comment]
FWIW, we still see this when building golang-go.crypto 0.42.0 on Debian:

https://ci.debian.net/packages/g/golang-go.crypto/unstable/s390x/64861487/#L2024

We have temporarily disabled this self-tests on s390x to get something to pass self tests.

Thanks,
Simon

```
819s === RUN   TestCSHAKELargeS
819s panic: test timed out after 10m0s
819s 	running tests:
819s 		TestCSHAKELargeS (9m53s)
819s 
819s goroutine 34 [running]:
819s testing.(*M).startAlarm.func1()
819s 	/usr/lib/go-1.24/src/testing/testing.go:2484 +0x46a
819s created by time.goFunc
819s 	/usr/lib/go-1.24/src/time/sleep.go:215 +0x42
819s 
819s goroutine 1 [chan receive, 9 minutes]:
819s testing.(*T).Run(0xc000003500, {0x20b398, 0x10}, 0x2178a8)
819s 	/usr/lib/go-1.24/src/testing/testing.go:1859 +0x504
819s testing.runTests.func1(0xc000003500)
819s 	/usr/lib/go-1.24/src/testing/testing.go:2279 +0x62
819s testing.tRunner(0xc000003500, 0xc00008cca0)
819s 	/usr/lib/go-1.24/src/testing/testing.go:1792 +0x132
819s testing.runTests(0xc00000c228, {0x34c1a0, 0xd, 0xd}, {0xc22fd6b28f7cc464, 0x8bb2cb96e4, 0x3510c0})
819s 	/usr/lib/go-1.24/src/testing/testing.go:2277 +0x510
819s testing.(*M).Run(0xc00007e6e0)
819s 	/usr/lib/go-1.24/src/testing/testing.go:2142 +0x6fc
819s main.main()
819s 	_testmain.go:97 +0xd8
819s 
819s goroutine 49 [running]:
819s 	goroutine running on other thread; stack unavailable
819s created by testing.(*T).Run in goroutine 1
819s 	/usr/lib/go-1.24/src/testing/testing.go:1851 +0x4e4
819s FAIL	golang.org/x/crypto/sha3	600.228s
```
