### ISSUE TITLE
runtime: GC failure "failed to find block beginning for"

### ISSUE THREAD

**Issue by bradfitz** [golang/go#9542]
New GC failure:

http://build.golang.org/log/97380f5183f0a50b2429db809f2bee1162b85854

```
ok  	regexp	3.471s
ok  	regexp/syntax	3.823s
runtime: failed to find block beginning for 0x10978000 s=0x10978000 s.limit=0x10979e00
fatal error: failed to find block beginning

runtime stack:
runtime.throw(0x1cc9c8, 0x1e)
	/tmp/buildlet-scatch236986588/src/runtime/panic.go:508 +0x71
runtime.objectstart(0x10978000, 0xdfffe7ac, 0x0)
	/tmp/buildlet-scatch236986588/src/runtime/mgc.go:323 +0x1bf
runtime.shade(0x10978000)
	/tmp/buildlet-scatch236986588/src/runtime/mgc.go:1073 +0x7e
runtime.gcmarkwb_m(0x303b7008, 0x10978000)
	/tmp/buildlet-scatch236986588/src/runtime/mgc.go:1125 +0x82
runtime.func·029()
	/tmp/buildlet-scatch236986588/src/runtime/mgc0.go:273 +0x31
runtime.systemstack(0x10450f00)
	/tmp/buildlet-scatch236986588/src/runtime/asm_386.s:254 +0x56
runtime.mstart()
	/tmp/buildlet-scatch236986588/src/runtime/proc1.go:714

goroutine 65985 [running]:
runtime.systemstack_switch()
	/tmp/buildlet-scatch236986588/src/runtime/asm_386.s:209 fp=0x108ede40 sp=0x108ede3c
runtime.writebarrierptr_nostore1(0x303b7008, 0x10978000)
	/tmp/buildlet-scatch236986588/src/runtime/mgc0.go:274 +0x46 fp=0x108ede58 sp=0x108ede40
runtime.writebarrierptr(0x303b7008, 0x10978000)
	/tmp/buildlet-scatch236986588/src/runtime/mgc0.go:182 +0xb3 fp=0x108ede70 sp=0x108ede58
runtime.mallocgc(0x4, 0x152160, 0x1, 0x103ce230)
	/tmp/buildlet-scatch236986588/src/runtime/malloc.go:137 +0x152 fp=0x108edef8 sp=0x108ede70
runtime.newobject(0x152160, 0x109523c0)
	/tmp/buildlet-scatch236986588/src/runtime/malloc.go:418 +0x47 fp=0x108edf0c sp=0x108edef8
reflect.unsafe_New(0x152160, 0x103ce238)
	/tmp/buildlet-scatch236986588/src/runtime/malloc.go:423 +0x27 fp=0x108edf18 sp=0x108edf0c
reflect.Value.MapKeys(0x152ae0, 0x103ca160, 0x15, 0x0, 0x0, 0x0)
	/tmp/buildlet-scatch236986588/src/reflect/value.go:1060 +0x17b fp=0x108edf74 sp=0x108edf18
runtime_test.func·058()
	/tmp/buildlet-scatch236986588/src/runtime/map_test.go:270 +0x8c fp=0x108edff0 sp=0x108edf74
runtime.goexit()
	/tmp/buildlet-scatch236986588/src/runtime/asm_386.s:2408 +0x1 fp=0x108edff4 sp=0x108edff0
created by runtime_test.testConcurrentReadsAfterGrowth
	/tmp/buildlet-scatch236986588/src/runtime/map_test.go:274 +0x307

goroutine 1 [chan receive]:...
FAIL	runtime	127.651s
```

**Comment by RLH** [comment]
The code that caused this has been completely redesigned for unrelated reasons. Currently object starts are calculated using span info and object size instead of relying on the bit map holding boundary bits. It was the corruption of these boundary bits that resulted in this bug.
