### ISSUE TITLE
x/tools/go/ssa: crash during SSA construction

### ISSUE THREAD

**Issue by alandonovan** [golang/go#9569]
package main

type I interface {
	f() chan int
}

func f(i I) {
	select {
	case <-chan int(nil):
		var i I
	case <-i.f():
	}
}
% ssadump -build=F a.go
panic: no Value for type.Object i

goroutine 17 [running]:
golang.org/x/tools/go/ssa.(*Function).lookup(0xc2080dc140, 0x7f4b4894e730, 0xc2080c63c0, 0x0, 0x0, 0x0)
        /home/adonovan/got5/src/golang.org/x/tools/go/ssa/func.go:429 +0x1d3
golang.org/x/tools/go/ssa.(*builder).addr(0xc208105bb7, 0xc2080dc140, 0x7f4b4894e2b8, 0xc2080c4220, 0x0, 0x0, 0x0)
        /home/adonovan/got5/src/golang.org/x/tools/go/ssa/builder.go:334 +0x2ca
golang.org/x/tools/go/ssa.(*builder).expr(0xc208105bb7, 0xc2080dc140, 0x7f4b4894e2b8, 0xc2080c4220, 0x0, 0x0)
        /home/adonovan/got5/src/golang.org/x/tools/go/ssa/builder.go:463 +0x2c9
golang.org/x/tools/go/ssa.(*builder).receiver(0xc208105bb7, 0xc2080dc140, 0x7f4b4894e2b8, 0xc2080c4220, 0xc2080c0100, 0xc2080c6410, 0x0, 0x0)
        /home/adonovan/got5/src/golang.org/x/tools/go/ssa/builder.go:745 +0x354
golang.org/x/tools/go/ssa.(*builder).setCallFunc(0xc208105bb7, 0xc2080dc140, 0xc20805e280, 0xc208106040)
        /home/adonovan/got5/src/golang.org/x/tools/go/ssa/builder.go:770 +0x1bd
golang.org/x/tools/go/ssa.(*builder).setCall(0xc208105bb7, 0xc2080dc140, 0xc20805e280, 0xc208106040)
        /home/adonovan/got5/src/golang.org/x/tools/go/ssa/builder.go:896 +0x5a
golang.org/x/tools/go/ssa.(*builder).expr0(0xc208105bb7, 0xc2080dc140, 0x7f4b4894e408, 0xc20805e280, 0x7, 0x7f4b4894e6d0, 0xc2080c43e0, 0x0, 0x0, 0x0, ...)
        /home/adonovan/got5/src/golang.org/x/tools/go/ssa/builder.go:531 +0x1a8c
golang.org/x/tools/go/ssa.(*builder).expr(0xc208105bb7, 0xc2080dc140, 0x7f4b4894e408, 0xc20805e280, 0x0, 0x0)
        /home/adonovan/got5/src/golang.org/x/tools/go/ssa/builder.go:465 +0x3c9
golang.org/x/tools/go/ssa.(*builder).selectStmt(0xc208105bb7, 0xc2080dc140, 0xc2080601d0, 0x0)
        /home/adonovan/got5/src/golang.org/x/tools/go/ssa/builder.go:1404 +0x240d
golang.org/x/tools/go/ssa.(*builder).stmt(0xc208105bb7, 0xc2080dc140, 0x7f4b4894e590, 0xc2080601d0)
        /home/adonovan/got5/src/golang.org/x/tools/go/ssa/builder.go:2025 +0xb5e
golang.org/x/tools/go/ssa.(*builder).stmtList(0xc208105bb7, 0xc2080dc140, 0xc2080601e0, 0x1, 0x1)
        /home/adonovan/got5/src/golang.org/x/tools/go/ssa/builder.go:725 +0xa5
golang.org/x/tools/go/ssa.(*builder).stmt(0xc208105bb7, 0xc2080dc140, 0x7f4b4894edd0, 0xc2080b0330)
        /home/adonovan/got5/src/golang.org/x/tools/go/ssa/builder.go:1993 +0x2872
golang.org/x/tools/go/ssa.(*builder).buildFunction(0xc208105bb7, 0xc2080dc140)
        /home/adonovan/got5/src/golang.org/x/tools/go/ssa/builder.go:2086 +0x53a
golang.org/x/tools/go/ssa.(*builder).buildFuncDecl(0xc208105bb7, 0xc2080d2100, 0xc2080b0360)
        /home/adonovan/got5/src/golang.org/x/tools/go/ssa/builder.go:2128 +0x59b
golang.org/x/tools/go/ssa.(*Package).Build(0xc2080d2100)
        /home/adonovan/got5/src/golang.org/x/tools/go/ssa/builder.go:2246 +0x1046
golang.org/x/tools/go/ssa.func·001(0xc2080d2100)
        /home/adonovan/got5/src/golang.org/x/tools/go/ssa/builder.go:2144 +0x31
created by golang.org/x/tools/go/ssa.(*Program).BuildAll
        /home/adonovan/got5/src/golang.org/x/tools/go/ssa/builder.go:2146 +0x155

goroutine 1 [semacquire]:
sync.(*WaitGroup).Wait(0xc2080c44e0)
        /home/adonovan/go/src/sync/waitgroup.go:132 +0x169
golang.org/x/tools/go/ssa.(*Program).BuildAll(0xc2080b20e0)
        /home/adonovan/got5/src/golang.org/x/tools/go/ssa/builder.go:2149 +0xdd
main.doMain(0x0, 0x0)

**Comment by alandonovan** [comment]
Fixed by https://go-review.googlesource.com/#/c/2655/
