### ISSUE TITLE
syscall: slice bounds out of range on OpenBSD 1.4 branch

### ISSUE THREAD

**Issue by bradfitz** [golang/go#9592]
On OpenBSD on the 1.4 release branch:

http://build.golang.org/log/9de1650315308371837119e5cfe31aec797e6089
```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
syscall.(*anyMessage).toRoutingMessage(0xc208056000, 0xc208056000, 0x458, 0x4c7, 0x0, 0x0)
	/tmp/buildlet-scatch342552602/src/syscall/route_openbsd.go:18 +0x4d1
syscall.ParseRoutingMessage(0xc208056000, 0x458, 0x4c7, 0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/buildlet-scatch342552602/src/syscall/route_bsd.go:210 +0x1c5
net.interfaceTable(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/buildlet-scatch342552602/src/net/interface_bsd.go:23 +0x23b
net.Interfaces(0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/buildlet-scatch342552602/src/net/interface.go:81 +0x54
net.loopbackInterface(0xc2080293d0)
	/tmp/buildlet-scatch342552602/src/net/interface_test.go:16 +0x27
net.init·2()
	/tmp/buildlet-scatch342552602/src/net/ipraw_test.go:46 +0x39
net.init()
	/tmp/buildlet-scatch342552602/src/net/cgo_unix.go:164 +0x8ef5
net_test.init()
	/tmp/buildlet-scatch342552602/src/net/example_test.go:36 +0x42
main.init()
	net/_test/_testmain.go:370 +0x4a

goroutine 2 [runnable]:
runtime.forcegchelper()
	/tmp/buildlet-scatch342552602/src/runtime/proc.go:90
runtime.goexit()
	/tmp/buildlet-scatch342552602/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
	/tmp/buildlet-scatch342552602/src/runtime/mgc0.go:82
runtime.goexit()
	/tmp/buildlet-scatch342552602/src/runtime/asm_amd64.s:2232 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
	/tmp/buildlet-scatch342552602/src/runtime/malloc.go:712
runtime.goexit()
	/tmp/buildlet-scatch342552602/src/runtime/asm_amd64.s:2232 +0x1
FAIL	net	0.101s
```

**Comment by mikioh** [comment]
Dup of #9102.
