### ISSUE TITLE
build: race.bat doesn't return an error on failure

### ISSUE THREAD

**Issue by bradfitz** [golang/go#9799]
race.bat doesn't seem to exit with a failure when the build fails.

I just verified that rev ac90d9ab473a says this when I watch it do its live build,

```
ok  	regexp/syntax	7.774s
ok  	runtime	62.079s
?   	runtime/cgo	[no test files]
ok  	runtime/debug	0.457s
fatal error: findfunc: bad findfunctab entry

goroutine 29 [running]:
runtime.throw(0x70dd90, 0x1f)
	C:/workdir/go/src/runtime/panic.go:511 +0x98 fp=0xc082475a38 sp=0xc082475a20
runtime.findfunc(0x609915, 0x4573d8)
	C:/workdir/go/src/runtime/symtab.go:162 +0xeb fp=0xc082475a58 sp=0xc082475a38
runtime.FuncForPC(0x609915, 0x788068)
	C:/workdir/go/src/runtime/symtab.go:125 +0x2f fp=0xc082475a70 sp=0xc082475a58
runtime/pprof_test.func·005(0x1, 0xc08215e168, 0x2, 0xce7b)
	C:/workdir/go/src/runtime/pprof/pprof_test.go:147 +0xb4 fp=0xc082475b60 sp=0xc082475a70
runtime/pprof_test.parseProfile(0xc082049200, 0xc08215e000, 0x6760, 0xcea8, 0xc082475ea0)
	C:/workdir/go/src/runtime/pprof/pprof_test.go:117 +0x928 fp=0xc082475cc0 sp=0xc082475b60
runtime/pprof_test.testCPUProfile(0xc082049200, 0x0, 0x0, 0x0, 0xc082475f58)
	C:/workdir/go/src/runtime/pprof/pprof_test.go:157 +0x3e5 fp=0xc082475f30 sp=0xc082475cc0
runtime/pprof_test.TestMathBigDivide(0xc082049200)
	C:/workdir/go/src/runtime/pprof/pprof_test.go:303 +0x80 fp=0xc082475f70 sp=0xc082475f30
testing.tRunner(0xc082049200, 0x11d6138)
	C:/workdir/go/src/testing/testing.go:448 +0x142 fp=0xc082475fd0 sp=0xc082475f70
runtime.goexit()
	C:/workdir/go/src/runtime/asm_amd64.s:2446 +0x1 fp=0xc082475fd8 sp=0xc082475fd0
created by testing.RunTests
	C:/workdir/go/src/testing/testing.go:556 +0xc85

goroutine 1 [chan receive]:
testing.RunTests(0x758678, 0x11d60c0, 0xc, 0xc, 0x1)
	C:/workdir/go/src/testing/testing.go:557 +0xce1
testing.(*M).Run(0xc08200c280, 0x11fb7a0)
	C:/workdir/go/src/testing/testing.go:486 +0xe8
main.main()
	runtime/pprof/_test/_testmain.go:76 +0x294

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	C:/workdir/go/src/runtime/asm_amd64.s:2446 +0x1
FAIL	runtime/pprof	14.129s
ok  	runtime/race	15.755s
ok  	sort	1.513s
ok  	strconv	4.073s
ok  	strings	2.181s
```

... but the build coordinator sees a successful exit status from it, so it reports "ok" to the dashboard.

/cc @dvyukov @alexbrainman @minux @adg for anybody who can help with Windows batch files.

**Comment by minux** [comment]
I went through the race.bat file, but it looks correct.

```
go test -race -short std
if errorlevel 1 goto fail
```

**Comment by dvyukov** [comment]
I suspect you need to set GOBUILDEXIT=1 env var.
Windows scripts do not do 'exit 1' by default, because if you run it from command line, that would close terminal windows as well.
This relates to all of all.bat, make.bat and race.bat.

**Comment by alexbrainman** [comment]
I am pretty sure @dvyukov is correct. Our old windows builder used to do that.

Alex

**Comment by bradfitz** [comment]
Indeed, thanks!

```
$ git grep GOBUILDEXIT
cmd/builder/env.go:                     "GOBUILDEXIT":  "1", // exit all.bat with completion status.
```

That's an easy fix.

**Comment by bradfitz** [comment]
I've purged all the Windows builds and they're rebuilding.

Fix is part of https://go-review.googlesource.com/4132
