### ISSUE TITLE
syscall: NewCallback panics when given a callback function with no input parameters

### ISSUE THREAD

**Issue by oxtoacart** [golang/go#9871]
Go 1.4.1 on Windows XP 32-bit (386)

The below program panics:

```go
package main

import (
        "log"
        "syscall"
)

func main() {
        cb := syscall.NewCallback(callback)
        log.Println(cb)
}

func callback() uintptr {
        return 0
}
```

```bash
$ go run callback.go
panic: runtime error: index out of range

goroutine 1 [running]:
syscall.NewCallback(0x499ba0, 0x4dfb68, 0x434503)
        c:/go/src/syscall/syscall_windows.go:115 +0x35
main.main()
        c:/Documents and Settings/Administrator/gocode/src/callback.go:9 +0x3a

goroutine 3 [runnable]:
runtime.bgsweep()
        c:/go/src/runtime/mgc0.go:82
runtime.goexit()
        c:/go/src/runtime/asm_386.s:2287 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
        c:/go/src/runtime/malloc.go:712
runtime.goexit()
        c:/go/src/runtime/asm_386.s:2287 +0x1
exit status 2
```

However this program does not panic:

```go
package main

import (
        "log"
        "syscall"
)

func main() {
        cb := syscall.NewCallback(callback)
        log.Println(cb)
}

func callback(ignored uintptr) uintptr {
        return 0
}
```

It seems that `syscall.NewCallback` requires the callback function to have at least one input parameter.  Note that in Go 1.3.3 it did not require the callback function to have at least one input parameter, so to avoid breaking existing code, it should probably continue not to require it.  However, if it does continue to require an input parameter, it should at least return a human-readable error and the documentation for the function should make that clear.

Note also that I get the same result with syscall.NewCallbackCDecl.

**Comment by minux** [comment]
It has been fixed on tip, and the following patch should fix it in 1.4.1.

```
--- src/runtime/syscall_windows.go 2015-02-14 00:09:23.834294000 -0500
+++ src/runtime/syscall_windows.go  2015-02-14 00:09:50.474651894 -0500
@@ -54,11 +54,13 @@ func compileCallback(fn eface, cleanstac
                panic("compilecallback: output parameter size is wrong")
        }
        argsize := uintptr(0)
-       for _, t := range (*[1024](*_type))(unsafe.Pointer(&ft.in[0]))[:len(ft.in)] {
-               if (*t).size > uintptrSize {
-                       panic("compilecallback: input parameter size is wrong")
+       if len(ft.in) > 0 {
+               for _, t := range (*[1024](*_type))(unsafe.Pointer(&ft.in[0]))[:len(ft.in)] {
+                       if (*t).size > uintptrSize {
+                               panic("compilecallback: input parameter size is wrong")
+                       }
+                       argsize += uintptrSize
                }
-               argsize += uintptrSize
        }
 
        lock(&cbs.lock)
```

I'm not sure if we want to fix it for 1.4.2 or not. Tentatively labeled Go1.4.2.

**Comment by oxtoacart** [comment]
@minux Thanks!

**Comment by adg** [comment]
@minux your patch does not apply cleanly to release-branch.go1.4. Did I miss a change go by?

**Comment by minux** [comment]
I will send a CL against release-branch.go1.4.
