### ISSUE TITLE
debug/gosym: tests fail when externally linked

### ISSUE THREAD

**Issue by mwhudson** [golang/go#9912]
This once again falls into the "maybe we don't really care" category, but:

```shellsession
mwhudson@narsil:src$ go.master test -ldflags '-linkmode external' debug/gosym -short
--- FAIL: TestLineFromAline (0.17s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x58 pc=0x4f89e2]

goroutine 4 [running]:
testing.func·006(0xc208064000)
	/opt/opensource/go.master/src/testing/testing.go:442 +0x179
debug/elf.(*Section).Data(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/opensource/go.master/src/debug/elf/file.go:77 +0x42
debug/gosym.parse(0x7fffceb44e7f, 0x33, 0xc2080601e0, 0xc208064000, 0x0, 0x0)
	/opt/opensource/go.master/src/debug/gosym/pclntab_test.go:87 +0x5b
debug/gosym.crack(0x7fffceb44e7f, 0x33, 0xc208064000, 0x47d88f, 0xc208030d10)
	/opt/opensource/go.master/src/debug/gosym/pclntab_test.go:83 +0x148
debug/gosym.getTable(0xc208064000, 0x641a10)
	/opt/opensource/go.master/src/debug/gosym/pclntab_test.go:72 +0x4c
debug/gosym.TestLineFromAline(0xc208064000)
	/opt/opensource/go.master/src/debug/gosym/pclntab_test.go:116 +0x78
testing.tRunner(0xc208064000, 0x8d0840)
	/opt/opensource/go.master/src/testing/testing.go:448 +0xad
created by testing.RunTests
	/opt/opensource/go.master/src/testing/testing.go:556 +0xa4c

goroutine 1 [chan receive]:
testing.RunTests(0x641a98, 0x8d0840, 0x3, 0x3, 0x1)
	/opt/opensource/go.master/src/testing/testing.go:557 +0xa8c
testing.(*M).Run(0xc20805a0a0, 0x903c40)
	/opt/opensource/go.master/src/testing/testing.go:486 +0x79
main.main()
	debug/gosym/_test/_testmain.go:56 +0x1d5
FAIL	debug/gosym	0.173s
```

The immediate failure is that f.Section(".gosymtab") is returning nil (because there is indeed no section with this name in an externally linked binary) and this is not being checked before .Data() is called on the return value.  I don't know if debug/gosym is expected to work in the external linking case but the failure mode seems unfortunate.

**Comment by rsc** [comment]
The failure error should be made clearer. I think this can only work without external linking, and that's fine. It's testing legacy code.

**Comment by mwhudson** [comment]
I forgot to tag the issue in the CL that fixed this.
