### ISSUE TITLE
runtime: nacl-386 unexpected return pc

### ISSUE THREAD

**Issue by bradfitz** [golang/go#9931]
The nacl-386 builder has been occasionally failing with:

```
...
ok  	reflect	0.218s
ok  	regexp	0.837s
ok  	regexp/syntax	1.185s
ok  	runtime	9.114s
ok  	runtime/debug	0.675s
runtime: unexpected return pc for runtime.getg called from 0x108a4240
fatal error: unknown caller pc

runtime stack:
runtime.throw(0x238228, 0x11)
	/tmp/buildlet-scatch290161130/go/src/runtime/panic.go:511 +0x100 fp=0x10881cf4 sp=0x10881ce8
runtime.gentraceback(0x6f660, 0x10818fdc, 0x0, 0x10800d20, 0x0, 0x0, 0x7fffffff, 0x10881dd4, 0x0, 0x0, ...)
	/tmp/buildlet-scatch290161130/go/src/runtime/traceback.go:234 +0x1120 fp=0x10881d8c sp=0x10881cf4
runtime.scanstack(0x10800d20)
	/tmp/buildlet-scatch290161130/go/src/runtime/mgc.go:747 +0x3a0 fp=0x10881de0 sp=0x10881d8c
runtime.gcphasework(0x10800d20)
	/tmp/buildlet-scatch290161130/go/src/runtime/mgc.go:853 +0xc0 fp=0x10881dec sp=0x10881de0
runtime.stopg(0x10800d20, 0x1)
	/tmp/buildlet-scatch290161130/go/src/runtime/proc1.go:395 +0xc0 fp=0x10881e00 sp=0x10881dec
runtime.markroot(0x1080e000, 0xf)
	/tmp/buildlet-scatch290161130/go/src/runtime/mgc.go:595 +0x260 fp=0x10881e48 sp=0x10881e00
runtime.parfordo(0x1080e000)
	/tmp/buildlet-scatch290161130/go/src/runtime/parfor.go:95 +0x1c0 fp=0x10881ea4 sp=0x10881e48
runtime.gc(0x9254200d, 0x13c42a5b, 0x0)
	/tmp/buildlet-scatch290161130/go/src/runtime/mgc.go:1490 +0x3a0 fp=0x10881fbc sp=0x10881ea4
runtime.gc_m(0x9254200d, 0x13c42a5b, 0x10886000)
	/tmp/buildlet-scatch290161130/go/src/runtime/mgc.go:1291 +0xc0 fp=0x10881fd0 sp=0x10881fbc
runtime.gcwork.func1()
	/tmp/buildlet-scatch290161130/go/src/runtime/malloc.go:434 +0x60 fp=0x10881fe0 sp=0x10881fd0
runtime.systemstack(0x10810500)
	/tmp/buildlet-scatch290161130/go/src/runtime/asm_386.s:254 +0x80 fp=0x10881fe4 sp=0x10881fe0
runtime.mstart()
	/tmp/buildlet-scatch290161130/go/src/runtime/proc1.go:667 fp=0x10881fe8 sp=0x10881fe4

goroutine 6 [garbage collection]:
runtime.systemstack_switch()
	/tmp/buildlet-scatch290161130/go/src/runtime/asm_386.s:209 fp=0x10818784 sp=0x10818780
runtime.gcwork(0x0)
	/tmp/buildlet-scatch290161130/go/src/runtime/malloc.go:435 +0x4c0 fp=0x108187dc sp=0x10818784
runtime.backgroundgc()
	/tmp/buildlet-scatch290161130/go/src/runtime/mgc0.go:66 +0x80 fp=0x108187f0 sp=0x108187dc
runtime.goexit()
	/tmp/buildlet-scatch290161130/go/src/runtime/asm_386.s:2410 +0x1 fp=0x108187f4 sp=0x108187f0
created by runtime.gogc
	/tmp/buildlet-scatch290161130/go/src/runtime/malloc.go:343 +0x120

goroutine 1 [chan receive]:
runtime.gopark(0x273fe4, 0x108a4230, 0x22f2a8, 0xc, 0x3efc0017)
	/tmp/buildlet-scatch290161130/go/src/runtime/proc.go:153 +0x1a0 fp=0x108195d8 sp=0x108195c0
runtime.goparkunlock(0x108a4230, 0x22f2a8, 0xc, 0x1084e317)
	/tmp/buildlet-scatch290161130/go/src/runtime/proc.go:159 +0x60 fp=0x108195f0 sp=0x108195d8
runtime.chanrecv(0x1ca460, 0x108a4200, 0x108196e4, 0x10882e01, 0xa0000)
	/tmp/buildlet-scatch290161130/go/src/runtime/chan.go:417 +0x4e0 fp=0x1081963c sp=0x108195f0
runtime.chanrecv1(0x1ca460, 0x108a4200, 0x108196e4)
	/tmp/buildlet-scatch290161130/go/src/runtime/chan.go:318 +0x40 fp=0x10819654 sp=0x1081963c
testing.RunTests(0x273db8, 0x6513e0, 0x6, 0x6, 0x1083a401)
	/tmp/buildlet-scatch290161130/go/src/testing/testing.go:557 +0xae0 fp=0x10819728 sp=0x10819654
testing.(*M).Run(0x108360f0, 0x66b080)
	/tmp/buildlet-scatch290161130/go/src/testing/testing.go:486 +0xe0 fp=0x1081976c sp=0x10819728
main.main()
	runtime/pprof/_test/_testmain.go:64 +0x200 fp=0x108197d0 sp=0x1081976c
runtime.main()
	/tmp/buildlet-scatch290161130/go/src/runtime/proc.go:88 +0x260 fp=0x108197f0 sp=0x108197d0
runtime.goexit()
	/tmp/buildlet-scatch290161130/go/src/runtime/asm_386.s:2410 +0x1 fp=0x108197f4 sp=0x108197f0

goroutine 2 [force gc (idle)]:
runtime.gopark(0x273fe4, 0x656378, 0x22f8a8, 0xf, 0x10800214)
	/tmp/buildlet-scatch290161130/go/src/runtime/proc.go:153 +0x1a0 fp=0x108167c4 sp=0x108167ac
runtime.goparkunlock(0x656378, 0x22f8a8, 0xf, 0x10800014)
	/tmp/buildlet-scatch290161130/go/src/runtime/proc.go:159 +0x60 fp=0x108167dc sp=0x108167c4
runtime.forcegchelper()
	/tmp/buildlet-scatch290161130/go/src/runtime/proc.go:121 +0xe0 fp=0x108167f0 sp=0x108167dc
runtime.goexit()
	/tmp/buildlet-scatch290161130/go/src/runtime/asm_386.s:2410 +0x1 fp=0x108167f4 sp=0x108167f0
created by runtime.init.4
	/tmp/buildlet-scatch290161130/go/src/runtime/proc.go:110 +0x40

goroutine 3 [finalizer wait]:
runtime.gopark(0x273fe4, 0x66b28c, 0x22f668, 0xe, 0x10800314)
	/tmp/buildlet-scatch290161130/go/src/runtime/proc.go:153 +0x1a0 fp=0x10816fa0 sp=0x10816f88
runtime.goparkunlock(0x66b28c, 0x22f668, 0xe, 0x14)
	/tmp/buildlet-scatch290161130/go/src/runtime/proc.go:159 +0x60 fp=0x10816fb8 sp=0x10816fa0
runtime.runfinq()
	/tmp/buildlet-scatch290161130/go/src/runtime/mfinal.go:132 +0xe0 fp=0x10816ff0 sp=0x10816fb8
runtime.goexit()
	/tmp/buildlet-scatch290161130/go/src/runtime/asm_386.s:2410 +0x1 fp=0x10816ff4 sp=0x10816ff0
created by runtime.createfing
	/tmp/buildlet-scatch290161130/go/src/runtime/mfinal.go:113 +0x80

goroutine 4 [syscall]:
runtime.notetsleepg(0x6564ec, 0xd2367ae7, 0x1b, 0x2)
	/tmp/buildlet-scatch290161130/go/src/runtime/lock_sema.go:262 +0xc0 fp=0x10817790 sp=0x10817768
runtime.timerproc()
	/tmp/buildlet-scatch290161130/go/src/runtime/time.go:209 +0x180 fp=0x108177f0 sp=0x10817790
runtime.goexit()
	/tmp/buildlet-scatch290161130/go/src/runtime/asm_386.s:2410 +0x1 fp=0x108177f4 sp=0x108177f0
created by runtime.addtimerLocked
	/tmp/buildlet-scatch290161130/go/src/runtime/time.go:116 +0x220

goroutine 7 [GC sweep wait]:
runtime.gopark(0x273fe4, 0x66b294, 0x22dec8, 0xd, 0x10800514)
	/tmp/buildlet-scatch290161130/go/src/runtime/proc.go:153 +0x1a0 fp=0x10817fc4 sp=0x10817fac
runtime.goparkunlock(0x66b294, 0x22dec8, 0xd, 0x1084e114)
	/tmp/buildlet-scatch290161130/go/src/runtime/proc.go:159 +0x60 fp=0x10817fdc sp=0x10817fc4
runtime.bgsweep()
	/tmp/buildlet-scatch290161130/go/src/runtime/mgc0.go:89 +0x120 fp=0x10817ff0 sp=0x10817fdc
runtime.goexit()
	/tmp/buildlet-scatch290161130/go/src/runtime/asm_386.s:2410 +0x1 fp=0x10817ff4 sp=0x10817ff0
created by runtime.gc
	/tmp/buildlet-scatch290161130/go/src/runtime/mgc.go:1597 +0x1600

goroutine 14 [semacquire]:
runtime.gopark(0x273fe4, 0x65afe0, 0x22a748, 0xa, 0x10836019)
	/tmp/buildlet-scatch290161130/go/src/runtime/proc.go:153 +0x1a0 fp=0x10814eb4 sp=0x10814e9c
runtime.goparkunlock(0x65afe0, 0x22a748, 0xa, 0x19)
	/tmp/buildlet-scatch290161130/go/src/runtime/proc.go:159 +0x60 fp=0x10814ecc sp=0x10814eb4
runtime.semacquire(0x640034, 0x108a0000)
	/tmp/buildlet-scatch290161130/go/src/runtime/sema.go:100 +0x300 fp=0x10814ef0 sp=0x10814ecc
runtime.GOMAXPROCS(0x1, 0x1083a320)
	/tmp/buildlet-scatch290161130/go/src/runtime/debug.go:25 +0xc0 fp=0x10814f04 sp=0x10814ef0
runtime/pprof_test.TestTraceStress(0x1084e3c0)
	/tmp/buildlet-scatch290161130/go/src/runtime/pprof/trace_test.go:198 +0xca0 fp=0x10814fbc sp=0x10814f04
testing.tRunner(0x1084e3c0, 0x651410)
	/tmp/buildlet-scatch290161130/go/src/testing/testing.go:448 +0x100 fp=0x10814fe8 sp=0x10814fbc
runtime.goexit()
	/tmp/buildlet-scatch290161130/go/src/runtime/asm_386.s:2410 +0x1 fp=0x10814fec sp=0x10814fe8
created by testing.RunTests
	/tmp/buildlet-scatch290161130/go/src/testing/testing.go:556 +0xaa0

goroutine 17 [trace reader (blocked)]:
runtime.gopark(0x273fe4, 0x663020, 0x23be48, 0x16, 0x10800b14)
	/tmp/buildlet-scatch290161130/go/src/runtime/proc.go:153 +0x1a0 fp=0x10815f28 sp=0x10815f10
runtime.goparkunlock(0x663020, 0x23be48, 0x16, 0x1084e414)
	/tmp/buildlet-scatch290161130/go/src/runtime/proc.go:159 +0x60 fp=0x10815f40 sp=0x10815f28
runtime.ReadTrace(0x0, 0x0, 0x0)
	/tmp/buildlet-scatch290161130/go/src/runtime/trace.go:306 +0x2e0 fp=0x10815fbc sp=0x10815f40
runtime/pprof.StartTrace.func1(0x3efde770, 0x1084e480)
	/tmp/buildlet-scatch290161130/go/src/runtime/pprof/pprof.go:629 +0x40 fp=0x10815fe8 sp=0x10815fbc
runtime.goexit()
	/tmp/buildlet-scatch290161130/go/src/runtime/asm_386.s:2410 +0x1 fp=0x10815fec sp=0x10815fe8
created by runtime/pprof.StartTrace
	/tmp/buildlet-scatch290161130/go/src/runtime/pprof/pprof.go:635 +0xa0

goroutine 18 [runnable, locked to thread]:
runtime.traceGoEnd()
	/tmp/buildlet-scatch290161130/go/src/runtime/trace.go:758 fp=0x10818fe0 sp=0x10818fdc
runtime.goexit1()
	/tmp/buildlet-scatch290161130/go/src/runtime/proc1.go:1540 +0x20 fp=0x10818fe8 sp=0x10818fe0
runtime.getg(0x0)
	/tmp/buildlet-scatch290161130/go/src/runtime/asm_386.s:2414 fp=0x10818fec sp=0x10818fe8
created by runtime/pprof_test.TestTraceStress
	/tmp/buildlet-scatch290161130/go/src/runtime/pprof/trace_test.go:123 +0x500

goroutine 45 [select (no cases)]:
runtime.gopark(0x0, 0x0, 0x237b88, 0x11, 0x273f10)
	/tmp/buildlet-scatch290161130/go/src/runtime/proc.go:153 +0x1a0 fp=0x160ca7d4 sp=0x160ca7bc
runtime.block()
	/tmp/buildlet-scatch290161130/go/src/runtime/select.go:176 +0x60 fp=0x160ca7ec sp=0x160ca7d4
runtime/pprof_test.TestTraceStress.func9()
	/tmp/buildlet-scatch290161130/go/src/runtime/pprof/trace_test.go:189 +0x60 fp=0x160ca7f0 sp=0x160ca7ec
runtime.goexit()
	/tmp/buildlet-scatch290161130/go/src/runtime/asm_386.s:2410 +0x1 fp=0x160ca7f4 sp=0x160ca7f0
created by runtime/pprof_test.TestTraceStress
	/tmp/buildlet-scatch290161130/go/src/runtime/pprof/trace_test.go:190 +0xb80
FAIL	runtime/pprof	0.594s
?   	runtime/race	[no test files]
ok  	sort	0.200s
ok  	strconv	1.742s
ok  	strings	0.210s
ok  	sync	0.187s
ok  	sync/atomic	0.398s
...
```

/cc @aclements @dvyukov @minux @randall77

**Comment by dvyukov** [comment]
I think it's mine.
