### ISSUE TITLE
runtime/pprof: TestTraceStressStartStop "out of memory" on Plan 9

### ISSUE THREAD

**Issue by 0intro** [golang/go#9952]
In CL 3601, TestTraceStressStartStop was added in the runtime/pprof package.

However, this test is failing on Plan 9:

```
fatal error: trace: out of memory

goroutine 55 [running]:
runtime.throw(0x19eaa8, 0x14)
	/usr/go/src/runtime/panic.go:511 +0x81 fp=0x103a3dd4 sp=0x103a3dc8
runtime.traceFlush(0x0, 0x3)
	/usr/go/src/runtime/trace.go:527 +0x200 fp=0x103a3e00 sp=0x103a3dd4
runtime.traceEvent(0x10d, 0x103a3eb8, 0x2, 0x2)
	/usr/go/src/runtime/trace.go:427 +0x692 fp=0x103a3ea8 sp=0x103a3e00
runtime.traceGoCreate(0x103860a0, 0x22ef0)
	/usr/go/src/runtime/trace.go:750 +0x99 fp=0x103a3ed8 sp=0x103a3ea8
runtime.StartTrace(0x0, 0x0)
	/usr/go/src/runtime/trace.go:151 +0x156 fp=0x103a3f34 sp=0x103a3ed8
runtime/pprof.StartTrace(0x303a5318, 0x103f8000, 0x0, 0x0)
	/usr/go/src/runtime/pprof/pprof.go:624 +0x2a fp=0x103a3f50 sp=0x103a3f34
runtime/pprof_test.TestTraceStressStartStop(0x103f8240)
	/usr/go/src/runtime/pprof/trace_test.go:337 +0xea fp=0x103a3fbc sp=0x103a3f50
testing.tRunner(0x103f8240, 0x25d1e4)
	/usr/go/src/testing/testing.go:448 +0x9f fp=0x103a3fe8 sp=0x103a3fbc
runtime.goexit()
	/usr/go/src/runtime/asm_386.s:2431 +0x1 fp=0x103a3fec sp=0x103a3fe8
created by testing.RunTests
	/usr/go/src/testing/testing.go:556 +0x847

goroutine 1 [chan receive]:
testing.RunTests(0x1d4948, 0x25d160, 0xd, 0xd, 0x5ccc6001)
	/usr/go/src/testing/testing.go:557 +0x879
testing.(*M).Run(0x103d8060, 0x273000)
	/usr/go/src/testing/testing.go:486 +0x6a
main.main()
	runtime/pprof/_test/_testmain.go:78 +0x176

goroutine 56 [runnable]:
runtime/pprof_test.TestTraceStressStartStop.func1(0x103f0740, 0x103f8240)
	/usr/go/src/runtime/pprof/trace_test.go:262 +0x270
created by runtime/pprof_test.TestTraceStressStartStop
	/usr/go/src/runtime/pprof/trace_test.go:333 +0x9b

goroutine 59 [syscall]:
syscall.Syscall6(0x3, 0x103a4fcf, 0x1, 0xffffffff, 0xffffffff, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/go/src/syscall/asm_plan9_386.s:57 +0x5
syscall.Pread(0x3, 0x103a4fcf, 0x1, 0x1, 0xffffffff, 0xffffffff, 0x103aa1e8, 0x0, 0x0)
	/usr/go/src/syscall/zsyscall_plan9_386.go:121 +0x75
syscall.Read(0x3, 0x103a4fcf, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/go/src/syscall/syscall_plan9.go:123 +0x5b
os.(*File).read(0x103aa398, 0x103a4fcf, 0x1, 0x1, 0x168980c0, 0x0, 0x0)
	/usr/go/src/os/file_plan9.go:248 +0x50
os.(*File).Read(0x103aa398, 0x103a4fcf, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/go/src/os/file.go:95 +0x71
runtime/pprof_test.TestTraceStressStartStop.func1.4(0x103aa398, 0x103f0780, 0x14554420)
	/usr/go/src/runtime/pprof/trace_test.go:241 +0x59
created by runtime/pprof_test.TestTraceStressStartStop.func1
	/usr/go/src/runtime/pprof/trace_test.go:244 +0x202

goroutine 58 [chan receive]:
runtime/pprof_test.TestTraceStressStartStop.func1.2(0x103f0780, 0x14554420)
	/usr/go/src/runtime/pprof/trace_test.go:226 +0x37
created by runtime/pprof_test.TestTraceStressStartStop.func1
	/usr/go/src/runtime/pprof/trace_test.go:228 +0xb9

goroutine 97 [select (no cases)]:
runtime/pprof_test.TestTraceStress.func9()
	/usr/go/src/runtime/pprof/trace_test.go:190 +0x22
created by runtime/pprof_test.TestTraceStress
	/usr/go/src/runtime/pprof/trace_test.go:191 +0x819

goroutine 98 [runnable, locked to thread]:
runtime.Gosched()
	/usr/go/src/runtime/proc.go:135 +0x10
runtime/pprof_test.TestTraceStressStartStop.func1.5(0x103f0780)
	/usr/go/src/runtime/pprof/trace_test.go:254 +0x4f
created by runtime/pprof_test.TestTraceStressStartStop.func1
	/usr/go/src/runtime/pprof/trace_test.go:257 +0x232
FAIL	runtime/pprof	14.315s
```

**Comment by 0intro** [comment]
```
cpu% go test -v -run TestTraceStressStartStop
sysAlloc(262144, 0x27a080) -> 0x30387000
sysAlloc(65536, 0x27a080) -> 0x303c7000
sysAlloc(719996, 0x27a070) -> 0x303d7000
=== RUN TestTraceStressStartStop
sysAlloc(65536, 0x27a080) -> 0x30487000
sysAlloc(65536, 0x27a080) -> 0x30497000
sysAlloc(65536, 0x27a080) -> 0x304a7000
sysAlloc(65536, 0x27a080) -> 0x304b7000
sysAlloc(65536, 0x27a080) -> 0x304c7000
0 make(1048576)
sysAlloc(65536, 0x27a080) -> 0x304d7000
sysAlloc(65536, 0x27a080) -> 0x304e7000
sysFree(65536, 0x27a080)
sysFree(65536, 0x27a080)
sysFree(65536, 0x27a080)
sysFree(65536, 0x27a080)
sysFree(65536, 0x27a080)
sysFree(65536, 0x27a080)
sysFree(65536, 0x27a080)
1 make(1048576)
sysAlloc(65536, 0x27a080) -> 0x0
fatal error: trace: out of memory
```

**Comment by dvyukov** [comment]
Seems to be a dup of #9803 and #9736
