### ISSUE TITLE
build error on windows 32bit

### ISSUE THREAD

**Issue by mattn** [golang/go#9973]
Compiling git HEAD. This is part of console output.
```
# cmd/internal/gc
runtime: garbage collector found invalid heap pointer *(0x74bfa0+0xc0c)=0x31fd0000 s=nil
fatal error: invalid heap pointer

runtime stack:
runtime.throw(0x737b03)
        c:/go/src/runtime/panic.go:491 +0x83 fp=0x6fc68 sp=0x6fc50
scanblock(0x74bfa0, 0xe980, 0x18c9d8)
        c:/go/src/runtime/mgc0.c:378 +0x48d fp=0x6fd08 sp=0x6fc68
markroot(0x1192e0f0, 0x1)
        c:/go/src/runtime/mgc0.c:496 +0x139 fp=0x6fd40 sp=0x6fd08
runtime.parfordo(0x1192e0f0)
        c:/go/src/runtime/parfor.c:76 +0x99 fp=0x6fd9c sp=0x6fd40
gc(0x6fed8)
        c:/go/src/runtime/mgc0.c:1439 +0x1fb fp=0x6fec8 sp=0x6fd9c
runtime.gc_m()
        c:/go/src/runtime/mgc0.c:1368 +0xd2 fp=0x6fee8 sp=0x6fec8
runtime.onM(0x74cef8)
        c:/go/src/runtime/asm_386.s:266 +0x50 fp=0x6feec sp=0x6fee8
runtime.mstart()
        c:/go/src/runtime/proc.c:818 fp=0x6fef0 sp=0x6feec

goroutine 1 [garbage collection]:
runtime.switchtoM()
        c:/go/src/runtime/asm_386.s:208 fp=0x27033a2c sp=0x27033a28
runtime.gogc(0x0)
        c:/go/src/runtime/malloc.go:469 +0x1aa fp=0x27033a4c sp=0x27033a2c
runtime.mallocgc(0x30, 0x605c80, 0x1, 0x23e1cae7)
        c:/go/src/runtime/malloc.go:341 +0x2c4 fp=0x27033aa4 sp=0x27033a4c
runtime.newarray(0x605c80, 0x25, 0x5b1814)
        c:/go/src/runtime/malloc.go:365 +0xb5 fp=0x27033ac4 sp=0x27033aa4
runtime.makeslice(0x6008c0, 0x25, 0x0, 0x25, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/runtime/slice.go:32 +0x165 fp=0x27033af4 sp=0x27033ac4
strings.Replace(0x17bd5710, 0x25, 0x638ff8, 0x1, 0x637638, 0x1, 0x6, 0x0, 0x0)
        c:/go/src/strings/strings.go:688 +0x10f fp=0x27033b54 sp=0x27033af4
path/filepath.ToSlash(0x17bd5710, 0x25, 0x0, 0x0)
        c:/go/src/path/filepath/path.go:162 +0x62 fp=0x27033b7c sp=0x27033b54
bootstrap/internal/obj.wrpath(0x1195e000, 0x23c02260, 0x17bd5710, 0x25)
        c:/go/pkg/bootstrap/src/bootstrap/internal/obj/objfile.go:396 +0x30 fp=0x27033b98 sp=0x27033b7c
bootstrap/internal/obj.wrpathsym(0x1195e000, 0x23c02260, 0x26e23680)
        c:/go/pkg/bootstrap/src/bootstrap/internal/obj/objfile.go:411 +0x80 fp=0x27033bac sp=0x27033b98
bootstrap/internal/obj.writesym(0x1195e000, 0x23c02260, 0x176e5800)
        c:/go/pkg/bootstrap/src/bootstrap/internal/obj/objfile.go:369 +0x17a8 fp=0x27033ca8 sp=0x27033bac
bootstrap/internal/obj.Writeobjdirect(0x1195e000, 0x23c02260)
        c:/go/pkg/bootstrap/src/bootstrap/internal/obj/objfile.go:224 +0x412 fp=0x27033d50 sp=0x27033ca8
bootstrap/internal/gc.dumpobj()
        c:/go/pkg/bootstrap/src/bootstrap/internal/gc/obj.go:97 +0xad3 fp=0x27033e44 sp=0x27033d50
bootstrap/internal/gc.Main()
        c:/go/pkg/bootstrap/src/bootstrap/internal/gc/lex.go:478 +0x1cbf fp=0x27033fb8 sp=0x27033e44
main.main()
        c:/go/pkg/bootstrap/src/bootstrap/8g/galign.go:85 +0x46a fp=0x27033fcc sp=0x27033fb8
runtime.main()
        c:/go/src/runtime/proc.go:63 +0xcc fp=0x27033ff0 sp=0x27033fcc
runtime.goexit()
        c:/go/src/runtime/asm_386.s:2287 +0x1 fp=0x27033ff4 sp=0x27033ff0

goroutine 2 [force gc (idle)]:
runtime.gopark(0x442b80, 0x74c6a0, 0x650b68, 0xf)
        c:/go/src/runtime/proc.go:130 +0xde fp=0x11940fcc sp=0x11940fb4
runtime.goparkunlock(0x74c6a0, 0x650b68, 0xf)
        c:/go/src/runtime/proc.go:136 +0x42 fp=0x11940fe0 sp=0x11940fcc
runtime.forcegchelper()
        c:/go/src/runtime/proc.go:99 +0xa3 fp=0x11940ff0 sp=0x11940fe0
runtime.goexit()
        c:/go/src/runtime/asm_386.s:2287 +0x1 fp=0x11940ff4 sp=0x11940ff0
created by runtime.init·4
        c:/go/src/runtime/proc.go:87 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x442b80, 0x75abb0, 0x64ea68, 0xd)
        c:/go/src/runtime/proc.go:130 +0xde fp=0x11942fcc sp=0x11942fb4
runtime.goparkunlock(0x75abb0, 0x64ea68, 0xd)
        c:/go/src/runtime/proc.go:136 +0x42 fp=0x11942fe0 sp=0x11942fcc
runtime.bgsweep()
        c:/go/src/runtime/mgc0.go:98 +0x97 fp=0x11942ff0 sp=0x11942fe0
runtime.goexit()
        c:/go/src/runtime/asm_386.s:2287 +0x1 fp=0x11942ff4 sp=0x11942ff0
created by gc
        c:/go/src/runtime/mgc0.c:1383

goroutine 4 [finalizer wait]:
runtime.gopark(0x442b80, 0x75abac, 0x6508e8, 0xe)
        c:/go/src/runtime/proc.go:130 +0xde fp=0x1193df98 sp=0x1193df80
runtime.goparkunlock(0x75abac, 0x6508e8, 0xe)
        c:/go/src/runtime/proc.go:136 +0x42 fp=0x1193dfac sp=0x1193df98
runtime.runfinq()
        c:/go/src/runtime/malloc.go:727 +0x9c fp=0x1193dff0 sp=0x1193dfac
runtime.goexit()
        c:/go/src/runtime/asm_386.s:2287 +0x1 fp=0x1193dff4 sp=0x1193dff0
created by runtime.createfing
        c:/go/src/runtime/malloc.go:707 +0x59
```

**Comment by randall77** [comment]
Probably dup of #9954

**Comment by randall77** [comment]
Try updating your Go1.4 to 1.4.2 and see if that helps.

**Comment by mattn** [comment]
`Go 1.4.2` is bootstrap base of go, do you mean?

**Comment by mattn** [comment]
Just fixed on my environment.
